#!/bin/sh

set -o errexit
set -o nounset

# Assume the environment variables MDBOOK_VERSION and MDBOOK_ADMONISH_VERSION are set

# Download a tar ball and then unpack it into a destination
# Arguments
#   1 - URL for the .tar.gz to download
#   2 - target directory to unpack into
download() {
  wget -q -O - "${1}" | tar -xz --directory "${2}"
}

download \
  https://github.com/rust-lang/mdBook/releases/download/v${MDBOOK_VERSION}/mdbook-v${MDBOOK_VERSION}-x86_64-unknown-linux-gnu.tar.gz \
  ~/.local/bin
download \
  https://github.com/tommilligan/mdbook-admonish/releases/download/v${MDBOOK_ADMONISH_VERSION}/mdbook-admonish-v${MDBOOK_ADMONISH_VERSION}-x86_64-unknown-linux-gnu.tar.gz \
  ~/.local/bin
