
title: Light Dark Matter eXperiment (LDMX)
email: '' 
description: >- # this means to ignore newlines until "baseurl:"
    The Light Dark Matter eXperiment aims to decisively test a variety of dark
    matter scenarios in the MeV - GeV mass range. 
baseurl: '' # the subpath of your site, e.g. /blog
url: 'http://localhost:4000' 
sass:
    sass_dir: _sass
include: 
    - _pages
    - _doxygen
    - _sphinx
