LDMX Software: Tools/src/AnalysisUtils.cxx File Reference
AnalysisUtils.cxx File Reference
Collection of utility functions useful for analysis.
#include "Tools/AnalysisUtils.h"
#include <string>
#include <tuple>
#include "Event/FindableTrackResult.h"
#include "Event/SimParticle.h"
#include "Exception/Exception.h"
#include "TVector3.h"
Namespaces
ldmx
All classes in the ldmx-sw project use this namespace.
Functions
std::tuple< int, const SimParticle * > ldmx::Analysis::getRecoil (const std::map< int, SimParticle > &particleMap)
const SimParticle * ldmx::Analysis::getPNGamma (const std::map< int, SimParticle > &particleMap)
const SimParticle * ldmx::Analysis::getRecoilPNGamma (const std::map< int, SimParticle > &particleMap)
TrackMaps ldmx::Analysis::getFindableTrackMaps (const std::vector< FindableTrackResult > &tracks)
Detailed Description
Collection of utility functions useful for analysis.
Author
Omar Moreno, SLAC National Accelerator Laboratory
Definition in file AnalysisUtils.cxx.
Function Documentation
getFindableTrackMaps()
TrackMaps ldmx::Analysis::getFindableTrackMaps (const std::vector< FindableTrackResult > & tracks)
Sort tracks depending on how finable they are.
Definition at line 94 of file AnalysisUtils.cxx.
{
             TrackMaps map;
             for (const FindableTrackResult &track : tracks ) {
                 if (track.is4sFindable() || track.is3s1aFindable() || track.is2s2aFindable()) {
                     map.findable[track.getParticleTrackID()] =  &track;
                 }
                 if (track.is2sFindable()) map.loose[track.getParticleTrackID()] = &track;
                 if (track.is2aFindable()) map.axial[track.getParticleTrackID()] = &track;
             }
             return map;
         }
References ldmx::Analysis::getFindableTrackMaps().
Referenced by ldmx::Analysis::getFindableTrackMaps().
getPNGamma()
const SimParticle * ldmx::Analysis::getPNGamma (const std::map< int, SimParticle > & particleMap)
Get a pointer to the sim particle associated with the photon that underwent a photo-nuclear reaction.
Returns the first particle in the map that underwent a PN interaction. If more than one particle undergoes a PN interaction, this will NOT notice.
Parameters
particleMap map of sim particles
Returns
pointer to sim particle labeled as PN Gamma photon (nullptr if not found)
Definition at line 37 of file AnalysisUtils.cxx.
{
             for ( const auto &sp : particleMap ) {
                if ( (sp.second.getPdgID() == 0 ) //particle is a photon
                     and (sp.second.getDaughters().size() > 0) //has offspring
                   ) {
                    std::vector<int> daughterTrackIDs = sp.second.getDaughters();
                    for ( const int &trackID : daughterTrackIDs ) {
                         if ( particleMap.count(trackID) > 0 and //daughter exists in particleMap
                              particleMap.at(trackID).getProcessType() == SimParticle::ProcessType::photonNuclear //daughter came from PN
                            ) { return &(sp.second); }
                    } //loop through daughter track IDs
                } //current particle is a photon and has offspring
             } //loop through particle map
             //no particles satisfy
             //  1) Is a photon
             //  2) Has a daughter with origin process PN
             return nullptr;
         }
References ldmx::SimParticle::getDaughters(), and ldmx::Analysis::getPNGamma().
Referenced by ldmx::Analysis::getPNGamma().
getRecoil()
std::tuple< int, const SimParticle * > ldmx::Analysis::getRecoil (const std::map< int, SimParticle > & particleMap)
Find and return the sim particle associated with the recoil electron.
Parameters
particleMap map of sim particles
Returns
pointer to sim particle labeled as recoil electron (nullptr if not found)
Definition at line 31 of file AnalysisUtils.cxx.
{
             // The recoil electron always has a track ID of 1.
             return {1, &(particleMap.at(1))};
         }
References ldmx::Analysis::getRecoil().
Referenced by ldmx::Analysis::getRecoil().
getRecoilPNGamma()
const SimParticle * ldmx::Analysis::getRecoilPNGamma (const std::map< int, SimParticle > & particleMap)
Get a pointer to the sim particle associated with the photon daughter of the recoil electron that underwent a photo-nuclear reaction.
Parameters
particleMap map of sim particles
Returns
pointer to sim particle (nullptr if not found)
Definition at line 63 of file AnalysisUtils.cxx.
{
             // Search for and rretrieve the recoil electron
             auto [trackID, recoilElectron] = Analysis::getRecoil(particleMap);
             // If the recoil electron was found, continue to search for the
             // PN gamma. If not, return null.
             if ( recoilElectron ) {
                auto daughterTrackIDs{recoilElectron->getDaughters()};
                auto pit = std::find_if(daughterTrackIDs.begin(), daughterTrackIDs.end(), [particleMap] (const int& id) {
                             // If the particle doesn't have any daughters, return false
                             if (particleMap.at(id).getDaughters().size() == 0) return false;
                             // If the particle has daughters that were a result
                             // of a photo-nuclear reaction, then tag it as the
                             // PN gamma.
                             return (particleMap.at(particleMap.at(id).getDaughters().front()).getProcessType()
                                     == SimParticle::ProcessType::photonNuclear);
                             });
                 // If a PN daughter was found, return it.
                 if (pit != daughterTrackIDs.end()) return &particleMap.at(*pit);
             }
             return nullptr;
         }
References ldmx::Analysis::getRecoilPNGamma().
Referenced by ldmx::Analysis::getRecoilPNGamma().