[book]
authors = ["tomeichlersmith"]
language = "en"
multilingual = false
src = "src"
title = "LDMX Software"

[build]
create-missing = false

[output.html]
mathjax-support = true
git-repository-url = "https://github.com/LDMX-Software/ldmx-software.github.io/tree/trunk/"
edit-url-template = "https://github.com/LDMX-Software/ldmx-software.github.io/edit/trunk/{path}"
additional-css = ["./mdbook-admonish.css"]

[output.html.redirect]
"/_doxygen/index.html" = "/cpp_refman.html"
"/_sphinx/index.html" = "/python_refman.html"
"/Dark-Brem-Signal-Process.html" = "/dark-brem/intro.html"
"/docs/Alternative-Photo-Nuclear-Models.html" = "/Alternative-Photo-Nuclear-Models.html"
"/Configuring-the-Simulation.html" = "/simulation/configuring.html"
"/Running-and-configuring-fire.html" = "/fire/intro.html"
"/fire-config-tips.html" = "/fire/config-tips.html"
"/Structure-of-Event-Processors.html" = "/fire/structure-of-event-processors.html"

[preprocessor]

[preprocessor.admonish]
command = "mdbook-admonish"
assets_version = "3.0.1" # do not edit: managed by `mdbook-admonish install`
