[book]
authors = ["tomeichlersmith"]
language = "en"
multilingual = false
src = "src"
title = "LDMX Software"

[build]
create-missing = false

[output.html]
mathjax-support = true
git-repository-url = "https://github.com/LDMX-Software/ldmx-software.github.io/tree/trunk/"
edit-url-template = "https://github.com/LDMX-Software/ldmx-software.github.io/edit/trunk/{path}"

