[book]
authors = ["tomeichlersmith"]
language = "en"
multilingual = false
src = "src"
title = "LDMX Software"

[build]
create-missing = false

[output.html]
mathjax-support = true
git-repository-url = "https://github.com/LDMX-Software/ldmx-software.github.io/tree/trunk/"
edit-url-template = "https://github.com/LDMX-Software/ldmx-software.github.io/edit/trunk/{path}"

[output.html.redirect]
"/_doxygen/index.html" = "/cpp_refman.html"
"/_sphinx/index.html" = "/python_refman.html"
"/Dark-Brem-Signal-Process.html" = "/dark-brem/intro.html"
