LDMX Software: ldmx::RecoilTrackerDQM Class Reference
ldmx::RecoilTrackerDQM Class Reference
Public Member Functions
RecoilTrackerDQM (const std::string &name, Process &process)
~RecoilTrackerDQM ()
void configure (Parameters &parameters) final override
void analyze (const Event &event)
void onProcessStart ()
Public Member Functions inherited from ldmx::Analyzer
Analyzer (const std::string &name, Process &process)
Public Member Functions inherited from ldmx::EventProcessor
EventProcessor (const std::string &name, Process &process)
virtual ~EventProcessor ()
virtual void onNewRun (const RunHeader &runHeader)
virtual void onFileOpen (EventFile &eventFile)
virtual void onFileClose (EventFile &eventFile)
virtual void onProcessEnd ()
TDirectory * getHistoDirectory ()
void setStorageHint (ldmx::StorageControlHint hint)
void setStorageHint (ldmx::StorageControlHint hint, const std::string &purposeString)
Private Attributes
HistogramPool * histograms_ {nullptr}
Additional Inherited Members
Static Public Member Functions inherited from ldmx::EventProcessor
static void declare (const std::string &classname, int classtype, EventProcessorMaker *)
Static Public Attributes inherited from ldmx::Analyzer
static const int CLASSTYPE {2}
Protected Member Functions inherited from ldmx::EventProcessor
void abortEvent ()
Protected Attributes inherited from ldmx::EventProcessor
Process & process_
Detailed Description
Definition at line 38 of file RecoilTrackerDQM.h.
Constructor & Destructor Documentation
RecoilTrackerDQM()
ldmx::RecoilTrackerDQM::RecoilTrackerDQM (const std::string & name, Process & process)
Constructor
Definition at line 11 of file RecoilTrackerDQM.cxx.
                                                                               :
         Analyzer(name, process) { }
~RecoilTrackerDQM()
ldmx::RecoilTrackerDQM::~RecoilTrackerDQM ()
Destructor
Definition at line 14 of file RecoilTrackerDQM.cxx.
 { }
Member Function Documentation
analyze()
void ldmx::RecoilTrackerDQM::analyze (const Event & event) virtual
Process the event and make histograms ro summaries.
Parameters
event The event to analyze.
Implements ldmx::Analyzer.
Definition at line 29 of file RecoilTrackerDQM.cxx.
{
         // If the collection of findable tracks doesn't exist, stop processing
         // the event.
         if (!event.exists("FindableTracks")) return;
         // Get the collection of simulated particles from the event
         const std::vector<FindableTrackResult> tracks
             = event.getCollection<FindableTrackResult>("FindableTracks");
         TrackMaps map = Analysis::getFindableTrackMaps(tracks);
         histograms_->get("track_count")->Fill(map.findable.size());
         histograms_->get("loose_track_count")->Fill(map.loose.size());
         histograms_->get("axial_track_count")->Fill(map.axial.size());
         // Get the collection of simulated particles from the event
         auto particleMap{event.getMap<int, SimParticle>("SimParticles")};
         // Search for the recoil electron
         auto [recoilTrackID, recoil] = Analysis::getRecoil(particleMap);
         auto it = map.findable.find(recoilTrackID);
         bool recoilIsFindable = ( it != map.findable.end() );
         // Fill the recoil vertex position histograms
         std::vector<double> recoilVertex = recoil->getVertex();
         histograms_->get("recoil_vx")->Fill(recoilVertex[0]);
         histograms_->get("recoil_vy")->Fill(recoilVertex[1]);
         histograms_->get("recoil_vz")->Fill(recoilVertex[2]);
         double p{-1}, pt{-1}, px{-9999}, py{-9999}, pz{-9999};
         const SimTrackerHit* spHit{nullptr};
         if (event.exists("TargetScoringPlaneHits")) {
             // Get the collection of simulated particles from the event
             const std::vector<SimTrackerHit> spHits = event.getCollection<SimTrackerHit>("TargetScoringPlaneHits");
             for (const SimTrackerHit &hit : spHits ) {
                 if ( (hit.getTrackID() == recoilTrackID) /*hit caused by recoil*/ and
                      (hit.getLayerID() == 2) /*hit on downstream side of target*/ and
                      (hit.getMomentum()[2] > 0) /*hit momentum leaving target*/
                    ) {
                     spHit = &hit;
                     break;
                 }
             }
             if ( spHit ) {
                 TVector3 recoilP(spHit->getMomentum().data());
                 p = recoilP.Mag();
                 pt = recoilP.Pt();
                 px = recoilP.Px();
                 py = recoilP.Py();
                 pz = recoilP.Pz();
             }
         }
         histograms_->get("tp")->Fill(p);
         histograms_->get("tpt")->Fill(pt);
         histograms_->get("tpx")->Fill(px);
         histograms_->get("tpy")->Fill(py);
         histograms_->get("tpz")->Fill(pz);
         bool passesTrackVeto{false};
         // Check if the TrackerVeto result exists
         if (event.exists("TrackerVeto")) {
             // Get the collection of trackerVeto results
             const TrackerVetoResult trackerVeto = event.getObject<TrackerVetoResult>("TrackerVeto");
             // Check if the event passes the tracker veto
             if (trackerVeto.passesVeto()) {
                 passesTrackVeto = true;
             }
         }
         if (passesTrackVeto) {
             histograms_->get("tp_track_veto")->Fill(p);
             histograms_->get("tpt_track_veto")->Fill(pt);
             histograms_->get("tpx_track_veto")->Fill(px);
             histograms_->get("tpy_track_veto")->Fill(py);
             histograms_->get("tpz_track_veto")->Fill(pz);
         }
     }
References ldmx::Event::exists(), ldmx::HistogramPool::get(), histograms_, and ldmx::TrackerVetoResult::passesVeto().
configure()
void ldmx::RecoilTrackerDQM::configure (Parameters & parameters) final override virtual
Configure the processor using the given user specified parameters.
Parameters
parameters Set of parameters used to configure this processor.
Reimplemented from ldmx::EventProcessor.
Definition at line 26 of file RecoilTrackerDQM.cxx.
{
     }
onProcessStart()
void ldmx::RecoilTrackerDQM::onProcessStart () virtual
Method executed before processing of events begins.
Reimplemented from ldmx::EventProcessor.
Definition at line 16 of file RecoilTrackerDQM.cxx.
{
         // Get an instance of the histogram pool
         histograms_ = HistogramPool::getInstance();
         // Open the file and move into the histogram directory
         getHistoDirectory();
     }
References ldmx::EventProcessor::getHistoDirectory(), and histograms_.
Member Data Documentation
histograms_
HistogramPool* ldmx::RecoilTrackerDQM::histograms_ {nullptr} private
Singleton used to access histograms.
Definition at line 70 of file RecoilTrackerDQM.h.
Referenced by analyze(), and onProcessStart().
The documentation for this class was generated from the following files:
DQM/include/DQM/RecoilTrackerDQM.h
DQM/src/RecoilTrackerDQM.cxx