LDMX Software: ldmx::Histogram1DBuilder< T > Class Template Reference
ldmx::Histogram1DBuilder< T > Class Template Reference
Public Member Functions
Histogram1DBuilder (const std::string &name, const int &bins, const double &xLow, const double &xHigh)
Histogram1DBuilder title (const std::string &title)
Histogram1DBuilder xLabel (const std::string &xLabel)
T * build ()
Static Private Attributes
static std::string name_ {""}
static std::string title_ {""}
static std::string xLabel_ {""}
static int bins_ {-1}
static double xLow_ {-1}
static double xHigh_ {-1}
Detailed Description
template<class T>
class ldmx::Histogram1DBuilder< T >
Definition at line 19 of file Histogram1DBuilder.h.
Constructor & Destructor Documentation
Histogram1DBuilder()
template<class T > ldmx::Histogram1DBuilder< T >::Histogram1DBuilder (const std::string & name, const int & bins, const double & xLow, const double & xHigh)
Constructor
Definition at line 36 of file Histogram1DBuilder.cxx.
{
         name_  = name;
         bins_  = bins;
         xLow_  = xLow;
         xHigh_ = xHigh;
         title_ = "";
         xLabel_ = "";
         gStyle->SetOptStat(0);
         gStyle->SetGridColor(17);
         gStyle->SetCanvasDefW(1100);
         gStyle->SetCanvasDefH(800);
         gStyle->SetCanvasColor(0);
         gStyle->SetCanvasBorderMode(0);
         gStyle->SetCanvasBorderSize(0);
         gStyle->SetPadBottomMargin(0.1);
         gStyle->SetPadTopMargin(0.01);
         gStyle->SetPadLeftMargin(0.1);
         gStyle->SetPadRightMargin(0.09);
         gStyle->SetPadGridX(1);
         gStyle->SetPadGridY(1);
         gStyle->SetPadTickX(1);
         gStyle->SetPadTickY(1);
         gStyle->SetFrameBorderMode(0);
         gStyle->SetTitleOffset(1.2, "yx");
         gStyle->SetOptLogy(1);
         gStyle->SetTitleFontSize(25);
     }
Member Function Documentation
build()
template<class T > T * ldmx::Histogram1DBuilder< T >::build
Returns
An instance of a histogram of type T (TH1F, etc.)
Definition at line 69 of file Histogram1DBuilder.cxx.
{
         T* hist = new T(name_.c_str(), name_.c_str(), bins_, xLow_, xHigh_);
         hist->SetTitle(title_.c_str());
         hist->GetXaxis()->SetTitle(xLabel_.c_str());
         hist->GetXaxis()->CenterTitle();
         hist->SetLineWidth(2);
         return hist;
     }
title()
template<class T > Histogram1DBuilder ldmx::Histogram1DBuilder< T >::title (const std::string & title) inline
Set the histogram title.
Definition at line 28 of file Histogram1DBuilder.h.
 { title_ = title; };
References ldmx::Histogram1DBuilder< T >::title(), and ldmx::Histogram1DBuilder< T >::title_.
Referenced by ldmx::Histogram1DBuilder< T >::title().
xLabel()
template<class T > Histogram1DBuilder ldmx::Histogram1DBuilder< T >::xLabel (const std::string & xLabel) inline
Set the x Label.
Definition at line 31 of file Histogram1DBuilder.h.
 { xLabel_ = xLabel; };
References ldmx::Histogram1DBuilder< T >::xLabel(), and ldmx::Histogram1DBuilder< T >::xLabel_.
Referenced by ldmx::Histogram1DBuilder< T >::xLabel().
Member Data Documentation
bins_
template<class T > int ldmx::Histogram1DBuilder< T >::bins_ {-1} static private
The number of bins.
Definition at line 48 of file Histogram1DBuilder.h.
name_
template<class T > std::string ldmx::Histogram1DBuilder< T >::name_ {""} static private
Name of the histogram.
Definition at line 39 of file Histogram1DBuilder.h.
title_
template<class T > std::string ldmx::Histogram1DBuilder< T >::title_ {""} static private
The histogram title.
Definition at line 42 of file Histogram1DBuilder.h.
Referenced by ldmx::Histogram1DBuilder< T >::title().
xHigh_
template<class T > double ldmx::Histogram1DBuilder< T >::xHigh_ {-1} static private
The high edge of the histogram.
Definition at line 54 of file Histogram1DBuilder.h.
xLabel_
template<class T > std::string ldmx::Histogram1DBuilder< T >::xLabel_ {""} static private
The title of the x-axis.
Definition at line 45 of file Histogram1DBuilder.h.
Referenced by ldmx::Histogram1DBuilder< T >::xLabel().
xLow_
template<class T > double ldmx::Histogram1DBuilder< T >::xLow_ {-1} static private
The low edge of the histogram.
Definition at line 51 of file Histogram1DBuilder.h.
The documentation for this class was generated from the following files:
DQM/include/DQM/Histogram1DBuilder.h
DQM/src/Histogram1DBuilder.cxx