LDMX Software: G4eDarkBremsstrahlung Class Reference
G4eDarkBremsstrahlung Class Reference
#include <G4eDarkBremsstrahlung.h>
Public Member Functions
G4eDarkBremsstrahlung (const G4String &name="eDBrem")
virtual ~G4eDarkBremsstrahlung ()
virtual G4bool IsApplicable (const G4ParticleDefinition &p)
virtual void PrintInfo ()
void SetMethod (G4eDarkBremsstrahlungModel::DarkBremMethod method)
void SetMadGraphDataFile (std::string file)
Protected Member Functions
virtual void InitialiseEnergyLossProcess (const G4ParticleDefinition *, const G4ParticleDefinition *)
Protected Attributes
G4bool isInitialised
Private Member Functions
G4eDarkBremsstrahlung & operator= (const G4eDarkBremsstrahlung &right)
G4eDarkBremsstrahlung (const G4eDarkBremsstrahlung &)
Private Attributes
G4eDarkBremsstrahlungModel::DarkBremMethod method_ {G4eDarkBremsstrahlungModel::DarkBremMethod::Undefined}
std::string madGraphFile_
Detailed Description
Class that represents the dark brem process. A electron or positron is allowed to brem a dark photon
Definition at line 25 of file G4eDarkBremsstrahlung.h.
Constructor & Destructor Documentation
G4eDarkBremsstrahlung() [1/2]
G4eDarkBremsstrahlung::G4eDarkBremsstrahlung (const G4String & name = "eDBrem")
Constructor
Sets this process up
Definition at line 18 of file G4eDarkBremsstrahlung.cxx.
                                                                 :
     G4VEnergyLossProcess(name),
     isInitialised(false) {
     G4int subtype = 63;
     SetProcessSubType(subtype);
     SetSecondaryParticle(G4APrime::APrime());
     SetIonisation(false);
 }
References G4APrime::APrime().
~G4eDarkBremsstrahlung()
virtual G4eDarkBremsstrahlung::~G4eDarkBremsstrahlung () inline virtual
Destructor
Definition at line 39 of file G4eDarkBremsstrahlung.h.
 { /*Nothing on purpose*/ }
G4eDarkBremsstrahlung() [2/2]
G4eDarkBremsstrahlung::G4eDarkBremsstrahlung (const G4eDarkBremsstrahlung &) private
remove ability to copy construct
Member Function Documentation
InitialiseEnergyLossProcess()
void G4eDarkBremsstrahlung::InitialiseEnergyLossProcess (const G4ParticleDefinition * , const G4ParticleDefinition *) protected virtual
Setup this process to get ready for simulation
Definition at line 46 of file G4eDarkBremsstrahlung.cxx.
{
     if(!isInitialised) {
         this->SetEmModel(new G4eDarkBremsstrahlungModel(),0); //adds model to vector stored in process
         //TODO: could make this depend on maximum beam energy passed through LHE files?
         G4double energyLimit = 4*GeV;
         this->EmModel(0)->SetLowEnergyLimit(MinKinEnergy());
         this->EmModel(0)->SetHighEnergyLimit(energyLimit);
         dynamic_cast<G4eDarkBremsstrahlungModel*>(this->EmModel(0))->SetMethod( method_ );
         dynamic_cast<G4eDarkBremsstrahlungModel*>(this->EmModel(0))->SetMadGraphDataFile( madGraphFile_ );
         G4VEmFluctuationModel* fm = 0;
         //adds model to ModelManager which handles initialisation procedures and cleaning up pointers
         this->AddEmModel(0, EmModel(0), fm);
         isInitialised = true;
     }
     G4double eth = 0*MeV;
     this->EmModel(0)->SetSecondaryThreshold(eth);
     this->EmModel(0)->SetLPMFlag(false);
 }
References isInitialised, madGraphFile_, method_, SetMadGraphDataFile(), and SetMethod().
IsApplicable()
G4bool G4eDarkBremsstrahlung::IsApplicable (const G4ParticleDefinition & p) virtual
Checks if the passed particle should be able to do this process
Returns
true if particle is electron
Definition at line 28 of file G4eDarkBremsstrahlung.cxx.
{
     return &p == G4Electron::Electron();
 }
operator=()
G4eDarkBremsstrahlung& G4eDarkBremsstrahlung::operator= (const G4eDarkBremsstrahlung & right) private
remove ability to assign this object
PrintInfo()
void G4eDarkBremsstrahlung::PrintInfo () virtual
Reports the file name and the method (in string form)
Definition at line 32 of file G4eDarkBremsstrahlung.cxx.
{
     std::string method = "UNDEFINED";
     if ( method_ == G4eDarkBremsstrahlungModel::DarkBremMethod::ForwardOnly ) {
         method = "forward_only";
     } else if ( method_ == G4eDarkBremsstrahlungModel::DarkBremMethod::CMScaling ) {
         method = "cm_scaling";
     }
     std::cout << "\tInterpretation Method: " + method << std::endl;
     std::cout << "\tMad Graph Data File  : " + madGraphFile_ << std::endl;
 }
References madGraphFile_, and method_.
SetMadGraphDataFile()
void G4eDarkBremsstrahlung::SetMadGraphDataFile (std::string file)
Pass LHE file of dark brem events to the model
Definition at line 77 of file G4eDarkBremsstrahlung.cxx.
{
     madGraphFile_ = file;
     return;
 }
References madGraphFile_.
Referenced by ldmx::APrimePhysics::ConstructProcess(), and InitialiseEnergyLossProcess().
SetMethod()
void G4eDarkBremsstrahlung::SetMethod (G4eDarkBremsstrahlungModel::DarkBremMethod method)
Pass the method for this process to the model
Definition at line 72 of file G4eDarkBremsstrahlung.cxx.
{
     method_ = method;
     return;
 }
References method_.
Referenced by ldmx::APrimePhysics::ConstructProcess(), and InitialiseEnergyLossProcess().
Member Data Documentation
isInitialised
G4bool G4eDarkBremsstrahlung::isInitialised protected
Has this process been setup yet?
Definition at line 66 of file G4eDarkBremsstrahlung.h.
Referenced by InitialiseEnergyLossProcess().
madGraphFile_
std::string G4eDarkBremsstrahlung::madGraphFile_ private
Mad Graph file passed to model
Definition at line 80 of file G4eDarkBremsstrahlung.h.
Referenced by InitialiseEnergyLossProcess(), PrintInfo(), and SetMadGraphDataFile().
method_
G4eDarkBremsstrahlungModel::DarkBremMethod G4eDarkBremsstrahlung::method_ {G4eDarkBremsstrahlungModel::DarkBremMethod::Undefined} private
Method that was passed to the model
Definition at line 77 of file G4eDarkBremsstrahlung.h.
Referenced by InitialiseEnergyLossProcess(), PrintInfo(), and SetMethod().
The documentation for this class was generated from the following files:
SimCore/include/SimCore/G4eDarkBremsstrahlung.h
SimCore/src/G4eDarkBremsstrahlung.cxx