LDMX Software: ldmx Namespace Reference
ldmx Namespace Reference
All classes in the ldmx-sw project use this namespace.
Classes
class AbortEventException
Specific exception used to abort an event.
class Analyzer
Base class for a module which does not produce a data product.
class APrimePhysics
Defines basic APrime physics.
class AuxInfoReader
Reads auxiliary information from GDML userinfo block.
class BatchSession
class CalorimeterHit
Represents a reconstructed hit in a calorimeter cell within the detector.
class CalorimeterSD
Basic calorimeter sensitive detector.
struct Class
Encapsualtes the information required to create a class of type className_.
class ClusterAlgoResult
Contains details about the clustering algorithm.
struct cmpStr
class ConfigurePython
Utility class which reads/executes a python script and creates a Process object based on the input.
class DarkBremFilter
class DarkBremXsecBiasingOperator
class DefaultDetectorID
Defines a default detector ID with encoded layer and subdetector values.
class DetectorConstruction
Implements the Geant4 detector construction.
class DetectorGeometry
Class to translated between detector location (section, layer, strip) and real space.
class DetectorHeader
Defines detector header information.
class DetectorID
Defines a 32-bit packed ID for uniquely identifying hits and detector components.
class DetectorIDStore
A global store for accessing DetectorID objects.
class DNNEcalVetoProcessor
Determines if event is vetoable using ECAL hit information w/ a deep neural network.
class DummyAnalyzer
A dummy Analyzer implementation that just prints some messages and makes a simple histogram of calorimeter energy.
class DummyProducer
Defines a dummy Producer implementation that adds some random data to the event.
class EcalCluster
Stores cluster information from the ECal.
class EcalClusterProducer
Simple algorithm that does clustering in the ECal.
class EcalDetectorID
Extension of DefaultDetectorID providing access to ECal cell number in a hex grid.
class EcalDigiCollection
Represents a collection of the ECal digi hits.
class EcalDigiProducer
Performs basic ECal digitization.
struct EcalDigiSample
One sample of an Ecal digi channel.
class EcalDigiVerifier
Generate histograms to check digi pipeline performance.
class EcalHexReadout
Implementation of ECal hexagonal cell readout.
class EcalHit
Stores reconstructed hit information from the ECAL.
class EcalHitIO
Provides hit readout for simulated ECal detector.
class EcalProcessFilter
class EcalRecProducer
Performs basic ECal reconstruction.
class EcalSD
ECal sensitive detector that uses an EcalHexReadout to create the hits.
class EcalSim2Rec
Performs basic ECal digitization.
class EcalVetoProcessor
Determines if event is vetoable using ECAL hit information.
class EcalVetoResult
class ElectroNuclearXsecBiasingOperator
class EveDetectorGeometry
Class that constructs the detector components for the event display.
class Event
Implements an event buffer system for storing event data.
class EventConstants
Provides access to static event constants used by the Event class.
class EventDisplay
class EventFile
Manages a file of events.
class EventHeader
Provides header information an event such as event number and timestamp.
class EventObjects
Drawing methods for event objects.
class EventProcessor
Base class for all event processing components.
class EventProcessorFactory
Singleton module factory that creates EventProcessor objects.
class EveShapeDrawer
Helper class for drawing common shapes.
class Exception
Standard base exception class with some useful output information.
class FindableTrackProcessor
class FindableTrackResult
class G4CalorimeterHit
Calorimeter hit which is used to create output SimCalorimeterHit objects.
class G4TrackerHit
Track hit which is used to create output SimTrackerHit collection.
class GammaPhysics
Adds extra gamma particle physics for simulation.
class GammaToMuPairXsecBiasingOperator
class GeneralParticleSource
Class that extends the functionality of G4GeneralParticleSource.
class HcalDigiProducer
Performs digitization of simulated HCal data.
class HCalDQM
class HcalHit
Stores reconstructed hit information from the HCAL.
class HcalID
Implements sensitive detector for HCal subdetector.
class HcalSD
class HcalVetoProcessor
class HcalVetoResult
struct HexPrism
Stores the necessary geometry details for a hexagonal prism.
class Histogram1DBuilder
struct HistogramInfo
Encapsulates the information required to create a histogram.
class HistogramPool
class IDField
Provides information about a field within a DetectorID.
class LHEEvent
LHE event with a list of particles and information from the header block.
class LHEParticle
Single particle record in an LHE event.
class LHEPrimaryGenerator
Generates a Geant4 event from an LHEEvent.
class LHEReader
Reads LHE event data into an LHEEvent object.
class LoggedSession
class MagneticFieldMap3D
A 3D B-field map defined as a grid of points with associated B-field values.
class MagneticFieldStore
Global store to access magnetic field objects.
class MultiParticleGunPrimaryGenerator
Generates a Geant4 event from particle gun, but can have many particles.
class MyClusterWeight
class MyProcessor
class NoiseGenerator
class NonFidBDTHelper
Runs the Boost Decision Tree (BDT) on NonFidEcalVetoResult objects using TPython.
class NonFidEcalVetoProcessor
Determines if event is vetoable using ECAL hit information.
class NonFidEcalVetoResult
class NtupleManager
Singleton class used to manage the creation and pooling of ntuples.
class ParallelWorld
class Parameters
class ParticleGun
Class that extends the functionality of G4ParticleGun.
class PhotoNuclearDQM
class PhotoNuclearXsecBiasingOperator
class PnWeightProcessor
class PnWeightResult
class PrimaryGenerator
Interface that defines a simulation primary generator.
class PrimaryGeneratorAction
Implementation of Geant4 primary generator action.
class PrimaryGeneratorManager
Class that manages the generators used to fire particles.
class Process
Class which represents the process under execution.
struct ProcessorClass
Represents the configuration of an EventProcessor in the job.
class Producer
Base class for a module which produces a data product.
class ProductTag
Defines the identity of a product and can be used for searches.
class RawHit
class RecoilMissesEcalSkimmer
class RecoilTrackerDQM
class RootCompleteReSim
class RootPersistencyManager
class RootSimFromEcalSP
class RunHeader
class RunManager
Extension of Geant4 run manager.
class ScoringPlaneSD
class SimCalorimeterHit
Stores simulated calorimeter hit information.
class SimParticle
class SimParticleBuilder
Builds output SimParticle collection from Trajectory container.
class SimTrackerHit
Represents a simulated tracker hit in the simulation.
class Simulator
Producer that runs Geant4 simulation inside of ldmx-app.
class SiStripHit
class StepPrinter
class StorageControl
Class which encapsulates storage control functionality, used by the Process class.
class TaggerVetoFilter
class TargetBremFilter
class TargetENProcessFilter
class TargetProcessFilter
Biases Geant4 to only process events where PN reaction occurred in the target.
class TemplatedClusterFinder
class TrackerHitKiller
class TrackerID
Extension of DefaultDetectorID providing access to module number for tracker IDs.
class TrackerSD
Basic sensitive detector for trackers.
class TrackerVetoProcessor
class TrackerVetoResult
class TrackMap
Defines a map of track ID to parent ID and Trajectory.
struct TrackMaps
class TrackProcessFilter
class Trajectory
Trajectory implementation for storing track info for persistence and visualization.
class TrajectoryContainer
Trajectory container extension that allows searching by track ID.
class TriggerProcessor
Provides a trigger decision for recon using a TriggerResult object.
class TriggerResult
Represents the trigger decision (pass/fail) for reconstruction.
class TrigScintDigiProducer
Performs digitization of simulated Trigger Scintillator data.
class TrigScintDQM
class TrigScintHit
class TrigScintHitDQM
class TrigScintID
class TrigScintSD
class UserAction
Interface that defines a user action.
class UserActionManager
class UserEventAction
Implementation of user event action hook.
class UserEventInformation
class UserPrimaryParticleInformation
Defines extra information attached to a Geant4 primary particle.
class UserRegionInformation
Defines extra information for a detector region.
class UserRunAction
Implementation of user run action hook.
class UserStackingAction
Class implementing a user stacking action.
class UserTrackInformation
class UserTrackingAction
Implementation of user tracking action.
class USteppingAction
Implements the Geant4 user stepping action.
class VisAttributesStore
Global store of G4VisAttributes created from GDML data.
class WorkingCluster
class XsecBiasingOperator
Typedefs
typedef std::pair< double, double > XYCoords
typedef std::variant< ClusterAlgoResult, EcalDigiCollection, EcalVetoResult, EventHeader, HcalVetoResult, NonFidEcalVetoResult, PnWeightResult, TrackerVetoResult, TriggerResult, TrigScintHit, std::vector< CalorimeterHit >, std::vector< EcalCluster >, std::vector< EcalHit >, std::vector< FindableTrackResult >, std::vector< HcalHit >, std::vector< RawHit >, std::vector< SimCalorimeterHit >, std::vector< SiStripHit >, std::vector< SimTrackerHit >, std::vector< TrigScintHit >, std::map< int, SimParticle > > EventBusPassenger
typedef std::vector< std::pair< double, double > > BoundingBox
Stores the minimum and maximum of each coordinate for a box.
typedef EventProcessor * EventProcessorMaker(const std::string &name, Process &process)
typedef std::unique_ptr< Process > ProcessHandle
typedef enum ldmx::enum_StorageControlHint StorageControlHint
typedef G4THitsCollection< G4CalorimeterHit > G4CalorimeterHitsCollection
typedef G4THitsCollection< G4TrackerHit > G4TrackerHitsCollection
typedef PrimaryGenerator * PrimaryGeneratorBuilder(const std::string &name, Parameters &parameters)
typedef UserAction * UserActionBuilder(const std::string &name, Parameters &parameters)
typedef std::variant< UserRunAction *, UserEventAction *, UserTrackingAction *, USteppingAction *, UserStackingAction * > action
typedef std::map< TYPE, action > actionMap
Enumerations
enum HcalSection {
BACK = 0, TOP = 1, BOTTOM = 2, LEFT = 4,
RIGHT = 3
}
enum TrigScintSection { UPSTREAM_TAGGER = 1, UPSTREAM_TARGET, DOWNSTREAM_TARGET, NUM_SECTIONS }
enum enum_StorageControlHint {
hint_Undefined =0, hint_NoOpinion, hint_shouldKeep =10, hint_mustKeep =11,
hint_shouldDrop =20, hint_mustDrop =21
}
enum TYPE {
RUN = 1, EVENT, TRACKING, STEPPING,
STACKING, NONE
}
Enum for each of the user action types.
Functions
static bool compEcalHits (const EcalHit &a, const EcalHit &b)
static bool compHcalHits (const HcalHit &a, const HcalHit &b)
static bool compScorePlaneHits (const SimTrackerHit &a, const SimTrackerHit &b)
static bool areScorePlaneHitsEqual (const SimTrackerHit &a, const SimTrackerHit &b)
static wchar_t * getWC (const char *cstr)
static bool isPyString (PyObject *pyObj)
static bool isPyInt (PyObject *pyObj)
static std::string getPyString (PyObject *pyObj)
static int getPyInt (PyObject *pyObj)
static std::string stringMember (PyObject *owner, const std::string &name)
static long intMember (PyObject *owner, const std::string &name)
static std::vector< std::string > stringListMember (PyObject *owner, const char *listname)
std::ostream & operator<< (std::ostream &stream, const LHEParticle &particle)
Variables
const std::vector< double > radius68_thetalt10_plt500 = {4.045666158618167, 4.086393662224346, 4.359141107602775, 4.666549994726691, 5.8569181911416015, 6.559716356124256, 8.686967529043072, 10.063482736354674, 13.053528344041274, 14.883496407943747, 18.246694748611368, 19.939799900443724, 22.984795944506224, 25.14745829663406, 28.329169392203216, 29.468032123356345, 34.03271241527079, 35.03747443690781, 38.50748727211848, 39.41576583301171, 42.63622296033334, 45.41123601592071, 48.618139095742876, 48.11801717451056, 53.220539860213655, 58.87753380915155, 66.31550881539764, 72.94685877928593, 85.95506228335348, 89.20607201266672, 93.34370253818409, 96.59471226749734, 100.7323427930147, 103.98335252232795}
const std::vector< double > radius68_thetalt10_pgt500 = {4.081926458777424, 4.099431732299409, 4.262428482867968, 4.362017581473145, 4.831341579961153, 4.998346041276382, 6.2633736512415705, 6.588371889265881, 8.359969947444522, 9.015085558044309, 11.262722588206483, 12.250305471269183, 15.00547660437276, 16.187264014640103, 19.573764900578503, 20.68072032434797, 24.13797140783321, 25.62942209291236, 29.027596514735617, 30.215039667389316, 33.929540248019585, 36.12911729771914, 39.184563500620946, 42.02062468386282, 46.972125628650204, 47.78214816041894, 55.88428562462974, 59.15520134927332, 63.31816666637158, 66.58908239101515, 70.75204770811342, 74.022963432757, 78.18592874985525, 81.45684447449884}
const std::vector< double > radius68_theta10to20 = {4.0251896715647115, 4.071661598616328, 4.357690094817289, 4.760224640141712, 6.002480766325418, 6.667318981016246, 8.652513285172342, 9.72379373302137, 12.479492693251478, 14.058548828317289, 17.544872909347912, 19.43616066939176, 23.594162859513734, 25.197329065282954, 29.55995803074302, 31.768946746958296, 35.79247330197688, 37.27810357669942, 41.657281051476545, 42.628141392692626, 47.94208483539388, 49.9289473559796, 54.604030254423975, 53.958762417361655, 53.03339560920388, 57.026277390001425, 62.10810455035879, 66.10098633115634, 71.1828134915137, 75.17569527231124, 80.25752243266861, 84.25040421346615, 89.33223137382352, 93.32511315462106}
const std::vector< double > radius68_thetagt20 = {4.0754238481177705, 4.193693485630508, 5.14209420056253, 6.114996249971468, 7.7376807326481645, 8.551663213602291, 11.129110612057813, 13.106293737495639, 17.186617323282082, 19.970887612094604, 25.04088272634407, 28.853696411302344, 34.72538105333071, 40.21218694947545, 46.07344239520299, 50.074953583805346, 62.944045771758645, 61.145621459396814, 69.86940198299047, 74.82378572939959, 89.4528387422834, 93.18228303096758, 92.51751129204555, 98.80228884380018, 111.17537347472128, 120.89712563907408, 133.27021026999518, 142.99196243434795, 155.36504706526904, 165.08679922962185, 177.45988386054293, 187.18163602489574, 199.55472065581682, 209.2764728201696}
G4Allocator< G4CalorimeterHit > G4CalorimeterHitAllocator
G4Allocator< G4TrackerHit > G4TrackerHitAllocator
G4Allocator< Trajectory > TrajectoryAllocator
Detailed Description
All classes in the ldmx-sw project use this namespace.
Typedef Documentation
BoundingBox
typedef std::vector< std::pair< double, double > > ldmx::BoundingBox
Stores the minimum and maximum of each coordinate for a box.
@type BoundingBox This has all of the information needed to define an axis-aligned rectangular prism.
Definition at line 33 of file DetectorGeometry.h.
EventBusPassenger
typedef std::variant< ClusterAlgoResult, EcalDigiCollection, EcalVetoResult, EventHeader, HcalVetoResult, NonFidEcalVetoResult, PnWeightResult, TrackerVetoResult, TriggerResult, TrigScintHit, std::vector < CalorimeterHit >, std::vector < EcalCluster >, std::vector < EcalHit >, std::vector < FindableTrackResult >, std::vector < HcalHit >, std::vector < RawHit >, std::vector < SimCalorimeterHit >, std::vector < SiStripHit >, std::vector < SimTrackerHit >, std::vector < TrigScintHit >, std::map< int , SimParticle > > ldmx::EventBusPassenger
@type EventBusPassenger Allows all event bus passenger objects to be handled under one name (without an inheritance tree).
Note
Any object that you want to be put into the event bus needs to be listed here as well as above.
There are two types of EventBusPassengers: 1) Those that exist inside of an STL collection (e.g. SimParticle or EcalHit). These must have Print and operator< (for sorting) methods defined. 2) Those that exist outside an STL collection (e.g. EcalVetoResult) These must have Print and Clear methods defined.
TODO: Figure out if there are a maximum number of types allowed.
TODO: Dynamically (pre-processor) set the EventBusPassenger object to be the objects being used in the run.
Definition at line 73 of file EventDef.h.
EventProcessorMaker
typedef EventProcessor* ldmx::EventProcessorMaker(const std::string &name, Process &process)
Typedef for EventProcessorFactory use.
Definition at line 39 of file EventProcessor.h.
G4CalorimeterHitsCollection
typedef G4THitsCollection<G4CalorimeterHit> ldmx::G4CalorimeterHitsCollection
Template instantiation of G4 hits collection class.
Definition at line 209 of file G4CalorimeterHit.h.
G4TrackerHitsCollection
typedef G4THitsCollection<G4TrackerHit> ldmx::G4TrackerHitsCollection
Template instantiation of G4 hits collection class.
Definition at line 320 of file G4TrackerHit.h.
ProcessHandle
typedef std::unique_ptr<Process> ldmx::ProcessHandle
A handle to the current process Used to pass a process from ConfigurePython to ldmx-app.
Definition at line 216 of file Process.h.
Enumeration Type Documentation
HcalSection
enum ldmx::HcalSection
Encodes the section of the HCal based on the 'section' field value.
Definition at line 18 of file HcalID.h.
                      {
         BACK = 0,
         TOP = 1,
         BOTTOM = 2,
         LEFT = 4,
         RIGHT = 3
     };
Function Documentation
getPyInt()
static int ldmx::getPyInt (PyObject * pyObj) static
Turn the input python int object into a C++ int.
Only a function to isolate the if-else compile-time macro.
Parameters
[in] python object assumed to be an int python object
Returns
the value stored in it
Definition at line 110 of file ConfigurePython.cxx.
{
         int retval(0);
 #if PY_MAJOR_VERSION < 3
         retval = PyInt_AsLong(pyObj);
 #else
         retval = PyLong_AsLong(pyObj);
 #endif
         return retval;
     }
Referenced by intMember().
getPyString()
static std::string ldmx::getPyString (PyObject * pyObj) static
Turn the input python string object into a C++ string.
Helpful to condense down the multi-line nature of the python3 code.
Parameters
[in] python object assumed to be a string python object
Returns
the value stored in it
Definition at line 90 of file ConfigurePython.cxx.
{
         std::string retval;
 #if PY_MAJOR_VERSION < 3
         retval = PyString_AsString(pyObj);
 #else
         PyObject* pyStr = PyUnicode_AsEncodedString(pyObj, "utf-8","Error ~");
         retval = PyBytes_AS_STRING(pyStr);
         Py_XDECREF(pyStr);
 #endif
         return retval;
     }
Referenced by ldmx::ConfigurePython::getParameters(), stringListMember(), and stringMember().
getWC()
static wchar_t* ldmx::getWC (const char * cstr) static
Converts a char string to a wide char string.
Note
Newly allocates the returned object, so make sure to cleanup.
Parameters
[in] cstr char string to translate
Returns
newly allocated wide char string
Definition at line 40 of file ConfigurePython.cxx.
{
         const size_t cSize = mbstowcs(NULL,cstr,0)+1;
         wchar_t* wc = new wchar_t[cSize];
         mbstowcs( wc , cstr , cSize );
         return wc;
     }
Referenced by ldmx::ConfigurePython::ConfigurePython().
intMember()
static long ldmx::intMember (PyObject * owner, const std::string & name) static
Get a integer member of the input owner.
Parameters
[in] owner python object to look for the integer member
[in] name name of integer member of python object
Returns
value of integer member
Definition at line 145 of file ConfigurePython.cxx.
{
         long retval(0);
         PyObject* temp = PyObject_GetAttrString(owner, name.c_str());
         if (temp != 0) {
             retval = getPyInt(temp);
             Py_DECREF(temp);
         }
         return retval;
     }
References getPyInt().
Referenced by ldmx::ConfigurePython::ConfigurePython().
isPyInt()
static bool ldmx::isPyInt (PyObject * pyObj) static
Check if the input python object is an integer
Simple enough, only a function to isolate the if-else compile-time macro.
Parameters
[in] python object
Returns
true if an integer python object
Definition at line 73 of file ConfigurePython.cxx.
{
 #if PY_MAJOR_VERSION < 3
         return PyInt_Check(pyObj);
 #else
         return PyLong_Check(pyObj);
 #endif
     }
Referenced by ldmx::ConfigurePython::getParameters().
isPyString()
static bool ldmx::isPyString (PyObject * pyObj) static
Check if the input python object is a string
Simple enough, only a function to isolate the if-else compile-time macro.
Parameters
[in] python object
Returns
true if a string python object
Definition at line 56 of file ConfigurePython.cxx.
{
 #if PY_MAJOR_VERSION < 3
         return PyString_Check(pyObj);
 #else
         return PyUnicode_Check(pyObj);
 #endif
     }
Referenced by ldmx::ConfigurePython::getParameters().
operator<<()
std::ostream& ldmx::operator<< (std::ostream & stream, const LHEParticle & particle)
Overloaded stream operator.
Parameters
stream The output stream.
particle The particle to print.
Definition at line 89 of file LHEParticle.cxx.
{
         particle.print(stream);
         return stream;
     }
References ldmx::LHEParticle::print().
stringListMember()
static std::vector<std::string> ldmx::stringListMember (PyObject * owner, const char * listname) static
Get a string list member of the input owner.
Exceptions
Exception if input name does not reference a python list object.
Parameters
[in] owner python object to look for the list member
[in] name name of list member of python object
Returns
vector of strings containing the entries in the python member list
Definition at line 164 of file ConfigurePython.cxx.
{
         auto pylist = PyObject_GetAttrString( owner , listname );
         if ( !PyList_Check(pylist) ) {
             EXCEPTION_RAISE(
                     "BadType",
                     "'" + std::string(listname) + "' is not a python list as expected."
                     );
         }
         std::vector<std::string> list;
         for ( Py_ssize_t i = 0; i < PyList_Size(pylist); i++ ) {
             PyObject *elem = PyList_GetItem(pylist , i );
             list.push_back( getPyString( elem ) );
             Py_DECREF( elem );
         }
         Py_DECREF(pylist);
         return std::move(list);
     }
References EXCEPTION_RAISE, and getPyString().
Referenced by ldmx::ConfigurePython::ConfigurePython().
stringMember()
static std::string ldmx::stringMember (PyObject * owner, const std::string & name) static
Get a string object member of the input owner. Otherwise, return the empty string.
Parameters
[in] owner python object to look for the string member
[in] name name of string member of python object
Returns
value of string member
Definition at line 128 of file ConfigurePython.cxx.
{
         std::string retval;
         PyObject* temp = PyObject_GetAttrString(owner, name.c_str());
         if (temp != 0) {
             retval = getPyString(temp);
             Py_DECREF(temp);
         }
         return retval;
     }
References getPyString().
Referenced by ldmx::ConfigurePython::ConfigurePython(), and ldmx::ConfigurePython::getParameters().
Variable Documentation
G4CalorimeterHitAllocator
G4Allocator< G4CalorimeterHit > ldmx::G4CalorimeterHitAllocator
Memory allocator for objects of this class.
Definition at line 11 of file G4CalorimeterHit.cxx.
Referenced by ldmx::G4CalorimeterHit::operator delete(), and ldmx::G4CalorimeterHit::operator new().
G4TrackerHitAllocator
G4Allocator< G4TrackerHit > ldmx::G4TrackerHitAllocator
Memory allocator for objects of this class.
Definition at line 11 of file G4TrackerHit.cxx.
Referenced by ldmx::G4TrackerHit::operator delete(), and ldmx::G4TrackerHit::operator new().
TrajectoryAllocator
G4Allocator< Trajectory > ldmx::TrajectoryAllocator
Custom memory allocator.
Definition at line 13 of file Trajectory.cxx.
Referenced by ldmx::Trajectory::operator delete(), and ldmx::Trajectory::operator new().