LDMX Software: ldmx::PnWeightResult Class Reference
ldmx::PnWeightResult Class Reference
Public Member Functions
PnWeightResult ()
~PnWeightResult ()
double getHardestNucleonKe () const
double getHardestNucleonTheta () const
double getHardestNucleonW () const
double getHighestWNucleonKe () const
double getHighestWNucleonTheta () const
double getHighestWNucleonW () const
double getWeight () const
std::vector< double > getInclusiveW ()
void addTheta (double theta)
void addW (double w)
void setHardestNucleonKe (const double hardestNucleonKe)
void setHardestNucleonTheta (const double hardestNucleonTheta)
void setHardestNucleonW (const double hardestNucleonW)
void setHighestWNucleonKe (const double highestWNucleonKe)
void setHighestWNucleonTheta (const double highestWNucleonTheta)
void setHighestWNucleonW (const double highestWNucleonW)
void setWeight (const double weight)
void Clear ()
void Print () const
Private Member Functions
ClassDef (PnWeightResult, 1)
Private Attributes
std::vector< double > theta_
std::vector< double > w_
double hardestNucleonKe_ {-9999}
double hardestNucleonTheta_ {-9999}
double hardestNucleonW_ {-9999}
double highestWNucleonKe_ {-9999}
double highestWNucleonTheta_ {-9999}
double highestWNucleonW_ {-9999}
double weight_ {1.0}
Detailed Description
Definition at line 29 of file PnWeightResult.h.
Constructor & Destructor Documentation
PnWeightResult()
ldmx::PnWeightResult::PnWeightResult ()
Constructor
~PnWeightResult()
ldmx::PnWeightResult::~PnWeightResult ()
Destructor
Member Function Documentation
addTheta()
void ldmx::PnWeightResult::addTheta (double theta) inline
Add theta to the collection of theta's.
Definition at line 64 of file PnWeightResult.h.
 { theta_.push_back(theta); }
References theta_.
Referenced by ldmx::PnWeightProcessor::produce().
addW()
void ldmx::PnWeightResult::addW (double w) inline
Add W to the inclusive collection of W's.
Definition at line 67 of file PnWeightResult.h.
 { w_.push_back(w); }
References w_.
Referenced by ldmx::PnWeightProcessor::produce().
Clear()
void ldmx::PnWeightResult::Clear ()
Reset the object.
getHardestNucleonKe()
double ldmx::PnWeightResult::getHardestNucleonKe () const inline
Get the kinetic energy of the hardest nucleon.
Definition at line 40 of file PnWeightResult.h.
 { return hardestNucleonKe_; }
References hardestNucleonKe_.
getHardestNucleonTheta()
double ldmx::PnWeightResult::getHardestNucleonTheta () const inline
Get the polar angle of the hardest nucleon.
Definition at line 43 of file PnWeightResult.h.
 { return hardestNucleonTheta_; }
References hardestNucleonTheta_.
getHardestNucleonW()
double ldmx::PnWeightResult::getHardestNucleonW () const inline
Get the W of the hardest nucleon.
Definition at line 46 of file PnWeightResult.h.
 { return hardestNucleonW_; }
References hardestNucleonW_.
getHighestWNucleonKe()
double ldmx::PnWeightResult::getHighestWNucleonKe () const inline
Get the kinetic energy of the hardest nucleon.
Definition at line 49 of file PnWeightResult.h.
 { return highestWNucleonKe_; }
References highestWNucleonKe_.
getHighestWNucleonTheta()
double ldmx::PnWeightResult::getHighestWNucleonTheta () const inline
Get the polar angle of the hardest nucleon.
Definition at line 52 of file PnWeightResult.h.
 { return highestWNucleonTheta_; }
References highestWNucleonTheta_.
getHighestWNucleonW()
double ldmx::PnWeightResult::getHighestWNucleonW () const inline
Get the W of the hardest nucleon.
Definition at line 55 of file PnWeightResult.h.
 { return highestWNucleonW_; }
References highestWNucleonW_.
getInclusiveW()
std::vector<double> ldmx::PnWeightResult::getInclusiveW () inline
Return the collection of inclusive W values for the event.
Definition at line 61 of file PnWeightResult.h.
 { return w_; }
References w_.
getWeight()
double ldmx::PnWeightResult::getWeight () const inline
Return the calcualted PN weight associated with this event.
Definition at line 58 of file PnWeightResult.h.
 { return weight_; }
References weight_.
Print()
void ldmx::PnWeightResult::Print () const
Print the object
setHardestNucleonKe()
void ldmx::PnWeightResult::setHardestNucleonKe (const double hardestNucleonKe) inline
Set the kinetic energy of the hardest nucleon.
Definition at line 70 of file PnWeightResult.h.
 { hardestNucleonKe_ = hardestNucleonKe; }
References hardestNucleonKe_.
Referenced by ldmx::PnWeightProcessor::produce().
setHardestNucleonTheta()
void ldmx::PnWeightResult::setHardestNucleonTheta (const double hardestNucleonTheta) inline
Set the polar angle of the hardest nucleon.
Definition at line 73 of file PnWeightResult.h.
 { hardestNucleonTheta_ = hardestNucleonTheta; }
References hardestNucleonTheta_.
Referenced by ldmx::PnWeightProcessor::produce().
setHardestNucleonW()
void ldmx::PnWeightResult::setHardestNucleonW (const double hardestNucleonW) inline
Set the W of the hardest nucleon.
Definition at line 76 of file PnWeightResult.h.
 { hardestNucleonW_ = hardestNucleonW; }
References hardestNucleonW_.
Referenced by ldmx::PnWeightProcessor::produce().
setHighestWNucleonKe()
void ldmx::PnWeightResult::setHighestWNucleonKe (const double highestWNucleonKe) inline
Set the kinetic energy of the hardest nucleon.
Definition at line 79 of file PnWeightResult.h.
 { highestWNucleonKe_ = highestWNucleonKe; }
References highestWNucleonKe_.
Referenced by ldmx::PnWeightProcessor::produce().
setHighestWNucleonTheta()
void ldmx::PnWeightResult::setHighestWNucleonTheta (const double highestWNucleonTheta) inline
Set the polar angle of the hardest nucleon.
Definition at line 82 of file PnWeightResult.h.
 { highestWNucleonTheta_ = highestWNucleonTheta; }
References highestWNucleonTheta_.
Referenced by ldmx::PnWeightProcessor::produce().
setHighestWNucleonW()
void ldmx::PnWeightResult::setHighestWNucleonW (const double highestWNucleonW) inline
Set the W of the hardest nucleon.
Definition at line 85 of file PnWeightResult.h.
 { highestWNucleonW_ = highestWNucleonW; }
References highestWNucleonW_.
Referenced by ldmx::PnWeightProcessor::produce().
setWeight()
void ldmx::PnWeightResult::setWeight (const double weight) inline
Set the PN weight associated with this event.
Definition at line 88 of file PnWeightResult.h.
 { weight_ = weight; }
References weight_.
Referenced by ldmx::PnWeightProcessor::produce().
Member Data Documentation
hardestNucleonKe_
double ldmx::PnWeightResult::hardestNucleonKe_ {-9999} private
Kinetic energy of the hardest nucleon.
Definition at line 105 of file PnWeightResult.h.
Referenced by getHardestNucleonKe(), and setHardestNucleonKe().
hardestNucleonTheta_
double ldmx::PnWeightResult::hardestNucleonTheta_ {-9999} private
Polar angle of the hardest nucleon.
Definition at line 108 of file PnWeightResult.h.
Referenced by getHardestNucleonTheta(), and setHardestNucleonTheta().
hardestNucleonW_
double ldmx::PnWeightResult::hardestNucleonW_ {-9999} private
W of the hardest nucleon.
Definition at line 111 of file PnWeightResult.h.
Referenced by getHardestNucleonW(), and setHardestNucleonW().
highestWNucleonKe_
double ldmx::PnWeightResult::highestWNucleonKe_ {-9999} private
Kinetic energy of the nucleon with the highest W.
Definition at line 114 of file PnWeightResult.h.
Referenced by getHighestWNucleonKe(), and setHighestWNucleonKe().
highestWNucleonTheta_
double ldmx::PnWeightResult::highestWNucleonTheta_ {-9999} private
Polar angle of the nucleon with the highest W.
Definition at line 117 of file PnWeightResult.h.
Referenced by getHighestWNucleonTheta(), and setHighestWNucleonTheta().
highestWNucleonW_
double ldmx::PnWeightResult::highestWNucleonW_ {-9999} private
W of the nucleon with the highest W.
Definition at line 120 of file PnWeightResult.h.
Referenced by getHighestWNucleonW(), and setHighestWNucleonW().
theta_
std::vector<double> ldmx::PnWeightResult::theta_ private
Theta of all nucleons.
Definition at line 99 of file PnWeightResult.h.
Referenced by addTheta().
w_
std::vector<double> ldmx::PnWeightResult::w_ private
W of all nucleons.
Definition at line 102 of file PnWeightResult.h.
Referenced by addW(), and getInclusiveW().
weight_
double ldmx::PnWeightResult::weight_ {1.0} private
Calculated PN weight
Definition at line 123 of file PnWeightResult.h.
Referenced by getWeight(), and setWeight().
The documentation for this class was generated from the following file:
Event/include/Event/PnWeightResult.h