LDMX Software: ldmx::test::TestAnalyzer Class Reference
ldmx::test::TestAnalyzer Class Reference
Public Member Functions
TestAnalyzer (const std::string &name, Process &p)
void onProcessStart () final override
void analyze (const Event &event) final override
Public Member Functions inherited from ldmx::Analyzer
Analyzer (const std::string &name, Process &process)
Public Member Functions inherited from ldmx::EventProcessor
EventProcessor (const std::string &name, Process &process)
virtual ~EventProcessor ()
virtual void configure (Parameters &parameters)
virtual void onNewRun (const RunHeader &runHeader)
virtual void onFileOpen (EventFile &eventFile)
virtual void onFileClose (EventFile &eventFile)
virtual void onProcessEnd ()
template<class T >
const T & getCondition (const std::string &condition_name)
TDirectory * getHistoDirectory ()
void setStorageHint (ldmx::StorageControlHint hint)
void setStorageHint (ldmx::StorageControlHint hint, const std::string &purposeString)
int getLogFrequency () const
int getRunNumber () const
std::string getName () const
void createHistograms (const std::vector< Parameters > &histos)
Private Attributes
TH1F * test_hist_
test histogram filled with event indices
Additional Inherited Members
Static Public Member Functions inherited from ldmx::EventProcessor
static void declare (const std::string &classname, int classtype, EventProcessorMaker *)
Static Public Attributes inherited from ldmx::Analyzer
static const int CLASSTYPE {2}
Protected Member Functions inherited from ldmx::EventProcessor
void abortEvent ()
Protected Attributes inherited from ldmx::EventProcessor
HistogramHelper histograms_
Interface class for making and filling histograms.
NtupleManager & ntuple_ {NtupleManager::getInstance()}
Manager for any ntuples.
logging::logger theLog_
The logger for this EventProcessor.
Detailed Description
Bare analyzer that looks for objects matching what the TestProducer put in.
Checks
the correct number and contents following the pattern produced by TestProducer.
Event::getCollection and Event::getObject don't throw errors.
Definition at line 102 of file FunctionalCoreTest.cxx.
Member Function Documentation
analyze()
void ldmx::test::TestAnalyzer::analyze (const Event & event) inline final override virtual
Process the event and make histograms or summaries
Parameters
event The Event to analyze
Implements ldmx::Analyzer.
Definition at line 117 of file FunctionalCoreTest.cxx.
{
             int i_event = event.getEventNumber();
             REQUIRE( i_event > 0 );
             std::vector<CalorimeterHit> caloHits;
             REQUIRE_NOTHROW(caloHits = event.getCollection<CalorimeterHit>( "TestCollection" ));
             CHECK( caloHits.size() == i_event );
             for ( unsigned int i = 0; i < caloHits.size(); i++ ) {
                 CHECK( caloHits.at(i).getID() == i_event*10 + i );
                 test_hist_->Fill( caloHits.at(i).getID() );
             }
             HcalVetoResult vetoRes;
             REQUIRE_NOTHROW(vetoRes = event.getObject<HcalVetoResult>( "TestObject" ));
             auto maxPEHit{vetoRes.getMaxPEHit()};
             CHECK( maxPEHit.getID()     == i_event );
             CHECK( vetoRes.passesVeto() == (i_event%2==0) );
             return;
         }
References ldmx::HcalVetoResult::getMaxPEHit(), ldmx::HcalVetoResult::passesVeto(), and test_hist_.
onProcessStart()
void ldmx::test::TestAnalyzer::onProcessStart () inline final override virtual
Callback for the EventProcessor to take any necessary action when the processing of events starts, such as creating histograms.
Reimplemented from ldmx::EventProcessor.
Definition at line 109 of file FunctionalCoreTest.cxx.
{
             REQUIRE_NOTHROW(getHistoDirectory());
             test_hist_ = new TH1F(
                     "test_hist_" , "Test Histogram",
                     101, -50, 50 );
             test_hist_->SetCanExtend(TH1::kAllAxes);
         }
References ldmx::EventProcessor::getHistoDirectory(), and test_hist_.
The documentation for this class was generated from the following file:
Framework/test/FunctionalCoreTest.cxx