LDMX Software: ldmx::UserTrackInformation Class Reference
ldmx::UserTrackInformation Class Reference
#include <UserTrackInformation.h>
Public Member Functions
UserTrackInformation ()
Constructor.
~UserTrackInformation ()
Destructor.
void Print () const final override
Print the information associated with the track.
bool getSaveFlag ()
void setSaveFlag (bool saveFlag)
bool isBremCandidate ()
void tagBremCandidate (bool isBremCandidate=true)
const G4ThreeVector & getInitialMomentum ()
void setInitialMomentum (const G4ThreeVector &p)
void setVertexVolume (const std::string vertexVolume)
std::string getVertexVolume () const
Private Attributes
bool saveFlag_ {false}
Flag for saving the track as a Trajectory.
bool isBremCandidate_ {false}
Flag indicating whether this track is a brem candidate.
std::string vertexVolume_ {""}
Volume the track was created in.
G4ThreeVector initialMomentum_
The initial momentum of the track.
Detailed Description
Provides user defined information to associate with a Geant4 track.
Definition at line 12 of file UserTrackInformation.h.
Member Function Documentation
getInitialMomentum()
const G4ThreeVector& ldmx::UserTrackInformation::getInitialMomentum () inline
Get the initial momentum 3-vector of the track [MeV].
Returns
The initial momentum of the track.
Definition at line 63 of file UserTrackInformation.h.
{
                 return initialMomentum_;
             }
References initialMomentum_.
getSaveFlag()
bool ldmx::UserTrackInformation::getSaveFlag () inline
Get the flag which indicates whether this track should be saved as a Trajectory.
Returns
The save flag.
Definition at line 31 of file UserTrackInformation.h.
 { return saveFlag_; }
References saveFlag_.
Referenced by ldmx::UserTrackingAction::PostUserTrackingAction().
isBremCandidate()
bool ldmx::UserTrackInformation::isBremCandidate () inline
Check whether this track is a brem candidate.
Returns
True if this track is a brem candidate, false otherwise.
Definition at line 46 of file UserTrackInformation.h.
 { return isBremCandidate_; }
References isBremCandidate_.
Referenced by tagBremCandidate().
setInitialMomentum()
void ldmx::UserTrackInformation::setInitialMomentum (const G4ThreeVector & p) inline
Set the initial momentum of the associated track.
Parameters
[in] p The initial momentum of the track.
Definition at line 72 of file UserTrackInformation.h.
{
                 initialMomentum_.set(p.x(), p.y(), p.z());
             }
References initialMomentum_.
Referenced by ldmx::UserTrackingAction::processTrack().
setSaveFlag()
void ldmx::UserTrackInformation::setSaveFlag (bool saveFlag) inline
Set the save flag so the associated track will be persisted as a Trajectory.
Parameters
[in] saveFlag True to save the associated track.
Definition at line 39 of file UserTrackInformation.h.
 { saveFlag_ = saveFlag; }
References saveFlag_.
Referenced by ldmx::TrackProcessFilter::PostUserTrackingAction().
tagBremCandidate()
void ldmx::UserTrackInformation::tagBremCandidate (bool isBremCandidate = true) inline
Tag this flag as a brem candidate by the biasing filters.
Parameters
[in] isBremCandidate flag indicating whether this track is a candidate or not.
Definition at line 54 of file UserTrackInformation.h.
{
                 isBremCandidate_ = isBremCandidate;
             }
References isBremCandidate(), and isBremCandidate_.
Referenced by ldmx::TargetBremFilter::stepping().
The documentation for this class was generated from the following files:
SimCore/include/SimCore/UserTrackInformation.h
SimCore/src/UserTrackInformation.cxx