LDMX Software: ldmx::MagneticFieldStore Class Reference
ldmx::MagneticFieldStore Class Reference
Global store to access magnetic field objects.
#include <MagneticFieldStore.h>
Public Types
typedef std::map< std::string, G4MagneticField * > MagFieldMap
Public Member Functions
~MagneticFieldStore ()
G4MagneticField * getMagneticField (const std::string &name)
void addMagneticField (const std::string &name, G4MagneticField *magField)
Static Public Member Functions
static MagneticFieldStore * getInstance ()
Private Attributes
MagFieldMap magFields_
Detailed Description
Global store to access magnetic field objects.
Definition at line 19 of file MagneticFieldStore.h.
Member Typedef Documentation
MagFieldMap
typedef std::map<std::string, G4MagneticField*> ldmx::MagneticFieldStore::MagFieldMap
Map of names to magnetic fields.
Definition at line 26 of file MagneticFieldStore.h.
Constructor & Destructor Documentation
~MagneticFieldStore()
ldmx::MagneticFieldStore::~MagneticFieldStore () inline
Destructor
Cleans up all stored G4MagneticFields
Definition at line 42 of file MagneticFieldStore.h.
{
                 for ( auto &nameField : magFields_ ) {
                     delete nameField.second;
                 }
                 magFields_.clear();
             }
References magFields_.
Member Function Documentation
addMagneticField()
void ldmx::MagneticFieldStore::addMagneticField (const std::string & name, G4MagneticField * magField) inline
Add a magnetic field by name.
Parameters
name The name of the magnetic field.
magField The magnetic field definition.
Definition at line 63 of file MagneticFieldStore.h.
{
                 magFields_[name] = magField;
             }
References magFields_.
Referenced by ldmx::AuxInfoReader::createMagneticField().
getInstance()
static MagneticFieldStore* ldmx::MagneticFieldStore::getInstance () inline static
Get the global instance of the magnetic field store.
Returns
The magnetic field store.
Definition at line 32 of file MagneticFieldStore.h.
{
                 static MagneticFieldStore INSTANCE;
                 return &INSTANCE;
             }
Referenced by ldmx::AuxInfoReader::assignAuxInfoToVolumes(), and ldmx::AuxInfoReader::createMagneticField().
getMagneticField()
G4MagneticField* ldmx::MagneticFieldStore::getMagneticField (const std::string & name) inline
Get a magnetic field by name.
Parameters
name The name of the magnetic field.
Definition at line 54 of file MagneticFieldStore.h.
{
                 return magFields_.at(name);
             }
References magFields_.
Referenced by ldmx::AuxInfoReader::assignAuxInfoToVolumes().
Member Data Documentation
magFields_
MagFieldMap ldmx::MagneticFieldStore::magFields_ private
Map of names to magnetic fields.
Definition at line 72 of file MagneticFieldStore.h.
Referenced by addMagneticField(), getMagneticField(), and ~MagneticFieldStore().
The documentation for this class was generated from the following file:
SimApplication/include/SimApplication/MagneticFieldStore.h