LDMX Software: Tools/include/Tools/AnalysisUtils.h File Reference
AnalysisUtils.h File Reference
Collection of utility functions useful for analysis.
#include <cmath>
#include <vector>
#include <map>
#include <unordered_map>
Classes
struct ldmx::TrackMaps
Namespaces
ldmx
All classes in the ldmx-sw project use this namespace.
Functions
std::tuple< int, const SimParticle * > ldmx::Analysis::getRecoil (const std::map< int, SimParticle > &particleMap)
const SimParticle * ldmx::Analysis::getPNGamma (const std::map< int, SimParticle > &particleMap, const SimParticle *recoil, const float &energyThreshold)
TrackMaps ldmx::Analysis::getFindableTrackMaps (const std::vector< FindableTrackResult > &tracks)
Detailed Description
Collection of utility functions useful for analysis.
Author
Omar Moreno, SLAC National Accelerator Laboratory
Definition in file AnalysisUtils.h.
Function Documentation
getFindableTrackMaps()
TrackMaps ldmx::Analysis::getFindableTrackMaps (const std::vector< FindableTrackResult > & tracks)
Sort tracks depending on how finable they are.
Definition at line 66 of file AnalysisUtils.cxx.
{
             TrackMaps map;
             for (const FindableTrackResult &track : tracks ) {
                 if (track.is4sFindable() || track.is3s1aFindable() || track.is2s2aFindable()) {
                     map.findable[track.getParticleTrackID()] =  &track;
                 }
                 if (track.is2sFindable()) map.loose[track.getParticleTrackID()] = &track;
                 if (track.is2aFindable()) map.axial[track.getParticleTrackID()] = &track;
             }
             return map;
         }
References ldmx::Analysis::getFindableTrackMaps().
Referenced by ldmx::Analysis::getFindableTrackMaps().
getPNGamma()
const SimParticle * ldmx::Analysis::getPNGamma (const std::map< int, SimParticle > & particleMap, const SimParticle * recoil, const float & energyThreshold)
Get a pointer to the sim particle associated with the photon that underwent a photo-nuclear reaction.
Returns the first particle in the map that underwent a PN interaction and has an energy above the threshold. If more than one particle satisfied this condition, this will NOT notice.
Parameters
[in] particleMap Map of sim particles
[in] recoil The recoil electron
[in] energyThreshold The energy that the photon energy must be greater than.
Returns
[out] Pointer to sim particle labeled as PN Gamma photon (nullptr if not found)
Definition at line 37 of file AnalysisUtils.cxx.
{
             // Get all of the daughter track IDs
             auto daughterTrackIDs{recoil->getDaughters()};
             auto pit = std::find_if(daughterTrackIDs.begin(), daughterTrackIDs.end(),
                     [energyThreshold, particleMap] (const int& id) {
                 // Get the SimParticle from the map
                 auto daughter{particleMap.at(id)};
                 // If the particle doesn't have any daughters, return false
                 if (daughter.getDaughters().size() == 0) return false;
                 // If the particle has daughters that were a result of a
                 // photo-nuclear reaction, and its energy is above threshold,
                 // then tag it as the PN gamma.
                 return ((particleMap.at(daughter.getDaughters().front()).getProcessType()
                             == SimParticle::ProcessType::photonNuclear)
                         && (daughter.getEnergy() >= energyThreshold));
             });
             // If a PN daughter was found, return it.
             if (pit != daughterTrackIDs.end()) return &particleMap.at(*pit);
             return nullptr;
         }
References ldmx::SimParticle::getDaughters(), and ldmx::Analysis::getPNGamma().
Referenced by ldmx::Analysis::getPNGamma().
getRecoil()
std::tuple< int, const SimParticle * > ldmx::Analysis::getRecoil (const std::map< int, SimParticle > & particleMap)
Find and return the sim particle associated with the recoil electron.
Parameters
[in] particleMap map of sim particles
Returns
[out] Pointer to sim particle labeled as recoil electron (nullptr if not found)
Definition at line 31 of file AnalysisUtils.cxx.
{
             // The recoil electron always has a track ID of 1.
             return {1, &(particleMap.at(1))};
         }
References ldmx::Analysis::getRecoil().
Referenced by ldmx::Analysis::getRecoil().