LDMX Software: SimCore/src/SimCore/APrimePhysics.cxx File Reference
APrimePhysics.cxx File Reference
Class which defines basic APrime physics.
#include "SimCore/APrimePhysics.h"
#include "G4DarkBreM/G4APrime.h"
#include "G4DarkBreM/G4DarkBreMModel.h"
#include "SimCore/UserEventInformation.h"
#include "G4Electron.hh"
#include "G4EventManager.hh"
#include "G4ProcessManager.hh"
Functions
static void simcore::store_element_z (const G4Element &element)
Detailed Description
Class which defines basic APrime physics.
Author
Michael Revering, University of Minnesota
Tom Eichlersmith, University of Minnesota
Definition in file APrimePhysics.cxx.
Function Documentation
store_element_z()
static void simcore::store_element_z (const G4Element & element) static
Store the atomic Z for the element in which the dark brem occurred.
This function is registered with G4DarkBremsstrahlung and will be called with the element that the dark brem will occurr off of. We store the element Z in UserEventInformation for later serialization into the EventHeader
Parameters
[in] element G4Element off-which the dark brem occurred
Definition at line 33 of file APrimePhysics.cxx.
{
  static_cast<UserEventInformation*>(
      G4EventManager::GetEventManager()->GetUserInformation())
      ->setDarkBremMaterialZ(element.GetZ());
}
References simcore::store_element_z().
Referenced by simcore::APrimePhysics::ConstructProcess(), and simcore::store_element_z().