LDMX Software: ldmx::ConditionsObjectProvider Class Reference
ldmx::ConditionsObjectProvider Class Reference abstract
Base class for all providers of conditions objects.
#include <ConditionsObjectProvider.h>
Public Member Functions
ConditionsObjectProvider (const std::string &objname, const std::string &tagname, const Parameters &parameters, Process &process)
virtual ~ConditionsObjectProvider ()
virtual std::pair< const ConditionsObject *, ConditionsIOV > getCondition (const EventHeader &context)=0
virtual void releaseConditionsObject (const ConditionsObject *co)
virtual void onProcessStart ()
virtual void onProcessEnd ()
const std::string & getConditionObjectName () const
const std::string & getTagName () const
Static Public Member Functions
static void declare (const std::string &classname, ConditionsObjectProviderMaker *)
Static Public Attributes
static const int CLASSTYPE {10}
Protected Member Functions
std::pair< const ConditionsObject *, ConditionsIOV > requestParentCondition (const std::string &name, const EventHeader &context)
Protected Attributes
logging::logger theLog_
The logger for this ConditionsObjectProvider.
Private Attributes
Process & process_
std::string objectName_
std::string tagname_
Detailed Description
Base class for all providers of conditions objects.
be configured to load conditions objects from CSV files.
Configuration via Python uses the following parameters: "dataType", "columns", "entries" "DataType may be "int" or "double".
The "columns" parameter is the list of names of data columns to be read out.
"entries" is an array of parameter sets. Each entry must contain a "URL" The entry may contain "firstRun", "lastRun", "runType", and "values". If "firstRun" is not provided, -1 is assumed. If "lastRun" is not provided, -1 is assumed. The parameter "runType" could have the value "data", "MC", or "any". If "runType" is not provided, "any" is assumed. The parameter "values" is only used when the URL is "python:". In this case, the value for each column will be taken from the values array and the configuration is expected to be independend of id.
In any URL, envrironment variables in the format ${VARNAME} will be expanded. Also, the variable ${LDMX_CONDITION_TAG} will be replaced with the tagname provided in the constructor.
Definition at line 42 of file ConditionsObjectProvider.h.
Constructor & Destructor Documentation
ConditionsObjectProvider()
ldmx::ConditionsObjectProvider::ConditionsObjectProvider (const std::string & objname, const std::string & tagname, const Parameters & parameters, Process & process)
Class constructor.
Parameters
name Name for this instance of the class.
tagName The tag for the database entry (should not include whitespace)
process The Process class associated with ConditionsObjectProvider, provided by the framework.
Note
The name provided to this function should not be the class name, but rather a logical label for this instance of the class, as more than one copy of a given class can be loaded into a Process with different parameters. Names should not include whitespace or special characters.
Definition at line 9 of file ConditionsObjectProvider.cxx.
                                                                                                                                                  :
     process_{process}, objectName_ {objname}, tagname_{tagname}, theLog_{logging::makeLogger(objname)} { }
~ConditionsObjectProvider()
virtual ldmx::ConditionsObjectProvider::~ConditionsObjectProvider () inline virtual
Class destructor.
Definition at line 66 of file ConditionsObjectProvider.h.
 {;}
Member Function Documentation
declare()
void ldmx::ConditionsObjectProvider::declare (const std::string & classname, ConditionsObjectProviderMaker * maker) static
Internal function which is part of the PluginFactory machinery.
Parameters
classname The class name of the processor.
Definition at line 20 of file ConditionsObjectProvider.cxx.
{
   PluginFactory::getInstance().registerConditionsObjectProvider(classname, CLASSTYPE, maker);
 }
References CLASSTYPE, ldmx::PluginFactory::getInstance(), and ldmx::PluginFactory::registerConditionsObjectProvider().
getCondition()
virtual std::pair<const ConditionsObject*,ConditionsIOV> ldmx::ConditionsObjectProvider::getCondition (const EventHeader & context) pure virtual
Pure virtual getCondition function. Must be implemented by any Conditions providers.
Implemented in ldmx::SimpleCSVTableProvider.
getConditionObjectName()
const std::string& ldmx::ConditionsObjectProvider::getConditionObjectName () const inline
Get the list of conditions objects available from this provider.
Definition at line 100 of file ConditionsObjectProvider.h.
 { return objectName_; }
References objectName_.
Referenced by ldmx::Conditions::createConditionsObjectProvider().
getTagName()
const std::string& ldmx::ConditionsObjectProvider::getTagName () const inline
Access the tag name
Definition at line 111 of file ConditionsObjectProvider.h.
 { return tagname_; }
References tagname_.
onProcessEnd()
virtual void ldmx::ConditionsObjectProvider::onProcessEnd () inline virtual
Callback for the ConditionsObjectProvider to take any necessary action when the processing of events finishes, such as closing database connections.
Definition at line 94 of file ConditionsObjectProvider.h.
{
   }
onProcessStart()
virtual void ldmx::ConditionsObjectProvider::onProcessStart () inline virtual
Callback for the ConditionsObjectProvider to take any necessary action when the processing of events starts.
Definition at line 86 of file ConditionsObjectProvider.h.
{
   }
releaseConditionsObject()
virtual void ldmx::ConditionsObjectProvider::releaseConditionsObject (const ConditionsObject * co) inline virtual
Called by conditions system when done with a conditions object, appropriate point for cleanup.
Note
Default behavior is to delete the object!
Definition at line 78 of file ConditionsObjectProvider.h.
{
     delete co;
   }
requestParentCondition()
std::pair< const ConditionsObject *, ConditionsIOV > ldmx::ConditionsObjectProvider::requestParentCondition (const std::string & name, const EventHeader & context) protected
Request another condition needed to construct this condition
Definition at line 13 of file ConditionsObjectProvider.cxx.
{
   const ConditionsObject* obj=process_.getConditions().getConditionPtr(name);
   ConditionsIOV iov=process_.getConditions().getConditionIOV(name);
   return std::make_pair(obj,iov);
 }
References ldmx::Conditions::getConditionIOV(), ldmx::Conditions::getConditionPtr(), ldmx::Process::getConditions(), and process_.
Member Data Documentation
CLASSTYPE
const int ldmx::ConditionsObjectProvider::CLASSTYPE {10} static
Constant used to types by the PluginFactory
Definition at line 47 of file ConditionsObjectProvider.h.
Referenced by declare().
objectName_
std::string ldmx::ConditionsObjectProvider::objectName_ private
The name of the object provided by this provider.
Definition at line 127 of file ConditionsObjectProvider.h.
Referenced by getConditionObjectName().
process_
Process& ldmx::ConditionsObjectProvider::process_ private
Handle to the Process.
Definition at line 124 of file ConditionsObjectProvider.h.
Referenced by requestParentCondition().
tagname_
std::string ldmx::ConditionsObjectProvider::tagname_ private
The tag name for the ConditionsObjectProvider.
Definition at line 130 of file ConditionsObjectProvider.h.
Referenced by getTagName().
The documentation for this class was generated from the following files:
Framework/include/Framework/ConditionsObjectProvider.h
Framework/src/ConditionsObjectProvider.cxx