LDMX Software: ldmx::HistogramPool Class Reference
ldmx::HistogramPool Class Reference
Public Member Functions
template<typename T >
void create (const std::string &name, const std::string &xLabel, const int &bins, const int &xmin, const int &xmax)
template<typename T >
void create (const std::string &name, const std::string &xLabel, const int &xbins, const int &xmin, const int &xmax, const std::string &yLabel, const int &ybins, const int &ymin, const int &ymax)
TH1 * get (const std::string &name)
Static Public Member Functions
static HistogramPool * getInstance ()
Private Member Functions
HistogramPool ()
Private Attributes
std::unordered_map< std::string, TH1 * > histograms_
Static Private Attributes
static HistogramPool * instance = nullptr
Detailed Description
Definition at line 22 of file HistogramPool.h.
Constructor & Destructor Documentation
HistogramPool()
ldmx::HistogramPool::HistogramPool () private
Private constructor to prevent instantiation
Definition at line 25 of file HistogramPool.cxx.
{
         gStyle->SetOptStat(0);
         gStyle->SetGridColor(17);
         gStyle->SetFrameBorderMode(0);
         gStyle->SetTitleOffset(1.2, "yx");
         gStyle->SetTitleFontSize(25);
         gStyle->SetPadBottomMargin(0.1);
         gStyle->SetPadTopMargin(0.01);
         gStyle->SetPadLeftMargin(0.1);
         gStyle->SetPadRightMargin(0.09);
         gStyle->SetPadGridX(1);
         gStyle->SetPadGridY(1);
         gStyle->SetPadTickX(1);
         gStyle->SetPadTickY(1);
         gStyle->SetHistLineWidth(2);
     }
Member Function Documentation
create() [1/2]
template<typename T > void ldmx::HistogramPool::create (const std::string & name, const std::string & xLabel, const int & bins, const int & xmin, const int & xmax) inline
Create a ROOT 1D histogram of type T and pool it for later use.
Parameters
name Name of the histogram. This will also be used as a title.
xLabel Title of the x axis.
bins Total number of histogram bins.
xmin The lower histogram limit.
xmax The upper histogram limit.
Definition at line 50 of file HistogramPool.h.
{
                 // Create a histogram of type T
                 T* hist = new T(name.c_str(), name.c_str(), bins, xmin, xmax);
                 // Set the title
                 hist->SetTitle("");
                 // Set the x-axis label
                 hist->GetXaxis()->SetTitle(xLabel.c_str());
                 hist->GetXaxis()->CenterTitle();
                 // Insert it into the pool of histograms for later use
                 histograms_[name] = hist;
             }
References histograms_.
Referenced by ldmx::ConfigurePython::makeProcess(), ldmx::PhotoNuclearDQM::onProcessStart(), ldmx::TrigScintHitDQM::onProcessStart(), ldmx::HCalDQM::onProcessStart(), and ldmx::TrigScintDQM::onProcessStart().
create() [2/2]
template<typename T > void ldmx::HistogramPool::create (const std::string & name, const std::string & xLabel, const int & xbins, const int & xmin, const int & xmax, const std::string & yLabel, const int & ybins, const int & ymin, const int & ymax) inline
Create a ROOT 2D histogram of type T and pool it for later use.
Parameters
name Name of the histogram. This will also be used as a title.
xLabel Title of the x axis.
xbins Total number of histogram bins in x.
xmin The lower histogram limit in x.
xmax The upper histogram limit in x.
yLabel Title of the x axis.
ybins Total number of histogram bins in y.
ymin The lower histogram limit in y.
ymax The upper histogram limit in y.
Definition at line 82 of file HistogramPool.h.
{
                 // Create a histogram of type T
                 T* hist = new T(name.c_str(), name.c_str(), xbins, xmin, xmax, ybins, ymin, ymax);
                 // Set the title
                 hist->SetTitle("");
                 // Set the x-axis label
                 hist->GetXaxis()->SetTitle(xLabel.c_str());
                 hist->GetXaxis()->CenterTitle();
                 // Set the x-axis label
                 hist->GetYaxis()->SetTitle(yLabel.c_str());
                 hist->GetYaxis()->CenterTitle();
                 // Insert it into the pool of histograms for later use
                 histograms_[name] = hist;
             }
References histograms_.
get()
TH1 * ldmx::HistogramPool::get (const std::string & name)
Returns
Retrieve the histogram named "name" from the pool.
Definition at line 54 of file HistogramPool.cxx.
{
         auto histo = histograms_.find(name);
         if (histo == histograms_.end()) {
             EXCEPTION_RAISE( "InvalidArg" , "Histogram " + name + " not found in pool." );
         }
         return histograms_[name];
     }
References EXCEPTION_RAISE, and histograms_.
Referenced by ldmx::PhotoNuclearDQM::analyze(), ldmx::TrigScintHitDQM::analyze(), ldmx::HCalDQM::analyze(), ldmx::TrigScintDQM::analyze(), ldmx::RecoilTrackerDQM::analyze(), and ldmx::PhotoNuclearDQM::onProcessStart().
Member Data Documentation
histograms_
std::unordered_map< std::string, TH1* > ldmx::HistogramPool::histograms_ private
Container for all histograms.
Definition at line 27 of file HistogramPool.h.
Referenced by create(), and get().
instance
HistogramPool * ldmx::HistogramPool::instance = nullptr static private
HistogramPool singlenton.
Definition at line 30 of file HistogramPool.h.
The documentation for this class was generated from the following files:
Framework/include/Framework/HistogramPool.h
Framework/src/HistogramPool.cxx