LDMX Software: simcore::geo::GDMLParser Class Reference
simcore::geo::GDMLParser Class Reference
#include <GDMLParser.h>
Public Member Functions
GDMLParser (framework::config::Parameters &parameters, simcore::ConditionsInterface &ci)
~GDMLParser ()=default
Default destructor.
G4VPhysicalVolume * GetWorldVolume () final override
std::string getDetectorName () final override
void read () final override
Static Public Member Functions
static Parser * create (framework::config::Parameters &parameters, simcore::ConditionsInterface &ci)
Private Attributes
std::unique_ptr< G4GDMLParser > parser_
The GDML parser.
std::unique_ptr< simcore::geo::AuxInfoReader > info_
The auxiliary info reader.
framework::config::Parameters parameters_
The parameters used to configure this parser.
std::string detector_name_ {""}
The name of the parsed detector.
Detailed Description
Parse GDML files, build the geometry in memory and load it into Geant4.
This class extends the interface Parser which allows creation of the parser at runtime via a factory.
Definition at line 26 of file GDMLParser.h.
Constructor & Destructor Documentation
GDMLParser()
simcore::geo::GDMLParser::GDMLParser (framework::config::Parameters & parameters, simcore::ConditionsInterface & ci)
Default constructor.
Parameters
parameters The parameters used to configure this parser.
ci Interface that allows access to the conditions.
Definition at line 6 of file GDMLParser.cxx.
{
   parser_ = std::make_unique<G4GDMLParser>();
   info_ =
       std::make_unique<simcore::geo::AuxInfoReader>(parser_.get(), parameters, ci);
   parameters_ = parameters;
 }
References info_, parameters_, and parser_.
Referenced by create().
Member Function Documentation
create()
static Parser* simcore::geo::GDMLParser::create (framework::config::Parameters & parameters, simcore::ConditionsInterface & ci) inline static
Create an instance of this parser.
Definition at line 66 of file GDMLParser.h.
{
     return new GDMLParser(parameters, ci);
   }
References GDMLParser().
Referenced by simcore::geo::ParserFactory::ParserFactory().
getDetectorName()
std::string simcore::geo::GDMLParser::getDetectorName () inline final override virtual
Get the name of the parsed detector.
This name is typically extracted from the file containing the detector description.
Returns
The name of the detector.
Implements simcore::geo::Parser.
Definition at line 56 of file GDMLParser.h.
 { return detector_name_; }
References detector_name_.
GetWorldVolume()
G4VPhysicalVolume * simcore::geo::GDMLParser::GetWorldVolume () final override virtual
Retrieve the G4VPhysicalVolume associated with the most top-level (world) volume.
Returns
The world volume.
Implements simcore::geo::Parser.
Definition at line 14 of file GDMLParser.cxx.
{
   return parser_->GetWorldVolume();
 }
References parser_.
read()
void simcore::geo::GDMLParser::read () final override virtual
Parse the detector geometry and read it into memory.
Implements simcore::geo::Parser.
Definition at line 18 of file GDMLParser.cxx.
                       {
   parser_->Read(parameters_.getParameter<std::string>("detector"),
                 parameters_.getParameter<bool>("validate_detector"));
   info_->readGlobalAuxInfo();
   info_->assignAuxInfoToVolumes();
   detector_name_ = info_->getDetectorHeader()->getName();
 }
References detector_name_, framework::config::Parameters::getParameter(), info_, parameters_, and parser_.
The documentation for this class was generated from the following files:
SimCore/include/SimCore/Geo/GDMLParser.h
SimCore/src/SimCore/Geo/GDMLParser.cxx