LDMX Software: dqm::SimObjects Class Reference
dqm::SimObjects Class Reference
Generate histograms to check simulation output.
#include <SimObjects.h>
Public Member Functions
SimObjects (const std::string &name, framework::Process &process)
virtual void configure (framework::config::Parameters &ps)
virtual void onProcessStart ()
virtual void analyze (const framework::Event &event)
Public Member Functions inherited from framework::Analyzer
Analyzer (const std::string &name, Process &process)
virtual void analyze (const Event &event)=0
Public Member Functions inherited from framework::EventProcessor
EventProcessor (const std::string &name, Process &process)
virtual ~EventProcessor ()
virtual void configure (framework::config::Parameters &parameters)
virtual void onNewRun (const ldmx::RunHeader &runHeader)
virtual void onFileOpen (EventFile &eventFile)
virtual void onFileClose (EventFile &eventFile)
virtual void onProcessStart ()
virtual void onProcessEnd ()
template<class T >
const T & getCondition (const std::string &condition_name)
TDirectory * getHistoDirectory ()
void setStorageHint (framework::StorageControlHint hint)
void setStorageHint (framework::StorageControlHint hint, const std::string &purposeString)
int getLogFrequency () const
int getRunNumber () const
std::string getName () const
void createHistograms (const std::vector< framework::config::Parameters > &histos)
Private Member Functions
void createCalorimeterHists (const std::string &coll_name)
new calorimeter histograms
void createTrackerHists (const std::string &coll_name)
new tracker histograms
Private Attributes
std::string sim_pass_
Pass Name for sim objects.
Additional Inherited Members
Static Public Member Functions inherited from framework::EventProcessor
static void declare (const std::string &classname, int classtype, EventProcessorMaker *)
Static Public Attributes inherited from framework::Analyzer
static const int CLASSTYPE {2}
Protected Member Functions inherited from framework::EventProcessor
void abortEvent ()
Protected Attributes inherited from framework::EventProcessor
HistogramHelper histograms_
Interface class for making and filling histograms.
NtupleManager & ntuple_ {NtupleManager::getInstance()}
Manager for any ntuples.
logging::logger theLog_
The logger for this EventProcessor.
Detailed Description
Generate histograms to check simulation output.
Definition at line 14 of file SimObjects.h.
Constructor & Destructor Documentation
SimObjects()
dqm::SimObjects::SimObjects (const std::string & name, framework::Process & process) inline
Constructor
Blank Analyzer constructor
Definition at line 21 of file SimObjects.h.
      : framework::Analyzer(name, process) {}
Member Function Documentation
analyze()
void dqm::SimObjects::analyze (const framework::Event & event) virtual
Fills histograms
Implements framework::Analyzer.
Definition at line 80 of file SimObjects.cxx.
{
  static std::vector<framework::ProductTag> sp_maps, calo_colls, track_colls;
  if (sp_maps.empty()) {
    sp_maps = event.searchProducts("SimParticles","","");
    if (sp_maps.size() != 1) {
      ldmx_log(warn) << sp_maps.size() << " SimParticle maps which is not one!";
    }
  }
  if (calo_colls.empty()) {
    calo_colls = event.searchProducts("",sim_pass_,".*SimCalorimeterHit.*");
    for (auto pt : calo_colls)
      createCalorimeterHists(pt.name());
  }
  if (track_colls.empty()) {
    track_colls = event.searchProducts("",sim_pass_,".*SimTrackerHit.*");
    for (auto pt : track_colls)
      createTrackerHists(pt.name());
  }
  auto const& particle_map{event.getMap<int,ldmx::SimParticle>("SimParticles")};
  for (auto const& [track_id, particle] : particle_map) {
    auto const& momentum{particle.getMomentum()};
    auto const& vertex{particle.getVertex()};
    histograms_.fill("SimParticles.E", particle.getEnergy());
    histograms_.fill("SimParticles.px",momentum.at(0));
    histograms_.fill("SimParticles.py",momentum.at(1));
    histograms_.fill("SimParticles.pz",momentum.at(2));
    histograms_.fill("SimParticles.time",particle.getTime());
    histograms_.fill("SimParticles.pdg",particle.getPdgID());
    histograms_.fill("SimParticles.x", vertex.at(0));
    histograms_.fill("SimParticles.y", vertex.at(1));
    histograms_.fill("SimParticles.z", vertex.at(2));
    histograms_.fill("SimParticles.process", particle.getProcessType());
    histograms_.fill("SimParticles.track_id", track_id);
    for (auto const& parent : particle.getParents())
      histograms_.fill("SimParticles.parent", parent);
    for (auto const& child : particle.getDaughters())
      histograms_.fill("SimParticles.children", child);
    // PN particles are special
    if (particle.getProcessType() == ldmx::SimParticle::ProcessType::photonNuclear) {
      histograms_.fill("pn_child.E", particle.getEnergy());
      histograms_.fill("pn_child.px",momentum.at(0));
      histograms_.fill("pn_child.py",momentum.at(1));
      histograms_.fill("pn_child.pz",momentum.at(2));
      histograms_.fill("pn_child.time",particle.getTime());
      histograms_.fill("pn_child.pdg",particle.getPdgID());
      histograms_.fill("pn_child.x", vertex.at(0));
      histograms_.fill("pn_child.y", vertex.at(1));
      histograms_.fill("pn_child.z", vertex.at(2));
      histograms_.fill("pn_child.track_id", track_id);
      for (auto const& parent : particle.getParents())
        histograms_.fill("pn_child.parent", parent);
      for (auto const& child : particle.getDaughters())
        histograms_.fill("pn_child.children", child);
    }
  }  // loop over sim particle map
  for (auto const& pt : calo_colls) {
    auto const& coll{event.getCollection<ldmx::SimCalorimeterHit>(pt.name(),sim_pass_)};
    for (auto const& hit : coll) {
      unsigned int n_contribs{hit.getNumberOfContribs()};
      histograms_.fill(pt.name()+".n_contribs", n_contribs);
      for (unsigned int i_contrib{0}; i_contrib<n_contribs; i_contrib++) {
        ldmx::SimCalorimeterHit::Contrib contrib{hit.getContrib(i_contrib)};
        histograms_.fill(pt.name()+".incidents", contrib.incidentID);
        histograms_.fill(pt.name()+".tracks", contrib.trackID);
        histograms_.fill(pt.name()+".pdg", contrib.pdgCode);
      }
      histograms_.fill(pt.name()+".edep", hit.getEdep());
      auto pos{hit.getPosition()};
      histograms_.fill(pt.name()+".x",pos.at(0));
      histograms_.fill(pt.name()+".y",pos.at(1));
      histograms_.fill(pt.name()+".z",pos.at(2));
      histograms_.fill(pt.name()+".time", hit.getTime());
    }  // loop over hits in the calorimeter collection
  }    // loop over different calorimeter hit collections
  for (auto const& pt : track_colls) {
    auto const& coll{event.getCollection<ldmx::SimTrackerHit>(pt.name(),sim_pass_)};
    for (auto const& hit : coll) {
      histograms_.fill(pt.name()+".particle_E", hit.getEnergy());
      auto momentum{hit.getMomentum()};
      histograms_.fill(pt.name()+".particle_px", momentum.at(0));
      histograms_.fill(pt.name()+".particle_py", momentum.at(1));
      histograms_.fill(pt.name()+".particle_pz", momentum.at(2));
      histograms_.fill(pt.name()+".edep", hit.getEdep());
      histograms_.fill(pt.name()+".time", hit.getTime());
      auto pos{hit.getPosition()};
      histograms_.fill(pt.name()+".x", pos.at(0));
      histograms_.fill(pt.name()+".y", pos.at(1));
      histograms_.fill(pt.name()+".z", pos.at(2));
      histograms_.fill(pt.name()+".track", hit.getTrackID());
      histograms_.fill(pt.name()+".pdg", hit.getPdgID());
    }  // loop over hits in the tracker collection
  }    // loop over different tracker hit collections
  return;
}
References createCalorimeterHists(), createTrackerHists(), framework::HistogramHelper::fill(), ldmx::SimParticle::getMomentum(), ldmx::SimCalorimeterHit::getNumberOfContribs(), framework::EventProcessor::histograms_, and sim_pass_.
configure()
void dqm::SimObjects::configure (framework::config::Parameters & ps) virtual
Input python configuration parameters
Reimplemented from framework::EventProcessor.
Definition at line 12 of file SimObjects.cxx.
{
  sim_pass_ = ps.getParameter<std::string>("sim_pass");
  return;
}
References framework::config::Parameters::getParameter(), and sim_pass_.
createCalorimeterHists()
void dqm::SimObjects::createCalorimeterHists (const std::string & coll_name) private
new calorimeter histograms
Definition at line 50 of file SimObjects.cxx.
{
  getHistoDirectory();
  histograms_.create(coll_name+".incidents","Incident Track IDs",100,0,1000);
  histograms_.create(coll_name+".tracks","Contributing Track IDs",100,0,1000);
  histograms_.create(coll_name+".pdg","Contributing PDG IDs",401,-200,200);
  histograms_.create(coll_name+".edep","Energy Deposited [MeV]",100,0,200);
  histograms_.create(coll_name+".x","Hit x-Position [mm]",401,-200,200);
  histograms_.create(coll_name+".y","Hit y-Position [mm]",401,-200,200);
  histograms_.create(coll_name+".z","Hit z-Position [mm]",171,-700,1000.);
  histograms_.create(coll_name+".time","Hit Time [ns]",50,0.,10.);
  histograms_.create(coll_name+".n_contribs","Number of Contributors",20,0.,20.);
  return;
}
References framework::HistogramHelper::create(), framework::EventProcessor::getHistoDirectory(), and framework::EventProcessor::histograms_.
Referenced by analyze().
createTrackerHists()
void dqm::SimObjects::createTrackerHists (const std::string & coll_name) private
new tracker histograms
Definition at line 64 of file SimObjects.cxx.
{
  getHistoDirectory();
  histograms_.create(coll_name+".particle_E","Particle E at Hit [MeV]",400,0,4000);
  histograms_.create(coll_name+".particle_px","Particle Momentum in x [MeV]",50,0.,500.);
  histograms_.create(coll_name+".particle_py","Particle Momentum in y [MeV]",50,0.,500.);
  histograms_.create(coll_name+".particle_pz","Particle Momentum in z [MeV]",400,0.,4000.);
  histograms_.create(coll_name+".edep","Energy Deposited [MeV]",100,0,200);
  histograms_.create(coll_name+".time","Hit Time [ns]",50,0.,10.);
  histograms_.create(coll_name+".x","Hit x-Position [mm]",401,-200,200);
  histograms_.create(coll_name+".y","Hit y-Position [mm]",401,-200,200);
  histograms_.create(coll_name+".z","Hit z-Position [mm]",171,-700,1000.);
  histograms_.create(coll_name+".track","Particle Track ID",100,0,1000);
  histograms_.create(coll_name+".pdg","Particle PDG ID",401,-200,200);
  return;
}
References framework::HistogramHelper::create(), framework::EventProcessor::getHistoDirectory(), and framework::EventProcessor::histograms_.
Referenced by analyze().
onProcessStart()
void dqm::SimObjects::onProcessStart () virtual
Construct histograms depending on which objects are requested.
Reimplemented from framework::EventProcessor.
Definition at line 17 of file SimObjects.cxx.
{
  getHistoDirectory();
  // create sim particles histograms
  histograms_.create("SimParticles.E","Vertex Total Energy [MeV]",800,0.,8000.);
  histograms_.create("SimParticles.px","Vertex Momentum in x-Direction [MeV]",50,0.,500.);
  histograms_.create("SimParticles.py","Vertex Momentum in y-Direction [MeV]",50,0.,500.);
  histograms_.create("SimParticles.pz","Vertex Momentum in z-Direction [MeV]",400,0.,4000.);
  histograms_.create("SimParticles.time","Global Time of Creation [ns]",50,0.,10.);
  histograms_.create("SimParticles.pdg","PDG ID of Particle",201,-100,100);
  histograms_.create("SimParticles.x","Vertex x-Position [mm]",401,-200,200);
  histograms_.create("SimParticles.y","Vertex y-Position [mm]",401,-200,200);
  histograms_.create("SimParticles.z","Vertex z-Position [mm]",171,-700,1000.);
  histograms_.create("SimParticles.process","Creator Process Type",12,0,12);
  histograms_.create("SimParticles.track_id","Track ID of Particle",100,0,1000);
  histograms_.create("SimParticles.parent","Track ID of Parent",100,0,1000);
  histograms_.create("SimParticles.children","Track IDs of Children",100,0,1000);
  // create pn children histograms
  histograms_.create("pn_child.E","Vertex Total Energy [MeV]",800,0.,8000.);
  histograms_.create("pn_child.px","Vertex Momentum in x-Direction [MeV]",50,0.,500.);
  histograms_.create("pn_child.py","Vertex Momentum in y-Direction [MeV]",50,0.,500.);
  histograms_.create("pn_child.pz","Vertex Momentum in z-Direction [MeV]",400,0.,4000.);
  histograms_.create("pn_child.time","Global Time of Creation [ns]",50,0.,10.);
  histograms_.create("pn_child.pdg","PDG ID of Particle",201,-100,100);
  histograms_.create("pn_child.x","Vertex x-Position [mm]",401,-200,200);
  histograms_.create("pn_child.y","Vertex y-Position [mm]",401,-200,200);
  histograms_.create("pn_child.z","Vertex z-Position [mm]",171,-700,1000.);
  histograms_.create("pn_child.track_id","Track ID of Particle",100,0,1000);
  histograms_.create("pn_child.parent","Track ID of Parent",100,0,1000);
  histograms_.create("pn_child.children","Track IDs of Children",100,0,1000);
}
References framework::HistogramHelper::create(), framework::EventProcessor::getHistoDirectory(), and framework::EventProcessor::histograms_.
Member Data Documentation
sim_pass_
std::string dqm::SimObjects::sim_pass_ private
Pass Name for sim objects.
Definition at line 48 of file SimObjects.h.
Referenced by analyze(), and configure().
The documentation for this class was generated from the following files:
DQM/include/DQM/SimObjects.h
DQM/src/DQM/SimObjects.cxx