LDMX Software: ecal::EcalDetectorMap Class Reference
ecal::EcalDetectorMap Class Reference
Class which provides various information about how the parts of the Ecal connect to each other.
#include <EcalDetectorMap.h>
Classes
struct CellInformation
struct MotherboardLinksInformation
struct MotherboardsPerLayer
Public Member Functions
EcalDetectorMap (const std::string &cell_map, const std::string &motherboard_map, const std::string &layer_map, bool want_d2e)
Public Member Functions inherited from framework::ConditionsObject
ConditionsObject (const std::string &name)
virtual ~ConditionsObject ()
std::string getName () const
Public Member Functions inherited from ldmx::ElectronicsMap< ldmx::EcalElectronicsID, ldmx::EcalID >
ElectronicsMap (bool want_d2e=false)
void clear ()
void addEntry (ldmx::EcalElectronicsID eid, ldmx::EcalID did)
bool exists (ldmx::EcalElectronicsID eid) const
bool exists (ldmx::EcalID did) const
ldmx::EcalID get (ldmx::EcalElectronicsID eid) const
ldmx::EcalElectronicsID get (ldmx::EcalID did) const
Static Public Attributes
static constexpr const char * CONDITIONS_OBJECT_NAME {"EcalDetectorMap"}
The name of the EID <-> DetID map for the ECal.
Private Member Functions
void loadCellMap (conditions::GeneralCSVLoader &loader)
import cell map from the provided CSV loader
void loadMotherboardMap (conditions::GeneralCSVLoader &loader)
import motherboard map from the provided CSV loader
void loadLayerMap (conditions::GeneralCSVLoader &loader)
import layer map from the provided CSV loader
void buildElectronicsMap ()
build the electronics map from loaded maps
Private Attributes
std::vector< CellInformation > cells_
std::vector< MotherboardLinksInformation > elinks_
std::vector< MotherboardsPerLayer > layers_
Friends
class EcalDetectorMapLoader
Provider which loads the map.
Detailed Description
Class which provides various information about how the parts of the Ecal connect to each other.
The class is loaded from three tables, currently in the form of CSV objects, using the EcalDetectorMapLoader declared and defined in the source.
CellMap gives the information for a single Ecal module and has the following columns CELLID – EcalDetectorID cell id ROCID – which ROC on the module ROC_ELINK_NUMBER – which elink on the ROC (0/1) ROC_ELINK_CHANNEL – which channel on the elink (0-35)
MotherboardMap gives information about how the modules plug into a given type of motherboard ROCID – which ROC on the module ROC_ELINK_NUMBER – which elink on the ROC (0/1) MODULE – which module on the layer POLARFIRE_ELINK – elink input number on the Polarfire MOTHERBOARD_TYPE – what type of motherboard is this
LayerMap gives information about how the motherboards are used on the various layers LAYER – layer number MOTHERBOARD_TYPE OLINK – DAQ optical link number
We inherit from two classes: (1) the ConditionsObject because we are a conditions object and (2) from the ElectronicsMap template because we are a electronics map.
Definition at line 47 of file EcalDetectorMap.h.
Constructor & Destructor Documentation
EcalDetectorMap()
ecal::EcalDetectorMap::EcalDetectorMap (const std::string & cell_map, const std::string & motherboard_map, const std::string & layer_map, bool want_d2e)
Default constructor which builds the necessary maps.
Parameters
[in] want_d2e true if we want to build a reverse mapping Building a reverse (detector->electronics) map takes extra time and memory so it should be off by default.
Definition at line 50 of file EcalDetectorMap.cxx.
    : framework::ConditionsObject(CONDITIONS_OBJECT_NAME),
      ldmx::ElectronicsMap<ldmx::EcalElectronicsID, ldmx::EcalID>(want_d2e) {
      conditions::StreamCSVLoader scell(cell_map);
      this->loadCellMap(scell);
      conditions::StreamCSVLoader smb(motherboard_map);
      this->loadMotherboardMap(smb);
      conditions::StreamCSVLoader slayer(layer_map);
      this->loadLayerMap(slayer);
      this->buildElectronicsMap();
}
References buildElectronicsMap(), loadCellMap(), loadLayerMap(), and loadMotherboardMap().
Member Function Documentation
buildElectronicsMap()
void ecal::EcalDetectorMap::buildElectronicsMap () private
build the electronics map from loaded maps
Definition at line 99 of file EcalDetectorMap.cxx.
{
  this->clear();  // empty the electronics map
  // loop over optical links
  for (auto olink : layers_) {
    for (auto elink : elinks_) {
      // select only matching motherboard types
      if (elink.motherboard_type != olink.motherboard_type) continue;
      for (auto cell : cells_) {
        // select only cells which are associated with the appropriate elink
        if (elink.rocid != cell.rocid ||
            elink.roc_elink_number != cell.roc_elink_number)
          continue;
        // now, we have only cells which are relevant
        ldmx::EcalID precisionId(olink.layer, elink.module, cell.module_cellid);
        ldmx::EcalElectronicsID elecId(olink.daq_opticallink,
                                       elink.polarfire_elink,
                                       cell.roc_elink_channel);
        if (this->exists(elecId)) {
          std::stringstream ss;
          ss << "Two different mappings for electronics channel " << elecId;
          EXCEPTION_RAISE("DuplicateMapping", ss.str());
        }
        this->addEntry(elecId, precisionId);
      }
    }
  }
}
References ldmx::ElectronicsMap< ldmx::EcalElectronicsID, ldmx::EcalID >::addEntry(), ldmx::ElectronicsMap< ldmx::EcalElectronicsID, ldmx::EcalID >::clear(), and ldmx::ElectronicsMap< ldmx::EcalElectronicsID, ldmx::EcalID >::exists().
Referenced by EcalDetectorMap().
loadCellMap()
void ecal::EcalDetectorMap::loadCellMap (conditions::GeneralCSVLoader & loader) private
import cell map from the provided CSV loader
Definition at line 63 of file EcalDetectorMap.cxx.
{
  cells_.clear();
  while (loader.nextRow()) {
    CellInformation ci;
    ci.module_cellid = loader.getInteger("CELLID");
    ci.rocid = loader.getInteger("ROCID");
    ci.roc_elink_number = loader.getInteger("ROC_ELINK_NUMBER");
    ci.roc_elink_channel = loader.getInteger("ROC_ELINK_CHANNEL");
    cells_.push_back(ci);
  }
}
References conditions::GeneralCSVLoader::getInteger(), ecal::EcalDetectorMap::CellInformation::module_cellid, conditions::GeneralCSVLoader::nextRow(), ecal::EcalDetectorMap::CellInformation::roc_elink_channel, ecal::EcalDetectorMap::CellInformation::roc_elink_number, and ecal::EcalDetectorMap::CellInformation::rocid.
Referenced by EcalDetectorMap().
loadLayerMap()
void ecal::EcalDetectorMap::loadLayerMap (conditions::GeneralCSVLoader & loader) private
import layer map from the provided CSV loader
Definition at line 88 of file EcalDetectorMap.cxx.
{
  layers_.clear();
  while (loader.nextRow()) {
    MotherboardsPerLayer mpl;
    mpl.motherboard_type = loader.getInteger("MOTHERBOARD_TYPE");
    mpl.layer = loader.getInteger("LAYER");
    mpl.daq_opticallink = loader.getInteger("OLINK");
    layers_.push_back(mpl);
  }
}
References ecal::EcalDetectorMap::MotherboardsPerLayer::daq_opticallink, conditions::GeneralCSVLoader::getInteger(), ecal::EcalDetectorMap::MotherboardsPerLayer::layer, ecal::EcalDetectorMap::MotherboardsPerLayer::motherboard_type, and conditions::GeneralCSVLoader::nextRow().
Referenced by EcalDetectorMap().
loadMotherboardMap()
void ecal::EcalDetectorMap::loadMotherboardMap (conditions::GeneralCSVLoader & loader) private
import motherboard map from the provided CSV loader
Definition at line 75 of file EcalDetectorMap.cxx.
{
  elinks_.clear();
  while (loader.nextRow()) {
    MotherboardLinksInformation mli;
    mli.motherboard_type = loader.getInteger("MOTHERBOARD_TYPE");
    mli.module = loader.getInteger("MODULE");
    mli.rocid = loader.getInteger("ROCID");
    mli.roc_elink_number = loader.getInteger("ROC_ELINK_NUMBER");
    mli.polarfire_elink = loader.getInteger("POLARFIRE_ELINK");
    elinks_.push_back(mli);
  }
}
References conditions::GeneralCSVLoader::getInteger(), ecal::EcalDetectorMap::MotherboardLinksInformation::module, ecal::EcalDetectorMap::MotherboardLinksInformation::motherboard_type, conditions::GeneralCSVLoader::nextRow(), ecal::EcalDetectorMap::MotherboardLinksInformation::polarfire_elink, ecal::EcalDetectorMap::MotherboardLinksInformation::roc_elink_number, and ecal::EcalDetectorMap::MotherboardLinksInformation::rocid.
Referenced by EcalDetectorMap().
Friends And Related Function Documentation
EcalDetectorMapLoader
friend class EcalDetectorMapLoader friend
Provider which loads the map.
Definition at line 64 of file EcalDetectorMap.h.
Member Data Documentation
cells_
std::vector<CellInformation> ecal::EcalDetectorMap::cells_ private
Definition at line 91 of file EcalDetectorMap.h.
CONDITIONS_OBJECT_NAME
constexpr const char* ecal::EcalDetectorMap::CONDITIONS_OBJECT_NAME {"EcalDetectorMap"} static constexpr
The name of the EID <-> DetID map for the ECal.
Definition at line 52 of file EcalDetectorMap.h.
Referenced by ecal::EcalRawDecoder::produce(), and ecal::EcalRawEncoder::produce().
elinks_
std::vector<MotherboardLinksInformation> ecal::EcalDetectorMap::elinks_ private
Definition at line 108 of file EcalDetectorMap.h.
layers_
std::vector<MotherboardsPerLayer> ecal::EcalDetectorMap::layers_ private
Definition at line 121 of file EcalDetectorMap.h.
The documentation for this class was generated from the following files:
Ecal/include/Ecal/EcalDetectorMap.h
Ecal/src/Ecal/EcalDetectorMap.cxx