LDMX Software: ldmx::Exception Class Reference
ldmx::Exception Class Reference
Standard base exception class with some useful output information.
#include <Exception.h>
Public Member Functions
Exception () throw ()
Exception (const std::string &name, const std::string &message, const std::string &module, int line, const std::string &function)
virtual ~Exception () throw ()
const std::string & name () const throw ()
const std::string & message () const throw ()
const std::string & module () const throw ()
const std::string & function () const throw ()
int line () const throw ()
virtual const char * what () const throw ()
const std::string & stackTrace () const throw ()
Private Member Functions
void buildStackTrace () throw ()
Private Attributes
std::string name_
std::string message_
std::string module_
std::string function_
int line_ {0}
std::string stackTrace_
Detailed Description
Standard base exception class with some useful output information.
Note
It is strongly recommended to use the EXCEPTION_RAISE macro to throw exceptions.
Definition at line 18 of file Exception.h.
Constructor & Destructor Documentation
Exception() [1/2]
ldmx::Exception::Exception () throw () inline
Empty constructor.
Don't build stack trace for empty exceptions.
Definition at line 27 of file Exception.h.
{
             }
Exception() [2/2]
ldmx::Exception::Exception (const std::string & name, const std::string & message, const std::string & module, int line, const std::string & function) inline
Class constructor.
Parameters
name Name of the exception.
message Extended message describing the exception.
module Filename in the source code where the exception occurred.
line Line in the source code where the exception occurred.
function Function in which the exception occurred.
Definition at line 38 of file Exception.h.
                                                                                                                                      :
                     name_ { name }, message_ { message }, module_ { module }, function_ { function }, line_ { line } {
                 buildStackTrace();
             }
References name().
~Exception()
virtual ldmx::Exception::~Exception () throw () inline virtual
Class destructor.
Definition at line 46 of file Exception.h.
{
             }
Member Function Documentation
function()
const std::string& ldmx::Exception::function () const throw () inline
Get the function name where the exception occurred.
Returns
The function name where the exception occurred.
Definition at line 77 of file Exception.h.
{
                 return function_;
             }
References function_.
Referenced by ldmx::test::runProcess().
line()
int ldmx::Exception::line () const throw () inline
Get the source line number where the exception occurred.
Returns
The source line number where the exception occurred.
Definition at line 85 of file Exception.h.
{
                 return line_;
             }
References line_.
Referenced by ldmx::test::runProcess().
message()
const std::string& ldmx::Exception::message () const throw () inline
Get the message of the exception.
Returns
The message of the exception.
Definition at line 61 of file Exception.h.
{
                 return message_;
             }
References message_.
Referenced by ldmx::test::runProcess().
module()
const std::string& ldmx::Exception::module () const throw () inline
Get the source filename where the exception occurred.
Returns
The source filename where the exception occurred.
Definition at line 69 of file Exception.h.
{
                 return module_;
             }
References module_.
Referenced by ldmx::test::runProcess().
name()
const std::string& ldmx::Exception::name () const throw () inline
Get the name of the exception.
Returns
The name of the exception.
Definition at line 53 of file Exception.h.
{
                 return name_;
             }
References name_.
Referenced by Exception(), and ldmx::test::runProcess().
stackTrace()
const std::string& ldmx::Exception::stackTrace () const throw () inline
Get the full stack trace
Definition at line 100 of file Exception.h.
{
                 return stackTrace_;
             }
References stackTrace_.
what()
virtual const char* ldmx::Exception::what () const throw () inline virtual
The error message.
Returns
The error message.
Definition at line 93 of file Exception.h.
{
                 return message_.c_str();
             }
References message_.
Member Data Documentation
function_
std::string ldmx::Exception::function_ private
Function name where the exception occurred.
Definition at line 118 of file Exception.h.
Referenced by function().
line_
int ldmx::Exception::line_ {0} private
Source line number where the exception occurred.
Definition at line 121 of file Exception.h.
Referenced by line().
message_
std::string ldmx::Exception::message_ private
Error message.
Definition at line 112 of file Exception.h.
Referenced by message(), and what().
module_
std::string ldmx::Exception::module_ private
Source filename where the exception occurred.
Definition at line 115 of file Exception.h.
Referenced by module().
name_
std::string ldmx::Exception::name_ private
Exception name.
Definition at line 109 of file Exception.h.
Referenced by name().
stackTrace_
std::string ldmx::Exception::stackTrace_ private
The stack trace
Definition at line 124 of file Exception.h.
Referenced by stackTrace().
The documentation for this class was generated from the following files:
Framework/include/Framework/Exception/Exception.h
Framework/src/Framework/Exception/Exception.cxx