LDMX Software: ldmx::EcalVetoResult Class Reference
ldmx::EcalVetoResult Class Reference
Public Member Functions
EcalVetoResult ()
~EcalVetoResult ()
void setVariables (int nReadoutHits, int deepestLayerHit, float summedDet, float summedTightIso, float maxCellDep, float showerRMS, float xStd, float yStd, float avgLayerHit, float stdLayerHit, float ecalBackEnergy, int nStraightTracks, int nLinregTracks, int firstNearPhLayer, float epAng, float epSep, std::vector< float > electronContainmentEnergy, std::vector< float > photonContainmentEnergy, std::vector< float > outsideContainmentEnergy, std::vector< int > outsideContainmentNHits, std::vector< float > outsideContainmentXStd, std::vector< float > outsideContainmentYStd, std::vector< float > EcalLayerEdepReadout, std::vector< double > recoilP, std::vector< float > recoilPos)
void Clear ()
void Print () const
bool passesVeto () const
float getDisc () const
int getDeepestLayerHit () const
int getNReadoutHits () const
float getSummedDet () const
float getSummedTightIso () const
float getMaxCellDep () const
float getShowerRMS () const
float getXStd () const
float getYStd () const
float getAvgLayerHit () const
float getStdLayerHit () const
float getEcalBackEnergy () const
const std::vector< float > & getElectronContainmentEnergy () const
const std::vector< float > & getPhotonContainmentEnergy () const
const std::vector< float > & getOutsideContainmentEnergy () const
const std::vector< int > & getOutsideContainmentNHits () const
const std::vector< float > & getOutsideContainmentXStd () const
const std::vector< float > & getOutsideContainmentYStd () const
const std::vector< float > & getEcalLayerEdepReadout () const
void setVetoResult (bool passesVeto)
void setDiscValue (float discValue)
std::vector< double > getRecoilMomentum ()
double getRecoilX () const
double getRecoilY () const
int getNStraightTracks () const
Number of straight tracks found.
int getNLinRegTracks () const
Number of linear-regression tracks found.
int getFirstNearPhLayer () const
float getEPAng () const
float getEPSep () const
Private Member Functions
ClassDef (EcalVetoResult, 5)
Private Attributes
bool passesVeto_ {false}
int nReadoutHits_ {0}
int deepestLayerHit_ {0}
float summedDet_ {0}
float summedTightIso_ {0}
float maxCellDep_ {0}
float showerRMS_ {0}
float xStd_ {0}
float yStd_ {0}
float avgLayerHit_ {0}
float stdLayerHit_ {0}
float ecalBackEnergy_ {0}
int nStraightTracks_ {0}
Number of "straight" tracks found in the event.
int nLinregTracks_ {0}
Number of "linreg" tracks found in the event.
int firstNearPhLayer_ {0}
Earliest ECal layer in which a hit is found near the projected photon trajectory (currently unused)
float epAng_ {0}
Angular separation between the projected photon and electron trajectories (currently unused)
float epSep_ {0}
Distance between the projected photon and electron trajectories at the ECal face (currently unused)
std::vector< float > electronContainmentEnergy_
std::vector< float > photonContainmentEnergy_
std::vector< float > outsideContainmentEnergy_
std::vector< int > outsideContainmentNHits_
std::vector< float > outsideContainmentXStd_
std::vector< float > outsideContainmentYStd_
float discValue_ {0}
double recoilPx_ {-9999}
double recoilPy_ {-9999}
double recoilPz_ {-9999}
float recoilX_ {-9999}
float recoilY_ {-9999}
std::vector< float > ecalLayerEdepReadout_
Detailed Description
Definition at line 24 of file EcalVetoResult.h.
Constructor & Destructor Documentation
EcalVetoResult()
ldmx::EcalVetoResult::EcalVetoResult ()
Constructor
~EcalVetoResult()
ldmx::EcalVetoResult::~EcalVetoResult ()
Destructor
Member Function Documentation
Clear()
void ldmx::EcalVetoResult::Clear ()
Reset the object.
getRecoilMomentum()
std::vector<double> ldmx::EcalVetoResult::getRecoilMomentum () inline
Return the momentum of the recoil at the Ecal face.
Definition at line 116 of file EcalVetoResult.h.
{
     return {recoilPx_, recoilPy_, recoilPz_};
   };
References recoilPx_, recoilPy_, and recoilPz_.
getRecoilX()
double ldmx::EcalVetoResult::getRecoilX () const inline
Return the x position of the recoil at the Ecal face.
Definition at line 121 of file EcalVetoResult.h.
 { return recoilX_; };
References recoilX_.
getRecoilY()
double ldmx::EcalVetoResult::getRecoilY () const inline
Return the y position of the recoil at the Ecal face.
Definition at line 124 of file EcalVetoResult.h.
 { return recoilY_; };
References recoilY_.
passesVeto()
bool ldmx::EcalVetoResult::passesVeto () const inline
Checks if the event passes the Ecal veto.
Definition at line 59 of file EcalVetoResult.h.
 { return passesVeto_; }
References passesVeto_.
Referenced by ecal::DNNEcalVetoProcessor::produce(), and ecal::EcalVetoProcessor::produce().
Print()
void ldmx::EcalVetoResult::Print () const
Print the object
setVariables()
void ldmx::EcalVetoResult::setVariables (int nReadoutHits, int deepestLayerHit, float summedDet, float summedTightIso, float maxCellDep, float showerRMS, float xStd, float yStd, float avgLayerHit, float stdLayerHit, float ecalBackEnergy, int nStraightTracks, int nLinregTracks, int firstNearPhLayer, float epAng, float epSep, std::vector< float > electronContainmentEnergy, std::vector< float > photonContainmentEnergy, std::vector< float > outsideContainmentEnergy, std::vector< int > outsideContainmentNHits, std::vector< float > outsideContainmentXStd, std::vector< float > outsideContainmentYStd, std::vector< float > EcalLayerEdepReadout, std::vector< double > recoilP, std::vector< float > recoilPos)
Set the sim particle and 'is findable' flag.
Referenced by ecal::EcalVetoProcessor::produce().
Member Data Documentation
passesVeto_
bool ldmx::EcalVetoResult::passesVeto_ {false} private
Flag indicating whether the event is vetoed by the Ecal.
Definition at line 138 of file EcalVetoResult.h.
Referenced by passesVeto().
recoilPx_
double ldmx::EcalVetoResult::recoilPx_ {-9999} private
px of recoil electron at the Ecal face.
Definition at line 174 of file EcalVetoResult.h.
Referenced by getRecoilMomentum().
recoilPy_
double ldmx::EcalVetoResult::recoilPy_ {-9999} private
py of recoil electron at the Ecal face.
Definition at line 177 of file EcalVetoResult.h.
Referenced by getRecoilMomentum().
recoilPz_
double ldmx::EcalVetoResult::recoilPz_ {-9999} private
py of recoil electron at the Ecal face.
Definition at line 180 of file EcalVetoResult.h.
Referenced by getRecoilMomentum().
recoilX_
float ldmx::EcalVetoResult::recoilX_ {-9999} private
x position of recoil electron at the Ecal face.
Definition at line 183 of file EcalVetoResult.h.
Referenced by getRecoilX().
recoilY_
float ldmx::EcalVetoResult::recoilY_ {-9999} private
y position of recoil electron at the Ecal face.
Definition at line 186 of file EcalVetoResult.h.
Referenced by getRecoilY().
The documentation for this class was generated from the following file:
Ecal/include/Ecal/Event/EcalVetoResult.h