LDMX Software: biasing::EcalDarkBremFilter Class Reference
biasing::EcalDarkBremFilter Class Reference
#include <EcalDarkBremFilter.h>
Public Member Functions
EcalDarkBremFilter (const std::string &name, framework::config::Parameters &parameters)
~EcalDarkBremFilter ()
std::vector< simcore::TYPE > getTypes () final override
void BeginOfEventAction (const G4Event *event) final override
G4ClassificationOfNewTrack ClassifyNewTrack (const G4Track *aTrack, const G4ClassificationOfNewTrack &currentTrackClass) final override
void NewStage () final override
void PostUserTrackingAction (const G4Track *track) final override
Public Member Functions inherited from simcore::UserAction
UserAction (const std::string &name, framework::config::Parameters &parameters)
virtual ~UserAction ()=default
Destructor.
virtual void BeginOfEventAction (const G4Event *)
virtual void EndOfEventAction (const G4Event *)
virtual void BeginOfRunAction (const G4Run *)
virtual void EndOfRunAction (const G4Run *)
virtual void PreUserTrackingAction (const G4Track *)
virtual void PostUserTrackingAction (const G4Track *)
virtual void stepping (const G4Step *)
virtual G4ClassificationOfNewTrack ClassifyNewTrack (const G4Track *, const G4ClassificationOfNewTrack &cl)
virtual void NewStage ()
virtual void PrepareNewEvent ()
virtual std::vector< TYPE > getTypes ()=0
Private Member Functions
bool inDesiredVolume (const G4Track *) const
void AbortEvent (const std::string &reason) const
Private Attributes
double threshold_
std::vector< G4LogicalVolume * > volumes_
bool foundAp_
Additional Inherited Members
Public Types inherited from simcore::UserAction
using Factory = ::simcore::Factory< UserAction, std::shared_ptr< UserAction >, const std::string &, framework::config::Parameters & >
factory for user actions
Protected Member Functions inherited from simcore::UserAction
UserEventInformation * getEventInfo () const
const std::map< int, ldmx::SimParticle > & getCurrentParticleMap () const
Protected Attributes inherited from simcore::UserAction
std::string name_ {""}
Name of the UserAction.
framework::config::Parameters parameters_
The set of parameters used to configure this class.
Detailed Description
This class is meant to filter for events that produce a dark brem occuring within the ECal and producing an A' of a minimum energy threshold [MeV].
Note
The threshold that the A' needs to have should be equal to or greater than the threshold of the PartialEnergySorter.
See also
PartialEnergySorter Here we assume that the partial energy sorter is being run in sequence with this filter. This filter makes sure that any events passing this filter have an A' of the required input energy and generated inside of the required input volume.
Definition at line 46 of file EcalDarkBremFilter.h.
Constructor & Destructor Documentation
EcalDarkBremFilter()
EcalDarkBremFilter::EcalDarkBremFilter (const std::string & name, framework::config::Parameters & parameters)
Class constructor.
Retrieve the necessary configuration parameters
Definition at line 19 of file EcalDarkBremFilter.cxx.
    : simcore::UserAction(name, parameters) {
  threshold_ = parameters.getParameter<double>("threshold");
  /*
   * We look for the logical volumes that match the following pattern:
   *  - 'volume' is in the name AND
   *  - 'Si' OR 'W' OR 'CFMix' OR 'PCB' are in the name
   */
  for (G4LogicalVolume* volume : *G4LogicalVolumeStore::GetInstance()) {
    G4String volumeName = volume->GetName();
    // looking for ecal volumes
    if (volumeName.contains("volume") and
        (volumeName.contains("Si") or volumeName.contains("W") or
         volumeName.contains("CFMix") or volumeName.contains("PCB") or
         volumeName.contains("Al"))) {
      volumes_.push_back(volume);
    }
  }
  if (G4RunManager::GetRunManager()->GetVerboseLevel() > 0) {
    std::cout << "[ EcalDarkBremFilter ]: "
              << "Looking for A' in: ";
    for (auto const& volume : volumes_) std::cout << volume->GetName() << ", ";
    std::cout << std::endl;
  }
}
References framework::config::Parameters::getParameter(), threshold_, and volumes_.
~EcalDarkBremFilter()
biasing::EcalDarkBremFilter::~EcalDarkBremFilter () inline
Class destructor.
Definition at line 59 of file EcalDarkBremFilter.h.
{}
Member Function Documentation
AbortEvent()
void EcalDarkBremFilter::AbortEvent (const std::string & reason) const private
Helper to abort an event with a message
Tells the RunManger to abort the current event after displaying the input message.
Parameters
[in] reason reason for aborting the event
Definition at line 131 of file EcalDarkBremFilter.cxx.
{
  if (G4RunManager::GetRunManager()->GetVerboseLevel() > 1) {
    std::cout << "[ EcalDarkBremFilter ]: "
              << "("
              << G4EventManager::GetEventManager()
                     ->GetConstCurrentEvent()
                     ->GetEventID()
              << ") " << reason << " Aborting event." << std::endl;
  }
  G4RunManager::GetRunManager()->AbortEvent();
  return;
}
Referenced by ClassifyNewTrack(), NewStage(), and PostUserTrackingAction().
BeginOfEventAction()
void EcalDarkBremFilter::BeginOfEventAction (const G4Event * event) final override virtual
Reset flag on if A' has been found
Parameters
event unused
Reimplemented from simcore::UserAction.
Definition at line 48 of file EcalDarkBremFilter.cxx.
{
  /* Debug message
  std::cout << "[ EcalDarkBremFilter ]: "
      << "(" <<
  G4EventManager::GetEventManager()->GetConstCurrentEvent()->GetEventID() << ")
  "
      << "Beginning event."
      << std::endl;
  */
  foundAp_ = false;
  return;
}
References foundAp_.
ClassifyNewTrack()
G4ClassificationOfNewTrack EcalDarkBremFilter::ClassifyNewTrack (const G4Track * aTrack, const G4ClassificationOfNewTrack & currentTrackClass) final override virtual
We return the classification of the track done by the PartialEnergySorter, but we can check here if the A' has been created above the required energy.
Checks a new track for being an A' above threshold_ if it is an A', sets the foundAp_ member
See also
PartialEnergySort::ClassifyNewTrack
Parameters
aTrack The Geant4 track.
currentTrackClass The current track classification.
Returns
current track classification
Reimplemented from simcore::UserAction.
Definition at line 61 of file EcalDarkBremFilter.cxx.
{
  if (aTrack->GetParticleDefinition() == G4APrime::APrime()) {
    // there is an A'! Yay!
    /* Debug message
    std::cout << "[ EcalDarkBremFilter ]: "
              << "Found A', still need to check if it originated in requested
    volume."
              << std::endl;
    */
    if (not foundAp_ and aTrack->GetTotalEnergy() > threshold_) {
      // The A' is the first one created in this event and is above the energy
      // threshold
      foundAp_ = true;
    } else if (foundAp_) {
      AbortEvent("Found more than one A' during filtering.");
    } else {
      AbortEvent("A' was not produced above the required threshold.");
    }
  }
  return cl;
}
References AbortEvent(), G4APrime::APrime(), foundAp_, and threshold_.
getTypes()
std::vector< simcore::TYPE > biasing::EcalDarkBremFilter::getTypes () inline final override virtual
Get the types of actions this class can do
Returns
list of action types this class does
Implements simcore::UserAction.
Definition at line 66 of file EcalDarkBremFilter.h.
{
    return {simcore::TYPE::STACKING, simcore::TYPE::EVENT,
            simcore::TYPE::TRACKING};
  }
inDesiredVolume()
bool EcalDarkBremFilter::inDesiredVolume (const G4Track * track) const private
Check if input volume is in the desired volume name
Parameters
pointer to track to check
Returns
true if originated in desired volume
Comparing the pointers to logical volumes isn't very robust. TODO find a better way to do this
Definition at line 117 of file EcalDarkBremFilter.cxx.
{
  auto inVol = track->GetLogicalVolumeAtVertex();
  for (auto const& volume : volumes_) {
    if (inVol == volume) return true;
  }
  return false;
}
References volumes_.
Referenced by PostUserTrackingAction().
NewStage()
void EcalDarkBremFilter::NewStage () final override virtual
When using the PartialEnergySorter, the first time that a new stage begins is when all particles are now below the threshold.
We take this opportunity to make sure that the A' has been found.
See also
PartialEnergySort::NewStage
Reimplemented from simcore::UserAction.
Definition at line 85 of file EcalDarkBremFilter.cxx.
{
  if (not foundAp_) AbortEvent("A' wasn't produced.");
  return;
}
References AbortEvent(), and foundAp_.
PostUserTrackingAction()
void EcalDarkBremFilter::PostUserTrackingAction (const G4Track * track) final override virtual
Make sure A' is saved.
If passed track is A', set save status to true Aborts event if A' does not originate in desired volume. This is the last check that the event needs to pass to be kept.
Parameters
track G4Track to check if it is an A'
Reimplemented from simcore::UserAction.
Definition at line 91 of file EcalDarkBremFilter.cxx.
{
  /* Check that generational stacking is working
  std::cout << "[ EcalDarkBremFilter ]:"
      << track->GetTrackID() << " " <<
  track->GetParticleDefinition()->GetPDGEncoding()
      << std::endl;
  */
  const G4VProcess* creator = track->GetCreatorProcess();
  if (creator and creator->GetProcessName().contains(
                      G4DarkBremsstrahlung::PROCESS_NAME)) {
    // make sure all secondaries of dark brem process are saved
    simcore::UserTrackInformation* userInfo = simcore::UserTrackInformation::get(track);
    // make sure A' is persisted into output file
    userInfo->setSaveFlag(true);
    if (track->GetParticleDefinition() == G4APrime::APrime()) {
      // check if A' was made in the desired volume and has the minimum energy
      if (not inDesiredVolume(track)) {
        AbortEvent("A' wasn't produced inside of the requested volume.");
      }  // A' was made in desired volume and has the minimum energy
    }    // track was A'
  }      // track created by dark brem process
  return;
}
References AbortEvent(), G4APrime::APrime(), simcore::UserTrackInformation::get(), inDesiredVolume(), G4DarkBremsstrahlung::PROCESS_NAME, and simcore::UserTrackInformation::setSaveFlag().
Member Data Documentation
foundAp_
bool biasing::EcalDarkBremFilter::foundAp_ private
Have we found the A' yet?
Reset to false in BeginOfEventAction
Definition at line 159 of file EcalDarkBremFilter.h.
Referenced by BeginOfEventAction(), ClassifyNewTrack(), and NewStage().
threshold_
double biasing::EcalDarkBremFilter::threshold_ private
Minimum energy [MeV] that the A' should have to keep the event.
Also used by PartialEnergySorter to determine which tracks should be processed first.
Parameter Name: 'threshold'
Definition at line 147 of file EcalDarkBremFilter.h.
Referenced by ClassifyNewTrack(), and EcalDarkBremFilter().
volumes_
std::vector<G4LogicalVolume*> biasing::EcalDarkBremFilter::volumes_ private
The volumes that the filter will be applied to.
Definition at line 152 of file EcalDarkBremFilter.h.
Referenced by EcalDarkBremFilter(), and inDesiredVolume().
The documentation for this class was generated from the following files:
Biasing/include/Biasing/EcalDarkBremFilter.h
Biasing/src/Biasing/EcalDarkBremFilter.cxx