LDMX Software: ldmx::EcalAbstractID Class Reference
ldmx::EcalAbstractID Class Reference
Parent of precision and trigger EcalIDs.
#include <EcalAbstractID.h>
Public Types
enum EcalCellType { PrecisionGlobal = 0 , PrecisionLocal = 1 , TriggerCell = 2 , Special = 7 }
Public Types inherited from ldmx::DetectorID
typedef uint32_t RawValue
Public Member Functions
EcalAbstractID ()
EcalAbstractID (RawValue rawid)
EcalAbstractID (const DetectorID id)
EcalAbstractID (unsigned int cell_type, unsigned int payload)
int cell_type () const
int payload () const
Public Member Functions inherited from ldmx::DetectorID
DetectorID ()
Class constructor for a null DetectorID.
DetectorID (RawValue rawid)
Class constructor from a raw 32-bit integer.
DetectorID (SubdetectorIDType sdtype, RawValue raw_subpayload)
bool null () const
SubdetectorIDType subdet () const
RawValue raw () const
void setRawValue (RawValue rawValue)
bool operator< (const DetectorID &id) const
bool operator== (const DetectorID &id) const
bool operator!= (const DetectorID &id) const
Static Public Attributes
static const RawValue CELL_TYPE_MASK
static const RawValue CELL_TYPE_SHIFT {23}
static const RawValue ECAL_PAYLOAD_MASK {0x007FFFFF}
Static Public Attributes inherited from ldmx::DetectorID
static const RawValue SUBDETECTORID_MASK {0x3F}
static const RawValue SUBDETECTORID_SHIFT {26}
static const RawValue SUBDETECTOR_PAYLOAD_MASK {0x3FFFFFF}
Additional Inherited Members
Protected Attributes inherited from ldmx::DetectorID
RawValue id_
The raw, packed value of the ID.
Detailed Description
Parent of precision and trigger EcalIDs.
Definition at line 19 of file EcalAbstractID.h.
Member Enumeration Documentation
EcalCellType
enum ldmx::EcalAbstractID::EcalCellType
Definition at line 21 of file EcalAbstractID.h.
                    {
    PrecisionGlobal = 0,  // full-granularity cells, transformed to a uniform
                          // grid not alternating by layer
    PrecisionLocal = 1,   // full-granularity cells, labelled by their local
                          // coordinatate system as from DAQ
    TriggerCell = 2,      // trigger cells
    Special = 7           // common-mode, calibration cells, etc
  };
Constructor & Destructor Documentation
EcalAbstractID() [1/4]
ldmx::EcalAbstractID::EcalAbstractID () inline
Empty ECAL id (but not null!)
Definition at line 38 of file EcalAbstractID.h.
: DetectorID(SD_ECAL, 0) {}
EcalAbstractID() [2/4]
ldmx::EcalAbstractID::EcalAbstractID (RawValue rawid) inline
Create from raw number
Definition at line 43 of file EcalAbstractID.h.
                                 : DetectorID(rawid) {
    SUBDETECTORID_TEST("EcalAbstractID", SD_ECAL);
  }
EcalAbstractID() [3/4]
ldmx::EcalAbstractID::EcalAbstractID (const DetectorID id) inline
Create from a DetectorID, but check
Definition at line 50 of file EcalAbstractID.h.
                                      : DetectorID(id) {
    SUBDETECTORID_TEST("EcalAbstractID", SD_ECAL);
  }
EcalAbstractID() [4/4]
ldmx::EcalAbstractID::EcalAbstractID (unsigned int cell_type, unsigned int payload) inline
Create from pieces
Definition at line 57 of file EcalAbstractID.h.
      : DetectorID(SD_ECAL, 0) {
    id_ |= (cell_type & CELL_TYPE_MASK) << CELL_TYPE_SHIFT;
    id_ |= (payload & ECAL_PAYLOAD_MASK);
  }
References cell_type(), ldmx::DetectorID::id_, and payload().
Member Function Documentation
cell_type()
int ldmx::EcalAbstractID::cell_type () const inline
Get the value of the cell field from the ID.
Returns
The value of the cell field.
Definition at line 67 of file EcalAbstractID.h.
{ return (id_ >> CELL_TYPE_SHIFT) & CELL_TYPE_MASK; }
References ldmx::DetectorID::id_.
Referenced by EcalAbstractID(), ldmx::EcalID::EcalID(), and ldmx::EcalTriggerID::EcalTriggerID().
payload()
int ldmx::EcalAbstractID::payload () const inline
Get the value of the payload field from the ID.
Returns
The value of the payload field.
Definition at line 73 of file EcalAbstractID.h.
{ return id_ & ECAL_PAYLOAD_MASK; }
References ldmx::DetectorID::id_.
Referenced by EcalAbstractID().
Member Data Documentation
CELL_TYPE_MASK
const RawValue ldmx::EcalAbstractID::CELL_TYPE_MASK static
Initial value:
{
      0x7}
Definition at line 30 of file EcalAbstractID.h.
CELL_TYPE_SHIFT
const RawValue ldmx::EcalAbstractID::CELL_TYPE_SHIFT {23} static
Definition at line 32 of file EcalAbstractID.h.
ECAL_PAYLOAD_MASK
const RawValue ldmx::EcalAbstractID::ECAL_PAYLOAD_MASK {0x007FFFFF} static
Definition at line 33 of file EcalAbstractID.h.
The documentation for this class was generated from the following file:
DetDescr/include/DetDescr/EcalAbstractID.h