LDMX Software: ldmx::NtupleManager Class Reference
ldmx::NtupleManager Class Reference
Singleton class used to manage the creation and pooling of ntuples.
#include <NtupleManager.h>
Public Member Functions
void create (const std::string &tname)
template<typename T >
void addVar (const std::string &tname, const std::string &vname)
template<typename T >
void setVar (const std::string &vname, const T value)
void fill ()
void clear ()
Reset all of the variables to their limits.
Static Public Member Functions
static NtupleManager * getInstance ()
Private Member Functions
NtupleManager ()
Private constructor to prevent instantiation.
Private Attributes
std::unordered_map< std::string, TTree * > trees_
Container for ROOT trees.
std::unordered_map< std::string, vtype > variables_
Container for tree leaves.
const std::map< const char *, std::string, cmpStr > rtype_
Map from variable type to string representation used by ROOT.
Static Private Attributes
static NtupleManager * instance_ = nullptr
NtupleManager instance.
Detailed Description
Singleton class used to manage the creation and pooling of ntuples.
Definition at line 45 of file NtupleManager.h.
Member Function Documentation
addVar()
template<typename T > void ldmx::NtupleManager::addVar (const std::string & tname, const std::string & vname) inline
Add a variable of type T to the ROOT tree with name 'tname'.
If the variable already exists in any tree or the requested tree does not exists, an exception is thrown.
Parameters
tname Name of the tree to add the variable to.
vname Name of the variable to add to the tree
Exceptions
exception
Definition at line 69 of file NtupleManager.h.
{
                 // Check if the variable exists in the map. If it does, throw
                 // an exception.
                 if (variables_.count(vname) != 0) {
                     EXCEPTION_RAISE(
                             "NtupleManager",
                             "A variable with name " + vname + " has already been defined.");
                 }
                 // Check if a tree named 'tname' has already been created.  If
                 // not, throw an exception.
                 if (trees_.count(tname) == 0)
                     EXCEPTION_RAISE(
                         "NtupleManager",
                         "A tree with name " + tname + " has already been created."
                     );
                 // Initialize the variable to the minimum limit of that type.
                 variables_[vname] = T(std::numeric_limits<T>::min());
                 // Get the type name
                 auto typeName = typeid(boost::get<T>(variables_[vname])).name();
                 // Add the variable to the ROOT tree
                 trees_[tname]->Branch(vname.c_str(), &boost::get<T>(variables_[vname]),
                         (vname + "/" + rtype_.at(typeName)).c_str());
             }
References EXCEPTION_RAISE, rtype_, trees_, and variables_.
Referenced by ldmx::DummyAnalyzer::onProcessStart().
create()
void ldmx::NtupleManager::create (const std::string & tname)
Create a ROOT tree to hold the ntuple variables (ROOT leaves).
Parameters
name Name of the tree.
Definition at line 18 of file NtupleManager.cxx.
{
         // Check if a tree named 'name' has already been created.  If so
         // throw an exception.
         if (trees_.count(name) != 0)
             EXCEPTION_RAISE(
                     "NtupleManager",
                     "A tree with name " + name + " has already been created."
             );
         // Create a tree with the given name and add it to the list of trees.
         auto tree{new TTree{name.c_str(), name.c_str()}};
         trees_[name] = tree;
     }
References EXCEPTION_RAISE, and trees_.
Referenced by ldmx::DummyAnalyzer::onProcessStart().
getInstance()
NtupleManager * ldmx::NtupleManager::getInstance () static
Returns
The NtupleManager instance
Definition at line 10 of file NtupleManager.cxx.
{
         // Create an instance of the NtupleManager if needed
         if (!instance_) instance_ = new NtupleManager;
         return instance_;
     }
References instance_, and NtupleManager().
Referenced by ldmx::DummyAnalyzer::onProcessStart(), and ldmx::Process::run().
setVar()
template<typename T > void ldmx::NtupleManager::setVar (const std::string & vname, const T value) inline
Set the value of the variable named 'vname'. If the variable value is not set, the default value will be used when filling the tree. If the requested variable has not been created, a warning will be printed. This allows a user to choose to make a subset of an ntuple by simply not adding the variable to the tree.
Parameters
vname Name of the variable
value The value of the variable
Definition at line 110 of file NtupleManager.h.
{
                 // Check if the variable already exists in the map.  If it
                 // doesn't, warn the user and don't try to set the variable
                 // value.
                 if (variables_.count(vname) == 0) {
                     std::cout << "[ NtupleManager ]: Warning! The variable "
                               << vname << " does not exist in the tree." << std::endl;
                     return;
                 }
                 // Set the value of the variable
                 variables_[vname] = value;
             }
References variables_.
Referenced by ldmx::DummyAnalyzer::analyze().
Member Data Documentation
rtype_
const std::map< const char*, std::string, cmpStr> ldmx::NtupleManager::rtype_ private
Initial value:
=
            {
                {"s", "S"},
                {"i", "I"},
                {"f", "F"},
                {"d", "D"},
                {"l", "L"},
            }
Map from variable type to string representation used by ROOT.
Definition at line 143 of file NtupleManager.h.
Referenced by addVar().
The documentation for this class was generated from the following files:
Framework/include/Framework/NtupleManager.h
Framework/src/NtupleManager.cxx