LDMX Software: G4eDarkBremsstrahlungModel Class Reference
G4eDarkBremsstrahlungModel Class Reference
#include <G4eDarkBremsstrahlungModel.h>
Classes
struct Chi
struct DiffCross
struct OutgoingKinematics
Public Types
enum DarkBremMethod { ForwardOnly = 1, CMScaling, Undefined }
Public Member Functions
G4eDarkBremsstrahlungModel (const G4ParticleDefinition *p=0, const G4String &theName="eDBrem")
virtual ~G4eDarkBremsstrahlungModel ()
virtual void Initialise (const G4ParticleDefinition *p, const G4DataVector &cuts)
virtual void SampleSecondaries (std::vector< G4DynamicParticle * > *secondaries, const G4MaterialCutsCouple *, const G4DynamicParticle *primary, G4double tmin, G4double maxEnergy)
void SetMethod (DarkBremMethod method)
void SetMadGraphDataFile (std::string file)
Protected Member Functions
const G4Element * SelectRandomAtom (const G4MaterialCutsCouple *couple)
Protected Attributes
const G4ParticleDefinition * particle_
G4ParticleChangeForLoss * fParticleChange_
Private Types
typedef std::vector< double > StateType
Private Member Functions
void SetParticle (const G4ParticleDefinition *p)
void ParseLHE (std::string fname)
void MakePlaceholders ()
G4eDarkBremsstrahlungModel::OutgoingKinematics GetMadgraphData (double E0)
virtual G4double ComputeCrossSectionPerAtom (const G4ParticleDefinition *, G4double E0, G4double Z, G4double A, G4double cut, G4double)
G4DataVector * ComputePartialSumSigma (const G4Material *material, G4double kineticEnergy, G4double cut)
G4eDarkBremsstrahlungModel & operator= (const G4eDarkBremsstrahlungModel &right)
G4eDarkBremsstrahlungModel (const G4eDarkBremsstrahlungModel &)
Private Attributes
unsigned int maxIterations_ {10000}
double MA_
double Mel_
DarkBremMethod method_ {DarkBremMethod::Undefined}
bool alwaysCreateNewElectron_ {true}
std::map< double, std::vector< OutgoingKinematics > > madGraphData_
std::map< double, unsigned int > currentDataPoints_
std::vector< G4DataVector * > partialSumSigma_
Detailed Description
Geant4 implementation of the model for a particle undergoing a dark brem.
This is where all the heavy lifting in terms of calculating cross sections and actually having an electron do a dark brem occurs.
Definition at line 25 of file G4eDarkBremsstrahlungModel.h.
Member Typedef Documentation
StateType
typedef std::vector<double> G4eDarkBremsstrahlungModel::StateType private
Helpful typedef for boost integration.
Definition at line 106 of file G4eDarkBremsstrahlungModel.h.
Member Enumeration Documentation
DarkBremMethod
enum G4eDarkBremsstrahlungModel::DarkBremMethod
Possible methods to dark brem inside of this model.
Enumerator
CMScaling
Use actual electron energy and get pT from LHE (such that pT^2+me^2 < Eacc^2)
Undefined
Boost LHE vertex momenta to the actual electron energy.
Use LHE vertex as is
Definition at line 34 of file G4eDarkBremsstrahlungModel.h.
{
             ForwardOnly = 1,
             CMScaling,
             Undefined
         };
Constructor & Destructor Documentation
G4eDarkBremsstrahlungModel() [1/2]
G4eDarkBremsstrahlungModel::G4eDarkBremsstrahlungModel (const G4ParticleDefinition * p = 0, const G4String & theName = "eDBrem")
Set the particle definition that this model will represent.
Definition at line 36 of file G4eDarkBremsstrahlungModel.cxx.
     : G4VEmModel(theName),
       particle_(nullptr),
       fParticleChange_(nullptr),
       method_(DarkBremMethod::Undefined) {
     if(p) { SetParticle(p); } //Verify that the particle is an electron.
     MA_  = G4APrime::APrime()    ->GetPDGMass()/CLHEP::GeV; //Get the A' mass in GeV
     Mel_ = G4Electron::Electron()->GetPDGMass()/CLHEP::GeV;
 }
References G4APrime::APrime(), MA_, Mel_, and SetParticle().
~G4eDarkBremsstrahlungModel()
G4eDarkBremsstrahlungModel::~G4eDarkBremsstrahlungModel () virtual
Destructor
Attempt to cleanup hanging pointers and leftover memory.
Definition at line 50 of file G4eDarkBremsstrahlungModel.cxx.
{
     for (G4DataVector *dv : partialSumSigma_ ) {
        if ( dv )  delete dv;
     }
     partialSumSigma_.clear();
     madGraphData_.clear();
     currentDataPoints_.clear();
 }
References currentDataPoints_, and madGraphData_.
G4eDarkBremsstrahlungModel() [2/2]
G4eDarkBremsstrahlungModel::G4eDarkBremsstrahlungModel (const G4eDarkBremsstrahlungModel &) private
Hide copy constructor
Member Function Documentation
ComputeCrossSectionPerAtom()
G4double G4eDarkBremsstrahlungModel::ComputeCrossSectionPerAtom (const G4ParticleDefinition * , G4double E0, G4double Z, G4double A, G4double cut, G4double) private virtual
Calculates the cross section per atom in GEANT4 internal units. Uses WW approximation to find the total cross section, performing numerical integrals over x and theta.
Non named parameters are not used.
Numerical integrals are done using boost::numeric::odeint.
Integrate Chi from to
Integrate diffcross from 0 to
Total cross section is given by
Parameters
E0 energy of beam (incoming particle)
Z atomic number of atom
A atomic mass of atom
cut minimum energy cut to calculate cross section
Returns
cross section (0. if outside energy cuts)
Definition at line 400 of file G4eDarkBremsstrahlungModel.cxx.
{
     if ( E0 < keV or E0 < cut) return 0.; //outside viable region for model
     E0 = E0 / CLHEP::GeV; //Change energy to GeV.
     if(E0 < 2.*MA_) return 0.; //can't produce a prime
     //begin: chi-formfactor calculation
     Chi chiformfactor;
     //  set parameters
     chiformfactor.A  = A;
     chiformfactor.Z  = Z;
     chiformfactor.E0 = E0;
     chiformfactor.MA = MA_;
     chiformfactor.Mel = Mel_;
     double tmin = MA_*MA_*MA_*MA_/(4.*E0*E0);
     double tmax = MA_*MA_;
     //Integrate over chi.
     StateType integral(1);
     integral[0] = 0.; //start integral value at zero
     boost::numeric::odeint::integrate (
             chiformfactor // how to calculate integrand
             , integral // integral result
             , tmin // integral lower limit
             , tmax // integral upper limit
             , (tmax - tmin)/1000 // dt - initial, adapts based off error
             );
     G4double ChiRes = integral[0];
     //Integrate over x. Can use log approximation instead, which falls off at high A' mass.
     DiffCross diffcross;
     diffcross.E0 = E0;
     diffcross.MA = MA_;
     diffcross.Mel = Mel_;
     double xmin = 0;
     double xmax = 1;
     if((Mel_/E0)>(MA_/E0)) xmax = 1-Mel_/E0;
     else xmax = 1-MA_/E0;
     //Integrate over differential cross section.
     integral[0] = 0.; //start integral value at zero
     boost::numeric::odeint::integrate (
             diffcross // how to calculate integrand
             , integral // integral result
             , xmin // integral lower limit
             , xmax // integral upper limit
             , (xmax - xmin)/1000 // dx - initial, adapts based off error
             );
     G4double DsDx = integral[0];
     G4double GeVtoPb = 3.894E08;
     G4double alphaEW = 1.0/137.0;
     G4double epsilBench = 1;
     G4double cross = GeVtoPb*4.*alphaEW*alphaEW*alphaEW*epsilBench*epsilBench*ChiRes*DsDx*CLHEP::picobarn;
     if(cross < 0.) return 0.; //safety check all the math
     return cross;
 }
References G4eDarkBremsstrahlungModel::Chi::E0, G4eDarkBremsstrahlungModel::Chi::MA, G4eDarkBremsstrahlungModel::DiffCross::MA, MA_, G4eDarkBremsstrahlungModel::Chi::Mel, G4eDarkBremsstrahlungModel::DiffCross::Mel, Mel_, and G4eDarkBremsstrahlungModel::Chi::Z.
Referenced by ComputePartialSumSigma().
ComputePartialSumSigma()
G4DataVector * G4eDarkBremsstrahlungModel::ComputePartialSumSigma (const G4Material * material, G4double kineticEnergy, G4double cut) private
Build the table of cross section per element.
The table is built for MATERIALS. This table is used by DoIt to select randomly an element in the material.
Parameters
material Material to build cross section table for
kineticEnergy kinetic energy of incoming particle
cut minimum energy cut on cross section
Returns
G4DataVector of elements to cross sections for the input material.
Definition at line 471 of file G4eDarkBremsstrahlungModel.cxx.
{
     G4int nElements = material->GetNumberOfElements();
     const G4ElementVector* theElementVector = material->GetElementVector();
     const G4double* theAtomNumDensityVector = material->GetAtomicNumDensityVector();
     G4DataVector* dv = new G4DataVector(); //stored into partialSumSigma_ and then cleaned up later
     G4double cross = 0.0;
     for (G4int i=0; i<nElements; i++ ) {
         cross += theAtomNumDensityVector[i] * ComputeCrossSectionPerAtom(
                 particle_, kineticEnergy, (*theElementVector)[i]->GetZ(), (*theElementVector)[i]->GetA(), cut, 0.
                 );
         dv->push_back(cross);
     }
     return dv;
 }
References ComputeCrossSectionPerAtom(), and particle_.
Referenced by Initialise().
GetMadgraphData()
G4eDarkBremsstrahlungModel::OutgoingKinematics G4eDarkBremsstrahlungModel::GetMadgraphData (double E0) private
Returns mad graph data given an energy [GeV].
Gets the energy fraction and Pt from the imported LHE data. E0 should be in GeV, returns the total energy and Pt in GeV. Scales from the closest imported beam energy above the given value (scales down to avoid biasing issues).
Parameters
E0 energy of particle undergoing dark brem [GeV]
Returns
total energy and transverse momentum of particle [GeV]
Definition at line 373 of file G4eDarkBremsstrahlungModel.cxx.
{
     OutgoingKinematics cmdata; //data frame to return
     //Cycle through imported beam energies until the closest one above is found, or the max is reached.
     double samplingE = 0.;
     for ( const auto &keyVal : currentDataPoints_ ) {
         samplingE = keyVal.first; //move samplingE up
         //check if went under the sampling energy
         //  the map is sorted by key, so we can be done right after E0 goes under samplingE
         if ( E0 < samplingE ) break;
     }
     //now samplingE is the closest energy above E0 or the maximum energy imported from mad graph
     //Need to loop around if we hit the end, when the size of madGraphData_[samplingE] is smaller than
     //  the number of events we want
     if(currentDataPoints_.at(samplingE)>=madGraphData_.at(samplingE).size()) {currentDataPoints_[samplingE] = 0;}
     //Get the lorentz vectors from the index given by the placeholder.
     cmdata = madGraphData_.at(samplingE).at(currentDataPoints_.at(samplingE));
     //Increment the current index
     currentDataPoints_[samplingE]++;
     return cmdata;
 }
References currentDataPoints_, and madGraphData_.
Referenced by SampleSecondaries().
Initialise()
void G4eDarkBremsstrahlungModel::Initialise (const G4ParticleDefinition * p, const G4DataVector & cuts) virtual
Set the cuts using the particle definition and comput the partial sum sigma.
Definition at line 59 of file G4eDarkBremsstrahlungModel.cxx.
{
     if(p) { SetParticle(p); }
     G4double highKinEnergy = this->HighEnergyLimit();
     const G4ProductionCutsTable* theCoupleTable = G4ProductionCutsTable::GetProductionCutsTable();
     if(theCoupleTable) {
         G4int numOfCouples = theCoupleTable->GetTableSize();
         G4int nn = partialSumSigma_.size();
         G4int nc = cuts.size();
         if(nn > 0) {
             //reset partialSumSigma
             for (G4DataVector *dv : partialSumSigma_ ) {
                 if ( dv )  delete dv;
             }
             partialSumSigma_.clear();
         }
         for (G4int i=0; i<numOfCouples; i++) {
             G4double cute   = DBL_MAX;
             if(i < nc) cute = cuts[i];
             const G4MaterialCutsCouple* couple = theCoupleTable->GetMaterialCutsCouple(i);
             const G4Material* material = couple->GetMaterial();
             G4DataVector* dv = ComputePartialSumSigma(material, 0.5*highKinEnergy,std::min(cute, 0.25*highKinEnergy));
             partialSumSigma_.push_back(dv);
         }
     }
     if(not fParticleChange_) fParticleChange_ = GetParticleChangeForLoss();
 }
References ComputePartialSumSigma(), fParticleChange_, and SetParticle().
MakePlaceholders()
void G4eDarkBremsstrahlungModel::MakePlaceholders () private
Fill vector of energies with the same number of items as the madgraph data.
Definition at line 364 of file G4eDarkBremsstrahlungModel.cxx.
{
     currentDataPoints_.clear();
     maxIterations_ = 10000;
     for ( const auto &iter : madGraphData_ ) {
         currentDataPoints_[iter.first] = int(G4UniformRand()*iter.second.size());
         if ( iter.second.size() < maxIterations_ ) maxIterations_ = iter.second.size();
     }
 }
References currentDataPoints_, madGraphData_, and maxIterations_.
Referenced by SetMadGraphDataFile().
operator=()
G4eDarkBremsstrahlungModel& G4eDarkBremsstrahlungModel::operator= (const G4eDarkBremsstrahlungModel & right) private
Hide assignment operator
SampleSecondaries()
void G4eDarkBremsstrahlungModel::SampleSecondaries (std::vector< G4DynamicParticle * > * secondaries, const G4MaterialCutsCouple * , const G4DynamicParticle * primary, G4double tmin, G4double maxEnergy) virtual
Simulates the emission of a dark photon + electron.
Gets an energy fraction and Pt from madgraph files. Scales the energy so that the fraction of kinectic energy is constant, keeps the Pt constant. If the Pt is larger than the new energy, that event is skipped, and a new one is taken from the file.
Deactivates the dark brem, ensuring only one dark brem per step and per event. Needs to be reactived in the end of event action.
Parameters
secondaries vector of primary particle's offspring
primary particle that could go dark brem
tmin minimum energy possible for sampling
maxEnergy maximum energy possible for sampling
Definition at line 90 of file G4eDarkBremsstrahlungModel.cxx.
{
     //Deactivate the process after one dark brem. Needs to be reactivated in the end of event action.
     //If this is in the stepping action instead, more than one brem can occur within each step.
     G4bool state = false;
     G4String pname = "biasWrapper(eDBrem)";
     G4ProcessTable* ptable = G4ProcessTable::GetProcessTable();
     ptable->SetProcessActivation(pname,state);
     if ( G4RunManager::GetRunManager()->GetVerboseLevel() > 1 ) {
         std::cout << "[ G4eDarkBremsstrahlungModel ] : A dark brem occurred!" << std::endl;
     }
     G4double E0 = primary->GetTotalEnergy();
     G4double tmax = std::min(maxEnergy, E0);
     if(tmin >= tmax) { return; } // limits of the energy sampling
     E0 = E0 / CLHEP::GeV; //Convert the energy to GeV, the units used in the LHE files.
     OutgoingKinematics data = GetMadgraphData(E0);
     double EAcc   = (data.electron.E()-Mel_)/(data.E-Mel_-MA_)*(E0-Mel_-MA_);
     double Pt     = data.electron.Pt();
     double P      = sqrt(EAcc*EAcc-Mel_*Mel_);
     double PhiAcc = data.electron.Phi();
     if ( method_ == DarkBremMethod::ForwardOnly ) {
         unsigned int i = 0;
         while(Pt*Pt+Mel_*Mel_>EAcc*EAcc) {
             //Skip events until the Pt is less than the energy.
             i++;
             data = GetMadgraphData(E0);
             EAcc = (data.electron.E()-Mel_)/(data.E-Mel_-MA_)*(E0-Mel_-MA_);
             Pt = data.electron.Pt();
             P = sqrt(EAcc*EAcc-Mel_*Mel_);
             PhiAcc = data.electron.Phi();
             if(i > maxIterations_) {
                 std::cout << "[ G4eDarkBremsstrahlungModel ] : "
                     << "Did not manage to simulate with E0 = " << E0
                     << " and EAcc = " << EAcc << std::endl;
                 break;
             }
         }
     } else if( method_ == DarkBremMethod::CMScaling ) {
         TLorentzVector el(data.electron.X(),data.electron.Y(),data.electron.Z(),data.electron.E());
         double ediff = data.E-E0;
         TLorentzVector newcm(
                 data.centerMomentum.X(),data.centerMomentum.Y()
                 ,data.centerMomentum.Z()-ediff,data.centerMomentum.E()-ediff);
         el.Boost(-1.*data.centerMomentum.BoostVector());
         el.Boost(newcm.BoostVector());
         double newE = (data.electron.E()-Mel_)/(data.E-Mel_-MA_)*(E0-Mel_-MA_);
         el.SetE(newE);
         EAcc = el.E();
         Pt = el.Pt();
         P = el.P();
     } else if ( method_ == DarkBremMethod::Undefined ) {
         EAcc = E0;
         P = primary->GetTotalMomentum();
         Pt = sqrt(primary->Get4Momentum().px()*primary->Get4Momentum().px()+primary->Get4Momentum().py()*primary->Get4Momentum().py());
     } else {
         EXCEPTION_RAISE(
                 "InvalidMethod",
                 "Invallid dark brem simulation method " + std::to_string(method_) + "."
                 );
     }
     EAcc = EAcc*CLHEP::GeV; //Change the energy back to MeV, the internal GEANT unit.
     G4double momentum = sqrt(EAcc*EAcc-electron_mass_c2*electron_mass_c2); //Electron momentum in MeV.
     G4ThreeVector newDirection;
     double ThetaAcc = std::asin(Pt/P);
     newDirection.set(std::sin(ThetaAcc)*std::cos(PhiAcc),std::sin(ThetaAcc)*std::sin(PhiAcc), std::cos(ThetaAcc));
     newDirection.rotateUz(primary->GetMomentumDirection());
     newDirection.setMag(momentum);
     // create g4dynamicparticle object for the dark photon.
     G4ThreeVector direction = (primary->GetMomentum()- newDirection);
     G4DynamicParticle* dphoton = new G4DynamicParticle(G4APrime::APrime(),direction);
     secondaries->push_back(dphoton);
     // energy of primary
     G4double finalKE = EAcc - electron_mass_c2;
     // stop tracking and create new secondary instead of primary
     if(alwaysCreateNewElectron_ or finalKE < SecondaryThreshold()) {
         fParticleChange_->ProposeTrackStatus(fStopAndKill);
         fParticleChange_->SetProposedKineticEnergy(0.0);
         G4DynamicParticle* el = new G4DynamicParticle(const_cast<G4ParticleDefinition*>(particle_),
                                     newDirection.unit(), finalKE);
         secondaries->push_back(el);
         // continue tracking
     } else {
         // just have primary lose energy (don't rename to different track ID)
         fParticleChange_->SetProposedMomentumDirection(newDirection.unit());
         fParticleChange_->SetProposedKineticEnergy(finalKE);
     }
 }
References alwaysCreateNewElectron_, G4APrime::APrime(), G4eDarkBremsstrahlungModel::OutgoingKinematics::centerMomentum, G4eDarkBremsstrahlungModel::OutgoingKinematics::E, EXCEPTION_RAISE, fParticleChange_, GetMadgraphData(), MA_, maxIterations_, Mel_, method_, and particle_.
SelectRandomAtom()
const G4Element * G4eDarkBremsstrahlungModel::SelectRandomAtom (const G4MaterialCutsCouple * couple) protected
Selects random element out of the material information given.
Uses weights for materials calculated before and stored in partialSumSigma
Parameters
couple G4 package containing material and other relevant information
Returns
the chosen G4Element
Definition at line 229 of file G4eDarkBremsstrahlungModel.cxx.
{
     // select randomly 1 element within the material
     const G4Material* material = couple->GetMaterial();
     G4int nElements = material->GetNumberOfElements();
     const G4ElementVector* theElementVector = material->GetElementVector();
     const G4Element* elm = 0;
     if(1 < nElements) {
         --nElements;
         G4DataVector* dv = partialSumSigma_.at(couple->GetIndex());
         G4double rval = G4UniformRand()*((*dv)[nElements]);
         elm = (*theElementVector)[nElements];
         for (G4int i=0; i<nElements; ++i) {
             if (rval <= (*dv)[i]) {
                 elm = (*theElementVector)[i];
                 break;
             }
         }
     } else {
         elm = (*theElementVector)[0];
     }
     SetCurrentElement(elm);
     return elm;
 }
SetMadGraphDataFile()
void G4eDarkBremsstrahlungModel::SetMadGraphDataFile (std::string file)
Set the data file for the dark brem events to be scaled.
Parameters
file path to LHE file
Definition at line 196 of file G4eDarkBremsstrahlungModel.cxx.
{
     //TODO do we need to read all LHE files in a directory? Can it just be one LHE file?
     //Read all of the lhe files in the Resources/ directory. Assumes that they
     //are of the correct mass, need to implement method of separating masses
     //(either filenames, or skipping events with incorrect masses).
 //    DIR *dir;
 //    dir = opendir("Resources/");
 //    struct dirent *directory;
 //    if(dir) {
 //        while((directory = readdir(dir)) != NULL) {
 //            std::string fname = "Resources/" + std::string(directory->d_name);
 //            //Parse files that end in ".lhe"
 //            if(fname.substr(fname.find_last_of(".")+1) == "lhe") {ParseLHE(fname);}
 //        }
 //    }
     if( file.substr(file.find_last_of(".")+1) == "lhe" ) {
         //is an lhe file
         ParseLHE(file);
     } else {
         EXCEPTION_RAISE(
                 "LHEFile",
                 "The passed file path '" + file
                 + "' does not end with 'lhe', so we are assuming it is not an LHE file."
                 );
     }
     MakePlaceholders(); //Setup the placeholder offsets for getting data.
     return;
 }
References EXCEPTION_RAISE, and MakePlaceholders().
SetMethod()
void G4eDarkBremsstrahlungModel::SetMethod (DarkBremMethod method)
Set the method for the dark brem simulation
Definition at line 191 of file G4eDarkBremsstrahlungModel.cxx.
{
     method_ = method;
     return;
 }
References method_.
SetParticle()
void G4eDarkBremsstrahlungModel::SetParticle (const G4ParticleDefinition * p) private
Sets the particle being looked at and checks whether it is an electron or not.
Definition at line 291 of file G4eDarkBremsstrahlungModel.cxx.
{
     if (p != G4Electron::Electron()) {
         EXCEPTION_RAISE(
                 "InvalidParticle",
                 "The particle passed to G4eDarkBremsstrahlungModel '"
                 + p->GetParticleName() + "' is not an electron."
                 );
     }
     particle_ = p;
 }
References EXCEPTION_RAISE, and particle_.
Referenced by G4eDarkBremsstrahlungModel(), and Initialise().
Member Data Documentation
alwaysCreateNewElectron_
bool G4eDarkBremsstrahlungModel::alwaysCreateNewElectron_ {true} private
should we always create a totally new electron when we dark brem?
TODO make this configurable? I (Tom E) can't think of a reason NOT to have it...
Definition at line 289 of file G4eDarkBremsstrahlungModel.h.
Referenced by SampleSecondaries().
currentDataPoints_
std::map< double , unsigned int > G4eDarkBremsstrahlungModel::currentDataPoints_ private
Stores a map of current access points to mad graph data.
Maps incoming electron energy to the index of the data vector that we will get the data from.
Also sorts the incoming electron energy so that we can find the sampling energy that is closest above the actual incoming energy.
Definition at line 307 of file G4eDarkBremsstrahlungModel.h.
Referenced by GetMadgraphData(), MakePlaceholders(), and ~G4eDarkBremsstrahlungModel().
fParticleChange_
G4ParticleChangeForLoss* G4eDarkBremsstrahlungModel::fParticleChange_ protected
loss in particle energy
Definition at line 268 of file G4eDarkBremsstrahlungModel.h.
Referenced by Initialise(), and SampleSecondaries().
MA_
double G4eDarkBremsstrahlungModel::MA_ private
mass of the A Prime [GeV]
Definition at line 276 of file G4eDarkBremsstrahlungModel.h.
Referenced by ComputeCrossSectionPerAtom(), G4eDarkBremsstrahlungModel(), and SampleSecondaries().
madGraphData_
std::map< double , std::vector < OutgoingKinematics > > G4eDarkBremsstrahlungModel::madGraphData_ private
Storage of data from mad graph
Maps incoming electron energy to various options for outgoing kinematics.
Definition at line 296 of file G4eDarkBremsstrahlungModel.h.
Referenced by GetMadgraphData(), MakePlaceholders(), and ~G4eDarkBremsstrahlungModel().
maxIterations_
unsigned int G4eDarkBremsstrahlungModel::maxIterations_ {10000} private
maximum number of iterations to check before giving up on an event
Definition at line 273 of file G4eDarkBremsstrahlungModel.h.
Referenced by MakePlaceholders(), and SampleSecondaries().
Mel_
double G4eDarkBremsstrahlungModel::Mel_ private
mass of an electron [GeV]
Definition at line 279 of file G4eDarkBremsstrahlungModel.h.
Referenced by ComputeCrossSectionPerAtom(), G4eDarkBremsstrahlungModel(), and SampleSecondaries().
method_
DarkBremMethod G4eDarkBremsstrahlungModel::method_ {DarkBremMethod::Undefined} private
method for this model
Definition at line 282 of file G4eDarkBremsstrahlungModel.h.
Referenced by SampleSecondaries(), and SetMethod().
particle_
const G4ParticleDefinition* G4eDarkBremsstrahlungModel::particle_ protected
definition of particle
Definition at line 265 of file G4eDarkBremsstrahlungModel.h.
Referenced by ComputePartialSumSigma(), SampleSecondaries(), and SetParticle().
The documentation for this class was generated from the following files:
SimApplication/include/SimApplication/G4eDarkBremsstrahlungModel.h
SimApplication/src/G4eDarkBremsstrahlungModel.cxx