LDMX Software: ldmx::EventFile Class Reference
ldmx::EventFile Class Reference
Manages a file of events.
#include <EventFile.h>
Public Member Functions
EventFile (const std::string &filename, EventFile *parent, bool isOutputFile, bool isSingleOutput, int compressionSetting)
EventFile (const std::string &fileName)
EventFile (const std::string &fileName, int compressionSetting)
EventFile (const std::string &fileName, EventFile *parent, bool isSingleOutput=false, int compressionSetting=9)
~EventFile ()=default
void addDrop (const std::string &rule)
void setupEvent (Event *evt)
void updateParent (EventFile *parent)
Event * getEvent ()
bool nextEvent (bool storeCurrentEvent=true)
void close ()
void writeRunHeader (RunHeader &runHeader)
RunHeader & getRunHeader (int runNumber)
const std::string & getFileName ()
Private Member Functions
void importRunHeaders ()
Private Attributes
Long64_t entries_ {-1}
Long64_t ientry_ {-1}
std::string fileName_
bool isOutputFile_
bool isSingleOutput_
TFile * file_ {nullptr}
TTree * tree_ {nullptr}
EventFile * parent_ {nullptr}
Event * event_ {nullptr}
std::vector< std::pair< std::string, bool > > preCloneRules_
std::vector< std::string > reactivateRules_
std::map< int, std::pair< bool, RunHeader * > > runMap_
Detailed Description
Manages a file of events.
Definition at line 30 of file EventFile.h.
Constructor & Destructor Documentation
EventFile() [1/4]
ldmx::EventFile::EventFile (const std::string & filename, EventFile * parent, bool isOutputFile, bool isSingleOutput, int compressionSetting)
Constructor to make a general file.
This is not used directly, but it is called in the more specialised constructors. This method is mainly focused on reducing code copying.
Parameters
[in] filename the name of the file to read/write
[in] parent a pointer to the parent file to copy
[in] isOutputFile true if this file is written out
[in] isSingleOutput true if only one output file is being written to
[in] compressionSetting the compression setting for the TFile (100*algo+level)
Definition at line 14 of file EventFile.cxx.
                                                                                                                                      :
                 fileName_(filename), parent_(parent), isOutputFile_(isOutputFile), isSingleOutput_(isSingleOutput) {
         if (isOutputFile_) {
             //we are writting out so open the file and make sure it is writable
             file_ = new TFile(fileName_.c_str(), "RECREATE");
             if (!file_->IsOpen() or !file_->IsWritable()) {
                 EXCEPTION_RAISE("FileError", "Output file '" + fileName_ + "' is not writable.");
             }
             //set compression settings
             //  Check out the TFile constructor for explanation of how this integer is built
             //  Short Reference: setting = 100*algorithem + level
             //  algorithm = 0 ==> use global default
             file_->SetCompressionSettings(compressionSetting);
             if( parent_ ) {
                 //output file when there are input files
                 //  might be drop/keep rules, so we should have these rules to make sure it works
                 //turn everything on
                 //  hypothetically could turn everything off? Doesn't work for some reason?
                 preCloneRules_.emplace_back( "*" , true );
                 //except EventHeader (copies over to output)
                 preCloneRules_.emplace_back( "EventHeader*" , true );
                 //reactivate all branches so default behavior is drop
                 reactivateRules_.push_back( "*" );
             }
         } else {
             //open file with only reading enabled
             file_ = new TFile(fileName_.c_str());
             //double check that file is open
             if (!file_->IsOpen()) {
                 EXCEPTION_RAISE("FileError", "Input file '" + fileName_ + "' is not readable or does not exist.");
             }
             tree_ = (TTree*) (file_->Get( EventConstants::EVENT_TREE_NAME.c_str() ));
             if (!tree_) {
                 EXCEPTION_RAISE("FileError" ,
                         "File '" + fileName_ + "' does not have a TTree named '"
                         + EventConstants::EVENT_TREE_NAME + "' in it." );
             }
             entries_ = tree_->GetEntriesFast();
         }
         importRunHeaders();
     }
References entries_, ldmx::EventConstants::EVENT_TREE_NAME, file_, fileName_, importRunHeaders(), isOutputFile_, parent_, preCloneRules_, reactivateRules_, and tree_.
EventFile() [2/4]
ldmx::EventFile::EventFile (const std::string & fileName)
Class constructor to make a file to read in an event root file.
This is used for all input files.
Parameters
fileName The file name.
Definition at line 65 of file EventFile.cxx.
                                                   :
         EventFile(filename,nullptr,false,false,-1) { }
EventFile() [3/4]
ldmx::EventFile::EventFile (const std::string & fileName, int compressionSetting)
Constructor to make an output file that has no parent input file.
This is for an output file in Production Mode.
isSingleOutput is set to true. This may or may not be necessary, but it is the single output in Production Mode, so it is a good default.
Parameters
fileName The file name.
compressionSetting the compression setting for the TFile (100*algo+level)
Definition at line 68 of file EventFile.cxx.
                                                                           :
         EventFile(filename,nullptr,true,true,compressionSetting) { }
EventFile() [4/4]
ldmx::EventFile::EventFile (const std::string & fileName, EventFile * parent, bool isSingleOutput = false, int compressionSetting = 9)
Class constructor for cloning data from a "parent" file.
This is used for output files when there is an input file. (OR for files with a parent EventFile to clone)
Parameters
fileName The file name.
parent Parent file for cloning data tree.
isSingleOutput boolean check if only one output file is being written to
compressionSetting the compression setting for the TFile (100*algo+level)
Definition at line 71 of file EventFile.cxx.
                                                                                                                   :
         EventFile(filename,parent,true,isSingleOutput,compressionSetting) { }
~EventFile()
ldmx::EventFile::~EventFile () default
Class destructor.
Member Function Documentation
addDrop()
void ldmx::EventFile::addDrop (const std::string & rule)
Add a rule for dropping collections from the output.
This needs to be called after setupEvent. This method uses the event to help drop collections.
The rules should be of the following form: <drop,keep, or ignore> exp where exp is an expression that matches the collectionName. ignore ==> any branch with name matching exp is not even read in from the input file (if it exists) keep ==> any branch with name matching exp is read in from the input (if exists) and written to output (if exists) drop ==> any branch with name matching exp is read in from the input (if exists) and NOT written to output
The default behavior for all branches is keep.
ROOT uses the internal TRegexp to match branch names to the passed expression and set the status of the branch (whether it will be read or not). This internal object has different rules than real regular expressions, so it is best to keep it safe and only use asterisks or full names. Additionally, the rules you pass are analyzed in succession, so you can go from something more general to something more specific.
For example to drop all EcalSimHits.* drop EcalSimHits.*
or drop scoring plane collections drop .*ScoringPlane.*
or drop scoring plane collections but keep EcalScoringPlane collection drop .*ScoringPlane.* keep EcalScoringPlane.*
Note
The Event::getImpl overrides any ignore rules for the input file in order to avoid any seg faults. The items accessed will still be dropped.
Parameters
rule The rule for dropping collections.
Definition at line 74 of file EventFile.cxx.
{
         int offset;
         bool isKeep=false,isDrop=false,isIgnore=false;
         size_t i = rule.find("keep");
         if( i != std::string::npos ){
             offset = i+4 ;
             isKeep = true;
         }
         i = rule.find("drop");
         if( i != std::string::npos ){
             offset = i+4 ;
             isDrop = true;
         }
         i = rule.find("ignore");
         if( i != std::string::npos ){
             offset = i+6 ;
             isIgnore = true;
         }
         //more than one of (keep,drop,ignore) was provided => not valid rule
         if( int(isKeep) + int(isDrop) + int(isIgnore) != 1 ) return;
         std::string srule = rule.substr(offset);
         for (i = srule.find_first_of(" \t\n\r"); i != std::string::npos; i = srule.find_first_of(" \t\n\r"))
             srule.erase(i, 1);
         //name of branch is not given
         if (srule.length() == 0) return;
         //add wild card at end for matching purposes
         if (srule.back() != '*') srule += ".*"; //add wildcard to back
         if( isKeep ) {
             //turn both the input and output tree's on
             //root needs . removed otherwise it gets cranky
             srule.erase( std::remove( srule.begin(), srule.end(), '.' ) , srule.end() );
             preCloneRules_.emplace_back( srule , true );
             //this branch will then be copied over into output tree and be active
         } else if( isIgnore ) {
             //don't even read it from the input file
             //root needs . removed otherwise it gets cranky
             srule.erase( std::remove( srule.begin(), srule.end(), '.' ) , srule.end() );
             preCloneRules_.emplace_back( srule , false );
             //these branches won't be copied over into output tree
         } else if ( isDrop ) {
             //drop means allowing it on reading but not writing
             // pass these regex to event bus so Event::add knows
             event_->addDrop( srule ); //requires event_ to be set
             //root needs . removed otherwise it gets cranky
             srule.erase( std::remove( srule.begin(), srule.end(), '.' ) , srule.end() );
             preCloneRules_.emplace_back( srule , false );
             //these branches won't be copied over into output tree
             //reactivate input branch after clone
             reactivateRules_.push_back( srule );
         }
     }
References ldmx::Event::addDrop(), event_, preCloneRules_, and reactivateRules_.
Referenced by ldmx::Process::run().
close()
void ldmx::EventFile::close ()
Close the file, writing the tree to disk if creating an output file.
Deletes any RunHeaders that this instance of EventFile owns.
Exceptions
Exception if run tree already exists in output file.
Definition at line 259 of file EventFile.cxx.
{
         //MEMORY 'Conditional jump or move depends on uninitialised values' when closing TFile and/or writing TTree
         //  TFile::Close --> TDirectoryFile::Close --> ~TTree
         //MEMORY 'Syscall param write(buf) points to uninitialised byte(s)'
         //  when writing TTree below
         //  From filling TTree in nextEvent
         // Before an output file, the Event tree needs to be written.
         if (isOutputFile_) {
             tree_->Write();
             //store the run map into the output tree
             // Check for the existence of the run tree in the file.
             // If it already exists, throw an exception.
             // TODO: Tree name shouldn't be hardcoded. Is this check really necessary?
             auto runTree{static_cast<TTree*>(file_->Get("LDMX_Run"))};
             if (runTree) {
                 EXCEPTION_RAISE(
                         "RunTree",
                         "RunTree 'LDMX_Run' already exists in output file '" + fileName_ + "'."
                         );
             }
             runTree = new TTree("LDMX_Run", "LDMX run header");
             //create the branch on this tree
             RunHeader *theHandle = nullptr;
             runTree->Branch("RunHeader", EventConstants::RUN_HEADER.c_str(), &theHandle, 32000, 3);
             //copy over the run headers into the tree
             for( auto& [ num , header_pair ] : runMap_ ) {
                 theHandle = header_pair.second;
                 runTree->Fill();
                 if (header_pair.first) delete header_pair.second;
             }
             runTree->Write();
         }
         // Close the file
         file_->Close();
     }
References file_, fileName_, isOutputFile_, runMap_, and tree_.
Referenced by ldmx::Process::run().
getEvent()
Event* ldmx::EventFile::getEvent () inline
Get the Event object containing the event data.
Returns
The Event object containing event data.
Definition at line 145 of file EventFile.h.
 { return event_; };
References event_.
getRunHeader()
RunHeader & ldmx::EventFile::getRunHeader (int runNumber)
Get the RunHeader for a given run, if it exists in the input file.
Parameters
runNumber The run number.
Returns
The RunHeader from the input file.
Exceptions
Exception if there is no RunHeader in the map with the given run number.
Definition at line 317 of file EventFile.cxx.
{
         if (runMap_.find(runNumber) != runMap_.end()) {
             return *(runMap_.at(runNumber).second);
         } else {
             EXCEPTION_RAISE("DataError", "No run header exists for " + std::to_string(runNumber) + " in the run map.");
         }
     }
References runMap_.
Referenced by ldmx::Process::run(), and ldmx::RootPersistencyManager::Store().
importRunHeaders()
void ldmx::EventFile::importRunHeaders () private
Fill the internal map of run numbers to RunHeader objects from the input file.
If this file is an output file and parent_ and parent_->file_ are valid pointers, then the run headers are imported from parent_->file_.
Otherwise, we try to import run headers from file_.
Does not check if any run headers are getting overwritten!
Any RunHeaders read in from this function are owned by this instance of EventFile and are deleted in close().
Note
This function does nothing if parent_->file_ and file_ are nullptrs.
Definition at line 325 of file EventFile.cxx.
{
         //choose which file to import from
         auto theImportFile{file_}; //if this is an input file
         if ( isOutputFile_ and parent_ and parent_->file_ )
             theImportFile = parent_->file_; //output file with input parent to read from
         else if ( isOutputFile_ )
             return; //output file, no input parent to read from
         if (theImportFile) {
             //the file exist
             TTreeReader oldRunTree( "LDMX_Run" , theImportFile );
             TTreeReaderValue<RunHeader> oldRunHeader( oldRunTree , "RunHeader" );
             //TODO check that setup went correctly
             while( oldRunTree.Next() ) {
                 //copy input run tree into run map
                 runMap_[ oldRunHeader->getRunNumber() ] = std::make_pair(true,new RunHeader(*oldRunHeader));
             }
         }
         return;
     }
References file_, isOutputFile_, parent_, and runMap_.
Referenced by EventFile(), and updateParent().
nextEvent()
bool ldmx::EventFile::nextEvent (bool storeCurrentEvent = true)
Prepare the next event.
Returns
If event was prepared/read successfully.
Definition at line 133 of file EventFile.cxx.
{
         if (ientry_ < 0 && parent_) {
             if (!parent_->tree_) {
                 EXCEPTION_RAISE("EventFile", "No event tree in the file");
             }
             //Only clone parent tree if either
             //  1) There is no tree setup yet (first input file)
             //  2) This is not single output (new input file --> new output file)
             if ( !tree_ or !isSingleOutput_ ) {
                 //clones parent_->tree_ to our tree_ keeping drop/keep rules in mind
                 //clone tree (only copies over branches that are active on input tree)
                 file_->cd(); //go into output file
                 for ( auto const& rulePair : preCloneRules_ )
                     parent_->tree_->SetBranchStatus( rulePair.first.c_str() , rulePair.second );
                 tree_ = parent_->tree_->CloneTree(0);
                 //reactivate any drop branches (drop) on input tree
                 for ( auto const& rule : reactivateRules_ )
                     parent_->tree_->SetBranchStatus( rule.c_str(), 1 );
             }
             event_->setInputTree( parent_->tree_ );
             event_->setOutputTree( tree_ );
         }
         // close up the last event
         if (ientry_ >= 0) {
             if (isOutputFile_) {
                 event_->beforeFill();
                 if (storeCurrentEvent) tree_->Fill(); // fill the clones...
             }
             if (event_) {
                 event_->Clear();
                 event_->onEndOfEvent();
             }
         }
         if (parent_) {
             if (!parent_->nextEvent()) {
                 return false;
             }
             parent_->tree_->GetEntry(parent_->ientry_);
             ientry_ = parent_->ientry_;
             event_->nextEvent();
             entries_++;
             return true;
         } else {
             // if we are reading, move the pointer
             if (!isOutputFile_) {
                 if (ientry_ + 1 >= entries_) {
                     return false;
                 }
                 ientry_++;
                 tree_->LoadTree(ientry_);
                 if (event_) {
                     event_->nextEvent();
                 }
                 return true;
             } else {
                 ientry_++;
                 entries_++;
                 return true;
             }
         }
         return false;
     }
References ldmx::Event::beforeFill(), ldmx::Event::Clear(), entries_, event_, file_, ientry_, isOutputFile_, isSingleOutput_, ldmx::Event::nextEvent(), nextEvent(), ldmx::Event::onEndOfEvent(), parent_, preCloneRules_, reactivateRules_, ldmx::Event::setInputTree(), ldmx::Event::setOutputTree(), and tree_.
Referenced by nextEvent(), and ldmx::Process::run().
setupEvent()
void ldmx::EventFile::setupEvent (Event * evt)
Set an Event object containing the event data to work with this file.
Parameters
evt The Event object with event data.
Definition at line 211 of file EventFile.cxx.
{
         event_ = evt;
         if (isOutputFile_) {
             if (!tree_ && !parent_) {
                 tree_ = event_->createTree();
                 ientry_ = 0;
                 entries_ = 0;
             }
             if (parent_) {
                 event_->setInputTree(parent_->tree_);
             }
         } else {
             event_->setInputTree(tree_);
         }
     }
References ldmx::Event::createTree(), entries_, event_, ientry_, isOutputFile_, parent_, ldmx::Event::setInputTree(), and tree_.
Referenced by ldmx::Process::run().
updateParent()
void ldmx::EventFile::updateParent (EventFile * parent)
Change pointer to different parent file.
Parameters
parent pointer to new parent file
Definition at line 228 of file EventFile.cxx.
{
         parent_ = parent;
         TTree* parentTree = (TTree *)parent_->file_->Get("LDMX_Events");
         if ( parentTree ) {
             //Enter output file
             file_->cd();
             //need to turn on/off the same branches as in the initial setup...
             for ( auto const& rulePair : preCloneRules_ )
                 parent_->tree_->SetBranchStatus( rulePair.first.c_str() , rulePair.second );
             //Copy over addresses from the new parent
             parentTree->CopyAddresses( tree_ );
             //and reactivate any dropping rules
             for ( auto const& rule : reactivateRules_ )
                 parent_->tree_->SetBranchStatus( rule.c_str() , 1 );
             //Reset the entry index with the new parent index
             ientry_ = parent_->ientry_;
         }
         //import run headers from new input file
         importRunHeaders();
         return;
     }
References file_, ientry_, importRunHeaders(), parent_, preCloneRules_, reactivateRules_, and tree_.
Referenced by ldmx::Process::run().
writeRunHeader()
void ldmx::EventFile::writeRunHeader (RunHeader & runHeader)
Write the run header into the run map
Any RunHeader passed here is not owned or cleaned up by this EventFile instance.
Parameters
runHeader The run header to write into the map
Exceptions
Exception if run number is already in run map
Definition at line 302 of file EventFile.cxx.
{
         int runNumber = runHeader.getRunNumber();
         if ( runMap_.find(runNumber) != runMap_.end() ) {
             EXCEPTION_RAISE( "RunMap" ,
                     "Run map already contains a run with number '" + std::to_string(runNumber)
                     + "'." );
         }
         runMap_[runNumber] = std::make_pair(false,&runHeader);
         return;
     }
References ldmx::RunHeader::getRunNumber(), and runMap_.
Referenced by ldmx::Process::run().
Member Data Documentation
entries_
Long64_t ldmx::EventFile::entries_ {-1} private
The number of entries in the tree.
Definition at line 207 of file EventFile.h.
Referenced by EventFile(), nextEvent(), and setupEvent().
event_
Event* ldmx::EventFile::event_ {nullptr} private
The object containing the actual event data (trees and branches).
Definition at line 231 of file EventFile.h.
Referenced by addDrop(), getEvent(), nextEvent(), and setupEvent().
file_
TFile* ldmx::EventFile::file_ {nullptr} private
The backing TFile for this EventFile.
Definition at line 222 of file EventFile.h.
Referenced by close(), EventFile(), importRunHeaders(), nextEvent(), and updateParent().
fileName_
std::string ldmx::EventFile::fileName_ private
The file name.
Definition at line 213 of file EventFile.h.
Referenced by close(), and EventFile().
ientry_
Long64_t ldmx::EventFile::ientry_ {-1} private
The current entry in the tree.
Definition at line 210 of file EventFile.h.
Referenced by nextEvent(), setupEvent(), and updateParent().
isOutputFile_
bool ldmx::EventFile::isOutputFile_ private
True if file is an output file being written to disk.
Definition at line 216 of file EventFile.h.
Referenced by close(), EventFile(), importRunHeaders(), nextEvent(), and setupEvent().
isSingleOutput_
bool ldmx::EventFile::isSingleOutput_ private
True if there is only one output file
Definition at line 219 of file EventFile.h.
Referenced by nextEvent().
parent_
EventFile* ldmx::EventFile::parent_ {nullptr} private
A parent file containing event data.
Definition at line 228 of file EventFile.h.
Referenced by EventFile(), importRunHeaders(), nextEvent(), setupEvent(), and updateParent().
preCloneRules_
std::vector< std::pair< std::string , bool > > ldmx::EventFile::preCloneRules_ private
Pre-clone rules.
The series of rules to call before cloning/copying the parent tree.
Definition at line 239 of file EventFile.h.
Referenced by addDrop(), EventFile(), nextEvent(), and updateParent().
reactivateRules_
std::vector< std::string > ldmx::EventFile::reactivateRules_ private
Vector of drop rules that have been parsed and need to be used to reactivate these branches on the input tree
The branches were initial deactivated so they don't get cloned to output tree.
Definition at line 248 of file EventFile.h.
Referenced by addDrop(), EventFile(), nextEvent(), and updateParent().
runMap_
std::map<int, std::pair<bool,RunHeader*> > ldmx::EventFile::runMap_ private
Map of run numbers to RunHeader objects
The value object is a pair that should remain internal.
True if EventFile owns the RunHeader (and needs to clean it up)
This happens when RunHeaders are imported from an input file
False if EventFile does not own the RunHeader
This happens when the RunHeader is created by Process::run during production
Definition at line 259 of file EventFile.h.
Referenced by close(), getRunHeader(), importRunHeaders(), and writeRunHeader().
tree_
TTree* ldmx::EventFile::tree_ {nullptr} private
The tree with event data.
Definition at line 225 of file EventFile.h.
Referenced by close(), EventFile(), nextEvent(), setupEvent(), and updateParent().
The documentation for this class was generated from the following files:
Framework/include/Framework/EventFile.h
Framework/src/EventFile.cxx