LDMX Software: ldmx::TrigScintHit Class Reference
ldmx::TrigScintHit Class Reference
Public Member Functions
TrigScintHit ()
~TrigScintHit ()
void Clear (Option_t *option="")
void Print (Option_t *option="") const
void setBarID (const int barID)
int getBarID () const
Get the bar ID.
void setModuleID (const int moduleID)
int getModuleID () const
Get the module ID.
void setBeamEfrac (const float beamEfrac)
float getBeamEfrac () const
Get the beam energy fraction.
Public Member Functions inherited from ldmx::HcalHit
HcalHit ()
virtual ~HcalHit ()
void Clear ()
void Print () const
float getPE () const
float getMinPE () const
void setPE (float pe)
void setMinPE (float minpe)
Public Member Functions inherited from ldmx::CalorimeterHit
CalorimeterHit ()
virtual ~CalorimeterHit ()
void Clear ()
void Print () const
int getID () const
void setID (int id)
float getAmplitude () const
void setAmplitude (float amplitude)
float getEnergy () const
void setEnergy (float energy)
float getTime () const
void setTime (float time)
float getXPos () const
void setXPos (float xpos)
float getYPos () const
void setYPos (float ypos)
float getZPos () const
void setZPos (float zpos)
bool isNoise () const
void setNoise (bool yes)
bool operator< (const CalorimeterHit &rhs) const
Private Member Functions
ClassDef (TrigScintHit, 2)
Private Attributes
int barID_ {-1}
int moduleID_ {-1}
float beamEfrac_ {0}
The fraction of energy associated with beam electrons.
Detailed Description
Definition at line 24 of file TrigScintHit.h.
Constructor & Destructor Documentation
TrigScintHit()
ldmx::TrigScintHit::TrigScintHit () inline
Class constructor.
Definition at line 31 of file TrigScintHit.h.
 { }
~TrigScintHit()
ldmx::TrigScintHit::~TrigScintHit () inline
Class destructor.
Definition at line 36 of file TrigScintHit.h.
 { }
Member Function Documentation
Clear()
void ldmx::TrigScintHit::Clear (Option_t * option = "")
Clear the data in the object.
Print()
void ldmx::TrigScintHit::Print (Option_t * option = "") const
Print out the object.
setBarID()
void ldmx::TrigScintHit::setBarID (const int barID) inline
Set hit bar ID.
Parameters
barID The bar ID of the hit.
Definition at line 53 of file TrigScintHit.h.
 { barID_ = barID; };
Referenced by ldmx::TrigScintDigiProducer::produce().
setBeamEfrac()
void ldmx::TrigScintHit::setBeamEfrac (const float beamEfrac) inline
Set beam energy fraction of hit.
Parameters
beamEfrac The beam energy fraction of the hit.
Definition at line 73 of file TrigScintHit.h.
 { beamEfrac_ = beamEfrac; };
References beamEfrac_.
Referenced by ldmx::TrigScintDigiProducer::produce().
setModuleID()
void ldmx::TrigScintHit::setModuleID (const int moduleID) inline
Set hit module ID.
Parameters
moduleID The module ID of the hit.
Definition at line 63 of file TrigScintHit.h.
 { moduleID_ = moduleID; };
Referenced by ldmx::TrigScintDigiProducer::produce().
The documentation for this class was generated from the following file:
Event/include/Event/TrigScintHit.h