LDMX Software: ldmx::EcalDigiVerifier Class Reference
ldmx::EcalDigiVerifier Class Reference
Generate histograms to check digi pipeline performance.
#include <EcalDigiVerifier.h>
Public Member Functions
EcalDigiVerifier (const std::string &name, ldmx::Process &process)
virtual void configure (Parameters &ps)
virtual void analyze (const ldmx::Event &event)
Public Member Functions inherited from ldmx::Analyzer
Analyzer (const std::string &name, Process &process)
Public Member Functions inherited from ldmx::EventProcessor
EventProcessor (const std::string &name, Process &process)
virtual ~EventProcessor ()
virtual void onNewRun (const RunHeader &runHeader)
virtual void onFileOpen (EventFile &eventFile)
virtual void onFileClose (EventFile &eventFile)
virtual void onProcessStart ()
virtual void onProcessEnd ()
TDirectory * getHistoDirectory ()
void setStorageHint (ldmx::StorageControlHint hint)
void setStorageHint (ldmx::StorageControlHint hint, const std::string &purposeString)
void createHistograms (const std::vector< Parameters > &histos)
Private Attributes
std::string ecalSimHitColl_
Collection Name for SimHits.
std::string ecalSimHitPass_
Pass Name for SimHits.
std::string ecalRecHitColl_
Collection Name for RecHits.
std::string ecalRecHitPass_
Pass Name for RecHits.
Additional Inherited Members
Static Public Member Functions inherited from ldmx::EventProcessor
static void declare (const std::string &classname, int classtype, EventProcessorMaker *)
Static Public Attributes inherited from ldmx::Analyzer
static const int CLASSTYPE {2}
Protected Member Functions inherited from ldmx::EventProcessor
void abortEvent ()
Protected Attributes inherited from ldmx::EventProcessor
Process & process_
HistogramHelper histograms_
Interface class for making and filling histograms.
NtupleManager & ntuple_ {NtupleManager::getInstance()}
Manager for any ntuples.
logging::logger theLog_
The logger for this EventProcessor.
Detailed Description
Generate histograms to check digi pipeline performance.
Definition at line 15 of file EcalDigiVerifier.h.
Constructor & Destructor Documentation
EcalDigiVerifier()
ldmx::EcalDigiVerifier::EcalDigiVerifier (const std::string & name, ldmx::Process & process) inline
Constructor
Blank Analyzer constructor
Definition at line 24 of file EcalDigiVerifier.h.
 : ldmx::Analyzer(name, process) {}
Member Function Documentation
analyze()
void ldmx::EcalDigiVerifier::analyze (const ldmx::Event & event) virtual
Fills histograms
Implements ldmx::Analyzer.
Definition at line 16 of file EcalDigiVerifier.cxx.
{
         //get truth information sorted into an ID based map
         std::vector<SimCalorimeterHit> ecalSimHits = event.getCollection<SimCalorimeterHit>( ecalSimHitColl_ , ecalSimHitPass_ );
         //sort sim hits by ID
         std::sort( ecalSimHits.begin() , ecalSimHits.end() ,
                 []( const SimCalorimeterHit &lhs , const SimCalorimeterHit &rhs ) {
                     return lhs.getID() < rhs.getID();
                 }
                 );
         std::vector<EcalHit> ecalRecHits = event.getCollection<EcalHit>( ecalRecHitColl_ , ecalRecHitPass_ );
         //sort rec hits by ID
         std::sort( ecalRecHits.begin() , ecalRecHits.end() ,
                 []( const EcalHit &lhs , const EcalHit &rhs ) {
                     return lhs.getID() < rhs.getID();
                 }
                 );
         double totalRecEnergy = 0.;
         for ( const EcalHit &recHit : ecalRecHits ) {
             //skip anything that digi flagged as noise
             if ( recHit.isNoise() ) continue;
             int rawID = recHit.getID();
             //get information for this hit
             int numSimHits = 0;
             double totalSimEDep = 0.;
             for ( const SimCalorimeterHit &simHit : ecalSimHits ) {
                 if ( rawID == simHit.getID() ) {
                     numSimHits += simHit.getNumberOfContribs();
                     totalSimEDep += simHit.getEdep();
                 } else if ( rawID < simHit.getID() ) {
                     //later sim hits - all done
                     break;
                 }
             }
             histograms_.fill( "num_sim_hits_per_cell"   , numSimHits );
             histograms_.fill( "sim_edep__rec_amplitude" , totalSimEDep , recHit.getAmplitude() );
             totalRecEnergy += recHit.getEnergy();
         }
         histograms_.fill( "total_rec_energy" , totalRecEnergy );
         if ( totalRecEnergy > 6000. ) {
             setStorageHint( hint_shouldKeep );
         } else {
             setStorageHint( hint_shouldDrop );
         }
         return;
     }
References ecalRecHitColl_, ecalRecHitPass_, ecalSimHitColl_, ecalSimHitPass_, ldmx::HistogramHelper::fill(), ldmx::EventProcessor::histograms_, and ldmx::EventProcessor::setStorageHint().
configure()
void ldmx::EcalDigiVerifier::configure (Parameters & ps) virtual
Input python configuration parameters
Reimplemented from ldmx::EventProcessor.
Definition at line 6 of file EcalDigiVerifier.cxx.
{
         ecalSimHitColl_ = ps.getParameter<std::string>( "ecalSimHitColl" );
         ecalSimHitPass_ = ps.getParameter<std::string>( "ecalSimHitPass" );
         ecalRecHitColl_ = ps.getParameter<std::string>( "ecalRecHitColl" );
         ecalRecHitPass_ = ps.getParameter<std::string>( "ecalRecHitPass" );
         return;
     }
References ecalRecHitColl_, ecalRecHitPass_, ecalSimHitColl_, ecalSimHitPass_, and ldmx::Parameters::getParameter().
The documentation for this class was generated from the following files:
DQM/include/DQM/EcalDigiVerifier.h
DQM/src/EcalDigiVerifier.cxx