LDMX Software: biasing::PhotoNuclearTopologyFilter Class Reference
biasing::PhotoNuclearTopologyFilter Class Reference abstract
#include <PhotoNuclearTopologyFilters.h>
Public Member Functions
PhotoNuclearTopologyFilter (const std::string &name, framework::config::Parameters &parameters)
~PhotoNuclearTopologyFilter ()=default
Destructor.
void stepping (const G4Step *step) override
virtual bool rejectEvent (const std::vector< G4Track * > &secondaries) const =0
std::vector< simcore::TYPE > getTypes () final override
Retrieve the type of actions this class defines.
Public Member Functions inherited from simcore::UserAction
UserAction (const std::string &name, framework::config::Parameters &parameters)
virtual ~UserAction ()
Destructor.
virtual void BeginOfEventAction (const G4Event *)
virtual void EndOfEventAction (const G4Event *)
virtual void BeginOfRunAction (const G4Run *)
virtual void EndOfRunAction (const G4Run *)
virtual void PreUserTrackingAction (const G4Track *)
virtual void PostUserTrackingAction (const G4Track *)
virtual void stepping (const G4Step *)
virtual G4ClassificationOfNewTrack ClassifyNewTrack (const G4Track *, const G4ClassificationOfNewTrack &cl)
virtual void NewStage ()
virtual void PrepareNewEvent ()
virtual std::vector< TYPE > getTypes ()=0
Protected Member Functions
constexpr bool isLightIon (const int pdgCode) const
constexpr bool skipCountingParticle (const int pdgcode) const
constexpr bool isNeutron (const int pdgID) const
Protected Member Functions inherited from simcore::UserAction
UserEventInformation * getEventInfo () const
const std::map< int, ldmx::SimParticle > & getCurrentParticleMap () const
Protected Attributes
bool count_light_ions_
double hard_particle_threshold_
Protected Attributes inherited from simcore::UserAction
std::string name_ {""}
Name of the UserAction.
framework::config::Parameters parameters_
The set of parameters used to configure this class.
Additional Inherited Members
Public Types inherited from simcore::UserAction
using Factory = ::simcore::Factory< UserAction, std::shared_ptr< UserAction >, const std::string &, framework::config::Parameters & >
factory for user actions
Detailed Description
Abstract base class for a user action used to filter out photo-nuclear events that don't match the topology the user is interested in studying. Derived classes implement the event rejection
Similar to the PhotoNuclearProductsFilter, this user action will only process steps whose associated track has been tagged as a "PN Gamma". This tag is currently only set in ECalProcessFilter and needs to be placed in the UserAction pipeline before this class.
Definition at line 31 of file PhotoNuclearTopologyFilters.h.
Constructor & Destructor Documentation
PhotoNuclearTopologyFilter()
biasing::PhotoNuclearTopologyFilter::PhotoNuclearTopologyFilter (const std::string & name, framework::config::Parameters & parameters)
Constructor
Parameters
[in] name The name of this class instance.
[in] parameters The parameters used to configure this class.
Definition at line 44 of file PhotoNuclearTopologyFilters.cxx.
    : UserAction{name, parameters},
      hard_particle_threshold_{
          parameters.getParameter<double>("hard_particle_threshold")},
      count_light_ions_{parameters.getParameter<bool>("count_light_ions")} {}
Member Function Documentation
getTypes()
std::vector< simcore::TYPE > biasing::PhotoNuclearTopologyFilter::getTypes () inline final override virtual
Retrieve the type of actions this class defines.
Implements simcore::UserAction.
Definition at line 57 of file PhotoNuclearTopologyFilters.h.
{
    return {simcore::TYPE::STEPPING};
  }
isLightIon()
constexpr bool biasing::PhotoNuclearTopologyFilter::isLightIon (const int pdgCode) const inline constexpr protected
Check if the PDG code corresponds to a light ion nucleus.
Nuclear PDG codes are given by ±10LZZZAAAI So to find the atomic number, we first divide by 10 (to lose the I-component) and then take the modulo with 1000.
TODO: Repeated code from SimCore, could probably live elsewhere.
Definition at line 72 of file PhotoNuclearTopologyFilters.h.
{
    //
    // TODO: Is the < check necessary?
    if (pdgCode > 1000000000 && pdgCode < 10000000000) {
      // Check if the atomic number is less than or equal to 4
      return ((pdgCode / 10) % 1000) <= 4;
    }
    return false;
  }
Referenced by skipCountingParticle().
isNeutron()
constexpr bool biasing::PhotoNuclearTopologyFilter::isNeutron (const int pdgID) const inline constexpr protected
Definition at line 99 of file PhotoNuclearTopologyFilters.h.
{ return pdgID == 2112; }
skipCountingParticle()
constexpr bool biasing::PhotoNuclearTopologyFilter::skipCountingParticle (const int pdgcode) const inline constexpr protected
Whether or not to include a particular particle type in any counting. Unless count_light_ions_ is set, we don't count anything with a nuclear PDG code. This is consistent with the counting behaviour used in the PhotoNuclearDQM.
If count_light_ions_ is set, we also match PDG codes for nuclei with atomic number < 4.
TODO: Repeated code from SimCore, could probably live elsewhere.
See also
isLightIon
Definition at line 95 of file PhotoNuclearTopologyFilters.h.
{
    return !(pdgcode < 10000 || count_light_ions_ && isLightIon(pdgcode));
  }
References isLightIon().
stepping()
void biasing::PhotoNuclearTopologyFilter::stepping (const G4Step * step) override virtual
Callback that allows a user to take some actions at the end of a step.
Parameters
[in] step The Geant4 step containing transient information about the step taken by a track.
Reimplemented from simcore::UserAction.
Definition at line 51 of file PhotoNuclearTopologyFilters.cxx.
{
  // Get the track associated with this step.
  auto track{step->GetTrack()};
  // Get the track info and check if this track has been tagged as the
  // photon that underwent a photo-nuclear reaction. Only those tracks
  // tagged as PN photos will be processed. The track is currently only
  // tagged by the UserAction ECalProcessFilter which needs to be run
  // before this UserAction.
  auto trackInfo{simcore::UserTrackInformation::get(track)};
  if ((trackInfo != nullptr) && !trackInfo->isPNGamma()) return;
  // Get the PN photon daughters.
  auto secondaries{step->GetSecondary()};
  if (rejectEvent(*secondaries)) {
    track->SetTrackStatus(fKillTrackAndSecondaries);
    G4RunManager::GetRunManager()->AbortEvent();
  }
  // Once the PN gamma has been procesed, untag it so its not reprocessed
  // again.
  trackInfo->tagPNGamma(false);
}
References simcore::UserTrackInformation::get(), and simcore::UserTrackInformation::tagPNGamma().
Member Data Documentation
count_light_ions_
bool biasing::PhotoNuclearTopologyFilter::count_light_ions_ protected
Definition at line 101 of file PhotoNuclearTopologyFilters.h.
hard_particle_threshold_
double biasing::PhotoNuclearTopologyFilter::hard_particle_threshold_ protected
Definition at line 102 of file PhotoNuclearTopologyFilters.h.
The documentation for this class was generated from the following files:
Biasing/include/Biasing/PhotoNuclearTopologyFilters.h
Biasing/src/Biasing/PhotoNuclearTopologyFilters.cxx