LDMX Software: dqm::TrigScintClusterDQM Class Reference
dqm::TrigScintClusterDQM Class Reference
Public Member Functions
TrigScintClusterDQM (const std::string &name, framework::Process &process)
~TrigScintClusterDQM ()
void configure (framework::config::Parameters &pSet)
void analyze (const framework::Event &event)
void onProcessStart ()
Public Member Functions inherited from framework::Analyzer
Analyzer (const std::string &name, Process &process)
virtual void analyze (const Event &event)=0
Public Member Functions inherited from framework::EventProcessor
EventProcessor (const std::string &name, Process &process)
virtual ~EventProcessor ()
virtual void configure (framework::config::Parameters &parameters)
virtual void onNewRun (const ldmx::RunHeader &runHeader)
virtual void onFileOpen (EventFile &eventFile)
virtual void onFileClose (EventFile &eventFile)
virtual void onProcessStart ()
virtual void onProcessEnd ()
template<class T >
const T & getCondition (const std::string &condition_name)
TDirectory * getHistoDirectory ()
void setStorageHint (framework::StorageControlHint hint)
void setStorageHint (framework::StorageControlHint hint, const std::string &purposeString)
int getLogFrequency () const
int getRunNumber () const
std::string getName () const
void createHistograms (const std::vector< framework::config::Parameters > &histos)
Private Attributes
std::string clusterCollectionName_ {"TriggerPadUpClusters"}
std::string padName_ {"_up"}
std::string passName_ {""}
Additional Inherited Members
Static Public Member Functions inherited from framework::EventProcessor
static void declare (const std::string &classname, int classtype, EventProcessorMaker *)
Static Public Attributes inherited from framework::Analyzer
static const int CLASSTYPE {2}
Protected Member Functions inherited from framework::EventProcessor
void abortEvent ()
Protected Attributes inherited from framework::EventProcessor
HistogramHelper histograms_
Interface class for making and filling histograms.
NtupleManager & ntuple_ {NtupleManager::getInstance()}
Manager for any ntuples.
logging::logger theLog_
The logger for this EventProcessor.
Detailed Description
Definition at line 19 of file TrigScintClusterDQM.h.
Constructor & Destructor Documentation
TrigScintClusterDQM()
dqm::TrigScintClusterDQM::TrigScintClusterDQM (const std::string & name, framework::Process & process)
Constructor
Definition at line 5 of file TrigScintClusterDQM.cxx.
    : framework::Analyzer(name, process) {}
~TrigScintClusterDQM()
dqm::TrigScintClusterDQM::~TrigScintClusterDQM ()
Destructor
Definition at line 9 of file TrigScintClusterDQM.cxx.
{}
Member Function Documentation
analyze()
void dqm::TrigScintClusterDQM::analyze (const framework::Event & event) virtual
Process the event and make histograms ro summaries.
Parameters
event The event to analyze.
Implements framework::Analyzer.
Definition at line 44 of file TrigScintClusterDQM.cxx.
{
  // Get the collection of TrigScintCluster digitized clusters if the exists
  const std::vector<ldmx::TrigScintCluster> TrigScintClusters =
      event.getCollection<ldmx::TrigScintCluster>(clusterCollectionName_,
                                                  passName_);
  double totalPE{0};
  // Loop through all TrigScint clusters in the event
  for (const ldmx::TrigScintCluster &cluster : TrigScintClusters) {
    histograms_.fill("pe", cluster.getPE());
    histograms_.fill("energy", cluster.getEnergy());
    histograms_.fill("cluster_time", cluster.getTime());
    histograms_.fill("centroid", cluster.getCentroid());
    histograms_.fill("n_hits", cluster.getNHits());
    histograms_.fill("seed", cluster.getSeed());
    histograms_.fill("beamEfrac", cluster.getBeamEfrac());
    histograms_.fill("x", cluster.getCentroidX());
    histograms_.fill("y", cluster.getCentroidY());
    histograms_.fill("z", cluster.getCentroidZ());
    totalPE += cluster.getPE();
  }
  histograms_.fill("n_clusters", TrigScintClusters.size());
  histograms_.fill("total_pe", totalPE);
}
References clusterCollectionName_, framework::HistogramHelper::fill(), and framework::EventProcessor::histograms_.
configure()
void dqm::TrigScintClusterDQM::configure (framework::config::Parameters & pSet) virtual
Configure the processor using the given user specified parameters.
Parameters
pSet Set of parameters used to configure this processor.
Reimplemented from framework::EventProcessor.
Definition at line 34 of file TrigScintClusterDQM.cxx.
{
  clusterCollectionName_ = ps.getParameter<std::string>("cluster_collection");
  padName_ = ps.getParameter<std::string>("pad").c_str();
  passName_ = ps.getParameter<std::string>("passName").c_str();
  ldmx_log(info) << "In TrigScintClusterDQM::configure, got parameters "
                 << clusterCollectionName_ << ", pad = " << padName_
                 << ", pass = " << passName_;
}
References clusterCollectionName_, and framework::config::Parameters::getParameter().
onProcessStart()
void dqm::TrigScintClusterDQM::onProcessStart () virtual
Method executed before processing of events begins.
Reimplemented from framework::EventProcessor.
Definition at line 11 of file TrigScintClusterDQM.cxx.
{
  getHistoDirectory();
  histograms_.create("centroid", "Cluster channel centroid", 500, 0, 100);
  histograms_.create("total_pe", "Total cluster PEs in the pad/event", 500, 0,
                     2000);
  histograms_.create("n_clusters", "Clusters in the pad/event", 25, 0, 25);
  histograms_.create("n_hits", "N_{hits} forming the clusters", 4, 0, 4);
  histograms_.create("seed", "Cluster seed hit channel ID", 100, 0, 100);
  histograms_.create("beamEfrac", "Cluster edep fraction from beam electron",
                     101, 0., 1.01);
  histograms_.create("x", "Cluster x position", 1000, -100, 100);
  histograms_.create("y", "Cluster y position", 1000, -100, 100);
  histograms_.create("z", "Cluster z position", 1000, -900, 100);
  histograms_.create("pe", "PE in a cluster", 250, 0, 1000);
  histograms_.create("energy", "Energy dep in a cluster [MeV]", 500, 0, 1500);
  histograms_.create("cluster_time", "Cluster time (ns)", 600, -150, 150);
  // TODO: implement getting a list of the constructed histograms, to iterate
  // through and set overflow boolean.
}
References framework::HistogramHelper::create(), framework::EventProcessor::getHistoDirectory(), and framework::EventProcessor::histograms_.
Member Data Documentation
clusterCollectionName_
std::string dqm::TrigScintClusterDQM::clusterCollectionName_ {"TriggerPadUpClusters"} private
Name of trigger pad cluster collection.
Definition at line 46 of file TrigScintClusterDQM.h.
Referenced by analyze(), and configure().
padName_
std::string dqm::TrigScintClusterDQM::padName_ {"_up"} private
Definition at line 47 of file TrigScintClusterDQM.h.
passName_
std::string dqm::TrigScintClusterDQM::passName_ {""} private
Definition at line 48 of file TrigScintClusterDQM.h.
The documentation for this class was generated from the following files:
DQM/include/DQM/TrigScintClusterDQM.h
DQM/src/DQM/TrigScintClusterDQM.cxx