LDMX Software: simcore::persist::RootPersistencyManager Class Reference
simcore::persist::RootPersistencyManager Class Reference
#include <RootPersistencyManager.h>
Public Member Functions
RootPersistencyManager (framework::EventFile &file, framework::config::Parameters &parameters, const int &runNumber, ConditionsInterface &ci)
virtual ~RootPersistencyManager ()
Destructor.
G4bool Store (const G4Event *anEvent)
G4bool Store (const G4Run *aRun)
G4bool Store (const G4VPhysicalVolume *)
void Initialize ()
void setCurrentEvent (framework::Event *event)
void setNumEvents (int began, int completed)
void buildEvent (const G4Event *anEvent)
void writeHeader (const G4Event *anEvent)
void writeHitsCollections (const G4Event *anEvent, framework::Event *outputEvent)
void writeTrackerHitsCollection (G4TrackerHitsCollection *hc, std::vector< ldmx::SimTrackerHit > &outputColl)
void writeCalorimeterHitsCollection (G4CalorimeterHitsCollection *hc, std::vector< ldmx::SimCalorimeterHit > &outputColl)
Static Public Member Functions
static RootPersistencyManager * getInstance ()
Private Attributes
framework::config::Parameters parameters_
Configuration parameters passed to Simulator.
int run_
Run Number, given to us by Simulator from Process.
int eventsBegan_ {-1}
Number of events started on this production run.
int eventsCompleted_ {-1}
Number of events completed without being aborted (due to filters)
framework::EventFile & file_
The output file.
framework::Event * event_ {nullptr}
The event container used to manage the tree/branches/collections.
EcalHitIO ecalHitIO_
Handles ECal hit readout and IO.
Detailed Description
Note
Output is written at the end of each event. An EventFile is used to write from an Event buffer object into an output branch within a tree. The event buffer is cleared after the event is written. A SimParticleBuilder is used to build a set of SimParticle objects from the Trajectory objects which were created during event processing. An EcalHitIO instance provides translation of G4CalorimeterHit objects in the ECal to an output SimCalorimeterHit collection, transforming the individual steps into cell energy depositions. The tracker hit collections of G4TrackerHit objects are translated directly into output SimTrackerHit collections.
Definition at line 56 of file RootPersistencyManager.h.
Constructor & Destructor Documentation
RootPersistencyManager()
simcore::persist::RootPersistencyManager::RootPersistencyManager (framework::EventFile & file, framework::config::Parameters & parameters, const int & runNumber, ConditionsInterface & ci)
Class constructor.
Parameters
eventFile file to put output events into
parameters configuration parameters from Simulator
runNumber current run identifer from Process
Definition at line 41 of file RootPersistencyManager.cxx.
    : G4PersistencyManager(G4PersistencyCenter::GetPersistencyCenter(),
                           "RootPersistencyManager"),
      file_(file),
      ecalHitIO_(ci) {
  // Let Geant4 know what to use this persistency manager
  G4PersistencyCenter::GetPersistencyCenter()->RegisterPersistencyManager(this);
  G4PersistencyCenter::GetPersistencyCenter()->SetPersistencyManager(
      this, "RootPersistencyManager");
  // Set the parameters, used laster when printing run header
  parameters_ = parameters;
  ecalHitIO_.configure(parameters_);
  run_ = runNumber;
}
References simcore::EcalHitIO::configure(), ecalHitIO_, parameters_, and run_.
~RootPersistencyManager()
virtual simcore::persist::RootPersistencyManager::~RootPersistencyManager () inline virtual
Destructor.
Definition at line 70 of file RootPersistencyManager.h.
{}
Member Function Documentation
buildEvent()
void simcore::persist::RootPersistencyManager::buildEvent (const G4Event * anEvent)
Build an output event from the current Geant4 event.
Parameters
anEvent The Geant4 event.
outputEvent The output event.
Definition at line 89 of file RootPersistencyManager.cxx.
{
  // Set basic event information.
  writeHeader(anEvent);
  TrackMap* tracks{UserTrackingAction::getUserTrackingAction()->getTrackMap()};
  tracks->traceAncestry();
  event_->add("SimParticles", tracks->getParticleMap());
  // Copy hit objects from SD hit collections into the output event.
  writeHitsCollections(anEvent, event_);
}
References framework::Event::add(), event_, simcore::UserTrackingAction::getTrackMap(), simcore::UserTrackingAction::getUserTrackingAction(), simcore::TrackMap::traceAncestry(), writeHeader(), and writeHitsCollections().
Referenced by Store().
getInstance()
static RootPersistencyManager * simcore::persist::RootPersistencyManager::getInstance () inline static
Get the current ROOT persistency manager or nullptr if not registered.
Returns
The ROOT persistency manager.
Definition at line 78 of file RootPersistencyManager.h.
{
    return static_cast<RootPersistencyManager *>(
        G4PersistencyCenter::GetPersistencyCenter()
            ->CurrentPersistencyManager());
  }
Initialize()
void simcore::persist::RootPersistencyManager::Initialize ()
This is called "manually" in UserRunAction to open the ROOT writer for the run.
Definition at line 87 of file RootPersistencyManager.cxx.
{}
setCurrentEvent()
void simcore::persist::RootPersistencyManager::setCurrentEvent (framework::Event * event) inline
Set the current ldmx-sw event. This is used by the persistency manager to retrieve and fill the containers that will be persisted.
Parameters
event Event buffer for the current event.
Definition at line 119 of file RootPersistencyManager.h.
{ event_ = event; }
References event_.
setNumEvents()
void simcore::persist::RootPersistencyManager::setNumEvents (int began, int completed) inline
Set the number of events began and completed.
These two numbers may or may not be equal depending on if the simulation ran with any filters that would abort events early.
These numbers are helpful for evaluating filtering performance, so we put them both in the RunHeader.
Parameters
[in] began number of events that were started
[in] completed number of events that were completed without an abort signal
Definition at line 135 of file RootPersistencyManager.h.
{
    eventsBegan_ = began;
    eventsCompleted_ = completed;
  }
References eventsBegan_, and eventsCompleted_.
Store() [1/3]
G4bool simcore::persist::RootPersistencyManager::Store (const G4Event * anEvent)
Builds the output ROOT event.
Parameters
anEvent The Geant4 event data.
Definition at line 61 of file RootPersistencyManager.cxx.
{
  // Check if the event has been aborted.  If so, skip storage of the
  // event.
  if (G4RunManager::GetRunManager()->GetCurrentEvent()->IsAborted())
    return false;
  // Build the output collections.
  buildEvent(anEvent);
  return true;
}
References buildEvent().
Store() [2/3]
G4bool simcore::persist::RootPersistencyManager::Store (const G4Run * aRun)
This gets called automatically at the end of the run and is used to write out the run header and close the writer.
Parameters
aRun The Geant4 run data (not used right now)
Returns
True if event is stored (function is hard-coded to return true).
Definition at line 73 of file RootPersistencyManager.cxx.
{
  // NOTE: This method is called once the run is terminated through
  // the run manager.
  // throws an exception if not correct run number
  ldmx::RunHeader &runHeader = file_.getRunHeader(run_);
  // Set parameter value with number of events processed.
  runHeader.setIntParameter("Event Count", eventsCompleted_);
  runHeader.setIntParameter("Events Began", eventsBegan_);
  return true;
}
References eventsBegan_, eventsCompleted_, file_, framework::EventFile::getRunHeader(), run_, and ldmx::RunHeader::setIntParameter().
Store() [3/3]
G4bool simcore::persist::RootPersistencyManager::Store (const G4VPhysicalVolume *) inline
Implementing this makes an "overloaded-virtual" compiler warning go away.
Definition at line 104 of file RootPersistencyManager.h.
{ return false; }
writeCalorimeterHitsCollection()
void simcore::persist::RootPersistencyManager::writeCalorimeterHitsCollection (G4CalorimeterHitsCollection * hc, std::vector< ldmx::SimCalorimeterHit > & outputColl)
Write a collection of tracker hits to an output collection.
Parameters
hc The collection of G4CalorimeterHits.
outputColl The output collection of SimCalorimeterHits.
Definition at line 202 of file RootPersistencyManager.cxx.
{
  // get ancestral tracking information
  auto trackMap{UserTrackingAction::getUserTrackingAction()->getTrackMap()};
  int nHits = hc->GetSize();
  for (int iHit = 0; iHit < nHits; iHit++) {
    G4CalorimeterHit *g4hit = (G4CalorimeterHit *)hc->GetHit(iHit);
    const G4ThreeVector &pos = g4hit->getPosition();
    ldmx::SimCalorimeterHit simHit;
    simHit.setID(g4hit->getID());
    simHit.addContrib(trackMap->findIncident(g4hit->getTrackID()),
                      g4hit->getTrackID(), g4hit->getPdgCode(),
                      g4hit->getEdep(), g4hit->getTime());
    simHit.setPosition(pos.x(), pos.y(), pos.z());
    outputColl.push_back(simHit);
  }
  return;
}
References ldmx::SimCalorimeterHit::addContrib(), simcore::G4CalorimeterHit::getEdep(), simcore::G4CalorimeterHit::getID(), simcore::G4CalorimeterHit::getPdgCode(), simcore::G4CalorimeterHit::getPosition(), simcore::G4CalorimeterHit::getTime(), simcore::G4CalorimeterHit::getTrackID(), simcore::UserTrackingAction::getTrackMap(), simcore::UserTrackingAction::getUserTrackingAction(), ldmx::SimCalorimeterHit::setID(), and ldmx::SimCalorimeterHit::setPosition().
Referenced by writeHitsCollections().
writeHeader()
void simcore::persist::RootPersistencyManager::writeHeader (const G4Event * anEvent)
Write header info into the output event from Geant4.
Parameters
anEvent The Geant4 event.
Definition at line 102 of file RootPersistencyManager.cxx.
{
  // Retrieve a mutable version of the event header
  ldmx::EventHeader &eventHeader = event_->getEventHeader();
  auto event_info{
      static_cast<UserEventInformation *>(anEvent->GetUserInformation())};
  eventHeader.setWeight(event_info->getWeight());
  eventHeader.setFloatParameter("total_photonuclear_energy",
                                event_info->getPNEnergy());
  eventHeader.setFloatParameter("total_electronuclear_energy",
                                event_info->getENEnergy());
  // Save the state of the random engine to an output stream. A string
  // is then extracted and saved to the event header.
  std::ostringstream stream;
  G4Random::saveFullState(stream);
  // std::cout << stream.str() << std::endl;
  eventHeader.setStringParameter("eventSeed", stream.str());
}
References event_, framework::Event::getEventHeader(), ldmx::EventHeader::setFloatParameter(), ldmx::EventHeader::setStringParameter(), and ldmx::EventHeader::setWeight().
Referenced by buildEvent().
writeHitsCollections()
void simcore::persist::RootPersistencyManager::writeHitsCollections (const G4Event * anEvent, framework::Event * outputEvent)
Write hits collections from Geant4 into a ROOT event.
Parameters
anEvent The Geant4 event.
outputEvent The output event.
Definition at line 123 of file RootPersistencyManager.cxx.
{
  // Get the HC of this event.
  G4HCofThisEvent *hce = anEvent->GetHCofThisEvent();
  int nColl = hce->GetNumberOfCollections();
  // Loop over all hits collections.
  for (int iColl = 0; iColl < nColl; iColl++) {
    // Get a hits collection and its name.
    G4VHitsCollection *hc = hce->GetHC(iColl);
    if (!hc) {
      EXCEPTION_RAISE("G4HitColl", "G4VHitsCollection indexed " +
                                       std::to_string(iColl) +
                                       " returned a nullptr.");
    }
    std::string collName = hc->GetName();
    if (dynamic_cast<G4TrackerHitsCollection *>(hc) != nullptr) {
      // Write G4TrackerHit collection to output SimTrackerHit collection.
      G4TrackerHitsCollection *trackerHitsColl =
          dynamic_cast<G4TrackerHitsCollection *>(hc);
      std::vector<ldmx::SimTrackerHit> outputColl;
      writeTrackerHitsCollection(trackerHitsColl, outputColl);
      // Add hits collection to output event.
      outputEvent->add(collName, outputColl);
    } else if (dynamic_cast<G4CalorimeterHitsCollection *>(hc) != nullptr) {
      G4CalorimeterHitsCollection *calHitsColl =
          dynamic_cast<G4CalorimeterHitsCollection *>(hc);
      std::vector<ldmx::SimCalorimeterHit> outputColl;
      if (collName == ldmx::EventConstants::ECAL_SIM_HITS) {
        // Write ECal G4CalorimeterHit collection to output SimCalorimeterHit
        // collection using helper class.
        ecalHitIO_.writeHitsCollection(calHitsColl, outputColl);
      } else {
        // Write generic G4CalorimeterHit collection to output SimCalorimeterHit
        // collection.
        writeCalorimeterHitsCollection(calHitsColl, outputColl);
      }
      // Add hits collection to output event.
      outputEvent->add(collName, outputColl);
    }  // switch on type of hit collection
  }  // loop through geant4 hit collections
  return;
}
References framework::Event::add(), ecalHitIO_, writeCalorimeterHitsCollection(), simcore::EcalHitIO::writeHitsCollection(), and writeTrackerHitsCollection().
Referenced by buildEvent().
writeTrackerHitsCollection()
void simcore::persist::RootPersistencyManager::writeTrackerHitsCollection (G4TrackerHitsCollection * hc, std::vector< ldmx::SimTrackerHit > & outputColl)
Write a collection of tracker hits to an output collection.
Parameters
hc The collection of G4TrackerHits.
outputColl The output collection of SimTrackerHits.
Definition at line 174 of file RootPersistencyManager.cxx.
{
  outputColl.clear();
  int nHits = hc->GetSize();
  for (int iHit = 0; iHit < nHits; iHit++) {
    G4TrackerHit *g4hit = (G4TrackerHit *)hc->GetHit(iHit);
    const G4ThreeVector &momentum = g4hit->getMomentum();
    const G4ThreeVector &position = g4hit->getPosition();
    ldmx::SimTrackerHit simTrackerHit;
    simTrackerHit.setID(g4hit->getID());
    simTrackerHit.setTime(g4hit->getTime());
    simTrackerHit.setLayerID(g4hit->getLayerID());
    simTrackerHit.setModuleID(g4hit->getModuleID());
    simTrackerHit.setEdep(g4hit->getEdep());
    simTrackerHit.setEnergy(g4hit->getEnergy());
    simTrackerHit.setPathLength(g4hit->getPathLength());
    simTrackerHit.setTrackID(g4hit->getTrackID());
    simTrackerHit.setPdgID(g4hit->getPdgID());
    simTrackerHit.setPosition(position.x(), position.y(), position.z());
    simTrackerHit.setMomentum(momentum.x(), momentum.y(), momentum.z());
    outputColl.push_back(simTrackerHit);
  }
  return;
}
References simcore::G4TrackerHit::getEdep(), simcore::G4TrackerHit::getEnergy(), simcore::G4TrackerHit::getID(), simcore::G4TrackerHit::getLayerID(), simcore::G4TrackerHit::getModuleID(), simcore::G4TrackerHit::getMomentum(), simcore::G4TrackerHit::getPathLength(), simcore::G4TrackerHit::getPdgID(), simcore::G4TrackerHit::getPosition(), simcore::G4TrackerHit::getTime(), simcore::G4TrackerHit::getTrackID(), ldmx::SimTrackerHit::setEdep(), ldmx::SimTrackerHit::setEnergy(), ldmx::SimTrackerHit::setID(), ldmx::SimTrackerHit::setLayerID(), ldmx::SimTrackerHit::setModuleID(), ldmx::SimTrackerHit::setMomentum(), ldmx::SimTrackerHit::setPathLength(), ldmx::SimTrackerHit::setPdgID(), ldmx::SimTrackerHit::setPosition(), ldmx::SimTrackerHit::setTime(), and ldmx::SimTrackerHit::setTrackID().
Referenced by writeHitsCollections().
Member Data Documentation
ecalHitIO_
EcalHitIO simcore::persist::RootPersistencyManager::ecalHitIO_ private
Handles ECal hit readout and IO.
Definition at line 204 of file RootPersistencyManager.h.
Referenced by RootPersistencyManager(), and writeHitsCollections().
event_
framework::Event* simcore::persist::RootPersistencyManager::event_ {nullptr} private
The event container used to manage the tree/branches/collections.
Definition at line 201 of file RootPersistencyManager.h.
Referenced by buildEvent(), setCurrentEvent(), and writeHeader().
eventsBegan_
int simcore::persist::RootPersistencyManager::eventsBegan_ {-1} private
Number of events started on this production run.
Definition at line 192 of file RootPersistencyManager.h.
Referenced by setNumEvents(), and Store().
eventsCompleted_
int simcore::persist::RootPersistencyManager::eventsCompleted_ {-1} private
Number of events completed without being aborted (due to filters)
Definition at line 195 of file RootPersistencyManager.h.
Referenced by setNumEvents(), and Store().
file_
framework::EventFile& simcore::persist::RootPersistencyManager::file_ private
The output file.
Definition at line 198 of file RootPersistencyManager.h.
Referenced by Store().
parameters_
framework::config::Parameters simcore::persist::RootPersistencyManager::parameters_ private
Configuration parameters passed to Simulator.
Definition at line 186 of file RootPersistencyManager.h.
Referenced by RootPersistencyManager().
run_
int simcore::persist::RootPersistencyManager::run_ private
Run Number, given to us by Simulator from Process.
Definition at line 189 of file RootPersistencyManager.h.
Referenced by RootPersistencyManager(), and Store().
The documentation for this class was generated from the following files:
SimCore/include/SimCore/Persist/RootPersistencyManager.h
SimCore/src/SimCore/Persist/RootPersistencyManager.cxx