LDMX Software: ldmx::TrigScintSD Class Reference
ldmx::TrigScintSD Class Reference
#include <TrigScintSD.h>
Public Member Functions
TrigScintSD (G4String name, G4String collectionName, int subDetID)
~TrigScintSD ()
Destructor.
G4bool ProcessHits (G4Step *step, G4TouchableHistory *history)
Public Member Functions inherited from ldmx::CalorimeterSD
CalorimeterSD (G4String name, G4String theCollectionName)
virtual ~CalorimeterSD ()
void setLayerDepth (int layerDepth)
void Initialize (G4HCofThisEvent *hcEvent)
void EndOfEvent (G4HCofThisEvent *hcEvent)
Additional Inherited Members
Protected Attributes inherited from ldmx::CalorimeterSD
G4CalorimeterHitsCollection * hitsCollection_
int subdet_
DetectorID * detID_
int layerDepth_ {2}
Detailed Description
Class defining a sensitive detector of type trigger scintillator.
Definition at line 18 of file TrigScintSD.h.
Constructor & Destructor Documentation
TrigScintSD()
ldmx::TrigScintSD::TrigScintSD (G4String name, G4String collectionName, int subDetID)
Class constructor.
Parameters
[in] name The name of the sensitive detector.
[in] theCollectionName The name of the hits collection.
[in] subdet The subdetector ID.
Definition at line 19 of file TrigScintSD.cxx.
         : CalorimeterSD(name, theCollectionName) {
         detID_ = new TrigScintID();
         // Set the subdet ID as it will always be the same for every hit.
         detID_->setFieldValue("module", subDetID);
     }
References ldmx::CalorimeterSD::detID_, and ldmx::DetectorID::setFieldValue().
Member Function Documentation
ProcessHits()
G4bool ldmx::TrigScintSD::ProcessHits (G4Step * step, G4TouchableHistory * history) virtual
Process steps to create hits.
Parameters
[in] step The step information.
[in] history The readout history.
Implements ldmx::CalorimeterSD.
Definition at line 33 of file TrigScintSD.cxx.
{
         // Get the energy deposited by the particle during the step
         auto energy{step->GetTotalEnergyDeposit()};
         // If a non-Geantino particle doesn't deposit energy during the step,
         // skip processing it.
         if (auto particleDef{step->GetTrack()->GetDefinition()};
                 (energy == 0)
                 && ((particleDef != G4Geantino::Definition())
                         || (particleDef != G4ChargedGeantino::Definition()))) return false;
         // Create a new instance of a calorimeter hit
         auto hit{new G4CalorimeterHit()};
         // Set the energy deposition
         hit->setEdep(energy);
         // Set the hit position
         auto position{0.5 * (step->GetPreStepPoint()->GetPosition() + step->GetPostStepPoint()->GetPosition())};
         auto volumePosition{step->GetPreStepPoint()->GetTouchableHandle()->GetHistory()->GetTopTransform().Inverse().TransformPoint(G4ThreeVector())};
         hit->setPosition(position[0], position[1], volumePosition.z());
         // Get the track associated with this step
         auto track{step->GetTrack()};
         // Set the global time.
         hit->setTime(track->GetGlobalTime());
         // Set the ID on the hit.
         auto bar{track->GetVolume()->GetCopyNo()};
         detID_->setFieldValue("bar", bar);
         hit->setID(detID_->pack());
         // Set the track ID on the hit.
         hit->setTrackID(track->GetTrackID());
         // Set the PDG code from the track.
         hit->setPdgCode(track->GetParticleDefinition()->GetPDGEncoding());
         hitsCollection_->insert(hit);
         return true;
     }
References ldmx::CalorimeterSD::detID_, ldmx::CalorimeterSD::hitsCollection_, ldmx::DetectorID::pack(), ldmx::G4CalorimeterHit::setEdep(), and ldmx::DetectorID::setFieldValue().
The documentation for this class was generated from the following files:
SimCore/include/SimCore/TrigScintSD.h
SimCore/src/TrigScintSD.cxx