LDMX Software: framework::EventProcessor Class Reference
framework::EventProcessor Class Reference
Base class for all event processing components.
#include <EventProcessor.h>
Public Member Functions
EventProcessor (const std::string &name, Process &process)
virtual ~EventProcessor ()
virtual void configure (framework::config::Parameters &parameters)
virtual void onNewRun (const ldmx::RunHeader &runHeader)
virtual void onFileOpen (EventFile &eventFile)
virtual void onFileClose (EventFile &eventFile)
virtual void onProcessStart ()
virtual void onProcessEnd ()
template<class T >
const T & getCondition (const std::string &condition_name)
TDirectory * getHistoDirectory ()
void setStorageHint (framework::StorageControlHint hint)
void setStorageHint (framework::StorageControlHint hint, const std::string &purposeString)
int getLogFrequency () const
int getRunNumber () const
std::string getName () const
void createHistograms (const std::vector< framework::config::Parameters > &histos)
Static Public Member Functions
static void declare (const std::string &classname, int classtype, EventProcessorMaker *)
Protected Member Functions
void abortEvent ()
Protected Attributes
HistogramHelper histograms_
Interface class for making and filling histograms.
NtupleManager & ntuple_ {NtupleManager::getInstance()}
Manager for any ntuples.
logging::logger theLog_
The logger for this EventProcessor.
Private Member Functions
Conditions & getConditions () const
const ldmx::EventHeader & getEventHeader () const
Private Attributes
Process & process_
std::string name_
TDirectory * histoDir_ {0}
Detailed Description
Base class for all event processing components.
Definition at line 65 of file EventProcessor.h.
Constructor & Destructor Documentation
EventProcessor()
framework::EventProcessor::EventProcessor (const std::string & name, Process & process)
Class constructor.
Parameters
name Name for this instance of the class.
process The Process class associated with EventProcessor, provided by the framework.
Note
The name provided to this function should not be the class name, but rather a logical label for this instance of the class, as more than one copy of a given class can be loaded into a Process with different parameters. Names should not include whitespace or special characters.
Definition at line 11 of file EventProcessor.cxx.
    : process_{process},
      name_{name},
      histograms_{name},
      theLog_{logging::makeLogger(name)} {}
~EventProcessor()
virtual framework::EventProcessor::~EventProcessor () inline virtual
Class destructor.
Definition at line 84 of file EventProcessor.h.
{ ; }
Member Function Documentation
abortEvent()
void framework::EventProcessor::abortEvent () inline protected
Abort the event immediately.
Skip the rest of the sequence and don't save anything in the event bus.
Definition at line 213 of file EventProcessor.h.
{ throw AbortEventException(); }
Referenced by packing::SingleSubsystemPacker::analyze(), hcal::HcalAlignPolarfires::produce(), packing::RawIO::produce(), packing::SingleSubsystemUnpacker::produce(), and simcore::Simulator::produce().
configure()
virtual void framework::EventProcessor::configure (framework::config::Parameters & parameters) inline virtual
Callback for the EventProcessor to configure itself from the given set of parameters.
The parameters a processor has access to are the member variables of the python class in the sequence that has className equal to the EventProcessor class name.
For an example, look at MyProcessor.
Parameters
parameters Parameters for configuration.
Reimplemented in ecal::EcalDigiProducer, ecal::EcalRawDecoder, ecal::EcalRawEncoder, ecal::EcalRecProducer, ecal::EcalTrigPrimDigiProducer, hcal::HcalTrigPrimDigiProducer, hcal::HcalDigiProducer, hcal::HcalRecProducer, hcal::HcalRawDecoder, packing::FiberTrackerRawDecoder, packing::WRRawDecoder, framework::test::TestProducer, hcal::HcalDoubleEndRecProducer, hcal::HcalSingleEndRecProducer, trigscint::QIEAnalyzer, trigscint::TestBeamHitAnalyzer, dqm::HCalDQM, dqm::HCalRawDigi, dqm::PhotoNuclearDQM, dqm::RecoilTrackerDQM, ecal::DNNEcalVetoProcessor, ecal::EcalClusterProducer, ecal::EcalVetoProcessor, framework::test::TestConfig, hcal::HcalClusterProducer, hcal::HcalVetoProcessor, hcal::HcalWABVetoProcessor, recon::ElectronCounter, recon::MyProcessor, recon::OverlayProducer, recon::TriggerProcessor, simcore::Simulator, tracking::sim::HitSmearingProcessor, trigscint::EventReadoutProducer, trigscint::TestBeamHitProducer, trigscint::TrigScintDigiProducer, trigscint::TrigScintQIEDigiProducer, trigscint::TrigScintRecHitProducer, trigscint::TruthHitProducer, dqm::EcalDigiVerifier, dqm::EcalShowerFeatures, dqm::SimObjects, dqm::Trigger, trigscint::QIEDecoder, trigscint::QIEEncoder, trigscint::TestBeamClusterProducer, trigscint::TrigScintClusterProducer, trigscint::TrigScintTrackProducer, dqm::NtuplizeHgcrocDigiCollection, dqm::NtuplizeTrigScintQIEDigis, hcal::HcalAlignPolarfires, hcal::HcalPedestalAnalyzer, packing::RawIO, packing::SingleSubsystemPacker, packing::SingleSubsystemUnpacker, dqm::TrigScintClusterDQM, dqm::TrigScintDQM, dqm::TrigScintHitDQM, and dqm::TrigScintTrackDQM.
Definition at line 98 of file EventProcessor.h.
{}
Referenced by framework::Process::Process().
createHistograms()
void framework::EventProcessor::createHistograms (const std::vector< framework::config::Parameters > & histos)
Internal function which is used to create histograms passed from the python configuration @parma histos vector of Parameters that configure histograms to create
Definition at line 50 of file EventProcessor.cxx.
{
  for (auto const &h : histos) {
    auto name{h.getParameter<std::string>("name")};
    auto xLabel{h.getParameter<std::string>("xlabel")};
    auto xbins{h.getParameter<std::vector<double>>("xbins")};
    auto yLabel{h.getParameter<std::string>("ylabel")};
    auto ybins{h.getParameter<std::vector<double>>("ybins", {})};
    if (ybins.empty()) {
      // assume 1D histogram
      histograms_.create(name, xLabel, xbins);
    } else {
      // assume 2D histogram
      histograms_.create(name, xLabel, xbins, yLabel, ybins);
    }
  }
}
References framework::HistogramHelper::create(), and histograms_.
Referenced by framework::Process::Process().
declare()
void framework::EventProcessor::declare (const std::string & classname, int classtype, EventProcessorMaker * maker) static
Internal function which is part of the PluginFactory machinery.
Parameters
classname The class name of the processor.
classtype The class type of the processor (1 for Producer, 2 for Analyzer).
Definition at line 44 of file EventProcessor.cxx.
{
  PluginFactory::getInstance().registerEventProcessor(classname, classtype,
                                                      maker);
}
References framework::PluginFactory::getInstance(), and framework::PluginFactory::registerEventProcessor().
getCondition()
template<class T > const T & framework::EventProcessor::getCondition (const std::string & condition_name) inline
Access a conditions object for the current event
Definition at line 141 of file EventProcessor.h.
{
    return getConditions().getCondition<T>(condition_name);
  }
References framework::Conditions::getCondition(), and getConditions().
Referenced by simcore::ConditionsInterface::getCondition().
getConditions()
Conditions & framework::EventProcessor::getConditions () const private
Internal getter for conditions without exposing all of Process
Definition at line 17 of file EventProcessor.cxx.
{
  return process_.getConditions();
}
References framework::Process::getConditions(), and process_.
Referenced by getCondition().
getEventHeader()
const ldmx::EventHeader & framework::EventProcessor::getEventHeader () const private
Internal getter for EventHeader without exposing all of Process
Definition at line 21 of file EventProcessor.cxx.
{
  return *(process_.getEventHeader());
}
References framework::Process::getEventHeader(), and process_.
getHistoDirectory()
TDirectory * framework::EventProcessor::getHistoDirectory ()
Access/create a directory in the histogram file for this event processor to create histograms and analysis tuples.
Note
This method makes the returned directory the current directory so that newly created objects should go into that directory
Returns
TDirectory* reference to directory in histogram file
Definition at line 25 of file EventProcessor.cxx.
{
  if (!histoDir_) {
    histoDir_ = process_.makeHistoDirectory(name_);
  }
  histoDir_->cd();  // make this the current directory
  return histoDir_;
}
References histoDir_, framework::Process::makeHistoDirectory(), name_, and process_.
Referenced by dqm::SimObjects::createCalorimeterHists(), dqm::SimObjects::createTrackerHists(), dqm::SimObjects::onProcessStart(), dqm::Trigger::onProcessStart(), dqm::TrigScintClusterDQM::onProcessStart(), dqm::TrigScintDQM::onProcessStart(), dqm::TrigScintHitDQM::onProcessStart(), dqm::TrigScintTrackDQM::onProcessStart(), dqm::HCalRawDigi::onProcessStart(), dqm::NtuplizeHgcrocDigiCollection::onProcessStart(), dqm::NtuplizeTrigScintQIEDigis::onProcessStart(), ecal::test::EcalCheckEnergyReconstruction::onProcessStart(), framework::test::TestAnalyzer::onProcessStart(), hcal::test::HcalCheckReconstruction::onProcessStart(), packing::FiberTrackerRawDecoder::onProcessStart(), packing::WRRawDecoder::onProcessStart(), and framework::Process::Process().
getLogFrequency()
int framework::EventProcessor::getLogFrequency () const
Get the current logging frequency from the process
Returns
int frequency logging should occurr
Definition at line 38 of file EventProcessor.cxx.
{
  return process_.getLogFrequency();
}
References framework::Process::getLogFrequency(), and process_.
getName()
std::string framework::EventProcessor::getName () const inline
Get the processor name
Definition at line 188 of file EventProcessor.h.
{ return name_; }
References name_.
Referenced by ecal::EcalTrigPrimDigiProducer::produce(), and hcal::HcalTrigPrimDigiProducer::produce().
getRunNumber()
int framework::EventProcessor::getRunNumber () const
Get the run number from the process
Returns
int run number
Definition at line 42 of file EventProcessor.cxx.
{ return process_.getRunNumber(); }
References framework::Process::getRunNumber(), and process_.
onFileClose()
virtual void framework::EventProcessor::onFileClose (EventFile & eventFile) inline virtual
Callback for the EventProcessor to take any necessary action when a event input ROOT file is closed.
Parameters
filename Input event ROOT file name
Note
This callback is rarely used.
Reimplemented in simcore::Simulator.
Definition at line 121 of file EventProcessor.h.
{}
onFileOpen()
virtual void framework::EventProcessor::onFileOpen (EventFile & eventFile) inline virtual
Callback for the EventProcessor to take any necessary action when a new event input ROOT file is opened.
Parameters
filename Input event ROOT file name.
Note
This callback is rarely used.
Definition at line 113 of file EventProcessor.h.
{}
onNewRun()
virtual void framework::EventProcessor::onNewRun (const ldmx::RunHeader & runHeader) inline virtual
Callback for the EventProcessor to take any necessary action when the run being processed changes.
Parameters
runHeader The RunHeader containing run information.
Reimplemented in recon::OverlayProducer, and simcore::Simulator.
Definition at line 105 of file EventProcessor.h.
{}
onProcessEnd()
virtual void framework::EventProcessor::onProcessEnd () inline virtual
Callback for the EventProcessor to take any necessary action when the processing of events finishes, such as calculating job-summary quantities.
Reimplemented in hcal::HcalPedestalAnalyzer, trigscint::QIEDecoder, trigscint::QIEEncoder, trigscint::TestBeamClusterProducer, trigscint::TrigScintClusterProducer, trigscint::TrigScintTrackProducer, packing::RawIO, simcore::Simulator, trigscint::QIEAnalyzer, and trigscint::TestBeamHitAnalyzer.
Definition at line 135 of file EventProcessor.h.
{}
onProcessStart()
virtual void framework::EventProcessor::onProcessStart () inline virtual
Callback for the EventProcessor to take any necessary action when the processing of events starts, such as creating histograms.
Reimplemented in dqm::PhotoNuclearDQM, dqm::RecoilTrackerDQM, dqm::SimObjects, dqm::Trigger, dqm::TrigScintClusterDQM, dqm::TrigScintDQM, dqm::TrigScintHitDQM, dqm::TrigScintTrackDQM, trigscint::QIEDecoder, trigscint::QIEEncoder, trigscint::TestBeamClusterProducer, trigscint::TrigScintClusterProducer, trigscint::TrigScintTrackProducer, dqm::HCalRawDigi, dqm::NtuplizeHgcrocDigiCollection, dqm::NtuplizeTrigScintQIEDigis, ecal::test::EcalCheckEnergyReconstruction, framework::test::TestAnalyzer, hcal::test::HcalCheckReconstruction, hcal::test::HcalCheckPositionMap, packing::FiberTrackerRawDecoder, packing::WRRawDecoder, recon::OverlayProducer, simcore::Simulator, tracking::sim::HitSmearingProcessor, trigscint::QIEAnalyzer, and trigscint::TestBeamHitAnalyzer.
Definition at line 128 of file EventProcessor.h.
{}
setStorageHint() [1/2]
void framework::EventProcessor::setStorageHint (framework::StorageControlHint hint) inline
Mark the current event as having the given storage control hint from this module
Parameters
controlhint The storage control hint to apply for the given event
Definition at line 160 of file EventProcessor.h.
{
    setStorageHint(hint, "");
  }
References setStorageHint().
Referenced by dqm::EcalDigiVerifier::analyze(), ecal::EcalVetoProcessor::produce(), hcal::HcalVetoProcessor::produce(), hcal::HcalWABVetoProcessor::produce(), recon::RecoilMissesEcalSkimmer::produce(), recon::TriggerProcessor::produce(), framework::test::TestProducer::produce(), hcal::HcalAlignPolarfires::produce(), and setStorageHint().
setStorageHint() [2/2]
void framework::EventProcessor::setStorageHint (framework::StorageControlHint hint, const std::string & purposeString)
Mark the current event as having the given storage control hint from this module and the given purpose string
Parameters
controlhint The storage control hint to apply for the given event
purposeString A purpose string which can be used in the skim control configuration
Definition at line 33 of file EventProcessor.cxx.
{
  process_.getStorageController().addHint(name_, hint, purposeString);
}
References framework::StorageControl::addHint(), framework::Process::getStorageController(), name_, and process_.
Member Data Documentation
histoDir_
TDirectory* framework::EventProcessor::histoDir_ {0} private
Histogram directory
Definition at line 242 of file EventProcessor.h.
Referenced by getHistoDirectory().
histograms_
HistogramHelper framework::EventProcessor::histograms_ protected
Interface class for making and filling histograms.
Definition at line 216 of file EventProcessor.h.
Referenced by dqm::EcalDigiVerifier::analyze(), dqm::EcalShowerFeatures::analyze(), dqm::HCalDQM::analyze(), dqm::HCalRawDigi::analyze(), dqm::RecoilTrackerDQM::analyze(), dqm::SimObjects::analyze(), dqm::Trigger::analyze(), dqm::TrigScintClusterDQM::analyze(), dqm::TrigScintDQM::analyze(), dqm::TrigScintHitDQM::analyze(), dqm::TrigScintTrackDQM::analyze(), dqm::PhotoNuclearDQM::analyze(), dqm::SimObjects::createCalorimeterHists(), createHistograms(), dqm::SimObjects::createTrackerHists(), dqm::PhotoNuclearDQM::onProcessStart(), dqm::SimObjects::onProcessStart(), dqm::Trigger::onProcessStart(), dqm::TrigScintClusterDQM::onProcessStart(), dqm::TrigScintDQM::onProcessStart(), dqm::TrigScintHitDQM::onProcessStart(), dqm::TrigScintTrackDQM::onProcessStart(), and dqm::HCalRawDigi::onProcessStart().
name_
std::string framework::EventProcessor::name_ private
The name of the EventProcessor.
Definition at line 239 of file EventProcessor.h.
Referenced by getHistoDirectory(), getName(), and setStorageHint().
ntuple_
NtupleManager& framework::EventProcessor::ntuple_ {NtupleManager::getInstance()} protected
Manager for any ntuples.
Definition at line 219 of file EventProcessor.h.
Referenced by ecal::test::EcalCheckEnergyReconstruction::analyze(), hcal::test::HcalCheckReconstruction::analyze(), ecal::test::EcalCheckEnergyReconstruction::onProcessStart(), and hcal::test::HcalCheckReconstruction::onProcessStart().
process_
Process& framework::EventProcessor::process_ private
Handle to the Process.
Definition at line 236 of file EventProcessor.h.
Referenced by getConditions(), getEventHeader(), getHistoDirectory(), getLogFrequency(), getRunNumber(), and setStorageHint().
theLog_
logging::logger framework::EventProcessor::theLog_ protected
The logger for this EventProcessor.
Definition at line 222 of file EventProcessor.h.
The documentation for this class was generated from the following files:
Framework/include/Framework/EventProcessor.h
Framework/src/Framework/EventProcessor.cxx