LDMX Software: dqm::HCalRawDigi Class Reference
dqm::HCalRawDigi Class Reference
Public Member Functions
HCalRawDigi (const std::string &name, framework::Process &process)
~HCalRawDigi ()
void configure (framework::config::Parameters &parameters) final override
void onProcessStart () final override
void analyze (const framework::Event &event)
Public Member Functions inherited from framework::Analyzer
Analyzer (const std::string &name, Process &process)
Public Member Functions inherited from framework::EventProcessor
EventProcessor (const std::string &name, Process &process)
virtual ~EventProcessor ()
virtual void onNewRun (const ldmx::RunHeader &runHeader)
virtual void onFileOpen (EventFile &eventFile)
virtual void onFileClose (EventFile &eventFile)
virtual void onProcessEnd ()
template<class T >
const T & getCondition (const std::string &condition_name)
TDirectory * getHistoDirectory ()
void setStorageHint (framework::StorageControlHint hint)
void setStorageHint (framework::StorageControlHint hint, const std::string &purposeString)
int getLogFrequency () const
int getRunNumber () const
std::string getName () const
void createHistograms (const std::vector< framework::config::Parameters > &histos)
Private Attributes
std::string input_name_
std::string input_pass_
Additional Inherited Members
Static Public Member Functions inherited from framework::EventProcessor
static void declare (const std::string &classname, int classtype, EventProcessorMaker *)
Static Public Attributes inherited from framework::Analyzer
static const int CLASSTYPE {2}
Protected Member Functions inherited from framework::EventProcessor
void abortEvent ()
Protected Attributes inherited from framework::EventProcessor
HistogramHelper histograms_
Interface class for making and filling histograms.
NtupleManager & ntuple_ {NtupleManager::getInstance()}
Manager for any ntuples.
logging::logger theLog_
The logger for this EventProcessor.
Detailed Description
Definition at line 25 of file HCalRawDigi.h.
Constructor & Destructor Documentation
HCalRawDigi()
dqm::HCalRawDigi::HCalRawDigi (const std::string & name, framework::Process & process) inline
Constructor
Definition at line 28 of file HCalRawDigi.h.
: framework::Analyzer(name, process) {}
~HCalRawDigi()
dqm::HCalRawDigi::~HCalRawDigi () inline
Destructor
Definition at line 31 of file HCalRawDigi.h.
{}
Member Function Documentation
analyze()
void dqm::HCalRawDigi::analyze (const framework::Event & event) virtual
Process the event and make histograms ro summaries.
Parameters
event The event to analyze.
we can do this incrementing of channel indices because the decoder uses a map which sorts by electronic ID and then adds the digis in sequence, so the order from event to event is the same without zero supp
Implements framework::Analyzer.
Definition at line 23 of file HCalRawDigi.cxx.
{
  auto digis{event.getObject<ldmx::HgcrocDigiCollection>(input_name_,input_pass_)};
  unsigned int i_digi{1};
  for (auto const& digi : digis) {
    for (unsigned int i_sample{0}; i_sample < digis.getNumSamplesPerDigi(); i_sample++) {
      histograms_.fill("adc_by_channel_sample"+std::to_string(i_sample),
          i_digi,digi.at(i_sample).adc_t());
    }
    i_digi++;
  }
}
References framework::HistogramHelper::fill(), and framework::EventProcessor::histograms_.
configure()
void dqm::HCalRawDigi::configure (framework::config::Parameters & parameters) final override virtual
Configure the processor using the given user specified parameters.
Parameters
parameters Set of parameters used to configure this processor.
Reimplemented from framework::EventProcessor.
Definition at line 8 of file HCalRawDigi.cxx.
{
  input_name_ = ps.getParameter<std::string>("input_name");
  input_pass_ = ps.getParameter<std::string>("input_pass");
}
References framework::config::Parameters::getParameter().
onProcessStart()
void dqm::HCalRawDigi::onProcessStart () final override virtual
Callback for the EventProcessor to take any necessary action when the processing of events starts, such as creating histograms.
Reimplemented from framework::EventProcessor.
Definition at line 13 of file HCalRawDigi.cxx.
{
  getHistoDirectory();
  for (unsigned int i_sample{0}; i_sample < 4; i_sample++) {
    histograms_.create("adc_by_channel_sample"+std::to_string(i_sample),
      "Arbitrary Channel Index", 250, 0, 250,
      "ADC Counts in Sample "+std::to_string(i_sample), 200, 0, 200);
    //histograms_.get("adc_by_channel_sample"+std::to_string(i_sample))->SetCanExtend(TH1::kAllAxes);
  }
}
References framework::HistogramHelper::create(), framework::EventProcessor::getHistoDirectory(), and framework::EventProcessor::histograms_.
Member Data Documentation
input_name_
std::string dqm::HCalRawDigi::input_name_ private
Definition at line 50 of file HCalRawDigi.h.
input_pass_
std::string dqm::HCalRawDigi::input_pass_ private
Definition at line 51 of file HCalRawDigi.h.
The documentation for this class was generated from the following files:
DQM/include/DQM/HCalRawDigi.h
DQM/src/DQM/HCalRawDigi.cxx