LDMX Software: ldmx::EcalVetoProcessor Class Reference
ldmx::EcalVetoProcessor Class Reference
Determines if event is vetoable using ECAL hit information.
#include <EcalVetoProcessor.h>
Public Types
typedef std::pair< int, int > LayerCellPair
typedef std::pair< int, float > CellEnergyPair
typedef std::pair< float, float > XYCoords
Public Member Functions
EcalVetoProcessor (const std::string &name, Process &process)
void configure (Parameters &parameters) final override
void produce (Event &event)
Public Member Functions inherited from ldmx::Producer
Producer (const std::string &name, Process &process)
Public Member Functions inherited from ldmx::EventProcessor
EventProcessor (const std::string &name, Process &process)
virtual ~EventProcessor ()
virtual void onNewRun (const RunHeader &runHeader)
virtual void onFileOpen (EventFile &eventFile)
virtual void onFileClose (EventFile &eventFile)
virtual void onProcessStart ()
virtual void onProcessEnd ()
TDirectory * getHistoDirectory ()
void setStorageHint (ldmx::StorageControlHint hint)
void setStorageHint (ldmx::StorageControlHint hint, const std::string &purposeString)
void createHistograms (const std::vector< Parameters > &histos)
Private Member Functions
bool isInShowerInnerRing (int centroidID, int probeID)
bool isInShowerOuterRing (int centroidID, int probeID)
XYCoords getCellCentroidXYPair (int centroidID)
std::vector< int > getInnerRingCellIds (int cellModuleID)
std::vector< int > getOuterRingCellIds (int cellModuleID)
void clearProcessor ()
LayerCellPair hitToPair (const EcalHit &hit)
int GetShowerCentroidIDAndRMS (const std::vector< EcalHit > &ecalRecHits, double &showerRMS)
void fillHitMap (const std::vector< EcalHit > &ecalRecHits, std::vector< std::map< int, float >> &cellMap_)
void fillIsolatedHitMap (const std::vector< EcalHit > &ecalRecHits, float globalCentroid, std::vector< std::map< int, float >> &cellMap_, std::vector< std::map< int, float >> &cellMapIso_, bool doTight=false)
std::vector< XYCoords > getTrajectory (std::vector< double > momentum, std::vector< float > position)
void buildBDTFeatureVector (const ldmx::EcalVetoResult &result)
Private Attributes
std::vector< std::map< int, float > > cellMap_
std::vector< std::map< int, float > > cellMapTightIso_
std::vector< float > ecalLayerEdepRaw_
std::vector< float > ecalLayerEdepReadout_
std::vector< float > ecalLayerTime_
std::vector< float > mapsx
std::vector< float > mapsy
int nEcalLayers_ {0}
int backEcalStartingLayer_ {0}
int nReadoutHits_ {0}
int deepestLayerHit_ {0}
int doBdt_ {0}
double summedDet_ {0}
double summedTightIso_ {0}
double maxCellDep_ {0}
double showerRMS_ {0}
double xStd_ {0}
double yStd_ {0}
double avgLayerHit_ {0}
double stdLayerHit_ {0}
double ecalBackEnergy_ {0}
double bdtCutVal_ {0}
EcalDetectorID detID_
bool verbose_ {false}
bool doesPassVeto_ {false}
std::unique_ptr< EcalHexReadout > hexReadout_
std::string bdtFileName_
std::string cellFileNamexy_
std::vector< float > bdtFeatures_
std::string collectionName_ {"EcalVeto"}
Additional Inherited Members
Static Public Member Functions inherited from ldmx::EventProcessor
static void declare (const std::string &classname, int classtype, EventProcessorMaker *)
Static Public Attributes inherited from ldmx::Producer
static const int CLASSTYPE {1}
Protected Member Functions inherited from ldmx::EventProcessor
void abortEvent ()
Protected Attributes inherited from ldmx::EventProcessor
Process & process_
HistogramHelper histograms_
Interface class for making and filling histograms.
NtupleManager & ntuple_ {NtupleManager::getInstance()}
Manager for any ntuples.
logging::logger theLog_
The logger for this EventProcessor.
Detailed Description
Determines if event is vetoable using ECAL hit information.
Definition at line 31 of file EcalVetoProcessor.h.
Member Function Documentation
configure()
void ldmx::EcalVetoProcessor::configure (Parameters & parameters) final override virtual
Configure the processor using the given user specified parameters.
Parameters
parameters Set of parameters used to configure this processor.
Reimplemented from ldmx::EventProcessor.
Definition at line 63 of file EcalVetoProcessor.cxx.
{
         doBdt_ = parameters.getParameter< bool >("do_bdt");
         if (doBdt_){
 #ifdef LDMX_USE_ONNXRUNTIME
             rt_ = std::make_unique<Ort::ONNXRuntime>(parameters.getParameter<std::string>("bdt_file"));
 #else
             EXCEPTION_RAISE("EcalVetoProcessor",
                             "Cannot run BDT because ONNXRuntime is not installed.");
 #endif
         }
         cellFileNamexy_ = parameters.getParameter< std::string >("cellxy_file");
         if (!std::ifstream(cellFileNamexy_).good()) {
             EXCEPTION_RAISE("EcalVetoProcessor",
                             "The specified x,y cell file '" + cellFileNamexy_ + "' does not exist!");
         } else {
             std::ifstream cellxyfile(cellFileNamexy_);
             float valuex;
             float valuey;
             while ( cellxyfile >> valuex >> valuey) {
                 mapsx.push_back(valuex);
                 mapsy.push_back(valuey);
             }
         }
         // These are the v12 parameters
         //  all distances in mm
         double moduleRadius = 85.0; //same as default
         int    numCellsWide = 23; //same as default
         double moduleGap = 1.0;
         double ecalFrontZ = 220;
         std::vector<double> ecalSensLayersZ = {
              7.850,
             13.300,
             26.400,
             33.500,
             47.950,
             56.550,
             72.250,
             81.350,
             97.050,
             106.150,
             121.850,
             130.950,
             146.650,
             155.750,
             171.450,
             180.550,
             196.250,
             205.350,
             221.050,
             230.150,
             245.850,
             254.950,
             270.650,
             279.750,
             298.950,
             311.550,
             330.750,
             343.350,
             362.550,
             375.150,
             394.350,
             406.950,
             426.150,
             438.750
         };
         hexReadout_ = std::make_unique<EcalHexReadout>(
                 moduleRadius,
                 moduleGap,
                 numCellsWide,
                 ecalSensLayersZ,
                 ecalFrontZ
                 );
         nEcalLayers_ = parameters.getParameter< int >("num_ecal_layers");
         bdtCutVal_ = parameters.getParameter< double >("disc_cut");
         ecalLayerEdepRaw_.resize(nEcalLayers_, 0);
         ecalLayerEdepReadout_.resize(nEcalLayers_, 0);
         ecalLayerTime_.resize(nEcalLayers_, 0);
         cellMap_.resize(nEcalLayers_, std::map<int, float>());
         cellMapTightIso_.resize(nEcalLayers_, std::map<int, float>());
         // Set the collection name as defined in the configuration
         collectionName_ = parameters.getParameter< std::string >("collection_name");
     }
References collectionName_, EXCEPTION_RAISE, and ldmx::Parameters::getParameter().
isInShowerInnerRing()
bool ldmx::EcalVetoProcessor::isInShowerInnerRing (int centroidID, int probeID) inline private
Wrappers for ecalHexReadout functions. See hitToPair(). Necessary to easily combine cellID with moduleID to get unique ID of hit in layer. In future: combine celID+moduleID+layerID.
Definition at line 62 of file EcalVetoProcessor.h.
{
                 return hexReadout_->isNN(centroidID, probeID);
             }
produce()
void ldmx::EcalVetoProcessor::produce (Event & event) virtual
Process the event and put new data products into it.
Parameters
event The Event to process.
Implements ldmx::Producer.
Definition at line 177 of file EcalVetoProcessor.cxx.
{
         EcalVetoResult result;
         clearProcessor();
         // Get the collection of Ecal scoring plane hits. If it doesn't exist,
         // don't bother adding any truth tracking information.
         std::vector<double> recoilP;
         std::vector<float> recoilPos;
         std::vector<double> recoilPAtTarget;
         std::vector<float> recoilPosAtTarget;
         if (event.exists("EcalScoringPlaneHits")) {
             //
             // Loop through all of the sim particles and find the recoil electron.
             //
             // Get the collection of simulated particles from the event
             auto particleMap{event.getMap< int, SimParticle >("SimParticles")};
             // Search for the recoil electron
             auto [recoilTrackID, recoilElectron] = Analysis::getRecoil(particleMap);
             // Find ECAL SP hit for recoil electron
             auto ecalSpHits{event.getCollection< SimTrackerHit >( "EcalScoringPlaneHits" )};
             float pmax = 0;
             for ( SimTrackerHit &spHit : ecalSpHits ) {
                 if (spHit.getLayerID() != 31 || spHit.getMomentum()[2] <= 0) continue;
                 if (spHit.getTrackID() == recoilTrackID) {
                     if(sqrt(pow(spHit.getMomentum()[0],2) + pow(spHit.getMomentum()[1],2) + pow(spHit.getMomentum()[2],2)) > pmax) {
                         recoilP = spHit.getMomentum();
                         recoilPos = spHit.getPosition();
                         pmax = sqrt(pow(recoilP[0],2) + pow(recoilP[1],2) + pow(recoilP[2],2));
                     }
                 }
             }
             // Find target SP hit for recoil electron
             if (event.exists("TargetScoringPlaneHits")) {
                 std::vector< SimTrackerHit > targetSpHits = event.getCollection< SimTrackerHit >( "TargetScoringPlaneHits" );
                 pmax = 0;
                 for ( SimTrackerHit &spHit : targetSpHits ) {
                     if (spHit.getLayerID() != 1 || spHit.getMomentum()[2] <= 0) continue;
                     if (spHit.getTrackID() == recoilTrackID) {
                         if(sqrt(pow(spHit.getMomentum()[0],2) + pow(spHit.getMomentum()[1],2) + pow(spHit.getMomentum()[2],2)) > pmax) {
                             recoilPAtTarget = spHit.getMomentum();
                             recoilPosAtTarget = spHit.getPosition();
                             pmax = sqrt(pow(recoilPAtTarget[0],2) + pow(recoilPAtTarget[1],2) + pow(recoilPAtTarget[2],2));
                         }
                     }
                 }
             }
         }
         // Get projected trajectories for electron and photon
         std::vector<XYCoords> ele_trajectory, photon_trajectory;
         if(recoilP.size() > 0) {
             ele_trajectory = getTrajectory(recoilP, recoilPos);
             std::vector<double> pvec = recoilPAtTarget.size() ? recoilPAtTarget : std::vector<double>{0.0, 0.0, 0.0};
             std::vector<float>  posvec = recoilPosAtTarget.size() ? recoilPosAtTarget : std::vector<float>{0.0, 0.0, 0.0};
             photon_trajectory = getTrajectory({-pvec[0], -pvec[1], 4000.0 - pvec[2]}, posvec);
         }
         float recoilPMag = recoilP.size() ? sqrt(pow(recoilP[0],2) + pow(recoilP[1],2) + pow(recoilP[2],2)) : -1.0;
         float recoilTheta = recoilPMag > 0 ? recoilP[2]/recoilPMag : -1.0;
         std::vector<double> ele_radii = radius68_thetalt10_plt500;
         if(recoilTheta<10 && recoilPMag >= 500) ele_radii = radius68_thetalt10_pgt500;
         else if(recoilTheta>=10 && recoilTheta<20) ele_radii = radius68_theta10to20;
         else if(recoilTheta>=20) ele_radii = radius68_thetagt20;
         // Use default binning
         std::vector<double> photon_radii = radius68_thetalt10_plt500;
         // Get the collection of digitized Ecal hits from the event.
         const std::vector< EcalHit > ecalRecHits = event.getCollection< EcalHit >( "EcalRecHits" );
         int globalCentroid = GetShowerCentroidIDAndRMS( ecalRecHits , showerRMS_);
         /* ~~ Fill the hit map ~~ O(n)  */
         fillHitMap( ecalRecHits , cellMap_);
         bool doTight = true;
         /* ~~ Fill the isolated hit maps ~~ O(n)  */
         fillIsolatedHitMap( ecalRecHits , globalCentroid, cellMap_, cellMapTightIso_, doTight);
         //Loop over the hits from the event to calculate the rest of the important quantities
         float wavgLayerHit = 0;
         float xMean = 0;
         float yMean = 0;
         // Containment variables
         unsigned int nregions = 5;
         std::vector<float> electronContainmentEnergy (nregions, 0.0);
         std::vector<float> photonContainmentEnergy (nregions, 0.0);
         std::vector<float> outsideContainmentEnergy (nregions, 0.0);
         std::vector<int>   outsideContainmentNHits (nregions, 0);
         std::vector<float> outsideContainmentXmean (nregions, 0.0);
         std::vector<float> outsideContainmentYmean (nregions, 0.0);
         std::vector<float> outsideContainmentXstd (nregions, 0.0);
         std::vector<float> outsideContainmentYstd (nregions, 0.0);
         for ( const EcalHit &hit : ecalRecHits ) {
             //Layer-wise quantities
             LayerCellPair hit_pair = hitToPair(hit);
             ecalLayerEdepRaw_[hit_pair.first] = ecalLayerEdepRaw_[hit_pair.first] + hit.getEnergy();
             if(hit.getLayer() >= 20)
                 ecalBackEnergy_ += hit.getEnergy();
             if (maxCellDep_ < hit.getEnergy())
                 maxCellDep_ = hit.getEnergy();
             if (hit.getEnergy() > 0) {
                 nReadoutHits_++;
                 ecalLayerEdepReadout_[hit_pair.first] += hit.getEnergy();
                 ecalLayerTime_[hit_pair.first] += (hit.getEnergy()) * hit.getTime();
                 xMean += getCellCentroidXYPair(hit_pair.second).first * hit.getEnergy();
                 yMean += getCellCentroidXYPair(hit_pair.second).second * hit.getEnergy();
                 avgLayerHit_ += hit.getLayer();
                 wavgLayerHit += hit.getLayer() * hit.getEnergy();
                 if (deepestLayerHit_ < hit.getLayer()) {
                     deepestLayerHit_ = hit.getLayer();
                 }
                 XYCoords xy_pair = getCellCentroidXYPair(hit_pair.second);
                 float distance_ele_trajectory = ele_trajectory.size() ? sqrt( pow((xy_pair.first - ele_trajectory[hit.getLayer()].first),2) + pow((xy_pair.second - ele_trajectory[hit.getLayer()].second),2) ) : -1.0;
                 float distance_photon_trajectory = photon_trajectory.size() ? sqrt( pow((xy_pair.first - photon_trajectory[hit.getLayer()].first),2) + pow((xy_pair.second - photon_trajectory[hit.getLayer()].second),2) ) : -1.0;
                 // Decide which region a hit goes into and add to sums
                 for(unsigned int ireg = 0; ireg < nregions; ireg++) {
                     if(distance_ele_trajectory >= ireg*ele_radii[hit.getLayer()] && distance_ele_trajectory < (ireg+1)*ele_radii[hit.getLayer()])
                         electronContainmentEnergy[ireg] += hit.getEnergy();
                     if(distance_photon_trajectory >= ireg*photon_radii[hit.getLayer()] && distance_photon_trajectory < (ireg+1)*photon_radii[hit.getLayer()])
                         photonContainmentEnergy[ireg] += hit.getEnergy();
                     if(distance_ele_trajectory > (ireg+1)*ele_radii[hit.getLayer()] && distance_photon_trajectory > (ireg+1)*photon_radii[hit.getLayer()]) {
                         outsideContainmentEnergy[ireg] += hit.getEnergy();
                         outsideContainmentNHits[ireg] += 1;
                         outsideContainmentXmean[ireg] += xy_pair.first*hit.getEnergy();
                         outsideContainmentYmean[ireg] += xy_pair.second*hit.getEnergy();
                     }
                 }
             }
         }
         for (int iLayer = 0; iLayer < ecalLayerEdepReadout_.size(); iLayer++) {
             for (auto cell : cellMapTightIso_[iLayer]) {
                 if (cell.second > 0) {
                     summedTightIso_ += cell.second;
                 }
             }
             ecalLayerTime_[iLayer] = ecalLayerTime_[iLayer] / ecalLayerEdepReadout_[iLayer];
             summedDet_ += ecalLayerEdepReadout_[iLayer];
         }
         if (nReadoutHits_ > 0) {
             avgLayerHit_ /= nReadoutHits_;
             wavgLayerHit /= summedDet_;
             xMean /= summedDet_;
             yMean /= summedDet_;
         } else {
             wavgLayerHit = 0;
             avgLayerHit_ = 0;
             xMean = 0;
             yMean = 0;
         }
         for(unsigned int ireg = 0; ireg < nregions; ireg++) {
             if(outsideContainmentEnergy[ireg] > 0) {
                 outsideContainmentXmean[ireg] /= outsideContainmentEnergy[ireg];
                 outsideContainmentYmean[ireg] /= outsideContainmentEnergy[ireg];
             }
         }
         // Loop over hits a second time to find the standard deviations.
         for ( const EcalHit &hit : ecalRecHits ) {
             LayerCellPair hit_pair = hitToPair(hit);
             if (hit.getEnergy() > 0) {
                 xStd_ += pow((getCellCentroidXYPair(hit_pair.second).first - xMean), 2) * hit.getEnergy();
                 yStd_ += pow((getCellCentroidXYPair(hit_pair.second).second - yMean), 2) * hit.getEnergy();
                 stdLayerHit_ += pow((hit.getLayer() - wavgLayerHit), 2) * hit.getEnergy();
             }
             XYCoords xy_pair = getCellCentroidXYPair(hit_pair.second);
             float distance_ele_trajectory = ele_trajectory.size() ? sqrt( pow((xy_pair.first - ele_trajectory[hit.getLayer()].first),2) + pow((xy_pair.second - ele_trajectory[hit.getLayer()].second),2) ) : -1.0;
             float distance_photon_trajectory = photon_trajectory.size() ? sqrt( pow((xy_pair.first - photon_trajectory[hit.getLayer()].first),2) + pow((xy_pair.second - photon_trajectory[hit.getLayer()].second),2) ) : -1.0;
             for(unsigned int ireg = 0; ireg < nregions; ireg++) {
                 if(distance_ele_trajectory > (ireg+1)*ele_radii[hit.getLayer()] && distance_photon_trajectory > (ireg+1)*photon_radii[hit.getLayer()]) {
                     outsideContainmentXstd[ireg] += pow((xy_pair.first - outsideContainmentXmean[ireg]),2) * hit.getEnergy();
                     outsideContainmentYstd[ireg] += pow((xy_pair.second - outsideContainmentYmean[ireg]),2) * hit.getEnergy();
                 }
             }
         }
         if (nReadoutHits_ > 0) {
             xStd_ = sqrt (xStd_ / summedDet_);
             yStd_ = sqrt (yStd_ / summedDet_);
             stdLayerHit_ = sqrt (stdLayerHit_ / summedDet_);
         } else {
             xStd_ = 0;
             yStd_ = 0;
             stdLayerHit_ = 0;
         }
         for(unsigned int ireg = 0; ireg < nregions; ireg++) {
             if(outsideContainmentEnergy[ireg] > 0) {
                 outsideContainmentXstd[ireg] = sqrt(outsideContainmentXstd[ireg]/outsideContainmentEnergy[ireg]);
                 outsideContainmentYstd[ireg] = sqrt(outsideContainmentYstd[ireg]/outsideContainmentEnergy[ireg]);
             }
         }
         // end loop over sim hits
         /* Code for fiducial region below */
         std::vector<float> faceXY(2);
         if (!recoilP.empty() && recoilP[2] != 0) {
             faceXY[0] = ((223.8 - 220.0) * (recoilP[0] / recoilP[2])) + recoilPos[0];
             faceXY[1] = ((223.8 - 220.0) * (recoilP[1] / recoilP[2])) + recoilPos[1];
         } else {
             faceXY[0] = -9999.0;
             faceXY[1] = -9999.0;
         }
         int inside = 0;
         int up = 0;
         int step = 0;
         int index;
         float cell_radius = 5.0;
         std::vector<float>::iterator it;
         it = std::lower_bound(mapsx.begin(), mapsx.end(), faceXY[0]);
         index = std::distance( mapsx.begin(), it);
         if (index == mapsx.size()) {
             index += -1;
         }
         if (!recoilP.empty() && faceXY[0] != -9999.0) {
             while (true) {
                 std::vector<double> dis(2);
                 dis[0] = faceXY[0] - mapsx[index + step];
                 dis[1] = faceXY[1] - mapsy[index + step];
                 float celldis = sqrt (pow(dis[0],2) + pow(dis[1],2));
                 if (celldis <= cell_radius) {
                     inside = 1;
                     break;
                 }
                 if ((abs(dis[0]) > 5 && up == 0) || index + step == mapsx.size()-1) {
                     up = 1;
                     step = 0;
                 } else if ((abs(dis[0]) > 5 && up == 1) || (index + step == 0 && up == 1)) {
                     break;
                 }
                 if (up == 0) {
                     step += 1;
                 } else {
                     step += -1;
                 }
             }
         }
         result.setVariables(nReadoutHits_, deepestLayerHit_, summedDet_, summedTightIso_, maxCellDep_,
             showerRMS_, xStd_, yStd_, avgLayerHit_, stdLayerHit_, ecalBackEnergy_, electronContainmentEnergy, photonContainmentEnergy, outsideContainmentEnergy, outsideContainmentNHits, outsideContainmentXstd, outsideContainmentYstd, ecalLayerEdepReadout_, recoilP, recoilPos);
 #ifdef LDMX_USE_ONNXRUNTIME
         if (doBdt_) {
             buildBDTFeatureVector(result);
             Ort::FloatArrays inputs({bdtFeatures_});
             float pred = rt_->run({"features"}, inputs, {"probabilities"})[0].at(1);
             result.setVetoResult(pred > bdtCutVal_);
             result.setDiscValue(pred);
             //std::cout << "  pred > bdtCutVal = " << (pred > bdtCutVal_) << std::endl;
             // If the event passes the veto, keep it. Otherwise,
             // drop the event.
             if (result.passesVeto() && inside) {
                 setStorageHint(hint_shouldKeep);
             } else {
                 setStorageHint(hint_shouldDrop);
             }
         }
 #endif
         if (inside) {
             setStorageHint(hint_shouldKeep);
         } else {
             setStorageHint(hint_shouldDrop);
         }
         event.add( collectionName_, result );
     }
References collectionName_, ldmx::Event::exists(), ldmx::SimTrackerHit::getMomentum(), ldmx::EcalVetoResult::passesVeto(), ldmx::EventProcessor::setStorageHint(), and ldmx::EcalVetoResult::setVariables().
Member Data Documentation
collectionName_
std::string ldmx::EcalVetoProcessor::collectionName_ {"EcalVeto"} private
Name of the collection which will containt the results.
Definition at line 141 of file EcalVetoProcessor.h.
Referenced by configure(), and produce().
The documentation for this class was generated from the following files:
Ecal/include/Ecal/EcalVetoProcessor.h
Ecal/src/EcalVetoProcessor.cxx