LDMX Software: ldmx::RunManager Class Reference
ldmx::RunManager Class Reference
Extension of Geant4 run manager.
#include <RunManager.h>
Public Member Functions
RunManager (Parameters &parameters, ConditionsInterface &ci)
virtual ~RunManager ()
void setupPhysics ()
void Initialize ()
void TerminateOneEvent ()
DetectorConstruction * getDetectorConstruction ()
void setUseRootSeed (bool useIt=true)
bool useRootSeed ()
Private Attributes
Parameters parameters_
The set of parameters used to configure the RunManager.
G4PhysListFactory physicsListFactory_
bool isPWEnabled_ {false}
std::string parallelWorldPath_ {""}
bool useRootSeed_ {false}
ConditionsInterface & conditionsIntf_
Detailed Description
Extension of Geant4 run manager.
Definition at line 40 of file RunManager.h.
Constructor & Destructor Documentation
RunManager()
ldmx::RunManager::RunManager (Parameters & parameters, ConditionsInterface & ci)
Class constructor.
Definition at line 36 of file RunManager.cxx.
                                                                           : conditionsIntf_(ci) {
         parameters_ = parameters;
         // Set whether the ROOT primary generator should use the persisted seed.
         auto rootPrimaryGenUseSeed{parameters.getParameter< bool >("rootPrimaryGenUseSeed")};
         // Validate the geometry if specified.
         setUseRootSeed(rootPrimaryGenUseSeed);
     }
References ldmx::Parameters::getParameter(), parameters_, and setUseRootSeed().
~RunManager()
ldmx::RunManager::~RunManager () virtual
Class destructor.
Definition at line 48 of file RunManager.cxx.
{
     }
Member Function Documentation
getDetectorConstruction()
DetectorConstruction * ldmx::RunManager::getDetectorConstruction ()
Get the user detector construction cast to a specific type.
Returns
The user detector construction.
Definition at line 148 of file RunManager.cxx.
{
         return static_cast<DetectorConstruction*>(this->userDetector);
     }
Referenced by Initialize().
Initialize()
void ldmx::RunManager::Initialize ()
Perform application initialization.
Definition at line 84 of file RunManager.cxx.
{
         setupPhysics();
         // The parallel world needs to be registered before the mass world is
         // constructed i.e. before G4RunManager::Initialize() is called.
         if (isPWEnabled_) {
             std::cout << "[ RunManager ]: Parallel worlds have been enabled." << std::endl;
             auto validateGeometry_{parameters_.getParameter< bool >("validate_detector")};
             G4GDMLParser* pwParser = new G4GDMLParser();
             pwParser->Read(parallelWorldPath_, validateGeometry_);
             this->getDetectorConstruction()->RegisterParallelWorld(new ParallelWorld(pwParser, "ldmxParallelWorld", conditionsIntf_));
         }
         G4RunManager::Initialize();
         // Instantiate the primary generator action
         auto primaryGeneratorAction{ new PrimaryGeneratorAction(parameters_) };
         SetUserAction( primaryGeneratorAction );
         // Instantiate action manager
         auto actionManager{UserActionManager::getInstance()};
         // Get instances of all G4 actions
         //      also create them in the action manager
         auto actions{actionManager.getActions()};
         // Create all user actions
         auto userActions{parameters_.getParameter< std::vector< Parameters > >("actions",{})};
         for ( auto& userAction : userActions ) {
             actionManager.createAction(
                     userAction.getParameter<std::string>("class_name"),
                     userAction.getParameter<std::string>("instance_name"),
                     userAction
                     );
         }
         // Register all actions with the G4 engine
         for (const auto& [key, act] : actions) {
             std::visit([this](auto&& arg) { this->SetUserAction(arg); }, act);
         }
     }
References conditionsIntf_, getDetectorConstruction(), ldmx::UserActionManager::getInstance(), ldmx::Parameters::getParameter(), isPWEnabled_, parallelWorldPath_, parameters_, and setupPhysics().
setupPhysics()
void ldmx::RunManager::setupPhysics ()
Initialize physics.
Definition at line 51 of file RunManager.cxx.
{
         auto pList{physicsListFactory_.GetReferencePhysList("FTFP_BERT")};
         parallelWorldPath_ = parameters_.getParameter<std::string>("scoringPlanes");
         isPWEnabled_ = !parallelWorldPath_.empty();
         if ( isPWEnabled_ ) {
             std::cout << "[ RunManager ]: Parallel worlds physics list has been registered." << std::endl;
             pList->RegisterPhysics(new G4ParallelWorldPhysics("ldmxParallelWorld"));
         }
         pList->RegisterPhysics(new GammaPhysics);
         pList->RegisterPhysics(new APrimePhysics( parameters_ ));
         auto biasingEnabled{parameters_.getParameter< bool >("biasing_enabled")};
         if (biasingEnabled) {
             auto biasedParticle{parameters_.getParameter< std::string >("biasing_particle")};
             std::cout << "RunManager::setupPhysics : Enabling biasing of particle type " << biasedParticle << std::endl;
             // Instantiate the constructor used when biasing
             G4GenericBiasingPhysics* biasingPhysics = new G4GenericBiasingPhysics();
             // Specify what particles are being biased
             biasingPhysics->Bias(biasedParticle);
             // Register the physics constructor to the physics list:
             pList->RegisterPhysics(biasingPhysics);
         }
         this->SetUserInitialization(pList);
     }
References ldmx::Parameters::getParameter(), isPWEnabled_, parallelWorldPath_, parameters_, and physicsListFactory_.
Referenced by Initialize().
setUseRootSeed()
void ldmx::RunManager::setUseRootSeed (bool useIt = true) inline
Tell RunManager to use the seed from the root file.
Definition at line 82 of file RunManager.h.
 { useRootSeed_ = useIt; }
References useRootSeed_.
Referenced by RunManager().
TerminateOneEvent()
void ldmx::RunManager::TerminateOneEvent ()
Called at the end of each event.
Runs parent process G4RunManager::TerminateOneEvent() and resets the activation for the G4eDarkBremsstrahlung process (if dark brem is possible)
Definition at line 128 of file RunManager.cxx.
{
         //have geant4 do its own thing
         G4RunManager::TerminateOneEvent();
         //reset dark brem process (if needed)
         G4ProcessTable* ptable = G4ProcessTable::GetProcessTable();
         G4int verbosity = ptable->GetVerboseLevel();
         ptable->SetVerboseLevel(0); //silent ptable while searching for process that may/may not exist
         G4String pname = "biasWrapper(eDBrem)"; //TODO allow eDBrem to be biased or unbiased
         bool active = true;
         ptable->SetProcessActivation(pname,active);
         if ( this->GetVerboseLevel() > 1 ) {
             std::cout << "[ RunManager ] : "
                 << "Reset the dark brem process (if it was activated)." << std::endl;
         }
         ptable->SetVerboseLevel(verbosity);
     }
useRootSeed()
bool ldmx::RunManager::useRootSeed () inline
Should we use the seed from the root file?
Definition at line 87 of file RunManager.h.
 { return useRootSeed_; }
References useRootSeed_.
Member Data Documentation
conditionsIntf_
ConditionsInterface& ldmx::RunManager::conditionsIntf_ private
ConditionsInterface
Definition at line 115 of file RunManager.h.
Referenced by Initialize().
isPWEnabled_
bool ldmx::RunManager::isPWEnabled_ {false} private
Flag indicating whether a parallel world should be registered
Definition at line 103 of file RunManager.h.
Referenced by Initialize(), and setupPhysics().
parallelWorldPath_
std::string ldmx::RunManager::parallelWorldPath_ {""} private
Path to GDML description of parallel world.
Definition at line 106 of file RunManager.h.
Referenced by Initialize(), and setupPhysics().
physicsListFactory_
G4PhysListFactory ldmx::RunManager::physicsListFactory_ private
Factory class for instantiating the physics list.
Definition at line 97 of file RunManager.h.
Referenced by setupPhysics().
useRootSeed_
bool ldmx::RunManager::useRootSeed_ {false} private
Should we use random seed from root file?
Definition at line 111 of file RunManager.h.
Referenced by setUseRootSeed(), and useRootSeed().
The documentation for this class was generated from the following files:
SimCore/include/SimCore/RunManager.h
SimCore/src/SimCore/RunManager.cxx