LDMX Software: ldmx::EcalSD Class Reference
ldmx::EcalSD Class Reference
ECal sensitive detector that uses an EcalHexReadout to create the hits.
#include <EcalSD.h>
Public Member Functions
EcalSD (G4String name, G4String theCollectionName, int subDetID)
virtual ~EcalSD ()
G4bool ProcessHits (G4Step *aStep, G4TouchableHistory *ROhist)
Public Member Functions inherited from ldmx::CalorimeterSD
CalorimeterSD (G4String name, G4String theCollectionName)
virtual ~CalorimeterSD ()
void setLayerDepth (int layerDepth)
void Initialize (G4HCofThisEvent *hcEvent)
void EndOfEvent (G4HCofThisEvent *hcEvent)
Private Member Functions
G4ThreeVector getHitPosition (G4Step *aStep)
Private Attributes
std::unique_ptr< EcalHexReadout > hitMap_
std::map< G4VSolid *, G4Polyhedron * > polyMap_
Additional Inherited Members
Protected Attributes inherited from ldmx::CalorimeterSD
G4CalorimeterHitsCollection * hitsCollection_
int subdet_
DetectorID * detID_
int layerDepth_ {2}
Detailed Description
ECal sensitive detector that uses an EcalHexReadout to create the hits.
Definition at line 27 of file EcalSD.h.
Constructor & Destructor Documentation
EcalSD()
ldmx::EcalSD::EcalSD (G4String name, G4String theCollectionName, int subDetID)
Class constructor.
Parameters
name The name of the sensitive detector.
theCollectionName The name of the hits collection.
subDetID The subdetector ID.
Definition at line 18 of file EcalSD.cxx.
                                                                           :
             CalorimeterSD(name, theCollectionName) {
         detID_ = new EcalDetectorID();
         detID_->setFieldValue("subdet", subDetID);
         // These are the v12 parameters
         //  all distances in mm
         double moduleRadius = 85.0; //same as default
         int    numCellsWide = 23; //same as default
         double moduleGap = 1.0;
         double ecalFrontZ = 220;
         std::vector<double> ecalSensLayersZ = {
              7.850,
             13.300,
             26.400,
             33.500,
             47.950,
             56.550,
             72.250,
             81.350,
             97.050,
             106.150,
             121.850,
             130.950,
             146.650,
             155.750,
             171.450,
             180.550,
             196.250,
             205.350,
             221.050,
             230.150,
             245.850,
             254.950,
             270.650,
             279.750,
             298.950,
             311.550,
             330.750,
             343.350,
             362.550,
             375.150,
             394.350,
             406.950,
             426.150,
             438.750
         };
         hitMap_ = std::make_unique<EcalHexReadout>(
                 moduleRadius,
                 moduleGap,
                 numCellsWide,
                 ecalSensLayersZ,
                 ecalFrontZ
                 );
     }
References ldmx::CalorimeterSD::detID_, hitMap_, and ldmx::DetectorID::setFieldValue().
~EcalSD()
ldmx::EcalSD::~EcalSD () virtual
Class destructor.
Definition at line 76 of file EcalSD.cxx.
                     {
         delete detID_;
     }
References ldmx::CalorimeterSD::detID_.
Member Function Documentation
getHitPosition()
G4ThreeVector ldmx::EcalSD::getHitPosition (G4Step * aStep) private
Return the hit position of a step. X and Y are computed from the midpoint of the step. Z corresponds to the volume's center.
Returns
The hit position from the step.
Set initial hit position from midpoint of the step.
Use facet info of the solid for setting Z to the sensor midpoint.
Definition at line 144 of file EcalSD.cxx.
{
         G4StepPoint* prePoint = aStep->GetPreStepPoint();
         G4StepPoint* postPoint = aStep->GetPostStepPoint();
         G4ThreeVector position = 0.5 * (prePoint->GetPosition() + postPoint->GetPosition());
         /*
          * Get the volume position in global coordinates, which for the ECal is the center of
          * the front face of the sensor.
          */
         G4ThreeVector volumePosition = aStep->GetPreStepPoint()->GetTouchableHandle()->GetHistory()->GetTopTransform().Inverse().TransformPoint(G4ThreeVector());
         // Get the solid from this step.
         G4VSolid* solid = prePoint->GetTouchableHandle()->GetVolume()->GetLogicalVolume()->GetSolid();
         auto it = polyMap_.find(solid);
         G4Polyhedron* poly;
         if (it == polyMap_.end()) {
             poly = solid->CreatePolyhedron();
             polyMap_[solid] = poly;
         } else {
             poly = polyMap_[solid];
         }
         G4Point3D iNodes[4];
         G4int n;
         poly->GetFacet(1, n, iNodes);
         G4double zstart = iNodes[1][2];
         G4double zend = iNodes[0][2];
         G4double zmid = (zstart - zend) / 2;
         position.setZ(volumePosition.z() + zmid);
         return position;
     }
References polyMap_.
Referenced by ProcessHits().
ProcessHits()
G4bool ldmx::EcalSD::ProcessHits (G4Step * aStep, G4TouchableHistory * ROhist) virtual
Process steps to create hits.
Parameters
aStep The step information.
ROhist The readout history.
Implements ldmx::CalorimeterSD.
Definition at line 80 of file EcalSD.cxx.
{
         // Determine if current particle of this step is a Geantino.
         G4ParticleDefinition* pdef = aStep->GetTrack()->GetDefinition();
         bool isGeantino = false;
         if (pdef == G4Geantino::Definition() || pdef == G4ChargedGeantino::Definition()) {
             isGeantino = true;
         }
         // Get the edep from the step.
         G4double edep = aStep->GetTotalEnergyDeposit();
         // Skip steps with no energy dep which come from non-Geantino particles.
         if (edep == 0.0 && !isGeantino) {
             if (verboseLevel > 2) {
                 G4cout << "CalorimeterSD skipping step with zero edep." << G4endl << G4endl;
             }
             return false;
         }
         // Create a new cal hit.
         G4CalorimeterHit* hit = new G4CalorimeterHit();
         // Set the edep.
         hit->setEdep(edep);
         // Compute the hit position using the utility function.
         G4ThreeVector hitPosition = getHitPosition(aStep);
         hit->setPosition(hitPosition.x(), hitPosition.y(), hitPosition.z());
         // Set the global time.
         hit->setTime(aStep->GetTrack()->GetGlobalTime());
         // Create the ID for the hit.
         int cpynum = aStep->GetPreStepPoint()->GetTouchableHandle()->GetHistory()->GetVolume(layerDepth_)->GetCopyNo();
         int layerNumber;
         layerNumber = int(cpynum/7);
         int module_position = cpynum%7;
         int cellModuleID = hitMap_->getCellModuleID(hitPosition[0], hitPosition[1]);
         int cellID = (hitMap_->separateID(cellModuleID)).first;
         detID_->setFieldValue(1, layerNumber);
         detID_->setFieldValue(2, module_position);
         detID_->setFieldValue(3, cellID);
         hit->setID(detID_->pack());
         // Set the track ID on the hit.
         hit->setTrackID(aStep->GetTrack()->GetTrackID());
         // Set the PDG code from the track.
         hit->setPdgCode(aStep->GetTrack()->GetParticleDefinition()->GetPDGEncoding());
         if (this->verboseLevel > 2) {
             G4cout << "Created new SimCalorimeterHit in detector " << this->GetName() << " with subdet ID " << subdet_ << " and layer " << layerNumber << " and cellid " << cellID << " module position " << module_position << " ...";
             hit->Print();
             G4cout << G4endl;
         }
         // Insert the hit into the hits collection.
         hitsCollection_->insert(hit);
         return true;
     }
References ldmx::CalorimeterSD::detID_, getHitPosition(), hitMap_, ldmx::CalorimeterSD::hitsCollection_, ldmx::CalorimeterSD::layerDepth_, ldmx::DetectorID::pack(), ldmx::G4CalorimeterHit::Print(), ldmx::G4CalorimeterHit::setEdep(), ldmx::DetectorID::setFieldValue(), ldmx::G4CalorimeterHit::setID(), ldmx::G4CalorimeterHit::setPdgCode(), ldmx::G4CalorimeterHit::setPosition(), ldmx::G4CalorimeterHit::setTime(), ldmx::G4CalorimeterHit::setTrackID(), and ldmx::CalorimeterSD::subdet_.
Member Data Documentation
hitMap_
std::unique_ptr<EcalHexReadout> ldmx::EcalSD::hitMap_ private
The hex readout defining the cell grid.
Definition at line 68 of file EcalSD.h.
Referenced by EcalSD(), and ProcessHits().
polyMap_
std::map<G4VSolid*, G4Polyhedron*> ldmx::EcalSD::polyMap_ private
Map of polygonal layers for getting Z positions.
Definition at line 73 of file EcalSD.h.
Referenced by getHitPosition().
The documentation for this class was generated from the following files:
SimApplication/include/SimApplication/EcalSD.h
SimApplication/src/EcalSD.cxx