LDMX Software: trigscint::TrigScintRecHitProducer Class Reference
trigscint::TrigScintRecHitProducer Class Reference
Organizes digis into TrigScintHits, linearizes TDC and ADC info, and converts amplitudes to PEs.
#include <TrigScintRecHitProducer.h>
Public Member Functions
TrigScintRecHitProducer (const std::string &name, framework::Process &process)
void configure (framework::config::Parameters &parameters) final override
void produce (framework::Event &event)
Public Member Functions inherited from framework::Producer
Producer (const std::string &name, Process &process)
virtual void produce (Event &event)=0
virtual void beforeNewRun (ldmx::RunHeader &header)
Public Member Functions inherited from framework::EventProcessor
EventProcessor (const std::string &name, Process &process)
virtual ~EventProcessor ()
virtual void configure (framework::config::Parameters &parameters)
virtual void onNewRun (const ldmx::RunHeader &runHeader)
virtual void onFileOpen (EventFile &eventFile)
virtual void onFileClose (EventFile &eventFile)
virtual void onProcessStart ()
virtual void onProcessEnd ()
template<class T >
const T & getCondition (const std::string &condition_name)
TDirectory * getHistoDirectory ()
void setStorageHint (framework::StorageControlHint hint)
void setStorageHint (framework::StorageControlHint hint, const std::string &purposeString)
int getLogFrequency () const
int getRunNumber () const
std::string getName () const
void createHistograms (const std::vector< framework::config::Parameters > &histos)
Private Attributes
bool verbose_ {false}
Class to set the verbosity level.
std::string inputCollection_
Name of the input collection containing the sim hits.
std::string inputPassName_
std::string outputCollection_
double gain_ {1e6}
SiPM gain.
double pedestal_ {6.0}
QIE pedestal.
double mevPerMip_ {1.40}
Total MeV per MIP.
double pePerMip_ {13.5}
Total number of photoelectrons per MIP.
int sample_of_interest_ {2}
Total number of photoelectrons per MIP.
Additional Inherited Members
Static Public Member Functions inherited from framework::EventProcessor
static void declare (const std::string &classname, int classtype, EventProcessorMaker *)
Static Public Attributes inherited from framework::Producer
static const int CLASSTYPE {1}
Protected Member Functions inherited from framework::EventProcessor
void abortEvent ()
Protected Attributes inherited from framework::EventProcessor
HistogramHelper histograms_
Interface class for making and filling histograms.
NtupleManager & ntuple_ {NtupleManager::getInstance()}
Manager for any ntuples.
logging::logger theLog_
The logger for this EventProcessor.
Detailed Description
Organizes digis into TrigScintHits, linearizes TDC and ADC info, and converts amplitudes to PEs.
Definition at line 41 of file TrigScintRecHitProducer.h.
Constructor & Destructor Documentation
TrigScintRecHitProducer()
trigscint::TrigScintRecHitProducer::TrigScintRecHitProducer (const std::string & name, framework::Process & process)
Definition at line 9 of file TrigScintRecHitProducer.cxx.
    : Producer(name, process) {}
~TrigScintRecHitProducer()
trigscint::TrigScintRecHitProducer::~TrigScintRecHitProducer ()
Definition at line 13 of file TrigScintRecHitProducer.cxx.
{}
Member Function Documentation
configure()
void trigscint::TrigScintRecHitProducer::configure (framework::config::Parameters & parameters) final override virtual
Callback for the processor to configure itself from the given set of parameters.
Parameters
parameters ParameterSet for configuration.
Reimplemented from framework::EventProcessor.
Definition at line 15 of file TrigScintRecHitProducer.cxx.
{
  // Configure this instance of the producer
  pedestal_ = parameters.getParameter<double>("pedestal");
  gain_ = parameters.getParameter<double>("gain");
  mevPerMip_ = parameters.getParameter<double>("mev_per_mip");
  pePerMip_ = parameters.getParameter<double>("pe_per_mip");
  inputCollection_ = parameters.getParameter<std::string>("input_collection");
  inputPassName_ = parameters.getParameter<std::string>("input_pass_name");
  outputCollection_ = parameters.getParameter<std::string>("output_collection");
  verbose_ = parameters.getParameter<bool>("verbose");
  sample_of_interest_ = parameters.getParameter<int>("sample_of_interest");
}
References framework::config::Parameters::getParameter().
produce()
void trigscint::TrigScintRecHitProducer::produce (framework::Event & event) virtual
Process the event and put new data products into it.
Parameters
event The Event to process.
Implements framework::Producer.
Definition at line 29 of file TrigScintRecHitProducer.cxx.
{
  // initialize QIE object for linearizing ADCs
  SimQIE qie;
  // Ensure the sample of interest <4
  /* // this assumes we are in well-behaved simulation land, not test beam wilderness
  if(sample_of_interest_>3) {
    ldmx_log(error)<<"sample_of_interest_ should be one of 0,1,2,3\n"
           <<"Currently, sample_of_interest = "<<sample_of_interest_
           <<"\n";
    return;
  }
  */
  // looper over sim hits and aggregate energy depositions
  // for each detID
  const auto digis{event.getCollection<trigscint::TrigScintQIEDigis>(
      inputCollection_, inputPassName_)};
  std::vector<ldmx::TrigScintHit> trigScintHits;
  for (const auto &digi : digis) {
    ldmx::TrigScintHit hit;
    auto adc{digi.getADC()};
    auto tdc{digi.getTDC()};
    hit.setModuleID(0);
    hit.setBarID(digi.getChanID());
    hit.setBeamEfrac(-1.);
    //leave amplitude as sum of the first two
    hit.setAmplitude(qie.ADC2Q(adc[sample_of_interest_]) +
                     qie.ADC2Q(adc[sample_of_interest_+1]));  // femptocoulombs
    if (tdc[sample_of_interest_] > 49)
      hit.setTime(-999.);
    else
      hit.setTime(tdc[sample_of_interest_] * 0.5);
    float integratedCharge=0;
    //integrate pulse over all time samples. will subtract pedestal next
    for (const auto &adcVal : adc ) {
      integratedCharge+=qie.ADC2Q(adcVal);
    }
    uint nSamp=adc.size();
    float pedSubtrQ=integratedCharge-nSamp*pedestal_;
    hit.setEnergy(pedSubtrQ*6250./gain_ *mevPerMip_/pePerMip_);  // MeV
    hit.setPE(pedSubtrQ*6250./gain_);
    trigScintHits.push_back(hit);
  }
  // Create the container to hold the
  // digitized trigger scintillator hits.
  event.add(outputCollection_, trigScintHits);
}
References trigscint::SimQIE::ADC2Q(), ldmx::CalorimeterHit::setAmplitude(), ldmx::TrigScintHit::setBarID(), ldmx::TrigScintHit::setBeamEfrac(), ldmx::CalorimeterHit::setEnergy(), ldmx::TrigScintHit::setModuleID(), ldmx::TrigScintHit::setPE(), and ldmx::CalorimeterHit::setTime().
Member Data Documentation
gain_
double trigscint::TrigScintRecHitProducer::gain_ {1e6} private
SiPM gain.
Definition at line 74 of file TrigScintRecHitProducer.h.
inputCollection_
std::string trigscint::TrigScintRecHitProducer::inputCollection_ private
Name of the input collection containing the sim hits.
Definition at line 63 of file TrigScintRecHitProducer.h.
inputPassName_
std::string trigscint::TrigScintRecHitProducer::inputPassName_ private
Name of the pass that the input collection is on (empty string means take any pass)
Definition at line 67 of file TrigScintRecHitProducer.h.
mevPerMip_
double trigscint::TrigScintRecHitProducer::mevPerMip_ {1.40} private
Total MeV per MIP.
Definition at line 80 of file TrigScintRecHitProducer.h.
outputCollection_
std::string trigscint::TrigScintRecHitProducer::outputCollection_ private
Name of the output collection that will be used to stored the digitized trigger scintillator hits
Definition at line 71 of file TrigScintRecHitProducer.h.
pedestal_
double trigscint::TrigScintRecHitProducer::pedestal_ {6.0} private
QIE pedestal.
Definition at line 77 of file TrigScintRecHitProducer.h.
pePerMip_
double trigscint::TrigScintRecHitProducer::pePerMip_ {13.5} private
Total number of photoelectrons per MIP.
Definition at line 83 of file TrigScintRecHitProducer.h.
sample_of_interest_
int trigscint::TrigScintRecHitProducer::sample_of_interest_ {2} private
Total number of photoelectrons per MIP.
Definition at line 86 of file TrigScintRecHitProducer.h.
verbose_
bool trigscint::TrigScintRecHitProducer::verbose_ {false} private
Class to set the verbosity level.
Definition at line 60 of file TrigScintRecHitProducer.h.
The documentation for this class was generated from the following files:
TrigScint/include/TrigScint/TrigScintRecHitProducer.h
TrigScint/src/TrigScint/TrigScintRecHitProducer.cxx