LDMX Software: ldmx::UserTrackingAction Class Reference
ldmx::UserTrackingAction Class Reference
Implementation of user tracking action.
#include <UserTrackingAction.h>
Public Member Functions
UserTrackingAction ()
virtual ~UserTrackingAction ()
void PreUserTrackingAction (const G4Track *aTrack)
void PostUserTrackingAction (const G4Track *aTrack)
TrackMap * getTrackMap ()
void processTrack (const G4Track *aTrack)
void storeTrajectory (const G4Track *aTrack)
void registerAction (UserAction *trackingAction)
Static Public Member Functions
static UserTrackingAction * getUserTrackingAction ()
Private Attributes
std::vector< UserAction * > trackingActions_
TrackMap trackMap_
Detailed Description
Implementation of user tracking action.
Definition at line 34 of file UserTrackingAction.h.
Constructor & Destructor Documentation
UserTrackingAction()
ldmx::UserTrackingAction::UserTrackingAction () inline
Class constructor.
Definition at line 41 of file UserTrackingAction.h.
{
             }
~UserTrackingAction()
virtual ldmx::UserTrackingAction::~UserTrackingAction () inline virtual
Class destructor.
Definition at line 47 of file UserTrackingAction.h.
{
             }
Member Function Documentation
getTrackMap()
TrackMap* ldmx::UserTrackingAction::getTrackMap () inline
Get a pointer to the current TrackMap for the event.
Returns
A pointer to the current TrackMap for the event.
Definition at line 66 of file UserTrackingAction.h.
{
                 return &trackMap_;
             }
References trackMap_.
Referenced by ldmx::UserEventAction::BeginOfEventAction(), ldmx::SimParticleBuilder::SimParticleBuilder(), ldmx::RootPersistencyManager::writeCalorimeterHitsCollection(), and ldmx::EcalHitIO::writeHitsCollection().
getUserTrackingAction()
static UserTrackingAction* ldmx::UserTrackingAction::getUserTrackingAction () inline static
Get a pointer to the current UserTrackingAction from the G4RunManager.
Returns
A pointer to the current UserTrackingAction.
Definition at line 92 of file UserTrackingAction.h.
{
                 return static_cast<UserTrackingAction*>(const_cast<G4UserTrackingAction*>(G4RunManager::GetRunManager()->GetUserTrackingAction()));
             }
Referenced by ldmx::UserEventAction::BeginOfEventAction(), ldmx::SimParticleBuilder::SimParticleBuilder(), ldmx::RootPersistencyManager::writeCalorimeterHitsCollection(), and ldmx::EcalHitIO::writeHitsCollection().
PostUserTrackingAction()
void ldmx::UserTrackingAction::PostUserTrackingAction (const G4Track * aTrack)
Implementation of post-tracking action.
Parameters
aTrack The Geant4 track.
Definition at line 38 of file UserTrackingAction.cxx.
{
         // Activate user tracking actions
         for( auto& trackingAction : trackingActions_) trackingAction->PostUserTrackingAction(track);
         // std::cout << "tracking acition: zpos = " << track->GetPosition().z() << ", pdgid = " << track->GetDefinition()->GetPDGEncoding() << ", volname = " << track->GetVolume()->GetLogicalVolume()->GetName().c_str() << std::endl;
         // Save extra trajectories on tracks that were flagged for saving during event processing.
         if (dynamic_cast<UserTrackInformation*>(track->GetUserInformation())->getSaveFlag()) {
             if (!trackMap_.hasTrajectory(track->GetTrackID())) {
                 storeTrajectory(track);
             }
         }
         // Set end point momentum on the trajectory.
         if (fpTrackingManager->GetStoreTrajectory()) {
             auto traj = dynamic_cast<Trajectory*>(fpTrackingManager->GimmeTrajectory());
             if (traj) {
                 if (track->GetTrackStatus() == G4TrackStatus::fStopAndKill) {
                     traj->setEndPointMomentum(track);
                 }
             }
         }
     }
References ldmx::UserTrackInformation::getSaveFlag(), ldmx::TrackMap::hasTrajectory(), storeTrajectory(), and trackMap_.
PreUserTrackingAction()
void ldmx::UserTrackingAction::PreUserTrackingAction (const G4Track * aTrack)
Implementation of pre-tracking action.
Parameters
aTrack The Geant4 track.
Definition at line 20 of file UserTrackingAction.cxx.
{
         int trackID = track->GetTrackID();
         if (trackMap_.contains(trackID)) {
             if (trackMap_.hasTrajectory(trackID)) {
                 // This makes sure the tracking manager does not delete the trajectory.
                 fpTrackingManager->SetStoreTrajectory(true);
             }
         } else {
             // New track so call the process method.
             processTrack(track);
         }
         // Activate user tracking actions
         for( auto& trackingAction : trackingActions_) trackingAction->PreUserTrackingAction(track);
     }
References ldmx::TrackMap::contains(), ldmx::TrackMap::hasTrajectory(), processTrack(), and trackMap_.
processTrack()
void ldmx::UserTrackingAction::processTrack (const G4Track * aTrack)
Process one track.
Parameters
aTrack The track to process.
Note
Creates a new trajectory if track should be saved.
Copies gen status setting from primary particle to the trajectory.
Saves parentage in the TrackMap for all processed tracks.
Definition at line 82 of file UserTrackingAction.cxx.
{
         // Set user track info on new track.
         if (!track->GetUserInformation()) {
             auto trackInfo = new UserTrackInformation;
             trackInfo->setInitialMomentum(track->GetMomentum());
             const_cast<G4Track*>(track)->SetUserInformation(trackInfo);
             trackInfo->setVertexVolume(track->GetVolume()->GetName());
         }
         // Check if trajectory storage should be turned on or off from the region info.
         UserRegionInformation* regionInfo = (UserRegionInformation*) track->GetLogicalVolumeAtVertex()->GetRegion()->GetUserInformation();
         // Check if trajectory storage should be turned on or off from the gen status info
         int curGenStatus = -1;
         if (track->GetDynamicParticle()->GetPrimaryParticle() != NULL){
             G4VUserPrimaryParticleInformation* primaryInfo = track->GetDynamicParticle()->GetPrimaryParticle()->GetUserInformation();
             curGenStatus = ((UserPrimaryParticleInformation*) primaryInfo)->getHepEvtStatus();
         }
         // Always save a particle if it has gen status == 1
         if (curGenStatus == 1){
             storeTrajectory(track);
         }
         else if (regionInfo && !regionInfo->getStoreSecondaries()) {
             // Turn off trajectory storage for this track from region flag.
             fpTrackingManager->SetStoreTrajectory(false);
         }
         else {
             // Store a new trajectory for this track.
             storeTrajectory(track);
         }
         // Save the association between track ID and its parent ID for all tracks in the event.
         if ( track->GetParentID() > 0 ) trackMap_.addSecondary(track->GetTrackID(), track->GetParentID());
     }
References ldmx::TrackMap::addSecondary(), ldmx::UserTrackInformation::setInitialMomentum(), storeTrajectory(), and trackMap_.
Referenced by PreUserTrackingAction().
registerAction()
void ldmx::UserTrackingAction::registerAction (UserAction * trackingAction) inline
Register a user action of type RunAction with this class.
Parameters
action User action of type RunAction
Definition at line 101 of file UserTrackingAction.h.
 { trackingActions_.push_back(trackingAction); }
storeTrajectory()
void ldmx::UserTrackingAction::storeTrajectory (const G4Track * aTrack)
Store a Trajectory for the given G4Track.
Parameters
aTrack The Geant4 track.
Definition at line 63 of file UserTrackingAction.cxx.
{
         // Create a new trajectory for this track.
         fpTrackingManager->SetStoreTrajectory(true);
         Trajectory* traj = new Trajectory(track);
         fpTrackingManager->SetTrajectory(traj);
         // Update the gen status from the primary particle.
         if (track->GetDynamicParticle()->GetPrimaryParticle() != NULL) {
             G4VUserPrimaryParticleInformation* primaryInfo = track->GetDynamicParticle()->GetPrimaryParticle()->GetUserInformation();
             if (primaryInfo != NULL) {
                 traj->setGenStatus(((UserPrimaryParticleInformation*) primaryInfo)->getHepEvtStatus());
             }
         }
         // Map track ID to trajectory.
         trackMap_.addTrajectory(traj);
     }
References ldmx::TrackMap::addTrajectory(), ldmx::Trajectory::setGenStatus(), and trackMap_.
Referenced by PostUserTrackingAction(), and processTrack().
Member Data Documentation
trackMap_
TrackMap ldmx::UserTrackingAction::trackMap_ private
Stores parentage information for all tracks in the event.
Definition at line 109 of file UserTrackingAction.h.
Referenced by getTrackMap(), PostUserTrackingAction(), PreUserTrackingAction(), processTrack(), and storeTrajectory().
The documentation for this class was generated from the following files:
SimCore/include/SimCore/UserTrackingAction.h
SimCore/src/UserTrackingAction.cxx