LDMX Software: dqm::TrigScintHitDQM Class Reference
dqm::TrigScintHitDQM Class Reference
Public Member Functions
TrigScintHitDQM (const std::string &name, framework::Process &process)
~TrigScintHitDQM ()
void configure (framework::config::Parameters &pSet)
void analyze (const framework::Event &event)
void onProcessStart ()
Public Member Functions inherited from framework::Analyzer
Analyzer (const std::string &name, Process &process)
Public Member Functions inherited from framework::EventProcessor
EventProcessor (const std::string &name, Process &process)
virtual ~EventProcessor ()
virtual void onNewRun (const ldmx::RunHeader &runHeader)
virtual void onFileOpen (EventFile &eventFile)
virtual void onFileClose (EventFile &eventFile)
virtual void onProcessEnd ()
template<class T >
const T & getCondition (const std::string &condition_name)
TDirectory * getHistoDirectory ()
void setStorageHint (framework::StorageControlHint hint)
void setStorageHint (framework::StorageControlHint hint, const std::string &purposeString)
int getLogFrequency () const
int getRunNumber () const
std::string getName () const
void createHistograms (const std::vector< framework::config::Parameters > &histos)
Private Attributes
std::string hitCollectionName_ {"TriggerPadUpDigiHits"}
std::string padName_ {"_up"}
Additional Inherited Members
Static Public Member Functions inherited from framework::EventProcessor
static void declare (const std::string &classname, int classtype, EventProcessorMaker *)
Static Public Attributes inherited from framework::Analyzer
static const int CLASSTYPE {2}
Protected Member Functions inherited from framework::EventProcessor
void abortEvent ()
Protected Attributes inherited from framework::EventProcessor
HistogramHelper histograms_
Interface class for making and filling histograms.
NtupleManager & ntuple_ {NtupleManager::getInstance()}
Manager for any ntuples.
logging::logger theLog_
The logger for this EventProcessor.
Detailed Description
Definition at line 19 of file TrigScintHitDQM.h.
Constructor & Destructor Documentation
TrigScintHitDQM()
dqm::TrigScintHitDQM::TrigScintHitDQM (const std::string & name, framework::Process & process)
Constructor
Definition at line 5 of file TrigScintHitDQM.cxx.
    : framework::Analyzer(name, process) {}
~TrigScintHitDQM()
dqm::TrigScintHitDQM::~TrigScintHitDQM ()
Destructor
Definition at line 9 of file TrigScintHitDQM.cxx.
{}
Member Function Documentation
analyze()
void dqm::TrigScintHitDQM::analyze (const framework::Event & event) virtual
Process the event and make histograms ro summaries.
Parameters
event The event to analyze.
Implements framework::Analyzer.
Definition at line 56 of file TrigScintHitDQM.cxx.
{
  // Get the collection of TrigScintHit digitized hits if the exists
  const std::vector<ldmx::TrigScintHit> TrigScintHits =
      event.getCollection<ldmx::TrigScintHit>(hitCollectionName_);
  // Get the total hit count
  int hitCount = TrigScintHits.size();
  histograms_.fill("n_hits", hitCount);
  double totalPE{0};
  int noiseHitCount = 0;
  ldmx_log(debug) << "Looping over hits in " << hitCollectionName_;
  // Loop through all TrigScint hits in the event
  for (const ldmx::TrigScintHit &hit : TrigScintHits) {
    histograms_.fill("pe", hit.getPE());
    histograms_.fill("hit_time", hit.getTime());
    histograms_.fill("id", hit.getBarID());
    totalPE += hit.getPE();
    if (hit.isNoise() > 0) {
      noiseHitCount++;
      histograms_.fill("pe_noise", hit.getPE());
      histograms_.fill("id_noise", hit.getBarID());
    } else {  // x, y, z not set for noise hits
      histograms_.fill("x", hit.getXPos());
      histograms_.fill("y", hit.getYPos());
      histograms_.fill("z", hit.getZPos());
    }
  }
  histograms_.fill("total_pe", totalPE);
  histograms_.fill("n_hits_noise", noiseHitCount);
}
References framework::HistogramHelper::fill(), framework::EventProcessor::histograms_, and hitCollectionName_.
configure()
void dqm::TrigScintHitDQM::configure (framework::config::Parameters & pSet) virtual
Configure the processor using the given user specified parameters.
Parameters
pSet Set of parameters used to configure this processor.
Reimplemented from framework::EventProcessor.
Definition at line 48 of file TrigScintHitDQM.cxx.
{
  hitCollectionName_ = ps.getParameter<std::string>("hit_collection");
  padName_ = ps.getParameter<std::string>("pad").c_str();
  std::cout << "In TrigScintHitDQM::configure, got parameters "
            << hitCollectionName_ << " and " << padName_ << std::endl;
}
References framework::config::Parameters::getParameter(), and hitCollectionName_.
onProcessStart()
void dqm::TrigScintHitDQM::onProcessStart () virtual
Method executed before processing of events begins.
Reimplemented from framework::EventProcessor.
Definition at line 11 of file TrigScintHitDQM.cxx.
{
  std::cout << "Process starts!" << std::endl;
  getHistoDirectory();
  histograms_.create("id", "Channel ID of sim hit", 100, 0, 100);
  histograms_.create("total_pe", "Total pe deposition in the pad/event", 500,
                     0, 2000);
  histograms_.create("n_hits", "TrigScint hit multiplicity in the pad/event",
                     100, 0, 100);
  histograms_.create("x", "Hit x position", 1000, -100, 100);
  histograms_.create("y", "Hit y position", 1000, -100, 100);
  histograms_.create("z", "Hit z position", 1000, -900, 100);
  histograms_.create("pe", "Pe deposition in a TrigScint bar", 250, 0, 1000);
  histograms_.create("hit_time", "TrigScint hit time (ns)", 600, -150, 150);
  histograms_.create("id_noise", "Channel ID of noise hit", 101, -1, 100);
  histograms_.create("pe_noise", "Pe deposition in a TrigScint bar noise hit",
                     100, 0, 100);
  histograms_.create("n_hits_noise",
                     "TrigScint noise hit multiplicity in the pad/event", 100,
                     0, 100);
  histograms_.create("max_pe:time", "Max Photoelectrons in a TrigScint bar",
                     1500, 0, 1500, "TrigScint max PE hit time (ns)", 1500, 0,
                     1500);
  histograms_.create("min_time_hit_above_thresh:pe",
                     "Photoelectrons in a TrigScint bar", 1500, 0, 1500,
                     "Earliest time of TrigScint hit above threshold (ns)",
                     1600, -100, 1500);
  // TODO: implement getting a list of the constructed histograms, to iterate
  // through and set overflow boolean.
}
References framework::HistogramHelper::create(), framework::EventProcessor::getHistoDirectory(), and framework::EventProcessor::histograms_.
Member Data Documentation
hitCollectionName_
std::string dqm::TrigScintHitDQM::hitCollectionName_ {"TriggerPadUpDigiHits"} private
Name of trigger pad hit collection.
Definition at line 46 of file TrigScintHitDQM.h.
Referenced by analyze(), and configure().
padName_
std::string dqm::TrigScintHitDQM::padName_ {"_up"} private
Definition at line 47 of file TrigScintHitDQM.h.
The documentation for this class was generated from the following files:
DQM/include/DQM/TrigScintHitDQM.h
DQM/src/DQM/TrigScintHitDQM.cxx