LDMX Software: ldmx::EcalReconConditions Class Reference
ldmx::EcalReconConditions Class Reference
#include <EcalReconConditions.h>
Public Member Functions
EcalReconConditions (const DoubleTableCondition &table, bool validate=true)
double adcPedestal (const EcalID &id) const
double adcGain (const EcalID &id) const
double totPedestal (const EcalID &id) const
double totGain (const EcalID &id) const
Static Public Attributes
static const std::string CONDITIONS_NAME = "EcalReconConditions"
the name of the EcalReconConditions table (must match python registration name)
static const unsigned int IADC_PEDESTAL = 0
column index for ADC pedestal
static const unsigned int IADC_GAIN = 1
column index for ADC threshold
static const unsigned int ITOT_PEDESTAL = 2
column index for TOT pedestal
static const unsigned int ITOT_GAIN = 3
column index for TOT gain
static const std::vector< std::string > EXPECTED_COLUMNS
expected order of column names matching the above indices (must match the indices above)
Private Attributes
const DoubleTableCondition & the_table_
reference to the table of conditions storing the chip conditions
Detailed Description
Class to wrap around an double table of conditions.
This hardcodes the column numbers and checks that the hardcoded numbers match the imported columns during construction.
Definition at line 17 of file EcalReconConditions.h.
Constructor & Destructor Documentation
EcalReconConditions()
ldmx::EcalReconConditions::EcalReconConditions (const DoubleTableCondition & table, bool validate = true)
Constructor
Assign the conditions table to use and (if validate is true), check if the hard-coded column indices correctly match the table that is passed.
@raises Exception if any of the column names from the passed table do not match the hardcoded indices.
Parameters
[in] table double table of reconstruction conditions
[in] validate true if you want to check the columns
Definition at line 18 of file EcalReconConditions.cxx.
     : the_table_{table} {
   //leave early if we don't want to validate
   if (!validate) return;
   if (the_table_.getColumnCount() != EXPECTED_COLUMNS.size()) {
     EXCEPTION_RAISE("ConditionsException",
                     "Inconsistent condition for EcalReconConditions :" +
                      table.getName());
   }
   //not using fancy C++17 to shorten this because we want the error to
   // tell us where the failure is
   for (size_t i = 0; i < EXPECTED_COLUMNS.size(); i++) {
     if (the_table_.getColumnNames().at(i) != EXPECTED_COLUMNS.at(i)) {
       EXCEPTION_RAISE("ConditionsException",
                       "Expected column '" + EXPECTED_COLUMNS.at(i) + "', got '" +
                           the_table_.getColumnNames().at(i) + "'");
     }//does name match?
   }//loop through columns
 }
Member Function Documentation
adcGain()
double ldmx::EcalReconConditions::adcGain (const EcalID & id) const inline
get the ADC gain
The ADC gain converts the ADC counts measuring a voltage amplitude into an estimated charge deposition [fC].
Parameters
[in] id raw ID for specific chip
Returns
the ADC threshold for that chip in fC/counts
Definition at line 68 of file EcalReconConditions.h.
{
     return the_table_.get(id.raw(), IADC_GAIN);
   }
References ldmx::HomogenousTableCondition< T >::get(), IADC_GAIN, and the_table_.
Referenced by ldmx::EcalRecProducer::produce().
adcPedestal()
double ldmx::EcalReconConditions::adcPedestal (const EcalID & id) const inline
get the ADC pedestal
Parameters
[in] id ECal ID for specific chip
Returns
the ADC pedestal for that chip in counts
Definition at line 54 of file EcalReconConditions.h.
{
     return the_table_.get(id.raw(), IADC_PEDESTAL);
   }
References ldmx::HomogenousTableCondition< T >::get(), IADC_PEDESTAL, and the_table_.
Referenced by ldmx::EcalRecProducer::produce().
totGain()
double ldmx::EcalReconConditions::totGain (const EcalID & id) const inline
get the TOT gain
The TOT gain converts counts measuring time over threshold into an estimate for charge deposited in that cell [fC].
Parameters
[in] id ECal ID for specific chip
Returns
the TOT gain for that chip in fC/counts
Definition at line 92 of file EcalReconConditions.h.
{
     return the_table_.get(id.raw(), ITOT_GAIN);
   }
References ldmx::HomogenousTableCondition< T >::get(), ITOT_GAIN, and the_table_.
Referenced by ldmx::EcalRecProducer::produce().
totPedestal()
double ldmx::EcalReconConditions::totPedestal (const EcalID & id) const inline
get the TOT pedestal
Parameters
[in] id ECal ID for specific chip
Returns
the TOT pedestal for that chip in counts
Definition at line 78 of file EcalReconConditions.h.
{
     return the_table_.get(id.raw(), ITOT_PEDESTAL);
   }
References ldmx::HomogenousTableCondition< T >::get(), ITOT_PEDESTAL, and the_table_.
Referenced by ldmx::EcalRecProducer::produce().
Member Data Documentation
EXPECTED_COLUMNS
const std::vector< std::string > ldmx::EcalReconConditions::EXPECTED_COLUMNS static
Initial value:
= {
    "ADC_PEDESTAL",
    "ADC_GAIN",
    "TOT_PEDESTAL",
    "TOT_GAIN"
}
expected order of column names matching the above indices (must match the indices above)
The order of these column names needs to match the indices listed in the header.
Definition at line 31 of file EcalReconConditions.h.
The documentation for this class was generated from the following files:
Ecal/include/Ecal/EcalReconConditions.h
Ecal/src/Ecal/EcalReconConditions.cxx