LDMX Software: ldmx::DetectorConstruction Class Reference
ldmx::DetectorConstruction Class Reference
Implements the Geant4 detector construction.
#include <DetectorConstruction.h>
Public Member Functions
DetectorConstruction (G4GDMLParser *theParser, Parameters &parameters)
virtual ~DetectorConstruction ()
G4VPhysicalVolume * Construct ()
void ConstructSDandField ()
ldmx::DetectorHeader * getDetectorHeader ()
Private Attributes
G4GDMLParser * parser_
AuxInfoReader * auxInfoReader_
Parameters parameters_
The set of parameters used to configure this class.
Detailed Description
Implements the Geant4 detector construction.
Note
This class reads in a detector description from a GDML file using the basic G4GDMLParser and instantiates supplemental information using the AuxInfoReader.
See also
AuxInfoReader
Definition at line 43 of file DetectorConstruction.h.
Constructor & Destructor Documentation
DetectorConstruction()
ldmx::DetectorConstruction::DetectorConstruction (G4GDMLParser * theParser, Parameters & parameters)
Class constructor.
Parameters
theParser GDML parser defining the geometry.
Definition at line 10 of file DetectorConstruction.cxx.
                                                                                               :
             parser_(theParser), auxInfoReader_(new AuxInfoReader(theParser)) {
                 parameters_ = parameters;
     }
References parameters_.
~DetectorConstruction()
ldmx::DetectorConstruction::~DetectorConstruction () virtual
Class destructor.
Definition at line 15 of file DetectorConstruction.cxx.
{
         delete auxInfoReader_;
     }
References auxInfoReader_.
Member Function Documentation
Construct()
G4VPhysicalVolume * ldmx::DetectorConstruction::Construct ()
Construct the detector.
Returns
The top volume of the detector.
Definition at line 19 of file DetectorConstruction.cxx.
{
         auxInfoReader_->readGlobalAuxInfo();
         auxInfoReader_->assignAuxInfoToVolumes();
         return parser_->GetWorldVolume();
     }
References ldmx::AuxInfoReader::assignAuxInfoToVolumes(), auxInfoReader_, parser_, and ldmx::AuxInfoReader::readGlobalAuxInfo().
getDetectorHeader()
ldmx::DetectorHeader* ldmx::DetectorConstruction::getDetectorHeader () inline
Get the detector header.
Returns
The detector header.
Definition at line 72 of file DetectorConstruction.h.
{
                 return auxInfoReader_->getDetectorHeader();
             }
References auxInfoReader_, and ldmx::AuxInfoReader::getDetectorHeader().
Member Data Documentation
auxInfoReader_
AuxInfoReader* ldmx::DetectorConstruction::auxInfoReader_ private
The auxiliary GDML info reader.
Definition at line 86 of file DetectorConstruction.h.
Referenced by Construct(), getDetectorHeader(), and ~DetectorConstruction().
parser_
G4GDMLParser* ldmx::DetectorConstruction::parser_ private
The GDML parser defining the detector.
Definition at line 81 of file DetectorConstruction.h.
Referenced by Construct().
The documentation for this class was generated from the following files:
SimCore/include/SimCore/DetectorConstruction.h
SimCore/src/DetectorConstruction.cxx