LDMX Software: ldmx::test::ecal::EcalCheckEnergyReconstruction Class Reference
ldmx::test::ecal::EcalCheckEnergyReconstruction Class Reference
Public Member Functions
EcalCheckEnergyReconstruction (const std::string &name, Process &p)
void onProcessStart () final override
void analyze (const Event &event) final override
Public Member Functions inherited from ldmx::Analyzer
Analyzer (const std::string &name, Process &process)
Public Member Functions inherited from ldmx::EventProcessor
EventProcessor (const std::string &name, Process &process)
virtual ~EventProcessor ()
virtual void configure (Parameters &parameters)
virtual void onNewRun (const RunHeader &runHeader)
virtual void onFileOpen (EventFile &eventFile)
virtual void onFileClose (EventFile &eventFile)
virtual void onProcessEnd ()
template<class T >
const T & getCondition (const std::string &condition_name)
TDirectory * getHistoDirectory ()
void setStorageHint (ldmx::StorageControlHint hint)
void setStorageHint (ldmx::StorageControlHint hint, const std::string &purposeString)
int getLogFrequency () const
int getRunNumber () const
std::string getName () const
void createHistograms (const std::vector< Parameters > &histos)
Additional Inherited Members
Static Public Member Functions inherited from ldmx::EventProcessor
static void declare (const std::string &classname, int classtype, EventProcessorMaker *)
Static Public Attributes inherited from ldmx::Analyzer
static const int CLASSTYPE {2}
Protected Member Functions inherited from ldmx::EventProcessor
void abortEvent ()
Protected Attributes inherited from ldmx::EventProcessor
HistogramHelper histograms_
Interface class for making and filling histograms.
NtupleManager & ntuple_ {NtupleManager::getInstance()}
Manager for any ntuples.
logging::logger theLog_
The logger for this EventProcessor.
Detailed Description
Checks
Amplitude of EcalRecHit matches SimCalorimeterHit EDep with the same ID
Estimated energy at TP level matches sim energy
Assumptions
Only one sim hit per event
Noise generation has been turned off
Definition at line 178 of file EcalDigiPipelineTest.cxx.
Member Function Documentation
analyze()
void ldmx::test::ecal::EcalCheckEnergyReconstruction::analyze (const Event & event) inline final override virtual
Process the event and make histograms or summaries
Parameters
event The Event to analyze
Implements ldmx::Analyzer.
Definition at line 202 of file EcalDigiPipelineTest.cxx.
{
             const auto simHits = event.getCollection<SimCalorimeterHit>( "EcalSimHits" );
             REQUIRE( simHits.size() == 1 );
             float truth_energy = simHits.at(0).getEdep();
             ntuple_.setVar<float>("SimEnergy",truth_energy);
             const auto daqDigis{event.getObject<HgcrocDigiCollection>("EcalDigis")};
             CHECK( daqDigis.getNumDigis() == 1 );
             auto daqDigi = daqDigis.getDigi(0);
             ntuple_.setVar<int>("DaqDigi",daqDigi.soi().raw());
             bool is_in_adc_mode = daqDigi.isADC();
             ntuple_.setVar<int>("DaqDigiIsADC",is_in_adc_mode);
             ntuple_.setVar<int>("DaqDigiADC",daqDigi.soi().adc_t());
             ntuple_.setVar<int>("DaqDigiTOT",daqDigi.tot());
             const auto recHits = event.getCollection<EcalHit>( "EcalRecHits" );
             CHECK( recHits.size() == 1 );
             auto hit = recHits.at(0);
             EcalID id(hit.getID());
             CHECK_FALSE( hit.isNoise() );
             CHECK( id.raw() == simHits.at(0).getID() );
             //define target energy by using the settings at the top
             auto target_daq_energy = Approx(truth_energy).epsilon(MAX_ENERGY_PERCENT_ERROR_DAQ_TOT_MODE/100);
             if (is_in_adc_mode) target_daq_energy = Approx(truth_energy).margin(MAX_ENERGY_ERROR_DAQ_ADC_MODE);
             CHECK( hit.getAmplitude() == target_daq_energy );
             ntuple_.setVar<float>("RecEnergy",hit.getAmplitude());
             const auto trigDigis{event.getObject<HgcrocTrigDigiCollection>("ecalTrigDigis")};
             CHECK( trigDigis.size() == 1 );
             auto trigDigi = trigDigis.at(0);
             float tp_energy = 8*trigDigi.linearPrimitive()*320./1024*MeV_per_fC;
             auto target_tp_energy = Approx(truth_energy).epsilon(MAX_ENERGY_PERCENT_ERROR_TP_TOT_MODE/100);
             if (is_in_adc_mode) target_tp_energy = Approx(truth_energy).margin(MAX_ENERGY_ERROR_TP_ADC_MODE);
             CHECK( tp_energy == target_tp_energy );
             ntuple_.setVar<float>("TrigPrimEnergy",tp_energy);
             ntuple_.setVar<int>("TrigPrimDigiEncoded",trigDigi.getPrimitive());
             ntuple_.setVar<int>("TrigPrimDigiLinear",trigDigi.linearPrimitive());
             return;
         }
References ldmx::test::ecal::MAX_ENERGY_ERROR_DAQ_ADC_MODE, ldmx::test::ecal::MAX_ENERGY_ERROR_TP_ADC_MODE, ldmx::test::ecal::MAX_ENERGY_PERCENT_ERROR_DAQ_TOT_MODE, ldmx::test::ecal::MAX_ENERGY_PERCENT_ERROR_TP_TOT_MODE, ldmx::test::ecal::MeV_per_fC, ldmx::EventProcessor::ntuple_, and ldmx::NtupleManager::setVar().
onProcessStart()
void ldmx::test::ecal::EcalCheckEnergyReconstruction::onProcessStart () inline final override virtual
Callback for the EventProcessor to take any necessary action when the processing of events starts, such as creating histograms.
Reimplemented from ldmx::EventProcessor.
Definition at line 185 of file EcalDigiPipelineTest.cxx.
{
             getHistoDirectory();
             ntuple_.create("EcalDigiTest");
             ntuple_.addVar<float>("EcalDigiTest","SimEnergy");
             ntuple_.addVar<float>("EcalDigiTest","RecEnergy");
             ntuple_.addVar<float>("EcalDigiTest","TrigPrimEnergy");
             ntuple_.addVar<int>("EcalDigiTest","DaqDigi");
             ntuple_.addVar<int>("EcalDigiTest","DaqDigiIsADC");
             ntuple_.addVar<int>("EcalDigiTest","DaqDigiADC");
             ntuple_.addVar<int>("EcalDigiTest","DaqDigiTOT");
             ntuple_.addVar<int>("EcalDigiTest","TrigPrimDigiEncoded");
             ntuple_.addVar<int>("EcalDigiTest","TrigPrimDigiLinear" );
         }
References ldmx::NtupleManager::addVar(), ldmx::NtupleManager::create(), ldmx::EventProcessor::getHistoDirectory(), and ldmx::EventProcessor::ntuple_.
The documentation for this class was generated from the following file:
Ecal/test/EcalDigiPipelineTest.cxx