LDMX Software: ldmx::EcalID Class Reference
ldmx::EcalID Class Reference
Extension of DetectorID providing access to ECal layers and cell numbers in a hex grid.
#include <EcalID.h>
Public Member Functions
EcalID ()
EcalID (RawValue rawid)
EcalID (const DetectorID id)
EcalID (unsigned int layer, unsigned int module, unsigned int cell)
EcalID (unsigned int layer, unsigned int module, unsigned int u, unsigned int v)
EcalID (unsigned int layer, unsigned int module, std::pair< unsigned int, unsigned int > uv)
int module () const
int getModuleID () const
int layer () const
int getLayerID () const
int cell () const
int getCellID () const
std::pair< unsigned int, unsigned int > getCellUV () const
Public Member Functions inherited from ldmx::EcalAbstractID
EcalAbstractID ()
EcalAbstractID (RawValue rawid)
EcalAbstractID (const DetectorID id)
EcalAbstractID (unsigned int cell_type, unsigned int payload)
int cell_type () const
Public Member Functions inherited from ldmx::DetectorID
DetectorID ()
Class constructor for a null DetectorID.
DetectorID (RawValue rawid)
Class constructor from a raw 32-bit integer.
DetectorID (SubdetectorIDType sdtype, RawValue raw_subpayload)
bool null () const
SubdetectorIDType subdet () const
RawValue raw () const
void setRawValue (RawValue rawValue)
bool operator< (const DetectorID &id) const
bool operator== (const DetectorID &id) const
bool operator!= (const DetectorID &id) const
Static Public Member Functions
static void createInterpreters ()
Static Public Attributes
static const RawValue LAYER_MASK {0x3F}
static const RawValue LAYER_SHIFT {17}
static const RawValue MODULE_MASK {0x1F}
static const RawValue MODULE_SHIFT {12}
static const RawValue CELL_MASK {0xFFF}
static const RawValue CELL_SHIFT {0}
Static Public Attributes inherited from ldmx::EcalAbstractID
static const RawValue CELL_TYPE_MASK
static const RawValue CELL_TYPE_SHIFT {23}
static const RawValue ECAL_PAYLOAD_MASK {0x007FFFFF}
Static Public Attributes inherited from ldmx::DetectorID
static const RawValue SUBDETECTORID_MASK {0x3F}
static const RawValue SUBDETECTORID_SHIFT {26}
static const RawValue SUBDETECTOR_PAYLOAD_MASK {0x3FFFFFFF}
Additional Inherited Members
Public Types inherited from ldmx::EcalAbstractID
enum EcalCellType { PrecisionGlobal = 0 , PrecisionLocal = 1 , TriggerCell = 2 , Special = 7 }
Public Types inherited from ldmx::DetectorID
typedef uint32_t RawValue
Protected Attributes inherited from ldmx::DetectorID
RawValue id_
The raw, packed value of the ID.
Detailed Description
Extension of DetectorID providing access to ECal layers and cell numbers in a hex grid.
Definition at line 20 of file EcalID.h.
Constructor & Destructor Documentation
EcalID() [1/6]
ldmx::EcalID::EcalID () inline
Empty ECAL id (but not null!)
Definition at line 32 of file EcalID.h.
 : EcalAbstractID() {}
EcalID() [2/6]
ldmx::EcalID::EcalID (RawValue rawid) inline
Create from raw number
Definition at line 37 of file EcalID.h.
                          : EcalAbstractID(rawid) {
     if (!null() && cell_type() != PrecisionGlobal &&
         cell_type() != PrecisionLocal) {
       EXCEPTION_RAISE(
           "DetectorIDMismatch",
           "Attempted to create EcalID from mismatched Ecal cell_type " +
               std::to_string(cell_type()));
     }
   }
References ldmx::EcalAbstractID::cell_type().
EcalID() [3/6]
ldmx::EcalID::EcalID (const DetectorID id) inline
Create from a DetectorID, but check
Definition at line 50 of file EcalID.h.
                               : EcalAbstractID(id) {
     if (!null() && cell_type() != PrecisionGlobal &&
         cell_type() != PrecisionLocal) {
       EXCEPTION_RAISE(
           "DetectorIDMismatch",
           "Attempted to create EcalID from mismatched Ecal cell_type " +
               std::to_string(cell_type()));
     }
   }
References ldmx::EcalAbstractID::cell_type().
EcalID() [4/6]
ldmx::EcalID::EcalID (unsigned int layer, unsigned int module, unsigned int cell) inline
Create from pieces
Definition at line 63 of file EcalID.h.
       : EcalAbstractID(PrecisionGlobal, 0) {
     id_ |= (layer & LAYER_MASK) << LAYER_SHIFT;
     id_ |= (module & MODULE_MASK) << MODULE_SHIFT;
     id_ |= (cell & CELL_MASK) << CELL_SHIFT;
   }
References cell(), ldmx::DetectorID::id_, layer(), and module().
EcalID() [5/6]
ldmx::EcalID::EcalID (unsigned int layer, unsigned int module, unsigned int u, unsigned int v)
Create from pieces including u/v cell
Definition at line 41 of file EcalID.cxx.
     : EcalAbstractID(EcalAbstractID::PrecisionGlobal, 0) {
   id_ |= (layer & LAYER_MASK) << LAYER_SHIFT;
   id_ |= (module & MODULE_MASK) << MODULE_SHIFT;
   unsigned int cell = 0;
   if (v > max_v) {
     EXCEPTION_RAISE("InvalidIdException",
                     "Attempted to create EcalID with invalid (u,v)=(" +
                         std::to_string(u) + "," + std::to_string(v) + ")");
   }
   if (v <= v_middle) {  // simple case...
     if (u > (base_row_w - 1 + v)) {
       EXCEPTION_RAISE("InvalidIdException",
                       "Attempted to create EcalID with invalid (u,v)=(" +
                           std::to_string(u) + "," + std::to_string(v) + ")");
     }
     cell = u + v * base_row_w + (v - 1) * v / 2;
   } else {
     unsigned int umin = v - v_middle;
     static unsigned int umax = 23;  // constant
     unsigned int vrel = v - v_middle - 1;
     if (u < umin || u > umax) {
       EXCEPTION_RAISE("InvalidIdException",
                       "Attempted to create EcalID with invalid (u,v)=(" +
                           std::to_string(u) + "," + std::to_string(v) + ")");
     }
     cell = 222 + (u - umin) + vrel * base_row_w + 55 -
            (v_middle - vrel - 1) * (v_middle - vrel) / 2;
   }
   id_ |= (cell & CELL_MASK) << CELL_SHIFT;
 }
References cell(), ldmx::DetectorID::id_, layer(), and module().
EcalID() [6/6]
ldmx::EcalID::EcalID (unsigned int layer, unsigned int module, std::pair< unsigned int, unsigned int > uv) inline
Create from pieces including u/v cell
Definition at line 79 of file EcalID.h.
       : EcalID(layer, module, uv.first, uv.second) {}
Member Function Documentation
cell()
int ldmx::EcalID::cell () const inline
Get the value of the cell field from the ID.
Returns
The value of the cell field.
Definition at line 111 of file EcalID.h.
 { return (id_ >> CELL_SHIFT) & CELL_MASK; }
References ldmx::DetectorID::id_.
Referenced by ecal::EcalTriggerGeometry::belongsTo(), ldmx::EcalHexReadout::distanceToEdge(), EcalID(), ldmx::EcalHexReadout::getCellCenterAbsolute(), getCellUV(), ecal::EcalTriggerGeometry::localPosition(), simcore::EcalSD::ProcessHits(), and TEST_CASE().
getCellID()
int ldmx::EcalID::getCellID () const inline
Get the value of the cell field from the ID.
Returns
The value of the cell field.
Definition at line 117 of file EcalID.h.
 { return (id_ >> CELL_SHIFT) & CELL_MASK; }
References ldmx::DetectorID::id_.
Referenced by getCellUV(), and TEST_CASE().
getCellUV()
std::pair< unsigned int, unsigned int > ldmx::EcalID::getCellUV () const
Get the cell u,v index assuming a CMS-standard 432-cell sensor
Returns
Pair providing a U/V index
Definition at line 80 of file EcalID.cxx.
{
   int cell = getCellID();
   unsigned int v;
   for (v = 0; v < max_v && cell >= row_starts[v + 1]; v++)
     ;  // find the right v value
   unsigned int u = cell - row_starts[v];
   if (v > v_middle) u += (v - v_middle);
   return std::pair<unsigned int, unsigned int>(u, v);
 }
References cell(), and getCellID().
getLayerID()
int ldmx::EcalID::getLayerID () const inline
Get the value of the layer field from the ID.
Returns
The value of the layer field.
Definition at line 105 of file EcalID.h.
 { return (id_ >> LAYER_SHIFT) & LAYER_MASK; }
References ldmx::DetectorID::id_.
Referenced by TEST_CASE().
getModuleID()
int ldmx::EcalID::getModuleID () const inline
Get the value of the module field from the ID.
Returns
The value of the module field.
Definition at line 93 of file EcalID.h.
 { return (id_ >> MODULE_SHIFT) & MODULE_MASK; }
References ldmx::DetectorID::id_.
Referenced by TEST_CASE().
layer()
int ldmx::EcalID::layer () const inline
Get the value of the layer field from the ID.
Returns
The value of the layer field.
Definition at line 99 of file EcalID.h.
 { return (id_ >> LAYER_SHIFT) & LAYER_MASK; }
References ldmx::DetectorID::id_.
Referenced by ecal::EcalTriggerGeometry::belongsTo(), EcalID(), and TEST_CASE().
module()
int ldmx::EcalID::module () const inline
Get the value of the module field from the ID.
Returns
The value of the module field.
Definition at line 87 of file EcalID.h.
 { return (id_ >> MODULE_SHIFT) & MODULE_MASK; }
References ldmx::DetectorID::id_.
Referenced by ecal::EcalTriggerGeometry::belongsTo(), EcalID(), ldmx::EcalHexReadout::getCellCenterAbsolute(), and TEST_CASE().
The documentation for this class was generated from the following files:
DetDescr/include/DetDescr/EcalID.h
DetDescr/src/DetDescr/EcalID.cxx