LDMX Software: ldmx::EventProcessor Class Reference
ldmx::EventProcessor Class Reference
Base class for all event processing components.
#include <EventProcessor.h>
Public Member Functions
EventProcessor (const std::string &name, Process &process)
virtual ~EventProcessor ()
virtual void configure (Parameters &parameters)
virtual void onNewRun (const RunHeader &runHeader)
virtual void onFileOpen (EventFile &eventFile)
virtual void onFileClose (EventFile &eventFile)
virtual void onProcessStart ()
virtual void onProcessEnd ()
template<class T >
const T & getCondition (const std::string &condition_name)
TDirectory * getHistoDirectory ()
void setStorageHint (ldmx::StorageControlHint hint)
void setStorageHint (ldmx::StorageControlHint hint, const std::string &purposeString)
int getLogFrequency () const
int getRunNumber () const
std::string getName () const
void createHistograms (const std::vector< Parameters > &histos)
Static Public Member Functions
static void declare (const std::string &classname, int classtype, EventProcessorMaker *)
Protected Member Functions
void abortEvent ()
Protected Attributes
HistogramHelper histograms_
Interface class for making and filling histograms.
NtupleManager & ntuple_ {NtupleManager::getInstance()}
Manager for any ntuples.
logging::logger theLog_
The logger for this EventProcessor.
Private Member Functions
Conditions & getConditions () const
const EventHeader & getEventHeader () const
Private Attributes
Process & process_
std::string name_
TDirectory * histoDir_ {0}
Detailed Description
Base class for all event processing components.
Definition at line 71 of file EventProcessor.h.
Constructor & Destructor Documentation
EventProcessor()
ldmx::EventProcessor::EventProcessor (const std::string & name, Process & process)
Class constructor.
Parameters
name Name for this instance of the class.
process The Process class associated with EventProcessor, provided by the framework.
Note
The name provided to this function should not be the class name, but rather a logical label for this instance of the class, as more than one copy of a given class can be loaded into a Process with different parameters. Names should not include whitespace or special characters.
Definition at line 11 of file EventProcessor.cxx.
                                                                           :
         process_{process}, name_ {name} , histograms_{name} , theLog_{logging::makeLogger(name)} {
     }
~EventProcessor()
virtual ldmx::EventProcessor::~EventProcessor () inline virtual
Class destructor.
Definition at line 91 of file EventProcessor.h.
 {;}
Member Function Documentation
abortEvent()
void ldmx::EventProcessor::abortEvent () inline protected
Abort the event immediately.
Skip the rest of the sequence and don't save anything in the event bus.
Definition at line 218 of file EventProcessor.h.
 { throw AbortEventException(); }
Referenced by ldmx::Simulator::produce().
configure()
virtual void ldmx::EventProcessor::configure (Parameters & parameters) inline virtual
Callback for the EventProcessor to configure itself from the given set of parameters.
The parameters a processor has access to are the member variables of the python class in the sequence that has className equal to the EventProcessor class name.
For an example, look at MyProcessor.
Parameters
parameters Parameters for configuration.
Reimplemented in ldmx::TrigScintHitDQM, ldmx::TrigScintDQM, ldmx::EcalDigiVerifier, ldmx::TruthHitProducer, ldmx::TrigScintDigiProducer, ldmx::Simulator, ldmx::HcalVetoProcessor, ldmx::HcalDigiProducer, ldmx::test::TestConfig, ldmx::TriggerProcessor, ldmx::TrackerHitKiller, ldmx::PnWeightProcessor, ldmx::MyProcessor, ldmx::FindableTrackProcessor, ldmx::EcalVetoProcessor, ldmx::EcalClusterProducer, ldmx::DNNEcalVetoProcessor, ldmx::RecoilTrackerDQM, ldmx::PhotoNuclearDQM, ldmx::HCalDQM, ldmx::test::TestProducer, ldmx::EcalTrigPrimDigiProducer, ldmx::EcalRecProducer, ldmx::EcalDigiProducer, ldmx::TrigScintTrackProducer, and ldmx::TrigScintClusterProducer.
Definition at line 105 of file EventProcessor.h.
 { }
createHistograms()
void ldmx::EventProcessor::createHistograms (const std::vector< Parameters > & histos)
Internal function which is used to create histograms passed from the python configuration @parma histos vector of Parameters that configure histograms to create
Definition at line 43 of file EventProcessor.cxx.
{
         for ( auto const& h : histos ) {
             auto name{h.getParameter<std::string>("name")};
             auto xLabel{h.getParameter<std::string>("xlabel")};
             auto xbins{h.getParameter<std::vector<double>>("xbins")};
             auto yLabel{h.getParameter<std::string>("ylabel")};
             auto ybins{h.getParameter<std::vector<double>>("ybins",{})};
             if ( ybins.empty() ) {
                 //assume 1D histogram
                 histograms_.create( name , xLabel , xbins );
             } else {
                 //assume 2D histogram
                 histograms_.create( name , xLabel , xbins , yLabel , ybins );
             }
         }
     }
References ldmx::HistogramHelper::create(), and histograms_.
declare()
void ldmx::EventProcessor::declare (const std::string & classname, int classtype, EventProcessorMaker * maker) static
Internal function which is part of the PluginFactory machinery.
Parameters
classname The class name of the processor.
classtype The class type of the processor (1 for Producer, 2 for Analyzer).
Definition at line 39 of file EventProcessor.cxx.
{
         PluginFactory::getInstance().registerEventProcessor(classname, classtype, maker);
     }
References ldmx::PluginFactory::getInstance(), and ldmx::PluginFactory::registerEventProcessor().
getCondition()
template<class T > const T& ldmx::EventProcessor::getCondition (const std::string & condition_name) inline
Access a conditions object for the current event
Definition at line 153 of file EventProcessor.h.
{
                 return getConditions().getCondition<T>(condition_name);
             }
References ldmx::Conditions::getCondition(), and getConditions().
Referenced by ldmx::ConditionsInterface::getCondition().
getConditions()
Conditions & ldmx::EventProcessor::getConditions () const private
Internal getter for conditions without exposing all of Process
Definition at line 15 of file EventProcessor.cxx.
 { return process_.getConditions(); }
References ldmx::Process::getConditions(), and process_.
Referenced by getCondition().
getEventHeader()
const EventHeader & ldmx::EventProcessor::getEventHeader () const private
Internal getter for EventHeader without exposing all of Process
Definition at line 17 of file EventProcessor.cxx.
 { return *(process_.getEventHeader()); }
References ldmx::Process::getEventHeader(), and process_.
getHistoDirectory()
TDirectory * ldmx::EventProcessor::getHistoDirectory ()
Access/create a directory in the histogram file for this event processor to create histograms and analysis tuples.
Note
This method makes the returned directory the current directory so that newly created objects should go into that directory
Returns
TDirectory* reference to directory in histogram file
Definition at line 19 of file EventProcessor.cxx.
{
         if (!histoDir_) {
             histoDir_=process_.makeHistoDirectory(name_);
         }
         histoDir_->cd(); // make this the current directory
         return histoDir_;
     }
References histoDir_, ldmx::Process::makeHistoDirectory(), name_, and process_.
Referenced by ldmx::TrigScintDQM::onProcessStart(), ldmx::TrigScintHitDQM::onProcessStart(), and ldmx::test::TestAnalyzer::onProcessStart().
getLogFrequency()
int ldmx::EventProcessor::getLogFrequency () const
Get the current logging frequency from the process
Returns
int frequency logging should occurr
Definition at line 31 of file EventProcessor.cxx.
{
         return process_.getLogFrequency();
     }
References ldmx::Process::getLogFrequency(), and process_.
Referenced by ldmx::Simulator::produce().
getName()
std::string ldmx::EventProcessor::getName () const inline
Get the processor name
Definition at line 196 of file EventProcessor.h.
 { return name_; }
References name_.
Referenced by ldmx::EcalTrigPrimDigiProducer::produce().
getRunNumber()
int ldmx::EventProcessor::getRunNumber () const
Get the run number from the process
Returns
int run number
Definition at line 35 of file EventProcessor.cxx.
{
         return process_.getRunNumber();
     }
References ldmx::Process::getRunNumber(), and process_.
Referenced by ldmx::Simulator::onFileOpen().
onFileClose()
virtual void ldmx::EventProcessor::onFileClose (EventFile & eventFile) inline virtual
Callback for the EventProcessor to take any necessary action when a event input ROOT file is closed.
Parameters
filename Input event ROOT file name
Note
This callback is rarely used.
Reimplemented in ldmx::Simulator.
Definition at line 130 of file EventProcessor.h.
{
             }
onFileOpen()
virtual void ldmx::EventProcessor::onFileOpen (EventFile & eventFile) inline virtual
Callback for the EventProcessor to take any necessary action when a new event input ROOT file is opened.
Parameters
filename Input event ROOT file name.
Note
This callback is rarely used.
Reimplemented in ldmx::Simulator.
Definition at line 121 of file EventProcessor.h.
{
             }
onNewRun()
virtual void ldmx::EventProcessor::onNewRun (const RunHeader & runHeader) inline virtual
Callback for the EventProcessor to take any necessary action when the run being processed changes.
Parameters
runHeader The RunHeader containing run information.
Reimplemented in ldmx::Simulator.
Definition at line 112 of file EventProcessor.h.
{
             }
onProcessEnd()
virtual void ldmx::EventProcessor::onProcessEnd () inline virtual
Callback for the EventProcessor to take any necessary action when the processing of events finishes, such as calculating job-summary quantities.
Reimplemented in ldmx::Simulator, ldmx::TrigScintTrackProducer, and ldmx::TrigScintClusterProducer.
Definition at line 146 of file EventProcessor.h.
{
             }
onProcessStart()
virtual void ldmx::EventProcessor::onProcessStart () inline virtual
Callback for the EventProcessor to take any necessary action when the processing of events starts, such as creating histograms.
Reimplemented in ldmx::Simulator, ldmx::test::TestAnalyzer, ldmx::TrigScintTrackProducer, ldmx::TrigScintClusterProducer, ldmx::TrigScintHitDQM, ldmx::TrigScintDQM, ldmx::RecoilTrackerDQM, and ldmx::PhotoNuclearDQM.
Definition at line 138 of file EventProcessor.h.
{
             }
setStorageHint() [1/2]
void ldmx::EventProcessor::setStorageHint (ldmx::StorageControlHint hint) inline
Mark the current event as having the given storage control hint from this module
Parameters
controlhint The storage control hint to apply for the given event
Definition at line 171 of file EventProcessor.h.
{
                 setStorageHint(hint,"");
             }
Referenced by ldmx::EcalDigiVerifier::analyze(), ldmx::DNNEcalVetoProcessor::produce(), ldmx::EcalVetoProcessor::produce(), ldmx::RecoilMissesEcalSkimmer::produce(), ldmx::TrackerVetoProcessor::produce(), ldmx::TriggerProcessor::produce(), ldmx::HcalVetoProcessor::produce(), and ldmx::test::TestProducer::produce().
setStorageHint() [2/2]
void ldmx::EventProcessor::setStorageHint (ldmx::StorageControlHint hint, const std::string & purposeString)
Mark the current event as having the given storage control hint from this module and the given purpose string
Parameters
controlhint The storage control hint to apply for the given event
purposeString A purpose string which can be used in the skim control configuration
Definition at line 27 of file EventProcessor.cxx.
{
         process_.getStorageController().addHint(name_,hint,purposeString);
     }
References ldmx::StorageControl::addHint(), ldmx::Process::getStorageController(), name_, and process_.
Member Data Documentation
histoDir_
TDirectory* ldmx::EventProcessor::histoDir_ {0} private
Histogram directory
Definition at line 248 of file EventProcessor.h.
Referenced by getHistoDirectory().
name_
std::string ldmx::EventProcessor::name_ private
The name of the EventProcessor.
Definition at line 245 of file EventProcessor.h.
Referenced by getHistoDirectory(), getName(), and setStorageHint().
process_
Process& ldmx::EventProcessor::process_ private
Handle to the Process.
Definition at line 242 of file EventProcessor.h.
Referenced by getConditions(), getEventHeader(), getHistoDirectory(), getLogFrequency(), getRunNumber(), and setStorageHint().
The documentation for this class was generated from the following files:
Framework/include/Framework/EventProcessor.h
Framework/src/EventProcessor.cxx