LDMX Software: hcal::HcalTriggerGeometry Class Reference
hcal::HcalTriggerGeometry Class Reference
defines the relationship between HCal strips and CMB quad trigger primitives and provides geometry information for trigger primitives
#include <HcalTriggerGeometry.h>
Public Member Functions
HcalTriggerGeometry (const ldmx::HcalGeometry *hcalGeom=0)
std::vector< ldmx::HcalDigiID > contentsOfQuad (ldmx::HcalTriggerID triggerCell) const
std::vector< ldmx::HcalDigiID > contentsOfSTQ (ldmx::HcalTriggerID triggerCell) const
ldmx::HcalTriggerID belongsToQuad (ldmx::HcalDigiID precisionCell) const
ldmx::HcalTriggerID belongsToSTQ (ldmx::HcalDigiID precisionCell) const
Public Member Functions inherited from framework::ConditionsObject
ConditionsObject (const std::string &name)
virtual ~ConditionsObject ()
std::string getName () const
Static Public Attributes
static constexpr const char * CONDITIONS_OBJECT_NAME {"HcalTriggerGeometry"}
Private Attributes
const ldmx::HcalGeometry * hcalGeometry_
Detailed Description
defines the relationship between HCal strips and CMB quad trigger primitives and provides geometry information for trigger primitives
Definition at line 25 of file HcalTriggerGeometry.h.
Constructor & Destructor Documentation
HcalTriggerGeometry()
hcal::HcalTriggerGeometry::HcalTriggerGeometry (const ldmx::HcalGeometry * hcalGeom = 0)
Definition at line 10 of file HcalTriggerGeometry.cxx.
  : ConditionsObject(CONDITIONS_OBJECT_NAME),
    hcalGeometry_{hcalGeom} {
}
Member Function Documentation
belongsToQuad()
ldmx::HcalTriggerID hcal::HcalTriggerGeometry::belongsToQuad (ldmx::HcalDigiID precisionCell) const
Returns which trigger cell this precision cell is associated with, or a null id if there is no such association.
Definition at line 45 of file HcalTriggerGeometry.cxx.
{
  return ldmx::HcalTriggerID(precisionCell.section(), precisionCell.layer(),
                             precisionCell.strip()/4, precisionCell.end());
}
References ldmx::HcalDigiID::end(), ldmx::HcalDigiID::layer(), ldmx::HcalDigiID::section(), and ldmx::HcalDigiID::strip().
Referenced by hcal::HcalTrigPrimDigiProducer::produce().
belongsToSTQ()
ldmx::HcalTriggerID hcal::HcalTriggerGeometry::belongsToSTQ (ldmx::HcalDigiID precisionCell) const
Definition at line 51 of file HcalTriggerGeometry.cxx.
{
  // 2x2 groups of quads, with "superlayers" like:
  // 0 1 0 1 2 3 2 3 ...
  // V H V H V H V H ...
  int layer = precisionCell.layer();
  int superlayer = 2*(layer / 4) + (layer % 4)%2;
  return ldmx::HcalTriggerID(precisionCell.section(), superlayer,
                             precisionCell.strip()/8, precisionCell.end());
}
contentsOfQuad()
std::vector< ldmx::HcalDigiID > hcal::HcalTriggerGeometry::contentsOfQuad (ldmx::HcalTriggerID triggerCell) const
Returns the set of precision (full-granularity/DAQ) cells which are associated with the given trigger cell.
Definition at line 16 of file HcalTriggerGeometry.cxx.
{
  std::vector<ldmx::HcalDigiID> retval;
  for(int iStrip=0;iStrip<4;iStrip++){
    int strip = iStrip+4*triggerCell.superstrip();
    if (strip >= hcalGeometry_->getNumStrips(triggerCell.section())) break;
    retval.push_back( ldmx::HcalDigiID(triggerCell.section(), triggerCell.layer(),
                                       strip, triggerCell.end()) );
  }
  return retval;
}
References ldmx::HcalTriggerID::end(), ldmx::HcalTriggerID::layer(), and ldmx::HcalTriggerID::superstrip().
Referenced by hcal::HcalTrigPrimDigiProducer::produce().
contentsOfSTQ()
std::vector< ldmx::HcalDigiID > hcal::HcalTriggerGeometry::contentsOfSTQ (ldmx::HcalTriggerID triggerCell) const
Definition at line 28 of file HcalTriggerGeometry.cxx.
{
  std::vector<ldmx::HcalDigiID> retval;
  for(int iStrip=0;iStrip<8;iStrip++){
    for(int iLayer=0;iLayer<2;iLayer++){
      int strip = iStrip+8*triggerCell.superstrip();
      if (strip >= hcalGeometry_->getNumStrips(triggerCell.section())) continue;
      int tlayer = triggerCell.layer();
      int player = 2*(tlayer+iStrip) - tlayer%2;
      if (player >= hcalGeometry_->getNumLayers(triggerCell.section())) continue;
      retval.push_back(ldmx::HcalDigiID(triggerCell.section(), player,
                                        strip, triggerCell.end()));
    }
  }
  return retval;
}
Member Data Documentation
CONDITIONS_OBJECT_NAME
constexpr const char* hcal::HcalTriggerGeometry::CONDITIONS_OBJECT_NAME {"HcalTriggerGeometry"} static constexpr
Definition at line 27 of file HcalTriggerGeometry.h.
hcalGeometry_
const ldmx::HcalGeometry* hcal::HcalTriggerGeometry::hcalGeometry_ private
Reference to the Hcal geometry used for trigger geometry information
Definition at line 49 of file HcalTriggerGeometry.h.
The documentation for this class was generated from the following files:
Hcal/include/Hcal/HcalTriggerGeometry.h
Hcal/src/Hcal/HcalTriggerGeometry.cxx