LDMX Software: ActsExamples::IndexSourceLink Class Reference
ActsExamples::IndexSourceLink Class Reference final
#include <IndexSourceLink.h>
Public Member Functions
constexpr IndexSourceLink (Acts::GeometryIdentifier gid, Index idx)
Construct from geometry identifier and index.
IndexSourceLink ()=default
satisfy SourceLinkConcept.
IndexSourceLink (const IndexSourceLink &)=default
IndexSourceLink (IndexSourceLink &&)=default
IndexSourceLink & operator= (const IndexSourceLink &)=default
IndexSourceLink & operator= (IndexSourceLink &&)=default
constexpr Index index () const
Access the index.
Acts::GeometryIdentifier geometryId () const
Private Attributes
Acts::GeometryIdentifier m_geometryId
Index m_index = 0
Friends
bool operator== (const IndexSourceLink &lhs, const IndexSourceLink &rhs)
bool operator!= (const IndexSourceLink &lhs, const IndexSourceLink &rhs)
Detailed Description
A source link that stores just an index.
This is intentionally kept as barebones as possible. The source link is just a reference and will be copied, moved around, etc. often. Keeping it small and separate from the actual, potentially large, measurement data should result in better overall performance. Using an index instead of e.g. a pointer, means source link and measurement are decoupled and the measurement represenation can be easily changed without having to also change the source link.
Definition at line 30 of file IndexSourceLink.h.
Constructor & Destructor Documentation
IndexSourceLink()
constexpr ActsExamples::IndexSourceLink::IndexSourceLink (Acts::GeometryIdentifier gid, Index idx) inline constexpr
Construct from geometry identifier and index.
Definition at line 33 of file IndexSourceLink.h.
      : m_geometryId(gid), m_index(idx) {}
Member Function Documentation
geometryId()
Acts::GeometryIdentifier ActsExamples::IndexSourceLink::geometryId () const inline
Definition at line 47 of file IndexSourceLink.h.
{ return m_geometryId; }
index()
constexpr Index ActsExamples::IndexSourceLink::index () const inline constexpr
Access the index.
Definition at line 45 of file IndexSourceLink.h.
{ return m_index; }
Referenced by tracking::sim::LdmxMeasurementCalibrator::calibrate(), tracking::sim::LdmxMeasurementCalibrator::calibrate_1d(), and tracking::reco::CKFProcessor::produce().
Friends And Related Function Documentation
operator!=
bool operator!= (const IndexSourceLink & lhs, const IndexSourceLink & rhs) friend
Definition at line 58 of file IndexSourceLink.h.
{
    return not(lhs == rhs);
  }
operator==
bool operator== (const IndexSourceLink & lhs, const IndexSourceLink & rhs) friend
Definition at line 53 of file IndexSourceLink.h.
{
    return (lhs.geometryId() == rhs.geometryId()) and
           (lhs.m_index == rhs.m_index);
  }
Member Data Documentation
m_geometryId
Acts::GeometryIdentifier ActsExamples::IndexSourceLink::m_geometryId private
Definition at line 50 of file IndexSourceLink.h.
m_index
Index ActsExamples::IndexSourceLink::m_index = 0 private
Definition at line 51 of file IndexSourceLink.h.
The documentation for this class was generated from the following file:
Tracking/include/Tracking/Sim/IndexSourceLink.h