LDMX Software: framework::Conditions Class Reference
framework::Conditions Class Reference
Container and cache for conditions and conditions providers.
#include <Conditions.h>
Classes
struct CacheEntry
Public Member Functions
Conditions (Process &)
~Conditions ()
const ConditionsObject * getConditionPtr (const std::string &condition_name)
template<class T >
const T & getCondition (const std::string &condition_name)
ConditionsIOV getConditionIOV (const std::string &condition_name) const
void onProcessStart ()
void onProcessEnd ()
void onNewRun (ldmx::RunHeader &)
void createConditionsObjectProvider (const std::string &classname, const std::string &instancename, const std::string &tagname, const framework::config::Parameters &params)
Private Attributes
Process & process_
std::map< std::string, ConditionsObjectProvider * > providerMap_
std::map< std::string, CacheEntry > cache_
Detailed Description
Container and cache for conditions and conditions providers.
Definition at line 43 of file Conditions.h.
Constructor & Destructor Documentation
Conditions()
framework::Conditions::Conditions (Process & p)
Constructor
Definition at line 8 of file Conditions.cxx.
 : process_{p} {}
~Conditions()
framework::Conditions::~Conditions () inline
Class destructor.
Definition at line 53 of file Conditions.h.
 { ; }
Member Function Documentation
createConditionsObjectProvider()
void framework::Conditions::createConditionsObjectProvider (const std::string & classname, const std::string & instancename, const std::string & tagname, const framework::config::Parameters & params)
Create a ConditionsObjectProvider given the information
Definition at line 10 of file Conditions.cxx.
{
   ConditionsObjectProvider* cop =
       PluginFactory::getInstance().createConditionsObjectProvider(
           classname, objname, tagname, params, process_);
   if (cop) {
     std::string provides = cop->getConditionObjectName();
     if (providerMap_.find(provides) != providerMap_.end()) {
       EXCEPTION_RAISE(
           "ConditionAmbiguityException",
           std::string(
               "Multiple ConditonsObjectProviders configured to provide ") +
               provides);
     }
     providerMap_[provides] = cop;
   } else {
     EXCEPTION_RAISE("ConditionsException",
                     "No ConditionsObjectProvider for " + classname);
   }
 }
References framework::PluginFactory::createConditionsObjectProvider(), framework::ConditionsObjectProvider::getConditionObjectName(), framework::PluginFactory::getInstance(), process_, and providerMap_.
Referenced by framework::Process::Process().
getCondition()
template<class T > const T& framework::Conditions::getCondition (const std::string & condition_name) inline
Primary request action for a conditions object If the object is in the cache and still valid (IOV), the cached object will be returned. If it is not in the cache, or is out of date, the ConditionsObjectProvider::getCondition method will be called to provide the object.
See also
getConditionPtr
Template Parameters
T type to cast condition object to
Parameters
[in] condition_name name of condition to retrieve
Returns
const reference to conditions object
Definition at line 83 of file Conditions.h.
{
     return dynamic_cast<const T&>(*getConditionPtr(condition_name));
   }
References getConditionPtr().
Referenced by framework::EventProcessor::getCondition().
getConditionIOV()
ConditionsIOV framework::Conditions::getConditionIOV (const std::string & condition_name) const
Access the IOV for the given condition
Parameters
[in] condition_name name of condition to get IOV for
Returns
Interval Of Validity for the input condition name
Definition at line 45 of file Conditions.cxx.
{
   auto cacheptr = cache_.find(condition_name);
   if (cacheptr == cache_.end())
     return ConditionsIOV();
   else
     return cacheptr->second.iov;
 }
References cache_.
Referenced by framework::ConditionsObjectProvider::requestParentCondition().
getConditionPtr()
const ConditionsObject * framework::Conditions::getConditionPtr (const std::string & condition_name)
Primary request action for a conditions object If the object is in the cache and still valid (IOV), the cached object will be returned. If it is not in the cache, or is out of date, the ConditionsObjectProvider::getCondition method will be called to provide the object.
Exceptions
Exception if condition object or provider for that object is not found.
Parameters
[in] condition_name name of condition to retrieve
Returns
pointer to conditions object with input name
if still valid, we return what we have
Definition at line 54 of file Conditions.cxx.
{
   const ldmx::EventHeader& context = *(process_.getEventHeader());
   auto cacheptr = cache_.find(condition_name);
   if (cacheptr == cache_.end()) {
     auto copptr = providerMap_.find(condition_name);
     if (copptr == providerMap_.end()) {
       EXCEPTION_RAISE(
           "ConditionUnavailable",
           std::string("No provider is available for : " + condition_name));
     }
     std::pair<const ConditionsObject*, ConditionsIOV> cond =
         copptr->second->getCondition(context);
     if (!cond.first) {
       EXCEPTION_RAISE(
           "ConditionUnavailable",
           std::string("Null condition returned for requested item : " +
                       condition_name));
     }
     // first request, create a cache entry
     CacheEntry ce;
     ce.iov = cond.second;
     ce.obj = cond.first;
     ce.provider = copptr->second;
     cache_[condition_name] = ce;
     return ce.obj;
   } else {
     if (cacheptr->second.iov.validForEvent(context))
       return cacheptr->second.obj;
     else {
       // if not, we release the old object
       cacheptr->second.provider->releaseConditionsObject(cacheptr->second.obj);
       // now ask for a new one
       std::pair<const ConditionsObject*, ConditionsIOV> cond =
           cacheptr->second.provider->getCondition(context);
       if (!cond.first) {
         std::stringstream s;
         s << "Unable to update condition '" << condition_name << "' for event "
           << context.getEventNumber() << " run " << context.getRun();
         if (context.isRealData())
           s << " DATA";
         else
           s << " MC";
         EXCEPTION_RAISE("ConditionUnavailable", s.str());
       }
       cacheptr->second.iov = cond.second;
       cacheptr->second.obj = cond.first;
       return cond.first;
     }
   }
 }
References cache_, framework::Process::getEventHeader(), ldmx::EventHeader::getEventNumber(), ldmx::EventHeader::getRun(), framework::Conditions::CacheEntry::iov, ldmx::EventHeader::isRealData(), framework::Conditions::CacheEntry::obj, process_, framework::Conditions::CacheEntry::provider, and providerMap_.
Referenced by getCondition(), and framework::ConditionsObjectProvider::requestParentCondition().
onNewRun()
void framework::Conditions::onNewRun (ldmx::RunHeader & rh)
Calls onNewRun for all ConditionsObjectProviders
Definition at line 41 of file Conditions.cxx.
{
   for (auto ptr : providerMap_) ptr.second->onNewRun(rh);
 }
References providerMap_.
Referenced by framework::Process::run().
onProcessEnd()
void framework::Conditions::onProcessEnd ()
Calls onProcessEnd for all ConditionsObjectProviders
Definition at line 37 of file Conditions.cxx.
{
   for (auto ptr : providerMap_) ptr.second->onProcessEnd();
 }
References providerMap_.
onProcessStart()
void framework::Conditions::onProcessStart ()
Calls onProcessStart for all ConditionsObjectProviders
Definition at line 33 of file Conditions.cxx.
{
   for (auto ptr : providerMap_) ptr.second->onProcessStart();
 }
References providerMap_.
Referenced by framework::Process::run().
Member Data Documentation
cache_
std::map<std::string, CacheEntry> framework::Conditions::cache_ private
Conditions cache
Definition at line 137 of file Conditions.h.
Referenced by getConditionIOV(), and getConditionPtr().
process_
Process& framework::Conditions::process_ private
Handle to the Process.
Definition at line 119 of file Conditions.h.
Referenced by createConditionsObjectProvider(), and getConditionPtr().
providerMap_
std::map<std::string, ConditionsObjectProvider*> framework::Conditions::providerMap_ private
Map of who provides which condition
Definition at line 122 of file Conditions.h.
Referenced by createConditionsObjectProvider(), getConditionPtr(), onNewRun(), onProcessEnd(), and onProcessStart().
The documentation for this class was generated from the following files:
Framework/include/Framework/Conditions.h
Framework/src/Framework/Conditions.cxx