LDMX Software: ldmx::G4TrackerHit Class Reference
ldmx::G4TrackerHit Class Reference
Track hit which is used to create output SimTrackerHit collection.
#include <G4TrackerHit.h>
Public Member Functions
G4TrackerHit ()
virtual ~G4TrackerHit ()
void Draw ()
void Print ()
std::ostream & print (std::ostream &os)
void * operator new (size_t s)
void operator delete (void *aHit)
void setTrackID (int trackID)
int getTrackID ()
int getID ()
void setID (int id)
int getPdgID ()
void setPdgID (int pdgid)
int getLayerID ()
void setLayerID (int layerID)
int getModuleID () const
void setModuleID (const int moduleID)
float getEdep ()
float getEnergy ()
void setEdep (float edep)
float getTime ()
void setTime (float time)
const G4ThreeVector & getMomentum ()
void setMomentum (float px, float py, float pz)
const G4ThreeVector & getPosition ()
void setPosition (float x, float y, float z)
void setEnergy (float energy)
float getPathLength ()
void setPathLength (float pathLength)
Private Attributes
G4int trackID_ {0}
int id_ {0}
int pdgid_ {0}
int layerID_ {0}
int moduleID_ {0}
float edep_ {0}
float time_ {0}
G4ThreeVector momentum_
G4ThreeVector position_
float energy_ {0}
float pathLength_ {0}
Detailed Description
Track hit which is used to create output SimTrackerHit collection.
Note
One of these is created for every step in a TrackerSD. These are basically copied verbatim into SimTrackerHit objects by the RootPersistencyManager.
Definition at line 35 of file G4TrackerHit.h.
Constructor & Destructor Documentation
G4TrackerHit()
ldmx::G4TrackerHit::G4TrackerHit () inline
Class constructor.
Definition at line 42 of file G4TrackerHit.h.
{
             }
~G4TrackerHit()
virtual ldmx::G4TrackerHit::~G4TrackerHit () inline virtual
Class destructor.
Definition at line 48 of file G4TrackerHit.h.
{
             }
Member Function Documentation
Draw()
void ldmx::G4TrackerHit::Draw ()
Draw the hit in the Geant4 runtime.
Definition at line 13 of file G4TrackerHit.cxx.
{
         G4VVisManager* visManager = G4VVisManager::GetConcreteInstance();
         if (visManager) {
             G4Point3D p3D = G4Point3D(this->position_);
             G4Circle chit(p3D);
             chit.SetScreenDiameter(3.0);
             chit.SetFillStyle(G4Circle::filled);
             G4Colour col(1.0, 0.0, 1.0);
             chit.SetVisAttributes(G4VisAttributes(col));
             visManager->Draw(chit);
         }
     }
References position_.
getEdep()
float ldmx::G4TrackerHit::getEdep () inline
Get the energy deposition.
Returns
The energy deposition.
Definition at line 162 of file G4TrackerHit.h.
{
                 return edep_;
             }
References edep_.
Referenced by ldmx::RootPersistencyManager::writeTrackerHitsCollection().
getEnergy()
float ldmx::G4TrackerHit::getEnergy () inline
Get the energy .
Returns
The energy .
Definition at line 170 of file G4TrackerHit.h.
{
                 return energy_;
             }
References energy_.
Referenced by ldmx::RootPersistencyManager::writeTrackerHitsCollection().
getID()
int ldmx::G4TrackerHit::getID () inline
Get the detector ID.
Returns
The detector ID.
Definition at line 100 of file G4TrackerHit.h.
{
                 return id_;
             }
References id_.
Referenced by ldmx::RootPersistencyManager::writeTrackerHitsCollection().
getLayerID()
int ldmx::G4TrackerHit::getLayerID () inline
Get the layer ID.
Returns
The layer ID.
Definition at line 132 of file G4TrackerHit.h.
{
                 return layerID_;
             }
References layerID_.
Referenced by ldmx::RootPersistencyManager::writeTrackerHitsCollection().
getModuleID()
int ldmx::G4TrackerHit::getModuleID () const inline
Get the module ID associated with a hit. This is used to uniquely identify a sensor within a layer.
Returns
The module ID associated with a hit.
Definition at line 149 of file G4TrackerHit.h.
 { return moduleID_; };
References moduleID_.
Referenced by ldmx::RootPersistencyManager::writeTrackerHitsCollection().
getMomentum()
const G4ThreeVector& ldmx::G4TrackerHit::getMomentum () inline
Get the XYZ momentum.
Returns
The XYZ momentum.
Definition at line 202 of file G4TrackerHit.h.
{
                 return momentum_;
             }
References momentum_.
Referenced by ldmx::RootPersistencyManager::writeTrackerHitsCollection().
getPathLength()
float ldmx::G4TrackerHit::getPathLength () inline
Get the path length from the pre and post step points [mm].
Returns
The path length.
Definition at line 250 of file G4TrackerHit.h.
{
                 return pathLength_;
             }
References pathLength_.
Referenced by ldmx::RootPersistencyManager::writeTrackerHitsCollection().
getPdgID()
int ldmx::G4TrackerHit::getPdgID () inline
Get the PDG ID.
Returns
The detector ID.
Definition at line 116 of file G4TrackerHit.h.
{
                 return pdgid_;
             }
References pdgid_.
Referenced by ldmx::RootPersistencyManager::writeTrackerHitsCollection().
getPosition()
const G4ThreeVector& ldmx::G4TrackerHit::getPosition () inline
Get the XYZ hit position [mm].
Returns
The hit position.
Definition at line 222 of file G4TrackerHit.h.
{
                 return position_;
             }
References position_.
Referenced by ldmx::RootPersistencyManager::writeTrackerHitsCollection().
getTime()
float ldmx::G4TrackerHit::getTime () inline
Get the global time.
Returns
The global time.
Definition at line 186 of file G4TrackerHit.h.
{
                 return time_;
             }
References time_.
Referenced by ldmx::RootPersistencyManager::writeTrackerHitsCollection().
getTrackID()
int ldmx::G4TrackerHit::getTrackID () inline
Get the track ID.
Returns
The track ID.
Definition at line 92 of file G4TrackerHit.h.
{
                 return this->trackID_;
             }
References trackID_.
Referenced by ldmx::RootPersistencyManager::writeTrackerHitsCollection().
operator delete()
void ldmx::G4TrackerHit::operator delete (void * aHit) inline
Delete a hit object.
Parameters
aHit The hit to delete.
Implementation of custom delete operator.
Definition at line 339 of file G4TrackerHit.h.
{
         G4TrackerHitAllocator.FreeSingle((G4TrackerHit*) aHit);
     }
References ldmx::G4TrackerHitAllocator.
operator new()
void * ldmx::G4TrackerHit::operator new (size_t s) inline
Create a new hit object.
Parameters
s The size of the hit object.
Implementation of custom new operator.
Definition at line 330 of file G4TrackerHit.h.
{
         void* aHit;
         aHit = (void*) G4TrackerHitAllocator.MallocSingle();
         return aHit;
     }
References ldmx::G4TrackerHitAllocator.
Print()
void ldmx::G4TrackerHit::Print ()
Print out hit information.
Definition at line 31 of file G4TrackerHit.cxx.
{
         print(std::cout);
     }
References print().
Referenced by ldmx::TrackerSD::ProcessHits(), and ldmx::ScoringPlaneSD::ProcessHits().
print()
std::ostream & ldmx::G4TrackerHit::print (std::ostream & os)
Print hit information to an output stream.
Parameters
os The output stream.
Returns
The same output stream.
Definition at line 35 of file G4TrackerHit.cxx.
{
         os << "G4TrackerHit { " "edep: " << this->edep_
                 << ", " "position: (" << this->position_[0] << ", " << this->position_[1] << ", " << this->position_[2] << "), "
                 <<  "layerID: " << this->layerID_ << ", "
                 << "momentum: (" << this->momentum_[0] << ", " << this->momentum_[1] << ", " << this->momentum_[2] << "), "
                 << "pathLength: " << this->pathLength_ << ", " << "time: " << this->time_ << " }" << std::endl;
         return os;
     }
References edep_, layerID_, momentum_, pathLength_, position_, and time_.
Referenced by Print().
setEdep()
void ldmx::G4TrackerHit::setEdep (float edep) inline
Set the energy deposition.
Parameters
edep The energy deposition.
Definition at line 178 of file G4TrackerHit.h.
{
                 this->edep_ = edep;
             }
References edep_.
Referenced by ldmx::TrackerSD::ProcessHits(), and ldmx::ScoringPlaneSD::ProcessHits().
setEnergy()
void ldmx::G4TrackerHit::setEnergy (float energy) inline
Set the energy.
Parameters
edep The energy.
Definition at line 242 of file G4TrackerHit.h.
{
                 this->energy_ = energy;
             }
References energy_.
Referenced by ldmx::TrackerSD::ProcessHits(), and ldmx::ScoringPlaneSD::ProcessHits().
setID()
void ldmx::G4TrackerHit::setID (int id) inline
Set the detector ID.
Parameters
id The detector ID.
Definition at line 108 of file G4TrackerHit.h.
{
                 this->id_ = id;
             }
References id_.
Referenced by ldmx::TrackerSD::ProcessHits(), and ldmx::ScoringPlaneSD::ProcessHits().
setLayerID()
void ldmx::G4TrackerHit::setLayerID (int layerID) inline
Set the layer ID.
Parameters
layerID The layer ID.
Definition at line 140 of file G4TrackerHit.h.
{
                 this->layerID_ = layerID;
             }
References layerID_.
Referenced by ldmx::TrackerSD::ProcessHits(), and ldmx::ScoringPlaneSD::ProcessHits().
setModuleID()
void ldmx::G4TrackerHit::setModuleID (const int moduleID) inline
Set the module ID associated with a hit. This is used to uniquely identify a sensor within a layer.
Returns
moduleID The module ID associated with a hit.
Definition at line 156 of file G4TrackerHit.h.
 { this->moduleID_ = moduleID; };
References moduleID_.
Referenced by ldmx::TrackerSD::ProcessHits().
setMomentum()
void ldmx::G4TrackerHit::setMomentum (float px, float py, float pz) inline
Set the momentum.
Parameters
px The X momentum.
py The Y momentum.
pz The Z momentum.
Definition at line 212 of file G4TrackerHit.h.
{
                 momentum_.setX(px);
                 momentum_.setY(py);
                 momentum_.setZ(pz);
             }
References momentum_.
Referenced by ldmx::TrackerSD::ProcessHits(), and ldmx::ScoringPlaneSD::ProcessHits().
setPathLength()
void ldmx::G4TrackerHit::setPathLength (float pathLength) inline
Set the path length [mm]. @pathLength The path length.
Definition at line 258 of file G4TrackerHit.h.
{
                 this->pathLength_ = pathLength;
             }
References pathLength_.
Referenced by ldmx::TrackerSD::ProcessHits(), and ldmx::ScoringPlaneSD::ProcessHits().
setPdgID()
void ldmx::G4TrackerHit::setPdgID (int pdgid) inline
Set the PDG ID.
Parameters
id The detector ID.
Definition at line 124 of file G4TrackerHit.h.
{
                 this->pdgid_ = pdgid;
             }
References pdgid_.
Referenced by ldmx::TrackerSD::ProcessHits(), and ldmx::ScoringPlaneSD::ProcessHits().
setPosition()
void ldmx::G4TrackerHit::setPosition (float x, float y, float z) inline
Set the hit position [mm].
Parameters
x The X position.
y The Y position. 2param z The Z position.
Definition at line 232 of file G4TrackerHit.h.
{
                 position_.setX(x);
                 position_.setY(y);
                 position_.setZ(z);
             }
References position_.
Referenced by ldmx::TrackerSD::ProcessHits(), and ldmx::ScoringPlaneSD::ProcessHits().
setTime()
void ldmx::G4TrackerHit::setTime (float time) inline
Set the global time.
Parameters
time The global time.
Definition at line 194 of file G4TrackerHit.h.
{
                 this->time_ = time;
             }
References time_.
Referenced by ldmx::TrackerSD::ProcessHits(), and ldmx::ScoringPlaneSD::ProcessHits().
setTrackID()
void ldmx::G4TrackerHit::setTrackID (int trackID) inline
Set the track ID.
Parameters
trackID The track ID.
Definition at line 84 of file G4TrackerHit.h.
{
                 this->trackID_ = trackID;
             }
References trackID_.
Referenced by ldmx::TrackerSD::ProcessHits(), and ldmx::ScoringPlaneSD::ProcessHits().
Member Data Documentation
edep_
float ldmx::G4TrackerHit::edep_ {0} private
The energy deposition.
Definition at line 289 of file G4TrackerHit.h.
Referenced by getEdep(), print(), and setEdep().
energy_
float ldmx::G4TrackerHit::energy_ {0} private
The energy .
Definition at line 309 of file G4TrackerHit.h.
Referenced by getEnergy(), and setEnergy().
id_
int ldmx::G4TrackerHit::id_ {0} private
The detector ID.
Definition at line 272 of file G4TrackerHit.h.
Referenced by getID(), and setID().
layerID_
int ldmx::G4TrackerHit::layerID_ {0} private
The layer ID.
Definition at line 281 of file G4TrackerHit.h.
Referenced by getLayerID(), print(), and setLayerID().
moduleID_
int ldmx::G4TrackerHit::moduleID_ {0} private
The module ID.
Definition at line 284 of file G4TrackerHit.h.
Referenced by getModuleID(), and setModuleID().
momentum_
G4ThreeVector ldmx::G4TrackerHit::momentum_ private
The XYZ momentum.
Definition at line 299 of file G4TrackerHit.h.
Referenced by getMomentum(), print(), and setMomentum().
pathLength_
float ldmx::G4TrackerHit::pathLength_ {0} private
The path length.
Definition at line 314 of file G4TrackerHit.h.
Referenced by getPathLength(), print(), and setPathLength().
pdgid_
int ldmx::G4TrackerHit::pdgid_ {0} private
The detector ID.
Definition at line 277 of file G4TrackerHit.h.
Referenced by getPdgID(), and setPdgID().
position_
G4ThreeVector ldmx::G4TrackerHit::position_ private
The XYZ position.
Definition at line 304 of file G4TrackerHit.h.
Referenced by Draw(), getPosition(), print(), and setPosition().
time_
float ldmx::G4TrackerHit::time_ {0} private
The global time.
Definition at line 294 of file G4TrackerHit.h.
Referenced by getTime(), print(), and setTime().
trackID_
G4int ldmx::G4TrackerHit::trackID_ {0} private
The track ID.
Definition at line 267 of file G4TrackerHit.h.
Referenced by getTrackID(), and setTrackID().
The documentation for this class was generated from the following files:
SimCore/include/SimCore/G4TrackerHit.h
SimCore/src/G4TrackerHit.cxx