LDMX Software: ldmx::EcalHitIO Class Reference
ldmx::EcalHitIO Class Reference
Provides hit readout for simulated ECal detector.
#include <EcalHitIO.h>
Public Types
typedef std::pair< int, int > LayerCellPair
Public Member Functions
EcalHitIO ()
~EcalHitIO ()
void configure (const Parameters &ps)
void writeHitsCollection (G4CalorimeterHitsCollection *hc, std::vector< SimCalorimeterHit > &outputColl)
void setEnableHitContribs (bool enableHitContribs)
void setCompressHitContribs (bool compressHitContribs)
Private Attributes
std::unique_ptr< EcalHexReadout > hexReadout_
bool enableHitContribs_ {true}
bool compressHitContribs_ {true}
Detailed Description
Provides hit readout for simulated ECal detector.
Note
This class uses the EcalHexReadout to transform the G4CalorimeterHit hits collection into a collection of SimCalorimeterHit objects assigned to hexagonal cells by their ID and positions. Energy depositions in the same cells are combined together into single hits.
It can be run in three modes:
Compressed hit contributions combined by matching SimParticle and PDG code (default mode)
Full hit contributions with one record per step (when compressHitContribs_ is false)
No hit contribution information where energy is combined but vectors are not filled (when enableHitContribs_ is false)
Definition at line 41 of file EcalHitIO.h.
Member Typedef Documentation
LayerCellPair
typedef std::pair<int, int> ldmx::EcalHitIO::LayerCellPair
Layer-cell pair.
Definition at line 48 of file EcalHitIO.h.
Constructor & Destructor Documentation
EcalHitIO()
ldmx::EcalHitIO::EcalHitIO () inline
Class constructor.
Definition at line 55 of file EcalHitIO.h.
 { }
~EcalHitIO()
ldmx::EcalHitIO::~EcalHitIO () inline
Class destructor.
Definition at line 60 of file EcalHitIO.h.
 { }
Member Function Documentation
configure()
void ldmx::EcalHitIO::configure (const Parameters & ps) inline
Configure the EcalHitIO using the passed parameters
Definition at line 65 of file EcalHitIO.h.
{
                 enableHitContribs_   = ps.getParameter<bool>("enableHitContribs");
                 compressHitContribs_ = ps.getParameter<bool>("compressHitContribs");
                 auto hexReadout{ps.getParameter<Parameters>("ecalHexReadout")};
                 hexReadout_ = std::make_unique<EcalHexReadout>(hexReadout);
             }
References compressHitContribs_, enableHitContribs_, ldmx::Parameters::getParameter(), and hexReadout_.
Referenced by ldmx::RootPersistencyManager::RootPersistencyManager().
setCompressHitContribs()
void ldmx::EcalHitIO::setCompressHitContribs (bool compressHitContribs) inline
Set whether hit contributions should be compressed by particle and PDG code.
Parameters
compressHitContribs True to compress hit contribution information.
Definition at line 92 of file EcalHitIO.h.
{
                 compressHitContribs_ = compressHitContribs;
             }
References compressHitContribs_.
setEnableHitContribs()
void ldmx::EcalHitIO::setEnableHitContribs (bool enableHitContribs) inline
Set whether hit contributions should be enabled for the output hits.
Parameters
enableHitContribs True to enable hit contributions.
Definition at line 84 of file EcalHitIO.h.
{
                 enableHitContribs_ = enableHitContribs;
             }
References enableHitContribs_.
writeHitsCollection()
void ldmx::EcalHitIO::writeHitsCollection (G4CalorimeterHitsCollection * hc, std::vector< SimCalorimeterHit > & outputColl)
Write out a Geant4 hits collection to the provided ROOT array.
Parameters
hc The input hits collection.
outputColl The output collection in ROOT.
Assign XY position to the hit using the ECal hex readout. Z position is set from the original hit, which should be the middle of the sensor.
Definition at line 14 of file EcalHitIO.cxx.
{
         //get ancestral mapping of tracks
         auto trackMap{UserTrackingAction::getUserTrackingAction()->getTrackMap()};
         int nHits = hc->GetSize();
         std::map< int, SimCalorimeterHit > hitMap;
         // Loop over input hits from Geant4.
         for (int iHit = 0; iHit < nHits; iHit++) {
             // Get the hit and its ID.
             G4CalorimeterHit* g4hit = (G4CalorimeterHit*) hc->GetHit(iHit);
             int hitID = g4hit->getID();
             // See if hit exists in map already.
             std::map<int, SimCalorimeterHit >::iterator it = hitMap.find(hitID);
             // Is it a new hit?
             if (it == hitMap.end()) {
                 // Create sim hit and assign the ID.
                 hitMap[hitID] = SimCalorimeterHit();
                 hitMap[hitID].setID(hitID);
                 double x,y,z;
                 hexReadout_->getCellAbsolutePosition( hitID , x , y , z );
                 hitMap[hitID].setPosition( x , y , z );
             }
             // Get info from the G4 hit.
             float edep = g4hit->getEdep();
             float time = g4hit->getTime();
             int pdgCode = g4hit->getPdgCode();
             // Is hit contrib output enabled?
             if (enableHitContribs_) {
                 // Find the SimParticle associated with this hit.
                 int trackID = g4hit->getTrackID();
                 // Find if there is an existing hit contrib.
                 int contribIndex = hitMap[hitID].findContribIndex(trackID, pdgCode);
                 // Is contrib output being compressed and a record exists for this SimParticle and PDG code?
                 if (compressHitContribs_ && contribIndex != -1) {
                     // Update an existing hit contrib.
                     hitMap[hitID].updateContrib(contribIndex, edep, time);
                 } else {
                     // Add a hit contrib because all steps are being saved or there is not an existing record.
                     hitMap[hitID].addContrib(trackMap->findIncident(trackID),trackID, pdgCode, edep, time);
                 }
             } else {
                 // Hit contributions are not being saved so manually increment the edep and set time.
                 hitMap[hitID].setEdep(hitMap[hitID].getEdep() + edep);
                 if (time < hitMap[hitID].getTime() || hitMap[hitID].getTime() == 0) {
                     hitMap[hitID].setTime(time);
                 }
             } //contrib output enabled or not
         }//loop through geant4 hits
         //copy aggregated hits into output collection
         outputColl.clear();
         for ( auto &mapHit : hitMap ) {
             outputColl.push_back( mapHit.second );
         }
         return;
     }
References compressHitContribs_, enableHitContribs_, ldmx::G4CalorimeterHit::getEdep(), ldmx::G4CalorimeterHit::getID(), ldmx::G4CalorimeterHit::getPdgCode(), ldmx::G4CalorimeterHit::getTime(), ldmx::G4CalorimeterHit::getTrackID(), ldmx::UserTrackingAction::getTrackMap(), ldmx::UserTrackingAction::getUserTrackingAction(), and hexReadout_.
Referenced by ldmx::RootPersistencyManager::writeHitsCollections().
Member Data Documentation
compressHitContribs_
bool ldmx::EcalHitIO::compressHitContribs_ {true} private
Enable compression of hit contributions by SimParticle and PDG code.
Definition at line 113 of file EcalHitIO.h.
Referenced by configure(), setCompressHitContribs(), and writeHitsCollection().
enableHitContribs_
bool ldmx::EcalHitIO::enableHitContribs_ {true} private
Enable hit contribution output.
Definition at line 108 of file EcalHitIO.h.
Referenced by configure(), setEnableHitContribs(), and writeHitsCollection().
hexReadout_
std::unique_ptr<EcalHexReadout> ldmx::EcalHitIO::hexReadout_ private
Hex cell readout.
Inputs v12 geometry parameters
Definition at line 103 of file EcalHitIO.h.
Referenced by configure(), and writeHitsCollection().
The documentation for this class was generated from the following files:
SimCore/include/SimCore/EcalHitIO.h
SimCore/src/EcalHitIO.cxx