LDMX Software: eventdisplay::EveDetectorGeometry Class Reference
eventdisplay::EveDetectorGeometry Class Reference
Class that constructs the detector components for the event display.
#include <EveDetectorGeometry.h>
Public Member Functions
EveDetectorGeometry ()
~EveDetectorGeometry ()
void drawECAL ()
void drawHCAL ()
void drawRecoilTracker ()
TEveElement * getECAL ()
TEveElement * getHCAL ()
TEveElement * getRecoilTracker ()
TEveElement * getDetector ()
Private Attributes
TEveElement * hcal_
TEveElement * sidehcal_
TEveElement * ecal_
TEveElement * recoilTracker_
TEveElement * detector_
Detailed Description
Class that constructs the detector components for the event display.
Definition at line 22 of file EveDetectorGeometry.h.
Constructor & Destructor Documentation
EveDetectorGeometry()
eventdisplay::EveDetectorGeometry::EveDetectorGeometry ()
Constructor Builds and draws all of the detector elements.
Definition at line 12 of file EveDetectorGeometry.cxx.
{
  hcal_ = new TEveElementList("HCAL");
  sidehcal_ = new TEveElementList("Side HCAL");
  ecal_ = new TEveElementList("ECAL");
  recoilTracker_ = new TEveElementList("Recoil Tracker");
  detector_ = new TEveElementList("LDMX Detector");
  drawECAL();
  drawHCAL();
  drawRecoilTracker();
}
References drawECAL(), drawHCAL(), and drawRecoilTracker().
~EveDetectorGeometry()
eventdisplay::EveDetectorGeometry::~EveDetectorGeometry () inline
Destructor Cleanup leftover pointers.
Definition at line 34 of file EveDetectorGeometry.h.
{
    delete hcal_;
    delete sidehcal_;
    delete ecal_;
    delete recoilTracker_;
    delete detector_;
  }
Member Function Documentation
drawECAL()
void eventdisplay::EveDetectorGeometry::drawECAL ()
Draw the elements of the ECAL
Definition at line 24 of file EveDetectorGeometry.cxx.
{
  for (int col = 0; col < 7; ++col) {
    TString colName;
    colName.Form("Tower %d", col);
    TEveGeoShape* hexCol = EveShapeDrawer::getInstance().drawHexPrism(
        DetectorGeometry::getInstance().getHexTower(col), 0, 0, 0, kBlue, 90,
        colName);
    ecal_->AddElement(hexCol);
  }
  detector_->AddElement(ecal_);
}
References eventdisplay::EveShapeDrawer::drawHexPrism(), eventdisplay::DetectorGeometry::getInstance(), and eventdisplay::EveShapeDrawer::getInstance().
Referenced by EveDetectorGeometry().
drawHCAL()
void eventdisplay::EveDetectorGeometry::drawHCAL ()
Draw the elements of the HCAL
Definition at line 38 of file EveDetectorGeometry.cxx.
{
  TEveGeoShape* backHcal = EveShapeDrawer::getInstance().drawRectPrism(
      DetectorGeometry::getInstance().getBoundingBox(ldmx::HcalID::HcalSection::BACK),
      0, 0, 0, kCyan, 90, "Back HCal");
  hcal_->AddElement(backHcal);
  TEveGeoShape* sideTopHcal = EveShapeDrawer::getInstance().drawRectPrism(
      DetectorGeometry::getInstance().getBoundingBox(ldmx::HcalID::HcalSection::TOP),
      0, 0, 0, kCyan, 90, "Module 1");
  sidehcal_->AddElement(sideTopHcal);
  TEveGeoShape* sideBottomHcal = EveShapeDrawer::getInstance().drawRectPrism(
      DetectorGeometry::getInstance().getBoundingBox(
          ldmx::HcalID::HcalSection::BOTTOM),
      0, 0, 0, kCyan, 90, "Module 4");
  sidehcal_->AddElement(sideBottomHcal);
  TEveGeoShape* sideLeftHcal = EveShapeDrawer::getInstance().drawRectPrism(
      DetectorGeometry::getInstance().getBoundingBox(ldmx::HcalID::HcalSection::LEFT),
      0, 0, 0, kCyan, 90, "Module 2");
  sidehcal_->AddElement(sideLeftHcal);
  TEveGeoShape* sideRightHcal = EveShapeDrawer::getInstance().drawRectPrism(
      DetectorGeometry::getInstance().getBoundingBox(
          ldmx::HcalID::HcalSection::RIGHT),
      0, 0, 0, kCyan, 90, "Module 3");
  sidehcal_->AddElement(sideRightHcal);
  hcal_->AddElement(sidehcal_);
  detector_->AddElement(hcal_);
}
References eventdisplay::EveShapeDrawer::drawRectPrism(), eventdisplay::DetectorGeometry::getInstance(), and eventdisplay::EveShapeDrawer::getInstance().
Referenced by EveDetectorGeometry().
drawRecoilTracker()
void eventdisplay::EveDetectorGeometry::drawRecoilTracker ()
Draw the elements of the Recoil Tracker
Definition at line 74 of file EveDetectorGeometry.cxx.
{
  for (int layerID = 1; layerID < 9; layerID++) {
    TString name;
    name.Form("Stereo_%d", layerID);
    TEveGeoShape* layer = EveShapeDrawer::getInstance().drawRectPrism(
        DetectorGeometry::getInstance().getBoundingBox(layerID, 0), 0, 0,
        DetectorGeometry::getInstance().getRotAngle(layerID, 0) * 180 / M_PI,
        kRed - 10, 90, name);
    recoilTracker_->AddElement(layer);
  }
  for (int layerID = 9; layerID < 11; layerID++) {
    for (int moduleID = 0; moduleID < 10; moduleID++) {
      TString name;
      name.Form("Mono_%d_%d", layerID, moduleID);
      TEveGeoShape* layer = EveShapeDrawer::getInstance().drawRectPrism(
          DetectorGeometry::getInstance().getBoundingBox(layerID, moduleID), 0,
          0,
          DetectorGeometry::getInstance().getRotAngle(layerID, moduleID) * 180 /
              M_PI,
          kRed - 10, 90, name);
      recoilTracker_->AddElement(layer);
    }
  }
  detector_->AddElement(recoilTracker_);
  return;
}
References eventdisplay::EveShapeDrawer::drawRectPrism(), eventdisplay::DetectorGeometry::getInstance(), and eventdisplay::EveShapeDrawer::getInstance().
Referenced by EveDetectorGeometry().
getDetector()
TEveElement * eventdisplay::EveDetectorGeometry::getDetector () inline
Access Entire Detector Eve Element
Definition at line 75 of file EveDetectorGeometry.h.
{ return detector_; }
getECAL()
TEveElement * eventdisplay::EveDetectorGeometry::getECAL () inline
Access ECAL Eve Element
Definition at line 60 of file EveDetectorGeometry.h.
{ return ecal_; }
Referenced by eventdisplay::Display::Display().
getHCAL()
TEveElement * eventdisplay::EveDetectorGeometry::getHCAL () inline
Access HCAL Eve Element
Definition at line 65 of file EveDetectorGeometry.h.
{ return hcal_; }
Referenced by eventdisplay::Display::Display().
getRecoilTracker()
TEveElement * eventdisplay::EveDetectorGeometry::getRecoilTracker () inline
Access Recoil Tracker Eve Element
Definition at line 70 of file EveDetectorGeometry.h.
{ return recoilTracker_; }
Referenced by eventdisplay::Display::Display().
Member Data Documentation
detector_
TEveElement* eventdisplay::EveDetectorGeometry::detector_ private
Definition at line 82 of file EveDetectorGeometry.h.
ecal_
TEveElement* eventdisplay::EveDetectorGeometry::ecal_ private
Definition at line 80 of file EveDetectorGeometry.h.
hcal_
TEveElement* eventdisplay::EveDetectorGeometry::hcal_ private
Definition at line 78 of file EveDetectorGeometry.h.
recoilTracker_
TEveElement* eventdisplay::EveDetectorGeometry::recoilTracker_ private
Definition at line 81 of file EveDetectorGeometry.h.
sidehcal_
TEveElement* eventdisplay::EveDetectorGeometry::sidehcal_ private
Definition at line 79 of file EveDetectorGeometry.h.
The documentation for this class was generated from the following files:
EventDisplay/include/EventDisplay/EveDetectorGeometry.h
EventDisplay/src/EventDisplay/EveDetectorGeometry.cxx