LDMX Software: ldmx::PrimaryGeneratorManager Class Reference
ldmx::PrimaryGeneratorManager Class Reference
Class that manages the generators used to fire particles.
#include <PrimaryGeneratorManager.h>
Classes
struct GeneratorInfo
Holds necessary information to create a generator.
Public Member Functions
std::vector< PrimaryGenerator * > getGenerators () const
void registerGenerator (const std::string &className, PrimaryGeneratorBuilder *builder)
void createGenerator (const std::string &className, const std::string &instanceName, Parameters &parameters)
Static Public Member Functions
static PrimaryGeneratorManager & getInstance ()
Private Member Functions
PrimaryGeneratorManager ()
Constructor - private to prevent initialization.
Private Attributes
std::map< std::string, GeneratorInfo > generatorMap_
A map of all register generators.
std::vector< PrimaryGenerator * > generators_
Cointainer for all generators to be used by the simulation.
Static Private Attributes
static PrimaryGeneratorManager instance_
PrimaryGeneratorManager instance.
Detailed Description
Class that manages the generators used to fire particles.
Definition at line 22 of file PrimaryGeneratorManager.h.
Member Function Documentation
createGenerator()
void ldmx::PrimaryGeneratorManager::createGenerator (const std::string & className, const std::string & instanceName, Parameters & parameters)
Create a new generate and attach it to the list of generators
Definition at line 38 of file PrimaryGeneratorManager.cxx.
{
         auto it{generatorMap_.find(className)};
         if ( it == generatorMap_.end()) {
             EXCEPTION_RAISE( "CreateGenerator" , "Failed to create generator '" + className + "'." );
         }
         auto generator{it->second.builder_(instanceName, parameters)};
         //now that the generator is built --> put it on active list
         generators_.push_back( generator );
     }
References generatorMap_, and generators_.
getGenerators()
std::vector< PrimaryGenerator* > ldmx::PrimaryGeneratorManager::getGenerators () const inline
Get the collection of all enabled generators
Definition at line 32 of file PrimaryGeneratorManager.h.
 { return generators_; };
References generators_.
Referenced by ldmx::PrimaryGeneratorAction::GeneratePrimaries().
getInstance()
PrimaryGeneratorManager & ldmx::PrimaryGeneratorManager::getInstance () static
Returns
the global PrimaryGeneratorManager instance
Definition at line 27 of file PrimaryGeneratorManager.cxx.
 { return instance_; }
References instance_.
Referenced by ldmx::PrimaryGenerator::declare().
registerGenerator()
void ldmx::PrimaryGeneratorManager::registerGenerator (const std::string & className, PrimaryGeneratorBuilder * builder)
Attach a new generator to the list of generators
Definition at line 29 of file PrimaryGeneratorManager.cxx.
{
         GeneratorInfo info;
         info.className_ = className;
         info.builder_   = builder;
         generatorMap_[className] = info;
     }
References generatorMap_.
Referenced by ldmx::PrimaryGenerator::declare().
The documentation for this class was generated from the following files:
SimCore/include/SimCore/PrimaryGeneratorManager.h
SimCore/src/SimCore/PrimaryGeneratorManager.cxx