LDMX Software: ldmx::MyProcessor Class Reference
ldmx::MyProcessor Class Reference
#include <MyProcessor.h>
Public Member Functions
MyProcessor (const std::string &name, Process &process)
~MyProcessor ()
Destructor.
void configure (Parameters &parameters) final override
void produce (Event &event)
Public Member Functions inherited from ldmx::Producer
Producer (const std::string &name, Process &process)
Public Member Functions inherited from ldmx::EventProcessor
EventProcessor (const std::string &name, Process &process)
virtual ~EventProcessor ()
virtual void onNewRun (const RunHeader &runHeader)
virtual void onFileOpen (EventFile &eventFile)
virtual void onFileClose (EventFile &eventFile)
virtual void onProcessStart ()
virtual void onProcessEnd ()
TDirectory * getHistoDirectory ()
void setStorageHint (ldmx::StorageControlHint hint)
void setStorageHint (ldmx::StorageControlHint hint, const std::string &purposeString)
int getLogFrequency () const
int getRunNumber () const
void createHistograms (const std::vector< Parameters > &histos)
Additional Inherited Members
Static Public Member Functions inherited from ldmx::EventProcessor
static void declare (const std::string &classname, int classtype, EventProcessorMaker *)
Static Public Attributes inherited from ldmx::Producer
static const int CLASSTYPE {1}
Protected Member Functions inherited from ldmx::EventProcessor
void abortEvent ()
Protected Attributes inherited from ldmx::EventProcessor
HistogramHelper histograms_
Interface class for making and filling histograms.
NtupleManager & ntuple_ {NtupleManager::getInstance()}
Manager for any ntuples.
logging::logger theLog_
The logger for this EventProcessor.
Detailed Description
Minimal example of a processor.
This processor will loop over all of the ECal hits in an event and print out their details.
Definition at line 20 of file MyProcessor.h.
Constructor & Destructor Documentation
MyProcessor()
ldmx::MyProcessor::MyProcessor (const std::string & name, Process & process)
Constructor.
Parameters
name Name for this instance of the class.
process The Process class associated with EventProcessor, provided by the framework.
Definition at line 6 of file MyProcessor.cxx.
                                                                     :
         Producer(name, process) {
     }
Member Function Documentation
configure()
void ldmx::MyProcessor::configure (Parameters & parameters) final override virtual
Configure the processor using the given user specified parameters.
The user specified parameters that are availabed are defined in the python configuration class. Look at the my_processor.py module of the EventProc python for the python structure.
Parameters
parameters Set of parameters used to configure this processor.
You access configuration parameters set in the python by asking for the parameter with the same name as the python member variable.
Reimplemented from ldmx::EventProcessor.
Definition at line 13 of file MyProcessor.cxx.
{
         int my_parameter = parameters.getParameter<int>("my_parameter");
         std::cout << "MyProcessor has my_parameter = "
             << my_parameter << std::endl;
     }
References ldmx::Parameters::getParameter().
produce()
void ldmx::MyProcessor::produce (Event & event) virtual
Process the event and put new data products into it.
Parameters
event The event to process.
Implements ldmx::Producer.
Definition at line 27 of file MyProcessor.cxx.
{
         // Check if the collection of reconstructed ECal hits exist.  If not,
         // don't bother processing the event.
         if (!event.exists("EcalRecHits")) return;
         // Get the collection of digitized ECal hits from the event
         const std::vector<EcalHit> hits = event.getCollection<EcalHit>("EcalRecHits");
         // Loop over the collection of hits and print the hit details
         for (const EcalHit &hit : hits ) {
             // Print the hit
             hit.Print();
         }
     }
References ldmx::Event::exists(), and ldmx::EcalHit::Print().
The documentation for this class was generated from the following files:
EventProc/include/EventProc/MyProcessor.h
EventProc/src/MyProcessor.cxx