LDMX Software: ldmx::LHEPrimaryGenerator Class Reference
ldmx::LHEPrimaryGenerator Class Reference
Generates a Geant4 event from an LHEEvent.
#include <LHEPrimaryGenerator.h>
Public Member Functions
LHEPrimaryGenerator (const std::string &name, Parameters &parameters)
virtual ~LHEPrimaryGenerator ()
void GeneratePrimaryVertex (G4Event *anEvent)
Public Member Functions inherited from ldmx::PrimaryGenerator
PrimaryGenerator (const std::string &name, Parameters &parameters)
virtual ~PrimaryGenerator ()
Destructor.
Private Attributes
LHEReader * reader_
Additional Inherited Members
Static Public Member Functions inherited from ldmx::PrimaryGenerator
static void declare (const std::string &className, PrimaryGeneratorBuilder *builder)
Protected Attributes inherited from ldmx::PrimaryGenerator
std::string name_ {""}
Name of the PrimaryGenerator.
Parameters parameters_
The set of parameters used to configure this class.
Detailed Description
Generates a Geant4 event from an LHEEvent.
Definition at line 25 of file LHEPrimaryGenerator.h.
Constructor & Destructor Documentation
LHEPrimaryGenerator()
ldmx::LHEPrimaryGenerator::LHEPrimaryGenerator (const std::string & name, Parameters & parameters)
Class constructor.
Parameters
reader The LHE reader with the event data.
Definition at line 24 of file LHEPrimaryGenerator.cxx.
         : PrimaryGenerator( name , parameters ) {
         std::string filePath = parameters_.getParameter< std::string >( "filePath" );
         reader_ = new LHEReader( filePath );
     }
References ldmx::Parameters::getParameter(), ldmx::PrimaryGenerator::parameters_, and reader_.
~LHEPrimaryGenerator()
ldmx::LHEPrimaryGenerator::~LHEPrimaryGenerator () virtual
Class destructor.
Definition at line 32 of file LHEPrimaryGenerator.cxx.
{
         delete reader_;
     }
References reader_.
Member Function Documentation
GeneratePrimaryVertex()
void ldmx::LHEPrimaryGenerator::GeneratePrimaryVertex (G4Event * anEvent) virtual
Generate vertices in the Geant4 event.
Parameters
anEvent The Geant4 event.
Implements ldmx::PrimaryGenerator.
Definition at line 36 of file LHEPrimaryGenerator.cxx.
{
         LHEEvent* lheEvent = reader_->readNextEvent();
         if (lheEvent != NULL) {
             G4PrimaryVertex* vertex = new G4PrimaryVertex();
             vertex->SetPosition(lheEvent->getVertex()[0],lheEvent->getVertex()[1],lheEvent->getVertex()[2]);
             vertex->SetWeight(lheEvent->getXWGTUP());
             std::map<LHEParticle*, G4PrimaryParticle*> particleMap;
             int particleIndex = 0;
             const std::vector<LHEParticle*>& particles = lheEvent->getParticles();
             for (std::vector<LHEParticle*>::const_iterator it = particles.begin(); it != particles.end(); it++) {
                 LHEParticle* particle = (*it);
                 if (particle->getISTUP() > 0) {
                     G4PrimaryParticle* primary = new G4PrimaryParticle();
                     if (particle->getIDUP() == -623) { /* Tungsten ion */
                         G4ParticleDefinition* tungstenIonDef = G4IonTable::GetIonTable()->GetIon(74, 184, 0.);
                         if (tungstenIonDef != NULL) {
                             primary->SetParticleDefinition(tungstenIonDef);
                         } else {
                             EXCEPTION_RAISE( "EventGenerator" ,
                                     "Failed to find particle definition for W ion." );
                         }
                     } else {
                         primary->SetPDGcode(particle->getIDUP());
                     }
                     primary->Set4Momentum(particle->getPUP(0) * GeV,
                                           particle->getPUP(1) * GeV,
                                           particle->getPUP(2) * GeV,
                                           particle->getPUP(3) * GeV);
                     primary->SetProperTime(particle->getVTIMUP() * nanosecond);
                     UserPrimaryParticleInformation* primaryInfo = new UserPrimaryParticleInformation();
                     primaryInfo->setHepEvtStatus(particle->getISTUP());
                     primary->SetUserInformation(primaryInfo);
                     particleMap[particle] = primary;
                     /*
                      * Assign primary as daughter but only if the mother is not a DOC particle.
                      */
                     if (particle->getMother(0) != NULL && particle->getMother(0)->getISTUP() > 0) {
                         G4PrimaryParticle* primaryMom = particleMap[particle->getMother(0)];
                         if (primaryMom != NULL) {
                             primaryMom->SetDaughter(primary);
                         }
                     } else {
                         vertex->SetPrimary(primary);
                     }
                 }
                 ++particleIndex;
             }
             anEvent->AddPrimaryVertex(vertex);
         } else {
             std::cout << "[ LHEPrimaryGenerator ] : Ran out of input events so run will be aborted!" << std::endl;
             G4RunManager::GetRunManager()->AbortRun(true);
             anEvent->SetEventAborted();
         }
         delete lheEvent;
     }
References EXCEPTION_RAISE, ldmx::LHEParticle::getIDUP(), ldmx::LHEParticle::getISTUP(), ldmx::LHEParticle::getMother(), ldmx::LHEEvent::getParticles(), ldmx::LHEParticle::getPUP(), ldmx::LHEEvent::getVertex(), ldmx::LHEParticle::getVTIMUP(), ldmx::LHEEvent::getXWGTUP(), reader_, ldmx::LHEReader::readNextEvent(), and ldmx::UserPrimaryParticleInformation::setHepEvtStatus().
Member Data Documentation
reader_
LHEReader* ldmx::LHEPrimaryGenerator::reader_ private
The LHE reader with the event data.
Definition at line 51 of file LHEPrimaryGenerator.h.
Referenced by GeneratePrimaryVertex(), LHEPrimaryGenerator(), and ~LHEPrimaryGenerator().
The documentation for this class was generated from the following files:
SimCore/include/SimCore/LHEPrimaryGenerator.h
SimCore/src/LHEPrimaryGenerator.cxx