LDMX Software: trigscint::TestBeamHit Class Reference
trigscint::TestBeamHit Class Reference
This class represents the linearised QIE output from the trigger scintillator, in charge (fC).
#include <TestBeamHit.h>
Public Member Functions
TestBeamHit ()=default
~TestBeamHit ()=default
void Clear (Option_t *option="")
void Print (Option_t *option="") const
void setPedestal (const float pedestal)
float getEarlyPedestal () const
Get the pedestal calculated only from first N time samples.
void setEarlyPedestal (const float earlyPed)
float getPedestal () const
Get the pedestal.
void setQ (const float q)
float getQ () const
void setStartSample (const int startSample)
int getStartSample () const
Get the pulse/hit startSample.
void setSampAbovePed (const int sampAbovePed)
int getSampAbovePed () const
Get the pulse/hit sampAbovePed.
void setSampAboveThr (const int sampAboveThr)
int getSampAboveThr () const
Get the pulse/hit sampAboveThr.
void setHitQuality (const int isClean)
int getHitQuality () const
Get the pulse/hit isClean.
void setQualityFlag (const uint flag)
float getQualityFlag () const
Get the hit data quality flag.
void setPulseWidth (const int pulseWidth)
int getPulseWidth () const
Get the pulse/hit pulseWidth.
bool operator< (const TestBeamHit &rhs) const
Public Member Functions inherited from ldmx::TrigScintHit
TrigScintHit ()
~TrigScintHit ()
void Clear (Option_t *option="")
void Print (Option_t *option="") const
void setBarID (const int barID)
int getBarID () const
Get the bar ID.
void setPE (const float PE)
float getPE () const
Get the hit pe.
void setModuleID (const int moduleID)
int getModuleID () const
Get the module ID.
void setBeamEfrac (const float beamEfrac)
float getBeamEfrac () const
Get the beam energy fraction.
Public Member Functions inherited from ldmx::HcalHit
HcalHit ()
virtual ~HcalHit ()
void Clear ()
void Print () const
float getPE () const
float getMinPE () const
int getSection () const
int getLayer () const
int getStrip () const
int getEnd () const
int getIsADC () const
void setPE (float pe)
void setMinPE (float minpe)
void setSection (int section)
void setLayer (int layer)
void setStrip (int strip)
void setEnd (int end)
void setIsADC (int isADC)
Public Member Functions inherited from ldmx::CalorimeterHit
CalorimeterHit ()
virtual ~CalorimeterHit ()
void Clear ()
void Print () const
int getID () const
void setID (int id)
float getAmplitude () const
void setAmplitude (float amplitude)
float getEnergy () const
void setEnergy (float energy)
float getTime () const
void setTime (float time)
float getXPos () const
void setXPos (float xpos)
float getYPos () const
void setYPos (float ypos)
float getZPos () const
void setZPos (float zpos)
bool isNoise () const
void setNoise (bool yes)
bool operator< (const CalorimeterHit &rhs) const
Private Member Functions
ClassDef (TestBeamHit, 2)
Private Attributes
float pedestal_ {-999.}
float earlyPedestal_ {-999.}
float pulseQ_ {-999.}
int startSample_ {-1}
int pulseWidth_ {-1}
int sampAbovePed_ {-1}
int sampAboveThr_ {-1}
int passHitQuality_ {0}
uint flag_ {0}
Detailed Description
This class represents the linearised QIE output from the trigger scintillator, in charge (fC).
Definition at line 23 of file TestBeamHit.h.
Constructor & Destructor Documentation
TestBeamHit()
trigscint::TestBeamHit::TestBeamHit () default
Class constructor.
~TestBeamHit()
trigscint::TestBeamHit::~TestBeamHit () default
Class destructor.
Member Function Documentation
Clear()
void trigscint::TestBeamHit::Clear (Option_t * option = "")
Clear the data in the object.
getEarlyPedestal()
float trigscint::TestBeamHit::getEarlyPedestal () const inline
Get the pedestal calculated only from first N time samples.
Definition at line 54 of file TestBeamHit.h.
{ return earlyPedestal_; }
getHitQuality()
int trigscint::TestBeamHit::getHitQuality () const inline
Get the pulse/hit isClean.
Definition at line 130 of file TestBeamHit.h.
{ return passHitQuality_; }
getPedestal()
float trigscint::TestBeamHit::getPedestal () const inline
Get the pedestal.
Definition at line 65 of file TestBeamHit.h.
{ return pedestal_; }
getPulseWidth()
int trigscint::TestBeamHit::getPulseWidth () const inline
Get the pulse/hit pulseWidth.
Definition at line 155 of file TestBeamHit.h.
{ return pulseWidth_; }
getQ()
float trigscint::TestBeamHit::getQ () const inline
Get hit charge
Definition at line 76 of file TestBeamHit.h.
{ return pulseQ_; }
getQualityFlag()
float trigscint::TestBeamHit::getQualityFlag () const inline
Get the hit data quality flag.
Definition at line 145 of file TestBeamHit.h.
{ return flag_; }
getSampAbovePed()
int trigscint::TestBeamHit::getSampAbovePed () const inline
Get the pulse/hit sampAbovePed.
Definition at line 109 of file TestBeamHit.h.
{ return sampAbovePed_; }
getSampAboveThr()
int trigscint::TestBeamHit::getSampAboveThr () const inline
Get the pulse/hit sampAboveThr.
Definition at line 120 of file TestBeamHit.h.
{ return sampAboveThr_; }
getStartSample()
int trigscint::TestBeamHit::getStartSample () const inline
Get the pulse/hit startSample.
Definition at line 98 of file TestBeamHit.h.
{ return startSample_; }
operator<()
bool trigscint::TestBeamHit::operator< (const TestBeamHit & rhs) const inline
A dummy operator overloading
Note
required for declaring std::vector<> in EventDef.h
Definition at line 162 of file TestBeamHit.h.
{
    return this->pulseQ_ < rhs.pulseQ_;
  }
Print()
void trigscint::TestBeamHit::Print (Option_t * option = "") const
Print out the object.
setEarlyPedestal()
void trigscint::TestBeamHit::setEarlyPedestal (const float earlyPed) inline
Set channel (linearized. charge) pedestal calculated from beginning of readout
Parameters
pedestal The pedestal of the first N time samples in the channel
Definition at line 61 of file TestBeamHit.h.
{ earlyPedestal_ = earlyPed; };
Referenced by trigscint::TestBeamHitProducer::produce().
setHitQuality()
void trigscint::TestBeamHit::setHitQuality (const int isClean) inline
Set whether hit has been checked for and passed quality criteria
Parameters
isClean The boolean being TRUE if hit quality criteria are checkad AND passed
Definition at line 127 of file TestBeamHit.h.
{ passHitQuality_ = isClean; };
Referenced by trigscint::TestBeamHitProducer::produce().
setPedestal()
void trigscint::TestBeamHit::setPedestal (const float pedestal) inline
Set channel (linearized. charge) pedestal
Parameters
pedestal The pedestal of the channel
Definition at line 50 of file TestBeamHit.h.
{ pedestal_ = pedestal; };
Referenced by trigscint::TestBeamHitProducer::produce().
setPulseWidth()
void trigscint::TestBeamHit::setPulseWidth (const int pulseWidth) inline
Set width used to integrate pulse/hit (in time samples)
Parameters
pulseWidth The number of (time) samples used to make up the pulse
Definition at line 152 of file TestBeamHit.h.
{ pulseWidth_ = pulseWidth; };
Referenced by trigscint::TestBeamHitProducer::produce().
setQ()
void trigscint::TestBeamHit::setQ (const float q) inline
Store total charge
Parameters
q total charge in pulse making hit
Definition at line 71 of file TestBeamHit.h.
{ pulseQ_ = q; }
Referenced by trigscint::TestBeamHitProducer::produce().
setQualityFlag()
void trigscint::TestBeamHit::setQualityFlag (const uint flag) inline
Set hit data quality flag. This is the binary combination of 4 flags from the total channel readout: spike: 1 plateau: 10 long pulse: 100 (implemented as hit quantity) oscillation: 1000
Parameters
flag The quality flag of the hit
Definition at line 141 of file TestBeamHit.h.
{ this->flag_ = flag; };
Referenced by trigscint::TestBeamHitProducer::produce().
setSampAbovePed()
void trigscint::TestBeamHit::setSampAbovePed (const int sampAbovePed) inline
Set number of samples above pedestal in pulse/hit
Parameters
sampAbovePed The number of (time) samples above pedestal in (or continuing after) the pulse
Definition at line 106 of file TestBeamHit.h.
{ sampAbovePed_ = sampAbovePed; };
Referenced by trigscint::TestBeamHitProducer::produce().
setSampAboveThr()
void trigscint::TestBeamHit::setSampAboveThr (const int sampAboveThr) inline
Set number of samples above threshold in pulse/hit
Parameters
sampAboveThr The number of (time) samples above threshold in (or continuing after) the pulse
Definition at line 117 of file TestBeamHit.h.
{ sampAboveThr_ = sampAboveThr; };
Referenced by trigscint::TestBeamHitProducer::produce().
setStartSample()
void trigscint::TestBeamHit::setStartSample (const int startSample) inline
Store total charge
Parameters
pe total charge in pulse making hit Get hit charge Set pulse/hit start sample
startSample The start (time) sample in the pulse
Definition at line 94 of file TestBeamHit.h.
{ startSample_ = startSample; };
Referenced by trigscint::TestBeamHitProducer::produce().
Member Data Documentation
earlyPedestal_
float trigscint::TestBeamHit::earlyPedestal_ {-999.} private
Definition at line 168 of file TestBeamHit.h.
flag_
uint trigscint::TestBeamHit::flag_ {0} private
Definition at line 178 of file TestBeamHit.h.
passHitQuality_
int trigscint::TestBeamHit::passHitQuality_ {0} private
Definition at line 176 of file TestBeamHit.h.
pedestal_
float trigscint::TestBeamHit::pedestal_ {-999.} private
Definition at line 167 of file TestBeamHit.h.
pulseQ_
float trigscint::TestBeamHit::pulseQ_ {-999.} private
Definition at line 169 of file TestBeamHit.h.
pulseWidth_
int trigscint::TestBeamHit::pulseWidth_ {-1} private
Definition at line 172 of file TestBeamHit.h.
sampAbovePed_
int trigscint::TestBeamHit::sampAbovePed_ {-1} private
Definition at line 173 of file TestBeamHit.h.
sampAboveThr_
int trigscint::TestBeamHit::sampAboveThr_ {-1} private
Definition at line 174 of file TestBeamHit.h.
startSample_
int trigscint::TestBeamHit::startSample_ {-1} private
Definition at line 171 of file TestBeamHit.h.
The documentation for this class was generated from the following file:
TrigScint/include/TrigScint/Event/TestBeamHit.h