LDMX Software: simcore::persist::SimParticleBuilder Class Reference
simcore::persist::SimParticleBuilder Class Reference
Builds output SimParticle collection from Trajectory container.
#include <SimParticleBuilder.h>
Public Member Functions
SimParticleBuilder ()
virtual ~SimParticleBuilder ()
void setCurrentEvent (const G4Event *anEvent)
void buildSimParticles (framework::Event *outputEvent)
Private Attributes
TrackMap * trackMap_
G4Event * currentEvent_
Detailed Description
Builds output SimParticle collection from Trajectory container.
Definition at line 26 of file SimParticleBuilder.h.
Constructor & Destructor Documentation
SimParticleBuilder()
simcore::persist::SimParticleBuilder::SimParticleBuilder ()
Class constructor.
Definition at line 23 of file SimParticleBuilder.cxx.
 : currentEvent_(nullptr) {}
~SimParticleBuilder()
simcore::persist::SimParticleBuilder::~SimParticleBuilder () virtual
Class destructor.
Definition at line 25 of file SimParticleBuilder.cxx.
 {}
Member Function Documentation
buildSimParticles()
void simcore::persist::SimParticleBuilder::buildSimParticles (framework::Event * outputEvent)
Build SimParticle collection into an output event.
Parameters
outputEvent The output event.
Definition at line 27 of file SimParticleBuilder.cxx.
{
   // Get the trajectory container for the event.
   auto trajectories{
       (const_cast<G4Event *>(currentEvent_))->GetTrajectoryContainer()};
   if (!trajectories or !(trajectories->GetVector())) {
     EXCEPTION_RAISE("PersistFault",
                     "Event's trajectory container does not exist.");
   }
   const std::vector<G4VTrajectory *> &trajectory_list =
       *(trajectories->GetVector());
   // Create empty SimParticle objects and create the map of track ID to
   // particles.
   std::map<int, ldmx::SimParticle> outputParticleMap;
   for (G4VTrajectory *trajectory : trajectory_list) {
     if (!trajectory)
       EXCEPTION_RAISE("PersistFault",
                       "NULL G4VTrajectory ended up in storage.");
     outputParticleMap[trajectory->GetTrackID()];
   }
   // Fill information into the particles.
   for (G4VTrajectory *trajectory : trajectory_list) {
     Trajectory *traj = dynamic_cast<Trajectory *>(trajectory);
     if (!traj)
       EXCEPTION_RAISE("PersistFault", "NULL Trajectory ended up in storage.");
     ldmx::SimParticle *simParticle = &outputParticleMap[traj->GetTrackID()];
     simParticle->setGenStatus(traj->getGenStatus());
     simParticle->setPdgID(traj->GetPDGEncoding());
     simParticle->setCharge(traj->GetCharge());
     simParticle->setMass(traj->getMass());
     simParticle->setEnergy(traj->getEnergy());
     simParticle->setTime(traj->getGlobalTime());
     simParticle->setProcessType(traj->getProcessType());
     simParticle->setVertexVolume(traj->getVertexVolume());
     const G4ThreeVector &vertex = traj->getVertexPosition();
     simParticle->setVertex(vertex[0], vertex[1], vertex[2]);
     const G4ThreeVector &momentum = traj->GetInitialMomentum();
     simParticle->setMomentum(momentum[0], momentum[1], momentum[2]);
     const G4ThreeVector &endpMomentum = traj->getEndPointMomentum();
     simParticle->setEndPointMomentum(endpMomentum[0], endpMomentum[1],
                                      endpMomentum[2]);
     G4ThreeVector endpoint = traj->getEndPoint();
     simParticle->setEndPoint(endpoint[0], endpoint[1], endpoint[2]);
     if (traj->GetParentID() > 0) {
       simParticle->addParent(traj->GetParentID());
       // check if parent track is being stored
       auto parentParticle = outputParticleMap.find(traj->GetParentID());
       if (parentParticle != outputParticleMap.end()) {
         // this parent has been found in the particle map
         outputParticleMap[traj->GetParentID()].addDaughter(
             trajectory->GetTrackID());
       }  // check if parent exists in output map
     }    // check if particle has a parent
   }
   // Add the collection data to the output event.
   outputEvent->add("SimParticles", outputParticleMap);
 }
References framework::Event::add(), ldmx::SimParticle::addParent(), currentEvent_, simcore::Trajectory::GetCharge(), simcore::Trajectory::getEndPoint(), simcore::Trajectory::getEnergy(), simcore::Trajectory::getGenStatus(), simcore::Trajectory::getGlobalTime(), simcore::Trajectory::GetInitialMomentum(), simcore::Trajectory::getMass(), simcore::Trajectory::GetParentID(), simcore::Trajectory::GetPDGEncoding(), simcore::Trajectory::getProcessType(), simcore::Trajectory::GetTrackID(), simcore::Trajectory::getVertexPosition(), ldmx::SimParticle::setCharge(), ldmx::SimParticle::setEndPoint(), ldmx::SimParticle::setEndPointMomentum(), ldmx::SimParticle::setEnergy(), ldmx::SimParticle::setGenStatus(), ldmx::SimParticle::setMass(), ldmx::SimParticle::setMomentum(), ldmx::SimParticle::setPdgID(), ldmx::SimParticle::setProcessType(), ldmx::SimParticle::setTime(), ldmx::SimParticle::setVertex(), and ldmx::SimParticle::setVertexVolume().
Referenced by simcore::persist::RootPersistencyManager::buildEvent().
setCurrentEvent()
void simcore::persist::SimParticleBuilder::setCurrentEvent (const G4Event * anEvent) inline
Set the current Geant4 event.
Parameters
anEvent The Geant4 event.
Definition at line 42 of file SimParticleBuilder.h.
{
     this->currentEvent_ = const_cast<G4Event *>(anEvent);
   }
References currentEvent_.
Referenced by simcore::persist::RootPersistencyManager::buildEvent().
Member Data Documentation
currentEvent_
G4Event* simcore::persist::SimParticleBuilder::currentEvent_ private
The current Geant4 event.
Definition at line 57 of file SimParticleBuilder.h.
Referenced by buildSimParticles(), and setCurrentEvent().
trackMap_
TrackMap* simcore::persist::SimParticleBuilder::trackMap_ private
The map of tracks to their parent IDs and Trajectory objects.
Definition at line 54 of file SimParticleBuilder.h.
The documentation for this class was generated from the following files:
SimCore/include/SimCore/Persist/SimParticleBuilder.h
SimCore/src/SimCore/Persist/SimParticleBuilder.cxx