LDMX Software: framework::ConditionsObject Class Reference
framework::ConditionsObject Class Reference
Base class for all conditions objects, very simple.
#include <ConditionsObject.h>
Public Member Functions
ConditionsObject (const std::string &name)
virtual ~ConditionsObject ()
std::string getName () const
Private Attributes
std::string name_
Detailed Description
Base class for all conditions objects, very simple.
Definition at line 18 of file ConditionsObject.h.
Constructor & Destructor Documentation
ConditionsObject()
framework::ConditionsObject::ConditionsObject (const std::string & name) inline
Class constructor
Definition at line 23 of file ConditionsObject.h.
: name_(name) {}
~ConditionsObject()
virtual framework::ConditionsObject::~ConditionsObject () inline virtual
Destructor
Definition at line 28 of file ConditionsObject.h.
{}
Member Function Documentation
getName()
std::string framework::ConditionsObject::getName () const inline
Get the name of this object
Definition at line 33 of file ConditionsObject.h.
{ return name_; }
References name_.
Referenced by conditions::HomogenousTableCondition< T >::add(), ecal::EcalReconConditions::EcalReconConditions(), conditions::BaseTableCondition::getColumnName(), hcal::HcalReconConditions::HcalReconConditions(), and ldmx::HgcrocTriggerConditions::HgcrocTriggerConditions().
Member Data Documentation
name_
std::string framework::ConditionsObject::name_ private
Name of the object
Definition at line 39 of file ConditionsObject.h.
Referenced by getName().
The documentation for this class was generated from the following file:
Framework/include/Framework/ConditionsObject.h