LDMX Software: ldmx::DarkBremFilter Class Reference
ldmx::DarkBremFilter Class Reference
Public Member Functions
DarkBremFilter (const std::string &name, Parameters &parameters)
~DarkBremFilter ()
std::vector< TYPE > getTypes () final override
void stepping (const G4Step *step)
G4ClassificationOfNewTrack ClassifyNewTrack (const G4Track *aTrack, const G4ClassificationOfNewTrack &currentTrackClass) final override
Public Member Functions inherited from ldmx::UserAction
UserAction (const std::string &name, Parameters &parameters)
virtual ~UserAction ()
Destructor.
virtual void BeginOfEventAction (const G4Event *)
virtual void EndOfEventAction (const G4Event *)
virtual void BeginOfRunAction (const G4Run *)
virtual void EndOfRunAction (const G4Run *)
virtual void PreUserTrackingAction (const G4Track *)
virtual void PostUserTrackingAction (const G4Track *)
virtual void NewStage ()
virtual void PrepareNewEvent ()
Private Member Functions
bool hasAPrime (const G4TrackVector *secondaries) const
Private Attributes
int verbosity_
std::string volumeName_
Additional Inherited Members
Static Public Member Functions inherited from ldmx::UserAction
static void declare (const std::string &className, UserActionBuilder *builder)
Protected Attributes inherited from ldmx::UserAction
std::string name_ {""}
Name of the UserAction.
Parameters parameters_
The set of parameters used to configure this class.
Detailed Description
Definition at line 35 of file DarkBremFilter.h.
Constructor & Destructor Documentation
DarkBremFilter()
DarkBremFilter::DarkBremFilter (const std::string & name, Parameters & parameters)
Class constructor.
Links this filter to its messenger.
Definition at line 16 of file DarkBremFilter.cxx.
         : UserAction(name, parameters) {
         volumeName_ = parameters.getParameter< std::string >("volume");
         verbosity_  = parameters.getParameter< int         >("verbosity");
         //re-set verbosity and volumes to reasonable defaults
         if ( verbosity_ < 0 ) verbosity_ = 0;
         if ( volumeName_.empty() ) volumeName_ = "target_PV";
     }
References ldmx::Parameters::getParameter(), verbosity_, and volumeName_.
~DarkBremFilter()
DarkBremFilter::~DarkBremFilter ()
Class destructor.
Definition at line 26 of file DarkBremFilter.cxx.
{
     }
Member Function Documentation
ClassifyNewTrack()
G4ClassificationOfNewTrack DarkBremFilter::ClassifyNewTrack (const G4Track * aTrack, const G4ClassificationOfNewTrack & currentTrackClass) final override virtual
Classify a new track which postpones track processing. Track processing resumes normally if an interaction occurred.
Parameters
aTrack The Geant4 track.
currentTrackClass The current track classification.
Reimplemented from ldmx::UserAction.
Definition at line 29 of file DarkBremFilter.cxx.
{
         // get the PDGID of the track.
         G4int pdgID = track->GetParticleDefinition()->GetPDGEncoding();
         // Get the particle type.
         G4String particleName = track->GetParticleDefinition()->GetParticleName();
         // Use current classification by default so values from other plugins are not overridden.
         G4ClassificationOfNewTrack classification = currentTrackClass;
         if (track->GetTrackID() == 1 && pdgID == 11) {
             if ( verbosity_ > 2 ) {
                 std::cout << "[ DarkBremFilter ]: Pushing track to waiting stack." << std::endl;
             }
             return fWaiting;
         }
         return classification;
     }
References verbosity_.
getTypes()
std::vector< TYPE > ldmx::DarkBremFilter::getTypes () inline final override virtual
Get the types of actions this class can do
Implements ldmx::UserAction.
Definition at line 54 of file DarkBremFilter.h.
{
                 return { TYPE::STACKING , TYPE::STEPPING };
             }
hasAPrime()
bool DarkBremFilter::hasAPrime (const G4TrackVector * secondaries) const private
Checks if the secondaries given has an A Prime.
Parameters
secondaries list to search
Returns
true if A Prime in secondaries
Definition at line 125 of file DarkBremFilter.cxx.
{
         for (auto& secondary_track : *secondaries) {
             if (secondary_track->GetParticleDefinition() == G4APrime::APrime()) return true;
         }
         return false;
     }
References G4APrime::APrime().
Referenced by stepping().
stepping()
void DarkBremFilter::stepping (const G4Step * step) virtual
Kills events that don't contain a DarkBrem produced by the primary electron within the desired volume.
Parameters
step The Geant4 step.
Reimplemented from ldmx::UserAction.
Definition at line 52 of file DarkBremFilter.cxx.
{
         // Get the track associated with this step.
         G4Track* track = step->GetTrack();
         // Only process the primary electron track
         if (track->GetParentID() != 0) return;
         // get the PDGID of the track.
         G4int pdgID = track->GetParticleDefinition()->GetPDGEncoding();
         // Make sure that the particle being processed is an electron.
         if (pdgID != 11) return;
         // Get the volume the particle is in.
         G4VPhysicalVolume* volume = track->GetVolume();
         G4String volumeName = volume->GetName();
         // If the particle isn't in the given volume, don't continue with the processing.
         if (not volumeName.contains(volumeName_.c_str())) return;
         // Get the particle type.
         G4String particleName = track->GetParticleDefinition()->GetParticleName();
         if (step->GetPostStepPoint()->GetStepStatus() == fGeomBoundary) {
             // primary electron is exiting the volume.
             // Get the particles daughters.
             const G4TrackVector* secondaries = step->GetSecondary();
             if (secondaries->size() == 0) {
                 // If the particle didn't produce any secondaries, stop processing the event.
                 if ( verbosity_ > 1 ) {
                     std::cout << "[ DarkBremFilter ]: "
                                 << "Primary did not produce secondaries --> Killing primary track!"
                                 << std::endl;
                 }
                 track->SetTrackStatus(fKillTrackAndSecondaries);
                 G4RunManager::GetRunManager()->AbortEvent();
                 return;
             } else if (not hasAPrime(secondaries)) {
                 // If the particle din't produce an A Prime, stop processing the event
                 if ( verbosity_ > 1 ) {
                     std::cout << "[ DarkBremFilter ]: "
                                 << "No dark brem in " << volumeName_ << " --> Aborting event."
                                 << std::endl;
                 }
                 track->SetTrackStatus(fKillTrackAndSecondaries);
                 G4RunManager::GetRunManager()->AbortEvent();
                 return;
             }
         } else if (step->GetPostStepPoint()->GetKineticEnergy() == 0) {
             //primary electron stopped inside of volume
             const G4TrackVector* secondaries = step->GetSecondary();
             if(not hasAPrime( secondaries )){
                 // If the particle din't produce an A Prime, stop processing the event
                 if ( verbosity_ > 1 ) {
                     std::cout << "[ DarkBremFilter ]: "
                               << "Electron never made it out of the " << volumeName_ << " --> Killing all tracks!"
                               << std::endl;
                 }
                 track->SetTrackStatus(fKillTrackAndSecondaries);
                 G4RunManager::GetRunManager()->AbortEvent();
                 return;
             }
         } //check if particle is leaving volume or stopped within it
     }//stepping
References hasAPrime(), verbosity_, and volumeName_.
Member Data Documentation
verbosity_
int ldmx::DarkBremFilter::verbosity_ private
Level of verbosity for this filter
Parameter Name: 'verbosity'
Definition at line 91 of file DarkBremFilter.h.
Referenced by ClassifyNewTrack(), DarkBremFilter(), and stepping().
volumeName_
std::string ldmx::DarkBremFilter::volumeName_ private
The volume that the filter will be applied to.
Parameter Name: 'volume'
Definition at line 98 of file DarkBremFilter.h.
Referenced by DarkBremFilter(), and stepping().
The documentation for this class was generated from the following files:
Biasing/include/Biasing/DarkBremFilter.h
Biasing/src/DarkBremFilter.cxx