LDMX Software: ldmx::HgcrocEmulator::CompositePulse Class Reference
ldmx::HgcrocEmulator::CompositePulse Class Reference
Public Member Functions
CompositePulse (TF1 &func, const double &g, const double &p)
void addOrMerge (const std::pair< double, double > &hit, double hit_merge_ns)
double findCrossing (double low, double high, double level, double prec=0.01)
void setGainPedestal (double gain, double pedestal)
Configure the pulses for the current chip.
double operator() (double time) const
double at (double time) const
const std::vector< std::pair< double, double > > & hits () const
Get list of individual pulses that are entering the chip.
Private Attributes
std::vector< std::pair< double, double > > hits_
double gain_
gain for current chip we are emulating
double pedestal_
pedestal for current chip we are emulating
TF1 & pulseFunc_
reference to pulse shape function shared by all pulses
Detailed Description
CompositePulse
An emulator for a pulse that the chip needs to read. This handles merging two hits that are "close-enough" to one another.
Definition at line 240 of file HgcrocEmulator.h.
Constructor & Destructor Documentation
CompositePulse()
ldmx::HgcrocEmulator::CompositePulse::CompositePulse (TF1 & func, const double & g, const double & p) inline
Constructore
Connect this pulse emulator with the pulse shape function already configured by the chip emulator.
Definition at line 249 of file HgcrocEmulator.h.
       : pulseFunc_{func}, gain_{g}, pedestal_{p} { }
Member Function Documentation
addOrMerge()
void ldmx::HgcrocEmulator::CompositePulse::addOrMerge (const std::pair< double, double > & hit, double hit_merge_ns) inline
Put another hit into this composite pulse.
If the hit is within the merge input of a hit already included, then it is merged with that hit. Otherwise, it is included as its own hit.
Parameters
[in] hit voltage,time pair representing a sime hit
[in] hit_merge_ns maximum time separation [ns] to merge two hits
Definition at line 262 of file HgcrocEmulator.h.
{
       auto imerge{hits_.begin()};
       for (; imerge!=hits_.end(); imerge++)
         if (fabs(imerge->second-hit.second)<hit_merge_ns) break;
       if (imerge == hits_.end()) { // didn't find a match, add to the list
         hits_.push_back(hit);
       } else { // merge hits, shifting time to average
         imerge->second=(imerge->second*imerge->first+hit.first*hit.second);
         imerge->first+=hit.first;
         imerge->second/=imerge->first;
       }
     }
References hits_.
Referenced by ldmx::HgcrocEmulator::digitize().
at()
double ldmx::HgcrocEmulator::CompositePulse::at (double time) const inline
Measure the voltage at the input time
Includes the effects from all pulses but does not put any noise into the measurement.
Parameters
[in] time time to measure [ns]
Returns
voltage at that time [mV]
Definition at line 329 of file HgcrocEmulator.h.
{
       double signal = gain_ * pedestal_;
       for (auto hit : hits_)
         signal += hit.first * pulseFunc_.Eval(time-hit.second);
       return signal;
     };
References gain_, hits_, pedestal_, and pulseFunc_.
Referenced by findCrossing(), and operator()().
findCrossing()
double ldmx::HgcrocEmulator::CompositePulse::findCrossing (double low, double high, double level, double prec = 0.01) inline
Find the time at which we cross the input level.
We use the midpoint algorithm, assuming the input low is below the threshold and hight is above.
Parameters
[in] low minimum value (below threshold) to start search at [mV]
[in] high maximum value (above threshold) to start search at [mV]
[in] level threshold to look for time [mV]
[in] prec precision with which to look [mV]
Returns
time [ns] at which the pulse cross level
Definition at line 287 of file HgcrocEmulator.h.
{
       // use midpoint algorithm, assumes low is below and high is above
       double step=high-low;
       double pt=(high+low)/2;
       while (step>prec) {
         double vmid=at(pt);
         if (vmid<level) {
           low=pt;
         } else {
           high=pt;
         }
         step=high-low;
         pt=(high+low)/2;
       }
       return pt;
     }
References at().
Referenced by ldmx::HgcrocEmulator::digitize().
operator()()
double ldmx::HgcrocEmulator::CompositePulse::operator() (double time) const inline
Evaluating this object as a function gives the same result as at.
See also
at
Definition at line 316 of file HgcrocEmulator.h.
{
       return at(time);
     }
References at().
Member Data Documentation
hits_
std::vector<std::pair<double,double> > ldmx::HgcrocEmulator::CompositePulse::hits_ private
pulses entering the chip
The pair is {voltage amplitude [mV], time of peak [ns]}
Definition at line 345 of file HgcrocEmulator.h.
Referenced by addOrMerge(), at(), and hits().
The documentation for this class was generated from the following file:
Tools/include/Tools/HgcrocEmulator.h