LDMX Software: ldmx::PluginFactory Class Reference
ldmx::PluginFactory Class Reference
Singleton module factory that creates EventProcessor objects.
#include <PluginFactory.h>
Classes
struct PluginInfo
info container to hold classname, class type and maker.
Public Member Functions
void registerEventProcessor (const std::string &classname, int classtype, EventProcessorMaker *maker)
void registerConditionsObjectProvider (const std::string &classname, int classtype, ConditionsObjectProviderMaker *maker)
std::vector< std::string > getEventProcessorClasses () const
int getEventProcessorClasstype (const std::string &) const
EventProcessor * createEventProcessor (const std::string &classname, const std::string &moduleInstanceName, Process &process)
ConditionsObjectProvider * createConditionsObjectProvider (const std::string &classname, const std::string &moduleInstanceName, const std::string &tagname, const Parameters &params, Process &process)
void loadLibrary (const std::string &libname)
Static Public Member Functions
static PluginFactory & getInstance ()
Private Member Functions
PluginFactory ()
Private Attributes
std::map< std::string, PluginInfo > moduleInfo_
std::set< std::string > librariesLoaded_
Static Private Attributes
static PluginFactory theFactory_
Detailed Description
Singleton module factory that creates EventProcessor objects.
Definition at line 25 of file PluginFactory.h.
Constructor & Destructor Documentation
PluginFactory()
ldmx::PluginFactory::PluginFactory () private
Constructor
Definition at line 9 of file PluginFactory.cxx.
{
     }
Member Function Documentation
createConditionsObjectProvider()
ConditionsObjectProvider * ldmx::PluginFactory::createConditionsObjectProvider (const std::string & classname, const std::string & moduleInstanceName, const std::string & tagname, const Parameters & params, Process & process)
Make a conditions object provider
Parameters
classname Class name of conditions object provider
moduleInstanceName
params Parameters for the conditoons object provider
process The process handle
Definition at line 65 of file PluginFactory.cxx.
{
         auto ptr = moduleInfo_.find(classname);
         if (ptr == moduleInfo_.end() || ptr->second.cop_maker==0) {
             return 0;
         }
         return ptr->second.cop_maker(moduleInstanceName, tagname, params, process);
     }
References moduleInfo_.
Referenced by ldmx::Conditions::createConditionsObjectProvider().
createEventProcessor()
EventProcessor * ldmx::PluginFactory::createEventProcessor (const std::string & classname, const std::string & moduleInstanceName, Process & process)
Make an event processor.
Parameters
classname Class name of event processor.
moduleInstanceName TODO.
process The process handle
Definition at line 57 of file PluginFactory.cxx.
{
         auto ptr = moduleInfo_.find(classname);
         if (ptr == moduleInfo_.end() || ptr->second.ep_maker==0) {
             return 0;
         }
         return ptr->second.ep_maker(moduleInstanceName, process);
     }
References moduleInfo_.
getEventProcessorClasses()
std::vector< std::string > ldmx::PluginFactory::getEventProcessorClasses () const
Get the classes associated with the processor.
Returns
a vector of strings corresponding to processor classes.
Definition at line 38 of file PluginFactory.cxx.
{
         std::vector<std::string> classes;
         for (auto ptr : moduleInfo_) {
         if (ptr.second.ep_maker!=0)
         classes.push_back(ptr.first);
         }
         return classes;
     }
References moduleInfo_.
getEventProcessorClasstype()
int ldmx::PluginFactory::getEventProcessorClasstype (const std::string & ct) const
Get the class type for the event processor.
Parameters
TODO.
Definition at line 47 of file PluginFactory.cxx.
{
         auto ptr = moduleInfo_.find(ct);
         if (ptr == moduleInfo_.end() || ptr->second.ep_maker==0) {
             return 0;
         } else {
             return ptr->second.classtype;
         }
     }
References moduleInfo_.
getInstance()
static PluginFactory& ldmx::PluginFactory::getInstance () inline static
Get the factory instance.
Returns
The factory.
Definition at line 33 of file PluginFactory.h.
{
                 return theFactory_;
             }
References theFactory_.
Referenced by ldmx::Conditions::createConditionsObjectProvider(), ldmx::ConditionsObjectProvider::declare(), and ldmx::EventProcessor::declare().
loadLibrary()
void ldmx::PluginFactory::loadLibrary (const std::string & libname)
Load a library.
Parameters
libname The library to load.
Definition at line 73 of file PluginFactory.cxx.
{
         if (librariesLoaded_.find(libname) != librariesLoaded_.end()) {
             return; // already loaded
         }
         void* handle = dlopen(libname.c_str(), RTLD_NOW);
         if (handle == nullptr) {
             EXCEPTION_RAISE("LibraryLoadFailure", "Error loading library '" + libname + "':" + dlerror());
         }
         librariesLoaded_.insert(libname);
     }
References librariesLoaded_.
registerConditionsObjectProvider()
void ldmx::PluginFactory::registerConditionsObjectProvider (const std::string & classname, int classtype, ConditionsObjectProviderMaker * maker)
Register a conditions object provider
Parameters
classname The name of the class associated with the conditions object provider.
classtype The type of class associated with conditions object provider.
maker TODO.
Definition at line 25 of file PluginFactory.cxx.
{
         auto ptr = moduleInfo_.find(classname);
         if (ptr != moduleInfo_.end()) {
             EXCEPTION_RAISE("ExistingEventProcessorDefinition", "Already have a module registered with the classname '" + classname + "'");
         }
         PluginInfo mi;
         mi.classname = classname;
         mi.classtype = classtype;
         mi.cop_maker = maker;
         mi.ep_maker = 0;
         moduleInfo_[classname] = mi;
     }
References moduleInfo_.
Referenced by ldmx::ConditionsObjectProvider::declare().
registerEventProcessor()
void ldmx::PluginFactory::registerEventProcessor (const std::string & classname, int classtype, EventProcessorMaker * maker)
Register the event processor.
Parameters
classname The name of the class associated with processor.
classtype The type of class associated with processor.
maker TODO.
Definition at line 12 of file PluginFactory.cxx.
{
         auto ptr = moduleInfo_.find(classname);
         if (ptr != moduleInfo_.end()) {
             EXCEPTION_RAISE("ExistingEventProcessorDefinition", "Already have a module registered with the classname '" + classname + "'");
         }
         PluginInfo mi;
         mi.classname = classname;
         mi.classtype = classtype;
         mi.ep_maker = maker;
         mi.cop_maker = 0;
         moduleInfo_[classname] = mi;
     }
References moduleInfo_.
Referenced by ldmx::EventProcessor::declare().
Member Data Documentation
librariesLoaded_
std::set<std::string> ldmx::PluginFactory::librariesLoaded_ private
A set of names of loaded libraries.
Definition at line 110 of file PluginFactory.h.
Referenced by loadLibrary().
moduleInfo_
std::map<std::string, PluginInfo> ldmx::PluginFactory::moduleInfo_ private
A map of names to processor containers.
Definition at line 107 of file PluginFactory.h.
Referenced by createConditionsObjectProvider(), createEventProcessor(), getEventProcessorClasses(), getEventProcessorClasstype(), registerConditionsObjectProvider(), and registerEventProcessor().
theFactory_
PluginFactory ldmx::PluginFactory::theFactory_ static private
Factory for creating the plugin objects.
Definition at line 113 of file PluginFactory.h.
Referenced by getInstance().
The documentation for this class was generated from the following files:
Framework/include/Framework/PluginFactory.h
Framework/src/PluginFactory.cxx