LDMX Software: ldmx::RootPersistencyManager Class Reference
ldmx::RootPersistencyManager Class Reference
#include <RootPersistencyManager.h>
Public Member Functions
RootPersistencyManager (EventFile &file, Parameters &parameters)
virtual ~RootPersistencyManager ()
Destructor.
G4bool Store (const G4Event *anEvent)
G4bool Store (const G4Run *aRun)
G4bool Store (const G4VPhysicalVolume *)
void Initialize ()
void setCurrentEvent (Event *event)
void setNumEvents (int began, int completed)
void buildEvent (const G4Event *anEvent)
void writeHeader (const G4Event *anEvent)
std::string getEventSeeds (std::string fileName="currentEvent.rndm")
void writeHitsCollections (const G4Event *anEvent, Event *outputEvent)
void writeTrackerHitsCollection (G4TrackerHitsCollection *hc, std::vector< SimTrackerHit > &outputColl)
void writeCalorimeterHitsCollection (G4CalorimeterHitsCollection *hc, std::vector< SimCalorimeterHit > &outputColl)
Static Public Member Functions
static RootPersistencyManager * getInstance ()
Private Attributes
Parameters parameters_
Configuration parameters passed to Simulator.
int eventsBegan_ {-1}
Number of events started on this production run.
int eventsCompleted_ {-1}
Number of events completed without being aborted (due to filters)
EventFile & file_
The output file.
Event * event_ {nullptr}
The event container used to manage the tree/branches/collections.
EcalHitIO ecalHitIO_
Handles ECal hit readout and IO.
SimParticleBuilder simParticleBuilder_
Helper for building output SimParticle collection.
Detailed Description
Note
Output is written at the end of each event. An EventFile is used to write from an Event buffer object into an output branch within a tree. The event buffer is cleared after the event is written. A SimParticleBuilder is used to build a set of SimParticle objects from the Trajectory objects which were created during event processing. An EcalHitIO instance provides translation of G4CalorimeterHit objects in the ECal to an output SimCalorimeterHit collection, transforming the individual steps into cell energy depositions. The tracker hit collections of G4TrackerHit objects are translated directly into output SimTrackerHit collections.
Definition at line 56 of file RootPersistencyManager.h.
Constructor & Destructor Documentation
RootPersistencyManager()
ldmx::RootPersistencyManager::RootPersistencyManager (EventFile & file, Parameters & parameters)
Class constructor.
Parameters
eventFile
Definition at line 35 of file RootPersistencyManager.cxx.
                                                                                           :
         G4PersistencyManager(G4PersistencyCenter::GetPersistencyCenter(), "RootPersistencyManager"),
         file_(file) {
         // Let Geant4 know what to use this persistency manager
         G4PersistencyCenter::GetPersistencyCenter()->RegisterPersistencyManager(this);
         G4PersistencyCenter::GetPersistencyCenter()->SetPersistencyManager(this, "RootPersistencyManager");
         // Set the parameters, used laster when printing run header
         parameters_ = parameters;
         ecalHitIO_.setEnableHitContribs(parameters.getParameter< bool >("enableHitContribs"));
         ecalHitIO_.setCompressHitContribs(parameters.getParameter< bool >("compressHitContribs"));
     }
References ecalHitIO_, ldmx::Parameters::getParameter(), parameters_, ldmx::EcalHitIO::setCompressHitContribs(), and ldmx::EcalHitIO::setEnableHitContribs().
Member Function Documentation
buildEvent()
void ldmx::RootPersistencyManager::buildEvent (const G4Event * anEvent)
Build an output event from the current Geant4 event.
Parameters
anEvent The Geant4 event.
outputEvent The output event.
Definition at line 111 of file RootPersistencyManager.cxx.
{
         // Set basic event information.
         writeHeader(anEvent);
         // Set pointer to current G4Event.
         simParticleBuilder_.setCurrentEvent(anEvent);
         // Build the SimParticle list for the output ROOT event.
         simParticleBuilder_.buildSimParticles(event_);
         // Copy hit objects from SD hit collections into the output event.
         writeHitsCollections(anEvent, event_);
     }
References ldmx::SimParticleBuilder::buildSimParticles(), event_, ldmx::SimParticleBuilder::setCurrentEvent(), simParticleBuilder_, writeHeader(), and writeHitsCollections().
Referenced by Store().
getEventSeeds()
std::string ldmx::RootPersistencyManager::getEventSeeds (std::string fileName = "currentEvent.rndm")
Write header info into the output event from Geant4.
Parameters
fileName The filename that stores temporary seeds.
Definition at line 149 of file RootPersistencyManager.cxx.
{
         std::ifstream t(fileName);
         std::stringstream buffer;
         buffer << t.rdbuf();
         t.close();
         return buffer.str();
     }
getInstance()
static RootPersistencyManager* ldmx::RootPersistencyManager::getInstance () inline static
Get the current ROOT persistency manager or nullptr if not registered.
Returns
The ROOT persistency manager.
Definition at line 76 of file RootPersistencyManager.h.
{
                 return static_cast<RootPersistencyManager*>(
                         G4PersistencyCenter::GetPersistencyCenter()->CurrentPersistencyManager());
             }
Initialize()
void ldmx::RootPersistencyManager::Initialize ()
This is called "manually" in UserRunAction to open the ROOT writer for the run.
Definition at line 108 of file RootPersistencyManager.cxx.
{
     }
setCurrentEvent()
void ldmx::RootPersistencyManager::setCurrentEvent (Event * event) inline
Set the current ldmx-sw event. This is used by the persistency manager to retrieve and fill the containers that will be persisted.
Parameters
event Event buffer for the current event.
Definition at line 114 of file RootPersistencyManager.h.
 { event_ = event; }
References event_.
setNumEvents()
void ldmx::RootPersistencyManager::setNumEvents (int began, int completed) inline
Set the number of events began and completed.
These two numbers may or may not be equal depending on if the simulation ran with any filters that would abort events early.
These numbers are helpful for evaluating filtering performance, so we put them both in the RunHeader.
Parameters
[in] began number of events that were started
[in] completed number of events that were completed without an abort signal
Definition at line 128 of file RootPersistencyManager.h.
{
                 eventsBegan_ = began;
                 eventsCompleted_ = completed;
             }
References eventsBegan_, and eventsCompleted_.
Store() [1/3]
G4bool ldmx::RootPersistencyManager::Store (const G4Event * anEvent)
Builds the output ROOT event.
Parameters
anEvent The Geant4 event data.
Definition at line 51 of file RootPersistencyManager.cxx.
{
         // Check if the event has been aborted.  If so, skip storage of the
         // event.
         if (G4RunManager::GetRunManager()->GetCurrentEvent()->IsAborted()) return false;
         // Build the output collections.
         buildEvent(anEvent);
         return true;
     }
References buildEvent().
Store() [2/3]
G4bool ldmx::RootPersistencyManager::Store (const G4Run * aRun)
This gets called automatically at the end of the run and is used to write out the run header and close the writer.
Parameters
aRun The Geant4 run data.
Returns
True if event is stored (function is hard-coded to return true).
Definition at line 63 of file RootPersistencyManager.cxx.
{
         // NOTE: This method is called once the run is terminated through
         // the run manager.
         // Get the detector header from the user detector construction
         auto detector
             = static_cast<RunManager*>(RunManager::GetRunManager())->getDetectorConstruction();
         // Create the run header.
         RunHeader runHeader(
                 parameters_.getParameter<int>("runNumber"),
                 detector->getDetectorHeader()->getName(),
                 parameters_.getParameter<std::string>("description")
                 );
         // Set parameter value with number of events processed.
         runHeader.setIntParameter("Event Count", eventsCompleted_ );
         runHeader.setIntParameter("Events Began" , eventsBegan_ );
         runHeader.setIntParameter("Save ECal Hit Contribs" , parameters_.getParameter<bool>("enableHitContribs"));
         runHeader.setIntParameter("Compress ECal Hit Contribs" , parameters_.getParameter<bool>("compressHitContribs"));
         if ( parameters_.getParameter<bool>("biasing_enabled") ) {
             runHeader.setStringParameter("Biasing Process"  , parameters_.getParameter<std::string>("biasing_process"));
             runHeader.setStringParameter("Biasing Volume"   , parameters_.getParameter<std::string>("biasing_volume"));
             runHeader.setStringParameter("Biasing Particle" , parameters_.getParameter<std::string>("biasing_particle"));
             runHeader.setIntParameter(   "Biasing All"      , parameters_.getParameter<bool>(       "biasing_all" ));
             runHeader.setIntParameter(   "Biasing Incident" , parameters_.getParameter<bool>(       "biasing_incident" ));
             runHeader.setIntParameter(   "Biasing Disable EM",parameters_.getParameter<bool>(       "biasing_disableEMBiasing" ));
             runHeader.setIntParameter(   "Biasing Factor"   , parameters_.getParameter<int>(        "biasing_factor" ));
             runHeader.setFloatParameter( "Biasing Threshold", parameters_.getParameter<double>(     "biasing_threshold" ));
         }
         // Set a string parameter with the Geant4 SHA-1.
         G4String g4Version{G4RunManagerKernel::GetRunManagerKernel()->GetVersionString()};
         runHeader.setStringParameter("Geant4 revision", g4Version);
         // Write the header to the file.
         file_.writeRunHeader(runHeader);
         return true;
     }
References eventsBegan_, eventsCompleted_, file_, ldmx::Parameters::getParameter(), parameters_, ldmx::RunHeader::setFloatParameter(), ldmx::RunHeader::setIntParameter(), ldmx::RunHeader::setStringParameter(), and ldmx::EventFile::writeRunHeader().
Store() [3/3]
G4bool ldmx::RootPersistencyManager::Store (const G4VPhysicalVolume *) inline
Implementing this makes an "overloaded-virtual" compiler warning go away.
Definition at line 98 of file RootPersistencyManager.h.
{
                 return false;
             }
writeCalorimeterHitsCollection()
void ldmx::RootPersistencyManager::writeCalorimeterHitsCollection (G4CalorimeterHitsCollection * hc, std::vector< SimCalorimeterHit > & outputColl)
Write a collection of tracker hits to an output collection.
Parameters
hc The collection of G4CalorimeterHits.
outputColl The output collection of SimCalorimeterHits.
Definition at line 237 of file RootPersistencyManager.cxx.
{
         //get ancestral tracking information
         auto trackMap{UserTrackingAction::getUserTrackingAction()->getTrackMap()};
         int nHits = hc->GetSize();
         for (int iHit = 0; iHit < nHits; iHit++) {
             G4CalorimeterHit* g4hit = (G4CalorimeterHit*) hc->GetHit(iHit);
             const G4ThreeVector& pos = g4hit->getPosition();
             SimCalorimeterHit simHit;
             simHit.setID( g4hit->getID() );
             simHit.addContrib( trackMap->findIncident(g4hit->getTrackID()), g4hit->getTrackID(), g4hit->getPdgCode(), g4hit->getEdep(), g4hit->getTime() );
             simHit.setPosition( pos.x(), pos.y(), pos.z() );
             outputColl.push_back( simHit );
         }
         return;
     }
References ldmx::SimCalorimeterHit::addContrib(), ldmx::G4CalorimeterHit::getEdep(), ldmx::G4CalorimeterHit::getID(), ldmx::G4CalorimeterHit::getPdgCode(), ldmx::G4CalorimeterHit::getPosition(), ldmx::G4CalorimeterHit::getTime(), ldmx::G4CalorimeterHit::getTrackID(), ldmx::UserTrackingAction::getTrackMap(), ldmx::UserTrackingAction::getUserTrackingAction(), ldmx::SimCalorimeterHit::setID(), and ldmx::SimCalorimeterHit::setPosition().
Referenced by writeHitsCollections().
writeHeader()
void ldmx::RootPersistencyManager::writeHeader (const G4Event * anEvent)
Write header info into the output event from Geant4.
Parameters
anEvent The Geant4 event.
Definition at line 127 of file RootPersistencyManager.cxx.
{
         // Retrieve a mutable version of the event header
         EventHeader& eventHeader = event_->getEventHeader();
         // Set the event weight
         double weight{1};
         if (anEvent->GetUserInformation() != nullptr) {
             weight = static_cast<UserEventInformation*>(anEvent->GetUserInformation())->getWeight();
         } else if (anEvent->GetPrimaryVertex(0)) {
             weight = anEvent->GetPrimaryVertex(0)->GetWeight();
         }
         eventHeader.setWeight(weight);
         // Save the state of the random engine to an output stream. A string
         // is then extracted and saved to the event header.
         std::ostringstream stream;
         G4Random::saveFullState(stream);
         //std::cout << stream.str() << std::endl;
         eventHeader.setStringParameter("eventSeed", stream.str());
     }
References event_, ldmx::Event::getEventHeader(), ldmx::EventHeader::setStringParameter(), and ldmx::EventHeader::setWeight().
Referenced by buildEvent().
writeHitsCollections()
void ldmx::RootPersistencyManager::writeHitsCollections (const G4Event * anEvent, Event * outputEvent)
Write hits collections from Geant4 into a ROOT event.
Parameters
anEvent The Geant4 event.
outputEvent The output event.
Definition at line 158 of file RootPersistencyManager.cxx.
{
         // Get the HC of this event.
         G4HCofThisEvent* hce = anEvent->GetHCofThisEvent();
         int nColl = hce->GetNumberOfCollections();
         // Loop over all hits collections.
         for (int iColl = 0; iColl < nColl; iColl++) {
             // Get a hits collection and its name.
             G4VHitsCollection* hc = hce->GetHC(iColl);
             if ( ! hc ) {
                 EXCEPTION_RAISE(
                         "G4HitColl",
                         "G4VHitsCollection indexed " + std::to_string(iColl) + " returned a nullptr."
                         );
             }
             std::string collName = hc->GetName();
             if (dynamic_cast<G4TrackerHitsCollection*>(hc) != nullptr) {
                 // Write G4TrackerHit collection to output SimTrackerHit collection.
                 G4TrackerHitsCollection* trackerHitsColl = dynamic_cast<G4TrackerHitsCollection*>(hc);
                 std::vector<SimTrackerHit> outputColl;
                 writeTrackerHitsCollection( trackerHitsColl, outputColl );
                 // Add hits collection to output event.
                 outputEvent->add( collName, outputColl );
             } else if (dynamic_cast<G4CalorimeterHitsCollection*>(hc) != nullptr) {
                 G4CalorimeterHitsCollection* calHitsColl = dynamic_cast<G4CalorimeterHitsCollection*>(hc);
                 std::vector<SimCalorimeterHit> outputColl;
                 if (collName == EventConstants::ECAL_SIM_HITS) {
                     // Write ECal G4CalorimeterHit collection to output SimCalorimeterHit collection using helper class.
                     ecalHitIO_.writeHitsCollection(calHitsColl, outputColl );
                 } else {
                     // Write generic G4CalorimeterHit collection to output SimCalorimeterHit collection.
                     writeCalorimeterHitsCollection(calHitsColl, outputColl );
                 }
                 // Add hits collection to output event.
                 outputEvent->add( collName, outputColl );
             } //switch on type of hit collection
         } //loop through geant4 hit collections
         return;
     }
References ldmx::Event::add(), ecalHitIO_, EXCEPTION_RAISE, writeCalorimeterHitsCollection(), ldmx::EcalHitIO::writeHitsCollection(), and writeTrackerHitsCollection().
Referenced by buildEvent().
writeTrackerHitsCollection()
void ldmx::RootPersistencyManager::writeTrackerHitsCollection (G4TrackerHitsCollection * hc, std::vector< SimTrackerHit > & outputColl)
Write a collection of tracker hits to an output collection.
Parameters
hc The collection of G4TrackerHits.
outputColl The output collection of SimTrackerHits.
Definition at line 209 of file RootPersistencyManager.cxx.
{
         outputColl.clear();
         int nHits = hc->GetSize();
         for (int iHit = 0; iHit < nHits; iHit++) {
             G4TrackerHit* g4hit = (G4TrackerHit*) hc->GetHit(iHit);
             const G4ThreeVector& momentum = g4hit->getMomentum();
             const G4ThreeVector& position = g4hit->getPosition();
             SimTrackerHit simTrackerHit;
             simTrackerHit.setID(         g4hit->getID()         );
             simTrackerHit.setTime(       g4hit->getTime()       );
             simTrackerHit.setLayerID(    g4hit->getLayerID()    );
             simTrackerHit.setModuleID(   g4hit->getModuleID()   );
             simTrackerHit.setEdep(       g4hit->getEdep()       );
             simTrackerHit.setEnergy(     g4hit->getEnergy()     );
             simTrackerHit.setPathLength( g4hit->getPathLength() );
             simTrackerHit.setTrackID(    g4hit->getTrackID()    );
             simTrackerHit.setPdgID(      g4hit->getPdgID()      );
             simTrackerHit.setPosition(position.x(), position.y(), position.z());
             simTrackerHit.setMomentum(momentum.x(), momentum.y(), momentum.z());
             outputColl.push_back( simTrackerHit );
         }
         return;
     }
References ldmx::G4TrackerHit::getEdep(), ldmx::G4TrackerHit::getEnergy(), ldmx::G4TrackerHit::getID(), ldmx::G4TrackerHit::getLayerID(), ldmx::G4TrackerHit::getModuleID(), ldmx::G4TrackerHit::getMomentum(), ldmx::G4TrackerHit::getPathLength(), ldmx::G4TrackerHit::getPdgID(), ldmx::G4TrackerHit::getPosition(), ldmx::G4TrackerHit::getTime(), ldmx::G4TrackerHit::getTrackID(), ldmx::SimTrackerHit::setEdep(), ldmx::SimTrackerHit::setEnergy(), ldmx::SimTrackerHit::setID(), ldmx::SimTrackerHit::setLayerID(), ldmx::SimTrackerHit::setModuleID(), ldmx::SimTrackerHit::setMomentum(), ldmx::SimTrackerHit::setPathLength(), ldmx::SimTrackerHit::setPdgID(), ldmx::SimTrackerHit::setPosition(), ldmx::SimTrackerHit::setTime(), and ldmx::SimTrackerHit::setTrackID().
Referenced by writeHitsCollections().
The documentation for this class was generated from the following files:
SimCore/include/SimCore/RootPersistencyManager.h
SimCore/src/RootPersistencyManager.cxx