LDMX Software: simcore::lhe::LHEParticle Class Reference
simcore::lhe::LHEParticle Class Reference
Single particle record in an LHE event.
#include <LHEParticle.h>
Public Member Functions
LHEParticle (std::string &data)
int getIDUP () const
int getISTUP () const
int getMOTHUP (int) const
int getICOLUP (int) const
double getPUP (int) const
double getVTIMUP () const
double getSPINUP () const
void setMother (int i, LHEParticle *particle)
LHEParticle * getMother (int) const
void print (std::ostream &stream) const
Private Attributes
LHEParticle * mothers_ [2]
int idup_
int istup_
int mothup_ [2]
int icolup_ [2]
double pup_ [5]
double vtimup_
int spinup_
Friends
std::ostream & operator<< (std::ostream &stream, const LHEParticle &particle)
Detailed Description
Single particle record in an LHE event.
Definition at line 20 of file LHEParticle.h.
Constructor & Destructor Documentation
LHEParticle()
simcore::lhe::LHEParticle::LHEParticle (std::string & data)
Class constructor.
Parameters
data The particle record as a space-delimited string.
Definition at line 15 of file LHEParticle.cxx.
{
  std::istringstream iss(line);
  std::vector<std::string> tokens;
  do {
    std::string elem;
    iss >> elem;
    if (elem.size() != 0) {
      tokens.push_back(elem);
    }
  } while (iss);
  if (tokens.size() != 13) {
    EXCEPTION_RAISE("TokenNum",
                    "Wrong number of tokens in LHE particle record.");
  }
  idup_ = atof(tokens[0].c_str());
  istup_ = atoi(tokens[1].c_str());
  mothup_[0] = atoi(tokens[2].c_str());
  mothup_[1] = atoi(tokens[3].c_str());
  icolup_[0] = atoi(tokens[4].c_str());
  icolup_[1] = atoi(tokens[5].c_str());
  pup_[0] = atof(tokens[6].c_str());
  pup_[1] = atof(tokens[7].c_str());
  pup_[2] = atof(tokens[8].c_str());
  pup_[3] = atof(tokens[9].c_str());
  pup_[4] = atof(tokens[10].c_str());
  vtimup_ = atof(tokens[11].c_str());
  spinup_ = atof(tokens[12].c_str());
  mothers_[0] = NULL;
  mothers_[1] = NULL;
}
References icolup_, idup_, istup_, mothers_, mothup_, pup_, spinup_, and vtimup_.
Member Function Documentation
getICOLUP()
int simcore::lhe::LHEParticle::getICOLUP (int i) const
Get the particle color (ICOLUP) by index.
Returns
The particle color by index.
Definition at line 55 of file LHEParticle.cxx.
{ return icolup_[i]; }
References icolup_.
Referenced by print().
getIDUP()
int simcore::lhe::LHEParticle::getIDUP () const
Get the PDG code (IDUP).
Returns
The PDG code.
Definition at line 49 of file LHEParticle.cxx.
{ return idup_; }
References idup_.
Referenced by simcore::generators::LHEPrimaryGenerator::GeneratePrimaryVertex(), and print().
getISTUP()
int simcore::lhe::LHEParticle::getISTUP () const
Get the status code (ISTUP).
Returns
The status code.
Definition at line 51 of file LHEParticle.cxx.
{ return istup_; }
References istup_.
Referenced by simcore::generators::LHEPrimaryGenerator::GeneratePrimaryVertex(), and print().
getMother()
LHEParticle * simcore::lhe::LHEParticle::getMother (int i) const
Get a mother particle by index.
Returns
The mother particle at the index.
Definition at line 67 of file LHEParticle.cxx.
{ return mothers_[i]; }
References mothers_.
Referenced by simcore::generators::LHEPrimaryGenerator::GeneratePrimaryVertex().
getMOTHUP()
int simcore::lhe::LHEParticle::getMOTHUP (int i) const
Get a mother particle index (MOTHUP) by index.
Returns
The mother particle by index.
Definition at line 53 of file LHEParticle.cxx.
{ return mothup_[i]; }
References mothup_.
Referenced by print(), and simcore::lhe::LHEReader::readNextEvent().
getPUP()
double simcore::lhe::LHEParticle::getPUP (int i) const
Get a momentum component (PUP) by index. Defined in order: E/C, Px, Py, Pz, mass
Returns
The momentum component by index.
Definition at line 57 of file LHEParticle.cxx.
{ return pup_[i]; }
References pup_.
Referenced by simcore::generators::LHEPrimaryGenerator::GeneratePrimaryVertex(), and print().
getSPINUP()
double simcore::lhe::LHEParticle::getSPINUP () const
Get the particle's spin (SPINUP).
Returns
The particle's spin.
Definition at line 61 of file LHEParticle.cxx.
{ return spinup_; }
References spinup_.
Referenced by print().
getVTIMUP()
double simcore::lhe::LHEParticle::getVTIMUP () const
Get the proper lifetime (VTIMUP).
Returns
The particle's proper lifetime.
Definition at line 59 of file LHEParticle.cxx.
{ return vtimup_; }
References vtimup_.
Referenced by simcore::generators::LHEPrimaryGenerator::GeneratePrimaryVertex(), and print().
print()
void simcore::lhe::LHEParticle::print (std::ostream & stream) const
Print particle information to an output stream.
Parameters
stream The output stream.
Definition at line 69 of file LHEParticle.cxx.
{
  stream << "LHEParticle { "
         << "IDUP: " << getIDUP() << ", ISTUP: " << getISTUP()
         << ", MOTHUP[0]: " << getMOTHUP(0) << ", MOTHUP[1]: " << getMOTHUP(1)
         << ", ICOLUP[0]: " << getICOLUP(0) << ", ICOLUP[1]: " << getICOLUP(1)
         << ", PUP[0]: " << getPUP(0) << ", PUP[1]: " << getPUP(1)
         << ", PUP[2]: " << getPUP(2) << ", PUP[3]: " << getPUP(3)
         << ", PUP[4]: " << getPUP(4) << ", VTIMUP: " << getVTIMUP()
         << ", SPINUP: " << getSPINUP() << " }" << std::endl;
}
References getICOLUP(), getIDUP(), getISTUP(), getMOTHUP(), getPUP(), getSPINUP(), and getVTIMUP().
setMother()
void simcore::lhe::LHEParticle::setMother (int i, LHEParticle * particle)
Set a mother particle by index.
Parameters
i The mother index.
particle The mother particle.
Definition at line 63 of file LHEParticle.cxx.
{
  mothers_[i] = mother;
}
References mothers_.
Referenced by simcore::lhe::LHEReader::readNextEvent().
Friends And Related Function Documentation
operator<<
std::ostream & operator<< (std::ostream & stream, const LHEParticle & particle) friend
Overloaded stream operator.
Parameters
stream The output stream.
particle The particle to print.
Definition at line 80 of file LHEParticle.cxx.
{
  particle.print(stream);
  return stream;
}
Member Data Documentation
icolup_
int simcore::lhe::LHEParticle::icolup_[2] private
The particle color.
Definition at line 122 of file LHEParticle.h.
Referenced by getICOLUP(), and LHEParticle().
idup_
int simcore::lhe::LHEParticle::idup_ private
The PDG code.
Definition at line 107 of file LHEParticle.h.
Referenced by getIDUP(), and LHEParticle().
istup_
int simcore::lhe::LHEParticle::istup_ private
The status code.
Definition at line 112 of file LHEParticle.h.
Referenced by getISTUP(), and LHEParticle().
mothers_
LHEParticle* simcore::lhe::LHEParticle::mothers_[2] private
The mother particles.
Definition at line 102 of file LHEParticle.h.
Referenced by getMother(), LHEParticle(), and setMother().
mothup_
int simcore::lhe::LHEParticle::mothup_[2] private
The mother particle indices.
Definition at line 117 of file LHEParticle.h.
Referenced by getMOTHUP(), and LHEParticle().
pup_
double simcore::lhe::LHEParticle::pup_[5] private
The momentum components.
Definition at line 127 of file LHEParticle.h.
Referenced by getPUP(), and LHEParticle().
spinup_
int simcore::lhe::LHEParticle::spinup_ private
The particle's spin.
Definition at line 137 of file LHEParticle.h.
Referenced by getSPINUP(), and LHEParticle().
vtimup_
double simcore::lhe::LHEParticle::vtimup_ private
The proper time.
Definition at line 132 of file LHEParticle.h.
Referenced by getVTIMUP(), and LHEParticle().
The documentation for this class was generated from the following files:
SimCore/include/SimCore/LHE/LHEParticle.h
SimCore/src/SimCore/LHE/LHEParticle.cxx