LDMX Software: framework::Bus::Passenger< BaggageType > Class Template Reference
framework::Bus::Passenger< BaggageType > Class Template Reference
Classes
struct the_type
Public Member Functions
Passenger ()
virtual ~Passenger ()
virtual TBranch * attach (TTree *tree, const std::string &branch_name, bool can_create)
const BaggageType & get () const
void update (const BaggageType &updated_obj)
virtual void clear ()
virtual void stream (std::ostream &s) const
Public Member Functions inherited from framework::Bus::Seat
virtual ~Seat ()
Private Member Functions
template<typename T >
TBranch * attach (the_type< T > t, TTree *tree, const std::string &branch_name, bool can_create)
TBranch * attachBasic (TTree *tree, const std::string &branch_name, bool can_create)
TBranch * attach (the_type< bool > t, TTree *tree, const std::string &branch_name, bool can_create)
TBranch * attach (the_type< short > t, TTree *tree, const std::string &branch_name, bool can_create)
TBranch * attach (the_type< int > t, TTree *tree, const std::string &branch_name, bool can_create)
TBranch * attach (the_type< long > t, TTree *tree, const std::string &branch_name, bool can_create)
TBranch * attach (the_type< float > t, TTree *tree, const std::string &branch_name, bool can_create)
TBranch * attach (the_type< double > t, TTree *tree, const std::string &branch_name, bool can_create)
void clear (the_type< bool > t)
void clear (the_type< short > t)
void clear (the_type< int > t)
void clear (the_type< long > t)
void clear (the_type< float > t)
void clear (the_type< double > t)
template<typename T >
void clear (the_type< T > t)
template<typename Content >
void clear (the_type< std::vector< Content > > t)
template<typename Key , typename Val >
void clear (the_type< std::map< Key, Val > > t)
template<typename T >
void post_update (the_type< T > t)
template<typename T >
void stream (the_type< T > t, std::ostream &s) const
template<typename Content >
void stream (the_type< std::vector< Content > > t, std::ostream &s) const
template<typename Key , typename Val >
void stream (the_type< std::map< Key, Val > > t, std::ostream &s) const
Private Attributes
BaggageType * baggage_
A pointer to the baggage we own and created.
Friends
std::ostream & operator<< (std::ostream &s, const framework::Bus::Passenger< BaggageType > &p)
Detailed Description
template<typename BaggageType>
class framework::Bus::Passenger< BaggageType >
A bus passenger
We store the bus passenger's baggage as a dynamically created object. This is necessary so that we can interface with the ROOT TTree.
Here we do all the heavy lifting of carrying a certain type of object with specializations for clearing, sorting, and printing.
Note
Printing specialization is possible if we include the requirement that all event objects must define the 'operator<<' method.
Core Functions
Define the type of "baggage" that is being carried on the event bus
"Attach" the baggage to a output or input TTree for writing or reading
"Update" the contents of the baggage
"Clear" the baggage to a default or empty state at the end of each event
"Print" the baggage to a ostream (via the operator<<)
Basic Structure
The method of specializing the clear, post_update, and attach methods to the different types of passenger's baggage is derived from a helpful blog post. Basically, the idea is to add a parameter input into the functions that "stores" the type that we are currently carrying. This allows the compiler to choose the best method from the overloaded functions by matching the types of parameters.
Possible Types
BSILFD - bool, short, int, long, float, double
class with Clear() method defined
std::vector of type with operator< defined
std::map with key type that has operator< defined
Template Parameters
in] BaggageType the type of object that this passenger carries
Definition at line 284 of file Bus.h.
Constructor & Destructor Documentation
Passenger()
template<typename BaggageType > framework::Bus::Passenger< BaggageType >::Passenger () inline
Constructor
Dynamically create a default constructed instance of our baggage.
Note
This requires that all of the BaggageTypes are default-constructible. This is a simple requirement because ROOT dictionary generation already requires a default constructor to be defined.
Definition at line 296 of file Bus.h.
: Seat(), baggage_{new BaggageType} {}
~Passenger()
template<typename BaggageType > virtual framework::Bus::Passenger< BaggageType >::~Passenger () inline virtual
Destructor
Clean up after ourselves by deleting the object we created earlier in the constructor.
Note
Because the baggage_ member variable may be attached to a TTree, this object needs to be destructed carefully. The TTree assumes that the object we attach to it is valid until we either destruct the TTree or reset its addresses. As such, if we want to destruct a Passenger, we need to know that its baggage is either not attached to a TTree or the TTree it was attached to has stopped looking at it (either by deletion or reset).
Definition at line 315 of file Bus.h.
{ delete baggage_; }
References framework::Bus::Passenger< BaggageType >::baggage_.
Member Function Documentation
attach() [1/8]
template<typename BaggageType > TBranch * framework::Bus::Passenger< BaggageType >::attach (the_type< bool > t, TTree * tree, const std::string & branch_name, bool can_create) inline private
Specialization for bools
See also
attachBasic for the actual implementation
Parameters
t Unused, only helping compiler choose the correct method
[in] tree pointer to TTree to attach to
[in] branch_name name of branch we should attach to
[in] can_create allow us to create a branch on tree if needed
Returns
pointer to branch that we attached to (maybe be null)
Definition at line 505 of file Bus.h.
{
      return attachBasic(tree, branch_name, can_create);
    }
References framework::Bus::Passenger< BaggageType >::attachBasic().
attach() [2/8]
template<typename BaggageType > TBranch * framework::Bus::Passenger< BaggageType >::attach (the_type< double > t, TTree * tree, const std::string & branch_name, bool can_create) inline private
Specialization for doubles
See also
attachBasic for the actual implementation
Parameters
t Unused, only helping compiler choose the correct method
[in] tree pointer to TTree to attach to
[in] branch_name name of branch we should attach to
[in] can_create allow us to create a branch on tree if needed
Returns
pointer to branch that we attached to (maybe be null)
Definition at line 585 of file Bus.h.
{
      return attachBasic(tree, branch_name, can_create);
    }
References framework::Bus::Passenger< BaggageType >::attachBasic().
attach() [3/8]
template<typename BaggageType > TBranch * framework::Bus::Passenger< BaggageType >::attach (the_type< float > t, TTree * tree, const std::string & branch_name, bool can_create) inline private
Specialization for floats
See also
attachBasic for the actual implementation
Parameters
t Unused, only helping compiler choose the correct method
[in] tree pointer to TTree to attach to
[in] branch_name name of branch we should attach to
[in] can_create allow us to create a branch on tree if needed
Returns
pointer to branch that we attached to (maybe be null)
Definition at line 569 of file Bus.h.
{
      return attachBasic(tree, branch_name, can_create);
    }
References framework::Bus::Passenger< BaggageType >::attachBasic().
attach() [4/8]
template<typename BaggageType > TBranch * framework::Bus::Passenger< BaggageType >::attach (the_type< int > t, TTree * tree, const std::string & branch_name, bool can_create) inline private
Specialization for ints
See also
attachBasic for the actual implementation
Parameters
t Unused, only helping compiler choose the correct method
[in] tree pointer to TTree to attach to
[in] branch_name name of branch we should attach to
[in] can_create allow us to create a branch on tree if needed
Returns
pointer to branch that we attached to (maybe be null)
Definition at line 537 of file Bus.h.
{
      return attachBasic(tree, branch_name, can_create);
    }
References framework::Bus::Passenger< BaggageType >::attachBasic().
attach() [5/8]
template<typename BaggageType > TBranch * framework::Bus::Passenger< BaggageType >::attach (the_type< long > t, TTree * tree, const std::string & branch_name, bool can_create) inline private
Specialization for longs
See also
attachBasic for the actual implementation
Parameters
t Unused, only helping compiler choose the correct method
[in] tree pointer to TTree to attach to
[in] branch_name name of branch we should attach to
[in] can_create allow us to create a branch on tree if needed
Returns
pointer to branch that we attached to (maybe be null)
Definition at line 553 of file Bus.h.
{
      return attachBasic(tree, branch_name, can_create);
    }
References framework::Bus::Passenger< BaggageType >::attachBasic().
attach() [6/8]
template<typename BaggageType > TBranch * framework::Bus::Passenger< BaggageType >::attach (the_type< short > t, TTree * tree, const std::string & branch_name, bool can_create) inline private
Specialization for shorts
See also
attachBasic for the actual implementation
Parameters
t Unused, only helping compiler choose the correct method
[in] tree pointer to TTree to attach to
[in] branch_name name of branch we should attach to
[in] can_create allow us to create a branch on tree if needed
Returns
pointer to branch that we attached to (maybe be null)
Definition at line 521 of file Bus.h.
{
      return attachBasic(tree, branch_name, can_create);
    }
References framework::Bus::Passenger< BaggageType >::attachBasic().
attach() [7/8]
template<typename BaggageType > template<typename T > TBranch * framework::Bus::Passenger< BaggageType >::attach (the_type< T > t, TTree * tree, const std::string & branch_name, bool can_create) inline private
Attach to a (potentially) new branch on the input tree.
This is the attachment mechanism used for all non-basic types. The specializations for the basic types (BSILFD - bool, short, int, long, float, double) use attachBasic which is slightly different in its branching.
See also
TBranchElement::SetObject for attaching an object to a branch that already exists
TTree::Branch for creating a new branch
With complicated objects like most of our event bus baggage, ROOT is able to deduce the type as long as we load a ROOT dictionary with all of the classes defined inside of it.
Parameters
t Unused, only helping compiler choose the correct method
[in] tree pointer to TTree to attach to
[in] branch_name name of branch we should attach to
[in] can_create allow us to create a branch on tree if needed
Returns
pointer to branch that we attached to (maybe be null)
Definition at line 436 of file Bus.h.
{
      TBranch* branch = tree->GetBranch(branch_name.c_str());
      if (branch) {
        // branch already exists
        //  set the object the branch should read/write from/to
        branch->SetObject(baggage_);
      } else if (can_create) {
        // branch doesnt exist and we are allowed to make a new one
        branch = tree->Branch(branch_name.c_str(), baggage_, 100000, 3);
      }
      return branch;
    }
References framework::Bus::Passenger< BaggageType >::baggage_.
attach() [8/8]
template<typename BaggageType > virtual TBranch * framework::Bus::Passenger< BaggageType >::attach (TTree * tree, const std::string & branch_name, bool can_create) inline virtual
Attach this passenger to the input tree.
Now we know what type of object this passenger is carrying, so we can attach it to the tree.
If the 'can_create' parameter is true and a branch of the input name doesn't exist on the tree, we create a new branch of the input branch name. If this parameter is false, we simply return the nullptr signifying that this branch doesn't exist.
See also
attach(the_type<T>,TTree*,const std::string&,bool) for how we attach to higher-level classes
attachBasic(TTree*,const std::string&,bool) for how we attach to basic types
Parameters
[in] tree pointer to TTree to attach to
[in] branch_name name of branch we should attach to
[in] can_create allow us to create a branch on tree if needed
Returns
pointer to branch that we attached to (maybe be null)
Implements framework::Bus::Seat.
Definition at line 340 of file Bus.h.
{
      return attach(the_type<BaggageType>{}, tree, branch_name, can_create);
    }
References framework::Bus::Passenger< BaggageType >::attach().
Referenced by framework::Bus::Passenger< BaggageType >::attach().
attachBasic()
template<typename BaggageType > TBranch * framework::Bus::Passenger< BaggageType >::attachBasic (TTree * tree, const std::string & branch_name, bool can_create) inline private
Attach a basic type
We assume that the current baggage is one of BSILFD bool, short, int, long, float, double
We need this attaching mechanism to be different from the higher-level objects because TTree requires different inputs and returns different outputs for the basic types.
See also
TBranch::SetAddress for attaching a basic type to a branch that already exists
TTree::Branch for creating a new branch
typeid for identifying the type of an object
Parameters
[in] tree pointer to TTree to attach to
[in] branch_name name of branch we should attach to
[in] can_create allow us to create a branch on tree if needed
Returns
pointer to branch that we attached to (maybe be null)
Definition at line 474 of file Bus.h.
{
      TBranch* branch = tree->GetBranch(branch_name.c_str());
      if (branch) {
        // branch already exists
        //  set the object the branch should read/write from/to
        branch->SetAddress(baggage_);
      } else if (can_create) {
        static const std::map<std::string, std::string> cpp_to_root_type_name =
            {{"b", "O"}, {"s", "S"}, {"i", "I"},
             {"l", "L"}, {"f", "F"}, {"d", "D"}};
        // branch doesnt exist and we are allowed to make a new one
        std::string cpp_type = typeid(*baggage_).name();
        branch = tree->Branch(
            branch_name.c_str(), baggage_,
            (branch_name + "/" + cpp_to_root_type_name.at(cpp_type)).c_str());
      }
      return branch;
    }
References framework::Bus::Passenger< BaggageType >::baggage_.
Referenced by framework::Bus::Passenger< BaggageType >::attach().
clear() [1/10]
template<typename BaggageType > virtual void framework::Bus::Passenger< BaggageType >::clear () inline virtual
Reset the object we are carrying to an undefined state.
We call the overloaded, templated clear method that allows the compiler to deduce which implementation to use depending on the type of baggage we are carrying.
Implements framework::Bus::Seat.
Definition at line 374 of file Bus.h.
{ clear(the_type<BaggageType>{}); }
References framework::Bus::Passenger< BaggageType >::clear().
Referenced by framework::Bus::Passenger< BaggageType >::clear().
clear() [2/10]
template<typename BaggageType > void framework::Bus::Passenger< BaggageType >::clear (the_type< bool > t) inline private
Clear bool by setting it to false.
Parameters
t Unused, only helping compiler choose the correct method
Definition at line 595 of file Bus.h.
{ *baggage_ = false; }
References framework::Bus::Passenger< BaggageType >::baggage_.
clear() [3/10]
template<typename BaggageType > void framework::Bus::Passenger< BaggageType >::clear (the_type< double > t) inline private
Clear double by setting it to the minimum defined by the compiler.
Parameters
t Unused, only helping compiler choose the correct method
Definition at line 633 of file Bus.h.
{
      *baggage_ = std::numeric_limits<BaggageType>::min();
    }
References framework::Bus::Passenger< BaggageType >::baggage_.
clear() [4/10]
template<typename BaggageType > void framework::Bus::Passenger< BaggageType >::clear (the_type< float > t) inline private
Clear float by setting it to the minimum defined by the compiler.
Parameters
t Unused, only helping compiler choose the correct method
Definition at line 625 of file Bus.h.
{
      *baggage_ = std::numeric_limits<BaggageType>::min();
    }
References framework::Bus::Passenger< BaggageType >::baggage_.
clear() [5/10]
template<typename BaggageType > void framework::Bus::Passenger< BaggageType >::clear (the_type< int > t) inline private
Clear int by setting it to the minimum defined by the compiler.
Parameters
t Unused, only helping compiler choose the correct method
Definition at line 609 of file Bus.h.
{
      *baggage_ = std::numeric_limits<BaggageType>::min();
    }
References framework::Bus::Passenger< BaggageType >::baggage_.
clear() [6/10]
template<typename BaggageType > void framework::Bus::Passenger< BaggageType >::clear (the_type< long > t) inline private
Clear long by setting it to the minimum defined by the compiler.
Parameters
t Unused, only helping compiler choose the correct method
Definition at line 617 of file Bus.h.
{
      *baggage_ = std::numeric_limits<BaggageType>::min();
    }
References framework::Bus::Passenger< BaggageType >::baggage_.
clear() [7/10]
template<typename BaggageType > void framework::Bus::Passenger< BaggageType >::clear (the_type< short > t) inline private
Clear short by setting it to the minimum defined by the compiler.
Parameters
t Unused, only helping compiler choose the correct method
Definition at line 601 of file Bus.h.
{
      *baggage_ = std::numeric_limits<BaggageType>::min();
    }
References framework::Bus::Passenger< BaggageType >::baggage_.
clear() [8/10]
template<typename BaggageType > template<typename Key , typename Val > void framework::Bus::Passenger< BaggageType >::clear (the_type< std::map< Key, Val > > t) inline private
Clear a map by calling the std::map::clear method.
Parameters
t Unused, only helping compiler choose the correct method
Definition at line 662 of file Bus.h.
{ baggage_->clear(); }
References framework::Bus::Passenger< BaggageType >::baggage_.
clear() [9/10]
template<typename BaggageType > template<typename Content > void framework::Bus::Passenger< BaggageType >::clear (the_type< std::vector< Content > > t) inline private
Clear a vector by calling the std::vector::clear method.
Parameters
t Unused, only helping compiler choose the correct method
Definition at line 655 of file Bus.h.
{ baggage_->clear(); }
References framework::Bus::Passenger< BaggageType >::baggage_.
clear() [10/10]
template<typename BaggageType > template<typename T > void framework::Bus::Passenger< BaggageType >::clear (the_type< T > t) inline private
Clear a general class by calling its 'Clear' method.
Note
The capitalization of 'Clear' is a relic of when the event bus objects needed to inherit from TObject. We could simplify this code by renaming the 'Clear' method to 'clear' which would match std::vector and std::map.
Parameters
t Unused, only helping compiler choose the correct method
Definition at line 648 of file Bus.h.
{ baggage_->Clear(); }
References framework::Bus::Passenger< BaggageType >::baggage_.
get()
template<typename BaggageType > const BaggageType & framework::Bus::Passenger< BaggageType >::get () const inline
Get the object this passenger is carrying
Returns
const reference to the object
Definition at line 349 of file Bus.h.
{ return *baggage_; }
References framework::Bus::Passenger< BaggageType >::baggage_.
post_update()
template<typename BaggageType > template<typename T > void framework::Bus::Passenger< BaggageType >::post_update (the_type< T > t) inline private
In general, don't do anything after an object has been updated.
Parameters
t Unused, only helping compiler choose the correct method
Definition at line 670 of file Bus.h.
{}
Referenced by framework::Bus::Passenger< BaggageType >::update().
stream() [1/4]
template<typename BaggageType > virtual void framework::Bus::Passenger< BaggageType >::stream (std::ostream & s) const inline virtual
Stream the passenger's object to the input ostream
We call the overloaded, templated stream method that allows the compiler to deduce which implementation to use depending on the type of baggage we are carrying.
Implements framework::Bus::Seat.
Definition at line 383 of file Bus.h.
{
      stream(the_type<BaggageType>{}, s);
    }
References framework::Bus::Passenger< BaggageType >::stream().
Referenced by framework::Bus::Passenger< BaggageType >::stream().
stream() [2/4]
template<typename BaggageType > template<typename Key , typename Val > void framework::Bus::Passenger< BaggageType >::stream (the_type< std::map< Key, Val > > t, std::ostream & s) const inline private
Stream a map of objects by looping through them
Note
Here is where we require that all event objects used as a key or value in a map need the 'operator<<' defined.
Parameters
t Unused, only helping compiler choose the correct method
s ostream to write to
Definition at line 732 of file Bus.h.
{
      s << baggage_->size();
      /*
      s << "{ ";
      for (auto const& [k, v] : *baggage_) {
        s << k << " -> " << v << " ";
      }
      s << "}";
      */
    }
References framework::Bus::Passenger< BaggageType >::baggage_.
stream() [3/4]
template<typename BaggageType > template<typename Content > void framework::Bus::Passenger< BaggageType >::stream (the_type< std::vector< Content > > t, std::ostream & s) const inline private
Stream a vector of objects by looping through them.
Note
Here is where we require that all event objects inside a vector need the 'operator<<' defined.
Parameters
t Unused, only helping compiler choose the correct method
s ostream to write to
Definition at line 712 of file Bus.h.
{
      s << baggage_->size();
      /*
      s << "[ ";
      for (auto const& entry : *baggage_) s << entry << " ";
      s << "]";
      */
    }
References framework::Bus::Passenger< BaggageType >::baggage_.
stream() [4/4]
template<typename BaggageType > template<typename T > void framework::Bus::Passenger< BaggageType >::stream (the_type< T > t, std::ostream & s) const inline private
For std::vector, use the sort method after the contents are updated.
Note
This is where we require that any contents of vectors have the operator< defined.
Parameters
t Unused, only helping compiler choose the correct method template <typename Content> void post_update(the_type<std::vector<Content>> t) { std::sort(baggage_->begin(), baggage_->end()); } Stream a basic type that has its own definition of 'operator<<'.
Note
Here is where we require that all event bus objects (not inside a vector or map) need the 'operatore<<' defined.
Parameters
t Unused, only helping compiler choose the correct method
s ostream to write to
Definition at line 698 of file Bus.h.
{
      //s << *baggagage_;
    }
update()
template<typename BaggageType > void framework::Bus::Passenger< BaggageType >::update (const BaggageType & updated_obj) inline
Update this passenger's baggage.
See also
post_update to allow the different types to take actions after the baggage is updated. For example, the vector specialization of post_update uses this opportunity to sort the list of objects.
Parameters
[in] updated_obj BaggageType to copy into our object
Definition at line 362 of file Bus.h.
{
      *baggage_ = updated_obj;
      post_update(the_type<BaggageType>());
    }
References framework::Bus::Passenger< BaggageType >::baggage_, and framework::Bus::Passenger< BaggageType >::post_update().
Friends And Related Function Documentation
operator<<
template<typename BaggageType > std::ostream & operator<< (std::ostream & s, const framework::Bus::Passenger< BaggageType > & p) friend
Stream this object to the output stream
May contain newlines if large object.
See also
stream for detailed implementation
Parameters
[in] s ostream to write to
[in] p Passenger to write out
Returns
modified ostream
Definition at line 397 of file Bus.h.
{
      p.stream(s);
      return s;
    }
Member Data Documentation
baggage_
template<typename BaggageType > BaggageType* framework::Bus::Passenger< BaggageType >::baggage_ private
A pointer to the baggage we own and created.
Definition at line 745 of file Bus.h.
Referenced by framework::Bus::Passenger< BaggageType >::attach(), framework::Bus::Passenger< BaggageType >::attachBasic(), framework::Bus::Passenger< BaggageType >::clear(), framework::Bus::Passenger< BaggageType >::get(), framework::Bus::Passenger< BaggageType >::stream(), framework::Bus::Passenger< BaggageType >::update(), and framework::Bus::Passenger< BaggageType >::~Passenger().
The documentation for this class was generated from the following file:
Framework/include/Framework/Bus.h