LDMX Software: packing::utility::Writer Class Reference
packing::utility::Writer Class Reference
#include <Writer.h>
Public Member Functions
Writer ()
void open (const std::string &file_name)
Writer (const std::string &file_name)
~Writer ()=default
destructor, close the input file stream
template<typename WordType , std::enable_if_t< std::is_integral< WordType >::value, bool > = true>
Writer & write (const WordType *w, std::size_t num)
template<typename WordType , std::enable_if_t< std::is_integral< WordType >::value, bool > = true>
Writer & operator<< (const WordType &w)
template<typename WordType , std::enable_if_t< std::is_integral< WordType >::value, bool > = true>
Writer & operator<< (const std::vector< WordType > &vec)
template<typename ObjectType , std::enable_if_t< std::is_class< ObjectType >::value, bool > = true>
Writer & operator<< (const ObjectType &o)
template<typename ObjectType , std::enable_if_t< std::is_class< ObjectType >::value, bool > = true>
Writer & operator<< (const std::vector< ObjectType > &vec)
bool operator! () const
operator bool () const
Private Attributes
std::ofstream file_
file stream we are writing to
Detailed Description
Writing a raw data file.
We wrap a basic std::ifstream in order to make the writing of specific-width words easier for ourselves.
Definition at line 19 of file Writer.h.
Constructor & Destructor Documentation
Writer() [1/2]
packing::utility::Writer::Writer () inline
default constructor
make sure we don't skip "whitespace"
Definition at line 26 of file Writer.h.
           {
    file_.unsetf(std::ios::skipws);
  }
References file_.
Writer() [2/2]
packing::utility::Writer::Writer (const std::string & file_name) inline
Open the input file name upon construction of this writer.
Parameters
[in] file_name name of file to open
Definition at line 46 of file Writer.h.
                                     : Writer() {
    this->open(file_name);
  }
References open().
Member Function Documentation
open()
void packing::utility::Writer::open (const std::string & file_name) inline
Open a file with this writer
We open the file stream in output, binary mode.
Parameters
[in] file_name name of file to open
Definition at line 37 of file Writer.h.
{
    file_.open(file_name, std::ios::out | std::ios::binary);
  }
References file_.
Referenced by packing::rawdatafile::File::File(), and Writer().
operator bool()
packing::utility::Writer::operator bool () const inline
Check if writer is in a good/bad state
Uses std::ofstream::fail to check on stream.
Returns
true if stream is in good state
Definition at line 151 of file Writer.h.
{
    return !file_.fail();
  }
References file_.
operator!()
bool packing::utility::Writer::operator! () const inline
Check if writer is in a fail state
Uses std::ofstream::fail to check on stream.
Returns
true if stream is in fail state
Definition at line 140 of file Writer.h.
{
    return file_.fail();
  }
References file_.
operator<<() [1/4]
template<typename ObjectType , std::enable_if_t< std::is_class< ObjectType >::value, bool > = true> Writer & packing::utility::Writer::operator<< (const ObjectType & o) inline
Write out a class object.
We assume that the input class object has a specific method defined.
Writer& write(Writer&) const;
With this method defined, then the class can be streamed out through this object.
Template Parameters
in] ObjectType class-type to write out
Parameters
[in] o object to write out
Returns
*this
Definition at line 113 of file Writer.h.
{
    return o.write(*this);
  }
References write().
operator<<() [2/4]
template<typename ObjectType , std::enable_if_t< std::is_class< ObjectType >::value, bool > = true> Writer & packing::utility::Writer::operator<< (const std::vector< ObjectType > & vec) inline
Write out a vector fo class objects
We make the same assumptions as when streaming out a single class object. We leave early if any write action changes the file to a fail state.
Template Parameters
in] ObjectType class-type inside vector to write out
Parameters
[in] vec vector of objects to write out
Returns
*this
Definition at line 128 of file Writer.h.
{
    for (auto const& o : vec) if (!o.write(*this)) return *this;
    return *this;
  }
operator<<() [3/4]
template<typename WordType , std::enable_if_t< std::is_integral< WordType >::value, bool > = true> Writer & packing::utility::Writer::operator<< (const std::vector< WordType > & vec) inline
Write out a vector of integral-type objects.
This is a short-cut in order to help speed up writing.
Template Parameters
in] WordType integral-type to write out
Parameters
[in] vec vector of integral words to write out
Returns
*this
Definition at line 94 of file Writer.h.
{
    return write(vec.data(), vec.size());
  }
References write().
operator<<() [4/4]
template<typename WordType , std::enable_if_t< std::is_integral< WordType >::value, bool > = true> Writer & packing::utility::Writer::operator<< (const WordType & w) inline
Write a single integral-type word to the output file stream.
See also
write
Template Parameters
in] WordType integral-type to write out
Parameters
[in] w single word to write out
Returns
*this
Definition at line 80 of file Writer.h.
{
    return write(&w, 1);
  }
References write().
write()
template<typename WordType , std::enable_if_t< std::is_integral< WordType >::value, bool > = true> Writer & packing::utility::Writer::write (const WordType * w, std::size_t num) inline
Write a certain number of words from the input array to the output file stream.
This method is only enabled for integral types so we can safely reinterpret the underlying data as an array of characters.
Template Parameters
in] WordType integral-type to write out
Parameters
[in] w pointer to array of words to write
[in] num number of words in array
Returns
*this
Definition at line 65 of file Writer.h.
{
    file_.write(reinterpret_cast<const char*>(w), sizeof(WordType)*num);
    return *this;
  }
References file_.
Referenced by operator<<().
Member Data Documentation
file_
std::ofstream packing::utility::Writer::file_ private
file stream we are writing to
Definition at line 157 of file Writer.h.
Referenced by open(), operator bool(), operator!(), write(), and Writer().
The documentation for this class was generated from the following file:
Packing/include/Packing/Utility/Writer.h