LDMX Software: dqm::TrigScintTrackDQM Class Reference
dqm::TrigScintTrackDQM Class Reference
Public Member Functions
TrigScintTrackDQM (const std::string &name, framework::Process &process)
~TrigScintTrackDQM ()
void configure (framework::config::Parameters &pSet)
void analyze (const framework::Event &event)
void onProcessStart ()
Public Member Functions inherited from framework::Analyzer
Analyzer (const std::string &name, Process &process)
virtual void analyze (const Event &event)=0
Public Member Functions inherited from framework::EventProcessor
EventProcessor (const std::string &name, Process &process)
virtual ~EventProcessor ()
virtual void configure (framework::config::Parameters &parameters)
virtual void onNewRun (const ldmx::RunHeader &runHeader)
virtual void onFileOpen (EventFile &eventFile)
virtual void onFileClose (EventFile &eventFile)
virtual void onProcessStart ()
virtual void onProcessEnd ()
template<class T >
const T & getCondition (const std::string &condition_name)
TDirectory * getHistoDirectory ()
void setStorageHint (framework::StorageControlHint hint)
void setStorageHint (framework::StorageControlHint hint, const std::string &purposeString)
int getLogFrequency () const
int getRunNumber () const
std::string getName () const
void createHistograms (const std::vector< framework::config::Parameters > &histos)
Private Attributes
std::string trackCollectionName_ {"TriggerPadTracks"}
std::string passName_ {""}
Additional Inherited Members
Static Public Member Functions inherited from framework::EventProcessor
static void declare (const std::string &classname, int classtype, EventProcessorMaker *)
Static Public Attributes inherited from framework::Analyzer
static const int CLASSTYPE {2}
Protected Member Functions inherited from framework::EventProcessor
void abortEvent ()
Protected Attributes inherited from framework::EventProcessor
HistogramHelper histograms_
Interface class for making and filling histograms.
NtupleManager & ntuple_ {NtupleManager::getInstance()}
Manager for any ntuples.
logging::logger theLog_
The logger for this EventProcessor.
Detailed Description
Definition at line 19 of file TrigScintTrackDQM.h.
Constructor & Destructor Documentation
TrigScintTrackDQM()
dqm::TrigScintTrackDQM::TrigScintTrackDQM (const std::string & name, framework::Process & process)
Constructor
Definition at line 5 of file TrigScintTrackDQM.cxx.
    : framework::Analyzer(name, process) {}
~TrigScintTrackDQM()
dqm::TrigScintTrackDQM::~TrigScintTrackDQM ()
Destructor
Definition at line 9 of file TrigScintTrackDQM.cxx.
{}
Member Function Documentation
analyze()
void dqm::TrigScintTrackDQM::analyze (const framework::Event & event) virtual
Process the event and make histograms ro summaries.
Parameters
event The event to analyze.
Implements framework::Analyzer.
Definition at line 38 of file TrigScintTrackDQM.cxx.
{
  // Get the collection of TrigScintTrack digitized tracks if the exists
  const std::vector<ldmx::TrigScintTrack> TrigScintTracks =
      event.getCollection<ldmx::TrigScintTrack>(trackCollectionName_,
                                                passName_);
  // Loop through all TrigScint tracks in the event
  for (const ldmx::TrigScintTrack &track : TrigScintTracks) {
    histograms_.fill("centroid", track.getCentroid());
    histograms_.fill("residual", track.getResidual());
    histograms_.fill("n_clusters", track.getNclusters());
    histograms_.fill("beamEfrac", track.getBeamEfrac());
    histograms_.fill("x", track.getCentroidX());
    histograms_.fill("y", track.getCentroidY());
    histograms_.fill("z", track.getCentroidZ());
  }
  histograms_.fill("n_tracks", TrigScintTracks.size());
}
References framework::HistogramHelper::fill(), framework::EventProcessor::histograms_, and trackCollectionName_.
configure()
void dqm::TrigScintTrackDQM::configure (framework::config::Parameters & pSet) virtual
Configure the processor using the given user specified parameters.
Parameters
pSet Set of parameters used to configure this processor.
Reimplemented from framework::EventProcessor.
Definition at line 30 of file TrigScintTrackDQM.cxx.
{
  trackCollectionName_ = ps.getParameter<std::string>("track_collection");
  passName_ = ps.getParameter<std::string>("passName").c_str();
  ldmx_log(info) << "In TrigScintTrackDQM::configure, got parameters "
                 << trackCollectionName_ << " and " << passName_;
}
References framework::config::Parameters::getParameter(), and trackCollectionName_.
onProcessStart()
void dqm::TrigScintTrackDQM::onProcessStart () virtual
Method executed before processing of events begins.
Reimplemented from framework::EventProcessor.
Definition at line 11 of file TrigScintTrackDQM.cxx.
{
  getHistoDirectory();
  histograms_.create("centroid", "Track channel centroid", 500, 0, 100);
  histograms_.create(
      "n_tracks", "TrigScint track multiplicity in the pad/event", 25, 0, 25);
  histograms_.create("n_clusters", "N_{clusters} forming the track", 4, 0, 4);
  histograms_.create("residual", "Track residual [channels]", 100, 0., 2.);
  histograms_.create("beamEfrac",
                     "Track edep fraction associated with beam electron", 101,
                     0., 1.01);
  histograms_.create("x", "Track x position", 1000, -100, 100);
  histograms_.create("y", "Track y position", 1000, -100, 100);
  histograms_.create("z", "Track z position", 1000, -900, 100);
  // TODO: implement getting a list of the constructed histograms, to iterate
  // through and set overflow boolean.
}
References framework::HistogramHelper::create(), framework::EventProcessor::getHistoDirectory(), and framework::EventProcessor::histograms_.
Member Data Documentation
passName_
std::string dqm::TrigScintTrackDQM::passName_ {""} private
Definition at line 47 of file TrigScintTrackDQM.h.
trackCollectionName_
std::string dqm::TrigScintTrackDQM::trackCollectionName_ {"TriggerPadTracks"} private
Name of trigger pad track collection.
Definition at line 46 of file TrigScintTrackDQM.h.
Referenced by analyze(), and configure().
The documentation for this class was generated from the following files:
DQM/include/DQM/TrigScintTrackDQM.h
DQM/src/DQM/TrigScintTrackDQM.cxx