LDMX Software: ldmx::SimpleCSVTableProvider Class Reference
ldmx::SimpleCSVTableProvider Class Reference
Classes
struct Entry
Public Member Functions
SimpleCSVTableProvider (const std::string &name, const std::string &tagname, const Parameters &parameters, Process &process)
virtual std::pair< const ConditionsObject *, ConditionsIOV > getCondition (const EventHeader &context)
Public Member Functions inherited from ldmx::ConditionsObjectProvider
ConditionsObjectProvider (const std::string &objname, const std::string &tagname, const Parameters &parameters, Process &process)
virtual ~ConditionsObjectProvider ()
virtual void releaseConditionsObject (const ConditionsObject *co)
virtual void onProcessStart ()
virtual void onProcessEnd ()
virtual void onNewRun (RunHeader &)
const std::string & getConditionObjectName () const
const std::string & getTagName () const
Private Types
enum { OBJ_unknown, OBJ_int, OBJ_double }
Private Member Functions
std::string expandEnv (const std::string &s) const
Private Attributes
enum ldmx::SimpleCSVTableProvider:: { ... } objectType_
std::vector< std::string > columns_
std::vector< Entry > entries_
Additional Inherited Members
Static Public Member Functions inherited from ldmx::ConditionsObjectProvider
static void declare (const std::string &classname, ConditionsObjectProviderMaker *)
Static Public Attributes inherited from ldmx::ConditionsObjectProvider
static const int CLASSTYPE {10}
Protected Member Functions inherited from ldmx::ConditionsObjectProvider
std::pair< const ConditionsObject *, ConditionsIOV > requestParentCondition (const std::string &name, const EventHeader &context)
const Process & process () const
Protected Attributes inherited from ldmx::ConditionsObjectProvider
logging::logger theLog_
The logger for this ConditionsObjectProvider.
Detailed Description
Definition at line 34 of file SimpleCSVTableProvider.h.
Member Function Documentation
expandEnv()
std::string ldmx::SimpleCSVTableProvider::expandEnv (const std::string & s) const private
Utility for expanding environment variables
Definition at line 195 of file SimpleCSVTableProvider.cxx.
{
   std::string retval;
   std::string::size_type j=0;
   for (std::string::size_type i=s.find("${",j); i<s.size(); i=s.find("${",j)) {
     if (i!=j) retval.append(s,j,i-j); // append
     j=s.find("}",i); // look for the end of request
     std::string key=std::string(s,i+2,j-i-2);
     if (key=="LDMX_CONDITION_TAG") retval+=getTagName();
     else {
       const char* cenv=getenv(key.c_str());
       if (cenv!=0) {
         retval+=cenv;
       }
       else {
         // ERROR!
       }
     }
     j++;
   }
   if (j<s.size()) retval.append(s,j);
   //    std::cout << s << "=>" << retval << std::endl;
   return retval;
 }
getCondition()
std::pair< const ConditionsObject *, ConditionsIOV > ldmx::SimpleCSVTableProvider::getCondition (const EventHeader & context) virtual
Pure virtual getCondition function. Must be implemented by any Conditions providers.
Implements ldmx::ConditionsObjectProvider.
Definition at line 219 of file SimpleCSVTableProvider.cxx.
{
   // put the condition tag into the environment for wordexp to use
   setenv("LDMX_CONDITION_TAG",getTagName().c_str(),1);
   for (auto tabledef : entries_) {
     //      std::cout << condition_name << " " << tabledef.objectName_ << " " << tabledef.iov_ << " " << std::endl;
     if (tabledef.iov_.validForEvent(context)) {
       std::string expurl=expandEnv(tabledef.url_);
       //        std::cout << "url:" <<  expurl << " from " << tabledef.url_ << std::endl;
       if (expurl.find("http://")!=std::string::npos) {
         std::string buffer;
         httpstream(expurl,buffer);
         //std::cout <<buffer <<std::endl;
         std::stringstream ss(buffer);
         if (objectType_==OBJ_int) {
           IntegerTableCondition* table=new IntegerTableCondition(getConditionObjectName(),columns_);
           ldmx::utility::SimpleTableStreamerCSV::load(*table,ss);
           return std::pair<const ConditionsObject*,ConditionsIOV>(table,tabledef.iov_);
         } else if (objectType_==OBJ_double) {
           DoubleTableCondition* table=new DoubleTableCondition(getConditionObjectName(),columns_);
           ldmx::utility::SimpleTableStreamerCSV::load(*table,ss);
           return std::pair<const ConditionsObject*,ConditionsIOV>(table,tabledef.iov_);
         }
       } else if (expurl.find("file://")!=std::string::npos || expurl.find(":")==std::string::npos) {
         std::string fname(expurl);
         if (expurl.find("file://")!=std::string::npos) fname=expurl.substr(expurl.find("file://")+strlen("file://"));
         std::ifstream fs(fname);
         if (!fs.good()) {
           EXCEPTION_RAISE("ConditionsException","Unable to open CSV file '"+fname+"'");
         }
         if (objectType_==OBJ_int) {
           IntegerTableCondition* table=new IntegerTableCondition(getConditionObjectName(),columns_);
           ldmx::utility::SimpleTableStreamerCSV::load(*table,fs);
           return std::pair<const ConditionsObject*,ConditionsIOV>(table,tabledef.iov_);
         } else if (objectType_==OBJ_double) {
           DoubleTableCondition* table=new DoubleTableCondition(getConditionObjectName(),columns_);
           ldmx::utility::SimpleTableStreamerCSV::load(*table,fs);
           return std::pair<const ConditionsObject*,ConditionsIOV>(table,tabledef.iov_);
         }
       } else if (expurl=="python:") {
         // here we just copy values...
         if (objectType_==OBJ_int) {
           IntegerTableCondition* table=new IntegerTableCondition(getConditionObjectName(),columns_);
           table->setIdMask(0); // all ids are the same...
           table->add(0,tabledef.ivalues_);
           return std::pair<const ConditionsObject*,ConditionsIOV>(table,tabledef.iov_);
         } else if (objectType_==OBJ_double) {
           DoubleTableCondition* table=new DoubleTableCondition(getConditionObjectName(),columns_);
           table->setIdMask(0); // all ids are the same...
           table->add(0,tabledef.dvalues_);
           return std::pair<const ConditionsObject*,ConditionsIOV>(table,tabledef.iov_);
         }
       }
     }
   }
   return std::pair<const ConditionsObject*,ConditionsIOV>(0,ConditionsIOV());
 }
References ldmx::HomogenousTableCondition< T >::add(), ldmx::utility::SimpleTableStreamerCSV::load(), and ldmx::BaseTableCondition::setIdMask().
The documentation for this class was generated from the following files:
Conditions/include/Conditions/SimpleCSVTableProvider.h
Conditions/src/SimpleCSVTableProvider.cxx