LDMX Software: ldmx::EcalTriggerID Class Reference
ldmx::EcalTriggerID Class Reference
Extension of DetectorID providing access to ECal trigger cell information.
#include <EcalTriggerID.h>
Public Member Functions
EcalTriggerID ()
EcalTriggerID (RawValue rawid)
EcalTriggerID (const DetectorID id)
EcalTriggerID (unsigned int layer, unsigned int module, unsigned int cell)
int module () const
int getModuleID () const
int layer () const
int getLayerID () const
int triggercell () const
int getTriggerCellID () const
std::pair< unsigned int, unsigned int > getCellUV () const
Public Member Functions inherited from ldmx::EcalAbstractID
EcalAbstractID ()
EcalAbstractID (RawValue rawid)
EcalAbstractID (const DetectorID id)
EcalAbstractID (unsigned int cell_type, unsigned int payload)
int cell_type () const
Public Member Functions inherited from ldmx::DetectorID
DetectorID ()
Class constructor for a null DetectorID.
DetectorID (RawValue rawid)
Class constructor from a raw 32-bit integer.
DetectorID (SubdetectorIDType sdtype, RawValue raw_subpayload)
bool null () const
SubdetectorIDType subdet () const
RawValue raw () const
void setRawValue (RawValue rawValue)
bool operator< (const DetectorID &id) const
bool operator== (const DetectorID &id) const
bool operator!= (const DetectorID &id) const
Static Public Member Functions
static void createInterpreters ()
Static Public Attributes
static const RawValue LAYER_MASK {0x3F}
static const RawValue LAYER_SHIFT {12}
static const RawValue MODULE_MASK {0x1F}
static const RawValue MODULE_SHIFT {7}
static const RawValue CELL_MASK {0x7F}
static const RawValue CELL_SHIFT {0}
Static Public Attributes inherited from ldmx::EcalAbstractID
static const RawValue CELL_TYPE_MASK {0x7}
static const RawValue CELL_TYPE_SHIFT {23}
static const RawValue ECAL_PAYLOAD_MASK {0x007FFFFF}
Static Public Attributes inherited from ldmx::DetectorID
static const RawValue SUBDETECTORID_MASK {0x3F}
static const RawValue SUBDETECTORID_SHIFT {26}
static const RawValue SUBDETECTOR_PAYLOAD_MASK {0x3FFFFFFF}
Additional Inherited Members
Public Types inherited from ldmx::EcalAbstractID
enum EcalCellType { PrecisionGlobal = 0, PrecisionLocal = 1, TriggerCell = 2, Special = 7 }
Public Types inherited from ldmx::DetectorID
typedef uint32_t RawValue
Protected Attributes inherited from ldmx::DetectorID
RawValue id_
The raw, packed value of the ID.
Detailed Description
Extension of DetectorID providing access to ECal trigger cell information.
Definition at line 19 of file EcalTriggerID.h.
Constructor & Destructor Documentation
EcalTriggerID() [1/4]
ldmx::EcalTriggerID::EcalTriggerID () inline
Empty ECAL id (but not null!)
Definition at line 33 of file EcalTriggerID.h.
 : EcalAbstractID() { }
EcalTriggerID() [2/4]
ldmx::EcalTriggerID::EcalTriggerID (RawValue rawid) inline
Create from raw number
Definition at line 38 of file EcalTriggerID.h.
                                   : EcalAbstractID(rawid) {
       if (!null() && cell_type()!=TriggerCell) {
         EXCEPTION_RAISE("DetectorIDMismatch","Attempted to create EcalTriggerID from mismatched Ecal cell_type "+std::to_string(cell_type()));
       }
     }
References ldmx::EcalAbstractID::cell_type().
EcalTriggerID() [3/4]
ldmx::EcalTriggerID::EcalTriggerID (const DetectorID id) inline
Create from a DetectorID, but check
Definition at line 47 of file EcalTriggerID.h.
                                        : EcalAbstractID(id) {
       if (!null() && cell_type()!=TriggerCell) {
         EXCEPTION_RAISE("DetectorIDMismatch","Attempted to create EcalTriggerID from mismatched Ecal cell_type "+std::to_string(cell_type()));
       }
     }
References ldmx::EcalAbstractID::cell_type().
EcalTriggerID() [4/4]
ldmx::EcalTriggerID::EcalTriggerID (unsigned int layer, unsigned int module, unsigned int cell) inline
Create from pieces
Definition at line 57 of file EcalTriggerID.h.
                                                                               : EcalAbstractID(TriggerCell,0) {
         id_|=(layer&LAYER_MASK)<<LAYER_SHIFT;
         id_|=(module&MODULE_MASK)<<MODULE_SHIFT;
         id_|=(cell&CELL_MASK)<<CELL_SHIFT;
     }
References ldmx::DetectorID::id_, layer(), and module().
Member Function Documentation
getCellUV()
std::pair<unsigned int,unsigned int> ldmx::EcalTriggerID::getCellUV () const
Get the cell u,v index assuming a CMS-standard 432-cell sensor
Returns
Pair providing a U/V index
getLayerID()
int ldmx::EcalTriggerID::getLayerID () const inline
Get the value of the layer field from the ID.
Returns
The value of the layer field.
Definition at line 91 of file EcalTriggerID.h.
{
         return (id_>>LAYER_SHIFT) & LAYER_MASK;
     }
References ldmx::DetectorID::id_.
getModuleID()
int ldmx::EcalTriggerID::getModuleID () const inline
Get the value of the module field from the ID.
Returns
The value of the module field.
Definition at line 75 of file EcalTriggerID.h.
{
         return (id_>>MODULE_SHIFT) & MODULE_MASK;
     }
References ldmx::DetectorID::id_.
getTriggerCellID()
int ldmx::EcalTriggerID::getTriggerCellID () const inline
Get the value of the trigger cell field from the ID.
Returns
The value of the cell field.
Definition at line 107 of file EcalTriggerID.h.
{
         return (id_>>CELL_SHIFT)&CELL_MASK;
     }
References ldmx::DetectorID::id_.
layer()
int ldmx::EcalTriggerID::layer () const inline
Get the value of the layer field from the ID.
Returns
The value of the layer field.
Definition at line 83 of file EcalTriggerID.h.
                       {
         return (id_>>LAYER_SHIFT) & LAYER_MASK;
     }
References ldmx::DetectorID::id_.
Referenced by ldmx::EcalTriggerGeometry::centerInTriggerCell(), ldmx::EcalTriggerGeometry::contentsOfTriggerCell(), and EcalTriggerID().
module()
int ldmx::EcalTriggerID::module () const inline
Get the value of the module field from the ID.
Returns
The value of the module field.
Definition at line 67 of file EcalTriggerID.h.
{
         return (id_>>MODULE_SHIFT) & MODULE_MASK;
     }
References ldmx::DetectorID::id_.
Referenced by ldmx::EcalTriggerGeometry::centerInTriggerCell(), ldmx::EcalTriggerGeometry::contentsOfTriggerCell(), and EcalTriggerID().
triggercell()
int ldmx::EcalTriggerID::triggercell () const inline
Get the value of the trigger cell field from the ID.
Returns
The value of the cell field.
Definition at line 99 of file EcalTriggerID.h.
{
         return (id_>>CELL_SHIFT)&CELL_MASK;
     }
References ldmx::DetectorID::id_.
Referenced by ldmx::EcalTriggerGeometry::centerInTriggerCell(), and ldmx::EcalTriggerGeometry::contentsOfTriggerCell().
The documentation for this class was generated from the following files:
DetDescr/include/DetDescr/EcalTriggerID.h
DetDescr/src/DetDescr/EcalTriggerID.cxx