LDMX Software: recon::MyProcessor Class Reference
recon::MyProcessor Class Reference
#include <MyProcessor.h>
Public Member Functions
MyProcessor (const std::string &name, framework::Process &process)
~MyProcessor ()
Destructor.
void configure (framework::config::Parameters &parameters) final override
void produce (framework::Event &event)
Public Member Functions inherited from framework::Producer
Producer (const std::string &name, Process &process)
virtual void produce (Event &event)=0
virtual void beforeNewRun (ldmx::RunHeader &header)
Public Member Functions inherited from framework::EventProcessor
EventProcessor (const std::string &name, Process &process)
virtual ~EventProcessor ()
virtual void configure (framework::config::Parameters &parameters)
virtual void onNewRun (const ldmx::RunHeader &runHeader)
virtual void onFileOpen (EventFile &eventFile)
virtual void onFileClose (EventFile &eventFile)
virtual void onProcessStart ()
virtual void onProcessEnd ()
template<class T >
const T & getCondition (const std::string &condition_name)
TDirectory * getHistoDirectory ()
void setStorageHint (framework::StorageControlHint hint)
void setStorageHint (framework::StorageControlHint hint, const std::string &purposeString)
int getLogFrequency () const
int getRunNumber () const
std::string getName () const
void createHistograms (const std::vector< framework::config::Parameters > &histos)
Additional Inherited Members
Static Public Member Functions inherited from framework::EventProcessor
static void declare (const std::string &classname, int classtype, EventProcessorMaker *)
Static Public Attributes inherited from framework::Producer
static const int CLASSTYPE {1}
Protected Member Functions inherited from framework::EventProcessor
void abortEvent ()
Protected Attributes inherited from framework::EventProcessor
HistogramHelper histograms_
Interface class for making and filling histograms.
NtupleManager & ntuple_ {NtupleManager::getInstance()}
Manager for any ntuples.
logging::logger theLog_
The logger for this EventProcessor.
Detailed Description
Minimal example of a processor.
This processor will loop over all of the ECal hits in an event and print out their details.
Definition at line 20 of file MyProcessor.h.
Constructor & Destructor Documentation
MyProcessor()
recon::MyProcessor::MyProcessor (const std::string & name, framework::Process & process)
Constructor.
Parameters
name Name for this instance of the class.
process The Process class associated with EventProcessor, provided by the framework.
Definition at line 6 of file MyProcessor.cxx.
    : framework::Producer(name, process) {}
~MyProcessor()
recon::MyProcessor::~MyProcessor ()
Destructor.
Definition at line 9 of file MyProcessor.cxx.
{}
Member Function Documentation
configure()
void recon::MyProcessor::configure (framework::config::Parameters & parameters) final override virtual
Configure the processor using the given user specified parameters.
The user specified parameters that are availabed are defined in the python configuration class. Look at the my_processor.py module of the EventProc python for the python structure.
Parameters
parameters Set of parameters used to configure this processor.
You access configuration parameters set in the python by asking for the parameter with the same name as the python member variable.
Reimplemented from framework::EventProcessor.
Definition at line 11 of file MyProcessor.cxx.
{
  int my_parameter = parameters.getParameter<int>("my_parameter");
  std::cout << "MyProcessor has my_parameter = " << my_parameter << std::endl;
}
References framework::config::Parameters::getParameter().
produce()
void recon::MyProcessor::produce (framework::Event & event) virtual
Process the event and put new data products into it.
Parameters
event The event to process.
Implements framework::Producer.
Definition at line 23 of file MyProcessor.cxx.
{
  // Check if the collection of reconstructed ECal hits exist.  If not,
  // don't bother processing the event.
  if (!event.exists("EcalRecHits")) return;
  // Get the collection of digitized ECal hits from the event
  const std::vector<ldmx::EcalHit> hits =
      event.getCollection<ldmx::EcalHit>("EcalRecHits");
  // Loop over the collection of hits and print the hit details
  for (const ldmx::EcalHit &hit : hits) {
    // Print the hit
    hit.Print();
  }
}
References framework::Event::exists(), and ldmx::EcalHit::Print().
The documentation for this class was generated from the following files:
Recon/include/Recon/Examples/MyProcessor.h
Recon/src/Recon/Examples/MyProcessor.cxx