LDMX Software: ldmx::EcalRecProducer Class Reference
ldmx::EcalRecProducer Class Reference
Performs basic ECal reconstruction.
#include <EcalRecProducer.h>
Public Member Functions
EcalRecProducer (const std::string &name, Process &process)
virtual ~EcalRecProducer ()
virtual void configure (Parameters &)
virtual void produce (Event &event)
Public Member Functions inherited from ldmx::Producer
Producer (const std::string &name, Process &process)
Public Member Functions inherited from ldmx::EventProcessor
EventProcessor (const std::string &name, Process &process)
virtual ~EventProcessor ()
virtual void onNewRun (const RunHeader &runHeader)
virtual void onFileOpen (EventFile &eventFile)
virtual void onFileClose (EventFile &eventFile)
virtual void onProcessStart ()
virtual void onProcessEnd ()
TDirectory * getHistoDirectory ()
void setStorageHint (ldmx::StorageControlHint hint)
void setStorageHint (ldmx::StorageControlHint hint, const std::string &purposeString)
void createHistograms (const std::vector< Parameters > &histos)
Private Member Functions
double convertTOT (const int tot) const
Private Attributes
std::string digiCollName_
std::string digiPassName_
std::vector< double > layerWeights_
double secondOrderEnergyCorrection_
EcalDetectorID detID_
std::unique_ptr< EcalHexReadout > ecalHexReadout_
Static Private Attributes
static const double MIP_SI_RESPONSE = 0.130
Additional Inherited Members
Static Public Member Functions inherited from ldmx::EventProcessor
static void declare (const std::string &classname, int classtype, EventProcessorMaker *)
Static Public Attributes inherited from ldmx::Producer
static const int CLASSTYPE {1}
Protected Member Functions inherited from ldmx::EventProcessor
void abortEvent ()
Protected Attributes inherited from ldmx::EventProcessor
Process & process_
HistogramHelper histograms_
Interface class for making and filling histograms.
NtupleManager & ntuple_ {NtupleManager::getInstance()}
Manager for any ntuples.
Detailed Description
Performs basic ECal reconstruction.
Reconstruction is done from the EcalDigi samples. Some hard-coded parameters are used for position and energy calculation.
Definition at line 42 of file EcalRecProducer.h.
Constructor & Destructor Documentation
EcalRecProducer()
ldmx::EcalRecProducer::EcalRecProducer (const std::string & name, Process & process)
Constructor
Definition at line 13 of file EcalRecProducer.cxx.
                                                                             :
         Producer(name, process) {
     }
~EcalRecProducer()
ldmx::EcalRecProducer::~EcalRecProducer () virtual
Destructor Deletes hanging pointers if they exist
Definition at line 17 of file EcalRecProducer.cxx.
 { }
Member Function Documentation
configure()
void ldmx::EcalRecProducer::configure (Parameters & ps) virtual
Grabs configure parameters from the python config file.
Parameter Default digiCollName EcalDigis digiPassName "" <– blank means take any pass if only one collection exists layerWeights DEFAULT_LAYER_WEIGHTS secondOrderEnergyCorrection DEFAULT_SECOND_ORDER_ENERGY_CORRECTION
Reimplemented from ldmx::EventProcessor.
Definition at line 19 of file EcalRecProducer.cxx.
{
         digiCollName_ = ps.getParameter<std::string>( "digiCollName" );
         digiPassName_ = ps.getParameter<std::string>( "digiPassName" );
         layerWeights_ = ps.getParameter<std::vector<double>>( "layerWeights" );
         secondOrderEnergyCorrection_ = ps.getParameter<double>( "secondOrderEnergyCorrection" );
         //if changing Ecal geometry, input geometry parameters here
         //  module radius - center-to-flat radius of a module in mm
         //  num cells wide - number of cells in center horizontal row
         //  gap between modules - air gap between adjacent flat edges of module
         //  z-position of front face of ECal [mm]
         //  list of positions of sensitive layers relative to front of ECal [mm]
         // These are the v12 parameters
         //  all distances in mm
         double moduleRadius = 85.0; //same as default
         int    numCellsWide = 23; //same as default
         double moduleGap = 1.0;
         double ecalFrontZ = 220;
         std::vector<double> ecalSensLayersZ = {
              7.850,
             13.300,
             26.400,
             33.500,
             47.950,
             56.550,
             72.250,
             81.350,
             97.050,
             106.150,
             121.850,
             130.950,
             146.650,
             155.750,
             171.450,
             180.550,
             196.250,
             205.350,
             221.050,
             230.150,
             245.850,
             254.950,
             270.650,
             279.750,
             298.950,
             311.550,
             330.750,
             343.350,
             362.550,
             375.150,
             394.350,
             406.950,
             426.150,
             438.750
         };
         ecalHexReadout_ = std::make_unique<EcalHexReadout>(
                 moduleRadius,
                 moduleGap,
                 numCellsWide,
                 ecalSensLayersZ,
                 ecalFrontZ
                 );
     }
References digiCollName_, digiPassName_, ecalHexReadout_, ldmx::Parameters::getParameter(), layerWeights_, and secondOrderEnergyCorrection_.
Referenced by TEST_CASE().
convertTOT()
double ldmx::EcalRecProducer::convertTOT (const int tot) const private
Convert TOT from digis to a reconstructed energy deposited in the Silicon.
We construct this conversion by fitting the plot of TOT vs Sim Energy Dep. The choice of fit and different scalings pre- or post- fit may have a large effect and should be studied.
Parameters
tot tot to convert
Returns
converted silicon energy
Fit retrieved from a SimEDep vs TOT plot. NOT physically motivated, will need to investigate further.
Fit (for TOT > 3000): Function: expo ==> exp([0]+[1]*x) EDM=1.27359e-07 STRATEGY= 1 ERROR MATRIX ACCURATE EXT PARAMETER STEP FIRST
NO. NAME VALUE ERROR SIZE DERIVATIVE 1 Constant -1.36729e+01 1.91947e-03 3.15252e-05 -6.27332e-01 2 Slope 2.41246e-03 3.53378e-07 5.80385e-09 -1.99549e+03 Roughly flattens out (within uncertainty) to ~5e-2MeV when TOT < 3000
For TOT < 3000: Just assume a linear line from (0,0) to (3000, 1e-2) This is discontinuous!
Definition at line 154 of file EcalRecProducer.cxx.
{
         if ( tot > 3000 ) return exp( -1.36729e1 + 2.41246e-3*tot );
         return (1e-2/3000)*tot;
     }
Referenced by produce().
produce()
void ldmx::EcalRecProducer::produce (Event & event) virtual
Produce EcalHits and put them into the event bus using the EcalDigis as input.
Implements ldmx::Producer.
Definition at line 86 of file EcalRecProducer.cxx.
{
         std::vector<EcalHit> ecalRecHits;
         EcalDigiCollection ecalDigis = event.getObject<EcalDigiCollection>( digiCollName_ , digiPassName_ );
         int numDigiHits = ecalDigis.getNumDigis();
         //loop through digis
         for ( unsigned int iDigi = 0; iDigi < numDigiHits; iDigi++ ) {
             //Right now, hard-coded to only use one sample in EcalDigiProducer
             //TODO: expand to multiple samples per digi
             EcalDigiSample sample = (ecalDigis.getDigi( iDigi )).at(0);
             int rawID = sample.rawID_;
             //ID to real space position
             double x,y,z;
             ecalHexReadout_->getCellAbsolutePosition( rawID , x , y , z );
             //get energy and time estimate from digi information
             double siEnergy, hitTime;
             //TODO: Energy estimate from N samples can (and should be) refined
             //TOA is the time of arrival with respect to the 25ns clock window
             double timeRelClock25 = sample.toa_*(25./1024); //ns
             hitTime = timeRelClock25;
             //ADC - voltage measurement at a specific time of the pulse
             // Pulse Shape:
             //  p[0]/(1.0+exp(p[1](t-p[2]+p[3]-p[4])))/(1.0+exp(p[5]*(t-p[6]+p[3]-p[4])))
             //  p[0] = amplitude to be fit (TBD)
             //  p[1] = -0.345 shape parameter - rate of up slope
             //  p[2] = 70.6547 shape parameter - time of up slope relative to shape fit
             //  p[3] = 77.732 shape parameter - time of peak relative to shape fit
             //  p[4] = peak time to be fit (TBD)
             //  p[5] = 0.140068 shape parameter - rate of down slope
             //  p[6] = 87.7649 shape paramter - time of down slope relative to shape fit
             //These measurements can be used to fit the pulse shape if TOT is not available
             //TOT - number of clock ticks that pulse was over threshold
             //  this is related to the amplitude of the pulse through some convoluted relation using the pulse shape
             //  the amplitude of the pulse is related to the energy deposited
             //  TODO actually have mutliple samples instead of having adc_t_ count number of samples over threshold
             siEnergy = convertTOT( sample.adc_t_*1024 + sample.tot_ );
             //printf( "%6d Clocks and %6d tot --> %6.2f MeV\n" , sample.adc_t_ , sample.tot_ , siEnergy );
             //incorporate layer weights
             detID_.setRawValue( rawID );
             detID_.unpack();
             int layer = detID_.getLayerID();
             double recHitEnergy =
                 ( (siEnergy / MIP_SI_RESPONSE)*layerWeights_.at(layer)+siEnergy )*secondOrderEnergyCorrection_;
             //copy over information to rec hit structure in new collection
             EcalHit recHit;
             recHit.setID( rawID );
             recHit.setXPos( x );
             recHit.setYPos( y );
             recHit.setZPos( z );
             recHit.setAmplitude( siEnergy );
             recHit.setEnergy( recHitEnergy );
             recHit.setTime( hitTime );
             ecalRecHits.push_back( recHit );
         }
         //add collection to event bus
         event.add( "EcalRecHits", ecalRecHits );
     }
References ldmx::EcalDigiSample::adc_t_, convertTOT(), detID_, digiCollName_, digiPassName_, ecalHexReadout_, ldmx::EcalDigiCollection::getDigi(), ldmx::DefaultDetectorID::getLayerID(), ldmx::EcalDigiCollection::getNumDigis(), layerWeights_, MIP_SI_RESPONSE, ldmx::EcalDigiSample::rawID_, secondOrderEnergyCorrection_, ldmx::CalorimeterHit::setAmplitude(), ldmx::CalorimeterHit::setEnergy(), ldmx::CalorimeterHit::setID(), ldmx::DetectorID::setRawValue(), ldmx::CalorimeterHit::setTime(), ldmx::CalorimeterHit::setXPos(), ldmx::CalorimeterHit::setYPos(), ldmx::CalorimeterHit::setZPos(), ldmx::EcalDigiSample::toa_, ldmx::EcalDigiSample::tot_, and ldmx::DetectorID::unpack().
Referenced by TEST_CASE().
Member Data Documentation
detID_
EcalDetectorID ldmx::EcalRecProducer::detID_ private
Helper Instance of EcalDetectorID: used to translate the raw ID to layer, module, cell IDs
Definition at line 119 of file EcalRecProducer.h.
Referenced by produce().
digiCollName_
std::string ldmx::EcalRecProducer::digiCollName_ private
Digi Collection Name to use as input
Definition at line 90 of file EcalRecProducer.h.
Referenced by configure(), and produce().
digiPassName_
std::string ldmx::EcalRecProducer::digiPassName_ private
Digi Pass Name to use as input
Definition at line 93 of file EcalRecProducer.h.
Referenced by configure(), and produce().
ecalHexReadout_
std::unique_ptr<EcalHexReadout> ldmx::EcalRecProducer::ecalHexReadout_ private
Helper Instance of EcalHexReadout: performs real space x,y postion <-> module,cell ID translation
Definition at line 125 of file EcalRecProducer.h.
Referenced by configure(), and produce().
layerWeights_
std::vector<double> ldmx::EcalRecProducer::layerWeights_ private
Layer Weights to use for this reconstruction
Layer weights account for the energy lost in the absorber directly in front of the Silicon layer where the measured energy was deposited. These are determined by calculating the average amount of energy lost by a MIP passing through the extra material between sensitive layers.
Definition at line 103 of file EcalRecProducer.h.
Referenced by configure(), and produce().
MIP_SI_RESPONSE
const double ldmx::EcalRecProducer::MIP_SI_RESPONSE = 0.130 static private
Approximate energy deposited in Silicon layer for a MIP hit MeV
Definition at line 131 of file EcalRecProducer.h.
Referenced by produce().
secondOrderEnergyCorrection_
double ldmx::EcalRecProducer::secondOrderEnergyCorrection_ private
Second Order Energy Correction to use for this reconstruction
This is a shift applied to all of the energies in order to have the mean of the total energy deposited in the ECal be accurate. This is less physically motivated than the layer weights and is more of a calibration number.
Definition at line 113 of file EcalRecProducer.h.
Referenced by configure(), and produce().
The documentation for this class was generated from the following files:
Ecal/include/Ecal/EcalRecProducer.h
Ecal/src/EcalRecProducer.cxx