LDMX Software: ldmx::SimSpecialID Class Reference
ldmx::SimSpecialID Class Reference
Implements detector ids for special simulation-derived hits like scoring planes.
#include <SimSpecialID.h>
Public Types
enum SimSpecialType { SCORING_PLANE = 1 }
Public Types inherited from ldmx::DetectorID
typedef uint32_t RawValue
Public Member Functions
SimSpecialID ()
SimSpecialID (RawValue rawid)
SimSpecialID (const DetectorID id)
SimSpecialID (SimSpecialType sst, RawValue rawfield)
SimSpecialType getSubtype () const
int plane () const
RawValue subtypePayload () const
Public Member Functions inherited from ldmx::DetectorID
DetectorID ()
Class constructor for a null DetectorID.
DetectorID (RawValue rawid)
Class constructor from a raw 32-bit integer.
DetectorID (SubdetectorIDType sdtype, RawValue raw_subpayload)
bool null () const
SubdetectorIDType subdet () const
RawValue raw () const
void setRawValue (RawValue rawValue)
bool operator< (const DetectorID &id) const
bool operator== (const DetectorID &id) const
bool operator!= (const DetectorID &id) const
Static Public Member Functions
static SimSpecialID ScoringPlaneID (int plane)
static void createInterpreters ()
Static Public Attributes
static const RawValue SUBTYPE_MASK {0xF}
static const RawValue SUBTYPE_SHIFT {22}
static const RawValue SUBTYPE_DATA_MASK {0x3FFFFF}
static const RawValue PLANE_MASK
static const RawValue PLANE_SHIFT {0}
Static Public Attributes inherited from ldmx::DetectorID
static const RawValue SUBDETECTORID_MASK {0x3F}
static const RawValue SUBDETECTORID_SHIFT {26}
static const RawValue SUBDETECTOR_PAYLOAD_MASK {0x3FFFFFFF}
Additional Inherited Members
Protected Attributes inherited from ldmx::DetectorID
RawValue id_
The raw, packed value of the ID.
Detailed Description
Implements detector ids for special simulation-derived hits like scoring planes.
Definition at line 15 of file SimSpecialID.h.
Member Enumeration Documentation
SimSpecialType
enum ldmx::SimSpecialID::SimSpecialType
Encodes which of several possible special types this SimSpecial ID is
Definition at line 20 of file SimSpecialID.h.
{ SCORING_PLANE = 1 };
Constructor & Destructor Documentation
SimSpecialID() [1/4]
ldmx::SimSpecialID::SimSpecialID () inline
Empty id (but not null!)
Definition at line 34 of file SimSpecialID.h.
: DetectorID(SD_SIM_SPECIAL, 0) {}
Referenced by ScoringPlaneID().
SimSpecialID() [2/4]
ldmx::SimSpecialID::SimSpecialID (RawValue rawid) inline
Create from raw number
Definition at line 39 of file SimSpecialID.h.
                               : DetectorID(rawid) {
    SUBDETECTORID_TEST("SimSpecialID", SD_SIM_SPECIAL);
  }
SimSpecialID() [3/4]
ldmx::SimSpecialID::SimSpecialID (const DetectorID id) inline
Create from a DetectorID, but check
Definition at line 46 of file SimSpecialID.h.
                                    : DetectorID(id) {
    SUBDETECTORID_TEST("SimSpecialID", SD_SIM_SPECIAL);
  }
SimSpecialID() [4/4]
ldmx::SimSpecialID::SimSpecialID (SimSpecialType sst, RawValue rawfield) inline
Create from a subtype number and raw field
Definition at line 53 of file SimSpecialID.h.
      : DetectorID(SD_SIM_SPECIAL, 0) {
    id_ |= ((sst & SUBTYPE_MASK) << SUBTYPE_SHIFT);
    id_ |= rawfield & SUBTYPE_DATA_MASK;
  }
References ldmx::DetectorID::id_.
Member Function Documentation
createInterpreters()
void ldmx::SimSpecialID::createInterpreters () static
Definition at line 15 of file SimSpecialID.cxx.
{
  IDField::IDFieldList fields;
  fields.push_back(new IDField("subdetector", 0, SUBDETECTORID_SHIFT, 31));
  fields.push_back(
      new IDField("subtype", 1, SUBTYPE_SHIFT,
                  SUBTYPE_SHIFT + IDField::countOnes(SUBTYPE_MASK) - 1));
  fields.push_back(
      new IDField("payload", 2, 0, IDField::countOnes(SUBTYPE_DATA_MASK) - 1));
  DetectorIDInterpreter::registerInterpreter(SD_SIM_SPECIAL, fields);
}
getSubtype()
SimSpecialType ldmx::SimSpecialID::getSubtype () const inline
Definition at line 70 of file SimSpecialID.h.
{
    return SimSpecialType((id_ >> SUBTYPE_SHIFT) & SUBTYPE_MASK);
  }
plane()
int ldmx::SimSpecialID::plane () const inline
Get the value of the plane field from the ID, if it is a scoring plane.
Returns
The value of the plane field or -1 if not a scoring plane
Definition at line 78 of file SimSpecialID.h.
                    {
    return (getSubtype() == SCORING_PLANE) ? ((id_ >> PLANE_SHIFT) & PLANE_MASK)
                                           : (-1);
  }
References ldmx::DetectorID::id_.
Referenced by ecal::EcalVetoProcessor::produce(), ScoringPlaneID(), and TEST_CASE().
ScoringPlaneID()
static SimSpecialID ldmx::SimSpecialID::ScoringPlaneID (int plane) inline static
Create a scoring id from pieces
Definition at line 62 of file SimSpecialID.h.
{
    return SimSpecialID(SCORING_PLANE, (plane & PLANE_MASK) << PLANE_SHIFT);
  }
References plane(), and SimSpecialID().
Referenced by simcore::ScoringPlaneSD::ProcessHits().
subtypePayload()
RawValue ldmx::SimSpecialID::subtypePayload () const inline
Get the raw payload contents
Definition at line 86 of file SimSpecialID.h.
{ return id_ & SUBTYPE_DATA_MASK; }
References ldmx::DetectorID::id_.
Referenced by TEST_CASE().
Member Data Documentation
PLANE_MASK
const RawValue ldmx::SimSpecialID::PLANE_MASK static
Initial value:
{
      0xFFF}
Definition at line 27 of file SimSpecialID.h.
PLANE_SHIFT
const RawValue ldmx::SimSpecialID::PLANE_SHIFT {0} static
Definition at line 29 of file SimSpecialID.h.
SUBTYPE_DATA_MASK
const RawValue ldmx::SimSpecialID::SUBTYPE_DATA_MASK {0x3FFFFF} static
Definition at line 24 of file SimSpecialID.h.
SUBTYPE_MASK
const RawValue ldmx::SimSpecialID::SUBTYPE_MASK {0xF} static
Definition at line 22 of file SimSpecialID.h.
SUBTYPE_SHIFT
const RawValue ldmx::SimSpecialID::SUBTYPE_SHIFT {22} static
Definition at line 23 of file SimSpecialID.h.
The documentation for this class was generated from the following files:
DetDescr/include/DetDescr/SimSpecialID.h
DetDescr/src/DetDescr/SimSpecialID.cxx