LDMX Software: framework::NtupleManager Class Reference
framework::NtupleManager Class Reference
Singleton class used to manage the creation and pooling of ntuples.
#include <NtupleManager.h>
Public Member Functions
void create (const std::string &tname)
template<typename VarType >
void addVar (const std::string &tname, const std::string &vname)
template<typename T >
void setVar (const std::string &vname, const T &value)
void fill ()
void clear ()
Reset all of the variables to their limits.
void reset ()
NtupleManager (const NtupleManager &)=delete
Hide Copy Constructor.
void operator= (const NtupleManager &)=delete
Hide Assignment Operator.
Static Public Member Functions
static NtupleManager & getInstance ()
Private Member Functions
NtupleManager ()
Private constructor to prevent instantiation.
Private Attributes
std::unordered_map< std::string, TTree * > trees_
Container for output ROOT trees.
framework::Bus bus_
Container for buffering variables.
Detailed Description
Singleton class used to manage the creation and pooling of ntuples.
See also
framework::Bus Similar to the Event bus itself, we use the Bus to buffer the variable values and attach them to their output TTrees. Unlike the event bus, we don't implement retrieval mechanisms for reading these values.
Definition at line 36 of file NtupleManager.h.
Constructor & Destructor Documentation
NtupleManager()
framework::NtupleManager::NtupleManager () private
Private constructor to prevent instantiation.
Definition at line 6 of file NtupleManager.cxx.
{}
Member Function Documentation
addVar()
template<typename VarType > void framework::NtupleManager::addVar (const std::string & tname, const std::string & vname) inline
Add a variable of type VarType to the ROOT tree with name 'tname'. If the variable already exists in any tree or the requested tree does not exists, an exception is thrown.
Template Parameters
in] VarType type of variable to add to the tree
Parameters
[in] tname Name of the tree to add the variable to.
[in] vname Name of the variable to add to the tree
Exceptions
Exception if tree doesn't exist or variable already does
Definition at line 58 of file NtupleManager.h.
{
    // Check if a tree named 'tname' has already been created.  If
    // not, throw an exception.
    if (trees_.count(tname) == 0)
      EXCEPTION_RAISE("NtupleManager", "A tree with name " + tname +
                                           " has not been been created.");
    // Check if the variable exists in the map. If it does, throw
    // an exception.
    if (bus_.isOnBoard(vname)) {
      EXCEPTION_RAISE("NtupleManager", "A variable with name " + vname +
                                           " has already been defined.");
    }
    // Board the bus
    bus_.board<VarType>(vname);
    // Attach the tree to the bus
    bus_.attach(trees_[tname], vname, true);
  }
References framework::Bus::attach(), framework::Bus::board(), bus_, framework::Bus::isOnBoard(), and trees_.
Referenced by dqm::NtuplizeDarkBremInteraction::onProcessStart(), ecal::test::EcalCheckEnergyReconstruction::onProcessStart(), and hcal::test::HcalCheckReconstruction::onProcessStart().
clear()
void framework::NtupleManager::clear ()
Reset all of the variables to their limits.
Definition at line 30 of file NtupleManager.cxx.
{ bus_.clear(); }
References bus_, and framework::Bus::clear().
Referenced by framework::Process::run().
create()
void framework::NtupleManager::create (const std::string & tname)
Create a ROOT tree to hold the ntuple variables (ROOT leaves).
Parameters
name Name of the tree.
Definition at line 14 of file NtupleManager.cxx.
{
  // Check if a tree named 'name' has already been created.  If so
  // throw an exception.
  if (trees_.count(name) != 0)
    EXCEPTION_RAISE("NtupleManager",
                    "A tree with name " + name + " has already been created.");
  // Create a tree with the given name and add it to the list of trees.
  trees_[name] = new TTree{name.c_str(), name.c_str()};
}
References trees_.
Referenced by dqm::NtuplizeDarkBremInteraction::onProcessStart(), ecal::test::EcalCheckEnergyReconstruction::onProcessStart(), and hcal::test::HcalCheckReconstruction::onProcessStart().
fill()
void framework::NtupleManager::fill ()
Definition at line 25 of file NtupleManager.cxx.
{
  // Loop over all the trees and fill them
  for (const auto& [name, tree]: trees_) tree->Fill();
}
getInstance()
NtupleManager & framework::NtupleManager::getInstance () static
Returns
The NtupleManager instance
Definition at line 8 of file NtupleManager.cxx.
{
  // Create an instance of the NtupleManager if needed
  static NtupleManager instance;
  return instance;
}
Referenced by framework::Process::run().
reset()
void framework::NtupleManager::reset ()
Reset NtupleManager to blank state
We assume that ROOT handles cleanup of TTrees when writing them to a blank state.
Definition at line 32 of file NtupleManager.cxx.
{
  // we assume that ROOT handles clean-up
  //  of the TTrees when they are written to the output histogram file
  trees_.clear();
  bus_.everybodyOff();
}
References bus_, framework::Bus::everybodyOff(), and trees_.
Referenced by framework::Process::run().
setVar()
template<typename T > void framework::NtupleManager::setVar (const std::string & vname, const T & value) inline
Set the value of the variable named 'vname'. If the variable value is not set, the default value will be used when filling the tree. If the requested variable has not been created, a warning will be printed. This allows a user to choose to make a subset of an ntuple by simply not adding the variable to the tree.
Template Parameters
in] T type of variable
Parameters
[in] vname Name of the variable
[in] value The value of the variable
Definition at line 93 of file NtupleManager.h.
{
    // Check if the variable already exists in the map.  If it
    // doesn't, warn the user and don't try to set the variable
    // value.
    if (not bus_.isOnBoard(vname)) {
      ldmx_log(warn) << "The variable " << vname
                     << " does not exist in the tree. Skipping.";
      return;
    }
    // Set the value of the variable
    try {
      bus_.update(vname,value);
    } catch (const std::bad_cast&) {
      EXCEPTION_RAISE("TypeMismatch", "Ntuple variable '" + vname +
                                          "' is being set by the wrong type '" +
                                          typeid(value).name() + "'.");
    }
  }
References bus_, framework::Bus::isOnBoard(), and framework::Bus::update().
Referenced by dqm::NtuplizeDarkBremInteraction::analyze(), ecal::test::EcalCheckEnergyReconstruction::analyze(), and hcal::test::HcalCheckReconstruction::analyze().
Member Data Documentation
bus_
framework::Bus framework::NtupleManager::bus_ private
Container for buffering variables.
Definition at line 138 of file NtupleManager.h.
Referenced by addVar(), clear(), reset(), and setVar().
trees_
std::unordered_map<std::string, TTree*> framework::NtupleManager::trees_ private
Container for output ROOT trees.
Definition at line 135 of file NtupleManager.h.
Referenced by addVar(), create(), and reset().
The documentation for this class was generated from the following files:
Framework/include/Framework/NtupleManager.h
Framework/src/Framework/NtupleManager.cxx