LDMX Software: ldmx::EcalElectronicsID Class Reference
ldmx::EcalElectronicsID Class Reference
Identifies a location in the Ecal readout chain.
#include <EcalElectronicsID.h>
Public Types
typedef PackedIndex< 38, 48 > Index
Public Types inherited from ldmx::DetectorID
typedef uint32_t RawValue
Public Member Functions
EcalElectronicsID ()
EcalElectronicsID (RawValue rawid)
EcalElectronicsID (const DetectorID id)
EcalElectronicsID (unsigned int fiber, unsigned int elink, unsigned int channel)
int fiber () const
int elink () const
int channel () const
unsigned int index () const
Public Member Functions inherited from ldmx::DetectorID
DetectorID ()
Class constructor for a null DetectorID.
DetectorID (RawValue rawid)
Class constructor from a raw 32-bit integer.
DetectorID (SubdetectorIDType sdtype, RawValue raw_subpayload)
bool null () const
SubdetectorIDType subdet () const
RawValue raw () const
void setRawValue (RawValue rawValue)
bool operator< (const DetectorID &id) const
bool operator== (const DetectorID &id) const
bool operator!= (const DetectorID &id) const
Static Public Member Functions
static EcalElectronicsID idFromIndex (unsigned int index)
Static Public Attributes
static const RawValue INDEX_MASK {0xFFFFFF}
static const unsigned int MAX_INDEX {38*48*200}
Static Public Attributes inherited from ldmx::DetectorID
static const RawValue SUBDETECTORID_MASK {0x3F}
static const RawValue SUBDETECTORID_SHIFT {26}
static const RawValue SUBDETECTOR_PAYLOAD_MASK {0x3FFFFFF}
Additional Inherited Members
Protected Attributes inherited from ldmx::DetectorID
RawValue id_
The raw, packed value of the ID.
Detailed Description
Identifies a location in the Ecal readout chain.
– fiber : optical fiber number (backend number), range assumed O(0-96) – elink : electronic link number, range assumed O(0-47) – channel : channel-on-elink, range O(0-37)
For transient use only i.e. we use this ID to help translate the digitized data coming off the detector into spatially-important EcalIDs.
Definition at line 27 of file EcalElectronicsID.h.
Member Typedef Documentation
Index
typedef PackedIndex<38,48> ldmx::EcalElectronicsID::Index
Definition at line 32 of file EcalElectronicsID.h.
Constructor & Destructor Documentation
EcalElectronicsID() [1/4]
ldmx::EcalElectronicsID::EcalElectronicsID () inline
Empty ECAL id (but not null!)
Definition at line 39 of file EcalElectronicsID.h.
: DetectorID(EID_ECAL, 0) {}
EcalElectronicsID() [2/4]
ldmx::EcalElectronicsID::EcalElectronicsID (RawValue rawid) inline
Create from raw number
Definition at line 44 of file EcalElectronicsID.h.
                                    : DetectorID(rawid) {
    SUBDETECTORID_TEST("EcalElectronicsID", EID_ECAL);
  }
EcalElectronicsID() [3/4]
ldmx::EcalElectronicsID::EcalElectronicsID (const DetectorID id) inline
Create from a DetectorID, but check
Definition at line 51 of file EcalElectronicsID.h.
                                         : DetectorID(id) {
    SUBDETECTORID_TEST("EcalElectronicsID", EID_ECAL);
  }
EcalElectronicsID() [4/4]
ldmx::EcalElectronicsID::EcalElectronicsID (unsigned int fiber, unsigned int elink, unsigned int channel) inline
Create from pieces
Definition at line 58 of file EcalElectronicsID.h.
      : DetectorID(EID_ECAL, 0) {
    Index index(channel,elink,fiber);
    id_ |= index.value();
  }
References channel(), elink(), fiber(), ldmx::DetectorID::id_, and index().
Member Function Documentation
channel()
int ldmx::EcalElectronicsID::channel () const inline
Get the value of the fiber from the ID.
Returns
The value of the fiber field.
Definition at line 92 of file EcalElectronicsID.h.
{ return Index(id_&INDEX_MASK).field0(); }
References ldmx::PackedIndex< m0, m1, m2 >::field0(), and ldmx::DetectorID::id_.
Referenced by EcalElectronicsID().
elink()
int ldmx::EcalElectronicsID::elink () const inline
Get the value of the fiber from the ID.
Returns
The value of the fiber field.
Definition at line 87 of file EcalElectronicsID.h.
{ return Index(id_&INDEX_MASK).field1(); }
References ldmx::PackedIndex< m0, m1, m2 >::field1(), and ldmx::DetectorID::id_.
Referenced by EcalElectronicsID().
fiber()
int ldmx::EcalElectronicsID::fiber () const inline
Get the value of the fiber from the ID.
Returns
The value of the fiber field.
Definition at line 82 of file EcalElectronicsID.h.
{ return Index(id_&INDEX_MASK).field2(); }
References ldmx::PackedIndex< m0, m1, m2 >::field2(), and ldmx::DetectorID::id_.
Referenced by EcalElectronicsID().
idFromIndex()
static EcalElectronicsID ldmx::EcalElectronicsID::idFromIndex (unsigned int index) inline static
Construct an electronics id from an index
This looks ugly (and it is) because we already have a constructor that uses the unsigned int type. This means we need a different static method for translating something we know to be an EID index rather than a full DetID raw value.
Definition at line 72 of file EcalElectronicsID.h.
{
    EcalElectronicsID eid;
    eid.id_|=index;
    return eid;
  }
References ldmx::DetectorID::id_, and index().
index()
unsigned int ldmx::EcalElectronicsID::index () const inline
Get the compact index value
Definition at line 97 of file EcalElectronicsID.h.
{ return id_&INDEX_MASK; }
References ldmx::DetectorID::id_.
Referenced by EcalElectronicsID(), and idFromIndex().
Member Data Documentation
INDEX_MASK
const RawValue ldmx::EcalElectronicsID::INDEX_MASK {0xFFFFFF} static
Definition at line 30 of file EcalElectronicsID.h.
MAX_INDEX
const unsigned int ldmx::EcalElectronicsID::MAX_INDEX {38*48*200} static
Definition at line 34 of file EcalElectronicsID.h.
The documentation for this class was generated from the following file:
DetDescr/include/DetDescr/EcalElectronicsID.h