LDMX Software: hcal::test::HcalCheckReconstruction Class Reference
hcal::test::HcalCheckReconstruction Class Reference
Public Member Functions
HcalCheckReconstruction (const std::string &name, framework::Process &p)
void onProcessStart () final override
void analyze (const framework::Event &event) final override
Public Member Functions inherited from framework::Analyzer
Analyzer (const std::string &name, Process &process)
Public Member Functions inherited from framework::EventProcessor
EventProcessor (const std::string &name, Process &process)
virtual ~EventProcessor ()
virtual void configure (framework::config::Parameters &parameters)
virtual void onNewRun (const ldmx::RunHeader &runHeader)
virtual void onFileOpen (EventFile &eventFile)
virtual void onFileClose (EventFile &eventFile)
virtual void onProcessEnd ()
template<class T >
const T & getCondition (const std::string &condition_name)
TDirectory * getHistoDirectory ()
void setStorageHint (framework::StorageControlHint hint)
void setStorageHint (framework::StorageControlHint hint, const std::string &purposeString)
int getLogFrequency () const
int getRunNumber () const
std::string getName () const
void createHistograms (const std::vector< framework::config::Parameters > &histos)
Private Attributes
const bool save_ = false
Additional Inherited Members
Static Public Member Functions inherited from framework::EventProcessor
static void declare (const std::string &classname, int classtype, EventProcessorMaker *)
Static Public Attributes inherited from framework::Analyzer
static const int CLASSTYPE {2}
Protected Member Functions inherited from framework::EventProcessor
void abortEvent ()
Protected Attributes inherited from framework::EventProcessor
HistogramHelper histograms_
Interface class for making and filling histograms.
NtupleManager & ntuple_ {NtupleManager::getInstance()}
Manager for any ntuples.
logging::logger theLog_
The logger for this EventProcessor.
Detailed Description
Checks
Energy of HcalRecHit matches SimCalorimeterHit EDep with the same ID
Position of HcalRecHit for back Hcal matches SimCalorimeterHit position along the bar with the same ID
Assumptions
Only one sim hit per event
Noise generation has been turned off
Definition at line 198 of file HcalDigiPipelineTest.cxx.
Constructor & Destructor Documentation
HcalCheckReconstruction()
hcal::test::HcalCheckReconstruction::HcalCheckReconstruction (const std::string & name, framework::Process & p) inline
Definition at line 204 of file HcalDigiPipelineTest.cxx.
      : framework::Analyzer(name, p) {}
~HcalCheckReconstruction()
hcal::test::HcalCheckReconstruction::~HcalCheckReconstruction () inline
Definition at line 206 of file HcalDigiPipelineTest.cxx.
{}
Member Function Documentation
analyze()
void hcal::test::HcalCheckReconstruction::analyze (const framework::Event & event) inline final override virtual
Process the event and make histograms or summaries
Parameters
event The Event to analyze
Implements framework::Analyzer.
Definition at line 229 of file HcalDigiPipelineTest.cxx.
{
    const auto simHits =
        event.getCollection<ldmx::SimCalorimeterHit>("HcalFakeSimHits");
    REQUIRE(simHits.size() == 1);
    float truth_energy = simHits.at(0).getEdep();
    if (save_) {
      ntuple_.setVar<float>("SimEnergy", truth_energy);
      ntuple_.setVar<float>("SimX", simHits.at(0).getPosition()[0]);
      ntuple_.setVar<float>("SimY", simHits.at(0).getPosition()[1]);
      ntuple_.setVar<float>("SimZ", simHits.at(0).getPosition()[2]);
      ntuple_.setVar<float>("SimTime", simHits.at(0).getContrib(0).time);
    }
    const auto daqDigis{
        event.getObject<ldmx::HgcrocDigiCollection>("HcalDigis")};
    auto daqDigi = daqDigis.getDigi(0);
    bool is_in_adc_mode = daqDigi.isADC();
    if (save_) {
      ntuple_.setVar<int>("DaqDigi", daqDigi.soi().raw());
      ntuple_.setVar<int>("DaqDigiIsADC", is_in_adc_mode);
      ntuple_.setVar<int>("DaqDigiADC", daqDigi.soi().adc_t());
      ntuple_.setVar<int>("DaqDigiTOT", daqDigi.tot());
    }
    const auto recHits = event.getCollection<ldmx::HcalHit>("HcalRecHits");
    CHECK(recHits.size() == 1);
    auto hit = recHits.at(0);
    ldmx::HcalID id(hit.getID());
    CHECK_FALSE(hit.isNoise());
    CHECK(id.raw() == simHits.at(0).getID());
    if (save_) {
      ntuple_.setVar<float>("RecX", hit.getXPos());
      ntuple_.setVar<float>("RecY", hit.getYPos());
      ntuple_.setVar<float>("RecZ", hit.getZPos());
      ntuple_.setVar<float>("RecTime", hit.getTime());
      ntuple_.setVar<float>("RecEnergy", hit.getEnergy());
    }
    // define target energy by using the settings at the top
    double daq_energy{hit.getEnergy()};
    CHECK_THAT(daq_energy, isCloseEnough(truth_energy, MAX_ENERGY_ERROR_DAQ,
                                         MAX_ENERGY_PERCENT_ERROR_DAQ));
    // std::cout << "rec energy " << hit.getEnergy() << " truth " <<
    // truth_energy
    //          << std::endl;
    // ntuple_.setVar<float>("RecEnergy", hit.getEnergy());
    if (id.section() == 0) {
      double truth_pos, rec_pos;
      if ((id.layer() % 2) == 1) {
        truth_pos = simHits.at(0).getPosition()[0];
        rec_pos = hit.getXPos();
      } else {
        truth_pos = simHits.at(0).getPosition()[1];
        rec_pos = hit.getYPos();
      }
      // std::cout << "rec pos " << rec_pos << " truth " << truth_pos <<
      // std::endl;
      // comment position check for now
      // CHECK_THAT(rec_pos, isCloseEnough(truth_pos, MAX_POSITION_ERROR_DAQ,
      //                                 MAX_POSITION_PERCENT_ERROR_DAQ));
    }
    return;
  }
References ldmx::HgcrocDigiCollection::getDigi(), ldmx::HgcrocDigiCollection::HgcrocDigi::isADC(), framework::EventProcessor::ntuple_, and framework::NtupleManager::setVar().
onProcessStart()
void hcal::test::HcalCheckReconstruction::onProcessStart () inline final override virtual
Callback for the EventProcessor to take any necessary action when the processing of events starts, such as creating histograms.
Reimplemented from framework::EventProcessor.
Definition at line 208 of file HcalDigiPipelineTest.cxx.
{
    if (save_) {
      getHistoDirectory();
      ntuple_.create("HcalDigiTest");
      ntuple_.addVar<float>("HcalDigiTest", "SimEnergy");
      ntuple_.addVar<float>("HcalDigiTest", "RecEnergy");
      ntuple_.addVar<float>("HcalDigiTest", "SimX");
      ntuple_.addVar<float>("HcalDigiTest", "SimY");
      ntuple_.addVar<float>("HcalDigiTest", "SimZ");
      ntuple_.addVar<float>("HcalDigiTest", "SimTime");
      ntuple_.addVar<float>("HcalDigiTest", "RecX");
      ntuple_.addVar<float>("HcalDigiTest", "RecY");
      ntuple_.addVar<float>("HcalDigiTest", "RecZ");
      ntuple_.addVar<float>("HcalDigiTest", "RecTime");
      ntuple_.addVar<int>("HcalDigiTest", "DaqDigi");
      ntuple_.addVar<int>("HcalDigiTest", "DaqDigiIsADC");
      ntuple_.addVar<int>("HcalDigiTest", "DaqDigiADC");
      ntuple_.addVar<int>("HcalDigiTest", "DaqDigiTOT");
    }
  }
References framework::NtupleManager::addVar(), framework::NtupleManager::create(), framework::EventProcessor::getHistoDirectory(), and framework::EventProcessor::ntuple_.
Member Data Documentation
save_
const bool hcal::test::HcalCheckReconstruction::save_ = false private
Definition at line 201 of file HcalDigiPipelineTest.cxx.
The documentation for this class was generated from the following file:
Hcal/test/HcalDigiPipelineTest.cxx