LDMX Software: simcore::UserTrackingAction Class Reference
simcore::UserTrackingAction Class Reference
Implementation of user tracking action.
#include <UserTrackingAction.h>
Public Member Functions
UserTrackingAction ()
virtual ~UserTrackingAction ()
void PreUserTrackingAction (const G4Track *aTrack)
void PostUserTrackingAction (const G4Track *aTrack)
TrackMap * getTrackMap ()
void storeTrajectory (const G4Track *aTrack)
void registerAction (UserAction *trackingAction)
Static Public Member Functions
static UserTrackingAction * getUserTrackingAction ()
Private Attributes
std::vector< UserAction * > trackingActions_
custom user actions to be called before and after processing a track
TrackMap trackMap_
Detailed Description
Implementation of user tracking action.
Here, we manage the interaction between our track storage machinery (TrackMap) and Geant4's tracking manager (G4TrackingManager).
Definition at line 37 of file UserTrackingAction.h.
Constructor & Destructor Documentation
UserTrackingAction()
simcore::UserTrackingAction::UserTrackingAction () inline
Class constructor.
Definition at line 42 of file UserTrackingAction.h.
 {}
~UserTrackingAction()
virtual simcore::UserTrackingAction::~UserTrackingAction () inline virtual
Class destructor.
Definition at line 47 of file UserTrackingAction.h.
 {}
Member Function Documentation
getTrackMap()
TrackMap* simcore::UserTrackingAction::getTrackMap () inline
Get a pointer to the current TrackMap for the event.
Returns
A pointer to the current TrackMap for the event.
Definition at line 111 of file UserTrackingAction.h.
 { return &trackMap_; }
References trackMap_.
Referenced by simcore::UserEventAction::BeginOfEventAction(), simcore::persist::RootPersistencyManager::writeCalorimeterHitsCollection(), and simcore::EcalHitIO::writeHitsCollection().
getUserTrackingAction()
static UserTrackingAction* simcore::UserTrackingAction::getUserTrackingAction () inline static
Get a pointer to the current UserTrackingAction from the G4RunManager.
Returns
A pointer to the current UserTrackingAction.
Definition at line 134 of file UserTrackingAction.h.
{
     return static_cast<UserTrackingAction*>(const_cast<G4UserTrackingAction*>(
         G4RunManager::GetRunManager()->GetUserTrackingAction()));
   }
Referenced by simcore::UserEventAction::BeginOfEventAction(), simcore::persist::RootPersistencyManager::writeCalorimeterHitsCollection(), and simcore::EcalHitIO::writeHitsCollection().
PostUserTrackingAction()
void simcore::UserTrackingAction::PostUserTrackingAction (const G4Track * aTrack)
Implementation of post-tracking action.
We start by calling any other tracking actions' PostUserTrackingAction methods.
If the track's user information has a save flag set to true, then we make sure it will be stored by checking our track map and calling storeTrajectory if it isn't within the track map.
Finally, if the Geant4 tracking manager agrees that this track will be stored and the trajectory is going to be killed, then we retrieve the end point momentum and pass that onto the trajectory.
Parameters
aTrack The Geant4 track.
Definition at line 83 of file UserTrackingAction.cxx.
{
   // Activate user tracking actions
   for (auto& trackingAction : trackingActions_)
     trackingAction->PostUserTrackingAction(track);
   // Save extra trajectories on tracks that were flagged for saving during event
   // processing.
   if (dynamic_cast<UserTrackInformation*>(track->GetUserInformation())
           ->getSaveFlag()) {
     if (!trackMap_.hasTrajectory(track->GetTrackID())) {
       storeTrajectory(track);
     }
   }
   // Set end point momentum on the trajectory.
   if (fpTrackingManager->GetStoreTrajectory()) {
     auto traj = dynamic_cast<Trajectory*>(fpTrackingManager->GimmeTrajectory());
     if (traj) {
       if (track->GetTrackStatus() == G4TrackStatus::fStopAndKill) {
         traj->setEndPointMomentum(track);
       }
     }
   }
 }
References simcore::UserTrackInformation::getSaveFlag(), simcore::TrackMap::hasTrajectory(), storeTrajectory(), trackingActions_, and trackMap_.
PreUserTrackingAction()
void simcore::UserTrackingAction::PreUserTrackingAction (const G4Track * aTrack)
Implementation of pre-tracking action.
This is called whenever a track is going to start being processed.
Note
A track could go through this function more than once in an event if it is suspended.
We first check if we have seen this track before by looking inside of our track map.
If we have seen it before, then we simply make sure that our track map and Geant4's tracking manager are on the same page about whether or not to store this track.
If we haven't seen it before, then we must do some setup.
Make an instance of UserTrackInformation and attach it to the track after setting the initial momentum and vertex volume.
Using the gen status of the track and the region the track was produced in, decide if we will store the track by default. (Other user tracking actions can change the save flag in the track information.)
We choose to store the track by default if it is a primary or if it was created within a region where the 'StoreSecondaries' flag was set to true.
No matter what, if the track has parents, we insert the track into the track map's ancestry tree.
Finally, before we wrap up, we call any other tracking actions' 'PreUserTrackingAction' methods.
Parameters
aTrack The Geant4 track.
When a track is suspended and then put onto the waiting stack (like what is done using the PartialEnergySorter) The track ends up being passed through the user tracking action more than one time. We need this here to make sure Geant4's trajectory manager has the same setting for whether we should keep the trajectroy as our trajectory manager (TrackMap)
Definition at line 20 of file UserTrackingAction.cxx.
{
   int trackID = track->GetTrackID();
   if (trackMap_.contains(trackID)) {
     fpTrackingManager->SetStoreTrajectory(trackMap_.hasTrajectory(trackID));
   } else {
     // New Track
     // Set user track info on new track.
     if (!track->GetUserInformation()) {
       auto trackInfo = new UserTrackInformation;
       trackInfo->setInitialMomentum(track->GetMomentum());
       const_cast<G4Track*>(track)->SetUserInformation(trackInfo);
       trackInfo->setVertexVolume(track->GetVolume()->GetName());
     }
     // Check if trajectory storage should be turned on or off from the region
     // info.
     auto regionInfo = (UserRegionInformation*)track->GetLogicalVolumeAtVertex()
                           ->GetRegion()
                           ->GetUserInformation();
     // Check if trajectory storage should be turned on or off from the gen
     // status info
     int curGenStatus = -1;
     if (track->GetDynamicParticle()->GetPrimaryParticle()) {
       auto primaryInfo = dynamic_cast<UserPrimaryParticleInformation*>(
           track->GetDynamicParticle()
               ->GetPrimaryParticle()
               ->GetUserInformation());
       curGenStatus = primaryInfo->getHepEvtStatus();
     }
     // Always save a particle if it has gen status == 1
     if (curGenStatus == 1) {
       storeTrajectory(track);
     } else if (regionInfo && !regionInfo->getStoreSecondaries()) {
       // Turn off trajectory storage for this track from region flag.
       fpTrackingManager->SetStoreTrajectory(false);
     } else {
       // Store a new trajectory for this track.
       storeTrajectory(track);
     }
     // Save the association between track ID and its parent ID for all tracks in
     // the event.
     if (track->GetParentID() > 0)
       trackMap_.addSecondary(track->GetTrackID(), track->GetParentID());
   }
   // Activate user tracking actions
   for (auto& trackingAction : trackingActions_)
     trackingAction->PreUserTrackingAction(track);
 }
References simcore::TrackMap::addSecondary(), simcore::TrackMap::contains(), simcore::UserPrimaryParticleInformation::getHepEvtStatus(), simcore::TrackMap::hasTrajectory(), simcore::UserTrackInformation::setInitialMomentum(), storeTrajectory(), trackingActions_, and trackMap_.
registerAction()
void simcore::UserTrackingAction::registerAction (UserAction * trackingAction) inline
Register a user action of type RunAction with this class.
Parameters
action User action of type RunAction
Definition at line 144 of file UserTrackingAction.h.
{
     trackingActions_.push_back(trackingAction);
   }
References trackingActions_.
storeTrajectory()
void simcore::UserTrackingAction::storeTrajectory (const G4Track * aTrack)
Store a Trajectory for the given G4Track.
We make sure the Geant4 tracking manager will also store this track and then we create a Trajectory object for the track's storage.
If the track is a primary particle, we pass the HepEvtStatus as the trajectory's gen status.
Finally, we add the newly created trajectory to the track map.
Parameters
aTrack The Geant4 track.
Definition at line 108 of file UserTrackingAction.cxx.
{
   // Create a new trajectory for this track.
   fpTrackingManager->SetStoreTrajectory(true);
   Trajectory* traj = new Trajectory(track);
   fpTrackingManager->SetTrajectory(traj);
   // Update the gen status from the primary particle.
   if (track->GetDynamicParticle()->GetPrimaryParticle() != NULL) {
     G4VUserPrimaryParticleInformation* primaryInfo =
         track->GetDynamicParticle()->GetPrimaryParticle()->GetUserInformation();
     if (primaryInfo != NULL) {
       traj->setGenStatus(
           ((UserPrimaryParticleInformation*)primaryInfo)->getHepEvtStatus());
     }
   }
   // Map track ID to trajectory.
   trackMap_.addTrajectory(traj);
 }
References simcore::TrackMap::addTrajectory(), simcore::Trajectory::setGenStatus(), and trackMap_.
Referenced by PostUserTrackingAction(), and PreUserTrackingAction().
Member Data Documentation
trackMap_
TrackMap simcore::UserTrackingAction::trackMap_ private
Stores parentage information for all tracks in the event.
Definition at line 153 of file UserTrackingAction.h.
Referenced by getTrackMap(), PostUserTrackingAction(), PreUserTrackingAction(), and storeTrajectory().
The documentation for this class was generated from the following files:
SimCore/include/SimCore/UserTrackingAction.h
SimCore/src/SimCore/UserTrackingAction.cxx