LDMX Software: hcal::HcalDigiProducer Class Reference
hcal::HcalDigiProducer Class Reference
Performs basic HCal digitization.
#include <HcalDigiProducer.h>
Public Member Functions
HcalDigiProducer (const std::string &name, framework::Process &process)
~HcalDigiProducer ()=default
Default destructor.
void configure (framework::config::Parameters &) final override
void produce (framework::Event &event) final override
Public Member Functions inherited from framework::Producer
Producer (const std::string &name, Process &process)
virtual void beforeNewRun (ldmx::RunHeader &header)
Public Member Functions inherited from framework::EventProcessor
EventProcessor (const std::string &name, Process &process)
virtual ~EventProcessor ()
virtual void onNewRun (const ldmx::RunHeader &runHeader)
virtual void onFileOpen (EventFile &eventFile)
virtual void onFileClose (EventFile &eventFile)
virtual void onProcessStart ()
virtual void onProcessEnd ()
template<class T >
const T & getCondition (const std::string &condition_name)
TDirectory * getHistoDirectory ()
void setStorageHint (framework::StorageControlHint hint)
void setStorageHint (framework::StorageControlHint hint, const std::string &purposeString)
int getLogFrequency () const
int getRunNumber () const
std::string getName () const
void createHistograms (const std::vector< framework::config::Parameters > &histos)
Private Attributes
std::string inputCollName_
input hit collection name
std::string inputPassName_
input pass name
std::string digiCollName_
output hit collection name
double clockCycle_
Time interval for chip clock in ns.
int nADCs_
Depth of ADC buffer.
int iSOI_
Index for the Sample Of Interest in the list of digi samples.
double MeV_
Conversion from energy in MeV to voltage in mV.
double attlength_
Strip attenuation length [m].
bool noise_ {true}
std::unique_ptr< ldmx::HgcrocEmulator > hgcroc_
Hgcroc Emulator to digitize analog voltage signals.
double ns_
Conversion from time in ns to ticks of the internal clock.
std::unique_ptr< ldmx::NoiseGenerator > noiseGenerator_
Generates noise hits based off of number of cells that are not hit.
std::unique_ptr< TRandom3 > noiseInjector_
Generates Gaussian noise on top of real hits.
Additional Inherited Members
Static Public Member Functions inherited from framework::EventProcessor
static void declare (const std::string &classname, int classtype, EventProcessorMaker *)
Static Public Attributes inherited from framework::Producer
static const int CLASSTYPE {1}
Protected Member Functions inherited from framework::EventProcessor
void abortEvent ()
Protected Attributes inherited from framework::EventProcessor
HistogramHelper histograms_
Interface class for making and filling histograms.
NtupleManager & ntuple_ {NtupleManager::getInstance()}
Manager for any ntuples.
logging::logger theLog_
The logger for this EventProcessor.
Detailed Description
Performs basic HCal digitization.
Definition at line 29 of file HcalDigiProducer.h.
Constructor & Destructor Documentation
HcalDigiProducer()
hcal::HcalDigiProducer::HcalDigiProducer (const std::string & name, framework::Process & process)
Constructor Makes unique noise generator and injector for this class
Definition at line 15 of file HcalDigiProducer.cxx.
     : Producer(name, process) {
   /*
    * Noise generator by default uses a Gausian model for noise
    * i.e. It assumes the noise is distributed around a mean (setPedestal)
    * with a certain RMS (setNoise) and then calculates
    * how many hits should be generated for a given number of empty
    * channels and a minimum readout value (setNoiseThreshold)
    */
   noiseGenerator_ = std::make_unique<ldmx::NoiseGenerator>();
 }
References noiseGenerator_.
Member Function Documentation
configure()
void hcal::HcalDigiProducer::configure (framework::config::Parameters & ps) final override virtual
Configure this producer from the python configuration. Sets event constants and configures the noise generator, noise injector, and pulse function. Creates digi collection
Reimplemented from framework::EventProcessor.
Definition at line 28 of file HcalDigiProducer.cxx.
{
   // settings of readout chip
   //  used  in actual digitization
   auto hgcrocParams = ps.getParameter<framework::config::Parameters>("hgcroc");
   hgcroc_ = std::make_unique<ldmx::HgcrocEmulator>(hgcrocParams);
   clockCycle_ = hgcrocParams.getParameter<double>("clockCycle");
   nADCs_ = hgcrocParams.getParameter<int>("nADCs");
   iSOI_ = hgcrocParams.getParameter<int>("iSOI");
   noise_ = hgcrocParams.getParameter<bool>("noise");
   // collection names
   inputCollName_ = ps.getParameter<std::string>("inputCollName");
   inputPassName_ = ps.getParameter<std::string>("inputPassName");
   digiCollName_ = ps.getParameter<std::string>("digiCollName");
   // physical constants
   //  used to calculate unit conversions
   MeV_ = ps.getParameter<double>("MeV");
   attlength_ = ps.getParameter<double>("attenuationLength");
   // Time -> clock counts conversion
   //  time [ns] * ( 2^10 / max time in ns ) = clock counts
   ns_ = 1024. / clockCycle_;
   // Configure generator that will produce noise hits in empty channels
   double readoutThreshold = ps.getParameter<double>("avgReadoutThreshold");
   double gain = ps.getParameter<double>("avgGain");
   double pedestal = ps.getParameter<double>("avgPedestal");
   // rms noise in mV
   noiseGenerator_->setNoise(
       hgcrocParams.getParameter<double>("noiseRMS"));  // rms noise in mV
   // mean noise amplitude (if using Gaussian Model for the noise) in mV
   noiseGenerator_->setPedestal(gain * pedestal);
   // threshold for readout in mV
   noiseGenerator_->setNoiseThreshold(gain * readoutThreshold);
 }
References attlength_, clockCycle_, digiCollName_, framework::config::Parameters::getParameter(), hgcroc_, inputCollName_, inputPassName_, iSOI_, MeV_, nADCs_, noise_, noiseGenerator_, and ns_.
produce()
void hcal::HcalDigiProducer::produce (framework::Event & event) final override virtual
Simulates measurement of pulse and creates digi collection for input event.
Define two pulses: with positive and negative ends. For this we need to: (1) Find the position along the bar: For back Hcal: x (y) for even (odd) layers. For side Hcal: x (top,bottom) and y (left,right).
(2) Define the end of the bar: The end of an HcalDigiID is based on its distance (x,y) along the bar.
A positive end (endID=0), corresponds to top,left.
A negative end (endID=1), corresponds to bottom,right. For back Hcal:
if the position along the bar > 0, the close pulse's end is 0, else 1. For side Hcal:
if the position along the bar > half_width point of the bar, the close pulse's end is 0, else 1. The far pulse's end will be opposite to the close pulse's end.
(3) Find the distance to each end (positive and negative) from the origin. For the back Hcal, the half point of the bar coincides with the coordinates of the origin. For the side Hcal, the length of the bar from the origin is:
2 *(half_width) - Ecal_dx(y)/2 away from the positive end, and,
Ecal_dx(y) away from the negative end.
Now we have all the sub-hits from all the simhits Digitize: For back Hcal return two digis. For side Hcal we choose which pulse to readout based on the position of the hit and the sub-section. For Top and Left we read the positive end digi. For Bottom and Right we read the negative end digi.
Implements framework::Producer.
Definition at line 65 of file HcalDigiProducer.cxx.
{
   // Handle seeding on the first event
   if (!noiseGenerator_->hasSeed()) {
     const auto& rseed = getCondition<framework::RandomNumberSeedService>(
         framework::RandomNumberSeedService::CONDITIONS_OBJECT_NAME);
     noiseGenerator_->seedGenerator(
         rseed.getSeed("HcalDigiProducer::NoiseGenerator"));
   }
   if (noiseInjector_.get() == nullptr) {
     const auto& rseed = getCondition<framework::RandomNumberSeedService>(
         framework::RandomNumberSeedService::CONDITIONS_OBJECT_NAME);
     noiseInjector_ = std::make_unique<TRandom3>(
         rseed.getSeed("HcalDigiProducer::NoiseInjector"));
   }
   if (!hgcroc_->hasSeed()) {
     const auto& rseed = getCondition<framework::RandomNumberSeedService>(
         framework::RandomNumberSeedService::CONDITIONS_OBJECT_NAME);
     hgcroc_->seedGenerator(rseed.getSeed("HcalDigiProducer::HgcrocEmulator"));
   }
   // Get the Hgcroc Conditions
   hgcroc_->condition(
       getCondition<conditions::DoubleTableCondition>("HcalHgcrocConditions"));
   // Get the Hcal Geometry
   const auto& hcalGeometry = getCondition<ldmx::HcalGeometry>(
       ldmx::HcalGeometry::CONDITIONS_OBJECT_NAME);
   // Empty collection to be filled
   ldmx::HgcrocDigiCollection hcalDigis;
   hcalDigis.setNumSamplesPerDigi(nADCs_);
   hcalDigis.setSampleOfInterestIndex(iSOI_);
   std::map<unsigned int, std::vector<const ldmx::SimCalorimeterHit*>> hitsByID;
   // get simulated hcal hits from Geant4 and group them by id
   auto hcalSimHits{event.getCollection<ldmx::SimCalorimeterHit>(
       inputCollName_, inputPassName_)};
   for (auto const& simHit : hcalSimHits) {
     // get ID
     unsigned int hitID = simHit.getID();
     auto idh = hitsByID.find(hitID);
     if (idh == hitsByID.end()) {
       hitsByID[hitID] = std::vector<const ldmx::SimCalorimeterHit*>(1, &simHit);
     } else {
       idh->second.push_back(&simHit);
     }
   }
   /******************************************************************************************
    * HGCROC Emulation on Simulated Hits (grouped by HcalID)
    ******************************************************************************************/
   for (auto const& simBar : hitsByID) {
     ldmx::HcalID detID(simBar.first);
     int section = detID.section();
     int layer = detID.layer();
     int strip = detID.strip();
     // get position
     double half_total_width = hcalGeometry.getHalfTotalWidth(section);
     double ecal_dx = hcalGeometry.getEcalDx();
     double ecal_dy = hcalGeometry.getEcalDy();
     // contributions
     std::vector<std::pair<double, double>> pulses_posend;
     std::vector<std::pair<double, double>> pulses_negend;
     for (auto psimHit : simBar.second) {
       const ldmx::SimCalorimeterHit& simHit = *psimHit;
       std::vector<float> position = simHit.getPosition();
       float distance_along_bar, distance_ecal;
       float distance_close, distance_far;
       int end_close;
       if (section == ldmx::HcalID::HcalSection::BACK) {
         distance_along_bar = (layer % 2) ? position[0] : position[1];
         end_close = (distance_along_bar > 0) ? 0 : 1;
         distance_close = half_total_width;
         distance_far = half_total_width;
       } else {
         if ((section == ldmx::HcalID::HcalSection::TOP) ||
             ((section == ldmx::HcalID::HcalSection::BOTTOM))) {
           distance_along_bar = position[0];
           distance_ecal = ecal_dx;
         } else if ((section == ldmx::HcalID::HcalSection::LEFT) ||
                    (section == ldmx::HcalID::HcalSection::RIGHT)) {
           distance_along_bar = position[1];
           distance_ecal = ecal_dy;
         }
         end_close = (distance_along_bar > half_total_width) ? 0 : 1;
         distance_close = (end_close == 0)
                              ? 2 * half_total_width - distance_ecal / 2
                              : distance_ecal / 2;
         distance_far = (end_close == 0)
                            ? distance_ecal / 2
                            : 2 * half_total_width - distance_ecal / 2;
       }
       // Calculate voltage attenuation and time shift for the close and far
       // pulse.
       float v = 299.792 /
                 1.6;  // velocity of light in Polystyrene, n = 1.6 = c/v mm/ns
       double att_close =
           exp(-1. * ((distance_close - fabs(distance_along_bar)) / 1000.) /
               attlength_);
       double att_far =
           exp(-1. * ((distance_far + fabs(distance_along_bar)) / 1000.) /
               attlength_);
       double shift_close =
           fabs((distance_close - fabs(distance_along_bar)) / v);
       double shift_far = fabs((distance_far + fabs(distance_along_bar)) / v);
       // Get voltages and times.
       for (int iContrib = 0; iContrib < simHit.getNumberOfContribs();
            iContrib++) {
         double voltage = simHit.getContrib(iContrib).edep * MeV_;
         double time =
             simHit.getContrib(iContrib).time;  // global time (t=0ns at target)
         time -= position.at(2) /
                 299.702547;  // shift light-speed particle traveling along z
         if (end_close == 0) {
           pulses_posend.emplace_back(voltage * att_close, time + shift_close);
           pulses_negend.emplace_back(voltage * att_far, time + shift_far);
         } else {
           pulses_posend.emplace_back(voltage * att_far, time + shift_far);
           pulses_negend.emplace_back(voltage * att_close, time + shift_close);
         }
       }
     }
     if (section == ldmx::HcalID::HcalSection::BACK) {
       std::vector<ldmx::HgcrocDigiCollection::Sample> digiToAddPosend,
           digiToAddNegend;
       ldmx::HcalDigiID posendID(section, layer, strip, 0);
       ldmx::HcalDigiID negendID(section, layer, strip, 1);
       if (hgcroc_->digitize(posendID.raw(), pulses_posend, digiToAddPosend) &&
           hgcroc_->digitize(negendID.raw(), pulses_negend, digiToAddNegend)) {
         hcalDigis.addDigi(posendID.raw(), digiToAddPosend);
         hcalDigis.addDigi(negendID.raw(), digiToAddNegend);
       }  // Back Hcal needs to digitize both pulses or none
     } else {
       bool is_posend = false;
       std::vector<ldmx::HgcrocDigiCollection::Sample> digiToAdd;
       if ((section == ldmx::HcalID::HcalSection::TOP) ||
           (section == ldmx::HcalID::HcalSection::LEFT)) {
         is_posend = true;
       } else if ((section == ldmx::HcalID::HcalSection::BOTTOM) ||
                  (section == ldmx::HcalID::HcalSection::RIGHT)) {
         is_posend = false;
       }
       if (is_posend) {
         ldmx::HcalDigiID digiID(section, layer, strip, 0);
         if (hgcroc_->digitize(digiID.raw(), pulses_posend, digiToAdd)) {
           hcalDigis.addDigi(digiID.raw(), digiToAdd);
         }
       } else {
         ldmx::HcalDigiID digiID(section, layer, strip, 1);
         if (hgcroc_->digitize(digiID.raw(), pulses_negend, digiToAdd)) {
           hcalDigis.addDigi(digiID.raw(), digiToAdd);
         }
       }
     }
   }
   /******************************************************************************************
    * Noise Simulation on Empty Channels
    *****************************************************************************************/
   if (noise_) {
     int numChannels = 0;
     for (int l = 0; l < hcalGeometry.getNumSections(); l++) {
       int nChannels =
           hcalGeometry.getNumLayers(l) * hcalGeometry.getNumStrips(l);
       // for back Hcal we have double readout, therefore we multiply the number
       // of channels by 2.
       if (l == 0) nChannels *= 2;
       numChannels += nChannels;
     }
     int numEmptyChannels = numChannels - hcalDigis.getNumDigis();
     // noise generator gives us a list of noise amplitudes [mV] that randomly
     // populate the empty channels and are above the readout threshold
     auto noiseHitAmplitudes{
         noiseGenerator_->generateNoiseHits(numEmptyChannels)};
     std::vector<std::pair<double, double>> fake_pulse(1, {0., 0.});
     for (double noiseHit : noiseHitAmplitudes) {
       // generate detector ID for noise hit
       // making sure that it is in an empty channel
       unsigned int noiseID;
       int sectionID, layerID, stripID, endID;
       do {
         sectionID = noiseInjector_->Integer(hcalGeometry.getNumSections());
         layerID = noiseInjector_->Integer(hcalGeometry.getNumLayers(sectionID));
         // set layer to 1 if the generator says it is 0 (geometry map starts
         // from 1)
         if (layerID == 0) layerID = 1;
         stripID = noiseInjector_->Integer(hcalGeometry.getNumStrips(sectionID));
         endID = noiseInjector_->Integer(2);
         if ((sectionID == ldmx::HcalID::HcalSection::TOP) ||
             (sectionID == ldmx::HcalID::HcalSection::LEFT)) {
           endID = 0;
         } else if ((sectionID == ldmx::HcalID::HcalSection::BOTTOM) ||
                    (sectionID == ldmx::HcalID::HcalSection::RIGHT)) {
           endID = 1;
         }
         auto detID = ldmx::HcalDigiID(sectionID, layerID, stripID, endID);
         noiseID = detID.raw();
       } while (hitsByID.find(noiseID) != hitsByID.end());
       hitsByID[noiseID] =
           std::vector<const ldmx::SimCalorimeterHit*>();  // mark this as used
       // get a time for this noise hit
       fake_pulse[0].second = noiseInjector_->Uniform(clockCycle_);
       // noise generator gives the amplitude above the readout threshold
       // we need to convert it to the amplitude above the pedestal
       double gain = hgcroc_->gain(noiseID);
       fake_pulse[0].first = noiseHit +
                             gain * hgcroc_->readoutThreshold(noiseID) -
                             gain * hgcroc_->pedestal(noiseID);
       if (sectionID == ldmx::HcalID::HcalSection::BACK) {
         std::vector<ldmx::HgcrocDigiCollection::Sample> digiToAddPosend,
             digiToAddNegend;
         ldmx::HcalDigiID posendID(sectionID, layerID, stripID, 0);
         ldmx::HcalDigiID negendID(sectionID, layerID, stripID, 1);
         if (hgcroc_->digitize(posendID.raw(), fake_pulse, digiToAddPosend) &&
             hgcroc_->digitize(negendID.raw(), fake_pulse, digiToAddNegend)) {
           hcalDigis.addDigi(posendID.raw(), digiToAddPosend);
           hcalDigis.addDigi(negendID.raw(), digiToAddNegend);
         }
       } else {
         std::vector<ldmx::HgcrocDigiCollection::Sample> digiToAdd;
         if (hgcroc_->digitize(noiseID, fake_pulse, digiToAdd)) {
           hcalDigis.addDigi(noiseID, digiToAdd);
         }
       }
     }  // loop over noise amplitudes
   }    // if we should add noise
   event.add(digiCollName_, hcalDigis);
   return;
 }  // produce
References ldmx::HgcrocDigiCollection::addDigi(), attlength_, clockCycle_, ldmx::HcalGeometry::CONDITIONS_OBJECT_NAME, framework::RandomNumberSeedService::CONDITIONS_OBJECT_NAME, digiCollName_, ldmx::SimCalorimeterHit::Contrib::edep, ldmx::SimCalorimeterHit::getContrib(), ldmx::SimCalorimeterHit::getID(), ldmx::SimCalorimeterHit::getNumberOfContribs(), ldmx::HgcrocDigiCollection::getNumDigis(), ldmx::SimCalorimeterHit::getPosition(), hgcroc_, inputCollName_, inputPassName_, iSOI_, ldmx::HcalID::layer(), MeV_, nADCs_, noise_, noiseGenerator_, noiseInjector_, ldmx::DetectorID::raw(), ldmx::HgcrocDigiCollection::setNumSamplesPerDigi(), ldmx::HgcrocDigiCollection::setSampleOfInterestIndex(), ldmx::HcalID::strip(), and ldmx::SimCalorimeterHit::Contrib::time.
Member Data Documentation
noise_
bool hcal::HcalDigiProducer::noise_ {true} private
Put noise into empty channels, not configurable, only helpful in development
Definition at line 85 of file HcalDigiProducer.h.
Referenced by configure(), and produce().
The documentation for this class was generated from the following files:
Hcal/include/Hcal/HcalDigiProducer.h
Hcal/src/Hcal/HcalDigiProducer.cxx