LDMX Software: dqm::Trigger Class Reference
dqm::Trigger Class Reference
Generate histograms to check digi pipeline performance.
#include <Trigger.h>
Public Member Functions
Trigger (const std::string &name, framework::Process &process)
virtual void configure (framework::config::Parameters &ps)
virtual void onProcessStart ()
virtual void analyze (const framework::Event &event)
Public Member Functions inherited from framework::Analyzer
Analyzer (const std::string &name, Process &process)
Public Member Functions inherited from framework::EventProcessor
EventProcessor (const std::string &name, Process &process)
virtual ~EventProcessor ()
virtual void onNewRun (const ldmx::RunHeader &runHeader)
virtual void onFileOpen (EventFile &eventFile)
virtual void onFileClose (EventFile &eventFile)
virtual void onProcessEnd ()
template<class T >
const T & getCondition (const std::string &condition_name)
TDirectory * getHistoDirectory ()
void setStorageHint (framework::StorageControlHint hint)
void setStorageHint (framework::StorageControlHint hint, const std::string &purposeString)
int getLogFrequency () const
int getRunNumber () const
std::string getName () const
void createHistograms (const std::vector< framework::config::Parameters > &histos)
Private Attributes
std::string trigger_collName_
Trigger collection name.
std::string trigger_passName_
Trigger collection pass name.
Additional Inherited Members
Static Public Member Functions inherited from framework::EventProcessor
static void declare (const std::string &classname, int classtype, EventProcessorMaker *)
Static Public Attributes inherited from framework::Analyzer
static const int CLASSTYPE {2}
Protected Member Functions inherited from framework::EventProcessor
void abortEvent ()
Protected Attributes inherited from framework::EventProcessor
HistogramHelper histograms_
Interface class for making and filling histograms.
NtupleManager & ntuple_ {NtupleManager::getInstance()}
Manager for any ntuples.
logging::logger theLog_
The logger for this EventProcessor.
Detailed Description
Generate histograms to check digi pipeline performance.
Definition at line 14 of file Trigger.h.
Constructor & Destructor Documentation
Trigger()
dqm::Trigger::Trigger (const std::string & name, framework::Process & process) inline
Constructor
Blank Analyzer constructor
Definition at line 21 of file Trigger.h.
      : framework::Analyzer(name, process) {}
Member Function Documentation
analyze()
void dqm::Trigger::analyze (const framework::Event & event) virtual
Fills histograms
Implements framework::Analyzer.
Definition at line 39 of file Trigger.cxx.
{
  auto trigResult{event.getObject<ldmx::TriggerResult>(trigger_collName_,
                                                  trigger_passName_)};
  histograms_.fill(trigger_collName_+".EcalEsum", trigResult.getAlgoVar(0) );
  histograms_.fill(trigger_collName_+".EcalEcut", trigResult.getAlgoVar(1) );
  histograms_.fill(trigger_collName_+".EcalLayercut", trigResult.getAlgoVar(2) );
  histograms_.fill(trigger_collName_+".nElectrons", trigResult.getAlgoVar(3) );
  histograms_.fill(trigger_collName_+".pass", trigResult.passed() );
  return;
}
References framework::HistogramHelper::fill(), framework::EventProcessor::histograms_, trigger_collName_, and trigger_passName_.
configure()
void dqm::Trigger::configure (framework::config::Parameters & ps) virtual
Input python configuration parameters
Reimplemented from framework::EventProcessor.
Definition at line 8 of file Trigger.cxx.
{
  trigger_collName_ = ps.getParameter<std::string>("trigger_name");
  trigger_passName_ = ps.getParameter<std::string>("trigger_pass");
  return;
}
References framework::config::Parameters::getParameter(), trigger_collName_, and trigger_passName_.
onProcessStart()
void dqm::Trigger::onProcessStart () virtual
Method executed before processing of events begins.
Reimplemented from framework::EventProcessor.
Definition at line 15 of file Trigger.cxx.
{
  getHistoDirectory();
  // create trigger variable histograms
  //pass/fail is a boolean, simple binning
  histograms_.create(trigger_collName_+".pass","Pass trigger",2,0,2);
  int maxE = 20000;
  int minE = 0;
  int nBinsE = (maxE-minE)/100;
  histograms_.create(trigger_collName_+".EcalEsum","Ecal energy sum [MeV]",nBinsE,minE,maxE);
  histograms_.create(trigger_collName_+".EcalEcut","Ecal E_{max} cut [MeV]",nBinsE,minE,maxE);
  int maxLayer = 32;
  int minLayer = 0;
  int nBinsLayer = (maxLayer-minLayer);
  histograms_.create(trigger_collName_+".EcalLayercut","Ecal layer_{max}",nBinsLayer,minLayer,maxLayer);
  int maxElectrons = 10;
  int minElectrons = 0;
  int nBinsElectrons = (maxElectrons-minElectrons);
  histograms_.create(trigger_collName_+".nElectrons","N_{electrons} used for trigger decision",nBinsElectrons,minElectrons,maxElectrons);
}
References framework::HistogramHelper::create(), framework::EventProcessor::getHistoDirectory(), framework::EventProcessor::histograms_, and trigger_collName_.
Member Data Documentation
trigger_collName_
std::string dqm::Trigger::trigger_collName_ private
Trigger collection name.
Definition at line 42 of file Trigger.h.
Referenced by analyze(), configure(), and onProcessStart().
trigger_passName_
std::string dqm::Trigger::trigger_passName_ private
Trigger collection pass name.
Definition at line 45 of file Trigger.h.
Referenced by analyze(), and configure().
The documentation for this class was generated from the following files:
DQM/include/DQM/Trigger.h
DQM/src/DQM/Trigger.cxx