LDMX Software: ldmx::UserEventAction Class Reference
ldmx::UserEventAction Class Reference
Implementation of user event action hook.
#include <UserEventAction.h>
Public Member Functions
UserEventAction ()
virtual ~UserEventAction ()
void BeginOfEventAction (const G4Event *event)
void EndOfEventAction (const G4Event *event)
void registerAction (UserAction *eventAction)
Private Attributes
std::vector< UserAction * > eventActions_
Detailed Description
Implementation of user event action hook.
Definition at line 34 of file UserEventAction.h.
Constructor & Destructor Documentation
UserEventAction()
ldmx::UserEventAction::UserEventAction () inline
Class constructor.
Definition at line 41 of file UserEventAction.h.
{
             }
~UserEventAction()
virtual ldmx::UserEventAction::~UserEventAction () inline virtual
Class destructor.
Definition at line 47 of file UserEventAction.h.
{
             }
Member Function Documentation
BeginOfEventAction()
void ldmx::UserEventAction::BeginOfEventAction (const G4Event * event)
Implementation of begin of event hook.
Parameters
event The Geant4 event.
Definition at line 31 of file UserEventAction.cxx.
{
         // Clear the global track map.
         UserTrackingAction::getUserTrackingAction()->getTrackMap()->clear();
         // Call user event actions
         for ( auto& eventAction : eventActions_ ) eventAction->BeginOfEventAction(event);
     }
References ldmx::TrackMap::clear(), ldmx::UserTrackingAction::getTrackMap(), and ldmx::UserTrackingAction::getUserTrackingAction().
EndOfEventAction()
void ldmx::UserEventAction::EndOfEventAction (const G4Event * event)
Implementation of end of event hook.
Parameters
event The Geant4 event.
Definition at line 40 of file UserEventAction.cxx.
{
         // Call user event actions
         for ( auto& eventAction : eventActions_ ) eventAction->EndOfEventAction(event);
     }
registerAction()
void ldmx::UserEventAction::registerAction (UserAction * eventAction) inline
Register a user action of type EventAction with this class.
Parameters
action User action of type EventAction
Definition at line 67 of file UserEventAction.h.
 { eventActions_.push_back(eventAction); }
The documentation for this class was generated from the following files:
SimCore/include/SimCore/UserEventAction.h
SimCore/src/UserEventAction.cxx