LDMX Software: ldmx::HgcrocDigiCollection::HgcrocDigi Class Reference
ldmx::HgcrocDigiCollection::HgcrocDigi Class Reference
#include <HgcrocDigiCollection.h>
Public Member Functions
HgcrocDigi (unsigned int id, std::vector< HgcrocDigiCollection::Sample >::const_iterator first, const HgcrocDigiCollection &collection)
unsigned int id () const
auto begin () const
auto end () const
bool isADC () const
bool isTOT () const
int tot () const
const HgcrocDigiCollection::Sample & soi () const
Private Attributes
unsigned int id_
channel ID where this signal is coming from
std::vector< HgcrocDigiCollection::Sample >::const_iterator first_
the location of the first sample that are in this digi
const HgcrocDigiCollection & collection_
Reference to collection that owns this DIGI.
Detailed Description
One DIGI signal coming from the HGC ROC
This stores the channel ID and the samples coming from a channel It really only makes sense to use this object when retrieving DIGIs from the collection. Do not try to make one of these yourself.
Definition at line 225 of file HgcrocDigiCollection.h.
Constructor & Destructor Documentation
HgcrocDigi()
ldmx::HgcrocDigiCollection::HgcrocDigi::HgcrocDigi (unsigned int id, std::vector< HgcrocDigiCollection::Sample >::const_iterator first, const HgcrocDigiCollection & collection) inline
Constructor
Passes required variables to this structure.
Parameters
[in] id global integer ID for the DIGI channel
[in] first iterator pointing to first sample of this DIGI in the collection
[in] collection const reference to the collection this DIGI references
Definition at line 238 of file HgcrocDigiCollection.h.
        : id_(id), first_(first), collection_(collection) {}
Member Function Documentation
begin()
auto ldmx::HgcrocDigiCollection::HgcrocDigi::begin () const inline
Get the starting iterator for looping through this DIGI
Returns
const vector iterator pointing to start of this DIGI
Definition at line 255 of file HgcrocDigiCollection.h.
{ return first_; }
References first_.
Referenced by hcal::HcalRecProducer::getTOA().
end()
auto ldmx::HgcrocDigiCollection::HgcrocDigi::end () const inline
Get the ending iterator for looping through this DIGI
Returns
const vector iterator pointing to end of this DIGI
Definition at line 262 of file HgcrocDigiCollection.h.
{ return first_ + collection_.getNumSamplesPerDigi(); }
References collection_, first_, and ldmx::HgcrocDigiCollection::getNumSamplesPerDigi().
Referenced by hcal::HcalRecProducer::getTOA().
id()
unsigned int ldmx::HgcrocDigiCollection::HgcrocDigi::id () const inline
Get the ID for this DIGI
Returns
global integer ID for this DIGI channel
Definition at line 248 of file HgcrocDigiCollection.h.
{ return id_; }
References id_.
Referenced by ecal::EcalTrigPrimDigiProducer::produce(), and hcal::HcalTrigPrimDigiProducer::produce().
isADC()
bool ldmx::HgcrocDigiCollection::HgcrocDigi::isADC () const inline
Check if this DIGI is an ADC measurement
We consider this DIGI an ADC measurement if both of the flags for the Sample Of Interest are false.
Returns
true if we consider this DIGI an ADC measurement
Definition at line 272 of file HgcrocDigiCollection.h.
                       {
      return !(soi().isTOTinProgress() or soi().isTOTComplete());
    }
References ldmx::HgcrocDigiCollection::Sample::isTOTComplete(), ldmx::HgcrocDigiCollection::Sample::isTOTinProgress(), and soi().
Referenced by hcal::test::HcalCheckReconstruction::analyze(), and isTOT().
isTOT()
bool ldmx::HgcrocDigiCollection::HgcrocDigi::isTOT () const inline
Check if this DIGI is a TOT measurement
Note
Just NOT an ADC measurement right now. May need to include the callibration case in the future.
Returns
true if this DIGI is a TOT measurement
Definition at line 284 of file HgcrocDigiCollection.h.
{ return !isADC(); }
References isADC().
Referenced by tot().
soi()
const HgcrocDigiCollection::Sample & ldmx::HgcrocDigiCollection::HgcrocDigi::soi () const inline
Get the sample of interest from this DIGI
Returns
Sample that is the sample of interest in this DIGI
Definition at line 306 of file HgcrocDigiCollection.h.
{
      return *(first_ + collection_.getSampleOfInterestIndex());
    }
References collection_, first_, and ldmx::HgcrocDigiCollection::getSampleOfInterestIndex().
Referenced by isADC(), ecal::EcalTrigPrimDigiProducer::produce(), hcal::HcalTrigPrimDigiProducer::produce(), and tot().
tot()
int ldmx::HgcrocDigiCollection::HgcrocDigi::tot () const inline
Get the 12-bit decoded TOT measurement from this DIGI
Note
Returns -1 if this DIGI is not TOT.
Returns -2 if this DIGI has a TOT in progress during the SOI.
Returns
12-bit TOT measurement
Definition at line 295 of file HgcrocDigiCollection.h.
                    {
      if (not isTOT()) return -1;
      if (soi().isTOTinProgress()) return -2;
      return soi().tot();
    }
References isTOT(), soi(), and ldmx::HgcrocDigiCollection::Sample::tot().
Member Data Documentation
collection_
const HgcrocDigiCollection& ldmx::HgcrocDigiCollection::HgcrocDigi::collection_ private
Reference to collection that owns this DIGI.
Definition at line 318 of file HgcrocDigiCollection.h.
Referenced by end(), and soi().
first_
std::vector<HgcrocDigiCollection::Sample>::const_iterator ldmx::HgcrocDigiCollection::HgcrocDigi::first_ private
the location of the first sample that are in this digi
Definition at line 315 of file HgcrocDigiCollection.h.
Referenced by begin(), end(), and soi().
id_
unsigned int ldmx::HgcrocDigiCollection::HgcrocDigi::id_ private
channel ID where this signal is coming from
Definition at line 312 of file HgcrocDigiCollection.h.
Referenced by id().
The documentation for this class was generated from the following file:
Recon/include/Recon/Event/HgcrocDigiCollection.h