LDMX Software: simcore::generators::ParticleGun Class Reference
simcore::generators::ParticleGun Class Reference
Class that extends the functionality of G4ParticleGun.
#include <ParticleGun.h>
Public Member Functions
ParticleGun (const std::string &name, const framework::config::Parameters &parameters)
~ParticleGun ()
Destructor.
void GeneratePrimaryVertex (G4Event *event) final override
void RecordConfig (const std::string &id, ldmx::RunHeader &rh) final override
Public Member Functions inherited from simcore::PrimaryGenerator
PrimaryGenerator (const std::string &name, const framework::config::Parameters &parameters)
virtual ~PrimaryGenerator ()
Destructor.
virtual void GeneratePrimaryVertex (G4Event *)=0
virtual void RecordConfig (const std::string &id, ldmx::RunHeader &rh)=0
Private Attributes
G4ParticleGun theGun_
int verbosity_
Additional Inherited Members
Public Types inherited from simcore::PrimaryGenerator
using Factory = ::simcore::Factory< PrimaryGenerator, std::shared_ptr< PrimaryGenerator >, const std::string &, const framework::config::Parameters & >
Factory for primary generators.
Protected Attributes inherited from simcore::PrimaryGenerator
std::string name_ {""}
Name of the PrimaryGenerator.
Detailed Description
Class that extends the functionality of G4ParticleGun.
Definition at line 31 of file ParticleGun.h.
Constructor & Destructor Documentation
ParticleGun()
simcore::generators::ParticleGun::ParticleGun (const std::string & name, const framework::config::Parameters & parameters)
Constructor.
Parameters
parameters Parameters used to configure the particle gun.
Parameters: verbosity: > 1 means print configuration particle : name of particle to shoot (Geant4 naming) energy : energy of particle (GeV) position : position to shoot from (mm three-vector) time : time to shoot at (ns) direction: direction to shoot in (unitless three-vector)
Definition at line 31 of file ParticleGun.cxx.
    : PrimaryGenerator(name, parameters) {
  verbosity_ = parameters.getParameter<int>("verbosity");
  auto particleTable{G4ParticleTable::GetParticleTable()};
  auto particle{parameters.getParameter<std::string>("particle")};
  if (auto particleDef{particleTable->FindParticle(particle)};
      particleDef != 0) {
    if (verbosity_ > 1) {
      std::cout << "[ ParticleGun ] : Firing particle of type " << particle
                << std::endl;
    }
    theGun_.SetParticleDefinition(particleDef);
  }
  auto energy{parameters.getParameter<double>("energy")};
  if (verbosity_ > 1) {
    std::cout << "[ ParticleGun ] : Setting energy to " << energy * GeV
              << std::endl;
  }
  theGun_.SetParticleEnergy(energy * GeV);
  auto position{parameters.getParameter<std::vector<double> >("position")};
  if (!position.empty()) {
    G4ThreeVector pVec(position[0] * mm, position[1] * mm, position[2] * mm);
    if (verbosity_ > 1) {
      std::cout << "[ ParticleGun ] : position " << pVec << std::endl;
    }
    theGun_.SetParticlePosition(pVec);
  }
  auto time{parameters.getParameter<double>("time")};
  if (time < 0) time = 0.0;
  if (verbosity_ > 1) {
    std::cout << "[ ParticleGun ] : Setting particle time  to " << time
              << std::endl;
  }
  theGun_.SetParticleTime(time * ns);
  auto direction{parameters.getParameter<std::vector<double> >("direction")};
  if (!direction.empty()) {
    G4ThreeVector dVec(direction[0], direction[1], direction[2]);
    if (verbosity_ > 1) {
      std::cout << "[ ParticleGun ] : direction " << dVec.unit() << std::endl;
    }
    theGun_.SetParticleMomentumDirection(dVec);
  }
}
References framework::config::Parameters::getParameter(), theGun_, and verbosity_.
~ParticleGun()
simcore::generators::ParticleGun::~ParticleGun ()
Destructor.
Definition at line 82 of file ParticleGun.cxx.
{}
Member Function Documentation
GeneratePrimaryVertex()
void simcore::generators::ParticleGun::GeneratePrimaryVertex (G4Event * event) final override virtual
Generate the primary vertices in the Geant4 event.
Parameters
event The Geant4 event.
Implements simcore::PrimaryGenerator.
Definition at line 84 of file ParticleGun.cxx.
{
  // Call G4 class method to generate primaries.
  theGun_.GeneratePrimaryVertex(event);
}
References theGun_.
RecordConfig()
void simcore::generators::ParticleGun::RecordConfig (const std::string & id, ldmx::RunHeader & rh) final override virtual
Record the configuration of the primary generator into the run header
Note
you must include the id number in each entry into the run header just in case there are other generators
Implements simcore::PrimaryGenerator.
Definition at line 89 of file ParticleGun.cxx.
{
  rh.setStringParameter(id + " Class", "simcore::generators::ParticleGun");
  rh.setFloatParameter(id + " Time [ns]", theGun_.GetParticleTime());
  rh.setFloatParameter(id + " Energy [GeV]", theGun_.GetParticleEnergy()/GeV);
  rh.setStringParameter(id + " Particle", theGun_.GetParticleDefinition()->GetParticleName());
  rh.setFloatParameter(id + " X [mm]", theGun_.GetParticlePosition().x());
  rh.setFloatParameter(id + " Y [mm]", theGun_.GetParticlePosition().y());
  rh.setFloatParameter(id + " Z [mm]", theGun_.GetParticlePosition().z());
  rh.setFloatParameter(id + " Direction X", theGun_.GetParticleMomentumDirection().x());
  rh.setFloatParameter(id + " Direction Y", theGun_.GetParticleMomentumDirection().y());
  rh.setFloatParameter(id + " Direction Z", theGun_.GetParticleMomentumDirection().z());
}
References ldmx::RunHeader::setFloatParameter(), ldmx::RunHeader::setStringParameter(), and theGun_.
Member Data Documentation
theGun_
G4ParticleGun simcore::generators::ParticleGun::theGun_ private
The actual Geant4 implementation of the ParticleGun
Definition at line 64 of file ParticleGun.h.
Referenced by GeneratePrimaryVertex(), ParticleGun(), and RecordConfig().
verbosity_
int simcore::generators::ParticleGun::verbosity_ private
LDMX Verbosity for this generator
Definition at line 69 of file ParticleGun.h.
Referenced by ParticleGun().
The documentation for this class was generated from the following files:
SimCore/include/SimCore/Generators/ParticleGun.h
SimCore/src/SimCore/Generators/ParticleGun.cxx