LDMX Software: ecal::EcalGeometryProvider Class Reference
ecal::EcalGeometryProvider Class Reference
Public Member Functions
EcalGeometryProvider (const std::string &name, const std::string &tagname, const framework::config::Parameters &parameters, framework::Process &process)
virtual ~EcalGeometryProvider ()
virtual std::pair< const framework::ConditionsObject *, framework::ConditionsIOV > getCondition (const ldmx::EventHeader &context)
virtual void releaseConditionsObject (const framework::ConditionsObject *co)
virtual void onNewRun (ldmx::RunHeader &rh)
Public Member Functions inherited from framework::ConditionsObjectProvider
ConditionsObjectProvider (const std::string &objname, const std::string &tagname, const framework::config::Parameters &parameters, Process &process)
virtual ~ConditionsObjectProvider ()
virtual std::pair< const ConditionsObject *, ConditionsIOV > getCondition (const ldmx::EventHeader &context)=0
virtual void releaseConditionsObject (const ConditionsObject *co)
virtual void onProcessStart ()
virtual void onProcessEnd ()
virtual void onNewRun (ldmx::RunHeader &)
const std::string & getConditionObjectName () const
const std::string & getTagName () const
Private Attributes
framework::config::Parameters params_
std::string detectorGeometry_
ldmx::EcalHexReadout * ecalGeometry_
Additional Inherited Members
Static Public Member Functions inherited from framework::ConditionsObjectProvider
static void declare (const std::string &classname, ConditionsObjectProviderMaker *)
Static Public Attributes inherited from framework::ConditionsObjectProvider
static const int CLASSTYPE {10}
Protected Member Functions inherited from framework::ConditionsObjectProvider
std::pair< const ConditionsObject *, ConditionsIOV > requestParentCondition (const std::string &name, const ldmx::EventHeader &context)
const Process & process () const
Protected Attributes inherited from framework::ConditionsObjectProvider
logging::logger theLog_
The logger for this ConditionsObjectProvider.
Detailed Description
Definition at line 16 of file EcalGeometryProvider.cxx.
Constructor & Destructor Documentation
EcalGeometryProvider()
ecal::EcalGeometryProvider::EcalGeometryProvider (const std::string & name, const std::string & tagname, const framework::config::Parameters & parameters, framework::Process & process)
Class constructor
Parameters
parameters – uses the "EcalHexReadout" section to configure the EcalHexReadout
Definition at line 71 of file EcalGeometryProvider.cxx.
    : framework::
          ConditionsObjectProvider{ldmx::EcalHexReadout::CONDITIONS_OBJECT_NAME,
                                   tagname, parameters, process},
      params_{parameters} {
  ecalGeometry_ = 0;
}
~EcalGeometryProvider()
ecal::EcalGeometryProvider::~EcalGeometryProvider () virtual
Destructor
Definition at line 82 of file EcalGeometryProvider.cxx.
{
  if (ecalGeometry_) delete ecalGeometry_;
  ecalGeometry_ = 0;
}
Member Function Documentation
getCondition()
std::pair< const framework::ConditionsObject *, framework::ConditionsIOV > ecal::EcalGeometryProvider::getCondition (const ldmx::EventHeader & context) virtual
Provides access to the EcalHexReadout or EcalTriggerGeometry
Note
Currently, these are assumed to be valid for all time, but this behavior could be changed. Users should not cache the pointer between events
Implements framework::ConditionsObjectProvider.
Definition at line 88 of file EcalGeometryProvider.cxx.
{
  static const std::string KEYNAME("detectors_valid");
  if (!ecalGeometry_) {
    framework::config::Parameters phex =
        (params_.exists("EcalHexReadout"))
            ? (params_.getParameter<framework::config::Parameters>(
                  "EcalHexReadout"))
            : (params_);
    // search through the subtrees
    for (auto key : phex.keys()) {
      framework::config::Parameters pver =
          phex.getParameter<framework::config::Parameters>(key);
      if (!pver.exists(KEYNAME)) {
        ldmx_log(warn) << "No parameter " << KEYNAME << " found in " << key;
        // log strange situation and continue
        continue;
      }
      std::vector<std::string> dets_valid =
          pver.getParameter<std::vector<std::string> >(KEYNAME);
      for (auto detregex : dets_valid) {
        std::string regex(detregex);
        if (regex.empty()) continue;  // no empty regex allowed
        if (regex[0] != '^') regex.insert(0, 1, '^');
        if (regex.back() != '$') regex += '$';
        regex_t reg;
        int rv =
            regcomp(&reg, regex.c_str(), REG_EXTENDED | REG_ICASE | REG_NOSUB);
        if (rv) {
          char err[1024];
          regerror(rv, &reg, err, 1024);
          EXCEPTION_RAISE(
              "GeometryException",
              "Invalid detector regular expression : '" + regex + "' " + err);
        }
        int nmatch = regexec(&reg, detectorGeometry_.c_str(), 0, 0, 0);
        regfree(&reg);
        if (!nmatch) {
          ecalGeometry_ = new ldmx::EcalHexReadout(pver);
          break;
        }
      }
      if (ecalGeometry_) break;
    }
    if (!ecalGeometry_) {
      EXCEPTION_RAISE("GeometryException", "Unable to create EcalHexReadout");
    }
  }
  return std::make_pair(
      ecalGeometry_,
      framework::ConditionsIOV(context.getRun(), context.getRun(), true, true));
}
References detectorGeometry_, framework::config::Parameters::exists(), framework::config::Parameters::getParameter(), ldmx::EventHeader::getRun(), framework::config::Parameters::keys(), and params_.
onNewRun()
virtual void ecal::EcalGeometryProvider::onNewRun (ldmx::RunHeader &) inline virtual
Callback for the ConditionsObjectProvider to take any necessary action when the processing of events starts for a given run.
Reimplemented from framework::ConditionsObjectProvider.
Definition at line 46 of file EcalGeometryProvider.cxx.
{
    if (detectorGeometry_.empty())
      detectorGeometry_ = rh.getDetectorName();
    else if (ecalGeometry_ != nullptr &&
             detectorGeometry_ != rh.getDetectorName()) {
      EXCEPTION_RAISE(
          "GeometryException",
          "Attempting to run a single job with multiple geometries " +
              detectorGeometry_ + " and '" + rh.getDetectorName() + "'");
    }
    // make sure detector name has been set
    if (detectorGeometry_.empty())
      EXCEPTION_RAISE("GeometryException",
                      "EcalGeometryProvider unable to get the name of the "
                      "detector from the RunHeader.");
  }
References detectorGeometry_, and ldmx::RunHeader::getDetectorName().
releaseConditionsObject()
virtual void ecal::EcalGeometryProvider::releaseConditionsObject (const framework::ConditionsObject * co) inline virtual
Take no action on release, as the object is permanently owned by the Provider
Reimplemented from framework::ConditionsObjectProvider.
Definition at line 44 of file EcalGeometryProvider.cxx.
{}
Member Data Documentation
detectorGeometry_
std::string ecal::EcalGeometryProvider::detectorGeometry_ private
Geometry as last used
Definition at line 67 of file EcalGeometryProvider.cxx.
Referenced by getCondition(), and onNewRun().
ecalGeometry_
ldmx::EcalHexReadout* ecal::EcalGeometryProvider::ecalGeometry_ private
Definition at line 68 of file EcalGeometryProvider.cxx.
params_
framework::config::Parameters ecal::EcalGeometryProvider::params_ private
Handle to the parameters, needed for future use during get condition
Definition at line 65 of file EcalGeometryProvider.cxx.
Referenced by getCondition().
The documentation for this class was generated from the following file:
Ecal/src/Ecal/EcalGeometryProvider.cxx