LDMX Software: hcal::HcalTrigPrimDigiProducer Class Reference
hcal::HcalTrigPrimDigiProducer Class Reference
Performs basic Hcal trigger reconstruction.
#include <HcalTrigPrimDigiProducer.h>
Public Member Functions
HcalTrigPrimDigiProducer (const std::string &name, framework::Process &process)
virtual void configure (framework::config::Parameters &)
virtual void produce (framework::Event &event)
Public Member Functions inherited from framework::Producer
Producer (const std::string &name, Process &process)
virtual void produce (Event &event)=0
virtual void beforeNewRun (ldmx::RunHeader &header)
Public Member Functions inherited from framework::EventProcessor
EventProcessor (const std::string &name, Process &process)
virtual ~EventProcessor ()
virtual void configure (framework::config::Parameters &parameters)
virtual void onNewRun (const ldmx::RunHeader &runHeader)
virtual void onFileOpen (EventFile &eventFile)
virtual void onFileClose (EventFile &eventFile)
virtual void onProcessStart ()
virtual void onProcessEnd ()
template<class T >
const T & getCondition (const std::string &condition_name)
TDirectory * getHistoDirectory ()
void setStorageHint (framework::StorageControlHint hint)
void setStorageHint (framework::StorageControlHint hint, const std::string &purposeString)
int getLogFrequency () const
int getRunNumber () const
std::string getName () const
void createHistograms (const std::vector< framework::config::Parameters > &histos)
Private Attributes
std::string digiCollName_
std::string digiPassName_
std::string condObjName_
std::map< unsigned int, unsigned int > stq_tps
Additional Inherited Members
Static Public Member Functions inherited from framework::EventProcessor
static void declare (const std::string &classname, int classtype, EventProcessorMaker *)
Static Public Attributes inherited from framework::Producer
static const int CLASSTYPE {1}
Protected Member Functions inherited from framework::EventProcessor
void abortEvent ()
Protected Attributes inherited from framework::EventProcessor
HistogramHelper histograms_
Interface class for making and filling histograms.
NtupleManager & ntuple_ {NtupleManager::getInstance()}
Manager for any ntuples.
logging::logger theLog_
The logger for this EventProcessor.
Detailed Description
Performs basic Hcal trigger reconstruction.
Definition at line 15 of file HcalTrigPrimDigiProducer.h.
Constructor & Destructor Documentation
HcalTrigPrimDigiProducer()
hcal::HcalTrigPrimDigiProducer::HcalTrigPrimDigiProducer (const std::string & name, framework::Process & process)
Constructor
Definition at line 11 of file HcalTrigPrimDigiProducer.cxx.
    : Producer(name, process) {}
Member Function Documentation
configure()
void hcal::HcalTrigPrimDigiProducer::configure (framework::config::Parameters & ps) virtual
Grabs configure parameters from the python config file.
Parameter Default digiCollName HcalDigis digiPassName "" <– blank means take any pass if only one collection exists
Reimplemented from framework::EventProcessor.
Definition at line 15 of file HcalTrigPrimDigiProducer.cxx.
{
  digiCollName_ = ps.getParameter<std::string>("digiCollName");
  digiPassName_ = ps.getParameter<std::string>("digiPassName");
  condObjName_ =
      ps.getParameter<std::string>("condObjName", "HcalTrigPrimDigiConditions");
}
References condObjName_, digiCollName_, digiPassName_, and framework::config::Parameters::getParameter().
produce()
void hcal::HcalTrigPrimDigiProducer::produce (framework::Event & event) virtual
Produce HcalTrigPrimDigis and put them into the event bus using the HcalDigis as input.
Implements framework::Producer.
Definition at line 22 of file HcalTrigPrimDigiProducer.cxx.
{
  const HcalTriggerGeometry& geom = getCondition<HcalTriggerGeometry>(
      HcalTriggerGeometry::CONDITIONS_OBJECT_NAME);
  const ldmx::HgcrocDigiCollection& hcalDigis =
      event.getObject<ldmx::HgcrocDigiCollection>(digiCollName_, digiPassName_);
  // get the calibration object
  const conditions::IntegerTableCondition& conditions =
      getCondition<conditions::IntegerTableCondition>(condObjName_);
  // construct the calculator...
  ldmx::HgcrocTriggerCalculations calc(conditions);
  // Loop over the digis
  for (unsigned int ix = 0; ix < hcalDigis.getNumDigis(); ix++) {
    const ldmx::HgcrocDigiCollection::HgcrocDigi pdigi = hcalDigis.getDigi(ix);
    ldmx::HcalTriggerID tid = geom.belongsToQuad(ldmx::HcalDigiID(pdigi.id()));
    if (!tid.null()) {
      int tot = 0;
      if (pdigi.soi().isTOTComplete()) tot = pdigi.soi().tot();
      calc.addDigi(pdigi.id(), tid.raw(), pdigi.soi().adc_t(), tot);
    }
  }
  // Now, we compress the digis
  calc.compressDigis(4);
  const float hgc_compress_factor = 2;
  // const std::map<unsigned int, uint8_t> results;
  const std::map<unsigned int, uint8_t>& results = calc.compressedEnergies();
  ldmx::HgcrocTrigDigiCollection tdigis;
  // ldmx::CaloTrigPrimCollection tdigisUC; // sums without any compression
  // applied
  for (auto result : results) {
    if (result.second > 0) {
      tdigis.push_back(ldmx::HgcrocTrigDigi(result.first, result.second));
      // tdigisUC.push_back( ldmx::CaloTrigPrim(result.first,
      //         hgc_compress_factor*ldmx::HgcrocTrigDigi::compressed2Linear(result.second))
      //         );
    }
  }
  // build STQs from the quads (w/ compressed energies)
  stq_tps.clear();
  for (auto result : results) {
    if (result.second > 0) {
      const ldmx::HcalTriggerID quad_id(result.first);
      const std::vector<ldmx::HcalDigiID> precisions_ids =
          geom.contentsOfQuad(quad_id);
      if (precisions_ids.size() == 0) {
        std::cout << "Failing HcalTriggerID(" << quad_id.section() << ','
                  << quad_id.layer() << ',' << quad_id.superstrip() << ','
                  << quad_id.end() << ')' << std::endl;
        EXCEPTION_RAISE("TrigToPrecIDMismatch",
                        "Attempted to lookup a nonexistent HcalDigiID from an "
                        "HcalTriggerID");
      }
      const ldmx::HcalDigiID prec_id(precisions_ids.front().raw());
      const ldmx::HcalTriggerID stq_id = geom.belongsToSTQ(prec_id);
      auto ptr = stq_tps.find(stq_id.raw());
      int linear_charge =
          hgc_compress_factor *
          ldmx::HgcrocTrigDigi::compressed2Linear(result.second);
      if (ptr != stq_tps.end()) {
        ptr->second += linear_charge;
      } else {
        stq_tps[stq_id.raw()] = linear_charge;
      }
    }
  }
  ldmx::CaloTrigPrimCollection stq_digis;
  for (auto result : stq_tps) {
    if (result.second > 0) {
      stq_digis.push_back(ldmx::CaloTrigPrim(result.first, result.second));
    }
  }
  event.add(getName(), tdigis);
  // event.add(getName()+"Uncompress", tdigisUC);
  event.add("hcalTrigPrimDigiSTQs", stq_digis);
}
References ldmx::HgcrocDigiCollection::Sample::adc_t(), ldmx::HgcrocTriggerCalculations::addDigi(), hcal::HcalTriggerGeometry::belongsToQuad(), ldmx::HgcrocTriggerCalculations::compressDigis(), ldmx::HgcrocTrigDigi::compressed2Linear(), ldmx::HgcrocTriggerCalculations::compressedEnergies(), condObjName_, hcal::HcalTriggerGeometry::contentsOfQuad(), digiCollName_, digiPassName_, ldmx::HcalTriggerID::end(), ldmx::HgcrocDigiCollection::getDigi(), framework::EventProcessor::getName(), ldmx::HgcrocDigiCollection::getNumDigis(), ldmx::HgcrocDigiCollection::HgcrocDigi::id(), ldmx::HgcrocDigiCollection::Sample::isTOTComplete(), ldmx::HcalTriggerID::layer(), ldmx::DetectorID::null(), ldmx::DetectorID::raw(), ldmx::HgcrocDigiCollection::HgcrocDigi::soi(), stq_tps, ldmx::HcalTriggerID::superstrip(), and ldmx::HgcrocDigiCollection::Sample::tot().
Member Data Documentation
condObjName_
std::string hcal::HcalTrigPrimDigiProducer::condObjName_ private
Conditions object for the calibration information
Definition at line 47 of file HcalTrigPrimDigiProducer.h.
Referenced by configure(), and produce().
digiCollName_
std::string hcal::HcalTrigPrimDigiProducer::digiCollName_ private
Digi Collection Name to use as input
Definition at line 41 of file HcalTrigPrimDigiProducer.h.
Referenced by configure(), and produce().
digiPassName_
std::string hcal::HcalTrigPrimDigiProducer::digiPassName_ private
Digi Pass Name to use as input
Definition at line 44 of file HcalTrigPrimDigiProducer.h.
Referenced by configure(), and produce().
stq_tps
std::map<unsigned int, unsigned int> hcal::HcalTrigPrimDigiProducer::stq_tps private
map of digis to the super trigger primitives
Definition at line 50 of file HcalTrigPrimDigiProducer.h.
Referenced by produce().
The documentation for this class was generated from the following files:
Hcal/include/Hcal/HcalTrigPrimDigiProducer.h
Hcal/src/Hcal/HcalTrigPrimDigiProducer.cxx