LDMX Software: hcal::HcalGeometryProvider Class Reference
hcal::HcalGeometryProvider Class Reference
Public Member Functions
HcalGeometryProvider (const std::string &name, const std::string &tagname, const framework::config::Parameters &parameters, framework::Process &process)
virtual ~HcalGeometryProvider ()
virtual std::pair< const framework::ConditionsObject *, framework::ConditionsIOV > getCondition (const ldmx::EventHeader &context)
virtual void releaseConditionsObject (const framework::ConditionsObject *co)
virtual void onNewRun (ldmx::RunHeader &rh)
Public Member Functions inherited from framework::ConditionsObjectProvider
ConditionsObjectProvider (const std::string &objname, const std::string &tagname, const framework::config::Parameters &parameters, Process &process)
virtual ~ConditionsObjectProvider ()
virtual void onProcessStart ()
virtual void onProcessEnd ()
const std::string & getConditionObjectName () const
const std::string & getTagName () const
Private Attributes
framework::config::Parameters params_
std::string detectorGeometry_
ldmx::HcalGeometry * hcalGeometry_
Additional Inherited Members
Static Public Member Functions inherited from framework::ConditionsObjectProvider
static void declare (const std::string &classname, ConditionsObjectProviderMaker *)
Static Public Attributes inherited from framework::ConditionsObjectProvider
static const int CLASSTYPE {10}
Protected Member Functions inherited from framework::ConditionsObjectProvider
std::pair< const ConditionsObject *, ConditionsIOV > requestParentCondition (const std::string &name, const ldmx::EventHeader &context)
const Process & process () const
Protected Attributes inherited from framework::ConditionsObjectProvider
logging::logger theLog_
The logger for this ConditionsObjectProvider.
Detailed Description
Definition at line 18 of file HcalGeometryProvider.cxx.
Constructor & Destructor Documentation
HcalGeometryProvider()
hcal::HcalGeometryProvider::HcalGeometryProvider (const std::string & name, const std::string & tagname, const framework::config::Parameters & parameters, framework::Process & process)
Class constructor
Parameters
parameters – uses the "HcalGeometry" section to configure the HcalGeometry
Definition at line 73 of file HcalGeometryProvider.cxx.
     : framework::
           ConditionsObjectProvider{ldmx::HcalGeometry::CONDITIONS_OBJECT_NAME,
                                    tagname, parameters, process},
       params_{parameters} {
   hcalGeometry_ = 0;
 }
~HcalGeometryProvider()
hcal::HcalGeometryProvider::~HcalGeometryProvider () virtual
Destructor
Definition at line 84 of file HcalGeometryProvider.cxx.
{
   if (hcalGeometry_) delete hcalGeometry_;
   hcalGeometry_ = 0;
 }
Member Function Documentation
getCondition()
std::pair< const framework::ConditionsObject *, framework::ConditionsIOV > hcal::HcalGeometryProvider::getCondition (const ldmx::EventHeader & context) virtual
Provides access to the HcalGeometry
Note
Currently, these are assumed to be valid for all time, but this behavior could be changed. Users should not cache the pointer between events
Implements framework::ConditionsObjectProvider.
Definition at line 90 of file HcalGeometryProvider.cxx.
{
   static const std::string KEYNAME("detectors_valid");
   if (!hcalGeometry_) {
     framework::config::Parameters phex =
         (params_.exists("HcalGeometry"))
             ? (params_.getParameter<framework::config::Parameters>(
                   "HcalGeometry"))
             : (params_);
     // search through the subtrees
     for (auto key : phex.keys()) {
       framework::config::Parameters pver =
           phex.getParameter<framework::config::Parameters>(key);
       if (!pver.exists(KEYNAME)) {
         ldmx_log(warn) << "No parameter " << KEYNAME << " found in " << key;
         // log strange situation and continue
         continue;
       }
       std::vector<std::string> dets_valid =
           pver.getParameter<std::vector<std::string> >(KEYNAME);
       for (auto detregex : dets_valid) {
         std::string regex(detregex);
         if (regex.empty()) continue;  // no empty regex allowed
         if (regex[0] != '^') regex.insert(0, 1, '^');
         if (regex.back() != '$') regex += '$';
         regex_t reg;
         int rv =
             regcomp(&reg, regex.c_str(), REG_EXTENDED | REG_ICASE | REG_NOSUB);
         if (rv) {
           char err[1024];
           regerror(rv, &reg, err, 1024);
           EXCEPTION_RAISE(
               "GeometryException",
               "Invalid detector regular expression : '" + regex + "' " + err);
         }
         int nmatch = regexec(&reg, detectorGeometry_.c_str(), 0, 0, 0);
         regfree(&reg);
         if (!nmatch) {
           hcalGeometry_ = new ldmx::HcalGeometry(pver);
           break;
         }
       }
       if (hcalGeometry_) break;
     }
     if (!hcalGeometry_) {
       EXCEPTION_RAISE("GeometryException", "Unable to create HcalGeometry");
     }
   }
   return std::make_pair(
       hcalGeometry_,
       framework::ConditionsIOV(context.getRun(), context.getRun(), true, true));
 }
References detectorGeometry_, framework::config::Parameters::exists(), framework::config::Parameters::getParameter(), ldmx::EventHeader::getRun(), framework::config::Parameters::keys(), and params_.
onNewRun()
virtual void hcal::HcalGeometryProvider::onNewRun (ldmx::RunHeader &) inline virtual
Callback for the ConditionsObjectProvider to take any necessary action when the processing of events starts for a given run.
Reimplemented from framework::ConditionsObjectProvider.
Definition at line 48 of file HcalGeometryProvider.cxx.
{
     if (detectorGeometry_.empty())
       detectorGeometry_ = rh.getDetectorName();
     else if (hcalGeometry_ != nullptr &&
              detectorGeometry_ != rh.getDetectorName()) {
       EXCEPTION_RAISE(
           "GeometryException",
           "Attempting to run a single job with multiple geometries " +
               detectorGeometry_ + " and '" + rh.getDetectorName() + "'");
     }
     // make sure detector name has been set
     if (detectorGeometry_.empty())
       EXCEPTION_RAISE("GeometryException",
                       "HcalGeometryProvider unable to get the name of the "
                       "detector from the RunHeader.");
   }
References detectorGeometry_, and ldmx::RunHeader::getDetectorName().
releaseConditionsObject()
virtual void hcal::HcalGeometryProvider::releaseConditionsObject (const framework::ConditionsObject * co) inline virtual
Take no action on release, as the object is permanently owned by the Provider
Reimplemented from framework::ConditionsObjectProvider.
Definition at line 46 of file HcalGeometryProvider.cxx.
 {}
Member Data Documentation
detectorGeometry_
std::string hcal::HcalGeometryProvider::detectorGeometry_ private
Geometry as last used
Definition at line 69 of file HcalGeometryProvider.cxx.
Referenced by getCondition(), and onNewRun().
params_
framework::config::Parameters hcal::HcalGeometryProvider::params_ private
Handle to the parameters, needed for future use during get condition
Definition at line 67 of file HcalGeometryProvider.cxx.
Referenced by getCondition().
The documentation for this class was generated from the following file:
Hcal/src/Hcal/HcalGeometryProvider.cxx