LDMX Software: ldmx::RunHeader Class Reference
ldmx::RunHeader Class Reference
Public Member Functions
RunHeader (int runNumber)
RunHeader ()
virtual ~RunHeader ()
int getRunNumber () const
const std::string & getDetectorName () const
void setDetectorName (const std::string &det)
const std::string & getSoftwareTag () const
const std::string & getDescription () const
void setDescription (const std::string &des)
int getRunStart () const
void setRunStart (const int runStart)
int getRunEnd () const
void setRunEnd (const int runEnd)
int getIntParameter (const std::string &name) const
const std::map< std::string, int > & getIntParameters () const
Get a const reference to all int parameters.
void setIntParameter (const std::string &name, int value)
float getFloatParameter (const std::string &name) const
const std::map< std::string, float > & getFloatParameters () const
Get a const reference to all float parameters.
void setFloatParameter (const std::string &name, float value)
std::string getStringParameter (const std::string &name) const
const std::map< std::string, std::string > & getStringParameters () const
Get a const reference to all string parameters.
void setStringParameter (const std::string &name, std::string value)
void stream (std::ostream &s) const
void Print () const
Private Member Functions
ClassDef (RunHeader, 3)
Private Attributes
int runNumber_ {0}
std::string detectorName_ {""}
std::string description_ {""}
int runStart_ {0}
Run start in seconds since epoch.
int runEnd_ {0}
Run end in seconds since epoch.
std::string softwareTag_ {GIT_SHA1}
std::map< std::string, int > intParameters_
std::map< std::string, float > floatParameters_
std::map< std::string, std::string > stringParameters_
Friends
std::ostream & operator<< (std::ostream &s, const ldmx::RunHeader &h)
Detailed Description
Definition at line 22 of file RunHeader.h.
Constructor & Destructor Documentation
RunHeader() [1/2]
ldmx::RunHeader::RunHeader (int runNumber)
Constructor.
Parameters
runNumber The run number uniquely identifying this run
Definition at line 13 of file RunHeader.cxx.
: runNumber_(runNumber) {}
RunHeader() [2/2]
ldmx::RunHeader::RunHeader () inline
Default constructor.
Note
This exists for filling the object from a ROOT branch.
Definition at line 36 of file RunHeader.h.
{}
~RunHeader()
virtual ldmx::RunHeader::~RunHeader () inline virtual
Destructor.
Definition at line 39 of file RunHeader.h.
{}
Member Function Documentation
getDescription()
const std::string & ldmx::RunHeader::getDescription () const inline
Returns
A short description of the run.
Definition at line 57 of file RunHeader.h.
{ return description_; }
References description_.
Referenced by stream().
getDetectorName()
const std::string & ldmx::RunHeader::getDetectorName () const inline
Returns
The name of the detector used to create the events.
Definition at line 45 of file RunHeader.h.
{ return detectorName_; }
References detectorName_.
Referenced by ecal::EcalGeometryProvider::onNewRun(), hcal::HcalGeometryProvider::onNewRun(), and stream().
getFloatParameter()
float ldmx::RunHeader::getFloatParameter (const std::string & name) const inline
Get a float parameter value.
Parameters
name The name of the parameter.
Returns
value The parameter value.
Definition at line 122 of file RunHeader.h.
{
    return floatParameters_.at(name);
  }
References floatParameters_.
getFloatParameters()
const std::map< std::string, float > & ldmx::RunHeader::getFloatParameters () const inline
Get a const reference to all float parameters.
Definition at line 127 of file RunHeader.h.
{
    return floatParameters_;
  }
References floatParameters_.
getIntParameter()
int ldmx::RunHeader::getIntParameter (const std::string & name) const inline
Get an int parameter value.
Parameters
name The name of the parameter.
Returns
The parameter value.
Definition at line 97 of file RunHeader.h.
{
    return intParameters_.at(name);
  }
References intParameters_.
getIntParameters()
const std::map< std::string, int > & ldmx::RunHeader::getIntParameters () const inline
Get a const reference to all int parameters.
Definition at line 102 of file RunHeader.h.
{
    return intParameters_;
  }
References intParameters_.
getRunEnd()
int ldmx::RunHeader::getRunEnd () const inline
Get the end time of the run in seconds since epoch.
Returns
The end time of the run.
Definition at line 82 of file RunHeader.h.
{ return runEnd_; }
References runEnd_.
getRunNumber()
int ldmx::RunHeader::getRunNumber () const inline
Returns
The run number.
Definition at line 42 of file RunHeader.h.
{ return runNumber_; }
References runNumber_.
Referenced by framework::RandomNumberSeedService::onNewRun(), stream(), packing::rawdatafile::File::writeRunHeader(), and framework::EventFile::writeRunHeader().
getRunStart()
int ldmx::RunHeader::getRunStart () const inline
Get the start time of the run in seconds since epoch.
Returns
The start time of the run.
Definition at line 68 of file RunHeader.h.
{ return runStart_; }
References runStart_.
getSoftwareTag()
const std::string & ldmx::RunHeader::getSoftwareTag () const inline
Returns
The git SHA-1 associated with the software tag used to generate this file.
Definition at line 54 of file RunHeader.h.
{ return softwareTag_; }
References softwareTag_.
getStringParameter()
std::string ldmx::RunHeader::getStringParameter (const std::string & name) const inline
Get a string parameter value.
Parameters
name The name of the parameter.
Returns
value The parameter value.
Definition at line 147 of file RunHeader.h.
{
    return stringParameters_.at(name);
  }
References stringParameters_.
getStringParameters()
const std::map< std::string, std::string > & ldmx::RunHeader::getStringParameters () const inline
Get a const reference to all string parameters.
Definition at line 152 of file RunHeader.h.
{
    return stringParameters_;
  }
References stringParameters_.
Print()
void ldmx::RunHeader::Print () const
Print a string desciption of this object.
Definition at line 34 of file RunHeader.cxx.
{ stream(std::cout); }
References stream().
setDescription()
void ldmx::RunHeader::setDescription (const std::string & des) inline
Set the description of this run
Definition at line 60 of file RunHeader.h.
{ description_ = des; }
References description_.
Referenced by simcore::Simulator::beforeNewRun().
setDetectorName()
void ldmx::RunHeader::setDetectorName (const std::string & det) inline
Set the name of the detector that was used in this run
Definition at line 48 of file RunHeader.h.
{ detectorName_ = det; }
References detectorName_.
Referenced by ecal::test::EcalFakeSimHits::beforeNewRun(), hcal::test::HcalFakeSimHits::beforeNewRun(), simcore::Simulator::beforeNewRun(), hcal::HcalRawDecoder::beforeNewRun(), and packing::SingleSubsystemUnpacker::beforeNewRun().
setFloatParameter()
void ldmx::RunHeader::setFloatParameter (const std::string & name, float value) inline
Set a float parameter value.
Parameters
name The name of the parameter.
value The parameter value.
Definition at line 137 of file RunHeader.h.
{
    floatParameters_[name] = value;
  }
References floatParameters_.
Referenced by simcore::Simulator::beforeNewRun(), simcore::biasoperators::PhotoNuclear::RecordConfig(), simcore::darkbrem::DarkBremVertexLibraryModel::RecordConfig(), simcore::darkbrem::G4eDarkBremsstrahlung::RecordConfig(), simcore::biasoperators::DarkBrem::RecordConfig(), simcore::biasoperators::ElectroNuclear::RecordConfig(), simcore::biasoperators::GammaToMuPair::RecordConfig(), simcore::biasoperators::K0LongInelastic::RecordConfig(), and simcore::biasoperators::NeutronInelastic::RecordConfig().
setIntParameter()
void ldmx::RunHeader::setIntParameter (const std::string & name, int value) inline
Set an int parameter value.
Parameters
name The name of the parameter.
value The value of the parameter.
Definition at line 112 of file RunHeader.h.
{
    intParameters_[name] = value;
  }
References intParameters_.
Referenced by simcore::Simulator::beforeNewRun(), framework::RandomNumberSeedService::onNewRun(), simcore::biasoperators::PhotoNuclear::RecordConfig(), simcore::darkbrem::G4eDarkBremsstrahlung::RecordConfig(), simcore::biasoperators::DarkBrem::RecordConfig(), simcore::persist::RootPersistencyManager::Store(), and packing::rawdatafile::File::writeRunHeader().
setRunEnd()
void ldmx::RunHeader::setRunEnd (const int runEnd) inline
Set the end time of the run in seconds since epoch
Parameters
[in] runEnd the end time of the run.
Definition at line 89 of file RunHeader.h.
{ runEnd_ = runEnd; }
References runEnd_.
Referenced by framework::Process::run().
setRunStart()
void ldmx::RunHeader::setRunStart (const int runStart) inline
Set the run start time in seconds since epoch.
Parameters
[in] runStart the start time of the run.
Definition at line 75 of file RunHeader.h.
{ runStart_ = runStart; }
References runStart_.
Referenced by framework::Process::run().
setStringParameter()
void ldmx::RunHeader::setStringParameter (const std::string & name, std::string value) inline
Set a string parameter value.
Parameters
name The name of the parameter.
value The parameter value.
Definition at line 162 of file RunHeader.h.
{
    stringParameters_[name] = value;
  }
References stringParameters_.
Referenced by simcore::Simulator::beforeNewRun(), simcore::biasoperators::PhotoNuclear::RecordConfig(), simcore::darkbrem::DarkBremVertexLibraryModel::RecordConfig(), simcore::biasoperators::DarkBrem::RecordConfig(), simcore::biasoperators::ElectroNuclear::RecordConfig(), simcore::biasoperators::GammaToMuPair::RecordConfig(), simcore::biasoperators::K0LongInelastic::RecordConfig(), and simcore::biasoperators::NeutronInelastic::RecordConfig().
stream()
void ldmx::RunHeader::stream (std::ostream & s) const
Stream this object into the input ostream
Includes new-line characters to separate out the different parameter maps
Parameters
[in] s ostream to write to
Definition at line 15 of file RunHeader.cxx.
{
  s << "RunHeader { run: " << getRunNumber()
    << ", detectorName: " << getDetectorName()
    << ", description: " << getDescription() << "\n";
  s << "  intParameters: "
    << "\n";
  for (const auto &[key, val] : intParameters_)
    s << "    " << key << " = " << val << "\n";
  s << "  floatParameters: "
    << "\n";
  for (const auto &[key, val] : floatParameters_)
    s << "    " << key << " = " << val << "\n";
  s << "  stringParameters: "
    << "\n";
  for (const auto &[key, val] : stringParameters_)
    s << "    " << key << " = " << val << "\n";
  s << "}";
}
References floatParameters_, getDescription(), getDetectorName(), getRunNumber(), intParameters_, and stringParameters_.
Referenced by Print().
Friends And Related Function Documentation
operator<<
std::ostream & operator<< (std::ostream & s, const ldmx::RunHeader & h) friend
Stream this object to an output stream
Needs to be here and labeled as friend for it to be compatible with Boost logging.
See also
ldmx::RunHeader::stream
Parameters
[in] s ostream to write to
[in] h RunHeader to write out
Returns
modified ostream
Definition at line 189 of file RunHeader.h.
{
    h.stream(s);
    return s;
  }
Member Data Documentation
description_
std::string ldmx::RunHeader::description_ {""} private
Run description.
Definition at line 202 of file RunHeader.h.
Referenced by getDescription(), and setDescription().
detectorName_
std::string ldmx::RunHeader::detectorName_ {""} private
Detector name.
Definition at line 199 of file RunHeader.h.
Referenced by getDetectorName(), and setDetectorName().
floatParameters_
std::map<std::string, float> ldmx::RunHeader::floatParameters_ private
Map of float parameters.
Definition at line 220 of file RunHeader.h.
Referenced by getFloatParameter(), getFloatParameters(), setFloatParameter(), and stream().
intParameters_
std::map<std::string, int> ldmx::RunHeader::intParameters_ private
Map of int parameters.
Definition at line 217 of file RunHeader.h.
Referenced by getIntParameter(), getIntParameters(), setIntParameter(), and stream().
runEnd_
int ldmx::RunHeader::runEnd_ {0} private
Run end in seconds since epoch.
Definition at line 208 of file RunHeader.h.
Referenced by getRunEnd(), and setRunEnd().
runNumber_
int ldmx::RunHeader::runNumber_ {0} private
Run number.
Definition at line 196 of file RunHeader.h.
Referenced by getRunNumber().
runStart_
int ldmx::RunHeader::runStart_ {0} private
Run start in seconds since epoch.
Definition at line 205 of file RunHeader.h.
Referenced by getRunStart(), and setRunStart().
softwareTag_
std::string ldmx::RunHeader::softwareTag_ {GIT_SHA1} private
git SHA-1 hash associated with the software tag used to generate this file.
Definition at line 214 of file RunHeader.h.
Referenced by getSoftwareTag().
stringParameters_
std::map<std::string, std::string> ldmx::RunHeader::stringParameters_ private
Map of string parameters.
Definition at line 223 of file RunHeader.h.
Referenced by getStringParameter(), getStringParameters(), setStringParameter(), and stream().
The documentation for this class was generated from the following files:
Framework/include/Framework/RunHeader.h
Framework/src/Framework/RunHeader.cxx