LDMX Software: ldmx::TrigScintID Class Reference
ldmx::TrigScintID Class Reference
#include <TrigScintID.h>
Public Member Functions
TrigScintID ()
Constructor.
TrigScintID (unsigned int rawid)
Constructor with raw id.
TrigScintID (const DetectorID id)
TrigScintID (unsigned int module, unsigned int bar)
~TrigScintID ()
Destructor.
int module () const
int getModule () const
int bar () const
int getBarID () const
Public Member Functions inherited from ldmx::DetectorID
DetectorID ()
Class constructor for a null DetectorID.
DetectorID (RawValue rawid)
Class constructor from a raw 32-bit integer.
DetectorID (SubdetectorIDType sdtype, RawValue raw_subpayload)
bool null () const
SubdetectorIDType subdet () const
RawValue raw () const
void setRawValue (RawValue rawValue)
bool operator< (const DetectorID &id) const
bool operator== (const DetectorID &id) const
bool operator!= (const DetectorID &id) const
Static Public Member Functions
static void createInterpreters ()
Static Public Attributes
static const RawValue MODULE_MASK {0xFF}
static const RawValue MODULE_SHIFT {8}
static const RawValue BAR_MASK {0xFF}
static const RawValue BAR_SHIFT {0}
Static Public Attributes inherited from ldmx::DetectorID
static const RawValue SUBDETECTORID_MASK {0x3F}
static const RawValue SUBDETECTORID_SHIFT {26}
static const RawValue SUBDETECTOR_PAYLOAD_MASK {0x3FFFFFF}
Additional Inherited Members
Public Types inherited from ldmx::DetectorID
typedef uint32_t RawValue
Protected Attributes inherited from ldmx::DetectorID
RawValue id_
The raw, packed value of the ID.
Detailed Description
Class that defines the detector ID of the trigger scintillator.
Definition at line 14 of file TrigScintID.h.
Constructor & Destructor Documentation
TrigScintID() [1/4]
ldmx::TrigScintID::TrigScintID () inline
Constructor.
Definition at line 22 of file TrigScintID.h.
: DetectorID(SD_TRIGGER_SCINT, 0) {}
TrigScintID() [2/4]
ldmx::TrigScintID::TrigScintID (unsigned int rawid) inline
Constructor with raw id.
Definition at line 25 of file TrigScintID.h.
                                  : DetectorID(rawid) {
    SUBDETECTORID_TEST("TrigScintID", SD_TRIGGER_SCINT);
  }
TrigScintID() [3/4]
ldmx::TrigScintID::TrigScintID (const DetectorID id) inline
Create from a DetectorID, but check
Definition at line 32 of file TrigScintID.h.
                                   : DetectorID(id) {
    SUBDETECTORID_TEST("TrigScintID", SD_TRIGGER_SCINT);
  }
TrigScintID() [4/4]
ldmx::TrigScintID::TrigScintID (unsigned int module, unsigned int bar) inline
Create from pieces
Definition at line 39 of file TrigScintID.h.
      : DetectorID(SD_TRIGGER_SCINT, 0) {
    id_ |= (module & MODULE_MASK) << MODULE_SHIFT;
    id_ |= (bar & BAR_MASK) << BAR_SHIFT;
  }
References bar(), ldmx::DetectorID::id_, and module().
~TrigScintID()
ldmx::TrigScintID::~TrigScintID () inline
Destructor.
Definition at line 46 of file TrigScintID.h.
{}
Member Function Documentation
bar()
int ldmx::TrigScintID::bar () const inline
Get the value of the bar field from the ID.
Returns
The value of the bar field.
Definition at line 64 of file TrigScintID.h.
{ return (id_ >> BAR_SHIFT) & BAR_MASK; }
References ldmx::DetectorID::id_.
Referenced by dqm::TrigScintDQM::analyze(), trigscint::TrigScintDigiProducer::produce(), TEST_CASE(), and TrigScintID().
createInterpreters()
void ldmx::TrigScintID::createInterpreters () static
Definition at line 10 of file TrigScintID.cxx.
{
  IDField::IDFieldList fields;
  fields.push_back(new IDField("subdetector", 0, SUBDETECTORID_SHIFT, 31));
  fields.push_back(
      new IDField("module", 1, MODULE_SHIFT,
                  MODULE_SHIFT + IDField::countOnes(MODULE_MASK) - 1));
  fields.push_back(new IDField("bar", 2, BAR_SHIFT,
                               BAR_SHIFT + IDField::countOnes(BAR_MASK) - 1));
  DetectorIDInterpreter::registerInterpreter(SD_TRIGGER_SCINT, fields);
}
getBarID()
int ldmx::TrigScintID::getBarID () const inline
Get the bar ID.
Returns
The bar ID.
Definition at line 70 of file TrigScintID.h.
{ return (id_ >> BAR_SHIFT) & BAR_MASK; }
References ldmx::DetectorID::id_.
Referenced by TEST_CASE().
getModule()
int ldmx::TrigScintID::getModule () const inline
Get the value of the module field from the ID.
Returns
The value of the module field.
Definition at line 58 of file TrigScintID.h.
{ return (id_ >> MODULE_SHIFT) & MODULE_MASK; }
References ldmx::DetectorID::id_.
Referenced by TEST_CASE().
module()
int ldmx::TrigScintID::module () const inline
Get the value of the module field from the ID.
Returns
The value of the module field.
Definition at line 52 of file TrigScintID.h.
{ return (id_ >> MODULE_SHIFT) & MODULE_MASK; }
References ldmx::DetectorID::id_.
Referenced by TEST_CASE(), and TrigScintID().
Member Data Documentation
BAR_MASK
const RawValue ldmx::TrigScintID::BAR_MASK {0xFF} static
Definition at line 18 of file TrigScintID.h.
BAR_SHIFT
const RawValue ldmx::TrigScintID::BAR_SHIFT {0} static
Definition at line 19 of file TrigScintID.h.
MODULE_MASK
const RawValue ldmx::TrigScintID::MODULE_MASK {0xFF} static
Definition at line 16 of file TrigScintID.h.
MODULE_SHIFT
const RawValue ldmx::TrigScintID::MODULE_SHIFT {8} static
Definition at line 17 of file TrigScintID.h.
The documentation for this class was generated from the following files:
DetDescr/include/DetDescr/TrigScintID.h
DetDescr/src/DetDescr/TrigScintID.cxx