LDMX Software: tracking::sim::LdmxMeasurementCalibrator Class Reference
tracking::sim::LdmxMeasurementCalibrator Class Reference
Public Member Functions
LdmxMeasurementCalibrator ()=default
Construct an invalid calibrator. Required to allow copying.
LdmxMeasurementCalibrator (const std::vector< ldmx::Measurement > &measurements)
void calibrate (const Acts::GeometryContext &, Acts::MultiTrajectory< Acts::VectorMultiTrajectory >::TrackStateProxy trackState) const
void calibrate_1d (const Acts::GeometryContext &, Acts::MultiTrajectory< Acts::VectorMultiTrajectory >::TrackStateProxy trackState) const
void test (const Acts::GeometryContext &, const ActsExamples::IndexSourceLink &sourceLink) const
Private Attributes
const std::vector< ldmx::Measurement > * m_measurements = nullptr
Detailed Description
Definition at line 33 of file MeasurementCalibrator.h.
Constructor & Destructor Documentation
LdmxMeasurementCalibrator()
tracking::sim::LdmxMeasurementCalibrator::LdmxMeasurementCalibrator (const std::vector< ldmx::Measurement > & measurements) inline
Definition at line 41 of file MeasurementCalibrator.h.
{
      m_measurements = &measurements;
    }
Member Function Documentation
calibrate()
void tracking::sim::LdmxMeasurementCalibrator::calibrate (const Acts::GeometryContext & , Acts::MultiTrajectory< Acts::VectorMultiTrajectory >::TrackStateProxy trackState) const inline
Find the measurement corresponding to the source link. Uses a 2D measurement, cov-matrix and projection
Template Parameters
parameters_t Track parameters type
Parameters
gctx The geometry context (unused)
trackState The track state to calibrate
Definition at line 50 of file MeasurementCalibrator.h.
{
        ActsExamples::IndexSourceLink sourceLink =
            trackState.getUncalibratedSourceLink().get<ActsExamples::IndexSourceLink>();
        assert(m_measurements and
               "Undefined measurement container in LdmxMeasurementCalibrator");
        assert((sourceLink.index() < m_measurements->size()) and
               "Source link index is outside the container bounds in LdmxMeasurementCalibrator");
        auto meas = m_measurements->at(sourceLink.index());
        trackState.calibrated<2>().setZero();
        Acts::Vector2 local_pos{meas.getLocalPosition()[0], meas.getLocalPosition()[1]};
        trackState.calibrated<2>().head<2>() = local_pos;
        //trackState.data().measdim = 2;
        trackState.calibratedCovariance<2>().setZero();
        Acts::SymMatrix2 local_cov;
        local_cov.setZero();
        local_cov(0,0) = meas.getLocalCovariance()[0];
        local_cov(1,1) = meas.getLocalCovariance()[1];
        trackState.calibratedCovariance<2>().block<2,2>(0,0) = local_cov;
        Acts::ActsMatrix<2,6> projector;
        projector.setZero();
        projector(0,0) = 1.;
        projector(1,1) = 1.;
        trackState.setProjector(projector);
      }
References ActsExamples::IndexSourceLink::index().
Referenced by tracking::reco::CKFProcessor::produce().
calibrate_1d()
void tracking::sim::LdmxMeasurementCalibrator::calibrate_1d (const Acts::GeometryContext & , Acts::MultiTrajectory< Acts::VectorMultiTrajectory >::TrackStateProxy trackState) const inline
Find the measurement corresponding to the source link. Uses a 1D measurement, cov-matrix and projection
Template Parameters
parameters_t Track parameters type
Parameters
gctx The geometry context (unused)
trackState The track state to calibrate
Definition at line 91 of file MeasurementCalibrator.h.
{
        //Use by value - life management is not working properly
        ActsExamples::IndexSourceLink sourceLink =
            trackState.getUncalibratedSourceLink().get<ActsExamples::IndexSourceLink>();
        assert(m_measurements and
               "Undefined measurement container in LdmxMeasurementCalibrator");
        assert((sourceLink.index() < m_measurements->size()) and
               "Source link index is outside the container bounds in LdmxMeasurementCalibrator");
        //std::cout<<"calibrate_1d ==> NMeasurements available=" << m_measurements->size()<<std::endl;
        auto meas = m_measurements->at(sourceLink.index());
        //You need to explicitly allocate measurements here
        trackState.allocateCalibrated(1);
        trackState.calibrated<1>().setZero();
        trackState.calibrated<1>()(0) = (meas.getLocalPosition())[0];
        trackState.calibratedCovariance<1>().setZero();
        trackState.calibratedCovariance<1>()(0,0) = (meas.getLocalCovariance())[0];
        Acts::ActsMatrix<2,6> projector;
        projector.setZero();
        projector(0,0) = 1.;
        projector(1,1) = 1.;
        trackState.setProjector(projector.row(0));
      }
References ActsExamples::IndexSourceLink::index().
Referenced by tracking::reco::CKFProcessor::produce().
test()
void tracking::sim::LdmxMeasurementCalibrator::test (const Acts::GeometryContext & , const ActsExamples::IndexSourceLink & sourceLink) const inline
Definition at line 124 of file MeasurementCalibrator.h.
{
        auto meas = m_measurements->at(sourceLink.index());
        //get the measurement
        std::cout<<"Measurement layer::\n"<<meas.getLayer()<<std::endl;
        Acts::Vector3 global_pos{meas.getGlobalPosition()[0],
          meas.getGlobalPosition()[1],
          meas.getGlobalPosition()[2]};
        std::cout<<"Measurement global_position::\n"<<global_pos<<std::endl;
        Acts::Vector2 local_pos{meas.getLocalPosition()[0],
          meas.getLocalPosition()[1]};
        std::cout<<"Measurement local_position::\n"<<local_pos<<std::endl;
      }
Member Data Documentation
m_measurements
const std::vector<ldmx::Measurement>* tracking::sim::LdmxMeasurementCalibrator::m_measurements = nullptr private
Definition at line 147 of file MeasurementCalibrator.h.
The documentation for this class was generated from the following file:
Tracking/include/Tracking/Sim/MeasurementCalibrator.h