LDMX Software: simcore::TrigScintSD Class Reference
simcore::TrigScintSD Class Reference
#include <TrigScintSD.h>
Public Member Functions
TrigScintSD (const std::string &name, simcore::ConditionsInterface &ci, const framework::config::Parameters &p)
~TrigScintSD ()
Destructor.
virtual bool isSensDet (G4LogicalVolume *vol) const final override
G4bool ProcessHits (G4Step *step, G4TouchableHistory *history)
virtual void saveHits (framework::Event &event) final override
virtual void EndOfEvent () final override
Public Member Functions inherited from simcore::SensitiveDetector
SensitiveDetector (const std::string &name, simcore::ConditionsInterface &ci, const framework::config::Parameters &parameters)
virtual ~SensitiveDetector ()
virtual bool isSensDet (G4LogicalVolume *lv) const =0
virtual G4bool ProcessHits (G4Step *step, G4TouchableHistory *hist)=0
virtual void saveHits (framework::Event &event)=0
virtual void EndOfEvent (G4HCofThisEvent *) final override
virtual void EndOfEvent ()=0
Private Attributes
std::vector< ldmx::SimCalorimeterHit > hits_
our collection of hits in this SD
std::string collection_name_
name of the hit collection for this SD
std::string vol_name_
name of trigger pad volume this SD is capturing
int module_id_
the ID number for the module we are gathering hits from
Additional Inherited Members
Public Types inherited from simcore::SensitiveDetector
using Factory = ::simcore::Factory< SensitiveDetector, SensitiveDetector *, const std::string &, simcore::ConditionsInterface &, const framework::config::Parameters & >
Protected Member Functions inherited from simcore::SensitiveDetector
template<class T >
const T & getCondition (const std::string &condition_name)
bool isGeantino (const G4Step *step) const
const TrackMap & getTrackMap () const
Detailed Description
Class defining a sensitive detector of type trigger scintillator.
Definition at line 12 of file TrigScintSD.h.
Constructor & Destructor Documentation
TrigScintSD()
simcore::TrigScintSD::TrigScintSD (const std::string & name, simcore::ConditionsInterface & ci, const framework::config::Parameters & p)
Class constructor.
Parameters
[in] name The name of the sensitive detector.
[in] ci interface to conditions objects
[in] p python configuration parameters
Definition at line 16 of file TrigScintSD.cxx.
    : SensitiveDetector(name, ci, p) {
      module_id_ = p.getParameter<int>("module_id");
      collection_name_ = p.getParameter<std::string>("collection_name");
      vol_name_ = p.getParameter<std::string>("volume_name");
    }
References collection_name_, framework::config::Parameters::getParameter(), module_id_, and vol_name_.
~TrigScintSD()
simcore::TrigScintSD::~TrigScintSD ()
Destructor.
Definition at line 25 of file TrigScintSD.cxx.
{}
Member Function Documentation
EndOfEvent()
virtual void simcore::TrigScintSD::EndOfEvent () inline final override virtual
Cleanup SD and prepare a new-event state
Implements simcore::SensitiveDetector.
Definition at line 53 of file TrigScintSD.h.
{
    hits_.clear();
  }
References hits_.
isSensDet()
virtual bool simcore::TrigScintSD::isSensDet (G4LogicalVolume * vol) const inline final override virtual
Should the input logical volume be included in this sensitive detector?
Note
Depends on names in GDML!
Implements simcore::SensitiveDetector.
Definition at line 34 of file TrigScintSD.h.
{
    return vol->GetName().contains(vol_name_);
  }
References vol_name_.
ProcessHits()
G4bool simcore::TrigScintSD::ProcessHits (G4Step * step, G4TouchableHistory * history) virtual
Process steps to create hits.
Parameters
[in] step The step information.
[in] history The readout history.
Implements simcore::SensitiveDetector.
Definition at line 27 of file TrigScintSD.cxx.
{
  // Get the energy deposited by the particle during the step
  auto energy{step->GetTotalEnergyDeposit()};
  // If a non-Geantino particle doesn't deposit energy during the step,
  // skip processing it.
  if (energy == 0 and not isGeantino(step)) return false;
  // Create a new instance of a calorimeter hit
  //  emplace_back returns a *reference* to the hit that was constructed
  //  and we should keep that reference so that we are editing the correct hit
  ldmx::SimCalorimeterHit& hit = hits_.emplace_back();
  // Set the hit position
  auto position{0.5 * (step->GetPreStepPoint()->GetPosition() +
                       step->GetPostStepPoint()->GetPosition())};
  auto volumePosition{step->GetPreStepPoint()
                          ->GetTouchableHandle()
                          ->GetHistory()
                          ->GetTopTransform()
                          .Inverse()
                          .TransformPoint(G4ThreeVector())};
  hit.setPosition(position[0], position[1], volumePosition.z());
  // Get the track associated with this step
  auto track{step->GetTrack()};
  // Set the ID on the hit.
  auto bar{track->GetVolume()->GetCopyNo()};
  ldmx::TrigScintID id(module_id_, bar);
  hit.setID(id.raw());
  // add single contrib to this calorimeter hit
  //  IncidentID - this track's ID
  //  Track ID
  //  PDG ID
  //  energy deposited
  //  global time of this hit
  hit.addContrib(track->GetTrackID(), track->GetTrackID(),
                 track->GetParticleDefinition()->GetPDGEncoding(), energy,
                 track->GetGlobalTime());
  return true;
}
References ldmx::SimCalorimeterHit::addContrib(), hits_, simcore::SensitiveDetector::isGeantino(), module_id_, ldmx::SimCalorimeterHit::setID(), and ldmx::SimCalorimeterHit::setPosition().
saveHits()
virtual void simcore::TrigScintSD::saveHits (framework::Event & event) inline final override virtual
Save our hits collection into the event bus and reset it.
Implements simcore::SensitiveDetector.
Definition at line 49 of file TrigScintSD.h.
{
    event.add(collection_name_, hits_);
  }
References collection_name_, and hits_.
Member Data Documentation
collection_name_
std::string simcore::TrigScintSD::collection_name_ private
name of the hit collection for this SD
Definition at line 61 of file TrigScintSD.h.
Referenced by saveHits(), and TrigScintSD().
hits_
std::vector<ldmx::SimCalorimeterHit> simcore::TrigScintSD::hits_ private
our collection of hits in this SD
Definition at line 59 of file TrigScintSD.h.
Referenced by EndOfEvent(), ProcessHits(), and saveHits().
module_id_
int simcore::TrigScintSD::module_id_ private
the ID number for the module we are gathering hits from
Definition at line 65 of file TrigScintSD.h.
Referenced by ProcessHits(), and TrigScintSD().
vol_name_
std::string simcore::TrigScintSD::vol_name_ private
name of trigger pad volume this SD is capturing
Definition at line 63 of file TrigScintSD.h.
Referenced by isSensDet(), and TrigScintSD().
The documentation for this class was generated from the following files:
SimCore/include/SimCore/SDs/TrigScintSD.h
SimCore/src/SimCore/SDs/TrigScintSD.cxx