LDMX Software: ldmx::EveDetectorGeometry Class Reference
ldmx::EveDetectorGeometry Class Reference
Class that constructs the detector components for the event display.
#include <EveDetectorGeometry.h>
Public Member Functions
EveDetectorGeometry ()
~EveDetectorGeometry ()
void drawECAL ()
void drawHCAL ()
void drawRecoilTracker ()
TEveElement * getECAL ()
TEveElement * getHCAL ()
TEveElement * getRecoilTracker ()
TEveElement * getDetector ()
Private Attributes
TEveElement * hcal_
TEveElement * sidehcal_
TEveElement * ecal_
TEveElement * recoilTracker_
TEveElement * detector_
Detailed Description
Class that constructs the detector components for the event display.
Definition at line 22 of file EveDetectorGeometry.h.
Constructor & Destructor Documentation
EveDetectorGeometry()
ldmx::EveDetectorGeometry::EveDetectorGeometry ()
Constructor Builds and draws all of the detector elements.
Definition at line 12 of file EveDetectorGeometry.cxx.
{
         hcal_           = new TEveElementList("HCAL");
         sidehcal_       = new TEveElementList("Side HCAL");
         ecal_           = new TEveElementList("ECAL");
         recoilTracker_  = new TEveElementList("Recoil Tracker");
         detector_       = new TEveElementList("LDMX Detector");
         drawECAL();
         drawHCAL();
         drawRecoilTracker();
     }
References drawECAL(), drawHCAL(), and drawRecoilTracker().
~EveDetectorGeometry()
ldmx::EveDetectorGeometry::~EveDetectorGeometry () inline
Destructor Cleanup leftover pointers.
Definition at line 36 of file EveDetectorGeometry.h.
{
                 delete hcal_;
                 delete sidehcal_;
                 delete ecal_;
                 delete recoilTracker_;
                 delete detector_;
             }
Member Function Documentation
drawECAL()
void ldmx::EveDetectorGeometry::drawECAL ()
Draw the elements of the ECAL
Definition at line 26 of file EveDetectorGeometry.cxx.
{
         for (int col = 0; col < 7; ++col) {
             TString colName;
             colName.Form("Tower %d", col);
             TEveGeoShape* hexCol = EveShapeDrawer::getInstance().drawHexPrism(
                     DetectorGeometry::getInstance().getHexPrism( col ),
                     0, 0, 0,
                     kBlue, 90, colName);
             ecal_->AddElement(hexCol);
         }
         detector_->AddElement(ecal_);
     }
References ldmx::EveShapeDrawer::drawHexPrism(), ldmx::EveShapeDrawer::getInstance(), and ldmx::DetectorGeometry::getInstance().
Referenced by EveDetectorGeometry().
drawHCAL()
void ldmx::EveDetectorGeometry::drawHCAL ()
Draw the elements of the HCAL
Definition at line 44 of file EveDetectorGeometry.cxx.
{
         TEveGeoShape* backHcal = EveShapeDrawer::getInstance().drawRectPrism(
                 DetectorGeometry::getInstance().getBoundingBox( HcalSection::BACK ),
                 0, 0, 0, kCyan, 90, "Back HCal");
         hcal_->AddElement(backHcal);
         TEveGeoShape* sideTopHcal = EveShapeDrawer::getInstance().drawRectPrism(
                 DetectorGeometry::getInstance().getBoundingBox( HcalSection::TOP ),
                 0, 0, 0, kCyan, 90, "Module 1");
         sidehcal_->AddElement(sideTopHcal);
         TEveGeoShape* sideBottomHcal = EveShapeDrawer::getInstance().drawRectPrism(
                 DetectorGeometry::getInstance().getBoundingBox( HcalSection::BOTTOM ),
                 0, 0, 0, kCyan, 90, "Module 4");
         sidehcal_->AddElement(sideBottomHcal);
         TEveGeoShape* sideLeftHcal = EveShapeDrawer::getInstance().drawRectPrism(
                 DetectorGeometry::getInstance().getBoundingBox( HcalSection::LEFT ),
                 0, 0, 0, kCyan, 90, "Module 2");
         sidehcal_->AddElement(sideLeftHcal);
         TEveGeoShape* sideRightHcal = EveShapeDrawer::getInstance().drawRectPrism(
                 DetectorGeometry::getInstance().getBoundingBox( HcalSection::RIGHT ),
                 0, 0, 0, kCyan, 90, "Module 3");
         sidehcal_->AddElement(sideRightHcal);
         hcal_->AddElement(sidehcal_);
         detector_->AddElement(hcal_);
     }
References ldmx::EveShapeDrawer::drawRectPrism(), ldmx::EveShapeDrawer::getInstance(), and ldmx::DetectorGeometry::getInstance().
Referenced by EveDetectorGeometry().
drawRecoilTracker()
void ldmx::EveDetectorGeometry::drawRecoilTracker ()
Draw the elements of the Recoil Tracker
Definition at line 79 of file EveDetectorGeometry.cxx.
{
         for (int layerID = 1; layerID < 9; layerID++ ) {
             TString name;
             name.Form("Stereo_%d", layerID );
             TEveGeoShape *layer = EveShapeDrawer::getInstance().drawRectPrism(
                     DetectorGeometry::getInstance().getBoundingBox( layerID , 0 ),
                     0, 0, DetectorGeometry::getInstance().getRotAngle( layerID , 0 )*180/M_PI,
                     kRed-10, 90, name );
             recoilTracker_->AddElement(layer);
         }
         for (int layerID = 9; layerID < 11; layerID++ ) {
             for (int moduleID = 0; moduleID < 10; moduleID++ ) {
                 TString name;
                 name.Form("Mono_%d_%d" , layerID , moduleID );
                 TEveGeoShape *layer = EveShapeDrawer::getInstance().drawRectPrism(
                         DetectorGeometry::getInstance().getBoundingBox( layerID , moduleID ),
                         0, 0, DetectorGeometry::getInstance().getRotAngle( layerID , moduleID )*180/M_PI,
                         kRed-10, 90, name );
                 recoilTracker_->AddElement(layer);
             }
         }
         detector_->AddElement(recoilTracker_);
         return;
     }
References ldmx::EveShapeDrawer::drawRectPrism(), ldmx::EveShapeDrawer::getInstance(), and ldmx::DetectorGeometry::getInstance().
Referenced by EveDetectorGeometry().
getDetector()
TEveElement* ldmx::EveDetectorGeometry::getDetector () inline
Access Entire Detector Eve Element
Definition at line 78 of file EveDetectorGeometry.h.
 { return detector_; }
getECAL()
TEveElement* ldmx::EveDetectorGeometry::getECAL () inline
Access ECAL Eve Element
Definition at line 63 of file EveDetectorGeometry.h.
 { return ecal_; }
Referenced by ldmx::EventDisplay::EventDisplay().
getHCAL()
TEveElement* ldmx::EveDetectorGeometry::getHCAL () inline
Access HCAL Eve Element
Definition at line 68 of file EveDetectorGeometry.h.
 { return hcal_; }
Referenced by ldmx::EventDisplay::EventDisplay().
getRecoilTracker()
TEveElement* ldmx::EveDetectorGeometry::getRecoilTracker () inline
Access Recoil Tracker Eve Element
Definition at line 73 of file EveDetectorGeometry.h.
 { return recoilTracker_; }
Referenced by ldmx::EventDisplay::EventDisplay().
The documentation for this class was generated from the following files:
EventDisplay/include/EventDisplay/EveDetectorGeometry.h
EventDisplay/src/EveDetectorGeometry.cxx