LDMX Software: ldmx::HcalHit Class Reference
ldmx::HcalHit Class Reference
Stores reconstructed hit information from the HCAL.
#include <HcalHit.h>
Public Member Functions
HcalHit ()
virtual ~HcalHit ()
void Clear ()
void Print () const
float getPE () const
float getMinPE () const
int getSection () const
int getLayer () const
int getStrip () const
int getEnd () const
int getIsADC () const
int getToaPos () const
int getToaNeg () const
int getAmplitudePos () const
int getAmplitudeNeg () const
void setPE (float pe)
void setMinPE (float minpe)
void setSection (int section)
void setLayer (int layer)
void setStrip (int strip)
void setEnd (int end)
void setIsADC (int isADC)
void setTimeDiff (double timeDiff)
void setToaPos (double toaPos)
void setToaNeg (double toaNeg)
void setAmplitudePos (double amplitudePos)
void setAmplitudeNeg (double amplitudeNeg)
void setPositionUnchanged (double position, int isX)
double getPosition () const
int getIsX () const
double getTimeDiff () const
Public Member Functions inherited from ldmx::CalorimeterHit
CalorimeterHit ()
virtual ~CalorimeterHit ()
void Clear ()
void Print () const
int getID () const
void setID (int id)
float getAmplitude () const
void setAmplitude (float amplitude)
float getEnergy () const
void setEnergy (float energy)
float getTime () const
void setTime (float time)
float getXPos () const
void setXPos (float xpos)
float getYPos () const
void setYPos (float ypos)
float getZPos () const
void setZPos (float zpos)
bool isNoise () const
void setNoise (bool yes)
bool operator< (const CalorimeterHit &rhs) const
Private Member Functions
ClassDef (HcalHit, 2)
Private Attributes
float pe_ {0}
float minpe_ {-99}
int section_
section, layer, strip and end
int layer_
int strip_
int end_
int isADC_
isADC
double timeDiff_
double position_
double isX_
double toaPos_
double toaNeg_
double amplitudePos_
double amplitudeNeg_
Detailed Description
Stores reconstructed hit information from the HCAL.
Note
This class represents the reconstructed hit information from the HCAL, providing particular information for the HCAL, above and beyond what is available in the CalorimeterHit.
Definition at line 23 of file HcalHit.h.
Constructor & Destructor Documentation
HcalHit()
ldmx::HcalHit::HcalHit () inline
Class constructor.
Definition at line 28 of file HcalHit.h.
{}
~HcalHit()
virtual ldmx::HcalHit::~HcalHit () inline virtual
Class destructor.
Definition at line 33 of file HcalHit.h.
{}
Member Function Documentation
ClassDef()
ldmx::HcalHit::ClassDef (HcalHit , 2) private
The ROOT class definition.
Clear()
void ldmx::HcalHit::Clear ()
Clear the data in the object.
getAmplitudeNeg()
int ldmx::HcalHit::getAmplitudeNeg () const inline
Get the amplitude of the negative end.
Returns
amplitudeNeg
Definition at line 112 of file HcalHit.h.
{ return amplitudeNeg_; }
getAmplitudePos()
int ldmx::HcalHit::getAmplitudePos () const inline
Get the amplitude of the positive end.
Returns
amplitudePos
Definition at line 106 of file HcalHit.h.
{ return amplitudePos_; }
getEnd()
int ldmx::HcalHit::getEnd () const inline
Get end for this hit.
Returns
end
Definition at line 82 of file HcalHit.h.
{ return end_; }
getIsADC()
int ldmx::HcalHit::getIsADC () const inline
Get if hit was reconstructed using ADC.
Returns
isADC
Definition at line 88 of file HcalHit.h.
{ return isADC_; }
References isADC_.
getIsX()
int ldmx::HcalHit::getIsX () const inline
Definition at line 194 of file HcalHit.h.
{ return isX_;}
getLayer()
int ldmx::HcalHit::getLayer () const inline
Get the layer for this hit.
Returns
layer number
Definition at line 70 of file HcalHit.h.
{ return layer_; }
getMinPE()
float ldmx::HcalHit::getMinPE () const inline
Get the minimum number of photoelectrons estimated for this hit if two sided readout.
Returns
Minimum number of photoelectrons, including noise which affects the estimate.
Definition at line 58 of file HcalHit.h.
{ return minpe_; }
References minpe_.
getPE()
float ldmx::HcalHit::getPE () const inline
Get the number of photoelectrons estimated for this hit.
Returns
Number of photoelectrons, including noise which affects the estimate.
Definition at line 50 of file HcalHit.h.
{ return pe_; }
References pe_.
Referenced by hcal::HcalVetoProcessor::produce(), and hcal::HcalWABVetoProcessor::produce().
getPosition()
double ldmx::HcalHit::getPosition () const inline
Definition at line 193 of file HcalHit.h.
{ return position_;}
getSection()
int ldmx::HcalHit::getSection () const inline
Get the section for this hit.
Returns
section number
Definition at line 64 of file HcalHit.h.
{ return section_; }
References section_.
getStrip()
int ldmx::HcalHit::getStrip () const inline
Get the strip for this hit.
Returns
strip number
Definition at line 76 of file HcalHit.h.
{ return strip_; }
getTimeDiff()
double ldmx::HcalHit::getTimeDiff () const inline
Definition at line 195 of file HcalHit.h.
{ return timeDiff_;}
getToaNeg()
int ldmx::HcalHit::getToaNeg () const inline
Get the toa of the negative end.
Returns
toaNeg
Definition at line 100 of file HcalHit.h.
{ return toaNeg_; }
getToaPos()
int ldmx::HcalHit::getToaPos () const inline
Get the toa of the positive end.
Returns
toaPos
Definition at line 94 of file HcalHit.h.
{ return toaPos_; }
Print()
void ldmx::HcalHit::Print () const
Print out the object.
setAmplitudeNeg()
void ldmx::HcalHit::setAmplitudeNeg (double amplitudeNeg) inline
Set amplitude of the negative end
Parameters
amplitude
Definition at line 186 of file HcalHit.h.
{ amplitudeNeg_ = amplitudeNeg; }
Referenced by hcal::HcalDoubleEndRecProducer::produce().
setAmplitudePos()
void ldmx::HcalHit::setAmplitudePos (double amplitudePos) inline
Set amplitude of the positive end
Parameters
amplitude
Definition at line 180 of file HcalHit.h.
{ amplitudePos_ = amplitudePos; }
Referenced by hcal::HcalDoubleEndRecProducer::produce().
setEnd()
void ldmx::HcalHit::setEnd (int end) inline
Set the end (0 neg, 1 pos side).
Parameters
end
Definition at line 150 of file HcalHit.h.
{ end_ = end; }
Referenced by hcal::HcalSingleEndRecProducer::produce().
setIsADC()
void ldmx::HcalHit::setIsADC (int isADC) inline
Set if the hit is reconstructed using ADC
Parameters
isADC int
Definition at line 156 of file HcalHit.h.
{ isADC_ = isADC; }
References isADC_.
Referenced by hcal::HcalSingleEndRecProducer::produce().
setLayer()
void ldmx::HcalHit::setLayer (int layer) inline
Set the layer for this hit.
Parameters
layer number
Definition at line 138 of file HcalHit.h.
{ layer_ = layer; }
Referenced by hcal::HcalRecProducer::produce(), hcal::HcalDoubleEndRecProducer::produce(), and hcal::HcalSingleEndRecProducer::produce().
setMinPE()
void ldmx::HcalHit::setMinPE (float minpe) inline
Set the minimum number of photoelectrons estimated for this hit.
Parameters
pe Minimum number of photoelectrons, including noise which affects the estimate.
Definition at line 126 of file HcalHit.h.
{ minpe_ = minpe; }
References minpe_.
Referenced by trigscint::TrigScintDigiProducer::produce(), hcal::HcalRecProducer::produce(), hcal::HcalDoubleEndRecProducer::produce(), and hcal::HcalSingleEndRecProducer::produce().
setPE()
void ldmx::HcalHit::setPE (float pe) inline
Set the number of photoelectrons estimated for this hit.
Parameters
pe Number of photoelectrons, including noise which affects the estimate.
Definition at line 119 of file HcalHit.h.
{ pe_ = pe; }
References pe_.
Referenced by hcal::HcalRecProducer::produce(), hcal::HcalDoubleEndRecProducer::produce(), and hcal::HcalSingleEndRecProducer::produce().
setPositionUnchanged()
void ldmx::HcalHit::setPositionUnchanged (double position, int isX) inline
Set original position
Definition at line 191 of file HcalHit.h.
{ position_ = position; isX_ = isX; }
Referenced by hcal::HcalDoubleEndRecProducer::produce().
setSection()
void ldmx::HcalHit::setSection (int section) inline
Set the section for this hit.
Parameters
section number
Definition at line 132 of file HcalHit.h.
{ section_ = section; }
References section_.
Referenced by hcal::HcalRecProducer::produce(), hcal::HcalDoubleEndRecProducer::produce(), and hcal::HcalSingleEndRecProducer::produce().
setStrip()
void ldmx::HcalHit::setStrip (int strip) inline
Set the strip for this hit.
Parameters
strip number
Definition at line 144 of file HcalHit.h.
{ strip_ = strip; }
Referenced by hcal::HcalRecProducer::produce(), hcal::HcalDoubleEndRecProducer::produce(), and hcal::HcalSingleEndRecProducer::produce().
setTimeDiff()
void ldmx::HcalHit::setTimeDiff (double timeDiff) inline
Set time difference (uncorrected)
Parameters
time
Definition at line 162 of file HcalHit.h.
{ timeDiff_ = timeDiff; }
Referenced by hcal::HcalDoubleEndRecProducer::produce().
setToaNeg()
void ldmx::HcalHit::setToaNeg (double toaNeg) inline
Set toa of the negative end
Parameters
time
Definition at line 174 of file HcalHit.h.
{ toaNeg_ = toaNeg; }
Referenced by hcal::HcalDoubleEndRecProducer::produce().
setToaPos()
void ldmx::HcalHit::setToaPos (double toaPos) inline
Set toa of the positive end
Parameters
time
Definition at line 168 of file HcalHit.h.
{ toaPos_ = toaPos; }
Referenced by hcal::HcalDoubleEndRecProducer::produce().
Member Data Documentation
amplitudeNeg_
double ldmx::HcalHit::amplitudeNeg_ private
Definition at line 221 of file HcalHit.h.
amplitudePos_
double ldmx::HcalHit::amplitudePos_ private
Definition at line 220 of file HcalHit.h.
end_
int ldmx::HcalHit::end_ private
Definition at line 209 of file HcalHit.h.
isADC_
int ldmx::HcalHit::isADC_ private
isADC
Definition at line 212 of file HcalHit.h.
Referenced by getIsADC(), and setIsADC().
isX_
double ldmx::HcalHit::isX_ private
Definition at line 216 of file HcalHit.h.
layer_
int ldmx::HcalHit::layer_ private
Definition at line 207 of file HcalHit.h.
minpe_
float ldmx::HcalHit::minpe_ {-99} private
The minimum number of PE estimated for this hit, different from pe_ when you have two ended readout
Definition at line 203 of file HcalHit.h.
Referenced by getMinPE(), and setMinPE().
pe_
float ldmx::HcalHit::pe_ {0} private
The number of PE estimated for this hit.
Definition at line 199 of file HcalHit.h.
Referenced by getPE(), and setPE().
position_
double ldmx::HcalHit::position_ private
Definition at line 215 of file HcalHit.h.
section_
int ldmx::HcalHit::section_ private
section, layer, strip and end
Definition at line 206 of file HcalHit.h.
Referenced by getSection(), and setSection().
strip_
int ldmx::HcalHit::strip_ private
Definition at line 208 of file HcalHit.h.
timeDiff_
double ldmx::HcalHit::timeDiff_ private
Definition at line 214 of file HcalHit.h.
toaNeg_
double ldmx::HcalHit::toaNeg_ private
Definition at line 219 of file HcalHit.h.
toaPos_
double ldmx::HcalHit::toaPos_ private
Definition at line 218 of file HcalHit.h.
The documentation for this class was generated from the following file:
Hcal/include/Hcal/Event/HcalHit.h