LDMX Software: tracking::reco::TruthSeedProcessor Class Reference
tracking::reco::TruthSeedProcessor Class Reference
#include <TruthSeedProcessor.h>
Public Member Functions
TruthSeedProcessor (const std::string &name, framework::Process &process)
~TruthSeedProcessor ()=default
Destructor.
void configure (framework::config::Parameters &parameters) final override
void onProcessStart () final override
void produce (framework::Event &event) final override
Public Member Functions inherited from framework::Producer
Producer (const std::string &name, Process &process)
virtual void produce (Event &event)=0
virtual void beforeNewRun (ldmx::RunHeader &header)
Public Member Functions inherited from framework::EventProcessor
EventProcessor (const std::string &name, Process &process)
virtual ~EventProcessor ()
virtual void configure (framework::config::Parameters &parameters)
virtual void onNewRun (const ldmx::RunHeader &runHeader)
virtual void onFileOpen (EventFile &eventFile)
virtual void onFileClose (EventFile &eventFile)
virtual void onProcessStart ()
virtual void onProcessEnd ()
template<class T >
const T & getCondition (const std::string &condition_name)
TDirectory * getHistoDirectory ()
void setStorageHint (framework::StorageControlHint hint)
void setStorageHint (framework::StorageControlHint hint, const std::string &purposeString)
int getLogFrequency () const
int getRunNumber () const
std::string getName () const
void createHistograms (const std::vector< framework::config::Parameters > &histos)
Private Member Functions
void createTruthTrack (const ldmx::SimParticle &particle, ldmx::TruthTrack &trk)
void createTruthTrack (const ldmx::SimParticle &particle, const ldmx::SimTrackerHit &hit, ldmx::TruthTrack &trk)
void createTruthTrack (const std::vector< double > &pos_vec, const std::vector< double > &p_vec, int charge, ldmx::TruthTrack &trk)
bool scoringPlaneHitFilter (const ldmx::SimTrackerHit &hit, const std::vector< ldmx::SimTrackerHit > &ecal_sp_hits)
Private Attributes
Acts::GeometryContext gctx_
The ACTS geometry context properly.
std::vector< int > pdg_ids_ {11}
pdg_ids of the particles we want to select for the seeds
std::string scoring_hits_coll_name_ {"TargetScoringPlaneHits"}
Which scoring plane hits to use for the truth seeds generation.
std::string recoil_sim_hits_coll_name_ {"RecoilSimHits"}
Sim hits to check if the truth seed is findable.
int n_min_hits_ {7}
float z_min_ {-999}
int track_id_ {-999}
Only select a particular trackID.
double pz_cut_ {-9999}
Ask for a minimum pz for the seeds.
double p_cut_ {0.}
Ask for a minimum p for the seeds.
double p_cut_max_ {100000.}
Ask for a maximum p for the seeds.
double p_cut_ecal_ {-1.}
bool recoil_sp_ {true}
bool target_sp_ {true}
Additional Inherited Members
Static Public Member Functions inherited from framework::EventProcessor
static void declare (const std::string &classname, int classtype, EventProcessorMaker *)
Static Public Attributes inherited from framework::Producer
static const int CLASSTYPE {1}
Protected Member Functions inherited from framework::EventProcessor
void abortEvent ()
Protected Attributes inherited from framework::EventProcessor
HistogramHelper histograms_
Interface class for making and filling histograms.
NtupleManager & ntuple_ {NtupleManager::getInstance()}
Manager for any ntuples.
logging::logger theLog_
The logger for this EventProcessor.
Detailed Description
Create a track seed using truth information extracted from the corresponding SimParticle or SimTrackerHit. When creating seeds in the Tagger tracker, the SimParticle associated with the incident electron (trackID == 1) is used to create the seed from the parameters (x, y, z, px, py, pz, q) at the vertex. For the Recoil tracker, since the electron is produced upstream, the SimParticle can't be used to get any parameters at the target. In this case, the target scoring plane hits are used to extract the parameters above.
Definition at line 34 of file TruthSeedProcessor.h.
Constructor & Destructor Documentation
TruthSeedProcessor()
tracking::reco::TruthSeedProcessor::TruthSeedProcessor (const std::string & name, framework::Process & process)
Constructor.
Parameters
name Name for this instance of the class.
process The Process class associated with EventProcessor, provided by the framework.
Definition at line 6 of file TruthSeedProcessor.cxx.
    : framework::Producer(name, process) {}
Member Function Documentation
configure()
void tracking::reco::TruthSeedProcessor::configure (framework::config::Parameters & parameters) final override virtual
Callback for the EventProcessor to configure itself from the given set of parameters.
The parameters a processor has access to are the member variables of the python class in the sequence that has className equal to the EventProcessor class name.
Parameters
parameters Parameters for configuration.
Reimplemented from framework::EventProcessor.
Definition at line 12 of file TruthSeedProcessor.cxx.
{
  pdg_ids_ = parameters.getParameter<std::vector<int> >("pdg_ids", {11});
  scoring_hits_coll_name_ =
      parameters.getParameter<std::string>("scoring_hits_coll_name");
  recoil_sim_hits_coll_name_ =
      parameters.getParameter<std::string>("recoil_sim_hits_coll_name");
  n_min_hits_ = parameters.getParameter<int>("n_min_hits", 7);
  z_min_ = parameters.getParameter<double>("z_min", -9999);  // mm
  track_id_ = parameters.getParameter<int>("track_id", -9999);
  pz_cut_ = parameters.getParameter<double>("pz_cut", -9999);  // MeV
  p_cut_ = parameters.getParameter<double>("p_cut", 0.);
  p_cut_max_ = parameters.getParameter<double>("p_cut_max", 100000.);  // MeV
  p_cut_ecal_ = parameters.getParameter<double>("p_cut_ecal", -1.);    // MeV
  recoil_sp_ = parameters.getParameter<double>("recoil_sp",true);
  target_sp_ = parameters.getParameter<double>("tagger_sp",true);
}
References framework::config::Parameters::getParameter(), n_min_hits_, p_cut_, p_cut_max_, pdg_ids_, pz_cut_, recoil_sim_hits_coll_name_, scoring_hits_coll_name_, track_id_, and z_min_.
createTruthTrack() [1/3]
void tracking::reco::TruthSeedProcessor::createTruthTrack (const ldmx::SimParticle & particle, const ldmx::SimTrackerHit & hit, ldmx::TruthTrack & trk) private
Use the scoring plane hit at the target to extract (x, y, z, px, py, pz) and create a track seed. In this case, the SimParticle is used to extract the charge of the particle.
Parameters
particle The SimParticle to extract the charge from.
hit The SimTrackerHit used to create the seed.
Definition at line 29 of file TruthSeedProcessor.cxx.
{
  std::vector<double> pos{static_cast<double>(hit.getPosition()[0]),
    static_cast<double>(hit.getPosition()[1]),
    static_cast<double>(hit.getPosition()[2])};
  createTruthTrack(pos, hit.getMomentum(), particle.getCharge(),trk);
  trk.setTrackID(hit.getTrackID());
  trk.setPdgID(hit.getPdgID());
}
References createTruthTrack(), ldmx::SimParticle::getCharge(), ldmx::SimTrackerHit::getMomentum(), ldmx::SimTrackerHit::getPdgID(), ldmx::SimTrackerHit::getPosition(), ldmx::SimTrackerHit::getTrackID(), and ldmx::TruthTrack::setTrackID().
createTruthTrack() [2/3]
void tracking::reco::TruthSeedProcessor::createTruthTrack (const ldmx::SimParticle & particle, ldmx::TruthTrack & trk) private
Use the vertex position of the SimParticle to extract (x, y, z, px, py, pz, q) and create a track seed.
Parameters
particle The SimParticle to make a seed from.
Definition at line 42 of file TruthSeedProcessor.cxx.
{
  createTruthTrack(particle.getVertex(), particle.getMomentum(),
                   particle.getCharge(),trk);
  trk.setPdgID(particle.getPdgID());
}
References createTruthTrack(), ldmx::SimParticle::getCharge(), ldmx::SimParticle::getMomentum(), ldmx::SimParticle::getPdgID(), and ldmx::SimParticle::getVertex().
Referenced by createTruthTrack().
createTruthTrack() [3/3]
void tracking::reco::TruthSeedProcessor::createTruthTrack (const std::vector< double > & pos_vec, const std::vector< double > & p_vec, int charge, ldmx::TruthTrack & trk) private
Create a seed track from the given position, momentum and charge.
Parameters
pos The position at which the particle was created.
p The momentum of the particle at the point of creation.
charge The charge of the particle.
Definition at line 51 of file TruthSeedProcessor.cxx.
{
  // Get the position and momentum of the particle at the point of creation.
  // This only works for the incident electron when creating a tagger tracker
  // seed. For the recoil tracker, the scoring plane position will need to
  // be used.  For other particles created in the target or tracker planes,
  // this version of the method can also be used.
  // These are just Eigen vectors defined as
  // Eigen::Matrix<double, kSize, 1>;
  Acts::Vector3 pos{pos_vec.data()};
  Acts::Vector3 mom{p_vec.data()};
  double time{0.};
  // Rotate the position and momentum into the ACTS frame.
  pos = tracking::sim::utils::Ldmx2Acts(pos);
  mom = tracking::sim::utils::Ldmx2Acts(mom);
  // Get the charge of the particle.
  // TODO: Add function that uses the PDG ID to calculate this.
  double q{charge * Acts::UnitConstants::e};
  // Transform the position, momentum and charge to free parameters.
  auto free_params{tracking::sim::utils::toFreeParameters(pos, mom, q)};
  // Create a line surface at the perigee.  The perigee position is extracted
  // from a particle's vertex or the particle's position at a specific
  // scoring plane.
  auto gen_surface{Acts::Surface::makeShared<Acts::PerigeeSurface>(
      Acts::Vector3(free_params[Acts::eFreePos0], free_params[Acts::eFreePos1],
                    free_params[Acts::eFreePos2]))};
  // Transform the parameters to local positions on the perigee surface.
  auto bound_params{Acts::detail::transformFreeToBoundParameters(
                        free_params, *gen_surface, gctx_)
                        .value()};
  // Create the seed track object.
  trk.setPerigeeLocation(free_params[Acts::eFreePos0],
                         free_params[Acts::eFreePos1],
                         free_params[Acts::eFreePos2]);
  trk.setPerigeeParameters(
      tracking::sim::utils::convertActsToLdmxPars(bound_params));
  trk.setPosition(pos(0),pos(1),pos(2));
  trk.setMomentum(mom(0),mom(1),mom(2));
}
References gctx_.
onProcessStart()
void tracking::reco::TruthSeedProcessor::onProcessStart () final override virtual
Callback for the EventProcessor to take any necessary action when the processing of events starts. For this class, the callback is used to retrieve the GeometryContext from ACTS.
Reimplemented from framework::EventProcessor.
Definition at line 10 of file TruthSeedProcessor.cxx.
{ gctx_ = Acts::GeometryContext(); }
References gctx_.
produce()
void tracking::reco::TruthSeedProcessor::produce (framework::Event & event) final override virtual
Main loop that creates the seed tracks for both the tagger and recoil tracker.
Parameters
event The event containing the collections to process.
Implements framework::Producer.
Definition at line 157 of file TruthSeedProcessor.cxx.
{
  //Retrieve the particleMap
  auto particleMap{event.getMap<int, ldmx::SimParticle>("SimParticles")};
  //Retrieve the target scoring hits
  // Information is extracted using the
  // scoring plane hit left by the particle at the target.
  const std::vector<ldmx::SimTrackerHit> scoring_hits{
    event.getCollection<ldmx::SimTrackerHit>(scoring_hits_coll_name_)};
  // Retrieve the scoring plane hits at the ECAL
  const std::vector<ldmx::SimTrackerHit> scoring_hits_ecal{
    event.getCollection<ldmx::SimTrackerHit>("EcalScoringPlaneHits")};
  // Retrieve the sim hits in the tracker of interest
  const std::vector<ldmx::SimTrackerHit> sim_hits =
      event.getCollection<ldmx::SimTrackerHit>(recoil_sim_hits_coll_name_);
  // Create a mapping from the selected scoring plane hit objects to the number
  // of hits they associated particle creates in the tracker.
  // In this way I can keep track of the amount of hits left by each trackID
  std::unordered_map<int, int> hit_count_map;
  for (auto &sim_hit : sim_hits) {
    if (!hit_count_map.count(sim_hit.getTrackID()))
      hit_count_map[sim_hit.getTrackID()] = 1;
    hit_count_map[sim_hit.getTrackID()]++;
  }
  // to keep track of how many sim particles leave hits on the s-plane
  std::vector<int> recoil_sh_idxs;
  std::unordered_map<int,std::vector<int> > recoil_sh_count_map;
  int idx_taggerhit = -1; //We are interested only in the trackID==1 electron
  //Target scoring hits for Tagger will have Z<0, Recoil scoring hits will have Z>0
  for (unsigned int i_sh=0; i_sh < scoring_hits.size(); i_sh++) {
    const ldmx::SimTrackerHit& hit  = scoring_hits.at(i_sh);
    Acts::Vector3 p_vec{hit.getMomentum()[0],hit.getMomentum()[1],hit.getMomentum()[2]};
    double tagger_p_max  = 0.;
    //Check if it is a tagger track going fwd that passes basic cuts
    if (hit.getPosition()[2] < 0.) {
      //Tagger selection cuts
      //Negative scoring plane hit, with momentum > p_cut
      if (p_vec(2)         < 0.      ||
          p_vec.norm()     < p_cut_  ||
          hit.getPdgID()   != 11     ||
          hit.getTrackID() != 1)
        continue;
      if (p_vec.norm() > tagger_p_max) {
        idx_taggerhit = i_sh;
        tagger_p_max = p_vec.norm();
      }
    }//Tagger loop
    //Check the recoil hits
    else {
      //Recoil selection cuts
      //Positive scoring plane hit, forward direction with momentum > p_cut
      if (p_vec(2) < 0.         ||
          p_vec.norm() < p_cut_ )
        continue;
      //Check that the hit was left by a charged particle
      if  (abs(particleMap[hit.getTrackID()].getCharge()) < 1e-8)
        continue;
      recoil_sh_count_map[hit.getTrackID()].push_back(i_sh);
    }//Recoil
  }// loop on Target scoring plane hits
  for (std::pair<int,std::vector<int>> element : recoil_sh_count_map) {
    std::sort(element.second.begin(),element.second.end(),
              [&](const int idx1, int idx2) -> bool {
                const ldmx::SimTrackerHit& hit1 = scoring_hits.at(idx1);
                const ldmx::SimTrackerHit& hit2 = scoring_hits.at(idx2);
                Acts::Vector3 phit1{hit1.getMomentum()[0],hit1.getMomentum()[1],hit1.getMomentum()[2]};
                Acts::Vector3 phit2{hit2.getMomentum()[0],hit2.getMomentum()[1],hit2.getMomentum()[2]};
                return phit1.norm() > phit2.norm();
              }
              );
  }
  std::vector<ldmx::TruthTrack> tagger_truth_tracks;
  std::vector<ldmx::TruthTrack> recoil_truth_tracks;
  //Define the perigee_surface at 0.0.0
  auto perigee_surface{Acts::Surface::makeShared<Acts::PerigeeSurface>(Acts::Vector3(0.,0.,0.))};
  //Define the target_surface
  auto target_surface = tracking::sim::utils::unboundSurface(0.);
  if (idx_taggerhit != -1) {
    const ldmx::SimTrackerHit& hit = scoring_hits.at(idx_taggerhit);
    const ldmx::SimParticle& phit = particleMap[hit.getTrackID()];
    if (hit_count_map[hit.getTrackID()] > n_min_hits_) {
      ldmx::TruthTrack truth_tagger_track;
      createTruthTrack(phit, hit, truth_tagger_track);
      //get track state at the generation point
      //ldmx::TruthTrack::TrackState ts_beamOrigin(phit,"beam_origin");
      //propagate track to target
      //trackExtrapolator(truth_tagger_track, perigee_surface);
      //truth_tagger_track.addTrackState(ts_beamOrigin);
      tagger_truth_tracks.push_back(truth_tagger_track);
    }
  }
  for (std::pair<int,std::vector<int>> element : recoil_sh_count_map) {
    //Only take the first entry of the vector: it should be the scoring plane hit with the highest momentum.
    const ldmx::SimTrackerHit& hit  = scoring_hits.at(element.second.at(0));
    const ldmx::SimParticle&   phit = particleMap[hit.getTrackID()];
    //Findable particle selection
    if (hit_count_map[hit.getTrackID()] < n_min_hits_)
      continue;
    ldmx::TruthTrack truth_recoil_track;
    createTruthTrack(phit,hit,truth_recoil_track);
    recoil_truth_tracks.push_back(truth_recoil_track);
  }
  /*
  std::cout<<"TAGGER TRUTH TRACKS"<<std::endl;
  for (auto tt : tagger_truth_tracks) {
    std::cout<<tt<<std::endl;
  }
  std::cout<<"#########"<<std::endl;
  std::cout<<"RECOIL TRUTH TRACKS"<<std::endl;
  for (auto tt : recoil_truth_tracks) {
    std::cout<<tt<<std::endl;
  }
  std::cout<<"#########"<<std::endl;
  */
  event.add("TaggerTruthTracks",tagger_truth_tracks);
  event.add("RecoilTruthTracks",recoil_truth_tracks);
}
References ldmx::SimTrackerHit::getMomentum(), ldmx::SimTrackerHit::getPdgID(), ldmx::SimTrackerHit::getPosition(), ldmx::SimTrackerHit::getTrackID(), p_cut_, recoil_sim_hits_coll_name_, and scoring_hits_coll_name_.
scoringPlaneHitFilter()
bool tracking::reco::TruthSeedProcessor::scoringPlaneHitFilter (const ldmx::SimTrackerHit & hit, const std::vector< ldmx::SimTrackerHit > & ecal_sp_hits) private
Filter that checks if a scoring plane passes specified momentum cuts as well as if the associated SimParticle hits the ECal.
Parameters
hit The target scoring plane hit to check.
ecal_sp_hits The ECal scoring plane hit used to check if the associated particle hits the ECal.
Definition at line 103 of file TruthSeedProcessor.cxx.
{
  // Clean some of the hits we don't want
  if (hit.getPosition()[2] < z_min_) return false;
  // Check if the track_id was requested
  if (track_id_ > 0 && hit.getTrackID() != track_id_) return false;
  // Check if we are requesting particular particles
  if (std::find(pdg_ids_.begin(), pdg_ids_.end(), hit.getPdgID()) ==
      pdg_ids_.end())
    return false;
  Acts::Vector3 p_vec{hit.getMomentum()[0], hit.getMomentum()[1],
                      hit.getMomentum()[2]};
  // p cut
  if (p_cut_ >= 0. && p_vec.norm() < p_cut_) return false;
  // p cut Max
  if (p_cut_ < 100000. && p_vec.norm() > p_cut_max_) return false;
  // pz cut
  if (pz_cut_ > -9999 && p_vec(2) < pz_cut_) return false;
  // Check the ecal scoring plane
  bool pass_ecal_scoring_plane = true;
  if (p_cut_ecal_ > 0) {  // only check if we care about it.
    for (auto &e_sp_hit : ecal_sp_hits) {
      if (e_sp_hit.getTrackID() == hit.getTrackID() &&
          e_sp_hit.getPdgID() == hit.getPdgID()) {
        Acts::Vector3 e_sp_p{e_sp_hit.getMomentum()[0],
                             e_sp_hit.getMomentum()[1],
                             e_sp_hit.getMomentum()[2]};
        if (e_sp_p.norm() < p_cut_ecal_) pass_ecal_scoring_plane = false;
        // Skip the rest of the scoring plane hits since we already found the
        // track we care about
        break;
      }  // check that the hit belongs to the inital particle from the target
         // scoring plane hit
    }    // loop on Ecal scoring plane hits
  }      // pcutEcal
  if (!pass_ecal_scoring_plane) return false;
  return true;
}
References ldmx::SimTrackerHit::getMomentum(), ldmx::SimTrackerHit::getPdgID(), ldmx::SimTrackerHit::getPosition(), ldmx::SimTrackerHit::getTrackID(), p_cut_, p_cut_max_, pdg_ids_, pz_cut_, track_id_, and z_min_.
Member Data Documentation
gctx_
Acts::GeometryContext tracking::reco::TruthSeedProcessor::gctx_ private
The ACTS geometry context properly.
Definition at line 122 of file TruthSeedProcessor.h.
Referenced by createTruthTrack(), and onProcessStart().
n_min_hits_
int tracking::reco::TruthSeedProcessor::n_min_hits_ {7} private
Minimum number of hits left in the recoil tracker to consider the seed as findable
Definition at line 137 of file TruthSeedProcessor.h.
Referenced by configure().
p_cut_
double tracking::reco::TruthSeedProcessor::p_cut_ {0.} private
Ask for a minimum p for the seeds.
Definition at line 152 of file TruthSeedProcessor.h.
Referenced by configure(), produce(), and scoringPlaneHitFilter().
p_cut_ecal_
double tracking::reco::TruthSeedProcessor::p_cut_ecal_ {-1.} private
Definition at line 158 of file TruthSeedProcessor.h.
p_cut_max_
double tracking::reco::TruthSeedProcessor::p_cut_max_ {100000.} private
Ask for a maximum p for the seeds.
Definition at line 155 of file TruthSeedProcessor.h.
Referenced by configure(), and scoringPlaneHitFilter().
pdg_ids_
std::vector<int> tracking::reco::TruthSeedProcessor::pdg_ids_ {11} private
pdg_ids of the particles we want to select for the seeds
Definition at line 125 of file TruthSeedProcessor.h.
Referenced by configure(), and scoringPlaneHitFilter().
pz_cut_
double tracking::reco::TruthSeedProcessor::pz_cut_ {-9999} private
Ask for a minimum pz for the seeds.
Definition at line 149 of file TruthSeedProcessor.h.
Referenced by configure(), and scoringPlaneHitFilter().
recoil_sim_hits_coll_name_
std::string tracking::reco::TruthSeedProcessor::recoil_sim_hits_coll_name_ {"RecoilSimHits"} private
Sim hits to check if the truth seed is findable.
Definition at line 131 of file TruthSeedProcessor.h.
Referenced by configure(), and produce().
recoil_sp_
bool tracking::reco::TruthSeedProcessor::recoil_sp_ {true} private
Definition at line 161 of file TruthSeedProcessor.h.
scoring_hits_coll_name_
std::string tracking::reco::TruthSeedProcessor::scoring_hits_coll_name_ {"TargetScoringPlaneHits"} private
Which scoring plane hits to use for the truth seeds generation.
Definition at line 128 of file TruthSeedProcessor.h.
Referenced by configure(), and produce().
target_sp_
bool tracking::reco::TruthSeedProcessor::target_sp_ {true} private
Definition at line 164 of file TruthSeedProcessor.h.
track_id_
int tracking::reco::TruthSeedProcessor::track_id_ {-999} private
Only select a particular trackID.
Definition at line 146 of file TruthSeedProcessor.h.
Referenced by configure(), and scoringPlaneHitFilter().
z_min_
float tracking::reco::TruthSeedProcessor::z_min_ {-999} private
Min cut on the z of the scoring hit. It could be used to clean the scoring hits if desired.
Definition at line 143 of file TruthSeedProcessor.h.
Referenced by configure(), and scoringPlaneHitFilter().
The documentation for this class was generated from the following files:
Tracking/include/Tracking/Reco/TruthSeedProcessor.h
Tracking/src/Tracking/Reco/TruthSeedProcessor.cxx