LDMX Software: simcore::PluginFactory Class Reference
simcore::PluginFactory Class Reference
Class that manages the generators used to fire particles.
#include <PluginFactory.h>
Public Member Functions
PluginFactory (const PluginFactory &)=delete
Delete the copy constructor.
void operator= (const PluginFactory &)=delete
Delete the assignment operator.
std::vector< PrimaryGenerator * > getGenerators () const
void registerGenerator (const std::string &className, PrimaryGeneratorBuilder *builder)
void createGenerator (const std::string &className, const std::string &instanceName, framework::config::Parameters &parameters)
actionMap getActions ()
void registerAction (const std::string &className, UserActionBuilder *builder)
void createAction (const std::string &className, const std::string &instanceName, framework::config::Parameters &parameters)
std::vector< XsecBiasingOperator * > getBiasingOperators () const
void registerBiasingOperator (const std::string &className, XsecBiasingOperatorBuilder *builder)
void createBiasingOperator (const std::string &className, const std::string &instanceName, framework::config::Parameters &parameters)
Static Public Member Functions
static PluginFactory & getInstance ()
Private Member Functions
PluginFactory ()
Constructor - private to prevent initialization.
Private Attributes
std::map< std::string, PrimaryGeneratorBuilder * > registeredGenerators_
A map of all register generators.
std::vector< PrimaryGenerator * > generators_
Cointainer for all generators to be used by the simulation.
std::map< std::string, UserActionBuilder * > registeredActions_
A map of all registered user actions to their corresponding info.
actionMap actions_
Container for all Geant4 actions.
std::map< std::string, XsecBiasingOperatorBuilder * > registeredOperators_
A map of all registered user actions to their corresponding info.
std::vector< XsecBiasingOperator * > biasing_operators_
Container for all biasing operators.
framework::logging::logger theLog_
Allow for us to log here.
Detailed Description
Class that manages the generators used to fire particles.
Follows the template for a modern C++ singleton explained on stackoverflow
Definition at line 35 of file PluginFactory.h.
Constructor & Destructor Documentation
PluginFactory()
simcore::PluginFactory::PluginFactory () inline private
Constructor - private to prevent initialization.
Definition at line 180 of file PluginFactory.h.
{}
Member Function Documentation
createAction()
void simcore::PluginFactory::createAction (const std::string & className, const std::string & instanceName, framework::config::Parameters & parameters)
Construct a new action and attach it to the types of actions it will be a part of.
This checks the list of registered actions for the input className. If the className is not found, then we assume that the action is not registered and throw and exception.
Otherwise, we use the registered builder to create a action and give it the passed instanceName and paramters. After creation, we then use UserAction::getTypes() to determine which types of actions we should attach this specific action to.
Parameters
[in] className Full name of class (including namespaces) of the action
[in] instanceName unique run-time instance name for the action
[in] parameters Parameters to pass to the action for configuration
Definition at line 81 of file PluginFactory.cxx.
{
  auto it{registeredActions_.find(className)};
  if (it == registeredActions_.end()) {
    EXCEPTION_RAISE("PluginFactory", "Failed to create " + className);
  }
  auto act{it->second(instanceName, parameters)};
  std::vector<TYPE> types = act->getTypes();
  for (auto& type : types) {
    if (type == TYPE::RUN)
      std::get<UserRunAction*>(actions_[TYPE::RUN])->registerAction(act);
    else if (type == TYPE::EVENT)
      std::get<UserEventAction*>(actions_[TYPE::EVENT])->registerAction(act);
    else if (type == TYPE::TRACKING)
      std::get<UserTrackingAction*>(actions_[TYPE::TRACKING])
          ->registerAction(act);
    else if (type == TYPE::STEPPING)
      std::get<USteppingAction*>(actions_[TYPE::STEPPING])->registerAction(act);
    else if (type == TYPE::STACKING)
      std::get<UserStackingAction*>(actions_[TYPE::STACKING])
          ->registerAction(act);
    else
      EXCEPTION_RAISE("PluginFactory", "User action type doesn't exist.");
  }
  // now that the biasing is built --> put it on active list
  ldmx_log(info) << "User Action '" << instanceName << "' of class '"
                 << className << "' has been created.";
}
References actions_, and registeredActions_.
Referenced by simcore::RunManager::Initialize().
createBiasingOperator()
void simcore::PluginFactory::createBiasingOperator (const std::string & className, const std::string & instanceName, framework::config::Parameters & parameters)
Create a biasing operator from the input parameters.
This checks the list of registered biasing operators for the input className. If the className is not found, then we assume that the biasing operator is not registered and throw and exception.
Otherwise, we use the registered builder to create an operator and give it the passed instanceName and paramters. We insert the created operator into the list of biasing operators.
Parameters
[in] classNmae Full name of class (including namespaces) of the operator
[in] instanceName unique run-time instance name for the operator
[in] parameters Parameters to pass to the operator for configuration
Definition at line 126 of file PluginFactory.cxx.
{
  auto it{registeredOperators_.find(className)};
  if (it == registeredOperators_.end()) {
    EXCEPTION_RAISE("CreateBiasingOperator",
                    "Failed to create biasing '" + className + "'.");
  }
  auto bop{it->second(instanceName, parameters)};
  // now that the biasing is built --> put it on active list
  biasing_operators_.push_back(bop);
  ldmx_log(info) << "Biasing operator '" << instanceName << "' of class '"
                 << className << "' has been created.";
}
References biasing_operators_, and registeredOperators_.
Referenced by simcore::RunManager::setupPhysics().
createGenerator()
void simcore::PluginFactory::createGenerator (const std::string & className, const std::string & instanceName, framework::config::Parameters & parameters)
Create a new generate and attach it to the list of generators
This checks the list of registered generators for the input className. If the className is not found, then we assume that the generator is not registered and throw and exception.
Otherwise, we use the registered builder to create a generator and give it the passed instanceName and paramters. We insert the created generator into the list of generators.
Parameters
[in] className Full name of class (including namespaces) of the generator
[in] instanceName unique run-time instance name for the generator
[in] parameters Parameters to pass to the generator for configuration
Definition at line 39 of file PluginFactory.cxx.
{
  auto it{registeredGenerators_.find(className)};
  if (it == registeredGenerators_.end()) {
    EXCEPTION_RAISE("CreateGenerator",
                    "Failed to create generator '" + className + "'.");
  }
  auto generator{it->second(instanceName, parameters)};
  // now that the generator is built --> put it on active list
  generators_.push_back(generator);
  ldmx_log(info) << "Primary Generator '" << instanceName << "' of class '"
                 << className << "' has been created.";
}
References generators_, and registeredGenerators_.
getActions()
actionMap simcore::PluginFactory::getActions ()
Get the map of all types of user actions to a pointer to the user action we have created.
Note
The createAction method assumes that the internal map of actions has already been created, so the user should call this method before any calls to createAction.
Returns
actionMap of created user actions
Definition at line 57 of file PluginFactory.cxx.
{
  if (actions_.empty()) {
    actions_[TYPE::RUN] = new UserRunAction();
    actions_[TYPE::EVENT] = new UserEventAction();
    actions_[TYPE::TRACKING] = new UserTrackingAction();
    actions_[TYPE::STEPPING] = new USteppingAction();
    actions_[TYPE::STACKING] = new UserStackingAction();
  }
  return actions_;
}
References actions_.
Referenced by simcore::RunManager::Initialize().
getBiasingOperators()
std::vector< XsecBiasingOperator * > simcore::PluginFactory::getBiasingOperators () const inline
Retrieve the current list of biasing operators.
In un-biased running modes, this will return an empty vector.
Returns
vector of pointers to biasing operators
Definition at line 139 of file PluginFactory.h.
{
    return biasing_operators_;
  }
References biasing_operators_.
Referenced by simcore::Simulator::beforeNewRun().
getGenerators()
std::vector< PrimaryGenerator * > simcore::PluginFactory::getGenerators () const inline
Get the collection of all enabled generators
Returns
vector of pointers to constructed primary generators
Definition at line 51 of file PluginFactory.h.
{ return generators_; };
References generators_.
getInstance()
PluginFactory & simcore::PluginFactory::getInstance () static
Returns
the global PluginFactory instance
Definition at line 20 of file PluginFactory.cxx.
{
  // the_factory is created on first call to getInstance
  //  and is guaranteed to be destroyed
  static PluginFactory the_factory;
  return the_factory;
}
Referenced by simcore::Simulator::beforeNewRun(), simcore::UserAction::declare(), simcore::XsecBiasingOperator::declare(), simcore::RunManager::Initialize(), and simcore::RunManager::setupPhysics().
registerAction()
void simcore::PluginFactory::registerAction (const std::string & className, UserActionBuilder * builder)
Put the user action into the list of possible actions.
See also
UserAction::declare for where this method is called. This method is used to construct a list of all possible actions that the user could use.
Parameters
[in] className full name of class (including namespaces) of action
[in] builder pointer to function to use to create the action
Definition at line 69 of file PluginFactory.cxx.
{
  auto it{registeredActions_.find(className)};
  if (it != registeredActions_.end()) {
    EXCEPTION_RAISE(
        "ExistingActionDefinition",
        "The user action " + className + " has already been registered.");
  }
  registeredActions_[className] = builder;
}
References registeredActions_.
Referenced by simcore::UserAction::declare().
registerBiasingOperator()
void simcore::PluginFactory::registerBiasingOperator (const std::string & className, XsecBiasingOperatorBuilder * builder)
Put the biasing operator into the list of possible biasing operators.
See also
XsecBiasingOperator::declare for where this method is called. The declare method is then called using the DECLARE_XSECBIASINGOPERATOR macro.
Parameters
[in] className Full name of class (including namespaces) of the operator
[in] builder a pointer to the function that should be used to create the operator
Definition at line 114 of file PluginFactory.cxx.
{
  auto it{registeredOperators_.find(className)};
  if (it != registeredOperators_.end()) {
    EXCEPTION_RAISE(
        "ExistingOperatorDefinition",
        "The biasing operator " + className + " has already been registered.");
  }
  registeredOperators_[className] = builder;
}
References registeredOperators_.
Referenced by simcore::XsecBiasingOperator::declare().
registerGenerator()
void simcore::PluginFactory::registerGenerator (const std::string & className, PrimaryGeneratorBuilder * builder)
Put the primary generator into the list of possible generators
See also
PrimaryGenerator::declare for where this method is called. This method is used to construct a list of all possible generators that the user could use.
Parameters
[in] className full name of class (including namespaces) of generator
[in] builder pointer to function to use to create the generator
Definition at line 27 of file PluginFactory.cxx.
{
  auto it{registeredGenerators_.find(className)};
  if (it != registeredGenerators_.end()) {
    EXCEPTION_RAISE(
        "ExistingGeneratorDefinition",
        "The primary generator " + className + " has already been registered.");
  }
  registeredGenerators_[className] = builder;
}
Member Data Documentation
actions_
actionMap simcore::PluginFactory::actions_ private
Container for all Geant4 actions.
Definition at line 192 of file PluginFactory.h.
Referenced by createAction(), and getActions().
biasing_operators_
std::vector<XsecBiasingOperator*> simcore::PluginFactory::biasing_operators_ private
Container for all biasing operators.
Definition at line 198 of file PluginFactory.h.
Referenced by createBiasingOperator(), and getBiasingOperators().
generators_
std::vector<PrimaryGenerator*> simcore::PluginFactory::generators_ private
Cointainer for all generators to be used by the simulation.
Definition at line 186 of file PluginFactory.h.
Referenced by createGenerator(), and getGenerators().
registeredActions_
std::map<std::string, UserActionBuilder*> simcore::PluginFactory::registeredActions_ private
A map of all registered user actions to their corresponding info.
Definition at line 189 of file PluginFactory.h.
Referenced by createAction(), and registerAction().
registeredGenerators_
std::map<std::string, PrimaryGeneratorBuilder*> simcore::PluginFactory::registeredGenerators_ private
A map of all register generators.
Definition at line 183 of file PluginFactory.h.
Referenced by createGenerator().
registeredOperators_
std::map<std::string, XsecBiasingOperatorBuilder*> simcore::PluginFactory::registeredOperators_ private
A map of all registered user actions to their corresponding info.
Definition at line 195 of file PluginFactory.h.
Referenced by createBiasingOperator(), and registerBiasingOperator().
theLog_
framework::logging::logger simcore::PluginFactory::theLog_ private
Initial value:
{
      framework::logging::makeLogger("SimPluginFactory")}
Allow for us to log here.
Definition at line 201 of file PluginFactory.h.
The documentation for this class was generated from the following files:
SimCore/include/SimCore/PluginFactory.h
SimCore/src/SimCore/PluginFactory.cxx