LDMX Software: ldmx::UserPrimaryParticleInformation Class Reference
ldmx::UserPrimaryParticleInformation Class Reference
Defines extra information attached to a Geant4 primary particle.
#include <UserPrimaryParticleInformation.h>
Public Member Functions
UserPrimaryParticleInformation ()
virtual ~UserPrimaryParticleInformation ()
void setHepEvtStatus (int hepEvtStatus)
int getHepEvtStatus ()
void Print () const
Private Attributes
int hepEvtStatus_ {-1}
Detailed Description
Defines extra information attached to a Geant4 primary particle.
Definition at line 19 of file UserPrimaryParticleInformation.h.
Constructor & Destructor Documentation
UserPrimaryParticleInformation()
ldmx::UserPrimaryParticleInformation::UserPrimaryParticleInformation () inline
Class Constructor.
Definition at line 26 of file UserPrimaryParticleInformation.h.
 {;}
~UserPrimaryParticleInformation()
virtual ldmx::UserPrimaryParticleInformation::~UserPrimaryParticleInformation () inline virtual
Class destructor.
Definition at line 31 of file UserPrimaryParticleInformation.h.
 {;}
Member Function Documentation
getHepEvtStatus()
int ldmx::UserPrimaryParticleInformation::getHepEvtStatus () inline
Get the HEP event status.
Returns
The HEP event status.
Definition at line 45 of file UserPrimaryParticleInformation.h.
{
                 return hepEvtStatus_;
             }
References hepEvtStatus_.
Referenced by ldmx::PrimaryGeneratorAction::setUserPrimaryInfo().
Print()
void ldmx::UserPrimaryParticleInformation::Print () const inline
Implement virtual method (no-op).
Definition at line 52 of file UserPrimaryParticleInformation.h.
{
             }
setHepEvtStatus()
void ldmx::UserPrimaryParticleInformation::setHepEvtStatus (int hepEvtStatus) inline
Set the HEP event status (generator status) e.g. from an LHE particle.
Parameters
hepEvtStatus The HEP event status.
Definition at line 37 of file UserPrimaryParticleInformation.h.
{
                 hepEvtStatus_ = hepEvtStatus;
             }
References hepEvtStatus_.
Referenced by ldmx::LHEPrimaryGenerator::GeneratePrimaryVertex(), and ldmx::MultiParticleGunPrimaryGenerator::GeneratePrimaryVertex().
Member Data Documentation
hepEvtStatus_
int ldmx::UserPrimaryParticleInformation::hepEvtStatus_ {-1} private
The HEP event status.
Definition at line 60 of file UserPrimaryParticleInformation.h.
Referenced by getHepEvtStatus(), and setHepEvtStatus().
The documentation for this class was generated from the following file:
SimCore/include/SimCore/UserPrimaryParticleInformation.h