LDMX Software: ldmx::ConditionsInterface Class Reference
ldmx::ConditionsInterface Class Reference
Handle to the conditions system, provided at construction to classes which require it.
#include <ConditionsInterface.h>
Public Member Functions
ConditionsInterface (EventProcessor *p)
template<class T >
const T & getCondition (const std::string &condition_name)
Private Attributes
EventProcessor * processor_
Detailed Description
Handle to the conditions system, provided at construction to classes which require it.
Definition at line 19 of file ConditionsInterface.h.
Member Function Documentation
getCondition()
template<class T > const T& ldmx::ConditionsInterface::getCondition (const std::string & condition_name) inline
Primary request action for a conditions object If the object is in the cache and still valid (IOV), the cached object will be returned. If it is not in the cache, or is out of date, the () method will be called to provide the object.
Definition at line 31 of file ConditionsInterface.h.
{
         if (processor_==0) {
         EXCEPTION_RAISE("ConditionUnavailableException", "No conditions system object available in SimCore");
         }
         return processor_->getCondition<T>(condition_name);
     }
References ldmx::EventProcessor::getCondition(), and processor_.
Referenced by ldmx::EcalSD::ProcessHits(), and ldmx::EcalHitIO::writeHitsCollection().
Member Data Documentation
processor_
EventProcessor* ldmx::ConditionsInterface::processor_ private
Pointer to the owner processor object
Definition at line 43 of file ConditionsInterface.h.
Referenced by getCondition().
The documentation for this class was generated from the following file:
SimCore/include/SimCore/ConditionsInterface.h