LDMX Software: framework::Process Class Reference
framework::Process Class Reference
Class which represents the process under execution.
#include <Process.h>
Public Member Functions
Process (const framework::config::Parameters &configuration)
~Process ()
const std::string & getPassName () const
int getRunNumber () const
const ldmx::EventHeader * getEventHeader () const
const ldmx::RunHeader * getRunHeader () const
Conditions & getConditions ()
int getLogFrequency () const
void run ()
void requestFinish ()
TDirectory * makeHistoDirectory (const std::string &dirName)
TDirectory * openHistoFile ()
StorageControl & getStorageController ()
void setEventHeader (ldmx::EventHeader *h)
Static Public Member Functions
static Process getDummy ()
Private Member Functions
Process ()
Private Attributes
framework::config::Parameters config_
The parameters used to configure this class.
std::string passname_
int eventLimit_
int logFrequency_
int termLevelInt_
int fileLevelInt_
std::string logFileName_
int maxTries_
StorageControl m_storageController
std::vector< EventProcessor * > sequence_
Conditions conditions_
std::vector< std::string > inputFiles_
std::vector< std::string > outputFiles_
int compressionSetting_
std::vector< std::string > dropKeepRules_
int runForGeneration_ {1}
std::string histoFilename_
const ldmx::EventHeader * eventHeader_ {0}
const ldmx::RunHeader * runHeader_ {0}
TFile * histoTFile_ {0}
Detailed Description
Class which represents the process under execution.
Definition at line 35 of file Process.h.
Constructor & Destructor Documentation
Process() [1/2]
framework::Process::Process (const framework::config::Parameters & configuration)
Class constructor.
Parameters
configuration Parameters to configure process with
Definition at line 21 of file Process.cxx.
     : conditions_{*this} {
   config_ = configuration;
   passname_ = configuration.getParameter<std::string>("passName", "");
   histoFilename_ = configuration.getParameter<std::string>("histogramFile", "");
   logFileName_ = configuration.getParameter<std::string>("logFileName", "");
   maxTries_ = configuration.getParameter<int>("maxTriesPerEvent", 1);
   eventLimit_ = configuration.getParameter<int>("maxEvents", -1);
   logFrequency_ = configuration.getParameter<int>("logFrequency", -1);
   compressionSetting_ =
       configuration.getParameter<int>("compressionSetting", 9);
   termLevelInt_ = configuration.getParameter<int>("termLogLevel", 2);
   fileLevelInt_ = configuration.getParameter<int>("fileLogLevel", 0);
   inputFiles_ =
       configuration.getParameter<std::vector<std::string>>("inputFiles", {});
   outputFiles_ =
       configuration.getParameter<std::vector<std::string>>("outputFiles", {});
   dropKeepRules_ =
       configuration.getParameter<std::vector<std::string>>("keep", {});
   eventHeader_ = 0;
   auto run{configuration.getParameter<int>("run", -1)};
   if (run > 0) runForGeneration_ = run;
   auto libs{
       configuration.getParameter<std::vector<std::string>>("libraries", {})};
   std::for_each(libs.begin(), libs.end(), [](auto &lib) {
     PluginFactory::getInstance().loadLibrary(lib);
   });
   m_storageController.setDefaultKeep(
       configuration.getParameter<bool>("skimDefaultIsKeep", true));
   auto skimRules{
       configuration.getParameter<std::vector<std::string>>("skimRules", {})};
   for (size_t i = 0; i < skimRules.size(); i += 2) {
     m_storageController.addRule(skimRules[i], skimRules[i + 1]);
   }
   auto sequence{
       configuration.getParameter<std::vector<framework::config::Parameters>>(
           "sequence", {})};
   if (sequence.empty() &&
       configuration.getParameter<bool>("testingMode", false)) {
     EXCEPTION_RAISE(
         "NoSeq",
         "No sequence has been defined. What should I be doing?\nUse "
         "p.sequence to tell me what processors to run.");
   }
   for (auto proc : sequence) {
     auto className{proc.getParameter<std::string>("className")};
     auto instanceName{proc.getParameter<std::string>("instanceName")};
     EventProcessor *ep = PluginFactory::getInstance().createEventProcessor(
         className, instanceName, *this);
     if (ep == 0) {
       EXCEPTION_RAISE(
           "UnableToCreate",
           "Unable to create instance '" + instanceName + "' of class '" +
               className +
               "'. Did you load the library that this class is apart of?");
     }
     auto histograms{
         proc.getParameter<std::vector<framework::config::Parameters>>(
             "histograms", {})};
     if (!histograms.empty()) {
       ep->getHistoDirectory();
       ep->createHistograms(histograms);
     }
     ep->configure(proc);
     sequence_.push_back(ep);
   }
   auto conditionsObjectProviders{
       configuration.getParameter<std::vector<framework::config::Parameters>>(
           "conditionsObjectProviders", {})};
   for (auto cop : conditionsObjectProviders) {
     auto className{cop.getParameter<std::string>("className")};
     auto objectName{cop.getParameter<std::string>("objectName")};
     auto tagName{cop.getParameter<std::string>("tagName")};
     conditions_.createConditionsObjectProvider(className, objectName, tagName,
                                                cop);
   }
 }
References framework::StorageControl::addRule(), compressionSetting_, conditions_, config_, framework::EventProcessor::configure(), framework::Conditions::createConditionsObjectProvider(), framework::PluginFactory::createEventProcessor(), framework::EventProcessor::createHistograms(), dropKeepRules_, eventHeader_, eventLimit_, fileLevelInt_, framework::EventProcessor::getHistoDirectory(), framework::PluginFactory::getInstance(), framework::config::Parameters::getParameter(), histoFilename_, inputFiles_, logFileName_, logFrequency_, m_storageController, maxTries_, outputFiles_, passname_, run(), runForGeneration_, sequence_, framework::StorageControl::setDefaultKeep(), and termLevelInt_.
~Process()
framework::Process::~Process ()
Class Destructor
Cleans up sequence of EventProcessors. These processors were created by ConfigurePython and should be deleted.
Definition at line 110 of file Process.cxx.
                   {
   for (EventProcessor *ep : sequence_) {
     delete ep;
   }
 }
References sequence_.
Process() [2/2]
framework::Process::Process () inline private
Private dummy constructor We hide it here because it shouldn't be used anywhere else.
nothing on purpose
Definition at line 132 of file Process.h.
             : conditions_{*this} {
   }
Referenced by getDummy().
Member Function Documentation
getConditions()
Conditions& framework::Process::getConditions () inline
Get a reference to the conditions system
Definition at line 77 of file Process.h.
 { return conditions_; }
References conditions_.
Referenced by framework::EventProcessor::getConditions(), and framework::ConditionsObjectProvider::requestParentCondition().
getDummy()
static Process framework::Process::getDummy () inline static
Get a dummy process
This function returns an instance of this class without any configuration. This is only helpful in the use case where the user is writing a test for a processor and needs to pass a Process object to the processor's constructor.
Returns
Process without any configuration
Definition at line 125 of file Process.h.
 { return std::move(Process()); }
References Process().
getEventHeader()
const ldmx::EventHeader* framework::Process::getEventHeader () const inline
Get the pointer to the current event header, if defined
Definition at line 67 of file Process.h.
 { return eventHeader_; }
References eventHeader_.
Referenced by framework::Conditions::getConditionPtr(), and framework::EventProcessor::getEventHeader().
getLogFrequency()
int framework::Process::getLogFrequency () const inline
Get the frequency with which the event information is printed.
Returns
integer log frequency (negative if turned off)
Definition at line 83 of file Process.h.
 { return logFrequency_; }
References logFrequency_.
Referenced by framework::EventProcessor::getLogFrequency(), and run().
getPassName()
const std::string& framework::Process::getPassName () const inline
Get the processing pass label.
Returns
The processing pass label.
Definition at line 55 of file Process.h.
 { return passname_; }
References passname_.
Referenced by framework::RandomNumberSeedService::onNewRun().
getRunHeader()
const ldmx::RunHeader* framework::Process::getRunHeader () const inline
Get the pointer to the current run header, if defined
Definition at line 72 of file Process.h.
 { return runHeader_; }
References runHeader_.
getRunNumber()
int framework::Process::getRunNumber () const
Get the current run number or the run number to be used when initiating new events from the job
Returns
int Run number
Definition at line 410 of file Process.cxx.
{
   return (eventHeader_) ? (eventHeader_->getRun()) : (runForGeneration_);
 }
References eventHeader_, ldmx::EventHeader::getRun(), and runForGeneration_.
Referenced by framework::EventProcessor::getRunNumber().
getStorageController()
StorageControl& framework::Process::getStorageController () inline
Access the storage control unit for this process
Definition at line 108 of file Process.h.
 { return m_storageController; }
References m_storageController.
Referenced by framework::EventProcessor::setStorageHint().
makeHistoDirectory()
TDirectory * framework::Process::makeHistoDirectory (const std::string & dirName)
Construct a TDirectory* for the given module
Definition at line 414 of file Process.cxx.
{
   auto owner{openHistoFile()};
   TDirectory *child = owner->mkdir((char *)dirName.c_str());
   if (child) child->cd();
   return child;
 }
References openHistoFile().
Referenced by framework::EventProcessor::getHistoDirectory().
openHistoFile()
TDirectory * framework::Process::openHistoFile ()
Open a ROOT TFile to write histograms and TTrees.
Definition at line 421 of file Process.cxx.
{
   TDirectory *owner{nullptr};
   if (histoFilename_.empty()) {
     // trying to write histograms/ntuples but no file defined
     EXCEPTION_RAISE("NoHistFileName",
                     "You did not provide the necessary histogram file name to "
                     "put your histograms (or ntuples) in.\n    Provide this "
                     "name in the python configuration with 'p.histogramFile = "
                     "\"myHistFile.root\"' where p is the Process object.");
   } else if (histoTFile_ == nullptr) {
     histoTFile_ = new TFile(histoFilename_.c_str(), "RECREATE");
     owner = histoTFile_;
   } else
     owner = histoTFile_;
   owner->cd();
   return owner;
 }
References histoFilename_, and histoTFile_.
Referenced by makeHistoDirectory().
requestFinish()
void framework::Process::requestFinish () inline
Request that the processing finish with this event
Definition at line 93 of file Process.h.
 { eventLimit_ = 0; }
References eventLimit_.
run()
void framework::Process::run ()
Run the process.
Definition at line 116 of file Process.cxx.
                   {
   // set up the logging for this run
   logging::open(logging::convertLevel(termLevelInt_),
                 logging::convertLevel(fileLevelInt_),
                 logFileName_  // if this is empty string, no file is logged to
   );
   // create a logger for this process
   //      other objects will have their own channels
   //      the ldmx_log macro uses a variable called theLog_,
   //      so we are going to name it that for now.
   auto theLog_{logging::makeLogger("Process")};
   // Counter to keep track of the number of events that have been
   // procesed
   auto n_events_processed{0};
   // event bus for this process
   Event theEvent(passname_);
   // Start by notifying everyone that modules processing is beginning
   conditions_.onProcessStart();
   for (auto module : sequence_) module->onProcessStart();
   // If we have no input files, but do have an event number, run for
   // that number of events and generate an output file.
   if (inputFiles_.empty() && eventLimit_ > 0) {
     if (outputFiles_.empty()) {
       EXCEPTION_RAISE("InvalidConfig",
                       "No input files or output files were given.");
     } else if (outputFiles_.size() > 1) {
       ldmx_log(warn) << "Several output files given with no input files. "
                      << "Only the first output file '" << outputFiles_.at(0)
                      << "' will be used.";
     }
     std::string outputFileName = outputFiles_.at(0);
     // Configure the event file to create an output file with no parent. This
     // requires setting the parameters isOutputFile and isSingleOutput to true.
     EventFile outFile(config_, outputFileName, nullptr, true, true, false);
     for (auto module : sequence_) module->onFileOpen(outFile);
     outFile.setupEvent(&theEvent);
     for (auto rule : dropKeepRules_) outFile.addDrop(rule);
     ldmx::RunHeader runHeader(runForGeneration_);
     runHeader.setRunStart(std::time(nullptr));  // set run starting
     runHeader_ = &runHeader;            // give handle to run header to process
     outFile.writeRunHeader(runHeader);  // add run header to file
     for (auto module : sequence_)
       if (dynamic_cast<Producer *>(module))
         dynamic_cast<Producer *>(module)->beforeNewRun(runHeader);
     // now run header has been modified by Producers, so it is valid to read
     // from
     conditions_.onNewRun(runHeader);
     for (auto module : sequence_) module->onNewRun(runHeader);
     int numTries = 0;  // number of tries for the current event number
     while (n_events_processed < eventLimit_) {
       ldmx::EventHeader &eh = theEvent.getEventHeader();
       eh.setRun(runForGeneration_);
       eh.setEventNumber(n_events_processed + 1);
       eh.setTimestamp(TTimeStamp());
       // event header pointer grab
       eventHeader_ = theEvent.getEventHeaderPtr();
       numTries++;
       // reset the storage controller state
       m_storageController.resetEventState();
       if (numTries <= 1 and getLogFrequency() > 0 and
           (eh.getEventNumber() % getLogFrequency() == 0)) {
         TTimeStamp t;
         ldmx_log(info) << "Processing " << n_events_processed + 1 << " Run "
                        << theEvent.getEventHeader().getRun() << " Event "
                        << theEvent.getEventHeader().getEventNumber() << "  ("
                        << t.AsString("lc") << ")";
       }
       bool eventAborted = false;
       for (auto module : sequence_) {
         try {
           if (dynamic_cast<Producer *>(module)) {
             (dynamic_cast<Producer *>(module))->produce(theEvent);
           } else if (dynamic_cast<Analyzer *>(module)) {
             (dynamic_cast<Analyzer *>(module))->analyze(theEvent);
           }
         } catch (AbortEventException &) {
           eventAborted = true;
           break;
         }
       }
       outFile.nextEvent(
           eventAborted
               ? false
               : m_storageController
                     .keepEvent() /*ignore storage control if event aborted*/);
       if (not eventAborted or numTries >= maxTries_) {
         n_events_processed++;                 // increment events made
         NtupleManager::getInstance().fill();  // fill ntuples
         numTries = 0;                         // reset try counter
       }
       NtupleManager::getInstance().clear();
       theEvent.Clear();
     }
     for (auto module : sequence_) module->onFileClose(outFile);
     runHeader.setRunEnd(std::time(nullptr));
     ldmx_log(info) << runHeader;
     outFile.close();
   } else {
     // there are input files
     EventFile *outFile(0);
     bool singleOutput = false;
     if (outputFiles_.size() == 1) {
       singleOutput = true;
     } else if (!outputFiles_.empty() and
                outputFiles_.size() != inputFiles_.size()) {
       EXCEPTION_RAISE("Process",
                       "Unable to handle case of different number of input and "
                       "output files (other than zero/one ouput file).");
     }
     // next, loop through the files
     int ifile = 0;
     int wasRun = -1;
     for (auto infilename : inputFiles_) {
       EventFile inFile(config_, infilename);
       ldmx_log(info) << "Opening file " << infilename;
       for (auto module : sequence_) module->onFileOpen(inFile);
       // configure event file that will be iterated over
       EventFile *masterFile;
       if (!outputFiles_.empty()) {
         // setup new output file if either
         // 1) we are not in single output mode
         // 2) this is the first input file
         if (!singleOutput or ifile == 0) {
           // setup new output file
           outFile = new EventFile(config_, outputFiles_[ifile], &inFile, singleOutput);
           ifile++;
           // setup theEvent we will iterate over
           if (outFile) {
             outFile->setupEvent(&theEvent);
             masterFile = outFile;
           } else {
             EXCEPTION_RAISE("Process", "Unable to construct output file for " +
                                            outputFiles_[ifile]);
           }
           for (auto rule : dropKeepRules_) outFile->addDrop(rule);
         } else {
           // all other input files
           outFile->updateParent(&inFile);
           masterFile = outFile;
         }  // check if in singleOutput mode
       } else {
         // empty output file list, use inputFile as master file
         inFile.setupEvent(&theEvent);
         masterFile = &inFile;
       }
       bool eventAborted = false;
       while (
           masterFile->nextEvent(eventAborted ? false
                                              : m_storageController.keepEvent() /*ignore storage controller if event aborted*/) &&
           (eventLimit_ < 0 || (n_events_processed) < eventLimit_)) {
         // clean up for storage control calculation
         m_storageController.resetEventState();
         // event header pointer grab
         eventHeader_ = theEvent.getEventHeaderPtr();
         // notify for new run if necessary
         if (theEvent.getEventHeader().getRun() != wasRun) {
           wasRun = theEvent.getEventHeader().getRun();
           try {
             auto runHeader = masterFile->getRunHeader(wasRun);
             runHeader_ = &runHeader;  // save current run header for later
             ldmx_log(info) << "Got new run header from '"
                            << masterFile->getFileName() << "' ...\n"
                            << runHeader;
             for (auto module : sequence_)
               if (dynamic_cast<Producer *>(module))
                 dynamic_cast<Producer *>(module)->beforeNewRun(runHeader);
             // now run header has been modified by Producers, so it is valid to
             // read from
             conditions_.onNewRun(runHeader);
             for (auto module : sequence_) module->onNewRun(runHeader);
           } catch (const framework::exception::Exception &) {
             ldmx_log(warn) << "Run header for run " << wasRun
                            << " was not found!";
           }
         }
         if ((logFrequency_ != -1) &&
             ((n_events_processed + 1) % logFrequency_ == 0)) {
           TTimeStamp t;
           ldmx_log(info) << "Processing " << n_events_processed + 1 << " Run "
                          << theEvent.getEventHeader().getRun() << " Event "
                          << theEvent.getEventHeader().getEventNumber() << "  ("
                          << t.AsString("lc") << ")";
         }
         eventAborted = false;
         for (auto module : sequence_) {
           try {
             if (dynamic_cast<Producer *>(module)) {
               (dynamic_cast<Producer *>(module))->produce(theEvent);
             } else if (dynamic_cast<Analyzer *>(module)) {
               (dynamic_cast<Analyzer *>(module))->analyze(theEvent);
             }
           } catch (AbortEventException &) {
             eventAborted = true;
             break;
           }
         }
         if (not eventAborted) NtupleManager::getInstance().fill();
         NtupleManager::getInstance().clear();
         n_events_processed++;
       }  // loop through events
       if (eventLimit_ > 0 && n_events_processed == eventLimit_) {
         ldmx_log(info) << "Reached event limit of " << eventLimit_ << " events";
       }
       if (eventLimit_ == 0 && n_events_processed > eventLimit_) {
         ldmx_log(warn) << "Processing interrupted";
       }
       ldmx_log(info) << "Closing file " << infilename;
       for (auto module : sequence_) module->onFileClose(inFile);
       inFile.close();
       // Reset the event in case of multiple input files
       theEvent.onEndOfFile();
       if (outFile and !singleOutput) {
         outFile->close();
         delete outFile;
         outFile = nullptr;
       }
     }  // loop through input files
     if (outFile) {
       // close outFile
       //  outFile would survive to here in single output mode
       outFile->close();
       delete outFile;
       outFile = nullptr;
     }
   }  // are there input files? if-else tree
   // close up histogram file if anything was put into it
   if (histoTFile_) {
     histoTFile_->Write();
     delete histoTFile_;
     histoTFile_ = 0;
   }
   // finally, notify everyone that we are stopping
   for (auto module : sequence_) {
     module->onProcessEnd();
   }
   // we're done so let's close up the logging
   logging::close();
 }
References framework::EventFile::addDrop(), framework::Event::Clear(), framework::NtupleManager::clear(), framework::EventFile::close(), conditions_, config_, dropKeepRules_, eventHeader_, eventLimit_, fileLevelInt_, framework::Event::getEventHeader(), framework::Event::getEventHeaderPtr(), ldmx::EventHeader::getEventNumber(), framework::EventFile::getFileName(), framework::NtupleManager::getInstance(), getLogFrequency(), ldmx::EventHeader::getRun(), framework::EventFile::getRunHeader(), histoTFile_, inputFiles_, framework::StorageControl::keepEvent(), logFileName_, logFrequency_, m_storageController, maxTries_, framework::EventFile::nextEvent(), framework::Event::onEndOfFile(), framework::Conditions::onNewRun(), framework::Conditions::onProcessStart(), outputFiles_, passname_, framework::StorageControl::resetEventState(), runForGeneration_, runHeader_, sequence_, ldmx::EventHeader::setEventNumber(), ldmx::EventHeader::setRun(), ldmx::RunHeader::setRunEnd(), ldmx::RunHeader::setRunStart(), ldmx::EventHeader::setTimestamp(), framework::EventFile::setupEvent(), termLevelInt_, framework::EventFile::updateParent(), and framework::EventFile::writeRunHeader().
Referenced by Process().
setEventHeader()
void framework::Process::setEventHeader (ldmx::EventHeader * h) inline
Set the pointer to the current event header, used only for tests
Definition at line 113 of file Process.h.
 { eventHeader_ = h; }
References eventHeader_.
Member Data Documentation
compressionSetting_
int framework::Process::compressionSetting_ private
Compression setting to pass to output files
Look at the documentation for the TFile constructor if you want to learn more details. Essentially, setting = 100*algo + level with algo = 0 being the global default.
Definition at line 183 of file Process.h.
Referenced by Process().
conditions_
Conditions framework::Process::conditions_ private
Set of ConditionsProviders
Definition at line 167 of file Process.h.
Referenced by getConditions(), Process(), and run().
dropKeepRules_
std::vector<std::string> framework::Process::dropKeepRules_ private
Set of drop/keep rules.
Definition at line 186 of file Process.h.
Referenced by Process(), and run().
eventHeader_
const ldmx::EventHeader* framework::Process::eventHeader_ {0} private
Pointer to the current EventHeader, used for Conditions information
Definition at line 195 of file Process.h.
Referenced by getEventHeader(), getRunNumber(), Process(), run(), and setEventHeader().
eventLimit_
int framework::Process::eventLimit_ private
Limit on events to process.
Definition at line 143 of file Process.h.
Referenced by Process(), requestFinish(), and run().
fileLevelInt_
int framework::Process::fileLevelInt_ private
Integer form of logging level to print to file
Definition at line 152 of file Process.h.
Referenced by Process(), and run().
histoFilename_
std::string framework::Process::histoFilename_ private
Filename for histograms and other user products
Definition at line 192 of file Process.h.
Referenced by openHistoFile(), and Process().
histoTFile_
TFile* framework::Process::histoTFile_ {0} private
TFile for histograms and other user products
Definition at line 201 of file Process.h.
Referenced by openHistoFile(), and run().
inputFiles_
std::vector<std::string> framework::Process::inputFiles_ private
List of input files to process. May be empty if this Process will generate new events.
Definition at line 171 of file Process.h.
Referenced by Process(), and run().
logFileName_
std::string framework::Process::logFileName_ private
Name of file to print logging to
Definition at line 155 of file Process.h.
Referenced by Process(), and run().
logFrequency_
int framework::Process::logFrequency_ private
The frequency with which event info is printed.
Definition at line 146 of file Process.h.
Referenced by getLogFrequency(), Process(), and run().
m_storageController
StorageControl framework::Process::m_storageController private
Storage controller
Definition at line 161 of file Process.h.
Referenced by getStorageController(), Process(), and run().
maxTries_
int framework::Process::maxTries_ private
Maximum number of attempts to make before giving up on an event
Definition at line 158 of file Process.h.
Referenced by Process(), and run().
outputFiles_
std::vector<std::string> framework::Process::outputFiles_ private
List of output file names. If empty, no output file will be created.
Definition at line 174 of file Process.h.
Referenced by Process(), and run().
passname_
std::string framework::Process::passname_ private
Processing pass name.
Definition at line 140 of file Process.h.
Referenced by getPassName(), Process(), and run().
runForGeneration_
int framework::Process::runForGeneration_ {1} private
Run number to use if generating events.
Definition at line 189 of file Process.h.
Referenced by getRunNumber(), Process(), and run().
runHeader_
const ldmx::RunHeader* framework::Process::runHeader_ {0} private
Pointer to the current RunHeader, used for Conditions information
Definition at line 198 of file Process.h.
Referenced by getRunHeader(), and run().
sequence_
std::vector<EventProcessor *> framework::Process::sequence_ private
Ordered list of EventProcessors to execute.
Definition at line 164 of file Process.h.
Referenced by Process(), run(), and ~Process().
termLevelInt_
int framework::Process::termLevelInt_ private
Integer form of logging level to print to terminal
Definition at line 149 of file Process.h.
Referenced by Process(), and run().
The documentation for this class was generated from the following files:
Framework/include/Framework/Process.h
Framework/src/Framework/Process.cxx