LDMX Software: G4APrime Class Reference
G4APrime Class Reference
#include <G4APrime.h>
Static Public Member Functions
static G4APrime * APrime ()
static void Initialize (double mass, int id=62)
Private Member Functions
G4APrime (const G4String &Name, G4double mass, G4double width, G4double charge, G4int iSpin, G4int iParity, G4int iConjugation, G4int iIsospin, G4int iIsospin3, G4int gParity, const G4String &pType, G4int lepton, G4int baryon, G4int encoding, G4bool stable, G4double lifetime, G4DecayTable *decaytable)
virtual ~G4APrime ()
Static Private Attributes
static G4APrime * theAPrime = 0
Detailed Description
Formal class representing the A' (a dark photon)
This class follows the standard prototype for all G4ParticleDefinitions where a static private member holds onto the single instance of this particle definition to be shared by everyone. In this case, G4APrime::Initialize needs to be called before any calls to G4APrime::G4APrime so that the simulation has a defined A' mass.
The G4APrime::Initialize call should be done in the ConstructParticle function of a physics constructor.
Definition at line 29 of file G4APrime.h.
Constructor & Destructor Documentation
G4APrime()
G4APrime::G4APrime (const G4String & Name, G4double mass, G4double width, G4double charge, G4int iSpin, G4int iParity, G4int iConjugation, G4int iIsospin, G4int iIsospin3, G4int gParity, const G4String & pType, G4int lepton, G4int baryon, G4int encoding, G4bool stable, G4double lifetime, G4DecayTable * decaytable) inline private
Constructor
Passes all parameters to the base class constructor to register this particle definition with Geant4.
Definition at line 40 of file G4APrime.h.
      : G4ParticleDefinition(Name, mass, width, charge, iSpin, iParity,
                             iConjugation, iIsospin, iIsospin3, gParity, pType,
                             lepton, baryon, encoding, stable, lifetime,
                             decaytable) {}
~G4APrime()
virtual G4APrime::~G4APrime () inline private virtual
Destructor
Does nothing on purpose.
Definition at line 55 of file G4APrime.h.
{}
Member Function Documentation
APrime()
G4APrime * G4APrime::APrime () static
Accessor for APrime definition
Exceptions
std::runtime_error if the APrime is not initialized yet.
See also
Initialize for configuring and constructing the APrime at the start of a run.
Definition at line 15 of file G4APrime.cxx.
{
  if (!theAPrime) {
    throw std::runtime_error("Attempting to access the APrime particle before it has been initialized.");
  }
  return theAPrime;
}
References theAPrime.
Referenced by biasing::EcalDarkBremFilter::ClassifyNewTrack(), g4db::G4DarkBreMModel::ComputeCrossSectionPerAtom(), g4db::G4DarkBreMModel::G4DarkBreMModel(), g4db::G4DarkBreMModel::GenerateChange(), biasing::EcalDarkBremFilter::PostUserTrackingAction(), g4db::example::FindDarkBremProducts::PreUserTrackingAction(), g4db::G4DarkBreMModel::scale(), and biasing::TargetDarkBremFilter::stepping().
Initialize()
void G4APrime::Initialize (double mass, int id = 62) static
Initialize the APrime particle with the passed configuration
Exceptions
std::runtime_error if the APrime has already been initialized
Parameters
[in] mass The mass of the APrime in MeV
[in] id The PDG ID number to use for the APrime particle
The default value for the PDG ID is set to 62 and has been arbitrarily chosen from the range defined by 11(c) in the PDG ID numbering scheme, avoiding the already-defined "one-of-a-kind" particles using 39, 41, and 42.
Here are the properties of the formal Geant4 dark photon we define.
Property Value
short name A^1
mass configured
mass width 0
electric charge 0
spin 0
parity 0
conjugation 0
isospin 0
isospin3 0
Gparity 0
long name APrime
lepton number 0
baryon number 0
PDG ID encoding configured
is stable (no decay) true
lifetime -1 (i.e. no decay)
decay table nullptr (i.e. no decay)
Definition at line 23 of file G4APrime.cxx.
{
  if (theAPrime)
    throw std::runtime_error("Attempting to initialize the APrime particle more than once.");
  theAPrime = new G4APrime(
      "A^1" /* short name */, mass * MeV,
      0. /* mass width */, 0. /*electric charge */,
      0 /* spin */, 0 /* parity */, 0 /* conjugation */,
      0 /* isospine */, 0 /* isospin3 */, 0 /* G parity */,
      "APrime" /* long name */, 0 /* lepton number */,
      0 /* baryon number */, id, true /* stable? */,
      -1 /* lifetime */, nullptr /* decay table */
      );
  return;
}
References theAPrime.
Referenced by simcore::APrimePhysics::ConstructParticle(), g4db::example::APrimePhysics::ConstructParticle(), and main().
Member Data Documentation
theAPrime
G4APrime * G4APrime::theAPrime = 0 static private
Reference to single particle definition of A'
Definition at line 32 of file G4APrime.h.
Referenced by APrime(), and Initialize().
The documentation for this class was generated from the following files:
SimCore/G4DarkBreM/include/G4DarkBreM/G4APrime.h
SimCore/G4DarkBreM/src/G4DarkBreM/G4APrime.cxx