LDMX Software: ldmx::ConfigurePython Class Reference
ldmx::ConfigurePython Class Reference
Utility class which reads/executes a python script and creates a Process object based on the input.
#include <ConfigurePython.h>
Public Member Functions
ConfigurePython (const std::string &pythonScript, char *args[], int nargs)
~ConfigurePython ()
ProcessHandle makeProcess ()
Private Member Functions
std::map< std::string, std::any > getParameters (PyObject *dictionary)
Private Attributes
std::string passname_
int eventLimit_ {-1}
int run_ {-1}
int logFrequency_ {-1}
std::vector< std::string > inputFiles_
std::vector< std::string > keepRules_
bool skimDefaultIsKeep_
std::vector< std::string > skimRules_
std::vector< std::string > libraries_
std::vector< std::string > outputFiles_
int compressionSetting_
std::string histoOutFile_ {""}
std::vector< ProcessorClass > sequence_
Detailed Description
Utility class which reads/executes a python script and creates a Process object based on the input.
Note
The configuration language is documented in the overall Framework package documentation.
Definition at line 73 of file ConfigurePython.h.
Constructor & Destructor Documentation
ConfigurePython()
ldmx::ConfigurePython::ConfigurePython (const std::string & pythonScript, char * args[], int nargs)
Class constructor.
This method contains all the parsing and execution of the python script.
Exceptions
Exception if any necessary components of the python configuration are missing. e.g. The Process class or the different members of the lastProcess object.
The basic premis of this constructor is to execute the python configuration script by loading it into python as a module. Then, after the script has been executed, all of the parameters for the Process and EventProcessors are gathered from python. The fact that the script has been executed means that the user can get up to a whole lot of nonsense that can help them make their work more efficient.
Parameters
pythonScript Filename location of the python script.
args Commandline arguments to be passed to the python script.
nargs Number of commandline arguments.
Definition at line 184 of file ConfigurePython.cxx.
{
         //assumes that nargs >= 0
         //  this is true always because we error out if no python script has been found
         std::string cmd = pythonScript;
         if (pythonScript.rfind("/") != std::string::npos) {
             cmd = pythonScript.substr(pythonScript.rfind("/") + 1);
         }
         cmd = cmd.substr(0, cmd.find(".py"));
         Py_Initialize();
         //python needs the argument list as if you are on the command line
         //  targs = [ script , arg0 , arg1 , ... ] ==> len(targs) = nargs+1
         //The third argument to PySys_SetArgvEx tells python to import
         //the args and add the directory of the first argument to
         //the PYTHONPATH
         //This way, the command to import the module just needs to be
         //the name of the python script
 #if PY_MAJOR_VERSION < 3
         char** targs = new char*[nargs+1];
         targs[0] = (char*) pythonScript.c_str();
         for (int i = 0; i < nargs; i++)
             targs[i+1] = args[i];
         PySys_SetArgvEx(nargs+1, targs, 1);
         delete [ ] targs; //1D array because args is owned by main
 #else
         //PySys_SetArgvEx uses wchar_t instead of char in python3
         wchar_t** targs = new wchar_t*[nargs+1];
         targs[0] = getWC(pythonScript.c_str());
         for (int i = 0; i < nargs;  i++)
             targs[i+1] = getWC(args[i]);
         PySys_SetArgvEx(nargs+1, targs, 1);
         //clean up the 2D character array
         for ( int i = 0; i < nargs+1; i++ )
             delete [] targs[i];
         delete [] targs;
 #endif
         //the following line is what actually runs the script
         PyObject* script = PyImport_ImportModule(cmd.c_str());
         if (script == 0) {
             PyErr_Print();
             EXCEPTION_RAISE("ConfigureError", "Problem loading python script");
         }
         PyObject* pCMod = PyObject_GetAttrString(script, "ldmxcfg");
         Py_DECREF(script); //don't need the script anymore
         if (pCMod == 0) {
             PyErr_Print();
             EXCEPTION_RAISE("ConfigureError", "Problem loading python script");
         }
         PyObject* pProcessClass = PyObject_GetAttrString(pCMod, "Process");
         Py_DECREF(pCMod); //don't need the config module anymore
         if (pProcessClass == 0) {
             PyErr_Print();
             EXCEPTION_RAISE("ConfigureError",
                     "Process object not defined. This object is required to run ldmx-app."
                     );
         }
         PyObject* pProcess = PyObject_GetAttrString(pProcessClass, "lastProcess");
         Py_DECREF(pProcessClass); //don't need the Process class anymore
         if (pProcess == 0) {
             //wasn't able to get lastProcess class member
             PyErr_Print();
             EXCEPTION_RAISE("ConfigureError",
                     "Process object not defined. This object is required to run ldmx-app."
                     );
         } else if ( pProcess == Py_None ) {
             //lasProcess was left undefined
             EXCEPTION_RAISE("ConfigureError",
                     "Process object not defined. This object is required to run ldmx-app."
                     );
         }
         //okay, now we have fully imported the script and gotten the handle
         //to the last Process object defined in the script.
         //We can now look at pProcess and get all of our parameters out of it.
         keepRules_    = stringListMember( pProcess , "keep" );
         skimRules_    = stringListMember( pProcess , "skimRules" );
         inputFiles_   = stringListMember( pProcess , "inputFiles" );
         outputFiles_  = stringListMember( pProcess , "outputFiles" );
         libraries_    = stringListMember( pProcess , "libraries" );
         eventLimit_   = intMember( pProcess , "maxEvents" );
         run_          = intMember( pProcess , "run" );
         logFrequency_ = intMember( pProcess , "logFrequency" );
         compressionSetting_ = intMember( pProcess , "compressionSetting" );
         histoOutFile_ = stringMember( pProcess , "histogramFile" );
         passname_     = stringMember( pProcess , "passName" );
         skimDefaultIsKeep_ = bool(intMember(pProcess, "skimDefaultIsKeep"));
         //Now the more complicated paramter: sequence
         //  we need to go through this list and attach all of the parameters
         //  of each processor to itself as well
         PyObject* pysequence = PyObject_GetAttrString( pProcess , "sequence" );
         for (auto i{0}; i < PyList_Size(pysequence); ++i) {
             PyObject* processor{PyList_GetItem(pysequence, i)};
             ProcessorClass pc;
             pc.className_ = stringMember(processor, "className");
             pc.instanceName_ = stringMember(processor, "instanceName");
             PyObject* histos{PyObject_GetAttrString(processor, "histograms")};
             for (auto ihisto{0}; ihisto < PyList_Size(histos); ++ihisto) {
                 PyObject* histogram{PyList_GetItem(histos, ihisto)};
                 HistogramInfo histInfo;
                 histInfo.name_   = stringMember(histogram, "name");
                 histInfo.xLabel_ = stringMember(histogram, "xlabel");
                 histInfo.bins_   = intMember(histogram, "bins");
                 histInfo.xmin_   = intMember(histogram, "xmin");
                 histInfo.xmax_   = intMember(histogram, "xmax");
                 pc.histograms_.push_back(histInfo);
                 Py_DECREF(histogram);
             }
             Py_DECREF(histos);
             PyObject* parameters{PyObject_GetAttrString(processor, "parameters")};
             if (parameters != 0 && PyDict_Check(parameters)) {
                 auto params{getParameters(parameters)};
                 pc.params_.setParameters(params);
             }
             Py_DECREF(parameters);
             sequence_.push_back(pc);
             Py_DECREF(processor);
         }
         Py_DECREF(pysequence);
         //all done with python nonsense
         //do nothing for some reason ¯\_(ツ)_/¯
         //  too lazy to figure out how to close up python well
         //  calling the below function leads to a seg fault on
         //  some machines
         //Py_Finalize();
     }
References ldmx::HistogramInfo::bins_, ldmx::Class::className_, compressionSetting_, eventLimit_, EXCEPTION_RAISE, getParameters(), ldmx::getWC(), ldmx::ProcessorClass::histograms_, histoOutFile_, inputFiles_, ldmx::Class::instanceName_, ldmx::intMember(), keepRules_, libraries_, logFrequency_, ldmx::HistogramInfo::name_, outputFiles_, ldmx::Class::params_, passname_, run_, sequence_, ldmx::Parameters::setParameters(), skimDefaultIsKeep_, skimRules_, ldmx::stringListMember(), ldmx::stringMember(), ldmx::HistogramInfo::xLabel_, ldmx::HistogramInfo::xmax_, and ldmx::HistogramInfo::xmin_.
~ConfigurePython()
ldmx::ConfigurePython::~ConfigurePython () inline
Class destructor.
Does nothing at the moment.
Definition at line 105 of file ConfigurePython.h.
 { }
Member Function Documentation
getParameters()
std::map< std::string, std::any > ldmx::ConfigurePython::getParameters (PyObject * dictionary) private
Extract parameter array from a python object.
Assumes that the input PyObject is a python dictionary.
Iterates through the dictionary and translates the objects inside of it into the type-specified C++ equivalents, then puts these objects into a STL map that can be passed to the Parameters class.
Parameters
dictionary Python dictionary class.
Returns
Mapping between parameter name and value.
Definition at line 388 of file ConfigurePython.cxx.
{
         PyObject *key(0), *value(0);
         Py_ssize_t pos = 0;
         std::map < std::string, std::any > params;
         while (PyDict_Next(dictionary, &pos, &key, &value)) {
             std::string skey{getPyString(key)};
             if (isPyInt(value)) {
                 if (PyBool_Check(value)) {
                     params[skey] = bool(PyLong_AsLong(value));
                 } else {
                     params[skey] = int(PyLong_AsLong(value));
                 }
             } else if (PyFloat_Check(value)) {
                 params[skey] = PyFloat_AsDouble(value);
             } else if (isPyString(value)) {
                 params[skey] = getPyString(value);
             } else if (PyList_Check(value)) { // assume everything is same value as first value
                 if (PyList_Size(value) > 0) {
                     auto vec0{PyList_GetItem(value, 0)};
                     if (isPyInt(vec0)) {
                         std::vector<int> vals;
                         for (auto j{0}; j < PyList_Size(value); j++)
                             vals.push_back(PyLong_AsLong(PyList_GetItem(value, j)));
                         params[skey] = vals;
                     } else if (PyFloat_Check(vec0)) {
                         std::vector<double> vals;
                         for (auto j{0}; j < PyList_Size(value); j++)
                             vals.push_back(PyFloat_AsDouble(PyList_GetItem(value, j)));
                         params[skey] = vals;
                     } else if (isPyString(vec0)) {
                         std::vector<std::string> vals;
                         for (Py_ssize_t j = 0; j < PyList_Size(value); j++){
                             PyObject* elem = PyList_GetItem(value , j );
                             vals.push_back(getPyString(elem));
                             Py_DECREF(elem);
                         }
                         params[skey] = vals;
                     } else {
                         // If the objects stored in the list doesn't
                         // satisfy any of the above conditions, just
                         // create a vector of Class objects.
                         std::vector< Class > vals;
                         for (auto j{0}; j < PyList_Size(value); ++j) {
                             auto object{PyList_GetItem( value, j )};
                             Class c;
                             c.className_    = stringMember(object, "class_name");
                             c.instanceName_ = stringMember(object, "instance_name");
                             auto dict{PyObject_GetAttrString(object, "parameters")};
                             auto classParams{getParameters(dict)};
                             c.params_.setParameters(classParams);
                             Py_DECREF(dict);
                             vals.push_back(c);
                             Py_DECREF(object);
                         }
                         params[skey] = vals;
                     } //type of object in python list
                 } //python list has non-zero size
             } //python object type
             Py_XDECREF( key );
             Py_XDECREF(value);
         } //loop through python dictionary
         return params;
     }
References ldmx::Class::className_, ldmx::getPyString(), ldmx::Class::instanceName_, ldmx::isPyInt(), ldmx::isPyString(), ldmx::Class::params_, ldmx::Parameters::setParameters(), and ldmx::stringMember().
Referenced by ConfigurePython().
makeProcess()
ProcessHandle ldmx::ConfigurePython::makeProcess ()
Create a process object based on the python file information
No python parsing actually happens in this function. All of the parsing is done in the constructor, this just copies that information into the Process object.
Definition at line 336 of file ConfigurePython.cxx.
{
         //no python nonsense happens in here,
         //this just takes the parameters determined earlier
         //and puts them into the Process + EventProcessor framework
         auto process{std::make_unique<Process>(passname_)};
         process->setHistogramFileName(histoOutFile_);
         process->setEventLimit(eventLimit_);
         process->setLogFrequency(logFrequency_);
         std::for_each(libraries_.begin(), libraries_.end(),
                 [](auto& lib) { EventProcessorFactory::getInstance().loadLibrary(lib);}
                 );
         for (auto proc : sequence_) {
             EventProcessor* ep = EventProcessorFactory::getInstance().createEventProcessor(proc.className_, proc.instanceName_, *process);
             if (ep == 0) {
                 EXCEPTION_RAISE("UnableToCreate", "Unable to create instance '" + proc.instanceName_ + "' of class '" + proc.className_ + "'");
             }
             if (!proc.histograms_.empty()) {
                 HistogramPool* histograms = HistogramPool::getInstance();
                 ep->getHistoDirectory();
                 for (const auto& hist : proc.histograms_) {
                     histograms->create<TH1F>(hist.name_, hist.xLabel_, hist.bins_, hist.xmin_, hist.xmax_);
                 }
             }
             ep->configure(proc.params_);
             process->addToSequence(ep);
         }
         for (auto file : inputFiles_) {
             process->addFileToProcess(file);
         }
         for (auto file : outputFiles_) {
             process->addOutputFileName(file);
         }
         process->setCompressionSetting(compressionSetting_);
         for (auto rule : keepRules_) {
             process->addDropKeepRule(rule);
         }
         process->getStorageController().setDefaultKeep(skimDefaultIsKeep_);
         for (size_t i=0; i<skimRules_.size(); i+=2) {
             process->getStorageController().addRule(skimRules_[i],skimRules_[i+1]);
         }
         if (run_ > 0)
             process->setRunNumber(run_);
         return process;
     }
References compressionSetting_, ldmx::EventProcessor::configure(), ldmx::HistogramPool::create(), ldmx::EventProcessorFactory::createEventProcessor(), eventLimit_, EXCEPTION_RAISE, ldmx::EventProcessor::getHistoDirectory(), ldmx::EventProcessorFactory::getInstance(), histoOutFile_, inputFiles_, keepRules_, libraries_, logFrequency_, outputFiles_, passname_, run_, sequence_, skimDefaultIsKeep_, and skimRules_.
Member Data Documentation
compressionSetting_
int ldmx::ConfigurePython::compressionSetting_ private
Compression setting for the output files taken from python file.
Definition at line 187 of file ConfigurePython.h.
Referenced by ConfigurePython(), and makeProcess().
eventLimit_
int ldmx::ConfigurePython::eventLimit_ {-1} private
The maximum number of events to process, if provided in python file.
Definition at line 140 of file ConfigurePython.h.
Referenced by ConfigurePython(), and makeProcess().
histoOutFile_
std::string ldmx::ConfigurePython::histoOutFile_ {""} private
Histogram output file name
Definition at line 190 of file ConfigurePython.h.
Referenced by ConfigurePython(), and makeProcess().
inputFiles_
std::vector<std::string> ldmx::ConfigurePython::inputFiles_ private
List of input ROOT files to process in the job, if provided in python file.
Definition at line 155 of file ConfigurePython.h.
Referenced by ConfigurePython(), and makeProcess().
keepRules_
std::vector<std::string> ldmx::ConfigurePython::keepRules_ private
List of rules for keeping and dropping data products, if provided in python file.
Definition at line 161 of file ConfigurePython.h.
Referenced by ConfigurePython(), and makeProcess().
libraries_
std::vector<std::string> ldmx::ConfigurePython::libraries_ private
List of rules for shared libraries to load, if provided in python file.
Definition at line 176 of file ConfigurePython.h.
Referenced by ConfigurePython(), and makeProcess().
logFrequency_
int ldmx::ConfigurePython::logFrequency_ {-1} private
The frequency with which event info is printed.
Definition at line 149 of file ConfigurePython.h.
Referenced by ConfigurePython(), and makeProcess().
outputFiles_
std::vector<std::string> ldmx::ConfigurePython::outputFiles_ private
List of rules for output ROOT file names, if provided in python file.
Definition at line 182 of file ConfigurePython.h.
Referenced by ConfigurePython(), and makeProcess().
passname_
std::string ldmx::ConfigurePython::passname_ private
The label for this processing pass.
Definition at line 134 of file ConfigurePython.h.
Referenced by ConfigurePython(), and makeProcess().
run_
int ldmx::ConfigurePython::run_ {-1} private
The run number to use when generating events (no input file), if provided in python file.
Definition at line 146 of file ConfigurePython.h.
Referenced by ConfigurePython(), and makeProcess().
sequence_
std::vector<ProcessorClass> ldmx::ConfigurePython::sequence_ private
The sequence of EventProcessor objects to be executed in order.
Definition at line 193 of file ConfigurePython.h.
Referenced by ConfigurePython(), and makeProcess().
skimDefaultIsKeep_
bool ldmx::ConfigurePython::skimDefaultIsKeep_ private
Default sense for keeping events (keep or drop)
Definition at line 164 of file ConfigurePython.h.
Referenced by ConfigurePython(), and makeProcess().
skimRules_
std::vector<std::string> ldmx::ConfigurePython::skimRules_ private
List of rules for keeping and dropping events, if provided in python file.
Definition at line 170 of file ConfigurePython.h.
Referenced by ConfigurePython(), and makeProcess().
The documentation for this class was generated from the following files:
Framework/include/Framework/ConfigurePython.h
Framework/src/ConfigurePython.cxx