LDMX Software: ecal::DNNEcalVetoProcessor Class Reference
ecal::DNNEcalVetoProcessor Class Reference
Determines if event is vetoable using ECAL hit information w/ a deep neural network.
#include <DNNEcalVetoProcessor.h>
Public Member Functions
DNNEcalVetoProcessor (const std::string &name, framework::Process &process)
void configure (framework::config::Parameters &parameters) final override
void produce (framework::Event &event)
Public Member Functions inherited from framework::Producer
Producer (const std::string &name, Process &process)
virtual void produce (Event &event)=0
virtual void beforeNewRun (ldmx::RunHeader &header)
Public Member Functions inherited from framework::EventProcessor
EventProcessor (const std::string &name, Process &process)
virtual ~EventProcessor ()
virtual void configure (framework::config::Parameters &parameters)
virtual void onNewRun (const ldmx::RunHeader &runHeader)
virtual void onFileOpen (EventFile &eventFile)
virtual void onFileClose (EventFile &eventFile)
virtual void onProcessStart ()
virtual void onProcessEnd ()
template<class T >
const T & getCondition (const std::string &condition_name)
TDirectory * getHistoDirectory ()
void setStorageHint (framework::StorageControlHint hint)
void setStorageHint (framework::StorageControlHint hint, const std::string &purposeString)
int getLogFrequency () const
int getRunNumber () const
std::string getName () const
void createHistograms (const std::vector< framework::config::Parameters > &histos)
Private Member Functions
void make_inputs (const ldmx::EcalGeometry &geom, const std::vector< ldmx::EcalHit > &ecalRecHits)
Private Attributes
float disc_cut_ = -99
std::vector< std::vector< float > > data_
std::unique_ptr< ldmx::Ort::ONNXRuntime > rt_
std::string collectionName_ {"DNNEcalVeto"}
bool debug_ = false
Static Private Attributes
static constexpr unsigned int max_num_hits_ = 50
static constexpr unsigned int n_coordinate_dim_ = 3
static constexpr unsigned int coordinate_x_offset_ = 0
static constexpr unsigned int coordinate_y_offset_ = max_num_hits_
static constexpr unsigned int coordinate_z_offset_ = 2 * max_num_hits_
static constexpr unsigned int n_feature_dim_ = 5
static constexpr unsigned int feature_x_offset_ = 0
static constexpr unsigned int feature_y_offset_ = max_num_hits_
static constexpr unsigned int feature_z_offset_ = 2 * max_num_hits_
static constexpr unsigned int feature_layerid_offset_ = 3 * max_num_hits_
static constexpr unsigned int feature_energy_offset_ = 4 * max_num_hits_
static const std::vector< std::string > input_names_
static const std::vector< unsigned int > input_sizes_
Additional Inherited Members
Static Public Member Functions inherited from framework::EventProcessor
static void declare (const std::string &classname, int classtype, EventProcessorMaker *)
Static Public Attributes inherited from framework::Producer
static const int CLASSTYPE {1}
Protected Member Functions inherited from framework::EventProcessor
void abortEvent ()
Protected Attributes inherited from framework::EventProcessor
HistogramHelper histograms_
Interface class for making and filling histograms.
NtupleManager & ntuple_ {NtupleManager::getInstance()}
Manager for any ntuples.
logging::logger theLog_
The logger for this EventProcessor.
Detailed Description
Determines if event is vetoable using ECAL hit information w/ a deep neural network.
Definition at line 27 of file DNNEcalVetoProcessor.h.
Constructor & Destructor Documentation
DNNEcalVetoProcessor()
ecal::DNNEcalVetoProcessor::DNNEcalVetoProcessor (const std::string & name, framework::Process & process)
Definition at line 15 of file DNNEcalVetoProcessor.cxx.
    : Producer(name, process) {
  for (const auto& s : input_sizes_) {
    data_.emplace_back(s, 0);
  }
}
~DNNEcalVetoProcessor()
virtual ecal::DNNEcalVetoProcessor::~DNNEcalVetoProcessor () inline virtual
Definition at line 30 of file DNNEcalVetoProcessor.h.
{}
Member Function Documentation
configure()
void ecal::DNNEcalVetoProcessor::configure (framework::config::Parameters & parameters) final override virtual
Callback for the EventProcessor to configure itself from the given set of parameters.
The parameters a processor has access to are the member variables of the python class in the sequence that has className equal to the EventProcessor class name.
For an example, look at MyProcessor.
Parameters
parameters Parameters for configuration.
Reimplemented from framework::EventProcessor.
Definition at line 23 of file DNNEcalVetoProcessor.cxx.
{
  disc_cut_ = parameters.getParameter<double>("disc_cut");
  rt_ = std::make_unique<ldmx::Ort::ONNXRuntime>(
      parameters.getParameter<std::string>("model_path"));
  // debug mode
  debug_ = parameters.getParameter<bool>("debug");
  // Set the collection name as defined in the configuration
  collectionName_ = parameters.getParameter<std::string>("collection_name");
}
References framework::config::Parameters::getParameter().
make_inputs()
void ecal::DNNEcalVetoProcessor::make_inputs (const ldmx::EcalGeometry & geom, const std::vector< ldmx::EcalHit > & ecalRecHits) private
Make inputs to the DNN from ECAL RecHits.
Parameters
ecalRecHits The EcalHit collection.
Definition at line 75 of file DNNEcalVetoProcessor.cxx.
{
  // clear data
  for (auto& v : data_) {
    std::fill(v.begin(), v.end(), 0);
  }
  unsigned idx = 0;
  for (const auto& hit : ecalRecHits) {
    if (hit.getEnergy() <= 0) continue;
    ldmx::EcalID id(hit.getID());
    auto [x,y,z] = geom.getPosition(id);
    data_[0].at(coordinate_x_offset_ + idx) = x;
    data_[0].at(coordinate_y_offset_ + idx) = y;
    data_[0].at(coordinate_z_offset_ + idx) = z;
    data_[1].at(feature_x_offset_ + idx) = x;
    data_[1].at(feature_y_offset_ + idx) = y;
    data_[1].at(feature_z_offset_ + idx) = z;
    data_[1].at(feature_layerid_offset_ + idx) = id.layer();
    data_[1].at(feature_energy_offset_ + idx) = std::log(hit.getEnergy());
    ++idx;
  }
  if (debug_) {
    for (unsigned iname = 0; iname < input_names_.size(); ++iname) {
      std::cout << "=== " << input_names_[iname] << " ===" << std::endl;
      for (unsigned i = 0; i < input_sizes_[iname]; ++i) {
        std::cout << data_[iname].at(i) << ", ";
        if ((i + 1) % max_num_hits_ == 0) {
          std::cout << std::endl;
        }
      }
    }
  }  // debug
}
References ldmx::EcalGeometry::getPosition().
produce()
void ecal::DNNEcalVetoProcessor::produce (framework::Event & event) virtual
Process the event and put new data products into it.
Parameters
event The Event to process.
Implements framework::Producer.
Definition at line 36 of file DNNEcalVetoProcessor.cxx.
{
  ldmx::EcalVetoResult result;
  // Get the Ecal Geometry
  const auto& ecal_geometry = getCondition<ldmx::EcalGeometry>(
      ldmx::EcalGeometry::CONDITIONS_OBJECT_NAME);
  // Get the collection of digitized Ecal hits from the event.
  const auto ecalRecHits = event.getCollection<ldmx::EcalHit>("EcalRecHits");
  auto nhits = std::count_if(
      ecalRecHits.begin(), ecalRecHits.end(),
      [](const ldmx::EcalHit& hit) { return hit.getEnergy() > 0; });
  if (nhits < max_num_hits_) {
    // make inputs
    make_inputs(ecal_geometry, ecalRecHits);
    // run the DNN
    auto outputs = rt_->run(input_names_, data_)[0];
    result.setDiscValue(outputs.at(1));
  } else {
    result.setDiscValue(-99);
  }
  if (debug_) {
    std::cout << "... disc_val = " << result.getDisc() << std::endl;
  }
  result.setVetoResult(result.getDisc() > disc_cut_);
  // If the event passes the veto, keep it. Otherwise, drop the event.
  if (result.passesVeto()) {
    setStorageHint(framework::hint_shouldKeep);
  } else {
    setStorageHint(framework::hint_shouldDrop);
  }
  event.add(collectionName_, result);
}
References ldmx::EcalVetoResult::passesVeto().
Member Data Documentation
collectionName_
std::string ecal::DNNEcalVetoProcessor::collectionName_ {"DNNEcalVeto"} private
Name of the collection which will containt the results.
Definition at line 67 of file DNNEcalVetoProcessor.h.
coordinate_x_offset_
constexpr unsigned int ecal::DNNEcalVetoProcessor::coordinate_x_offset_ = 0 static constexpr private
Definition at line 48 of file DNNEcalVetoProcessor.h.
coordinate_y_offset_
constexpr unsigned int ecal::DNNEcalVetoProcessor::coordinate_y_offset_ = max_num_hits_ static constexpr private
Definition at line 49 of file DNNEcalVetoProcessor.h.
coordinate_z_offset_
constexpr unsigned int ecal::DNNEcalVetoProcessor::coordinate_z_offset_ = 2 * max_num_hits_ static constexpr private
Definition at line 50 of file DNNEcalVetoProcessor.h.
data_
std::vector<std::vector<float> > ecal::DNNEcalVetoProcessor::data_ private
Definition at line 63 of file DNNEcalVetoProcessor.h.
debug_
bool ecal::DNNEcalVetoProcessor::debug_ = false private
Definition at line 69 of file DNNEcalVetoProcessor.h.
disc_cut_
float ecal::DNNEcalVetoProcessor::disc_cut_ = -99 private
Definition at line 62 of file DNNEcalVetoProcessor.h.
feature_energy_offset_
constexpr unsigned int ecal::DNNEcalVetoProcessor::feature_energy_offset_ = 4 * max_num_hits_ static constexpr private
Definition at line 57 of file DNNEcalVetoProcessor.h.
feature_layerid_offset_
constexpr unsigned int ecal::DNNEcalVetoProcessor::feature_layerid_offset_ = 3 * max_num_hits_ static constexpr private
Definition at line 56 of file DNNEcalVetoProcessor.h.
feature_x_offset_
constexpr unsigned int ecal::DNNEcalVetoProcessor::feature_x_offset_ = 0 static constexpr private
Definition at line 53 of file DNNEcalVetoProcessor.h.
feature_y_offset_
constexpr unsigned int ecal::DNNEcalVetoProcessor::feature_y_offset_ = max_num_hits_ static constexpr private
Definition at line 54 of file DNNEcalVetoProcessor.h.
feature_z_offset_
constexpr unsigned int ecal::DNNEcalVetoProcessor::feature_z_offset_ = 2 * max_num_hits_ static constexpr private
Definition at line 55 of file DNNEcalVetoProcessor.h.
input_names_
const std::vector< std::string > ecal::DNNEcalVetoProcessor::input_names_ static private
Initial value:
{"coordinates",
                                                                  "features"}
Definition at line 59 of file DNNEcalVetoProcessor.h.
input_sizes_
const std::vector< unsigned int > ecal::DNNEcalVetoProcessor::input_sizes_ static private
Initial value:
{
    n_coordinate_dim_ * max_num_hits_, n_feature_dim_* max_num_hits_}
Definition at line 60 of file DNNEcalVetoProcessor.h.
max_num_hits_
constexpr unsigned int ecal::DNNEcalVetoProcessor::max_num_hits_ = 50 static constexpr private
Maximum number of hits allowed in ECAL. Events with more hits will be marked as BKG directly without running the DNN.
Definition at line 45 of file DNNEcalVetoProcessor.h.
n_coordinate_dim_
constexpr unsigned int ecal::DNNEcalVetoProcessor::n_coordinate_dim_ = 3 static constexpr private
Definition at line 47 of file DNNEcalVetoProcessor.h.
n_feature_dim_
constexpr unsigned int ecal::DNNEcalVetoProcessor::n_feature_dim_ = 5 static constexpr private
Definition at line 52 of file DNNEcalVetoProcessor.h.
rt_
std::unique_ptr<ldmx::Ort::ONNXRuntime> ecal::DNNEcalVetoProcessor::rt_ private
Definition at line 64 of file DNNEcalVetoProcessor.h.
The documentation for this class was generated from the following files:
Ecal/include/Ecal/DNNEcalVetoProcessor.h
Ecal/src/Ecal/DNNEcalVetoProcessor.cxx