LDMX Software: trigscint::TrigScintDigiProducer Class Reference
trigscint::TrigScintDigiProducer Class Reference
Performs digitization of simulated Trigger Scintillator data.
#include <TrigScintDigiProducer.h>
Public Types
typedef int layer
typedef std::pair< double, double > zboundaries
Public Member Functions
TrigScintDigiProducer (const std::string &name, framework::Process &process)
void configure (framework::config::Parameters &parameters) final override
void produce (framework::Event &event)
ldmx::TrigScintID generateRandomID (int module)
Public Member Functions inherited from framework::Producer
Producer (const std::string &name, Process &process)
virtual void produce (Event &event)=0
virtual void beforeNewRun (ldmx::RunHeader &header)
Public Member Functions inherited from framework::EventProcessor
EventProcessor (const std::string &name, Process &process)
virtual ~EventProcessor ()
virtual void configure (framework::config::Parameters &parameters)
virtual void onNewRun (const ldmx::RunHeader &runHeader)
virtual void onFileOpen (EventFile &eventFile)
virtual void onFileClose (EventFile &eventFile)
virtual void onProcessStart ()
virtual void onProcessEnd ()
template<class T >
const T & getCondition (const std::string &condition_name)
TDirectory * getHistoDirectory ()
void setStorageHint (framework::StorageControlHint hint)
void setStorageHint (framework::StorageControlHint hint, const std::string &purposeString)
int getLogFrequency () const
int getRunNumber () const
std::string getName () const
void createHistograms (const std::vector< framework::config::Parameters > &histos)
Private Attributes
std::unique_ptr< TRandom3 > random_ {nullptr}
Random number generator.
std::unique_ptr< ldmx::NoiseGenerator > noiseGenerator_ {nullptr}
Generate noise hits given the number of channels and mean noise.
bool verbose_ {false}
Class to set the verbosity level.
std::string inputCollection_
Name of the input collection containing the sim hits.
std::string inputPassName_
std::string outputCollection_
int stripsPerArray_ {50}
Number of strips per array.
int numberOfArrays_ {3}
Number of arrays.
double meanNoise_ {0}
Mean readout noise.
double mevPerMip_ {1.40}
Total MeV per MIP.
double pePerMip_ {13.5}
Total number of photoelectrons per MIP.
Additional Inherited Members
Static Public Member Functions inherited from framework::EventProcessor
static void declare (const std::string &classname, int classtype, EventProcessorMaker *)
Static Public Attributes inherited from framework::Producer
static const int CLASSTYPE {1}
Protected Member Functions inherited from framework::EventProcessor
void abortEvent ()
Protected Attributes inherited from framework::EventProcessor
HistogramHelper histograms_
Interface class for making and filling histograms.
NtupleManager & ntuple_ {NtupleManager::getInstance()}
Manager for any ntuples.
logging::logger theLog_
The logger for this EventProcessor.
Detailed Description
Performs digitization of simulated Trigger Scintillator data.
Definition at line 41 of file TrigScintDigiProducer.h.
Member Typedef Documentation
layer
typedef int trigscint::TrigScintDigiProducer::layer
Definition at line 43 of file TrigScintDigiProducer.h.
zboundaries
typedef std::pair<double, double> trigscint::TrigScintDigiProducer::zboundaries
Definition at line 45 of file TrigScintDigiProducer.h.
Constructor & Destructor Documentation
TrigScintDigiProducer()
trigscint::TrigScintDigiProducer::TrigScintDigiProducer (const std::string & name, framework::Process & process)
Definition at line 9 of file TrigScintDigiProducer.cxx.
    : Producer(name, process) {}
~TrigScintDigiProducer()
trigscint::TrigScintDigiProducer::~TrigScintDigiProducer ()
Definition at line 13 of file TrigScintDigiProducer.cxx.
{}
Member Function Documentation
configure()
void trigscint::TrigScintDigiProducer::configure (framework::config::Parameters & parameters) final override virtual
Callback for the processor to configure itself from the given set of parameters.
Parameters
parameters ParameterSet for configuration.
Reimplemented from framework::EventProcessor.
Definition at line 15 of file TrigScintDigiProducer.cxx.
{
  // Configure this instance of the producer
  stripsPerArray_ = parameters.getParameter<int>("number_of_strips");
  numberOfArrays_ = parameters.getParameter<int>("number_of_arrays");
  meanNoise_ = parameters.getParameter<double>("mean_noise");
  mevPerMip_ = parameters.getParameter<double>("mev_per_mip");
  pePerMip_ = parameters.getParameter<double>("pe_per_mip");
  inputCollection_ = parameters.getParameter<std::string>("input_collection");
  inputPassName_ = parameters.getParameter<std::string>("input_pass_name");
  outputCollection_ = parameters.getParameter<std::string>("output_collection");
  verbose_ = parameters.getParameter<bool>("verbose");
  random_ =
      std::make_unique<TRandom3>(parameters.getParameter<int>("randomSeed"));
  noiseGenerator_ = std::make_unique<ldmx::NoiseGenerator>(meanNoise_, false);
  noiseGenerator_->setNoiseThreshold(1);
}
References framework::config::Parameters::getParameter().
generateRandomID()
ldmx::TrigScintID trigscint::TrigScintDigiProducer::generateRandomID (int module)
Definition at line 35 of file TrigScintDigiProducer.cxx.
{
  ldmx::TrigScintID tempID(module, random_->Integer(stripsPerArray_));
  if (module >= TrigScintSection::NUM_SECTIONS) {
    // Throw an exception
    std::cout << "WARNING [TrigScintDigiProducer::generateRandomID]: "
                 "TrigScintSection is not known"
              << std::endl;
  }
  return tempID;
}
produce()
void trigscint::TrigScintDigiProducer::produce (framework::Event & event) virtual
Process the event and put new data products into it.
Parameters
event The Event to process.
Implements framework::Producer.
Definition at line 47 of file TrigScintDigiProducer.cxx.
{
  // Need to handle seeding on the first event
  if (!noiseGenerator_->hasSeed()) {
    const auto &rseed = getCondition<framework::RandomNumberSeedService>(
        framework::RandomNumberSeedService::CONDITIONS_OBJECT_NAME);
    noiseGenerator_->seedGenerator(
        rseed.getSeed("TrigScintDigiProducer::NoiseGenerator"));
  }
  std::map<ldmx::TrigScintID, int> cellPEs;
  std::map<ldmx::TrigScintID, int> cellMinPEs;
  std::map<ldmx::TrigScintID, float> Xpos, Ypos, Zpos, Edep, Time, beamFrac;
  std::set<ldmx::TrigScintID> noiseHitIDs;
  auto numRecHits{0};
  // looper over sim hits and aggregate energy depositions for each detID
  const auto simHits{event.getCollection<ldmx::SimCalorimeterHit>(
      inputCollection_, inputPassName_)};
  auto particleMap{event.getMap<int, ldmx::SimParticle>("SimParticles")};
  int module{-1};
  for (const auto &simHit : simHits) {
    ldmx::TrigScintID id(simHit.getID());
    // Just set the module ID to use for noise hits here.  Given that
    // we are currently processing a single module at a time, setting
    // it within the loop shouldn't matter.
    module = id.module();
    std::vector<float> position = simHit.getPosition();
    if (verbose_) {
      std::cout << id << std::endl;
    }
    unsigned int detIDRaw = id.raw();
    // check if hits is from beam electron and, if so, add to beamFrac
    for (int i = 0; i < simHit.getNumberOfContribs(); i++) {
      auto contrib = simHit.getContrib(i);
      if (verbose_) {
        std::cout << "contrib " << i << " trackID: " << contrib.trackID
                  << " pdgID: " << contrib.pdgCode << " edep: " << contrib.edep
                  << std::endl;
        std::cout << "\t particle id: "
                  << particleMap[contrib.trackID].getPdgID()
                  << " particle status: "
                  << particleMap[contrib.trackID].getGenStatus() << std::endl;
      }
      if (particleMap[contrib.trackID].getPdgID() == 11 &&
          particleMap[contrib.trackID].getGenStatus() == 1) {
        if (beamFrac.find(id) == beamFrac.end())
          beamFrac[id] = contrib.edep;
        else
          beamFrac[id] += contrib.edep;
      }
    }
    // for now, we take am energy weighted average of the hit in each stip to
    // simulate the hit position. AJW: these should be dropped, they are likely
    // to lead to a problem since we can't measure them anyway except roughly y
    // and z, which is encoded in the ids.
    if (Edep.find(id) == Edep.end()) {
      // first hit, initialize
      Edep[id] = simHit.getEdep();
      Time[id] = simHit.getTime() * simHit.getEdep();
      Xpos[id] = position[0] * simHit.getEdep();
      Ypos[id] = position[1] * simHit.getEdep();
      Zpos[id] = position[2] * simHit.getEdep();
      numRecHits++;
    } else {
      // not first hit, aggregate, and store the largest radius hit
      Xpos[id] += position[0] * simHit.getEdep();
      Ypos[id] += position[1] * simHit.getEdep();
      Zpos[id] += position[2] * simHit.getEdep();
      Edep[id] += simHit.getEdep();
      // AJW: need to figure out a better way to model this...
      Time[id] += simHit.getTime() * simHit.getEdep();
    }
  }
  // Create the container to hold the digitized trigger scintillator hits.
  std::vector<ldmx::TrigScintHit> trigScintHits;
  // loop over detIDs and simulate number of PEs
  int ihit = 0;
  for (std::map<ldmx::TrigScintID, float>::iterator it = Edep.begin();
       it != Edep.end(); ++it) {
    ldmx::TrigScintID id(it->first);
    double depEnergy = Edep[id];
    Time[id] = Time[id] / Edep[id];
    Xpos[id] = Xpos[id] / Edep[id];
    Ypos[id] = Ypos[id] / Edep[id];
    Zpos[id] = Zpos[id] / Edep[id];
    double meanPE = depEnergy / mevPerMip_ * pePerMip_;
    cellPEs[id] = random_->Poisson(meanPE + meanNoise_);
    // If a cell has a PE count above threshold, persit the hit.
    if (cellPEs[id] >= 1) {
      ldmx::TrigScintHit hit;
      hit.setID(id.raw());
      hit.setPE(cellPEs[id]);
      hit.setMinPE(cellMinPEs[id]);
      hit.setAmplitude(cellPEs[id]);
      hit.setEnergy(depEnergy);
      hit.setTime(Time[id]);
      hit.setXPos(Xpos[id]);
      hit.setYPos(Ypos[id]);
      hit.setZPos(Zpos[id]);
      hit.setModuleID(module);
      hit.setBarID(id.bar());  // getFieldValue("bar"));
      hit.setNoise(false);
      hit.setBeamEfrac(beamFrac[id] / depEnergy);
      trigScintHits.push_back(hit);
    }
    if (verbose_) {
      std::cout << id << std::endl;
      std::cout << "Edep: " << Edep[id] << std::endl;
      std::cout << "numPEs: " << cellPEs[id] << std::endl;
      std::cout << "time: " << Time[id] << std::endl;
      std::cout << "z: " << Zpos[id] << std::endl;
      std::cout << "\t X: " << Xpos[id] << "\t Y: " << Ypos[id]
                << "\t Z: " << Zpos[id] << std::endl;
    }  // end verbose
  }
  // ------------------------------- Noise simulation -----------------------//
  // ------------------------------------------------------------------------//
  int numEmptyCells = stripsPerArray_ -
                      numRecHits;  // only simulating for single array until
                                   // all arrays are merged into one collection
  std::vector<double> noiseHits_PE =
      noiseGenerator_->generateNoiseHits(numEmptyCells);
  ldmx::TrigScintID tempID;
  for (auto &noiseHitPE : noiseHits_PE) {
    ldmx::TrigScintHit hit;
    // generate random ID from remaining cells
    do {
      tempID = generateRandomID(module);
    } while (Edep.find(tempID) != Edep.end() ||
             noiseHitIDs.find(tempID) != noiseHitIDs.end());
    ldmx::TrigScintID noiseID = tempID;
    noiseHitIDs.insert(noiseID);
    hit.setID(noiseID.raw());
    hit.setPE(noiseHitPE);
    hit.setMinPE(noiseHitPE);
    hit.setAmplitude(noiseHitPE);
    hit.setEnergy(0.);
    hit.setTime(0.);
    hit.setXPos(0.);
    hit.setYPos(0.);
    hit.setZPos(0.);
    hit.setModuleID(module);
    hit.setBarID(noiseID.bar());
    hit.setNoise(true);
    hit.setBeamEfrac(0.);
    trigScintHits.push_back(hit);
  }
  // - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
  // - -
  event.add(outputCollection_, trigScintHits);
}
References ldmx::TrigScintID::bar(), framework::RandomNumberSeedService::CONDITIONS_OBJECT_NAME, ldmx::DetectorID::raw(), ldmx::CalorimeterHit::setAmplitude(), ldmx::TrigScintHit::setBarID(), ldmx::TrigScintHit::setBeamEfrac(), ldmx::CalorimeterHit::setEnergy(), ldmx::CalorimeterHit::setID(), ldmx::HcalHit::setMinPE(), ldmx::TrigScintHit::setModuleID(), ldmx::CalorimeterHit::setNoise(), ldmx::HcalHit::setPE(), ldmx::CalorimeterHit::setTime(), ldmx::CalorimeterHit::setXPos(), ldmx::CalorimeterHit::setYPos(), and ldmx::CalorimeterHit::setZPos().
Member Data Documentation
inputCollection_
std::string trigscint::TrigScintDigiProducer::inputCollection_ private
Name of the input collection containing the sim hits.
Definition at line 75 of file TrigScintDigiProducer.h.
inputPassName_
std::string trigscint::TrigScintDigiProducer::inputPassName_ private
Name of the pass that the input collection is on (empty string means take any pass)
Definition at line 79 of file TrigScintDigiProducer.h.
meanNoise_
double trigscint::TrigScintDigiProducer::meanNoise_ {0} private
Mean readout noise.
Definition at line 92 of file TrigScintDigiProducer.h.
mevPerMip_
double trigscint::TrigScintDigiProducer::mevPerMip_ {1.40} private
Total MeV per MIP.
Definition at line 95 of file TrigScintDigiProducer.h.
noiseGenerator_
std::unique_ptr<ldmx::NoiseGenerator> trigscint::TrigScintDigiProducer::noiseGenerator_ {nullptr} private
Generate noise hits given the number of channels and mean noise.
Definition at line 68 of file TrigScintDigiProducer.h.
numberOfArrays_
int trigscint::TrigScintDigiProducer::numberOfArrays_ {3} private
Number of arrays.
Definition at line 89 of file TrigScintDigiProducer.h.
outputCollection_
std::string trigscint::TrigScintDigiProducer::outputCollection_ private
Name of the output collection that will be used to stored the digitized trigger scintillator hits
Definition at line 83 of file TrigScintDigiProducer.h.
pePerMip_
double trigscint::TrigScintDigiProducer::pePerMip_ {13.5} private
Total number of photoelectrons per MIP.
Definition at line 98 of file TrigScintDigiProducer.h.
random_
std::unique_ptr<TRandom3> trigscint::TrigScintDigiProducer::random_ {nullptr} private
Random number generator.
Definition at line 65 of file TrigScintDigiProducer.h.
stripsPerArray_
int trigscint::TrigScintDigiProducer::stripsPerArray_ {50} private
Number of strips per array.
Definition at line 86 of file TrigScintDigiProducer.h.
verbose_
bool trigscint::TrigScintDigiProducer::verbose_ {false} private
Class to set the verbosity level.
Definition at line 72 of file TrigScintDigiProducer.h.
The documentation for this class was generated from the following files:
TrigScint/include/TrigScint/TrigScintDigiProducer.h
TrigScint/src/TrigScint/TrigScintDigiProducer.cxx