LDMX Software: ldmx::Parameters Class Reference
ldmx::Parameters Class Reference
#include <Parameters.h>
Public Member Functions
Parameters ()
Constructor.
~Parameters ()
Destructor.
void setParameters (std::map< std::string, std::any > parameters)
template<typename T >
void addParameter (const std::string &name, const T &value)
bool exists (const std::string &name) const
template<typename T >
T getParameter (const std::string &name) const
template<typename T >
T getParameter (const std::string &name, const T &def) const
std::vector< std::string > keys () const
Private Attributes
std::map< std::string, std::any > parameters_
Parameters.
Detailed Description
Class encapsulating parameters for configuring a processor.
Definition at line 26 of file Parameters.h.
Member Function Documentation
addParameter()
template<typename T > void ldmx::Parameters::addParameter (const std::string & name, const T & value) inline
Add a parameter to the parameter list. If the parameter already exists in the list, throw an exception.
Parameters
[in] name Name of the parameter.
[in] value The value of the parameter.
Exceptions
Exception if a parameter by that name already exist in the list.
Definition at line 55 of file Parameters.h.
{
                 if (exists(name)) {
                     EXCEPTION_RAISE("ParameterExist",
                             "The parameter " + name + " already exists in the list of parameters."
                     );
                 }
                 parameters_[name] = value;
             }
References exists(), and parameters_.
exists()
bool ldmx::Parameters::exists (const std::string & name) const inline
Check to see if a parameter exists
Parameters
[in] name name of parameter to check
Returns
true if parameter exists in configuration set
Definition at line 72 of file Parameters.h.
{
                 return parameters_.find(name)!=parameters_.end();
             }
References parameters_.
Referenced by addParameter(), ldmx::EcalGeometryProvider::getCondition(), and getParameter().
getParameter() [1/2]
template<typename T > T ldmx::Parameters::getParameter (const std::string & name) const inline
Retrieve the parameter of the given name.
Exceptions
Exception if parameter of the given name isn't found
Exception if parameter is found but not of the input type
Parameters
T the data type to cast the parameter to.
[in] name the name of the parameter value to retrieve.
Returns
The user specified parameter of type T.
Definition at line 90 of file Parameters.h.
{
                 // Check if the variable exists in the map.  If it doesn't,
                 // raise an exception.
                 if (not exists(name)) {
                     EXCEPTION_RAISE( "NonExistParam",
                             "Parameter '"+name+"' does not exist in list of parameters."
                             );
                 }
                 try {
                     auto parameter = std::any_cast< T >(parameters_.at(name));
                     return parameter;
                 } catch(const std::bad_any_cast& e) {
                     EXCEPTION_RAISE( "BadTypeParam",
                                      "Parameter '" + name + "' of type '"+parameters_.at(name).type().name()+"' is being cast to incorrect type '" + typeid(T).name() + "'.");
                 }
             }
References exists(), and parameters_.
Referenced by ldmx::APrimePhysics::APrimePhysics(), ldmx::Simulator::beforeNewRun(), ldmx::EcalHitIO::configure(), ldmx::TrigScintClusterProducer::configure(), ldmx::TrigScintTrackProducer::configure(), ldmx::EcalDigiProducer::configure(), ldmx::EcalRecProducer::configure(), ldmx::EcalTrigPrimDigiProducer::configure(), ldmx::DNNEcalVetoProcessor::configure(), ldmx::EcalClusterProducer::configure(), ldmx::EcalVetoProcessor::configure(), ldmx::HcalDigiProducer::configure(), ldmx::HcalVetoProcessor::configure(), ldmx::MyProcessor::configure(), ldmx::OverlayProducer::configure(), ldmx::TriggerProcessor::configure(), ldmx::Simulator::configure(), ldmx::TrigScintDigiProducer::configure(), ldmx::TruthHitProducer::configure(), ldmx::EcalDigiVerifier::configure(), ldmx::TrigScintDQM::configure(), ldmx::TrigScintHitDQM::configure(), ldmx::DarkBremFilter::DarkBremFilter(), ldmx::EcalHexReadout::EcalHexReadout(), ldmx::GeneralParticleSource::GeneralParticleSource(), ldmx::EcalGeometryProvider::getCondition(), ldmx::HgcrocEmulator::HgcrocEmulator(), ldmx::RunManager::Initialize(), ldmx::LHEPrimaryGenerator::LHEPrimaryGenerator(), ldmx::MultiParticleGunPrimaryGenerator::MultiParticleGunPrimaryGenerator(), ldmx::Simulator::onProcessStart(), ldmx::ParticleGun::ParticleGun(), ldmx::PhotoNuclearProductsFilter::PhotoNuclearProductsFilter(), ldmx::RandomNumberSeedService::RandomNumberSeedService(), ldmx::RootCompleteReSim::RootCompleteReSim(), ldmx::RootSimFromEcalSP::RootSimFromEcalSP(), ldmx::RunManager::RunManager(), ldmx::RunManager::setupPhysics(), ldmx::StepPrinter::StepPrinter(), ldmx::TaggerVetoFilter::TaggerVetoFilter(), ldmx::TargetBremFilter::TargetBremFilter(), ldmx::TargetENProcessFilter::TargetENProcessFilter(), ldmx::TargetProcessFilter::TargetProcessFilter(), and ldmx::TrackProcessFilter::TrackProcessFilter().
getParameter() [2/2]
template<typename T > T ldmx::Parameters::getParameter (const std::string & name, const T & def) const inline
Retrieve a parameter with a default specified.
Return the input default if a parameter is not found in map.
Returns
the user parameter of type T
Definition at line 117 of file Parameters.h.
{
                 if (not exists(name)) return def;
                 //get here knowing that name exists in parameters_
                 return getParameter<T>(name);
             }
References exists().
keys()
std::vector<std::string> ldmx::Parameters::keys () const inline
Get a list of the keys available. This may be helpful in debugging to make sure the parameters are spelled correctly.
Definition at line 129 of file Parameters.h.
{
                 std::vector<std::string> key;
                 for (auto i : parameters_) key.push_back(i.first);
                 return key;
             }
References parameters_.
Referenced by ldmx::EcalGeometryProvider::getCondition().
setParameters()
void ldmx::Parameters::setParameters (std::map< std::string, std::any > parameters) inline
Set the mapping of parameter names to value.
Parameters
[in,out] parameters mapping between parameter names and the corresponding value.
Definition at line 41 of file Parameters.h.
{
                 parameters_ = parameters;
             }
References parameters_.
Referenced by ldmx::ConfigurePython::ConfigurePython(), ldmx::DetectorGeometry::DetectorGeometry(), ldmx::getMembers(), ldmx::test::runProcess(), and TEST_CASE().
The documentation for this class was generated from the following file:
Framework/include/Framework/Configure/Parameters.h