LDMX Software: trigscint::QIEInputPulse Class Reference
trigscint::QIEInputPulse Class Reference abstract
The base class to store the most important functions.
#include <QIEInputPulse.h>
Public Member Functions
float Eval (float T)
virtual float EvalSingle (float T, int id)=0
virtual float Integrate (float T1, float T2)=0
virtual float Derivative (float T, int id)=0
virtual float Max (int id)=0
void AddPulse (float toff, float ampl)
int GetNPulses ()
Protected Attributes
std::vector< float > toff_
collection of pulse time offsets
std::vector< float > ampl_
collection of pulse amplitudes
Detailed Description
The base class to store the most important functions.
Note
Always use the classes inherited from this class for QIE input pulse.
Definition at line 17 of file QIEInputPulse.h.
Member Function Documentation
AddPulse()
void trigscint::QIEInputPulse::AddPulse (float toff, float ampl)
To add a pulse to the collection
Parameters
toff time at which the pulse starts
ampl pulse amplitude (total area under the curve)
Definition at line 12 of file QIEInputPulse.cxx.
{
   toff_.push_back(toff);
   ampl_.push_back(ampl);
 }
References ampl_, and toff_.
Referenced by trigscint::TrigScintQIEDigiProducer::produce().
Derivative()
virtual float trigscint::QIEInputPulse::Derivative (float T, int id) pure virtual
Differentiate pulse at time T
Implemented in trigscint::Expo, and trigscint::Bimoid.
Eval()
float trigscint::QIEInputPulse::Eval (float T)
Evaluate the pulse train at time T
Definition at line 17 of file QIEInputPulse.cxx.
{
   if (ampl_.size() == 0) return 0;
   float val = 0;
   for (int i = 0; i < ampl_.size(); i++) {
     val += EvalSingle(T, i);
   }
   return val;
 }
References ampl_, and EvalSingle().
Referenced by trigscint::SimQIE::TDC().
EvalSingle()
virtual float trigscint::QIEInputPulse::EvalSingle (float T, int id) pure virtual
Evaluate the pulse train at time T
Implemented in trigscint::Expo, and trigscint::Bimoid.
Referenced by Eval().
GetNPulses()
int trigscint::QIEInputPulse::GetNPulses () inline
Get the number of pulses in the collection
Definition at line 54 of file QIEInputPulse.h.
 { return ampl_.size(); }
References ampl_.
Referenced by trigscint::SimQIE::PulseCut().
Integrate()
virtual float trigscint::QIEInputPulse::Integrate (float T1, float T2) pure virtual
Integrate the pulse from T1 to T2
Implemented in trigscint::Expo, and trigscint::Bimoid.
Referenced by trigscint::SimQIE::Out_ADC(), and trigscint::SimQIE::PulseCut().
Max()
virtual float trigscint::QIEInputPulse::Max (int id) pure virtual
maximum of the pulse
Implemented in trigscint::Expo, and trigscint::Bimoid.
The documentation for this class was generated from the following files:
TrigScint/include/TrigScint/QIEInputPulse.h
TrigScint/src/TrigScint/QIEInputPulse.cxx