LDMX Software: simcore::MagneticFieldStore Class Reference
simcore::MagneticFieldStore Class Reference
Global store to access magnetic field objects.
#include <MagneticFieldStore.h>
Public Types
typedef std::map< std::string, G4MagneticField * > MagFieldMap
Public Member Functions
~MagneticFieldStore ()
G4MagneticField * getMagneticField (const std::string &name)
void addMagneticField (const std::string &name, G4MagneticField *magField)
Static Public Member Functions
static MagneticFieldStore * getInstance ()
Private Attributes
MagFieldMap magFields_
Detailed Description
Global store to access magnetic field objects.
Definition at line 19 of file MagneticFieldStore.h.
Member Typedef Documentation
MagFieldMap
typedef std::map<std::string, G4MagneticField*> simcore::MagneticFieldStore::MagFieldMap
Map of names to magnetic fields.
Definition at line 24 of file MagneticFieldStore.h.
Constructor & Destructor Documentation
~MagneticFieldStore()
simcore::MagneticFieldStore::~MagneticFieldStore () inline
Destructor
Cleans up all stored G4MagneticFields
Definition at line 40 of file MagneticFieldStore.h.
{
     for (auto& nameField : magFields_) {
       delete nameField.second;
     }
     magFields_.clear();
   }
References magFields_.
Member Function Documentation
addMagneticField()
void simcore::MagneticFieldStore::addMagneticField (const std::string & name, G4MagneticField * magField) inline
Add a magnetic field by name.
Parameters
name The name of the magnetic field.
magField The magnetic field definition.
Definition at line 60 of file MagneticFieldStore.h.
{
     magFields_[name] = magField;
   }
References magFields_.
Referenced by simcore::geo::AuxInfoReader::createMagneticField().
getInstance()
static MagneticFieldStore* simcore::MagneticFieldStore::getInstance () inline static
Get the global instance of the magnetic field store.
Returns
The magnetic field store.
Definition at line 30 of file MagneticFieldStore.h.
{
     static MagneticFieldStore INSTANCE;
     return &INSTANCE;
   }
Referenced by simcore::geo::AuxInfoReader::assignAuxInfoToVolumes(), and simcore::geo::AuxInfoReader::createMagneticField().
getMagneticField()
G4MagneticField* simcore::MagneticFieldStore::getMagneticField (const std::string & name) inline
Get a magnetic field by name.
Parameters
name The name of the magnetic field.
Definition at line 51 of file MagneticFieldStore.h.
{
     return magFields_.at(name);
   }
References magFields_.
Referenced by simcore::geo::AuxInfoReader::assignAuxInfoToVolumes().
Member Data Documentation
magFields_
MagFieldMap simcore::MagneticFieldStore::magFields_ private
Map of names to magnetic fields.
Definition at line 68 of file MagneticFieldStore.h.
Referenced by addMagneticField(), getMagneticField(), and ~MagneticFieldStore().
The documentation for this class was generated from the following file:
SimCore/include/SimCore/MagneticFieldStore.h