LDMX Software: biasing::utility::TrackProcessFilter Class Reference
biasing::utility::TrackProcessFilter Class Reference
#include <TrackProcessFilter.h>
Public Member Functions
TrackProcessFilter (const std::string &name, framework::config::Parameters &parameters)
~TrackProcessFilter ()
Destructor.
void PostUserTrackingAction (const G4Track *track) final override
std::vector< simcore::TYPE > getTypes () final override
Retrieve the type of actions this class defines.
Public Member Functions inherited from simcore::UserAction
UserAction (const std::string &name, framework::config::Parameters &parameters)
virtual ~UserAction ()=default
Destructor.
virtual void BeginOfEventAction (const G4Event *)
virtual void EndOfEventAction (const G4Event *)
virtual void BeginOfRunAction (const G4Run *)
virtual void EndOfRunAction (const G4Run *)
virtual void PreUserTrackingAction (const G4Track *)
virtual void PostUserTrackingAction (const G4Track *)
virtual void stepping (const G4Step *)
virtual G4ClassificationOfNewTrack ClassifyNewTrack (const G4Track *, const G4ClassificationOfNewTrack &cl)
virtual void NewStage ()
virtual void PrepareNewEvent ()
virtual std::vector< TYPE > getTypes ()=0
Private Attributes
std::string process_ {""}
The process to filter on.
Additional Inherited Members
Public Types inherited from simcore::UserAction
using Factory = ::simcore::Factory< UserAction, std::shared_ptr< UserAction >, const std::string &, framework::config::Parameters & >
factory for user actions
Protected Member Functions inherited from simcore::UserAction
UserEventInformation * getEventInfo () const
const std::map< int, ldmx::SimParticle > & getCurrentParticleMap () const
Protected Attributes inherited from simcore::UserAction
std::string name_ {""}
Name of the UserAction.
framework::config::Parameters parameters_
The set of parameters used to configure this class.
Detailed Description
Filter used to tag tracks for persistence based on the process they were created from.
All tracks are checked during the post user tracking action stage and are tagged to be persisted if the process used to create them match the user specified process. The process name specified by the user needs to match the names assigned by Geant4.
Note
Any track created through a process not the same as the configured process will not be saved.
Definition at line 30 of file TrackProcessFilter.h.
Constructor & Destructor Documentation
TrackProcessFilter()
biasing::utility::TrackProcessFilter::TrackProcessFilter (const std::string & name, framework::config::Parameters & parameters)
Constructor.
Parameters
[in] name the name of the instance of this UserAction.
[in] parameters the parameters used to configure this UserAction.
Definition at line 17 of file TrackProcessFilter.cxx.
    : simcore::UserAction(name, parameters) {
  process_ = parameters.getParameter<std::string>("process");
}
References framework::config::Parameters::getParameter(), and process_.
~TrackProcessFilter()
biasing::utility::TrackProcessFilter::~TrackProcessFilter ()
Destructor.
Definition at line 23 of file TrackProcessFilter.cxx.
{}
Member Function Documentation
getTypes()
std::vector< simcore::TYPE > biasing::utility::TrackProcessFilter::getTypes () inline final override virtual
Retrieve the type of actions this class defines.
Implements simcore::UserAction.
Definition at line 52 of file TrackProcessFilter.h.
{
    return {simcore::TYPE::TRACKING};
  }
PostUserTrackingAction()
void biasing::utility::TrackProcessFilter::PostUserTrackingAction (const G4Track * track) final override virtual
Method called when a track is done being processed.
Parameters
[in] track Geant4 track associated with a particle.
Reimplemented from simcore::UserAction.
Definition at line 25 of file TrackProcessFilter.cxx.
{
  if (const G4VProcess * process{track->GetCreatorProcess()}; process) {
    auto name{process->GetProcessName()};
    auto trackInfo{simcore::UserTrackInformation::get(track)};
    if (name.contains(process_))
      trackInfo->setSaveFlag(true);
  }  // does this track have a creator process
}
References simcore::UserTrackInformation::get(), process_, and simcore::UserTrackInformation::setSaveFlag().
Member Data Documentation
process_
std::string biasing::utility::TrackProcessFilter::process_ {""} private
The process to filter on.
Definition at line 58 of file TrackProcessFilter.h.
Referenced by PostUserTrackingAction(), and TrackProcessFilter().
The documentation for this class was generated from the following files:
Biasing/include/Biasing/Utility/TrackProcessFilter.h
Biasing/src/Biasing/Utility/TrackProcessFilter.cxx