LDMX Software: simcore::geo::ParserFactory Class Reference
simcore::geo::ParserFactory Class Reference
Public Member Functions
~ParserFactory ()=default
Default constructor.
Parser * createParser (const std::string &name, framework::config::Parameters &parameters, simcore::ConditionsInterface &ci)
ParserFactory (ParserFactory const &)=delete
void operator= (ParserFactory const &)=delete
Static Public Member Functions
static ParserFactory & getInstance ()
Get the instance to this factory.
Private Member Functions
ParserFactory ()
Default constructor.
void registerParser (const std::string &name, createFunc create)
Private Attributes
std::map< std::string, createFunc > parser_map
Detailed Description
Definition at line 19 of file ParserFactory.h.
Constructor & Destructor Documentation
ParserFactory()
simcore::geo::ParserFactory::ParserFactory () private
Default constructor.
Definition at line 19 of file ParserFactory.cxx.
{ registerParser("gdml", &GDMLParser::create); }
References simcore::geo::GDMLParser::create(), and registerParser().
Member Function Documentation
createParser()
Parser * simcore::geo::ParserFactory::createParser (const std::string & name, framework::config::Parameters & parameters, simcore::ConditionsInterface & ci)
Create an instance of the parser of the given type.
Parameters
[in] type String type of the perser that needs to be created.
[in] ci Interface to conditions system.
Definition at line 25 of file ParserFactory.cxx.
{
  auto it{parser_map.find(name)};
  if (it == parser_map.end())
    EXCEPTION_RAISE("ParserNotFound", "The parser " + name + " was not found.");
  return it->second(parameters, ci);
}
Referenced by simcore::Simulator::configure().
getInstance()
ParserFactory & simcore::geo::ParserFactory::getInstance () static
Get the instance to this factory.
Definition at line 14 of file ParserFactory.cxx.
{
  static ParserFactory instance;
  return instance;
}
Referenced by simcore::Simulator::configure().
registerParser()
void simcore::geo::ParserFactory::registerParser (const std::string & name, createFunc create) private
Register the parser with this factory.
This is used to map the name of the parser to the function used to create it.
Parameters
[in] name Name of the parser being registered.
[in] crate Function used to create this function.
Definition at line 21 of file ParserFactory.cxx.
{
  parser_map[name] = create;
}
Referenced by ParserFactory().
Member Data Documentation
parser_map
std::map<std::string, createFunc> simcore::geo::ParserFactory::parser_map private
Definition at line 57 of file ParserFactory.h.
The documentation for this class was generated from the following files:
SimCore/include/SimCore/Geo/ParserFactory.h
SimCore/src/SimCore/Geo/ParserFactory.cxx