LDMX Software: trigscint::Bimoid Class Reference
trigscint::Bimoid Class Reference
Pulse made out of difference of two sigmoids.
#include <QIEInputPulse.h>
Public Member Functions
Bimoid (float start, float qq)
Constructor.
~Bimoid ()=default
Default Destructor.
float EvalSingle (float T, int id) final override
float I_Int (float T, int id)
float Integrate (float T1, float T2) final override
float Max (int id) final override
float Derivative (float T, int id) final override
Public Member Functions inherited from trigscint::QIEInputPulse
float Eval (float T)
void AddPulse (float toff, float ampl)
int GetNPulses ()
Private Attributes
float rt_
rise time
float ft_
fall time
Additional Inherited Members
Protected Attributes inherited from trigscint::QIEInputPulse
std::vector< float > toff_
collection of pulse time offsets
std::vector< float > ampl_
collection of pulse amplitudes
Detailed Description
Pulse made out of difference of two sigmoids.
Note
The pulse maximum is found numerically
Definition at line 70 of file QIEInputPulse.h.
Constructor & Destructor Documentation
Bimoid()
trigscint::Bimoid::Bimoid (float start, float qq)
Constructor.
Definition at line 31 of file QIEInputPulse.cxx.
{
  rt_ = rise;
  ft_ = fall;
}
References ft_, and rt_.
Member Function Documentation
Derivative()
float trigscint::Bimoid::Derivative (float T, int id) final override virtual
Differentiate pulse at time T
Implements trigscint::QIEInputPulse.
Definition at line 85 of file QIEInputPulse.cxx.
{
  // Normalization constant
  float nc = (ft_ - rt_) * log(2) / ampl_[id];
  float T_ = T - toff_[id];
  float E1 = exp(-T_ / rt_);
  float E2 = exp(-T_ / ft_);
  float v1 = E1 / (rt_ * pow(1 + E1, 2));
  float v2 = E2 / (ft_ * pow(1 + E2, 2));
  return ((v1 - v2) / nc);  // Actual derivative
}
References trigscint::QIEInputPulse::ampl_, ft_, rt_, and trigscint::QIEInputPulse::toff_.
Referenced by Max().
EvalSingle()
float trigscint::Bimoid::EvalSingle (float T, int id) final override virtual
Evaluate the pulse at time T
Implements trigscint::QIEInputPulse.
Definition at line 36 of file QIEInputPulse.cxx.
{
  if (T < toff_[id]) return 0;
  // Normalization constant
  float nc = (ft_ - rt_) * log(2) / ampl_[id];
  float y1 = 1 / (1 + exp((toff_[id] - T) / rt_));
  float y2 = 1 / (1 + exp((toff_[id] - T) / ft_));
  return ((y1 - y2) / nc);
}
References trigscint::QIEInputPulse::ampl_, ft_, rt_, and trigscint::QIEInputPulse::toff_.
I_Int()
float trigscint::Bimoid::I_Int (float T, int id)
Indefinite integral at time T
Definition at line 56 of file QIEInputPulse.cxx.
{
  if (T <= toff_[id]) return 0;
  // Normalization constant
  float nc = (ft_ - rt_) * log(2) / ampl_[id];
  float t = T - toff_[id];  // time relative to offset
  float II =  // Integral
      rt_ * log(1 + exp((t - toff_[id]) / rt_)) -
      ft_ * log(1 + exp((t - toff_[id]) / ft_));
  return II / nc;
}
References trigscint::QIEInputPulse::ampl_, ft_, rt_, and trigscint::QIEInputPulse::toff_.
Referenced by Integrate().
Integrate()
float trigscint::Bimoid::Integrate (float T1, float T2) final override virtual
Integrate the pulse from T1 to T2
Implements trigscint::QIEInputPulse.
Definition at line 46 of file QIEInputPulse.cxx.
{
  float val = 0;
  for (int id = 0; id < ampl_.size(); id++) {
    if (ampl_[id] > 0 && T2 > toff_[id]) {
      val += I_Int(T2, id) - I_Int(T1, id);
    }
  }
  return val;
}
References trigscint::QIEInputPulse::ampl_, I_Int(), and trigscint::QIEInputPulse::toff_.
Max()
float trigscint::Bimoid::Max (int id) final override virtual
maximum of the pulse
Implements trigscint::QIEInputPulse.
Definition at line 70 of file QIEInputPulse.cxx.
{
  float a = 0;
  float b = 50;
  float mx = (a + b) / 2;  // maximum
  while (abs(Derivative(mx, id)) >= 1e-5) {
    if (Derivative(a, id) * Derivative(mx, id) > 0) {
      a = mx;
    } else
      b = mx;
    mx = (a + b) / 2;
  }
  return (mx);
}
References Derivative().
Member Data Documentation
ft_
float trigscint::Bimoid::ft_ private
fall time
Definition at line 107 of file QIEInputPulse.h.
Referenced by Bimoid(), Derivative(), EvalSingle(), and I_Int().
rt_
float trigscint::Bimoid::rt_ private
rise time
Definition at line 105 of file QIEInputPulse.h.
Referenced by Bimoid(), Derivative(), EvalSingle(), and I_Int().
The documentation for this class was generated from the following files:
TrigScint/include/TrigScint/QIEInputPulse.h
TrigScint/src/TrigScint/QIEInputPulse.cxx