LDMX Software: ldmx::SimParticle Class Reference
ldmx::SimParticle Class Reference
#include <SimParticle.h>
Public Types
enum ProcessType {
unknown = 0, annihil, compt, conv,
electronNuclear, eBrem, eIoni, msc,
phot, photonNuclear, GammaToMuPair, eDarkBrem
}
typedef std::map< std::string, ProcessType > ProcessTypeMap
Typedef for process map.
Public Member Functions
SimParticle ()
Constructor.
~SimParticle ()
Destructor.
void Clear ()
Reset an instance of this class by clearing all of its data.
void Print () const
Print a string representation of this object.
double getEnergy () const
int getPdgID () const
int getGenStatus () const
double getTime () const
std::vector< double > getVertex () const
std::string getVertexVolume () const
std::vector< double > getEndPoint () const
std::vector< double > getMomentum () const
double getMass () const
double getCharge () const
std::vector< int > getDaughters () const
std::vector< int > getParents () const
void setEnergy (const double &energy)
void setPdgID (const int &pdgID)
void setGenStatus (const int &genStatus)
void setTime (const double &time)
void setVertex (const double &x, const double &y, const double &z)
void setVertexVolume (const std::string &vertexVolume)
void setEndPoint (const double &endX, const double &endY, const double &endZ)
void setMomentum (const double &px, const double &py, const double &pz)
void setMass (const double &mass)
void setCharge (const double &charge)
void addDaughter (const int &daughterTrackID)
void addParent (const int &parentTrackID)
int getProcessType () const
void setProcessType (const int &processType)
void setEndPointMomentum (const double &endpx, const double &endpy, const double &endpz)
std::vector< double > getEndPointMomentum () const
Static Public Member Functions
static ProcessType findProcessType (std::string processName)
Private Member Functions
ClassDef (SimParticle, 7)
Static Private Member Functions
static ProcessTypeMap createProcessTypeMap ()
Private Attributes
double energy_ {0}
The energy of this particle.
int pdgID_ {0}
The PDG ID of this particle.
int genStatus_ {-1}
The generator status.
double time_ {0}
The global creation time.
double x_ {0}
The x component of the vertex.
double y_ {0}
The y component of the vertex.
double z_ {0}
The z component of the vertex.
double endX_ {0}
The x component of the end point.
double endY_ {0}
The y component of the end point.
double endZ_ {0}
The z component of the end point.
double px_ {0}
The x component of the momentum.
double py_ {0}
The y component of the momentum.
double pz_ {0}
The z component of the momentum.
double endpx_ {0}
The x component of the endpoint momentum.
double endpy_ {0}
The y component of the endpoint momentum.
double endpz_ {0}
The z component of the endpoint momentum.
double mass_ {0}
The particle's mass.
double charge_ {0}
The particle's charge.
std::vector< int > daughters_
The list of daughter particle track IDs.
std::vector< int > parents_
The list of parent particles track IDs.
int processType_ {-1}
Encoding of Geant4 process type.
std::string vertexVolume_ {""}
Volume the track was created in.
Static Private Attributes
static ProcessTypeMap PROCESS_MAP
Map containing the process types.
Detailed Description
Class representing a simulated particle.
The particles are created from the tracks produced by simulation.
Definition at line 23 of file SimParticle.h.
Member Enumeration Documentation
ProcessType
enum ldmx::SimParticle::ProcessType
Enum for interesting process types.
Definition at line 30 of file SimParticle.h.
{
                 unknown = 0,
                 annihil,
                 compt,
                 conv,
                 electronNuclear,
                 eBrem,
                 eIoni,
                 msc,
                 phot,
                 photonNuclear,
                 GammaToMuPair,
                 eDarkBrem,
                 // Only add additional processes to the end of this list!
             };
Member Function Documentation
addDaughter()
void ldmx::SimParticle::addDaughter (const int & daughterTrackID) inline
Add a reference to a daughter particle by its track ID.
This adds the track ID of the daughter particle to the vector of daughter particle IDs.
Parameters
[in] daughterTrackID The daughter particle track ID.
Definition at line 255 of file SimParticle.h.
 { daughters_.push_back( daughterTrackID ); }
References daughters_.
addParent()
void ldmx::SimParticle::addParent (const int & parentTrackID) inline
Add a reference to a parent particle by its track ID.
Parameters
[in] parentTrackID The track ID of the parent particle.
Definition at line 262 of file SimParticle.h.
 { parents_.push_back( parentTrackID ); }
References parents_.
Referenced by ldmx::SimParticleBuilder::buildSimParticles().
findProcessType()
static ProcessType ldmx::SimParticle::findProcessType (std::string processName) static
Get the process type enum from a G4VProcess name.
Returns
The process type from the string.
Referenced by ldmx::Trajectory::Trajectory().
getCharge()
double ldmx::SimParticle::getCharge () const inline
Get the charge of this particle.
Returns
The charge of this particle.
Definition at line 141 of file SimParticle.h.
 { return charge_; }
References charge_.
Referenced by ldmx::FindableTrackProcessor::produce().
getDaughters()
std::vector<int> ldmx::SimParticle::getDaughters () const inline
Get a vector containing the track IDs of all daughter particles.
Returns
A vector containing the track IDs of all daughter particles.
Definition at line 149 of file SimParticle.h.
 { return daughters_; }
References daughters_.
Referenced by ldmx::Analysis::getPNGamma(), and ldmx::PhotoNuclearDQM::printDaughters().
getEndPoint()
std::vector<double> ldmx::SimParticle::getEndPoint () const inline
Get the endpoint of this particle where it was destroyed or left the world volume [mm].
Returns
The endpoint of this particle
Definition at line 118 of file SimParticle.h.
 { return {endX_, endY_, endZ_}; }
References endX_, endY_, and endZ_.
getEndPointMomentum()
std::vector<double> ldmx::SimParticle::getEndPointMomentum () const inline
Get the momentum at this particle's end point.
Returns
The momentum at this particle's end point as a vector.
Definition at line 296 of file SimParticle.h.
 { return {endpx_, endpy_, endpz_}; }
References endpx_, endpy_, and endpz_.
getEnergy()
double ldmx::SimParticle::getEnergy () const inline
Get the energy of this particle [MeV].
Returns
The energy of this particle.
Definition at line 66 of file SimParticle.h.
 { return energy_; }
References energy_.
Referenced by ldmx::PnWeightProcessor::calculateW(), ldmx::PhotoNuclearDQM::classifyCompactEvent(), and ldmx::PnWeightProcessor::produce().
getGenStatus()
int ldmx::SimParticle::getGenStatus () const inline
Get the generator status of this particle. A non-zero status indicates that this particle originates from an external generator (e.g. LHE).
Returns
The generator status.
Definition at line 82 of file SimParticle.h.
 { return genStatus_; }
References genStatus_.
getMass()
double ldmx::SimParticle::getMass () const inline
Get the mass of this particle [GeV].
Returns
The mass of this particle in GeV.
Definition at line 134 of file SimParticle.h.
 { return mass_; }
References mass_.
Referenced by ldmx::PnWeightProcessor::calculateW(), and ldmx::PnWeightProcessor::produce().
getMomentum()
std::vector<double> ldmx::SimParticle::getMomentum () const inline
Get a vector containing the momentum of this particle [MeV].
The momentum of this particle is set at the time of its creation.
Returns
The momentum of this particle.
Definition at line 127 of file SimParticle.h.
 { return {px_, py_, pz_}; }
References px_, py_, and pz_.
Referenced by ldmx::PnWeightProcessor::calculateW(), and ldmx::PnWeightProcessor::produce().
getParents()
std::vector<int> ldmx::SimParticle::getParents () const inline
Get a vector containing the track IDs of the parent particles.
Returns
A vector containing the track IDs the parent particles.
Definition at line 156 of file SimParticle.h.
 { return parents_; }
References parents_.
getPdgID()
int ldmx::SimParticle::getPdgID () const inline
Get the PDG ID of this particle.
Returns
The PDG ID of this particle.
Definition at line 73 of file SimParticle.h.
 { return pdgID_; }
References pdgID_.
Referenced by ldmx::PnWeightProcessor::produce().
getProcessType()
int ldmx::SimParticle::getProcessType () const inline
Get the creator process type of this particle.
Returns
The creator process type of this particle.
Definition at line 269 of file SimParticle.h.
 { return processType_; }
References processType_.
getTime()
double ldmx::SimParticle::getTime () const inline
Get the global time of this particle's creation [ns].
Returns
The global time of this particle's creation.
Definition at line 89 of file SimParticle.h.
 { return time_; }
References time_.
getVertex()
std::vector<double> ldmx::SimParticle::getVertex () const inline
Get a vector containing the vertex of this particle in mm.
In this case, the vertex refers to the position where the particle is first created in the simulation. For a particle with generator status equal to 1, this will equal the position from which this particle is fired from.
Returns
The vertex of this particle.
Definition at line 101 of file SimParticle.h.
 { return {x_, y_, z_}; }
References x_, y_, and z_.
getVertexVolume()
std::string ldmx::SimParticle::getVertexVolume () const inline
Get the volume name in which this particle was created in.
The volumes names are set in the GDML detector description.
Returns
The volume name in which this particle was created in.
Definition at line 110 of file SimParticle.h.
 { return vertexVolume_; }
References vertexVolume_.
setCharge()
void ldmx::SimParticle::setCharge (const double & charge) inline
Set the charge of this particle.
Parameters
[in] charge The charge of this particle.
Definition at line 245 of file SimParticle.h.
 { charge_ = charge; }
References charge_.
Referenced by ldmx::SimParticleBuilder::buildSimParticles().
setEndPoint()
void ldmx::SimParticle::setEndPoint (const double & endX, const double & endY, const double & endZ) inline
Set the end point position of this particle [mm].
Parameters
[in] endX The x position of the end point.
[in] endY The y position of the end point.
[in] endZ The z position of the end point.
Definition at line 214 of file SimParticle.h.
{
                 endX_ = endX;
                 endY_ = endY;
                 endZ_ = endZ;
             }
References endX_, endY_, and endZ_.
Referenced by ldmx::SimParticleBuilder::buildSimParticles().
setEndPointMomentum()
void ldmx::SimParticle::setEndPointMomentum (const double & endpx, const double & endpy, const double & endpz) inline
Set the momentum at this particle's end point.
Parameters
[in] endpx The x component of the momentum.
[in] endpy The y component of the momentum.
[in] endpz The z component of the momentum.
Definition at line 285 of file SimParticle.h.
{
                 endpx_ = endpx;
                 endpy_ = endpy;
                 endpz_ = endpz;
             }
References endpx_, endpy_, and endpz_.
Referenced by ldmx::SimParticleBuilder::buildSimParticles().
setEnergy()
void ldmx::SimParticle::setEnergy (const double & energy) inline
Set the energy of this particle [MeV].
Parameters
[in] energy the energy of this particle.
Definition at line 163 of file SimParticle.h.
 { energy_ = energy; }
References energy_.
Referenced by ldmx::SimParticleBuilder::buildSimParticles().
setGenStatus()
void ldmx::SimParticle::setGenStatus (const int & genStatus) inline
Set the generator status of this particle.
Parameters
[in] genStatus the generator status of the hit.
Definition at line 177 of file SimParticle.h.
 { genStatus_ = genStatus; }
References genStatus_.
Referenced by ldmx::SimParticleBuilder::buildSimParticles().
setMass()
void ldmx::SimParticle::setMass (const double & mass) inline
Set the mass of this particle [GeV].
Parameters
[in] mass The mass of this particle.
Definition at line 238 of file SimParticle.h.
 { mass_ = mass; }
References mass_.
Referenced by ldmx::SimParticleBuilder::buildSimParticles().
setMomentum()
void ldmx::SimParticle::setMomentum (const double & px, const double & py, const double & pz) inline
Set the momentum of this particle [MeV].
Parameters
[in] px The x momentum component.
[in] py The y momentum component.
[in] pz The z momentum component.
Definition at line 227 of file SimParticle.h.
{
                 px_ = px;
                 py_ = py;
                 pz_ = pz;
             }
References px_, py_, and pz_.
Referenced by ldmx::SimParticleBuilder::buildSimParticles().
setPdgID()
void ldmx::SimParticle::setPdgID (const int & pdgID) inline
Set the PDG ID of this particle.
Parameters
[in] pdgID the PDG ID of the hit.
Definition at line 170 of file SimParticle.h.
 { pdgID_ = pdgID; }
References pdgID_.
Referenced by ldmx::SimParticleBuilder::buildSimParticles().
setProcessType()
void ldmx::SimParticle::setProcessType (const int & processType) inline
Set the creator process type of this particle.
Parameters
[in] processType the creator process type of this particle.
Definition at line 276 of file SimParticle.h.
 { processType_ = processType; }
References processType_.
Referenced by ldmx::SimParticleBuilder::buildSimParticles().
setTime()
void ldmx::SimParticle::setTime (const double & time) inline
Set the global time of this particle's creation [ns].
Parameters
[in] time The global time of this particle's creation.
Definition at line 184 of file SimParticle.h.
 { time_ = time; }
References time_.
Referenced by ldmx::SimParticleBuilder::buildSimParticles().
setVertex()
void ldmx::SimParticle::setVertex (const double & x, const double & y, const double & z) inline
Set the vertex of this particle [mm].
Parameters
[in] x The vertex x position.
[in] y The vertex y position.
[in] z The vertex z position.
Definition at line 193 of file SimParticle.h.
{
                 x_ = x;
                 y_ = y;
                 z_ = z;
             }
References x_, y_, and z_.
Referenced by ldmx::SimParticleBuilder::buildSimParticles().
setVertexVolume()
void ldmx::SimParticle::setVertexVolume (const std::string & vertexVolume) inline
Set the name of the volume that this particle was created in.
Parameters
[in] vertexVolume volume name that this particle was created in.
Definition at line 205 of file SimParticle.h.
 { vertexVolume_ = vertexVolume; }
References vertexVolume_.
Referenced by ldmx::SimParticleBuilder::buildSimParticles().
The documentation for this class was generated from the following file:
Event/include/Event/SimParticle.h