LDMX Software: simcore::PhotoNuclearModel Class Reference
simcore::PhotoNuclearModel Class Reference abstract
Public Types
using Factory = ::simcore::Factory< PhotoNuclearModel, std::shared_ptr< PhotoNuclearModel >, const std::string &, const framework::config::Parameters & >
Public Member Functions
PhotoNuclearModel (const std::string &name, const framework::config::Parameters &parameters)
virtual void ConstructGammaProcess (G4ProcessManager *processManager)=0
virtual void removeExistingModel (G4ProcessManager *processManager)
virtual void addPNCrossSectionData (G4HadronInelasticProcess *process) const
Detailed Description
Definition at line 27 of file PhotoNuclearModel.h.
Member Typedef Documentation
Factory
using simcore::PhotoNuclearModel::Factory = ::simcore::Factory<PhotoNuclearModel, std::shared_ptr<PhotoNuclearModel>, const std::string&, const framework::config::Parameters&>
The factory for PhotoNuclearModels.
Definition at line 52 of file PhotoNuclearModel.h.
Constructor & Destructor Documentation
PhotoNuclearModel()
simcore::PhotoNuclearModel::PhotoNuclearModel (const std::string & name, const framework::config::Parameters & parameters) inline
Base class does not take any parameters or do anything in particular, but any derived class may.
Parameters
[in] name unique instance name for this model
[in] parameters python configuration
Definition at line 36 of file PhotoNuclearModel.h.
                                                                {};
Member Function Documentation
addPNCrossSectionData()
void simcore::PhotoNuclearModel::addPNCrossSectionData (G4HadronInelasticProcess * process) const virtual
Default implementation for adding XS data for the process.
The default implementation is adapted from G4PhotoNuclearProcess.hh but can be overridden to add cross sections in another way (e.g. from FLUKA). If no cross-section is added to the process, the simulation process will halt when attempting to calculate the mean free path so there is no way of accidentally forgetting to enable the XS data.
Typically called during ConstructGammaProcess.
Definition at line 15 of file PhotonuclearModel.cxx.
{
  auto crossSectionRegistry{G4CrossSectionDataSetRegistry::Instance()};
  auto crossSection{
      crossSectionRegistry->GetCrossSectionDataSet("PhotoNuclearXS")};
  if (!crossSection) {
    crossSection = new G4PhotoNuclearCrossSection{};
  }
  process->AddDataSet(crossSection);
}
Referenced by simcore::BertiniAtLeastNProductsModel::ConstructGammaProcess(), simcore::BertiniNothingHardModel::ConstructGammaProcess(), and simcore::BertiniSingleNeutronModel::ConstructGammaProcess().
ConstructGammaProcess()
virtual void simcore::PhotoNuclearModel::ConstructGammaProcess (G4ProcessManager * processManager) pure virtual
The primary part of the model interface, responsible for adding the desired G4HadronicInteraction to the process manager for the G4Gamma class.
Parameters
[in] processManager the process manager for the G4Gamma class, passed in automatically by the GammaPhysics module.
Implemented in simcore::BertiniModel, simcore::BertiniAtLeastNProductsModel, simcore::BertiniNothingHardModel, simcore::BertiniSingleNeutronModel, and simcore::NoPhotoNuclearModel.
removeExistingModel()
void simcore::PhotoNuclearModel::removeExistingModel (G4ProcessManager * processManager) virtual
Removes any existing photonNuclear process from the process manager of the G4Gamma class. Should in general not be overridden for most models other than the default Bertini model (which just retains the default interaction).
Parameters
[in] processManager the process manager for the G4Gamma class, passed in automatically by the GammaPhysics module.
Reimplemented in simcore::BertiniModel.
Definition at line 4 of file PhotonuclearModel.cxx.
{
  const auto processes{processManager->GetProcessList()};
  for (int i{0}; i < processes->size(); ++i) {
    const auto process{(*processes)[i]};
    const auto processName{process->GetProcessName()};
    if (processName == "photonNuclear") {
      processManager->RemoveProcess(i);
    }
  }
}
The documentation for this class was generated from the following files:
SimCore/include/SimCore/PhotoNuclearModel.h
SimCore/src/SimCore/PhotonuclearModel.cxx