LDMX Software: framework::Event Class Reference
framework::Event Class Reference
Implements an event buffer system for storing event data.
#include <Event.h>
Classes
class clearPassenger
class printPassenger
class sortPassenger
Public Member Functions
Event (const std::string &passName)
~Event ()
ldmx::EventHeader & getEventHeader ()
const ldmx::EventHeader * getEventHeaderPtr ()
int getEventNumber () const
double getEventWeight () const
void Print (int verbosity) const
bool exists (const std::string &name) const
bool exists (const std::string &name, const std::string &passName) const
void addDrop (const std::string &exp)
template<typename T >
void add (const std::string &collectionName, T &obj)
std::vector< ProductTag > searchProducts (const std::string &namematch, const std::string &passmatch, const std::string &typematch) const
template<typename T >
const T getObject (const std::string &collectionName, const std::string &passName) const
template<typename T >
const T getObject (const std::string &collectionName) const
template<typename T >
const std::vector< T > getCollection (const std::string &collectionName, const std::string &passName) const
template<typename T >
const std::vector< T > getCollection (const std::string &collectionName) const
template<typename Key , typename Val >
const std::map< Key, Val > getMap (const std::string &collectionName, const std::string &passName) const
template<typename Key , typename Val >
const std::map< Key, Val > getMap (const std::string &collectionName) const
void setInputTree (TTree *tree)
void setOutputTree (TTree *tree)
TTree * createTree ()
std::string makeBranchName (const std::string &collectionName, const std::string &passName) const
std::string makeBranchName (const std::string &collectionName) const
const std::vector< ProductTag > & getProducts () const
bool nextEvent ()
void beforeFill ()
void Clear ()
void onEndOfEvent ()
void onEndOfFile ()
std::string getPassName ()
int getElectronCount () const
void setElectronCount (const int &electronCount)
Protected Member Functions
template<typename T >
T getImpl (const std::string &collectionName, const std::string &passName) const
Private Member Functions
bool shouldDrop (const std::string &collName) const
Private Attributes
ldmx::EventHeader eventHeader_
Long64_t entries_ {-1}
Long64_t ientry_ {-1}
std::string passName_
TTree * outputTree_ {nullptr}
TTree * inputTree_ {nullptr}
int electronCount_ {-1}
The total number of electrons in the event.
std::map< std::string, TBranchElement * > branches_
std::map< std::string, EventBusPassenger > passengers_
std::vector< TBranchElement * > newBranches_
std::vector< std::string > branchNames_
std::set< std::string > branchesFilled_
std::vector< regex_t > regexDropCollections_
std::map< std::string, std::string > knownLookups_
std::vector< ProductTag > products_
Detailed Description
Implements an event buffer system for storing event data.
Note
Event data is stored in ROOT trees and branches, which can be added on the fly.
Definition at line 40 of file Event.h.
Constructor & Destructor Documentation
Event()
framework::Event::Event (const std::string & passName)
Class constructor.
Parameters
passName The default pass name for adding event data.
Definition at line 5 of file Event.cxx.
 : passName_(thePassName) {}
~Event()
framework::Event::~Event ()
Class destructor.
Definition at line 7 of file Event.cxx.
               {
   for (regex_t& reg : regexDropCollections_) {
     regfree(&reg);
   }
 }
References regexDropCollections_.
Member Function Documentation
add()
template<typename T > void framework::Event::add (const std::string & collectionName, T & obj) inline
Adds an object to the event bus
Parameters
collectionName
obj in ROOT dictionary to add
Definition at line 127 of file Event.h.
{
     if (collectionName.find('_') != std::string::npos) {
       EXCEPTION_RAISE("IllegalName",
                       "The product name '" + collectionName +
                           "' is illegal as it contains an underscore.");
     }
     std::string branchName;
     if (collectionName == ldmx::EventHeader::BRANCH)
       branchName = collectionName;
     else
       branchName = makeBranchName(collectionName);
     if (branchesFilled_.find(branchName) != branchesFilled_.end()) {
       EXCEPTION_RAISE("ProductExists",
                       "A product named '" + collectionName +
                           "' already exists in the event (has been loaded by a "
                           "previous producer in this process).");
     }
     branchesFilled_.insert(branchName);
     // MEMORY add is leaking memory when given a vector (possible upon
     // destruction of Event?) MEMORY add is 'conditional jump or move depends on
     // uninitialised values' for all types of objects
     //  TTree::BranchImpRef or TTree::BronchExec
     if (passengers_.find(branchName) == passengers_.end()) {
       // create a new branch for this collection
       // TODO check if input type is listed as an EventBusPassenger?
       passengers_[branchName] = EventBusPassenger(obj);
       T *passengerAddress = std::get_if<T>(&passengers_[branchName]);
       std::string tname =
           typeid(obj)
               .name();  // type name (want to use branch element if possible)
       if (outputTree_ != 0 and not shouldDrop(branchName)) {
         TBranchElement *outBranch = dynamic_cast<TBranchElement *>(
             outputTree_->GetBranch(branchName.c_str()));
         if (outBranch) {
           // branch already exists, just reset branch object
           outBranch->SetObject(passengerAddress);
         } else {
           // branch doesnt exist, make new one
           outBranch = dynamic_cast<TBranchElement *>(outputTree_->Branch(
               branchName.c_str(), passengerAddress, 100000, 3));
         }
         newBranches_.push_back(outBranch);
         // get type name from branch if possible, otherwise use compiler level
         // type name (above)
         tname = outBranch->GetClassName();
       }  // output tree exists or not
       products_.emplace_back(collectionName, passName_, tname);
       branchNames_.push_back(branchName);
       knownLookups_.clear();  // have to invalidate this cache
     }
     // copy input contents into bus passenger
     EventBusPassenger toAdd(obj);
     if (toAdd.index() == passengers_[branchName].index()) {
       std::visit(sortPassenger(), toAdd);  // sort before copying over
       passengers_[branchName] = toAdd;
     } else {
       EXCEPTION_RAISE("TypeMismatch",
                       "Attempting to add an object whose type '" +
                           std::string(typeid(obj).name()) +
                           "' doesn't match the type stored in the collection.");
     }
     return;
   }
References ldmx::EventHeader::BRANCH, branchesFilled_, branchNames_, knownLookups_, makeBranchName(), newBranches_, outputTree_, passengers_, passName_, products_, and shouldDrop().
Referenced by beforeFill(), simcore::persist::SimParticleBuilder::buildSimParticles(), and simcore::persist::RootPersistencyManager::writeHitsCollections().
addDrop()
void framework::Event::addDrop (const std::string & exp)
Add a drop rule to the list of regex expressions to drop.
If a collection name matches one of the stored regex expressions, it will be stored as a passenger but not added to output tree.
Parameters
exp regex to match
Definition at line 20 of file Event.cxx.
{
   regex_t reg;
   if (!regcomp(&reg, exp.c_str(), REG_EXTENDED | REG_ICASE | REG_NOSUB)) {
     regexDropCollections_.push_back(reg);
   } else {
     EXCEPTION_RAISE("InvalidRegex", "The passed drop rule regex '" + exp +
                                         "' is not a valid regex.");
   }
 }
References regexDropCollections_.
Referenced by framework::EventFile::addDrop().
beforeFill()
void framework::Event::beforeFill ()
Action to be executed before the tree is filled.
Definition at line 119 of file Event.cxx.
{
   if (inputTree_ == 0 && branchesFilled_.find(ldmx::EventHeader::BRANCH) ==
                              branchesFilled_.end()) {
     // Event Header not copied from input and hasn't been added yet, need to put
     // it in
     add(ldmx::EventHeader::BRANCH, eventHeader_);
   }
 }
References add(), ldmx::EventHeader::BRANCH, branchesFilled_, eventHeader_, and inputTree_.
Referenced by framework::EventFile::nextEvent().
Clear()
void framework::Event::Clear ()
Clear this object's data (including passengers).
Definition at line 128 of file Event.cxx.
                   {
   // clear the event objects
   branchesFilled_.clear();
   for (auto passenger : passengers_) {
     std::visit(clearPassenger(), passenger.second);
   }
 }
References branchesFilled_, and passengers_.
Referenced by framework::EventFile::nextEvent(), and framework::Process::run().
createTree()
TTree * framework::Event::createTree ()
Create the output data tree.
Returns
The output data tree.
Definition at line 75 of file Event.cxx.
{
   outputTree_ = new TTree("LDMX_Events", "LDMX Events");
   return outputTree_;
 }
References outputTree_.
Referenced by framework::EventFile::setupEvent().
exists() [1/2]
bool framework::Event::exists (const std::string & name) const inline
Check the existence of one-and-only-one object with the given name (excluding the pass) in the event.
Parameters
name Name (label, not class name) given to the object when it was put into the event.
Returns
True if the object or collection exists in the event.
Definition at line 96 of file Event.h.
 { return exists(name, ""); }
References exists().
Referenced by dqm::HCalDQM::analyze(), dqm::RecoilTrackerDQM::analyze(), exists(), ecal::EcalRecProducer::produce(), ecal::EcalVetoProcessor::produce(), recon::MyProcessor::produce(), trigscint::TrigScintTrackProducer::produce(), trigscint::TruthHitProducer::produce(), hcal::HcalRecProducer::produce(), and recon::ElectronCounter::produce().
exists() [2/2]
bool framework::Event::exists (const std::string & name, const std::string & passName) const inline
Check for the existence of an object or collection with the given name and pass name in the event.
Parameters
name Name (label, not class name) given to the object when it was put into the event.
passName The process pass label which was in use when this object was put into the event, such as "sim" or "rerecov2".
Returns
True if the object or collection uniquely exists in the event.
Definition at line 107 of file Event.h.
{
     return (searchProducts(name, passName, "").size() == 1);
   }
References searchProducts().
getCollection() [1/2]
template<typename T > const std::vector<T> framework::Event::getCollection (const std::string & collectionName) const inline
Get a collection (std::vector) of objects from the event bus when you don't care about the pass
Definition at line 238 of file Event.h.
{
     return getCollection<T>(collectionName, "");
   }
getCollection() [2/2]
template<typename T > const std::vector<T> framework::Event::getCollection (const std::string & collectionName, const std::string & passName) const inline
Get a collection (std::vector) of objects from the event bus
Definition at line 228 of file Event.h.
{
     return getObject<std::vector<T> >(collectionName, passName);
   }
Referenced by simcore::RootSimFromEcalSP::GeneratePrimaryVertex(), and recon::OverlayProducer::produce().
getElectronCount()
int framework::Event::getElectronCount () const inline
Returns
The beam electron count.
Definition at line 451 of file Event.h.
 { return electronCount_; }
References electronCount_.
getEventHeader()
ldmx::EventHeader& framework::Event::getEventHeader () inline
Get the event header.
Returns
A reference to the event header.
Definition at line 57 of file Event.h.
 { return eventHeader_; }
References eventHeader_.
Referenced by simcore::RootCompleteReSim::GeneratePrimaryVertex(), simcore::RootSimFromEcalSP::GeneratePrimaryVertex(), recon::OverlayProducer::onNewRun(), recon::OverlayProducer::produce(), simcore::Simulator::produce(), framework::Process::run(), and simcore::persist::RootPersistencyManager::writeHeader().
getEventHeaderPtr()
const ldmx::EventHeader* framework::Event::getEventHeaderPtr () inline
Get the event header as a pointer
Returns
A const pointer to the event header.
Definition at line 63 of file Event.h.
 { return &eventHeader_; }
References eventHeader_.
Referenced by framework::Process::run().
getEventNumber()
int framework::Event::getEventNumber () const inline
Get the event number.
Returns
the event index/number
Definition at line 69 of file Event.h.
 { return eventHeader_.getEventNumber(); }
References eventHeader_, and ldmx::EventHeader::getEventNumber().
getEventWeight()
double framework::Event::getEventWeight () const inline
Get the event weight
Returns
weight from the EventHeader
Definition at line 75 of file Event.h.
 { return eventHeader_.getWeight(); }
References eventHeader_, and ldmx::EventHeader::getWeight().
getImpl()
template<typename T > T framework::Event::getImpl (const std::string & collectionName, const std::string & passName) const inline protected
Get an event passenger from the event bus (actual implementation)
Parameters
collectionName name of collection you want
passName name of pass you want
Definition at line 266 of file Event.h.
{
     // get branch name
     std::string branchName;
     if (collectionName == ldmx::EventHeader::BRANCH)
       branchName = collectionName;
     else
       branchName = makeBranchName(collectionName, passName);
     // if no passName, then find branchName by looking over known branches
     if (passName.empty() && collectionName != ldmx::EventHeader::BRANCH) {
       auto itKL = knownLookups_.find(collectionName);
       if (itKL != knownLookups_.end())
         branchName = itKL->second;
       else {
         // this collecitonName hasn't been found before
         std::vector<std::vector<std::string>::const_iterator> matches;
         branchName = collectionName + "_";
         for (auto itBN = branchNames_.begin(); itBN != branchNames_.end();
              itBN++) {
           if (!itBN->compare(0, branchName.size(), branchName))
             matches.push_back(itBN);
         }
         if (matches.empty()) {
           // no matches found
           EXCEPTION_RAISE("ProductNotFound",
                           "No product found for name '" + collectionName + "'");
         } else if (matches.size() > 1) {
           // more than one branch found
           std::string names;
           for (auto strs : matches) {
             if (!names.empty()) names += ", ";
             names += *strs;
           }
           EXCEPTION_RAISE("ProductAmbiguous",
                           "Multiple products found for name '" +
                               collectionName +
                               "' without specified pass name (" + names + ")");
         } else {
           // exactly one branch found
           branchName = *matches.front();
           knownLookups_[collectionName] = branchName;
         }
       }
     }
     // get iterators to branch and collection
     auto itBranch = branches_.find(branchName);
     auto itPassenger = passengers_.find(branchName);
     if (itPassenger != passengers_.end()) {
       if (itBranch != branches_.end()) {
         // passenger and branch found
         itBranch->second->GetEntry(ientry_);
         // reading branches from input tree need to be manually updated
         passengers_[branchName] = *((T *)(itBranch->second->GetObject()));
       }
       return std::get<T>(itPassenger->second);
     } else if (inputTree_ == 0) {
       // not found in loaded branches and there is no inputTree,
       // so no hope of finding an unloaded object
       EXCEPTION_RAISE("ProductNotFound", "No product found for name '" +
                                              collectionName + "' and pass '" +
                                              passName_ + "'");
     }
     // find the active branch and update if necessary
     if (itBranch != branches_.end()) {
       // update buffers if needed
       if (itBranch->second->GetReadEntry() != ientry_) {
         itBranch->second->GetEntry(ientry_, 1);
       }
       // check the objects map
       if (itPassenger != passengers_.end())
         return std::get<T>(itPassenger->second);
       // this case is hard (impossible?) to achieve
       EXCEPTION_RAISE(
           "ProductNotFound",
           "A branch mis-match occurred. I'm not sure how I got here!");
     } else {
       // ok, maybe we've not loaded this yet, look for a branch
       TBranchElement *branch = dynamic_cast<TBranchElement *>(
           inputTree_->GetBranch(branchName.c_str()));
       if (branch == 0) {
         // inputTree doesn't have that branch
         EXCEPTION_RAISE("ProductNotFound", "No product found for name '" +
                                                collectionName + "' and pass '" +
                                                passName_ + "'");
       }
       // ooh, new branch!
       // load in the current entry
       branch->SetStatus(1);  // overrides any 'ignore' rules
       branch->GetEntry((ientry_ < 0) ? (0) : (ientry_));
       // insert into maps of loaded branches and passengers
       passengers_[branchName] = *((
           T *)(branch->GetObject()));  // this will fail if wrong type is passed
       branches_[branchName] = branch;
       return std::get<T>(passengers_.at(branchName));
     }
   }  // getImpl
References ldmx::EventHeader::BRANCH, branches_, branchNames_, ientry_, inputTree_, knownLookups_, makeBranchName(), passengers_, and passName_.
getMap() [1/2]
template<typename Key , typename Val > const std::map<Key, Val> framework::Event::getMap (const std::string & collectionName) const inline
Get a map of objects from the event bus when you don't care about the pass
Definition at line 255 of file Event.h.
{
     return getMap<Key, Val>(collectionName, "");
   }
getMap() [2/2]
template<typename Key , typename Val > const std::map<Key, Val> framework::Event::getMap (const std::string & collectionName, const std::string & passName) const inline
Get a map (std::map) of objects from the event bus
Definition at line 246 of file Event.h.
{
     return getObject<std::map<Key, Val> >(collectionName, passName);
   }
Referenced by simcore::RootCompleteReSim::GeneratePrimaryVertex().
getObject() [1/2]
template<typename T > const T framework::Event::getObject (const std::string & collectionName) const inline
Get a general object from the event bus when you don't care about the pass
Definition at line 220 of file Event.h.
{
     return getObject<T>(collectionName, "");
   }
getObject() [2/2]
template<typename T > const T framework::Event::getObject (const std::string & collectionName, const std::string & passName) const inline
Get a general object from the event bus
Definition at line 211 of file Event.h.
{
     return getImpl<T>(collectionName, passName);
   }
Referenced by eventdisplay::Display::draw().
getPassName()
std::string framework::Event::getPassName () inline
Get the current/default pass name.
Returns
The current/default pass name.
Definition at line 448 of file Event.h.
 { return passName_; }
References passName_.
getProducts()
const std::vector<ProductTag>& framework::Event::getProducts () const inline
Get a list of the data products in the event
Definition at line 413 of file Event.h.
 { return products_; }
References products_.
Referenced by searchProducts().
makeBranchName() [1/2]
std::string framework::Event::makeBranchName (const std::string & collectionName) const inline
Make a branch name from a collection and the default(current) pass name.
Parameters
collectionName The collection name.
Definition at line 406 of file Event.h.
{
     return makeBranchName(collectionName, passName_);
   }
References makeBranchName(), and passName_.
makeBranchName() [2/2]
std::string framework::Event::makeBranchName (const std::string & collectionName, const std::string & passName) const inline
Make a branch name from a collection and pass name.
Parameters
collectionName The collection name.
passName The pass name.
Definition at line 397 of file Event.h.
{
     return collectionName + "_" + passName;
   }
Referenced by add(), getImpl(), and makeBranchName().
nextEvent()
bool framework::Event::nextEvent ()
Go to the next event by incrementing the entry index.
Returns
Hard-coded to return true.
Definition at line 113 of file Event.cxx.
                       {
   ientry_++;
   eventHeader_ = getObject<ldmx::EventHeader>(ldmx::EventHeader::BRANCH);
   return true;
 }
References ldmx::EventHeader::BRANCH, eventHeader_, and ientry_.
Referenced by framework::EventFile::nextEvent().
onEndOfEvent()
void framework::Event::onEndOfEvent ()
Perform end of event action (doesn't do anything right now).
Definition at line 136 of file Event.cxx.
 {}
Referenced by framework::EventFile::nextEvent().
onEndOfFile()
void framework::Event::onEndOfFile ()
Perform end of file action.
Clears buffer objects and resets output branch addresses. This prepares the event bus for a new input file (with new addresses).
Definition at line 138 of file Event.cxx.
{
   passengers_.clear();  // reset event bus
   branches_.clear();    // reset branches
   if (outputTree_)
     outputTree_->ResetBranchAddresses();  // reset addresses for output branch
   if (inputTree_)
     inputTree_ = nullptr;  // detach old inputTree (owned by EventFile)
   ientry_ = -1;            // reset current entry and total entries
   entries_ = -1;
 }
References branches_, entries_, ientry_, inputTree_, outputTree_, and passengers_.
Referenced by framework::EventFile::nextEvent(), and framework::Process::run().
Print()
void framework::Event::Print (int verbosity) const
Print event bus
Only prints passengers that have been loaded into the member object. This means what is printed depends on when this method is called. For example, if this method is called after the Clear method, then everything will be an empty object.
Parameters
verbosity integer flag to determine how verbose you want to be.
Definition at line 13 of file Event.cxx.
{
   for (const auto& keyVal : passengers_) {
     if (verbosity > 1) std::cout << keyVal.first << std::endl;
     std::visit(printPassenger(verbosity), keyVal.second);
   }
 }
References passengers_.
searchProducts()
std::vector< ProductTag > framework::Event::searchProducts (const std::string & namematch, const std::string & passmatch, const std::string & typematch) const
Get a list of products which match the given POSIX-Extended, case-insenstive regular-expressions. An empty argument is interpreted as ".*", which matches everything.
Parameters
namematch Regular expression to compare with the product name
passmatch Regular expression to compare with the pass name
typematch Regular expression to compare with the type name
Definition at line 30 of file Event.cxx.
{
   std::vector<ProductTag> retval;
   regex_t reg_name, reg_pass, reg_type;
   if (!regcomp(&reg_name, (namematch.empty() ? (".*") : (namematch.c_str())),
                REG_EXTENDED | REG_ICASE | REG_NOSUB)) {
     if (!regcomp(&reg_pass, (passmatch.empty() ? (".*") : (passmatch.c_str())),
                  REG_EXTENDED | REG_ICASE | REG_NOSUB)) {
       if (!regcomp(&reg_type,
                    (typematch.empty() ? (".*") : (typematch.c_str())),
                    REG_EXTENDED | REG_ICASE | REG_NOSUB)) {
         // all passed expressions are valid regular expressions
         const std::vector<ProductTag>& products = getProducts();
         for (std::vector<ProductTag>::const_iterator i = products.begin();
              i != products.end(); i++) {
           if (!regexec(&reg_name, i->name().c_str(), 0, 0, 0) &&
               !regexec(&reg_pass, i->passname().c_str(), 0, 0, 0) &&
               !regexec(&reg_type, i->type().c_str(), 0, 0, 0))
             retval.push_back(*i);
         }
         regfree(&reg_type);
       } else {
         EXCEPTION_RAISE("InvalidRegex",
                         "The passed type regex '" + typematch +
                             "' is not a valid regular expression");
       }
       regfree(&reg_pass);
     } else {
       EXCEPTION_RAISE("InvalidRegex",
                       "The passed name regex '" + namematch +
                           "' is not a valid regular expression");
     }
     regfree(&reg_name);
   } else {
     EXCEPTION_RAISE("RegexErr", "The passed passname regex '" + passmatch +
                                     "' is not a valid regular expression.");
   }
   return retval;
 }
References getProducts().
Referenced by exists().
setElectronCount()
void framework::Event::setElectronCount (const int & electronCount) inline
Set the beam electron count.
Parameters
electronCount The beam electron count.
Definition at line 458 of file Event.h.
{
     electronCount_ = electronCount;
   }
References electronCount_.
setInputTree()
void framework::Event::setInputTree (TTree * tree)
********* Functionality for storage ********** Set the input data tree.
Parameters
tree The input data tree.
Definition at line 83 of file Event.cxx.
{
   inputTree_ = tree;
   entries_ = inputTree_->GetEntriesFast();
   // in some cases, setInputTree is called more than once,
   // so reset branch listing before starting
   products_.clear();
   branchNames_.clear();
   branches_.clear();
   passengers_.clear();
   // put in EventHeader (only one without pass name)
   products_.emplace_back(ldmx::EventHeader::BRANCH, "", "ldmx::EventHeader");
   // find the names of all the existing branches
   TObjArray* branches = inputTree_->GetListOfBranches();
   for (int i = 0; i < branches->GetEntriesFast(); i++) {
     std::string brname = branches->At(i)->GetName();
     if (brname != ldmx::EventHeader::BRANCH) {
       size_t j = brname.find("_");
       std::string iname = brname.substr(0, j);
       std::string pname = brname.substr(j + 1);
       std::string tname =
           dynamic_cast<TBranchElement*>(branches->At(i))->GetClassName();
       products_.emplace_back(iname, pname, tname);
     }
     branchNames_.push_back(brname);
   }
 }
References ldmx::EventHeader::BRANCH, branches_, branchNames_, entries_, inputTree_, passengers_, and products_.
Referenced by framework::EventFile::nextEvent(), and framework::EventFile::setupEvent().
setOutputTree()
void framework::Event::setOutputTree (TTree * tree)
Set the output data tree.
Parameters
tree The output data tree.
Definition at line 81 of file Event.cxx.
 { outputTree_ = tree; }
References outputTree_.
Referenced by framework::EventFile::nextEvent().
shouldDrop()
bool framework::Event::shouldDrop (const std::string & collName) const private
Check if collection should be dropped.
Parameters
collName name of collection
Returns
true if the collection should be dropped (i.e. NOT saved)
Definition at line 149 of file Event.cxx.
{
   for (const regex_t& exp : regexDropCollections_) {
     if (!regexec(&exp, branchName.c_str(), 0, 0, 0)) return true;
   }
   return false;
 }
References regexDropCollections_.
Referenced by add().
Member Data Documentation
branches_
std::map<std::string, TBranchElement *> framework::Event::branches_ mutable private
Map of names to branches.
Definition at line 648 of file Event.h.
Referenced by getImpl(), onEndOfFile(), and setInputTree().
branchesFilled_
std::set<std::string> framework::Event::branchesFilled_ private
Names of branches filled during this event.
Definition at line 668 of file Event.h.
Referenced by add(), beforeFill(), and Clear().
branchNames_
std::vector<std::string> framework::Event::branchNames_ private
Names of all branches.
Definition at line 663 of file Event.h.
Referenced by add(), getImpl(), and setInputTree().
entries_
Long64_t framework::Event::entries_ {-1} private
Number of entries in the tree.
Definition at line 620 of file Event.h.
Referenced by onEndOfFile(), and setInputTree().
eventHeader_
ldmx::EventHeader framework::Event::eventHeader_ private
The event header object.
Definition at line 615 of file Event.h.
Referenced by beforeFill(), getEventHeader(), getEventHeaderPtr(), getEventNumber(), getEventWeight(), and nextEvent().
ientry_
Long64_t framework::Event::ientry_ {-1} private
Current entry in the tree.
Definition at line 625 of file Event.h.
Referenced by getImpl(), nextEvent(), and onEndOfFile().
inputTree_
TTree* framework::Event::inputTree_ {nullptr} private
The input tree for reading existing data.
Definition at line 640 of file Event.h.
Referenced by beforeFill(), getImpl(), onEndOfFile(), and setInputTree().
knownLookups_
std::map<std::string, std::string> framework::Event::knownLookups_ mutable private
Efficiency cache for empty pass name lookups.
Definition at line 678 of file Event.h.
Referenced by add(), and getImpl().
newBranches_
std::vector<TBranchElement *> framework::Event::newBranches_ private
List of new branches added.
Definition at line 658 of file Event.h.
Referenced by add().
outputTree_
TTree* framework::Event::outputTree_ {nullptr} private
The output tree for writing a new file.
Definition at line 635 of file Event.h.
Referenced by add(), createTree(), onEndOfFile(), and setOutputTree().
passengers_
std::map<std::string, EventBusPassenger> framework::Event::passengers_ mutable private
Map of names to passengers.
Definition at line 653 of file Event.h.
Referenced by add(), Clear(), getImpl(), onEndOfFile(), Print(), and setInputTree().
passName_
std::string framework::Event::passName_ private
The default pass name.
Definition at line 630 of file Event.h.
Referenced by add(), getImpl(), getPassName(), and makeBranchName().
products_
std::vector<ProductTag> framework::Event::products_ private
List of all the event products
Definition at line 683 of file Event.h.
Referenced by add(), getProducts(), and setInputTree().
regexDropCollections_
std::vector<regex_t> framework::Event::regexDropCollections_ private
Regex of collection names to not store in event.
Definition at line 673 of file Event.h.
Referenced by addDrop(), shouldDrop(), and ~Event().
The documentation for this class was generated from the following files:
Framework/include/Framework/Event.h
Framework/src/Framework/Event.cxx