LDMX Software: packing::FiberTrackerField Class Reference
packing::FiberTrackerField Class Reference
Public Member Functions
FiberTrackerField (utility::Reader &r, int i_field)
int to_int (const std::size_t i=0) const
std::string to_string () const
long int to_long (const std::size_t i=0) const
double to_double (const std::size_t i=0) const
const std::vector< uint32_t > & value () const
Private Attributes
uint32_t field_header_
std::vector< uint32_t > field_value_
Detailed Description
Each "field" of data in a FiberTracker packet
Definition at line 48 of file FiberTrackerRawDecoder.cxx.
Constructor & Destructor Documentation
FiberTrackerField()
packing::FiberTrackerField::FiberTrackerField (utility::Reader & r, int i_field) inline
r - reader i_field - field we are supposed to be reading from
Definition at line 56 of file FiberTrackerRawDecoder.cxx.
{
    uint32_t len;
    r >> len >> field_header_;
    r.read(field_value_,len-1);
    if (i_field != field_header_) {
      EXCEPTION_RAISE("BadForm", "Field "+std::to_string(i_field)+" has a mismatched header "+std::to_string(field_header_));
    }
  }
References packing::utility::Reader::read().
Member Function Documentation
to_double()
double packing::FiberTrackerField::to_double (const std::size_t i = 0) const inline
convert two ints into a double
Definition at line 96 of file FiberTrackerRawDecoder.cxx.
{
    return to_double_ft(this->to_long(i));
  }
References to_long().
Referenced by packing::FiberTrackerBinaryPacket::read().
to_int()
int packing::FiberTrackerField::to_int (const std::size_t i = 0) const inline
conversion to a single int
Definition at line 68 of file FiberTrackerRawDecoder.cxx.
{
    return field_value_.at(i);
  }
Referenced by packing::FiberTrackerBinaryPacket::read().
to_long()
long int packing::FiberTrackerField::to_long (const std::size_t i = 0) const inline
long split across two ints
i is index of field value to start from
Definition at line 89 of file FiberTrackerRawDecoder.cxx.
{
    return ((uint64_t)field_value_.at(i+1) << 32) | (uint64_t)field_value_.at(i);
  }
Referenced by packing::FiberTrackerBinaryPacket::read(), and to_double().
to_string()
std::string packing::FiberTrackerField::to_string () const inline
conversion from series of ints to string specific to FiberTrackerDAQ
Definition at line 75 of file FiberTrackerRawDecoder.cxx.
{
    std::string str;
    str.resize(field_value_.size());
    for (int i{0}; i < str.size(); i++) {
      str[i] = (char)field_value_[i];
    }
    return str;
  }
Referenced by packing::FiberTrackerBinaryPacket::read().
value()
const std::vector< uint32_t > & packing::FiberTrackerField::value () const inline
Get the field value
Definition at line 103 of file FiberTrackerRawDecoder.cxx.
{
    return field_value_;
  }
Referenced by packing::FiberTrackerBinaryPacket::read().
Member Data Documentation
field_header_
uint32_t packing::FiberTrackerField::field_header_ private
Definition at line 49 of file FiberTrackerRawDecoder.cxx.
field_value_
std::vector<uint32_t> packing::FiberTrackerField::field_value_ private
Definition at line 50 of file FiberTrackerRawDecoder.cxx.
The documentation for this class was generated from the following file:
Packing/src/Packing/FiberTrackerRawDecoder.cxx