LDMX Software: conditions::GeneralCSVLoader Class Reference
conditions::GeneralCSVLoader Class Reference abstract
Class which parses a CSV file and provides the rows one at a time to a user The parser ignores any line which begins with a '#' character The parser uses the first non-comment row to determine column names The parser handles quotation marks in a standard manner.
#include <GeneralCSVLoader.h>
Public Member Functions
virtual ~GeneralCSVLoader ()
std::vector< std::string > columnNames () const
bool nextRow ()
const std::string & get (const std::string &colname, bool ignore_case=true) const
int getInteger (const std::string &colname, bool ignore_case=true) const
Protected Member Functions
virtual std::string getNextLine ()=0
Private Attributes
std::vector< std::string > colNames_
std::vector< std::string > rowData_
Detailed Description
Class which parses a CSV file and provides the rows one at a time to a user The parser ignores any line which begins with a '#' character The parser uses the first non-comment row to determine column names The parser handles quotation marks in a standard manner.
Definition at line 18 of file GeneralCSVLoader.h.
Constructor & Destructor Documentation
~GeneralCSVLoader()
virtual conditions::GeneralCSVLoader::~GeneralCSVLoader () inline virtual
Destructor
Definition at line 21 of file GeneralCSVLoader.h.
{ }
GeneralCSVLoader()
conditions::GeneralCSVLoader::GeneralCSVLoader () inline protected
Definition at line 37 of file GeneralCSVLoader.h.
{ }
Member Function Documentation
columnNames()
std::vector< std::string > conditions::GeneralCSVLoader::columnNames () const inline
Get the column names
Definition at line 24 of file GeneralCSVLoader.h.
{ return colNames_; }
References colNames_.
get()
const std::string & conditions::GeneralCSVLoader::get (const std::string & colname, bool ignore_case = true) const
Get the value for the given column in the current row
Definition at line 11 of file GeneralCSVLoader.cxx.
{
  size_t i;
  for (i=0; i<colNames_.size(); i++) {
    if (ignore_case && !strcasecmp(colNames_[i].c_str(),colname.c_str())) break;
    if (colNames_[i]==colname) break;
  }
  if (i==colNames_.size()) {
    EXCEPTION_RAISE("CSVNoSuchColumn","No such column '"+colname+"' reading CSV");
  }
  return rowData_[i];
}
References colNames_, and rowData_.
Referenced by getInteger().
getInteger()
int conditions::GeneralCSVLoader::getInteger (const std::string & colname, bool ignore_case = true) const
Get the value for the given column in the current row as an integer
Definition at line 23 of file GeneralCSVLoader.cxx.
{
  return atoi(get(colname, ignore_case).c_str());
}
References get().
Referenced by hcal::HcalDetectorMap::HcalDetectorMap(), ecal::EcalDetectorMap::loadCellMap(), ecal::EcalDetectorMap::loadLayerMap(), and ecal::EcalDetectorMap::loadMotherboardMap().
getNextLine()
virtual std::string conditions::GeneralCSVLoader::getNextLine () protected pure virtual
Get the next line, returning an empty string when there is no further data
Implemented in conditions::StringCSVLoader, and conditions::StreamCSVLoader.
Referenced by nextRow().
nextRow()
bool conditions::GeneralCSVLoader::nextRow ()
Advance to next row if possible
Definition at line 27 of file GeneralCSVLoader.cxx.
{
  do {
    std::string line=getNextLine();
    if (line.empty()) return false;
    // it's a comment!
    if (line[0]=='#') continue;
    // split into pieces
    std::vector<std::string> line_split;
    // explicitly erase trailing white space
    line.erase(std::find_if(line.rbegin(), line.rend(),
          [](unsigned char c) { return !std::isspace(c); }).base(), line.end());
    boost::tokenizer<boost::escaped_list_separator<char>> tok(line);
    for (auto chunk : tok){
      line_split.push_back(chunk);
    }
    if (colNames_.empty()) {
      colNames_.swap(line_split);
      continue;
    }
    if (line_split.size()==colNames_.size()) rowData_.swap(line_split);
    else {
      EXCEPTION_RAISE("CSVLineMismatch","Reading CSV found line with "+std::to_string(line_split.size())+" in CSV with "+std::to_string(colNames_.size()) +" columns");
    }
    return true;
  } while (true);
}
References colNames_, getNextLine(), and rowData_.
Referenced by hcal::HcalDetectorMap::HcalDetectorMap(), ecal::EcalDetectorMap::loadCellMap(), ecal::EcalDetectorMap::loadLayerMap(), and ecal::EcalDetectorMap::loadMotherboardMap().
Member Data Documentation
colNames_
std::vector<std::string> conditions::GeneralCSVLoader::colNames_ private
The column names
Definition at line 46 of file GeneralCSVLoader.h.
Referenced by columnNames(), get(), and nextRow().
rowData_
std::vector<std::string> conditions::GeneralCSVLoader::rowData_ private
The row data
Definition at line 50 of file GeneralCSVLoader.h.
Referenced by get(), and nextRow().
The documentation for this class was generated from the following files:
Conditions/include/Conditions/GeneralCSVLoader.h
Conditions/src/Conditions/GeneralCSVLoader.cxx