LDMX Software: simcore::XsecBiasingOperator Class Reference
simcore::XsecBiasingOperator Class Reference abstract
#include <XsecBiasingOperator.h>
Public Types
using Factory = ::simcore::Factory< XsecBiasingOperator, std::shared_ptr< XsecBiasingOperator >, std::string, const framework::config::Parameters & >
Public Member Functions
XsecBiasingOperator (std::string name, const framework::config::Parameters &parameters)
virtual ~XsecBiasingOperator ()
virtual G4VBiasingOperation * ProposeOccurenceBiasingOperation (const G4Track *track, const G4BiasingProcessInterface *callingProcess)=0
void StartRun ()
virtual std::string getProcessToBias () const =0
virtual std::string getParticleToBias () const =0
virtual std::string getVolumeToBias () const =0
virtual void RecordConfig (ldmx::RunHeader &header) const =0
Protected Member Functions
G4VBiasingOperation * BiasedXsec (double biased_xsec)
bool processIsBiased (std::string process)
G4VBiasingOperation * ProposeFinalStateBiasingOperation (const G4Track *, const G4BiasingProcessInterface *)
G4VBiasingOperation * ProposeNonPhysicsBiasingOperation (const G4Track *, const G4BiasingProcessInterface *)
Protected Attributes
G4BOptnChangeCrossSection * xsecOperation_ {nullptr}
G4ProcessManager * processManager_ {nullptr}
Detailed Description
Our specialization of the biasing operator used with Geant4.
This specialization accomplishes three main tasks.
Allows any derived class to be dynamically loaded after using the declaration macro given below.
Interfaces with the derived class using our parameters class.
Pre-defines the necessary biasing operation so the derived class only needs to worry about calculating the biased xsec.
Definition at line 40 of file XsecBiasingOperator.h.
Member Typedef Documentation
Factory
using simcore::XsecBiasingOperator::Factory = ::simcore::Factory<XsecBiasingOperator, std::shared_ptr<XsecBiasingOperator>, std::string, const framework::config::Parameters&>
The BiasingOperator factory
Definition at line 58 of file XsecBiasingOperator.h.
Constructor & Destructor Documentation
XsecBiasingOperator()
simcore::XsecBiasingOperator::XsecBiasingOperator (std::string name, const framework::config::Parameters & parameters)
Constructor
Here, we define a unique name for this biasing operator and are given the configuration parameters loaded from the python script.
Parameters
[in] name unique instance name for this biasing operator
[in] parameters python configuration parameters
Definition at line 7 of file XsecBiasingOperator.cxx.
    : G4VBiasingOperator(name) {}
~XsecBiasingOperator()
simcore::XsecBiasingOperator::~XsecBiasingOperator () virtual
Destructor
Definition at line 11 of file XsecBiasingOperator.cxx.
{}
Member Function Documentation
BiasedXsec()
G4VBiasingOperation * simcore::XsecBiasingOperator::BiasedXsec (double biased_xsec) inline protected
Helper method for passing a biased interaction length to the Geant4 biasing framework.
Use like:
return BiasedXsec(biased_xsec);
inside of ProposeOccurenceBiasingOperation when you want to update the biased cross section.
Parameters
[in] biased_xsec the biased cross section
Returns
the biasing operation with the input biased cross section
Definition at line 144 of file XsecBiasingOperator.h.
{
    xsecOperation_->SetBiasedCrossSection(biased_xsec);
    xsecOperation_->Sample();
    return xsecOperation_;
  }
References xsecOperation_.
Referenced by simcore::biasoperators::DarkBrem::ProposeOccurenceBiasingOperation(), simcore::biasoperators::ElectroNuclear::ProposeOccurenceBiasingOperation(), simcore::biasoperators::GammaToMuPair::ProposeOccurenceBiasingOperation(), simcore::biasoperators::K0LongInelastic::ProposeOccurenceBiasingOperation(), simcore::biasoperators::NeutronInelastic::ProposeOccurenceBiasingOperation(), and simcore::biasoperators::PhotoNuclear::ProposeOccurenceBiasingOperation().
getParticleToBias()
virtual std::string simcore::XsecBiasingOperator::getParticleToBias () const pure virtual
Return the particle which should be biased.
We need this to be able to tell the physics list which particle to bias.
See also
RunManager::setupPhysics
Implemented in simcore::biasoperators::DarkBrem, simcore::biasoperators::ElectroNuclear, simcore::biasoperators::GammaToMuPair, simcore::biasoperators::K0LongInelastic, simcore::biasoperators::NeutronInelastic, and simcore::biasoperators::PhotoNuclear.
Referenced by StartRun().
getProcessToBias()
virtual std::string simcore::XsecBiasingOperator::getProcessToBias () const pure virtual
Return the process whose cross-section will be biased.
We need this to be able to check that the process was biased before creating the biasing operator.
Implemented in simcore::biasoperators::DarkBrem, simcore::biasoperators::ElectroNuclear, simcore::biasoperators::GammaToMuPair, simcore::biasoperators::K0LongInelastic, simcore::biasoperators::NeutronInelastic, and simcore::biasoperators::PhotoNuclear.
Referenced by StartRun().
getVolumeToBias()
virtual std::string simcore::XsecBiasingOperator::getVolumeToBias () const pure virtual
Return the volume which should be biased.
We need this to be able to tell the detector construction which volumes to attach this operator to.
Implemented in simcore::biasoperators::DarkBrem, simcore::biasoperators::ElectroNuclear, simcore::biasoperators::GammaToMuPair, simcore::biasoperators::K0LongInelastic, simcore::biasoperators::NeutronInelastic, and simcore::biasoperators::PhotoNuclear.
processIsBiased()
bool simcore::XsecBiasingOperator::processIsBiased (std::string process) protected
Check if the given processed is being biased.
Parameters
process Process of interest
Returns
true if the process is being biased, false otherwise
Definition at line 40 of file XsecBiasingOperator.cxx.
{
  // Loop over all processes and check if the given process is being
  // biased.
  const G4BiasingProcessSharedData* sharedData =
      G4BiasingProcessInterface::GetSharedData(processManager_);
  if (sharedData) {
    for (size_t iprocess = 0;
         iprocess < (sharedData->GetPhysicsBiasingProcessInterfaces()).size();
         ++iprocess) {
      const G4BiasingProcessInterface* wrapperProcess =
          (sharedData->GetPhysicsBiasingProcessInterfaces())[iprocess];
      if (wrapperProcess->GetWrappedProcess()->GetProcessName().compareTo(
              process) == 0) {
        return true;
      }
    }
  }
  return false;
}
References processManager_.
Referenced by simcore::biasoperators::PhotoNuclear::StartRun(), and StartRun().
ProposeFinalStateBiasingOperation()
G4VBiasingOperation * simcore::XsecBiasingOperator::ProposeFinalStateBiasingOperation (const G4Track * , const G4BiasingProcessInterface *) inline protected
Do not propose any biasing on final states.
Definition at line 167 of file XsecBiasingOperator.h.
{
    return nullptr;
  }
ProposeNonPhysicsBiasingOperation()
G4VBiasingOperation * simcore::XsecBiasingOperator::ProposeNonPhysicsBiasingOperation (const G4Track * , const G4BiasingProcessInterface *) inline protected
Do not propose any non-physics biasing.
Definition at line 175 of file XsecBiasingOperator.h.
{
    return nullptr;
  }
ProposeOccurenceBiasingOperation()
virtual G4VBiasingOperation * simcore::XsecBiasingOperator::ProposeOccurenceBiasingOperation (const G4Track * track, const G4BiasingProcessInterface * callingProcess) pure virtual
Propose a biasing operation for the current track and calling process.
Note
Returning 0 from this function will mean that the current track and process will not be biased.
See also
BiasedXsec for a method that allows the derived class to not interact with the biasing operation itself.
Parameters
[in] track handle to current track that could be biased
[in] callingProcess handle to process asking if it should be biased
Returns
the biasing operation with the biased xsec
Implemented in simcore::biasoperators::DarkBrem, simcore::biasoperators::ElectroNuclear, simcore::biasoperators::GammaToMuPair, simcore::biasoperators::K0LongInelastic, simcore::biasoperators::NeutronInelastic, and simcore::biasoperators::PhotoNuclear.
RecordConfig()
virtual void simcore::XsecBiasingOperator::RecordConfig (ldmx::RunHeader & header) const pure virtual
Record the configuration of this biasing operator into the run header.
Parameters
[in,out] header RunHeader to write configuration to
Implemented in simcore::biasoperators::PhotoNuclear, simcore::biasoperators::DarkBrem, simcore::biasoperators::ElectroNuclear, simcore::biasoperators::GammaToMuPair, simcore::biasoperators::K0LongInelastic, and simcore::biasoperators::NeutronInelastic.
StartRun()
void simcore::XsecBiasingOperator::StartRun ()
Method called at the beginning of a run.
This makes sure that the process we want to bias can be biased and constructs a corresponding biasing operation.
It can be over-written, but then the derived class should call XsecBiasingOperator::StartRun() at the beginning of their own StartRun.
Definition at line 13 of file XsecBiasingOperator.cxx.
{
  if (this->getParticleToBias().compare("gamma") == 0) {
    processManager_ = G4Gamma::GammaDefinition()->GetProcessManager();
  } else if (this->getParticleToBias().compare("e-") == 0) {
    processManager_ = G4Electron::ElectronDefinition()->GetProcessManager();
  } else if (this->getParticleToBias().compare("neutron") == 0) {
    processManager_ = G4Neutron::NeutronDefinition()->GetProcessManager();
  } else if (this->getParticleToBias().compare("kaon0L") == 0) {
    processManager_ = G4KaonZeroLong::KaonZeroLongDefinition()->GetProcessManager();
  } else {
    EXCEPTION_RAISE("BiasSetup", "Invalid particle type '" +
                                     this->getParticleToBias() + "'.");
  }
  std::cout << "[ XsecBiasingOperator ]: Biasing particles of type "
            << this->getParticleToBias() << std::endl;
  if (processIsBiased(this->getProcessToBias())) {
    xsecOperation_ =
        new G4BOptnChangeCrossSection("changeXsec-" + this->getProcessToBias());
  } else {
    EXCEPTION_RAISE("BiasSetup",
                    this->getProcessToBias() +
                        " is not found in list of biased processes!");
  }
}
References getParticleToBias(), getProcessToBias(), processIsBiased(), processManager_, and xsecOperation_.
Referenced by simcore::biasoperators::PhotoNuclear::StartRun().
Member Data Documentation
processManager_
G4ProcessManager* simcore::XsecBiasingOperator::processManager_ {nullptr} protected
Process manager associated with the particle of interest.
Definition at line 162 of file XsecBiasingOperator.h.
Referenced by processIsBiased(), and StartRun().
xsecOperation_
G4BOptnChangeCrossSection* simcore::XsecBiasingOperator::xsecOperation_ {nullptr} protected
Cross-section biasing operation.
Definition at line 159 of file XsecBiasingOperator.h.
Referenced by BiasedXsec(), and StartRun().
The documentation for this class was generated from the following files:
SimCore/include/SimCore/XsecBiasingOperator.h
SimCore/src/SimCore/XsecBiasingOperator.cxx