LDMX Software: simcore::UserAction Class Reference
simcore::UserAction Class Reference abstract
Interface that defines a user action.
#include <UserAction.h>
Public Types
using Factory = ::simcore::Factory< UserAction, std::shared_ptr< UserAction >, const std::string &, framework::config::Parameters & >
factory for user actions
Public Member Functions
UserAction (const std::string &name, framework::config::Parameters &parameters)
virtual ~UserAction ()
Destructor.
virtual void BeginOfEventAction (const G4Event *)
virtual void EndOfEventAction (const G4Event *)
virtual void BeginOfRunAction (const G4Run *)
virtual void EndOfRunAction (const G4Run *)
virtual void PreUserTrackingAction (const G4Track *)
virtual void PostUserTrackingAction (const G4Track *)
virtual void stepping (const G4Step *)
virtual G4ClassificationOfNewTrack ClassifyNewTrack (const G4Track *, const G4ClassificationOfNewTrack &cl)
virtual void NewStage ()
virtual void PrepareNewEvent ()
virtual std::vector< TYPE > getTypes ()=0
Protected Member Functions
UserEventInformation * getEventInfo () const
const std::map< int, ldmx::SimParticle > & getCurrentParticleMap () const
Protected Attributes
std::string name_ {""}
Name of the UserAction.
framework::config::Parameters parameters_
The set of parameters used to configure this class.
Detailed Description
Interface that defines a user action.
Definition at line 42 of file UserAction.h.
Member Typedef Documentation
Factory
using simcore::UserAction::Factory = ::simcore::Factory<UserAction, std::shared_ptr<UserAction>, const std::string&, framework::config::Parameters&>
factory for user actions
Definition at line 53 of file UserAction.h.
Constructor & Destructor Documentation
UserAction()
simcore::UserAction::UserAction (const std::string & name, framework::config::Parameters & parameters)
Constructor.
Parameters
name Name given the to class instance.
Definition at line 16 of file UserAction.cxx.
{
  name_ = name;
  parameters_ = parameters;
}
References name_, and parameters_.
~UserAction()
simcore::UserAction::~UserAction () virtual
Destructor.
Definition at line 22 of file UserAction.cxx.
{}
Member Function Documentation
BeginOfEventAction()
virtual void simcore::UserAction::BeginOfEventAction (const G4Event *) inline virtual
Method called at the beginning of every event.
TYPE::EVENT
Parameters
event Geant4 event object.
Reimplemented in biasing::TaggerVetoFilter, biasing::TargetDarkBremFilter, biasing::EcalDarkBremFilter, biasing::MidShowerNuclearBkgdFilter, and biasing::utility::PartialEnergySorter.
Definition at line 68 of file UserAction.h.
{};
BeginOfRunAction()
virtual void simcore::UserAction::BeginOfRunAction (const G4Run *) inline virtual
Method called at the beginning of a run.
TYPE::RUN
Parameters
run Current Geant4 run object.
Definition at line 86 of file UserAction.h.
{};
ClassifyNewTrack()
virtual G4ClassificationOfNewTrack simcore::UserAction::ClassifyNewTrack (const G4Track * , const G4ClassificationOfNewTrack & cl) inline virtual
Method called when a track is updated
TYPE::STEPPING
Parameters
current Geant4 track
current tracks' classification
Reimplemented in biasing::EcalDarkBremFilter, biasing::EcalProcessFilter, biasing::TargetBremFilter, biasing::TargetProcessFilter, and biasing::utility::PartialEnergySorter.
Definition at line 132 of file UserAction.h.
{
    return cl;
  };
EndOfEventAction()
virtual void simcore::UserAction::EndOfEventAction (const G4Event *) inline virtual
Method called at the end of every event.
TYPE::EVENT
Parameters
event Geant4 event object.
Reimplemented in biasing::TaggerVetoFilter, biasing::TargetBremFilter, biasing::TargetENProcessFilter, biasing::TargetProcessFilter, and biasing::TargetDarkBremFilter.
Definition at line 77 of file UserAction.h.
{};
EndOfRunAction()
virtual void simcore::UserAction::EndOfRunAction (const G4Run *) inline virtual
Method called at the end of a run.
TYPE::RUN
Parameters
run Current Geant4 run object.
Definition at line 95 of file UserAction.h.
{};
getCurrentParticleMap()
const std::map< int, ldmx::SimParticle > & simcore::UserAction::getCurrentParticleMap () const protected
Get the current particle map
Note
The current particle map will only have the particles already fully processed and chosen to be saved. The ancestry of the particles will not have been traced yet.
Definition at line 29 of file UserAction.cxx.
{
  return g4user::TrackingAction::get()->getTrackMap().getParticleMap();
}
References simcore::g4user::TrackingAction::get(), simcore::TrackMap::getParticleMap(), and simcore::g4user::TrackingAction::getTrackMap().
Referenced by biasing::utility::DecayChildrenKeeper::PostUserTrackingAction().
getEventInfo()
UserEventInformation * simcore::UserAction::getEventInfo () const protected
Get a handle to the event information
This is static just to point out that it doesn't depend on any of the member variables of this class. It is just a helper function for shortening any code that interacts with our event information.
Returns
pointer to the current event information
Definition at line 24 of file UserAction.cxx.
{
  return static_cast<UserEventInformation*>(
      G4EventManager::GetEventManager()->GetUserInformation());
}
Referenced by biasing::MidShowerNuclearBkgdFilter::stepping(), biasing::TargetBremFilter::stepping(), and biasing::TargetProcessFilter::stepping().
getTypes()
virtual std::vector< TYPE > simcore::UserAction::getTypes () pure virtual
Returns
The user action types
Must be defined by any UserActions so that we know what functions to call.
Implemented in biasing::utility::PartialEnergySorter, biasing::EcalDarkBremFilter, biasing::EcalProcessFilter, biasing::MidShowerNuclearBkgdFilter, biasing::PhotoNuclearProductsFilter, biasing::PrimaryToEcalFilter, biasing::TaggerVetoFilter, biasing::TargetBremFilter, biasing::TargetDarkBremFilter, biasing::TargetENProcessFilter, biasing::TargetProcessFilter, biasing::utility::DecayChildrenKeeper, biasing::utility::StepPrinter, and biasing::utility::TrackProcessFilter.
NewStage()
virtual void simcore::UserAction::NewStage () inline virtual
Method called at the beginning of a new stage
TYPE::STACKING
Reimplemented in biasing::EcalDarkBremFilter, biasing::MidShowerNuclearBkgdFilter, and biasing::utility::PartialEnergySorter.
Definition at line 142 of file UserAction.h.
{};
PostUserTrackingAction()
virtual void simcore::UserAction::PostUserTrackingAction (const G4Track *) inline virtual
Method called after the UserTrackingAction.
TYPE::TRACKING
Parameters
track current Geant4 track
Reimplemented in biasing::EcalDarkBremFilter, biasing::utility::DecayChildrenKeeper, and biasing::utility::TrackProcessFilter.
Definition at line 113 of file UserAction.h.
{};
PrepareNewEvent()
virtual void simcore::UserAction::PrepareNewEvent () inline virtual
Method called at the beginning of a new event
TYPE::STACKING
Definition at line 149 of file UserAction.h.
{};
PreUserTrackingAction()
virtual void simcore::UserAction::PreUserTrackingAction (const G4Track *) inline virtual
Method called before the UserTrackingAction.
TYPE::TRACKING
Parameters
track current Geant4 track
Definition at line 104 of file UserAction.h.
{};
stepping()
virtual void simcore::UserAction::stepping (const G4Step *) inline virtual
Method called after each simulation step.
TYPE::STEPPING
Parameters
current Geant4 step
Reimplemented in biasing::TargetDarkBremFilter, biasing::EcalProcessFilter, biasing::MidShowerNuclearBkgdFilter, biasing::PhotoNuclearProductsFilter, biasing::PrimaryToEcalFilter, biasing::TaggerVetoFilter, biasing::TargetBremFilter, biasing::TargetENProcessFilter, biasing::TargetProcessFilter, biasing::utility::PartialEnergySorter, and biasing::utility::StepPrinter.
Definition at line 122 of file UserAction.h.
{};
Member Data Documentation
name_
std::string simcore::UserAction::name_ {""} protected
Name of the UserAction.
Definition at line 182 of file UserAction.h.
Referenced by UserAction().
parameters_
framework::config::Parameters simcore::UserAction::parameters_ protected
The set of parameters used to configure this class.
Definition at line 185 of file UserAction.h.
Referenced by UserAction().
The documentation for this class was generated from the following files:
SimCore/include/SimCore/UserAction.h
SimCore/src/SimCore/UserAction.cxx