LDMX Software: ldmx::EventHeader Class Reference
ldmx::EventHeader Class Reference
Provides header information an event such as event number and timestamp.
#include <EventHeader.h>
Public Member Functions
EventHeader ()
virtual ~EventHeader ()
void Clear (Option_t *="")
void Print (Option_t *="") const
int getEventNumber () const
int getRun () const
const TTimeStamp & getTimestamp () const
double getWeight () const
bool isRealData () const
void setRealData (bool yes=true)
void setEventNumber (int eventNumber)
void setRun (int run)
void setTimestamp (const TTimeStamp &timestamp)
void setWeight (double weight)
int getIntParameter (const std::string &name)
void setIntParameter (const std::string &name, int value)
float getFloatParameter (const std::string &name)
void setFloatParameter (const std::string &name, float value)
std::string getStringParameter (const std::string &name)
void setStringParameter (const std::string &name, std::string value)
Static Public Attributes
static const std::string BRANCH = "EventHeader"
Protected Member Functions
ClassDef (EventHeader, 2)
Protected Attributes
int eventNumber_ {-1}
int run_ {-1}
TTimeStamp timestamp_ {0, 0}
double weight_ {1.0}
bool isRealData_ {false}
std::map< std::string, int > intParameters_
std::map< std::string, float > floatParameters_
std::map< std::string, std::string > stringParameters_
Detailed Description
Provides header information an event such as event number and timestamp.
Definition at line 27 of file EventHeader.h.
Constructor & Destructor Documentation
EventHeader()
ldmx::EventHeader::EventHeader () inline
Class constructor.
Definition at line 37 of file EventHeader.h.
{}
~EventHeader()
virtual ldmx::EventHeader::~EventHeader () inline virtual
Class destructor.
Definition at line 42 of file EventHeader.h.
{}
Member Function Documentation
ClassDef()
ldmx::EventHeader::ClassDef (EventHeader , 2) protected
ROOT class definition.
Clear()
void ldmx::EventHeader::Clear (Option_t * = "") inline
Clear information from this object.
Definition at line 47 of file EventHeader.h.
{
    eventNumber_ = -1;
    run_ = -1;
    timestamp_ = TTimeStamp(0, 0);
    weight_ = 1.0;
    isRealData_ = false;
    intParameters_.clear();
    floatParameters_.clear();
    stringParameters_.clear();
  }
References eventNumber_, floatParameters_, intParameters_, isRealData_, run_, stringParameters_, timestamp_, and weight_.
getEventNumber()
int ldmx::EventHeader::getEventNumber () const inline
Return the event number.
Returns
The event number.
Definition at line 76 of file EventHeader.h.
{ return eventNumber_; }
References eventNumber_.
Referenced by framework::Conditions::getConditionPtr(), framework::Event::getEventNumber(), trigscint::QIEDecoder::produce(), recon::OverlayProducer::produce(), and simcore::Simulator::produce().
getFloatParameter()
float ldmx::EventHeader::getFloatParameter (const std::string & name) inline
Get a float parameter value.
Parameters
name The name of the parameter.
Returns
value The parameter value.
Definition at line 160 of file EventHeader.h.
{
    return floatParameters_[name];
  }
References floatParameters_.
getIntParameter()
int ldmx::EventHeader::getIntParameter (const std::string & name) inline
Get an int parameter value.
Parameters
name The name of the parameter.
Returns
The parameter value.
Definition at line 143 of file EventHeader.h.
{ return intParameters_[name]; }
References intParameters_.
getRun()
int ldmx::EventHeader::getRun () const inline
Return the run number.
Returns
The run number.
Definition at line 82 of file EventHeader.h.
{ return run_; }
References run_.
Referenced by ecal::EcalDetectorMapLoader::getCondition(), ecal::EcalGeometryProvider::getCondition(), ecal::EcalTriggerGeometryProvider::getCondition(), framework::RandomNumberSeedService::getCondition(), hcal::HcalDetectorMapLoader::getCondition(), hcal::HcalGeometryProvider::getCondition(), hcal::HcalTriggerGeometryProvider::getCondition(), framework::Conditions::getConditionPtr(), framework::Process::getRunNumber(), framework::Process::run(), and framework::ConditionsIOV::validForEvent().
getStringParameter()
std::string ldmx::EventHeader::getStringParameter (const std::string & name) inline
Get a string parameter value.
Parameters
name The name of the parameter.
Returns
value The parameter value.
Definition at line 178 of file EventHeader.h.
{
    return stringParameters_[name];
  }
References stringParameters_.
Referenced by simcore::RootCompleteReSim::GeneratePrimaryVertex(), and simcore::RootSimFromEcalSP::GeneratePrimaryVertex().
getTimestamp()
const TTimeStamp & ldmx::EventHeader::getTimestamp () const inline
Get the event's timestamp. This currently returns second's since the epoch for simulated events.
Returns
The event's timestamp.
Note
The returned object has a possible resolution of nanoseconds.
Definition at line 90 of file EventHeader.h.
{ return timestamp_; }
References timestamp_.
getWeight()
double ldmx::EventHeader::getWeight () const inline
Get the event weight (default of 1.0).
Returns
The event weight.
Definition at line 96 of file EventHeader.h.
{ return weight_; }
References weight_.
Referenced by framework::Event::getEventWeight().
isRealData()
bool ldmx::EventHeader::isRealData () const inline
Is this a real data event?
Returns
True if this is a real data event.
Definition at line 102 of file EventHeader.h.
{ return isRealData_; }
References isRealData_.
Referenced by framework::Conditions::getConditionPtr(), and framework::ConditionsIOV::validForEvent().
Print()
void ldmx::EventHeader::Print (Option_t * = "") const inline
Print this object.
Definition at line 61 of file EventHeader.h.
{
    std::cout << "EventHeader {"
              << " eventNumber: " << eventNumber_ << ", run: " << run_
              << ", timestamp: " << timestamp_ << ", weight: " << weight_;
    if (isRealData_)
      std::cout << ", DATA";
    else
      std::cout << ", MC";
    std::cout << " }" << std::endl;
  }
References eventNumber_, isRealData_, run_, timestamp_, and weight_.
setEventNumber()
void ldmx::EventHeader::setEventNumber (int eventNumber) inline
Set the event number.
Parameters
eventNumber The event number.
Definition at line 116 of file EventHeader.h.
{ this->eventNumber_ = eventNumber; }
References eventNumber_.
Referenced by packing::rawdatafile::File::nextEvent(), recon::OverlayProducer::onNewRun(), and framework::Process::run().
setFloatParameter()
void ldmx::EventHeader::setFloatParameter (const std::string & name, float value) inline
Set a float parameter value.
Parameters
name The name of the parameter.
Returns
value The parameter value.
Definition at line 169 of file EventHeader.h.
{
    floatParameters_[name] = value;
  }
References floatParameters_.
Referenced by simcore::persist::RootPersistencyManager::writeHeader().
setIntParameter()
void ldmx::EventHeader::setIntParameter (const std::string & name, int value) inline
Set an int parameter value.
Parameters
name The name of the parameter.
value The value of the parameter.
Returns
The parameter value.
Definition at line 151 of file EventHeader.h.
{
    intParameters_[name] = value;
  }
References intParameters_.
setRealData()
void ldmx::EventHeader::setRealData (bool yes = true) inline
set whether this event is real or MC data
Parameters
[in] yes True if this event is real data
Definition at line 108 of file EventHeader.h.
{
    isRealData_ = yes;
  }
References isRealData_.
setRun()
void ldmx::EventHeader::setRun (int run) inline
Set the run number.
Parameters
run The run number.
Definition at line 122 of file EventHeader.h.
{ this->run_ = run; }
References run_.
Referenced by framework::Process::run().
setStringParameter()
void ldmx::EventHeader::setStringParameter (const std::string & name, std::string value) inline
Set a string parameter value.
Parameters
name The name of the parameter.
Returns
value The parameter value.
Definition at line 187 of file EventHeader.h.
{
    stringParameters_[name] = value;
  }
References stringParameters_.
Referenced by simcore::persist::RootPersistencyManager::writeHeader().
setTimestamp()
void ldmx::EventHeader::setTimestamp (const TTimeStamp & timestamp) inline
Set the timestamp.
Parameters
timestamp The timestamp.
Definition at line 128 of file EventHeader.h.
{
    this->timestamp_ = timestamp;
  }
References timestamp_.
Referenced by framework::Process::run().
setWeight()
void ldmx::EventHeader::setWeight (double weight) inline
Set the event weight.
Parameters
weight The event weight.
Definition at line 136 of file EventHeader.h.
{ this->weight_ = weight; }
References weight_.
Referenced by simcore::persist::RootPersistencyManager::writeHeader().
Member Data Documentation
BRANCH
const std::string ldmx::EventHeader::BRANCH = "EventHeader" static
Name of EventHeader branch
Definition at line 32 of file EventHeader.h.
Referenced by framework::Event::add(), framework::Event::beforeFill(), framework::Event::getObject(), framework::Event::nextEvent(), and framework::Event::setInputTree().
eventNumber_
int ldmx::EventHeader::eventNumber_ {-1} protected
The event number.
Definition at line 195 of file EventHeader.h.
Referenced by Clear(), getEventNumber(), Print(), and setEventNumber().
floatParameters_
std::map<std::string, float> ldmx::EventHeader::floatParameters_ protected
The float parameters.
Definition at line 225 of file EventHeader.h.
Referenced by Clear(), getFloatParameter(), and setFloatParameter().
intParameters_
std::map<std::string, int> ldmx::EventHeader::intParameters_ protected
The int parameters.
Definition at line 220 of file EventHeader.h.
Referenced by Clear(), getIntParameter(), and setIntParameter().
isRealData_
bool ldmx::EventHeader::isRealData_ {false} protected
Is this event real data?
Definition at line 215 of file EventHeader.h.
Referenced by Clear(), isRealData(), Print(), and setRealData().
run_
int ldmx::EventHeader::run_ {-1} protected
The run number.
Definition at line 200 of file EventHeader.h.
Referenced by Clear(), getRun(), Print(), and setRun().
stringParameters_
std::map<std::string, std::string> ldmx::EventHeader::stringParameters_ protected
The string parameters.
Definition at line 230 of file EventHeader.h.
Referenced by Clear(), getStringParameter(), and setStringParameter().
timestamp_
TTimeStamp ldmx::EventHeader::timestamp_ {0, 0} protected
The event timestamp
Definition at line 205 of file EventHeader.h.
Referenced by Clear(), getTimestamp(), Print(), and setTimestamp().
weight_
double ldmx::EventHeader::weight_ {1.0} protected
The event weight.
Definition at line 210 of file EventHeader.h.
Referenced by Clear(), getWeight(), Print(), and setWeight().
The documentation for this class was generated from the following files:
Framework/include/Framework/EventHeader.h
Framework/src/Framework/EventHeader.cxx