LDMX Software: hcal::HcalSingleEndRecProducer Class Reference
hcal::HcalSingleEndRecProducer Class Reference
Public Member Functions
HcalSingleEndRecProducer (const std::string &n, framework::Process &p)
virtual void configure (framework::config::Parameters &p) final override
virtual void produce (framework::Event &event) final override
Public Member Functions inherited from framework::Producer
Producer (const std::string &name, Process &process)
virtual void produce (Event &event)=0
virtual void beforeNewRun (ldmx::RunHeader &header)
Public Member Functions inherited from framework::EventProcessor
EventProcessor (const std::string &name, Process &process)
virtual ~EventProcessor ()
virtual void configure (framework::config::Parameters &parameters)
virtual void onNewRun (const ldmx::RunHeader &runHeader)
virtual void onFileOpen (EventFile &eventFile)
virtual void onFileClose (EventFile &eventFile)
virtual void onProcessStart ()
virtual void onProcessEnd ()
template<class T >
const T & getCondition (const std::string &condition_name)
TDirectory * getHistoDirectory ()
void setStorageHint (framework::StorageControlHint hint)
void setStorageHint (framework::StorageControlHint hint, const std::string &purposeString)
int getLogFrequency () const
int getRunNumber () const
std::string getName () const
void createHistograms (const std::vector< framework::config::Parameters > &histos)
Private Member Functions
std::tuple< double, double, int > extract_measurements (const ldmx::HgcrocDigiCollection::HgcrocDigi &digi, double pedestal, double bx_shift)
Private Attributes
std::string pass_name_ {""}
name of pass of digis to use
std::string coll_name_ {"HcalDigis"}
name of digis to reconstruct
std::string rec_pass_name_ {""}
name of pass of rechits to use
std::string rec_coll_name_ {"HcalRecHits"}
name of rechits to reconstruct
double pe_per_mip_
number of PEs per MIP
double mip_energy_
energy per MIP [MeV]
double clock_cycle_
length of clock cycle [ns]
unsigned int isoi_
sample of interest index
Additional Inherited Members
Static Public Member Functions inherited from framework::EventProcessor
static void declare (const std::string &classname, int classtype, EventProcessorMaker *)
Static Public Attributes inherited from framework::Producer
static const int CLASSTYPE {1}
Protected Member Functions inherited from framework::EventProcessor
void abortEvent ()
Protected Attributes inherited from framework::EventProcessor
HistogramHelper histograms_
Interface class for making and filling histograms.
NtupleManager & ntuple_ {NtupleManager::getInstance()}
Manager for any ntuples.
logging::logger theLog_
The logger for this EventProcessor.
Detailed Description
Definition at line 13 of file HcalSingleEndRecProducer.cxx.
Constructor & Destructor Documentation
HcalSingleEndRecProducer()
hcal::HcalSingleEndRecProducer::HcalSingleEndRecProducer (const std::string & n, framework::Process & p) inline
Definition at line 60 of file HcalSingleEndRecProducer.cxx.
      : Producer(n, p) {}
Member Function Documentation
configure()
void hcal::HcalSingleEndRecProducer::configure (framework::config::Parameters & parameters) final override virtual
Callback for the EventProcessor to configure itself from the given set of parameters.
The parameters a processor has access to are the member variables of the python class in the sequence that has className equal to the EventProcessor class name.
For an example, look at MyProcessor.
Parameters
parameters Parameters for configuration.
Reimplemented from framework::EventProcessor.
Definition at line 117 of file HcalSingleEndRecProducer.cxx.
{
  pass_name_ = p.getParameter("pass_name", pass_name_);
  coll_name_ = p.getParameter("coll_name", coll_name_);
  rec_pass_name_ = p.getParameter("rec_pass_name", rec_pass_name_);
  rec_coll_name_ = p.getParameter("rec_coll_name", rec_coll_name_);
  pe_per_mip_ = p.getParameter<double>("pe_per_mip");
  mip_energy_ = p.getParameter<double>("mip_energy");
  clock_cycle_ = p.getParameter<double>("clock_cycle");
}
References clock_cycle_, coll_name_, framework::config::Parameters::getParameter(), mip_energy_, pass_name_, pe_per_mip_, rec_coll_name_, and rec_pass_name_.
extract_measurements()
std::tuple< double, double, int > hcal::HcalSingleEndRecProducer::extract_measurements (const ldmx::HgcrocDigiCollection::HgcrocDigi & digi, double pedestal, double bx_shift) private
extract toa, sum adc, and sum tot from the input raw digi
in the far future, we can make these member functions ofthe HgcrocDigi class; however, right now as we develop our reconstruction method it is helpful to have more flexible control on how we extract these measurements
with C++17 structured bindings, this tuple return can be bound to separate variables:
auto [ toa, sum_adc, sum_tot ] = extract_measurements(digi,pedestal,bx_shift);
giving us the dual benefit of separate variable names while only having to loop over the samples within a single digi once
Uses isoi_ and clock_cycle_ member variables to convert TOA into ns since beginning of Sample Of Interest (SOI)
Parameters
[in] digi handle to HgcrocDigi to extract from
[in] pedestal pedestal for this channel
[in] shift in BX associated to TOA for this channel
Returns
tuple of (toa [ns since SOI], sum_adc, sum_tot)
Definition at line 68 of file HcalSingleEndRecProducer.cxx.
{
  // sum_adc = total of all but first in-time adc measurements
  double sum_adc{0};
  // sum_tot = total of all tot measurements
  int sum_tot{0};
  // first, get time of arrival w.r.t to start BX
  int toa_sample{0}, toa_startbx{0};
  // get the correction for the wrong BX assignment
  int bx_to_time{0};
  // and figure out sample of maximum amplitude
  int max_sample{0};
  double max_meas{0};
  for (std::size_t i_sample{0}; i_sample < digi.size(); i_sample++) {
    // adc logic
    if (i_sample > 0) sum_adc += (digi.at(i_sample).adc_t() - pedestal);
    // tot logic
    sum_tot += digi.at(i_sample).tot();
    // toa logic
    if (digi.at(i_sample).toa() > 0) {
      if (digi.at(i_sample).toa() >= bx_shift) {
    toa_sample = i_sample;
      }
      else {
    toa_sample = i_sample + 1;
      }
      // sum toa in given bx - given that multiple bx may be associated with the TOA measurement
      toa_startbx += digi.at(i_sample).toa() * (clock_cycle_ / 1024) + (clock_cycle_ * toa_sample);
    }
    if (digi.at(i_sample).adc_t() - pedestal > max_meas) {
      max_meas = digi.at(i_sample).adc_t() - pedestal;
      max_sample = i_sample;
    }
  }
  // get toa
  double toa = toa_startbx;
  // get toa w.r.t the peak
  //double toa = (max_sample - toa_sample) * clock_cycle_ - toa_startbx;
  // get toa w.r.t the SOI
  //toa += ((int)isoi_ - max_sample) * clock_cycle_;
  return std::make_tuple(toa, sum_adc, sum_tot);
}
References ldmx::HgcrocDigiCollection::Sample::adc_t(), ldmx::HgcrocDigiCollection::HgcrocDigi::at(), clock_cycle_, ldmx::HgcrocDigiCollection::Sample::toa(), and ldmx::HgcrocDigiCollection::Sample::tot().
Referenced by produce().
produce()
void hcal::HcalSingleEndRecProducer::produce (framework::Event & event) final override virtual
Process the event and put new data products into it.
Parameters
event The Event to process.
Implements framework::Producer.
Definition at line 129 of file HcalSingleEndRecProducer.cxx.
{
  const auto& hcalGeometry = getCondition<ldmx::HcalGeometry>(
      ldmx::HcalGeometry::CONDITIONS_OBJECT_NAME);
  const auto& conditions{
      getCondition<HcalReconConditions>(HcalReconConditions::CONDITIONS_NAME)};
  auto hcalDigis =
      event.getObject<ldmx::HgcrocDigiCollection>(coll_name_, pass_name_);
  std::vector<ldmx::HcalHit> hcalRecHits;
  isoi_ = hcalDigis.getSampleOfInterestIndex();
  for (auto const& digi : hcalDigis) {
    ldmx::HcalDigiID id_digi(digi.id());
    ldmx::HcalID id(id_digi.section(), id_digi.layer(), id_digi.strip());
    // amplitude/TOT reconstruction
    double num_mips_equivalent{0};
    auto [toa, sum_adc, sum_tot] =
      extract_measurements(digi, conditions.adcPedestal(digi.id()), conditions.toaCalib(digi.id(), 0));
    auto is_adc = conditions.is_adc(digi.id(), sum_tot);
    if (is_adc) {
      double adc_calib = sum_adc / conditions.adcGain(digi.id(), 0);
      num_mips_equivalent = adc_calib;
    } else {
      double tot_calib = conditions.linearize(digi.id(), sum_tot);
      num_mips_equivalent = tot_calib / conditions.adcGain(digi.id(), 0);
    }
    int PEs = num_mips_equivalent * pe_per_mip_;
    double reconstructed_energy =
        num_mips_equivalent * pe_per_mip_ * mip_energy_;
    // time reconstruction
    double hitTime = toa;
    // position single ended (taken directly from geometry)
    auto position = hcalGeometry.getStripCenterPosition(id);
    // reconstructed Hit
    ldmx::HcalHit recHit;
    recHit.setID(id.raw());
    recHit.setXPos(position.X());
    recHit.setYPos(position.Y());
    recHit.setZPos(position.Z());
    recHit.setSection(id.section());
    recHit.setStrip(id.strip());
    recHit.setLayer(id.layer());
    recHit.setEnd(id_digi.end());
    recHit.setPE(PEs);
    recHit.setMinPE(PEs);
    recHit.setAmplitude(num_mips_equivalent);
    recHit.setEnergy(reconstructed_energy);
    recHit.setTime(hitTime);
    recHit.setIsADC(is_adc);
    hcalRecHits.push_back(recHit);
  }
  // add collection to event bus
  event.add(rec_coll_name_, hcalRecHits);
}
References coll_name_, hcal::HcalReconConditions::CONDITIONS_NAME, ldmx::HcalGeometry::CONDITIONS_OBJECT_NAME, ldmx::HcalDigiID::end(), extract_measurements(), isoi_, ldmx::HcalDigiID::layer(), mip_energy_, pass_name_, pe_per_mip_, rec_coll_name_, ldmx::HcalDigiID::section(), ldmx::CalorimeterHit::setAmplitude(), ldmx::HcalHit::setEnd(), ldmx::CalorimeterHit::setEnergy(), ldmx::CalorimeterHit::setID(), ldmx::HcalHit::setIsADC(), ldmx::HcalHit::setLayer(), ldmx::HcalHit::setMinPE(), ldmx::HcalHit::setPE(), ldmx::HcalHit::setSection(), ldmx::HcalHit::setStrip(), ldmx::CalorimeterHit::setTime(), ldmx::CalorimeterHit::setXPos(), ldmx::CalorimeterHit::setYPos(), ldmx::CalorimeterHit::setZPos(), and ldmx::HcalDigiID::strip().
Member Data Documentation
clock_cycle_
double hcal::HcalSingleEndRecProducer::clock_cycle_ private
length of clock cycle [ns]
Definition at line 28 of file HcalSingleEndRecProducer.cxx.
Referenced by configure(), and extract_measurements().
coll_name_
std::string hcal::HcalSingleEndRecProducer::coll_name_ {"HcalDigis"} private
name of digis to reconstruct
Definition at line 17 of file HcalSingleEndRecProducer.cxx.
Referenced by configure(), and produce().
isoi_
unsigned int hcal::HcalSingleEndRecProducer::isoi_ private
sample of interest index
Definition at line 30 of file HcalSingleEndRecProducer.cxx.
Referenced by produce().
mip_energy_
double hcal::HcalSingleEndRecProducer::mip_energy_ private
energy per MIP [MeV]
Definition at line 26 of file HcalSingleEndRecProducer.cxx.
Referenced by configure(), and produce().
pass_name_
std::string hcal::HcalSingleEndRecProducer::pass_name_ {""} private
name of pass of digis to use
Definition at line 15 of file HcalSingleEndRecProducer.cxx.
Referenced by configure(), and produce().
pe_per_mip_
double hcal::HcalSingleEndRecProducer::pe_per_mip_ private
number of PEs per MIP
Definition at line 24 of file HcalSingleEndRecProducer.cxx.
Referenced by configure(), and produce().
rec_coll_name_
std::string hcal::HcalSingleEndRecProducer::rec_coll_name_ {"HcalRecHits"} private
name of rechits to reconstruct
Definition at line 21 of file HcalSingleEndRecProducer.cxx.
Referenced by configure(), and produce().
rec_pass_name_
std::string hcal::HcalSingleEndRecProducer::rec_pass_name_ {""} private
name of pass of rechits to use
Definition at line 19 of file HcalSingleEndRecProducer.cxx.
Referenced by configure().
The documentation for this class was generated from the following file:
Hcal/src/Hcal/HcalSingleEndRecProducer.cxx