LDMX Software: ldmx::TrigScintHitDQM Class Reference
ldmx::TrigScintHitDQM Class Reference
Public Member Functions
TrigScintHitDQM (const std::string &name, Process &process)
~TrigScintHitDQM ()
void configure (Parameters &pSet)
void analyze (const Event &event)
void onProcessStart ()
Public Member Functions inherited from ldmx::Analyzer
Analyzer (const std::string &name, Process &process)
Public Member Functions inherited from ldmx::EventProcessor
EventProcessor (const std::string &name, Process &process)
virtual ~EventProcessor ()
virtual void onNewRun (const RunHeader &runHeader)
virtual void onFileOpen (EventFile &eventFile)
virtual void onFileClose (EventFile &eventFile)
virtual void onProcessEnd ()
TDirectory * getHistoDirectory ()
void setStorageHint (ldmx::StorageControlHint hint)
void setStorageHint (ldmx::StorageControlHint hint, const std::string &purposeString)
void createHistograms (const std::vector< Parameters > &histos)
Private Attributes
std::string hitCollectionName_ {"TriggerPadUpDigiHits"}
std::string padName_ {"_up"}
Additional Inherited Members
Static Public Member Functions inherited from ldmx::EventProcessor
static void declare (const std::string &classname, int classtype, EventProcessorMaker *)
Static Public Attributes inherited from ldmx::Analyzer
static const int CLASSTYPE {2}
Protected Member Functions inherited from ldmx::EventProcessor
void abortEvent ()
Protected Attributes inherited from ldmx::EventProcessor
Process & process_
HistogramHelper histograms_
Interface class for making and filling histograms.
NtupleManager & ntuple_ {NtupleManager::getInstance()}
Manager for any ntuples.
logging::logger theLog_
The logger for this EventProcessor.
Detailed Description
Definition at line 27 of file TrigScintHitDQM.h.
Constructor & Destructor Documentation
TrigScintHitDQM()
ldmx::TrigScintHitDQM::TrigScintHitDQM (const std::string & name, Process & process)
Constructor
Definition at line 12 of file TrigScintHitDQM.cxx.
                                                                             :
         Analyzer(name, process) { }
~TrigScintHitDQM()
ldmx::TrigScintHitDQM::~TrigScintHitDQM ()
Destructor
Definition at line 15 of file TrigScintHitDQM.cxx.
 {}
Member Function Documentation
analyze()
void ldmx::TrigScintHitDQM::analyze (const Event & event) virtual
Process the event and make histograms ro summaries.
Parameters
event The event to analyze.
Implements ldmx::Analyzer.
Definition at line 56 of file TrigScintHitDQM.cxx.
{
         // Check if the collection of digitized TrigScint hits exist. If it doesn't
         // don't continue processing.
         if ( !event.exists(hitCollectionName_.c_str()) ) {
             std::cout << "No collection called " << hitCollectionName_ << std::endl;
             return;
         }
         // Get the collection of TrigScintHit digitized hits if the exists
         const std::vector<TrigScintHit> TrigScintHits = event.getCollection<TrigScintHit>( hitCollectionName_);
         // Get the total hit count
         int hitCount = TrigScintHits.size();
         histograms_.fill("n_hits",hitCount);
         double totalPE{0};
         int noiseHitCount = 0;
         // Loop through all TrigScint hits in the event
         for (const TrigScintHit &hit : TrigScintHits ) {
             histograms_.fill("pe",hit.getPE());
             histograms_.fill("hit_time",hit.getTime());
             histograms_.fill("id",hit.getBarID() );
             totalPE += hit.getPE();
             if ( hit.getNoise()>0 ) {
                 noiseHitCount++;
                 histograms_.fill("pe_noise",hit.getPE());
                 histograms_.fill("id_noise",hit.getBarID() );
             } else {  //x, y, z not set for noise hits
                 histograms_.fill("x", hit.getX() );
                 histograms_.fill("y", hit.getY() );
                 histograms_.fill("z", hit.getZ() );
             }
         }
         histograms_.fill("total_pe",totalPE);
         histograms_.fill("n_hits_noise",noiseHitCount);
     }
References ldmx::Event::exists(), ldmx::HistogramHelper::fill(), ldmx::EventProcessor::histograms_, and hitCollectionName_.
configure()
void ldmx::TrigScintHitDQM::configure (Parameters & pSet) virtual
Configure the processor using the given user specified parameters.
Parameters
pSet Set of parameters used to configure this processor.
Reimplemented from ldmx::EventProcessor.
Definition at line 49 of file TrigScintHitDQM.cxx.
{
         hitCollectionName_ = ps.getParameter< std::string >("hit_collection");
         padName_ = ps.getParameter< std::string >("pad").c_str();
         std::cout << "In TrigScintHitDQM::configure, got parameters " << hitCollectionName_ << " and " << padName_ << std::endl;
     }
References ldmx::Parameters::getParameter(), and hitCollectionName_.
onProcessStart()
void ldmx::TrigScintHitDQM::onProcessStart () virtual
Method executed before processing of events begins.
Reimplemented from ldmx::EventProcessor.
Definition at line 17 of file TrigScintHitDQM.cxx.
{
         std::cout << "Process starts!" << std::endl;
         getHistoDirectory();
         histograms_.create("id", "Channel ID of sim hit", 100, 0, 100);
         histograms_.create("total_pe", "Total pe deposition in the pad/event", 2000, 0, 2000);
         histograms_.create("n_hits", "TrigScint hit multiplicity in the pad/event", 100, 0, 100);
         histograms_.create("x", "Hit x position", 1000, -100, 100);
         histograms_.create("y", "Hit y position", 1000, -100, 100);
         histograms_.create("z", "Hit z position", 1000, -900, 100);
         histograms_.create("pe", "Pe deposition in a TrigScint bar", 1500, 0, 1500);
         histograms_.create("hit_time", "TrigScint hit time (ns)", 1600, -100, 1500);
         histograms_.create("id_noise", "Channel ID of noise hit", 100, 0, 100);
         histograms_.create("pe_noise", "Pe deposition in a TrigScint bar noise hit", 1500, 0, 1500);
         histograms_.create("n_hits_noise", "TrigScint noise hit multiplicity in the pad/event", 100, 0, 100);
         histograms_.create("max_pe:time",
                            "Max Photoelectrons in a TrigScint bar", 1500, 0, 1500,
                            "TrigScint max PE hit time (ns)", 1500, 0, 1500);
         histograms_.create("min_time_hit_above_thresh:pe",
                            "Photoelectrons in a TrigScint bar", 1500, 0, 1500,
                            "Earliest time of TrigScint hit above threshold (ns)", 1600, -100, 1500);
         // TODO: implement getting a list of the constructed histograms, to iterate through and set overflow boolean.
     }
References ldmx::HistogramHelper::create(), ldmx::EventProcessor::getHistoDirectory(), and ldmx::EventProcessor::histograms_.
Member Data Documentation
hitCollectionName_
std::string ldmx::TrigScintHitDQM::hitCollectionName_ {"TriggerPadUpDigiHits"} private
Name of trigger pad hit collection.
Definition at line 57 of file TrigScintHitDQM.h.
Referenced by analyze(), and configure().
The documentation for this class was generated from the following files:
DQM/include/DQM/TrigScintHitDQM.h
DQM/src/TrigScintHitDQM.cxx