LDMX Software: ldmx::BaseTableCondition Class Reference
ldmx::BaseTableCondition Class Reference
Public Member Functions
BaseTableCondition (const std::string &name, const std::vector< std::string > &columns)
unsigned int getColumnNumber (const std::string &colname) const
unsigned int getColumnCount () const
const std::string & getColumnName (unsigned int icol) const
unsigned int getRowId (unsigned int irow) const
const std::vector< std::string > & getColumnNames () const
std::size_t getRowCount () const
Public Member Functions inherited from ldmx::ConditionsObject
ConditionsObject (const std::string &name)
virtual ~ConditionsObject ()
std::string getName () const
Protected Member Functions
std::size_t findKey (unsigned int id) const
std::size_t findKeyInsert (unsigned int id) const
Protected Attributes
std::vector< std::string > columns_
unsigned int columnCount_
std::vector< uint32_t > keys_
Detailed Description
Definition at line 19 of file SimpleTableCondition.h.
Constructor & Destructor Documentation
BaseTableCondition()
ldmx::BaseTableCondition::BaseTableCondition (const std::string & name, const std::vector< std::string > & columns) inline
Create table with given set of columns
Definition at line 24 of file SimpleTableCondition.h.
                                                                                    : ConditionsObject{name}, columns_{columns} {
         columnCount_=(unsigned int)(columns.size());
     }
Member Function Documentation
getColumnCount()
unsigned int ldmx::BaseTableCondition::getColumnCount () const inline
Get the number of columns
Definition at line 40 of file SimpleTableCondition.h.
{
         return columnCount_;
     }
getColumnName()
const std::string& ldmx::BaseTableCondition::getColumnName (unsigned int icol) const inline
Get the name of the given column
Definition at line 47 of file SimpleTableCondition.h.
{
         if (icol>=columnCount_) {
         EXCEPTION_RAISE("ConditionsException",std::string("Column index out of range in ")+getName());
         }
         return columns_[icol];
     }
References ldmx::ConditionsObject::getName().
getColumnNames()
const std::vector<std::string>& ldmx::BaseTableCondition::getColumnNames () const inline
Get the names of the columns
Definition at line 67 of file SimpleTableCondition.h.
{
         return columns_;
     }
getColumnNumber()
unsigned int ldmx::BaseTableCondition::getColumnNumber (const std::string & colname) const inline
Get a the column number for the given column name
Definition at line 31 of file SimpleTableCondition.h.
{
         for (unsigned int i=0; i<columnCount_; i++)
         if (colname==columns_[i]) return i;
         return columnCount_;
     }
Referenced by ldmx::HomogenousTableCondition< int >::getByName(), and ldmx::HgcrocEmulator::getCondition().
getRowCount()
std::size_t ldmx::BaseTableCondition::getRowCount () const inline
Get the number of rows
Definition at line 74 of file SimpleTableCondition.h.
{
         return keys_.size();
     }
Referenced by ldmx::HomogenousTableCondition< int >::add(), ldmx::HomogenousTableCondition< int >::get(), ldmx::HomogenousTableCondition< int >::getRow(), and getRowId().
getRowId()
unsigned int ldmx::BaseTableCondition::getRowId (unsigned int irow) const inline
Get the id for the given row
Definition at line 57 of file SimpleTableCondition.h.
{
         if (irow>=getRowCount()) {// raise exception
         EXCEPTION_RAISE("ConditionsException","Row out of range: "+std::to_string(irow));
         }
         return keys_[irow];
     }
References getRowCount().
The documentation for this class was generated from the following files:
Conditions/include/Conditions/SimpleTableCondition.h
Conditions/src/BaseTableCondition.cxx