LDMX Software: simcore::ScoringPlaneSD Class Reference
simcore::ScoringPlaneSD Class Reference
#include <ScoringPlaneSD.h>
Public Member Functions
ScoringPlaneSD (G4String name, G4String colName, int subDetID)
~ScoringPlaneSD ()
G4bool ProcessHits (G4Step *step, G4TouchableHistory *history)
void Initialize (G4HCofThisEvent *hcEvent)
void EndOfEvent (G4HCofThisEvent *hcEvent)
Private Attributes
G4TrackerHitsCollection * hitsCollection_ {nullptr}
Detailed Description
Class defining a basic sensitive detector for scoring planes.
Definition at line 27 of file ScoringPlaneSD.h.
Constructor & Destructor Documentation
ScoringPlaneSD()
simcore::ScoringPlaneSD::ScoringPlaneSD (G4String name, G4String colName, int subDetID)
Constructor
Parameters
name The name of the sensitive detector.
collectionID The name of the hits collection.
subDetID The subdetector ID.
Definition at line 21 of file ScoringPlaneSD.cxx.
     : G4VSensitiveDetector(name) {
   // Add the collection name to vector of names.
   this->collectionName.push_back(colName);
   // Register this SD with the manager.
   G4SDManager::GetSDMpointer()->AddNewDetector(this);
   // at some point, confirm that the subDetID is as expected...
 }
~ScoringPlaneSD()
simcore::ScoringPlaneSD::~ScoringPlaneSD ()
Destructor
Definition at line 32 of file ScoringPlaneSD.cxx.
 {}
Member Function Documentation
EndOfEvent()
void simcore::ScoringPlaneSD::EndOfEvent (G4HCofThisEvent * hcEvent)
End of event hook.
Parameters
hcEvent The hits collections associated with this event.
Definition at line 104 of file ScoringPlaneSD.cxx.
{
   // Print number of hits.
   if (this->verboseLevel > 0) {
     std::cout << GetName() << " had " << hitsCollection_->entries()
               << " hits in event" << std::endl;
   }
   // Print each hit in hits collection.
   if (this->verboseLevel > 1) {
     for (unsigned iHit = 0; iHit < hitsCollection_->GetSize(); iHit++) {
       (*hitsCollection_)[iHit]->Print();
     }
   }
 }
References hitsCollection_.
Initialize()
void simcore::ScoringPlaneSD::Initialize (G4HCofThisEvent * hcEvent)
Initialize the sensitive detector.
Parameters
hcEvent The hits collections associated with this event.
Definition at line 96 of file ScoringPlaneSD.cxx.
{
   // Setup hits collection and the HC ID.
   hitsCollection_ =
       new G4TrackerHitsCollection(SensitiveDetectorName, collectionName[0]);
   int hcID = G4SDManager::GetSDMpointer()->GetCollectionID(collectionName[0]);
   hce->AddHitsCollection(hcID, hitsCollection_);
 }
References hitsCollection_.
ProcessHits()
G4bool simcore::ScoringPlaneSD::ProcessHits (G4Step * step, G4TouchableHistory * history)
Process a step and create a hit out of it.
Parameters
step The current step.
history The readout history.
Definition at line 34 of file ScoringPlaneSD.cxx.
{
   // Get the edep from the step.
   G4double edep = step->GetTotalEnergyDeposit();
   // Create a new hit object.
   G4TrackerHit* hit = new G4TrackerHit();
   // Assign track ID for finding the SimParticle in post event processing.
   hit->setTrackID(step->GetTrack()->GetTrackID());
   hit->setPdgID(step->GetTrack()->GetDynamicParticle()->GetPDGcode());
   // Set the edep.
   hit->setEdep(edep);
   // Set the start position.
   G4StepPoint* prePoint = step->GetPreStepPoint();
   // Set the end position.
   G4StepPoint* postPoint = step->GetPostStepPoint();
   G4ThreeVector start = prePoint->GetPosition();
   G4ThreeVector end = postPoint->GetPosition();
   // Set the mid position.
   G4ThreeVector mid = 0.5 * (start + end);
   hit->setPosition(mid.x(), mid.y(), mid.z());
   // Compute path length.
   G4double pathLength =
       sqrt(pow(start.x() - end.x(), 2) + pow(start.y() - end.y(), 2) +
            pow(start.z() - end.z(), 2));
   hit->setPathLength(pathLength);
   // Set the global time.
   hit->setTime(step->GetTrack()->GetGlobalTime());
   // Set the momentum
   G4ThreeVector p = postPoint->GetMomentum();
   hit->setMomentum(p.x(), p.y(), p.z());
   hit->setEnergy(postPoint->GetTotalEnergy());
   /*
    * Set the 32-bit ID on the hit.
    */
   int cpNumber = prePoint->GetTouchableHandle()->GetCopyNumber();
   ldmx::SimSpecialID id = ldmx::SimSpecialID::ScoringPlaneID(cpNumber);
   hit->setID(id.raw());
   /*
    * Debug print.
    */
   if (this->verboseLevel > 2) {
     hit->Print();
     std::cout << std::endl;
   }
   // Insert hit into current hits collection.
   hitsCollection_->insert(hit);
   return true;
 }
References hitsCollection_, simcore::G4TrackerHit::Print(), ldmx::SimSpecialID::ScoringPlaneID(), simcore::G4TrackerHit::setEdep(), simcore::G4TrackerHit::setEnergy(), simcore::G4TrackerHit::setID(), simcore::G4TrackerHit::setMomentum(), simcore::G4TrackerHit::setPathLength(), simcore::G4TrackerHit::setPdgID(), simcore::G4TrackerHit::setPosition(), simcore::G4TrackerHit::setTime(), and simcore::G4TrackerHit::setTrackID().
Member Data Documentation
hitsCollection_
G4TrackerHitsCollection* simcore::ScoringPlaneSD::hitsCollection_ {nullptr} private
Output hits collection
Definition at line 65 of file ScoringPlaneSD.h.
Referenced by EndOfEvent(), Initialize(), and ProcessHits().
The documentation for this class was generated from the following files:
SimCore/include/SimCore/ScoringPlaneSD.h
SimCore/src/SimCore/ScoringPlaneSD.cxx