LDMX Software: biasing::utility::DecayChildrenKeeper Class Reference
biasing::utility::DecayChildrenKeeper Class Reference
#include <DecayChildrenKeeper.h>
Public Member Functions
DecayChildrenKeeper (const std::string &name, framework::config::Parameters &parameters)
~DecayChildrenKeeper ()
Destructor.
void PostUserTrackingAction (const G4Track *track) final override
std::vector< simcore::TYPE > getTypes () final override
Retrieve the type of actions this class defines.
Public Member Functions inherited from simcore::UserAction
UserAction (const std::string &name, framework::config::Parameters &parameters)
virtual ~UserAction ()
Destructor.
virtual void BeginOfEventAction (const G4Event *)
virtual void EndOfEventAction (const G4Event *)
virtual void BeginOfRunAction (const G4Run *)
virtual void EndOfRunAction (const G4Run *)
virtual void PreUserTrackingAction (const G4Track *)
virtual void PostUserTrackingAction (const G4Track *)
virtual void stepping (const G4Step *)
virtual G4ClassificationOfNewTrack ClassifyNewTrack (const G4Track *, const G4ClassificationOfNewTrack &cl)
virtual void NewStage ()
virtual void PrepareNewEvent ()
virtual std::vector< TYPE > getTypes ()=0
Private Attributes
std::vector< int > parents_
The PDG IDs for which to keep decay children.
Additional Inherited Members
Static Public Member Functions inherited from simcore::UserAction
static void declare (const std::string &className, UserActionBuilder *builder)
Static Protected Member Functions inherited from simcore::UserAction
static UserEventInformation * getEventInfo ()
Protected Attributes inherited from simcore::UserAction
std::string name_ {""}
Name of the UserAction.
framework::config::Parameters parameters_
The set of parameters used to configure this class.
Detailed Description
Filter to keep tracks that are the products of certain particle's decays.
Note
It is important to emphasize that this filter is only able to persist products of particles that are themselves kept. i.e. Another action needs to keep the parent particle and then this action will save that particle's children.
Definition at line 27 of file DecayChildrenKeeper.h.
Constructor & Destructor Documentation
DecayChildrenKeeper()
biasing::utility::DecayChildrenKeeper::DecayChildrenKeeper (const std::string & name, framework::config::Parameters & parameters)
Constructor.
Parameters
[in] name the name of the instance of this UserAction.
[in] parameters the parameters used to configure this UserAction.
Definition at line 18 of file DecayChildrenKeeper.cxx.
    : simcore::UserAction(name, parameters) {
  parents_ = parameters.getParameter<std::vector<int>>("parents");
}
References framework::config::Parameters::getParameter(), and parents_.
~DecayChildrenKeeper()
biasing::utility::DecayChildrenKeeper::~DecayChildrenKeeper ()
Destructor.
Definition at line 24 of file DecayChildrenKeeper.cxx.
{}
Member Function Documentation
getTypes()
std::vector< simcore::TYPE > biasing::utility::DecayChildrenKeeper::getTypes () inline final override virtual
Retrieve the type of actions this class defines.
Implements simcore::UserAction.
Definition at line 60 of file DecayChildrenKeeper.h.
{
    return {simcore::TYPE::TRACKING};
  }
PostUserTrackingAction()
void biasing::utility::DecayChildrenKeeper::PostUserTrackingAction (const G4Track * track) final override virtual
Method called when a track is done being processed.
We get the stored particle map from the TrackMap object and look for the current track's parent in it. If the current track's parent is in it THEN we check if that parent has a PDG matching ANY of the configured PDGs.
Note
Techinically, we can check for children of any particle that has finished processing (and is therefore in the stored particle map), but I focus here on "decays" because that is the only one where the parent is definitely at the end of processing.
Parameters
[in] track Geant4 track associated with a particle.
Reimplemented from simcore::UserAction.
Definition at line 26 of file DecayChildrenKeeper.cxx.
{
  const auto& particle_map{
    simcore::UserTrackingAction::getUserTrackingAction()->getTrackMap()->getParticleMap()};
  if (particle_map.find(track->GetParentID()) != particle_map.end()) {
    const int& parent_pdg{particle_map.at(track->GetParentID()).getPdgID()};
    for (const int& parent : parents_) {
      if (parent_pdg == parent) {
        simcore::UserTrackInformation::get(track)->setSaveFlag(true);
        break;
      } //parent is an interesting one
    } // loop through interesting parent options
  } // parent is in particle map
}
References simcore::UserTrackInformation::get(), simcore::TrackMap::getParticleMap(), simcore::UserTrackingAction::getTrackMap(), simcore::UserTrackingAction::getUserTrackingAction(), parents_, and simcore::UserTrackInformation::setSaveFlag().
Member Data Documentation
parents_
std::vector<int> biasing::utility::DecayChildrenKeeper::parents_ private
The PDG IDs for which to keep decay children.
Definition at line 66 of file DecayChildrenKeeper.h.
Referenced by DecayChildrenKeeper(), and PostUserTrackingAction().
The documentation for this class was generated from the following files:
Biasing/include/Biasing/Utility/DecayChildrenKeeper.h
Biasing/src/Biasing/Utility/DecayChildrenKeeper.cxx