LDMX Software: hcal::HcalDetectorMap Class Reference
hcal::HcalDetectorMap Class Reference
Class which provides various information about how the parts of the Hcal connect to each other.
#include <HcalDetectorMap.h>
Public Member Functions
HcalDetectorMap (const std::string &connections_table, bool want_d2e)
Public Member Functions inherited from framework::ConditionsObject
ConditionsObject (const std::string &name)
virtual ~ConditionsObject ()
std::string getName () const
Public Member Functions inherited from ldmx::ElectronicsMap< ldmx::HcalElectronicsID, ldmx::HcalDigiID >
ElectronicsMap (bool want_d2e=false)
void clear ()
void addEntry (ldmx::HcalElectronicsID eid, ldmx::HcalDigiID did)
bool exists (ldmx::HcalElectronicsID eid) const
bool exists (ldmx::HcalDigiID did) const
ldmx::HcalDigiID get (ldmx::HcalElectronicsID eid) const
ldmx::HcalElectronicsID get (ldmx::HcalDigiID did) const
Static Public Attributes
static constexpr const char * CONDITIONS_OBJECT_NAME {"HcalDetectorMap"}
The name of the EID <-> DetID map for the ECal.
Friends
class HcalDetectorMapLoader
Provider which loads the map.
Detailed Description
Class which provides various information about how the parts of the Hcal connect to each other.
The class is loaded from a single connection table, currently in the form of a CSV file, using the HcalDetectorMapLoader declared and defined in the source.
We inherit from two classes: (1) the ConditionsObject because we are a conditions object and (2) from the ElectronicsMap template because we are a electronics map.
Definition at line 32 of file HcalDetectorMap.h.
Constructor & Destructor Documentation
HcalDetectorMap()
hcal::HcalDetectorMap::HcalDetectorMap (const std::string & connections_table, bool want_d2e)
Default constructor which builds the necessary maps.
Parameters
[in] want_d2e true if we want to build a reverse mapping Building a reverse (detector->electronics) map takes extra time and memory so it should be off by default.
Column Names "Polarfire" "HGCROC" "Channel" "CMB" "Quadbar" "Bar" "Plane" "Cable"
Each HGCROC has two links coming out of it, one for the upper half of the channels and one for the lower half, this means we need to modify the hgcroc/channel pair to be actual link/channel pairs where the new link has range twice as big as the hgcroc ID but the new channel has a range half as big as the old one.
each hgcroc has two links,
one for the upper half of channels (36-71)
one for the lower half (0-35)
we assign the links' number based on the hgcroc ID so that the link count starts from 0 and the two links for one hgcroc ID are next to each other. The upper half of channels are given the higher link number.
the Hcal skips every 9th channel because those are the channels that are skipped in the trigger sum when the chip is summing 4 channels together
Skipped: 8, 17, 26, 35, 44, 53, 62, 71
without zero suppresssion then, this means some channels will appear in the raw data but will not be in the detector mapping so they should be skipped
Definition at line 46 of file HcalDetectorMap.cxx.
    : framework::ConditionsObject(CONDITIONS_OBJECT_NAME),
      ldmx::ElectronicsMap<ldmx::HcalElectronicsID, ldmx::HcalDigiID>(want_d2e) {
  this->clear();
  conditions::StreamCSVLoader csv(connections_table);
  while (csv.nextRow()) {
    int polarfire = csv.getInteger("Polarfire");
    int hgcroc = csv.getInteger("HGCROC");
    int chan   = csv.getInteger("Channel");
    int link = 2*hgcroc; // link count starts from 0
    if (chan >= 36) {
      link += 1;
      chan -= 36;
    }
    // one quadbar groups 4 strips and each quadbar is connected to 2 CMBs - one in each end
    int end = csv.getInteger("CMB")%2;
    if(end==0) end=1; // negative end (?)
    else end=0; // positive end (?)
    // The Bar field in the map represents a numbering *within a quadbar* not
    // the strip number.
    //
    // This gives correct range for the strip numbers [0,7] and [0,11] but the
    // actual order of the quadbars has to be checked
    auto QuadBar {csv.getInteger("QuadBar")};
    auto BarNumber {csv.getInteger("Bar")};
    // Strip = (4 - Bar) + 4 * (QuadBar - 1)
    // QuadBar starts at 1 so we need to subtract to get first value
    // to be zero
    auto strip { (BarNumber - 1) + 4 * (QuadBar - 1)}; //This is flipped from the original
    if(csv.getInteger("Plane")%2 == 1) strip = (4 - BarNumber) + 4 * (QuadBar - 1); //Plane 2 is backward by mistake
    ldmx::HcalDigiID detid(0 /*section - only one section during test beam*/,
        csv.getInteger("Plane") /*layer*/,
        strip                   /*strip*/,
        end /*end*/);
    ldmx::HcalElectronicsID eleid(
        polarfire /*polarfire fpga*/,
        link /*elink*/,
        chan /*channel*/);
    if (this->exists(eleid)) {
      std::stringstream ss;
      ss << "Two different mappings for electronics channel " << eleid;
      EXCEPTION_RAISE("DuplicateMapping", ss.str());
    }
    this->addEntry(eleid, detid);
  }
}
References ldmx::ElectronicsMap< ldmx::HcalElectronicsID, ldmx::HcalDigiID >::addEntry(), ldmx::ElectronicsMap< ldmx::HcalElectronicsID, ldmx::HcalDigiID >::clear(), ldmx::ElectronicsMap< ldmx::HcalElectronicsID, ldmx::HcalDigiID >::exists(), conditions::GeneralCSVLoader::getInteger(), and conditions::GeneralCSVLoader::nextRow().
Friends And Related Function Documentation
HcalDetectorMapLoader
friend class HcalDetectorMapLoader friend
Provider which loads the map.
Definition at line 49 of file HcalDetectorMap.h.
Member Data Documentation
CONDITIONS_OBJECT_NAME
constexpr const char* hcal::HcalDetectorMap::CONDITIONS_OBJECT_NAME {"HcalDetectorMap"} static constexpr
The name of the EID <-> DetID map for the ECal.
Definition at line 37 of file HcalDetectorMap.h.
Referenced by hcal::HcalRawDecoder::produce().
The documentation for this class was generated from the following files:
Hcal/include/Hcal/HcalDetectorMap.h
Hcal/src/Hcal/HcalDetectorMap.cxx