LDMX Software: simcore::GammaPhysics Class Reference
simcore::GammaPhysics Class Reference
Public Member Functions
GammaPhysics (const G4String &name, const framework::config::Parameters &parameters)
GammaPhysics (const G4String &name="GammaPhysics")
virtual ~GammaPhysics ()=default
void ConstructParticle ()
void ConstructProcess ()
void SetPhotonNuclearAsFirstProcess () const
Private Member Functions
G4ProcessManager * GetGammaProcessManager () const
Private Attributes
G4GammaConversionToMuons gammaConvProcess
framework::config::Parameters modelParameters
Detailed Description
extra gamma particle physics for simulation and sets up the photonuclear model to use from the configuration
Note
Is responsible for selecting the photonuclear model from the python configuration. Currently adds gamma -> mumu reaction using the G4GammaConversionToMuons process. Also changes ordering of gamma processes such that photonNuclear and GammaToMuMu are called first.
Definition at line 33 of file GammaPhysics.h.
Constructor & Destructor Documentation
GammaPhysics()
simcore::GammaPhysics::GammaPhysics (const G4String & name, const framework::config::Parameters & parameters) inline
Class constructor.
Parameters
name The name of the physics.
parameters The python configuration
Definition at line 40 of file GammaPhysics.h.
      : G4VPhysicsConstructor(name),
        modelParameters{parameters.getParameter<framework::config::Parameters>(
            "photonuclear_model")} {}
~GammaPhysics()
virtual simcore::GammaPhysics::~GammaPhysics () virtual default
Class destructor.
Member Function Documentation
ConstructParticle()
void simcore::GammaPhysics::ConstructParticle () inline
Construct particles (no-op).
Definition at line 55 of file GammaPhysics.h.
{}
ConstructProcess()
void simcore::GammaPhysics::ConstructProcess ()
Construct the process (gamma to muons).
Definition at line 56 of file GammaPhysics.cxx.
{
  G4ProcessManager* processManager = GetGammaProcessManager();
  auto pn = PhotoNuclearModel::Factory::get().make(
      modelParameters.getParameter<std::string>("class_name"),
      modelParameters.getParameter<std::string>("instance_name"),
      modelParameters);
  pn->removeExistingModel(processManager);
  pn->ConstructGammaProcess(processManager);
  SetPhotonNuclearAsFirstProcess();
  // Add the gamma -> mumu to the physics list.
  processManager->AddDiscreteProcess(&gammaConvProcess);
}
References gammaConvProcess, simcore::Factory< Prototype, PrototypePtr, PrototypeConstructorArgs >::get(), GetGammaProcessManager(), framework::config::Parameters::getParameter(), simcore::Factory< Prototype, PrototypePtr, PrototypeConstructorArgs >::make(), modelParameters, and SetPhotonNuclearAsFirstProcess().
GetGammaProcessManager()
G4ProcessManager * simcore::GammaPhysics::GetGammaProcessManager () const private
Not entirely clear that there isn't a simpler way to do this, but to keep this function extraction to a pure refactoring, I'm leaving it here for now. /Einar
Definition at line 21 of file GammaPhysics.cxx.
{
  aParticleIterator->reset();
  // Loop through all of the particles and find the "gamma".
  while ((*aParticleIterator)()) {
    auto particle{aParticleIterator->value()};
    auto particleName{particle->GetParticleName()};
    if (particleName == "gamma") {
      return particle->GetProcessManager();
    }
  }
  EXCEPTION_RAISE("GammaPhysics",
                  "Was unable to access the process manager for photons, "
                  "something is very wrong!");
}
Referenced by ConstructProcess(), and SetPhotonNuclearAsFirstProcess().
SetPhotonNuclearAsFirstProcess()
void simcore::GammaPhysics::SetPhotonNuclearAsFirstProcess () const
Search the list for the process "photoNuclear". When found, change the calling order so photonNuclear is called before EM processes. The biasing operator needs the photonNuclear process to be called first because the cross-section is needed to bias down other process.
Definition at line 42 of file GammaPhysics.cxx.
{
  auto processManager{GetGammaProcessManager()};
  // Get the process list associated with the gamma.
  const auto processes{processManager->GetProcessList()};
  for (int i{0}; i < processes->size(); ++i) {
    const auto process{(*processes)[i]};
    const auto processName{process->GetProcessName()};
    if (processName == "photonNuclear") {
      processManager->SetProcessOrderingToFirst(
          process, G4ProcessVectorDoItIndex::idxAll);
    }
  }
}
References GetGammaProcessManager().
Referenced by ConstructProcess().
Member Data Documentation
gammaConvProcess
G4GammaConversionToMuons simcore::GammaPhysics::gammaConvProcess private
The gamma to muons process.
Definition at line 80 of file GammaPhysics.h.
Referenced by ConstructProcess().
modelParameters
framework::config::Parameters simcore::GammaPhysics::modelParameters private
Parameters from the configuration to pass along to the photonuclear model.
Definition at line 84 of file GammaPhysics.h.
Referenced by ConstructProcess().
The documentation for this class was generated from the following files:
SimCore/include/SimCore/GammaPhysics.h
SimCore/src/SimCore/GammaPhysics.cxx