LDMX Software: simcore::VisAttributesStore Class Reference
simcore::VisAttributesStore Class Reference
Global store of G4VisAttributes created from GDML data.
#include <VisAttributesStore.h>
Public Types
typedef std::map< std::string, G4VisAttributes * > VisAttributesMap
Public Member Functions
~VisAttributesStore ()
G4VisAttributes * getVisAttributes (const std::string &name)
void addVisAttributes (const std::string &name, G4VisAttributes *visAttributes)
Static Public Member Functions
static VisAttributesStore * getInstance ()
Private Attributes
VisAttributesMap visAttributesMap_
Detailed Description
Global store of G4VisAttributes created from GDML data.
Definition at line 19 of file VisAttributesStore.h.
Member Typedef Documentation
VisAttributesMap
typedef std::map<std::string, G4VisAttributes*> simcore::VisAttributesStore::VisAttributesMap
Map of name to vis attributes.
Definition at line 24 of file VisAttributesStore.h.
Constructor & Destructor Documentation
~VisAttributesStore()
simcore::VisAttributesStore::~VisAttributesStore () inline
Destructor
Cleans up G4VisAttributes
Definition at line 40 of file VisAttributesStore.h.
{
    for (auto& nameAtt : visAttributesMap_) {
      delete nameAtt.second;
    }
    visAttributesMap_.clear();
  }
References visAttributesMap_.
Member Function Documentation
addVisAttributes()
void simcore::VisAttributesStore::addVisAttributes (const std::string & name, G4VisAttributes * visAttributes) inline
Register a vis attributes by name.
Parameters
name The name of the vis attributes.
visAttributes The vis attributes to register.
Definition at line 66 of file VisAttributesStore.h.
{
    visAttributesMap_[name] = visAttributes;
  }
References visAttributesMap_.
Referenced by simcore::geo::AuxInfoReader::createVisAttributes().
getInstance()
static VisAttributesStore * simcore::VisAttributesStore::getInstance () inline static
Get the global instance of the store.
Returns
The vis attributes store.
Definition at line 30 of file VisAttributesStore.h.
{
    static VisAttributesStore INSTANCE;
    return &INSTANCE;
  }
Referenced by simcore::geo::AuxInfoReader::assignAuxInfoToVolumes(), and simcore::geo::AuxInfoReader::createVisAttributes().
getVisAttributes()
G4VisAttributes * simcore::VisAttributesStore::getVisAttributes (const std::string & name) inline
Get vis attributes by name.
Parameters
name The name of the vis attributes.
Returns
The vis attributes or nullptr if does not exist.
Definition at line 52 of file VisAttributesStore.h.
{
    try {
      return visAttributesMap_.at(name);
    } catch (const std::out_of_range& oor) {
      G4cout << "[ WARN ] : VisAttribute '" << name
        << "' not recognized. Ignoring." << G4endl;
    }
  }
References visAttributesMap_.
Referenced by simcore::geo::AuxInfoReader::assignAuxInfoToVolumes().
Member Data Documentation
visAttributesMap_
VisAttributesMap simcore::VisAttributesStore::visAttributesMap_ private
The map of names to vis attributes.
Definition at line 75 of file VisAttributesStore.h.
Referenced by addVisAttributes(), getVisAttributes(), and ~VisAttributesStore().
The documentation for this class was generated from the following file:
SimCore/include/SimCore/VisAttributesStore.h