LDMX Software: simcore::TrackerSD Class Reference
simcore::TrackerSD Class Reference
Basic sensitive detector for trackers.
#include <TrackerSD.h>
Public Member Functions
TrackerSD (G4String name, G4String collectionName, int subDetID)
~TrackerSD ()
Destructor.
G4bool ProcessHits (G4Step *step, G4TouchableHistory *history)
void Initialize (G4HCofThisEvent *hcEvent)
void EndOfEvent (G4HCofThisEvent *hcEvent)
Private Attributes
G4TrackerHitsCollection * hitsCollection_
The output hits collection of G4TrackerHits.
ldmx::SubdetectorIDType subDetID_
The detector ID.
Detailed Description
Basic sensitive detector for trackers.
Note
This class creates a G4TrackerHit for each step within the subdetector.
Definition at line 28 of file TrackerSD.h.
Constructor & Destructor Documentation
TrackerSD()
simcore::TrackerSD::TrackerSD (G4String name, G4String collectionName, int subDetID)
Class constructor.
Parameters
[in] name The name of the sensitive detector.
[in] collectionName The name of the hits collection.
[in] subDetID The subdetector ID.
Definition at line 18 of file TrackerSD.cxx.
    : G4VSensitiveDetector(name), hitsCollection_(0) {
  // Add the collection name to vector of names.
  this->collectionName.push_back(theCollectionName);
  // Register this SD with the manager.
  G4SDManager::GetSDMpointer()->AddNewDetector(this);
  // Set the subdet ID as it will always be the same for every hit.
  subDetID_ = ldmx::SubdetectorIDType(subDetID);
}
References subDetID_.
~TrackerSD()
simcore::TrackerSD::~TrackerSD ()
Destructor.
Definition at line 30 of file TrackerSD.cxx.
{}
Member Function Documentation
EndOfEvent()
void simcore::TrackerSD::EndOfEvent (G4HCofThisEvent * hcEvent)
End of event hook.
Parameters
hcEvent The hits collections of the event.
Definition at line 136 of file TrackerSD.cxx.
{
  // Print number of hits.
  if (this->verboseLevel > 0) {
    std::cout << GetName() << " had " << hitsCollection_->entries()
              << " hits in event" << std::endl;
  }
  // Print each hit in hits collection.
  if (this->verboseLevel > 1) {
    for (unsigned iHit = 0; iHit < hitsCollection_->GetSize(); iHit++) {
      (*hitsCollection_)[iHit]->Print();
    }
  }
}
References hitsCollection_.
Initialize()
void simcore::TrackerSD::Initialize (G4HCofThisEvent * hcEvent)
Initialize the sensitive detector.
Parameters
hcEvent The hits collections of the event.
Definition at line 128 of file TrackerSD.cxx.
{
  // Setup hits collection and the HC ID.
  hitsCollection_ =
      new G4TrackerHitsCollection(SensitiveDetectorName, collectionName[0]);
  int hcID = G4SDManager::GetSDMpointer()->GetCollectionID(collectionName[0]);
  hce->AddHitsCollection(hcID, hitsCollection_);
}
References hitsCollection_.
ProcessHits()
G4bool simcore::TrackerSD::ProcessHits (G4Step * step, G4TouchableHistory * history)
Process a step by creating a hit.
Parameters
step The step information
history The readout history.
Definition at line 32 of file TrackerSD.cxx.
{
  // Determine if current particle of this step is a Geantino.
  G4ParticleDefinition* pdef = aStep->GetTrack()->GetDefinition();
  bool isGeantino = false;
  if (pdef == G4Geantino::Definition() ||
      pdef == G4ChargedGeantino::Definition()) {
    isGeantino = true;
  }
  // Get the edep from the step.
  G4double edep = aStep->GetTotalEnergyDeposit();
  // Skip steps with no energy dep which come from non-Geantino particles.
  if (edep == 0.0 && !isGeantino) {
    if (verboseLevel > 2) {
      std::cout << "TrackerSD skipping step with zero edep" << std::endl
                << std::endl;
    }
    return false;
  }
  // Create a new hit object.
  G4TrackerHit* hit = new G4TrackerHit();
  // Assign track ID for finding the SimParticle in post event processing.
  hit->setTrackID(aStep->GetTrack()->GetTrackID());
  // Set the edep.
  hit->setEdep(edep);
  // Set the start position.
  G4StepPoint* prePoint = aStep->GetPreStepPoint();
  // hit->setStartPosition(prePoint->GetPosition());
  // Set the end position.
  G4StepPoint* postPoint = aStep->GetPostStepPoint();
  // hit->setEndPosition(postPoint->GetPosition());
  G4ThreeVector start = prePoint->GetPosition();
  G4ThreeVector end = postPoint->GetPosition();
  // Set the mid position.
  G4ThreeVector mid = 0.5 * (start + end);
  hit->setPosition(mid.x(), mid.y(), mid.z());
  // Compute path length.
  G4double pathLength =
      sqrt(pow(start.x() - end.x(), 2) + pow(start.y() - end.y(), 2) +
           pow(start.z() - end.z(), 2));
  hit->setPathLength(pathLength);
  // Set the global time.
  hit->setTime(aStep->GetTrack()->GetGlobalTime());
  /*
   * Compute and set the momentum.
   */
  /*
   double mag = (prePoint->GetMomentum().mag() + postPoint->GetMomentum().mag())
   / 2; G4ThreeVector p = (postPoint->GetPosition() - prePoint->GetPosition());
   if (mag > 0) {
   p.setMag(mag);
   }
   */
  G4ThreeVector p = postPoint->GetMomentum();
  hit->setMomentum(p.x(), p.y(), p.z());
  /*
   * Set the 32-bit ID on the hit.
   */
  int copyNum =
      prePoint->GetTouchableHandle()->GetHistory()->GetVolume(2)->GetCopyNo();
  int layer = copyNum / 10;
  int module = copyNum % 10;
  ldmx::TrackerID id(subDetID_, layer, module);
  hit->setID(id.raw());
  hit->setLayerID(layer);
  hit->setModuleID(module);
  // Set energy and pdg code of SimParticle (common things requested)
  hit->setEnergy(postPoint->GetTotalEnergy());
  hit->setPdgID(aStep->GetTrack()->GetDynamicParticle()->GetPDGcode());
  /*
   * Debug print.
   */
  if (this->verboseLevel > 2) {
    hit->Print();
  }
  // Insert hit into current hits collection.
  hitsCollection_->insert(hit);
  return true;
}
References hitsCollection_, simcore::G4TrackerHit::Print(), simcore::G4TrackerHit::setEdep(), simcore::G4TrackerHit::setEnergy(), simcore::G4TrackerHit::setID(), simcore::G4TrackerHit::setLayerID(), simcore::G4TrackerHit::setModuleID(), simcore::G4TrackerHit::setMomentum(), simcore::G4TrackerHit::setPathLength(), simcore::G4TrackerHit::setPdgID(), simcore::G4TrackerHit::setPosition(), simcore::G4TrackerHit::setTime(), simcore::G4TrackerHit::setTrackID(), and subDetID_.
Member Data Documentation
hitsCollection_
G4TrackerHitsCollection* simcore::TrackerSD::hitsCollection_ private
The output hits collection of G4TrackerHits.
Definition at line 63 of file TrackerSD.h.
Referenced by EndOfEvent(), Initialize(), and ProcessHits().
subDetID_
ldmx::SubdetectorIDType simcore::TrackerSD::subDetID_ private
The detector ID.
Definition at line 66 of file TrackerSD.h.
Referenced by ProcessHits(), and TrackerSD().
The documentation for this class was generated from the following files:
SimCore/include/SimCore/TrackerSD.h
SimCore/src/SimCore/TrackerSD.cxx