LDMX Software: ldmx::Event Class Reference
ldmx::Event Class Reference
Implements an event buffer system for storing event data.
#include <Event.h>
Classes
class clearPassenger
class printPassenger
class sortPassenger
Public Member Functions
Event (const std::string &passName)
~Event ()
EventHeader & getEventHeader ()
int getEventNumber () const
double getEventWeight () const
void Print (int verbosity) const
bool exists (const std::string &name) const
bool exists (const std::string &name, const std::string &passName) const
void addDrop (const std::string &exp)
template<typename T >
void add (const std::string &collectionName, T &obj)
std::vector< ProductTag > searchProducts (const std::string &namematch, const std::string &passmatch, const std::string &typematch) const
template<typename T >
const T getObject (const std::string &collectionName, const std::string &passName) const
template<typename T >
const T getObject (const std::string &collectionName) const
template<typename T >
const std::vector< T > getCollection (const std::string &collectionName, const std::string &passName) const
template<typename T >
const std::vector< T > getCollection (const std::string &collectionName) const
template<typename Key , typename Val >
const std::map< Key, Val > getMap (const std::string &collectionName, const std::string &passName) const
template<typename Key , typename Val >
const std::map< Key, Val > getMap (const std::string &collectionName) const
void setInputTree (TTree *tree)
void setOutputTree (TTree *tree)
TTree * createTree ()
std::string makeBranchName (const std::string &collectionName, const std::string &passName) const
std::string makeBranchName (const std::string &collectionName) const
const std::vector< ProductTag > & getProducts () const
bool nextEvent ()
void beforeFill ()
void Clear ()
void onEndOfEvent ()
void onEndOfFile ()
std::string getPassName ()
Protected Member Functions
template<typename T >
T getImpl (const std::string &collectionName, const std::string &passName) const
Private Member Functions
bool shouldDrop (const std::string &collName) const
Private Attributes
EventHeader eventHeader_
Long64_t entries_ {-1}
Long64_t ientry_ {-1}
std::string passName_
TTree * outputTree_ {nullptr}
TTree * inputTree_ {nullptr}
std::map< std::string, TBranchElement * > branches_
std::map< std::string, EventBusPassenger > passengers_
std::vector< TBranchElement * > newBranches_
std::vector< std::string > branchNames_
std::set< std::string > branchesFilled_
std::vector< regex_t > regexDropCollections_
std::map< std::string, std::string > knownLookups_
std::vector< ProductTag > products_
Detailed Description
Implements an event buffer system for storing event data.
Note
Event data is stored in ROOT trees and branches, which can be added on the fly.
Definition at line 38 of file Event.h.
Constructor & Destructor Documentation
Event()
ldmx::Event::Event (const std::string & passName)
Class constructor.
Parameters
passName The default pass name for adding event data.
Definition at line 5 of file Event.cxx.
 : passName_(thePassName) { }
~Event()
ldmx::Event::~Event ()
Class destructor.
Definition at line 7 of file Event.cxx.
                   {
         for ( regex_t &reg : regexDropCollections_ ) {
             regfree( &reg );
         }
     }
References regexDropCollections_.
Member Function Documentation
add()
template<typename T > void ldmx::Event::add (const std::string & collectionName, T & obj) inline
Adds an object to the event bus
Parameters
collectionName
obj in ROOT dictionary to add
Definition at line 126 of file Event.h.
{
                 if (collectionName.find('_') != std::string::npos) {
                     EXCEPTION_RAISE(
                             "IllegalName",
                             "The product name '"
                             + collectionName
                             + "' is illegal as it contains an underscore.");
                 }
                 std::string branchName;
                 if (collectionName== EventConstants::EVENT_HEADER) branchName=collectionName;
                 else branchName = makeBranchName(collectionName);
                 if (branchesFilled_.find(branchName) != branchesFilled_.end()) {
                     EXCEPTION_RAISE(
                             "ProductExists",
                             "A product named '"
                             + collectionName
                             + "' already exists in the event (has been loaded by a previous producer in this process)."
                             );
                 }
                 branchesFilled_.insert(branchName);
                 //MEMORY add is leaking memory when given a vector (possible upon destruction of Event?)
                 //MEMORY add is 'conditional jump or move depends on uninitialised values' for all types of objects
                 //  TTree::BranchImpRef or TTree::BronchExec
                 if (passengers_.find(branchName) == passengers_.end()) {
                     // create a new branch for this collection
                     //TODO check if input type is listed as an EventBusPassenger?
                     passengers_[branchName] = EventBusPassenger( obj );
                     T *passengerAddress = std::get_if<T>(&passengers_[branchName]);
                     std::string tname = typeid(obj).name();//type name (want to use branch element if possible)
                     if (outputTree_ != 0 and not shouldDrop( branchName ) ) {
                         TBranchElement *outBranch = dynamic_cast<TBranchElement *>(outputTree_->GetBranch( branchName.c_str() ));
                         if ( outBranch ) {
                             //branch already exists, just reset branch object
                             outBranch->SetObject( passengerAddress );
                         } else {
                             //branch doesnt exist, make new one
                             outBranch = dynamic_cast<TBranchElement*>(outputTree_->Branch( branchName.c_str(), passengerAddress , 100000, 3));
                         }
                         newBranches_.push_back(outBranch);
                         //get type name from branch if possible, otherwise use compiler level type name (above)
                         tname = outBranch->GetClassName();
                     } //output tree exists or not
                     products_.emplace_back(collectionName,passName_,tname);
                     branchNames_.push_back(branchName);
                     knownLookups_.clear(); // have to invalidate this cache
                 }
                 //copy input contents into bus passenger
                 EventBusPassenger toAdd( obj );
                 if ( toAdd.index() == passengers_[branchName].index() ) {
                     std::visit( sortPassenger() , toAdd ); //sort before copying over
                     passengers_[branchName] = toAdd;
                 } else {
                     EXCEPTION_RAISE(
                             "TypeMismatch",
                             "Attempting to add an object whose type '"
                             + std::string(typeid(obj).name())
                             + "' doesn't match the type stored in the collection."
                             );
                 }
                 return;
             }
References branchesFilled_, branchNames_, knownLookups_, makeBranchName(), newBranches_, outputTree_, passengers_, passName_, products_, and shouldDrop().
Referenced by beforeFill(), ldmx::SimParticleBuilder::buildSimParticles(), TEST_CASE(), and ldmx::RootPersistencyManager::writeHitsCollections().
addDrop()
void ldmx::Event::addDrop (const std::string & exp)
Add a drop rule to the list of regex expressions to drop.
If a collection name matches one of the stored regex expressions, it will be stored as a passenger but not added to output tree.
Parameters
exp regex to match
Definition at line 20 of file Event.cxx.
{
         regex_t reg;
         if (!regcomp(&reg,exp.c_str(),REG_EXTENDED|REG_ICASE|REG_NOSUB)) {
             regexDropCollections_.push_back( reg );
         } else {
             EXCEPTION_RAISE(
                     "InvalidRegex",
                     "The passed drop rule regex '"
                     + exp
                     + "' is not a valid regex."
                     );
         }
     }
References regexDropCollections_.
Referenced by ldmx::EventFile::addDrop().
beforeFill()
void ldmx::Event::beforeFill ()
Action to be executed before the tree is filled.
Definition at line 128 of file Event.cxx.
{
         if (inputTree_==0 && branchesFilled_.find(EventConstants::EVENT_HEADER)==branchesFilled_.end()) {
             //Event Header not copied from input and hasn't been added yet, need to put it in
             add(EventConstants::EVENT_HEADER, eventHeader_);
         }
     }
References add(), branchesFilled_, eventHeader_, and inputTree_.
Referenced by ldmx::EventFile::nextEvent().
Clear()
void ldmx::Event::Clear ()
Clear this object's data (including passengers).
Definition at line 135 of file Event.cxx.
                       {
         // clear the event objects
         branchesFilled_.clear();
         for ( auto passenger : passengers_ ) {
             std::visit( clearPassenger() , passenger.second );
         }
     }
References branchesFilled_, and passengers_.
Referenced by ldmx::EventFile::nextEvent(), and ldmx::Process::run().
createTree()
TTree * ldmx::Event::createTree ()
Create the output data tree.
Returns
The output data tree.
Definition at line 82 of file Event.cxx.
{
         outputTree_ = new TTree("LDMX_Events", "LDMX Events");
         return outputTree_;
     }
References outputTree_.
Referenced by ldmx::EventFile::setupEvent().
exists() [1/2]
bool ldmx::Event::exists (const std::string & name) const inline
Check the existence of one-and-only-one object with the given name (excluding the pass) in the event.
Parameters
name Name (label, not class name) given to the object when it was put into the event.
Returns
True if the object or collection exists in the event.
Definition at line 95 of file Event.h.
{
                 return exists( name , "" );
             }
Referenced by ldmx::HCalDQM::analyze(), ldmx::TrigScintHitDQM::analyze(), ldmx::RecoilTrackerDQM::analyze(), ldmx::TrigScintDQM::analyze(), ldmx::TrackerVetoProcessor::produce(), ldmx::MyProcessor::produce(), and ldmx::EcalVetoProcessor::produce().
exists() [2/2]
bool ldmx::Event::exists (const std::string & name, const std::string & passName) const inline
Check for the existence of an object or collection with the given name and pass name in the event.
Parameters
name Name (label, not class name) given to the object when it was put into the event.
passName The process pass label which was in use when this object was put into the event, such as "sim" or "rerecov2".
Returns
True if the object or collection uniquely exists in the event.
Definition at line 106 of file Event.h.
{
                 return ( searchProducts( name , passName , "" ).size() == 1 );
             }
References searchProducts().
getCollection() [1/2]
template<typename T > const std::vector<T> ldmx::Event::getCollection (const std::string & collectionName) const inline
Get a collection (std::vector) of objects from the event bus when you don't care about the pass
Definition at line 229 of file Event.h.
{
                 return getCollection<T>( collectionName , "" );
             }
getCollection() [2/2]
template<typename T > const std::vector<T> ldmx::Event::getCollection (const std::string & collectionName, const std::string & passName) const inline
Get a collection (std::vector) of objects from the event bus
Definition at line 221 of file Event.h.
{
                 return getObject< std::vector<T> >( collectionName , passName );
             }
Referenced by ldmx::RootSimFromEcalSP::GeneratePrimaryVertex(), and TEST_CASE().
getEventHeader()
EventHeader& ldmx::Event::getEventHeader () inline
Get the event header.
Returns
A reference to the event header.
Definition at line 57 of file Event.h.
{
                 return eventHeader_;
             }
References eventHeader_.
Referenced by ldmx::RootCompleteReSim::GeneratePrimaryVertex(), ldmx::RootSimFromEcalSP::GeneratePrimaryVertex(), ldmx::Simulator::produce(), ldmx::Process::run(), and ldmx::RootPersistencyManager::writeHeader().
getEventNumber()
int ldmx::Event::getEventNumber () const inline
Get the event number.
Returns
the event index/number
Definition at line 65 of file Event.h.
{
                 return eventHeader_.getEventNumber();
             }
References eventHeader_, and ldmx::EventHeader::getEventNumber().
getEventWeight()
double ldmx::Event::getEventWeight () const inline
Get the event weight
Returns
weight from the EventHeader
Definition at line 73 of file Event.h.
{
                 return eventHeader_.getWeight();
             }
References eventHeader_, and ldmx::EventHeader::getWeight().
getImpl()
template<typename T > T ldmx::Event::getImpl (const std::string & collectionName, const std::string & passName) const inline protected
Get an event passenger from the event bus (actual implementation)
Parameters
collectionName name of collection you want
passName name of pass you want
Definition at line 257 of file Event.h.
{
                 //get branch name
                 std::string branchName;
                 if (collectionName== EventConstants::EVENT_HEADER) branchName=collectionName;
                 else branchName = makeBranchName(collectionName, passName);
                 //if no passName, then find branchName by looking over known branches
                 if (passName.empty() && collectionName!= EventConstants::EVENT_HEADER) {
                     auto itKL = knownLookups_.find(collectionName);
                     if (itKL!=knownLookups_.end()) branchName=itKL->second;
                     else {
                         //this collecitonName hasn't been found before
                         std::vector<std::vector<std::string>::const_iterator> matches;
                         branchName=collectionName+"_";
                         for (auto itBN=branchNames_.begin(); itBN!=branchNames_.end(); itBN++) {
                             if (!itBN->compare(0,branchName.size(),branchName)) matches.push_back(itBN);
                         }
                         if (matches.empty()) {
                             //no matches found
                             EXCEPTION_RAISE(
                                     "ProductNotFound",
                                     "No product found for name '"
                                     + collectionName
                                     + "'"
                                     );
                         } else if (matches.size()>1) {
                             //more than one branch found
                             std::string names;
                             for (auto strs : matches) {
                                 if (!names.empty()) names+=", ";
                                 names+=*strs;
                             }
                             EXCEPTION_RAISE(
                                     "ProductAmbiguous",
                                     "Multiple products found for name '"
                                     + collectionName
                                     + "' without specified pass name ("
                                     + names
                                     + ")"
                                     );
                         } else {
                             //exactly one branch found
                             branchName=*matches.front();
                             knownLookups_[collectionName]=branchName;
                         }
                     }
                 }
                 //get iterators to branch and collection
                 auto itBranch = branches_.find(branchName);
                 auto itPassenger = passengers_.find(branchName);
                 if (itPassenger != passengers_.end()) {
                     if (itBranch != branches_.end()) {
                         //passenger and branch found
                         itBranch->second->GetEntry(ientry_);
                         //reading branches from input tree need to be manually updated
                         passengers_[branchName] = *((T *)(itBranch->second->GetObject()));
                     }
                     return std::get<T>(itPassenger->second);
                 } else if (inputTree_ == 0) {
                     //not found in loaded branches and there is no inputTree,
                     // so no hope of finding an unloaded object
                     EXCEPTION_RAISE(
                             "ProductNotFound",
                             "No product found for name '"
                             + collectionName
                             + "' and pass '"
                             + passName_
                             + "'");
                 }
                 // find the active branch and update if necessary
                 if (itBranch != branches_.end()) {
                     // update buffers if needed
                     if (itBranch->second->GetReadEntry() != ientry_) {
                         itBranch->second->GetEntry(ientry_, 1);
                     }
                     // check the objects map
                     if (itPassenger != passengers_.end())
                         return std::get<T>(itPassenger->second);
                     // this case is hard (impossible?) to achieve
                     EXCEPTION_RAISE(
                             "ProductNotFound",
                             "A branch mis-match occurred. I'm not sure how I got here!"
                             );
                 } else {
                     // ok, maybe we've not loaded this yet, look for a branch
                     TBranchElement* branch = dynamic_cast<TBranchElement *>(inputTree_->GetBranch(branchName.c_str()));
                     if (branch == 0) {
                         //inputTree doesn't have that branch
                         EXCEPTION_RAISE(
                                 "ProductNotFound",
                                 "No product found for name '"
                                 + collectionName
                                 + "' and pass '"
                                 + passName_
                                 + "'"
                                 );
                     }
                     // ooh, new branch!
                     // load in the current entry
                     branch->SetStatus(1); //overrides any 'ignore' rules
                     branch->GetEntry((ientry_<0)?(0):(ientry_));
                     //insert into maps of loaded branches and passengers
                     passengers_[branchName] = *((T *)(branch->GetObject())); //this will fail if wrong type is passed
                     branches_[branchName]   = branch;
                     return std::get<T>( passengers_.at(branchName) );
                 }
             } //getImpl
References branches_, branchNames_, ientry_, inputTree_, knownLookups_, makeBranchName(), passengers_, and passName_.
getMap() [1/2]
template<typename Key , typename Val > const std::map<Key,Val> ldmx::Event::getMap (const std::string & collectionName) const inline
Get a map of objects from the event bus when you don't care about the pass
Definition at line 245 of file Event.h.
{
                 return getMap<Key,Val>( collectionName , "" );
             }
getMap() [2/2]
template<typename Key , typename Val > const std::map<Key,Val> ldmx::Event::getMap (const std::string & collectionName, const std::string & passName) const inline
Get a map (std::map) of objects from the event bus
Definition at line 237 of file Event.h.
{
                 return getObject< std::map<Key,Val> >( collectionName , passName );
             }
Referenced by ldmx::RootCompleteReSim::GeneratePrimaryVertex().
getObject() [1/2]
template<typename T > const T ldmx::Event::getObject (const std::string & collectionName) const inline
Get a general object from the event bus when you don't care about the pass
Definition at line 213 of file Event.h.
{
                 return getObject<T>( collectionName , "" );
             }
getObject() [2/2]
template<typename T > const T ldmx::Event::getObject (const std::string & collectionName, const std::string & passName) const inline
Get a general object from the event bus
Definition at line 205 of file Event.h.
{
                 return getImpl<T>( collectionName , passName );
             }
getPassName()
std::string ldmx::Event::getPassName () inline
Get the current/default pass name.
Returns
The current/default pass name.
Definition at line 452 of file Event.h.
{
                 return passName_;
             }
References passName_.
getProducts()
const std::vector<ProductTag>& ldmx::Event::getProducts () const inline
Get a list of the data products in the event
Definition at line 417 of file Event.h.
 { return products_; }
References products_.
Referenced by searchProducts().
makeBranchName() [1/2]
std::string ldmx::Event::makeBranchName (const std::string & collectionName) const inline
Make a branch name from a collection and the default(current) pass name.
Parameters
collectionName The collection name.
Definition at line 410 of file Event.h.
{
                 return makeBranchName(collectionName, passName_);
             }
References makeBranchName(), and passName_.
makeBranchName() [2/2]
std::string ldmx::Event::makeBranchName (const std::string & collectionName, const std::string & passName) const inline
Make a branch name from a collection and pass name.
Parameters
collectionName The collection name.
passName The pass name.
Definition at line 402 of file Event.h.
{
                 return collectionName + "_" + passName;
             }
Referenced by add(), getImpl(), and makeBranchName().
nextEvent()
bool ldmx::Event::nextEvent ()
Go to the next event by incrementing the entry index.
Returns
Hard-coded to return true.
Definition at line 122 of file Event.cxx.
{
         ientry_++;
         eventHeader_ = getObject<EventHeader>(EventConstants::EVENT_HEADER);
         return true;
     }
References eventHeader_, and ientry_.
Referenced by ldmx::EventFile::nextEvent().
onEndOfEvent()
void ldmx::Event::onEndOfEvent ()
Perform end of event action (doesn't do anything right now).
Definition at line 143 of file Event.cxx.
 { }
Referenced by ldmx::EventFile::nextEvent().
onEndOfFile()
void ldmx::Event::onEndOfFile ()
Perform end of file action.
Clears buffer objects and resets output branch addresses. This prepares the event bus for a new input file (with new addresses).
Definition at line 145 of file Event.cxx.
{
         passengers_.clear(); //reset event bus
         branches_.clear(); //reset branches
         if ( outputTree_ ) outputTree_->ResetBranchAddresses(); //reset addresses for output branch
         if ( inputTree_ ) inputTree_ = nullptr; //detach old inputTree (owned by EventFile)
         ientry_ = -1; //reset current entry and total entries
         entries_ = -1;
     }
References branches_, entries_, ientry_, inputTree_, outputTree_, and passengers_.
Referenced by ldmx::Process::run().
Print()
void ldmx::Event::Print (int verbosity) const
Print event bus
Only prints passengers that have been loaded into the member object. This means what is printed depends on when this method is called. For example, if this method is called after the Clear method, then everything will be an empty object.
Parameters
verbosity integer flag to determine how verbose you want to be.
Definition at line 13 of file Event.cxx.
{
         for ( const auto &keyVal : passengers_ ) {
             if ( verbosity > 1 ) std::cout << keyVal.first << std::endl;
             std::visit( printPassenger(verbosity) , keyVal.second );
         }
     }
References passengers_.
searchProducts()
std::vector< ProductTag > ldmx::Event::searchProducts (const std::string & namematch, const std::string & passmatch, const std::string & typematch) const
Get a list of products which match the given POSIX-Extended, case-insenstive regular-expressions. An empty argument is interpreted as ".*", which matches everything.
Parameters
namematch Regular expression to compare with the product name
passmatch Regular expression to compare with the pass name
typematch Regular expression to compare with the type name
Definition at line 34 of file Event.cxx.
{
         std::vector<ProductTag> retval;
         regex_t reg_name, reg_pass, reg_type;
         if (!regcomp(&reg_name,(namematch.empty()?(".*"):(namematch.c_str())),REG_EXTENDED|REG_ICASE|REG_NOSUB)) {
             if (!regcomp(&reg_pass,(passmatch.empty()?(".*"):(passmatch.c_str())),REG_EXTENDED|REG_ICASE|REG_NOSUB)) {
                 if (!regcomp(&reg_type,(typematch.empty()?(".*"):(typematch.c_str())),REG_EXTENDED|REG_ICASE|REG_NOSUB)) {
                     //all passed expressions are valid regular expressions
                     const std::vector<ProductTag>& products=getProducts();
                     for (std::vector<ProductTag>::const_iterator i=products.begin(); i!=products.end(); i++) {
                         if (!regexec(&reg_name,i->name().c_str(),0,0,0) &&
                             !regexec(&reg_pass,i->passname().c_str(),0,0,0) &&
                             !regexec(&reg_type,i->type().c_str(),0,0,0))
                             retval.push_back(*i);
                     }
                     regfree(&reg_type);
                  } else {
                     EXCEPTION_RAISE(
                         "InvalidRegex",
                         "The passed type regex '"
                         + typematch
                         + "' is not a valid regular expression"
                     );
                 }
                 regfree(&reg_pass);
             } else {
                 EXCEPTION_RAISE(
                     "InvalidRegex",
                     "The passed name regex '"
                     + namematch
                     + "' is not a valid regular expression"
                     );
             }
             regfree(&reg_name);
         } else {
             EXCEPTION_RAISE(
                     "RegexErr",
                     "The passed passname regex '"
                     + passmatch
                     + "' is not a valid regular expression."
                     );
         }
         return retval;
     }
References getProducts().
Referenced by exists().
setInputTree()
void ldmx::Event::setInputTree (TTree * tree)
********* Functionality for storage ********** Set the input data tree.
Parameters
tree The input data tree.
Definition at line 92 of file Event.cxx.
{
         inputTree_ = tree;
         entries_ = inputTree_->GetEntriesFast();
         // in some cases, setInputTree is called more than once,
         // so reset branch listing before starting
         products_.clear();
         branchNames_.clear();
         branches_.clear();
         passengers_.clear();
         // put in EventHeader (only one without pass name)
         products_.emplace_back(EventConstants::EVENT_HEADER,"","ldmx::EventHeader");
         // find the names of all the existing branches
         TObjArray* branches = inputTree_->GetListOfBranches();
         for (int i = 0; i < branches->GetEntriesFast(); i++) {
             std::string brname=branches->At(i)->GetName();
             if (brname!=EventConstants::EVENT_HEADER) {
                 size_t j=brname.find("_");
                 std::string iname=brname.substr(0,j);
                 std::string pname=brname.substr(j+1);
                 std::string tname = dynamic_cast<TBranchElement*>(branches->At(i))->GetClassName();
                 products_.emplace_back(iname,pname,tname);
             }
             branchNames_.push_back(brname);
         }
     }
References branches_, branchNames_, entries_, inputTree_, passengers_, and products_.
Referenced by ldmx::EventFile::nextEvent(), and ldmx::EventFile::setupEvent().
setOutputTree()
void ldmx::Event::setOutputTree (TTree * tree)
Set the output data tree.
Parameters
tree The output data tree.
Definition at line 88 of file Event.cxx.
{
         outputTree_ = tree;
     }
References outputTree_.
Referenced by ldmx::EventFile::nextEvent().
shouldDrop()
bool ldmx::Event::shouldDrop (const std::string & collName) const private
Check if collection should be dropped.
Parameters
collName name of collection
Returns
true if the collection should be dropped (i.e. NOT saved)
Definition at line 154 of file Event.cxx.
{
         for ( const regex_t &exp : regexDropCollections_ ) {
             if ( !regexec(&exp,branchName.c_str(),0,0,0) ) return true;
         }
         return false;
     }
References regexDropCollections_.
Referenced by add().
Member Data Documentation
branches_
std::map<std::string, TBranchElement*> ldmx::Event::branches_ mutable private
Map of names to branches.
Definition at line 636 of file Event.h.
Referenced by getImpl(), onEndOfFile(), and setInputTree().
branchesFilled_
std::set<std::string> ldmx::Event::branchesFilled_ private
Names of branches filled during this event.
Definition at line 656 of file Event.h.
Referenced by add(), beforeFill(), and Clear().
branchNames_
std::vector<std::string> ldmx::Event::branchNames_ private
Names of all branches.
Definition at line 651 of file Event.h.
Referenced by add(), getImpl(), and setInputTree().
entries_
Long64_t ldmx::Event::entries_ {-1} private
Number of entries in the tree.
Definition at line 611 of file Event.h.
Referenced by onEndOfFile(), and setInputTree().
eventHeader_
EventHeader ldmx::Event::eventHeader_ private
The event header object.
Definition at line 606 of file Event.h.
Referenced by beforeFill(), getEventHeader(), getEventNumber(), getEventWeight(), and nextEvent().
ientry_
Long64_t ldmx::Event::ientry_ {-1} private
Current entry in the tree.
Definition at line 616 of file Event.h.
Referenced by getImpl(), nextEvent(), and onEndOfFile().
inputTree_
TTree* ldmx::Event::inputTree_ {nullptr} private
The input tree for reading existing data.
Definition at line 631 of file Event.h.
Referenced by beforeFill(), getImpl(), onEndOfFile(), and setInputTree().
knownLookups_
std::map<std::string, std::string> ldmx::Event::knownLookups_ mutable private
Efficiency cache for empty pass name lookups.
Definition at line 666 of file Event.h.
Referenced by add(), and getImpl().
newBranches_
std::vector<TBranchElement*> ldmx::Event::newBranches_ private
List of new branches added.
Definition at line 646 of file Event.h.
Referenced by add().
outputTree_
TTree* ldmx::Event::outputTree_ {nullptr} private
The output tree for writing a new file.
Definition at line 626 of file Event.h.
Referenced by add(), createTree(), onEndOfFile(), and setOutputTree().
passengers_
std::map<std::string, EventBusPassenger > ldmx::Event::passengers_ mutable private
Map of names to passengers.
Definition at line 641 of file Event.h.
Referenced by add(), Clear(), getImpl(), onEndOfFile(), Print(), and setInputTree().
passName_
std::string ldmx::Event::passName_ private
The default pass name.
Definition at line 621 of file Event.h.
Referenced by add(), getImpl(), getPassName(), and makeBranchName().
products_
std::vector<ProductTag> ldmx::Event::products_ private
List of all the event products
Definition at line 671 of file Event.h.
Referenced by add(), getProducts(), and setInputTree().
regexDropCollections_
std::vector<regex_t> ldmx::Event::regexDropCollections_ private
Regex of collection names to not store in event.
Definition at line 661 of file Event.h.
Referenced by addDrop(), shouldDrop(), and ~Event().
The documentation for this class was generated from the following files:
Framework/include/Framework/Event.h
Framework/src/Event.cxx