LDMX Software: g4db::example::FindDarkBremProducts Class Reference
g4db::example::FindDarkBremProducts Class Reference
Public Member Functions
void PreUserTrackingAction (const G4Track *track) final override
Detailed Description
Look through the tracks to find the dark brem products
Definition at line 359 of file simulate.cxx.
Member Function Documentation
PreUserTrackingAction()
void g4db::example::FindDarkBremProducts::PreUserTrackingAction (const G4Track * track) inline final override
Check the new track that has been provided to see if it was created by the dark brem process. If it was, pass this track onto OutgoingKinematics depending on if it is the A' or the lepton.
Definition at line 366 of file simulate.cxx.
{
    const G4VProcess* creator = track->GetCreatorProcess();
    if (creator and creator->GetProcessName().contains(
                        G4DarkBremsstrahlung::PROCESS_NAME)) {
      if (track->GetParticleDefinition() == G4APrime::APrime()) {
        OutgoingKinematics::get()->setAPrime(track);
      } else {
        OutgoingKinematics::get()->setRecoil(track);
      }
    } // track created by dark brem process
  }
References G4APrime::APrime(), g4db::example::OutgoingKinematics::get(), G4DarkBremsstrahlung::PROCESS_NAME, g4db::example::OutgoingKinematics::setAPrime(), and g4db::example::OutgoingKinematics::setRecoil().
The documentation for this class was generated from the following file:
SimCore/G4DarkBreM/app/simulate.cxx