LDMX Software: ldmx::HcalCluster Class Reference
ldmx::HcalCluster Class Reference
Stores cluster information from the ECal.
#include <HcalCluster.h>
Public Member Functions
HcalCluster ()
virtual ~HcalCluster ()
void Print () const
void Clear ()
void addHits (const std::vector< const ldmx::HcalHit * > hitsVec)
void setEnergy (double energy)
void setNHits (int nHits)
void setIDs (std::vector< unsigned int > &hitIDs)
void setCentroidXYZ (double x, double y, double z)
void setTime (double x)
double getEnergy () const
int getNHits () const
double getCentroidX () const
double getCentroidY () const
double getCentroidZ () const
double getTime () const
const std::vector< unsigned int > & getHitIDs () const
bool operator< (const HcalCluster &rhs) const
Private Member Functions
ClassDef (HcalCluster, 1)
Private Attributes
std::vector< unsigned int > hitIDs_
double energy_ {0}
int nHits_ {0}
double centroidX_ {0}
double centroidY_ {0}
double centroidZ_ {0}
double time_ {0}
Detailed Description
Stores cluster information from the ECal.
Definition at line 28 of file HcalCluster.h.
Constructor & Destructor Documentation
HcalCluster()
ldmx::HcalCluster::HcalCluster ()
Class constructor.
~HcalCluster()
virtual ldmx::HcalCluster::~HcalCluster () virtual
Class destructor.
Member Function Documentation
addHits()
void ldmx::HcalCluster::addHits (const std::vector< const ldmx::HcalHit * > hitsVec)
Take in the hits that make up the cluster.
Parameters
hit The digi hit's entry number in the events digi collection.
Referenced by hcal::HcalClusterProducer::produce().
Clear()
void ldmx::HcalCluster::Clear ()
Reset the HcalCluster object.
getCentroidX()
double ldmx::HcalCluster::getCentroidX () const inline
Definition at line 94 of file HcalCluster.h.
{ return centroidX_; }
getCentroidY()
double ldmx::HcalCluster::getCentroidY () const inline
Definition at line 96 of file HcalCluster.h.
{ return centroidY_; }
getCentroidZ()
double ldmx::HcalCluster::getCentroidZ () const inline
Definition at line 98 of file HcalCluster.h.
{ return centroidZ_; }
getEnergy()
double ldmx::HcalCluster::getEnergy () const inline
Definition at line 90 of file HcalCluster.h.
{ return energy_; }
getHitIDs()
const std::vector< unsigned int > & ldmx::HcalCluster::getHitIDs () const inline
Definition at line 102 of file HcalCluster.h.
{ return hitIDs_; }
getNHits()
int ldmx::HcalCluster::getNHits () const inline
Definition at line 92 of file HcalCluster.h.
{ return nHits_; }
getTime()
double ldmx::HcalCluster::getTime () const inline
Definition at line 100 of file HcalCluster.h.
{ return time_; }
operator<()
bool ldmx::HcalCluster::operator< (const HcalCluster & rhs) const inline
Definition at line 104 of file HcalCluster.h.
{
    return this->getEnergy() < rhs.getEnergy();
  }
Print()
void ldmx::HcalCluster::Print () const
Print a description of this object.
setCentroidXYZ()
void ldmx::HcalCluster::setCentroidXYZ (double x, double y, double z) inline
Sets the three coordinates of the cluster centroid
Parameters
x The x coordinate.
y The y coordinate.
z The z coordinate.
Definition at line 82 of file HcalCluster.h.
{
    centroidX_ = x;
    centroidY_ = y;
    centroidZ_ = z;
  }
Referenced by hcal::HcalClusterProducer::produce().
setEnergy()
void ldmx::HcalCluster::setEnergy (double energy) inline
Sets total energy for the cluster.
Parameters
energy The total energy of the cluster.
Definition at line 61 of file HcalCluster.h.
{ energy_ = energy; }
Referenced by hcal::HcalClusterProducer::produce().
setIDs()
void ldmx::HcalCluster::setIDs (std::vector< unsigned int > & hitIDs) inline
Sets a sorted vector for the IDs of the hits that make up the cluster.
Parameters
IDs Sorted vector of hit IDs.
Definition at line 74 of file HcalCluster.h.
{ hitIDs_ = hitIDs; }
setNHits()
void ldmx::HcalCluster::setNHits (int nHits) inline
Sets total number of hits in the cluster.
Parameters
nHits The total number of hits.
Definition at line 67 of file HcalCluster.h.
{ nHits_ = nHits; }
Referenced by hcal::HcalClusterProducer::produce().
setTime()
void ldmx::HcalCluster::setTime (double x) inline
Definition at line 88 of file HcalCluster.h.
{ time_ = x; }
Member Data Documentation
centroidX_
double ldmx::HcalCluster::centroidX_ {0} private
Definition at line 112 of file HcalCluster.h.
centroidY_
double ldmx::HcalCluster::centroidY_ {0} private
Definition at line 113 of file HcalCluster.h.
centroidZ_
double ldmx::HcalCluster::centroidZ_ {0} private
Definition at line 114 of file HcalCluster.h.
energy_
double ldmx::HcalCluster::energy_ {0} private
Definition at line 110 of file HcalCluster.h.
hitIDs_
std::vector<unsigned int> ldmx::HcalCluster::hitIDs_ private
Definition at line 109 of file HcalCluster.h.
nHits_
int ldmx::HcalCluster::nHits_ {0} private
Definition at line 111 of file HcalCluster.h.
time_
double ldmx::HcalCluster::time_ {0} private
Definition at line 115 of file HcalCluster.h.
The documentation for this class was generated from the following file:
Hcal/include/Hcal/Event/HcalCluster.h