LDMX Software: ecal::test::EcalCheckEnergyReconstruction Class Reference
ecal::test::EcalCheckEnergyReconstruction Class Reference
Public Member Functions
EcalCheckEnergyReconstruction (const std::string &name, framework::Process &p)
void onProcessStart () final override
void analyze (const framework::Event &event) final override
Public Member Functions inherited from framework::Analyzer
Analyzer (const std::string &name, Process &process)
virtual void analyze (const Event &event)=0
Public Member Functions inherited from framework::EventProcessor
EventProcessor (const std::string &name, Process &process)
virtual ~EventProcessor ()
virtual void configure (framework::config::Parameters &parameters)
virtual void onNewRun (const ldmx::RunHeader &runHeader)
virtual void onFileOpen (EventFile &eventFile)
virtual void onFileClose (EventFile &eventFile)
virtual void onProcessStart ()
virtual void onProcessEnd ()
template<class T >
const T & getCondition (const std::string &condition_name)
TDirectory * getHistoDirectory ()
void setStorageHint (framework::StorageControlHint hint)
void setStorageHint (framework::StorageControlHint hint, const std::string &purposeString)
int getLogFrequency () const
int getRunNumber () const
std::string getName () const
void createHistograms (const std::vector< framework::config::Parameters > &histos)
Additional Inherited Members
Static Public Member Functions inherited from framework::EventProcessor
static void declare (const std::string &classname, int classtype, EventProcessorMaker *)
Static Public Attributes inherited from framework::Analyzer
static const int CLASSTYPE {2}
Protected Member Functions inherited from framework::EventProcessor
void abortEvent ()
Protected Attributes inherited from framework::EventProcessor
HistogramHelper histograms_
Interface class for making and filling histograms.
NtupleManager & ntuple_ {NtupleManager::getInstance()}
Manager for any ntuples.
logging::logger theLog_
The logger for this EventProcessor.
Detailed Description
Checks
Amplitude of EcalRecHit matches SimCalorimeterHit EDep with the same ID
Estimated energy at TP level matches sim energy
Assumptions
Only one sim hit per event
Noise generation has been turned off
Definition at line 233 of file EcalDigiPipelineTest.cxx.
Constructor & Destructor Documentation
EcalCheckEnergyReconstruction()
ecal::test::EcalCheckEnergyReconstruction::EcalCheckEnergyReconstruction (const std::string & name, framework::Process & p) inline
Definition at line 235 of file EcalDigiPipelineTest.cxx.
      : framework::Analyzer(name, p) {}
~EcalCheckEnergyReconstruction()
ecal::test::EcalCheckEnergyReconstruction::~EcalCheckEnergyReconstruction () inline
Definition at line 237 of file EcalDigiPipelineTest.cxx.
{}
Member Function Documentation
analyze()
void ecal::test::EcalCheckEnergyReconstruction::analyze (const framework::Event & event) inline final override virtual
Process the event and make histograms or summaries
Parameters
event The Event to analyze
Implements framework::Analyzer.
Definition at line 254 of file EcalDigiPipelineTest.cxx.
{
    const auto simHits =
        event.getCollection<ldmx::SimCalorimeterHit>("EcalSimHits");
    REQUIRE(simHits.size() == 1);
    float truth_energy = simHits.at(0).getEdep();
    ntuple_.setVar<float>("SimEnergy", truth_energy);
    const auto daqDigis{
        event.getObject<ldmx::HgcrocDigiCollection>("EcalDigis")};
    CHECK(daqDigis.getNumDigis() == 1);
    auto daqDigi = daqDigis.getDigi(0);
    ntuple_.setVar<int>("DaqDigi", daqDigi.soi().raw());
    bool is_in_adc_mode = daqDigi.isADC();
    ntuple_.setVar<int>("DaqDigiIsADC", is_in_adc_mode);
    ntuple_.setVar<int>("DaqDigiADC", daqDigi.soi().adc_t());
    ntuple_.setVar<int>("DaqDigiTOT", daqDigi.tot());
    const auto recHits = event.getCollection<ldmx::EcalHit>("EcalRecHits");
    CHECK(recHits.size() == 1);
    auto hit = recHits.at(0);
    ldmx::EcalID id(hit.getID());
    CHECK_FALSE(hit.isNoise());
    CHECK(id.raw() == simHits.at(0).getID());
    double daq_energy{hit.getAmplitude()};
    CHECK_THAT(daq_energy,
        isCloseEnough(truth_energy,MAX_ENERGY_ERROR_DAQ,MAX_ENERGY_PERCENT_ERROR_DAQ));
    ntuple_.setVar<float>("RecEnergy", hit.getAmplitude());
    const auto trigDigis{
        event.getObject<ldmx::HgcrocTrigDigiCollection>("ecalTrigDigis")};
    CHECK(trigDigis.size() == 1);
    auto trigDigi = trigDigis.at(0);
    float tp_energy = 8 * trigDigi.linearPrimitive() * 320. / 1024 * MeV_per_fC;
    CHECK_THAT(tp_energy ,
        isCloseEnough(truth_energy,MAX_ENERGY_ERROR_TP,MAX_ENERGY_PERCENT_ERROR_TP));
    ntuple_.setVar<float>("TrigPrimEnergy", tp_energy);
    ntuple_.setVar<int>("TrigPrimDigiEncoded", trigDigi.getPrimitive());
    ntuple_.setVar<int>("TrigPrimDigiLinear", trigDigi.linearPrimitive());
    return;
  }
References framework::EventProcessor::ntuple_, and framework::NtupleManager::setVar().
onProcessStart()
void ecal::test::EcalCheckEnergyReconstruction::onProcessStart () inline final override virtual
Callback for the EventProcessor to take any necessary action when the processing of events starts, such as creating histograms.
Reimplemented from framework::EventProcessor.
Definition at line 239 of file EcalDigiPipelineTest.cxx.
{
    getHistoDirectory();
    ntuple_.create("EcalDigiTest");
    ntuple_.addVar<float>("EcalDigiTest", "SimEnergy");
    ntuple_.addVar<float>("EcalDigiTest", "RecEnergy");
    ntuple_.addVar<float>("EcalDigiTest", "TrigPrimEnergy");
    ntuple_.addVar<int>("EcalDigiTest", "DaqDigi");
    ntuple_.addVar<int>("EcalDigiTest", "DaqDigiIsADC");
    ntuple_.addVar<int>("EcalDigiTest", "DaqDigiADC");
    ntuple_.addVar<int>("EcalDigiTest", "DaqDigiTOT");
    ntuple_.addVar<int>("EcalDigiTest", "TrigPrimDigiEncoded");
    ntuple_.addVar<int>("EcalDigiTest", "TrigPrimDigiLinear");
  }
References framework::NtupleManager::addVar(), framework::NtupleManager::create(), framework::EventProcessor::getHistoDirectory(), and framework::EventProcessor::ntuple_.
The documentation for this class was generated from the following file:
Ecal/test/EcalDigiPipelineTest.cxx