LDMX Software: biasing::TargetBremFilter Class Reference
biasing::TargetBremFilter Class Reference
#include <TargetBremFilter.h>
Public Member Functions
TargetBremFilter (const std::string &name, framework::config::Parameters &parameters)
Constructor.
~TargetBremFilter ()
Destructor.
void stepping (const G4Step *step) final override
void EndOfEventAction (const G4Event *) final override
G4ClassificationOfNewTrack ClassifyNewTrack (const G4Track *aTrack, const G4ClassificationOfNewTrack &currentTrackClass) final override
std::vector< simcore::TYPE > getTypes () final override
Retrieve the type of actions this class defines.
Public Member Functions inherited from simcore::UserAction
UserAction (const std::string &name, framework::config::Parameters &parameters)
virtual ~UserAction ()=default
Destructor.
virtual void BeginOfEventAction (const G4Event *)
virtual void EndOfEventAction (const G4Event *)
virtual void BeginOfRunAction (const G4Run *)
virtual void EndOfRunAction (const G4Run *)
virtual void PreUserTrackingAction (const G4Track *)
virtual void PostUserTrackingAction (const G4Track *)
virtual void stepping (const G4Step *)
virtual G4ClassificationOfNewTrack ClassifyNewTrack (const G4Track *, const G4ClassificationOfNewTrack &cl)
virtual void NewStage ()
virtual void PrepareNewEvent ()
virtual std::vector< TYPE > getTypes ()=0
Private Attributes
double recoilMaxPThreshold_ {1500}
Recoil electron threshold.
double bremEnergyThreshold_ {2500}
Brem gamma energy treshold.
bool killRecoil_ {false}
Flag indicating if the recoil electron track should be killed.
Additional Inherited Members
Public Types inherited from simcore::UserAction
using Factory = ::simcore::Factory< UserAction, std::shared_ptr< UserAction >, const std::string &, framework::config::Parameters & >
factory for user actions
Protected Member Functions inherited from simcore::UserAction
UserEventInformation * getEventInfo () const
const std::map< int, ldmx::SimParticle > & getCurrentParticleMap () const
Protected Attributes inherited from simcore::UserAction
std::string name_ {""}
Name of the UserAction.
framework::config::Parameters parameters_
The set of parameters used to configure this class.
Detailed Description
User action that allows a user to filter out events that don't result in a brem within the target.
Definition at line 25 of file TargetBremFilter.h.
Constructor & Destructor Documentation
TargetBremFilter()
biasing::TargetBremFilter::TargetBremFilter (const std::string & name, framework::config::Parameters & parameters)
Constructor.
Definition at line 18 of file TargetBremFilter.cxx.
    : simcore::UserAction(name, parameters) {
  recoilMaxPThreshold_ =
      parameters.getParameter<double>("recoil_max_p_threshold");
  bremEnergyThreshold_ =
      parameters.getParameter<double>("brem_min_energy_threshold");
  killRecoil_ = parameters.getParameter<bool>("kill_recoil_track");
}
References bremEnergyThreshold_, framework::config::Parameters::getParameter(), killRecoil_, and recoilMaxPThreshold_.
~TargetBremFilter()
biasing::TargetBremFilter::~TargetBremFilter ()
Destructor.
Definition at line 28 of file TargetBremFilter.cxx.
{}
Member Function Documentation
ClassifyNewTrack()
G4ClassificationOfNewTrack biasing::TargetBremFilter::ClassifyNewTrack (const G4Track * aTrack, const G4ClassificationOfNewTrack & currentTrackClass) final override virtual
Classify a new track which postpones track processing. Track processing resumes normally if a target PN interaction occurred.
Parameters
aTrack The Geant4 track.
currentTrackClass The current track classification.
Reimplemented from simcore::UserAction.
Definition at line 30 of file TargetBremFilter.cxx.
{
  // get the PDGID of the track.
  G4int pdgID = track->GetParticleDefinition()->GetPDGEncoding();
  // Get the particle type.
  G4String particleName = track->GetParticleDefinition()->GetParticleName();
  // Use current classification by default so values from other plugins are not
  // overridden.
  G4ClassificationOfNewTrack classification = currentTrackClass;
  if (track->GetTrackID() == 1 && pdgID == 11) {
    return fWaiting;
  }
  return classification;
}
EndOfEventAction()
void biasing::TargetBremFilter::EndOfEventAction (const G4Event *) final override virtual
Method called at the end of every event.
Parameters
event Geant4 event object.
Reimplemented from simcore::UserAction.
Definition at line 143 of file TargetBremFilter.cxx.
{}
getTypes()
std::vector< simcore::TYPE > biasing::TargetBremFilter::getTypes () inline final override virtual
Retrieve the type of actions this class defines.
Implements simcore::UserAction.
Definition at line 58 of file TargetBremFilter.h.
{
    return {simcore::TYPE::EVENT, simcore::TYPE::STACKING,
            simcore::TYPE::STEPPING};
  }
stepping()
void biasing::TargetBremFilter::stepping (const G4Step * step) final override virtual
Implement the stepping action which performs the target volume biasing.
Parameters
step The Geant4 step.
Check if the electron will be exiting the target
The 'recoil_PV' volume name is automatically constructed by Geant4's GDML parser and was found by inspecting the geometry using a visualization. This Physical Volume (PV) is associated with the recoil parent volume and so it will break if the recoil parent volume changes its name.
We also check if the next volume is World_PV because in some geometries (e.g. v14), there is a air-gap between the target region and the recoil.
Reimplemented from simcore::UserAction.
Definition at line 49 of file TargetBremFilter.cxx.
{
  // Get the track associated with this step.
  auto track{step->GetTrack()};
  // Only process the primary electron track
  if (track->GetParentID() != 0) return;
  // Get the PDG ID of the track and make sure it's an electron. If
  // another particle type is found, thrown an exception.
  if (auto pdgID{track->GetParticleDefinition()->GetPDGEncoding()}; pdgID != 11)
    return;
  // Get the region the particle is currently in.  Continue processing
  // the particle only if it's in the target region.
  if (auto region{
          track->GetVolume()->GetLogicalVolume()->GetRegion()->GetName()};
      region.compareTo("target") != 0)
    return;
  /*
  std::cout << "[TargetBremFilter] : Stepping primary electron in 'target' region into "
    << track->GetNextVolume()->GetName()
    << std::endl;
   */
  if (auto volume{track->GetNextVolume()->GetName()};
      volume.compareTo("recoil_PV") == 0
      or volume.compareTo("World_PV") == 0) {
    // If the recoil electron
    if (track->GetMomentum().mag() >= recoilMaxPThreshold_) {
      track->SetTrackStatus(fKillTrackAndSecondaries);
      G4RunManager::GetRunManager()->AbortEvent();
      return;
    }
    // Get the electron secondries
    bool hasBremCandidate = false;
    if (auto secondaries = step->GetSecondary(); secondaries->size() == 0) {
      track->SetTrackStatus(fKillTrackAndSecondaries);
      G4RunManager::GetRunManager()->AbortEvent();
      return;
    } else {
      for (auto& secondary_track : *secondaries) {
        G4String processName =
            secondary_track->GetCreatorProcess()->GetProcessName();
        if (processName.compareTo("eBrem") == 0 &&
            secondary_track->GetKineticEnergy() > bremEnergyThreshold_) {
          auto trackInfo{simcore::UserTrackInformation::get(secondary_track)};
          trackInfo->tagBremCandidate();
          getEventInfo()->incBremCandidateCount();
          hasBremCandidate = true;
        }
      }
    }
    if (!hasBremCandidate) {
      track->SetTrackStatus(fKillTrackAndSecondaries);
      G4RunManager::GetRunManager()->AbortEvent();
      return;
    }
    /*
    std::cout << "[TargetBremFilter] : Found brem candidate" << std::endl;
     */
    // Check if the recoil electron should be killed.  If not, postpone
    // its processing until the brem gamma has been processed.
    if (killRecoil_)
      track->SetTrackStatus(fStopAndKill);
    else
      track->SetTrackStatus(fSuspend);
  } else if (step->GetPostStepPoint()->GetKineticEnergy() == 0) {
    track->SetTrackStatus(fKillTrackAndSecondaries);
    G4RunManager::GetRunManager()->AbortEvent();
    return;
  }
}
References bremEnergyThreshold_, simcore::UserTrackInformation::get(), simcore::UserAction::getEventInfo(), simcore::UserEventInformation::incBremCandidateCount(), killRecoil_, recoilMaxPThreshold_, and simcore::UserTrackInformation::tagBremCandidate().
Member Data Documentation
bremEnergyThreshold_
double biasing::TargetBremFilter::bremEnergyThreshold_ {2500} private
Brem gamma energy treshold.
Definition at line 68 of file TargetBremFilter.h.
Referenced by stepping(), and TargetBremFilter().
killRecoil_
bool biasing::TargetBremFilter::killRecoil_ {false} private
Flag indicating if the recoil electron track should be killed.
Definition at line 71 of file TargetBremFilter.h.
Referenced by stepping(), and TargetBremFilter().
recoilMaxPThreshold_
double biasing::TargetBremFilter::recoilMaxPThreshold_ {1500} private
Recoil electron threshold.
Definition at line 65 of file TargetBremFilter.h.
Referenced by stepping(), and TargetBremFilter().
The documentation for this class was generated from the following files:
Biasing/include/Biasing/TargetBremFilter.h
Biasing/src/Biasing/TargetBremFilter.cxx