LDMX Software: simcore::ConditionsInterface Class Reference
simcore::ConditionsInterface Class Reference
Handle to the conditions system, provided at construction to classes which require it.
#include <ConditionsInterface.h>
Public Member Functions
ConditionsInterface (framework::EventProcessor *p)
template<class T >
const T & getCondition (const std::string &condition_name)
Private Attributes
framework::EventProcessor * processor_
Detailed Description
Handle to the conditions system, provided at construction to classes which require it.
Definition at line 21 of file ConditionsInterface.h.
Constructor & Destructor Documentation
ConditionsInterface()
simcore::ConditionsInterface::ConditionsInterface (framework::EventProcessor * p) inline
Definition at line 23 of file ConditionsInterface.h.
: processor_{p} {}
Member Function Documentation
getCondition()
template<class T > const T & simcore::ConditionsInterface::getCondition (const std::string & condition_name) inline
Primary request action for a conditions object If the object is in the cache and still valid (IOV), the cached object will be returned. If it is not in the cache, or is out of date, the () method will be called to provide the object.
Definition at line 33 of file ConditionsInterface.h.
{
    if (processor_ == 0) {
      EXCEPTION_RAISE("ConditionUnavailableException",
                      "No conditions system object available in SimCore");
    }
    return processor_->getCondition<T>(condition_name);
  }
References framework::EventProcessor::getCondition(), and processor_.
Referenced by simcore::EcalSD::ProcessHits(), and simcore::EcalHitIO::writeHitsCollection().
Member Data Documentation
processor_
framework::EventProcessor* simcore::ConditionsInterface::processor_ private
Pointer to the owner processor object
Definition at line 45 of file ConditionsInterface.h.
Referenced by getCondition().
The documentation for this class was generated from the following file:
SimCore/include/SimCore/ConditionsInterface.h