LDMX Software: ldmx::EventDisplay Class Reference
ldmx::EventDisplay Class Reference
Public Member Functions
EventDisplay (TEveManager *manager, bool verbose)
~EventDisplay ()
bool SetFile (const TString file)
void PreviousEvent ()
void NextEvent ()
template<typename T >
bool GetCollection (const TString branchName, std::vector< T > &collection)
void GetECALRecHitsCollInput ()
void GetClustersCollInput ()
void GetTrackerHitsCollInput ()
void GetHCALRecHitsCollInput ()
void GetEcalSimParticlesCollInput ()
bool GotoEvent (int event)
bool GotoEvent ()
bool SetSimThresh ()
bool SetEventTree ()
void ColorClusters ()
Private Member Functions
ClassDef (EventDisplay, 1)
Private Attributes
bool verbose_
TFile * file_
TTree * tree_
std::vector< EcalHit > ecalRecHits_
std::vector< HcalHit > hcalRecHits_
std::vector< SimTrackerHit > recoilHits_
std::vector< EcalCluster > ecalClusters_
std::vector< SimTrackerHit > ecalSimParticles_
bool foundECALRecHits_ = false
bool foundHCALRecHits_ = false
bool foundClusters_ = false
bool foundTrackerHits_ = false
bool foundEcalSPHits_ = false
int eventNum_ = -1
int eventNumMax_
TString clustersCollName_ = "ecalClusters_recon"
TString ecalRecHitsCollName_ = "EcalRecHits_recon"
TString hcalRecHitsCollName_ = "HcalRecHits_recon"
TString trackerHitsCollName_ = "RecoilSimHits_sim"
TString ecalSimParticlesCollName_ = "EcalScoringPlaneHits_sim"
TString eventTreeName_ = "LDMX_Events"
EveDetectorGeometry * theDetector_ {nullptr}
EventObjects * eventObjects_ {nullptr}
TGTextEntry * textBoxGotoEvent_
TGTextEntry * textBoxClustersCollName_
TGTextEntry * textBoxSimThresh_
TGTextEntry * textBoxEventTreeName_
TGTextEntry * textBoxEcalRecHitsCollName_
TGTextEntry * textBoxHcalRecHitsCollName_
TGTextEntry * textBoxTrackerHitsCollName_
TGTextEntry * textBoxEcalScorePlaneBranch_
TEveManager * manager_ {nullptr}
Detailed Description
Definition at line 33 of file EventDisplay.h.
Constructor & Destructor Documentation
EventDisplay()
ldmx::EventDisplay::EventDisplay (TEveManager * manager, bool verbose)
Constructor Builds window frame and and control panel. Imports geometry from EveDetectorGeometry.
Definition at line 13 of file EventDisplay.cxx.
         : TGMainFrame(gClient->GetRoot(), 320, 320), verbose_(verbose) {
         SetWindowName("LDMX Event Display");
         manager_ = manager;
         TGLViewer* viewer = manager_->GetDefaultGLViewer();
         viewer->UseLightColorSet();
         if ( verbose_ ) {
             std::cout << "[ EventDisplay ] : Drawing detector geometry... " << std::flush;
         }
         //when the first TGeoShape (a TGeoTube) is drawn, ROOT creates a default geometry for this drawing and
         // prints an Info statement to std-out. Currently, I can't figure out how to turn this behavior off.
         theDetector_ = new EveDetectorGeometry();
         eventObjects_ = new EventObjects();
         manager_->AddEvent(new TEveEventManager("LDMX Detector", ""));
         manager_->AddElement(theDetector_->getECAL());
         manager_->AddElement(theDetector_->getHCAL());
         manager_->AddElement(theDetector_->getRecoilTracker());
         manager_->AddEvent(new TEveEventManager("LDMX Event", ""));
         if ( verbose_ ) {
             std::cout << "done" << std::endl;
             std::cout << "[ EventDisplay ] : Constructing and linking buttons... " << std::flush;
         }
         TGVerticalFrame* contents = new TGVerticalFrame(this, 1000,1200);
         TGHorizontalFrame* commandFrameGotoEvent                = new TGHorizontalFrame(contents, 100,0);
         TGHorizontalFrame* commandFrameNextEvent                = new TGHorizontalFrame(contents, 100,0);
         TGHorizontalFrame* commandFrameColorClusters            = new TGHorizontalFrame(contents, 100,0);
         TGHorizontalFrame* commandFrameEcalClusterBranch        = new TGHorizontalFrame(contents, 100,0);
         TGHorizontalFrame* commandFrameSimThresh                = new TGHorizontalFrame(contents, 100,0);
         TGHorizontalFrame* commandFrameEventTree                = new TGHorizontalFrame(contents, 100,0);
         TGHorizontalFrame* commandFrameEcalHitBranch            = new TGHorizontalFrame(contents, 100,0);
         TGHorizontalFrame* commandFrameHcalHitBranch            = new TGHorizontalFrame(contents, 100,0);
         TGHorizontalFrame* commandFrameTrackerHitsBranch        = new TGHorizontalFrame(contents, 100,0);
         TGHorizontalFrame* commandFrameEcalScorePlaneBranch     = new TGHorizontalFrame(contents, 100,0);
         TGButton* buttonColor = new TGTextButton(commandFrameColorClusters, "Color Clusters");
         commandFrameColorClusters->AddFrame(buttonColor, new TGLayoutHints(kLHintsExpandX));
         buttonColor->Connect("Pressed()", "ldmx::EventDisplay", this, "ColorClusters()");
         TGButton* buttonPrevious = new TGTextButton(commandFrameNextEvent, "<<< Previous Event");
         commandFrameNextEvent->AddFrame(buttonPrevious, new TGLayoutHints(kLHintsExpandX));
         buttonPrevious->Connect("Pressed()", "ldmx::EventDisplay", this, "PreviousEvent()");
         TGButton* buttonNext = new TGTextButton(commandFrameNextEvent, "Next Event >>>");
         commandFrameNextEvent->AddFrame(buttonNext, new TGLayoutHints(kLHintsExpandX));
         buttonNext->Connect("Pressed()", "ldmx::EventDisplay", this, "NextEvent()");
         textBoxGotoEvent_ = new TGTextEntry(commandFrameGotoEvent, new TGTextBuffer(100));
         commandFrameGotoEvent->AddFrame(textBoxGotoEvent_, new TGLayoutHints(kLHintsExpandX));
         TGButton* buttonGoTo = new TGTextButton(commandFrameGotoEvent, "Go to Event");
         commandFrameGotoEvent->AddFrame(buttonGoTo, new TGLayoutHints(kLHintsExpandX));
         buttonGoTo->Connect("Pressed()", "ldmx::EventDisplay", this, "GotoEvent()");
         textBoxClustersCollName_ = new TGTextEntry(commandFrameEcalClusterBranch, new TGTextBuffer(100));
         commandFrameEcalClusterBranch->AddFrame(textBoxClustersCollName_, new TGLayoutHints(kLHintsExpandX));
         TGButton* buttonClusterName = new TGTextButton(commandFrameEcalClusterBranch, "Set Clusters Branch");
         commandFrameEcalClusterBranch->AddFrame(buttonClusterName, new TGLayoutHints(kLHintsExpandX));
         buttonClusterName->Connect("Pressed()", "ldmx::EventDisplay", this, "GetClustersCollInput()");
         textBoxSimThresh_ = new TGTextEntry(commandFrameSimThresh, new TGTextBuffer(100));
         commandFrameSimThresh->AddFrame(textBoxSimThresh_, new TGLayoutHints(kLHintsExpandX));
         TGButton* buttonDrawThresh = new TGTextButton(commandFrameSimThresh, "Sim P [MeV] Threshold");
         commandFrameSimThresh->AddFrame(buttonDrawThresh, new TGLayoutHints(kLHintsExpandX));
         buttonDrawThresh->Connect("Pressed()", "ldmx::EventDisplay", this, "SetSimThresh()");
         textBoxEventTreeName_ = new TGTextEntry(commandFrameEventTree, new TGTextBuffer(100));
         commandFrameEventTree->AddFrame(textBoxEventTreeName_, new TGLayoutHints(kLHintsExpandX));
         TGButton* buttonSetTree = new TGTextButton(commandFrameEventTree, "Set Event TTree");
         commandFrameEventTree->AddFrame(buttonSetTree, new TGLayoutHints(kLHintsExpandX));
         buttonSetTree->Connect("Pressed()", "ldmx::EventDisplay", this, "SetEventTree()");
         textBoxEcalRecHitsCollName_ = new TGTextEntry(commandFrameEcalHitBranch, new TGTextBuffer(100));
         commandFrameEcalHitBranch->AddFrame(textBoxEcalRecHitsCollName_, new TGLayoutHints(kLHintsExpandX));
         TGButton* buttonSetECALBranch = new TGTextButton(commandFrameEcalHitBranch, "Set ECAL RecHits Branch");
         commandFrameEcalHitBranch->AddFrame(buttonSetECALBranch, new TGLayoutHints(kLHintsExpandX));
         buttonSetECALBranch->Connect("Pressed()", "ldmx::EventDisplay", this, "GetECALRecHitsCollInput()");
         textBoxHcalRecHitsCollName_ = new TGTextEntry(commandFrameHcalHitBranch, new TGTextBuffer(100));
         commandFrameHcalHitBranch->AddFrame(textBoxHcalRecHitsCollName_, new TGLayoutHints(kLHintsExpandX));
         TGButton* buttonSetHCALBranch = new TGTextButton(commandFrameHcalHitBranch, "Set HCAL RecHits Branch");
         commandFrameHcalHitBranch->AddFrame(buttonSetHCALBranch, new TGLayoutHints(kLHintsExpandX));
         buttonSetHCALBranch->Connect("Pressed()", "ldmx::EventDisplay", this, "GetHCALRecHitsCollInput()");
         textBoxTrackerHitsCollName_ = new TGTextEntry(commandFrameTrackerHitsBranch, new TGTextBuffer(100));
         commandFrameTrackerHitsBranch->AddFrame(textBoxTrackerHitsCollName_, new TGLayoutHints(kLHintsExpandX));
         TGButton* buttonSetRecoilBranch = new TGTextButton(commandFrameTrackerHitsBranch, "Set Recoil Sims Branch");
         commandFrameTrackerHitsBranch->AddFrame(buttonSetRecoilBranch, new TGLayoutHints(kLHintsExpandX));
         buttonSetRecoilBranch->Connect("Pressed()", "ldmx::EventDisplay", this, "GetTrackerHitsCollInput()");
         textBoxEcalScorePlaneBranch_ = new TGTextEntry(commandFrameEcalScorePlaneBranch, new TGTextBuffer(100));
         commandFrameEcalScorePlaneBranch->AddFrame(textBoxEcalScorePlaneBranch_, new TGLayoutHints(kLHintsExpandX));
         TGButton* buttonSetSimParticlesBranch = new TGTextButton(commandFrameEcalScorePlaneBranch, "Set Sim Particles Branch");
         commandFrameEcalScorePlaneBranch->AddFrame(buttonSetSimParticlesBranch, new TGLayoutHints(kLHintsExpandX));
         buttonSetSimParticlesBranch->Connect("Pressed()", "ldmx::EventDisplay", this, "GetEcalSimParticlesCollInput()");
         //Order from top to bottom here
         contents->AddFrame(commandFrameEventTree            , new TGLayoutHints(kLHintsExpandX | kLHintsExpandY));
         contents->AddFrame(commandFrameEcalHitBranch        , new TGLayoutHints(kLHintsExpandX | kLHintsExpandY));
         contents->AddFrame(commandFrameHcalHitBranch        , new TGLayoutHints(kLHintsExpandX | kLHintsExpandY));
         contents->AddFrame(commandFrameTrackerHitsBranch    , new TGLayoutHints(kLHintsExpandX | kLHintsExpandY));
         contents->AddFrame(commandFrameEcalScorePlaneBranch , new TGLayoutHints(kLHintsExpandX | kLHintsExpandY));
         contents->AddFrame(commandFrameEcalClusterBranch    , new TGLayoutHints(kLHintsExpandX | kLHintsExpandY));
         contents->AddFrame(commandFrameGotoEvent            , new TGLayoutHints(kLHintsExpandX | kLHintsExpandY));
         contents->AddFrame(commandFrameNextEvent            , new TGLayoutHints(kLHintsExpandX | kLHintsExpandY));
         contents->AddFrame(commandFrameColorClusters        , new TGLayoutHints(kLHintsExpandX | kLHintsExpandY));
         contents->AddFrame(commandFrameSimThresh            , new TGLayoutHints(kLHintsExpandX | kLHintsExpandY));
         AddFrame(contents, new TGLayoutHints(kLHintsExpandX | kLHintsExpandY));
         MapSubwindows();
         Resize(GetDefaultSize());
         MapWindow();
         manager_->FullRedraw3D(kTRUE);
         if ( verbose_ ) {
             std::cout << "done" << std::endl;
         }
     }
References ldmx::EveDetectorGeometry::getECAL(), ldmx::EveDetectorGeometry::getHCAL(), and ldmx::EveDetectorGeometry::getRecoilTracker().
~EventDisplay()
ldmx::EventDisplay::~EventDisplay () inline
Destructor Deletes hanging pointers from constructor and closes the TFile.
Definition at line 48 of file EventDisplay.h.
{
                 file_->Close();
                 delete file_;
                 delete tree_;
                 delete theDetector_;
                 delete eventObjects_;
                 delete textBoxGotoEvent_;
                 delete textBoxClustersCollName_;
                 delete textBoxSimThresh_;
                 delete textBoxEventTreeName_;
                 delete textBoxEcalRecHitsCollName_;
                 delete textBoxHcalRecHitsCollName_;
                 delete textBoxTrackerHitsCollName_;
                 delete textBoxEcalScorePlaneBranch_;
                 delete manager_;
             }
Member Function Documentation
ColorClusters()
void ldmx::EventDisplay::ColorClusters ()
Colors cluster objects and redraws.
Definition at line 366 of file EventDisplay.cxx.
{
         eventObjects_->ColorClusters();
         manager_->RegisterRedraw3D();
         manager_->FullRedraw3D(kFALSE, kTRUE);
     }
References ldmx::EventObjects::ColorClusters().
GetClustersCollInput()
void ldmx::EventDisplay::GetClustersCollInput ()
Gets clusters collection name from text box
Definition at line 237 of file EventDisplay.cxx.
{
         const TString clustersCollName = textBoxClustersCollName_->GetText();
         foundClusters_ = GetCollection( clustersCollName , ecalClusters_ );
         if (foundClusters_) {
             clustersCollName_ = clustersCollName;
             if (eventNum_ != -1) {
                 GotoEvent(eventNum_);
             }
         }
     }
References clustersCollName_, GetCollection(), and GotoEvent().
GetCollection()
template<typename T > bool ldmx::EventDisplay::GetCollection (const TString branchName, std::vector< T > & collection) inline
Attempts to get branch from event tree and set the address to be the input collection.
Parameters
branchName name of branch containing collection
collection vector that will be used in event display
Returns
bool successful check
Definition at line 103 of file EventDisplay.h.
{
                 TBranchElement *br = dynamic_cast<TBranchElement*>(tree_->GetBranch(branchName));
                 if ( br ) {
                     br->SetObject( &collection );
                     if ( verbose_ ) {
                         std::cout << "[ EventDisplay ] : Collection retrieved from branch \"" << branchName << "\"" << std::endl;
                     }
                     return true;
                 } else {
                     std::cout << "[ EventDisplay ] : No branch with name \"" << branchName << "\"" << std::endl;
                     return false;
                 }
             }
Referenced by GetClustersCollInput(), GetECALRecHitsCollInput(), GetEcalSimParticlesCollInput(), GetHCALRecHitsCollInput(), GetTrackerHitsCollInput(), SetEventTree(), and SetFile().
GetECALRecHitsCollInput()
void ldmx::EventDisplay::GetECALRecHitsCollInput ()
Gets ecalRecHits collection name from text box
Definition at line 198 of file EventDisplay.cxx.
{
         const TString ecalRecHitsCollName = textBoxEcalRecHitsCollName_->GetText();
         foundECALRecHits_ = GetCollection( ecalRecHitsCollName , ecalRecHits_ );
         if (foundECALRecHits_) {
             ecalRecHitsCollName_ = ecalRecHitsCollName;
             if (eventNum_ != -1) {
                 GotoEvent(eventNum_);
             }
         }
     }
References GetCollection(), and GotoEvent().
GetEcalSimParticlesCollInput()
void ldmx::EventDisplay::GetEcalSimParticlesCollInput ()
Gets ECAL Sim Particles Branch name from text box
Definition at line 250 of file EventDisplay.cxx.
{
         const TString ecalSimParticlesCollName = textBoxEcalScorePlaneBranch_->GetText();
         foundEcalSPHits_ = GetCollection( ecalSimParticlesCollName , ecalSimParticles_ );
         if (foundEcalSPHits_ ) {
             ecalSimParticlesCollName_ = ecalSimParticlesCollName;
             if (eventNum_ != -1) {
                 GotoEvent(eventNum_);
             }
         }
     }
References GetCollection(), and GotoEvent().
GetHCALRecHitsCollInput()
void ldmx::EventDisplay::GetHCALRecHitsCollInput ()
Gets hcalRecHits collection name from text box
Definition at line 211 of file EventDisplay.cxx.
{
         const TString hcalRecHitsCollName = textBoxHcalRecHitsCollName_->GetText();
         foundHCALRecHits_ = GetCollection( hcalRecHitsCollName , hcalRecHits_ );
         if (foundHCALRecHits_) {
             hcalRecHitsCollName_ = hcalRecHitsCollName;
             if (eventNum_ != -1) {
                 GotoEvent(eventNum_);
             }
         }
     }
References GetCollection(), and GotoEvent().
GetTrackerHitsCollInput()
void ldmx::EventDisplay::GetTrackerHitsCollInput ()
Gets trackerHits collection name from text box
Definition at line 224 of file EventDisplay.cxx.
{
         const TString trackerHitsCollName = textBoxTrackerHitsCollName_->GetText();
         foundTrackerHits_ = GetCollection( trackerHitsCollName , recoilHits_ );
         if (foundTrackerHits_) {
             trackerHitsCollName_ = trackerHitsCollName;
             if (eventNum_ != -1) {
                 GotoEvent(eventNum_);
             }
         }
     }
References GetCollection(), and GotoEvent().
GotoEvent() [1/2]
bool ldmx::EventDisplay::GotoEvent ()
Takes input of event index from text box.
Definition at line 312 of file EventDisplay.cxx.
{
         int event = atoi(textBoxGotoEvent_->GetText());
         if (event == 0 && std::string(textBoxGotoEvent_->GetText()) != "0") {
             std::cout << "[ EventDisplay ] : Invalid event number entered: \""
                 << textBoxGotoEvent_->GetText() << "\"" << std::endl;
             return false;
         }
         return GotoEvent(event);
     }
Referenced by GetClustersCollInput(), GetECALRecHitsCollInput(), GetEcalSimParticlesCollInput(), GetHCALRecHitsCollInput(), GetTrackerHitsCollInput(), NextEvent(), PreviousEvent(), and SetEventTree().
GotoEvent() [2/2]
bool ldmx::EventDisplay::GotoEvent (int event)
Goes to the input event index if it is not outside the bounds.
Destroys the elements from previous event and re-initializes the eventObjects_ instance. Draws all objects that were able to be found.
Parameters
event index for the event we want to go to.
Returns
bool success check
Definition at line 264 of file EventDisplay.cxx.
{
         manager_->GetCurrentEvent()->DestroyElements();
         eventObjects_->Initialize();
         if (event > eventNumMax_ || event < 0) {
             std::cout << "[ EventDisplay ] : Event number out of range." << std::endl;
             return false;
         }
         eventNum_ = event;
         if ( verbose_ ) {
             std::cout << "[ EventDisplay ] : Loading event " << event << "... " << std::flush;
         }
         tree_->GetEntry(eventNum_);
         if (foundECALRecHits_) {
             eventObjects_->drawECALHits(ecalRecHits_);
         }
         if (foundHCALRecHits_) {
             eventObjects_->drawHCALHits(hcalRecHits_);
         }
         if (foundClusters_) {
             eventObjects_->drawECALClusters(ecalClusters_);
         }
         if (foundTrackerHits_) {
             eventObjects_->drawRecoilHits(recoilHits_);
         }
         if (foundEcalSPHits_) {
             eventObjects_->drawECALSimParticles(ecalSimParticles_);
         }
         manager_->AddElement(eventObjects_->getHitCollections());
         manager_->AddElement(eventObjects_->getRecoObjects());
         manager_->Redraw3D(kFALSE);
         if ( verbose_ ) {
             std::cout << "done" << std::endl;
         }
         return true;
     }
References ldmx::EventObjects::drawECALClusters(), ldmx::EventObjects::drawECALHits(), ldmx::EventObjects::drawECALSimParticles(), ldmx::EventObjects::drawHCALHits(), ldmx::EventObjects::drawRecoilHits(), ldmx::EventObjects::getHitCollections(), ldmx::EventObjects::getRecoObjects(), and ldmx::EventObjects::Initialize().
NextEvent()
void ldmx::EventDisplay::NextEvent ()
Goes forward one event unless the current event number equals the maximum event number.
See also
GotoEvent(int)
Definition at line 188 of file EventDisplay.cxx.
{
         if (eventNumMax_ == eventNum_) {
             std::cout << "[ EventDisplay ] : Already at last event in file." << std::endl;
             return;
         }
         GotoEvent(eventNum_ + 1);
     }
References GotoEvent().
PreviousEvent()
void ldmx::EventDisplay::PreviousEvent ()
Goes back one event unless the current event number is not positive.
See also
GotoEvent(int)
Definition at line 178 of file EventDisplay.cxx.
{
         if (eventNum_ <= 0) {
             std::cout << "[ EventDisplay ] : Already at first event in file." << std::endl;
             return;
         }
         GotoEvent(eventNum_ - 1);
     }
References GotoEvent().
SetEventTree()
bool ldmx::EventDisplay::SetEventTree ()
Sets event tree from input text box.
Returns
bool success check
Definition at line 324 of file EventDisplay.cxx.
{
         const TString treeName = textBoxEventTreeName_->GetText();
         TTree* tree = (TTree*) file_->Get(treeName);
         if (!tree) {
             std::cout << "[ EventDisplay ] : Input file contains no tree \"" << treeName << "\"" << std::endl;
             return false;
         } else if ( verbose_ ) {
             std::cout << "[ EventDisplay ] : Event tree set to \"" << treeName << "\"" << std::endl;
         }
         tree_ = tree;
         eventTreeName_ = treeName;
         foundECALRecHits_   = GetCollection( ecalRecHitsCollName_ , ecalRecHits_ );
         foundHCALRecHits_   = GetCollection( hcalRecHitsCollName_ , hcalRecHits_ );
         foundClusters_      = GetCollection( clustersCollName_ , ecalClusters_ );
         foundTrackerHits_   = GetCollection( trackerHitsCollName_ , recoilHits_ );
         foundEcalSPHits_    = GetCollection( ecalSimParticlesCollName_ , ecalSimParticles_ );
         return GotoEvent(eventNum_);
     }
References clustersCollName_, GetCollection(), and GotoEvent().
SetFile()
bool ldmx::EventDisplay::SetFile (const TString file)
Opens input file and attempts to obtain the necessary information from it.
Attempts to import the event objects from the event tree using the 'Get...' methods below.
Parameters
file name of file with events
Returns
true if successfully opened file and found tree named eventTreeName_
false unable to open file or find tree named eventTreeName_
Definition at line 147 of file EventDisplay.cxx.
{
         file_ = TFile::Open(file);
         if (!file_) {
             std::cout << "[ EventDisplay ] : Input root file cannot be opened." << std::endl;
             return false;
         } else if ( verbose_ ) {
             std::cout << "[ EventDisplay ] : Input root file opened successfully." << std::endl;
         }
         tree_ = (TTree*) file_->Get(eventTreeName_);
         if (!tree_) {
             std::cout << "[ EventDisplay ] : Input file contains no tree \"" << eventTreeName_ << "\"" << std::endl;
             return false;
         } else if ( verbose_ ) {
             std::cout << "[ EventDisplay ] : Event tree retrieved from input file." << std::endl;
         }
         eventNumMax_ = tree_->GetEntriesFast()-1;
         foundECALRecHits_   = GetCollection( ecalRecHitsCollName_ , ecalRecHits_ );
         foundHCALRecHits_   = GetCollection( hcalRecHitsCollName_ , hcalRecHits_ );
         foundClusters_      = GetCollection( clustersCollName_ , ecalClusters_ );
         foundTrackerHits_   = GetCollection( trackerHitsCollName_ , recoilHits_ );
         foundEcalSPHits_    = GetCollection( ecalSimParticlesCollName_ , ecalSimParticles_ );
         return true;
     }
References clustersCollName_, and GetCollection().
Referenced by main().
SetSimThresh()
bool ldmx::EventDisplay::SetSimThresh ()
Sets threshold energy from a SimParticle to be drawn from text box. Re-draws the display.
Returns
bool success check
Definition at line 347 of file EventDisplay.cxx.
{
         double thresh = atof(textBoxSimThresh_->GetText());
         if (thresh == 0 && std::string(textBoxSimThresh_->GetText()) != "0") {
             std::cout << "[ EventDisplay ] : Invalid sim energy threshold entered: \""
                 << textBoxSimThresh_->GetText() << "\"" << std::endl;
             return false;
         } else if ( verbose_ ) {
             std::cout << "[ EventDisplay ] : Setting SimParticle energy threshold to " << thresh << std::endl;
         }
         eventObjects_->SetSimThresh(thresh);
         manager_->RegisterRedraw3D();
         manager_->FullRedraw3D(kFALSE, kTRUE);
         return true;
     }
References ldmx::EventObjects::SetSimThresh().
Member Data Documentation
clustersCollName_
TString ldmx::EventDisplay::clustersCollName_ = "ecalClusters_recon" private
maximum event index for the current tree
Definition at line 199 of file EventDisplay.h.
Referenced by GetClustersCollInput(), SetEventTree(), and SetFile().
The documentation for this class was generated from the following files:
EventDisplay/include/EventDisplay/EventDisplay.h
EventDisplay/src/EventDisplay.cxx