LDMX Software: ldmx::TrackerVetoProcessor Class Reference
ldmx::TrackerVetoProcessor Class Reference
Public Member Functions
TrackerVetoProcessor (const std::string &name, Process &process)
~TrackerVetoProcessor ()
void produce (Event &event)
Public Member Functions inherited from ldmx::Producer
Producer (const std::string &name, Process &process)
Public Member Functions inherited from ldmx::EventProcessor
EventProcessor (const std::string &name, Process &process)
virtual ~EventProcessor ()
virtual void configure (Parameters &parameters)
virtual void onNewRun (const RunHeader &runHeader)
virtual void onFileOpen (EventFile &eventFile)
virtual void onFileClose (EventFile &eventFile)
virtual void onProcessStart ()
virtual void onProcessEnd ()
TDirectory * getHistoDirectory ()
void setStorageHint (ldmx::StorageControlHint hint)
void setStorageHint (ldmx::StorageControlHint hint, const std::string &purposeString)
int getLogFrequency () const
int getRunNumber () const
void createHistograms (const std::vector< Parameters > &histos)
Additional Inherited Members
Static Public Member Functions inherited from ldmx::EventProcessor
static void declare (const std::string &classname, int classtype, EventProcessorMaker *)
Static Public Attributes inherited from ldmx::Producer
static const int CLASSTYPE {1}
Protected Member Functions inherited from ldmx::EventProcessor
void abortEvent ()
Protected Attributes inherited from ldmx::EventProcessor
HistogramHelper histograms_
Interface class for making and filling histograms.
NtupleManager & ntuple_ {NtupleManager::getInstance()}
Manager for any ntuples.
logging::logger theLog_
The logger for this EventProcessor.
Detailed Description
Definition at line 22 of file TrackerVetoProcessor.h.
Constructor & Destructor Documentation
TrackerVetoProcessor()
ldmx::TrackerVetoProcessor::TrackerVetoProcessor (const std::string & name, Process & process)
Constructor
Definition at line 25 of file TrackerVetoProcessor.cxx.
                                                                                       :
             Producer(name, process) { }
~TrackerVetoProcessor()
ldmx::TrackerVetoProcessor::~TrackerVetoProcessor ()
Destructor
Definition at line 28 of file TrackerVetoProcessor.cxx.
 { }
Member Function Documentation
produce()
void ldmx::TrackerVetoProcessor::produce (Event & event) virtual
Run the processor and create a collection of results which indicate if the event passes/fails the Hcal veto.
Parameters
event The event to process.
Implements ldmx::Producer.
Definition at line 30 of file TrackerVetoProcessor.cxx.
{
         // Get the collection of simulated particles from the event
         auto particleMap{event.getMap< int, SimParticle >("SimParticles")};
         // Search for the recoil electron
         auto [recoilTrackID, recoilElectron] = Analysis::getRecoil(particleMap);
         // Find the target scoring plane hit associated with the recoil
         // electron and extract the momentum
         double p{-1}, pt{-1}, px{-9999}, py{-9999}, pz{-9999};
         const SimTrackerHit *recoilTrackerHit = nullptr;
         if (event.exists("TargetScoringPlaneHits")) {
             // Get the collection of simulated particles from the event
             const std::vector<SimTrackerHit> spHits = event.getCollection<SimTrackerHit>("TargetScoringPlaneHits");
             for (const SimTrackerHit &hit : spHits ) {
                 if (
                     (hit.getTrackID() == recoilTrackID) /*hit blamed on recoil*/ and
                     (hit.getLayerID() == 2) /*hit in outgoing layer*/ and
                     (hit.getMomentum()[2] > 0) /*particle leaving target*/
                    ) {
                     recoilTrackerHit = &hit;
                     break;
                 }
             }//check all target scoring plane hits
             if ( recoilTrackerHit ) {
                 TVector3 recoilP(recoilTrackerHit->getMomentum().data());
                 p  = recoilP.Mag();
                 pt = recoilP.Pt();
                 px = recoilP.Px();
                 py = recoilP.Py();
                 pz = recoilP.Pz();
             }
         }
         bool recoilIsFindable{false};
         TrackMaps map;
         if (event.exists("FindableTracks")) {
             // Get the collection of simulated particles from the event
             const std::vector<FindableTrackResult> tracks = event.getCollection<FindableTrackResult>("FindableTracks");
             map = Analysis::getFindableTrackMaps(tracks);
             auto it = map.findable.find(recoilTrackID);
             if ( it != map.findable.end()) recoilIsFindable = true;
         }
         bool passesTrackVeto{false};
         if ((map.findable.size() == 1) && recoilIsFindable && (p < 1200)) passesTrackVeto = true;
         TrackerVetoResult result;
         result.setVetoResult(passesTrackVeto);
         if (passesTrackVeto) {
             setStorageHint(hint_shouldKeep);
         } else {
             setStorageHint(hint_shouldDrop);
         }
         event.add("TrackerVeto", result);
     }
References ldmx::Event::exists(), ldmx::SimTrackerHit::getMomentum(), ldmx::EventProcessor::setStorageHint(), and ldmx::TrackerVetoResult::setVetoResult().
The documentation for this class was generated from the following files:
EventProc/include/EventProc/TrackerVetoProcessor.h
EventProc/src/TrackerVetoProcessor.cxx