LDMX Software: simcore::biasoperators::DarkBrem Class Reference
simcore::biasoperators::DarkBrem Class Reference
#include <DarkBrem.h>
Public Member Functions
DarkBrem (std::string name, const framework::config::Parameters &p)
~DarkBrem ()
G4VBiasingOperation * ProposeOccurenceBiasingOperation (const G4Track *track, const G4BiasingProcessInterface *callingProcess) final override
virtual std::string getProcessToBias () const
Return the name of the process this operator biases.
virtual std::string getParticleToBias () const
Return the name of the particle this operator biases.
virtual std::string getVolumeToBias () const
Return the volume this operator biases.
virtual void RecordConfig (ldmx::RunHeader &header) const
Public Member Functions inherited from simcore::XsecBiasingOperator
XsecBiasingOperator (std::string name, const framework::config::Parameters &parameters)
virtual ~XsecBiasingOperator ()
virtual G4VBiasingOperation * ProposeOccurenceBiasingOperation (const G4Track *track, const G4BiasingProcessInterface *callingProcess)=0
void StartRun ()
virtual std::string getProcessToBias () const =0
virtual std::string getParticleToBias () const =0
virtual std::string getVolumeToBias () const =0
virtual void RecordConfig (ldmx::RunHeader &header) const =0
Private Attributes
std::string volume_
volume we want to bias in
double factor_
factor we want to bias by
bool bias_all_
should we bias all electrons? (or only the primary)
Additional Inherited Members
Public Types inherited from simcore::XsecBiasingOperator
using Factory = ::simcore::Factory< XsecBiasingOperator, std::shared_ptr< XsecBiasingOperator >, std::string, const framework::config::Parameters & >
Protected Member Functions inherited from simcore::XsecBiasingOperator
G4VBiasingOperation * BiasedXsec (double biased_xsec)
bool processIsBiased (std::string process)
G4VBiasingOperation * ProposeFinalStateBiasingOperation (const G4Track *, const G4BiasingProcessInterface *)
G4VBiasingOperation * ProposeNonPhysicsBiasingOperation (const G4Track *, const G4BiasingProcessInterface *)
Protected Attributes inherited from simcore::XsecBiasingOperator
G4BOptnChangeCrossSection * xsecOperation_ {nullptr}
G4ProcessManager * processManager_ {nullptr}
Detailed Description
Bias operator for the dark brem process
Definition at line 16 of file DarkBrem.h.
Constructor & Destructor Documentation
DarkBrem()
simcore::biasoperators::DarkBrem::DarkBrem (std::string name, const framework::config::Parameters & p)
Constructor
Calls base class constructor and allows access to configuration parameters.
Definition at line 12 of file DarkBrem.cxx.
    : XsecBiasingOperator(name, p) {
  volume_ = p.getParameter<std::string>("volume");
  factor_ = p.getParameter<double>("factor");
  bias_all_ = p.getParameter<bool>("bias_all");
}
References bias_all_, factor_, framework::config::Parameters::getParameter(), and volume_.
~DarkBrem()
simcore::biasoperators::DarkBrem::~DarkBrem () inline
Destructor
Blank right now
Definition at line 31 of file DarkBrem.h.
{}
Member Function Documentation
getParticleToBias()
virtual std::string simcore::biasoperators::DarkBrem::getParticleToBias () const inline virtual
Return the name of the particle this operator biases.
Implements simcore::XsecBiasingOperator.
Definition at line 56 of file DarkBrem.h.
{ return "e-"; }
getProcessToBias()
virtual std::string simcore::biasoperators::DarkBrem::getProcessToBias () const inline virtual
Return the name of the process this operator biases.
Implements simcore::XsecBiasingOperator.
Definition at line 51 of file DarkBrem.h.
{
    return G4DarkBremsstrahlung::PROCESS_NAME;
  }
References G4DarkBremsstrahlung::PROCESS_NAME.
getVolumeToBias()
virtual std::string simcore::biasoperators::DarkBrem::getVolumeToBias () const inline virtual
Return the volume this operator biases.
Implements simcore::XsecBiasingOperator.
Definition at line 59 of file DarkBrem.h.
{ return volume_; }
References volume_.
ProposeOccurenceBiasingOperation()
G4VBiasingOperation * simcore::biasoperators::DarkBrem::ProposeOccurenceBiasingOperation (const G4Track * track, const G4BiasingProcessInterface * callingProcess) final override virtual
Calculate the biased cross section given the input process and track. This allows for us to have access to the current information about the track while calculating the biased cross section.
See also
XsecBiasingOperator::BiasedXsec
Parameters
[in] track const pointer to track to Bias
[in] callingProcess process that might be biased by this operator
Returns
Method that returns the biasing operation that will be used to bias the occurence of events.
Implements simcore::XsecBiasingOperator.
Definition at line 19 of file DarkBrem.cxx.
{
  std::string currentProcess =
      callingProcess->GetWrappedProcess()->GetProcessName();
  if (currentProcess.compare(this->getProcessToBias()) == 0) {
    // bias only the primary particle if we don't want to bias all particles
    if (not bias_all_ and track->GetParentID() != 0) return 0;
    G4double interactionLength =
        callingProcess->GetWrappedProcess()->GetCurrentInteractionLength();
    double dbXsecUnbiased = 1. / interactionLength;
    double dbXsecBiased = dbXsecUnbiased * factor_;
    if (G4RunManager::GetRunManager()->GetVerboseLevel() > 1) {
      std::cout << "[ DarkBremXsecBiasingOperator ]: "
                << " Unbiased DBrem xsec: " << dbXsecUnbiased
                << " -> Biased xsec: " << dbXsecBiased << std::endl;
    }
    return BiasedXsec(dbXsecBiased);
  } else
    return 0;
}
References bias_all_, simcore::XsecBiasingOperator::BiasedXsec(), and factor_.
RecordConfig()
void simcore::biasoperators::DarkBrem::RecordConfig (ldmx::RunHeader & header) const virtual
Record the configuration of this biasing operator into the run header
Parameters
[in,out] header RunHeader to record configuration to
Implements simcore::XsecBiasingOperator.
Definition at line 44 of file DarkBrem.cxx.
{
  h.setIntParameter("BiasOperator::DarkBrem::Bias All Electrons", bias_all_);
  h.setFloatParameter("BiasOperator::DarkBrem::Factor", factor_);
  h.setStringParameter("BiasOperator::DarkBrem::Volume", volume_);
}
References bias_all_, factor_, ldmx::RunHeader::setFloatParameter(), ldmx::RunHeader::setIntParameter(), ldmx::RunHeader::setStringParameter(), and volume_.
Member Data Documentation
bias_all_
bool simcore::biasoperators::DarkBrem::bias_all_ private
should we bias all electrons? (or only the primary)
Definition at line 103 of file DarkBrem.h.
Referenced by DarkBrem(), ProposeOccurenceBiasingOperation(), and RecordConfig().
factor_
double simcore::biasoperators::DarkBrem::factor_ private
factor we want to bias by
Definition at line 100 of file DarkBrem.h.
Referenced by DarkBrem(), ProposeOccurenceBiasingOperation(), and RecordConfig().
volume_
std::string simcore::biasoperators::DarkBrem::volume_ private
volume we want to bias in
DEBUG FUNCTION This function is called by the biasing interface class during PostStepDoIt. You can observe the particle change that was produced by the process and the weight that will be multiplied into this particle change.
This is called inside G4VBiasingOperator::ReportOperationApplied which is called inside G4BiasingProcessInterface::PostStepDoIt void OperationApplied(const G4BiasingProcessInterface* callingProcess, G4BiasingAppliedCase biasingCase, G4VBiasingOperation* operationApplied, G4double weight, G4VBiasingOperation* finalStateOpApplied, const G4VParticleChange* particleChangeProduced) { std::string currentProcess = callingProcess->GetWrappedProcess()->GetProcessName(); if (currentProcess.compare(this->getProcessToBias()) == 0) { std::cout << "DB Final State Biasing Operator Applied: " << callingProcess->GetProcessName() << " -> " << weight*particleChangeProduced->GetWeight() << std::endl; } }
Definition at line 97 of file DarkBrem.h.
Referenced by DarkBrem(), getVolumeToBias(), and RecordConfig().
The documentation for this class was generated from the following files:
SimCore/include/SimCore/BiasOperators/DarkBrem.h
SimCore/src/SimCore/BiasOperators/DarkBrem.cxx