LDMX Software: ecal::EcalDigiProducer Class Reference
ecal::EcalDigiProducer Class Reference
Performs basic ECal digitization.
#include <EcalDigiProducer.h>
Public Member Functions
EcalDigiProducer (const std::string &name, framework::Process &process)
virtual ~EcalDigiProducer ()
virtual void configure (framework::config::Parameters &)
virtual void produce (framework::Event &event)
Public Member Functions inherited from framework::Producer
Producer (const std::string &name, Process &process)
virtual void beforeNewRun (ldmx::RunHeader &header)
Public Member Functions inherited from framework::EventProcessor
EventProcessor (const std::string &name, Process &process)
virtual ~EventProcessor ()
virtual void onNewRun (const ldmx::RunHeader &runHeader)
virtual void onFileOpen (EventFile &eventFile)
virtual void onFileClose (EventFile &eventFile)
virtual void onProcessStart ()
virtual void onProcessEnd ()
template<class T >
const T & getCondition (const std::string &condition_name)
TDirectory * getHistoDirectory ()
void setStorageHint (framework::StorageControlHint hint)
void setStorageHint (framework::StorageControlHint hint, const std::string &purposeString)
int getLogFrequency () const
int getRunNumber () const
std::string getName () const
void createHistograms (const std::vector< framework::config::Parameters > &histos)
Private Attributes
std::string inputCollName_
input hit collection name
std::string inputPassName_
input pass name
std::string digiCollName_
output hit collection name
double clockCycle_
Time interval for chip clock in ns.
int nADCs_
Depth of ADC buffer.
int iSOI_
Index for the Sample Of Interest in the list of digi samples.
double MeV_
Conversion from energy in MeV to voltage in mV.
bool zero_suppression_
double avgNoiseRMS_
Store Average Noise RMS for no-zero-suppresion noise emulation mode.
bool noise_ {true}
std::unique_ptr< ldmx::HgcrocEmulator > hgcroc_
Hgcroc Emulator to digitize analog voltage signals.
int nTotalChannels_
Total number of channels in the ECal.
double ns_
Conversion from time in ns to ticks of the internal clock.
std::unique_ptr< ldmx::NoiseGenerator > noiseGenerator_
Generates noise hits based off of number of cells that are not hit.
std::unique_ptr< TRandom3 > noiseInjector_
Generates Gaussian noise on top of real hits.
Additional Inherited Members
Static Public Member Functions inherited from framework::EventProcessor
static void declare (const std::string &classname, int classtype, EventProcessorMaker *)
Static Public Attributes inherited from framework::Producer
static const int CLASSTYPE {1}
Protected Member Functions inherited from framework::EventProcessor
void abortEvent ()
Protected Attributes inherited from framework::EventProcessor
HistogramHelper histograms_
Interface class for making and filling histograms.
NtupleManager & ntuple_ {NtupleManager::getInstance()}
Manager for any ntuples.
logging::logger theLog_
The logger for this EventProcessor.
Detailed Description
Performs basic ECal digitization.
Definition at line 37 of file EcalDigiProducer.h.
Constructor & Destructor Documentation
EcalDigiProducer()
ecal::EcalDigiProducer::EcalDigiProducer (const std::string & name, framework::Process & process)
Constructor Makes unique noise generator and injector for this class
Definition at line 13 of file EcalDigiProducer.cxx.
     : Producer(name, process) {
   // noise generator by default uses a Gausian model for noise
   //  i.e. It assumes the noise is distributed around a mean (setPedestal)
   //  with a certain RMS (setNoise) and then calculates
   //  how many hits should be generated for a given number of empty
   //  channels and a minimum readout value (setNoiseThreshold)
   noiseGenerator_ = std::make_unique<ldmx::NoiseGenerator>();
 }
References noiseGenerator_.
~EcalDigiProducer()
ecal::EcalDigiProducer::~EcalDigiProducer () virtual
Destructor Deletes digi collection if it has been created
Definition at line 24 of file EcalDigiProducer.cxx.
 {}
Member Function Documentation
configure()
void ecal::EcalDigiProducer::configure (framework::config::Parameters & ps) virtual
Configure this producer from the python configuration. Sets event constants and configures the noise generator, noise injector, and pulse function. Creates digi collection
Reimplemented from framework::EventProcessor.
Definition at line 26 of file EcalDigiProducer.cxx.
{
   // settings of readout chip
   //  used  in actual digitization
   auto hgcrocParams = ps.getParameter<framework::config::Parameters>("hgcroc");
   hgcroc_ = std::make_unique<ldmx::HgcrocEmulator>(hgcrocParams);
   clockCycle_ = hgcrocParams.getParameter<double>("clockCycle");
   nADCs_ = hgcrocParams.getParameter<int>("nADCs");
   iSOI_ = hgcrocParams.getParameter<int>("iSOI");
   noise_ = hgcrocParams.getParameter<bool>("noise");
   // collection names
   inputCollName_ = ps.getParameter<std::string>("inputCollName");
   inputPassName_ = ps.getParameter<std::string>("inputPassName");
   digiCollName_ = ps.getParameter<std::string>("digiCollName");
   zero_suppression_ = ps.getParameter<bool>("zero_suppression");
   // physical constants
   //  used to calculate unit conversions
   MeV_ = ps.getParameter<double>("MeV");
   // Time -> clock counts conversion
   //  time [ns] * ( 2^10 / max time in ns ) = clock counts
   ns_ = 1024. / clockCycle_;
   // Configure generator that will produce noise hits in empty channels
   double readoutThreshold = ps.getParameter<double>("avgReadoutThreshold");
   double pedestal = ps.getParameter<double>("avgPedestal");
   // saved because it might be used later
   avgNoiseRMS_ = hgcrocParams.getParameter<double>("noiseRMS");
   // rms noise in mV
   noiseGenerator_->setNoise(avgNoiseRMS_);
   // mean noise amplitude (if using Gaussian Model for the noise) in mV
   noiseGenerator_->setPedestal(pedestal);
   // threshold for readout in mV
   noiseGenerator_->setNoiseThreshold(readoutThreshold);
 }
References avgNoiseRMS_, clockCycle_, digiCollName_, framework::config::Parameters::getParameter(), hgcroc_, inputCollName_, inputPassName_, iSOI_, MeV_, nADCs_, noise_, noiseGenerator_, ns_, and zero_suppression_.
produce()
void ecal::EcalDigiProducer::produce (framework::Event & event) virtual
Simulates measurement of pulse and creates digi collection for input event.
HACK ALERT The shifting of the time should not be done this sloppily. In reality, each chip has a set time phase that it samples at (relative to target), so the time shifting should be at the emulator level.
Implements framework::Producer.
Definition at line 64 of file EcalDigiProducer.cxx.
{
   // Need to handle seeding on the first event
   if (!noiseGenerator_->hasSeed()) {
     const auto& rseed = getCondition<framework::RandomNumberSeedService>(
         framework::RandomNumberSeedService::CONDITIONS_OBJECT_NAME);
     noiseGenerator_->seedGenerator(
         rseed.getSeed("EcalDigiProducer::NoiseGenerator"));
   }
   if (noiseInjector_.get() == nullptr) {
     const auto& rseed = getCondition<framework::RandomNumberSeedService>(
         framework::RandomNumberSeedService::CONDITIONS_OBJECT_NAME);
     noiseInjector_ = std::make_unique<TRandom3>(
         rseed.getSeed("EcalDigiProducer::NoiseInjector"));
   }
   if (!hgcroc_->hasSeed()) {
     const auto& rseed = getCondition<framework::RandomNumberSeedService>(
         framework::RandomNumberSeedService::CONDITIONS_OBJECT_NAME);
     hgcroc_->seedGenerator(rseed.getSeed("EcalDigiProducer::HgcrocEmulator"));
   }
   hgcroc_->condition(getCondition<conditions::DoubleTableCondition>("EcalHgcrocConditions"));
   // Empty collection to be filled
   ldmx::HgcrocDigiCollection ecalDigis;
   ecalDigis.setNumSamplesPerDigi(nADCs_);
   ecalDigis.setSampleOfInterestIndex(iSOI_);
   std::set<unsigned int>
       filledDetIDs;  // detector IDs that already have a hit in them
   /******************************************************************************************
    * HGCROC Emulation on Simulated Hits
    *****************************************************************************************/
   // std::cout << "Sim Hits" << std::endl;
   // get simulated ecal hits from Geant4
   //  the class EcalHitIO in the SimApplication module handles the translation
   //  from G4CalorimeterHits to SimCalorimeterHits this class ensures that only
   //  one SimCalorimeterHit is generated per cell, but multiple "contributions"
   //  are still handled within SimCalorimeterHit
   auto ecalSimHits{event.getCollection<ldmx::SimCalorimeterHit>(
       inputCollName_, inputPassName_)};
   /* debug printout
   std::cout << "Energy to Voltage Conversion: " << MeV_ << " mV/MeV" <<
   std::endl;
    */
   for (auto const& simHit : ecalSimHits) {
     std::vector<std::pair<double,double>> pulses_at_chip;
     for (int iContrib = 0; iContrib < simHit.getNumberOfContribs();
          iContrib++) {
       /* debug printout
       std::cout << simHit.getContrib(iContrib).edep << " MeV" << std::endl;
        */
       pulses_at_chip.emplace_back(
         simHit.getContrib(iContrib).edep * MeV_,
         simHit.getContrib(iContrib).time  // global time (t=0ns at target)
           - simHit.getPosition().at(2) /
                 299.702547  // shift light-speed particle traveling along z
       );
     }
     unsigned int hitID = simHit.getID();
     filledDetIDs.insert(hitID);
     /* debug printout
     std::cout << hitID << " "
         << simHit.getEdep()
         << " MeV at "
         << simHit.getTime() - simHit.getPosition().at(2)/299.702547
         << std::endl;
      */
     // container emulator uses to write out samples and
     // transfer samples into the digi collection
     std::vector<ldmx::HgcrocDigiCollection::Sample> digiToAdd;
     if (hgcroc_->digitize(hitID, pulses_at_chip, digiToAdd)) {
       ecalDigis.addDigi(hitID, digiToAdd);
     }
   }
   /******************************************************************************************
    * Noise Simulation on Empty Channels
    *****************************************************************************************/
   if (noise_) {
     // std::cout << "Noise Hits" << std::endl;
     // put noise into some empty channels
     // geometry constants
     //  These are used in the noise generation so that we can randomly
     //  distribute the noise uniformly throughout the ECal channels.
     const auto& hexGeom = getCondition<ldmx::EcalHexReadout>(
         ldmx::EcalHexReadout::CONDITIONS_OBJECT_NAME);
     int nEcalLayers = hexGeom.getNumLayers();
     int nModulesPerLayer = hexGeom.getNumModulesPerLayer();
     int nCellsPerModule = hexGeom.getNumCellsPerModule();
     int numEmptyChannels = nEcalLayers * nModulesPerLayer * nCellsPerModule -
                            ecalDigis.getNumDigis();
     if (zero_suppression_) {
       // noise generator gives us a list of noise amplitudes [mV] that randomly
       // populate the empty channels and are above the readout threshold
       auto noiseHitAmplitudes{
           noiseGenerator_->generateNoiseHits(numEmptyChannels)};
       std::vector<std::pair<double,double>> fake_pulse(1,{0.,0.});
       for (double noiseHit : noiseHitAmplitudes) {
         // generate detector ID for noise hit
         // making sure that it is in an empty channel
         unsigned int noiseID;
         do {
           int layerID = noiseInjector_->Integer(nEcalLayers);
           int moduleID = noiseInjector_->Integer(nModulesPerLayer);
           int cellID = noiseInjector_->Integer(nCellsPerModule);
           auto detID = ldmx::EcalID(layerID, moduleID, cellID);
           noiseID = detID.raw();
         } while (filledDetIDs.find(noiseID) != filledDetIDs.end());
         filledDetIDs.insert(noiseID);
         // noise generator gives the amplitude above the readout threshold
         //  we need to convert it to the amplitude above the pedestal
         noiseHit +=
             hgcroc_->gain(noiseID) *
             (hgcroc_->readoutThreshold(noiseID) - hgcroc_->pedestal(noiseID));
         // create a digi as put it into the collection
         ecalDigis.addDigi(noiseID, hgcroc_->noiseDigi(noiseID, noiseHit));
       }  // loop over noise amplitudes
     } else {
       // no zero suppression, put some noise emulation in **all** empty channels
       // loop through all channels
       for (int layer{0}; layer < nEcalLayers; layer++) {
         for (int module{0}; module < nModulesPerLayer; module++) {
           for (int cell{0}; cell < nCellsPerModule; cell++) {
             unsigned int channel{ldmx::EcalID(layer,module,cell).raw()};
             // check if channel already has a (real) hit in it
             if (filledDetIDs.find(channel) != filledDetIDs.end())
               continue;
             // create a digi as put it into the collection
             ecalDigis.addDigi(channel, hgcroc_->noiseDigi(channel));
           }  // cells in each module
         }    // modules in each layer
       }      // layers in ECal
     }        // yes or no zero suppression
   }          // if we should do the noise
   event.add(digiCollName_, ecalDigis);
   return;
 }  // produce
References ldmx::HgcrocDigiCollection::addDigi(), framework::RandomNumberSeedService::CONDITIONS_OBJECT_NAME, digiCollName_, ldmx::SimCalorimeterHit::getID(), ldmx::HgcrocDigiCollection::getNumDigis(), hgcroc_, inputCollName_, inputPassName_, iSOI_, MeV_, nADCs_, noise_, noiseGenerator_, noiseInjector_, ldmx::DetectorID::raw(), ldmx::HgcrocDigiCollection::setNumSamplesPerDigi(), ldmx::HgcrocDigiCollection::setSampleOfInterestIndex(), and zero_suppression_.
Member Data Documentation
noise_
bool ecal::EcalDigiProducer::noise_ {true} private
Put noise into empty channels, not configurable, only helpful in development
Definition at line 110 of file EcalDigiProducer.h.
Referenced by configure(), and produce().
zero_suppression_
bool ecal::EcalDigiProducer::zero_suppression_ private
When emulating noise in empty channels, do we zero suppress?
There are two ways to emulate the noise in the chip: 1) (with zero suppression) Use the NoiseGenerator to get a list of amplitudes (about 3-5 on avg) and put those noise hits which are above the readout threshold in random empty channels. 2) (without zero suppresion) Go through all channels and put noise in each channel that doesn't have a real hit in it. This will mean many channels with have a DIGI below readout threshold.
Definition at line 100 of file EcalDigiProducer.h.
Referenced by configure(), and produce().
The documentation for this class was generated from the following files:
Ecal/include/Ecal/EcalDigiProducer.h
Ecal/src/Ecal/EcalDigiProducer.cxx