LDMX Software: framework::HistogramPool Class Reference
framework::HistogramPool Class Reference
#include <Histograms.h>
Public Member Functions
HistogramPool (HistogramPool const &)=delete
Hide copy constructor.
void operator= (HistogramPool const &)=delete
Hide assignment operator.
void insert (const std::string &name, TH1 *hist)
TH1 * get (const std::string &name)
Static Public Member Functions
static HistogramPool & getInstance ()
Access the single instance of HistogramPool by reference.
Private Member Functions
HistogramPool ()
Private Attributes
std::unordered_map< std::string, TH1 * > histograms_
Detailed Description
Singleton class used to create and pool histograms.
Helpful for managing all those TH1 pointers by name instead of using variables.
Definition at line 27 of file Histograms.h.
Constructor & Destructor Documentation
HistogramPool()
framework::HistogramPool::HistogramPool () private
Private constructor to prevent instantiation
Sets some style options as well.
Definition at line 18 of file Histograms.cxx.
{
  gStyle->SetOptStat(0);
  gStyle->SetGridColor(17);
  gStyle->SetFrameBorderMode(0);
  gStyle->SetTitleOffset(1.2, "yx");
  gStyle->SetTitleFontSize(25);
  gStyle->SetPadBottomMargin(0.1);
  gStyle->SetPadTopMargin(0.01);
  gStyle->SetPadLeftMargin(0.1);
  gStyle->SetPadRightMargin(0.09);
  gStyle->SetPadGridX(1);
  gStyle->SetPadGridY(1);
  gStyle->SetPadTickX(1);
  gStyle->SetPadTickY(1);
  gStyle->SetHistLineWidth(2);
}
Member Function Documentation
get()
TH1 * framework::HistogramPool::get (const std::string & name)
Get a histogram using its name.
Checks if histogram exists.
Returns
Retrieve the histogram named "name" from the pool.
Definition at line 45 of file Histograms.cxx.
{
  auto histo = histograms_.find(name);
  if (histo == histograms_.end()) {
    EXCEPTION_RAISE("InvalidArg", "Histogram " + name + " not found in pool.");
  }
  return histograms_[name];
}
References histograms_.
Referenced by framework::HistogramHelper::get().
getInstance()
HistogramPool & framework::HistogramPool::getInstance () static
Access the single instance of HistogramPool by reference.
Definition at line 37 of file Histograms.cxx.
{
  // Create an instance of HistogramPool if needed
  //  Guarnteed to be destroyed, instantiaed on first use
  static HistogramPool instance;
  return instance;
}
Referenced by framework::HistogramHelper::create(), and framework::HistogramHelper::get().
insert()
void framework::HistogramPool::insert (const std::string & name, TH1 * hist) inline
Insert a histogram into the pool
Note
Does not check for any doubling of names!
Definition at line 54 of file Histograms.h.
{ histograms_[name] = hist; }
References histograms_.
Referenced by framework::HistogramHelper::create().
Member Data Documentation
histograms_
std::unordered_map<std::string, TH1*> framework::HistogramPool::histograms_ private
Container for all histograms.
Definition at line 30 of file Histograms.h.
Referenced by get(), and insert().
The documentation for this class was generated from the following files:
Framework/include/Framework/Histograms.h
Framework/src/Framework/Histograms.cxx