LDMX Software: packing::SingleSubsystemPacker Class Reference
packing::SingleSubsystemPacker Class Reference
#include <SingleSubsystemPacker.h>
Public Member Functions
SingleSubsystemPacker (const std::string &name, framework::Process &p)
normal constructor
virtual ~SingleSubsystemPacker ()
empty destructor
void configure (framework::config::Parameters &ps) final override
void analyze (const framework::Event &event) final override
Public Member Functions inherited from framework::Analyzer
Analyzer (const std::string &name, Process &process)
virtual void analyze (const Event &event)=0
Public Member Functions inherited from framework::EventProcessor
EventProcessor (const std::string &name, Process &process)
virtual ~EventProcessor ()
virtual void configure (framework::config::Parameters &parameters)
virtual void onNewRun (const ldmx::RunHeader &runHeader)
virtual void onFileOpen (EventFile &eventFile)
virtual void onFileClose (EventFile &eventFile)
virtual void onProcessStart ()
virtual void onProcessEnd ()
template<class T >
const T & getCondition (const std::string &condition_name)
TDirectory * getHistoDirectory ()
void setStorageHint (framework::StorageControlHint hint)
void setStorageHint (framework::StorageControlHint hint, const std::string &purposeString)
int getLogFrequency () const
int getRunNumber () const
std::string getName () const
void createHistograms (const std::vector< framework::config::Parameters > &histos)
Private Attributes
std::string input_name_
buffer object name on event bus
std::string input_pass_
buffer object pass on event bus
utility::Writer writer_
raw data file we are reading
Additional Inherited Members
Static Public Member Functions inherited from framework::EventProcessor
static void declare (const std::string &classname, int classtype, EventProcessorMaker *)
Static Public Attributes inherited from framework::Analyzer
static const int CLASSTYPE {2}
Protected Member Functions inherited from framework::EventProcessor
void abortEvent ()
Protected Attributes inherited from framework::EventProcessor
HistogramHelper histograms_
Interface class for making and filling histograms.
NtupleManager & ntuple_ {NtupleManager::getInstance()}
Manager for any ntuples.
logging::logger theLog_
The logger for this EventProcessor.
Detailed Description
This producer unpacks the data from the a single subsystem raw data file into a single buffer for a downstream processor to decode.
Definition at line 18 of file SingleSubsystemPacker.h.
Constructor & Destructor Documentation
SingleSubsystemPacker()
packing::SingleSubsystemPacker::SingleSubsystemPacker (const std::string & name, framework::Process & p) inline
normal constructor
Definition at line 21 of file SingleSubsystemPacker.h.
    : framework::Analyzer(name, p) {}
~SingleSubsystemPacker()
virtual packing::SingleSubsystemPacker::~SingleSubsystemPacker () inline virtual
empty destructor
Definition at line 24 of file SingleSubsystemPacker.h.
{}
Member Function Documentation
analyze()
void packing::SingleSubsystemPacker::analyze (const framework::Event & event) final override virtual
Actually do the unpacking/decoding.
Parameters
[in,out] event Event bus with raw data where we will put the digis
Implements framework::Analyzer.
Definition at line 13 of file SingleSubsystemPacker.cxx.
{
  if (!writer_) abortEvent();
  auto buff{event.getCollection<uint8_t>(input_name_,input_pass_)};
  writer_ << buff;
}
References framework::EventProcessor::abortEvent(), input_name_, input_pass_, and writer_.
configure()
void packing::SingleSubsystemPacker::configure (framework::config::Parameters & ps) final override virtual
Configure the unpacker and open the raw data file for IO
Parameters
[in] ps Parameters for configuration
Reimplemented from framework::EventProcessor.
Definition at line 7 of file SingleSubsystemPacker.cxx.
{
  writer_.open(ps.getParameter<std::string>("raw_file"));
  input_name_ = ps.getParameter<std::string>("input_name");
  input_pass_ = ps.getParameter<std::string>("input_pass");
}
References framework::config::Parameters::getParameter(), input_name_, input_pass_, packing::utility::Writer::open(), and writer_.
Member Data Documentation
input_name_
std::string packing::SingleSubsystemPacker::input_name_ private
buffer object name on event bus
Definition at line 42 of file SingleSubsystemPacker.h.
Referenced by analyze(), and configure().
input_pass_
std::string packing::SingleSubsystemPacker::input_pass_ private
buffer object pass on event bus
Definition at line 44 of file SingleSubsystemPacker.h.
Referenced by analyze(), and configure().
writer_
utility::Writer packing::SingleSubsystemPacker::writer_ private
raw data file we are reading
Definition at line 48 of file SingleSubsystemPacker.h.
Referenced by analyze(), and configure().
The documentation for this class was generated from the following files:
Packing/include/Packing/SingleSubsystemPacker.h
Packing/src/Packing/SingleSubsystemPacker.cxx