LDMX Software: simcore::generators::RootCompleteReSim Class Reference
simcore::generators::RootCompleteReSim Class Reference
#include <RootCompleteReSim.h>
Public Member Functions
RootCompleteReSim (const std::string &name, const framework::config::Parameters &parameters)
virtual ~RootCompleteReSim ()
void GeneratePrimaryVertex (G4Event *anEvent)
void RecordConfig (const std::string &id, ldmx::RunHeader &rh) final override
Public Member Functions inherited from simcore::PrimaryGenerator
PrimaryGenerator (const std::string &name, const framework::config::Parameters &parameters)
virtual ~PrimaryGenerator ()
Destructor.
virtual void GeneratePrimaryVertex (G4Event *)=0
virtual void RecordConfig (const std::string &id, ldmx::RunHeader &rh)=0
Private Attributes
std::string simParticleCollName_
std::string simParticlePassName_
std::unique_ptr< framework::EventFile > ifile_
framework::Event ievent_
Additional Inherited Members
Public Types inherited from simcore::PrimaryGenerator
using Factory = ::simcore::Factory< PrimaryGenerator, std::shared_ptr< PrimaryGenerator >, const std::string &, const framework::config::Parameters & >
Factory for primary generators.
Protected Attributes inherited from simcore::PrimaryGenerator
std::string name_ {""}
Name of the PrimaryGenerator.
Detailed Description
PrimaryGenerator that gets primaries and event seeds and inputs them into current event as primaries with the exact same kinematics.
Definition at line 44 of file RootCompleteReSim.h.
Constructor & Destructor Documentation
RootCompleteReSim()
simcore::generators::RootCompleteReSim::RootCompleteReSim (const std::string & name, const framework::config::Parameters & parameters)
Class constructor.
Parameters
name the name of the generator
parameters configuration parameters
Parameters: filePath : path to root file to re-sim simParticleCollName : name of collection of SimParticles simParticlePassName : name of pass of SimParticles
Definition at line 29 of file RootCompleteReSim.cxx.
    : PrimaryGenerator(name, parameters), ievent_("InputReSim") {
  framework::config::Parameters file_params;
  file_params.addParameter<std::string>("tree_name","LDMX_Events");
  std::string filename = parameters.getParameter<std::string>("filePath");
  ifile_ = std::make_unique<framework::EventFile>(file_params,filename);
  ifile_->setupEvent(&ievent_);
  simParticleCollName_ =
      parameters.getParameter<std::string>("collection_name");
  simParticlePassName_ = parameters.getParameter<std::string>("pass_name");
}
References framework::config::Parameters::addParameter(), framework::config::Parameters::getParameter(), ievent_, ifile_, simParticleCollName_, and simParticlePassName_.
~RootCompleteReSim()
simcore::generators::RootCompleteReSim::~RootCompleteReSim () virtual
Class destructor.
Definition at line 43 of file RootCompleteReSim.cxx.
{
  ifile_->close();
  ifile_.reset(nullptr);
}
References ifile_.
Member Function Documentation
GeneratePrimaryVertex()
void simcore::generators::RootCompleteReSim::GeneratePrimaryVertex (G4Event * anEvent) virtual
Generate vertices in the Geant4 event.
Parameters
anEvent The Geant4 event.
Implements simcore::PrimaryGenerator.
Definition at line 48 of file RootCompleteReSim.cxx.
{
  // go to next event
  //  if there isn't another event ==> EventFile::nextEvent returns false
  if (not ifile_->nextEvent()) {
    std::cout << "[ RootSimFromEcalSP ]: End of file reached." << std::endl;
    G4RunManager::GetRunManager()->AbortRun(true);
    anEvent->SetEventAborted();
  }
  auto simParticles{ievent_.getMap<int, ldmx::SimParticle>(simParticleCollName_,
                                                     simParticlePassName_)};
  std::vector<G4PrimaryVertex*> vertices;  // vertices already put into Geant4
  for (const auto& [trackID, sp] : simParticles) {
    // check if particle has status 1
    // skip if not primary gen status
    if (sp.getGenStatus() != 1) continue;
    bool vertexExists = false;
    G4PrimaryVertex* curvertex = new G4PrimaryVertex();
    for (unsigned int iV = 0; iV < vertices.size(); ++iV) {
      double cur_vx = sp.getVertex()[0];
      double cur_vy = sp.getVertex()[1];
      double cur_vz = sp.getVertex()[2];
      double i_vx = vertices.at(iV)->GetX0();
      double i_vy = vertices.at(iV)->GetY0();
      double i_vz = vertices.at(iV)->GetZ0();
      if ((cur_vx == i_vx) && (cur_vy == i_vy) && (cur_vz == i_vz)) {
        vertexExists = true;
        curvertex = vertices.at(iV);
      }
    }
    if (vertexExists == false) {
      curvertex->SetPosition(sp.getVertex()[0], sp.getVertex()[1],
                             sp.getVertex()[2]);
      curvertex->SetWeight(1.);
      anEvent->AddPrimaryVertex(curvertex);
    }
    G4PrimaryParticle* primary = new G4PrimaryParticle();
    primary->SetPDGcode(sp.getPdgID());
    primary->SetMomentum(sp.getMomentum()[0] * MeV, sp.getMomentum()[1] * MeV,
                         sp.getMomentum()[2] * MeV);
    primary->SetMass(sp.getMass() * MeV);
    curvertex->SetPrimary(primary);
  }
  // Create an input stream with a copy of the event seed as content.
  // The input stream is then passed to the random engine to restore
  // the state.
  std::istringstream iss(
      ievent_.getEventHeader().getStringParameter("eventSeed"));
  G4Random::restoreFullState(iss);
}
References framework::Event::getEventHeader(), framework::Event::getMap(), ldmx::EventHeader::getStringParameter(), ievent_, ifile_, simParticleCollName_, and simParticlePassName_.
RecordConfig()
void simcore::generators::RootCompleteReSim::RecordConfig (const std::string & id, ldmx::RunHeader & rh) final override virtual
Record the configuration of the primary generator into the run header
Note
you must include the id number in each entry into the run header just in case there are other generators
Implements simcore::PrimaryGenerator.
Definition at line 103 of file RootCompleteReSim.cxx.
{
  rh.setStringParameter(id + " Class", "simcore::generators::RootCompleteReSim");
  rh.setStringParameter(id + " File Path", ifile_->getFileName());
}
References ifile_, and ldmx::RunHeader::setStringParameter().
Member Data Documentation
ievent_
framework::Event simcore::generators::RootCompleteReSim::ievent_ private
The input ldmx event bus
Definition at line 89 of file RootCompleteReSim.h.
Referenced by GeneratePrimaryVertex(), and RootCompleteReSim().
ifile_
std::unique_ptr<framework::EventFile> simcore::generators::RootCompleteReSim::ifile_ private
The input root file
Definition at line 84 of file RootCompleteReSim.h.
Referenced by GeneratePrimaryVertex(), RecordConfig(), RootCompleteReSim(), and ~RootCompleteReSim().
simParticleCollName_
std::string simcore::generators::RootCompleteReSim::simParticleCollName_ private
Name of SimParticles collection
Definition at line 74 of file RootCompleteReSim.h.
Referenced by GeneratePrimaryVertex(), and RootCompleteReSim().
simParticlePassName_
std::string simcore::generators::RootCompleteReSim::simParticlePassName_ private
Name of SimParticles pass
Definition at line 79 of file RootCompleteReSim.h.
Referenced by GeneratePrimaryVertex(), and RootCompleteReSim().
The documentation for this class was generated from the following files:
SimCore/include/SimCore/Generators/RootCompleteReSim.h
SimCore/src/SimCore/Generators/RootCompleteReSim.cxx