LDMX Software: ldmx::EcalClusterProducer Class Reference
ldmx::EcalClusterProducer Class Reference
Simple algorithm that does clustering in the ECal.
#include <EcalClusterProducer.h>
Public Member Functions
EcalClusterProducer (const std::string &name, Process &process)
void configure (Parameters &parameters) final override
virtual void produce (Event &event)
Public Member Functions inherited from ldmx::Producer
Producer (const std::string &name, Process &process)
Public Member Functions inherited from ldmx::EventProcessor
EventProcessor (const std::string &name, Process &process)
virtual ~EventProcessor ()
virtual void onNewRun (const RunHeader &runHeader)
virtual void onFileOpen (EventFile &eventFile)
virtual void onFileClose (EventFile &eventFile)
virtual void onProcessStart ()
virtual void onProcessEnd ()
TDirectory * getHistoDirectory ()
void setStorageHint (ldmx::StorageControlHint hint)
void setStorageHint (ldmx::StorageControlHint hint, const std::string &purposeString)
void createHistograms (const std::vector< Parameters > &histos)
Private Attributes
std::shared_ptr< EcalHexReadout > hexReadout_
double seedThreshold_ {0}
double cutoff_ {0}
std::string digisPassName_
std::string algoCollName_
std::string clusterCollName_
TString algoName_
Additional Inherited Members
Static Public Member Functions inherited from ldmx::EventProcessor
static void declare (const std::string &classname, int classtype, EventProcessorMaker *)
Static Public Attributes inherited from ldmx::Producer
static const int CLASSTYPE {1}
Protected Member Functions inherited from ldmx::EventProcessor
void abortEvent ()
Protected Attributes inherited from ldmx::EventProcessor
Process & process_
HistogramHelper histograms_
Interface class for making and filling histograms.
NtupleManager & ntuple_ {NtupleManager::getInstance()}
Manager for any ntuples.
Detailed Description
Simple algorithm that does clustering in the ECal.
Definition at line 46 of file EcalClusterProducer.h.
Member Function Documentation
configure()
void ldmx::EcalClusterProducer::configure (Parameters & parameters) final override virtual
Configure the processor using the given user specified parameters.
Parameters
parameters Set of parameters used to configure this processor.
Reimplemented from ldmx::EventProcessor.
Definition at line 16 of file EcalClusterProducer.cxx.
{
         // These are the v12 parameters
         //  all distances in mm
         double moduleRadius = 85.0; //same as default
         int    numCellsWide = 23; //same as default
         double moduleGap = 1.0;
         double ecalFrontZ = 220;
         std::vector<double> ecalSensLayersZ = {
              7.850,
             13.300,
             26.400,
             33.500,
             47.950,
             56.550,
             72.250,
             81.350,
             97.050,
             106.150,
             121.850,
             130.950,
             146.650,
             155.750,
             171.450,
             180.550,
             196.250,
             205.350,
             221.050,
             230.150,
             245.850,
             254.950,
             270.650,
             279.750,
             298.950,
             311.550,
             330.750,
             343.350,
             362.550,
             375.150,
             394.350,
             406.950,
             426.150,
             438.750
         };
         hexReadout_ = std::make_shared<EcalHexReadout>(
                 moduleRadius,
                 moduleGap,
                 numCellsWide,
                 ecalSensLayersZ,
                 ecalFrontZ
                 );
         cutoff_ = parameters.getParameter< double >("cutoff");
         seedThreshold_ = parameters.getParameter< double >("seedThreshold");
         digisPassName_ = parameters.getParameter< std::string >("digisPassName");
         algoCollName_ = parameters.getParameter< std::string >("algoCollName");
         algoName_ = parameters.getParameter< std::string >("algoName");
         clusterCollName_ = parameters.getParameter< std::string >("clusterCollName");
     }
References algoName_, and ldmx::Parameters::getParameter().
produce()
void ldmx::EcalClusterProducer::produce (Event & event) virtual
Process the event and put new data products into it.
Parameters
event The Event to process.
Implements ldmx::Producer.
Definition at line 78 of file EcalClusterProducer.cxx.
{
         static const double layerZPos[] = {-137.2, -134.3, -127.95, -123.55, -115.7, -109.8, -100.7, -94.3, -85.2, -78.8, -69.7, -63.3, -54.2, -47.8, -38.7, -32.3, -23.2, -16.8, -7.7, -1.3, 7.8, 14.2, 23.3, 29.7, 42.3, 52.2, 64.8, 74.7, 87.3, 97.2, 109.8, 119.7, 132.3, 142.2};
         TemplatedClusterFinder<MyClusterWeight> cf;
         std::vector< EcalHit > ecalHits = event.getCollection< EcalHit >( "ecalDigis" , digisPassName_ );
         int nEcalDigis = ecalHits.size();
         // Don't do anything if there are no ECal digis!
         if (!(nEcalDigis > 0)) { return; }
         for (EcalHit &hit : ecalHits ) {
             //Skip zero energy digis.
             if (hit.getEnergy() == 0) { continue; }
             cf.add( &hit , hexReadout_, layerZPos[hit.getLayer()]);
         }
         cf.cluster(seedThreshold_, cutoff_);
         std::vector<WorkingCluster> wcVec = cf.getClusters();
         std::map<int, double> cWeights = cf.getWeights();
         ClusterAlgoResult algoResult;
         algoResult.set(algoName_, 3, cWeights.rbegin()->first);
         algoResult.setAlgoVar(0, cutoff_);
         algoResult.setAlgoVar(1, seedThreshold_);
         algoResult.setAlgoVar(2, cf.getNSeeds());
         std::map<int, double>::iterator it = cWeights.begin();
         for (it = cWeights.begin(); it != cWeights.end(); it++) {
             algoResult.setWeight(it->first, it->second/100);
         }
         std::vector< EcalCluster > ecalClusters;
         for (int aWC = 0; aWC < wcVec.size(); aWC++) {
             EcalCluster cluster;
             cluster.setEnergy(wcVec[aWC].centroid().E());
             cluster.setCentroidXYZ(wcVec[aWC].centroid().Px(), wcVec[aWC].centroid().Py(), wcVec[aWC].centroid().Pz());
             cluster.setNHits(wcVec[aWC].getHits().size());
             cluster.addHits(wcVec[aWC].getHits());
             ecalClusters.push_back( cluster );
         }
         event.add(clusterCollName_, ecalClusters );
         event.add(algoCollName_, algoResult );
     }
References ldmx::EcalCluster::addHits(), algoName_, ldmx::ClusterAlgoResult::set(), ldmx::ClusterAlgoResult::setAlgoVar(), ldmx::EcalCluster::setCentroidXYZ(), ldmx::EcalCluster::setEnergy(), ldmx::EcalCluster::setNHits(), and ldmx::ClusterAlgoResult::setWeight().
Member Data Documentation
algoName_
TString ldmx::EcalClusterProducer::algoName_ private
The name of the cluster algorithm used.
Definition at line 73 of file EcalClusterProducer.h.
Referenced by configure(), and produce().
The documentation for this class was generated from the following files:
Ecal/include/Ecal/EcalClusterProducer.h
Ecal/src/EcalClusterProducer.cxx