LDMX Software: ldmx::test::EcalFakeSimHits Class Reference
ldmx::test::EcalFakeSimHits Class Reference
Public Member Functions
EcalFakeSimHits (const std::string &name, Process &p)
void beforeNewRun (RunHeader &header)
void produce (Event &event) final override
Public Member Functions inherited from ldmx::Producer
Producer (const std::string &name, Process &process)
Public Member Functions inherited from ldmx::EventProcessor
EventProcessor (const std::string &name, Process &process)
virtual ~EventProcessor ()
virtual void configure (Parameters &parameters)
virtual void onNewRun (const RunHeader &runHeader)
virtual void onFileOpen (EventFile &eventFile)
virtual void onFileClose (EventFile &eventFile)
virtual void onProcessStart ()
virtual void onProcessEnd ()
template<class T >
const T & getCondition (const std::string &condition_name)
TDirectory * getHistoDirectory ()
void setStorageHint (ldmx::StorageControlHint hint)
void setStorageHint (ldmx::StorageControlHint hint, const std::string &purposeString)
int getLogFrequency () const
int getRunNumber () const
std::string getName () const
void createHistograms (const std::vector< Parameters > &histos)
Private Attributes
double maxEnergy_ = 80.
Maximum energy to make a simulated hit for [MeV].
double energyStep_ = 0.1
Difference between energies to make a sim hit for [MeV].
double minEnergy_ = 0.5
Additional Inherited Members
Static Public Member Functions inherited from ldmx::EventProcessor
static void declare (const std::string &classname, int classtype, EventProcessorMaker *)
Static Public Attributes inherited from ldmx::Producer
static const int CLASSTYPE {1}
Protected Member Functions inherited from ldmx::EventProcessor
void abortEvent ()
Protected Attributes inherited from ldmx::EventProcessor
HistogramHelper histograms_
Interface class for making and filling histograms.
NtupleManager & ntuple_ {NtupleManager::getInstance()}
Manager for any ntuples.
logging::logger theLog_
The logger for this EventProcessor.
Detailed Description
Definition at line 28 of file EcalDigiPipelineTest.cxx.
Member Function Documentation
beforeNewRun()
void ldmx::test::EcalFakeSimHits::beforeNewRun (RunHeader & header) inline virtual
Handle allowing producers to modify run headers before the run begins
Parameters
header RunHeader for Producer to add parameters to
Reimplemented from ldmx::Producer.
Definition at line 47 of file EcalDigiPipelineTest.cxx.
{
             header.setDetectorName("ldmx-det-v12");
         }
References ldmx::RunHeader::setDetectorName().
produce()
void ldmx::test::EcalFakeSimHits::produce (Event & event) inline final override virtual
Process the event and put new data products into it.
Parameters
event The Event to process.
Implements ldmx::Producer.
Definition at line 51 of file EcalDigiPipelineTest.cxx.
{
             std::vector<SimCalorimeterHit> pretendSimHits;
             //fill pretend sim hits with a range of simulated energies
             int cell(0), module(0), layer(0);
             double currEnergy{minEnergy_};
             while ( currEnergy < maxEnergy_ ) {
                 //TODO test several contribs
                 //  right now, not a big deal because we just do an energy weight average anyways
                 SimCalorimeterHit currHit;
                 //distribute indices across distince IDs
                 //  need to be careful to not exceed max count of subparts
                 EcalID id(layer,module,cell);
                 currHit.setID( id.raw() );
                 currHit.addContrib(
                         -1 //incidentID
                         , -1 // trackID
                         , 0 // pdg ID
                         , currEnergy // edep
                         , 1. //time
                         );
                 pretendSimHits.push_back( currHit );
                 currEnergy += energyStep_;
                 cell++;
                 if ( cell > 300 ) {
                     cell = 0;
                     module++;
                 }
                 if ( module > 7 ) {
                     module = 0;
                     layer++;
                 }
             }
             //needs to be correct collection name
             REQUIRE_NOTHROW(event.add( "EcalSimHits" , pretendSimHits ));
             return;
         }
References ldmx::SimCalorimeterHit::addContrib(), energyStep_, maxEnergy_, minEnergy_, and ldmx::SimCalorimeterHit::setID().
Member Data Documentation
minEnergy_
double ldmx::test::EcalFakeSimHits::minEnergy_ = 0.5 private
Minimum energy to make a sim hit for [MeV] Needs to be above readout threshold (after internal EcalDigi's calculation)
Definition at line 40 of file EcalDigiPipelineTest.cxx.
Referenced by produce().
The documentation for this class was generated from the following file:
Ecal/test/EcalDigiPipelineTest.cxx