LDMX Software: ldmx::HcalTriggerID Class Reference
ldmx::HcalTriggerID Class Reference
Extension of DetectorID providing access to HCal trigger cell.
#include <HcalTriggerID.h>
Public Types
enum HcalSection {
BACK = 0 , TOP = 1 , BOTTOM = 2 , LEFT = 4 ,
RIGHT = 3
}
Public Types inherited from ldmx::HcalAbstractID
enum HcalBarType { Global = 0 , Digi = 1 , Trigger = 2 , Special = 7 }
Public Types inherited from ldmx::DetectorID
typedef uint32_t RawValue
Public Member Functions
HcalTriggerID ()
HcalTriggerID (RawValue rawid)
HcalTriggerID (const HcalAbstractID id)
HcalTriggerID (unsigned int section, unsigned int layer, unsigned int superstrip, unsigned int end)
int getSection () const
int section () const
int layer () const
int getLayerID () const
int getSuperstrip () const
int superstrip () const
int end () const
bool isNegativeEnd () const
bool isComposite () const
Public Member Functions inherited from ldmx::HcalAbstractID
HcalAbstractID ()
HcalAbstractID (RawValue rawid)
HcalAbstractID (const DetectorID id)
HcalAbstractID (unsigned int bar_type, unsigned int payload)
int bar_type () const
Public Member Functions inherited from ldmx::DetectorID
DetectorID ()
Class constructor for a null DetectorID.
DetectorID (RawValue rawid)
Class constructor from a raw 32-bit integer.
DetectorID (SubdetectorIDType sdtype, RawValue raw_subpayload)
bool null () const
SubdetectorIDType subdet () const
RawValue raw () const
void setRawValue (RawValue rawValue)
bool operator< (const DetectorID &id) const
bool operator== (const DetectorID &id) const
bool operator!= (const DetectorID &id) const
Static Public Member Functions
static void createInterpreters ()
Static Public Attributes
static const RawValue END_MASK {0x3}
static const RawValue END_SHIFT {20}
static const RawValue SECTION_MASK {0x7}
static const RawValue SECTION_SHIFT {16}
static const RawValue LAYER_MASK {0xFF}
static const RawValue LAYER_SHIFT {8}
static const RawValue SUPERSTRIP_MASK {0xFF}
static const RawValue SUPERSTRIP_SHIFT {0}
Static Public Attributes inherited from ldmx::HcalAbstractID
static const RawValue BAR_TYPE_MASK {0x7}
static const RawValue BAR_TYPE_SHIFT {23}
static const RawValue HCAL_PAYLOAD_MASK {0x007FFFFF}
Static Public Attributes inherited from ldmx::DetectorID
static const RawValue SUBDETECTORID_MASK {0x3F}
static const RawValue SUBDETECTORID_SHIFT {26}
static const RawValue SUBDETECTOR_PAYLOAD_MASK {0x3FFFFFFF}
Additional Inherited Members
Protected Attributes inherited from ldmx::DetectorID
RawValue id_
The raw, packed value of the ID.
Detailed Description
Extension of DetectorID providing access to HCal trigger cell.
Definition at line 19 of file HcalTriggerID.h.
Member Enumeration Documentation
HcalSection
enum ldmx::HcalTriggerID::HcalSection
Encodes the section of the HCal based on the 'section' field value.
Definition at line 24 of file HcalTriggerID.h.
{ BACK = 0, TOP = 1, BOTTOM = 2, LEFT = 4, RIGHT = 3 };
Constructor & Destructor Documentation
HcalTriggerID() [1/4]
ldmx::HcalTriggerID::HcalTriggerID () inline
Empty HCAL trigger id (but not null!)
Definition at line 38 of file HcalTriggerID.h.
: HcalAbstractID() {}
HcalTriggerID() [2/4]
ldmx::HcalTriggerID::HcalTriggerID (RawValue rawid) inline
Create from raw number
Definition at line 43 of file HcalTriggerID.h.
                                : HcalAbstractID(rawid) {
    if (!null() && bar_type() != Trigger) {
      EXCEPTION_RAISE(
          "DetectorIDMismatch",
          "Attempted to create HcalTriggerID from mismatched Hcal bar_type " +
              std::to_string(bar_type()));
    }
  }
References ldmx::HcalAbstractID::bar_type().
HcalTriggerID() [3/4]
ldmx::HcalTriggerID::HcalTriggerID (const HcalAbstractID id) inline
Create from a DetectorID, but check
Definition at line 55 of file HcalTriggerID.h.
                                         : HcalAbstractID(id) {
    if (!null() && bar_type() != Trigger) {
      EXCEPTION_RAISE(
          "DetectorIDMismatch",
          "Attempted to create HcalTriggerID from mismatched Hcal bar_type " +
              std::to_string(bar_type()));
    }
  }
References ldmx::HcalAbstractID::bar_type().
HcalTriggerID() [4/4]
ldmx::HcalTriggerID::HcalTriggerID (unsigned int section, unsigned int layer, unsigned int superstrip, unsigned int end) inline
Create from pieces
Definition at line 67 of file HcalTriggerID.h.
      : HcalAbstractID(Trigger, 0) {
    id_ |= (section & SECTION_MASK) << SECTION_SHIFT;
    id_ |= (layer & LAYER_MASK) << LAYER_SHIFT;
    id_ |= (superstrip & SUPERSTRIP_MASK) << SUPERSTRIP_SHIFT;
    id_ |= (end & END_MASK) << END_SHIFT;
  }
References end(), ldmx::DetectorID::id_, layer(), and superstrip().
Member Function Documentation
createInterpreters()
void ldmx::HcalTriggerID::createInterpreters () static
Definition at line 13 of file HcalTriggerID.cxx.
{
  IDField::IDFieldList fields;
  fields.push_back(new IDField("subdetector", 0, SUBDETECTORID_SHIFT, 31));
  fields.push_back(
      new IDField("section", 1, SECTION_SHIFT,
                  SECTION_SHIFT + IDField::countOnes(SECTION_MASK) - 1));
  fields.push_back(
      new IDField("layer", 2, LAYER_SHIFT,
                  LAYER_SHIFT + IDField::countOnes(LAYER_MASK) - 1));
  fields.push_back(
      new IDField("superstrip", 3, SUPERSTRIP_SHIFT,
                  SUPERSTRIP_SHIFT + IDField::countOnes(SUPERSTRIP_MASK) - 1));
  fields.push_back(new IDField("end", 4, END_SHIFT,
                               END_SHIFT + IDField::countOnes(END_MASK) - 1));
  DetectorIDInterpreter::registerInterpreter(
      SD_HCAL, HcalAbstractID::BAR_TYPE_MASK << HcalAbstractID::BAR_TYPE_SHIFT,
      HcalAbstractID::Trigger << HcalAbstractID::BAR_TYPE_SHIFT, fields);
}
end()
int ldmx::HcalTriggerID::end () const inline
Get the value of the 'end' field from the ID.
Returns
The value of the 'end' field.
Definition at line 118 of file HcalTriggerID.h.
{ return (id_ >> END_SHIFT) & END_MASK; }
References ldmx::DetectorID::id_.
Referenced by HcalTriggerID(), isComposite(), and isNegativeEnd().
getLayerID()
int ldmx::HcalTriggerID::getLayerID () const inline
Get the value of the layer field from the ID.
Returns
The value of the layer field.
Definition at line 98 of file HcalTriggerID.h.
{ return (id_ >> LAYER_SHIFT) & LAYER_MASK; }
References ldmx::DetectorID::id_.
getSection()
int ldmx::HcalTriggerID::getSection () const inline
Definition at line 80 of file HcalTriggerID.h.
{ return (id_ >> SECTION_SHIFT) & SECTION_MASK; }
getSuperstrip()
int ldmx::HcalTriggerID::getSuperstrip () const inline
Get the value of the 'superstrip' field from the ID.
Returns
The value of 'superstrip' field.
Definition at line 104 of file HcalTriggerID.h.
{
    return (id_ >> SUPERSTRIP_SHIFT) & SUPERSTRIP_MASK;
  }
References ldmx::DetectorID::id_.
isComposite()
bool ldmx::HcalTriggerID::isComposite () const inline
Get whether the ID is the composite of two bar ends.
Returns
True if the ID corresponds to a composite TP.
Definition at line 130 of file HcalTriggerID.h.
{ return end() == 2; }
References end().
isNegativeEnd()
bool ldmx::HcalTriggerID::isNegativeEnd () const inline
Get whether the 'end' field from the ID is negative.
Returns
True if the end of the strip is negative
Definition at line 124 of file HcalTriggerID.h.
{ return end() == 1; }
References end().
layer()
int ldmx::HcalTriggerID::layer () const inline
Get the value of the layer field from the ID.
Returns
The value of the layer field.
Definition at line 92 of file HcalTriggerID.h.
{ return (id_ >> LAYER_SHIFT) & LAYER_MASK; }
References ldmx::DetectorID::id_.
Referenced by HcalTriggerID().
section()
int ldmx::HcalTriggerID::section () const inline
Definition at line 86 of file HcalTriggerID.h.
{ return (id_ >> SECTION_SHIFT) & SECTION_MASK; }
superstrip()
int ldmx::HcalTriggerID::superstrip () const inline
Get the value of the 'superstrip' field from the ID.
Returns
The value of 'superstrip' field.
Definition at line 112 of file HcalTriggerID.h.
{ return (id_ >> SUPERSTRIP_SHIFT) & SUPERSTRIP_MASK; }
References ldmx::DetectorID::id_.
Referenced by HcalTriggerID().
Member Data Documentation
END_MASK
const RawValue ldmx::HcalTriggerID::END_MASK {0x3} static
Definition at line 26 of file HcalTriggerID.h.
END_SHIFT
const RawValue ldmx::HcalTriggerID::END_SHIFT {20} static
Definition at line 27 of file HcalTriggerID.h.
LAYER_MASK
const RawValue ldmx::HcalTriggerID::LAYER_MASK {0xFF} static
Definition at line 30 of file HcalTriggerID.h.
LAYER_SHIFT
const RawValue ldmx::HcalTriggerID::LAYER_SHIFT {8} static
Definition at line 31 of file HcalTriggerID.h.
SECTION_MASK
const RawValue ldmx::HcalTriggerID::SECTION_MASK {0x7} static
Definition at line 28 of file HcalTriggerID.h.
SECTION_SHIFT
const RawValue ldmx::HcalTriggerID::SECTION_SHIFT {16} static
Definition at line 29 of file HcalTriggerID.h.
SUPERSTRIP_MASK
const RawValue ldmx::HcalTriggerID::SUPERSTRIP_MASK {0xFF} static
Definition at line 32 of file HcalTriggerID.h.
SUPERSTRIP_SHIFT
const RawValue ldmx::HcalTriggerID::SUPERSTRIP_SHIFT {0} static
Definition at line 33 of file HcalTriggerID.h.
The documentation for this class was generated from the following files:
DetDescr/include/DetDescr/HcalTriggerID.h
DetDescr/src/DetDescr/HcalTriggerID.cxx