LDMX Software: ldmx::HgcrocTriggerCalculations Class Reference
ldmx::HgcrocTriggerCalculations Class Reference
Contains the core logic for the Hgcroc trigger calculations.
#include <HgcrocTriggerCalculations.h>
Public Member Functions
HgcrocTriggerCalculations (const conditions::IntegerTableCondition &ict)
void addDigi (unsigned int id, unsigned int tid, int adc, int tot)
void compressDigis (int cells_per_trig)
const std::map< unsigned int, uint8_t > & compressedEnergies () const
Static Public Member Functions
static unsigned int singleChannelCharge (int adc, int tot, int adc_ped, int adc_thresh, int tot_ped, int tot_thresh, int tot_gain)
Private Attributes
HgcrocTriggerConditions conditions_
std::map< unsigned int, unsigned int > linearCharge_
std::map< unsigned int, uint8_t > compressedCharge_
Detailed Description
Contains the core logic for the Hgcroc trigger calculations.
This class is meant to be created once per event along with the conditions for the chip. These chip conditions are wrapped in an HgcrocTriggerConditions class for easier access. These chip conditions may change from event-to-event, so it is best to allow for this object to change from event-to-event.
Definition at line 108 of file HgcrocTriggerCalculations.h.
Constructor & Destructor Documentation
HgcrocTriggerCalculations()
ldmx::HgcrocTriggerCalculations::HgcrocTriggerCalculations (const conditions::IntegerTableCondition & ict)
Construct the chip trigger calculator
Here we pass the table of chip conditions that is used to emulate the chip's behavior for all of the different channel IDs.
We also use this opportunity to double check that the column indices in HgcrocTriggerConditions match the column indices imported from the input table.
Parameters
[in] ict table of chip conditions
Definition at line 55 of file HgcrocTriggerCalculations.cxx.
    : conditions_{ict, true} {}
Member Function Documentation
addDigi()
void ldmx::HgcrocTriggerCalculations::addDigi (unsigned int id, unsigned int tid, int adc, int tot)
Determine the linear charge for the given channel, using the calibration information, and add it to the map of trigger channel IDs to linear charge measurements.
See also
singleChannelCharge for how the precision channel measurement is converted to a linear trig-digi charge
Parameters
id Precision channel id (used to lookup in the conditions table)
tid Trigger channel id
adc ADC measurement of precision channel if not TOT complete
tot TOT measurement of precision channel if TOT is complete
Definition at line 59 of file HgcrocTriggerCalculations.cxx.
{
  unsigned int charge = singleChannelCharge(
      adc, tot, conditions_.adcPedestal(id), conditions_.adcThreshold(id),
      conditions_.totPedestal(id), conditions_.totThreshold(id),
      conditions_.totGain(id));
  if (charge > 0) {
    std::map<unsigned int, unsigned int>::iterator ic = linearCharge_.find(tid);
    if (ic == linearCharge_.end())
      linearCharge_[tid] = charge;
    else
      ic->second += charge;
  }
}
References ldmx::HgcrocTriggerConditions::adcPedestal(), ldmx::HgcrocTriggerConditions::adcThreshold(), conditions_, linearCharge_, singleChannelCharge(), ldmx::HgcrocTriggerConditions::totGain(), ldmx::HgcrocTriggerConditions::totPedestal(), and ldmx::HgcrocTriggerConditions::totThreshold().
Referenced by ecal::EcalTrigPrimDigiProducer::produce().
compressDigis()
void ldmx::HgcrocTriggerCalculations::compressDigis (int cells_per_trig)
Convert the linear charges to compressed charges, with a division depending on the number of cells summed by HGCROC
Fills the map of trigger channel IDs to compressed charge measurements. Some of the lowest order bits are dropped during compression in order to effectively reach the necessary dynamic range. The number of these bits that are dropped depends on the number of cells in each trigger grouping.
9 --> drop 8 lowest order bits --> multiply unpacked charge by 8 to get full amount
4 --> drop 4 lowest order bits --> mutliply unpacked charge by 4 to get full amount
@raises Exception if the input cells_per_trig is not 4 or 9.
Parameters
cells_per_trig Valid values are 4 or 9
Definition at line 74 of file HgcrocTriggerCalculations.cxx.
{
  int shift;
  if (cells_per_trig == 4)
    shift = 1;
  else if (cells_per_trig == 9)
    shift = 3;
  else {
    EXCEPTION_RAISE("HgcrocTriggerException",
                    "Invalid number of precision cells per trigger cell: " +
                        std::to_string(cells_per_trig));
  }
  for (auto ilinear : linearCharge_) {
    unsigned int lcharge = ilinear.second;
    lcharge = lcharge >> shift;
    uint8_t ccharge = ldmx::HgcrocTrigDigi::linear2Compressed(lcharge);
    compressedCharge_[ilinear.first] = ccharge;
  }
}
References compressedCharge_, ldmx::HgcrocTrigDigi::linear2Compressed(), and linearCharge_.
Referenced by ecal::EcalTrigPrimDigiProducer::produce().
compressedEnergies()
const std::map< unsigned int, uint8_t > & ldmx::HgcrocTriggerCalculations::compressedEnergies () const inline
Access the map of trigger ids to compressed energies
Returns
const reference to the map of trigger channel ID to compressed charge measurements
Definition at line 181 of file HgcrocTriggerCalculations.h.
{
    return compressedCharge_;
  }
References compressedCharge_.
Referenced by ecal::EcalTrigPrimDigiProducer::produce().
singleChannelCharge()
unsigned int ldmx::HgcrocTriggerCalculations::singleChannelCharge (int adc, int tot, int adc_ped, int adc_thresh, int tot_ped, int tot_thresh, int tot_gain) static
Calculates the linear trigger charge for a single precision channel (before 2x2 or 3x3 summing)
Parameters
adc ADC measurement for the channel
tot TOT measurement for the channel or zero if no TOT
adc_ped Trigger pedestal to subtract (8 bits, per channel)
adc_thresh ADC threshold for noise-suppression in the trigger path (5 bits, global for ROC)
tot_ped TOT pedestal (7 bits, group-of-nine)
tot_thresh TOT threshold, use this fixed value as "TOT" if the TOT is below this value (8 bits, group-of-nine)
tot_gain TOT to charge multiplicative factor (5 bits, integer math, global for ROC)
Returns
linear trigger charge from a single precision channel
Definition at line 33 of file HgcrocTriggerCalculations.cxx.
                  {
  unsigned int charge_adc = 0;
  if (adc > (adc_ped + adc_thresh))
    charge_adc = adc - adc_ped;  // otherwise zero
  unsigned int eff_tot{0};
  if (tot > tot_thresh && tot > tot_ped)
    eff_tot = tot - tot_ped;
  else
    eff_tot = tot_thresh - tot_ped;
  unsigned int charge_tot{0};
  charge_tot = eff_tot * tot_gain;
  unsigned int charge_final = (tot != 0) ? (charge_tot) : (charge_adc);
  return charge_final;
}
Referenced by addDigi().
Member Data Documentation
compressedCharge_
std::map<unsigned int, uint8_t> ldmx::HgcrocTriggerCalculations::compressedCharge_ private
A map of trigger channel id to compressed charge
Definition at line 191 of file HgcrocTriggerCalculations.h.
Referenced by compressDigis(), and compressedEnergies().
conditions_
HgcrocTriggerConditions ldmx::HgcrocTriggerCalculations::conditions_ private
The conditions to be used
Definition at line 187 of file HgcrocTriggerCalculations.h.
Referenced by addDigi().
linearCharge_
std::map<unsigned int, unsigned int> ldmx::HgcrocTriggerCalculations::linearCharge_ private
A map of trigger channel id to linear charge
Definition at line 189 of file HgcrocTriggerCalculations.h.
Referenced by addDigi(), and compressDigis().
The documentation for this class was generated from the following files:
Tools/include/Tools/HgcrocTriggerCalculations.h
Tools/src/Tools/HgcrocTriggerCalculations.cxx