LDMX Software: simcore::DetectorConstruction Class Reference
simcore::DetectorConstruction Class Reference
Implements the Geant4 detector construction.
#include <DetectorConstruction.h>
Public Member Functions
DetectorConstruction (simcore::geo::Parser *parser, framework::config::Parameters &parameters, ConditionsInterface &ci)
~DetectorConstruction ()=default
G4VPhysicalVolume * Construct ()
void ConstructSDandField ()
std::string getDetectorName ()
Private Attributes
simcore::geo::Parser * parser_
The parser used to load the detector into memory.
framework::config::Parameters parameters_
The set of parameters used to configure this class.
simcore::ConditionsInterface & conditions_interface_
interface to conditions to be passed to SDs
Detailed Description
Implements the Geant4 detector construction.
Note
This class reads in a detector description from a GDML file using the basic G4GDMLParser and instantiates supplemental information using the AuxInfoReader.
See also
AuxInfoReader
Definition at line 33 of file DetectorConstruction.h.
Constructor & Destructor Documentation
DetectorConstruction()
simcore::DetectorConstruction::DetectorConstruction (simcore::geo::Parser * parser, framework::config::Parameters & parameters, ConditionsInterface & ci)
Constructor.
Parameters
parser Parser used to parse the geometry into memory.
parameters The parameters used to configure this class.
ci The conditions needed to build the detector.
Definition at line 117 of file DetectorConstruction.cxx.
    : parser_(parser), parameters_{parameters}, conditions_interface_{ci} {}
~DetectorConstruction()
simcore::DetectorConstruction::~DetectorConstruction () default
Class destructor.
Member Function Documentation
Construct()
G4VPhysicalVolume * simcore::DetectorConstruction::Construct ()
Construct the detector.
Returns
The top volume of the detector.
Definition at line 122 of file DetectorConstruction.cxx.
{
  return parser_->GetWorldVolume();
}
References simcore::geo::Parser::GetWorldVolume(), and parser_.
ConstructSDandField()
void simcore::DetectorConstruction::ConstructSDandField ()
Definition at line 126 of file DetectorConstruction.cxx.
{
  auto sens_dets{parameters_.getParameter<std::vector<framework::config::Parameters>>(
      "sensitive_detectors",{})};
  for (auto& det : sens_dets) {
    // create
    auto sd = SensitiveDetector::Factory::get().make(
        det.getParameter<std::string>("class_name"),
        det.getParameter<std::string>("instance_name"),
        conditions_interface_, det);
    // attach to volumes
    for (G4LogicalVolume* volume : *G4LogicalVolumeStore::GetInstance()) {
      if (sd->isSensDet(volume)) {
        std::cout << "[ DetectorConstruction ] : "
          << "Attaching " << sd->GetName()
          << " to " << volume->GetName() << std::endl;
        volume->SetSensitiveDetector(sd);
      }
    }
  }
  // Biasing operators were created in RunManager::setupPhysics
  //  which is called before G4RunManager::Initialize
  //  which is where this method ends up being called.
  simcore::XsecBiasingOperator::Factory::get().apply([](auto bop) {
    logical_volume_tests::Test includeVolumeTest{nullptr};
    if (bop->getVolumeToBias().compare("ecal") == 0) {
      includeVolumeTest = &logical_volume_tests::isInEcal;
    } else if (bop->getVolumeToBias().compare("old_ecal") == 0) {
      includeVolumeTest = &logical_volume_tests::isInEcalOld;
    } else if (bop->getVolumeToBias().compare("target") == 0) {
      includeVolumeTest = &logical_volume_tests::isInTargetOnly;
    } else if (bop->getVolumeToBias().compare("target_region") == 0) {
      includeVolumeTest = &logical_volume_tests::isInTargetRegion;
    } else if (bop->getVolumeToBias().compare("hcal") == 0) {
      includeVolumeTest = &logical_volume_tests::isInHcal;
    } else {
      std::cerr << "[ DetectorConstruction ] : "
                << "WARN - Requested volume to bias '" << bop->getVolumeToBias()
                << "' is not recognized. Will attach volumes based on if their"
                << " name contains the volume to bias." << std::endl;
      includeVolumeTest = &logical_volume_tests::nameContains;
    }
    for (G4LogicalVolume* volume : *G4LogicalVolumeStore::GetInstance()) {
      auto volume_name = volume->GetName();
      if (includeVolumeTest(volume, bop->getVolumeToBias())) {
        bop->AttachTo(volume);
        std::cout << "[ DetectorConstruction ]: "
                  << "Attaching biasing operator " << bop->GetName()
                  << " to volume " << volume->GetName() << std::endl;
      }  // BOP attached to target or ecal
    }    // loop over volumes
  });    // loop over biasing operators
}
getDetectorName()
std::string simcore::DetectorConstruction::getDetectorName () inline
Returns
The name of this detector. This is extracted from the description file used to build this detector.
Definition at line 65 of file DetectorConstruction.h.
{ return parser_->getDetectorName(); }
References simcore::geo::Parser::getDetectorName(), and parser_.
Referenced by simcore::Simulator::beforeNewRun().
Member Data Documentation
conditions_interface_
simcore::ConditionsInterface& simcore::DetectorConstruction::conditions_interface_ private
interface to conditions to be passed to SDs
Definition at line 75 of file DetectorConstruction.h.
parameters_
framework::config::Parameters simcore::DetectorConstruction::parameters_ private
The set of parameters used to configure this class.
Definition at line 72 of file DetectorConstruction.h.
parser_
simcore::geo::Parser* simcore::DetectorConstruction::parser_ private
The parser used to load the detector into memory.
Definition at line 69 of file DetectorConstruction.h.
Referenced by Construct(), and getDetectorName().
The documentation for this class was generated from the following files:
SimCore/include/SimCore/DetectorConstruction.h
SimCore/src/SimCore/DetectorConstruction.cxx