LDMX Software: eventdisplay::EveShapeDrawer Class Reference
eventdisplay::EveShapeDrawer Class Reference
Helper class for drawing common shapes.
#include <EveShapeDrawer.h>
Public Member Functions
TEveGeoShape * drawHexPrism (Double_t xPos, Double_t yPos, Double_t zPos, Double_t xRot, Double_t yRot, Double_t zRot, Double_t h, Double_t r, Int_t color, Int_t transparency, TString name)
TEveGeoShape * drawHexPrism (HexPrism prism, Double_t xRot, Double_t yRot, Double_t zRot, Int_t color, Int_t transparency, TString name)
TEveGeoShape * drawRectPrism (Double_t xPos, Double_t yPos, Double_t zPos, Double_t dX, Double_t dY, Double_t dZ, Double_t xRot, Double_t yRot, Double_t zRot, Int_t color, Int_t transparency, TString name)
TEveGeoShape * drawRectPrism (BoundingBox boundingbox, Double_t xRot, Double_t yRot, Double_t zRot, Int_t color, Int_t transparency, TString name)
Static Public Member Functions
static EveShapeDrawer & getInstance ()
Private Attributes
UInt_t uid_ = 0
Detailed Description
Helper class for drawing common shapes.
Definition at line 27 of file EveShapeDrawer.h.
Member Function Documentation
drawHexPrism() [1/2]
TEveGeoShape * eventdisplay::EveShapeDrawer::drawHexPrism (Double_t xPos, Double_t yPos, Double_t zPos, Double_t xRot, Double_t yRot, Double_t zRot, Double_t h, Double_t r, Int_t color, Int_t transparency, TString name) inline
Draw a hexagonal prism.
Parameters
xPos x coordinate for center of prism [mm]
yPos y coordinate for center of prism [mm]
zPos z coordinate for center of prism [mm]
xRot rotation around x-axis [degrees]
yRot rotation around y-axis [degrees]
zRot rotation around z-axis [degrees]
h height of prism [mm]
r radius of prism (center to corner) [mm]
color color of prism
transparency transparency of prism
name name of prism
Definition at line 52 of file EveShapeDrawer.h.
{
    TGeoCombiTrans* locAndOrien = new TGeoCombiTrans(
        xPos, yPos, zPos, new TGeoRotation(name, xRot, yRot, zRot));
    TEveGeoShape* hexPrism = new TEveGeoShape(name);
    TGeoShape* tube = new TGeoTube(name, 0, r, h / 2);
    tube->SetUniqueID(uid_++);
    hexPrism->SetShape(tube);
    hexPrism->SetFillColor(color);
    hexPrism->SetMainTransparency(transparency);
    hexPrism->SetNSegments(6);
    hexPrism->SetTransMatrix(*locAndOrien);
    return hexPrism;
  }
Referenced by eventdisplay::Objects::draw(), eventdisplay::EveDetectorGeometry::drawECAL(), and drawHexPrism().
drawHexPrism() [2/2]
TEveGeoShape * eventdisplay::EveShapeDrawer::drawHexPrism (HexPrism prism, Double_t xRot, Double_t yRot, Double_t zRot, Int_t color, Int_t transparency, TString name) inline
Draw a hexagonal prism.
Parameters
HexPrism description of hexagonal prism geometry
xRot rotation around x-axis [degrees]
yRot rotation around y-axis [degrees]
zRot rotation around z-axis [degrees]
color color of prism
transparency transparency of prism
name name of prism
Definition at line 82 of file EveShapeDrawer.h.
{
    return drawHexPrism(prism.x, prism.y, prism.z, xRot, yRot, zRot,
                        prism.height, prism.radius, color, transparency, name);
  }
References drawHexPrism().
drawRectPrism() [1/2]
TEveGeoShape * eventdisplay::EveShapeDrawer::drawRectPrism (BoundingBox boundingbox, Double_t xRot, Double_t yRot, Double_t zRot, Int_t color, Int_t transparency, TString name) inline
Draw a rectangular prism
Parameters
boundingbox containing description of rectangular prism
xRot rotation around x-axis [degrees]
yRot rotation around y-axis [degrees]
zRot rotation around z-axis [degrees]
color color of prism
transparency transparency of prism
name name of prism
Definition at line 134 of file EveShapeDrawer.h.
{
    std::vector<double> center(3, 0);
    std::vector<double> widths(3, 0);
    for (unsigned int iC = 0; iC < 3; iC++) {
      center[iC] = (boundingbox[iC].second + boundingbox[iC].first) / 2.0;
      widths[iC] = abs(boundingbox[iC].second - boundingbox[iC].first);
    }
    return drawRectPrism(center[0], center[1], center[2], widths[0], widths[1],
                         widths[2], xRot, yRot, zRot, color, transparency,
                         name);
  }
References drawRectPrism().
drawRectPrism() [2/2]
TEveGeoShape * eventdisplay::EveShapeDrawer::drawRectPrism (Double_t xPos, Double_t yPos, Double_t zPos, Double_t dX, Double_t dY, Double_t dZ, Double_t xRot, Double_t yRot, Double_t zRot, Int_t color, Int_t transparency, TString name) inline
Draw a rectangular prism
Parameters
xPos x coordinate for center of prism [mm]
yPos y coordinate for center of prism [mm]
zPos z coordinate for center of prism [mm]
dX width in x direction [mm]
dY width in y direction [mm]
dZ width in z direction [mm]
xRot rotation around x-axis [degrees]
yRot rotation around y-axis [degrees]
zRot rotation around z-axis [degrees]
color color of prism
transparency transparency of prism
name name of prism
Definition at line 105 of file EveShapeDrawer.h.
{
    TGeoCombiTrans* locAndOrien = new TGeoCombiTrans(
        xPos, yPos, zPos, new TGeoRotation(name, xRot, yRot, zRot));
    TEveGeoShape* rectPrism = new TEveGeoShape(name);
    TGeoShape* box = new TGeoBBox(name, dX / 2, dY / 2, dZ / 2);
    box->SetUniqueID(uid_++);
    rectPrism->SetShape(box);
    rectPrism->SetFillColor(color);
    rectPrism->SetMainTransparency(transparency);
    rectPrism->SetTransMatrix(*locAndOrien);
    return rectPrism;
  }
Referenced by eventdisplay::Objects::draw(), eventdisplay::EveDetectorGeometry::drawHCAL(), eventdisplay::EveDetectorGeometry::drawRecoilTracker(), and drawRectPrism().
getInstance()
static EveShapeDrawer & eventdisplay::EveShapeDrawer::getInstance () inline static
Get Instance of Drawer
Definition at line 32 of file EveShapeDrawer.h.
{
    static EveShapeDrawer EVE_SHAPE_DRAWER;
    return EVE_SHAPE_DRAWER;
  }
Referenced by eventdisplay::Objects::draw(), eventdisplay::EveDetectorGeometry::drawECAL(), eventdisplay::EveDetectorGeometry::drawHCAL(), and eventdisplay::EveDetectorGeometry::drawRecoilTracker().
Member Data Documentation
uid_
UInt_t eventdisplay::EveShapeDrawer::uid_ = 0 private
Definition at line 151 of file EveShapeDrawer.h.
The documentation for this class was generated from the following file:
EventDisplay/include/EventDisplay/EveShapeDrawer.h