LDMX Software: ldmx::G4CalorimeterHit Class Reference
ldmx::G4CalorimeterHit Class Reference
Calorimeter hit which is used to create output SimCalorimeterHit objects.
#include <G4CalorimeterHit.h>
Public Member Functions
G4CalorimeterHit ()
virtual ~G4CalorimeterHit ()
void Draw ()
void Print ()
std::ostream & print (std::ostream &os)
void * operator new (size_t s)
void operator delete (void *aHit)
G4int getTrackID ()
void setTrackID (int trackID)
int getID ()
void setID (int id)
float getEdep ()
void setEdep (float edep)
const G4ThreeVector & getPosition ()
void setPosition (const float x, const float y, const float z)
float getTime ()
void setTime (float time)
int getPdgCode ()
void setPdgCode (int pdgCode)
Private Attributes
int trackID_ {-1}
int id_ {0}
double edep_ {0}
G4ThreeVector position_
float time_ {0}
int pdgCode_ {0}
Detailed Description
Calorimeter hit which is used to create output SimCalorimeterHit objects.
One of these is created for every step in a CalorimeterSD. These hits are combined later at the end of the event by the RootPersistencyManager from matching their detector IDs.
Definition at line 29 of file G4CalorimeterHit.h.
Constructor & Destructor Documentation
G4CalorimeterHit()
ldmx::G4CalorimeterHit::G4CalorimeterHit () inline
Class constructor.
Definition at line 36 of file G4CalorimeterHit.h.
{
             }
~G4CalorimeterHit()
virtual ldmx::G4CalorimeterHit::~G4CalorimeterHit () inline virtual
Class destructor.
Definition at line 42 of file G4CalorimeterHit.h.
{
             }
Member Function Documentation
Draw()
void ldmx::G4CalorimeterHit::Draw ()
Draw the hit in the Geant4 runtime.
Definition at line 13 of file G4CalorimeterHit.cxx.
{
         G4VVisManager* visManager = G4VVisManager::GetConcreteInstance();
         if (visManager) {
             G4Point3D p3D = G4Point3D(position_);
             G4Circle chit(p3D);
             chit.SetScreenDiameter(3.0);
             chit.SetFillStyle(G4Circle::filled);
             G4Colour col(1.0, 0.0, 1.0);
             chit.SetVisAttributes(G4VisAttributes(col));
             visManager->Draw(chit);
         }
     }
References position_.
getEdep()
float ldmx::G4CalorimeterHit::getEdep () inline
Get the energy deposition of the hit.
Returns
The energy deposition of the hit.
Definition at line 110 of file G4CalorimeterHit.h.
{
                 return edep_;
             }
References edep_.
Referenced by ldmx::RootPersistencyManager::writeCalorimeterHitsCollection(), and ldmx::EcalHitIO::writeHitsCollection().
getID()
int ldmx::G4CalorimeterHit::getID () inline
Get the detector ID of the hit.
Returns
The detector ID of the hit.
Definition at line 94 of file G4CalorimeterHit.h.
{
                 return id_;
             }
References id_.
Referenced by ldmx::RootPersistencyManager::writeCalorimeterHitsCollection(), and ldmx::EcalHitIO::writeHitsCollection().
getPdgCode()
int ldmx::G4CalorimeterHit::getPdgCode () inline
Get the PDG code of the track that made this hit.
Returns
The PDG code of the track that made the hit.
Definition at line 160 of file G4CalorimeterHit.h.
{
                 return pdgCode_;
             }
References pdgCode_.
Referenced by ldmx::RootPersistencyManager::writeCalorimeterHitsCollection(), and ldmx::EcalHitIO::writeHitsCollection().
getPosition()
const G4ThreeVector& ldmx::G4CalorimeterHit::getPosition () inline
Get the XYZ hit position [mm].
Returns
The hit position.
Definition at line 126 of file G4CalorimeterHit.h.
{
                 return position_;
             }
References position_.
Referenced by ldmx::RootPersistencyManager::writeCalorimeterHitsCollection().
getTime()
float ldmx::G4CalorimeterHit::getTime () inline
Get the global time of the hit [ns].
Returns
The global hit time.
Definition at line 144 of file G4CalorimeterHit.h.
{
                 return time_;
             }
References time_.
Referenced by ldmx::RootPersistencyManager::writeCalorimeterHitsCollection(), and ldmx::EcalHitIO::writeHitsCollection().
getTrackID()
G4int ldmx::G4CalorimeterHit::getTrackID () inline
Get the track ID of the hit.
Returns
The track ID of the hit.
Definition at line 78 of file G4CalorimeterHit.h.
{
                 return trackID_;
             }
References trackID_.
Referenced by ldmx::RootPersistencyManager::writeCalorimeterHitsCollection(), and ldmx::EcalHitIO::writeHitsCollection().
operator delete()
void ldmx::G4CalorimeterHit::operator delete (void * aHit) inline
Delete a hit object.
Parameters
aHit The hit to delete.
Implementation of custom delete operator.
Definition at line 228 of file G4CalorimeterHit.h.
{
         G4CalorimeterHitAllocator.FreeSingle((G4CalorimeterHit*) aHit);
     }
References ldmx::G4CalorimeterHitAllocator.
operator new()
void * ldmx::G4CalorimeterHit::operator new (size_t s) inline
Create a new hit object.
Parameters
s The size of the hit object.
Implementation of custom new operator.
Definition at line 219 of file G4CalorimeterHit.h.
{
         void* aHit;
         aHit = (void*) G4CalorimeterHitAllocator.MallocSingle();
         return aHit;
     }
References ldmx::G4CalorimeterHitAllocator.
Print()
void ldmx::G4CalorimeterHit::Print ()
Print information about the hit.
Definition at line 30 of file G4CalorimeterHit.cxx.
{
         print(std::cout);
     }
References print().
Referenced by ldmx::EcalSD::ProcessHits().
print()
std::ostream & ldmx::G4CalorimeterHit::print (std::ostream & os)
Print hit information to an output stream.
Parameters
os The output stream.
Returns
The same output stream.
Definition at line 34 of file G4CalorimeterHit.cxx.
{
         os << "G4CalorimeterHit { " << "edep: " << this->edep_ << ", " << "position: " << position_ << ", " << "time: " << this->time_ << " }" << std::endl;
         return os;
     }
References edep_, position_, and time_.
Referenced by Print().
setEdep()
void ldmx::G4CalorimeterHit::setEdep (float edep) inline
Set the energy deposition.
Parameters
edep The energy deposition.
Definition at line 118 of file G4CalorimeterHit.h.
{
                 this->edep_ = edep;
             }
References edep_.
Referenced by ldmx::TrigScintSD::ProcessHits(), ldmx::HcalSD::ProcessHits(), and ldmx::EcalSD::ProcessHits().
setID()
void ldmx::G4CalorimeterHit::setID (int id) inline
Set the detector ID.
Parameters
id The detector ID.
Definition at line 102 of file G4CalorimeterHit.h.
{
                 this->id_ = id;
             }
References id_.
Referenced by ldmx::EcalSD::ProcessHits().
setPdgCode()
void ldmx::G4CalorimeterHit::setPdgCode (int pdgCode) inline
Set the PDG code from the track that made the hit.
Parameters
pdgCode The PDG code.
Definition at line 168 of file G4CalorimeterHit.h.
{
                 pdgCode_ = pdgCode;
             }
References pdgCode_.
Referenced by ldmx::EcalSD::ProcessHits().
setPosition()
void ldmx::G4CalorimeterHit::setPosition (const float x, const float y, const float z) inline
Set the hit position [mm].
Parameters
x The X position.
y The Y position.
z The Z position.
Definition at line 136 of file G4CalorimeterHit.h.
{
                 position_.set(x, y, z);
             }
References position_.
Referenced by ldmx::HcalSD::ProcessHits(), and ldmx::EcalSD::ProcessHits().
setTime()
void ldmx::G4CalorimeterHit::setTime (float time) inline
Set the global hit time [ns].
Parameters
time The global hit time.
Definition at line 152 of file G4CalorimeterHit.h.
{
                 this->time_ = time;
             }
References time_.
Referenced by ldmx::HcalSD::ProcessHits(), and ldmx::EcalSD::ProcessHits().
setTrackID()
void ldmx::G4CalorimeterHit::setTrackID (int trackID) inline
Set the track ID.
Parameters
trackID The track ID.
Definition at line 86 of file G4CalorimeterHit.h.
{
                 this->trackID_ = trackID;
             }
References trackID_.
Referenced by ldmx::EcalSD::ProcessHits().
Member Data Documentation
edep_
double ldmx::G4CalorimeterHit::edep_ {0} private
The energy deposition.
Definition at line 187 of file G4CalorimeterHit.h.
Referenced by getEdep(), print(), and setEdep().
id_
int ldmx::G4CalorimeterHit::id_ {0} private
The detector ID.
Definition at line 182 of file G4CalorimeterHit.h.
Referenced by getID(), and setID().
pdgCode_
int ldmx::G4CalorimeterHit::pdgCode_ {0} private
The PDG code.
Definition at line 202 of file G4CalorimeterHit.h.
Referenced by getPdgCode(), and setPdgCode().
position_
G4ThreeVector ldmx::G4CalorimeterHit::position_ private
The hit position.
Definition at line 192 of file G4CalorimeterHit.h.
Referenced by Draw(), getPosition(), print(), and setPosition().
time_
float ldmx::G4CalorimeterHit::time_ {0} private
The global time.
Definition at line 197 of file G4CalorimeterHit.h.
Referenced by getTime(), print(), and setTime().
trackID_
int ldmx::G4CalorimeterHit::trackID_ {-1} private
The track ID.
Definition at line 177 of file G4CalorimeterHit.h.
Referenced by getTrackID(), and setTrackID().
The documentation for this class was generated from the following files:
SimCore/include/SimCore/G4CalorimeterHit.h
SimCore/src/G4CalorimeterHit.cxx