LDMX Software: biasing::PhotoNuclearProductsFilter Class Reference
biasing::PhotoNuclearProductsFilter Class Reference
#include <PhotoNuclearProductsFilter.h>
Public Member Functions
PhotoNuclearProductsFilter (const std::string &name, framework::config::Parameters &parameters)
~PhotoNuclearProductsFilter ()
Destructor.
void stepping (const G4Step *step) final override
std::vector< simcore::TYPE > getTypes () final override
Retrieve the type of actions this class defines.
Public Member Functions inherited from simcore::UserAction
UserAction (const std::string &name, framework::config::Parameters &parameters)
virtual ~UserAction ()
Destructor.
virtual void BeginOfEventAction (const G4Event *)
virtual void EndOfEventAction (const G4Event *)
virtual void BeginOfRunAction (const G4Run *)
virtual void EndOfRunAction (const G4Run *)
virtual void PreUserTrackingAction (const G4Track *)
virtual void PostUserTrackingAction (const G4Track *)
virtual void stepping (const G4Step *)
virtual G4ClassificationOfNewTrack ClassifyNewTrack (const G4Track *, const G4ClassificationOfNewTrack &cl)
virtual void NewStage ()
virtual void PrepareNewEvent ()
virtual std::vector< TYPE > getTypes ()=0
Private Attributes
std::vector< int > productsPdgID_
Container to hold the PDG IDs of products of interest.
Additional Inherited Members
Public Types inherited from simcore::UserAction
using Factory = ::simcore::Factory< UserAction, std::shared_ptr< UserAction >, const std::string &, framework::config::Parameters & >
factory for user actions
Protected Member Functions inherited from simcore::UserAction
UserEventInformation * getEventInfo () const
const std::map< int, ldmx::SimParticle > & getCurrentParticleMap () const
Protected Attributes inherited from simcore::UserAction
std::string name_ {""}
Name of the UserAction.
framework::config::Parameters parameters_
The set of parameters used to configure this class.
Detailed Description
User action used to filter out photo-nuclear events that don't see the photo-nuclear gamma produce specific products.
This user action will only process steps whose associated track has been tagged as a "PN Gamma". This tag is currently only set in ECalProcessFilter and needs to be placed in the UserAction pipeline before this class. The desired products are passed to this class through the parameter vector<int> parameter "pdg_ids".
Definition at line 30 of file PhotoNuclearProductsFilter.h.
Constructor & Destructor Documentation
PhotoNuclearProductsFilter()
biasing::PhotoNuclearProductsFilter::PhotoNuclearProductsFilter (const std::string & name, framework::config::Parameters & parameters)
Constructor
Parameters
[in] name The name of this class instance.
[in] parameters The parameters used to configure this class.
Definition at line 22 of file PhotoNuclearProductsFilter.cxx.
    : simcore::UserAction(name, parameters) {
  productsPdgID_ = parameters.getParameter<std::vector<int> >("pdg_ids");
}
References framework::config::Parameters::getParameter(), and productsPdgID_.
~PhotoNuclearProductsFilter()
biasing::PhotoNuclearProductsFilter::~PhotoNuclearProductsFilter ()
Destructor.
Definition at line 28 of file PhotoNuclearProductsFilter.cxx.
{}
Member Function Documentation
getTypes()
std::vector< simcore::TYPE > biasing::PhotoNuclearProductsFilter::getTypes () inline final override virtual
Retrieve the type of actions this class defines.
Implements simcore::UserAction.
Definition at line 54 of file PhotoNuclearProductsFilter.h.
{
    return {simcore::TYPE::STEPPING};
  }
stepping()
void biasing::PhotoNuclearProductsFilter::stepping (const G4Step * step) final override virtual
Callback that allows a user to take some actions at the end of a step.
Parameters
[in] step The Geant4 step containing transient information about the step taken by a track.
Reimplemented from simcore::UserAction.
Definition at line 30 of file PhotoNuclearProductsFilter.cxx.
{
  // Get the track associated with this step.
  auto track{step->GetTrack()};
  // Get the track info and check if this track has been tagged as the
  // photon that underwent a photo-nuclear reaction. Only those tracks
  // tagged as PN photos will be processed. The track is currently only
  // tagged by the UserAction ECalProcessFilter which needs to be run
  // before this UserAction.
  auto trackInfo{simcore::UserTrackInformation::get(track)};
  if ((trackInfo != nullptr) && !trackInfo->isPNGamma()) return;
  // Get the PN photon daughters.
  auto secondaries{step->GetSecondary()};
  // Loop through all of the secondaries and check for the product of
  // interest.  This is done by getting the PDG ID of a daughter and
  // checking that it's in the vector of PDG IDs passed to this
  // UserAction.
  bool productFound{false};
  for (const auto& secondary : *secondaries) {
    // Get the PDG ID of the track
    auto pdgID{std::abs(secondary->GetParticleDefinition()->GetPDGEncoding())};
    // Check if the PDG ID is in the list of products of interest
    if (std::find(productsPdgID_.begin(), productsPdgID_.end(), pdgID) !=
        productsPdgID_.end()) {
      productFound = true;
      break;
    }
  }
  // If the product of interest was not found, kill the track and abort
  // the event.
  if (!productFound) {
    track->SetTrackStatus(fKillTrackAndSecondaries);
    G4RunManager::GetRunManager()->AbortEvent();
    return;
  }
  // Once the PN gamma has been procesed, untag it so its not reprocessed
  // again.
  trackInfo->tagPNGamma(false);
}
References simcore::UserTrackInformation::get(), productsPdgID_, and simcore::UserTrackInformation::tagPNGamma().
Member Data Documentation
productsPdgID_
std::vector<int> biasing::PhotoNuclearProductsFilter::productsPdgID_ private
Container to hold the PDG IDs of products of interest.
Definition at line 60 of file PhotoNuclearProductsFilter.h.
Referenced by PhotoNuclearProductsFilter(), and stepping().
The documentation for this class was generated from the following files:
Biasing/include/Biasing/PhotoNuclearProductsFilter.h
Biasing/src/Biasing/PhotoNuclearProductsFilter.cxx