LDMX Software: conditions::BaseTableCondition Class Reference
conditions::BaseTableCondition Class Reference
Public Member Functions
BaseTableCondition (const std::string &name, const std::vector< std::string > &columns)
unsigned int getColumnNumber (const std::string &colname) const
unsigned int getColumnCount () const
const std::string & getColumnName (unsigned int icol) const
unsigned int getRowId (unsigned int irow) const
const std::vector< std::string > & getColumnNames () const
std::size_t getRowCount () const
void setIdMask (unsigned int mask)
unsigned int getIdMask () const
Public Member Functions inherited from framework::ConditionsObject
ConditionsObject (const std::string &name)
virtual ~ConditionsObject ()
std::string getName () const
Protected Member Functions
std::size_t findKey (unsigned int id) const
std::size_t findKeyInsert (unsigned int id) const
Protected Attributes
std::vector< std::string > columns_
unsigned int columnCount_
std::vector< uint32_t > keys_
unsigned int idMask_
Detailed Description
Definition at line 20 of file SimpleTableCondition.h.
Constructor & Destructor Documentation
BaseTableCondition()
conditions::BaseTableCondition::BaseTableCondition (const std::string & name, const std::vector< std::string > & columns) inline
Create table with given set of columns
Definition at line 23 of file SimpleTableCondition.h.
      : framework::ConditionsObject{name},
        columns_{columns},
        idMask_{0xFFFFFFFFu} {
    columnCount_ = (unsigned int)(columns.size());
  }
Member Function Documentation
findKey()
std::size_t conditions::BaseTableCondition::findKey (unsigned int id) const protected
Definition at line 6 of file BaseTableCondition.cxx.
{
  unsigned int effid = id & idMask_;
  std::vector<unsigned int>::const_iterator ptr =
      std::lower_bound(keys_.begin(), keys_.end(), effid);
  if (ptr == keys_.end() || *ptr != effid)
    return keys_.size();
  else
    return std::distance(keys_.begin(), ptr);
}
findKeyInsert()
std::size_t conditions::BaseTableCondition::findKeyInsert (unsigned int id) const protected
Definition at line 16 of file BaseTableCondition.cxx.
{
  unsigned int effid = id & idMask_;
  std::vector<unsigned int>::const_iterator ptr =
      std::lower_bound(keys_.begin(), keys_.end(), effid);
  return std::distance(keys_.begin(), ptr);
}
getColumnCount()
unsigned int conditions::BaseTableCondition::getColumnCount () const inline
Get the number of columns
Definition at line 43 of file SimpleTableCondition.h.
{ return columnCount_; }
Referenced by ecal::EcalReconConditions::EcalReconConditions(), hcal::HcalReconConditions::HcalReconConditions(), and ldmx::HgcrocTriggerConditions::HgcrocTriggerConditions().
getColumnName()
const std::string & conditions::BaseTableCondition::getColumnName (unsigned int icol) const inline
Get the name of the given column
Definition at line 48 of file SimpleTableCondition.h.
{
    if (icol >= columnCount_) {
      EXCEPTION_RAISE("ConditionsException",
                      std::string("Column index out of range in ") + getName());
    }
    return columns_[icol];
  }
References framework::ConditionsObject::getName().
getColumnNames()
const std::vector< std::string > & conditions::BaseTableCondition::getColumnNames () const inline
Get the names of the columns
Definition at line 70 of file SimpleTableCondition.h.
{ return columns_; }
Referenced by ecal::EcalReconConditions::EcalReconConditions(), hcal::HcalReconConditions::HcalReconConditions(), and ldmx::HgcrocTriggerConditions::HgcrocTriggerConditions().
getColumnNumber()
unsigned int conditions::BaseTableCondition::getColumnNumber (const std::string & colname) const inline
Get a the column number for the given column name
Definition at line 34 of file SimpleTableCondition.h.
{
    for (unsigned int i = 0; i < columnCount_; i++)
      if (colname == columns_[i]) return i;
    return columnCount_;
  }
Referenced by conditions::HomogenousTableCondition< T >::getByName(), and ldmx::HgcrocEmulator::getCondition().
getIdMask()
unsigned int conditions::BaseTableCondition::getIdMask () const inline
Get the AND mask to be applied to the id. Typically used to "flatten" a table in some manner.
Definition at line 87 of file SimpleTableCondition.h.
{ return idMask_; }
getRowCount()
std::size_t conditions::BaseTableCondition::getRowCount () const inline
Get the number of rows
Definition at line 75 of file SimpleTableCondition.h.
{ return keys_.size(); }
Referenced by conditions::HomogenousTableCondition< T >::add(), conditions::HomogenousTableCondition< T >::get(), conditions::HomogenousTableCondition< T >::getRow(), and getRowId().
getRowId()
unsigned int conditions::BaseTableCondition::getRowId (unsigned int irow) const inline
Get the id for the given row
Definition at line 59 of file SimpleTableCondition.h.
{
    if (irow >= getRowCount()) {  // raise exception
      EXCEPTION_RAISE("ConditionsException",
                      "Row out of range: " + std::to_string(irow));
    }
    return keys_[irow];
  }
References getRowCount().
setIdMask()
void conditions::BaseTableCondition::setIdMask (unsigned int mask) inline
Set an AND mask to be applied to the id. Typically used to "flatten" a table in some manner.
Definition at line 81 of file SimpleTableCondition.h.
{ idMask_ = mask; }
Referenced by conditions::SimpleCSVTableProvider::getCondition().
Member Data Documentation
columnCount_
unsigned int conditions::BaseTableCondition::columnCount_ protected
Definition at line 95 of file SimpleTableCondition.h.
columns_
std::vector<std::string> conditions::BaseTableCondition::columns_ protected
Definition at line 94 of file SimpleTableCondition.h.
idMask_
unsigned int conditions::BaseTableCondition::idMask_ protected
Definition at line 97 of file SimpleTableCondition.h.
keys_
std::vector<uint32_t> conditions::BaseTableCondition::keys_ protected
Definition at line 96 of file SimpleTableCondition.h.
The documentation for this class was generated from the following files:
Conditions/include/Conditions/SimpleTableCondition.h
Conditions/src/Conditions/BaseTableCondition.cxx