LDMX Software: framework::StorageControl Class Reference
framework::StorageControl Class Reference
Class which encapsulates storage control functionality, used by the Process class.
#include <StorageControl.h>
Classes
struct Hint
struct Rule
Public Member Functions
void setDefaultKeep (bool keep)
void resetEventState ()
void addHint (const std::string &processor_name, framework::StorageControlHint hint, const std::string &purposeString)
void addRule (const std::string &processor_pat, const std::string &purpose_pat)
bool keepEvent (bool event_completed) const
Private Attributes
bool defaultIsKeep_ {true}
std::vector< Hint > hints_
std::vector< Rule > rules_
Detailed Description
Class which encapsulates storage control functionality, used by the Process class.
Any EventProcessor can provide a hint as to whether a given event should be kept or dropped. The hint is cached in the StorageControl object until the end of the event. At that point, the process queries the StorageControl to determine if the event should be stored in the output file.
Definition at line 35 of file StorageControl.h.
Member Function Documentation
addHint()
void framework::StorageControl::addHint (const std::string & processor_name, framework::StorageControlHint hint, const std::string & purposeString)
Add a storage hint for a given module
Parameters
processor_name Name of the event processor
controlhint The storage control hint to apply for the given event
purposeString A purpose string which can be used in the skim control configuration
Definition at line 10 of file StorageControl.cxx.
{
  hints_.push_back(Hint());
  hints_.back().evpName_ = processor_name;
  hints_.back().hint_ = hint;
  hints_.back().purpose_ = purposeString;
}
References hints_.
Referenced by framework::EventProcessor::setStorageHint().
addRule()
void framework::StorageControl::addRule (const std::string & processor_pat, const std::string & purpose_pat)
Add a rule
Parameters
processor_pattern Regex pattern to compare with event processor
purpose_pattern Regex pattern to compare with the purpose string
Definition at line 19 of file StorageControl.cxx.
{
  if (processor_pat.empty()) return;
  regex_t* preg = new regex_t;
  int error = regcomp(preg, processor_pat.c_str(), REG_EXTENDED | REG_NOSUB);
  if (error) {
    char msg[1024];
    regerror(error, preg, msg, 1024);
    delete preg;
    EXCEPTION_RAISE("SkimRuleException", msg);
  }
  // ok, then keep it
  rules_.push_back(Rule());
  rules_.back().evpNameRegex_ = preg;
  if (!purpose_pat.empty()) {
    preg = new regex_t;
    int error = regcomp(preg, purpose_pat.c_str(), REG_EXTENDED | REG_NOSUB);
    if (error) {
      char msg[1024];
      regerror(error, preg, msg, 1024);
      delete preg;
      EXCEPTION_RAISE("SkimRuleException", msg);
    }
    rules_.back().purposeRegex_ = preg;
  }
  rules_.back().evpNamePattern_ = processor_pat;
  rules_.back().purposePattern_ = purpose_pat;
}
References rules_.
Referenced by framework::Process::Process().
keepEvent()
bool framework::StorageControl::keepEvent (bool event_completed) const
Determine if the current event should be kept, based on the defined rules
Note
If event_completed is false, we don't listen to anything and decide not to keep the event.
Parameters
[in] event_completed did we complete processing of the current event?
Returns
true if we should store the current event into the output file
Definition at line 60 of file StorageControl.cxx.
{
  if (not event_completed) return false;
  int votesKeep(0), votesDrop(0);
  // loop over all rules and then over all hints
  for (auto rule : rules_) {
    for (auto hint : hints_) {
      if (!rule.matches(hint)) continue;
      if (hint.hint_ == hint_shouldKeep || hint.hint_ == hint_mustKeep)
        votesKeep++;
      else if (hint.hint_ == hint_shouldDrop || hint.hint_ == hint_mustDrop)
        votesDrop++;
    }
  }
  // easy case
  if (!votesKeep && !votesDrop) return defaultIsKeep_;
  // harder cases
  if (votesKeep > votesDrop) return true;
  if (votesDrop > votesKeep) return false;
  // at the end, go with the default
  return defaultIsKeep_;
}
References defaultIsKeep_, hints_, and rules_.
Referenced by framework::Process::run().
resetEventState()
void framework::StorageControl::resetEventState ()
Reset the event-by-event state
Definition at line 8 of file StorageControl.cxx.
{ hints_.clear(); }
References hints_.
Referenced by framework::Process::run().
setDefaultKeep()
void framework::StorageControl::setDefaultKeep (bool keep) inline
Set the default state
Definition at line 38 of file StorageControl.h.
{ defaultIsKeep_ = keep; }
References defaultIsKeep_.
Referenced by framework::Process::Process().
Member Data Documentation
defaultIsKeep_
bool framework::StorageControl::defaultIsKeep_ {true} private
Default state for storage control
Definition at line 79 of file StorageControl.h.
Referenced by keepEvent(), and setDefaultKeep().
hints_
std::vector<Hint> framework::StorageControl::hints_ private
Collection of hints from the event processors
Definition at line 102 of file StorageControl.h.
Referenced by addHint(), keepEvent(), and resetEventState().
rules_
std::vector<Rule> framework::StorageControl::rules_ private
Collection of hints from the event processors
Definition at line 138 of file StorageControl.h.
Referenced by addRule(), and keepEvent().
The documentation for this class was generated from the following files:
Framework/include/Framework/StorageControl.h
Framework/src/Framework/StorageControl.cxx