LDMX Software: trigscint::TrigScintQIEDigiProducer Class Reference
trigscint::TrigScintQIEDigiProducer Class Reference
Class that simulates QIE chip of the trigger scintillator.
#include <TrigScintQIEDigiProducer.h>
Public Member Functions
TrigScintQIEDigiProducer (const std::string &name, framework::Process &process)
void configure (framework::config::Parameters &parameters) final override
void produce (framework::Event &event)
For each event, the SimHit information is converted to an output format analogous to real QIE output.
Public Member Functions inherited from framework::Producer
Producer (const std::string &name, Process &process)
virtual void produce (Event &event)=0
virtual void beforeNewRun (ldmx::RunHeader &header)
Public Member Functions inherited from framework::EventProcessor
EventProcessor (const std::string &name, Process &process)
virtual ~EventProcessor ()
virtual void configure (framework::config::Parameters &parameters)
virtual void onNewRun (const ldmx::RunHeader &runHeader)
virtual void onFileOpen (EventFile &eventFile)
virtual void onFileClose (EventFile &eventFile)
virtual void onProcessStart ()
virtual void onProcessEnd ()
template<class T >
const T & getCondition (const std::string &condition_name)
TDirectory * getHistoDirectory ()
void setStorageHint (framework::StorageControlHint hint)
void setStorageHint (framework::StorageControlHint hint, const std::string &purposeString)
int getLogFrequency () const
int getRunNumber () const
std::string getName () const
void createHistograms (const std::vector< framework::config::Parameters > &histos)
Private Attributes
std::unique_ptr< TRandom3 > random_ {nullptr}
Random number generator.
bool verbose_ {false}
Class to set the verbosity level.
std::string inputCollection_
Name of the input collection containing the sim hits.
std::string inputPassName_
std::string outputCollection_
int stripsPerArray_ {50}
Number of strips per array.
int numberOfArrays_ {3}
Number of arrays.
double meanNoise_ {0}
Mean readout noise.
double mevPerMip_ {1.40}
Total MeV per MIP.
double pePerMip_ {13.5}
Total number of photoelectrons per MIP.
std::string input_pulse_shape_
QIE Input pulse shape.
std::vector< float > pulse_params_
QIE Input pulse parameters.
float toff_overall_
Overall input pulse time offset.
int maxts_
no. of time samples analysed by QIE
float tdc_thr_
QIE TDC Current threshold.
float pedestal_
QIE pedestal.
float elec_noise_
QIE electronic noise.
float sipm_gain_
SiPM Gain.
float s_freq_
QIE sampling frequency [in MHz].
float zeroSuppCut_ {1.}
Zero-suppression: discard any integrated pulses with PE < this number.
SimQIE * smq_ {nullptr}
SimQIE pointer.
Additional Inherited Members
Static Public Member Functions inherited from framework::EventProcessor
static void declare (const std::string &classname, int classtype, EventProcessorMaker *)
Static Public Attributes inherited from framework::Producer
static const int CLASSTYPE {1}
Protected Member Functions inherited from framework::EventProcessor
void abortEvent ()
Protected Attributes inherited from framework::EventProcessor
HistogramHelper histograms_
Interface class for making and filling histograms.
NtupleManager & ntuple_ {NtupleManager::getInstance()}
Manager for any ntuples.
logging::logger theLog_
The logger for this EventProcessor.
Detailed Description
Class that simulates QIE chip of the trigger scintillator.
Definition at line 48 of file TrigScintQIEDigiProducer.h.
Constructor & Destructor Documentation
TrigScintQIEDigiProducer()
trigscint::TrigScintQIEDigiProducer::TrigScintQIEDigiProducer (const std::string & name, framework::Process & process)
Definition at line 10 of file TrigScintQIEDigiProducer.cxx.
    : Producer(name, process) {}
~TrigScintQIEDigiProducer()
trigscint::TrigScintQIEDigiProducer::~TrigScintQIEDigiProducer ()
Definition at line 14 of file TrigScintQIEDigiProducer.cxx.
{}
Member Function Documentation
configure()
void trigscint::TrigScintQIEDigiProducer::configure (framework::config::Parameters & parameters) final override virtual
Callback for the processor to configure itself from the given set of parameters.
Parameters
parameters ParameterSet for configuration.
Reimplemented from framework::EventProcessor.
Definition at line 16 of file TrigScintQIEDigiProducer.cxx.
{
  // Configure this instance of the producer
  stripsPerArray_ = parameters.getParameter<int>("number_of_strips");
  numberOfArrays_ = parameters.getParameter<int>("number_of_arrays");
  meanNoise_ = parameters.getParameter<double>("mean_noise");
  mevPerMip_ = parameters.getParameter<double>("mev_per_mip");
  pePerMip_ = parameters.getParameter<double>("pe_per_mip");
  inputCollection_ = parameters.getParameter<std::string>("input_collection");
  inputPassName_ = parameters.getParameter<std::string>("input_pass_name");
  outputCollection_ = parameters.getParameter<std::string>("output_collection");
  verbose_ = parameters.getParameter<bool>("verbose");
  // QIE specific parameters initialization
  maxts_ = parameters.getParameter<int>("maxts");
  toff_overall_ = parameters.getParameter<double>("toff_overall");
  input_pulse_shape_ =
      parameters.getParameter<std::string>("input_pulse_shape");
  tdc_thr_ = parameters.getParameter<double>("tdc_thr");
  pedestal_ = parameters.getParameter<double>("pedestal");
  elec_noise_ = parameters.getParameter<double>("elec_noise");
  sipm_gain_ = parameters.getParameter<double>("sipm_gain");
  s_freq_ = parameters.getParameter<double>("qie_sf");
  zeroSuppCut_ = parameters.getParameter<double>("zeroSupp_in_pe");
  if (input_pulse_shape_ == "Expo") {
    pulse_params_.clear();
    pulse_params_.push_back(parameters.getParameter<double>("expo_k"));
    pulse_params_.push_back(parameters.getParameter<double>("expo_tmax"));
    ldmx_log(debug) << "expo_k =" << pulse_params_[0];
    ldmx_log(debug) << "expo_tmax =" << pulse_params_[1];
  }
  // Debug mode: print parameter values.
  ldmx_log(debug) << "maxts_ =" << maxts_;
  ldmx_log(debug) << "toff_overall_ =" << toff_overall_;
  ldmx_log(debug) << "input_pulse_shape_ =" << input_pulse_shape_;
  ldmx_log(debug) << "tdc_thr =" << tdc_thr_;
  ldmx_log(debug) << "pedestal =" << pedestal_;
  ldmx_log(debug) << "elec_noise =" << elec_noise_;
  ldmx_log(debug) << "sipm_gain =" << sipm_gain_;
  ldmx_log(debug) << "qie_sf =" << s_freq_;
  ldmx_log(debug) << "zeroSupp_in_pe =" << zeroSuppCut_;
  ldmx_log(debug) << "pe_per_mip =" << pePerMip_;
  ldmx_log(debug) << "mev_per_mip =" << mevPerMip_;
}
References framework::config::Parameters::getParameter().
produce()
void trigscint::TrigScintQIEDigiProducer::produce (framework::Event & event) virtual
For each event, the SimHit information is converted to an output format analogous to real QIE output.
Method to produce a collection of QIE digis.
Implements framework::Producer.
Definition at line 64 of file TrigScintQIEDigiProducer.cxx.
{
  // Need to handle seeding on the first event
  if (random_.get() == nullptr) {
    const auto& rseed = getCondition<framework::RandomNumberSeedService>(
        framework::RandomNumberSeedService::CONDITIONS_OBJECT_NAME);
    const auto& rseed2 = getCondition<framework::RandomNumberSeedService>(
        framework::RandomNumberSeedService::CONDITIONS_OBJECT_NAME);
    random_ = std::make_unique<TRandom3>(rseed.getSeed(outputCollection_));
    // Initialize SimQIE instance with
    // pedestal, electronic noise and the random seed
    smq_ = new SimQIE(pedestal_, elec_noise_,
                      rseed2.getSeed(outputCollection_ + "SimQIE"));
    smq_->setGain(sipm_gain_);
    smq_->setFreq(s_freq_);
    smq_->setNTimeSamples(maxts_);
    smq_->setTDCThreshold(tdc_thr_);
  }
  // To simulate multiple pulses coming at different times, SiPMS
  float TrueEdep[stripsPerArray_];
  Expo* ex[stripsPerArray_] = {0};
  for (int i = 0; i < stripsPerArray_; i++) {
    // Set the pulse shape with fixed parameters given by config. file
    ex[i] = new Expo(pulse_params_[0], pulse_params_[1]);
    TrueEdep[i] = 0;
  }
  // loop over sim hits and aggregate energy depositions for each detID
  const auto simHits{event.getCollection<ldmx::SimCalorimeterHit>(
      inputCollection_, inputPassName_)};
  for (const auto& simHit : simHits) {
    ldmx::TrigScintID id(simHit.getID());
    ldmx_log(debug) << "Processing sim hit with bar ID: " << id.bar();
    // Simulating the noise corresponding to uncertainity in
    // detecting scintillating photons.
    // Poissonian distribution with mean = mean PEs generated
    double PulseAmp =
        random_->Poisson(simHit.getEdep() / mevPerMip_ * pePerMip_);
    // Adding a pulse for every sim hit recorded.
    // time offset = global offset+simhit time
    ex[id.bar()]->AddPulse(toff_overall_ + simHit.getTime(), PulseAmp);
    // incrementing true energy deposited in appropriate bar.
    TrueEdep[id.bar()] += simHit.getEdep();
  }
  // A container to hold the digitized trigger scintillator hits.
  std::vector<trigscint::TrigScintQIEDigis> QDigis;
  double TotalNoise = meanNoise_ * maxts_;
  // time period[ns] = 1000/sampling freq.[MHz]
  double SamplingTime = 1000 / s_freq_;
  // Loop over all the bars available.
  for (int bar_id = 0; bar_id < stripsPerArray_; bar_id++) {
    // Dark current simulation
    // e-hole pairs may be generated at random times in SiPM
    // due to thermal fluctuations.
    // Every e- thus generated, mimicks a Photo Electron.
    // Hence we will creat 1PE pulses for each electron generated.
    int n_noise_pulses = random_->Poisson(TotalNoise);
    for (int i = 0; i < n_noise_pulses; i++) {
      ex[bar_id]->AddPulse(random_->Uniform(0, maxts_ * SamplingTime), 1);
    }
    // Storing the "good" digis
    if (smq_->PulseCut(ex[bar_id], zeroSuppCut_)) {
      trigscint::TrigScintQIEDigis QIEInfo;
      QIEInfo.setChanID(bar_id);
      QIEInfo.setADC(smq_->Out_ADC(ex[bar_id]));
      QIEInfo.setTDC(smq_->Out_TDC(ex[bar_id]));
      QIEInfo.setCID(smq_->CapID(ex[bar_id]));
      QDigis.push_back(QIEInfo);
    }
  }
  event.add(outputCollection_, QDigis);
}
References trigscint::QIEInputPulse::AddPulse(), framework::RandomNumberSeedService::CONDITIONS_OBJECT_NAME, trigscint::TrigScintQIEDigis::setADC(), trigscint::TrigScintQIEDigis::setChanID(), trigscint::TrigScintQIEDigis::setCID(), and trigscint::TrigScintQIEDigis::setTDC().
Member Data Documentation
elec_noise_
float trigscint::TrigScintQIEDigiProducer::elec_noise_ private
QIE electronic noise.
Definition at line 122 of file TrigScintQIEDigiProducer.h.
input_pulse_shape_
std::string trigscint::TrigScintQIEDigiProducer::input_pulse_shape_ private
QIE Input pulse shape.
Definition at line 104 of file TrigScintQIEDigiProducer.h.
inputCollection_
std::string trigscint::TrigScintQIEDigiProducer::inputCollection_ private
Name of the input collection containing the sim hits.
Definition at line 78 of file TrigScintQIEDigiProducer.h.
inputPassName_
std::string trigscint::TrigScintQIEDigiProducer::inputPassName_ private
Name of the pass that the input collection is on (empty string means take any pass)
Definition at line 82 of file TrigScintQIEDigiProducer.h.
maxts_
int trigscint::TrigScintQIEDigiProducer::maxts_ private
no. of time samples analysed by QIE
Definition at line 113 of file TrigScintQIEDigiProducer.h.
meanNoise_
double trigscint::TrigScintQIEDigiProducer::meanNoise_ {0} private
Mean readout noise.
Definition at line 95 of file TrigScintQIEDigiProducer.h.
mevPerMip_
double trigscint::TrigScintQIEDigiProducer::mevPerMip_ {1.40} private
Total MeV per MIP.
Definition at line 98 of file TrigScintQIEDigiProducer.h.
numberOfArrays_
int trigscint::TrigScintQIEDigiProducer::numberOfArrays_ {3} private
Number of arrays.
Definition at line 92 of file TrigScintQIEDigiProducer.h.
outputCollection_
std::string trigscint::TrigScintQIEDigiProducer::outputCollection_ private
Name of the output collection that will be used to stored the digitized trigger scintillator hits
Definition at line 86 of file TrigScintQIEDigiProducer.h.
pedestal_
float trigscint::TrigScintQIEDigiProducer::pedestal_ private
QIE pedestal.
Definition at line 119 of file TrigScintQIEDigiProducer.h.
pePerMip_
double trigscint::TrigScintQIEDigiProducer::pePerMip_ {13.5} private
Total number of photoelectrons per MIP.
Definition at line 101 of file TrigScintQIEDigiProducer.h.
pulse_params_
std::vector<float> trigscint::TrigScintQIEDigiProducer::pulse_params_ private
QIE Input pulse parameters.
Definition at line 107 of file TrigScintQIEDigiProducer.h.
random_
std::unique_ptr<TRandom3> trigscint::TrigScintQIEDigiProducer::random_ {nullptr} private
Random number generator.
Definition at line 71 of file TrigScintQIEDigiProducer.h.
s_freq_
float trigscint::TrigScintQIEDigiProducer::s_freq_ private
QIE sampling frequency [in MHz].
Definition at line 128 of file TrigScintQIEDigiProducer.h.
sipm_gain_
float trigscint::TrigScintQIEDigiProducer::sipm_gain_ private
SiPM Gain.
Definition at line 125 of file TrigScintQIEDigiProducer.h.
smq_
SimQIE* trigscint::TrigScintQIEDigiProducer::smq_ {nullptr} private
SimQIE pointer.
Definition at line 134 of file TrigScintQIEDigiProducer.h.
stripsPerArray_
int trigscint::TrigScintQIEDigiProducer::stripsPerArray_ {50} private
Number of strips per array.
Definition at line 89 of file TrigScintQIEDigiProducer.h.
tdc_thr_
float trigscint::TrigScintQIEDigiProducer::tdc_thr_ private
QIE TDC Current threshold.
Definition at line 116 of file TrigScintQIEDigiProducer.h.
toff_overall_
float trigscint::TrigScintQIEDigiProducer::toff_overall_ private
Overall input pulse time offset.
Definition at line 110 of file TrigScintQIEDigiProducer.h.
verbose_
bool trigscint::TrigScintQIEDigiProducer::verbose_ {false} private
Class to set the verbosity level.
Definition at line 75 of file TrigScintQIEDigiProducer.h.
zeroSuppCut_
float trigscint::TrigScintQIEDigiProducer::zeroSuppCut_ {1.} private
Zero-suppression: discard any integrated pulses with PE < this number.
Definition at line 131 of file TrigScintQIEDigiProducer.h.
The documentation for this class was generated from the following files:
TrigScint/include/TrigScint/TrigScintQIEDigiProducer.h
TrigScint/src/TrigScint/TrigScintQIEDigiProducer.cxx