LDMX Software: ldmx::StorageControl Class Reference
ldmx::StorageControl Class Reference
Class which encapsulates storage control functionality, used by the Process class.
#include <StorageControl.h>
Classes
struct Hint
struct Rule
Public Member Functions
void setDefaultKeep (bool keep)
void resetEventState ()
void addHint (const std::string &processor_name, ldmx::StorageControlHint hint, const std::string &purposeString)
void addRule (const std::string &processor_pat, const std::string &purpose_pat)
bool keepEvent () const
Private Attributes
bool defaultIsKeep_ {true}
std::vector< Hint > hints_
std::vector< Rule > rules_
Detailed Description
Class which encapsulates storage control functionality, used by the Process class.
Any EventProcessor can provide a hint as to whether a given event should be kept or dropped. The hint is cached in the StorageControl object until the end of the event. At that point, the process queries the StorageControl to determine if the event should be stored in the output file.
Definition at line 34 of file StorageControl.h.
Member Function Documentation
addHint()
void ldmx::StorageControl::addHint (const std::string & processor_name, ldmx::StorageControlHint hint, const std::string & purposeString)
Add a storage hint for a given module
Parameters
processor_name Name of the event processor
controlhint The storage control hint to apply for the given event
purposeString A purpose string which can be used in the skim control configuration
Definition at line 12 of file StorageControl.cxx.
{
         hints_.push_back(Hint());
         hints_.back().evpName_=processor_name;
         hints_.back().hint_=hint;
         hints_.back().purpose_=purposeString;
     }
References hints_.
Referenced by ldmx::EventProcessor::setStorageHint().
addRule()
void ldmx::StorageControl::addRule (const std::string & processor_pat, const std::string & purpose_pat)
Add a rule
Parameters
processor_pattern Regex pattern to compare with event processor
purpose_pattern Regex pattern to compare with the purpose string
Definition at line 20 of file StorageControl.cxx.
{
         if (processor_pat.empty()) return;
         regex_t* preg=new regex_t;
         int error=regcomp(preg,processor_pat.c_str(),REG_EXTENDED|REG_NOSUB);
         if (error) {
             char msg[1024];
             regerror(error,preg,msg,1024);
             delete preg;
             EXCEPTION_RAISE("SkimRuleException",msg);
         }
         // ok, then keep it
         rules_.push_back(Rule());
         rules_.back().evpNameRegex_=preg;
         if (!purpose_pat.empty()) {
             preg=new regex_t;
             int error=regcomp(preg,purpose_pat.c_str(),REG_EXTENDED|REG_NOSUB);
             if (error) {
                 char msg[1024];
                 regerror(error,preg,msg,1024);
                 delete preg;
                 EXCEPTION_RAISE("SkimRuleException",msg);
             }
             rules_.back().purposeRegex_=preg;
         }
         rules_.back().evpNamePattern_=processor_pat;
         rules_.back().purposePattern_=purpose_pat;
     }
References EXCEPTION_RAISE, and rules_.
Referenced by TEST_CASE().
keepEvent()
bool ldmx::StorageControl::keepEvent () const
Determine if the current event should be kept, based on the defined rules
Definition at line 58 of file StorageControl.cxx.
{
         int votesKeep(0), votesDrop(0);
         // loop over all rules and then over all hints
         for (auto rule: rules_) {
             for (auto hint: hints_) {
                 if (!rule.matches(hint)) continue;
                 if (hint.hint_==hint_shouldKeep || hint.hint_==hint_mustKeep) votesKeep++;
                 else if (hint.hint_==hint_shouldDrop || hint.hint_==hint_mustDrop) votesDrop++;
             }
         }
         // easy case
         if (!votesKeep && !votesDrop) return defaultIsKeep_;
         // harder cases
         if (votesKeep>votesDrop) return true;
         if (votesDrop>votesKeep) return false;
         // at the end, go with the default
         return defaultIsKeep_;
     }
References defaultIsKeep_, hints_, and rules_.
Referenced by ldmx::Process::run().
resetEventState()
void ldmx::StorageControl::resetEventState ()
Reset the event-by-event state
Definition at line 8 of file StorageControl.cxx.
{
         hints_.clear();
     }
References hints_.
Referenced by ldmx::Process::run().
setDefaultKeep()
void ldmx::StorageControl::setDefaultKeep (bool keep) inline
Set the default state
Definition at line 39 of file StorageControl.h.
 { defaultIsKeep_=keep; }
References defaultIsKeep_.
Referenced by TEST_CASE().
Member Data Documentation
defaultIsKeep_
bool ldmx::StorageControl::defaultIsKeep_ {true} private
Default state for storage control
Definition at line 69 of file StorageControl.h.
Referenced by keepEvent(), and setDefaultKeep().
hints_
std::vector<Hint> ldmx::StorageControl::hints_ private
Collection of hints from the event processors
Definition at line 92 of file StorageControl.h.
Referenced by addHint(), keepEvent(), and resetEventState().
rules_
std::vector<Rule> ldmx::StorageControl::rules_ private
Collection of hints from the event processors
Definition at line 127 of file StorageControl.h.
Referenced by addRule(), and keepEvent().
The documentation for this class was generated from the following files:
Framework/include/Framework/StorageControl.h
Framework/src/StorageControl.cxx