LDMX Software: ldmx::PnWeightProcessor Class Reference
ldmx::PnWeightProcessor Class Reference
Public Member Functions
PnWeightProcessor (const std::string &name, Process &process)
~PnWeightProcessor ()
void configure (Parameters &parameters) final override
void produce (Event &event)
double calculateWeight (double w)
double calculateW (const SimParticle *particle, double delta=0.5)
Public Member Functions inherited from ldmx::Producer
Producer (const std::string &name, Process &process)
Public Member Functions inherited from ldmx::EventProcessor
EventProcessor (const std::string &name, Process &process)
virtual ~EventProcessor ()
virtual void onNewRun (const RunHeader &runHeader)
virtual void onFileOpen (EventFile &eventFile)
virtual void onFileClose (EventFile &eventFile)
virtual void onProcessStart ()
virtual void onProcessEnd ()
TDirectory * getHistoDirectory ()
void setStorageHint (ldmx::StorageControlHint hint)
void setStorageHint (ldmx::StorageControlHint hint, const std::string &purposeString)
void createHistograms (const std::vector< Parameters > &histos)
Static Public Attributes
static const int PROTON_PDGID = 2212
static const int NEUTRON_PDGID = 2112
Static Public Attributes inherited from ldmx::Producer
static const int CLASSTYPE {1}
Private Attributes
double wThreshold_ {1150 }
double thetaThreshold_ {100 }
std::unique_ptr< TF1 > lFit
std::unique_ptr< TF1 > hFit
Additional Inherited Members
Static Public Member Functions inherited from ldmx::EventProcessor
static void declare (const std::string &classname, int classtype, EventProcessorMaker *)
Protected Member Functions inherited from ldmx::EventProcessor
void abortEvent ()
Protected Attributes inherited from ldmx::EventProcessor
Process & process_
HistogramHelper histograms_
Interface class for making and filling histograms.
NtupleManager & ntuple_ {NtupleManager::getInstance()}
Manager for any ntuples.
Detailed Description
Definition at line 53 of file PnWeightProcessor.h.
Constructor & Destructor Documentation
PnWeightProcessor()
ldmx::PnWeightProcessor::PnWeightProcessor (const std::string & name, Process & process)
Constructor
Definition at line 30 of file PnWeightProcessor.cxx.
                                                                                 :
         Producer(name, process) {
             lFit = std::make_unique<TF1>( "lfit" , "exp([1]-[0]*x)" , 950 , 1150 );
             lFit->SetParameters(0.01093, 2.766);
             std::string func = "exp([1]-[0]*x)*([2]+[3]*x + [4]*pow(x,2)";
             func += " + [5]*pow(x,3) + [6]*pow(x,4) + [7]*pow(x,5) + [8]*pow(x,6))";
             hFit = std::make_unique<TF1>("hfit", func.c_str(), 1150, 3700);
             hFit->SetParameters(0.004008, 11.23, 1.242e-6, -1.964e-9,
                     8.243e-13, 9.333e-17, -7.584e-20, -1.991e-23, 9.757e-27);
     }
References hFit, and lFit.
~PnWeightProcessor()
ldmx::PnWeightProcessor::~PnWeightProcessor ()
Destructor
Definition at line 43 of file PnWeightProcessor.cxx.
{
     }
Member Function Documentation
calculateW()
double ldmx::PnWeightProcessor::calculateW (const SimParticle * particle, double delta = 0.5)
Calculate the measured W defined as W(measured) = 0.5*(p_tot + K)*(1.12-0.5*(p_z/p)) where p is the total momentum of the particle K is its kinetic energy p_z is the z component of the momentum all defined at the hardest PN vertex.
Parameters
particle SimParticle used to calculate W.
Returns
W
Definition at line 159 of file PnWeightProcessor.cxx.
{
         double px = particle->getMomentum()[0];
         double py = particle->getMomentum()[1];
         double pz = particle->getMomentum()[2];
         double p = sqrt(px*px + py*py + pz*pz);
         double ke = particle->getEnergy() - particle->getMass();
         return 0.5*(p + ke)*(sqrt(1 + (delta*delta)) - delta*(pz/p));
     }
References ldmx::SimParticle::getEnergy(), ldmx::SimParticle::getMass(), and ldmx::SimParticle::getMomentum().
Referenced by produce().
calculateWeight()
double ldmx::PnWeightProcessor::calculateWeight (double w)
Calculate the event weight.
Definition at line 155 of file PnWeightProcessor.cxx.
{
         return lFit->Eval(w)/hFit->Eval(w);
     }
References hFit, and lFit.
Referenced by produce().
configure()
void ldmx::PnWeightProcessor::configure (Parameters & parameters) final override virtual
Configure the processor using the given user specified parameters.
Parameters
parameters Set of parameters used to configure this processor.
Reimplemented from ldmx::EventProcessor.
Definition at line 46 of file PnWeightProcessor.cxx.
{
         wThreshold_ = parameters.getParameter< double >("w_threshold");
         thetaThreshold_ = parameters.getParameter< double >("theta_threshold");
     }
References ldmx::Parameters::getParameter(), thetaThreshold_, and wThreshold_.
produce()
void ldmx::PnWeightProcessor::produce (Event & event) virtual
Run the weight calculation and create a pnWeightResult.
Implements ldmx::Producer.
Definition at line 51 of file PnWeightProcessor.cxx.
{
         // Get the particle map from the event.  If the particle map is empty,
         // don't process the event.
         auto particleMap{event.getMap<int,SimParticle>("SimParticles")};
         if (particleMap.size() == 0) return;
         // Get the recoil electron
         auto [ trackID, recoil ] = Analysis::getRecoil(particleMap);
         // Use the recoil electron to retrieve the gamma that underwent a
         // photo-nuclear reaction.
         auto pnGamma{Analysis::getPNGamma(particleMap, recoil, 2500.)};
         // For PN biased events, there should always be a gamma that
         // underwent a PN reaction.
         if (pnGamma == nullptr) {
             EXCEPTION_RAISE( "PnWeightProc" , "Event doesn't contain a PN Gamma that is the daughter of the recoil electron." );
         }
         double hardestNucleonKe = -9999;
         double hardestNucleonTheta = -9999;
         double hardestNucleonW = -9999;
         double highestWNucleonKe = -9999;
         double highestWNucleonTheta = -9999;
         double highestWNucleonW = -9999;
         PnWeightResult result;
         for (const int &daughterTrackID : pnGamma->getDaughters() ) {
             // Get a daughter of the PN gamma
             const SimParticle *pnDaughter;
             if ( particleMap.count( daughterTrackID ) > 0 ) {
                 pnDaughter = &( particleMap.at( daughterTrackID ) );
             } else {
                 //pnDaughter not stored in particle map
                 EXCEPTION_RAISE(
                         "MissingPNDaughter",
                         "PN Daughter with track ID " + std::to_string(daughterTrackID) +
                         " has not been stored. Have you stored all of the daughters of PN interactions?"
                         );
             }
             // Calculate the kinetic energy
             double ke = (pnDaughter->getEnergy() - pnDaughter->getMass());
             // Calculate the momentum
             double px = pnDaughter->getMomentum()[0];
             double py = pnDaughter->getMomentum()[1];
             double pz = pnDaughter->getMomentum()[2];
             double p = sqrt(px*px + py*py + pz*pz);
             // Calculate the polar angle
             double theta = acos(pz/p)*180.0/3.14159;
             // Get the PDG ID of the daughter
             long int pdgID = std::abs(pnDaughter->getPdgID());
             double w = this->calculateW(pnDaughter);
             // Check if the daughter particle is a proton or neutron
             if ((pdgID == PROTON_PDGID) || (pdgID == NEUTRON_PDGID)) {
                 // Add the W of the current nucleon to the inclusive collection.
                 result.addW(w);
                 // Add the theta of the current nucleon to the inclusive collection.
                 result.addTheta(theta);
                 // Find the nucleon with the greatest kinetic energy
                 if (ke > hardestNucleonKe) {
                     hardestNucleonKe = ke;
                     hardestNucleonTheta = theta;
                     hardestNucleonW = w;
                 }
                 // Find the nucleon with the highest W
                 if (w > highestWNucleonW) {
                     highestWNucleonKe = ke;
                     highestWNucleonTheta = theta;
                     highestWNucleonW = w;
                 }
             }//pnDaughter is nucleon
         }//loop through pnDaughters
         // If the W of the highest W nucleon is above the threshold and the
         // polar angle is above the angle threshold, reweight the event.
         // Otherwise, set the event weight to 1.
         double eventWeight = 1;
         if ((highestWNucleonW > wThreshold_) && (highestWNucleonTheta > thetaThreshold_)) {
             eventWeight = calculateWeight(highestWNucleonW);
         }
         result.setHardestNucleonKe(hardestNucleonKe);
         result.setHardestNucleonTheta(hardestNucleonTheta);
         result.setHardestNucleonW(hardestNucleonW);
         result.setHighestWNucleonKe(highestWNucleonKe);
         result.setHighestWNucleonTheta(highestWNucleonTheta);
         result.setHighestWNucleonW(highestWNucleonW);
         result.setWeight(eventWeight);
         // Add the result to the collection
         event.add("PNweight", result);
     }
References ldmx::PnWeightResult::addTheta(), ldmx::PnWeightResult::addW(), calculateW(), calculateWeight(), EXCEPTION_RAISE, ldmx::SimParticle::getEnergy(), ldmx::SimParticle::getMass(), ldmx::SimParticle::getMomentum(), ldmx::SimParticle::getPdgID(), NEUTRON_PDGID, PROTON_PDGID, ldmx::PnWeightResult::setHardestNucleonKe(), ldmx::PnWeightResult::setHardestNucleonTheta(), ldmx::PnWeightResult::setHardestNucleonW(), ldmx::PnWeightResult::setHighestWNucleonKe(), ldmx::PnWeightResult::setHighestWNucleonTheta(), ldmx::PnWeightResult::setHighestWNucleonW(), ldmx::PnWeightResult::setWeight(), thetaThreshold_, and wThreshold_.
Member Data Documentation
hFit
std::unique_ptr<TF1> ldmx::PnWeightProcessor::hFit private
Fit to high tail of inclusive W (theta > 100) plot.
Definition at line 112 of file PnWeightProcessor.h.
Referenced by calculateWeight(), and PnWeightProcessor().
lFit
std::unique_ptr<TF1> ldmx::PnWeightProcessor::lFit private
Fit to lower slope of inclusive W (theta > 100) plot.
Definition at line 109 of file PnWeightProcessor.h.
Referenced by calculateWeight(), and PnWeightProcessor().
NEUTRON_PDGID
const int ldmx::PnWeightProcessor::NEUTRON_PDGID = 2112 static
Neutron PDG ID
Definition at line 65 of file PnWeightProcessor.h.
Referenced by produce().
PROTON_PDGID
const int ldmx::PnWeightProcessor::PROTON_PDGID = 2212 static
Proton PDG ID
Definition at line 62 of file PnWeightProcessor.h.
Referenced by produce().
thetaThreshold_
double ldmx::PnWeightProcessor::thetaThreshold_ {100 } private
Minimum angle for backwards-going hadron.
Definition at line 106 of file PnWeightProcessor.h.
Referenced by configure(), and produce().
wThreshold_
double ldmx::PnWeightProcessor::wThreshold_ {1150 } private
Threshold after which to apply W reweighting.
Definition at line 103 of file PnWeightProcessor.h.
Referenced by configure(), and produce().
The documentation for this class was generated from the following files:
EventProc/include/EventProc/PnWeightProcessor.h
EventProc/src/PnWeightProcessor.cxx