LDMX Software: simcore::generators::RootSimFromEcalSP Class Reference
simcore::generators::RootSimFromEcalSP Class Reference
#include <RootSimFromEcalSP.h>
Public Member Functions
RootSimFromEcalSP (const std::string &name, const framework::config::Parameters &parameters)
virtual ~RootSimFromEcalSP ()
void GeneratePrimaryVertex (G4Event *anEvent)
void RecordConfig (const std::string &id, ldmx::RunHeader &rh) final override
Public Member Functions inherited from simcore::PrimaryGenerator
PrimaryGenerator (const std::string &name, const framework::config::Parameters &parameters)
virtual ~PrimaryGenerator ()
Destructor.
virtual void GeneratePrimaryVertex (G4Event *)=0
virtual void RecordConfig (const std::string &id, ldmx::RunHeader &rh)=0
Private Attributes
double timeCutoff_
std::string ecalSPHitsCollName_
std::string ecalSPHitsPassName_
std::unique_ptr< framework::EventFile > ifile_
framework::Event ievent_
Additional Inherited Members
Public Types inherited from simcore::PrimaryGenerator
using Factory = ::simcore::Factory< PrimaryGenerator, std::shared_ptr< PrimaryGenerator >, const std::string &, const framework::config::Parameters & >
Factory for primary generators.
Protected Attributes inherited from simcore::PrimaryGenerator
std::string name_ {""}
Name of the PrimaryGenerator.
Detailed Description
Generate primaries that correspond to particles leaving the ECal (passing through the Ecal Scoring Planes) before a time cutoff.
Definition at line 45 of file RootSimFromEcalSP.h.
Constructor & Destructor Documentation
RootSimFromEcalSP()
simcore::generators::RootSimFromEcalSP::RootSimFromEcalSP (const std::string & name, const framework::config::Parameters & parameters)
Class constructor.
Parameters
name name of this generator
parameters configuration parameters
Parameters: filePath : path to root file containing events to re-sim timeCutoff : maximum time that a particle can pass through Ecal Scoring Planes and be included in re-sim (ns) ecalSPHitsCollName : name of collection for Ecal Scoring Plane hits ecalSPHitsPassName : name of pass for Ecal Scoring Plane hits
Definition at line 34 of file RootSimFromEcalSP.cxx.
    : PrimaryGenerator(name, parameters), ievent_("InputReSim") {
  framework::config::Parameters file_params;
  file_params.addParameter<std::string>("tree_name","LDMX_Events");
  std::string filename = parameters.getParameter<std::string>("filePath");
  ifile_ = std::make_unique<framework::EventFile>(file_params,filename);
  ifile_->setupEvent(&ievent_);
  timeCutoff_ = parameters.getParameter<double>("time_cutoff");
  ecalSPHitsCollName_ =
      parameters.getParameter<std::string>("collection_name");
  ecalSPHitsPassName_ = parameters.getParameter<std::string>("pass_name");
}
References framework::config::Parameters::addParameter(), ecalSPHitsCollName_, ecalSPHitsPassName_, framework::config::Parameters::getParameter(), ievent_, ifile_, and timeCutoff_.
~RootSimFromEcalSP()
simcore::generators::RootSimFromEcalSP::~RootSimFromEcalSP () virtual
Class destructor.
Definition at line 50 of file RootSimFromEcalSP.cxx.
{
  ifile_->close();
  ifile_.reset(nullptr);
}
References ifile_.
Member Function Documentation
GeneratePrimaryVertex()
void simcore::generators::RootSimFromEcalSP::GeneratePrimaryVertex (G4Event * anEvent) virtual
Generate vertices in the Geant4 event.
Parameters
anEvent The Geant4 event.
Implements simcore::PrimaryGenerator.
Definition at line 55 of file RootSimFromEcalSP.cxx.
{
  // go to next event
  //  if there isn't another event ==> EventFile::nextEvent returns false
  if (not ifile_->nextEvent()) {
    std::cout << "[ RootSimFromEcalSP ]: End of file reached." << std::endl;
    G4RunManager::GetRunManager()->AbortRun(true);
    anEvent->SetEventAborted();
  }
  // In this mode, we need to loop through all ECal scoring plane hits
  // and find the subset of unique hits created by particles exiting
  // the ECal.  These particles will be stored in a container and
  // re-fired into the HCal.
  std::unordered_map<int, const ldmx::SimTrackerHit*> spHits;
  auto ecalSPParticles{ievent_.getCollection<ldmx::SimTrackerHit>(
      ecalSPHitsCollName_, ecalSPHitsPassName_)};
  // Loop through all of the ECal scoring plane hits.
  for (const ldmx::SimTrackerHit& spHit : ecalSPParticles) {
    // First, start by skipping all hits that were created by
    // particles entering the ECal volume.
    if (spHit.getLayerID() == 1 and spHit.getMomentum()[2] > 0) continue;
    if (spHit.getLayerID() == 2 and spHit.getMomentum()[2] < 0) continue;
    if (spHit.getLayerID() == 3 and spHit.getMomentum()[1] < 0) continue;
    if (spHit.getLayerID() == 4 and spHit.getMomentum()[1] > 0) continue;
    if (spHit.getLayerID() == 5 and spHit.getMomentum()[0] > 0) continue;
    if (spHit.getLayerID() == 6 and spHit.getMomentum()[0] < 0) continue;
    // Don't consider particles created outside of the HCal readout
    // window.  Currently, this is estimated to be 50 ns.
    if (spHit.getTime() > timeCutoff_) continue;
    if (spHits.find(spHit.getTrackID()) == spHits.end()) {
      spHits[spHit.getTrackID()] = &spHit;
    } else {
      float currentPMag =
          sqrt(pow(spHit.getMomentum()[0], 2) + pow(spHit.getMomentum()[1], 2) +
               pow(spHit.getMomentum()[2], 2));
      float pMag = sqrt(pow(spHits[spHit.getTrackID()]->getMomentum()[0], 2) +
                        pow(spHits[spHit.getTrackID()]->getMomentum()[1], 2) +
                        pow(spHits[spHit.getTrackID()]->getMomentum()[2], 2));
      if (pMag < currentPMag) spHits[spHit.getTrackID()] = &spHit;
    }
  }
  for (auto const& spHit : spHits) {
    auto cVertex{new G4PrimaryVertex()};
    cVertex->SetPosition(spHit.second->getPosition()[0] * mm,
                         spHit.second->getPosition()[1] * mm,
                         spHit.second->getPosition()[2] * mm);
    cVertex->SetWeight(1.);
    auto primary{new G4PrimaryParticle()};
    primary->SetPDGcode(spHit.second->getPdgID());
    primary->SetMomentum(spHit.second->getMomentum()[0] * MeV,
                         spHit.second->getMomentum()[1] * MeV,
                         spHit.second->getMomentum()[2] * MeV);
    cVertex->SetPrimary(primary);
    anEvent->AddPrimaryVertex(cVertex);
  }
  // Create an input stream with a copy of the event seed as content.
  // The input stream is then passed to the random engine to restore
  // the state.
  std::istringstream iss(
      ievent_.getEventHeader().getStringParameter("eventSeed"));
  G4Random::restoreFullState(iss);
}
References ecalSPHitsCollName_, ecalSPHitsPassName_, framework::Event::getCollection(), framework::Event::getEventHeader(), ldmx::EventHeader::getStringParameter(), ievent_, ifile_, and timeCutoff_.
RecordConfig()
void simcore::generators::RootSimFromEcalSP::RecordConfig (const std::string & id, ldmx::RunHeader & rh) final override virtual
Record the configuration of the primary generator into the run header
Note
you must include the id number in each entry into the run header just in case there are other generators
Implements simcore::PrimaryGenerator.
Definition at line 126 of file RootSimFromEcalSP.cxx.
{
  rh.setStringParameter(id + " Class", "simcore::generators::RootSimFromEcalSP");
  rh.setStringParameter(id + " File Path", ifile_->getFileName());
  rh.setFloatParameter(id + " Time Cutoff [ns]", timeCutoff_);
}
References ifile_, ldmx::RunHeader::setFloatParameter(), ldmx::RunHeader::setStringParameter(), and timeCutoff_.
Member Data Documentation
ecalSPHitsCollName_
std::string simcore::generators::RootSimFromEcalSP::ecalSPHitsCollName_ private
The Ecal Scoring Planes Hits collection name
Definition at line 85 of file RootSimFromEcalSP.h.
Referenced by GeneratePrimaryVertex(), and RootSimFromEcalSP().
ecalSPHitsPassName_
std::string simcore::generators::RootSimFromEcalSP::ecalSPHitsPassName_ private
The Ecal Scoring Planes Hits pass name
Definition at line 90 of file RootSimFromEcalSP.h.
Referenced by GeneratePrimaryVertex(), and RootSimFromEcalSP().
ievent_
framework::Event simcore::generators::RootSimFromEcalSP::ievent_ private
The input ldmx event bus
Definition at line 100 of file RootSimFromEcalSP.h.
Referenced by GeneratePrimaryVertex(), and RootSimFromEcalSP().
ifile_
std::unique_ptr<framework::EventFile> simcore::generators::RootSimFromEcalSP::ifile_ private
The input root file
Definition at line 95 of file RootSimFromEcalSP.h.
Referenced by GeneratePrimaryVertex(), RecordConfig(), RootSimFromEcalSP(), and ~RootSimFromEcalSP().
timeCutoff_
double simcore::generators::RootSimFromEcalSP::timeCutoff_ private
The cutoff time
Any particle passing through the ECal scoring planes at a time greater than this time is NOT re-used as a primary.
Definition at line 80 of file RootSimFromEcalSP.h.
Referenced by GeneratePrimaryVertex(), RecordConfig(), and RootSimFromEcalSP().
The documentation for this class was generated from the following files:
SimCore/include/SimCore/Generators/RootSimFromEcalSP.h
SimCore/src/SimCore/Generators/RootSimFromEcalSP.cxx