LDMX Software: simcore::UserTrackInformation Class Reference
simcore::UserTrackInformation Class Reference
#include <UserTrackInformation.h>
Public Member Functions
UserTrackInformation ()=default
Constructor.
void initialize (const G4Track *track)
void Print () const final override
Print the information associated with the track.
bool getSaveFlag () const
void setSaveFlag (bool saveFlag)
bool isBremCandidate () const
void tagBremCandidate (bool isBremCandidate=true)
bool isPNGamma () const
void tagPNGamma (bool isPNGamma=true)
const G4ThreeVector & getInitialMomentum () const
std::string getVertexVolume () const
double getVertexTime () const
Static Public Member Functions
static UserTrackInformation * get (const G4Track *track)
Private Attributes
bool saveFlag_ {false}
bool isBremCandidate_ {false}
Flag indicating whether this track is a brem candidate.
bool isPNGamma_ {false}
std::string vertexVolume_ {""}
Volume the track was created in.
double vertex_time_ {0.}
Global Time of Creation.
G4ThreeVector initialMomentum_
The initial momentum of the track.
Detailed Description
Provides user defined information to associate with a Geant4 track.
This is helpful for keeping track of information we care about that Geant4 doesn't persist by default.
Definition at line 16 of file UserTrackInformation.h.
Member Function Documentation
get()
UserTrackInformation * simcore::UserTrackInformation::get (const G4Track * track) static
get
A static helper function for getting the track information from the passed G4Track. If the track doesn't have an information attached, a new one is created.
Note
The return value of this pointer is never NULL.
Parameters
[in] track G4Track to get information from
Definition at line 10 of file UserTrackInformation.cxx.
{
   if (!track->GetUserInformation()) {
     const_cast<G4Track*>(track)->SetUserInformation(new UserTrackInformation);
   }
   return dynamic_cast<UserTrackInformation*>(track->GetUserInformation());
 }
Referenced by simcore::UserTrackingAction::PostUserTrackingAction(), biasing::EcalDarkBremFilter::PostUserTrackingAction(), biasing::utility::DecayChildrenKeeper::PostUserTrackingAction(), biasing::utility::TrackProcessFilter::PostUserTrackingAction(), simcore::UserTrackingAction::PreUserTrackingAction(), simcore::TrackMap::save(), biasing::MidShowerNuclearBkgdFilter::save(), biasing::EcalProcessFilter::stepping(), biasing::PhotoNuclearProductsFilter::stepping(), biasing::TargetBremFilter::stepping(), and biasing::TargetProcessFilter::stepping().
getInitialMomentum()
const G4ThreeVector& simcore::UserTrackInformation::getInitialMomentum () const inline
Get the initial momentum 3-vector of the track [MeV].
Returns
The initial momentum of the track.
Definition at line 108 of file UserTrackInformation.h.
 { return initialMomentum_; }
References initialMomentum_.
Referenced by simcore::TrackMap::save().
getSaveFlag()
bool simcore::UserTrackInformation::getSaveFlag () const inline
Get the flag which indicates whether this track should be saved as a Trajectory.
Returns
The save flag.
Definition at line 58 of file UserTrackInformation.h.
 { return saveFlag_; }
References saveFlag_.
getVertexTime()
double simcore::UserTrackInformation::getVertexTime () const inline
Get the global time at which this track was created.
Definition at line 118 of file UserTrackInformation.h.
 { return vertex_time_; }
References vertex_time_.
getVertexVolume()
std::string simcore::UserTrackInformation::getVertexVolume () const inline
Get the name of the volume that this track was created in.
Definition at line 113 of file UserTrackInformation.h.
 { return vertexVolume_; }
References vertexVolume_.
initialize()
void simcore::UserTrackInformation::initialize (const G4Track * track)
Initialize the track information with the passed track.
We assume the passed track is newly created so we can copy its "current" kinematics and define those kinematics to be the "vertex" kinematics.
Even though we are "initializing" the track, we only change the kinematic values. The boolean flags may have been edited prior to the track reaching its own processing phase (where it is initialized), so those flags should (and are) not changed here.
Definition at line 17 of file UserTrackInformation.cxx.
{
   initialMomentum_ = track->GetMomentum();
   vertexVolume_ = track->GetLogicalVolumeAtVertex()->GetName();
   vertex_time_ = track->GetGlobalTime();
 }
References initialMomentum_, vertex_time_, and vertexVolume_.
Referenced by simcore::UserTrackingAction::PreUserTrackingAction().
isBremCandidate()
bool simcore::UserTrackInformation::isBremCandidate () const inline
Check whether this track is a brem candidate.
Returns
True if this track is a brem candidate, false otherwise.
Definition at line 73 of file UserTrackInformation.h.
 { return isBremCandidate_; }
References isBremCandidate_.
Referenced by tagBremCandidate().
isPNGamma()
bool simcore::UserTrackInformation::isPNGamma () const inline
Check whether this track is a photon that has undergone a photo-nuclear reaction.
Returns
True if this track is a photon that has undergone a photo-nuclear reaction, false otherwise.
Definition at line 92 of file UserTrackInformation.h.
 { return isPNGamma_; }
References isPNGamma_.
Referenced by tagPNGamma().
setSaveFlag()
void simcore::UserTrackInformation::setSaveFlag (bool saveFlag) inline
Set the save flag so the associated track will be persisted as a Trajectory.
Parameters
[in] saveFlag True to save the associated track.
Definition at line 66 of file UserTrackInformation.h.
 { saveFlag_ = saveFlag; }
References saveFlag_.
Referenced by biasing::EcalDarkBremFilter::PostUserTrackingAction(), biasing::utility::DecayChildrenKeeper::PostUserTrackingAction(), biasing::utility::TrackProcessFilter::PostUserTrackingAction(), and biasing::MidShowerNuclearBkgdFilter::save().
tagBremCandidate()
void simcore::UserTrackInformation::tagBremCandidate (bool isBremCandidate = true) inline
Tag this track as a brem candidate by the biasing filters.
Parameters
[in] isBremCandidate flag indicating whether this track is a candidate or not.
Definition at line 81 of file UserTrackInformation.h.
{
     isBremCandidate_ = isBremCandidate;
   }
References isBremCandidate(), and isBremCandidate_.
Referenced by biasing::EcalProcessFilter::stepping(), and biasing::TargetBremFilter::stepping().
tagPNGamma()
void simcore::UserTrackInformation::tagPNGamma (bool isPNGamma = true) inline
Tag this track as a photon that has undergone a photo-nuclear reaction.
Parameters
[in] isPNGamma flag indicating whether this track has undergone a photo-nuclear reaction or not.
Definition at line 101 of file UserTrackInformation.h.
 { isPNGamma_ = isPNGamma; }
References isPNGamma(), and isPNGamma_.
Referenced by biasing::PhotoNuclearProductsFilter::stepping().
Member Data Documentation
isPNGamma_
bool simcore::UserTrackInformation::isPNGamma_ {false} private
Flag indicating whether this track has undergone a photo-nuclear reaction.
Definition at line 137 of file UserTrackInformation.h.
Referenced by isPNGamma(), and tagPNGamma().
saveFlag_
bool simcore::UserTrackInformation::saveFlag_ {false} private
Flag for saving the track as a Trajectory.
Default value is false because we want to save space in the output file. We assume everywhere else that the save flag is false unless some other part changes it.
Definition at line 128 of file UserTrackInformation.h.
Referenced by getSaveFlag(), Print(), and setSaveFlag().
The documentation for this class was generated from the following files:
SimCore/include/SimCore/UserTrackInformation.h
SimCore/src/SimCore/UserTrackInformation.cxx