LDMX Software: framework::EventFile Class Reference
framework::EventFile Class Reference
#include <EventFile.h>
Public Member Functions
EventFile (const framework::config::Parameters &params, const std::string &filename, EventFile *parent, bool isOutputFile, bool isSingleOutput, bool isLoopable)
EventFile (const framework::config::Parameters &param, const std::string &fileName, bool isLoopable)
EventFile (const framework::config::Parameters &param, const std::string &fileName, EventFile *parent, bool isSingleOutput=false)
EventFile (const framework::config::Parameters &params, const std::string &fileName)
~EventFile ()=default
Defult destructor.
void addDrop (const std::string &rule)
void setupEvent (Event *evt)
void updateParent (EventFile *parent)
Event * getEvent ()
bool nextEvent (bool storeCurrentEvent=true)
int skipToEvent (int offset)
void close ()
void writeRunHeader (ldmx::RunHeader &runHeader)
ldmx::RunHeader & getRunHeader (int runNumber)
const std::string & getFileName ()
Private Member Functions
void importRunHeaders ()
Private Attributes
Long64_t entries_ {-1}
The number of entries in the tree.
Long64_t ientry_ {-1}
The current entry in the tree.
std::string fileName_
The file name.
bool isOutputFile_
True if file is an output file being written to disk.
bool isSingleOutput_
True if there is only one output file.
bool isLoopable_ {false}
True if this is an input file with pileup overlay events *‍/.
TFile * file_ {nullptr}
The backing TFile for this EventFile.
TTree * tree_ {nullptr}
The tree with event data.
EventFile * parent_ {nullptr}
A parent file containing event data.
Event * event_ {nullptr}
The object containing the actual event data (trees and branches).
std::vector< std::pair< std::string, bool > > preCloneRules_
std::vector< std::string > reactivateRules_
std::map< int, std::pair< bool, ldmx::RunHeader * > > runMap_
Detailed Description
This class manages all ROOT file input/output operations.
Definition at line 26 of file EventFile.h.
Constructor & Destructor Documentation
EventFile() [1/4]
framework::EventFile::EventFile (const framework::config::Parameters & params, const std::string & filename, EventFile * parent, bool isOutputFile, bool isSingleOutput, bool isLoopable)
Constructor to make a general file.
This is not used directly, but it is called in the more specialised constructors. This method is mainly focused on reducing code copying.
Parameters
[in] params The parameters used to configure this EventFile.
[in] filename the name of the file to read/write
[in] parent a pointer to the parent file to copy
[in] isOutputFile true if this file is written out
[in] isSingleOutput true if only one output file is being written to
[in] isLoopable true for an input file where events can be reused
Definition at line 13 of file EventFile.cxx.
    : fileName_(filename), parent_(parent), isOutputFile_(isOutputFile),
      isSingleOutput_(isSingleOutput), isLoopable_(isLoopable) {
  if (isOutputFile_) {
    // we are writting out so open the file and make sure it is writable
    file_ = new TFile(fileName_.c_str(), "RECREATE");
    if (!file_->IsOpen() or !file_->IsWritable()) {
      EXCEPTION_RAISE("FileError",
                      "Output file '" + fileName_ + "' is not writable.");
    }
    // set compression settings
    //  Check out the TFile constructor for explanation of how this integer is
    //  built Short Reference: setting = 100*algorithem + level algorithm = 0
    //  ==> use global default
    file_->SetCompressionSettings(
        params.getParameter<int>("compressionSetting", 9));
    if (parent_) {
      // output file when there are input files
      //  might be drop/keep rules, so we should have these rules to make sure
      //  it works
      // turn everything on
      //  hypothetically could turn everything off? Doesn't work for some
      //  reason?
      preCloneRules_.emplace_back("*", true);
      // except EventHeader (copies over to output)
      preCloneRules_.emplace_back("EventHeader*", true);
      // reactivate all branches so default behavior is drop
      reactivateRules_.push_back("*");
    }
  } else {
    // open file with only reading enabled
    file_ = new TFile(fileName_.c_str());
    // double check that file is open
    if (!file_->IsOpen()) {
      EXCEPTION_RAISE("FileError", "Input file '" + fileName_ +
                                       "' is not readable or does not exist.");
    }
    // Get the tree name from the configuration
    auto tree_name{params.getParameter<std::string>("tree_name")};
    tree_ = static_cast<TTree *>(file_->Get(tree_name.c_str()));
    if (!tree_) {
      EXCEPTION_RAISE("FileError", "File '" + fileName_ +
                                       "' does not have a TTree named '" +
                                       tree_name + "' in it.");
    }
    entries_ = tree_->GetEntriesFast();
  }
  importRunHeaders();
}
References entries_, file_, fileName_, framework::config::Parameters::getParameter(), importRunHeaders(), isOutputFile_, parent_, preCloneRules_, reactivateRules_, and tree_.
EventFile() [2/4]
framework::EventFile::EventFile (const framework::config::Parameters & param, const std::string & fileName, bool isLoopable)
Constructor to make a pileup overlay file.
This is an additional input file from which collections are pulled to be overlaid with simulated hit collections.
Parameters
[in] params The parameters used to configure this EventFile.
fileName The file name.
isLoopable true if we want to reset the event counter and keep processing from the start when we hit the end of the event tree in this input file (set in the call in the producer)
Definition at line 73 of file EventFile.cxx.
    : EventFile(params, filename, nullptr, false, false, isLoopable) {}
EventFile() [3/4]
framework::EventFile::EventFile (const framework::config::Parameters & param, const std::string & fileName, EventFile * parent, bool isSingleOutput = false)
Class constructor for cloning data from a "parent" file.
This is used for output files when there is an input file. (OR for files with a parent EventFile to clone)
Parameters
[in] params The parameters used to configure this EventFile.
[in] fileName The file name.
[in] parent Parent file for cloning data tree.
[in] isSingleOutput boolean check if only one output file is being written to
Definition at line 81 of file EventFile.cxx.
    : EventFile(params, filename, parent, true, isSingleOutput, false) {}
EventFile() [4/4]
framework::EventFile::EventFile (const framework::config::Parameters & params, const std::string & fileName)
Class constructor to make a file to read in an event root file.
This constructor just wraps the constructor above and sets the parent to null and the parameters isOutputFile/isSingleOutput to false.
This is used for all input files.
Parameters
[in] params The parameters used to configure this EventFile.
[in] fileName The file name.
Definition at line 77 of file EventFile.cxx.
    : EventFile(params, filename, nullptr, false, false, false) {}
Member Function Documentation
addDrop()
void framework::EventFile::addDrop (const std::string & rule)
Add a rule for dropping collections from the output.
This needs to be called after setupEvent. This method uses the event to help drop collections.
The rules should be of the following form: <drop,keep, or ignore> exp where exp is an expression that matches the collectionName. ignore ==> any branch with name matching exp is not even read in from the input file (if it exists) keep ==> any branch with name matching exp is read in from the input (if exists) and written to output (if exists) drop ==> any branch with name matching exp is read in from the input (if exists) and NOT written to output
The default behavior for all branches is keep.
ROOT uses the internal TRegexp to match branch names to the passed expression and set the status of the branch (whether it will be read or not). This internal object has different rules than real regular expressions, so it is best to keep it safe and only use asterisks or full names. Additionally, the rules you pass are analyzed in succession, so you can go from something more general to something more specific.
For example to drop all EcalSimHits.* drop EcalSimHits.*
or drop scoring plane collections drop .*ScoringPlane.*
or drop scoring plane collections but keep EcalScoringPlane collection drop .*ScoringPlane.* keep EcalScoringPlane.*
Note
The Event::getImpl overrides any ignore rules for the input file in order to avoid any seg faults. The items accessed will still be dropped.
Parameters
rule The rule for dropping collections.
Definition at line 86 of file EventFile.cxx.
{
  int offset;
  bool isKeep = false, isDrop = false, isIgnore = false;
  size_t i = rule.find("keep");
  if (i != std::string::npos) {
    offset = i + 4;
    isKeep = true;
  }
  i = rule.find("drop");
  if (i != std::string::npos) {
    offset = i + 4;
    isDrop = true;
  }
  i = rule.find("ignore");
  if (i != std::string::npos) {
    offset = i + 6;
    isIgnore = true;
  }
  // more than one of (keep,drop,ignore) was provided => not valid rule
  if (int(isKeep) + int(isDrop) + int(isIgnore) != 1)
    return;
  std::string srule = rule.substr(offset);
  for (i = srule.find_first_of(" \t\n\r"); i != std::string::npos;
       i = srule.find_first_of(" \t\n\r"))
    srule.erase(i, 1);
  // name of branch is not given
  if (srule.length() == 0)
    return;
  // add wild card at end for matching purposes
  if (srule.back() != '*')
    srule += ".*"; // add wildcard to back
  if (isKeep) {
    // turn both the input and output tree's on
    // root needs . removed otherwise it gets cranky
    srule.erase(std::remove(srule.begin(), srule.end(), '.'), srule.end());
    preCloneRules_.emplace_back(srule, true);
    // this branch will then be copied over into output tree and be active
  } else if (isIgnore) {
    // don't even read it from the input file
    // root needs . removed otherwise it gets cranky
    srule.erase(std::remove(srule.begin(), srule.end(), '.'), srule.end());
    preCloneRules_.emplace_back(srule, false);
    // these branches won't be copied over into output tree
  } else if (isDrop) {
    // drop means allowing it on reading but not writing
    // pass these regex to event bus so Event::add knows
    event_->addDrop(srule); // requires event_ to be set
    // root needs . removed otherwise it gets cranky
    srule.erase(std::remove(srule.begin(), srule.end(), '.'), srule.end());
    preCloneRules_.emplace_back(srule, false);
    // these branches won't be copied over into output tree
    // reactivate input branch after clone
    reactivateRules_.push_back(srule);
  }
}
References framework::Event::addDrop(), event_, preCloneRules_, and reactivateRules_.
Referenced by framework::Process::run().
close()
void framework::EventFile::close ()
Close the file, writing the tree to disk if creating an output file.
Deletes any RunHeaders that this instance of EventFile owns.
Exceptions
Exception if run tree already exists in output file.
Definition at line 295 of file EventFile.cxx.
                      {
  // MEMORY 'Conditional jump or move depends on uninitialised values' when
  // closing TFile and/or writing TTree
  //  TFile::Close --> TDirectoryFile::Close --> ~TTree
  // MEMORY 'Syscall param write(buf) points to uninitialised byte(s)'
  //  when writing TTree below
  //  From filling TTree in nextEvent
  // Before an output file, the Event tree needs to be written.
  if (isOutputFile_) {
    // make sure we are in output file before writing
    file_->cd();
    tree_->Write();
    // store the run map into the output tree
    // Check for the existence of the run tree in the file.
    // If it already exists, throw an exception.
    // TODO: Tree name shouldn't be hardcoded. Is this check really necessary?
    auto runTree{static_cast<TTree *>(file_->Get("LDMX_Run"))};
    if (runTree) {
      EXCEPTION_RAISE("RunTree",
                      "RunTree 'LDMX_Run' already exists in output file '" +
                          fileName_ + "'.");
    }
    runTree = new TTree("LDMX_Run", "LDMX run header");
    // create the branch on this tree
    ldmx::RunHeader *theHandle = nullptr;
    runTree->Branch("RunHeader", "ldmx::RunHeader", &theHandle, 32000, 3);
    // copy over the run headers into the tree
    for (auto &[num, header_pair] : runMap_) {
      theHandle = header_pair.second;
      runTree->Fill();
      if (header_pair.first)
        delete header_pair.second;
    }
    runTree->Write();
  }
  // Close the file
  file_->Close();
}
References file_, fileName_, isOutputFile_, runMap_, and tree_.
Referenced by framework::Process::run().
getEvent()
Event * framework::EventFile::getEvent () inline
Get the Event object containing the event data.
Returns
The Event object containing event data.
Definition at line 157 of file EventFile.h.
{ return event_; };
References event_.
getFileName()
const std::string & framework::EventFile::getFileName () inline
Returns
the name of the ROOT file being managed.
Definition at line 226 of file EventFile.h.
{ return fileName_; }
References fileName_.
Referenced by framework::Process::run().
getRunHeader()
ldmx::RunHeader & framework::EventFile::getRunHeader (int runNumber)
Get the RunHeader for a given run, if it exists in the input file.
Parameters
runNumber The run number.
Returns
The RunHeader from the input file.
Exceptions
Exception if there is no RunHeader in the map with the given run number.
Definition at line 354 of file EventFile.cxx.
{
  if (runMap_.find(runNumber) != runMap_.end()) {
    return *(runMap_.at(runNumber).second);
  } else {
    EXCEPTION_RAISE("DataError", "No run header exists for " +
                                     std::to_string(runNumber) +
                                     " in the run map.");
  }
}
References runMap_.
Referenced by framework::Process::run(), and simcore::persist::RootPersistencyManager::Store().
importRunHeaders()
void framework::EventFile::importRunHeaders () private
Fill the internal map of run numbers to RunHeader objects from the input file.
If this file is an output file and parent_ and parent_->file_ are valid pointers, then the run headers are imported from parent_->file_.
Otherwise, we try to import run headers from file_.
Does not check if any run headers are getting overwritten!
Any RunHeaders read in from this function are owned by this instance of EventFile and are deleted in close().
Note
This function does nothing if parent_->file_ and file_ are nullptrs.
Definition at line 364 of file EventFile.cxx.
{
  // choose which file to import from
  auto theImportFile{file_}; // if this is an input file
  if (isOutputFile_ and parent_ and parent_->file_)
    theImportFile = parent_->file_;  // output file with input parent
  else if (isOutputFile_)
    return; // output file, no input parent to read from
  if (theImportFile) {
    // the file exist
    TTreeReader oldRunTree("LDMX_Run", theImportFile);
    TTreeReaderValue<ldmx::RunHeader> oldRunHeader(oldRunTree, "RunHeader");
    // TODO check that setup went correctly
    while (oldRunTree.Next()) {
      // copy input run tree into run map
      runMap_[oldRunHeader->getRunNumber()] =
          std::make_pair(true, new ldmx::RunHeader(*oldRunHeader));
    }
  }
  return;
}
References file_, isOutputFile_, parent_, and runMap_.
Referenced by EventFile(), and updateParent().
nextEvent()
bool framework::EventFile::nextEvent (bool storeCurrentEvent = true)
Prepare the next event.
We do the necessary set-up if ientry_ < 0. This means if we are an output file with a parent file, we clone our parent tree to our tree so we have the same branches.
After the first entry (when ientry_ >= 0), we "close up" the last event, filling our tree if we storeCurrentEvent is true and telling the event bus to clear.
Going to the next event depends on the configuration of the event file. THere are three cases.
We have a parent file - Just follow the parent's lead by calling the parent's nextEvent.
We are an output file (and we don't have a parent file). Just increment the number of entries and the entry index.
We are an input file. Now we need to load the next entry of the our tree into the event bus objects. If we are configured to be "loopable", then we will reset ientry_ to -1 when we reach the last event. Otherwise, we will return false as a stopping condition.
Parameters
[in] storeCurrentEvent Should we save the current event to the output (if we are an output file)?
Returns
If event was prepared/read successfully.
Definition at line 148 of file EventFile.cxx.
{
  if (ientry_ < 0) {
    // first entry of this file
    if (parent_) {
      // we have a parent file
      if (!parent_->tree_) {
        // this should _never_ happen
        EXCEPTION_RAISE("EventFile", "No event tree in the file");
      }
      // Only clone parent tree if either
      //  1) There is no tree setup yet (first input file)
      //  2) This is not single output (new input file --> new output file)
      if (!tree_ or !isSingleOutput_) {
        // clones parent_->tree_ to our tree_ keeping drop/keep rules in mind
        // clone tree (only copies over branches that are active on input tree)
        file_->cd();  // go into output file
        for (auto const &rulePair : preCloneRules_)
          parent_->tree_->SetBranchStatus(rulePair.first.c_str(),
                                          rulePair.second);
        tree_ = parent_->tree_->CloneTree(0);
        // reactivate any drop branches (drop) on input tree
        for (auto const &rule : reactivateRules_)
          parent_->tree_->SetBranchStatus(rule.c_str(), 1);
      }
      event_->setInputTree(parent_->tree_);
      event_->setOutputTree(tree_);
    } //we have a parent file
  } else {
    //later than first entry of file
    if (isOutputFile_) {
      event_->beforeFill();
      if (storeCurrentEvent) // we should store before moving on
        tree_->Fill();  // fill the clones...
    } // we are an output file
    // the event bus may not be defined
    //  for this file if we are input file and
    //  there is an output file during this run
    if (event_) {
      event_->Clear();
      event_->onEndOfEvent();
    } // event bus defined
  } // first or not first entry in this file
  if (parent_) {
    // we have a parent, follow their lead
    if (!parent_->nextEvent()) {
      return false;
    }
    ientry_ = parent_->ientry_;
    entries_++;
  } else if (isOutputFile_) {
    // we don't have a parent and we
    //  are an output file
    // Just increment the number of entries
    //  and the index of the current entry
    ientry_++;
    entries_++;
  } else {
    // we don't have a parent and
    //  we aren't an output file
    // try to load another entry from our tree
    if (ientry_ + 1 >= entries_) {
        if (isLoopable_) {
          // reset the event counter: reuse events from start of pileup tree
          ientry_ = -1;
        } else
          return false;
    }
    ientry_++;
    tree_->GetEntry(ientry_);
  }
  // if we have an event_
  //  make sure it is iterated as well
  return event_ ? event_->nextEvent() : true;
}
References framework::Event::beforeFill(), framework::Event::Clear(), entries_, event_, file_, ientry_, isLoopable_, isOutputFile_, isSingleOutput_, framework::Event::nextEvent(), nextEvent(), framework::Event::onEndOfEvent(), parent_, preCloneRules_, reactivateRules_, framework::Event::setInputTree(), framework::Event::setOutputTree(), and tree_.
Referenced by nextEvent(), and framework::Process::run().
setupEvent()
void framework::EventFile::setupEvent (Event * evt)
Set an Event object containing the event data to work with this file.
Parameters
evt The Event object with event data.
Definition at line 230 of file EventFile.cxx.
{
  event_ = evt;
  if (isOutputFile_) {
    //we are an output file
    if (!tree_ && !parent_) {
      // we don't have a tree and we don't have a parent
      //  ==> *Production Mode* create a new tree
      tree_ = event_->createTree();
      ientry_ = 0;
      entries_ = 0;
    }
    if (parent_) {
      // we have a parent file so give
      //  the parent's tree to the event bus
      //  as the input tree
      event_->setInputTree(parent_->tree_);
    }
    // give our tree to the event as the output tree
    event_->setOutputTree(tree_);
  } else {
    // we are an input file
    //  so give our tree to the event as input tree
    event_->setInputTree(tree_);
  } //output or input file
}
References framework::Event::createTree(), entries_, event_, ientry_, isOutputFile_, parent_, framework::Event::setInputTree(), framework::Event::setOutputTree(), and tree_.
Referenced by framework::Process::run().
skipToEvent()
int framework::EventFile::skipToEvent (int offset)
Skip events using an offset. Used in pileup overlay.
Returns
New event number if read successfully, else -1.
Definition at line 258 of file EventFile.cxx.
{
  // make sure the event number exists
  ientry_ = offset % entries_ - 1;
  return ientry_;
}
References entries_, and ientry_.
updateParent()
void framework::EventFile::updateParent (EventFile * parent)
Change pointer to different parent file.
We assume that the parent file is an EventFile configured to be an input file. This allows us to assume that the tree_ member variable of parent is valid.
Parameters
parent pointer to new parent file
Definition at line 264 of file EventFile.cxx.
{
  parent_ = parent;
  // we can assume parent_->tree_ is valid
  //  because (for input files) the tree_ is imported
  //  from the file and then checked if its valid in the
  //  EventFile constructor
  // Enter output file
  file_->cd();
  // need to turn on/off the same branches as in the initial setup...
  for (auto const &rulePair : preCloneRules_)
    parent_->tree_->SetBranchStatus(rulePair.first.c_str(), rulePair.second);
  // Copy over addresses from the new parent
  parent_->tree_->CopyAddresses(tree_);
  // and reactivate any dropping rules
  for (auto const &rule : reactivateRules_)
    parent_->tree_->SetBranchStatus(rule.c_str(), 1);
  // Reset the entry index with the new parent index
  ientry_ = parent_->ientry_;
  // import run headers from new input file
  importRunHeaders();
  return;
}
References file_, ientry_, importRunHeaders(), parent_, preCloneRules_, reactivateRules_, and tree_.
Referenced by framework::Process::run().
writeRunHeader()
void framework::EventFile::writeRunHeader (ldmx::RunHeader & runHeader)
Write the run header into the run map
Any RunHeader passed here is not owned or cleaned up by this EventFile instance.
Parameters
runHeader The run header to write into the map
Exceptions
Exception if run number is already in run map
Definition at line 341 of file EventFile.cxx.
{
  int runNumber = runHeader.getRunNumber();
  if (runMap_.find(runNumber) != runMap_.end()) {
    EXCEPTION_RAISE("RunMap", "Run map already contains a run with number '" +
                                  std::to_string(runNumber) + "'.");
  }
  runMap_[runNumber] = std::make_pair(false, &runHeader);
  return;
}
References ldmx::RunHeader::getRunNumber(), and runMap_.
Referenced by framework::Process::run().
Member Data Documentation
entries_
Long64_t framework::EventFile::entries_ {-1} private
The number of entries in the tree.
Definition at line 249 of file EventFile.h.
Referenced by EventFile(), nextEvent(), setupEvent(), and skipToEvent().
event_
Event* framework::EventFile::event_ {nullptr} private
The object containing the actual event data (trees and branches).
Definition at line 276 of file EventFile.h.
Referenced by addDrop(), getEvent(), nextEvent(), and setupEvent().
file_
TFile* framework::EventFile::file_ {nullptr} private
The backing TFile for this EventFile.
Definition at line 267 of file EventFile.h.
Referenced by close(), EventFile(), importRunHeaders(), nextEvent(), and updateParent().
fileName_
std::string framework::EventFile::fileName_ private
The file name.
Definition at line 255 of file EventFile.h.
Referenced by close(), EventFile(), and getFileName().
ientry_
Long64_t framework::EventFile::ientry_ {-1} private
The current entry in the tree.
Definition at line 252 of file EventFile.h.
Referenced by nextEvent(), setupEvent(), skipToEvent(), and updateParent().
isLoopable_
bool framework::EventFile::isLoopable_ {false} private
True if this is an input file with pileup overlay events *‍/.
Definition at line 264 of file EventFile.h.
Referenced by nextEvent().
isOutputFile_
bool framework::EventFile::isOutputFile_ private
True if file is an output file being written to disk.
Definition at line 258 of file EventFile.h.
Referenced by close(), EventFile(), importRunHeaders(), nextEvent(), and setupEvent().
isSingleOutput_
bool framework::EventFile::isSingleOutput_ private
True if there is only one output file.
Definition at line 261 of file EventFile.h.
Referenced by nextEvent().
parent_
EventFile* framework::EventFile::parent_ {nullptr} private
A parent file containing event data.
Definition at line 273 of file EventFile.h.
Referenced by EventFile(), importRunHeaders(), nextEvent(), setupEvent(), and updateParent().
preCloneRules_
std::vector<std::pair<std::string, bool> > framework::EventFile::preCloneRules_ private
Pre-clone rules.
The series of rules to call before cloning/copying the parent tree.
Definition at line 284 of file EventFile.h.
Referenced by addDrop(), EventFile(), nextEvent(), and updateParent().
reactivateRules_
std::vector<std::string> framework::EventFile::reactivateRules_ private
Vector of drop rules that have been parsed and need to be used to reactivate these branches on the input tree
The branches were initial deactivated so they don't get cloned to output tree.
Definition at line 293 of file EventFile.h.
Referenced by addDrop(), EventFile(), nextEvent(), and updateParent().
runMap_
std::map<int, std::pair<bool, ldmx::RunHeader *> > framework::EventFile::runMap_ private
Map of run numbers to RunHeader objects
The value object is a pair that should remain internal.
True if EventFile owns the RunHeader (and needs to clean it up)
This happens when RunHeaders are imported from an input file
False if EventFile does not own the RunHeader
This happens when the RunHeader is created by Process::run during production
Definition at line 305 of file EventFile.h.
Referenced by close(), getRunHeader(), importRunHeaders(), and writeRunHeader().
tree_
TTree* framework::EventFile::tree_ {nullptr} private
The tree with event data.
Definition at line 270 of file EventFile.h.
Referenced by close(), EventFile(), nextEvent(), setupEvent(), and updateParent().
The documentation for this class was generated from the following files:
Framework/include/Framework/EventFile.h
Framework/src/Framework/EventFile.cxx