LDMX Software: simcore::biasoperators::ElectroNuclear Class Reference
simcore::biasoperators::ElectroNuclear Class Reference
#include <ElectroNuclear.h>
Public Member Functions
ElectroNuclear (std::string name, const framework::config::Parameters &p)
~ElectroNuclear ()
G4VBiasingOperation * ProposeOccurenceBiasingOperation (const G4Track *track, const G4BiasingProcessInterface *callingProcess) final override
virtual std::string getProcessToBias () const
Return the process to bias.
virtual std::string getParticleToBias () const
Return the particle to bias.
virtual std::string getVolumeToBias () const
Return the volume to bias in.
virtual void RecordConfig (ldmx::RunHeader &header) const
Public Member Functions inherited from simcore::XsecBiasingOperator
XsecBiasingOperator (std::string name, const framework::config::Parameters &parameters)
virtual ~XsecBiasingOperator ()
void StartRun ()
Private Attributes
std::string volume_
The volume to bias in.
double factor_
The biasing factor.
double threshold_
Minimum kinetic energy [MeV] to allow a track to be biased.
Additional Inherited Members
Static Public Member Functions inherited from simcore::XsecBiasingOperator
static void declare (const std::string &className, XsecBiasingOperatorBuilder *builder)
Protected Member Functions inherited from simcore::XsecBiasingOperator
G4VBiasingOperation * BiasedXsec (double biased_xsec)
bool processIsBiased (std::string process)
G4VBiasingOperation * ProposeFinalStateBiasingOperation (const G4Track *, const G4BiasingProcessInterface *)
G4VBiasingOperation * ProposeNonPhysicsBiasingOperation (const G4Track *, const G4BiasingProcessInterface *)
Protected Attributes inherited from simcore::XsecBiasingOperator
G4BOptnChangeCrossSection * xsecOperation_ {nullptr}
G4ProcessManager * processManager_ {nullptr}
Detailed Description
Bias the Electron-Nuclear process
Definition at line 12 of file ElectroNuclear.h.
Constructor & Destructor Documentation
ElectroNuclear()
simcore::biasoperators::ElectroNuclear::ElectroNuclear (std::string name, const framework::config::Parameters & p)
Constructor
Calls parent constructor and allows accesss to configuration parameters.
Definition at line 7 of file ElectroNuclear.cxx.
     : XsecBiasingOperator(name, p) {
   volume_ = p.getParameter<std::string>("volume");
   factor_ = p.getParameter<double>("factor");
   threshold_ = p.getParameter<double>("threshold");
 }
References factor_, framework::config::Parameters::getParameter(), threshold_, and volume_.
~ElectroNuclear()
simcore::biasoperators::ElectroNuclear::~ElectroNuclear () inline
Destructor
Definition at line 23 of file ElectroNuclear.h.
 {}
Member Function Documentation
ProposeOccurenceBiasingOperation()
G4VBiasingOperation * simcore::biasoperators::ElectroNuclear::ProposeOccurenceBiasingOperation (const G4Track * track, const G4BiasingProcessInterface * callingProcess) final override virtual
Returns
Method that returns the biasing operation that will be used to bias the occurence of photonuclear events.
Implements simcore::XsecBiasingOperator.
Definition at line 15 of file ElectroNuclear.cxx.
{
   /*std::cout << "[ ElectroNuclearXsecBiasingOperator ]: "
             << "Track ID: " << track->GetTrackID() << ", "
             << "Parent ID: " << track->GetParentID() << ", "
             << "Created within " << track->GetLogicalVolumeAtVertex()->GetName()
      << ", "
             << "Currently in volume " << track->GetVolume()->GetName()
             << std::endl;*/
   if (track->GetKineticEnergy() < threshold_) return 0;
   /*std::cout << "[ ElectroNuclearXsecBiasingOperator ]: "
             << "Calling process: "
             << callingProcess->GetWrappedProcess()->GetProcessName()
             << std::endl;*/
   std::string currentProcess =
       callingProcess->GetWrappedProcess()->GetProcessName();
   if (currentProcess.compare(this->getProcessToBias()) == 0) {
     G4double interactionLength =
         callingProcess->GetWrappedProcess()->GetCurrentInteractionLength();
     /*std::cout << "[ ElectroNuclearXsecBiasingOperator ]: "
               << "EN Interaction length: "
               << interactionLength << std::endl;*/
     double enXsecUnbiased = 1. / interactionLength;
     /*std::cout << "[ ElectroNuclearXsecBiasingOperator ]: Unbiased EN xsec: "
               << enXsecUnbiased << std::endl;*/
     double enXsecBiased = enXsecUnbiased * factor_;
     /*std::cout << "[ ElectroNuclearXsecBiasingOperator ]: Biased EN xsec: "
               << enXsecBiased << std::endl;*/
     return BiasedXsec(enXsecBiased);
   } else
     return 0;
 }
References simcore::XsecBiasingOperator::BiasedXsec(), factor_, and threshold_.
RecordConfig()
virtual void simcore::biasoperators::ElectroNuclear::RecordConfig (ldmx::RunHeader & header) const inline virtual
Record the configuration to the run header
Parameters
[in,out] header RunHeader to record to
Implements simcore::XsecBiasingOperator.
Definition at line 47 of file ElectroNuclear.h.
{
     header.setStringParameter("BiasOperator::ElectroNuclear::Volume", volume_);
     header.setFloatParameter("BiasOperator::ElectroNuclear::Factor", factor_);
     header.setFloatParameter("BiasOperator::ElectroNuclear::Threshold",
                              threshold_);
   }
References factor_, ldmx::RunHeader::setFloatParameter(), ldmx::RunHeader::setStringParameter(), threshold_, and volume_.
The documentation for this class was generated from the following files:
SimCore/include/SimCore/BiasOperators/ElectroNuclear.h
SimCore/src/SimCore/BiasOperators/ElectroNuclear.cxx