LDMX Software: ldmx::HcalID Class Reference
ldmx::HcalID Class Reference
Implements detector ids for HCal subdetector.
#include <HcalID.h>
Public Types
enum HcalSection {
BACK = 0 , TOP = 1 , BOTTOM = 2 , LEFT = 4 ,
RIGHT = 3
}
Public Types inherited from ldmx::HcalAbstractID
enum HcalBarType { Global = 0 , Digi = 1 , Trigger = 2 , Special = 7 }
Public Types inherited from ldmx::DetectorID
typedef uint32_t RawValue
Public Member Functions
HcalID ()
HcalID (RawValue rawid)
HcalID (const HcalAbstractID id)
HcalID (unsigned int section, unsigned int layer, unsigned int strip)
int getSection () const
int section () const
int layer () const
int getLayerID () const
int getStrip () const
int strip () const
Public Member Functions inherited from ldmx::HcalAbstractID
HcalAbstractID ()
HcalAbstractID (RawValue rawid)
HcalAbstractID (const DetectorID id)
HcalAbstractID (unsigned int bar_type, unsigned int payload)
int bar_type () const
int payload () const
Public Member Functions inherited from ldmx::DetectorID
DetectorID ()
Class constructor for a null DetectorID.
DetectorID (RawValue rawid)
Class constructor from a raw 32-bit integer.
DetectorID (SubdetectorIDType sdtype, RawValue raw_subpayload)
bool null () const
SubdetectorIDType subdet () const
RawValue raw () const
void setRawValue (RawValue rawValue)
bool operator< (const DetectorID &id) const
bool operator== (const DetectorID &id) const
bool operator!= (const DetectorID &id) const
Static Public Member Functions
static void createInterpreters ()
Static Public Attributes
static const RawValue SECTION_MASK {0x7}
static const RawValue SECTION_SHIFT {18}
static const RawValue LAYER_MASK {0xFF}
static const RawValue LAYER_SHIFT {10}
static const RawValue STRIP_MASK {0xFF}
static const RawValue STRIP_SHIFT {0}
Static Public Attributes inherited from ldmx::HcalAbstractID
static const RawValue BAR_TYPE_MASK {0x7}
static const RawValue BAR_TYPE_SHIFT {23}
static const RawValue HCAL_PAYLOAD_MASK {0x007FFFFF}
Static Public Attributes inherited from ldmx::DetectorID
static const RawValue SUBDETECTORID_MASK {0x3F}
static const RawValue SUBDETECTORID_SHIFT {26}
static const RawValue SUBDETECTOR_PAYLOAD_MASK {0x3FFFFFF}
Additional Inherited Members
Protected Attributes inherited from ldmx::DetectorID
RawValue id_
The raw, packed value of the ID.
Detailed Description
Implements detector ids for HCal subdetector.
Definition at line 19 of file HcalID.h.
Member Enumeration Documentation
HcalSection
enum ldmx::HcalID::HcalSection
Encodes the section of the HCal based on the 'section' field value.
Definition at line 24 of file HcalID.h.
{ BACK = 0, TOP = 1, BOTTOM = 2, LEFT = 4, RIGHT = 3 };
Constructor & Destructor Documentation
HcalID() [1/4]
ldmx::HcalID::HcalID () inline
Empty HCAL id (but not null!)
Definition at line 36 of file HcalID.h.
: HcalAbstractID() {}
HcalID() [2/4]
ldmx::HcalID::HcalID (RawValue rawid) inline
Create from raw number
Definition at line 41 of file HcalID.h.
                         : HcalAbstractID(rawid) {
    if (!null() && bar_type() != Global) {
      EXCEPTION_RAISE(
          "DetectorIDMismatch",
          "Attempted to create HcalID from mismatched Hcal bar_type " +
              std::to_string(bar_type()));
    }
  }
References ldmx::HcalAbstractID::bar_type(), and ldmx::DetectorID::null().
HcalID() [3/4]
ldmx::HcalID::HcalID (const HcalAbstractID id) inline
Create from a DetectorID, but check
Definition at line 53 of file HcalID.h.
                                  : HcalAbstractID(id) {
    if (!null() && bar_type() != Global) {
      EXCEPTION_RAISE(
          "DetectorIDMismatch",
          "Attempted to create HcalID from mismatched Hcal bar_type " +
              std::to_string(bar_type()));
    }
  }
References ldmx::HcalAbstractID::bar_type(), and ldmx::DetectorID::null().
HcalID() [4/4]
ldmx::HcalID::HcalID (unsigned int section, unsigned int layer, unsigned int strip) inline
Create from pieces
Definition at line 65 of file HcalID.h.
      : HcalAbstractID(Global, 0) {
    id_ |= (section & SECTION_MASK) << SECTION_SHIFT;
    id_ |= (layer & LAYER_MASK) << LAYER_SHIFT;
    id_ |= (strip & STRIP_MASK) << STRIP_SHIFT;
  }
References ldmx::DetectorID::id_, layer(), and strip().
Member Function Documentation
createInterpreters()
void ldmx::HcalID::createInterpreters () static
Definition at line 12 of file HcalID.cxx.
{
  IDField::IDFieldList fields;
  fields.push_back(new IDField("subdetector", 0, SUBDETECTORID_SHIFT, 31));
  fields.push_back(
      new IDField("section", 1, SECTION_SHIFT,
                  SECTION_SHIFT + IDField::countOnes(SECTION_MASK) - 1));
  fields.push_back(
      new IDField("layer", 2, LAYER_SHIFT,
                  LAYER_SHIFT + IDField::countOnes(LAYER_MASK) - 1));
  fields.push_back(
      new IDField("strip", 3, STRIP_SHIFT,
                  STRIP_SHIFT + IDField::countOnes(STRIP_MASK) - 1));
  DetectorIDInterpreter::registerInterpreter(
      SD_HCAL, HcalAbstractID::BAR_TYPE_MASK << HcalAbstractID::BAR_TYPE_SHIFT,
      HcalAbstractID::Global << HcalAbstractID::BAR_TYPE_SHIFT, fields);
}
getLayerID()
int ldmx::HcalID::getLayerID () const inline
Get the value of the layer field from the ID.
Returns
The value of the layer field.
Definition at line 94 of file HcalID.h.
{ return (id_ >> LAYER_SHIFT) & LAYER_MASK; }
References ldmx::DetectorID::id_.
Referenced by TEST_CASE().
getSection()
int ldmx::HcalID::getSection () const inline
Definition at line 76 of file HcalID.h.
{ return (id_ >> SECTION_SHIFT) & SECTION_MASK; }
getStrip()
int ldmx::HcalID::getStrip () const inline
Get the value of the 'strip' field from the ID.
Returns
The value of 'strip' field.
Definition at line 100 of file HcalID.h.
{ return (id_ >> STRIP_SHIFT) & STRIP_MASK; }
References ldmx::DetectorID::id_.
Referenced by TEST_CASE().
layer()
int ldmx::HcalID::layer () const inline
Get the value of the layer field from the ID.
Returns
The value of the layer field.
Definition at line 88 of file HcalID.h.
{ return (id_ >> LAYER_SHIFT) & LAYER_MASK; }
References ldmx::DetectorID::id_.
Referenced by hcal::test::HcalCheckPositionMap::analyze(), HcalID(), hcal::HcalDigiProducer::produce(), and TEST_CASE().
section()
int ldmx::HcalID::section () const inline
Definition at line 82 of file HcalID.h.
{ return (id_ >> SECTION_SHIFT) & SECTION_MASK; }
strip()
int ldmx::HcalID::strip () const inline
Get the value of the 'strip' field from the ID.
Returns
The value of 'strip' field.
Definition at line 106 of file HcalID.h.
{ return (id_ >> STRIP_SHIFT) & STRIP_MASK; }
References ldmx::DetectorID::id_.
Referenced by hcal::test::HcalCheckPositionMap::analyze(), HcalID(), hcal::HcalDigiProducer::produce(), and TEST_CASE().
Member Data Documentation
LAYER_MASK
const RawValue ldmx::HcalID::LAYER_MASK {0xFF} static
Definition at line 28 of file HcalID.h.
LAYER_SHIFT
const RawValue ldmx::HcalID::LAYER_SHIFT {10} static
Definition at line 29 of file HcalID.h.
SECTION_MASK
const RawValue ldmx::HcalID::SECTION_MASK {0x7} static
Definition at line 26 of file HcalID.h.
SECTION_SHIFT
const RawValue ldmx::HcalID::SECTION_SHIFT {18} static
Definition at line 27 of file HcalID.h.
STRIP_MASK
const RawValue ldmx::HcalID::STRIP_MASK {0xFF} static
Definition at line 30 of file HcalID.h.
STRIP_SHIFT
const RawValue ldmx::HcalID::STRIP_SHIFT {0} static
Definition at line 31 of file HcalID.h.
The documentation for this class was generated from the following files:
DetDescr/include/DetDescr/HcalID.h
DetDescr/src/DetDescr/HcalID.cxx