LDMX Software: framework::exception::Exception Class Reference
framework::exception::Exception Class Reference
Standard base exception class with some useful output information.
#include <Exception.h>
Public Member Functions
Exception () throw ()
Exception (const std::string &name, const std::string &message, const std::string &module, int line, const std::string &function)
virtual ~Exception () throw ()
const std::string & name () const throw ()
const std::string & message () const throw ()
const std::string & module () const throw ()
const std::string & function () const throw ()
int line () const throw ()
virtual const char * what () const throw ()
const std::string & stackTrace () const throw ()
Private Member Functions
void buildStackTrace () throw ()
Private Attributes
std::string name_
std::string message_
std::string module_
std::string function_
int line_ {0}
std::string stackTrace_
Detailed Description
Standard base exception class with some useful output information.
Note
It is strongly recommended to use the EXCEPTION_RAISE macro to throw exceptions.
Definition at line 20 of file Exception.h.
Constructor & Destructor Documentation
Exception() [1/2]
framework::exception::Exception::Exception () throw () inline
Empty constructor.
Don't build stack trace for empty exceptions.
Definition at line 27 of file Exception.h.
{}
Exception() [2/2]
framework::exception::Exception::Exception (const std::string & name, const std::string & message, const std::string & module, int line, const std::string & function) inline
Class constructor.
Parameters
name Name of the exception.
message Extended message describing the exception.
module Filename in the source code where the exception occurred.
line Line in the source code where the exception occurred.
function Function in which the exception occurred.
Definition at line 37 of file Exception.h.
      : name_{name},
        message_{message},
        module_{module},
        function_{function},
        line_{line} {
    buildStackTrace();
  }
~Exception()
virtual framework::exception::Exception::~Exception () throw () inline virtual
Class destructor.
Definition at line 50 of file Exception.h.
{}
Member Function Documentation
buildStackTrace()
void framework::exception::Exception::buildStackTrace () throw () private
Definition at line 155 of file Exception.cxx.
{ stackTrace_ = Backtrace(2); }
function()
const std::string & framework::exception::Exception::function () const throw () inline
Get the function name where the exception occurred.
Returns
The function name where the exception occurred.
Definition at line 74 of file Exception.h.
{ return function_; }
References function_.
Referenced by eventdisplay::Display::draw(), framework::test::runProcess(), and eventdisplay::Display::SetFile().
line()
int framework::exception::Exception::line () const throw () inline
Get the source line number where the exception occurred.
Returns
The source line number where the exception occurred.
Definition at line 80 of file Exception.h.
{ return line_; }
References line_.
Referenced by eventdisplay::Display::draw(), framework::test::runProcess(), and eventdisplay::Display::SetFile().
message()
const std::string & framework::exception::Exception::message () const throw () inline
Get the message of the exception.
Returns
The message of the exception.
Definition at line 62 of file Exception.h.
{ return message_; }
References message_.
Referenced by eventdisplay::Display::draw(), framework::test::runProcess(), and eventdisplay::Display::SetFile().
module()
const std::string & framework::exception::Exception::module () const throw () inline
Get the source filename where the exception occurred.
Returns
The source filename where the exception occurred.
Definition at line 68 of file Exception.h.
{ return module_; }
References module_.
Referenced by eventdisplay::Display::draw(), framework::test::runProcess(), and eventdisplay::Display::SetFile().
name()
const std::string & framework::exception::Exception::name () const throw () inline
Get the name of the exception.
Returns
The name of the exception.
Definition at line 56 of file Exception.h.
{ return name_; }
References name_.
Referenced by eventdisplay::Display::draw(), framework::test::runProcess(), and eventdisplay::Display::SetFile().
stackTrace()
const std::string & framework::exception::Exception::stackTrace () const throw () inline
Get the full stack trace
Definition at line 91 of file Exception.h.
{ return stackTrace_; }
References stackTrace_.
Referenced by eventdisplay::Display::SetFile().
what()
virtual const char * framework::exception::Exception::what () const throw () inline virtual
The error message.
Returns
The error message.
Definition at line 86 of file Exception.h.
{ return message_.c_str(); }
References message_.
Member Data Documentation
function_
std::string framework::exception::Exception::function_ private
Function name where the exception occurred.
Definition at line 106 of file Exception.h.
Referenced by function().
line_
int framework::exception::Exception::line_ {0} private
Source line number where the exception occurred.
Definition at line 109 of file Exception.h.
Referenced by line().
message_
std::string framework::exception::Exception::message_ private
Error message.
Definition at line 100 of file Exception.h.
Referenced by message(), and what().
module_
std::string framework::exception::Exception::module_ private
Source filename where the exception occurred.
Definition at line 103 of file Exception.h.
Referenced by module().
name_
std::string framework::exception::Exception::name_ private
Exception name.
Definition at line 97 of file Exception.h.
Referenced by name().
stackTrace_
std::string framework::exception::Exception::stackTrace_ private
The stack trace
Definition at line 112 of file Exception.h.
Referenced by stackTrace().
The documentation for this class was generated from the following files:
Framework/include/Framework/Exception/Exception.h
Framework/src/Framework/Exception/Exception.cxx