LDMX Software: simcore::geo::AuxInfoReader Class Reference
simcore::geo::AuxInfoReader Class Reference
Reads auxiliary information from GDML userinfo block.
#include <AuxInfoReader.h>
Public Member Functions
AuxInfoReader (G4GDMLParser *parser, framework::config::Parameters ps, ConditionsInterface &ci)
virtual ~AuxInfoReader ()
void readGlobalAuxInfo ()
void assignAuxInfoToVolumes ()
ldmx::DetectorHeader * getDetectorHeader ()
Private Member Functions
void createSensitiveDetector (G4String sdType, const G4GDMLAuxListType *auxInfoList)
void createMagneticField (G4String name, const G4GDMLAuxListType *auxInfoList)
void createRegion (G4String name, const G4GDMLAuxListType *auxInfoList)
void createVisAttributes (G4String name, const G4GDMLAuxListType *auxInfoList)
void createDetectorHeader (G4String detectorVersion, const G4GDMLAuxListType *auxInfoList)
Private Attributes
G4GDMLParser * parser_
G4GDMLEvaluator * eval_
ldmx::DetectorHeader * detectorHeader_ {nullptr}
framework::config::Parameters parameters_
Configuration parameters.
ConditionsInterface & conditionsIntf_
ConditionsInterface.
Detailed Description
Reads auxiliary information from GDML userinfo block.
Note
This class reads information to define a detector header block, sensitive detectors, visualization attributes, magnetic fields, detector IDs, and detector regions from the userinfo block of a GDML file. These objects are then assigned to the appropriate logical volumes which have auxiliary tags that reference these objects by name.
Definition at line 30 of file AuxInfoReader.h.
Constructor & Destructor Documentation
AuxInfoReader()
simcore::geo::AuxInfoReader::AuxInfoReader (G4GDMLParser * parser, framework::config::Parameters ps, ConditionsInterface & ci)
Class constructor.
Parameters
parser The GDML parser.
ps configuration parameters
Definition at line 34 of file AuxInfoReader.cxx.
    : parser_(theParser),
      eval_(new G4GDMLEvaluator),
      parameters_(ps),
      conditionsIntf_(ci) {}
~AuxInfoReader()
simcore::geo::AuxInfoReader::~AuxInfoReader () virtual
Class destructor.
Definition at line 42 of file AuxInfoReader.cxx.
{
  delete eval_;
  delete detectorHeader_;
}
References detectorHeader_, and eval_.
Member Function Documentation
assignAuxInfoToVolumes()
void simcore::geo::AuxInfoReader::assignAuxInfoToVolumes ()
Assign auxiliary info to volumes such as sensitive detectors.
Definition at line 152 of file AuxInfoReader.cxx.
{
  const G4LogicalVolumeStore* lvs = G4LogicalVolumeStore::GetInstance();
  std::vector<G4LogicalVolume*>::const_iterator lvciter;
  for (lvciter = lvs->begin(); lvciter != lvs->end(); lvciter++) {
    G4GDMLAuxListType auxInfo =
        parser_->GetVolumeAuxiliaryInformation(*lvciter);
    if (auxInfo.size() > 0) {
      for (std::vector<G4GDMLAuxStructType>::const_iterator iaux =
               auxInfo.begin();
           iaux != auxInfo.end(); iaux++) {
        G4String auxType = iaux->type;
        G4String auxVal = iaux->value;
        G4String auxUnit = iaux->unit;
        G4LogicalVolume* lv = (*lvciter);
        if (auxType == "SensDet") {
          G4String sdName = auxVal;
          G4VSensitiveDetector* sd =
              G4SDManager::GetSDMpointer()->FindSensitiveDetector(sdName);
          if (sd != NULL) {
            lv->SetSensitiveDetector(sd);
            // G4cout << "Assigned SD " << sd->GetName() << " to " <<
            // lv->GetName() << G4endl;
          } else {
            EXCEPTION_RAISE("MissingInfo",
                            "Unknown SensDet in volume's auxiliary info: " +
                                std::string(sdName.data()));
          }
        } else if (auxType == "MagneticField") {
          G4String magFieldName = auxVal;
          G4MagneticField* magField =
              MagneticFieldStore::getInstance()->getMagneticField(magFieldName);
          if (magField != NULL) {
            G4FieldManager* mgr = new G4FieldManager(magField);
            lv->SetFieldManager(mgr, true /* FIXME: hard-coded to force field manager to daughters */);
            // G4cout << "Assigned magnetic field " << magFieldName << " to
            // volume " << lv->GetName() << G4endl;
          } else {
            EXCEPTION_RAISE(
                "MissingInfo",
                "Unknown MagneticField ref in volume's auxiliary info: " +
                    std::string(magFieldName.data()));
          }
        } else if (auxType == "Region") {
          G4String regionName = auxVal;
          G4Region* region =
              G4RegionStore::GetInstance()->GetRegion(regionName);
          if (region != NULL) {
            region->AddRootLogicalVolume(lv);
            // G4cout << "Added volume " << lv->GetName() << " to region " <<
            // regionName << G4endl;
          } else {
            EXCEPTION_RAISE("MissingInfo", "Reference region '" +
                                               std::string(regionName.data()) +
                                               "' was not found!");
          }
        } else if (auxType == "VisAttributes") {
          G4String visName = auxVal;
          G4VisAttributes* visAttributes =
              VisAttributesStore::getInstance()->getVisAttributes(visName);
          if (visAttributes != NULL) {
            lv->SetVisAttributes(visAttributes);
            // G4cout << "Assigned VisAttributes " << visName << " to volume "
            // << lv->GetName() << G4endl;
          } else {
            EXCEPTION_RAISE("MissingInfo", "Referenced VisAttributes '" +
                                               std::string(visName.data()) +
                                               "' was not found!");
          }
        }
      }
    }
  }
}
References simcore::MagneticFieldStore::getInstance(), simcore::VisAttributesStore::getInstance(), simcore::MagneticFieldStore::getMagneticField(), simcore::VisAttributesStore::getVisAttributes(), and parser_.
createDetectorHeader()
void simcore::geo::AuxInfoReader::createDetectorHeader (G4String detectorVersion, const G4GDMLAuxListType * auxInfoList) private
Create the detector header from the global auxinfo.
Parameters
detectorVersion The aux value with the detector version.
auxInfoList The aux info with the detector header information.
Definition at line 428 of file AuxInfoReader.cxx.
{
  int detectorVersion = atoi(auxValue.c_str());
  std::string detectorName("");
  std::string author("");
  std::string description("");
  for (std::vector<G4GDMLAuxStructType>::const_iterator iaux =
           auxInfoList->begin();
       iaux != auxInfoList->end(); iaux++) {
    G4String auxType = iaux->type;
    G4String auxVal = iaux->value;
    G4String auxUnit = iaux->unit;
    if (auxType == "DetectorName") {
      detectorName = auxVal;
    } else if (auxType == "Author") {
      author = auxVal;
    } else if (auxType == "Description") {
      description = auxVal;
    }
  }
  detectorHeader_ = new ldmx::DetectorHeader(detectorName, detectorVersion,
                                             description, author);
  /*G4cout << G4endl;
  G4cout << "Read detector header from userinfo: " << G4endl;
  G4cout << "  DetectorName: " << detectorHeader_->getName() << G4endl;
  G4cout << "  DetectorVersion: " << detectorHeader_->getVersion() << G4endl;
  G4cout << "  Author: " << detectorHeader_->getAuthor() << G4endl;
  G4cout << "  Description: " << detectorHeader_->getDescription() << G4endl;
  G4cout << G4endl;*/
}
References detectorHeader_.
Referenced by readGlobalAuxInfo().
createMagneticField()
void simcore::geo::AuxInfoReader::createMagneticField (G4String name, const G4GDMLAuxListType * auxInfoList) private
Create a magnetic field from GDML data.
Parameters
name The name of the magnetic field.
auxInfoList The aux info defining the magnetic field.
Definition at line 228 of file AuxInfoReader.cxx.
{
  // Find type of the mag field.
  G4String magFieldType("");
  for (std::vector<G4GDMLAuxStructType>::const_iterator iaux =
           auxInfoList->begin();
       iaux != auxInfoList->end(); iaux++) {
    G4String auxType = iaux->type;
    G4String auxVal = iaux->value;
    if (auxType == "MagneticFieldType") {
      magFieldType = auxVal;
      break;
    }
  }
  if (magFieldType == "") {
    EXCEPTION_RAISE("MissingInfo",
                    "Missing MagFieldType for magnetic field definition.");
  }
  G4MagneticField* magField = NULL;
  // Create a uniform mag field using the built-in Geant4 type.
  if (magFieldType == "G4UniformMagField") {
      std::string::size_type sz;
    double bx, by, bz;
    bx = by = bz = 0.;
    for (std::vector<G4GDMLAuxStructType>::const_iterator iaux =
             auxInfoList->begin();
         iaux != auxInfoList->end(); iaux++) {
      G4String auxType = iaux->type;
      G4String auxVal = iaux->value;
      G4String auxUnit = iaux->unit;
      G4String expr = auxVal + "*" + auxUnit;
      if (auxType == "bx") {
        bx = eval_->Evaluate(expr);
      } else if (auxType == "by") {
        by = eval_->Evaluate(expr);
      } else if (auxType == "bz") {
        bz = eval_->Evaluate(expr);
      }
    }
    G4ThreeVector fieldComponents(bx, by, bz);
    magField = new G4UniformMagField(fieldComponents);
    // G4cout << "Created G4UniformMagField " << magFieldName << " with field
    // components " << fieldComponents << G4endl << G4endl;
    // Create a global 3D field map by reading from a data file.
  } else if (magFieldType == "MagneticFieldMap3D") {
      std::string fileName;
    double offsetX, offsetY, offsetZ;
    for (std::vector<G4GDMLAuxStructType>::const_iterator iaux =
             auxInfoList->begin();
         iaux != auxInfoList->end(); iaux++) {
      G4String auxType = iaux->type;
      G4String auxVal = iaux->value;
      G4String auxUnit = iaux->unit;
      G4String expr = auxVal + "*" + auxUnit;
      if (auxType == "File") {
        fileName = auxVal;
      } else if (auxType == "OffsetX") {
        offsetX = eval_->Evaluate(expr);
      } else if (auxType == "OffsetY") {
        offsetY = eval_->Evaluate(expr);
      } else if (auxType == "OffsetZ") {
        offsetZ = eval_->Evaluate(expr);
      }
    }
    if (fileName.size() == 0) {
      EXCEPTION_RAISE("MissingInfo",
                      "File info with field data was not provided.");
    }
    // Create new 3D field map.
    magField =
        new MagneticFieldMap3D(fileName.c_str(), offsetX, offsetY, offsetZ);
    // Assign field map as global field.
    G4FieldManager* fieldMgr =
        G4TransportationManager::GetTransportationManager()->GetFieldManager();
    if (fieldMgr->GetDetectorField() != nullptr) {
      EXCEPTION_RAISE("MisAssign", "Global mag field was already assigned.");
    }
    fieldMgr->SetDetectorField(magField);
    fieldMgr->CreateChordFinder(magField);
  } else {
    EXCEPTION_RAISE("UnknownType", "Unknown MagFieldType '" +
                                       std::string(magFieldType.data()) +
                                       "' in auxiliary info.");
  }
  MagneticFieldStore::getInstance()->addMagneticField(magFieldName, magField);
}
References simcore::MagneticFieldStore::addMagneticField(), eval_, and simcore::MagneticFieldStore::getInstance().
Referenced by readGlobalAuxInfo().
createRegion()
void simcore::geo::AuxInfoReader::createRegion (G4String name, const G4GDMLAuxListType * auxInfoList) private
Create a detector region from GDML data.
Parameters
name The name of the detector region.
auxInfoList The aux info defining the detector region.
Definition at line 330 of file AuxInfoReader.cxx.
{
  bool storeTrajectories = true;
  for (std::vector<G4GDMLAuxStructType>::const_iterator iaux =
           auxInfoList->begin();
       iaux != auxInfoList->end(); iaux++) {
    G4String auxType = iaux->type;
    G4String auxVal = iaux->value;
    G4String auxUnit = iaux->unit;
    if (auxType == "StoreTrajectories") {
      if (auxVal == "false") {
        storeTrajectories = false;
      } else if (auxVal == "true") {
        storeTrajectories = true;
      }
    }
  }
  G4VUserRegionInformation* regionInfo =
      new UserRegionInformation(storeTrajectories);
  G4Region* region = new G4Region(name);
  region->SetUserInformation(regionInfo);
  // G4cout << "Created new detector region " << region->GetName() << G4endl <<
  // G4endl;
}
Referenced by readGlobalAuxInfo().
createSensitiveDetector()
void simcore::geo::AuxInfoReader::createSensitiveDetector (G4String sdType, const G4GDMLAuxListType * auxInfoList) private
Create a sensitive detector from GDML data.
Parameters
sdType The type of the sensitive detector.
auxInfoList The aux info defining the sensitive detector.
Definition at line 71 of file AuxInfoReader.cxx.
{
  // G4cout << "Creating SensitiveDetector " << theSensDetName << G4endl;
  G4String sdType("");
  G4String hcName("");
  G4String idName("");
  int subdetID = -1;
  int layerDepth = -1;
  int verbose = 0;
  for (std::vector<G4GDMLAuxStructType>::const_iterator iaux =
           auxInfoList->begin();
       iaux != auxInfoList->end(); iaux++) {
    G4String auxType = iaux->type;
    G4String auxVal = iaux->value;
    G4String auxUnit = iaux->unit;
    // G4cout << "auxType: " << auxType << ", auxVal: " << auxVal << ", auxUnit:
    // " << auxUnit << G4endl;
    if (auxType == "SensDetType") {
      sdType = auxVal;
    } else if (auxType == "HitsCollection") {
      hcName = auxVal;
    } else if (auxType == "Verbose") {
      verbose = atoi(auxVal.c_str());
    } else if (auxType == "SubdetID") {
      subdetID = atoi(auxVal.c_str());
    } else if (auxType == "DetectorID") {
      idName = auxVal;
    } else if (auxType == "LayerDepth") {
      layerDepth = atoi(auxVal.c_str());
    }
  }
  if (sdType == "") {
    EXCEPTION_RAISE("MissingInfo", "The SensDet is missing the SensDetType.");
  }
  if (hcName == "") {
    EXCEPTION_RAISE("MissingInfo",
                    "The SensDet is missing the HitsCollection.");
  }
  if (subdetID <= 0) {
    EXCEPTION_RAISE("BadID", "The SubdetID '" + std::to_string(subdetID) +
                                 "' is missing or invalid.");
  }
  /*
   * Build the Sensitive Detector, and re-assign the detID if applicable
   */
  G4VSensitiveDetector* sd = 0;
  if (sdType == "TrackerSD") {
    sd = new TrackerSD(theSensDetName, hcName, subdetID);
  } else if (sdType == "EcalSD") {
    sd = new EcalSD(theSensDetName, hcName, subdetID, conditionsIntf_);
  } else if (sdType == "HcalSD") {
    sd = new HcalSD(theSensDetName, hcName, subdetID);
  } else if (sdType == "ScoringPlaneSD") {
    sd = new ScoringPlaneSD(theSensDetName, hcName, subdetID);
  } else if (sdType == "TrigScintSD") {
    sd = new TrigScintSD(theSensDetName, hcName, subdetID);
  } else {
    EXCEPTION_RAISE("DetType", "Unknown SensitiveDetector type: " + sdType);
  }
  /*
   * Fix  layer depth if the Sensitive Detector is not the Tracker
   */
  if (sdType != "TrackerSD" && layerDepth != -1) {
    ((CalorimeterSD*)sd)->setLayerDepth(layerDepth);
  }
  sd->SetVerboseLevel(verbose);
  // G4cout << "Created " << sdType << " " << theSensDetName << " with hits
  // collection " << hcName << " and verbose level " << verbose << G4endl <<
  // G4endl;
}
References conditionsIntf_.
Referenced by readGlobalAuxInfo().
createVisAttributes()
void simcore::geo::AuxInfoReader::createVisAttributes (G4String name, const G4GDMLAuxListType * auxInfoList) private
Create visualization attributes from GDML data.
Parameters
name The name of the visualization attributes.
auxInfoList The aux info defining the visualization attributes.
Definition at line 358 of file AuxInfoReader.cxx.
{
  G4double rgba[4] = {1., 1., 1., 1.};
  G4bool visible = true;
  G4bool dauInvisible = false;
  G4bool forceWireframe = false;
  G4bool forceSolid = false;
  G4double lineWidth = 1.0;
  G4VisAttributes::LineStyle lineStyle = G4VisAttributes::unbroken;
  for (std::vector<G4GDMLAuxStructType>::const_iterator iaux =
           auxInfoList->begin();
       iaux != auxInfoList->end(); iaux++) {
    G4String auxType = iaux->type;
    G4String auxVal = iaux->value;
    G4String auxUnit = iaux->unit;
    if (auxType == "R") {
      rgba[0] = atof(auxVal.c_str());
    } else if (auxType == "G") {
      rgba[1] = atof(auxVal.c_str());
    } else if (auxType == "B") {
      rgba[2] = atof(auxVal.c_str());
    } else if (auxType == "A") {
      rgba[3] = atof(auxVal.c_str());
    } else if (auxType == "Style") {
      if (auxVal == "wireframe") {
        forceWireframe = true;
      } else if (auxVal == "solid") {
        forceSolid = true;
      }
    } else if (auxType == "DaughtersInvisible") {
      if (auxVal == "true") {
        dauInvisible = true;
      } else if (auxVal == "false") {
        dauInvisible = false;
      }
    } else if (auxType == "Visible") {
      if (auxVal == "true") {
        visible = true;
      } else if (auxVal == "false") {
        visible = false;
      }
    } else if (auxType == "LineStyle") {
      if (auxVal == "unbroken") {
        lineStyle = G4VisAttributes::unbroken;
      } else if (auxVal == "dashed") {
        lineStyle = G4VisAttributes::dashed;
      } else if (auxVal == "dotted") {
        lineStyle = G4VisAttributes::dotted;
      }
    } else if (auxType == "LineWidth") {
      lineWidth = atof(auxVal.c_str());
    }
  }
  G4VisAttributes* visAttributes = new G4VisAttributes();
  visAttributes->SetColor(rgba[0], rgba[1], rgba[2], rgba[3]);
  visAttributes->SetVisibility(visible);
  visAttributes->SetDaughtersInvisible(dauInvisible);
  visAttributes->SetForceWireframe(forceWireframe);
  visAttributes->SetForceSolid(forceSolid);
  visAttributes->SetLineWidth(lineWidth);
  visAttributes->SetLineStyle(lineStyle);
  VisAttributesStore::getInstance()->addVisAttributes(name, visAttributes);
  // G4cout << "Created VisAttributes " << name << G4endl << (*visAttributes) <<
  // G4endl << G4endl;
}
References simcore::VisAttributesStore::addVisAttributes(), and simcore::VisAttributesStore::getInstance().
Referenced by readGlobalAuxInfo().
getDetectorHeader()
ldmx::DetectorHeader * simcore::geo::AuxInfoReader::getDetectorHeader () inline
Get the detector header that was created from the userinfo block.
Returns
The detector header.
Definition at line 59 of file AuxInfoReader.h.
{ return detectorHeader_; }
References detectorHeader_.
readGlobalAuxInfo()
void simcore::geo::AuxInfoReader::readGlobalAuxInfo ()
Read the global auxiliary information from the auxinfo block.
Definition at line 47 of file AuxInfoReader.cxx.
{
  const G4GDMLAuxListType* auxInfoList = parser_->GetAuxList();
  for (std::vector<G4GDMLAuxStructType>::const_iterator iaux =
           auxInfoList->begin();
       iaux != auxInfoList->end(); iaux++) {
    G4String auxType = iaux->type;
    G4String auxVal = iaux->value;
    G4String auxUnit = iaux->unit;
    if (auxType == "SensDet") {
      createSensitiveDetector(auxVal, iaux->auxList);
    } else if (auxType == "MagneticField") {
      createMagneticField(auxVal, iaux->auxList);
    } else if (auxType == "Region") {
      createRegion(auxVal, iaux->auxList);
    } else if (auxType == "VisAttributes") {
      createVisAttributes(auxVal, iaux->auxList);
    } else if (auxType == "DetectorVersion") {
      createDetectorHeader(auxVal, iaux->auxList);
    }
  }
  return;
}
References createDetectorHeader(), createMagneticField(), createRegion(), createSensitiveDetector(), createVisAttributes(), and parser_.
Member Data Documentation
conditionsIntf_
ConditionsInterface& simcore::geo::AuxInfoReader::conditionsIntf_ private
ConditionsInterface.
Definition at line 119 of file AuxInfoReader.h.
Referenced by createSensitiveDetector().
detectorHeader_
ldmx::DetectorHeader* simcore::geo::AuxInfoReader::detectorHeader_ {nullptr} private
Detector header with name and version.
Definition at line 113 of file AuxInfoReader.h.
Referenced by createDetectorHeader(), getDetectorHeader(), and ~AuxInfoReader().
eval_
G4GDMLEvaluator* simcore::geo::AuxInfoReader::eval_ private
The GDML expression evaluator.
Definition at line 108 of file AuxInfoReader.h.
Referenced by createMagneticField(), and ~AuxInfoReader().
parameters_
framework::config::Parameters simcore::geo::AuxInfoReader::parameters_ private
Configuration parameters.
Definition at line 116 of file AuxInfoReader.h.
parser_
G4GDMLParser* simcore::geo::AuxInfoReader::parser_ private
The GDML parser.
Definition at line 103 of file AuxInfoReader.h.
Referenced by assignAuxInfoToVolumes(), and readGlobalAuxInfo().
The documentation for this class was generated from the following files:
SimCore/include/SimCore/Geo/AuxInfoReader.h
SimCore/src/SimCore/Geo/AuxInfoReader.cxx