LDMX Software: g4db::ElementXsecInterpolation Class Reference
g4db::ElementXsecInterpolation Class Reference
#include <ElementXsecInterpolation.h>
Classes
class SampleSet
Public Member Functions
ElementXsecInterpolation ()=default
ElementXsecInterpolation (std::shared_ptr< PrototypeModel > model)
G4double get (G4double energy, G4double A, G4double Z)
void stream (std::ostream &o) const
Private Attributes
std::map< int, SampleSet > the_samples_
each element has its own set of sample points
std::shared_ptr< PrototypeModel > model_
shared pointer to the model for calculating cross sections
Friends
std::ostream & operator<< (std::ostream &o, const ElementXsecInterpolation c)
Detailed Description
Interpolation of cross sections by element
The interpolation method is a modified quadratic interpolation where the main modification is - since we have a way to calculate new sample points - we expand the set of sample points if a cross section is requested for a energy and/or element outside of our current sample range.
Definition at line 19 of file ElementXsecInterpolation.h.
Constructor & Destructor Documentation
ElementXsecInterpolation() [1/2]
g4db::ElementXsecInterpolation::ElementXsecInterpolation () default
Default constructor
Does nothing interesting, but no model for calculating cross section has been set. If interpolation is attempted with a default-constructed interpolator, an exception will be thrown.
ElementXsecInterpolation() [2/2]
g4db::ElementXsecInterpolation::ElementXsecInterpolation (std::shared_ptr< PrototypeModel > model) inline
Constructor with a model to calculate the cross section.
Definition at line 33 of file ElementXsecInterpolation.h.
      : model_{model} {}
Member Function Documentation
get()
G4double g4db::ElementXsecInterpolation::get (G4double energy, G4double A, G4double Z)
Get the value of the cross section for the input variables.
For the interpolation to be successful, we impose the kinematic limit immediately - i.e. if energy is less than twice the A' mass, the cross section is zero.
Exceptions
std::runtime_error if no model is available for calculating cross sections
Parameters
[in] energy Energy of incident lepton [MeV]
[in] A atomic mass of element [atomic mass units]
[in] Z atomic number of element [num protons]
Returns
cross section corresponding to the input parameters (including units Geant4 style)
Note
Implicit conversion to integer from the double form of Z. This may not function properly if users have a custom element that is an averaged Z, but since elements close in Z behave similarly, this may not matter either.
When there is no entry for an element yet, we initialize the samples by calculating the cross section in 10% energy steps from the kinematic minimum up to the requested energy.
When the requested energy is below the lowest sample point, we determine two more samples. One at the requested energy and one below it.
When the requested energy is above the highest sample point, we determine two more samples. One at the requested energy and one above it.
When the requested energy is within the range set by our samples, we do a quadratic interpolation using the three points that enclose the requested energy.
We do the interpolation with the first set of three points that encloses the requested energy, so this prefers the point set that has two samples below and one above.
Definition at line 6 of file ElementXsecInterpolation.cxx.
{
  static const double kinematic_min = 2*G4APrime::APrime()->GetPDGMass();
  if (energy <= kinematic_min) return 0;
  double x = energy - kinematic_min;
  int Z_key = Z;
  auto sample_set = the_samples_.find(Z_key);
  if (sample_set == the_samples_.end()) {
    if (model_.get() == nullptr) {
      throw std::runtime_error(
                      "ElementXsecInterpolation not given a model to calculate cross "
                      "sections with.");
    }
    std::vector<double> init_x{0.}, init_y{0.};
    double curr_x{0.1*kinematic_min};
    while (curr_x+kinematic_min < energy) {
      init_x.push_back(curr_x);
      init_y.push_back(model_->ComputeCrossSectionPerAtom(curr_x+kinematic_min, A, Z));
      curr_x *= 1.1;
    }
    init_x.push_back(energy-kinematic_min);
    double xsec = model_->ComputeCrossSectionPerAtom(energy, A, Z);
    init_y.push_back(xsec);
    the_samples_.emplace(std::piecewise_construct,
        std::forward_as_tuple(Z_key),
        std::forward_as_tuple(init_x, init_y));
    return xsec;
  } else if (x < sample_set->second.min()) {
    double xsec = model_->ComputeCrossSectionPerAtom(energy, A, Z);
    sample_set->second.prepend(x, xsec);
    sample_set->second.prepend(
        x/1.1,
        model_->ComputeCrossSectionPerAtom(x/1.1+kinematic_min, A, Z)
        );
    return xsec;
  } else if (x > sample_set->second.max()) {
    double xsec = model_->ComputeCrossSectionPerAtom(energy, A, Z);
    sample_set->second.append(x, xsec);
    sample_set->second.append(
        1.1*x,
        model_->ComputeCrossSectionPerAtom(1.1*x+kinematic_min, A, Z)
        );
    return xsec;
  } else {
    return sample_set->second.interpolate(x);
  }
}
References G4APrime::APrime(), model_, and the_samples_.
Referenced by G4DarkBremsstrahlung::GetMeanFreePath(), and main().
stream()
void g4db::ElementXsecInterpolation::stream (std::ostream & o) const
Stream the table of sample points into the output stream.
Parameters
[in,out] o ostream to write to
Definition at line 85 of file ElementXsecInterpolation.cxx.
{
  static const double kinematic_min = 2*G4APrime::APrime()->GetPDGMass();
  o << "Z [protons],Energy [MeV],Xsec [pb]\n"
    << std::setprecision(std::numeric_limits<double>::digits10 +
                         1);  // maximum precision
  for (const auto& sample : the_samples_) {
    sample.second.dump(o, sample.first, kinematic_min);
  }
  o << std::endl;
}
References G4APrime::APrime(), and the_samples_.
Friends And Related Function Documentation
operator<<
std::ostream & operator<< (std::ostream & o, const ElementXsecInterpolation c) friend
Overload the streaming operator for ease
Parameters
[in] o ostream to write to
[in] c interpolation to write out
Returns
modified ostream
Definition at line 66 of file ElementXsecInterpolation.h.
{
    c.stream(o);
    return o;
  }
Member Data Documentation
model_
std::shared_ptr<PrototypeModel> g4db::ElementXsecInterpolation::model_ private
shared pointer to the model for calculating cross sections
Definition at line 171 of file ElementXsecInterpolation.h.
Referenced by get().
the_samples_
std::map<int, SampleSet> g4db::ElementXsecInterpolation::the_samples_ private
each element has its own set of sample points
Definition at line 168 of file ElementXsecInterpolation.h.
Referenced by get(), and stream().
The documentation for this class was generated from the following files:
SimCore/G4DarkBreM/include/G4DarkBreM/ElementXsecInterpolation.h
SimCore/G4DarkBreM/src/G4DarkBreM/ElementXsecInterpolation.cxx