LDMX Software: packing::SingleSubsystemUnpacker Class Reference
packing::SingleSubsystemUnpacker Class Reference
#include <SingleSubsystemUnpacker.h>
Public Member Functions
SingleSubsystemUnpacker (const std::string &name, framework::Process &p)
normal constructor
virtual ~SingleSubsystemUnpacker ()
empty destructor
void configure (framework::config::Parameters &ps) final override
void produce (framework::Event &event) final override
Public Member Functions inherited from framework::Producer
Producer (const std::string &name, Process &process)
virtual void beforeNewRun (ldmx::RunHeader &header)
Public Member Functions inherited from framework::EventProcessor
EventProcessor (const std::string &name, Process &process)
virtual ~EventProcessor ()
virtual void onNewRun (const ldmx::RunHeader &runHeader)
virtual void onFileOpen (EventFile &eventFile)
virtual void onFileClose (EventFile &eventFile)
virtual void onProcessStart ()
virtual void onProcessEnd ()
template<class T >
const T & getCondition (const std::string &condition_name)
TDirectory * getHistoDirectory ()
void setStorageHint (framework::StorageControlHint hint)
void setStorageHint (framework::StorageControlHint hint, const std::string &purposeString)
int getLogFrequency () const
int getRunNumber () const
std::string getName () const
void createHistograms (const std::vector< framework::config::Parameters > &histos)
Private Member Functions
template<typename WordType >
void read (framework::Event &event)
Private Attributes
int num_words_per_event_
number of words per event to get from file
int num_bytes_per_word_
number of bytes in each word
std::string output_name_
destination object name
utility::Reader reader_
raw data file we are reading
Additional Inherited Members
Static Public Member Functions inherited from framework::EventProcessor
static void declare (const std::string &classname, int classtype, EventProcessorMaker *)
Static Public Attributes inherited from framework::Producer
static const int CLASSTYPE {1}
Protected Member Functions inherited from framework::EventProcessor
void abortEvent ()
Protected Attributes inherited from framework::EventProcessor
HistogramHelper histograms_
Interface class for making and filling histograms.
NtupleManager & ntuple_ {NtupleManager::getInstance()}
Manager for any ntuples.
logging::logger theLog_
The logger for this EventProcessor.
Detailed Description
This producer unpacks the data from the a single subsystem raw data file into a single buffer for a downstream processor to decode.
Definition at line 18 of file SingleSubsystemUnpacker.h.
Constructor & Destructor Documentation
SingleSubsystemUnpacker()
packing::SingleSubsystemUnpacker::SingleSubsystemUnpacker (const std::string & name, framework::Process & p) inline
normal constructor
Definition at line 21 of file SingleSubsystemUnpacker.h.
    : framework::Producer(name, p) {}
~SingleSubsystemUnpacker()
virtual packing::SingleSubsystemUnpacker::~SingleSubsystemUnpacker () inline virtual
empty destructor
Definition at line 24 of file SingleSubsystemUnpacker.h.
{}
Member Function Documentation
configure()
void packing::SingleSubsystemUnpacker::configure (framework::config::Parameters & ps) final override virtual
Configure the unpacker and open the raw data file for IO
Parameters
[in] ps Parameters for configuration
Reimplemented from framework::EventProcessor.
Definition at line 7 of file SingleSubsystemUnpacker.cxx.
{
  reader_.open(ps.getParameter<std::string>("raw_file"));
  num_words_per_event_ = ps.getParameter<int>("num_words_per_event");
  num_bytes_per_word_ = ps.getParameter<int>("num_bytes_per_word");
  output_name_ = ps.getParameter<std::string>("output_name");
}
References framework::config::Parameters::getParameter(), num_bytes_per_word_, num_words_per_event_, packing::utility::Reader::open(), output_name_, and reader_.
produce()
void packing::SingleSubsystemUnpacker::produce (framework::Event & event) final override virtual
Actually do the unpacking/decoding.
Parameters
[in,out] event Event bus with raw data where we will put the digis
Implements framework::Producer.
Definition at line 14 of file SingleSubsystemUnpacker.cxx.
{
  if (!reader_ or reader_.eof()) abortEvent();
  switch(num_bytes_per_word_) {
    case 1 :
      read<uint8_t>(event);
      break;
    case 2 :
      read<uint16_t>(event);
      break;
    case 4 :
      read<uint32_t>(event);
      break;
    case 8 :
      read<uint64_t>(event);
      break;
    default:
      EXCEPTION_RAISE("BadConfig",
          "Unable to handle "+std::to_string(num_bytes_per_word_)
          +" bytes per word.");
  }
}
References framework::EventProcessor::abortEvent(), packing::utility::Reader::eof(), num_bytes_per_word_, and reader_.
read()
template<typename WordType > void packing::SingleSubsystemUnpacker::read (framework::Event & event) inline private
Read the configured number of words of the input type from the file and put that buffer onto the event bus with the configured output_name_.
Definition at line 47 of file SingleSubsystemUnpacker.h.
{
    std::vector<WordType> buff;
    if(!reader_.read(buff, num_words_per_event_)) {
      EXCEPTION_RAISE("MalForm",
        "Raw file provided was unable to read "+std::to_string(num_words_per_event_)
        +" bytes in an event.");
    }
    event.add(output_name_, buff);
  }
References num_words_per_event_, output_name_, packing::utility::Reader::read(), and reader_.
Member Data Documentation
num_bytes_per_word_
int packing::SingleSubsystemUnpacker::num_bytes_per_word_ private
number of bytes in each word
Definition at line 61 of file SingleSubsystemUnpacker.h.
Referenced by configure(), and produce().
num_words_per_event_
int packing::SingleSubsystemUnpacker::num_words_per_event_ private
number of words per event to get from file
Definition at line 59 of file SingleSubsystemUnpacker.h.
Referenced by configure(), and read().
output_name_
std::string packing::SingleSubsystemUnpacker::output_name_ private
destination object name
Definition at line 63 of file SingleSubsystemUnpacker.h.
Referenced by configure(), and read().
reader_
utility::Reader packing::SingleSubsystemUnpacker::reader_ private
raw data file we are reading
Definition at line 67 of file SingleSubsystemUnpacker.h.
Referenced by configure(), produce(), and read().
The documentation for this class was generated from the following files:
Packing/include/Packing/SingleSubsystemUnpacker.h
Packing/src/Packing/SingleSubsystemUnpacker.cxx