LDMX Software: dqm::HCalDQM Class Reference
dqm::HCalDQM Class Reference
Public Member Functions
HCalDQM (const std::string &name, framework::Process &process)
~HCalDQM ()
void configure (framework::config::Parameters &parameters) final override
void analyze (const framework::Event &event)
Public Member Functions inherited from framework::Analyzer
Analyzer (const std::string &name, Process &process)
Public Member Functions inherited from framework::EventProcessor
EventProcessor (const std::string &name, Process &process)
virtual ~EventProcessor ()
virtual void onNewRun (const ldmx::RunHeader &runHeader)
virtual void onFileOpen (EventFile &eventFile)
virtual void onFileClose (EventFile &eventFile)
virtual void onProcessStart ()
virtual void onProcessEnd ()
template<class T >
const T & getCondition (const std::string &condition_name)
TDirectory * getHistoDirectory ()
void setStorageHint (framework::StorageControlHint hint)
void setStorageHint (framework::StorageControlHint hint, const std::string &purposeString)
int getLogFrequency () const
int getRunNumber () const
std::string getName () const
void createHistograms (const std::vector< framework::config::Parameters > &histos)
Private Attributes
float maxPEThreshold_ {5}
Additional Inherited Members
Static Public Member Functions inherited from framework::EventProcessor
static void declare (const std::string &classname, int classtype, EventProcessorMaker *)
Static Public Attributes inherited from framework::Analyzer
static const int CLASSTYPE {2}
Protected Member Functions inherited from framework::EventProcessor
void abortEvent ()
Protected Attributes inherited from framework::EventProcessor
HistogramHelper histograms_
Interface class for making and filling histograms.
NtupleManager & ntuple_ {NtupleManager::getInstance()}
Manager for any ntuples.
logging::logger theLog_
The logger for this EventProcessor.
Detailed Description
Definition at line 25 of file HCalDQM.h.
Constructor & Destructor Documentation
HCalDQM()
dqm::HCalDQM::HCalDQM (const std::string & name, framework::Process & process)
Constructor
Definition at line 9 of file HCalDQM.cxx.
     : framework::Analyzer(name, process) {}
~HCalDQM()
dqm::HCalDQM::~HCalDQM () inline
Destructor
Definition at line 31 of file HCalDQM.h.
 {}
Member Function Documentation
analyze()
void dqm::HCalDQM::analyze (const framework::Event & event) virtual
Process the event and make histograms ro summaries.
Parameters
event The event to analyze.
Implements framework::Analyzer.
Definition at line 14 of file HCalDQM.cxx.
{
   // Check if the collection of digitized HCal hits exist. If it doesn't
   // don't continue processing.
   if (!event.exists("hcalDigis")) return;
   // Get the collection of HCalDQM digitized hits if the exists
   const std::vector<ldmx::HcalHit> hcalHits =
       event.getCollection<ldmx::HcalHit>("hcalDigis");
   // Get the total hit count
   int hitCount = hcalHits.size();
   histograms_.fill("n_hits", hitCount);
   double totalPE{0};
   // Loop through all HCal hits in the event
   // Get non-noise generated hits into new vector for sorting
   std::vector<const ldmx::HcalHit*> filteredHits;
   for (const ldmx::HcalHit& hit : hcalHits) {
     histograms_.fill("pe", hit.getPE());
     histograms_.fill("hit_time", hit.getTime());
     totalPE += hit.getPE();
     if (hit.getTime() > -999.) {
       filteredHits.push_back(&hit);
     }
   }
   histograms_.fill("total_pe", totalPE);
   // Sort the array by hit time
   std::sort(filteredHits.begin(), filteredHits.end(),
             [](const auto& lhs, const auto& rhs) {
               return lhs->getTime() < rhs->getTime();
             });
   // get first time and PE of hit over threshold
   double minTime{-1};
   double minTimePE{-1};
   for (const auto& hit : filteredHits) {
     if (hit->getPE() < maxPEThreshold_) continue;
     minTime = hit->getTime();
     minTimePE = hit->getPE();
     break;
   }
   histograms_.fill("min_time_hit_above_thresh", minTime);
   histograms_.fill("min_time_hit_above_thresh:pe", minTimePE, minTime);
   float maxPE{-1};
   float maxPETime{-1};
   bool passesHcalVeto{false};
   // Check if the HcalVeto result exists
   if (event.exists("HcalVeto")) {
     // Get the collection of HCalDQM digitized hits if the exists
     const ldmx::HcalVetoResult hcalVeto =
         event.getObject<ldmx::HcalVetoResult>("HcalVeto");
     ldmx::HcalHit maxPEHit = hcalVeto.getMaxPEHit();
     // Get the max PE and it's time
     maxPE = maxPEHit.getPE();
     maxPETime = maxPEHit.getTime();
     histograms_.fill("max_pe", maxPE);
     histograms_.fill("hit_time_max_pe", maxPETime);
     histograms_.fill("max_pe:time", maxPE, maxPETime);
     histograms_.fill("veto", hcalVeto.passesVeto());
     if (hcalVeto.passesVeto()) {
       histograms_.fill("max_pe_hcal_veto", maxPE);
       histograms_.fill("hit_time_max_pe_hcal_veto", maxPETime);
       histograms_.fill("max_pe:time_hcal_veto", maxPE, maxPETime);
       histograms_.fill("total_pe_hcal_veto", totalPE);
       histograms_.fill("n_hits_hcal_veto", hitCount);
       passesHcalVeto = true;
     }
   }
 }
References framework::Event::exists(), framework::HistogramHelper::fill(), ldmx::HcalVetoResult::getMaxPEHit(), ldmx::HcalHit::getPE(), framework::EventProcessor::histograms_, maxPEThreshold_, and ldmx::HcalVetoResult::passesVeto().
configure()
void dqm::HCalDQM::configure (framework::config::Parameters & parameters) final override virtual
Configure the processor using the given user specified parameters.
Parameters
parameters Set of parameters used to configure this processor.
Reimplemented from framework::EventProcessor.
Definition at line 12 of file HCalDQM.cxx.
 {}
Member Data Documentation
maxPEThreshold_
float dqm::HCalDQM::maxPEThreshold_ {5} private
The maximum PE threshold used for the veto.
Definition at line 49 of file HCalDQM.h.
Referenced by analyze().
The documentation for this class was generated from the following files:
DQM/include/DQM/HCalDQM.h
DQM/src/DQM/HCalDQM.cxx