LDMX Software: framework::test::TestAnalyzer Class Reference
framework::test::TestAnalyzer Class Reference
Public Member Functions
TestAnalyzer (const std::string &name, Process &p)
void onProcessStart () final override
void analyze (const framework::Event &event) final override
Public Member Functions inherited from framework::Analyzer
Analyzer (const std::string &name, Process &process)
virtual void analyze (const Event &event)=0
Public Member Functions inherited from framework::EventProcessor
EventProcessor (const std::string &name, Process &process)
virtual ~EventProcessor ()
virtual void configure (framework::config::Parameters &parameters)
virtual void onNewRun (const ldmx::RunHeader &runHeader)
virtual void onFileOpen (EventFile &eventFile)
virtual void onFileClose (EventFile &eventFile)
virtual void onProcessStart ()
virtual void onProcessEnd ()
template<class T >
const T & getCondition (const std::string &condition_name)
TDirectory * getHistoDirectory ()
void setStorageHint (framework::StorageControlHint hint)
void setStorageHint (framework::StorageControlHint hint, const std::string &purposeString)
int getLogFrequency () const
int getRunNumber () const
std::string getName () const
void createHistograms (const std::vector< framework::config::Parameters > &histos)
Private Attributes
TH1F * test_hist_
test histogram filled with event indices
Additional Inherited Members
Static Public Member Functions inherited from framework::EventProcessor
static void declare (const std::string &classname, int classtype, EventProcessorMaker *)
Static Public Attributes inherited from framework::Analyzer
static const int CLASSTYPE {2}
Protected Member Functions inherited from framework::EventProcessor
void abortEvent ()
Protected Attributes inherited from framework::EventProcessor
HistogramHelper histograms_
Interface class for making and filling histograms.
NtupleManager & ntuple_ {NtupleManager::getInstance()}
Manager for any ntuples.
logging::logger theLog_
The logger for this EventProcessor.
Detailed Description
Bare analyzer that looks for objects matching what the TestProducer put in.
Checks
the correct number and contents following the pattern produced by TestProducer.
Event::getCollection and Event::getObject don't throw errors.
Definition at line 109 of file FunctionalCoreTest.cxx.
Constructor & Destructor Documentation
TestAnalyzer()
framework::test::TestAnalyzer::TestAnalyzer (const std::string & name, Process & p) inline
Definition at line 111 of file FunctionalCoreTest.cxx.
: Analyzer(name, p) {}
~TestAnalyzer()
framework::test::TestAnalyzer::~TestAnalyzer () inline
Definition at line 112 of file FunctionalCoreTest.cxx.
{}
Member Function Documentation
analyze()
void framework::test::TestAnalyzer::analyze (const framework::Event & event) inline final override virtual
Process the event and make histograms or summaries
Parameters
event The Event to analyze
Implements framework::Analyzer.
Definition at line 120 of file FunctionalCoreTest.cxx.
{
    int i_event = event.getEventNumber();
    REQUIRE(i_event > 0);
    const std::vector<ldmx::CalorimeterHit>& caloHits =
        event.getCollection<ldmx::CalorimeterHit>("TestCollection");
    CHECK(caloHits.size() == i_event);
    for (unsigned int i = 0; i < caloHits.size(); i++) {
      CHECK(caloHits.at(i).getID() == i_event * 10 + i);
      test_hist_->Fill(caloHits.at(i).getID());
    }
    const ldmx::HcalVetoResult& vetoRes =
        event.getObject<ldmx::HcalVetoResult>("TestObject");
    auto maxPEHit{vetoRes.getMaxPEHit()};
    CHECK(maxPEHit.getID() == i_event);
    CHECK(vetoRes.passesVeto() == (i_event % 2 == 0));
    const float& tenth_event = event.getObject<float>("EventTenth");
    CHECK(tenth_event == Approx(i_event * 0.1));
    const std::vector<int>& i_event_from_bus =
        event.getCollection<int>("EventIndex");
    CHECK(i_event_from_bus.size() == 2);
    CHECK(i_event_from_bus.at(0) == i_event);
    CHECK(i_event_from_bus.at(1) == i_event);
    return;
  }
References ldmx::HcalVetoResult::getMaxPEHit(), ldmx::HcalVetoResult::passesVeto(), and test_hist_.
onProcessStart()
void framework::test::TestAnalyzer::onProcessStart () inline final override virtual
Callback for the EventProcessor to take any necessary action when the processing of events starts, such as creating histograms.
Reimplemented from framework::EventProcessor.
Definition at line 114 of file FunctionalCoreTest.cxx.
{
    REQUIRE_NOTHROW(getHistoDirectory());
    test_hist_ = new TH1F("test_hist_", "Test Histogram", 101, -50, 50);
    test_hist_->SetCanExtend(TH1::kAllAxes);
  }
References framework::EventProcessor::getHistoDirectory(), and test_hist_.
Member Data Documentation
test_hist_
TH1F* framework::test::TestAnalyzer::test_hist_ private
test histogram filled with event indices
Definition at line 157 of file FunctionalCoreTest.cxx.
Referenced by analyze(), and onProcessStart().
The documentation for this class was generated from the following file:
Framework/test/FunctionalCoreTest.cxx