LDMX Software: g4db::G4DarkBreMModel Class Reference
g4db::G4DarkBreMModel Class Reference
#include <G4DarkBreMModel.h>
Public Types
enum class ScalingMethod { ForwardOnly = 1 , CMScaling = 2 , Undefined = 3 }
enum class XsecMethod { Full = 1 , Improved = 2 , HyperImproved = 3 , Auto = 4 }
Public Member Functions
G4DarkBreMModel (const std::string &library_path, bool muons, double threshold=0.0, double epsilon=1.0, ScalingMethod sm=ScalingMethod::ForwardOnly, XsecMethod xm=XsecMethod::Auto, double max_R_for_full=50.0, int aprime_lhe_id=622, bool load_library=true)
virtual ~G4DarkBreMModel ()=default
virtual void PrintInfo () const
virtual G4double ComputeCrossSectionPerAtom (G4double lepton_ke, G4double atomicA, G4double atomicZ)
G4ThreeVector scale (double incident_energy, double lepton_mass)
virtual void GenerateChange (G4ParticleChange &particleChange, const G4Track &track, const G4Step &step)
Public Member Functions inherited from g4db::PrototypeModel
PrototypeModel (bool muons)
virtual ~PrototypeModel ()=default
Destructor, nothing on purpose.
void SetVerboseLevel (int l)
int GetVerboseLevel () const
bool DarkBremOffMuons () const
virtual void PrintInfo () const =0
virtual G4double ComputeCrossSectionPerAtom (G4double leptonKE, G4double atomicA, G4double atomicZ)=0
virtual void GenerateChange (G4ParticleChange &particleChange, const G4Track &track, const G4Step &step)=0
Private Member Functions
void SetMadGraphDataLibrary (const std::string &path)
void MakePlaceholders ()
OutgoingKinematics sample (double incident_energy)
Private Attributes
unsigned int maxIterations_ {10000}
double threshold_
double epsilon_
int aprime_lhe_id_
ScalingMethod scaling_method_
XsecMethod xsec_method_
std::string method_name_
std::string library_path_
bool alwaysCreateNewLepton_ {true}
std::map< double, std::vector< OutgoingKinematics > > madGraphData_
std::map< double, unsigned int > currentDataPoints_
Additional Inherited Members
Protected Attributes inherited from g4db::PrototypeModel
bool muons_
whether muons (true) or electrons (false) are dark bremming
int verbose_level_ {0}
verbose level for this model
Detailed Description
Geant4 implementation of the model for a particle undergoing a dark brem where we use an imported event library to decide the outgoing kinematics.
This is where all the heavy lifting in terms of calculating cross sections and actually having a lepton do a dark brem occurs. This model depends on several configurable parameters which should be studied for your specific use case in order to better tune this model to your lepton/incident energy/ target material situation.
Definition at line 25 of file G4DarkBreMModel.h.
Member Enumeration Documentation
ScalingMethod
enum class g4db::G4DarkBreMModel::ScalingMethod strong
Possible methods to use the dark brem events from the imported library inside of this model.
Enumerator
ForwardOnly
Use actual lepton energy and get pT from LHE (such that)
Scales the energy so that the fraction of kinetic energy is constant, keeping the constant.
If the is larger than the new energy, that event is skipped, and a new one is taken from the file. If the loaded library does not fully represent the range of incident energies being seen by the simulation, this will occur frequently.
With only the kinetic energy fraction and , the sign of the longitudinal momentum is undetermined. This method simply chooses the of the recoil lepton to always be positive.
CMScaling
Boost LHE vertex momenta to the actual lepton energy
The scaling is done via two boosts.
Boost out of the center-of-momentum (CoM) frame read in along with the MadGraph event library.
Boost into approximately) the incident lepton energy frame by constructing a "new" CoM frame using the actual CoM frame's transverse momentum and lowering the and energy of the CoM by the difference between the input incident energy and the sampled incident energy.
After these boosts, the energy of the recoil and its are extracted.
Undefined
Use LHE vertex as is
We simply copy the read-in recoil energy's energy, momentum, and .
Definition at line 33 of file G4DarkBreMModel.h.
{
    ForwardOnly = 1,
    CMScaling = 2,
    Undefined = 3
  };
XsecMethod
enum class g4db::G4DarkBreMModel::XsecMethod strong
Possible methods for calculating the xsec using the WW approximation technique.
See also
flux_factor_chi_numerical for how the flux factor is calculated Here, we refer to the flux factor as .
integrate for how the numerical integrations are performed
As the methods are related, they share many variable definitions.
is the upper limit on the x integration
is the incoming lepton's energy in GeV
is the lepton's mass in GeV
is the dark photon's mass in GeV
is the fine-structure constant
is the dark photon mixsing strength with the standard photon
is the conversion from GeV to pico-barns
The integrand limits for are calculated as
Enumerator
Full
use the full WW approximation
This is the 2D integration of a differential cross section including evaluating the flux factor chi numerically at each sampled x and theta. This effectively means we perform a 3D numerical integration when using this method.
It is slow but very faithful to the sampled MadGraph total cross section for high (> 200 GeV) incident energies.
Improved
assume in the integrand
This reduces one of the dimensions of the numerical integration, allowing the theta integration to be done analytically and so we only have a numerical integration over x and t
HyperImproved
only calculate the flux factor once
This simplifies the numerical integration even further by calculating the flux factor chi only at and then using that value everywhere in the integration of the differential cross section over x.
where is the same as Improved. Since this uses the maximum value of for all values of , we modify the upper limit of integration to avoid making this overestimate too much of an overestimate. Instead of we use .
Auto
the default cross section calculation
This requires its own enum variant since it is determined by the ratio as configured by other parameters.
If , Full is used while Improved is used otherwise. These boarders were determine qualitatively by looking at a series of cross section plots comparing all of these methods.
The parameter is configurable in G4DarkBreMModel::G4DarkBreMModel as max_R_for_full.
Definition at line 105 of file G4DarkBreMModel.h.
{
    Full = 1,
    Improved = 2,
    HyperImproved = 3,
    Auto = 4
  };
Constructor & Destructor Documentation
G4DarkBreMModel()
g4db::G4DarkBreMModel::G4DarkBreMModel (const std::string & library_path, bool muons, double threshold = 0.0, double epsilon = 1.0, ScalingMethod sm = ScalingMethod::ForwardOnly, XsecMethod xm = XsecMethod::Auto, double max_R_for_full = 50.0, int aprime_lhe_id = 622, bool load_library = true)
Set the parameters for this model.
Parameters
[in] library_path full path to MG library The library path is immediately passed to G4DarkBreMModel::SetMadGraphDataLibrary which simply calls g4db::parseLibrary (where you should look for the specification options of a dark brem library).
[in] muons true if using muons, false for electrons
[in] threshold minimum energy lepton needs to have to dark brem [GeV] (overwritten by twice the A' mass if it is less so that it kinematically makes sense).
[in] epsilon dark photon mixing strength
[in] sm G4DarkBreMModel::ScalingMethod on how to scale the events in the library
[in] xm G4DarkBreMModel::XsecMethod on calculating the total cross section
[in] max_R_for_full maximum value of R where Full will still be used Only used with G4DarkBreMModel::XsecMethod::Auto (go there for context)
[in] aprime_lhe_id PDG ID number for the dark photon in the LHE files being loaded for the library. Only used if parsing LHE files.
[in] load_library only used in cross section executable where it is known that the library will not be used during program run
Definition at line 141 of file G4DarkBreMModel.cxx.
    : PrototypeModel(muons), maxIterations_{10000},
      threshold_{std::max(threshold, 2.*G4APrime::APrime()->GetPDGMass()/CLHEP::GeV)},
      epsilon_{epsilon}, aprime_lhe_id_{aprime_lhe_id},
      scaling_method_{scaling_method}, xsec_method_{xsec_method},
      library_path_{library_path} {
  if (xsec_method_ == XsecMethod::Auto) {
    static const double MA = G4APrime::APrime()->GetPDGMass() / GeV;
    const double lepton_mass{(muons_
       ? G4MuonMinus::MuonMinus()->GetPDGMass()
       : G4Electron::Electron()->GetPDGMass()
      ) / GeV};
    double mass_ratio = MA/lepton_mass;
    if (mass_ratio < max_R_for_full) {
      xsec_method_ = XsecMethod::Full;
    } else {
      xsec_method_ = XsecMethod::Improved;
    }
  }
  if (load_library) SetMadGraphDataLibrary(library_path_);
}
References G4APrime::APrime(), Auto, Full, Improved, library_path_, g4db::PrototypeModel::muons_, SetMadGraphDataLibrary(), and xsec_method_.
~G4DarkBreMModel()
virtual g4db::G4DarkBreMModel::~G4DarkBreMModel () virtual default
Destructor
Member Function Documentation
ComputeCrossSectionPerAtom()
G4double g4db::G4DarkBreMModel::ComputeCrossSectionPerAtom (G4double lepton_ke, G4double atomicA, G4double atomicZ) virtual
Calculates the cross section per atom in GEANT4 internal units.
The estimate for the total cross section given the material and the lepton's energy is done using an implementation of the WW approximation using Boost's Math Quadrature library to numerically calculate the integrals.
See also
XsecMethod for the different methods of calculating the cross section.
Parameters
lepton_ke kinetic energy of incoming particle
atomicZ atomic number of atom
atomicA atomic mass of atom
Returns
cross section (0. if outside energy cuts)
Implements g4db::PrototypeModel.
Definition at line 197 of file G4DarkBreMModel.cxx.
{
  static const double MA = G4APrime::APrime()->GetPDGMass() / GeV;
  static const double MA2 = MA*MA;
  static const double alphaEW = 1.0 / 137.0;
  const double lepton_mass{
    (muons_ ? G4MuonMinus::MuonMinus()->GetPDGMass() : G4Electron::Electron()->GetPDGMass()) / GeV};
  const double lepton_mass_sq{lepton_mass*lepton_mass};
  // the cross section is zero if the lepton does not have enough
  // energy to create an A'
  // the threshold_ can also be set by the user to a higher value
  // to prevent dark-brem within inaccessible regions of phase
  // space
  if (lepton_ke < keV or lepton_ke < threshold_*GeV) return 0.;
  // Change energy to GeV.
  double lepton_e = lepton_ke/GeV + lepton_mass;
  double lepton_e_sq = lepton_e*lepton_e;
  // deduce integral bounds
  double xmin = 0;
  double xmax = 1 - std::max(lepton_mass,MA) / lepton_e;
  double integrated_xsec{-1};
  if (xsec_method_ == XsecMethod::Full) {
    /*
     * max recoil angle of A'
     *
     * The wide angle A' are produced at a negligible rate
     * so we enforce a hard-coded cut-off to stay within
     * the small-angle regime.
     *
     * We choose the same cutoff as DMG4.
     */
    double theta_max{0.3};
    /*
     * Differential cross section with respect to x and theta
     *
     * Equation (16) from Appendix A of https://arxiv.org/pdf/2101.12192.pdf
     *
     * This `auto` represents a lambda-expression function, inheriting many
     * pre-calculated constants (like lepton_e and chi) while also calculating
     * the variables dependent on the integration variables. The return value
     * of this function is a double since it is calculated by arithmetic
     * operations on doubles.
     */
    auto diff_cross = [&](double x, double theta) {
      if (x*lepton_e < threshold_) return 0.;
      double theta_sq = theta*theta;
      double x_sq = x*x;
      double utilde = -x*lepton_e_sq*theta_sq - MA2*(1.-x)/x - lepton_mass_sq*x;
      double utilde_sq = utilde*utilde;
      // non-zero theta and non-zero m_l
      double tmin = utilde_sq/(4.0*lepton_e_sq*(1.0-x)*(1.0-x));
      // maximum t kinematically limited to the incident lepton energy
      double tmax = lepton_e_sq;
      /*
       * The chi integrand limits given by
       *
       * Eqs (3.20) and (A6) of
       * https://journals.aps.org/prd/pdf/10.1103/PhysRevD.8.3109
       * OR
       * Eqs (3.2) and (3.6) of
       * https://journals.aps.org/rmp/pdf/10.1103/RevModPhys.46.815
       *
       * to be
       *
       * tmax = m^2(1+l)^2
       * tmin = m^2 tmax / (2*E*x*(1-x))^2
       *
       * where
       *
       *  l = E^2x^2theta^2/m^2
       *  m is mass of dark photon
       *  E is the incident lepton energy
       *
       * were investigated in an attempt to control the numerical integration
       * of chi in the hopes that cutting the integral away from odd places
       * would be able to avoid the funky business. This was not successful,
       * but we are leaving them here in case a typo is found in the future
       * or the search is chosen to resume.
      double el = lepton_e_sq*x_sq*theta_sq/MA2;
      double tmax = MA2*pow(1 + el,2);
      double tmin = MA2*tmax / pow(2*lepton_e*x*(1-x),2);
       */
      // require 0 < tmin < tmax to procede
      if (tmin < 0) return 0.;
      if (tmax < tmin) return 0.;
      /*
       * numerically integrate to calculate chi ourselves
       */
      double chi = flux_factor_chi_numerical(A,Z, tmin, tmax);
      /*
       * Amplitude squared is taken from
       * Equation (17) from Appendix A of https://arxiv.org/pdf/2101.12192.pdf
       * with X = V
       */
      double factor1 = 2.0*(2.0 - 2.*x + x_sq)/(1. - x);
      double factor2 = 4.0*(MA2 + 2.0*lepton_mass_sq)/utilde_sq;
      double factor3 = utilde*x + MA2*(1. - x) + lepton_mass_sq*x_sq;
      double amplitude_sq = factor1 + factor2*factor3;
      return 2.*pow(epsilon_,2.)*pow(alphaEW,3.)
               *sqrt(x_sq*lepton_e_sq - MA2)*lepton_e*(1.-x)
               *(chi/utilde_sq)*amplitude_sq*sin(theta);
    };
    integrated_xsec = integrate(
        [&](double x) {
          auto theta_integrand = [&](double theta) {
            return diff_cross(x, theta);
          };
          return integrate(theta_integrand, 0., theta_max);
        }, xmin, xmax);
  } else if (xsec_method_ == XsecMethod::Improved) {
    /*
     * do the theta integral analytically by neglecting
     * all theta terms in the integrand.
     */
    integrated_xsec = integrate(
        [&](double x) {
          if (x*lepton_e < threshold_) return 0.;
          double utilde = -MA2*(1.-x)/x -lepton_mass_sq*x;
          double utilde_sq = utilde*utilde;
          // non-zero theta and non-zero m_l
          double tmin = utilde_sq/(4.0*lepton_e_sq*(1.0-x)*(1.0-x));
          // maximum t kinematically limited to the incident lepton energy
          double tmax = lepton_e_sq;
          // require 0 < tmin < tmax to procede
          if (tmin < 0) return 0.;
          if (tmax < tmin) return 0.;
          double chi = flux_factor_chi_numerical(A,Z,tmin,tmax);
          double beta = sqrt(1 - MA2/lepton_e_sq),
                 nume = 1. - x + x*x/3.,
                 deno = MA2*(1-x)/x + lepton_mass_sq;
          return 4*pow(epsilon_,2)*pow(alphaEW,3)*chi*beta*nume/deno;
        }, xmin, xmax);
  } else if (xsec_method_ == XsecMethod::HyperImproved) {
    /*
     * calculate chi once at x=1, theta=0 and then use it
     * everywhere in the integration over dsigma/dx
     *
     * cut off the integration earlier than the lepton energy squared
     * so that this overestimate isn't too much of an overestimate.
     */
    double chi_hiww = flux_factor_chi_numerical(A,Z,
        MA2*MA2/(4*lepton_e_sq),MA2+lepton_mass_sq);
    integrated_xsec = integrate(
        [&](double x) {
          if (x*lepton_e < threshold_) return 0.;
          double beta = sqrt(1 - MA2/lepton_e_sq),
                 nume = 1. - x + x*x/3.,
                 deno = MA2*(1-x)/x + lepton_mass_sq;
          return 4*pow(epsilon_,2)*pow(alphaEW,3)*chi_hiww*beta*nume/deno;
        }, xmin, xmax);
  } else {
    throw std::runtime_error("Unrecognized XsecMethod, should be set using the enum class.");
  }
  static const G4double GeVtoPb = 3.894E08;
  /*
   * The integrated_xsec should be the correct value, we are just
   * converting it to Geant4's pb units here
   */
  G4double cross = integrated_xsec * GeVtoPb * CLHEP::picobarn;
  if (cross < 0.) return 0.;  // safety check all the math
  return cross;
}
References G4APrime::APrime(), epsilon_, g4db::flux_factor_chi_numerical(), Full, HyperImproved, Improved, g4db::integrate(), g4db::PrototypeModel::muons_, threshold_, and xsec_method_.
GenerateChange()
void g4db::G4DarkBreMModel::GenerateChange (G4ParticleChange & particleChange, const G4Track & track, const G4Step & step) virtual
Simulates the emission of a dark photon + lepton
See also
scale for how the event library is sampled and scaled to the incident lepton's actual energy
After calling scale, we rotate the outgoing lepton's momentum to the frame of the incident particle and then calculate the dark photon's momentum such that three-momentum is conserved.
Parameters
[in,out] particleChange structure holding changes to make to particle track
[in] track current track being processesed
[in] step current step of the track
Implements g4db::PrototypeModel.
Definition at line 448 of file G4DarkBreMModel.cxx.
{
  // mass of incident lepton
  double Ml = track.GetDefinition()->GetPDGMass() / CLHEP::GeV;
  // convert to energy units in LHE files [GeV]
  G4double incidentEnergy = step.GetPostStepPoint()->GetTotalEnergy()/CLHEP::GeV;
  G4ThreeVector recoilMomentum = scale(incidentEnergy, Ml);
  recoilMomentum.rotateUz(track.GetMomentumDirection());
  // create g4dynamicparticle object for the dark photon.
  // define its 3-momentum so we conserve 3-momentum with primary and recoil
  // lepton NOTE: does _not_ take nucleus recoil into account
  G4ThreeVector darkPhotonMomentum =
      track.GetMomentum() - recoilMomentum;
  G4DynamicParticle *dphoton =
      new G4DynamicParticle(G4APrime::APrime(), darkPhotonMomentum);
  // stop tracking and create new secondary instead of primary
  if (alwaysCreateNewLepton_) {
    /*
     * Create a new lepton in order to make it easier to extract
     * the outgoing sim-level dark brem kinematics.
     */
    G4DynamicParticle *el = new G4DynamicParticle(
        track.GetDefinition(), recoilMomentum);
    particleChange.SetNumberOfSecondaries(2);
    particleChange.AddSecondary(dphoton);
    particleChange.AddSecondary(el);
    particleChange.ProposeTrackStatus(fStopAndKill);
    // continue tracking
  } else {
    /*
     * just have primary lose energy (don't rename to different track ID)
     *
     * This branch is untested and so we are not sure if it works as expected.
     */
    particleChange.SetNumberOfSecondaries(1);
    particleChange.AddSecondary(dphoton);
    particleChange.ProposeMomentumDirection(recoilMomentum.unit());
    double recoil_energy = sqrt(recoilMomentum.mag2()+Ml*Ml);
    // energy of primary recoiling
    G4double finalKE = recoil_energy - Ml;
    particleChange.ProposeEnergy(finalKE);
  }
}
References alwaysCreateNewLepton_, G4APrime::APrime(), and scale().
MakePlaceholders()
void g4db::G4DarkBreMModel::MakePlaceholders () private
Fill vector of currentDataPoints_ with the same number of items as the madgraph data.
Randomly choose a starting point so that the simulation run isn't dependent on the order of the events as written in the LHE library. The random starting position is uniformly chosen using G4Uniform() so. The sample function will loop from the last event parsed back to the first event parsed so that the starting position does not matter.
In this function, we also update maxIterations_ so that it is equal to the smallest entry in the library (with a maximum of 10k). This saves time in the situation where an incorrect library was accidentally used and the simulation is looping through events attempting to find one that can fit its criteria.
Definition at line 531 of file G4DarkBreMModel.cxx.
{
  currentDataPoints_.clear();
  maxIterations_ = 10000;
  for (const auto &iter : madGraphData_) {
    currentDataPoints_[iter.first] = int(G4UniformRand() * iter.second.size());
    if (iter.second.size() < maxIterations_)
      maxIterations_ = iter.second.size();
  }
}
References currentDataPoints_, madGraphData_, and maxIterations_.
Referenced by SetMadGraphDataLibrary().
PrintInfo()
void g4db::G4DarkBreMModel::PrintInfo () const virtual
Print the configuration of this model
Implements g4db::PrototypeModel.
Definition at line 172 of file G4DarkBreMModel.cxx.
{
  G4cout << " Dark Brem Vertex Library Model" << G4endl;
  G4cout << "   Threshold [GeV]: " << threshold_ << G4endl;
  G4cout << "   Epsilon:         " << epsilon_ << G4endl;
  G4cout << "   Scaling Method:  ";
  if (scaling_method_ == ScalingMethod::ForwardOnly) {
    G4cout << "ForwardOnly";
  } else if (scaling_method_ == ScalingMethod::CMScaling) {
    G4cout << "CMScaling";
  } else {
    G4cout << "Undefined";
  }
  G4cout << G4endl;
  G4cout << "   Xsec Method:     ";
  if (xsec_method_ == XsecMethod::Full) {
    G4cout << "Full";
  } else if (xsec_method_ == XsecMethod::Improved) {
    G4cout << "Improved";
  } else {
    G4cout << "HyperImproved";
  }
  G4cout << G4endl;
  G4cout << "   Vertex Library:  " << library_path_ << G4endl;
}
References CMScaling, epsilon_, ForwardOnly, Full, Improved, library_path_, scaling_method_, threshold_, and xsec_method_.
Referenced by main().
sample()
OutgoingKinematics g4db::G4DarkBreMModel::sample (double incident_energy) private
Returns MadGraph data given an energy [GeV].
Gets the energy fraction and from the imported LHE data. incident_energy should be in GeV, returns the sample outgoing kinematics.
Samples from the closest imported incident energy above the given value (this helps avoid biasing issues).
Parameters
incident_energy energy of particle undergoing dark brem [GeV]
Returns
sample outgoing kinematics
Definition at line 542 of file G4DarkBreMModel.cxx.
{
  // Cycle through imported beam energies until the closest one above is found,
  // or the max is reached.
  double samplingE = 0.;
  for (const auto &keyVal : currentDataPoints_) {
    samplingE = keyVal.first;  // move samplingE up
    // check if went under the sampling energy
    //  the map is sorted by key, so we can be done right after E0 goes under
    //  samplingE
    if (incident_energy < samplingE) break;
  }
  // now samplingE is the closest energy above E0 or the maximum energy imported
  // from mad graph
  // Need to loop around if we hit the end, in case our random
  // starting position happens to be late enough in the file
  if (currentDataPoints_.at(samplingE) >= madGraphData_.at(samplingE).size()) {
    currentDataPoints_[samplingE] = 0;
  }
  // increment the current index _after_ getting its entry from
  // the in-memory library
  return madGraphData_.at(samplingE).at(currentDataPoints_[samplingE]++);
}
References currentDataPoints_, and madGraphData_.
Referenced by scale().
scale()
G4ThreeVector g4db::G4DarkBreMModel::scale (double incident_energy, double lepton_mass)
Scale one of the MG events in our library to the input incident lepton energy.
This is also helpful for testing the scaling procedure in its own executable separate from the Geant4 infrastructure.
Note
The vector returned is relative to the incident lepton as if it came in along the z-axis.
Gets an energy fraction and transverse momentum () from the loaded library of MadGraph events using the entry in the library with the nearest incident energy above the actual input incident energy.
The scaling of this energy fraction and to the actual lepton energy depends on the input G4DarkBreMModel::ScalingMethod. In all cases, the azimuthal angle is chosen uniformly between 0 and .
Parameters
[in] incident_energy incident total energy of the lepton [GeV]
[in] lepton_mass mass of incident lepton [GeV]
Returns
G4ThreeVector representing the recoil lepton's outgoing momentum
Definition at line 380 of file G4DarkBreMModel.cxx.
{
  // mass A' in GeV
  static const double MA = G4APrime::APrime()->GetPDGMass() / CLHEP::GeV;
  OutgoingKinematics data = sample(incident_energy);
  double EAcc = (data.lepton.e() - lepton_mass) *
                    ((incident_energy - lepton_mass - MA) / (data.E - lepton_mass - MA))
                + lepton_mass;
  double Pt = data.lepton.perp();
  double P = sqrt(EAcc * EAcc - lepton_mass * lepton_mass);
  if (scaling_method_ == ScalingMethod::ForwardOnly) {
    unsigned int i = 0;
    while (Pt * Pt + lepton_mass * lepton_mass > EAcc * EAcc) {
      // Skip events until the transverse energy is less than the total energy.
      i++;
      data = sample(incident_energy);
      EAcc = (data.lepton.e() - lepton_mass) *
                 ((incident_energy - lepton_mass - MA) / (data.E - lepton_mass - MA))
             + lepton_mass;
      Pt = data.lepton.perp();
      P = sqrt(EAcc * EAcc - lepton_mass * lepton_mass);
      if (i > maxIterations_) {
        std::cerr
            << "Could not produce a realistic vertex with library energy "
            << data.lepton.e() << " GeV.\n"
            << "Consider expanding your libary of A' vertices to include a "
               "beam energy closer to "
            << incident_energy << " GeV."
            << std::endl;
        break;
      }
    }
  } else if (scaling_method_ == ScalingMethod::CMScaling) {
    CLHEP::HepLorentzVector el(data.lepton.px(), data.lepton.py(), data.lepton.pz(),
                               data.lepton.e());
    double ediff = data.E - incident_energy;
    CLHEP::HepLorentzVector newcm(data.centerMomentum.px(), data.centerMomentum.py(),
                                  data.centerMomentum.pz() - ediff,
                                  data.centerMomentum.e() - ediff);
    el.boost(-1. * data.centerMomentum.boostVector());
    el.boost(newcm.boostVector());
    double newE = (data.lepton.e() - lepton_mass) *
                      ((incident_energy - lepton_mass - MA) / (data.E - lepton_mass - MA)) +
                  lepton_mass;
    el.setE(newE);
    EAcc = el.e();
    Pt = el.perp();
    P = el.vect().mag();
  } else if (scaling_method_ == ScalingMethod::Undefined) {
    EAcc = data.lepton.e();
    P = sqrt(EAcc * EAcc - lepton_mass * lepton_mass);
    Pt = data.lepton.perp();
  } else {
    throw std::runtime_error("Unrecognized ScalingMethod, should be set by using the enum class.");
  }
  // outgoing lepton momentum
  G4double PhiAcc = G4UniformRand()*2*pi;
  G4double recoilMag = sqrt(EAcc * EAcc - lepton_mass*lepton_mass)*GeV;
  G4ThreeVector recoil;
  double ThetaAcc = std::asin(Pt / P);
  recoil.set(std::sin(ThetaAcc) * std::cos(PhiAcc),
                             std::sin(ThetaAcc) * std::sin(PhiAcc),
                             std::cos(ThetaAcc));
  recoil.setMag(recoilMag);
  return recoil;
}
References G4APrime::APrime(), g4db::OutgoingKinematics::centerMomentum, CMScaling, g4db::OutgoingKinematics::E, ForwardOnly, g4db::OutgoingKinematics::lepton, maxIterations_, sample(), scaling_method_, and Undefined.
Referenced by GenerateChange(), and main().
SetMadGraphDataLibrary()
void g4db::G4DarkBreMModel::SetMadGraphDataLibrary (const std::string & path) private
Set the library of dark brem events to be scaled.
This function loads the library from the on-disk file (or files).
See also
parseLibrary for how libraries are read and what the structure of a dark brem library is
Parameters
path path to the on-disk library
Definition at line 497 of file G4DarkBreMModel.cxx.
{
  /*
   * print status to user so they know what's happening
   */
  if (GetVerboseLevel() > 0) G4cout << "[ G4DarkBreMModel ] : loading event librariy..." << G4endl;
  parseLibrary(path, aprime_lhe_id_, madGraphData_);
  if (madGraphData_.size() == 0) {
    throw std::runtime_error("BadConf : Unable to find any library entries at '"+path+"'\n"
        "  The library is either a single CSV file or a directory of LHE files.\n"
        "  Any individual file can be compressed with `gzip`.\n"
        "  This means the valid extensions are '.lhe', '.lhe.gz', '.csv', and '.csv.gz'");
  }
  MakePlaceholders();  // Setup the placeholder offsets for getting data.
  if (GetVerboseLevel() > 0) G4cout << "[ G4DarkBreMModel ] : done" << G4endl;
  /*
   * Print out loaded MG library
   */
  if (GetVerboseLevel() > 1) {
    G4cout << "MadGraph Library of Dark Brem Events:\n";
    for (const auto &kV : madGraphData_) {
      G4cout << "\t" << kV.first << " GeV Beam -> "
                << kV.second.size() << " Events\n";
    }
    G4cout << G4endl;
  }
  return;
}
References aprime_lhe_id_, g4db::PrototypeModel::GetVerboseLevel(), madGraphData_, MakePlaceholders(), and g4db::parseLibrary().
Referenced by G4DarkBreMModel().
Member Data Documentation
alwaysCreateNewLepton_
bool g4db::G4DarkBreMModel::alwaysCreateNewLepton_ {true} private
should we always create a totally new lepton when we dark brem?
Note
make this configurable? I (Tom E) can't think of a reason NOT to have it... The alternative is to allow Geant4 to decide when to make a new particle by checking if the resulting kinetic energy is below some threshold.
Definition at line 394 of file G4DarkBreMModel.h.
Referenced by GenerateChange().
aprime_lhe_id_
int g4db::G4DarkBreMModel::aprime_lhe_id_ private
PDG ID number for the A' (dark photon) as written in the LHE files being loaded as the dark brem event library.
This is only used if parsing LHE files and can be ignored if the library is being loaded from an already-constructed CSV.
Definition at line 364 of file G4DarkBreMModel.h.
Referenced by SetMadGraphDataLibrary().
currentDataPoints_
std::map<double, unsigned int> g4db::G4DarkBreMModel::currentDataPoints_ private
Stores a map of current access points to mad graph data.
Maps incoming lepton energy to the index of the data vector that we will get the data from.
Also sorts the incoming lepton energy so that we can find the sampling energy that is closest above the actual incoming energy.
Definition at line 414 of file G4DarkBreMModel.h.
Referenced by MakePlaceholders(), and sample().
epsilon_
double g4db::G4DarkBreMModel::epsilon_ private
Epsilon value to plug into xsec calculation
See also
ComputeCrossSectionPerAtom for how this is used
Configurable with 'epsilon'
Definition at line 355 of file G4DarkBreMModel.h.
Referenced by ComputeCrossSectionPerAtom(), and PrintInfo().
library_path_
std::string g4db::G4DarkBreMModel::library_path_ private
Full path to the vertex library used for persisting into the RunHeader
Definition at line 384 of file G4DarkBreMModel.h.
Referenced by G4DarkBreMModel(), and PrintInfo().
madGraphData_
std::map<double, std::vector<OutgoingKinematics> > g4db::G4DarkBreMModel::madGraphData_ private
Storage of data from mad graph
Maps incoming lepton energy to various options for outgoing kinematics. This is a hefty map and is what stores all of the events imported from the LHE library of dark brem events.
Definition at line 403 of file G4DarkBreMModel.h.
Referenced by MakePlaceholders(), sample(), and SetMadGraphDataLibrary().
maxIterations_
unsigned int g4db::G4DarkBreMModel::maxIterations_ {10000} private
maximum number of iterations to check before giving up on an event
This is only used in the ForwardOnly scaling method and is only reached if the event library energies are not appropriately matched with the energy range of particles that are existing in the simulation.
Definition at line 338 of file G4DarkBreMModel.h.
Referenced by MakePlaceholders(), and scale().
method_name_
std::string g4db::G4DarkBreMModel::method_name_ private
Name of method for persisting into the RunHeader
Definition at line 379 of file G4DarkBreMModel.h.
scaling_method_
ScalingMethod g4db::G4DarkBreMModel::scaling_method_ private
method to scale events for this model
Definition at line 369 of file G4DarkBreMModel.h.
Referenced by PrintInfo(), and scale().
threshold_
double g4db::G4DarkBreMModel::threshold_ private
Threshold for non-zero xsec [GeV]
Configurable with 'threshold'. At minimum, it is always at least twice the dark photon mass.
Definition at line 346 of file G4DarkBreMModel.h.
Referenced by ComputeCrossSectionPerAtom(), and PrintInfo().
xsec_method_
XsecMethod g4db::G4DarkBreMModel::xsec_method_ private
method for calculating total cross section
Definition at line 374 of file G4DarkBreMModel.h.
Referenced by ComputeCrossSectionPerAtom(), G4DarkBreMModel(), and PrintInfo().
The documentation for this class was generated from the following files:
SimCore/G4DarkBreM/include/G4DarkBreM/G4DarkBreMModel.h
SimCore/G4DarkBreM/src/G4DarkBreM/G4DarkBreMModel.cxx