LDMX Software: simcore::G4CalorimeterHit Class Reference
simcore::G4CalorimeterHit Class Reference
Calorimeter hit which is used to create output SimCalorimeterHit objects.
#include <G4CalorimeterHit.h>
Public Member Functions
G4CalorimeterHit ()
virtual ~G4CalorimeterHit ()
void Draw ()
void Print ()
std::ostream & print (std::ostream &os)
void * operator new (size_t s)
void operator delete (void *aHit)
G4int getTrackID ()
void setTrackID (int trackID)
int getID ()
void setID (int id)
float getEdep ()
void setEdep (float edep)
const G4ThreeVector & getPosition ()
void setPosition (const float x, const float y, const float z)
float getTime ()
void setTime (float time)
int getPdgCode ()
void setPdgCode (int pdgCode)
Private Attributes
int trackID_ {-1}
int id_ {0}
double edep_ {0}
G4ThreeVector position_
float time_ {0}
int pdgCode_ {0}
Detailed Description
Calorimeter hit which is used to create output SimCalorimeterHit objects.
One of these is created for every step in a CalorimeterSD. These hits are combined later at the end of the event by the RootPersistencyManager from matching their detector IDs.
Definition at line 32 of file G4CalorimeterHit.h.
Constructor & Destructor Documentation
G4CalorimeterHit()
simcore::G4CalorimeterHit::G4CalorimeterHit () inline
Class constructor.
Definition at line 37 of file G4CalorimeterHit.h.
 {}
~G4CalorimeterHit()
virtual simcore::G4CalorimeterHit::~G4CalorimeterHit () inline virtual
Class destructor.
Definition at line 42 of file G4CalorimeterHit.h.
 {}
Member Function Documentation
Draw()
void simcore::G4CalorimeterHit::Draw ()
Draw the hit in the Geant4 runtime.
Definition at line 13 of file G4CalorimeterHit.cxx.
{
   G4VVisManager* visManager = G4VVisManager::GetConcreteInstance();
   if (visManager) {
     G4Point3D p3D = G4Point3D(position_);
     G4Circle chit(p3D);
     chit.SetScreenDiameter(3.0);
     chit.SetFillStyle(G4Circle::filled);
     G4Colour col(1.0, 0.0, 1.0);
     chit.SetVisAttributes(G4VisAttributes(col));
     visManager->Draw(chit);
   }
 }
References position_.
getEdep()
float simcore::G4CalorimeterHit::getEdep () inline
Get the energy deposition of the hit.
Returns
The energy deposition of the hit.
Definition at line 101 of file G4CalorimeterHit.h.
 { return edep_; }
References edep_.
Referenced by simcore::persist::RootPersistencyManager::writeCalorimeterHitsCollection(), and simcore::EcalHitIO::writeHitsCollection().
getID()
int simcore::G4CalorimeterHit::getID () inline
Get the detector ID of the hit.
Returns
The detector ID of the hit.
Definition at line 89 of file G4CalorimeterHit.h.
 { return id_; }
References id_.
Referenced by simcore::persist::RootPersistencyManager::writeCalorimeterHitsCollection(), and simcore::EcalHitIO::writeHitsCollection().
getPdgCode()
int simcore::G4CalorimeterHit::getPdgCode () inline
Get the PDG code of the track that made this hit.
Returns
The PDG code of the track that made the hit.
Definition at line 141 of file G4CalorimeterHit.h.
 { return pdgCode_; }
References pdgCode_.
Referenced by simcore::persist::RootPersistencyManager::writeCalorimeterHitsCollection(), and simcore::EcalHitIO::writeHitsCollection().
getPosition()
const G4ThreeVector& simcore::G4CalorimeterHit::getPosition () inline
Get the XYZ hit position [mm].
Returns
The hit position.
Definition at line 113 of file G4CalorimeterHit.h.
 { return position_; }
References position_.
Referenced by simcore::persist::RootPersistencyManager::writeCalorimeterHitsCollection().
getTime()
float simcore::G4CalorimeterHit::getTime () inline
Get the global time of the hit [ns].
Returns
The global hit time.
Definition at line 129 of file G4CalorimeterHit.h.
 { return time_; }
References time_.
Referenced by simcore::persist::RootPersistencyManager::writeCalorimeterHitsCollection(), and simcore::EcalHitIO::writeHitsCollection().
getTrackID()
G4int simcore::G4CalorimeterHit::getTrackID () inline
Get the track ID of the hit.
Returns
The track ID of the hit.
Definition at line 77 of file G4CalorimeterHit.h.
 { return trackID_; }
References trackID_.
Referenced by simcore::persist::RootPersistencyManager::writeCalorimeterHitsCollection(), and simcore::EcalHitIO::writeHitsCollection().
operator delete()
void simcore::G4CalorimeterHit::operator delete (void * aHit) inline
Delete a hit object.
Parameters
aHit The hit to delete.
Implementation of custom delete operator.
Definition at line 203 of file G4CalorimeterHit.h.
{
   G4CalorimeterHitAllocator.FreeSingle((G4CalorimeterHit*)aHit);
 }
References simcore::G4CalorimeterHitAllocator.
operator new()
void * simcore::G4CalorimeterHit::operator new (size_t s) inline
Create a new hit object.
Parameters
s The size of the hit object.
Implementation of custom new operator.
Definition at line 194 of file G4CalorimeterHit.h.
{
   void* aHit;
   aHit = (void*)G4CalorimeterHitAllocator.MallocSingle();
   return aHit;
 }
References simcore::G4CalorimeterHitAllocator.
Print()
void simcore::G4CalorimeterHit::Print ()
Print information about the hit.
Definition at line 29 of file G4CalorimeterHit.cxx.
 { print(std::cout); }
References print().
Referenced by simcore::EcalSD::ProcessHits(), and simcore::HcalSD::ProcessHits().
print()
std::ostream & simcore::G4CalorimeterHit::print (std::ostream & os)
Print hit information to an output stream.
Parameters
os The output stream.
Returns
The same output stream.
Definition at line 31 of file G4CalorimeterHit.cxx.
{
   os << "G4CalorimeterHit { "
      << "edep: " << this->edep_ << ", "
      << "position: " << position_ << ", "
      << "time: " << this->time_ << " }" << std::endl;
   return os;
 }
References edep_, position_, and time_.
Referenced by Print().
setEdep()
void simcore::G4CalorimeterHit::setEdep (float edep) inline
Set the energy deposition.
Parameters
edep The energy deposition.
Definition at line 107 of file G4CalorimeterHit.h.
 { this->edep_ = edep; }
References edep_.
Referenced by simcore::EcalSD::ProcessHits(), simcore::HcalSD::ProcessHits(), and simcore::TrigScintSD::ProcessHits().
setID()
void simcore::G4CalorimeterHit::setID (int id) inline
Set the detector ID.
Parameters
id The detector ID.
Definition at line 95 of file G4CalorimeterHit.h.
 { this->id_ = id; }
References id_.
Referenced by simcore::EcalSD::ProcessHits(), and simcore::HcalSD::ProcessHits().
setPdgCode()
void simcore::G4CalorimeterHit::setPdgCode (int pdgCode) inline
Set the PDG code from the track that made the hit.
Parameters
pdgCode The PDG code.
Definition at line 147 of file G4CalorimeterHit.h.
 { pdgCode_ = pdgCode; }
References pdgCode_.
Referenced by simcore::EcalSD::ProcessHits(), and simcore::HcalSD::ProcessHits().
setPosition()
void simcore::G4CalorimeterHit::setPosition (const float x, const float y, const float z) inline
Set the hit position [mm].
Parameters
x The X position.
y The Y position.
z The Z position.
Definition at line 121 of file G4CalorimeterHit.h.
{
     position_.set(x, y, z);
   }
References position_.
Referenced by simcore::EcalSD::ProcessHits(), and simcore::HcalSD::ProcessHits().
setTime()
void simcore::G4CalorimeterHit::setTime (float time) inline
Set the global hit time [ns].
Parameters
time The global hit time.
Definition at line 135 of file G4CalorimeterHit.h.
 { this->time_ = time; }
References time_.
Referenced by simcore::EcalSD::ProcessHits(), and simcore::HcalSD::ProcessHits().
setTrackID()
void simcore::G4CalorimeterHit::setTrackID (int trackID) inline
Set the track ID.
Parameters
trackID The track ID.
Definition at line 83 of file G4CalorimeterHit.h.
 { this->trackID_ = trackID; }
References trackID_.
Referenced by simcore::EcalSD::ProcessHits(), and simcore::HcalSD::ProcessHits().
Member Data Documentation
edep_
double simcore::G4CalorimeterHit::edep_ {0} private
The energy deposition.
Definition at line 163 of file G4CalorimeterHit.h.
Referenced by getEdep(), print(), and setEdep().
id_
int simcore::G4CalorimeterHit::id_ {0} private
The detector ID.
Definition at line 158 of file G4CalorimeterHit.h.
Referenced by getID(), and setID().
pdgCode_
int simcore::G4CalorimeterHit::pdgCode_ {0} private
The PDG code.
Definition at line 178 of file G4CalorimeterHit.h.
Referenced by getPdgCode(), and setPdgCode().
position_
G4ThreeVector simcore::G4CalorimeterHit::position_ private
The hit position.
Definition at line 168 of file G4CalorimeterHit.h.
Referenced by Draw(), getPosition(), print(), and setPosition().
time_
float simcore::G4CalorimeterHit::time_ {0} private
The global time.
Definition at line 173 of file G4CalorimeterHit.h.
Referenced by getTime(), print(), and setTime().
trackID_
int simcore::G4CalorimeterHit::trackID_ {-1} private
The track ID.
Definition at line 153 of file G4CalorimeterHit.h.
Referenced by getTrackID(), and setTrackID().
The documentation for this class was generated from the following files:
SimCore/include/SimCore/G4CalorimeterHit.h
SimCore/src/SimCore/G4CalorimeterHit.cxx