LDMX Software: g4db::example::OutgoingKinematics Class Reference
g4db::example::OutgoingKinematics Class Reference
Public Member Functions
bool found () const
void setRecoil (const G4Track *track)
void setAPrime (const G4Track *track)
void stream (std::ostream &o) const
virtual void Print () const final override
Static Public Member Functions
static OutgoingKinematics * get ()
Private Attributes
bool found_ {false}
have we found the dark brem products yet?
std::array< double, 4 > recoil_
the four momentum of the recoil lepton
std::array< double, 4 > aprime_
the four momentum of the produced dark photon (A')
Detailed Description
The event information we care about for studying the model
Since a new instance of this object is created for each event (and destroyed at the end of the event). The default values of its members correspond to the starting values at the beginning of an event.
Definition at line 198 of file simulate.cxx.
Member Function Documentation
found()
bool g4db::example::OutgoingKinematics::found () const inline
Check if the dark brem has been found
Definition at line 209 of file simulate.cxx.
                     {
    return found_;
  }
References found_.
get()
static OutgoingKinematics * g4db::example::OutgoingKinematics::get () inline static
Helper function to retrieve the current instance of the event information
Definition at line 258 of file simulate.cxx.
{
    auto user_info = G4EventManager::GetEventManager()->GetUserInformation();
    if (not user_info) throw std::runtime_error("Attempting to 'get' not-created event information");
    return dynamic_cast<OutgoingKinematics*>(user_info);
  }
Referenced by g4db::example::FindDarkBremProducts::PreUserTrackingAction().
Print()
virtual void g4db::example::OutgoingKinematics::Print () const inline final override virtual
Reequired by Geant4, simply print to std::cout using stream
Definition at line 250 of file simulate.cxx.
{
    stream(std::cout);
    std::cout << std::flush;
  }
References stream().
setAPrime()
void g4db::example::OutgoingKinematics::setAPrime (const G4Track * track) inline
Set the dark photon 4 momentum based on the passed track
Definition at line 229 of file simulate.cxx.
{
    found_ = true;
    aprime_ = {
      track->GetTotalEnergy(),
      track->GetMomentum().x(),
      track->GetMomentum().y(),
      track->GetMomentum().z()
    };
  }
References aprime_, and found_.
Referenced by g4db::example::FindDarkBremProducts::PreUserTrackingAction().
setRecoil()
void g4db::example::OutgoingKinematics::setRecoil (const G4Track * track) inline
Set the recoil 4 momentum based on the passed track
Definition at line 216 of file simulate.cxx.
{
    found_ = true;
    recoil_ = {
      track->GetTotalEnergy(),
      track->GetMomentum().x(),
      track->GetMomentum().y(),
      track->GetMomentum().z()
    };
  }
References found_, and recoil_.
Referenced by g4db::example::FindDarkBremProducts::PreUserTrackingAction().
stream()
void g4db::example::OutgoingKinematics::stream (std::ostream & o) const inline
Write out the two four-momenta in CSV format to the input stream
Definition at line 242 of file simulate.cxx.
{
    o << recoil_[0] << ',' << recoil_[1] << ',' << recoil_[2] << ',' << recoil_[3] << ','
      << aprime_[0] << ',' << aprime_[1] << ',' << aprime_[2] << ',' << aprime_[3] << '\n';
  }
References aprime_, and recoil_.
Referenced by Print().
Member Data Documentation
aprime_
std::array<double,4> g4db::example::OutgoingKinematics::aprime_ private
the four momentum of the produced dark photon (A')
Definition at line 204 of file simulate.cxx.
Referenced by setAPrime(), and stream().
found_
bool g4db::example::OutgoingKinematics::found_ {false} private
have we found the dark brem products yet?
Definition at line 200 of file simulate.cxx.
Referenced by found(), setAPrime(), and setRecoil().
recoil_
std::array<double,4> g4db::example::OutgoingKinematics::recoil_ private
the four momentum of the recoil lepton
Definition at line 202 of file simulate.cxx.
Referenced by setRecoil(), and stream().
The documentation for this class was generated from the following file:
SimCore/G4DarkBreM/app/simulate.cxx