LDMX Software: ldmx::HgcrocDigiCollection Class Reference
ldmx::HgcrocDigiCollection Class Reference
Represents a collection of the digi hits readout by an HGCROC.
#include <HgcrocDigiCollection.h>
Classes
class HgcrocDigi
class iterator
class Sample
One sample of a digi channel corresponding to one clock of the HGCROC chip.
Public Member Functions
HgcrocDigiCollection ()
virtual ~HgcrocDigiCollection ()
void Clear ()
void Print () const
int getVersion () const
void setVersion (int v)
unsigned int getNumSamplesPerDigi () const
void setNumSamplesPerDigi (unsigned int n)
unsigned int getSampleOfInterestIndex () const
void setSampleOfInterestIndex (unsigned int n)
const HgcrocDigi getDigi (unsigned int digiIndex) const
unsigned int getNumDigis () const
unsigned int size () const
void addDigi (unsigned int id, const std::vector< Sample > &digi)
void addDigi (unsigned int id, const std::vector< uint32_t > &digi)
iterator begin ()
iterator end ()
Private Member Functions
ClassDef (HgcrocDigiCollection, 4)
Private Attributes
std::vector< unsigned int > channelIDs_
std::vector< uint32_t > samples_
unsigned int numSamplesPerDigi_
unsigned int sampleOfInterest_
int version_
Static Private Attributes
static const int ONE_BIT_MASK = 1
static const int TEN_BIT_MASK = (1 << 10) - 1
static const int FIRSTFLAG_POS = 31
static const int SECONFLAG_POS = 30
static const int FIRSTMEAS_POS = 20
static const int SECONMEAS_POS = 10
Detailed Description
Represents a collection of the digi hits readout by an HGCROC.
Note
This class represents the digitized signal information in the form of a series of samples for each channel of readout. Each channel is represented by an ID integer and each sample is a 32-bit word. The number of samples for each digi is configurable, but is required to be the same for all channels.
Each digi corresponds to one channel ID and numSamplesPerDigi_ samples.
A custom iterator class and begin() and end() methods are also implemented so that a user can loop through this collection similar to any other container in C++.
for (auto digi : digi_collection) { // digi is of type HgcrocDigi }
Definition at line 42 of file HgcrocDigiCollection.h.
Constructor & Destructor Documentation
HgcrocDigiCollection()
ldmx::HgcrocDigiCollection::HgcrocDigiCollection () inline
Class constructor.
Definition at line 322 of file HgcrocDigiCollection.h.
{}
~HgcrocDigiCollection()
virtual ldmx::HgcrocDigiCollection::~HgcrocDigiCollection () inline virtual
Class destructor.
Definition at line 327 of file HgcrocDigiCollection.h.
{}
Member Function Documentation
addDigi()
void ldmx::HgcrocDigiCollection::addDigi (unsigned int id, const std::vector< Sample > & digi)
Add samples to collection
See also
Sample for how the valid measurements depend on the flags.
Parameters
[in] id global integer ID for this channel
[in] digi list of new samples to add
Referenced by ecal::EcalDigiProducer::produce(), ecal::EcalRawDecoder::produce(), hcal::HcalDigiProducer::produce(), hcal::HcalAlignPolarfires::produce(), and hcal::HcalRawDecoder::produce().
begin()
iterator ldmx::HgcrocDigiCollection::begin () inline
The beginning of this collection.
We just point the user to the zero'th entry.
Definition at line 484 of file HgcrocDigiCollection.h.
{ return iterator(*this, 0); }
ClassDef()
ldmx::HgcrocDigiCollection::ClassDef (HgcrocDigiCollection , 4) private
The ROOT class definition.
Clear()
void ldmx::HgcrocDigiCollection::Clear ()
Clear the data in the object.
Clears the vectors of channel IDs and samples, but does not change the other settings of this collection.
end()
iterator ldmx::HgcrocDigiCollection::end () inline
The end of this collection
The end of the collection is the number of digis stored in it.
Definition at line 492 of file HgcrocDigiCollection.h.
{ return iterator(*this, getNumDigis()); }
References getNumDigis().
getDigi()
const HgcrocDigi ldmx::HgcrocDigiCollection::getDigi (unsigned int digiIndex) const
Get samples for the input digi index
Each "digi" is numSamplesPerDigi_ samples. The sample is a single 32-bit word that is then translated into the 10-bit measurements depending on the first two bits.
See also
Sample for how the valid measurements depend on the flags.
HgcrocDigi for how to use the object returned from this function
Parameters
[in] digiIndex index of digi to decode
Returns
HgcrocDigi package with accessors
Referenced by hcal::HcalPedestalAnalyzer::analyze(), dqm::NtuplizeHgcrocDigiCollection::analyze(), hcal::test::HcalCheckReconstruction::analyze(), ldmx::HgcrocDigiCollection::iterator::operator*(), ecal::EcalTrigPrimDigiProducer::produce(), and hcal::HcalTrigPrimDigiProducer::produce().
getNumDigis()
unsigned int ldmx::HgcrocDigiCollection::getNumDigis () const inline
Get total number of digis
Returns
unsigned int number of digis
Definition at line 412 of file HgcrocDigiCollection.h.
{ return channelIDs_.size(); }
References channelIDs_.
Referenced by end(), ecal::EcalDigiProducer::produce(), ecal::EcalTrigPrimDigiProducer::produce(), hcal::HcalTrigPrimDigiProducer::produce(), hcal::HcalDigiProducer::produce(), hcal::HcalRecProducer::produce(), and hcal::HcalRawDecoder::produce().
getNumSamplesPerDigi()
unsigned int ldmx::HgcrocDigiCollection::getNumSamplesPerDigi () const inline
Get number of samples per digi
Returns
unsigned int number of samples per digi
Definition at line 363 of file HgcrocDigiCollection.h.
{ return numSamplesPerDigi_; }
References numSamplesPerDigi_.
Referenced by hcal::HcalRawDecoder::produce().
getSampleOfInterestIndex()
unsigned int ldmx::HgcrocDigiCollection::getSampleOfInterestIndex () const inline
Get index of sample of interest
Returns
unsigned int index for SOI
Definition at line 378 of file HgcrocDigiCollection.h.
{ return sampleOfInterest_; }
References sampleOfInterest_.
Referenced by ldmx::HgcrocDigiCollection::HgcrocDigi::soi().
getVersion()
int ldmx::HgcrocDigiCollection::getVersion () const inline
Get the version of ROC we have read
Returns
int version number of ROC
Definition at line 349 of file HgcrocDigiCollection.h.
{ return version_; }
References version_.
Referenced by ldmx::HgcrocDigiCollection::HgcrocDigi::at().
Print()
void ldmx::HgcrocDigiCollection::Print () const
Print out the object.
Prints out the lengths of the stored vectors and the other settings of this collection.
setNumSamplesPerDigi()
void ldmx::HgcrocDigiCollection::setNumSamplesPerDigi (unsigned int n) inline
Set number of samples for each digi
Parameters
[in] n number of samples per digi
Definition at line 369 of file HgcrocDigiCollection.h.
{
    numSamplesPerDigi_ = n;
    return;
  }
References numSamplesPerDigi_.
Referenced by ecal::EcalDigiProducer::produce(), ecal::EcalRawDecoder::produce(), hcal::HcalDigiProducer::produce(), and hcal::HcalRawDecoder::produce().
setSampleOfInterestIndex()
void ldmx::HgcrocDigiCollection::setSampleOfInterestIndex (unsigned int n) inline
Set index of sample of interest
Note
Does not check if input is a valid index! (i.e. input less than numSamplesPerDigi_)
Parameters
[in] n index for the sample of interest
Definition at line 388 of file HgcrocDigiCollection.h.
{
    sampleOfInterest_ = n;
    return;
  }
References sampleOfInterest_.
Referenced by ecal::EcalDigiProducer::produce(), ecal::EcalRawDecoder::produce(), hcal::HcalDigiProducer::produce(), and hcal::HcalRawDecoder::produce().
setVersion()
void ldmx::HgcrocDigiCollection::setVersion (int v) inline
Set the version of the ROC we have read
Definition at line 354 of file HgcrocDigiCollection.h.
{
    version_ = v;
    return;
  }
References version_.
Referenced by ecal::EcalRawDecoder::produce(), and hcal::HcalRawDecoder::produce().
size()
unsigned int ldmx::HgcrocDigiCollection::size () const inline
Get total number of digis
Returns
unsigned int number of digis
Definition at line 418 of file HgcrocDigiCollection.h.
{ return channelIDs_.size(); }
References channelIDs_.
Member Data Documentation
channelIDs_
std::vector<unsigned int> ldmx::HgcrocDigiCollection::channelIDs_ private
list of channel IDs that we have digis for
Definition at line 515 of file HgcrocDigiCollection.h.
Referenced by getNumDigis(), and size().
FIRSTFLAG_POS
const int ldmx::HgcrocDigiCollection::FIRSTFLAG_POS = 31 static private
Bit position of first flag
Definition at line 502 of file HgcrocDigiCollection.h.
Referenced by ldmx::HgcrocDigiCollection::Sample::isTOTinProgress().
FIRSTMEAS_POS
const int ldmx::HgcrocDigiCollection::FIRSTMEAS_POS = 20 static private
Bit position of first measurement
Definition at line 508 of file HgcrocDigiCollection.h.
Referenced by ldmx::HgcrocDigiCollection::Sample::first().
numSamplesPerDigi_
unsigned int ldmx::HgcrocDigiCollection::numSamplesPerDigi_ private
number of samples for each digi
Definition at line 521 of file HgcrocDigiCollection.h.
Referenced by getNumSamplesPerDigi(), and setNumSamplesPerDigi().
ONE_BIT_MASK
const int ldmx::HgcrocDigiCollection::ONE_BIT_MASK = 1 static private
Mask for lowest order bit in an int
Definition at line 496 of file HgcrocDigiCollection.h.
Referenced by ldmx::HgcrocDigiCollection::Sample::isTOTComplete(), and ldmx::HgcrocDigiCollection::Sample::isTOTinProgress().
sampleOfInterest_
unsigned int ldmx::HgcrocDigiCollection::sampleOfInterest_ private
index for the sample of interest in the samples list
Definition at line 524 of file HgcrocDigiCollection.h.
Referenced by getSampleOfInterestIndex(), and setSampleOfInterestIndex().
samples_
std::vector<uint32_t> ldmx::HgcrocDigiCollection::samples_ private
list of samples that we have been given
Definition at line 518 of file HgcrocDigiCollection.h.
SECONFLAG_POS
const int ldmx::HgcrocDigiCollection::SECONFLAG_POS = 30 static private
Bit position of second flag
Definition at line 505 of file HgcrocDigiCollection.h.
Referenced by ldmx::HgcrocDigiCollection::Sample::isTOTComplete().
SECONMEAS_POS
const int ldmx::HgcrocDigiCollection::SECONMEAS_POS = 10 static private
Bit position of second measurement
Definition at line 511 of file HgcrocDigiCollection.h.
Referenced by ldmx::HgcrocDigiCollection::Sample::secon().
TEN_BIT_MASK
const int ldmx::HgcrocDigiCollection::TEN_BIT_MASK = (1 << 10) - 1 static private
Mask for lowest order ten bits in an int
Definition at line 499 of file HgcrocDigiCollection.h.
Referenced by ldmx::HgcrocDigiCollection::Sample::first(), ldmx::HgcrocDigiCollection::Sample::secon(), and ldmx::HgcrocDigiCollection::Sample::third().
version_
int ldmx::HgcrocDigiCollection::version_ private
version of the ROC we have read
Definition at line 527 of file HgcrocDigiCollection.h.
Referenced by getVersion(), and setVersion().
The documentation for this class was generated from the following file:
Recon/include/Recon/Event/HgcrocDigiCollection.h