LDMX Software: simcore::EcalSD Class Reference
simcore::EcalSD Class Reference
ECal sensitive detector that uses an EcalHexReadout to create the hits.
#include <EcalSD.h>
Public Member Functions
EcalSD (const std::string &name, simcore::ConditionsInterface &ci, const framework::config::Parameters &p)
virtual ~EcalSD ()=default
virtual bool isSensDet (G4LogicalVolume *vol) const final override
G4bool ProcessHits (G4Step *aStep, G4TouchableHistory *ROhist) final override
virtual void saveHits (framework::Event &event) final override
virtual void OnFinishedEvent () final override
Public Member Functions inherited from simcore::SensitiveDetector
SensitiveDetector (const std::string &name, simcore::ConditionsInterface &ci, const framework::config::Parameters &parameters)
virtual ~SensitiveDetector ()=default
virtual bool isSensDet (G4LogicalVolume *lv) const =0
virtual G4bool ProcessHits (G4Step *step, G4TouchableHistory *hist) override=0
virtual void saveHits (framework::Event &event)=0
virtual void EndOfEvent (G4HCofThisEvent *) override
virtual void OnFinishedEvent ()=0
Static Public Attributes
static const std::string COLLECTION_NAME = "EcalSimHits"
Name of output collection of hits.
Private Attributes
std::map< ldmx::EcalID, ldmx::SimCalorimeterHit > hits_
map of hits to add to the event (will be squashed)
bool enableHitContribs_
enable hit contribs
bool compressHitContribs_
compress hit contribs
Additional Inherited Members
Public Types inherited from simcore::SensitiveDetector
using Factory = ::simcore::Factory< SensitiveDetector, SensitiveDetector *, const std::string &, simcore::ConditionsInterface &, const framework::config::Parameters & >
Protected Member Functions inherited from simcore::SensitiveDetector
template<class T >
const T & getCondition (const std::string &condition_name)
bool isGeantino (const G4Step *step) const
const TrackMap & getTrackMap () const
Detailed Description
ECal sensitive detector that uses an EcalHexReadout to create the hits.
Definition at line 30 of file EcalSD.h.
Constructor & Destructor Documentation
EcalSD()
simcore::EcalSD::EcalSD (const std::string & name, simcore::ConditionsInterface & ci, const framework::config::Parameters & p)
Class constructor.
Parameters
name The name of the sensitive detector.
theCollectionName The name of the hits collection.
subDetID The subdetector ID.
Definition at line 19 of file EcalSD.cxx.
    : SensitiveDetector(name, ci, p) {
  enableHitContribs_ = p.getParameter<bool>("enableHitContribs");
  compressHitContribs_ = p.getParameter<bool>("compressHitContribs");
}
References compressHitContribs_, enableHitContribs_, and framework::config::Parameters::getParameter().
~EcalSD()
virtual simcore::EcalSD::~EcalSD () virtual default
Class destructor.
Member Function Documentation
isSensDet()
virtual bool simcore::EcalSD::isSensDet (G4LogicalVolume * vol) const inline final override virtual
Should the input volume be consider apart of this sensitive detector?
Note
Dependent on names defined in GDML!
Implements simcore::SensitiveDetector.
Definition at line 54 of file EcalSD.h.
{
    auto region = vol->GetRegion();
    if (region and region->GetName().contains("CalorimeterRegion")) {
      return vol->GetName().contains("Si");
    }
    return false;
  }
OnFinishedEvent()
virtual void simcore::EcalSD::OnFinishedEvent () inline final override virtual
Clear the map of hits we have accumulated
Implements simcore::SensitiveDetector.
Definition at line 77 of file EcalSD.h.
{ hits_.clear(); }
References hits_.
ProcessHits()
G4bool simcore::EcalSD::ProcessHits (G4Step * aStep, G4TouchableHistory * ROhist) final override virtual
Process steps to create hits.
Parameters
aStep The step information.
ROhist The readout history.
DEBUG this printout is helpful when developing the GDML and/or EcalGeometry since Geant4 will probe where exactly the GDML sensitive volumes are std::cout << "(" << position[0] << ", " << position[1] << ", " << position[2] << ") " << cpynum << " -> layer " << layerNumber << " module " << module_position << std::endl;
convert position to center of cell position
This is the behavior that has been done in the past, although it is completely redundant with the ID information already deduced. It would probably help us more if we persisted the actual simulated position of the hit rather than the cell center; however, that is up for more discussion.
Implements simcore::SensitiveDetector.
Definition at line 26 of file EcalSD.cxx.
{
  static const int layer_depth = 2;  // index depends on GDML implementation
  const auto& geometry = getCondition<ldmx::EcalGeometry>(
      ldmx::EcalGeometry::CONDITIONS_OBJECT_NAME);
  // Get the edep from the step.
  G4double edep = aStep->GetTotalEnergyDeposit();
  // Skip steps with no energy dep which come from non-Geantino particles.
  if (edep == 0.0 and not isGeantino(aStep)) {
    if (verboseLevel > 2) {
      G4cout << "CalorimeterSD skipping step with zero edep." << G4endl
             << G4endl;
    }
    return false;
  }
  // Compute the hit position
  G4StepPoint* prePoint = aStep->GetPreStepPoint();
  G4StepPoint* postPoint = aStep->GetPostStepPoint();
  G4ThreeVector position =
      0.5 * (prePoint->GetPosition() + postPoint->GetPosition());
  // Create the ID for the hit.
  int cpynum = aStep->GetPreStepPoint()
                   ->GetTouchableHandle()
                   ->GetHistory()
                   ->GetVolume(layer_depth)
                   ->GetCopyNo();
  int layerNumber;
  layerNumber = cpynum / 7;
  int module_position = cpynum % 7;
  // fastest, but need to trust module number between GDML and EcalGeometry
  // match
  ldmx::EcalID id =
      geometry.getID(position[0], position[1], layerNumber, module_position);
  // medium, only need to trust z-layer positions in GDML and EcalGeometry match
  //    helpful for debugging any issues where transverse position is not
  //    matching between the GDML and EcalGeometry
  // ldmx::EcalID id = geometry.getID(position[0], position[1], layerNumber);
  // slowest, completely rely on EcalGeometry
  //    this is helpful for validating the EcalGeometry implementation and
  //    configuration since this will be called with any hit position that
  //    is inside of the configured SD volumes from Geant4's point of view
  // ldmx::EcalID id = geometry.getID(position[0], position[1], position[2]);
  if (hits_.find(id) == hits_.end()) {
    // hit in empty cell
    auto& hit = hits_[id];
    hit.setID(id.raw());
    auto [x, y, z] = geometry.getPosition(id);
    hit.setPosition(x, y, z);
  }
  auto& hit = hits_[id];
  // hit variables
  auto track = aStep->GetTrack();
  auto time = track->GetGlobalTime();
  auto track_id = track->GetTrackID();
  auto pdg = track->GetParticleDefinition()->GetPDGEncoding();
  if (enableHitContribs_) {
    int contrib_i = hit.findContribIndex(track_id, pdg);
    if (compressHitContribs_ and contrib_i != -1) {
      hit.updateContrib(contrib_i, edep, time);
    } else {
      hit.addContrib(getTrackMap().findIncident(track_id), track_id, pdg, edep,
                     time);
    }
  } else {
    // no hit contribs and hit already exists
    hit.setEdep(hit.getEdep() + edep);
    if (time < hit.getTime() or hit.getTime() == 0) {
      hit.setTime(time);
    }
  }
  return true;
}
References compressHitContribs_, enableHitContribs_, simcore::TrackMap::findIncident(), simcore::SensitiveDetector::getTrackMap(), hits_, and simcore::SensitiveDetector::isGeantino().
saveHits()
void simcore::EcalSD::saveHits (framework::Event & event) final override virtual
Add our hits to the event bus.
Implements simcore::SensitiveDetector.
Definition at line 129 of file EcalSD.cxx.
{
  // squash hits into list
  std::vector<ldmx::SimCalorimeterHit> hits;
  hits.reserve(hits_.size());
  for (const auto& [id, hit] : hits_) hits.push_back(hit);
  event.add(COLLECTION_NAME, hits);
}
References COLLECTION_NAME, and hits_.
Member Data Documentation
COLLECTION_NAME
const std::string simcore::EcalSD::COLLECTION_NAME = "EcalSimHits" static
Name of output collection of hits.
Definition at line 33 of file EcalSD.h.
Referenced by saveHits().
compressHitContribs_
bool simcore::EcalSD::compressHitContribs_ private
compress hit contribs
Definition at line 85 of file EcalSD.h.
Referenced by EcalSD(), and ProcessHits().
enableHitContribs_
bool simcore::EcalSD::enableHitContribs_ private
enable hit contribs
Definition at line 83 of file EcalSD.h.
Referenced by EcalSD(), and ProcessHits().
hits_
std::map<ldmx::EcalID, ldmx::SimCalorimeterHit> simcore::EcalSD::hits_ private
map of hits to add to the event (will be squashed)
Definition at line 81 of file EcalSD.h.
Referenced by OnFinishedEvent(), ProcessHits(), and saveHits().
The documentation for this class was generated from the following files:
SimCore/include/SimCore/SDs/EcalSD.h
SimCore/src/SimCore/SDs/EcalSD.cxx