LDMX Software: hcal::HcalDoubleEndRecProducer Class Reference
hcal::HcalDoubleEndRecProducer Class Reference
Public Member Functions
HcalDoubleEndRecProducer (const std::string &n, framework::Process &p)
virtual void configure (framework::config::Parameters &p) final override
virtual void produce (framework::Event &event) final override
Public Member Functions inherited from framework::Producer
Producer (const std::string &name, Process &process)
virtual void produce (Event &event)=0
virtual void beforeNewRun (ldmx::RunHeader &header)
Public Member Functions inherited from framework::EventProcessor
EventProcessor (const std::string &name, Process &process)
virtual ~EventProcessor ()
virtual void configure (framework::config::Parameters &parameters)
virtual void onNewRun (const ldmx::RunHeader &runHeader)
virtual void onFileOpen (EventFile &eventFile)
virtual void onFileClose (EventFile &eventFile)
virtual void onProcessStart ()
virtual void onProcessEnd ()
template<class T >
const T & getCondition (const std::string &condition_name)
TDirectory * getHistoDirectory ()
void setStorageHint (framework::StorageControlHint hint)
void setStorageHint (framework::StorageControlHint hint, const std::string &purposeString)
int getLogFrequency () const
int getRunNumber () const
std::string getName () const
void createHistograms (const std::vector< framework::config::Parameters > &histos)
Private Attributes
std::string pass_name_ {""}
name of pass of rechits to use
std::string coll_name_ {"HcalRecHits"}
name of rechits to use as input
std::string rec_pass_name_ {""}
name of pass of rechits to reconstruct
std::string rec_coll_name_ {"HcalRecHitsDoubleEnd"}
name of rechits to reconstruct
double pe_per_mip_
number of PEs per MIP
double mip_energy_
energy per MIP [MeV]
double clock_cycle_
length of clock cycle [ns]
Additional Inherited Members
Static Public Member Functions inherited from framework::EventProcessor
static void declare (const std::string &classname, int classtype, EventProcessorMaker *)
Static Public Attributes inherited from framework::Producer
static const int CLASSTYPE {1}
Protected Member Functions inherited from framework::EventProcessor
void abortEvent ()
Protected Attributes inherited from framework::EventProcessor
HistogramHelper histograms_
Interface class for making and filling histograms.
NtupleManager & ntuple_ {NtupleManager::getInstance()}
Manager for any ntuples.
logging::logger theLog_
The logger for this EventProcessor.
Detailed Description
Definition at line 13 of file HcalDoubleEndRecProducer.cxx.
Constructor & Destructor Documentation
HcalDoubleEndRecProducer()
hcal::HcalDoubleEndRecProducer::HcalDoubleEndRecProducer (const std::string & n, framework::Process & p) inline
Definition at line 33 of file HcalDoubleEndRecProducer.cxx.
      : Producer(n, p) {}
Member Function Documentation
configure()
void hcal::HcalDoubleEndRecProducer::configure (framework::config::Parameters & parameters) final override virtual
Callback for the EventProcessor to configure itself from the given set of parameters.
The parameters a processor has access to are the member variables of the python class in the sequence that has className equal to the EventProcessor class name.
For an example, look at MyProcessor.
Parameters
parameters Parameters for configuration.
Reimplemented from framework::EventProcessor.
Definition at line 41 of file HcalDoubleEndRecProducer.cxx.
{
  pass_name_ = p.getParameter("pass_name", pass_name_);
  coll_name_ = p.getParameter("coll_name", coll_name_);
  pe_per_mip_ = p.getParameter<double>("pe_per_mip");
  mip_energy_ = p.getParameter<double>("mip_energy");
  clock_cycle_ = p.getParameter<double>("clock_cycle");
}
References clock_cycle_, coll_name_, framework::config::Parameters::getParameter(), mip_energy_, pass_name_, and pe_per_mip_.
produce()
void hcal::HcalDoubleEndRecProducer::produce (framework::Event & event) final override virtual
Process the event and put new data products into it.
Parameters
event The Event to process.
Implements framework::Producer.
Definition at line 50 of file HcalDoubleEndRecProducer.cxx.
{
  const auto& hcalGeometry = getCondition<ldmx::HcalGeometry>(
      ldmx::HcalGeometry::CONDITIONS_OBJECT_NAME);
  const auto& conditions{
      getCondition<HcalReconConditions>(HcalReconConditions::CONDITIONS_NAME)};
  auto hcalRecHits =
      event.getCollection<ldmx::HcalHit>(coll_name_, pass_name_);
  std::vector<ldmx::HcalHit> doubleHcalRecHits;
  // group hcal rechits by the same HcalID
  std::map<ldmx::HcalID, std::vector<ldmx::HcalHit>> hitsByID;
  for (auto const& hit : hcalRecHits) {
    ldmx::HcalID id(hit.getSection(), hit.getLayer(), hit.getStrip());
    auto idh = hitsByID.find(id);
    if (idh == hitsByID.end()) {
      hitsByID[id] = std::vector<ldmx::HcalHit>(1, hit);
    } else {
      idh->second.push_back(hit);
    }
  }
  // make pairs of hcal rechits indices that belong to the same pulse
  // @TODO: for now we just take the first two indices that have opposite-ends
  //        we do not cover the case where two hits come separated in time
  std::map<ldmx::HcalID, std::pair<int,int>> indicesByID;
  for (auto const& hcalBar : hitsByID) {
    auto id = hcalBar.first;
    std::pair<int,int> indices(-1,-1);
    int iHit = 0;
    while ( iHit < hcalBar.second.size() ) {
      auto hit = hcalBar.second.at(iHit);
      ldmx::HcalDigiID digi_id(hit.getSection(), hit.getLayer(), hit.getStrip(), hit.getEnd());
      if(digi_id.isNegativeEnd() && indices.second==-1) {
    indices.second = iHit;
      }
      if(!digi_id.isNegativeEnd() && indices.first==-1) {
    indices.first = iHit;
      }
      iHit++;
    }
    indicesByID[id] = indices;
  }
  // reconstruct double-ended hits
  for (auto const& hcalBar : hitsByID) {
    auto id = hcalBar.first;
    // get bar position from geometry
    auto position = hcalGeometry.getStripCenterPosition(id);
    const auto orientation{hcalGeometry.getScintillatorOrientation(id)};
    // skip non-double-ended layers
    if (id.section() != ldmx::HcalID::HcalSection::BACK)
      continue;
    // get two hits to reconstruct
    auto hitPosEnd = hcalBar.second.at(indicesByID[id].first);
    auto hitNegEnd = hcalBar.second.at(indicesByID[id].second);
    // update position in strip according to time measurement
    double v =
      299.792 / 1.6;  // velocity of light in polystyrene, n = 1.6 = c/v
    double hitTimeDiff = hitPosEnd.getTime() - hitNegEnd.getTime();
    int position_bar_sign = hitTimeDiff > 0 ? 1 : -1;
    double position_bar = position_bar_sign * fabs(hitTimeDiff) * v / 2;
    if (orientation ==
        ldmx::HcalGeometry::ScintillatorOrientation::horizontal) {
      position.SetX(position_bar);
    } else {
      position.SetY(position_bar);
    }
    // TODO: switch unique hit time for this pulse
    double hitTime = (hitPosEnd.getTime() + hitNegEnd.getTime());
    // amplitude and PEs
    double num_mips_equivalent = (hitPosEnd.getAmplitude() + hitNegEnd.getAmplitude());
    double PEs = (hitPosEnd.getPE() + hitNegEnd.getPE());
    double reconstructed_energy =
      num_mips_equivalent * pe_per_mip_ * mip_energy_;
    // reconstructed Hit
    ldmx::HcalHit recHit;
    recHit.setID(id.raw());
    recHit.setXPos(position.X());
    recHit.setYPos(position.Y());
    recHit.setZPos(position.Z());
    recHit.setSection(id.section());
    recHit.setStrip(id.strip());
    recHit.setLayer(id.layer());
    recHit.setPE(PEs);
    recHit.setMinPE(std::min(hitPosEnd.getPE(),hitNegEnd.getPE()));
    recHit.setAmplitude(num_mips_equivalent);
    recHit.setEnergy(reconstructed_energy);
    recHit.setTime(hitTime);
    doubleHcalRecHits.push_back(recHit);
  }
  // add collection to event bus
  event.add(rec_coll_name_, doubleHcalRecHits);
}
References coll_name_, hcal::HcalReconConditions::CONDITIONS_NAME, ldmx::HcalGeometry::CONDITIONS_OBJECT_NAME, ldmx::HcalDigiID::isNegativeEnd(), mip_energy_, pass_name_, pe_per_mip_, rec_coll_name_, ldmx::CalorimeterHit::setAmplitude(), ldmx::CalorimeterHit::setEnergy(), ldmx::CalorimeterHit::setID(), ldmx::HcalHit::setLayer(), ldmx::HcalHit::setMinPE(), ldmx::HcalHit::setPE(), ldmx::HcalHit::setSection(), ldmx::HcalHit::setStrip(), ldmx::CalorimeterHit::setTime(), ldmx::CalorimeterHit::setXPos(), ldmx::CalorimeterHit::setYPos(), and ldmx::CalorimeterHit::setZPos().
Member Data Documentation
clock_cycle_
double hcal::HcalDoubleEndRecProducer::clock_cycle_ private
length of clock cycle [ns]
Definition at line 28 of file HcalDoubleEndRecProducer.cxx.
Referenced by configure().
coll_name_
std::string hcal::HcalDoubleEndRecProducer::coll_name_ {"HcalRecHits"} private
name of rechits to use as input
Definition at line 17 of file HcalDoubleEndRecProducer.cxx.
Referenced by configure(), and produce().
mip_energy_
double hcal::HcalDoubleEndRecProducer::mip_energy_ private
energy per MIP [MeV]
Definition at line 26 of file HcalDoubleEndRecProducer.cxx.
Referenced by configure(), and produce().
pass_name_
std::string hcal::HcalDoubleEndRecProducer::pass_name_ {""} private
name of pass of rechits to use
Definition at line 15 of file HcalDoubleEndRecProducer.cxx.
Referenced by configure(), and produce().
pe_per_mip_
double hcal::HcalDoubleEndRecProducer::pe_per_mip_ private
number of PEs per MIP
Definition at line 24 of file HcalDoubleEndRecProducer.cxx.
Referenced by configure(), and produce().
rec_coll_name_
std::string hcal::HcalDoubleEndRecProducer::rec_coll_name_ {"HcalRecHitsDoubleEnd"} private
name of rechits to reconstruct
Definition at line 21 of file HcalDoubleEndRecProducer.cxx.
Referenced by produce().
rec_pass_name_
std::string hcal::HcalDoubleEndRecProducer::rec_pass_name_ {""} private
name of pass of rechits to reconstruct
Definition at line 19 of file HcalDoubleEndRecProducer.cxx.
The documentation for this class was generated from the following file:
Hcal/src/Hcal/HcalDoubleEndRecProducer.cxx