LDMX Software: ldmx::PackedIndex< m0, m1, m2 > Class Template Reference
ldmx::PackedIndex< m0, m1, m2 > Class Template Reference
#include <PackedIndex.h>
Public Member Functions
PackedIndex (unsigned int v0, unsigned int v1, unsigned int v2=0, unsigned int v3=0)
PackedIndex (uint32_t value)
Constructor from index value.
unsigned int field0 () const
Get the value of field 0.
unsigned int field1 () const
Get the value of field 1.
unsigned int field2 () const
Get the value of field 2.
unsigned int field3 () const
Get the value of field 3.
uint32_t value () const
Get the fully packed index.
Private Attributes
uint32_t index_
The 32-bit integer that is storing our fields.
Detailed Description
template<unsigned int m0, unsigned int m1 = 0, unsigned int m2 = 0>
class ldmx::PackedIndex< m0, m1, m2 >
A maximally-packed index of upto four different fields.
Template Parameters
in] m0 modulus of field 0 (i.e. its maximum value)
Template Parameters
in] m1 modulus of field 1 (i.e. its maximum value) optional
Template Parameters
in] m2 modulus of field 2 (i.e. its maximum value) optional
Definition at line 23 of file PackedIndex.h.
Constructor & Destructor Documentation
PackedIndex() [1/2]
template<unsigned int m0, unsigned int m1 = 0, unsigned int m2 = 0> ldmx::PackedIndex< m0, m1, m2 >::PackedIndex (unsigned int v0, unsigned int v1, unsigned int v2 = 0, unsigned int v3 = 0) inline
Constructor from field values Put our values into a single 32-bit integer.
We are provided two to four values to pack.
Note
We do not check if the values are below the maxima defined by the template parameters.
Parameters
[in] v0 value of field 0
[in] v1 value of field 1
[in] v2 value of field 2
[in] v3 value of field 3
Definition at line 39 of file PackedIndex.h.
{
    index_=v0+v1*m0+v2*m0*m1+v3*m0*m1*m2;
  }
References ldmx::PackedIndex< m0, m1, m2 >::index_.
PackedIndex() [2/2]
template<unsigned int m0, unsigned int m1 = 0, unsigned int m2 = 0> ldmx::PackedIndex< m0, m1, m2 >::PackedIndex (uint32_t value) inline
Constructor from index value.
Definition at line 44 of file PackedIndex.h.
: index_{value} {}
Member Function Documentation
field0()
template<unsigned int m0, unsigned int m1 = 0, unsigned int m2 = 0> unsigned int ldmx::PackedIndex< m0, m1, m2 >::field0 () const inline
Get the value of field 0.
Definition at line 47 of file PackedIndex.h.
{ return index_%m0; }
References ldmx::PackedIndex< m0, m1, m2 >::index_.
Referenced by ldmx::EcalElectronicsID::channel(), and ldmx::HcalElectronicsID::channel().
field1()
template<unsigned int m0, unsigned int m1 = 0, unsigned int m2 = 0> unsigned int ldmx::PackedIndex< m0, m1, m2 >::field1 () const inline
Get the value of field 1.
Definition at line 49 of file PackedIndex.h.
{ return (index_/m0)%m1; }
References ldmx::PackedIndex< m0, m1, m2 >::index_.
Referenced by ldmx::EcalElectronicsID::elink(), and ldmx::HcalElectronicsID::elink().
field2()
template<unsigned int m0, unsigned int m1 = 0, unsigned int m2 = 0> unsigned int ldmx::PackedIndex< m0, m1, m2 >::field2 () const inline
Get the value of field 2.
Definition at line 51 of file PackedIndex.h.
{ return (index_/(m0*m1))%m2; }
References ldmx::PackedIndex< m0, m1, m2 >::index_.
Referenced by ldmx::EcalElectronicsID::fiber(), and ldmx::HcalElectronicsID::fiber().
field3()
template<unsigned int m0, unsigned int m1 = 0, unsigned int m2 = 0> unsigned int ldmx::PackedIndex< m0, m1, m2 >::field3 () const inline
Get the value of field 3.
Definition at line 53 of file PackedIndex.h.
{ return (index_/(m0*m1*m2)); }
References ldmx::PackedIndex< m0, m1, m2 >::index_.
value()
template<unsigned int m0, unsigned int m1 = 0, unsigned int m2 = 0> uint32_t ldmx::PackedIndex< m0, m1, m2 >::value () const inline
Get the fully packed index.
Definition at line 56 of file PackedIndex.h.
{ return index_; }
References ldmx::PackedIndex< m0, m1, m2 >::index_.
Member Data Documentation
index_
template<unsigned int m0, unsigned int m1 = 0, unsigned int m2 = 0> uint32_t ldmx::PackedIndex< m0, m1, m2 >::index_ private
The 32-bit integer that is storing our fields.
Definition at line 60 of file PackedIndex.h.
Referenced by ldmx::PackedIndex< m0, m1, m2 >::field0(), ldmx::PackedIndex< m0, m1, m2 >::field1(), ldmx::PackedIndex< m0, m1, m2 >::field2(), ldmx::PackedIndex< m0, m1, m2 >::field3(), ldmx::PackedIndex< m0, m1, m2 >::PackedIndex(), and ldmx::PackedIndex< m0, m1, m2 >::value().
The documentation for this class was generated from the following file:
DetDescr/include/DetDescr/PackedIndex.h