LDMX Software: tracking::dqm::TrackerDigiDQM Class Reference
tracking::dqm::TrackerDigiDQM Class Reference
Public Member Functions
TrackerDigiDQM (const std::string &name, framework::Process &process)
~TrackerDigiDQM ()=default
Destructor.
void analyze (const framework::Event &event) final override
Public Member Functions inherited from framework::Analyzer
Analyzer (const std::string &name, Process &process)
virtual void analyze (const Event &event)=0
Public Member Functions inherited from framework::EventProcessor
EventProcessor (const std::string &name, Process &process)
virtual ~EventProcessor ()
virtual void configure (framework::config::Parameters &parameters)
virtual void onNewRun (const ldmx::RunHeader &runHeader)
virtual void onFileOpen (EventFile &eventFile)
virtual void onFileClose (EventFile &eventFile)
virtual void onProcessStart ()
virtual void onProcessEnd ()
template<class T >
const T & getCondition (const std::string &condition_name)
TDirectory * getHistoDirectory ()
void setStorageHint (framework::StorageControlHint hint)
void setStorageHint (framework::StorageControlHint hint, const std::string &purposeString)
int getLogFrequency () const
int getRunNumber () const
std::string getName () const
void createHistograms (const std::vector< framework::config::Parameters > &histos)
Additional Inherited Members
Static Public Member Functions inherited from framework::EventProcessor
static void declare (const std::string &classname, int classtype, EventProcessorMaker *)
Static Public Attributes inherited from framework::Analyzer
static const int CLASSTYPE {2}
Protected Member Functions inherited from framework::EventProcessor
void abortEvent ()
Protected Attributes inherited from framework::EventProcessor
HistogramHelper histograms_
Interface class for making and filling histograms.
NtupleManager & ntuple_ {NtupleManager::getInstance()}
Manager for any ntuples.
logging::logger theLog_
The logger for this EventProcessor.
Detailed Description
Definition at line 8 of file TrackerDigiDQM.h.
Constructor & Destructor Documentation
TrackerDigiDQM()
tracking::dqm::TrackerDigiDQM::TrackerDigiDQM (const std::string & name, framework::Process & process) inline
Definition at line 12 of file TrackerDigiDQM.h.
      : framework::Analyzer(name, process){};
Member Function Documentation
analyze()
void tracking::dqm::TrackerDigiDQM::analyze (const framework::Event & event) final override virtual
Process the event and make histograms or summaries
Parameters
event The Event to analyze
Implements framework::Analyzer.
Definition at line 8 of file TrackerDigiDQM.cxx.
{
  if (!event.exists("OutputMeasurements")) return;
  auto measurements{event.getCollection<ldmx::Measurement>("OutputMeasurements")};
  for (auto& measurement : measurements) {
    auto global_position{measurement.getGlobalPosition()};
    auto local_position{measurement.getLocalPosition()};
    auto layer_id{measurement.getLayerID()};
    auto time{measurement.getTime()};
    histograms_.fill("global_yz_l"+std::to_string(layer_id), global_position[1], global_position[2]);
    histograms_.fill("global_xy", global_position[0], global_position[1]);
    histograms_.fill("local_uv_l"+std::to_string(layer_id), local_position[0], local_position[1]);
    histograms_.fill("time_l"+std::to_string(layer_id), time);
  }
}
References framework::Event::exists(), framework::HistogramHelper::fill(), ldmx::Measurement::getGlobalPosition(), and framework::EventProcessor::histograms_.
The documentation for this class was generated from the following files:
Tracking/include/Tracking/dqm/TrackerDigiDQM.h
Tracking/src/Tracking/dqm/TrackerDigiDQM.cxx