LDMX Software: ldmx::HcalGeometry Class Reference
ldmx::HcalGeometry Class Reference
Implementation of HCal strip readout.
#include <HcalGeometry.h>
Public Member Functions
~HcalGeometry ()=default
TVector3 getStripCenterPosition (ldmx::HcalID id) const
double getHalfTotalWidth (int isection) const
int getNumSections () const
int getNumLayers (int isection) const
int getNumStrips (int isection) const
double getEcalDx () const
double getEcalDy () const
Public Member Functions inherited from framework::ConditionsObject
ConditionsObject (const std::string &name)
virtual ~ConditionsObject ()
std::string getName () const
Static Public Attributes
static constexpr const char * CONDITIONS_OBJECT_NAME {"HcalGeometry"}
Private Member Functions
HcalGeometry (const framework::config::Parameters &ps)
void buildStripPositionMap ()
Private Attributes
int verbose_ {0}
Verbosity, not configurable but helpful if developing.
double ThicknessScint_
Thickness of scintillator.
double WidthScint_
Width of Scintillator Strip [mm].
std::vector< double > HalfTotalWidth_
Half Total Width of Strips [mm].
std::vector< double > ZeroLayer_
Front of HCal relative to world geometry for each section [mm].
std::vector< double > ZeroStrip_
The plane of the zero'th strip of each section [mm].
std::vector< double > LayerThickness_
Thickness of the layers in each section [mm].
std::vector< int > NumLayers_
Number of layers in each section.
std::vector< int > NumStrips_
Number of strips per layer in each section.
int NumSections_
Number of sections.
double EcalDx_
Lenght of the Ecal (in x and y)
double EcalDy_
std::map< ldmx::HcalID, TVector3 > stripPositionMap_
Friends
class hcal::HcalGeometryProvider
Detailed Description
Implementation of HCal strip readout.
Definition at line 34 of file HcalGeometry.h.
Constructor & Destructor Documentation
~HcalGeometry()
ldmx::HcalGeometry::~HcalGeometry () default
Class destructor.
Does nothing because the stl containers clean up automatically.
HcalGeometry()
ldmx::HcalGeometry::HcalGeometry (const framework::config::Parameters & ps) private
Class constructor, for use only by the provider
Parameters
ps Parameters to configure the HcalGeometry
Definition at line 10 of file HcalGeometry.cxx.
     : framework::ConditionsObject(HcalGeometry::CONDITIONS_OBJECT_NAME) {
   ThicknessScint_ = ps.getParameter<double>("ThicknessScint");
   WidthScint_ = ps.getParameter<double>("WidthScint");
   ZeroLayer_ = ps.getParameter<std::vector<double>>("ZeroLayer");
   ZeroStrip_ = ps.getParameter<std::vector<double>>("ZeroStrip");
   LayerThickness_ = ps.getParameter<std::vector<double>>("LayerThickness");
   NumLayers_ = ps.getParameter<std::vector<int>>("NumLayers");
   NumStrips_ = ps.getParameter<std::vector<int>>("NumStrips");
   NumSections_ = ps.getParameter<int>("NumSections");
   HalfTotalWidth_ = ps.getParameter<std::vector<double>>("HalfTotalWidth");
   EcalDx_ = ps.getParameter<double>("EcalDx");
   EcalDy_ = ps.getParameter<double>("EcalDy");
   verbose_ = ps.getParameter<int>("verbose");
   buildStripPositionMap();
 }
References buildStripPositionMap(), EcalDx_, framework::config::Parameters::getParameter(), HalfTotalWidth_, LayerThickness_, NumLayers_, NumSections_, NumStrips_, ThicknessScint_, verbose_, WidthScint_, ZeroLayer_, and ZeroStrip_.
Member Function Documentation
buildStripPositionMap()
void ldmx::HcalGeometry::buildStripPositionMap () private
Map builder of HcalID and position. To build the map we loop over the number of Hcal sections, layers and strips. The Hcal sections range from 0 to 4. (We hard-code the number of sections as seen in HcalID) The Hcal layers range from 1 to NumLayers_[section]. The Hcal strips range from 0 to NumStrips_[section].
Odd layers have horizontal strips. Even layers have vertical strips.
For back Hcal:
layers in z
strips occupy thickness of scintillator in z (e.g. 20mm)
strips orientation is in x(y) for odd(even) layers For side Hcal:
layers in x(y)
strips occupy width of scintillator in z (e.g. 50mm)
strips orientation is in x(y) for top-bottom(left-right) sections
Now compute, y(x) position for even(odd) layers, relative to the center of detector. Strips enumeration starts from -y(-x) stripcenter will be large for +y(+x) and the halfwidth of the strip needs to be subtracted The halfwidth of the scintillator is given by ZeroStrip_. The x(y) position is set to the center of the strip (0).
Top and Bottom sections have strips orientated in x The y coordinate will be given by layercenter + ZeroLayer_(y)
Definition at line 28 of file HcalGeometry.cxx.
{
   // We hard-code the number of sections as seen in HcalID
   for (int section = 0; section < NumSections_; section++) {
     for (int layer = 1; layer <= NumLayers_[section]; layer++) {
       for (int strip = 0; strip < NumStrips_[section]; strip++) {
         // initialize values
         double x{-99999}, y{-99999}, z{-99999};
         // get hcal section
         ldmx::HcalID::HcalSection hcalsection =
             (ldmx::HcalID::HcalSection)section;
         // the center of a layer: layer * (layer_dz) + (layer_dz)/2
         double layercenter =
             layer * LayerThickness_.at(section) + 0.5 * ThicknessScint_;
         // the center of a strip: (strip + 0.5) * (strip_dx)
         double stripcenter = (strip + 0.5) * WidthScint_;
         if (hcalsection == ldmx::HcalID::HcalSection::BACK) {
           // z position: zero-layer(z) + layer_z + thickness_scint
           z = ZeroLayer_.at(section) + layercenter;
           if (layer % 2 == 1) {
             y = stripcenter - ZeroStrip_.at(section);
             x = 0;
           } else {
             x = stripcenter - ZeroStrip_.at(section);
             y = 0;
           }
         } else {
           // z position: zero-strip(z) + strip_center(z)
           z = ZeroStrip_.at(section) + stripcenter;
           if (hcalsection == ldmx::HcalID::HcalSection::TOP or
               hcalsection == ldmx::HcalID::HcalSection::BOTTOM) {
             y = ZeroLayer_.at(section) + layercenter;
             x = HalfTotalWidth_.at(section);
             if (hcalsection == ldmx::HcalID::HcalSection::BOTTOM) {
               y *= -1;
               x *= -1;
             }
           } else {
             x = ZeroLayer_.at(section) + layercenter;
             y = HalfTotalWidth_.at(section);
             if (hcalsection == ldmx::HcalID::HcalSection::RIGHT) {
               x *= -1;
               y *= -1;
             }
           }
         }
         TVector3 pos;
         pos.SetXYZ(x, y, z);
         stripPositionMap_[ldmx::HcalID(section, layer, strip)] = pos;
       }  // loop over strips
     }    // loop over layers
   }      // loop over sections
 }  // strip position map
References HalfTotalWidth_, LayerThickness_, NumLayers_, NumSections_, NumStrips_, stripPositionMap_, ThicknessScint_, WidthScint_, ZeroLayer_, and ZeroStrip_.
Referenced by HcalGeometry().
getEcalDx()
double ldmx::HcalGeometry::getEcalDx () const inline
Get the length of the Ecal in (x) for the side Hcal.
Definition at line 90 of file HcalGeometry.h.
 { return EcalDx_; }
References EcalDx_.
getEcalDy()
double ldmx::HcalGeometry::getEcalDy () const inline
Get the length of the Ecal in (y) for the side Hcal
Definition at line 95 of file HcalGeometry.h.
 { return EcalDy_; }
getHalfTotalWidth()
double ldmx::HcalGeometry::getHalfTotalWidth (int isection) const inline
Get the half total width for a given section(strip) for back(side) Hcal.
Parameters
section
Returns
half total width [mm]
Definition at line 68 of file HcalGeometry.h.
{
     return HalfTotalWidth_.at(isection);
   }
References HalfTotalWidth_.
getNumLayers()
int ldmx::HcalGeometry::getNumLayers (int isection) const inline
Get the number of layers for that section.
Definition at line 80 of file HcalGeometry.h.
 { return NumLayers_.at(isection); }
References NumLayers_.
getNumSections()
int ldmx::HcalGeometry::getNumSections () const inline
Get the number of sections.
Definition at line 75 of file HcalGeometry.h.
 { return NumSections_; }
References NumSections_.
getNumStrips()
int ldmx::HcalGeometry::getNumStrips (int isection) const inline
Get the number of strips per layer for that section.
Definition at line 85 of file HcalGeometry.h.
 { return NumStrips_.at(isection); }
References NumStrips_.
getStripCenterPosition()
TVector3 ldmx::HcalGeometry::getStripCenterPosition (ldmx::HcalID id) const inline
Get a strip center position from a combined hcal ID.
Exceptions
std::out_of_range if HcalID is not on map.
Parameters
HcalID
Returns
A TVector3 with the X, Y and Z position of the center of the bar.
Definition at line 59 of file HcalGeometry.h.
{
     return stripPositionMap_.at(id);
   }
References stripPositionMap_.
Member Data Documentation
CONDITIONS_OBJECT_NAME
constexpr const char* ldmx::HcalGeometry::CONDITIONS_OBJECT_NAME {"HcalGeometry"} static constexpr
Conditions object: The name of the python configuration calling this class (Hcal/python/HcalGeometry.py) needs to match the CONDITIONS_OBJECT_NAME exactly.
Definition at line 42 of file HcalGeometry.h.
Referenced by hcal::test::HcalCheckPositionMap::analyze(), hcal::HcalDigiProducer::produce(), and hcal::HcalRecProducer::produce().
stripPositionMap_
std::map<ldmx::HcalID, TVector3> ldmx::HcalGeometry::stripPositionMap_ private
Map of the HcalID position of strip centers relative to world geometry. The map is not configurable and is calculated by buildStripPositionMap().
Definition at line 157 of file HcalGeometry.h.
Referenced by buildStripPositionMap(), and getStripCenterPosition().
The documentation for this class was generated from the following files:
DetDescr/include/DetDescr/HcalGeometry.h
DetDescr/src/DetDescr/HcalGeometry.cxx