LDMX Software: trigscint::TestBeamHitProducer Class Reference
trigscint::TestBeamHitProducer Class Reference
Organizes digis into TrigScintHits, based on linearized full event readout from test beam/test stand.
#include <TestBeamHitProducer.h>
Public Member Functions
TestBeamHitProducer (const std::string &name, framework::Process &process)
void configure (framework::config::Parameters &parameters) final override
void produce (framework::Event &event)
Public Member Functions inherited from framework::Producer
Producer (const std::string &name, Process &process)
virtual void produce (Event &event)=0
virtual void beforeNewRun (ldmx::RunHeader &header)
Public Member Functions inherited from framework::EventProcessor
EventProcessor (const std::string &name, Process &process)
virtual ~EventProcessor ()
virtual void configure (framework::config::Parameters &parameters)
virtual void onNewRun (const ldmx::RunHeader &runHeader)
virtual void onFileOpen (EventFile &eventFile)
virtual void onFileClose (EventFile &eventFile)
virtual void onProcessStart ()
virtual void onProcessEnd ()
template<class T >
const T & getCondition (const std::string &condition_name)
TDirectory * getHistoDirectory ()
void setStorageHint (framework::StorageControlHint hint)
void setStorageHint (framework::StorageControlHint hint, const std::string &purposeString)
int getLogFrequency () const
int getRunNumber () const
std::string getName () const
void createHistograms (const std::vector< framework::config::Parameters > &histos)
Private Attributes
bool verbose_ {false}
Set the local verbosity level.
std::string inputCol_
Name of the input collection containing the event readout samples.
std::string inputPassName_
std::string outputCollection_
std::vector< double > gain_
SiPM gain, per channel (all initialized to 2e6 in default config)
std::vector< double > peds_
channel pedestals [fC]
std::vector< double > MIPresponse_
channel MIP response for intercalibration
int startSample_ {10}
start sample for pulse integration (not including any fiber offsets)
int pulseWidth_ {5}
Total number of samples used in pulse integration.
int pulseWidthLYSO_ {8}
Total number of samples used in pulse integration for LYSO (long decay, might need wider window)
int nInstrumentedChannels_ {12}
Number of instrumented channels in module.
bool doCleanHits_ {false}
boolean indicating whether we want to apply quality criteria in hit reconstruction
Additional Inherited Members
Static Public Member Functions inherited from framework::EventProcessor
static void declare (const std::string &classname, int classtype, EventProcessorMaker *)
Static Public Attributes inherited from framework::Producer
static const int CLASSTYPE {1}
Protected Member Functions inherited from framework::EventProcessor
void abortEvent ()
Protected Attributes inherited from framework::EventProcessor
HistogramHelper histograms_
Interface class for making and filling histograms.
NtupleManager & ntuple_ {NtupleManager::getInstance()}
Manager for any ntuples.
logging::logger theLog_
The logger for this EventProcessor.
Detailed Description
Organizes digis into TrigScintHits, based on linearized full event readout from test beam/test stand.
Definition at line 33 of file TestBeamHitProducer.h.
Constructor & Destructor Documentation
TestBeamHitProducer()
trigscint::TestBeamHitProducer::TestBeamHitProducer (const std::string & name, framework::Process & process)
Definition at line 11 of file TestBeamHitProducer.cxx.
    : Producer(name, process) {}
~TestBeamHitProducer()
trigscint::TestBeamHitProducer::~TestBeamHitProducer ()
Definition at line 14 of file TestBeamHitProducer.cxx.
{}
Member Function Documentation
configure()
void trigscint::TestBeamHitProducer::configure (framework::config::Parameters & parameters) final override virtual
Callback for the processor to configure itself from the given set of parameters.
Parameters
parameters ParameterSet for configuration.
Reimplemented from framework::EventProcessor.
Definition at line 16 of file TestBeamHitProducer.cxx.
{
    inputCol_  = parameters.getParameter< std::string >("inputCollection");
    outputCollection_  = parameters.getParameter< std::string >("outputCollection");
    inputPassName_  = parameters.getParameter< std::string >("inputPassName");
    MIPresponse_  = parameters.getParameter< std::vector<double> >("MIPresponse");
    peds_  = parameters.getParameter< std::vector<double> >("pedestals");
    gain_  = parameters.getParameter< std::vector<double> >("gain");  //to do: vector
    startSample_  = parameters.getParameter< int >("startSample");
    pulseWidth_  = parameters.getParameter< int >("pulseWidth");
    pulseWidthLYSO_  = parameters.getParameter< int >("pulseWidthLYSO");
    nInstrumentedChannels_  = parameters.getParameter< int >("nInstrumentedChannels");
    doCleanHits_  = parameters.getParameter< bool >("doCleanHits");
    std::cout << " [ TestBeamHitProducer ] In configure(), got parameters "
          << "\n\t inputCollection = " << inputCol_
          << "\n\t inputPassName = " << inputPassName_
          << "\n\t outputCollection = " << outputCollection_
          << "\n\t startSample = " << startSample_
          << "\n\t pulseWidth = " << pulseWidth_
          << "\n\t pulseWidthLYSO = " << pulseWidthLYSO_
              << "\n\t gain[0] = " << gain_[0]
          << "\n\t nInstrumentedChannels = " << nInstrumentedChannels_
          << "\n\t doCleanHits = " << doCleanHits_
          << "\n\t pedestals[0] = " << peds_[0]
          << "\n\t MIPresponse[0] = " << MIPresponse_[0]
          << "\t." << std::endl;
    return;
  }
References framework::config::Parameters::getParameter().
produce()
void trigscint::TestBeamHitProducer::produce (framework::Event & event) virtual
Process the event and put new data products into it.
Parameters
event The Event to process.
Implements framework::Producer.
Definition at line 47 of file TestBeamHitProducer.cxx.
{
    /*
      hit producer.
      sum up all charge within a certain time window. could work two ways:
          - find a time sample above a threshold or where TDC is 0-50 (0-2)
               * this could allow for finding several pulses per event, just keep sliding along in time
               -- in that case, record nPulses, startsample, pulsewidth for each hit
          - use a fixed start sample, and keep summing from there until nSamples is reached or all time samples used
      specifics:
          - each channel has its own pedestal to subtract. also try using the first 5 samples to establish a threshold in the event. store both
          - store hit Q and hit PE conversion
          - for now use the same reconstruction paradigm for LYSO and plastic. two notes though
            1. LYSO pulse looks wider, and might need wider window. plastic is fine with 5. start by 8 for LYSO (even if for large pulses, sometimes 10 seem to be needed). could probe this by correlating plastic and LYSO, and checking if at some amplitude (in plastic), we start cutting off charge in LYSO
            2. there is a time offset between fibers. need to have a parameter fiber2offset to use for elecID >= 8
            -- added this as a variable in EventReadout, along with fiber number. so this class doesn't need any detailed knowledge
      variables to write out:
          - start sample
          - pulse width
          - n samples above threshold
          - nPulses
          - early pedestal (from first 5)
          - assumed/average channel pedestal
          - total Q
          - ped subtracted total Q
          - PE value
          - max amplitude in pulse
          - store material assumption? isLYSO?
     */
    float mevPerMip = 0.3;
    float pePerMip = 100;
    const auto channels{event.getCollection<trigscint::EventReadout >(inputCol_, inputPassName_)};
    int evNb = event.getEventNumber();
    int nChan = channels.size();
    std::vector<trigscint::TestBeamHit> hits;
    for (auto chan : channels) {
      trigscint::TestBeamHit hit;
      int bar = chan.getChanID();
      if (bar >= nInstrumentedChannels_) //don't run hit reconstruction on junk signal
        continue;
      int width=pulseWidth_;
      if (bar %2 == 0) { //LYSO channel: allow for wider pulses
        width=pulseWidthLYSO_; // avoid hardwiring
      }
      hit.setPulseWidth(width);
      hit.setStartSample(startSample_);
      float ped = peds_.at(bar); //chan.getPedestal() ;
      float earlyPed = chan.getEarlyPedestal();
      hit.setPedestal(ped);
      hit.setEarlyPedestal(earlyPed);
      int isClean=0; //false;
      float threshold =fabs(ped); // 2*fabs(peds_[ bar ]); // or sth
      if (doCleanHits_)
        threshold = 7*fabs(ped); // stricter cut
      int startT = startSample_ + chan.getTimeOffset();
      float maxQ = -999.;
      int nSampAbovePed = 0;
      int nSampAboveThr = 0;
      float totSubtrQ = 0;
      std::vector<float> q = chan.getQ();
      // go to the start sample defined for this channel.
      for (int iT = startT; iT < q.size() ; iT++) {
        ldmx_log(debug) << "in event " << evNb << "; channel " << bar << ", got charge[" << iT << "] = " << q.at(iT);
        // for the defined number of samples, subtract pedestal. if > 0, increment sample counter.
        float subQ=q.at(iT)-ped; //this might be addition, if ped is negative. should see this as channel dependence in nSampAbove
        // once beyond nSamples, want to see how long positive threshold subtracted tail is --> increment sample counter in any case.
        if (subQ > 0)
          nSampAbovePed++;
        if (subQ > threshold)
          nSampAboveThr++;
        if (iT - startT < width ) { //we're in the pulse integration window
          if ( subQ > maxQ )  // keep track of max Q. this is the pulse amplitude
            maxQ = subQ; //q.at(iT);
          if (subQ > 0)
            totSubtrQ+=subQ;        // add positive subtracted Q to total pulse charge.
        }
        else if (subQ < 0 || q.at(iT) < 0 )   // if after the full pulse width, subQ < pedestal, break. special case to break at q=0 for cases where ped < 0
          break;
        //done
      }// over time samples
      // first check that hit passes any quality cuts
      uint flag = chan.getQualityFlag();
      if (doCleanHits_) {
        //      int isLongPulse=(nSampAboveThr < 2 || nSampAboveThr > width + 2);
        int isLongPulse=( nSampAboveThr > width );  //the short ones we'll have to single out otherwise (like spike flag or low Q) or live with
        flag += 4*isLongPulse;
          if ( maxQ > 2e3 && nSampAboveThr < 3 && flag%2==0 ) //this was not flagged as a spike but is eerily narrow and with highQ; flag it as a spike.
            flag +=1;
        if ( flag == 0 )
            isClean=1;
      }
      float PE=totSubtrQ*6250./gain_[bar];
      if (PE > 20 ) // dont't want to intercalibrate the shot noise
        PE*=MIPresponse_[bar];
      // set pulse properties like PE and amplitude
      hit.setSampAbovePed(nSampAbovePed);
      hit.setSampAboveThr(nSampAboveThr);
      hit.setQ(totSubtrQ);
      hit.setAmplitude(maxQ);
      hit.setPE( PE );
      hit.setHitQuality( isClean );
      hit.setQualityFlag( flag );
      // set bar id. set moduleNB = 0
      hit.setBarID( bar );
      hit.setModuleID( 0 );  // test beam
      //the rest are a little ill-defined for now (PE-energy conversion not known/different between LYSO and plastic)
      hit.setTime(-999);//maybe?
      hit.setBeamEfrac(-1.);
      hit.setEnergy( hit.getPE()*mevPerMip/pePerMip );
      //add hit
      hits.push_back(hit);
    }// over channels
    // at end of event, write the collection of trigger scintillator hits.
  event.add(outputCollection_, hits);
    return;
  }
References ldmx::TrigScintHit::getPE(), ldmx::CalorimeterHit::setAmplitude(), ldmx::TrigScintHit::setBarID(), ldmx::TrigScintHit::setBeamEfrac(), trigscint::TestBeamHit::setEarlyPedestal(), ldmx::CalorimeterHit::setEnergy(), trigscint::TestBeamHit::setHitQuality(), ldmx::TrigScintHit::setModuleID(), ldmx::TrigScintHit::setPE(), trigscint::TestBeamHit::setPedestal(), trigscint::TestBeamHit::setPulseWidth(), trigscint::TestBeamHit::setQ(), trigscint::TestBeamHit::setQualityFlag(), trigscint::TestBeamHit::setSampAbovePed(), trigscint::TestBeamHit::setSampAboveThr(), trigscint::TestBeamHit::setStartSample(), and ldmx::CalorimeterHit::setTime().
Member Data Documentation
doCleanHits_
bool trigscint::TestBeamHitProducer::doCleanHits_ {false} private
boolean indicating whether we want to apply quality criteria in hit reconstruction
Definition at line 86 of file TestBeamHitProducer.h.
gain_
std::vector<double> trigscint::TestBeamHitProducer::gain_ private
SiPM gain, per channel (all initialized to 2e6 in default config)
Definition at line 65 of file TestBeamHitProducer.h.
inputCol_
std::string trigscint::TestBeamHitProducer::inputCol_ private
Name of the input collection containing the event readout samples.
Definition at line 54 of file TestBeamHitProducer.h.
inputPassName_
std::string trigscint::TestBeamHitProducer::inputPassName_ private
Name of the pass that the input collection is on (empty string means take any pass)
Definition at line 58 of file TestBeamHitProducer.h.
MIPresponse_
std::vector<double> trigscint::TestBeamHitProducer::MIPresponse_ private
channel MIP response for intercalibration
Definition at line 71 of file TestBeamHitProducer.h.
nInstrumentedChannels_
int trigscint::TestBeamHitProducer::nInstrumentedChannels_ {12} private
Number of instrumented channels in module.
Definition at line 83 of file TestBeamHitProducer.h.
outputCollection_
std::string trigscint::TestBeamHitProducer::outputCollection_ private
Name of the output collection that will be used to stored the trigger scintillator hits
Definition at line 62 of file TestBeamHitProducer.h.
peds_
std::vector<double> trigscint::TestBeamHitProducer::peds_ private
channel pedestals [fC]
Definition at line 68 of file TestBeamHitProducer.h.
pulseWidth_
int trigscint::TestBeamHitProducer::pulseWidth_ {5} private
Total number of samples used in pulse integration.
Definition at line 77 of file TestBeamHitProducer.h.
pulseWidthLYSO_
int trigscint::TestBeamHitProducer::pulseWidthLYSO_ {8} private
Total number of samples used in pulse integration for LYSO (long decay, might need wider window)
Definition at line 80 of file TestBeamHitProducer.h.
startSample_
int trigscint::TestBeamHitProducer::startSample_ {10} private
start sample for pulse integration (not including any fiber offsets)
Definition at line 74 of file TestBeamHitProducer.h.
verbose_
bool trigscint::TestBeamHitProducer::verbose_ {false} private
Set the local verbosity level.
Definition at line 51 of file TestBeamHitProducer.h.
The documentation for this class was generated from the following files:
TrigScint/include/TrigScint/TestBeamHitProducer.h
TrigScint/src/TrigScint/TestBeamHitProducer.cxx