LDMX Software: ldmx::FindableTrackProcessor Class Reference
ldmx::FindableTrackProcessor Class Reference
Public Member Functions
FindableTrackProcessor (const std::string &name, Process &process)
~FindableTrackProcessor ()
void configure (Parameters &parameters) final override
void produce (Event &event)
Public Member Functions inherited from ldmx::Producer
Producer (const std::string &name, Process &process)
Public Member Functions inherited from ldmx::EventProcessor
EventProcessor (const std::string &name, Process &process)
virtual ~EventProcessor ()
virtual void onNewRun (const RunHeader &runHeader)
virtual void onFileOpen (EventFile &eventFile)
virtual void onFileClose (EventFile &eventFile)
virtual void onProcessStart ()
virtual void onProcessEnd ()
template<class T >
const T & getCondition (const std::string &condition_name)
TDirectory * getHistoDirectory ()
void setStorageHint (ldmx::StorageControlHint hint)
void setStorageHint (ldmx::StorageControlHint hint, const std::string &purposeString)
int getLogFrequency () const
int getRunNumber () const
void createHistograms (const std::vector< Parameters > &histos)
Private Member Functions
void createHitMap (const std::vector< SiStripHit > &siStripHits)
void isFindable (FindableTrackResult &result, std::vector< int > hitCount)
Private Attributes
std::map< int, std::vector< int > > hitMap_
Additional Inherited Members
Static Public Member Functions inherited from ldmx::EventProcessor
static void declare (const std::string &classname, int classtype, EventProcessorMaker *)
Static Public Attributes inherited from ldmx::Producer
static const int CLASSTYPE {1}
Protected Member Functions inherited from ldmx::EventProcessor
void abortEvent ()
Protected Attributes inherited from ldmx::EventProcessor
HistogramHelper histograms_
Interface class for making and filling histograms.
NtupleManager & ntuple_ {NtupleManager::getInstance()}
Manager for any ntuples.
logging::logger theLog_
The logger for this EventProcessor.
Detailed Description
Definition at line 20 of file FindableTrackProcessor.h.
Constructor & Destructor Documentation
FindableTrackProcessor()
ldmx::FindableTrackProcessor::FindableTrackProcessor (const std::string & name, Process & process)
Constructor
Definition at line 12 of file FindableTrackProcessor.cxx.
                                                                                           :
             Producer(name, process) { }
~FindableTrackProcessor()
ldmx::FindableTrackProcessor::~FindableTrackProcessor ()
Destructor
Definition at line 15 of file FindableTrackProcessor.cxx.
 { }
Member Function Documentation
configure()
void ldmx::FindableTrackProcessor::configure (Parameters & parameters) final override virtual
Configure the processor using the given user specified parameters.
Parameters
parameters Set of parameters used to configure this processor.
Reimplemented from ldmx::EventProcessor.
Definition at line 17 of file FindableTrackProcessor.cxx.
 { }
createHitMap()
void ldmx::FindableTrackProcessor::createHitMap (const std::vector< SiStripHit > & siStripHits) private
Create a hit map which associates a charged particle to it's hits in the recoil tracker.
Parameters
recoilSimHit collection of simulated recoil tracker hits.
Definition at line 60 of file FindableTrackProcessor.cxx.
{
         // Clear the hit map to remove any previous relations
         hitMap_.clear();
         // Loop over all recoil tracker sim hits and check which layers, if any,
         // the sim particle deposited energy in.
         std::vector<int> recoilHitCount(10, 0);
         for ( const SiStripHit &siStripHit : siStripHits ) {
             // Get the SimTrackerHit associated with this strip hit
             const SimTrackerHit simTrackerHit = siStripHit.getSimTrackerHits().at(0);
             // Get the MC particle associated with this hit
             int simParticleTrackID = simTrackerHit.getTrackID();
             // If the particle ins't in the hit map, add it.
             if (hitMap_.count(simParticleTrackID) == 0) {
                 hitMap_[simParticleTrackID] = {0, 0, 0, 0, 0, 0, 0, 0, 0, 0};
             }
             // Increment the hit count for the layer
             hitMap_[simParticleTrackID][simTrackerHit.getLayerID() - 1]++;
         }
     }
References ldmx::SimTrackerHit::getLayerID(), ldmx::SimTrackerHit::getTrackID(), and hitMap_.
Referenced by produce().
isFindable()
void ldmx::FindableTrackProcessor::isFindable (FindableTrackResult & result, std::vector< int > hitCount) private
Given a set of hits, check if a sim particle is expected to fall within the acceptance of the recoil tracker.
Parameters
result The object used to encapsulate the results.
hitCount Vector indicating whether the nth layer of the recoil tracker has a hit.
Definition at line 86 of file FindableTrackProcessor.cxx.
{
         /*std::cout << "[ FindableTrackProcessor ]: Hit Vec [ ";
         for (auto index : hitCount) {
             std::cout << index << ", ";
         }
         std::cout << " ]" << std::endl;*/
         // Count how many 3D stereo hits are created by this particle
         std::vector<int> hit3dVec{0, 0, 0, 0};
         int hit3dCount{0};
         for (int layerN = 0; layerN  < 8; layerN += 2) {
             if (hitCount[layerN]*hitCount[layerN+1] != 0) {
                 hit3dCount++;
                 hit3dVec[layerN/2]++;
             }
         }
         /*std::cout << "[ FindableTrackProcessor ]: "
                   << "Total 3D Hits: " << hit3dCount << std::endl;*/
         // A track is considered findable if
         // 1) The first four stereo layers are hit
         // 2) Three of the first four layers are hit and an axial layer is hit
         // 3) Two of the first four layers are hit and both axial layers are hit
         bool trackFound{false};
         if (hit3dCount == 4) {
             result.setResult(FindableTrackResult::STRATEGY_4S, true);
             trackFound = true;
             /*std::cout << "[ FindableTrackProcessor ]: "
                       << "Can be found using 4S strategy." << std::endl;*/
         }
         if ((hit3dVec[0]*hit3dVec[1]*hit3dVec[2] > 0) && (hitCount[8] > 0 || hitCount[9] > 0)) {
             result.setResult(FindableTrackResult::STRATEGY_3S1A, true);
             trackFound = true;
             /*std::cout << "[ findabletrackprocessor ]: "
                       << "can be found using 3s1a strategy." << std::endl;*/
         }
         if (hit3dVec[0]*hit3dVec[1] > 0 && (hitCount[8] > 0 && hitCount[9] > 0)) {
             result.setResult(FindableTrackResult::STRATEGY_2S2A, true);
             trackFound = true;
             /*std::cout << "[ findabletrackprocessor ]: "
                       << "can be found using 2s2a strategy." << std::endl;*/
         }
         if (hitCount[8] > 0 && hitCount[9] > 0) {
             result.setResult(FindableTrackResult::STRATEGY_2A, true);
             trackFound = true;
             /*std::cout << "[ findabletrackprocessor ]: "
                       << "can be found using 2a strategy." << std::endl;*/
         }
         if (hit3dVec[0]*hit3dVec[1] > 0) {
             result.setResult(FindableTrackResult::STRATEGY_2S, true);
             trackFound = true;
             /*std::cout << "[ findabletrackprocessor ]: "
                       << "can be found using 2s strategy." << std::endl;*/
         }
         if (hit3dVec[0]*hit3dVec[1]*hit3dVec[2] > 0) {
             result.setResult(FindableTrackResult::STRATEGY_3S, true);
             trackFound = true;
             /*std::cout << "[ findabletrackprocessor ]: "
                       << "can be found using 3s strategy." << std::endl;*/
         }
         if (!trackFound) {
             result.setResult(FindableTrackResult::STRATEGY_NONE, false);
         }
     }
References ldmx::FindableTrackResult::setResult().
Referenced by produce().
produce()
void ldmx::FindableTrackProcessor::produce (Event & event) virtual
Run the processor and create a collection of results which indicate if a charge particle can be found by the recoil tracker.
Parameters
event The event to process.
Implements ldmx::Producer.
Definition at line 19 of file FindableTrackProcessor.cxx.
{
         // Get the collection of sim particles from the event
         const std::map<int,SimParticle> simParticles = event.getMap<int,SimParticle>("SimParticles");
         if (simParticles.size() == 0) return;
         // Get the collection of Recoil sim hits from the event
         const std::vector<SiStripHit> siStripHits = event.getCollection<SiStripHit>("SiStripHits");
         // Create the hit map
         this->createHitMap(siStripHits);
         // Loop through all sim particles and check which are findable
         int resultCount = 0;
         std::vector<FindableTrackResult> findableTrackResults;
         for (const auto &keyVal : simParticles ) {
             const SimParticle *simParticle = &(keyVal.second);
             // If the sim particle is neutral, skip it.
             if (abs(simParticle->getCharge()) != 1) continue;
             // Check if the track is findable
             if (hitMap_.count(keyVal.first) == 1) {
                 // Create a result instance
                 findableTrackResults.emplace_back();
                 // Set the sim particle associated with the result
                 findableTrackResults.back().setParticleTrackID(keyVal.first);
                 // Check if the track is findable
                 this->isFindable( findableTrackResults.back(), hitMap_[keyVal.first]);
                 resultCount++;
             }
         }
         //Add the result to the collection
         event.add( "FindableTracks", findableTrackResults );
     }
References createHitMap(), ldmx::SimParticle::getCharge(), hitMap_, and isFindable().
Member Data Documentation
hitMap_
std::map<int, std::vector<int> > ldmx::FindableTrackProcessor::hitMap_ private
Map between a sim particle and it's hit array.
Definition at line 66 of file FindableTrackProcessor.h.
Referenced by createHitMap(), and produce().
The documentation for this class was generated from the following files:
EventProc/include/EventProc/FindableTrackProcessor.h
EventProc/src/FindableTrackProcessor.cxx