LDMX Software: ldmx::HcalElectronicsID Class Reference
ldmx::HcalElectronicsID Class Reference
Identifies a location in the Hcal readout chain.
#include <HcalElectronicsID.h>
Public Types
typedef PackedIndex< 38, 48, 97 > Index
Public Types inherited from ldmx::DetectorID
typedef uint32_t RawValue
Public Member Functions
HcalElectronicsID ()
HcalElectronicsID (RawValue rawid)
HcalElectronicsID (const DetectorID id)
HcalElectronicsID (unsigned int fiber, unsigned int elink, unsigned int channel)
int fiber () const
int elink () const
int channel () const
unsigned int index () const
Public Member Functions inherited from ldmx::DetectorID
DetectorID ()
Class constructor for a null DetectorID.
DetectorID (RawValue rawid)
Class constructor from a raw 32-bit integer.
DetectorID (SubdetectorIDType sdtype, RawValue raw_subpayload)
bool null () const
SubdetectorIDType subdet () const
RawValue raw () const
void setRawValue (RawValue rawValue)
bool operator< (const DetectorID &id) const
bool operator== (const DetectorID &id) const
bool operator!= (const DetectorID &id) const
Static Public Member Functions
static HcalElectronicsID idFromIndex (unsigned int index)
Static Public Attributes
static const RawValue INDEX_MASK {0xFFFFFF}
static const unsigned int MAX_INDEX {38*48*200}
Static Public Attributes inherited from ldmx::DetectorID
static const RawValue SUBDETECTORID_MASK {0x3F}
static const RawValue SUBDETECTORID_SHIFT {26}
static const RawValue SUBDETECTOR_PAYLOAD_MASK {0x3FFFFFF}
Additional Inherited Members
Protected Attributes inherited from ldmx::DetectorID
RawValue id_
The raw, packed value of the ID.
Detailed Description
Identifies a location in the Hcal readout chain.
– fiber : optical fiber number (backend number), range assumed O(0-96) – elink : electronic link number, range assumed O(0-47) – channel : channel-on-elink, range O(0-37)
For transient use only i.e. we use this ID to help translate the digitized data coming off the detector into spatially-important HcalDigiIDs.
TODO update the ranges in the packed index template. These were originally copied from the EcalElectronicsID implementation and may not align with the Hcal readout design.
Definition at line 26 of file HcalElectronicsID.h.
Member Typedef Documentation
Index
typedef PackedIndex<38,48,97> ldmx::HcalElectronicsID::Index
Definition at line 31 of file HcalElectronicsID.h.
Constructor & Destructor Documentation
HcalElectronicsID() [1/4]
ldmx::HcalElectronicsID::HcalElectronicsID () inline
Empty HCAL id (but not null!)
Definition at line 38 of file HcalElectronicsID.h.
: DetectorID(EID_HCAL, 0) {}
HcalElectronicsID() [2/4]
ldmx::HcalElectronicsID::HcalElectronicsID (RawValue rawid) inline
Create from raw number
Definition at line 43 of file HcalElectronicsID.h.
                                    : DetectorID(rawid) {
    SUBDETECTORID_TEST("HcalElectronicsID", EID_HCAL);
  }
HcalElectronicsID() [3/4]
ldmx::HcalElectronicsID::HcalElectronicsID (const DetectorID id) inline
Create from a DetectorID, but check
Definition at line 50 of file HcalElectronicsID.h.
                                         : DetectorID(id) {
    SUBDETECTORID_TEST("HcalElectronicsID", EID_HCAL);
  }
HcalElectronicsID() [4/4]
ldmx::HcalElectronicsID::HcalElectronicsID (unsigned int fiber, unsigned int elink, unsigned int channel) inline
Create from pieces
Definition at line 57 of file HcalElectronicsID.h.
      : DetectorID(EID_HCAL, 0) {
    Index index(channel,elink,fiber);
    id_ |= index.value();
  }
References channel(), elink(), fiber(), ldmx::DetectorID::id_, and index().
Member Function Documentation
channel()
int ldmx::HcalElectronicsID::channel () const inline
Get the value of the fiber from the ID.
Returns
The value of the fiber field.
Definition at line 91 of file HcalElectronicsID.h.
{ return Index(id_&INDEX_MASK).field0(); }
References ldmx::PackedIndex< m0, m1, m2 >::field0(), and ldmx::DetectorID::id_.
Referenced by HcalElectronicsID().
elink()
int ldmx::HcalElectronicsID::elink () const inline
Get the value of the fiber from the ID.
Returns
The value of the fiber field.
Definition at line 86 of file HcalElectronicsID.h.
{ return Index(id_&INDEX_MASK).field1(); }
References ldmx::PackedIndex< m0, m1, m2 >::field1(), and ldmx::DetectorID::id_.
Referenced by HcalElectronicsID().
fiber()
int ldmx::HcalElectronicsID::fiber () const inline
Get the value of the fiber from the ID.
Returns
The value of the fiber field.
Definition at line 81 of file HcalElectronicsID.h.
{ return Index(id_&INDEX_MASK).field2(); }
References ldmx::PackedIndex< m0, m1, m2 >::field2(), and ldmx::DetectorID::id_.
Referenced by HcalElectronicsID().
idFromIndex()
static HcalElectronicsID ldmx::HcalElectronicsID::idFromIndex (unsigned int index) inline static
Construct an electronics id from an index
This looks ugly (and it is) because we already have a constructor that uses the unsigned int type. This means we need a different static method for translating something we know to be an EID index rather than a full DetID raw value.
Definition at line 71 of file HcalElectronicsID.h.
{
    HcalElectronicsID eid;
    eid.id_|=index;
    return eid;
  }
References ldmx::DetectorID::id_, and index().
index()
unsigned int ldmx::HcalElectronicsID::index () const inline
Get the compact index value
Definition at line 96 of file HcalElectronicsID.h.
{ return id_&INDEX_MASK; }
References ldmx::DetectorID::id_.
Referenced by HcalElectronicsID(), idFromIndex(), and hcal::HcalRawDecoder::read().
Member Data Documentation
INDEX_MASK
const RawValue ldmx::HcalElectronicsID::INDEX_MASK {0xFFFFFF} static
Definition at line 29 of file HcalElectronicsID.h.
MAX_INDEX
const unsigned int ldmx::HcalElectronicsID::MAX_INDEX {38*48*200} static
Definition at line 33 of file HcalElectronicsID.h.
The documentation for this class was generated from the following file:
DetDescr/include/DetDescr/HcalElectronicsID.h