LDMX Software: ldmx::HCalDQM Class Reference
ldmx::HCalDQM Class Reference
Public Member Functions
HCalDQM (const std::string &name, Process &process)
~HCalDQM ()
void configure (Parameters &parameters) final override
void analyze (const Event &event)
void onProcessStart ()
Public Member Functions inherited from ldmx::Analyzer
Analyzer (const std::string &name, Process &process)
Public Member Functions inherited from ldmx::EventProcessor
EventProcessor (const std::string &name, Process &process)
virtual ~EventProcessor ()
virtual void onNewRun (const RunHeader &runHeader)
virtual void onFileOpen (EventFile &eventFile)
virtual void onFileClose (EventFile &eventFile)
virtual void onProcessEnd ()
TDirectory * getHistoDirectory ()
void setStorageHint (ldmx::StorageControlHint hint)
void setStorageHint (ldmx::StorageControlHint hint, const std::string &purposeString)
Private Attributes
HistogramPool * histograms_ {nullptr}
float maxPEThreshold_ {5}
Additional Inherited Members
Static Public Member Functions inherited from ldmx::EventProcessor
static void declare (const std::string &classname, int classtype, EventProcessorMaker *)
Static Public Attributes inherited from ldmx::Analyzer
static const int CLASSTYPE {2}
Protected Member Functions inherited from ldmx::EventProcessor
void abortEvent ()
Protected Attributes inherited from ldmx::EventProcessor
Process & process_
Detailed Description
Definition at line 35 of file HCalDQM.h.
Constructor & Destructor Documentation
HCalDQM()
ldmx::HCalDQM::HCalDQM (const std::string & name, Process & process)
Constructor
Definition at line 11 of file HCalDQM.cxx.
                                                             :
         Analyzer(name, process) { }
~HCalDQM()
ldmx::HCalDQM::~HCalDQM ()
Destructor
Definition at line 14 of file HCalDQM.cxx.
 {}
Member Function Documentation
analyze()
void ldmx::HCalDQM::analyze (const Event & event) virtual
Process the event and make histograms ro summaries.
Parameters
event The event to analyze.
Implements ldmx::Analyzer.
Definition at line 43 of file HCalDQM.cxx.
{
         // Check if the collection of digitized HCal hits exist. If it doesn't
         // don't continue processing.
         if (!event.exists("hcalDigis")) return;
         // Get the collection of HCalDQM digitized hits if the exists
         const std::vector<HcalHit> hcalHits = event.getCollection<HcalHit>("hcalDigis");
         // Get the total hit count
         int hitCount = hcalHits.size();
         histograms_->get("n_hits")->Fill(hitCount);
         double totalPE{0};
         // Loop through all HCal hits in the event
         // Get non-noise generated hits into new vector for sorting
         std::vector<const HcalHit *> filteredHits;
         for (const HcalHit &hit : hcalHits ) {
             histograms_->get("pe")->Fill(hit.getPE());
             histograms_->get("hit_time")->Fill(hit.getTime());
             totalPE += hit.getPE();
             if ( hit.getTime() > -999. ) { filteredHits.push_back( &hit ); }
         }
         histograms_->get("total_pe")->Fill(totalPE);
         // Sort the array by hit time
         std::sort (filteredHits.begin(), filteredHits.end(), [ ](const auto& lhs, const auto& rhs)
         {
             return lhs->getTime() < rhs->getTime();
         });
         //get first time and PE of hit over threshold
         double minTime{-1};
         double minTimePE{-1};
         for (const auto& hit : filteredHits) {
             if (hit->getPE() < maxPEThreshold_) continue;
             minTime = hit->getTime();
             minTimePE = hit->getPE();
             break;
         }
         histograms_->get("min_time_hit_above_thresh")->Fill(minTime);
         histograms_->get("min_time_hit_above_thresh:pe")->Fill(minTimePE, minTime);
         float maxPE{-1};
         float maxPETime{-1};
         bool passesHcalVeto{false};
         // Check if the HcalVeto result exists
         if (event.exists("HcalVeto")) {
             // Get the collection of HCalDQM digitized hits if the exists
             const HcalVetoResult hcalVeto = event.getObject<HcalVetoResult>("HcalVeto");
             HcalHit maxPEHit = hcalVeto.getMaxPEHit();
             // Get the max PE and it's time
             maxPE = maxPEHit.getPE();
             maxPETime = maxPEHit.getTime();
             histograms_->get("max_pe")->Fill(maxPE);
             histograms_->get("hit_time_max_pe")->Fill(maxPETime);
             histograms_->get("max_pe:time")->Fill(maxPE, maxPETime);
             histograms_->get("veto")->Fill(hcalVeto.passesVeto());
             if (hcalVeto.passesVeto()) {
                 histograms_->get("max_pe_hcal_veto")->Fill(maxPE);
                 histograms_->get("hit_time_max_pe_hcal_veto")->Fill(maxPETime);
                 histograms_->get("max_pe:time_hcal_veto")->Fill(maxPE, maxPETime);
                 histograms_->get("total_pe_hcal_veto")->Fill(totalPE);
                 histograms_->get("n_hits_hcal_veto")->Fill(hitCount);
                 passesHcalVeto = true;
             }
         }
     }
References ldmx::Event::exists(), ldmx::HistogramPool::get(), ldmx::HcalVetoResult::getMaxPEHit(), ldmx::HcalHit::getPE(), histograms_, maxPEThreshold_, and ldmx::HcalVetoResult::passesVeto().
configure()
void ldmx::HCalDQM::configure (Parameters & parameters) final override virtual
Configure the processor using the given user specified parameters.
Parameters
parameters Set of parameters used to configure this processor.
Reimplemented from ldmx::EventProcessor.
Definition at line 40 of file HCalDQM.cxx.
{
     }
onProcessStart()
void ldmx::HCalDQM::onProcessStart () virtual
Method executed before processing of events begins.
Reimplemented from ldmx::EventProcessor.
Definition at line 16 of file HCalDQM.cxx.
{
         // Get an instance of the histogram pool
         histograms_ = HistogramPool::getInstance();
         // Move into the HCal directory
         getHistoDirectory();
         histograms_->create<TH2F>("bdt_n_hits", "BDT discriminant", 200, 0, 1,
                                   "HCal hit multiplicity", 300, 0, 300);
         histograms_->create<TH2F>("max_pe:time",
                                   "Max Photoelectrons in an HCal Module", 1500, 0, 1500,
                                   "HCal max PE hit time (ns)", 1500, 0, 1500);
         histograms_->create<TH2F>("max_pe:time_hcal_veto",
                                   "Max Photoelectrons in an HCal Module", 1500, 0, 1500,
                                   "HCal max PE hit time (ns)", 1500, 0, 1500);
         histograms_->create<TH2F>("min_time_hit_above_thresh:pe",
                                   "Photoelectrons in an HCal Module", 1500, 0, 1500,
                                   "Earliest time of HCal hit above threshold (ns)", 1600, -100, 1500);
     }
References ldmx::HistogramPool::create(), ldmx::EventProcessor::getHistoDirectory(), and histograms_.
Member Data Documentation
histograms_
HistogramPool* ldmx::HCalDQM::histograms_ {nullptr} private
Singleton used to access histograms.
Definition at line 65 of file HCalDQM.h.
Referenced by analyze(), and onProcessStart().
maxPEThreshold_
float ldmx::HCalDQM::maxPEThreshold_ {5} private
The maximum PE threshold used for the veto.
Definition at line 68 of file HCalDQM.h.
Referenced by analyze().
The documentation for this class was generated from the following files:
DQM/include/DQM/HCalDQM.h
DQM/src/HCalDQM.cxx