LDMX Software: g4db::ElementXsecCache Class Reference
g4db::ElementXsecCache Class Reference
#include <ElementXsecCache.h>
Public Member Functions
ElementXsecCache ()=default
ElementXsecCache (std::shared_ptr< PrototypeModel > model)
G4double get (G4double energy, G4double A, G4double Z)
void stream (std::ostream &o) const
Private Types
typedef unsigned long int key_t
The type for the key we use in the cache.
Private Member Functions
key_t computeKey (G4double energy, G4double A, G4double Z) const
Private Attributes
std::map< key_t, G4double > the_cache_
the actual map from cache keys to calculated cross sections
std::shared_ptr< PrototypeModel > model_
shared pointer to the model for calculating cross sections
Static Private Attributes
static const key_t MAX_A {1000}
The maximum value of A.
static const key_t MAX_E {1500000}
The maximum value for energy [MeV].
Friends
std::ostream & operator<< (std::ostream &o, const ElementXsecCache c)
Detailed Description
The cache of already computed cross sections
We make a specific class for the cache in order to keep the key encoding/decoding process in a central location.
Definition at line 17 of file ElementXsecCache.h.
Member Typedef Documentation
key_t
typedef unsigned long int g4db::ElementXsecCache::key_t private
The type for the key we use in the cache.
Definition at line 67 of file ElementXsecCache.h.
Constructor & Destructor Documentation
ElementXsecCache() [1/2]
g4db::ElementXsecCache::ElementXsecCache () default
Default constructor
Does nothing interesting, but no model for calculating cross section has been set.
ElementXsecCache() [2/2]
g4db::ElementXsecCache::ElementXsecCache (std::shared_ptr< PrototypeModel > model) inline
Constructor with a model to calculate the cross section.
Definition at line 30 of file ElementXsecCache.h.
      : model_{model} {}
Member Function Documentation
computeKey()
ElementXsecCache::key_t g4db::ElementXsecCache::computeKey (G4double energy, G4double A, G4double Z) const private
Compute a key for the cache map Generating a unique key after making the energy [MeV] an integer. The atomic mass (A) and charge (Z) are given by Geant4 as doubles as well, so I cast them to integers before computing the key.
This is what you would edit if you want a more/less find-grained cache of Xsecs. Right now, since the internal unit of energy in Geant4 is MeV, the cache is binned at the 1MeV scale.
Parameters
[in] energy Energy of incident lepton [MeV]
[in] A atomic mass of element [atomic mass units]
[in] Z atomic number of element [num protons]
Returns
unsigned integer cache key for these three inputs
Note
This implicitly converts the input double to a unsigned long int. Since the internal units for energy are MeV, this means the cache is binned at a 1 MeV level. The atomic inputs A and Z also undergo the implicit conversion; however, this is less of a worry since different elements are separated by at least one whole unit in A and Z.
Definition at line 33 of file ElementXsecCache.cxx.
{
  key_t energyKey = energy;
  key_t AKey = A;
  key_t ZKey = Z;
  return (ZKey * MAX_A + AKey) * MAX_E + energyKey;
}
References MAX_A, and MAX_E.
Referenced by get().
get()
G4double g4db::ElementXsecCache::get (G4double energy, G4double A, G4double Z)
Get the value of the cross section for the input variables and calculate the cross section if it wasn't calculated before.
Exceptions
std::runtime_error if no model is available for calculating cross sections
Parameters
[in] energy Energy of incident lepton [MeV]
[in] A atomic mass of element [atomic mass units]
[in] Z atomic number of element [num protons]
Returns
cross section corresponding to the input parameters (including units Geant4 style)
Definition at line 5 of file ElementXsecCache.cxx.
{
  key_t key = computeKey(energy, A, Z);
  if (the_cache_.find(key) == the_cache_.end()) {
    if (model_.get() == nullptr) {
      throw std::runtime_error(
                      "ElementXsecCache not given a model to calculate cross "
                      "sections with.");
    }
    the_cache_[key] = model_->ComputeCrossSectionPerAtom(energy, A, Z);
  }
  return the_cache_.at(key);
}
References computeKey(), model_, and the_cache_.
Referenced by G4DarkBremsstrahlung::GetMeanFreePath(), and main().
stream()
void g4db::ElementXsecCache::stream (std::ostream & o) const
Stream the entire table into the output stream.
Parameters
[in,out] o ostream to write to
Definition at line 18 of file ElementXsecCache.cxx.
{
  o << "A [au],Z [protons],Energy [MeV],Xsec [pb]\n"
    << std::setprecision(std::numeric_limits<double>::digits10 +
                         1);  // maximum precision
  for (auto const& cache_entry : the_cache_) {
    const key_t& key = cache_entry.first;
    const double& xsec = cache_entry.second;
    key_t E = key % MAX_E;
    key_t A = ((key - E) / MAX_E) % MAX_A;
    key_t Z = ((key - E) / MAX_E - A) / MAX_A;
    o << A << "," << Z << "," << E << "," << xsec / CLHEP::picobarn << "\n";
  }
  o << std::endl;
}
References MAX_A, MAX_E, and the_cache_.
Friends And Related Function Documentation
operator<<
std::ostream & operator<< (std::ostream & o, const ElementXsecCache c) friend
Overload the streaming operator for ease
Parameters
[in] o ostream to write to
[in] c cache to write out
Returns
modified ostream
Definition at line 60 of file ElementXsecCache.h.
{
    c.stream(o);
    return o;
  }
Member Data Documentation
MAX_A
const key_t g4db::ElementXsecCache::MAX_A {1000} static private
The maximum value of A.
Definition at line 70 of file ElementXsecCache.h.
Referenced by computeKey(), and stream().
MAX_E
const key_t g4db::ElementXsecCache::MAX_E {1500000} static private
The maximum value for energy [MeV].
Definition at line 73 of file ElementXsecCache.h.
Referenced by computeKey(), and stream().
model_
std::shared_ptr<PrototypeModel> g4db::ElementXsecCache::model_ private
shared pointer to the model for calculating cross sections
Definition at line 97 of file ElementXsecCache.h.
Referenced by get().
the_cache_
std::map<key_t, G4double> g4db::ElementXsecCache::the_cache_ private
the actual map from cache keys to calculated cross sections
Definition at line 94 of file ElementXsecCache.h.
Referenced by get(), and stream().
The documentation for this class was generated from the following files:
SimCore/G4DarkBreM/include/G4DarkBreM/ElementXsecCache.h
SimCore/G4DarkBreM/src/G4DarkBreM/ElementXsecCache.cxx