LDMX Software: biasing::TargetProcessFilter Class Reference
biasing::TargetProcessFilter Class Reference
Biases Geant4 to only process events where PN reaction occurred in the target.
#include <TargetProcessFilter.h>
Public Member Functions
TargetProcessFilter (const std::string &name, framework::config::Parameters &parameters)
~TargetProcessFilter ()
Destructor.
void stepping (const G4Step *step) final override
void EndOfEventAction (const G4Event *) final override
G4ClassificationOfNewTrack ClassifyNewTrack (const G4Track *aTrack, const G4ClassificationOfNewTrack &currentTrackClass) final override
std::vector< simcore::TYPE > getTypes () final override
Retrieve the type of actions this class defines.
Public Member Functions inherited from simcore::UserAction
UserAction (const std::string &name, framework::config::Parameters &parameters)
virtual ~UserAction ()
Destructor.
virtual void BeginOfEventAction (const G4Event *)
virtual void EndOfEventAction (const G4Event *)
virtual void BeginOfRunAction (const G4Run *)
virtual void EndOfRunAction (const G4Run *)
virtual void PreUserTrackingAction (const G4Track *)
virtual void PostUserTrackingAction (const G4Track *)
virtual void stepping (const G4Step *)
virtual G4ClassificationOfNewTrack ClassifyNewTrack (const G4Track *, const G4ClassificationOfNewTrack &cl)
virtual void NewStage ()
virtual void PrepareNewEvent ()
virtual std::vector< TYPE > getTypes ()=0
Private Attributes
G4Track * currentTrack_ {nullptr}
bool reactionOccurred_ {false}
std::string process_ {""}
The process to bias.
Additional Inherited Members
Public Types inherited from simcore::UserAction
using Factory = ::simcore::Factory< UserAction, std::shared_ptr< UserAction >, const std::string &, framework::config::Parameters & >
factory for user actions
Protected Member Functions inherited from simcore::UserAction
UserEventInformation * getEventInfo () const
const std::map< int, ldmx::SimParticle > & getCurrentParticleMap () const
Protected Attributes inherited from simcore::UserAction
std::string name_ {""}
Name of the UserAction.
framework::config::Parameters parameters_
The set of parameters used to configure this class.
Detailed Description
Biases Geant4 to only process events where PN reaction occurred in the target.
Definition at line 26 of file TargetProcessFilter.h.
Constructor & Destructor Documentation
TargetProcessFilter()
biasing::TargetProcessFilter::TargetProcessFilter (const std::string & name, framework::config::Parameters & parameters)
Class constructor.
Definition at line 25 of file TargetProcessFilter.cxx.
    : simcore::UserAction(name, parameters) {
  process_ = parameters.getParameter<std::string>("process");
}
References framework::config::Parameters::getParameter(), and process_.
~TargetProcessFilter()
biasing::TargetProcessFilter::~TargetProcessFilter ()
Destructor.
Definition at line 31 of file TargetProcessFilter.cxx.
{}
Member Function Documentation
ClassifyNewTrack()
G4ClassificationOfNewTrack biasing::TargetProcessFilter::ClassifyNewTrack (const G4Track * aTrack, const G4ClassificationOfNewTrack & currentTrackClass) final override virtual
Classify a new track which postpones track processing. Track processing resumes normally if a target PN interaction occurred.
Parameters
aTrack The Geant4 track.
currentTrackClass The current track classification.
Reimplemented from simcore::UserAction.
Definition at line 33 of file TargetProcessFilter.cxx.
{
  if (track == currentTrack_) {
    currentTrack_ = nullptr;
    // std::cout << "[ TargetBremFilter ]: Pushing track to waiting stack." <<
    // std::endl;
    return fWaiting;
  }
  // Use current classification by default so values from other plugins are not
  // overridden.
  G4ClassificationOfNewTrack classification = currentTrackClass;
  return classification;
}
References currentTrack_.
EndOfEventAction()
void biasing::TargetProcessFilter::EndOfEventAction (const G4Event *) final override virtual
End of event action.
Reimplemented from simcore::UserAction.
Definition at line 127 of file TargetProcessFilter.cxx.
{}
getTypes()
std::vector< simcore::TYPE > biasing::TargetProcessFilter::getTypes () inline final override virtual
Retrieve the type of actions this class defines.
Implements simcore::UserAction.
Definition at line 59 of file TargetProcessFilter.h.
{
    return {simcore::TYPE::EVENT, simcore::TYPE::STACKING,
            simcore::TYPE::STEPPING};
  }
stepping()
void biasing::TargetProcessFilter::stepping (const G4Step * step) final override virtual
Implementmthe stepping action which performs the target volume biasing.
Parameters
step The Geant4 step.
Check if the electron will be exiting the target
The 'recoil_PV' volume name is automatically constructed by Geant4's GDML parser and was found by inspecting the geometry using a visualization. This Physical Volume (PV) is associated with the recoil parent volume and so it will break if the recoil parent volume changes its name.
We also check for 'World_PV' because in later geometries, there is an air gap between the target region and the recoil tracker.
Reimplemented from simcore::UserAction.
Definition at line 49 of file TargetProcessFilter.cxx.
{
  // Get the track associated with this step.
  auto track{step->GetTrack()};
  // Get the track info and check if this track is a brem candidate
  auto trackInfo{simcore::UserTrackInformation::get(track)};
  if ((trackInfo != nullptr) && !trackInfo->isBremCandidate()) return;
  // Get the region the particle is currently in.  Continue processing
  // the particle only if it's in the calorimeter region.
  if (auto region{
          track->GetVolume()->GetLogicalVolume()->GetRegion()->GetName()};
      region.compareTo("target") != 0)
    return;
  // Get the particles daughters.
  auto secondaries{step->GetSecondary()};
  // If the brem photon doesn't undergo any reaction in the target, stop
  // processing the rest of the event if the particle is exiting the
  // target region.
  if (secondaries->size() == 0) {
    if (auto volume{track->GetNextVolume()->GetName()};
        volume.compareTo("recoil_PV") == 0 or
        volume.compareTo("World_PV") == 0) {
      if (secondaries->size() != 0) {
        if (getEventInfo()->bremCandidateCount() == 1) {
          track->SetTrackStatus(fKillTrackAndSecondaries);
          G4RunManager::GetRunManager()->AbortEvent();
          currentTrack_ = nullptr;
        } else {
          currentTrack_ = track;
          track->SetTrackStatus(fSuspend);
          getEventInfo()->decBremCandidateCount();
          trackInfo->tagBremCandidate(false);
        }
      }
      return;
    }
  } else {
    G4String processName =
        secondaries->at(0)->GetCreatorProcess()->GetProcessName();
    // Only record the process that is being biased
    if (!processName.contains(process_)) {
      if (getEventInfo()->bremCandidateCount() == 1) {
        track->SetTrackStatus(fKillTrackAndSecondaries);
        G4RunManager::GetRunManager()->AbortEvent();
        currentTrack_ = nullptr;
      } else {
        currentTrack_ = track;
        track->SetTrackStatus(fSuspend);
        getEventInfo()->decBremCandidateCount();
        trackInfo->tagBremCandidate(false);
      }
    }
    std::cout << "[ TargetProcessFilter ]: "
              << "Brem photon produced " << secondaries->size()
              << " particle via " << processName << " process." << std::endl;
    trackInfo->tagBremCandidate(false);
    trackInfo->tagPNGamma();
    getEventInfo()->decBremCandidateCount();
  }
}
References currentTrack_, simcore::UserEventInformation::decBremCandidateCount(), simcore::UserTrackInformation::get(), simcore::UserAction::getEventInfo(), and process_.
Member Data Documentation
currentTrack_
G4Track* biasing::TargetProcessFilter::currentTrack_ {nullptr} private
Pointer to the current track being processed.
Definition at line 66 of file TargetProcessFilter.h.
Referenced by ClassifyNewTrack(), and stepping().
process_
std::string biasing::TargetProcessFilter::process_ {""} private
The process to bias.
Definition at line 72 of file TargetProcessFilter.h.
Referenced by stepping(), and TargetProcessFilter().
reactionOccurred_
bool biasing::TargetProcessFilter::reactionOccurred_ {false} private
Flag indicating if the reaction of intereset occurred.
Definition at line 69 of file TargetProcessFilter.h.
The documentation for this class was generated from the following files:
Biasing/include/Biasing/TargetProcessFilter.h
Biasing/src/Biasing/TargetProcessFilter.cxx