LDMX Software: simcore::Simulator Class Reference
simcore::Simulator Class Reference
Producer that runs Geant4 simulation inside of ldmx-app.
#include <Simulator.h>
Public Member Functions
Simulator (const std::string &name, framework::Process &process)
~Simulator ()
void configure (framework::config::Parameters &parameters) final override
void beforeNewRun (ldmx::RunHeader &header) final override
void onNewRun (const ldmx::RunHeader &header) final override
virtual void produce (framework::Event &event) final override
void onFileOpen (framework::EventFile &eventFile) final override
void onFileClose (framework::EventFile &eventFile) final override
void onProcessStart () final override
void onProcessEnd () final override
Callback called once processing is complete.
Public Member Functions inherited from framework::Producer
Producer (const std::string &name, Process &process)
Public Member Functions inherited from framework::EventProcessor
EventProcessor (const std::string &name, Process &process)
virtual ~EventProcessor ()
template<class T >
const T & getCondition (const std::string &condition_name)
TDirectory * getHistoDirectory ()
void setStorageHint (framework::StorageControlHint hint)
void setStorageHint (framework::StorageControlHint hint, const std::string &purposeString)
int getLogFrequency () const
int getRunNumber () const
std::string getName () const
void createHistograms (const std::vector< framework::config::Parameters > &histos)
Private Member Functions
bool allowed (const std::string &command) const
void setSeeds (std::vector< int > seeds)
Private Attributes
std::unique_ptr< RunManager > runManager_
Manager controlling G4 simulation run.
G4UImanager * uiManager_ {nullptr}
User interface handle.
std::unique_ptr< simcore::persist::RootPersistencyManager > persistencyManager_
PersistencyManager.
std::unique_ptr< G4UIsession > sessionHandle_
Handle to the G4Session -> how to deal with G4cout and G4cerr.
int numEventsBegan_ {0}
Number of events started.
int numEventsCompleted_ {0}
Number of events completed.
ConditionsInterface conditionsIntf_
Conditions interface.
framework::config::Parameters parameters_
The parameters used to configure the simulation.
int verbosity_ {1}
Vebosity for the simulation.
Static Private Attributes
static const std::vector< std::string > invalidCommands_
Additional Inherited Members
Static Public Member Functions inherited from framework::EventProcessor
static void declare (const std::string &classname, int classtype, EventProcessorMaker *)
Static Public Attributes inherited from framework::Producer
static const int CLASSTYPE {1}
Protected Member Functions inherited from framework::EventProcessor
void abortEvent ()
Protected Attributes inherited from framework::EventProcessor
HistogramHelper histograms_
Interface class for making and filling histograms.
NtupleManager & ntuple_ {NtupleManager::getInstance()}
Manager for any ntuples.
logging::logger theLog_
The logger for this EventProcessor.
Detailed Description
Producer that runs Geant4 simulation inside of ldmx-app.
Most (if not all) of the heavy lifting is done in the classes in the Sim* modules. This producer is mainly focused on calling appropriate functions at the right time in the processing chain.
Definition at line 56 of file Simulator.h.
Constructor & Destructor Documentation
Simulator()
simcore::Simulator::Simulator (const std::string & name, framework::Process & process)
Constructor.
Blank Producer constructor Constructs object that are non-configurable.
Parameters
name Name for this instance of the class.
process The Process class assocaited with EventProcessor, provided by the Framework.
Definition at line 43 of file Simulator.cxx.
    : framework::Producer(name, process), conditionsIntf_(this) {
  // Get the ui manager from geant
  //      This pointer is handled by Geant4
  uiManager_ = G4UImanager::GetUIpointer();
}
References uiManager_.
~Simulator()
simcore::Simulator::~Simulator ()
Destructor.
Deletes hanging pointers
Definition at line 50 of file Simulator.cxx.
{}
Member Function Documentation
allowed()
bool simcore::Simulator::allowed (const std::string & command) const private
Check if the input command is allowed to be run.
Looks for sub-strings matching the ones listed as an invalid command. These invalid commands are mostly commands where control has been handed over to Simulator.
Definition at line 397 of file Simulator.cxx.
{
  for (const std::string& invalidSubstring : invalidCommands_) {
    if (command.find(invalidSubstring) != std::string::npos) {
      // found invalid substring in this command ==> NOT ALLOWED
      return false;
    }
  }
  // checked all invalid commands ==> ALLOWED
  return true;
}
References invalidCommands_.
Referenced by configure(), and onProcessStart().
beforeNewRun()
void simcore::Simulator::beforeNewRun (ldmx::RunHeader & header) final override virtual
Given a non-const reference to the new RunHeader, we can add parameters from the simulation here before the run starts.
Parameters
header of new run
Reimplemented from framework::Producer.
Definition at line 123 of file Simulator.cxx.
{
  // Get the detector header from the user detector construction
  DetectorConstruction* detector =
      static_cast<RunManager*>(RunManager::GetRunManager())
          ->getDetectorConstruction();
  if (!detector)
    EXCEPTION_RAISE("SimSetup", "Detector not constructed before run start.");
  header.setDetectorName(detector->getDetectorName());
  header.setDescription(parameters_.getParameter<std::string>("description"));
  header.setIntParameter("Save ECal Hit Contribs",
                         parameters_.getParameter<bool>("enableHitContribs"));
  header.setIntParameter("Compress ECal Hit Contribs",
                         parameters_.getParameter<bool>("compressHitContribs"));
  header.setIntParameter(
      "Included Scoring Planes",
      !parameters_.getParameter<std::string>("scoringPlanes").empty());
  header.setIntParameter(
      "Use Random Seed from Event Header",
      parameters_.getParameter<bool>("rootPrimaryGenUseSeed"));
  // lambda function for dumping 3-vectors into the run header
  auto threeVectorDump = [&header](const std::string& name,
                                   const std::vector<double>& vec) {
    header.setFloatParameter(name + " X", vec.at(0));
    header.setFloatParameter(name + " Y", vec.at(1));
    header.setFloatParameter(name + " Z", vec.at(2));
  };
  auto beamSpotSmear{
      parameters_.getParameter<std::vector<double>>("beamSpotSmear", {})};
  if (!beamSpotSmear.empty())
    threeVectorDump("Smear Beam Spot [mm]", beamSpotSmear);
  // lambda function for dumping vectors of strings to the run header
  auto stringVectorDump = [&header](const std::string& name,
                                    const std::vector<std::string>& vec) {
    int index = 0;
    for (auto const& val : vec) {
      header.setStringParameter(name + " " + std::to_string(++index), val);
    }
  };
  stringVectorDump("Pre Init Command",
                   parameters_.getParameter<std::vector<std::string>>(
                       "preInitCommands", {}));
  stringVectorDump("Post Init Command",
                   parameters_.getParameter<std::vector<std::string>>(
                       "postInitCommands", {}));
  auto bops{PluginFactory::getInstance().getBiasingOperators()};
  for (const XsecBiasingOperator* bop : bops) {
    bop->RecordConfig(header);
  }
  auto dark_brem{
      parameters_.getParameter<framework::config::Parameters>("dark_brem")};
  if (dark_brem.getParameter<bool>("enable")) {
    // the dark brem process is enabled, find it and then record its
    // configuration
    G4ProcessVector* electron_processes =
        G4Electron::Electron()->GetProcessManager()->GetProcessList();
    int n_electron_processes = electron_processes->size();
    for (int i_process = 0; i_process < n_electron_processes; i_process++) {
      G4VProcess* process = (*electron_processes)[i_process];
      if (process->GetProcessName().contains(
              darkbrem::G4eDarkBremsstrahlung::PROCESS_NAME)) {
        // reset process to wrapped process if it is biased
        if (dynamic_cast<G4BiasingProcessInterface*>(process))
          process = dynamic_cast<G4BiasingProcessInterface*>(process)
                        ->GetWrappedProcess();
        // record the process configuration to the run header
        dynamic_cast<darkbrem::G4eDarkBremsstrahlung*>(process)->RecordConfig(
            header);
        break;
      }  // this process is the dark brem process
    }    // loop through electron processes
  }      // dark brem has been enabled
  auto generators{
      parameters_.getParameter<std::vector<framework::config::Parameters>>(
          "generators")};
  int counter = 0;
  for (auto const& gen : generators) {
    std::string genID = "Gen " + std::to_string(++counter);
    auto className{gen.getParameter<std::string>("class_name")};
    header.setStringParameter(genID + " Class", className);
    if (className.find("simcore::ParticleGun") != std::string::npos) {
      header.setFloatParameter(genID + " Time [ns]",
                               gen.getParameter<double>("time"));
      header.setFloatParameter(genID + " Energy [GeV]",
                               gen.getParameter<double>("energy"));
      header.setStringParameter(genID + " Particle",
                                gen.getParameter<std::string>("particle"));
      threeVectorDump(genID + " Position [mm]",
                      gen.getParameter<std::vector<double>>("position"));
      threeVectorDump(genID + " Direction",
                      gen.getParameter<std::vector<double>>("direction"));
    } else if (className.find("simcore::MultiParticleGunPrimaryGenerator") !=
               std::string::npos) {
      header.setIntParameter(genID + " Poisson Enabled",
                             gen.getParameter<bool>("enablePoisson"));
      header.setIntParameter(genID + " N Particles",
                             gen.getParameter<int>("nParticles"));
      header.setIntParameter(genID + " PDG ID", gen.getParameter<int>("pdgID"));
      threeVectorDump(genID + " Vertex [mm]",
                      gen.getParameter<std::vector<double>>("vertex"));
      threeVectorDump(genID + " Momentum [MeV]",
                      gen.getParameter<std::vector<double>>("momentum"));
    } else if (className.find("simcore::LHEPrimaryGenerator") !=
               std::string::npos) {
      header.setStringParameter(genID + " LHE File",
                                gen.getParameter<std::string>("filePath"));
    } else if (className.find("simcore::RootCompleteReSim") !=
               std::string::npos) {
      header.setStringParameter(genID + " ROOT File",
                                gen.getParameter<std::string>("filePath"));
    } else if (className.find("simcore::RootSimFromEcalSP") !=
               std::string::npos) {
      header.setStringParameter(genID + " ROOT File",
                                gen.getParameter<std::string>("filePath"));
      header.setFloatParameter(genID + " Time Cutoff [ns]",
                               gen.getParameter<double>("time_cutoff"));
    } else if (className.find("simcore::GeneralParticleSource") !=
               std::string::npos) {
      stringVectorDump(
          genID + " Init Cmd",
          gen.getParameter<std::vector<std::string>>("initCommands"));
    } else {
      ldmx_log(warn) << "Unrecognized primary generator '" << className << "'. "
                     << "Will not be saving details to RunHeader.";
    }
  }
  // Set a string parameter with the Geant4 SHA-1.
  if (G4RunManagerKernel::GetRunManagerKernel()) {
    G4String g4Version{
        G4RunManagerKernel::GetRunManagerKernel()->GetVersionString()};
    header.setStringParameter("Geant4 revision", g4Version);
  } else {
    ldmx_log(warn) << "Unable to access G4 RunManager Kernel. Will not store "
                      "G4 Version string.";
  }
  header.setStringParameter("ldmx-sw revision", GIT_SHA1);
}
References simcore::PluginFactory::getBiasingOperators(), simcore::DetectorConstruction::getDetectorName(), simcore::PluginFactory::getInstance(), framework::config::Parameters::getParameter(), parameters_, simcore::darkbrem::G4eDarkBremsstrahlung::PROCESS_NAME, ldmx::RunHeader::setDescription(), ldmx::RunHeader::setDetectorName(), ldmx::RunHeader::setFloatParameter(), ldmx::RunHeader::setIntParameter(), and ldmx::RunHeader::setStringParameter().
configure()
void simcore::Simulator::configure (framework::config::Parameters & parameters) final override virtual
Callback for the processor to configure itself from the given set of parameters.
Parameters
parameters ParameterSet for configuration.
Reimplemented from framework::EventProcessor.
Definition at line 52 of file Simulator.cxx.
{
  // parameters used to configure the simulation
  parameters_ = parameters;
  // Set the verbosity level.  The default level  is 0.
  verbosity_ = parameters_.getParameter<int>("verbosity");
  // If the verbosity level is set to 0,
  // If the verbosity level is > 1, log everything to a file. Otherwise,
  // dump the output. If a prefix has been specified, append it ot the
  // log message.
  auto loggingPrefix = parameters_.getParameter<std::string>("logging_prefix");
  if (verbosity_ == 0)
    sessionHandle_ = std::make_unique<BatchSession>();
  else if (verbosity_ > 1) {
    if (loggingPrefix.empty())
      sessionHandle_ = std::make_unique<LoggedSession>();
    else
      sessionHandle_ = std::make_unique<LoggedSession>(
          loggingPrefix + "_G4cout.log", loggingPrefix + "_G4cerr.log");
  }
  if (sessionHandle_ != nullptr)
    uiManager_->SetCoutDestination(sessionHandle_.get());
  // Instantiate the run manager.
  runManager_ = std::make_unique<RunManager>(parameters, conditionsIntf_);
  // Instantiate the GDML parser
  auto parser{simcore::geo::ParserFactory::getInstance().createParser(
      "gdml", parameters, conditionsIntf_)};
  // Instantiate the class so cascade parameters can be set.
  G4CascadeParameters::Instance();
  // Set the DetectorConstruction instance used to build the detector
  // from the GDML description.
  runManager_->SetUserInitialization(
      new DetectorConstruction(parser, parameters, conditionsIntf_));
  G4GeometryManager::GetInstance()->OpenGeometry();
  parser->read();
  runManager_->DefineWorldVolume(parser->GetWorldVolume());
  auto preInitCommands =
      parameters_.getParameter<std::vector<std::string>>("preInitCommands", {});
  for (const std::string& cmd : preInitCommands) {
    if (allowed(cmd)) {
      int g4Ret = uiManager_->ApplyCommand(cmd);
      if (g4Ret > 0) {
        EXCEPTION_RAISE("PreInitCmd",
                        "Pre Initialization command '" + cmd +
                            "' returned a failue status from Geant4: " +
                            std::to_string(g4Ret));
      }
    } else {
      EXCEPTION_RAISE(
          "PreInitCmd",
          "Pre Initialization command '" + cmd +
              "' is not allowed because another part of Simulator handles it.");
    }
  }
}
References allowed(), conditionsIntf_, simcore::geo::ParserFactory::createParser(), simcore::geo::ParserFactory::getInstance(), framework::config::Parameters::getParameter(), parameters_, runManager_, sessionHandle_, uiManager_, and verbosity_.
onFileClose()
void simcore::Simulator::onFileClose (framework::EventFile & eventFile) final override virtual
Callback for the EventProcessor to take any necessary action when a file is closed.
Parameters
eventFile The intput/output file.
Reimplemented from framework::EventProcessor.
Definition at line 353 of file Simulator.cxx.
{
  // End the current run and print out some basic statistics if verbose
  // level > 0.
  runManager_->TerminateEventLoop();
  // Pass the **real** number of events to the persistency manager
  persistencyManager_->setNumEvents(numEventsBegan_, numEventsCompleted_);
  // Persist any remaining events, call the end of run action and
  // terminate the Geant4 kernel.
  runManager_->RunTermination();
  // Cleanup persistency manager
  //  Geant4 expects us to handle the persistency manager
  //  In order to avoid segfaulting nonsense, I delete it here
  //  so that it is deleted before the EventFile it references
  //  is deleted
  persistencyManager_.reset(nullptr);
}
References numEventsBegan_, numEventsCompleted_, persistencyManager_, and runManager_.
onFileOpen()
void simcore::Simulator::onFileOpen (framework::EventFile & eventFile) final override virtual
Callback for the EventProcessor to take any necessary action when a new file is opened.
Parameters
eventFile The input/output file.
Reimplemented from framework::EventProcessor.
Definition at line 115 of file Simulator.cxx.
{
  // Initialize persistency manager and connect it to the current EventFile
  persistencyManager_ =
      std::make_unique<simcore::persist::RootPersistencyManager>(
          file, parameters_, this->getRunNumber(), conditionsIntf_);
  persistencyManager_->Initialize();
}
References conditionsIntf_, framework::EventProcessor::getRunNumber(), parameters_, and persistencyManager_.
onNewRun()
void simcore::Simulator::onNewRun (const ldmx::RunHeader & header) final override virtual
Before the run starts (but after the conditions are configured) set up the random seeds for this run.
Parameters
[in] header RunHeader for this run, unused
Reimplemented from framework::EventProcessor.
Definition at line 273 of file Simulator.cxx.
{
  const framework::RandomNumberSeedService& rseed =
      getCondition<framework::RandomNumberSeedService>(
          framework::RandomNumberSeedService::CONDITIONS_OBJECT_NAME);
  std::vector<int> seeds;
  seeds.push_back(rseed.getSeed("Simulator[0]"));
  seeds.push_back(rseed.getSeed("Simulator[1]"));
  setSeeds(seeds);
}
References framework::RandomNumberSeedService::CONDITIONS_OBJECT_NAME, framework::RandomNumberSeedService::getSeed(), and setSeeds().
onProcessEnd()
void simcore::Simulator::onProcessEnd () final override virtual
Callback called once processing is complete.
Reimplemented from framework::EventProcessor.
Definition at line 373 of file Simulator.cxx.
{
  std::cout << "[ Simulator ] : "
            << "Started " << numEventsBegan_ << " events to produce "
            << numEventsCompleted_ << " events." << std::endl;
  // Delete Run Manager
  // From Geant4 Basic Example B01:
  //      Job termination
  //      Free the store: user actions, physics list and detector descriptions
  //      are owned and deleted by the run manager, so they should not be
  //      deleted in the main() program
  // This needs to happen here because otherwise, Geant4 objects are deleted
  // twice:
  //  1. When the histogram file is closed (all ROOT objects created during
  //  processing are put there because ROOT)
  //  2. When Simulator is deleted because runManager_ is a unique_ptr
  runManager_.reset(nullptr);
  // Delete the G4UIsession
  // I don't think this needs to happen here, but since we are cleaning up loose
  // ends...
  sessionHandle_.reset(nullptr);
}
References numEventsBegan_, numEventsCompleted_, runManager_, and sessionHandle_.
onProcessStart()
void simcore::Simulator::onProcessStart () final override virtual
Initialization of simulation
This uses the parameters set in the configure method to construct and initialize the simulation objects.
This function runs the post init setup commands.
Reimplemented from framework::EventProcessor.
Definition at line 317 of file Simulator.cxx.
{
  // initialize run
  runManager_->Initialize();
  // Get the extra simulation configuring commands
  auto postInitCommands = parameters_.getParameter<std::vector<std::string>>(
      "postInitCommands", {});
  for (const std::string& cmd : postInitCommands) {
    if (allowed(cmd)) {
      int g4Ret = uiManager_->ApplyCommand(cmd);
      if (g4Ret > 0) {
        EXCEPTION_RAISE("PostInitCmd",
                        "Post Initialization command '" + cmd +
                            "' returned a failue status from Geant4: " +
                            std::to_string(g4Ret));
      }
    } else {
      EXCEPTION_RAISE(
          "PostInitCmd",
          "Post Initialization command '" + cmd +
              "' is not allowed because another part of Simulator handles it.");
    }
  }
  // Instantiate the scoring worlds including any parallel worlds.
  runManager_->ConstructScoringWorlds();
  // Initialize the current run
  runManager_->RunInitialization();
  // Initialize the event processing
  runManager_->InitializeEventLoop(1);
  return;
}
References allowed(), framework::config::Parameters::getParameter(), parameters_, runManager_, and uiManager_.
produce()
void simcore::Simulator::produce (framework::Event & event) final override virtual
Run simulation and export results to output event.
Parameters
event The event to process.
Implements framework::Producer.
Definition at line 283 of file Simulator.cxx.
{
  // Pass the current LDMX event object to the persistency manager.  This
  // is needed by the persistency manager to fill the current event.
  persistencyManager_->setCurrentEvent(&event);
  // Generate and process a Geant4 event.
  numEventsBegan_++;
  runManager_->ProcessOneEvent(event.getEventHeader().getEventNumber());
  // If a Geant4 event has been aborted, skip the rest of the processing
  // sequence. This will immediately force the simulation to move on to
  // the next event.
  if (runManager_->GetCurrentEvent()->IsAborted()) {
    runManager_->TerminateOneEvent();  // clean up event objects
    this->abortEvent();                // get out of processors loop
  }
  if (this->getLogFrequency() > 0 and
      event.getEventHeader().getEventNumber() % this->getLogFrequency() == 0) {
    // print according to log frequency and verbosity
    if (verbosity_ > 1) {
      std::cout << "[ Simulator ] : Printing event contents:" << std::endl;
      event.Print();
    }
  }
  // Terminate the event.  This checks if an event is to be stored or
  // stacked for later.
  numEventsCompleted_++;
  runManager_->TerminateOneEvent();
  return;
}
References framework::EventProcessor::abortEvent(), framework::Event::getEventHeader(), ldmx::EventHeader::getEventNumber(), framework::EventProcessor::getLogFrequency(), numEventsBegan_, numEventsCompleted_, persistencyManager_, runManager_, and verbosity_.
setSeeds()
void simcore::Simulator::setSeeds (std::vector< int > seeds) private
Set the seeds to be used by the Geant4 random engine.
Parameters
[in] seeds A vector of seeds to pass to the G4 random engine. The vector must contain at least 2 seeds otherwise an exception is thrown.
Definition at line 408 of file Simulator.cxx.
{
  // If no seeds have been specified then return immediately.
  if (seeds.empty()) return;
  // If seeds are specified, make sure that the container has at least
  // two seeds.  If not, throw an exception.
  if (seeds.size() == 1) {
    EXCEPTION_RAISE("ConfigurationException",
                    "At least two seeds need to be specified.");
  }
  // Create the array of seeds and pass them to G4Random.  Currently,
  // only 100 seeds can be specified at a time.  If less than 100
  // seeds are specified, the remaining slots are set to 0.
  std::vector<long> seedVec(100, 0);
  for (std::size_t index{0}; index < seeds.size(); ++index)
    seedVec[index] = static_cast<long>(seeds[index]);
  // Pass the array of seeds to the random engine.
  G4Random::setTheSeeds(&seedVec[0]);
}
Referenced by onNewRun().
Member Data Documentation
conditionsIntf_
ConditionsInterface simcore::Simulator::conditionsIntf_ private
Conditions interface.
Definition at line 181 of file Simulator.h.
Referenced by configure(), and onFileOpen().
invalidCommands_
const std::vector< std::string > simcore::Simulator::invalidCommands_ static private
Initial value:
= {
    "/run/initialize",
    "/run/beamOn",
    "/random/setSeeds",
    "ldmx",
    "/persistency/gdml/read"
}
Commands not allowed to be passed from python config file This is because Simulator already runs them.
Definition at line 172 of file Simulator.h.
Referenced by allowed().
numEventsBegan_
int simcore::Simulator::numEventsBegan_ {0} private
Number of events started.
Definition at line 175 of file Simulator.h.
Referenced by onFileClose(), onProcessEnd(), and produce().
numEventsCompleted_
int simcore::Simulator::numEventsCompleted_ {0} private
Number of events completed.
Definition at line 178 of file Simulator.h.
Referenced by onFileClose(), onProcessEnd(), and produce().
parameters_
framework::config::Parameters simcore::Simulator::parameters_ private
The parameters used to configure the simulation.
Definition at line 188 of file Simulator.h.
Referenced by beforeNewRun(), configure(), onFileOpen(), and onProcessStart().
persistencyManager_
std::unique_ptr<simcore::persist::RootPersistencyManager> simcore::Simulator::persistencyManager_ private
PersistencyManager.
Definition at line 165 of file Simulator.h.
Referenced by onFileClose(), onFileOpen(), and produce().
runManager_
std::unique_ptr<RunManager> simcore::Simulator::runManager_ private
Manager controlling G4 simulation run.
Definition at line 159 of file Simulator.h.
Referenced by configure(), onFileClose(), onProcessEnd(), onProcessStart(), and produce().
sessionHandle_
std::unique_ptr<G4UIsession> simcore::Simulator::sessionHandle_ private
Handle to the G4Session -> how to deal with G4cout and G4cerr.
Definition at line 168 of file Simulator.h.
Referenced by configure(), and onProcessEnd().
uiManager_
G4UImanager* simcore::Simulator::uiManager_ {nullptr} private
User interface handle.
Definition at line 162 of file Simulator.h.
Referenced by configure(), onProcessStart(), and Simulator().
verbosity_
int simcore::Simulator::verbosity_ {1} private
Vebosity for the simulation.
Definition at line 191 of file Simulator.h.
Referenced by configure(), and produce().
The documentation for this class was generated from the following files:
SimCore/include/SimCore/Simulator.h
SimCore/src/SimCore/Simulator.cxx