LDMX Software: ldmx::EcalTriggerGeometry Class Reference
ldmx::EcalTriggerGeometry Class Reference
defines the relationship between precision cells and trigger cells and provides geometry information for trigger cells
#include <EcalTriggerGeometry.h>
Public Member Functions
EcalTriggerGeometry (int symmetry, const EcalHexReadout *ecalGeom=0)
std::vector< EcalID > contentsOfTriggerCell (EcalTriggerID triggerCell) const
EcalID centerInTriggerCell (EcalTriggerID triggerCell) const
EcalTriggerID belongsTo (EcalID precisionCell) const
std::pair< double, double > globalPosition (EcalTriggerID triggerCell) const
std::pair< double, double > localPosition (EcalTriggerID triggerCell) const
Public Member Functions inherited from ldmx::ConditionsObject
ConditionsObject (const std::string &name)
virtual ~ConditionsObject ()
std::string getName () const
Static Public Attributes
static constexpr const char * CONDITIONS_OBJECT_NAME {"EcalTriggerGeometry"}
Private Attributes
int symmetry_
const EcalHexReadout * ecalGeometry_
std::map< EcalID, EcalTriggerID > precision2trigger_
std::map< EcalTriggerID, std::vector< EcalID > > trigger2precision_
Detailed Description
defines the relationship between precision cells and trigger cells and provides geometry information for trigger cells
Definition at line 27 of file EcalTriggerGeometry.h.
Constructor & Destructor Documentation
EcalTriggerGeometry()
ldmx::EcalTriggerGeometry::EcalTriggerGeometry (int symmetry, const EcalHexReadout * ecalGeom = 0)
lower left-sector
upper-left sector
Definition at line 18 of file EcalTriggerGeometry.cxx.
                                                                                        : ConditionsObject(CONDITIONS_OBJECT_NAME), symmetry_{symmetry}, ecalGeometry_{ecalGeom} {
     if ((symmetry_ & MODULES_MASK)==INPLANE_IDENTICAL) {
       // first set is the same regardless of alignment...
       int tcell=0;
       for (int v=1; v<=10; v+=3) {
     for (int u=1; u<=10; u+=3) {
       EcalTriggerID tid(0,0,tcell);
       std::vector<EcalID> pids;
       for (int du=-1; du<=1; du++) {
         for (int dv=-1; dv<=1; dv++) {
           EcalID pid(0,0,u+du, v+dv);
           precision2trigger_[pid]=tid;
           pids.push_back(pid);
         }
       }
       trigger2precision_[tid]=pids;
       tcell++;
     }
       }
       for (int v=13; v<=22; v+=3) {
     for (int u=v-10; u<=v; u+=3) {
       EcalTriggerID tid(0,0,tcell);
       std::vector<EcalID> pids;
       for (int dv=-1; dv<=1; dv++) {
         for (int du=-1; du<=1; du++) {
           EcalID pid(0,0,u+du+dv,v+dv); // changes directions here
           precision2trigger_[pid]=tid;
           pids.push_back(pid);
         }
       }
       trigger2precision_[tid]=pids;
       tcell++;
     }
       }
       // right side
       for (int v=2; v<=22; v+=3) {
     int irow=(v-2)/3;
     for (int icol=0; icol<=std::min(irow,3); icol++) {
       if (irow-icol>=4) continue;
       EcalTriggerID tid(0,0,tcell);
       std::vector<EcalID> pids;
       int u=13+3*icol;
       for (int dv=-1; dv<=1; dv++) {
         for (int du=-1; du<=1; du++) {
           EcalID pid(0,0,u+du,v+du+dv);
           precision2trigger_[pid]=tid;
           pids.push_back(pid);
         }
       }
       trigger2precision_[tid]=pids;
       tcell++;
     }
       }
     } else {
       // raise an exception...
     }
   }
Member Function Documentation
belongsTo()
EcalTriggerID ldmx::EcalTriggerGeometry::belongsTo (EcalID precisionCell) const
Returns which trigger cell this precision cell is associated with, or a null id if there is no such association.
Definition at line 112 of file EcalTriggerGeometry.cxx.
{
     EcalID effId;
     if ((symmetry_ & MODULES_MASK)==INPLANE_IDENTICAL) {
       effId=EcalID(0,0,precisionCell.cell());
     }
     auto ptr=precision2trigger_.find(effId);
     if (ptr==precision2trigger_.end()) {
       return EcalTriggerID(0,0,0); // not ideal
     } else {
       return EcalTriggerID(precisionCell.layer(),precisionCell.module(),ptr->second.triggercell());
     }
   }
References ldmx::EcalID::cell(), ldmx::EcalID::layer(), ldmx::EcalID::module(), precision2trigger_, and symmetry_.
Referenced by ldmx::EcalTrigPrimDigiProducer::produce().
centerInTriggerCell()
EcalID ldmx::EcalTriggerGeometry::centerInTriggerCell (EcalTriggerID triggerCell) const
Returns the set of precision (full-granularity/DAQ) cell which is the center of the given trigger cell.
Definition at line 96 of file EcalTriggerGeometry.cxx.
{
     EcalTriggerID effId;
     if ((symmetry_ & MODULES_MASK)==INPLANE_IDENTICAL) {
       effId=EcalTriggerID(0,0,triggerCell.triggercell());
     }
     auto ptr=trigger2precision_.find(effId);
     if (ptr==trigger2precision_.end()) {
       std::stringstream ss;
       ss << "Unable to find trigger cell " << triggerCell;
       EXCEPTION_RAISE("EcalGeometryException",ss.str());
     }
     return EcalID(triggerCell.layer(),triggerCell.module(),ptr->second[4].cell());
   }
References ldmx::EcalTriggerID::layer(), ldmx::EcalTriggerID::module(), symmetry_, trigger2precision_, and ldmx::EcalTriggerID::triggercell().
Referenced by globalPosition(), and localPosition().
contentsOfTriggerCell()
std::vector< EcalID > ldmx::EcalTriggerGeometry::contentsOfTriggerCell (EcalTriggerID triggerCell) const
Returns the set of precision (full-granularity/DAQ) cells which are associated with the given trigger cell.
Definition at line 81 of file EcalTriggerGeometry.cxx.
{
     EcalTriggerID effId;
     std::vector<EcalID> retval;
     if ((symmetry_ & MODULES_MASK)==INPLANE_IDENTICAL) {
       effId=EcalTriggerID(0,0,triggerCell.triggercell());
     }
     auto ptr=trigger2precision_.find(effId);
     if (ptr!=trigger2precision_.end()) {
       for (auto idz : ptr->second) {
     retval.push_back(EcalID(triggerCell.layer(),triggerCell.module(),idz.cell()));
       }
     }
     return retval;
   }
References ldmx::EcalTriggerID::layer(), ldmx::EcalTriggerID::module(), symmetry_, trigger2precision_, and ldmx::EcalTriggerID::triggercell().
globalPosition()
std::pair< double, double > ldmx::EcalTriggerGeometry::globalPosition (EcalTriggerID triggerCell) const
Returns the center of the given trigger cell, depends on Ecal Geometry (EcalHexReadout)
Definition at line 127 of file EcalTriggerGeometry.cxx.
{
     if (!ecalGeometry_) return std::pair<double,double>(0,0);
     EcalID pid=centerInTriggerCell(triggerCell);
     return ecalGeometry_->getCellCenterAbsolute(pid);
   }
References centerInTriggerCell(), ecalGeometry_, and ldmx::EcalHexReadout::getCellCenterAbsolute().
localPosition()
std::pair< double, double > ldmx::EcalTriggerGeometry::localPosition (EcalTriggerID triggerCell) const
Returns the local (within module) center of the given trigger cell, depends on Ecal Geometry (EcalHexReadout)
Definition at line 133 of file EcalTriggerGeometry.cxx.
{
       if (!ecalGeometry_) return std::pair<double,double>(0,0);
       EcalID pid=centerInTriggerCell(triggerCell);
       return ecalGeometry_->getCellCenterRelative(pid.cell());
   }
References ldmx::EcalID::cell(), centerInTriggerCell(), ecalGeometry_, and ldmx::EcalHexReadout::getCellCenterRelative().
Member Data Documentation
ecalGeometry_
const EcalHexReadout* ldmx::EcalTriggerGeometry::ecalGeometry_ private
Reference to the Ecal geometry used for trigger geometry information
Definition at line 61 of file EcalTriggerGeometry.h.
Referenced by globalPosition(), and localPosition().
precision2trigger_
std::map<EcalID,EcalTriggerID> ldmx::EcalTriggerGeometry::precision2trigger_ private
Map of precision cells to trigger cells, under symmetry assumptions
Definition at line 64 of file EcalTriggerGeometry.h.
Referenced by belongsTo().
symmetry_
int ldmx::EcalTriggerGeometry::symmetry_ private
Identifies what symmetries apply in this case, such as all layers being identical, or all even and odd planes being identical and whether all modules on the same plane are identical.
Definition at line 59 of file EcalTriggerGeometry.h.
Referenced by belongsTo(), centerInTriggerCell(), and contentsOfTriggerCell().
trigger2precision_
std::map<EcalTriggerID,std::vector<EcalID> > ldmx::EcalTriggerGeometry::trigger2precision_ private
Map of trigger cells to precision cells, under symmetry assumptions
Definition at line 67 of file EcalTriggerGeometry.h.
Referenced by centerInTriggerCell(), and contentsOfTriggerCell().
The documentation for this class was generated from the following files:
Ecal/include/Ecal/EcalTriggerGeometry.h
Ecal/src/Ecal/EcalTriggerGeometry.cxx