LDMX Software: framework::config::Parameters Class Reference
framework::config::Parameters Class Reference
#include <Parameters.h>
Public Member Functions
Parameters ()
Constructor.
~Parameters ()
Destructor.
void setParameters (std::map< std::string, std::any > parameters)
template<typename T >
void addParameter (const std::string &name, const T &value)
bool exists (const std::string &name) const
template<typename T >
T getParameter (const std::string &name) const
template<typename T >
T getParameter (const std::string &name, const T &def) const
std::vector< std::string > keys () const
Private Attributes
std::map< std::string, std::any > parameters_
Parameters.
Detailed Description
Class encapsulating parameters for configuring a processor.
Definition at line 27 of file Parameters.h.
Constructor & Destructor Documentation
Parameters()
framework::config::Parameters::Parameters () inline
Constructor.
Definition at line 30 of file Parameters.h.
{};
~Parameters()
framework::config::Parameters::~Parameters () inline
Destructor.
Definition at line 33 of file Parameters.h.
{};
Member Function Documentation
addParameter()
template<typename T > void framework::config::Parameters::addParameter (const std::string & name, const T & value) inline
Add a parameter to the parameter list. If the parameter already exists in the list, throw an exception.
Parameters
[in] name Name of the parameter.
[in] value The value of the parameter.
Exceptions
Exception if a parameter by that name already exist in the list.
Definition at line 55 of file Parameters.h.
{
    if (exists(name)) {
      EXCEPTION_RAISE("ParameterExist",
                      "The parameter " + name +
                          " already exists in the list of parameters.");
    }
    parameters_[name] = value;
  }
References exists(), and parameters_.
Referenced by simcore::generators::RootCompleteReSim::RootCompleteReSim(), simcore::generators::RootSimFromEcalSP::RootSimFromEcalSP(), and eventdisplay::Display::SetFile().
exists()
bool framework::config::Parameters::exists (const std::string & name) const inline
Check to see if a parameter exists
Parameters
[in] name name of parameter to check
Returns
true if parameter exists in configuration set
Definition at line 71 of file Parameters.h.
{
    return parameters_.find(name) != parameters_.end();
  }
References parameters_.
Referenced by addParameter(), simcore::Simulator::configure(), hcal::HcalGeometryProvider::getCondition(), and getParameter().
getParameter() [1/2]
template<typename T > T framework::config::Parameters::getParameter (const std::string & name) const inline
Retrieve the parameter of the given name.
Exceptions
Exception if parameter of the given name isn't found
Exception if parameter is found but not of the input type
Parameters
T the data type to cast the parameter to.
[in] name the name of the parameter value to retrieve.
Returns
The user specified parameter of type T.
Definition at line 89 of file Parameters.h.
{
    // Check if the variable exists in the map.  If it doesn't,
    // raise an exception.
    if (not exists(name)) {
      EXCEPTION_RAISE(
          "NonExistParam",
          "Parameter '" + name + "' does not exist in list of parameters.");
    }
    try {
      auto parameter = std::any_cast<T>(parameters_.at(name));
      return parameter;
    } catch (const std::bad_any_cast& e) {
      EXCEPTION_RAISE("BadTypeParam",
                      "Parameter '" + name + "' of type '" +
                          parameters_.at(name).type().name() +
                          "' is being cast to incorrect type '" +
                          typeid(T).name() + "'.");
    }
  }
References exists(), and parameters_.
Referenced by simcore::darkbrem::APrimePhysics::APrimePhysics(), simcore::Simulator::beforeNewRun(), ecal::EcalDigiProducer::configure(), ecal::EcalRawDecoder::configure(), ecal::EcalRawEncoder::configure(), ecal::EcalRecProducer::configure(), ecal::EcalTrigPrimDigiProducer::configure(), hcal::HcalTrigPrimDigiProducer::configure(), hcal::HcalDigiProducer::configure(), hcal::HcalRecProducer::configure(), hcal::HcalRawDecoder::configure(), packing::FiberTrackerRawDecoder::configure(), packing::WRRawDecoder::configure(), hcal::HcalDoubleEndRecProducer::configure(), hcal::HcalSingleEndRecProducer::configure(), trigscint::QIEAnalyzer::configure(), trigscint::TestBeamHitAnalyzer::configure(), dqm::HCalDQM::configure(), dqm::HCalRawDigi::configure(), ecal::DNNEcalVetoProcessor::configure(), ecal::EcalClusterProducer::configure(), ecal::EcalVetoProcessor::configure(), hcal::HcalClusterProducer::configure(), hcal::HcalVetoProcessor::configure(), hcal::HcalWABVetoProcessor::configure(), recon::ElectronCounter::configure(), recon::MyProcessor::configure(), recon::OverlayProducer::configure(), recon::SequentialTrigger::configure(), recon::TriggerProcessor::configure(), simcore::Simulator::configure(), tracking::sim::HitSmearingProcessor::configure(), trigscint::EventReadoutProducer::configure(), trigscint::TestBeamHitProducer::configure(), trigscint::TrigScintDigiProducer::configure(), trigscint::TrigScintQIEDigiProducer::configure(), trigscint::TrigScintRecHitProducer::configure(), trigscint::TruthHitProducer::configure(), dqm::EcalDigiVerifier::configure(), dqm::EcalShowerFeatures::configure(), dqm::SimObjects::configure(), dqm::Trigger::configure(), trigscint::QIEDecoder::configure(), trigscint::QIEEncoder::configure(), trigscint::TestBeamClusterProducer::configure(), trigscint::TrigScintClusterProducer::configure(), trigscint::TrigScintTrackProducer::configure(), hcal::HcalAlignPolarfires::configure(), packing::RawIO::configure(), packing::SingleSubsystemPacker::configure(), packing::SingleSubsystemUnpacker::configure(), dqm::TrigScintClusterDQM::configure(), dqm::TrigScintDQM::configure(), dqm::TrigScintHitDQM::configure(), dqm::TrigScintTrackDQM::configure(), simcore::biasoperators::DarkBrem::DarkBrem(), simcore::darkbrem::DarkBremVertexLibraryModel::DarkBremVertexLibraryModel(), biasing::utility::DecayChildrenKeeper::DecayChildrenKeeper(), biasing::EcalDarkBremFilter::EcalDarkBremFilter(), ldmx::EcalGeometry::EcalGeometry(), ecal::EcalGeometryProvider::EcalGeometryProvider(), simcore::EcalSD::EcalSD(), simcore::biasoperators::ElectroNuclear::ElectroNuclear(), framework::EventFile::EventFile(), packing::rawdatafile::File::File(), simcore::darkbrem::G4eDarkBremsstrahlung::G4eDarkBremsstrahlung(), simcore::darkbrem::G4eDarkBremsstrahlungModel::G4eDarkBremsstrahlungModel(), simcore::biasoperators::GammaToMuPair::GammaToMuPair(), simcore::geo::GDMLParser::GDMLParser(), simcore::generators::GeneralParticleSource::GeneralParticleSource(), hcal::HcalGeometryProvider::getCondition(), ldmx::HcalGeometry::HcalGeometry(), hcal::HcalReconConditionsProvider::HcalReconConditionsProvider(), simcore::HcalSD::HcalSD(), ldmx::HgcrocEmulator::HgcrocEmulator(), simcore::RunManager::Initialize(), simcore::biasoperators::K0LongInelastic::K0LongInelastic(), simcore::generators::LHEPrimaryGenerator::LHEPrimaryGenerator(), biasing::MidShowerNuclearBkgdFilter::MidShowerNuclearBkgdFilter(), simcore::generators::MultiParticleGunPrimaryGenerator::MultiParticleGunPrimaryGenerator(), simcore::biasoperators::NeutronInelastic::NeutronInelastic(), simcore::Simulator::onProcessStart(), biasing::utility::PartialEnergySorter::PartialEnergySorter(), simcore::generators::ParticleGun::ParticleGun(), simcore::biasoperators::PhotoNuclear::PhotoNuclear(), biasing::PhotoNuclearProductsFilter::PhotoNuclearProductsFilter(), biasing::PrimaryToEcalFilter::PrimaryToEcalFilter(), framework::Process::Process(), framework::RandomNumberSeedService::RandomNumberSeedService(), simcore::generators::RootCompleteReSim::RootCompleteReSim(), simcore::generators::RootSimFromEcalSP::RootSimFromEcalSP(), simcore::RunManager::RunManager(), simcore::ScoringPlaneSD::ScoringPlaneSD(), simcore::RunManager::setupPhysics(), biasing::utility::StepPrinter::StepPrinter(), biasing::TaggerVetoFilter::TaggerVetoFilter(), biasing::TargetBremFilter::TargetBremFilter(), biasing::TargetDarkBremFilter::TargetDarkBremFilter(), biasing::TargetENProcessFilter::TargetENProcessFilter(), biasing::TargetProcessFilter::TargetProcessFilter(), simcore::TrackerSD::TrackerSD(), biasing::utility::TrackProcessFilter::TrackProcessFilter(), and simcore::TrigScintSD::TrigScintSD().
getParameter() [2/2]
template<typename T > T framework::config::Parameters::getParameter (const std::string & name, const T & def) const inline
Retrieve a parameter with a default specified.
Return the input default if a parameter is not found in map.
Returns
the user parameter of type T
Definition at line 118 of file Parameters.h.
{
    if (not exists(name)) return def;
    // get here knowing that name exists in parameters_
    return getParameter<T>(name);
  }
References exists().
keys()
std::vector< std::string > framework::config::Parameters::keys () const inline
Get a list of the keys available. This may be helpful in debugging to make sure the parameters are spelled correctly.
Definition at line 130 of file Parameters.h.
{
    std::vector<std::string> key;
    for (auto i : parameters_) key.push_back(i.first);
    return key;
  }
References parameters_.
Referenced by hcal::HcalGeometryProvider::getCondition().
setParameters()
void framework::config::Parameters::setParameters (std::map< std::string, std::any > parameters) inline
Set the mapping of parameter names to value.
Parameters
[in,out] parameters mapping between parameter names and the corresponding value.
Definition at line 41 of file Parameters.h.
{
    parameters_ = parameters;
  }
References parameters_.
Referenced by framework::ConfigurePython::ConfigurePython(), eventdisplay::DetectorGeometry::DetectorGeometry(), framework::getMembers(), framework::test::runProcess(), and TEST_CASE().
Member Data Documentation
parameters_
std::map<std::string, std::any> framework::config::Parameters::parameters_ private
Parameters.
Definition at line 138 of file Parameters.h.
Referenced by addParameter(), exists(), getParameter(), keys(), and setParameters().
The documentation for this class was generated from the following file:
Framework/include/Framework/Configure/Parameters.h