LDMX Software: simcore::darkbrem::DarkBremVertexLibraryModel Class Reference
simcore::darkbrem::DarkBremVertexLibraryModel Class Reference
#include <DarkBremVertexLibraryModel.h>
Classes
struct Chi
struct DiffCross
struct OutgoingKinematics
Public Member Functions
DarkBremVertexLibraryModel (framework::config::Parameters &params)
virtual ~DarkBremVertexLibraryModel ()
virtual void PrintInfo () const
virtual void RecordConfig (ldmx::RunHeader &h) const
virtual G4double ComputeCrossSectionPerAtom (G4double electronKE, G4double atomicA, G4double atomicZ)
virtual void GenerateChange (G4ParticleChange &particleChange, const G4Track &track, const G4Step &step)
Public Member Functions inherited from simcore::darkbrem::G4eDarkBremsstrahlungModel
G4eDarkBremsstrahlungModel (const framework::config::Parameters &p)
virtual ~G4eDarkBremsstrahlungModel ()=default
Destructor, nothing on purpose.
virtual void PrintInfo () const =0
virtual void RecordConfig (ldmx::RunHeader &h) const =0
virtual G4double ComputeCrossSectionPerAtom (G4double electronKE, G4double atomicA, G4double atomicZ)=0
virtual void GenerateChange (G4ParticleChange &particleChange, const G4Track &track, const G4Step &step)=0
Private Types
enum DarkBremMethod { ForwardOnly = 1 , CMScaling = 2 , Undefined = 3 }
typedef std::vector< double > StateType
Private Member Functions
void SetMadGraphDataLibrary (std::string path)
void ParseLHE (std::string fname)
void MakePlaceholders ()
OutgoingKinematics GetMadgraphData (double E0)
Private Attributes
unsigned int maxIterations_ {10000}
double threshold_
double epsilon_
DarkBremMethod method_ {DarkBremMethod::Undefined}
std::string method_name_
std::string library_path_
bool alwaysCreateNewElectron_ {true}
std::map< double, std::vector< OutgoingKinematics > > madGraphData_
std::map< double, unsigned int > currentDataPoints_
Additional Inherited Members
Protected Attributes inherited from simcore::darkbrem::G4eDarkBremsstrahlungModel
framework::logging::logger theLog_
The logging apparatus for this model.
Detailed Description
Geant4 implementation of the model for a particle undergoing a dark brem where we use an imported vertex library to decide the outgoing kinematics.
This is where all the heavy lifting in terms of calculating cross sections and actually having an electron do a dark brem occurs. This model depends on severl configurable parameters.
library_path : the full path to the directory containing the LHE dark brem vertices that will be read in to make the vertex library
epsilon : strength of the dark photon - photon mixing
threshold : minimum energy in GeV for the electron to have a non-zero cross section for going dark brem
method : scaling method to use to scale the dark brem vertices from the library to the actual electron energy when a dark brem occurs
The required parameter is a vertex library generated in MadGraph (library_path). The other parameters have helpful defaults set in the python configuration class DarkBrem and are there for you to be able to tune this model's behavior. An example library for each of the major mass points is installed with SimCore and is compressed as stored in the data directory.
Definition at line 37 of file DarkBremVertexLibraryModel.h.
Member Typedef Documentation
StateType
typedef std::vector<double> simcore::darkbrem::DarkBremVertexLibraryModel::StateType private
Helpful typedef for boost integration.
Definition at line 131 of file DarkBremVertexLibraryModel.h.
Member Enumeration Documentation
DarkBremMethod
enum simcore::darkbrem::DarkBremVertexLibraryModel::DarkBremMethod private
Possible methods to use the dark brem vertices from the imported library inside of this model.
Enumerator
ForwardOnly
Use actual electron energy and get pT from LHE (such that pT^2+me^2 < Eacc^2)
CMScaling
Boost LHE vertex momenta to the actual electron energy.
Undefined
Use LHE vertex as is.
Definition at line 288 of file DarkBremVertexLibraryModel.h.
                      {
    ForwardOnly = 1,
    CMScaling = 2,
    Undefined = 3
  };
Constructor & Destructor Documentation
DarkBremVertexLibraryModel()
simcore::darkbrem::DarkBremVertexLibraryModel::DarkBremVertexLibraryModel (framework::config::Parameters & params)
Constructor Set the parameters for this model.
The method name is converted to an enum through a hard-coded switch statement.
The threshold is set to the maximum of the passed value or twice the A' mass (so that it kinematically makes sense).
The library path is immediately passed to SetMadGraphDataLibrary.
Definition at line 27 of file DarkBremVertexLibraryModel.cxx.
    : G4eDarkBremsstrahlungModel(params), method_(DarkBremMethod::Undefined) {
  method_name_ = params.getParameter<std::string>("method");
  if (method_name_ == "forward_only") {
    method_ = DarkBremMethod::ForwardOnly;
  } else if (method_name_ == "cm_scaling") {
    method_ = DarkBremMethod::CMScaling;
  } else if (method_name_ == "undefined") {
    method_ = DarkBremMethod::Undefined;
  } else {
    EXCEPTION_RAISE("InvalidMethod", "Invalid dark brem simulation method '" +
                                         method_name_ + "'.");
  }
  threshold_ = std::max(
      params.getParameter<double>("threshold"),
      2. * G4APrime::APrime()->GetPDGMass() / CLHEP::GeV  // mass A' in GeV
  );
  epsilon_ = params.getParameter<double>("epsilon");
  library_path_ = params.getParameter<std::string>("library_path");
  SetMadGraphDataLibrary(library_path_);
}
References simcore::darkbrem::G4APrime::APrime(), CMScaling, epsilon_, ForwardOnly, framework::config::Parameters::getParameter(), library_path_, method_, method_name_, SetMadGraphDataLibrary(), threshold_, and Undefined.
~DarkBremVertexLibraryModel()
virtual simcore::darkbrem::DarkBremVertexLibraryModel::~DarkBremVertexLibraryModel () inline virtual
Destructor
Definition at line 56 of file DarkBremVertexLibraryModel.h.
{}
Member Function Documentation
ComputeCrossSectionPerAtom()
G4double simcore::darkbrem::DarkBremVertexLibraryModel::ComputeCrossSectionPerAtom (G4double electronKE, G4double atomicA, G4double atomicZ) virtual
Calculates the cross section per atom in GEANT4 internal units. Uses WW approximation to find the total cross section, performing numerical integrals over x and theta.
Numerical integrals are done using boost::numeric::odeint.
Integrate Chi from to
Integrate DiffCross from 0 to
Total cross section is given by
Parameters
E0 energy of beam (incoming particle)
Z atomic number of atom
A atomic mass of atom
cut minimum energy cut to calculate cross section
Returns
cross section (0. if outside energy cuts)
Implements simcore::darkbrem::G4eDarkBremsstrahlungModel.
Definition at line 68 of file DarkBremVertexLibraryModel.cxx.
{
  static const double MA =
      G4APrime::APrime()->GetPDGMass() / CLHEP::GeV;  // mass A' in GeV
  static const double Mel = G4Electron::Electron()->GetPDGMass() /
                            CLHEP::GeV;  // mass electron in GeV
  if (electronKE < keV) return 0.;  // outside viable region for model
  electronKE = electronKE / CLHEP::GeV;  // Change energy to GeV.
  // TODO move to first cut above
  if (electronKE < threshold_) return 0.;  // can't produce a prime
  // begin: chi-formfactor calculation
  Chi chiformfactor;
  //  set parameters
  chiformfactor.A = A;
  chiformfactor.Z = Z;
  chiformfactor.E0 = electronKE;
  chiformfactor.MA = MA;
  chiformfactor.Mel = Mel;
  double tmin = MA * MA * MA * MA / (4. * electronKE * electronKE);
  double tmax = MA * MA;
  // Integrate over chi.
  StateType integral(1);
  integral[0] = 0.;  // start integral value at zero
  boost::numeric::odeint::integrate(
      chiformfactor  // how to calculate integrand
      ,
      integral  // integral result
      ,
      tmin  // integral lower limit
      ,
      tmax  // integral upper limit
      ,
      (tmax - tmin) / 1000  // dt - initial, adapts based off error
  );
  G4double ChiRes = integral[0];
  // Integrate over x. Can use log approximation instead, which falls off at
  // high A' mass.
  DiffCross diffcross;
  diffcross.E0 = electronKE;
  diffcross.MA = MA;
  diffcross.Mel = Mel;
  double xmin = 0;
  double xmax = 1;
  if ((Mel / electronKE) > (MA / electronKE))
    xmax = 1 - Mel / electronKE;
  else
    xmax = 1 - MA / electronKE;
  // Integrate over differential cross section.
  integral[0] = 0.;  // start integral value at zero
  boost::numeric::odeint::integrate(
      diffcross  // how to calculate integrand
      ,
      integral  // integral result
      ,
      xmin  // integral lower limit
      ,
      xmax  // integral upper limit
      ,
      (xmax - xmin) / 1000  // dx - initial, adapts based off error
  );
  G4double DsDx = integral[0];
  G4double GeVtoPb = 3.894E08;
  G4double alphaEW = 1.0 / 137.0;
  G4double cross = GeVtoPb * 4. * alphaEW * alphaEW * alphaEW * epsilon_ *
                   epsilon_ * ChiRes * DsDx * CLHEP::picobarn;
  if (cross < 0.) return 0.;  // safety check all the math
  return cross;
}
References simcore::darkbrem::DarkBremVertexLibraryModel::Chi::A, simcore::darkbrem::G4APrime::APrime(), simcore::darkbrem::DarkBremVertexLibraryModel::Chi::E0, simcore::darkbrem::DarkBremVertexLibraryModel::DiffCross::E0, epsilon_, simcore::darkbrem::DarkBremVertexLibraryModel::Chi::MA, simcore::darkbrem::DarkBremVertexLibraryModel::DiffCross::MA, simcore::darkbrem::DarkBremVertexLibraryModel::Chi::Mel, simcore::darkbrem::DarkBremVertexLibraryModel::DiffCross::Mel, threshold_, and simcore::darkbrem::DarkBremVertexLibraryModel::Chi::Z.
GenerateChange()
void simcore::darkbrem::DarkBremVertexLibraryModel::GenerateChange (G4ParticleChange & particleChange, const G4Track & track, const G4Step & step) virtual
Simulates the emission of a dark photon + electron.
Gets an energy fraction and Pt from madgraph files. The scaling of this energy fraction and Pt to the actual electron energy depends on the input method.
Forward Only
Scales the energy so that the fraction of kinectic energy is constant, keeps the Pt constant. If the Pt is larger than the new energy, that event is skipped, and a new one is taken from the file. Choses the Pz of the recoil electron to always be positive.
CM Scaling
Scale MadGraph vertex to actual energy of electron using Lorentz boosts, and then extract the momentum from that.
Undefined
Don't scale the MadGraph vertex to the actual energy of the electron.
Parameters
[in,out] particleChange structure holding changes to make to particle track
[in] track current track being processesed
[in] step current step of the track
Implements simcore::darkbrem::G4eDarkBremsstrahlungModel.
Definition at line 152 of file DarkBremVertexLibraryModel.cxx.
{
  static const double MA =
      G4APrime::APrime()->GetPDGMass() / CLHEP::GeV;  // mass A' in GeV
  static const double Mel = G4Electron::Electron()->GetPDGMass() /
                            CLHEP::GeV;  // mass electron in GeV
  G4double incidentEnergy = step.GetPostStepPoint()->GetTotalEnergy();
  incidentEnergy =
      incidentEnergy / CLHEP::GeV;  // Convert the energy to GeV, the units used
                                    // in the LHE files.
  OutgoingKinematics data = GetMadgraphData(incidentEnergy);
  double EAcc = (data.electron.E() - Mel) *
                    ((incidentEnergy - Mel - MA) / (data.E - Mel - MA)) +
                Mel;
  double Pt = data.electron.Pt();
  double P = sqrt(EAcc * EAcc - Mel * Mel);
  double PhiAcc = data.electron.Phi();
  if (method_ == DarkBremMethod::ForwardOnly) {
    unsigned int i = 0;
    while (Pt * Pt + Mel * Mel > EAcc * EAcc) {
      // Skip events until the transverse energy is less than the total energy.
      i++;
      data = GetMadgraphData(incidentEnergy);
      EAcc = (data.electron.E() - Mel) *
                 ((incidentEnergy - Mel - MA) / (data.E - Mel - MA)) +
             Mel;
      Pt = data.electron.Pt();
      P = sqrt(EAcc * EAcc - Mel * Mel);
      PhiAcc = data.electron.Phi();
      if (i > maxIterations_) {
        ldmx_log(warn)
            << "Could not produce a realistic vertex with library energy "
            << data.electron.E() << " MeV.\n"
            << "Consider expanding your libary of A' vertices to include a "
               "beam energy closer to "
            << incidentEnergy << " MeV.";
        break;
      }
    }
  } else if (method_ == DarkBremMethod::CMScaling) {
    TLorentzVector el(data.electron.X(), data.electron.Y(), data.electron.Z(),
                      data.electron.E());
    double ediff = data.E - incidentEnergy;
    TLorentzVector newcm(data.centerMomentum.X(), data.centerMomentum.Y(),
                         data.centerMomentum.Z() - ediff,
                         data.centerMomentum.E() - ediff);
    el.Boost(-1. * data.centerMomentum.BoostVector());
    el.Boost(newcm.BoostVector());
    double newE = (data.electron.E() - Mel) *
                      ((incidentEnergy - Mel - MA) / (data.E - Mel - MA)) +
                  Mel;
    el.SetE(newE);
    EAcc = el.E();
    Pt = el.Pt();
    P = el.P();
  } else if (method_ == DarkBremMethod::Undefined) {
    EAcc = data.electron.E();
    P = sqrt(EAcc * EAcc - Mel * Mel);
    Pt = data.electron.Pt();
  }
  // What we need:
  //  - EAcc
  //  - P and Pt for ThetaAcc
  //  - PhiAcc
  // Basically we need the 3-momentum of the recoil electron
  EAcc = EAcc *
         CLHEP::GeV;  // Change the energy back to MeV, the internal GEANT unit.
  G4double recoilElectronMomentumMag =
      sqrt(EAcc * EAcc -
           electron_mass_c2 * electron_mass_c2);  // Electron momentum in MeV.
  G4ThreeVector recoilElectronMomentum;
  double ThetaAcc = std::asin(Pt / P);
  recoilElectronMomentum.set(std::sin(ThetaAcc) * std::cos(PhiAcc),
                             std::sin(ThetaAcc) * std::sin(PhiAcc),
                             std::cos(ThetaAcc));
  recoilElectronMomentum.rotateUz(track.GetMomentumDirection());
  recoilElectronMomentum.setMag(recoilElectronMomentumMag);
  // create g4dynamicparticle object for the dark photon.
  // define its 3-momentum so we conserve 3-momentum with primary and recoil
  // electron NOTE: does _not_ take nucleus recoil into account
  G4ThreeVector darkPhotonMomentum =
      track.GetMomentum() - recoilElectronMomentum;
  G4DynamicParticle *dphoton =
      new G4DynamicParticle(G4APrime::APrime(), darkPhotonMomentum);
  // energy of primary
  G4double finalKE = EAcc - electron_mass_c2;
  // stop tracking and create new secondary instead of primary
  if (alwaysCreateNewElectron_) {
    // TODO copy over all other particle information from track I am killing
    G4DynamicParticle *el = new G4DynamicParticle(
        track.GetDefinition(),  // should be all electrons right now, but leaves
                                // positrons open
        recoilElectronMomentum);
    particleChange.SetNumberOfSecondaries(2);
    particleChange.AddSecondary(dphoton);
    particleChange.AddSecondary(el);
    particleChange.ProposeTrackStatus(fStopAndKill);
    // continue tracking
  } else {
    // just have primary lose energy (don't rename to different track ID)
    // TODO untested this branch, not sure if it works as expected
    particleChange.SetNumberOfSecondaries(1);
    particleChange.AddSecondary(dphoton);
    particleChange.ProposeMomentumDirection(recoilElectronMomentum.unit());
    particleChange.ProposeEnergy(finalKE);
  }
}
References alwaysCreateNewElectron_, simcore::darkbrem::G4APrime::APrime(), simcore::darkbrem::DarkBremVertexLibraryModel::OutgoingKinematics::centerMomentum, CMScaling, simcore::darkbrem::DarkBremVertexLibraryModel::OutgoingKinematics::E, simcore::darkbrem::DarkBremVertexLibraryModel::OutgoingKinematics::electron, ForwardOnly, GetMadgraphData(), maxIterations_, method_, and Undefined.
GetMadgraphData()
DarkBremVertexLibraryModel::OutgoingKinematics simcore::darkbrem::DarkBremVertexLibraryModel::GetMadgraphData (double E0) private
Returns mad graph data given an energy [GeV].
Gets the energy fraction and Pt from the imported LHE data. E0 should be in GeV, returns the total energy and Pt in GeV. Scales from the closest imported beam energy above the given value (scales down to avoid biasing issues).
Parameters
E0 energy of particle undergoing dark brem [GeV]
Returns
total energy and transverse momentum of particle [GeV]
Definition at line 418 of file DarkBremVertexLibraryModel.cxx.
{
  OutgoingKinematics cmdata;  // data frame to return
  // Cycle through imported beam energies until the closest one above is found,
  // or the max is reached.
  double samplingE = 0.;
  for (const auto &keyVal : currentDataPoints_) {
    samplingE = keyVal.first;  // move samplingE up
    // check if went under the sampling energy
    //  the map is sorted by key, so we can be done right after E0 goes under
    //  samplingE
    if (E0 < samplingE) break;
  }
  // now samplingE is the closest energy above E0 or the maximum energy imported
  // from mad graph
  // Need to loop around if we hit the end, when the size of
  // madGraphData_[samplingE] is smaller than
  //  the number of events we want
  if (currentDataPoints_.at(samplingE) >= madGraphData_.at(samplingE).size()) {
    currentDataPoints_[samplingE] = 0;
  }
  // Get the lorentz vectors from the index given by the placeholder.
  cmdata = madGraphData_.at(samplingE).at(currentDataPoints_.at(samplingE));
  // Increment the current index
  currentDataPoints_[samplingE]++;
  return cmdata;
}
References currentDataPoints_, and madGraphData_.
Referenced by GenerateChange().
MakePlaceholders()
void simcore::darkbrem::DarkBremVertexLibraryModel::MakePlaceholders () private
Fill vector of currentDataPoints_ with the same number of items as the madgraph data.
Randomly choose a starting point so that the simulation run isn't dependent on the order of LHE vertices in the library.
Definition at line 407 of file DarkBremVertexLibraryModel.cxx.
{
  currentDataPoints_.clear();
  maxIterations_ = 10000;
  for (const auto &iter : madGraphData_) {
    currentDataPoints_[iter.first] = int(G4UniformRand() * iter.second.size());
    if (iter.second.size() < maxIterations_)
      maxIterations_ = iter.second.size();
  }
}
References currentDataPoints_, madGraphData_, and maxIterations_.
Referenced by SetMadGraphDataLibrary().
ParseLHE()
void simcore::darkbrem::DarkBremVertexLibraryModel::ParseLHE (std::string fname) private
Definition at line 343 of file DarkBremVertexLibraryModel.cxx.
{
  static const double MA =
      G4APrime::APrime()->GetPDGMass() / CLHEP::GeV;  // mass A' in GeV
  // TODO: use already written LHE parser?
  ldmx_log(info) << "Parsing LHE file '" << fname << "'... ";
  std::ifstream ifile;
  ifile.open(fname.c_str());
  if (!ifile) {
    EXCEPTION_RAISE("LHEFile", "Unable to open LHE file '" + fname + "'.");
  }
  std::string line;
  while (std::getline(ifile, line)) {
    std::istringstream iss(line);
    int ptype, state;
    double skip, px, py, pz, E, M;
    if (iss >> ptype >> state >> skip >> skip >> skip >> skip >> px >> py >>
        pz >> E >> M) {
      if ((ptype == 11) && (state == -1)) {
        double ebeam = E;
        double e_px, e_py, e_pz, a_px, a_py, a_pz, e_E, a_E, e_M, a_M;
        for (int i = 0; i < 2; i++) {
          std::getline(ifile, line);
        }
        std::istringstream jss(line);
        jss >> ptype >> state >> skip >> skip >> skip >> skip >> e_px >> e_py >>
            e_pz >> e_E >> e_M;
        if ((ptype == 11) && (state == 1)) {  // Find a final state electron.
          for (int i = 0; i < 2; i++) {
            std::getline(ifile, line);
          }
          std::istringstream kss(line);
          kss >> ptype >> state >> skip >> skip >> skip >> skip >> a_px >>
              a_py >> a_pz >> a_E >> a_M;
          if (ptype == 622 and state == 1) {
            if (abs(1. - a_M / MA) > 1e-3) {
              EXCEPTION_RAISE("BadMGEvnt",
                              "A MadGraph imported event has a different "
                              "APrime mass than the model has (MadGraph = " +
                                  std::to_string(a_M) + "GeV; Model = " +
                                  std::to_string(MA) + "GeV).");
            }
            OutgoingKinematics evnt;
            double cmpx = a_px + e_px;
            double cmpy = a_py + e_py;
            double cmpz = a_pz + e_pz;
            double cmE = a_E + e_E;
            evnt.electron = TLorentzVector(e_px, e_py, e_pz, e_E);
            evnt.centerMomentum = TLorentzVector(cmpx, cmpy, cmpz, cmE);
            evnt.E = ebeam;
            madGraphData_[ebeam].push_back(evnt);
          }  // get a prime kinematics
        }    // check for final state
      }      // check for particle type and state
    }        // able to get momentum/energy numbers
  }          // while getting lines
  // Add the energy to the list, with a random offset between 0 and the total
  // number of entries.
  ifile.close();
  ldmx_log(info) << "done parsing.";
}
PrintInfo()
void simcore::darkbrem::DarkBremVertexLibraryModel::PrintInfo () const virtual
Print the configuration of this model
Implements simcore::darkbrem::G4eDarkBremsstrahlungModel.
Definition at line 53 of file DarkBremVertexLibraryModel.cxx.
{
  G4cout << " Dark Brem Vertex Library Model" << G4endl;
  G4cout << "   Threshold [GeV]: " << threshold_ << G4endl;
  G4cout << "   Epsilon:         " << epsilon_ << G4endl;
  G4cout << "   Scaling Method:  " << method_name_ << G4endl;
  G4cout << "   Vertex Library:  " << library_path_ << G4endl;
}
References epsilon_, library_path_, method_name_, and threshold_.
RecordConfig()
void simcore::darkbrem::DarkBremVertexLibraryModel::RecordConfig (ldmx::RunHeader & h) const virtual
Record the configuration of this model into the RunHeader
Implements simcore::darkbrem::G4eDarkBremsstrahlungModel.
Definition at line 61 of file DarkBremVertexLibraryModel.cxx.
{
  h.setFloatParameter("Minimum Threshold to DB [GeV]", threshold_);
  h.setFloatParameter("DB Xsec Epsilon", epsilon_);
  h.setStringParameter("Vertex Scaling Method", method_name_);
  h.setStringParameter("Vertex Library", library_path_);
}
References epsilon_, library_path_, method_name_, ldmx::RunHeader::setFloatParameter(), ldmx::RunHeader::setStringParameter(), and threshold_.
SetMadGraphDataLibrary()
void simcore::darkbrem::DarkBremVertexLibraryModel::SetMadGraphDataLibrary (std::string path) private
Set the library of dark brem events to be scaled.
Parameters
file path to directory of LHE files
Definition at line 269 of file DarkBremVertexLibraryModel.cxx.
{
  // Assumptions:
  //  - Directory passed is a flat directory (no sub directories) containing LHE
  //  files
  //  - LHE files are events generated with the correct mass point
  // TODO automatically select LHE files of the correct mass point?
  bool foundOneFile = false;
  DIR *dir;            // handle to opened directory
  struct dirent *ent;  // handle to entry inside directory
  if ((dir = opendir(path.c_str())) != NULL) {
    // directory can be opened
    while ((ent = readdir(dir)) != NULL) {
      std::string fp = path + '/' + std::string(ent->d_name);
      if (fp.substr(fp.find_last_of('.') + 1) == "lhe") {
        // file ends in '.lhe'
        ParseLHE(fp);
        foundOneFile = true;
      }
    }
    closedir(dir);
  }
  if (not foundOneFile) {
    EXCEPTION_RAISE("DirDNE", "Directory '" + path +
                                  "' was unable to be opened or no '.lhe' "
                                  "files were found inside of it.");
  }
  MakePlaceholders();  // Setup the placeholder offsets for getting data.
  ldmx_log(info) << "MadGraph Library of Dark Brem Vertices:\n";
  for (const auto &kV : madGraphData_) {
    ldmx_log(info) << "\t" << std::setw(8) << kV.first << " GeV Beam -> "
                   << std::setw(6) << kV.second.size() << " Events";
  }
  return;
}
References madGraphData_, and MakePlaceholders().
Referenced by DarkBremVertexLibraryModel().
Member Data Documentation
alwaysCreateNewElectron_
bool simcore::darkbrem::DarkBremVertexLibraryModel::alwaysCreateNewElectron_ {true} private
should we always create a totally new electron when we dark brem?
@TODO make this configurable? I (Tom E) can't think of a reason NOT to have it... The alternative is to allow Geant4 to decide when to make a new particle by checking if the resulting kinetic energy is below some threshold.
Definition at line 322 of file DarkBremVertexLibraryModel.h.
Referenced by GenerateChange().
currentDataPoints_
std::map<double, unsigned int> simcore::darkbrem::DarkBremVertexLibraryModel::currentDataPoints_ private
Stores a map of current access points to mad graph data.
Maps incoming electron energy to the index of the data vector that we will get the data from.
Also sorts the incoming electron energy so that we can find the sampling energy that is closest above the actual incoming energy.
Definition at line 344 of file DarkBremVertexLibraryModel.h.
Referenced by GetMadgraphData(), and MakePlaceholders().
epsilon_
double simcore::darkbrem::DarkBremVertexLibraryModel::epsilon_ private
Epsilon value to plug into xsec calculation
See also
ComputeCrossSectionPerAtom for how this is used
Configurable with 'epsilon'
Definition at line 280 of file DarkBremVertexLibraryModel.h.
Referenced by ComputeCrossSectionPerAtom(), DarkBremVertexLibraryModel(), PrintInfo(), and RecordConfig().
library_path_
std::string simcore::darkbrem::DarkBremVertexLibraryModel::library_path_ private
Full path to the vertex library used for persisting into the RunHeader
Definition at line 312 of file DarkBremVertexLibraryModel.h.
Referenced by DarkBremVertexLibraryModel(), PrintInfo(), and RecordConfig().
madGraphData_
std::map<double, std::vector<OutgoingKinematics> > simcore::darkbrem::DarkBremVertexLibraryModel::madGraphData_ private
Storage of data from mad graph
Maps incoming electron energy to various options for outgoing kinematics. This is a hefty map and is what stores all of the vertices imported from the LHE library of dark brem vertices.
Library is read in from configuration parameter 'darkbrem.madgraphlibrary'
Definition at line 333 of file DarkBremVertexLibraryModel.h.
Referenced by GetMadgraphData(), MakePlaceholders(), and SetMadGraphDataLibrary().
maxIterations_
unsigned int simcore::darkbrem::DarkBremVertexLibraryModel::maxIterations_ {10000} private
maximum number of iterations to check before giving up on an event
@TODO make configurable and/or optimize somehow
Definition at line 266 of file DarkBremVertexLibraryModel.h.
Referenced by GenerateChange(), and MakePlaceholders().
method_
DarkBremMethod simcore::darkbrem::DarkBremVertexLibraryModel::method_ {DarkBremMethod::Undefined} private
method for this model
Configurable with 'method'
Definition at line 302 of file DarkBremVertexLibraryModel.h.
Referenced by DarkBremVertexLibraryModel(), and GenerateChange().
method_name_
std::string simcore::darkbrem::DarkBremVertexLibraryModel::method_name_ private
Name of method for persisting into the RunHeader
Definition at line 307 of file DarkBremVertexLibraryModel.h.
Referenced by DarkBremVertexLibraryModel(), PrintInfo(), and RecordConfig().
threshold_
double simcore::darkbrem::DarkBremVertexLibraryModel::threshold_ private
Threshold for non-zero xsec [GeV]
Configurable with 'threshold'
Definition at line 272 of file DarkBremVertexLibraryModel.h.
Referenced by ComputeCrossSectionPerAtom(), DarkBremVertexLibraryModel(), PrintInfo(), and RecordConfig().
The documentation for this class was generated from the following files:
SimCore/include/SimCore/DarkBrem/DarkBremVertexLibraryModel.h
SimCore/src/SimCore/DarkBrem/DarkBremVertexLibraryModel.cxx