LDMX Software: ldmx::DetectorID Class Reference
ldmx::DetectorID Class Reference
Defines a 32-bit packed ID for uniquely identifying hits and detector components.
#include <DetectorID.h>
Public Types
typedef uint32_t RawValue
Public Member Functions
DetectorID ()
Class constructor for a null DetectorID.
DetectorID (RawValue rawid)
Class constructor from a raw 32-bit integer.
DetectorID (SubdetectorIDType sdtype, RawValue raw_subpayload)
bool null () const
SubdetectorIDType subdet () const
RawValue raw () const
void setRawValue (RawValue rawValue)
bool operator< (const DetectorID &id) const
bool operator== (const DetectorID &id) const
bool operator!= (const DetectorID &id) const
Static Public Attributes
static const RawValue SUBDETECTORID_MASK {0x3F}
static const RawValue SUBDETECTORID_SHIFT {26}
static const RawValue SUBDETECTOR_PAYLOAD_MASK {0x3FFFFFFF}
Protected Attributes
RawValue id_
The raw, packed value of the ID.
Detailed Description
Defines a 32-bit packed ID for uniquely identifying hits and detector components.
Note
This class has a memory footprint of a single 32-bit integer, so can be efficiently used in data structures
Definition at line 34 of file DetectorID.h.
Constructor & Destructor Documentation
DetectorID()
ldmx::DetectorID::DetectorID (SubdetectorIDType sdtype, RawValue raw_subpayload) inline
Class constructor from a subdetector id and a subdetector-specific section (masked to
Definition at line 56 of file DetectorID.h.
{
                 id_ = ((RawValue(sdtype) & DetectorID::SUBDETECTORID_MASK ) << DetectorID::SUBDETECTORID_SHIFT) | (raw_subpayload & DetectorID::SUBDETECTOR_PAYLOAD_MASK);
             }
References id_.
Member Function Documentation
null()
bool ldmx::DetectorID::null () const inline
Returns
A null ID
Definition at line 62 of file DetectorID.h.
 { return id_==0; }
References id_.
Referenced by ldmx::DetectorIDInterpreter::init(), and TEST_CASE().
raw()
RawValue ldmx::DetectorID::raw () const inline
Returns
The raw value
Definition at line 71 of file DetectorID.h.
 { return id_; }
References id_.
Referenced by ldmx::DetectorIDInterpreter::getFieldValue(), ldmx::DetectorIDInterpreter::init(), ldmx::HcalDigiProducer::produce(), ldmx::TrigScintDigiProducer::produce(), TEST_CASE(), and ldmx::DetectorIDInterpreter::unpack().
setRawValue()
void ldmx::DetectorID::setRawValue (RawValue rawValue) inline
Set the raw value of the detector ID.
Parameters
rawValue The raw value of the ID.
Definition at line 77 of file DetectorID.h.
{
                 id_=rawValue;
             }
References id_.
Referenced by ldmx::DetectorIDInterpreter::pack().
subdet()
SubdetectorIDType ldmx::DetectorID::subdet () const inline
Returns
The subdetector range.
Definition at line 65 of file DetectorID.h.
{
                 return SubdetectorIDType((id_>>SUBDETECTORID_SHIFT)&SUBDETECTORID_MASK);
             }
References id_.
Referenced by TEST_CASE().
The documentation for this class was generated from the following file:
DetDescr/include/DetDescr/DetectorID.h