LDMX Software: ldmx::EcalDigiCollection Class Reference
ldmx::EcalDigiCollection Class Reference
Represents a collection of the ECal digi hits.
#include <EcalDigiCollection.h>
Public Member Functions
EcalDigiCollection ()
virtual ~EcalDigiCollection ()
void Clear ()
void Print () const
unsigned int getNumSamplesPerDigi () const
void setNumSamplesPerDigi (unsigned int n)
unsigned int getSampleOfInterestIndex () const
void setSampleOfInterestIndex (unsigned int n)
std::vector< EcalDigiSample > getDigi (unsigned int digiIndex) const
unsigned int getNumDigis () const
void addDigi (std::vector< EcalDigiSample > newSamples)
Private Member Functions
ClassDef (EcalDigiCollection, 1)
Private Attributes
std::vector< int > channelIDs_
std::vector< int32_t > samples_
unsigned int numSamplesPerDigi_ {1}
unsigned int sampleOfInterest_ {0}
Static Private Attributes
static const int ONE_BIT_MASK = 1
static const int TEN_BIT_MASK = (1 << 10) - 1
static const int FIRSTFLAG_POS = 31
static const int SECONFLAG_POS = 30
static const int FIRSTMEAS_POS = 20
static const int SECONMEAS_POS = 10
Detailed Description
Represents a collection of the ECal digi hits.
Note
This class represents the digitized signal information in the form of a series of samples for each channel of readout. Each channel is represented by an ID integer and each sample is a 32-bit word. The number of samples for each digi is configurable, but is required to be the same for all channels.
Each digi corresponds to a one channel ID and numSamplesPerDigi_ samples.
Definition at line 56 of file EcalDigiCollection.h.
Constructor & Destructor Documentation
EcalDigiCollection()
ldmx::EcalDigiCollection::EcalDigiCollection () inline
Class constructor.
Definition at line 63 of file EcalDigiCollection.h.
 { }
~EcalDigiCollection()
virtual ldmx::EcalDigiCollection::~EcalDigiCollection () inline virtual
Class destructor.
Definition at line 68 of file EcalDigiCollection.h.
 { }
Member Function Documentation
addDigi()
void ldmx::EcalDigiCollection::addDigi (std::vector< EcalDigiSample > newSamples)
Translate and add samples to collection
Referenced by ldmx::EcalDigiProducer::produce().
ClassDef()
ldmx::EcalDigiCollection::ClassDef (EcalDigiCollection , 1) private
The ROOT class definition.
Clear()
void ldmx::EcalDigiCollection::Clear ()
Clear the data in the object.
Clears the vectors of channel IDs and samples, but does not change the number of samples per digi setting.
getDigi()
std::vector< EcalDigiSample > ldmx::EcalDigiCollection::getDigi (unsigned int digiIndex) const
Get samples for the input digi index
Referenced by ldmx::EcalRecProducer::produce().
getNumDigis()
unsigned int ldmx::EcalDigiCollection::getNumDigis () const inline
Get total number of digis
Definition at line 112 of file EcalDigiCollection.h.
 { return channelIDs_.size(); }
References channelIDs_.
Referenced by ldmx::EcalDigiProducer::produce(), and ldmx::EcalRecProducer::produce().
getNumSamplesPerDigi()
unsigned int ldmx::EcalDigiCollection::getNumSamplesPerDigi () const inline
Get number of samples per digi
Definition at line 87 of file EcalDigiCollection.h.
 { return numSamplesPerDigi_; }
References numSamplesPerDigi_.
getSampleOfInterestIndex()
unsigned int ldmx::EcalDigiCollection::getSampleOfInterestIndex () const inline
Get index of sample of interest
Definition at line 97 of file EcalDigiCollection.h.
 { return sampleOfInterest_; }
References sampleOfInterest_.
Print()
void ldmx::EcalDigiCollection::Print () const
Print out the object.
Prints out the lengths of the stored vectors and the number of samples per digi setting.
setNumSamplesPerDigi()
void ldmx::EcalDigiCollection::setNumSamplesPerDigi (unsigned int n) inline
Set number of samples for each digi
Definition at line 92 of file EcalDigiCollection.h.
 { numSamplesPerDigi_ = n; return; }
References numSamplesPerDigi_.
Referenced by ldmx::EcalDigiProducer::produce().
setSampleOfInterestIndex()
void ldmx::EcalDigiCollection::setSampleOfInterestIndex (unsigned int n) inline
Set index of sample of interest
Definition at line 102 of file EcalDigiCollection.h.
 { sampleOfInterest_ = n; return; }
References sampleOfInterest_.
Referenced by ldmx::EcalDigiProducer::produce().
Member Data Documentation
channelIDs_
std::vector< int > ldmx::EcalDigiCollection::channelIDs_ private
list of channel IDs that we have digis for
Definition at line 142 of file EcalDigiCollection.h.
Referenced by getNumDigis().
FIRSTFLAG_POS
const int ldmx::EcalDigiCollection::FIRSTFLAG_POS = 31 static private
Bit position of first flag
Definition at line 128 of file EcalDigiCollection.h.
FIRSTMEAS_POS
const int ldmx::EcalDigiCollection::FIRSTMEAS_POS = 20 static private
Bit position of first measurement
Definition at line 134 of file EcalDigiCollection.h.
numSamplesPerDigi_
unsigned int ldmx::EcalDigiCollection::numSamplesPerDigi_ {1} private
number of samples for each digi
Definition at line 148 of file EcalDigiCollection.h.
Referenced by getNumSamplesPerDigi(), and setNumSamplesPerDigi().
ONE_BIT_MASK
const int ldmx::EcalDigiCollection::ONE_BIT_MASK = 1 static private
Mask for lowest order bit in an int
Definition at line 122 of file EcalDigiCollection.h.
sampleOfInterest_
unsigned int ldmx::EcalDigiCollection::sampleOfInterest_ {0} private
index for the sample of interest in the samples list
Definition at line 151 of file EcalDigiCollection.h.
Referenced by getSampleOfInterestIndex(), and setSampleOfInterestIndex().
samples_
std::vector< int32_t > ldmx::EcalDigiCollection::samples_ private
list of samples that we have been given
Definition at line 145 of file EcalDigiCollection.h.
SECONFLAG_POS
const int ldmx::EcalDigiCollection::SECONFLAG_POS = 30 static private
Bit position of second flag
Definition at line 131 of file EcalDigiCollection.h.
SECONMEAS_POS
const int ldmx::EcalDigiCollection::SECONMEAS_POS = 10 static private
Bit position of second measurement
Definition at line 137 of file EcalDigiCollection.h.
TEN_BIT_MASK
const int ldmx::EcalDigiCollection::TEN_BIT_MASK = (1 << 10) - 1 static private
Mask for lowest order ten bits in an int
Definition at line 125 of file EcalDigiCollection.h.
The documentation for this class was generated from the following file:
Event/include/Event/EcalDigiCollection.h