LDMX Software: ldmx::HcalVetoResult Class Reference
ldmx::HcalVetoResult Class Reference
Public Member Functions
HcalVetoResult ()
~HcalVetoResult ()
void Clear ()
void Print () const
bool passesVeto () const
ldmx::HcalHit getMaxPEHit () const
void setVetoResult (const bool &passesVeto=true)
void setMaxPEHit (const ldmx::HcalHit maxPEHit)
Private Member Functions
ClassDef (HcalVetoResult, 2)
Private Attributes
ldmx::HcalHit maxPEHit_
bool passesVeto_ {false}
Detailed Description
Definition at line 23 of file HcalVetoResult.h.
Constructor & Destructor Documentation
HcalVetoResult()
ldmx::HcalVetoResult::HcalVetoResult ()
Constructor
~HcalVetoResult()
ldmx::HcalVetoResult::~HcalVetoResult ()
Destructor
Member Function Documentation
Clear()
void ldmx::HcalVetoResult::Clear ()
Reset the object.
getMaxPEHit()
ldmx::HcalHit ldmx::HcalVetoResult::getMaxPEHit () const inline
Returns
The maximum PE HcalHit.
Definition at line 41 of file HcalVetoResult.h.
{ return maxPEHit_; }
References maxPEHit_.
Referenced by framework::test::TestAnalyzer::analyze().
passesVeto()
bool ldmx::HcalVetoResult::passesVeto () const inline
Checks if the event passes the Hcal veto.
Definition at line 38 of file HcalVetoResult.h.
{ return passesVeto_; };
References passesVeto_.
Referenced by framework::test::TestAnalyzer::analyze(), framework::test::TestProducer::produce(), and setVetoResult().
Print()
void ldmx::HcalVetoResult::Print () const
Print out the object
setMaxPEHit()
void ldmx::HcalVetoResult::setMaxPEHit (const ldmx::HcalHit maxPEHit) inline
Set the maximum PE hit.
Parameters
maxPEHit The maximum PE HcalHit
Definition at line 57 of file HcalVetoResult.h.
{
    maxPEHit_ = maxPEHit;
  }
References maxPEHit_.
Referenced by hcal::HcalVetoProcessor::produce(), hcal::HcalWABVetoProcessor::produce(), and framework::test::TestProducer::produce().
setVetoResult()
void ldmx::HcalVetoResult::setVetoResult (const bool & passesVeto = true) inline
Sets whether the Hcal veto was passed or not.
Parameters
passesVeto Veto result.
Definition at line 48 of file HcalVetoResult.h.
{
    passesVeto_ = passesVeto;
  }
References passesVeto(), and passesVeto_.
Referenced by hcal::HcalVetoProcessor::produce(), hcal::HcalWABVetoProcessor::produce(), and framework::test::TestProducer::produce().
Member Data Documentation
maxPEHit_
ldmx::HcalHit ldmx::HcalVetoResult::maxPEHit_ private
Reference to max PE hit.
Definition at line 63 of file HcalVetoResult.h.
Referenced by getMaxPEHit(), and setMaxPEHit().
passesVeto_
bool ldmx::HcalVetoResult::passesVeto_ {false} private
Flag indicating whether the event passes the Hcal veto.
Definition at line 66 of file HcalVetoResult.h.
Referenced by passesVeto(), and setVetoResult().
The documentation for this class was generated from the following file:
Hcal/include/Hcal/Event/HcalVetoResult.h