LDMX Software: simcore::g4user::EventAction Class Reference
simcore::g4user::EventAction Class Reference
Implementation of user event action hook.
#include <EventAction.h>
Public Member Functions
EventAction ()
virtual ~EventAction ()
void BeginOfEventAction (const G4Event *event)
void EndOfEventAction (const G4Event *event)
void registerAction (UserAction *eventAction)
Private Attributes
std::vector< UserAction * > eventActions_
Detailed Description
Implementation of user event action hook.
Definition at line 44 of file EventAction.h.
Constructor & Destructor Documentation
EventAction()
simcore::g4user::EventAction::EventAction () inline
Class constructor.
Definition at line 49 of file EventAction.h.
{}
~EventAction()
virtual simcore::g4user::EventAction::~EventAction () inline virtual
Class destructor.
Definition at line 54 of file EventAction.h.
{}
Member Function Documentation
BeginOfEventAction()
void simcore::g4user::EventAction::BeginOfEventAction (const G4Event * event)
Implementation of begin of event hook.
Parameters
event The Geant4 event.
Definition at line 25 of file EventAction.cxx.
{
  // Clear the global track map.
  simcore::g4user::TrackingAction::get()->getTrackMap().clear();
  // Call user event actions
  for (auto& eventAction : eventActions_)
    eventAction->BeginOfEventAction(event);
}
References simcore::TrackMap::clear(), simcore::g4user::TrackingAction::get(), and simcore::g4user::TrackingAction::getTrackMap().
EndOfEventAction()
void simcore::g4user::EventAction::EndOfEventAction (const G4Event * event)
Implementation of end of event hook.
Parameters
event The Geant4 event.
Definition at line 34 of file EventAction.cxx.
{
  // Call user event actions
  for (auto& eventAction : eventActions_) eventAction->EndOfEventAction(event);
}
registerAction()
void simcore::g4user::EventAction::registerAction (UserAction * eventAction) inline
Register a user action of type EventAction with this class.
Parameters
action User action of type EventAction
Definition at line 73 of file EventAction.h.
{
    eventActions_.push_back(eventAction);
  }
Member Data Documentation
eventActions_
std::vector<UserAction*> simcore::g4user::EventAction::eventActions_ private
Definition at line 78 of file EventAction.h.
The documentation for this class was generated from the following files:
SimCore/include/SimCore/G4User/EventAction.h
SimCore/src/SimCore/G4User/EventAction.cxx