LDMX Software: simcore::generators::LHEPrimaryGenerator Class Reference
simcore::generators::LHEPrimaryGenerator Class Reference
Generates a Geant4 event from an LHEEvent.
#include <LHEPrimaryGenerator.h>
Public Member Functions
LHEPrimaryGenerator (const std::string &name, const framework::config::Parameters &parameters)
virtual ~LHEPrimaryGenerator ()
void GeneratePrimaryVertex (G4Event *anEvent)
void RecordConfig (const std::string &id, ldmx::RunHeader &rh) final override
Public Member Functions inherited from simcore::PrimaryGenerator
PrimaryGenerator (const std::string &name, const framework::config::Parameters &parameters)
virtual ~PrimaryGenerator ()
Destructor.
virtual void GeneratePrimaryVertex (G4Event *)=0
virtual void RecordConfig (const std::string &id, ldmx::RunHeader &rh)=0
Private Attributes
simcore::lhe::LHEReader * reader_
std::string file_path_
path to LHE file
Additional Inherited Members
Public Types inherited from simcore::PrimaryGenerator
using Factory = ::simcore::Factory< PrimaryGenerator, std::shared_ptr< PrimaryGenerator >, const std::string &, const framework::config::Parameters & >
Factory for primary generators.
Protected Attributes inherited from simcore::PrimaryGenerator
std::string name_ {""}
Name of the PrimaryGenerator.
Detailed Description
Generates a Geant4 event from an LHEEvent.
Definition at line 24 of file LHEPrimaryGenerator.h.
Constructor & Destructor Documentation
LHEPrimaryGenerator()
simcore::generators::LHEPrimaryGenerator::LHEPrimaryGenerator (const std::string & name, const framework::config::Parameters & parameters)
Class constructor.
Parameters
reader The LHE reader with the event data.
Definition at line 25 of file LHEPrimaryGenerator.cxx.
    : PrimaryGenerator(name, parameters) {
  file_path_ = parameters.getParameter<std::string>("filePath");
  reader_ = new simcore::lhe::LHEReader(file_path_);
}
References file_path_, framework::config::Parameters::getParameter(), and reader_.
~LHEPrimaryGenerator()
simcore::generators::LHEPrimaryGenerator::~LHEPrimaryGenerator () virtual
Class destructor.
Definition at line 32 of file LHEPrimaryGenerator.cxx.
{ delete reader_; }
References reader_.
Member Function Documentation
GeneratePrimaryVertex()
void simcore::generators::LHEPrimaryGenerator::GeneratePrimaryVertex (G4Event * anEvent) virtual
Generate vertices in the Geant4 event.
Parameters
anEvent The Geant4 event.
Implements simcore::PrimaryGenerator.
Definition at line 34 of file LHEPrimaryGenerator.cxx.
{
  simcore::lhe::LHEEvent* lheEvent = reader_->readNextEvent();
  if (lheEvent != NULL) {
    G4PrimaryVertex* vertex = new G4PrimaryVertex();
    vertex->SetPosition(lheEvent->getVertex()[0], lheEvent->getVertex()[1],
                        lheEvent->getVertex()[2]);
    vertex->SetWeight(lheEvent->getXWGTUP());
    std::map<simcore::lhe::LHEParticle*, G4PrimaryParticle*> particleMap;
    int particleIndex = 0;
    const std::vector<simcore::lhe::LHEParticle*>& particles = lheEvent->getParticles();
    for (auto it = particles.begin();
         it != particles.end(); it++) {
      simcore::lhe::LHEParticle* particle = (*it);
      if (particle->getISTUP() > 0) {
        G4PrimaryParticle* primary = new G4PrimaryParticle();
        if (particle->getIDUP() == -623) { /* Tungsten ion */
          G4ParticleDefinition* tungstenIonDef =
              G4IonTable::GetIonTable()->GetIon(74, 184, 0.);
          if (tungstenIonDef != NULL) {
            primary->SetParticleDefinition(tungstenIonDef);
          } else {
            EXCEPTION_RAISE("EventGenerator",
                            "Failed to find particle definition for W ion.");
          }
        } else {
          primary->SetPDGcode(particle->getIDUP());
        }
        primary->Set4Momentum(
            particle->getPUP(0) * GeV, particle->getPUP(1) * GeV,
            particle->getPUP(2) * GeV, particle->getPUP(3) * GeV);
        primary->SetProperTime(particle->getVTIMUP() * nanosecond);
        UserPrimaryParticleInformation* primaryInfo =
            new UserPrimaryParticleInformation();
        primaryInfo->setHepEvtStatus(particle->getISTUP());
        primary->SetUserInformation(primaryInfo);
        particleMap[particle] = primary;
        /*
         * Assign primary as daughter but only if the mother is not a DOC
         * particle.
         */
        if (particle->getMother(0) != NULL &&
            particle->getMother(0)->getISTUP() > 0) {
          G4PrimaryParticle* primaryMom = particleMap[particle->getMother(0)];
          if (primaryMom != NULL) {
            primaryMom->SetDaughter(primary);
          }
        } else {
          vertex->SetPrimary(primary);
        }
      }
      ++particleIndex;
    }
    anEvent->AddPrimaryVertex(vertex);
  } else {
    std::cout << "[ LHEPrimaryGenerator ] : Ran out of input events so run "
                 "will be aborted!"
              << std::endl;
    G4RunManager::GetRunManager()->AbortRun(true);
    anEvent->SetEventAborted();
  }
  delete lheEvent;
}
References simcore::lhe::LHEParticle::getIDUP(), simcore::lhe::LHEParticle::getISTUP(), simcore::lhe::LHEParticle::getMother(), simcore::lhe::LHEEvent::getParticles(), simcore::lhe::LHEParticle::getPUP(), simcore::lhe::LHEEvent::getVertex(), simcore::lhe::LHEParticle::getVTIMUP(), simcore::lhe::LHEEvent::getXWGTUP(), reader_, simcore::lhe::LHEReader::readNextEvent(), and simcore::UserPrimaryParticleInformation::setHepEvtStatus().
RecordConfig()
void simcore::generators::LHEPrimaryGenerator::RecordConfig (const std::string & id, ldmx::RunHeader & rh) final override virtual
Record the configuration of the primary generator into the run header
Note
you must include the id number in each entry into the run header just in case there are other generators
Implements simcore::PrimaryGenerator.
Definition at line 109 of file LHEPrimaryGenerator.cxx.
{
  rh.setStringParameter(id+" Class", "simcore::generators::LHEPrimaryGenerator");
  rh.setStringParameter(id+" LHE File", file_path_);
}
References file_path_, and ldmx::RunHeader::setStringParameter().
Member Data Documentation
file_path_
std::string simcore::generators::LHEPrimaryGenerator::file_path_ private
path to LHE file
Definition at line 50 of file LHEPrimaryGenerator.h.
Referenced by LHEPrimaryGenerator(), and RecordConfig().
reader_
simcore::lhe::LHEReader* simcore::generators::LHEPrimaryGenerator::reader_ private
The LHE reader with the event data.
Definition at line 48 of file LHEPrimaryGenerator.h.
Referenced by GeneratePrimaryVertex(), LHEPrimaryGenerator(), and ~LHEPrimaryGenerator().
The documentation for this class was generated from the following files:
SimCore/include/SimCore/Generators/LHEPrimaryGenerator.h
SimCore/src/SimCore/Generators/LHEPrimaryGenerator.cxx