LDMX Software: ldmx::HgcrocEmulator Class Reference
ldmx::HgcrocEmulator Class Reference
Emulate the digitization procedure performed by the HGCROC.
#include <HgcrocEmulator.h>
Classes
class CompositePulse
Public Member Functions
HgcrocEmulator (const framework::config::Parameters &ps)
~HgcrocEmulator ()
bool hasSeed () const
void seedGenerator (uint64_t seed)
void condition (const conditions::DoubleTableCondition &table)
bool digitize (const int &channelID, std::vector< std::pair< double, double > > &arriving_pulses, std::vector< ldmx::HgcrocDigiCollection::Sample > &digiToAdd) const
std::vector< ldmx::HgcrocDigiCollection::Sample > noiseDigi (const int &channel, const double &soi_amplitude=0) const
double noise (const int &channelID) const
double gain (const int &channelID) const
Gain for input channel.
double pedestal (const int &id) const
Pedestal [ADC Counts] for input channel.
double readoutThreshold (const int &id) const
Readout Threshold (ADC Counts)
Private Member Functions
double getCondition (int id, const std::string &name) const
Private Attributes
bool noise_ {true}
Put noise in channels, only configure to false if testing.
int nADCs_
Depth of ADC buffer.
int iSOI_
Index for the Sample Of Interest in the list of digi samples.
double noiseRMS_
Noise RMS [mV].
double clockCycle_
Time interval for chip clock [ns].
double timingJitter_
Jitter of timing mechanism in the chip [ns].
double ns_
Conversion from time [ns] to counts.
double rateUpSlope_
Rate of Up Slope in Pulse Shape [1/ns].
double timeUpSlope_
Time of Up Slope relative to Pulse Shape Fit [ns].
double rateDnSlope_
Rate of Down Slope in Pulse Shape [1/ns].
double timeDnSlope_
Time of Down Slope relative to Pulse Shape Fit [ns].
double timePeak_
Time of Peak relative to pulse shape fit [ns].
double hit_merge_ns_
Hit merging time [ns].
const conditions::DoubleTableCondition * chipConditions_ {nullptr}
std::map< std::string, int > conditionNamesToIndex_
std::unique_ptr< TRandom3 > noiseInjector_
Generates Gaussian noise on top of real hits.
TF1 pulseFunc_
Detailed Description
Emulate the digitization procedure performed by the HGCROC.
This object emulates how the chip converts the analog signal into DIGI samples. With that in mind, the digitize method converts a set of voltages and times into the DIGI.
This object does not do everything related to subsystem information. It does not simulate noise within the empty channels, and it does not convert simulated energy depositions into voltages. These tasks depend on the detector construction, so they are left to the individual subsystem producers.
@TODO time phase setting relative to target t=0ns using electronic IDs
@TODO accurately model recovering from saturation (TOT Mode). Currently, we just have all the samples after the sample triggering TOT mode rail.
Definition at line 39 of file HgcrocEmulator.h.
Constructor & Destructor Documentation
HgcrocEmulator()
ldmx::HgcrocEmulator::HgcrocEmulator (const framework::config::Parameters & ps)
Constructor
Configures the chip emulator using the passed parameters.
Definition at line 6 of file HgcrocEmulator.cxx.
{
  // settings of readout chip that are the same for all chips
  //  used  in actual digitization
  noise_ = ps.getParameter<bool>("noise");
  noiseRMS_ = ps.getParameter<double>("noiseRMS");
  timingJitter_ = ps.getParameter<double>("timingJitter");
  rateUpSlope_ = ps.getParameter<double>("rateUpSlope");
  timeUpSlope_ = ps.getParameter<double>("timeUpSlope");
  rateDnSlope_ = ps.getParameter<double>("rateDnSlope");
  timeDnSlope_ = ps.getParameter<double>("timeDnSlope");
  timePeak_ = ps.getParameter<double>("timePeak");
  clockCycle_ = ps.getParameter<double>("clockCycle");
  nADCs_ = ps.getParameter<int>("nADCs");
  iSOI_ = ps.getParameter<int>("iSOI");
  // Time -> clock counts conversion
  //  time [ns] * ( 2^10 / max time in ns ) = clock counts
  ns_ = 1024. / clockCycle_;
  hit_merge_ns_ = 0.05;  // combine at 50 ps level
  // Configure the pulse shape function
  pulseFunc_ =
      TF1("pulseFunc",
          "[0]*((1.0+exp([1]*(-[2]+[3])))*(1.0+exp([5]*(-[6]+[3]))))/"
          "((1.0+exp([1]*(x-[2]+[3]-[4])))*(1.0+exp([5]*(x-[6]+[3]-[4]))))",
          0.0, (double)nADCs_ * clockCycle_);
  pulseFunc_.FixParameter(0, 1.0);  // amplitude is set externally
  pulseFunc_.FixParameter(1, rateUpSlope_);
  pulseFunc_.FixParameter(2, timeUpSlope_);
  pulseFunc_.FixParameter(3, timePeak_);
  pulseFunc_.FixParameter(4, 0);  // not using time offset in this way
  pulseFunc_.FixParameter(5, rateDnSlope_);
  pulseFunc_.FixParameter(6, timeDnSlope_);
}
References clockCycle_, framework::config::Parameters::getParameter(), hit_merge_ns_, iSOI_, nADCs_, noise_, noiseRMS_, ns_, pulseFunc_, rateDnSlope_, rateUpSlope_, timeDnSlope_, timePeak_, timeUpSlope_, and timingJitter_.
~HgcrocEmulator()
ldmx::HgcrocEmulator::~HgcrocEmulator () inline
Destructor
Definition at line 49 of file HgcrocEmulator.h.
{}
Member Function Documentation
condition()
void ldmx::HgcrocEmulator::condition (const conditions::DoubleTableCondition & table) inline
Set Conditions
Passes the chips conditions to be cached here and used later in digitization.
Parameters
table conditions::DoubleTableConditions to be used for chip parameters
Definition at line 72 of file HgcrocEmulator.h.
{
    // reset cache of column numbers if table changes
    if (&table != chipConditions_) conditionNamesToIndex_.clear();
    chipConditions_ = &table;
  }
References chipConditions_, and conditionNamesToIndex_.
digitize()
bool ldmx::HgcrocEmulator::digitize (const int & channelID, std::vector< std::pair< double, double > > & arriving_pulses, std::vector< ldmx::HgcrocDigiCollection::Sample > & digiToAdd) const
Digitize the signals from the simulated hits
This is where the hefty amount of work is done.
0. Prepare for Emulation
Clear input list of digi samples
Get conditions for the current chip
Sort the input sim voltage hits by amplitude
Combine input simulated hits into one CompositePulse to digitize.
This composite pulse decides whether to merge two simulated hits into one larger pulse depending on how close they are in time.
Add a timing jitter TODO
Go through sampling baskets one-by-one
If enter pulse goes above tot threshold, then enter TOT readout mode, digitize, and return true.
If pulse never goes above tot threshold, then only return true if the voltage sample taken in the SOI is above the readout threshold.
ADC Mode
Here, we measure the height of the pulse once per clock cycle. This leaves us with nADCs_ samples for each digitized hit. The voltage measurements are converted to ADC counts using the parameter gain_.
The time of arrival (TOA) is zero unless the amplitude is greater than toaThreshold_. Then the TOA is set to the point the pulse crosses the toaThreshold_ with respect to the current clock window. The time measurements are converted to clock counts using 2^10=1024 and clockCycle_.
Both the tot_complete_ and tot_progress_ flags are set to false for all the samples.
TOT Mode
Here, we measure how long the chip is in saturation. This is calculated using the drain rate and assuming a linear drain of the charge off of the chip.
The charge deposited on the chip is converted from the pulse triggering TOT without including the pedestal. The pedestal is included in the pulse when determining if the pulse should enter TOT mode.
Thus, TOT = charge deposited / drain rate and TOA is calculated as before, seeing when the pulse crossed the TOA threshold.
Pulse Measurement
All "measurements" of the pulse use the object CompositePulse. This function incorporates the pedestal_ and linearly adds all the pulses at a variety of times. The pulses at different times are "merged" upon addition to the composite pulse depending on how close they are. This is done in a single pass, so we might end up with pulses closer than the provided separation time.
Note
For more realism, some chip parameters should change depending on the chip they are coming from. This should be modified here, with a package of "HgcrocConditions" passed to this function to configure the emulator before digitizing.
Parameters
[in] channelID raw integer ID for this readout channel
[in] arriving_pulses pairs of (voltage,time) of hits arriving at the chip
[out] digiToAdd digi that will be filled with the samples from the chip
Returns
true if digis were constructed (false if hit was below readout)
the time here is nominal (zero gives peak if hit.second is zero)
Definition at line 46 of file HgcrocEmulator.cxx.
{
  // step 0: prepare ourselves for emulation
  digiToAdd.clear();  // make sure it is clean
  // Configure chip settings based off of table (that may have been passed)
  double totMax = getCondition(channelID, "TOT_MAX");
  double padCapacitance = getCondition(channelID, "PAD_CAPACITANCE");
  double gain = this->gain(channelID);
  double pedestal = this->pedestal(channelID);
  double toaThreshold = getCondition(channelID, "TOA_THRESHOLD");
  double totThreshold = getCondition(channelID, "TOT_THRESHOLD");
  // measTime defines the point in the BX where an in-time
  //  (time=0 in times vector) hit would arrive.
  // Used to determine BX boundaries and TOA behavior.
  double measTime = getCondition(channelID, "MEAS_TIME");
  double drainRate = getCondition(channelID, "DRAIN_RATE");
  double readoutThresholdFloat = this->readoutThreshold(channelID);
  int readoutThreshold = int(readoutThresholdFloat);
  // sort by amplitude
  //  ==> makes sure that puleses are merged towards higher ones
  std::sort(
      arriving_pulses.begin(), arriving_pulses.end(),
      [](const std::pair<double, double> &a,
         const std::pair<double, double> &b) { return a.first > b.first; });
  // step 1: gather voltages into groups separated by (programmable) ns, single
  // pass
  CompositePulse pulse(pulseFunc_, gain, pedestal);
  for (auto hit : arriving_pulses) pulse.addOrMerge(hit, hit_merge_ns_);
  // TODO step 2: add timing jitter
  // if (noise_) pulse.jitter();
  // step 3: go through each BX sample one by one
  bool doReadout = false;
  bool wasTOA = false;
  for (int iADC = 0; iADC < nADCs_; iADC++) {
    double startBX = (iADC - iSOI_) * clockCycle_ - measTime;
    // step 3b: check each merged hit to see if it peaks in this BX.  If so,
    // check its peak time to see if it's over TOT or TOA.
    bool startTOT = false;
    bool overTOA = false;
    double toverTOA = -1;
    double toverTOT = -1;
    for (auto hit : pulse.hits()) {
      int hitBX = int((hit.second + measTime) / clockCycle_ + iSOI_);
      if (hitBX != iADC)
        continue;  // if this hit wasn't in the current BX, continue...
      double vpeak = pulse(hit.second);
      if (vpeak > totThreshold) {
        startTOT = true;
        if (toverTOT < hit.second)
          toverTOT = hit.second;  // use the latest time in the window
      }
      if (vpeak > toaThreshold) {
        if (!overTOA || hit.second < toverTOA) toverTOA = hit.second;
        overTOA = true;
      }
    }  // loop over sim hits
    // check for the case of a TOA even though the peak is in the next BX
    if (!overTOA && pulse(startBX + clockCycle_) > toaThreshold) {
      if (pulse(startBX) < toaThreshold) {
        // pulse crossed TOA threshold somewhere between the start of this
        // basket and the end
        overTOA = true;
        toverTOA = startBX + clockCycle_;
      }
    }
    if (startTOT) {
      // above TOT threshold -> do TOT readout mode
      // @TODO NO NOISE
      //  CompositePulse includes pedestal, we need to remove it
      //  when calculating the charge deposited.
      double charge_deposited =
          (pulse(toverTOT) - gain * pedestal) * padCapacitance;
      // Measure Time Over Threshold (TOT) by using the drain rate.
      //  1. Use drain rate to see how long it takes for the charge to drain off
      //  2. Translate this into DIGI samples
      // Assume linear drain with slope drain rate:
      //      y-intercept = pulse amplitude
      //      slope       = drain rate
      //  ==> x-intercept = amplitude / rate
      // actual time over threshold using the real signal voltage amplitude
      double tot = charge_deposited / drainRate;
      // calculate the index that tot will complete on
      int num_whole_clocks = int(tot / clockCycle_);
      // calculate the TDC counts for this tot measurement
      //  internally, the chip uses 12 bits (2^12 = 4096)
      //  to measure a maximum of tot Max [ns]
      int tdc_counts = int(tot * 4096 / totMax) + pedestal;
      // were we already over TOA?  TOT is reported in BX where TOA went over
      // threshold...
      int toa{0};
      if (wasTOA) {
        // TOA was in the past
        toa = digiToAdd.back().toa();
      } else {
        // TOA is here and we need to find it
        double timecross = pulse.findCrossing(startBX, toverTOT, toaThreshold);
        toa = int((timecross - startBX) * ns_);
        // keep inside valid limits
        if (toa == 0) toa = 1;
        if (toa > 1023) toa = 1023;
      }
      digiToAdd.emplace_back(
          false, true,  // mark as a TOT measurement
          (iADC > 0) ? digiToAdd.at(iADC - 1).adc_t()
                     : pedestal,  // ADC t-1 is first measurement
          tdc_counts,             // TOT
          toa                     // TOA is third measurement
      );
      // TODO: properly handle saturation and recovery, eventually.
      // Now just kill everything...
      while (digiToAdd.size() < nADCs_) {
        digiToAdd.emplace_back(true, false,  // flags to mark type of sample
                               0x3FF, 0x3FF, 0);
      }
      return true;  // always readout
    } else {
      // determine the voltage at the sampling time
      double bxvolts = pulse((iADC - iSOI_) * clockCycle_);
      // add noise if requested
      if (noise_) bxvolts += noise(channelID);
      // convert to integer and keep in range (handle low and high saturation)
      int adc = bxvolts / gain;
      if (adc < 0) adc = 0;
      if (adc > 1023) adc = 1023;
      // check for TOA
      int toa(0);
      if (pulse(startBX) < toaThreshold && overTOA) {
        double timecross = pulse.findCrossing(startBX, toverTOA, toaThreshold);
        toa = int((timecross - startBX) * ns_);
        // keep inside valid limits
        if (toa == 0) toa = 1;
        if (toa > 1023) toa = 1023;
        wasTOA = true;
      } else {
        wasTOA = false;
      }
      digiToAdd.emplace_back(
          false, false,  // use flags to mark this sample as an ADC measurement
          (iADC > 0) ? digiToAdd.at(iADC - 1).adc_t()
                     : pedestal,  // ADC t-1 is first measurement
          adc,                    // ADC[t] is the second field
          toa                     // TOA is third measurement
      );
    }  // TOT or ADC Mode
  }    // sampling baskets
  // we only get here if we never went into TOT mode
  // check the SOI to see if we should read out
  return digiToAdd.at(iSOI_).adc_t() >= readoutThreshold;
}  // HgcrocEmulator::digitize
References ldmx::HgcrocEmulator::CompositePulse::addOrMerge(), clockCycle_, ldmx::HgcrocEmulator::CompositePulse::findCrossing(), gain(), getCondition(), hit_merge_ns_, ldmx::HgcrocEmulator::CompositePulse::hits(), iSOI_, nADCs_, noise(), noise_, ns_, pedestal(), pulseFunc_, and readoutThreshold().
gain()
double ldmx::HgcrocEmulator::gain (const int & channelID) const inline
Gain for input channel.
Definition at line 193 of file HgcrocEmulator.h.
{
    return getCondition(channelID, "GAIN");
  }
References getCondition().
Referenced by digitize(), noiseDigi(), and ldmx::HgcrocEmulator::CompositePulse::setGainPedestal().
getCondition()
double ldmx::HgcrocEmulator::getCondition (int id, const std::string & name) const inline private
Get condition for input chip ID, condition name, and default value
Parameters
[in] id chip global integer ID used in condition table
[in] name std::string name of chip parameter in table
[in] def default value for parameter if not found in table (or table not set)
Returns
value of chip parameter
Definition at line 217 of file HgcrocEmulator.h.
{
    // check if emulator has been passed a table of conditions
    if (!chipConditions_) {
      EXCEPTION_RAISE("HgcrocCond",
          "HGC ROC Emulator was not given a conditions table.");
    }
    // cache column index for the input name
    if (conditionNamesToIndex_.count(name) == 0)
      conditionNamesToIndex_[name] = chipConditions_->getColumnNumber(name);
    // get condition
    return chipConditions_->get(id, conditionNamesToIndex_.at(name));
  }
References chipConditions_, conditionNamesToIndex_, conditions::HomogenousTableCondition< T >::get(), and conditions::BaseTableCondition::getColumnNumber().
Referenced by digitize(), gain(), pedestal(), and readoutThreshold().
hasSeed()
bool ldmx::HgcrocEmulator::hasSeed () const inline
Check if emulator has been seeded
Returns
true if random generator has been seeded
Definition at line 55 of file HgcrocEmulator.h.
{ return noiseInjector_.get() != nullptr; }
References noiseInjector_.
noise()
double ldmx::HgcrocEmulator::noise (const int & channelID) const inline
Get random noise amplitdue for input channel [mV]
Currently, we don't have the noise separated by channel, but since this is a possibility in the future, I've put in the (required but unused) parameter.
Parameters
[in] channelID - UNUSED
Returns
electronic noise amplitude [mV] above pedestal
Definition at line 188 of file HgcrocEmulator.h.
{
    return noiseInjector_->Gaus(0,noiseRMS_);
  };
References noiseInjector_, and noiseRMS_.
Referenced by digitize(), and noiseDigi().
noiseDigi()
std::vector< ldmx::HgcrocDigiCollection::Sample > ldmx::HgcrocEmulator::noiseDigi (const int & channel, const double & soi_amplitude = 0) const
Generate a digi of pure noise
The (optional) input soi amplitude is added on-top of pedestal in the SOI after being divided by the gain. This is designed to be close to the output amplitudes generated by the noise generator.
Note
We don't go into TOT mode. We simply fill a DIGI with ADC samples with noise on top of the pedestal, including the SOI amplitude if provided.
We set the TOA for each of the samples created to 0 (or "not found"), so this also indirectly assumes we are below the TOA threshold as well as below the TOT threshold.
Parameters
[in] channel raw integer ID for this readout channel
[in] soi_amplitude amplitude of noise "pulse" in mV
Returns
DIGI of pure noise
Definition at line 227 of file HgcrocEmulator.cxx.
{
  // get chip conditions from emulator
  double pedestal{this->pedestal(channel)};
  double gain{this->gain(channel)};
  // fill a digi with noise samples
  std::vector<ldmx::HgcrocDigiCollection::Sample> noise_digi;
  for (int iADC{0}; iADC<nADCs_; iADC++) {
    // gen noise for ADC samples
    int adc_tm1{pedestal};
    if (iADC > 0)
      adc_tm1 = noise_digi.at(iADC-1).adc_t();
    else
      adc_tm1 += noise(channel)/gain;
    int adc_t{pedestal + noise(channel)/gain};
    if (iADC == iSOI_)
      adc_t += soi_amplitude/gain;
    // set toa to 0 (not determined)
    // put new sample into noise digi
    noise_digi.emplace_back(false,false,adc_tm1,adc_t,0);
  }  // samples in noise digi
  return noise_digi;
}
References gain(), iSOI_, nADCs_, noise(), and pedestal().
pedestal()
double ldmx::HgcrocEmulator::pedestal (const int & id) const inline
Pedestal [ADC Counts] for input channel.
Definition at line 198 of file HgcrocEmulator.h.
{
    return getCondition(id, "PEDESTAL");
  }
References getCondition().
Referenced by digitize(), noiseDigi(), and ldmx::HgcrocEmulator::CompositePulse::setGainPedestal().
readoutThreshold()
double ldmx::HgcrocEmulator::readoutThreshold (const int & id) const inline
Readout Threshold (ADC Counts)
Definition at line 203 of file HgcrocEmulator.h.
{
    return getCondition(id, "READOUT_THRESHOLD");
  }
References getCondition().
Referenced by digitize().
seedGenerator()
void ldmx::HgcrocEmulator::seedGenerator (uint64_t seed)
Seed the emulator for random number generation
Parameters
[in] seed integer to use as random seed
Definition at line 42 of file HgcrocEmulator.cxx.
{
  noiseInjector_ = std::make_unique<TRandom3>(seed);
}
References noiseInjector_.
Member Data Documentation
chipConditions_
const conditions::DoubleTableCondition* ldmx::HgcrocEmulator::chipConditions_ {nullptr} private
Handle to table of chip-dependent conditions
The defaults are listed below and are separate parameters passed through the python configuration.
Definition at line 412 of file HgcrocEmulator.h.
Referenced by condition(), and getCondition().
clockCycle_
double ldmx::HgcrocEmulator::clockCycle_ private
Time interval for chip clock [ns].
Definition at line 376 of file HgcrocEmulator.h.
Referenced by digitize(), and HgcrocEmulator().
conditionNamesToIndex_
std::map<std::string, int> ldmx::HgcrocEmulator::conditionNamesToIndex_ mutable private
Map of condition names to column numbers
mutable so that we can update the cached column values in getCondition during processing.
Definition at line 420 of file HgcrocEmulator.h.
Referenced by condition(), and getCondition().
hit_merge_ns_
double ldmx::HgcrocEmulator::hit_merge_ns_ private
Hit merging time [ns].
Definition at line 400 of file HgcrocEmulator.h.
Referenced by digitize(), and HgcrocEmulator().
iSOI_
int ldmx::HgcrocEmulator::iSOI_ private
Index for the Sample Of Interest in the list of digi samples.
Definition at line 370 of file HgcrocEmulator.h.
Referenced by digitize(), HgcrocEmulator(), and noiseDigi().
nADCs_
int ldmx::HgcrocEmulator::nADCs_ private
Depth of ADC buffer.
Definition at line 367 of file HgcrocEmulator.h.
Referenced by digitize(), HgcrocEmulator(), and noiseDigi().
noise_
bool ldmx::HgcrocEmulator::noise_ {true} private
Put noise in channels, only configure to false if testing.
Definition at line 364 of file HgcrocEmulator.h.
Referenced by digitize(), and HgcrocEmulator().
noiseInjector_
std::unique_ptr<TRandom3> ldmx::HgcrocEmulator::noiseInjector_ private
Generates Gaussian noise on top of real hits.
Definition at line 427 of file HgcrocEmulator.h.
Referenced by hasSeed(), noise(), and seedGenerator().
noiseRMS_
double ldmx::HgcrocEmulator::noiseRMS_ private
Noise RMS [mV].
Definition at line 373 of file HgcrocEmulator.h.
Referenced by HgcrocEmulator(), and noise().
ns_
double ldmx::HgcrocEmulator::ns_ private
Conversion from time [ns] to counts.
Definition at line 382 of file HgcrocEmulator.h.
Referenced by digitize(), and HgcrocEmulator().
pulseFunc_
TF1 ldmx::HgcrocEmulator::pulseFunc_ mutable private
Functional shape of signal pulse in time
Shape parameters are hardcoded into the function currently. Pulse Shape: [0]*((1.0+exp([1]*(-[2]+[3])))*(1.0+exp([5]*(-[6]+[3]))))/((1.0+exp([1]*(x-[2]+[3]-[4])))*(1.0+exp([5]*(x-[6]+[3]-[4])))) p[0] = amplitude (height of peak in mV) p[1] = rate of up slope - rateUpSlope_ p[2] = time of up slope relative to shape fit - timeUpSlope_ p[3] = time of peak relative to shape fit - timePeak_ p[4] = peak time (related to time of hit [ns]) p[5] = rate of down slope - rateDnSlope_ p[6] = time of down slope relative to shape fit - timeDnSlope_
Definition at line 449 of file HgcrocEmulator.h.
Referenced by digitize(), and HgcrocEmulator().
rateDnSlope_
double ldmx::HgcrocEmulator::rateDnSlope_ private
Rate of Down Slope in Pulse Shape [1/ns].
Definition at line 391 of file HgcrocEmulator.h.
Referenced by HgcrocEmulator().
rateUpSlope_
double ldmx::HgcrocEmulator::rateUpSlope_ private
Rate of Up Slope in Pulse Shape [1/ns].
Definition at line 385 of file HgcrocEmulator.h.
Referenced by HgcrocEmulator().
timeDnSlope_
double ldmx::HgcrocEmulator::timeDnSlope_ private
Time of Down Slope relative to Pulse Shape Fit [ns].
Definition at line 394 of file HgcrocEmulator.h.
Referenced by HgcrocEmulator().
timePeak_
double ldmx::HgcrocEmulator::timePeak_ private
Time of Peak relative to pulse shape fit [ns].
Definition at line 397 of file HgcrocEmulator.h.
Referenced by HgcrocEmulator().
timeUpSlope_
double ldmx::HgcrocEmulator::timeUpSlope_ private
Time of Up Slope relative to Pulse Shape Fit [ns].
Definition at line 388 of file HgcrocEmulator.h.
Referenced by HgcrocEmulator().
timingJitter_
double ldmx::HgcrocEmulator::timingJitter_ private
Jitter of timing mechanism in the chip [ns].
Definition at line 379 of file HgcrocEmulator.h.
Referenced by HgcrocEmulator().
The documentation for this class was generated from the following files:
Tools/include/Tools/HgcrocEmulator.h
Tools/src/Tools/HgcrocEmulator.cxx