LDMX Software: ldmx::HcalDigiID Class Reference
ldmx::HcalDigiID Class Reference
Extension of HcalAbstractID providing access to HCal digi information.
#include <HcalDigiID.h>
Public Member Functions
HcalDigiID ()
HcalDigiID (RawValue rawid)
HcalDigiID (const DetectorID id)
HcalDigiID (unsigned int section, unsigned int layer, unsigned int strip, unsigned int end)
int getSection () const
int section () const
int layer () const
int getLayerID () const
int getStrip () const
int strip () const
int end () const
bool isNegativeEnd () const
Public Member Functions inherited from ldmx::HcalAbstractID
HcalAbstractID ()
HcalAbstractID (RawValue rawid)
HcalAbstractID (const DetectorID id)
HcalAbstractID (unsigned int bar_type, unsigned int payload)
int bar_type () const
int payload () const
Public Member Functions inherited from ldmx::DetectorID
DetectorID ()
Class constructor for a null DetectorID.
DetectorID (RawValue rawid)
Class constructor from a raw 32-bit integer.
DetectorID (SubdetectorIDType sdtype, RawValue raw_subpayload)
bool null () const
SubdetectorIDType subdet () const
RawValue raw () const
void setRawValue (RawValue rawValue)
bool operator< (const DetectorID &id) const
bool operator== (const DetectorID &id) const
bool operator!= (const DetectorID &id) const
Static Public Member Functions
static void createInterpreters ()
Static Public Attributes
static const RawValue END_MASK {0x1}
static const RawValue END_SHIFT {19}
static const RawValue SECTION_MASK {0x7}
static const RawValue SECTION_SHIFT {16}
static const RawValue LAYER_MASK {0xFF}
static const RawValue LAYER_SHIFT {8}
static const RawValue STRIP_MASK {0xFF}
static const RawValue STRIP_SHIFT {0}
Static Public Attributes inherited from ldmx::HcalAbstractID
static const RawValue BAR_TYPE_MASK {0x7}
static const RawValue BAR_TYPE_SHIFT {23}
static const RawValue HCAL_PAYLOAD_MASK {0x007FFFFF}
Static Public Attributes inherited from ldmx::DetectorID
static const RawValue SUBDETECTORID_MASK {0x3F}
static const RawValue SUBDETECTORID_SHIFT {26}
static const RawValue SUBDETECTOR_PAYLOAD_MASK {0x3FFFFFF}
Additional Inherited Members
Public Types inherited from ldmx::HcalAbstractID
enum HcalBarType { Global = 0 , Digi = 1 , Trigger = 2 , Special = 7 }
Public Types inherited from ldmx::DetectorID
typedef uint32_t RawValue
Protected Attributes inherited from ldmx::DetectorID
RawValue id_
The raw, packed value of the ID.
Detailed Description
Extension of HcalAbstractID providing access to HCal digi information.
Definition at line 13 of file HcalDigiID.h.
Constructor & Destructor Documentation
HcalDigiID() [1/4]
ldmx::HcalDigiID::HcalDigiID () inline
Empty HCAL id (but not null!)
Definition at line 27 of file HcalDigiID.h.
: HcalAbstractID() {}
HcalDigiID() [2/4]
ldmx::HcalDigiID::HcalDigiID (RawValue rawid) inline
Create from raw number
Definition at line 32 of file HcalDigiID.h.
                             : HcalAbstractID(rawid) {
    if (!null() && bar_type() != Digi) {
      EXCEPTION_RAISE(
          "DetectorIDMismatch",
          "Attempted to create HcalDigiID from mismatched Hcal bar_type " +
              std::to_string(bar_type()));
    }
  }
References ldmx::HcalAbstractID::bar_type().
HcalDigiID() [3/4]
ldmx::HcalDigiID::HcalDigiID (const DetectorID id) inline
Create from a DetectorID, but check
Definition at line 44 of file HcalDigiID.h.
                                  : HcalAbstractID(id) {
    if (!null() && bar_type() != Digi) {
      EXCEPTION_RAISE(
          "DetectorIDMismatch",
          "Attempted to create HcalDigiID from mismatched Hcal bar_type " +
              std::to_string(bar_type()));
    }
  }
References ldmx::HcalAbstractID::bar_type().
HcalDigiID() [4/4]
ldmx::HcalDigiID::HcalDigiID (unsigned int section, unsigned int layer, unsigned int strip, unsigned int end) inline
Create from pieces
Definition at line 56 of file HcalDigiID.h.
      : HcalAbstractID(Digi, 0) {
    id_ |= (section & SECTION_MASK) << SECTION_SHIFT;
    id_ |= (layer & LAYER_MASK) << LAYER_SHIFT;
    id_ |= (strip & STRIP_MASK) << STRIP_SHIFT;
    id_ |= (end & END_MASK) << END_SHIFT;
  }
References end(), ldmx::DetectorID::id_, layer(), section(), and strip().
Member Function Documentation
createInterpreters()
void ldmx::HcalDigiID::createInterpreters () static
Definition at line 15 of file HcalDigiID.cxx.
{
  IDField::IDFieldList fields;
  fields.push_back(new IDField("subdetector", 0, SUBDETECTORID_SHIFT, 31));
  fields.push_back(
      new IDField("section", 1, SECTION_SHIFT,
                  SECTION_SHIFT + IDField::countOnes(SECTION_MASK) - 1));
  fields.push_back(
      new IDField("layer", 2, LAYER_SHIFT,
                  LAYER_SHIFT + IDField::countOnes(LAYER_MASK) - 1));
  fields.push_back(
      new IDField("strip", 3, STRIP_SHIFT,
                  STRIP_SHIFT + IDField::countOnes(STRIP_MASK) - 1));
  fields.push_back(new IDField("end", 4, END_SHIFT,
                               END_SHIFT + IDField::countOnes(END_MASK) - 1));
  DetectorIDInterpreter::registerInterpreter(
      SD_HCAL, HcalAbstractID::BAR_TYPE_MASK << HcalAbstractID::BAR_TYPE_SHIFT,
      HcalAbstractID::Digi << HcalAbstractID::BAR_TYPE_SHIFT, fields);
}
end()
int ldmx::HcalDigiID::end () const inline
Get the value of the 'end' field from the ID.
Returns
The value of the 'end' field.
Definition at line 105 of file HcalDigiID.h.
{ return (id_ >> END_SHIFT) & END_MASK; }
References ldmx::DetectorID::id_.
Referenced by hcal::HcalTriggerGeometry::belongsToQuad(), HcalDigiID(), and isNegativeEnd().
getLayerID()
int ldmx::HcalDigiID::getLayerID () const inline
Get the value of the layer field from the ID.
Returns
The value of the layer field.
Definition at line 87 of file HcalDigiID.h.
{ return (id_ >> LAYER_SHIFT) & LAYER_MASK; }
References ldmx::DetectorID::id_.
getSection()
int ldmx::HcalDigiID::getSection () const inline
Get the value of the 'section' field from the ID.
Returns
The value of the 'section' field.
Definition at line 69 of file HcalDigiID.h.
{ return (id_ >> SECTION_SHIFT) & SECTION_MASK; }
References ldmx::DetectorID::id_.
getStrip()
int ldmx::HcalDigiID::getStrip () const inline
Get the value of the 'strip' field from the ID.
Returns
The value of 'strip' field.
Definition at line 93 of file HcalDigiID.h.
{ return (id_ >> STRIP_SHIFT) & STRIP_MASK; }
References ldmx::DetectorID::id_.
isNegativeEnd()
bool ldmx::HcalDigiID::isNegativeEnd () const inline
Get whether the 'end' field from the ID is negative.
Returns
True if the end of the strip is negative
Definition at line 111 of file HcalDigiID.h.
{
    if (end() == 1)
      return true;
    else
      return false;
  }
References end().
Referenced by hcal::HcalRecProducer::produce().
layer()
int ldmx::HcalDigiID::layer () const inline
Get the value of the layer field from the ID.
Returns
The value of the layer field.
Definition at line 81 of file HcalDigiID.h.
{ return (id_ >> LAYER_SHIFT) & LAYER_MASK; }
References ldmx::DetectorID::id_.
Referenced by hcal::HcalTriggerGeometry::belongsToQuad(), HcalDigiID(), and hcal::HcalRecProducer::produce().
section()
int ldmx::HcalDigiID::section () const inline
Get the value of the 'section' field from the ID.
Returns
The value of the 'section' field.
Definition at line 75 of file HcalDigiID.h.
{ return (id_ >> SECTION_SHIFT) & SECTION_MASK; }
References ldmx::DetectorID::id_.
Referenced by hcal::HcalTriggerGeometry::belongsToQuad(), HcalDigiID(), and hcal::HcalRecProducer::produce().
strip()
int ldmx::HcalDigiID::strip () const inline
Get the value of the 'strip' field from the ID.
Returns
The value of 'strip' field.
Definition at line 99 of file HcalDigiID.h.
{ return (id_ >> STRIP_SHIFT) & STRIP_MASK; }
References ldmx::DetectorID::id_.
Referenced by hcal::HcalTriggerGeometry::belongsToQuad(), HcalDigiID(), and hcal::HcalRecProducer::produce().
Member Data Documentation
END_MASK
const RawValue ldmx::HcalDigiID::END_MASK {0x1} static
Definition at line 15 of file HcalDigiID.h.
END_SHIFT
const RawValue ldmx::HcalDigiID::END_SHIFT {19} static
Definition at line 16 of file HcalDigiID.h.
LAYER_MASK
const RawValue ldmx::HcalDigiID::LAYER_MASK {0xFF} static
Definition at line 19 of file HcalDigiID.h.
LAYER_SHIFT
const RawValue ldmx::HcalDigiID::LAYER_SHIFT {8} static
Definition at line 20 of file HcalDigiID.h.
SECTION_MASK
const RawValue ldmx::HcalDigiID::SECTION_MASK {0x7} static
Definition at line 17 of file HcalDigiID.h.
SECTION_SHIFT
const RawValue ldmx::HcalDigiID::SECTION_SHIFT {16} static
Definition at line 18 of file HcalDigiID.h.
STRIP_MASK
const RawValue ldmx::HcalDigiID::STRIP_MASK {0xFF} static
Definition at line 21 of file HcalDigiID.h.
STRIP_SHIFT
const RawValue ldmx::HcalDigiID::STRIP_SHIFT {0} static
Definition at line 22 of file HcalDigiID.h.
The documentation for this class was generated from the following files:
DetDescr/include/DetDescr/HcalDigiID.h
DetDescr/src/DetDescr/HcalDigiID.cxx