LDMX Software: framework::HistogramHelper Class Reference
framework::HistogramHelper Class Reference
#include <Histograms.h>
Public Member Functions
HistogramHelper (const std::string &name)
void setWeight (double w)
void create (const std::string &name, const std::string &xLabel, const double &bins, const double &xmin, const double &xmax)
void create (const std::string &name, const std::string &xLabel, const std::vector< double > &bins)
void create (const std::string &name, const std::string &xLabel, const double &xbins, const double &xmin, const double &xmax, const std::string &yLabel, const double &ybins, const double &ymin, const double &ymax)
void create (const std::string &name, const std::string &xLabel, const std::vector< double > &xbins, const std::string &yLabel, const std::vector< double > &ybins)
void fill (const std::string &name, const double &val)
void fill (const std::string &name, const double &valx, const double &valy)
TH1 * get (const std::string &name)
Private Attributes
double theWeight_ {1.}
The weight to fill histograms with.
std::string name_
The name of the processor that this helper is assigned to.
Detailed Description
Interface class between an EventProcessor and the HistogramPool
Definition at line 72 of file Histograms.h.
Constructor & Destructor Documentation
HistogramHelper()
framework::HistogramHelper::HistogramHelper (const std::string & name) inline
Constructor
Sets the name
Definition at line 86 of file Histograms.h.
: name_(name) {}
Member Function Documentation
create() [1/4]
void framework::HistogramHelper::create (const std::string & name, const std::string & xLabel, const double & bins, const double & xmin, const double & xmax)
Create a ROOT 1D histogram of type TH1F and pool it for later use.
Note
Does not check if another histogram of the same name is in use.
Parameters
name Name of the histogram. This will also be used as a title.
xLabel Title of the x axis.
bins Total number of histogram bins.
xmin The lower histogram limit.
xmax The upper histogram limit.
Definition at line 54 of file Histograms.cxx.
{
  std::string fullName = name_ + "_" + name;
  // Create a histogram of type T
  auto hist = new TH1F(fullName.c_str(), fullName.c_str(), bins, xmin, xmax);
  // Set the title
  hist->SetTitle("");
  // Set the x-axis label
  hist->GetXaxis()->SetTitle(xLabel.c_str());
  hist->GetXaxis()->CenterTitle();
  // Insert it into the pool of histograms for later use
  HistogramPool::getInstance().insert(fullName, hist);
}
References framework::HistogramPool::getInstance(), framework::HistogramPool::insert(), and name_.
Referenced by dqm::SimObjects::createCalorimeterHists(), framework::EventProcessor::createHistograms(), dqm::SimObjects::createTrackerHists(), dqm::SimObjects::onProcessStart(), dqm::Trigger::onProcessStart(), dqm::TrigScintClusterDQM::onProcessStart(), dqm::TrigScintDQM::onProcessStart(), dqm::TrigScintHitDQM::onProcessStart(), dqm::TrigScintTrackDQM::onProcessStart(), and dqm::HCalRawDigi::onProcessStart().
create() [2/4]
void framework::HistogramHelper::create (const std::string & name, const std::string & xLabel, const double & xbins, const double & xmin, const double & xmax, const std::string & yLabel, const double & ybins, const double & ymin, const double & ymax)
Create a ROOT 2D histogram of type TH2F and pool it for later use.
Note
Does not check if another histogram of the same name is in use.
Parameters
name Name of the histogram. This will also be used as a title.
xLabel Title of the x axis.
xbins Total number of histogram bins in x.
xmin The lower histogram limit in x.
xmax The upper histogram limit in x.
yLabel Title of the x axis.
ybins Total number of histogram bins in y.
ymin The lower histogram limit in y.
ymax The upper histogram limit in y.
Definition at line 98 of file Histograms.cxx.
{
  std::string fullName = name_ + "_" + name;
  // Create a histogram of type T
  auto hist = new TH2F(fullName.c_str(), fullName.c_str(), xbins, xmin, xmax,
                       ybins, ymin, ymax);
  // Set the title
  hist->SetTitle("");
  // Set the x-axis label
  hist->GetXaxis()->SetTitle(xLabel.c_str());
  hist->GetXaxis()->CenterTitle();
  // Set the x-axis label
  hist->GetYaxis()->SetTitle(yLabel.c_str());
  hist->GetYaxis()->CenterTitle();
  // Insert it into the pool of histograms for later use
  HistogramPool::getInstance().insert(fullName, hist);
}
References framework::HistogramPool::getInstance(), framework::HistogramPool::insert(), and name_.
create() [3/4]
void framework::HistogramHelper::create (const std::string & name, const std::string & xLabel, const std::vector< double > & bins)
Create a ROOT 1D histogram of type TH1F and pool it for later use.
Note
Does not check if another histogram of the same name is in use.
Parameters
name Name of the histogram. This will also be used as a title.
xLabel Title of the x axis.
bins vector of bin edges
Definition at line 73 of file Histograms.cxx.
{
  std::string fullName = name_ + "_" + name;
  // copy bin edges into a C98 form acceptable by ROOT
  int nbins = bins.size() - 1;
  double* binEdges = new double[bins.size()];
  for (unsigned int iBin = 0; iBin < bins.size(); iBin++)
    binEdges[iBin] = bins.at(iBin);
  auto hist = new TH1F(fullName.c_str(), fullName.c_str(), nbins, binEdges);
  delete[] binEdges;  // cleanup
  // Set the title
  hist->SetTitle("");
  // Set the x-axis label
  hist->GetXaxis()->SetTitle(xLabel.c_str());
  hist->GetXaxis()->CenterTitle();
  // Insert it into the pool of histograms for later use
  HistogramPool::getInstance().insert(fullName, hist);
}
References framework::HistogramPool::getInstance(), framework::HistogramPool::insert(), and name_.
create() [4/4]
void framework::HistogramHelper::create (const std::string & name, const std::string & xLabel, const std::vector< double > & xbins, const std::string & yLabel, const std::vector< double > & ybins)
Create a ROOT 2D histogram of type TH2F and pool it for later use.
Note
Does not check if another histogram of the same name is in use.
Parameters
name Name of the histogram. This will also be used as a title.
xLabel Title of the x axis.
xbins Bin edges on x axis
yLabel Title of the y axis.
ybins Bin edges on y axis
Definition at line 124 of file Histograms.cxx.
{
  std::string fullName = name_ + "_" + name;
  // copy bin edges into a C98 form acceptable by ROOT
  int xNBins = xbins.size() - 1;
  double* xBinEdges = new double[xbins.size()];
  for (unsigned int iBin = 0; iBin < xbins.size(); iBin++)
    xBinEdges[iBin] = xbins.at(iBin);
  int yNBins = ybins.size() - 1;
  double* yBinEdges = new double[ybins.size()];
  for (unsigned int iBin = 0; iBin < ybins.size(); iBin++)
    yBinEdges[iBin] = ybins.at(iBin);
  auto hist = new TH2F(fullName.c_str(), fullName.c_str(), xNBins, xBinEdges,
                       yNBins, yBinEdges);
  delete[] xBinEdges;  // cleanup
  delete[] yBinEdges;  // cleanup
  // Set the title
  hist->SetTitle("");
  // Set the x-axis label
  hist->GetXaxis()->SetTitle(xLabel.c_str());
  hist->GetXaxis()->CenterTitle();
  // Set the x-axis label
  hist->GetYaxis()->SetTitle(yLabel.c_str());
  hist->GetYaxis()->CenterTitle();
  // Insert it into the pool of histograms for later use
  HistogramPool::getInstance().insert(fullName, hist);
}
References framework::HistogramPool::getInstance(), framework::HistogramPool::insert(), and name_.
fill() [1/2]
void framework::HistogramHelper::fill (const std::string & name, const double & val) inline
Fill a 1D histogram
Uses the current setting of theWeight_.
Parameters
name name of the histogram to fill
val value to fill
Definition at line 166 of file Histograms.h.
{
    dynamic_cast<TH1F*>(this->get(name))->Fill(val, theWeight_);
  }
References get(), and theWeight_.
Referenced by dqm::EcalDigiVerifier::analyze(), dqm::EcalShowerFeatures::analyze(), dqm::HCalDQM::analyze(), dqm::HCalRawDigi::analyze(), dqm::RecoilTrackerDQM::analyze(), dqm::SimObjects::analyze(), dqm::Trigger::analyze(), dqm::TrigScintClusterDQM::analyze(), dqm::TrigScintDQM::analyze(), dqm::TrigScintHitDQM::analyze(), dqm::TrigScintTrackDQM::analyze(), and dqm::PhotoNuclearDQM::analyze().
fill() [2/2]
void framework::HistogramHelper::fill (const std::string & name, const double & valx, const double & valy) inline
Fill a 2D histogram
Uses the current setting of theWeight_.
Parameters
name name of the histogram to fill
valx x value to fill
valy y value to fill
Definition at line 179 of file Histograms.h.
{
    dynamic_cast<TH2F*>(this->get(name))->Fill(valx, valy, theWeight_);
  }
References get(), and theWeight_.
get()
TH1 * framework::HistogramHelper::get (const std::string & name) inline
Get a pointer to a histogram by name
Parameters
name name of the histogram to get
Definition at line 188 of file Histograms.h.
{
    return HistogramPool::getInstance().get(name_ + "_" + name);
  }
References framework::HistogramPool::get(), framework::HistogramPool::getInstance(), and name_.
Referenced by fill(), and dqm::PhotoNuclearDQM::onProcessStart().
setWeight()
void framework::HistogramHelper::setWeight (double w) inline
Set the weight for filling the histograms
Definition at line 91 of file Histograms.h.
{ theWeight_ = w; }
References theWeight_.
Member Data Documentation
name_
std::string framework::HistogramHelper::name_ private
The name of the processor that this helper is assigned to.
Definition at line 78 of file Histograms.h.
Referenced by create(), and get().
theWeight_
double framework::HistogramHelper::theWeight_ {1.} private
The weight to fill histograms with.
Definition at line 75 of file Histograms.h.
Referenced by fill(), and setWeight().
The documentation for this class was generated from the following files:
Framework/include/Framework/Histograms.h
Framework/src/Framework/Histograms.cxx