LDMX Software: trigscint::EventReadout Class Reference
trigscint::EventReadout Class Reference
This class represents the linearised QIE output from the trigger scintillator, in charge (fC).
#include <EventReadout.h>
Public Member Functions
EventReadout ()=default
~EventReadout ()=default
void Clear (Option_t *option="")
void Print (Option_t *option="") const
void setPedestal (const float pedestal)
float getEarlyPedestal () const
Get the pedestal calculated only from first N time samples.
void setEarlyPedestal (const float earlyPed)
float getPedestal () const
Get the pedestal.
void setNoise (const float noise)
float getNoise () const
Get the channel noise.
void setQualityFlag (const uint flag)
float getQualityFlag () const
Get the channel data quality flag.
void setQ (const std::vector< float > q)
std::vector< float > getQ () const
void setQError (const std::vector< float > qErr)
std::vector< float > getQError () const
void setTotQ (const float totQ)
float getTotQ () const
Get the channel totQ.
void setAvgQ (const float avgQ)
float getAvgQ () const
Get the channel avgQ.
void setMinQ (const float minQ)
float getMinQ () const
Get the channel minQ.
void setMaxQ (const float maxQ)
float getMaxQ () const
Get the channel maxQ.
void setMedQ (const float medQ)
float getMedQ () const
Get the channel medQ.
void setTimeOffset (const int timeOffset)
int getTimeOffset () const
Get the channel timeOffset.
void setFiberNb (const int fiberNb)
int getFiberNb () const
Get the channel fiberNb.
bool operator< (const EventReadout &rhs) const
Public Member Functions inherited from trigscint::TrigScintQIEDigis
TrigScintQIEDigis ()=default
Default constructor.
~TrigScintQIEDigis ()=default
Default destructor.
void Print (Option_t *option="") const
void Clear (Option_t *option="")
bool operator< (const TrigScintQIEDigis &rhs) const
int getChanID () const
int getElecID () const
std::vector< int > getADC () const
std::vector< int > getTDC () const
std::vector< int > getCID () const
void setTimeSinceSpill (const uint32_t timeSpill)
uint32_t getTimeSinceSpill () const
void setChanID (const int chanid)
void setElecID (const int elecid)
void setADC (const std::vector< int > adc)
void setTDC (const std::vector< int > tdc)
void setCID (const std::vector< int > cid)
Private Member Functions
ClassDef (EventReadout, 1)
Private Attributes
std::vector< float > qs_
analog to digital counts
std::vector< float > qErrs_
float pedestal_ {-999.}
float earlyPedestal_ {-999.}
float noise_ {-1.}
float totQ_ {-999.}
float avgQ_ {-999.}
float minQ_ {-999.}
float maxQ_ {-999.}
float medQ_ {-999.}
int timeOffset_ {0}
int fiberNb_ {-1}
uint flag_ {0}
Additional Inherited Members
Protected Attributes inherited from trigscint::TrigScintQIEDigis
int chanID_
channel ID
int elecID_ {-1}
channel ID
std::vector< int > adcs_
analog to digital counts
std::vector< int > tdcs_
Time to Digital counts.
uint32_t timeSinceSpillCounter_
Time since spill (a counter, to be divided by 125e6 or so)
Detailed Description
This class represents the linearised QIE output from the trigger scintillator, in charge (fC).
Definition at line 23 of file EventReadout.h.
Constructor & Destructor Documentation
EventReadout()
trigscint::EventReadout::EventReadout () default
Class constructor.
~EventReadout()
trigscint::EventReadout::~EventReadout () default
Class destructor.
Member Function Documentation
Clear()
void trigscint::EventReadout::Clear (Option_t * option = "")
Clear the data in the object.
Definition at line 24 of file EventReadout.cxx.
{}
getAvgQ()
float trigscint::EventReadout::getAvgQ () const inline
Get the channel avgQ.
Definition at line 134 of file EventReadout.h.
{ return avgQ_; }
getEarlyPedestal()
float trigscint::EventReadout::getEarlyPedestal () const inline
Get the pedestal calculated only from first N time samples.
Definition at line 54 of file EventReadout.h.
{ return earlyPedestal_; }
getFiberNb()
int trigscint::EventReadout::getFiberNb () const inline
Get the channel fiberNb.
Definition at line 190 of file EventReadout.h.
{ return fiberNb_; }
Referenced by trigscint::EventReadoutProducer::produce().
getMaxQ()
float trigscint::EventReadout::getMaxQ () const inline
Get the channel maxQ.
Definition at line 156 of file EventReadout.h.
{ return maxQ_; }
getMedQ()
float trigscint::EventReadout::getMedQ () const inline
Get the channel medQ.
Definition at line 167 of file EventReadout.h.
{ return medQ_; }
getMinQ()
float trigscint::EventReadout::getMinQ () const inline
Get the channel minQ.
Definition at line 145 of file EventReadout.h.
{ return minQ_; }
getNoise()
float trigscint::EventReadout::getNoise () const inline
Get the channel noise.
Definition at line 76 of file EventReadout.h.
{ return noise_; }
Referenced by trigscint::EventReadoutProducer::produce().
getPedestal()
float trigscint::EventReadout::getPedestal () const inline
Get the pedestal.
Definition at line 65 of file EventReadout.h.
{ return pedestal_; }
Referenced by trigscint::EventReadoutProducer::produce().
getQ()
std::vector< float > trigscint::EventReadout::getQ () const inline
Get charges of all time samples
Definition at line 102 of file EventReadout.h.
{ return qs_; }
References qs_.
getQError()
std::vector< float > trigscint::EventReadout::getQError () const inline
Get charges of all time samples
Definition at line 113 of file EventReadout.h.
{ return qErrs_; }
getQualityFlag()
float trigscint::EventReadout::getQualityFlag () const inline
Get the channel data quality flag.
Definition at line 91 of file EventReadout.h.
{ return flag_; }
getTimeOffset()
int trigscint::EventReadout::getTimeOffset () const inline
Get the channel timeOffset.
Definition at line 179 of file EventReadout.h.
{ return timeOffset_; }
getTotQ()
float trigscint::EventReadout::getTotQ () const inline
Get the channel totQ.
Definition at line 123 of file EventReadout.h.
{ return totQ_; }
Referenced by trigscint::EventReadoutProducer::produce().
operator<()
bool trigscint::EventReadout::operator< (const EventReadout & rhs) const inline
A dummy operator overloading
Note
required for declaring std::vector<> in EventDef.h
Definition at line 196 of file EventReadout.h.
{
    return this->chanID_ < rhs.chanID_;
  }
References trigscint::TrigScintQIEDigis::chanID_.
Print()
void trigscint::EventReadout::Print (Option_t * option = "") const
Print out the object.
Definition at line 14 of file EventReadout.cxx.
{
  std::cout << "EventReadout { "
            << "chanID= " << chanID_ << ", "
            << "ADC[0]= " << adcs_[0] << ", "
            << "charge[0]= " << qs_[0] << ", "
            << "pedestal= " << pedestal_ << ", "
            << "noise= " << noise_ << ", "
            << "}\n";
}
References trigscint::TrigScintQIEDigis::adcs_, trigscint::TrigScintQIEDigis::chanID_, and qs_.
setAvgQ()
void trigscint::EventReadout::setAvgQ (const float avgQ) inline
Set channel (linearized, charge-equiv) average charge
Parameters
avgQ The (time sample) average charge of the channel
Definition at line 130 of file EventReadout.h.
{ avgQ_ = avgQ; };
Referenced by trigscint::EventReadoutProducer::produce().
setEarlyPedestal()
void trigscint::EventReadout::setEarlyPedestal (const float earlyPed) inline
Set channel (linearized. charge) pedestal calculated from beginning of readout
Parameters
pedestal The pedestal of the first N time samples in the channel
Definition at line 61 of file EventReadout.h.
{ earlyPedestal_ = earlyPed; };
Referenced by trigscint::EventReadoutProducer::produce().
setFiberNb()
void trigscint::EventReadout::setFiberNb (const int fiberNb) inline
Set channel readout fiber number
Parameters
fiberNb The channel readout fiber number
Definition at line 186 of file EventReadout.h.
{ fiberNb_ = fiberNb; };
Referenced by trigscint::EventReadoutProducer::produce().
setMaxQ()
void trigscint::EventReadout::setMaxQ (const float maxQ) inline
Set channel (linearized, charge-equiv) maximum charge
Parameters
maxQ The (time sample) maximum charge of the channel
Definition at line 152 of file EventReadout.h.
{ maxQ_ = maxQ; };
Referenced by trigscint::EventReadoutProducer::produce().
setMedQ()
void trigscint::EventReadout::setMedQ (const float medQ) inline
Set channel (linearized, charge-equiv) median charge
Parameters
medQ The (time sample) median charge of the channel
Definition at line 163 of file EventReadout.h.
{ medQ_ = medQ; };
Referenced by trigscint::EventReadoutProducer::produce().
setMinQ()
void trigscint::EventReadout::setMinQ (const float minQ) inline
Set channel (linearized, charge-equiv) minimum charge
Parameters
minQ The (time sample) minimum charge of the channel
Definition at line 141 of file EventReadout.h.
{ minQ_ = minQ; };
Referenced by trigscint::EventReadoutProducer::produce().
setNoise()
void trigscint::EventReadout::setNoise (const float noise) inline
Set channel (linearized, charge-equiv) noise
Parameters
noise The noise of the channel
Definition at line 72 of file EventReadout.h.
{ noise_ = noise; };
Referenced by trigscint::EventReadoutProducer::produce().
setPedestal()
void trigscint::EventReadout::setPedestal (const float pedestal) inline
Set channel (linearized. charge) pedestal
Parameters
pedestal The pedestal of the channel
Definition at line 50 of file EventReadout.h.
{ pedestal_ = pedestal; };
Referenced by trigscint::EventReadoutProducer::produce().
setQ()
void trigscint::EventReadout::setQ (const std::vector< float > q) inline
Store charges of all time samples
Parameters
q_ array of qs
Definition at line 97 of file EventReadout.h.
{ qs_ = q; }
References qs_.
Referenced by trigscint::EventReadoutProducer::produce().
setQError()
void trigscint::EventReadout::setQError (const std::vector< float > qErr) inline
Store charge quantization errors of all time samples
Parameters
qErr_ array of quantization errors
Definition at line 108 of file EventReadout.h.
{ qErrs_ = qErr; }
Referenced by trigscint::EventReadoutProducer::produce().
setQualityFlag()
void trigscint::EventReadout::setQualityFlag (const uint flag) inline
Set channel data quality flag. This is the binary combination of 4 flags: spike: 1 plateau: 10 long pulse: 100 (not implemented yet) oscillation: 1000
Parameters
flag The quality flag of the channel
Definition at line 87 of file EventReadout.h.
{ this->flag_ = flag; };
Referenced by trigscint::EventReadoutProducer::produce().
setTimeOffset()
void trigscint::EventReadout::setTimeOffset (const int timeOffset) inline
Set channel readout itme offset (in units of samples)
Parameters
timeOffset The (time sample) offset in channel readout
Definition at line 175 of file EventReadout.h.
{ timeOffset_ = timeOffset; };
Referenced by trigscint::EventReadoutProducer::produce().
setTotQ()
void trigscint::EventReadout::setTotQ (const float totQ) inline
Set channel (linearized, charge-equiv) average charge
Parameters
totQ The (time sample) average charge of the channel
Definition at line 120 of file EventReadout.h.
{ totQ_ = totQ; };
Referenced by trigscint::EventReadoutProducer::produce().
Member Data Documentation
avgQ_
float trigscint::EventReadout::avgQ_ {-999.} private
Definition at line 209 of file EventReadout.h.
earlyPedestal_
float trigscint::EventReadout::earlyPedestal_ {-999.} private
Definition at line 206 of file EventReadout.h.
fiberNb_
int trigscint::EventReadout::fiberNb_ {-1} private
Definition at line 214 of file EventReadout.h.
flag_
uint trigscint::EventReadout::flag_ {0} private
Definition at line 216 of file EventReadout.h.
maxQ_
float trigscint::EventReadout::maxQ_ {-999.} private
Definition at line 211 of file EventReadout.h.
medQ_
float trigscint::EventReadout::medQ_ {-999.} private
Definition at line 212 of file EventReadout.h.
minQ_
float trigscint::EventReadout::minQ_ {-999.} private
Definition at line 210 of file EventReadout.h.
noise_
float trigscint::EventReadout::noise_ {-1.} private
Definition at line 207 of file EventReadout.h.
pedestal_
float trigscint::EventReadout::pedestal_ {-999.} private
Definition at line 205 of file EventReadout.h.
qErrs_
std::vector<float> trigscint::EventReadout::qErrs_ private
Definition at line 203 of file EventReadout.h.
qs_
std::vector<float> trigscint::EventReadout::qs_ private
analog to digital counts
Definition at line 202 of file EventReadout.h.
Referenced by getQ(), Print(), and setQ().
timeOffset_
int trigscint::EventReadout::timeOffset_ {0} private
Definition at line 213 of file EventReadout.h.
totQ_
float trigscint::EventReadout::totQ_ {-999.} private
Definition at line 208 of file EventReadout.h.
The documentation for this class was generated from the following files:
TrigScint/include/TrigScint/Event/EventReadout.h
TrigScint/src/TrigScint/Event/EventReadout.cxx