LDMX Software: simcore::darkbrem::G4eDarkBremsstrahlung Class Reference
simcore::darkbrem::G4eDarkBremsstrahlung Class Reference
#include <G4eDarkBremsstrahlung.h>
Public Member Functions
G4eDarkBremsstrahlung (const framework::config::Parameters &params)
virtual ~G4eDarkBremsstrahlung ()=default
virtual G4bool IsApplicable (const G4ParticleDefinition &p)
virtual void PrintInfo ()
void RecordConfig (ldmx::RunHeader &h) const
virtual G4VParticleChange * PostStepDoIt (const G4Track &track, const G4Step &step)
void CalculateCommonXsec ()
ElementXsecCache & getCache ()
Static Public Attributes
static const std::string PROCESS_NAME = "eDarkBrem"
Protected Member Functions
G4double GetMeanFreePath (const G4Track &track, G4double prevStepSize, G4ForceCondition *condition)
Private Member Functions
G4eDarkBremsstrahlung & operator= (const G4eDarkBremsstrahlung &right)
G4eDarkBremsstrahlung (const G4eDarkBremsstrahlung &)
Private Attributes
bool only_one_per_event_
double ap_mass_
bool cache_xsec_
std::shared_ptr< G4eDarkBremsstrahlungModel > model_
ElementXsecCache element_xsec_cache_
Our instance of a cross section cache.
framework::logging::logger theLog_
Enable logging for this process.
Detailed Description
Class that represents the dark brem process. An electron is allowed to brem a dark photon
@TODO allow positrons to dark brem as well
Definition at line 200 of file G4eDarkBremsstrahlung.h.
Constructor & Destructor Documentation
G4eDarkBremsstrahlung() [1/2]
simcore::darkbrem::G4eDarkBremsstrahlung::G4eDarkBremsstrahlung (const framework::config::Parameters & params)
Constructor
Configures this process by doing three main things:
Registers this process with Geant4 as a 'fElectromagnetic' process
Needed for Geant4 Biasing Framework to recognize this process as "bias-able"
Defines the EM subtype as one different from all other EM processes
Needed so we don't replace another EM process
Configures the process and passes the model parameters to the model
If caching the cross section is enabled, we calculate several common cross sections immediately to help even out the time it takes to simulate events.
See also
CalculateCommonXsec
Definition at line 59 of file G4eDarkBremsstrahlung.cxx.
     : G4VDiscreteProcess(G4eDarkBremsstrahlung::PROCESS_NAME,
                          fElectromagnetic) {
   // we need to pretend to be an EM process so the biasing framework recognizes
   // us
   SetProcessSubType(63);  // needs to be different from the other Em Subtypes
   only_one_per_event_ = params.getParameter<bool>("only_one_per_event");
   cache_xsec_ = params.getParameter<bool>("cache_xsec");
   ap_mass_ = params.getParameter<double>("ap_mass");
   auto model{params.getParameter<framework::config::Parameters>("model")};
   auto model_name{model.getParameter<std::string>("name")};
   if (model_name == "vertex_library") {
     model_ = std::make_shared<DarkBremVertexLibraryModel>(model);
   } else {
     EXCEPTION_RAISE("DarkBremModel",
                     "Model named '" + model_name + "' is not known.");
   }
   // now that the model is set, calculate common xsec and put them into the
   // cache
   if (cache_xsec_) {
     element_xsec_cache_ =
         ElementXsecCache(model_);  // remake cache with model attached
     CalculateCommonXsec();         // calculate common cross sections
   }
 }
References ap_mass_, cache_xsec_, CalculateCommonXsec(), element_xsec_cache_, framework::config::Parameters::getParameter(), model_, and only_one_per_event_.
~G4eDarkBremsstrahlung()
virtual simcore::darkbrem::G4eDarkBremsstrahlung::~G4eDarkBremsstrahlung () virtual default
Destructor
G4eDarkBremsstrahlung() [2/2]
simcore::darkbrem::G4eDarkBremsstrahlung::G4eDarkBremsstrahlung (const G4eDarkBremsstrahlung &) private
remove ability to copy construct
Member Function Documentation
CalculateCommonXsec()
void simcore::darkbrem::G4eDarkBremsstrahlung::CalculateCommonXsec ()
Calculate common cross sections for the cache using the already-created model.
This method is public so that we can access it for writing a short executable to print the cache to a file.
Definition at line 149 of file G4eDarkBremsstrahlung.cxx.
{
   // first in pair is A, second is Z
   std::vector<std::pair<G4double, G4double>> elements = {
       std::make_pair(183.84, 74),  // tungsten
       std::make_pair(28.085, 14)   // silicon
   };
   G4double current_energy = 2.0 * GeV;
   G4double maximum_energy = 4.0 * GeV;
   G4double energy_step = 1.0 * MeV;
   while (current_energy <= maximum_energy) {
     for (auto const& [A, Z] : elements)
       element_xsec_cache_.get(current_energy, A, Z);
     current_energy += energy_step;
   }
 }
References element_xsec_cache_, and simcore::darkbrem::ElementXsecCache::get().
Referenced by G4eDarkBremsstrahlung().
getCache()
ElementXsecCache& simcore::darkbrem::G4eDarkBremsstrahlung::getCache () inline
Get a reference to the cross section cache.
Again, this method is public only to be available to the executable that generates a cross section table and testing. Do not use this unless you really know what you are doing.
Definition at line 296 of file G4eDarkBremsstrahlung.h.
 { return element_xsec_cache_; }
References element_xsec_cache_.
GetMeanFreePath()
G4double simcore::darkbrem::G4eDarkBremsstrahlung::GetMeanFreePath (const G4Track & track, G4double prevStepSize, G4ForceCondition * condition) protected
Calculate the mean free path given the input conditions
We maintain a cache for the cross sections calculated by the model so that later in the run it is less likely that the model will need to be called to calculate the cross section. This is done in order to attempt to improve speed of simulation and avoid repetition of the same, deterministic calculations.
If you want to turn off the cache-ing behavior, set 'cache_xsec' to false in the python configuratin for the dark brem process.
See also
G4eDarkBremsstrahlungModel::ComputeCrossSectionPerAtom
Parameters
[in] track G4Track that is being stepped
[in] prevStepSize G4double measuring previous step size, unused
[in] condition G4ForceCondition, always NotForced for G4VDiscreteProcess, unused
Returns
G4double mean free path of the particle
Definition at line 166 of file G4eDarkBremsstrahlung.cxx.
{
   // won't happen if it isn't applicable
   if (not IsApplicable(*track.GetParticleDefinition())) return DBL_MAX;
   G4Material* materialWeAreIn = track.GetMaterial();
   const G4ElementVector* theElementVector = materialWeAreIn->GetElementVector();
   const G4double* NbOfAtomsPerVolume =
       materialWeAreIn->GetVecNbOfAtomsPerVolume();
   G4double SIGMA = 0;
   for (size_t i = 0; i < materialWeAreIn->GetNumberOfElements(); i++) {
     G4double AtomicZ = (*theElementVector)[i]->GetZ();
     G4double AtomicA = (*theElementVector)[i]->GetA() / (g / mole);
     G4double energy = track.GetDynamicParticle()->GetKineticEnergy();
     G4double element_xsec;
     if (cache_xsec_)
       element_xsec = element_xsec_cache_.get(energy, AtomicA, AtomicZ);
     else
       element_xsec =
           model_->ComputeCrossSectionPerAtom(energy, AtomicA, AtomicZ);
     SIGMA += NbOfAtomsPerVolume[i] * element_xsec;
   }
   return SIGMA > DBL_MIN ? 1. / SIGMA : DBL_MAX;
 }
References cache_xsec_, element_xsec_cache_, simcore::darkbrem::ElementXsecCache::get(), IsApplicable(), and model_.
IsApplicable()
G4bool simcore::darkbrem::G4eDarkBremsstrahlung::IsApplicable (const G4ParticleDefinition & p) virtual
Checks if the passed particle should be able to do this process
Returns
true if particle is electron
Definition at line 89 of file G4eDarkBremsstrahlung.cxx.
{
   return &p == G4Electron::Electron();
 }
Referenced by GetMeanFreePath(), and PostStepDoIt().
operator=()
G4eDarkBremsstrahlung& simcore::darkbrem::G4eDarkBremsstrahlung::operator= (const G4eDarkBremsstrahlung & right) private
remove ability to assign this object
PostStepDoIt()
G4VParticleChange * simcore::darkbrem::G4eDarkBremsstrahlung::PostStepDoIt (const G4Track & track, const G4Step & step) virtual
This is the function actually called by Geant4 that does the dark brem interaction.
aParticleChange is a protected member variable of G4VDiscreteProcess that we should edit here.
If only one per event is set, then we deactivate the dark brem process, ensuring only one dark brem per step and per event. Reactivated in RunManager::TerminateOneEvent.
See also
RunManager::TerminateOneEvent
G4eDarkBremsstrahlungModel::GenerateChange
Parameters
[in] track current G4Track that is being stepped
[in] step current step that just finished
Returns
G4VParticleChange detailing how this process changes the track
Definition at line 106 of file G4eDarkBremsstrahlung.cxx.
{
   // Debugging Purposes: Check if track we get is an electron
   if (not IsApplicable(*track.GetParticleDefinition()))
     EXCEPTION_RAISE(
         "DBBadTrack",
         "Dark brem process receieved a track that isn't applicable.");
   /*
    * Geant4 has decided that it is our time to interact,
    * so we are going to change the particle
    */
   ldmx_log(debug) << "A dark brem occurred!";
   if (only_one_per_event_) {
     // Deactivate the process after one dark brem if we restrict ourselves to
     // only one per event. If this is in the stepping action instead, more than
     // one brem can occur within each step. Reactivated in
     // RunManager::TerminateOneEvent Both biased and unbiased process could be
     // in the run (but not at the same time),
     //  so we turn off both while silencing the warnings from the process table.
     std::vector<G4String> db_process_name_options = {
         "biasWrapper(" + PROCESS_NAME + ")", PROCESS_NAME};
     G4ProcessTable* ptable = G4ProcessTable::GetProcessTable();
     G4int verbosity = ptable->GetVerboseLevel();
     ptable->SetVerboseLevel(0);
     for (auto const& name : db_process_name_options)
       ptable->SetProcessActivation(name, false);
     ptable->SetVerboseLevel(verbosity);
   }
   aParticleChange.Initialize(track);
   model_->GenerateChange(aParticleChange, track, step);
   /*
    * Parent class has some internal counters that need to be reset,
    * so we call it before returning. It will return our shared
    * protected member variable aParticleChange that we have been modifying
    */
   return G4VDiscreteProcess::PostStepDoIt(track, step);
 }
References IsApplicable(), model_, only_one_per_event_, and PROCESS_NAME.
PrintInfo()
void simcore::darkbrem::G4eDarkBremsstrahlung::PrintInfo () virtual
Reports the parameters to G4cout.
See also
G4eDarkBremsstrahlungModel::PrintInfo
Definition at line 93 of file G4eDarkBremsstrahlung.cxx.
{
   G4cout << " Only One Per Event               : " << only_one_per_event_
          << G4endl;
   G4cout << " A' Mass [MeV]                    : " << ap_mass_ << G4endl;
   model_->PrintInfo();
 }
References ap_mass_, model_, and only_one_per_event_.
RecordConfig()
void simcore::darkbrem::G4eDarkBremsstrahlung::RecordConfig (ldmx::RunHeader & h) const
Records the configuration of this process into the RunHeader
See also
G4eDarkBremsstrahlungModel::RecordConfig
Parameters
[in,out] h RunHeader to write to
Definition at line 100 of file G4eDarkBremsstrahlung.cxx.
{
   h.setIntParameter("Only One DB Per Event", only_one_per_event_);
   h.setFloatParameter("A' Mass [MeV]", ap_mass_);
   model_->RecordConfig(h);
 }
References ap_mass_, model_, only_one_per_event_, ldmx::RunHeader::setFloatParameter(), and ldmx::RunHeader::setIntParameter().
Member Data Documentation
ap_mass_
double simcore::darkbrem::G4eDarkBremsstrahlung::ap_mass_ private
The mass of the A' during this run [MeV]
Definition at line 343 of file G4eDarkBremsstrahlung.h.
Referenced by G4eDarkBremsstrahlung(), PrintInfo(), and RecordConfig().
cache_xsec_
bool simcore::darkbrem::G4eDarkBremsstrahlung::cache_xsec_ private
Should we have a cache for the computed cross sections?
Definition at line 348 of file G4eDarkBremsstrahlung.h.
Referenced by G4eDarkBremsstrahlung(), and GetMeanFreePath().
model_
std::shared_ptr<G4eDarkBremsstrahlungModel> simcore::darkbrem::G4eDarkBremsstrahlung::model_ private
The model that we are using in this run.
Shared with the chaching class.
Definition at line 355 of file G4eDarkBremsstrahlung.h.
Referenced by G4eDarkBremsstrahlung(), GetMeanFreePath(), PostStepDoIt(), PrintInfo(), and RecordConfig().
only_one_per_event_
bool simcore::darkbrem::G4eDarkBremsstrahlung::only_one_per_event_ private
Only allow the dark brem to happen once per event.
This allows for the dark brem process to be de-activated when SampleSecondaries is called.
The dark brem process is always re-activated in the RunManager::TerminateOneEvent method. This reactivation has no effect when the process is already active.
Definition at line 338 of file G4eDarkBremsstrahlung.h.
Referenced by G4eDarkBremsstrahlung(), PostStepDoIt(), PrintInfo(), and RecordConfig().
PROCESS_NAME
const std::string simcore::darkbrem::G4eDarkBremsstrahlung::PROCESS_NAME = "eDarkBrem" static
The name of this process in Geant4
Note
This process name should be used in all places that can depend on this file. (For example RunManager and DetectorConstruction). There are other places that can't use this constant directly, so if this name is changed you also need to change the following places.
Python: Biasing.filters.TrackProcessFilter.dark_brem
C++: Event/SimParticle::createProcessMap
Definition at line 213 of file G4eDarkBremsstrahlung.h.
Referenced by simcore::Simulator::beforeNewRun(), simcore::biasoperators::DarkBrem::getProcessToBias(), PostStepDoIt(), biasing::EcalDarkBremFilter::PostUserTrackingAction(), and simcore::RunManager::TerminateOneEvent().
theLog_
framework::logging::logger simcore::darkbrem::G4eDarkBremsstrahlung::theLog_ private
Initial value:
=
      framework::logging::makeLogger("DarkBremProcess")
Enable logging for this process.
Definition at line 361 of file G4eDarkBremsstrahlung.h.
The documentation for this class was generated from the following files:
SimCore/include/SimCore/DarkBrem/G4eDarkBremsstrahlung.h
SimCore/src/SimCore/DarkBrem/G4eDarkBremsstrahlung.cxx