LDMX Software: simcore::lhe::LHEReader Class Reference
simcore::lhe::LHEReader Class Reference
Reads LHE event data into an LHEEvent object.
#include <LHEReader.h>
Public Member Functions
LHEReader (std::string &fileName)
virtual ~LHEReader ()
LHEEvent * readNextEvent ()
Private Attributes
std::ifstream ifs_
Detailed Description
Reads LHE event data into an LHEEvent object.
Definition at line 22 of file LHEReader.h.
Constructor & Destructor Documentation
LHEReader()
simcore::lhe::LHEReader::LHEReader (std::string & fileName)
Class constructor.
Parameters
fileName The input file name.
Definition at line 8 of file LHEReader.cxx.
{
  std::cout << "Opening LHE file " << filename << std::endl;
  ifs_.open(filename.c_str(), std::ifstream::in);
}
References ifs_.
~LHEReader()
simcore::lhe::LHEReader::~LHEReader () virtual
Class destructor.
Definition at line 13 of file LHEReader.cxx.
{ ifs_.close(); }
References ifs_.
Member Function Documentation
readNextEvent()
LHEEvent * simcore::lhe::LHEReader::readNextEvent ()
Read the next event.
Returns
The next LHE event.
Definition at line 15 of file LHEReader.cxx.
{
  std::string line;
  bool foundEventElement = false;
  while (getline(ifs_, line)) {
    if (line == "<event>") {
      foundEventElement = true;
      break;
    }
  }
  if (!foundEventElement) {
    std::cerr << "WARNING: No next <event> element was found by the LHE reader."
              << std::endl;
    return NULL;
  }
  getline(ifs_, line);
  LHEEvent* nextEvent = new LHEEvent(line);
  while (getline(ifs_, line)) {
    if (line == "</event>") {
      break;
    }
    if (line.find("#") == std::string::npos) {  // not a comment line
      LHEParticle* particle = new LHEParticle(line);
      nextEvent->addParticle(particle);
    } else {
      if (line.find("#vertex") != std::string::npos) {
        nextEvent->setVertex(line);
      }
    }
  }
  const std::vector<LHEParticle*>& particles = nextEvent->getParticles();
  int particleIndex = 0;
  for (std::vector<LHEParticle*>::const_iterator it = particles.begin();
       it != particles.end(); it++) {
    LHEParticle* particle = (*it);
    if (particle->getMOTHUP(0) != 0) {
      int mother1 = particle->getMOTHUP(0);
      int mother2 = particle->getMOTHUP(1);
      if (mother1 > 0) {
        particle->setMother(0, particles[mother1 - 1]);
      }
      if (mother2 > 0) {
        particle->setMother(1, particles[mother2 - 1]);
      }
    }
    ++particleIndex;
  }
  return nextEvent;
}
References simcore::lhe::LHEEvent::addParticle(), simcore::lhe::LHEParticle::getMOTHUP(), simcore::lhe::LHEEvent::getParticles(), ifs_, simcore::lhe::LHEParticle::setMother(), and simcore::lhe::LHEEvent::setVertex().
Referenced by simcore::generators::LHEPrimaryGenerator::GeneratePrimaryVertex().
Member Data Documentation
ifs_
std::ifstream simcore::lhe::LHEReader::ifs_ private
The input file stream.
Definition at line 45 of file LHEReader.h.
Referenced by LHEReader(), readNextEvent(), and ~LHEReader().
The documentation for this class was generated from the following files:
SimCore/include/SimCore/LHE/LHEReader.h
SimCore/src/SimCore/LHE/LHEReader.cxx