LDMX Software: ldmx::SimTrackerHit Class Reference
ldmx::SimTrackerHit Class Reference
Represents a simulated tracker hit in the simulation.
#include <SimTrackerHit.h>
Public Member Functions
SimTrackerHit ()
virtual ~SimTrackerHit ()
void Print () const
void Clear ()
int getID () const
int getLayerID () const
int getModuleID () const
std::vector< float > getPosition () const
float getEdep () const
float getEnergy () const
float getTime () const
float getPathLength () const
std::vector< double > getMomentum () const
int getTrackID () const
int getPdgID () const
void setID (const long id)
void setLayerID (const int layerID)
void setModuleID (const int moduleID)
void setPosition (const float x, const float y, const float z)
void setEdep (const float edep)
void setEnergy (const float energy)
void setTime (const float time)
void setPathLength (const float pathLength)
void setMomentum (const float px, const float py, const float pz)
void setTrackID (const int simTrackID)
void setPdgID (const int simPdgID)
bool operator< (const SimTrackerHit &rhs) const
Private Member Functions
ClassDef (SimTrackerHit, 3)
Private Attributes
int id_ {0}
int layerID_ {0}
int moduleID_ {0}
float edep_ {0}
float time_ {0}
float px_ {0}
float py_ {0}
float pz_ {0}
float energy_ {0}
float x_ {0}
float y_ {0}
float z_ {0}
float pathLength_ {0}
int trackID_ {0}
int pdgID_ {0}
Detailed Description
Represents a simulated tracker hit in the simulation.
Definition at line 23 of file SimTrackerHit.h.
Constructor & Destructor Documentation
SimTrackerHit()
ldmx::SimTrackerHit::SimTrackerHit ()
Class constructor.
~SimTrackerHit()
virtual ldmx::SimTrackerHit::~SimTrackerHit () virtual
Class destructor.
Member Function Documentation
ClassDef()
ldmx::SimTrackerHit::ClassDef (SimTrackerHit , 3) private
The ROOT class definition.
Clear()
void ldmx::SimTrackerHit::Clear ()
Reset the SimTrackerHit object.
getEdep()
float ldmx::SimTrackerHit::getEdep () const inline
Get the energy deposited on the hit [MeV].
Returns
The energy deposited on the hit.
Definition at line 76 of file SimTrackerHit.h.
 { return edep_; };
References edep_.
getEnergy()
float ldmx::SimTrackerHit::getEnergy () const inline
Get the energy
Returns
The energy of the hit.
Definition at line 82 of file SimTrackerHit.h.
 { return energy_; };
References energy_.
getID()
int ldmx::SimTrackerHit::getID () const inline
Get the detector ID of the hit.
Returns
The detector ID of the hit.
Definition at line 51 of file SimTrackerHit.h.
 { return id_; };
References id_.
getLayerID()
int ldmx::SimTrackerHit::getLayerID () const inline
Get the geometric layer ID of the hit.
Returns
The layer ID of the hit.
Definition at line 57 of file SimTrackerHit.h.
 { return layerID_; };
References layerID_.
Referenced by ldmx::FindableTrackProcessor::createHitMap(), and ldmx::DetectorGeometry::getBoundingBox().
getModuleID()
int ldmx::SimTrackerHit::getModuleID () const inline
Get the module ID associated with a hit. This is used to uniquely identify a sensor within a layer.
Returns
The module ID associated with a hit.
Definition at line 64 of file SimTrackerHit.h.
 { return moduleID_; };
References moduleID_.
Referenced by ldmx::DetectorGeometry::getBoundingBox().
getMomentum()
std::vector<double> ldmx::SimTrackerHit::getMomentum () const inline
Get the XYZ momentum of the particle at the position at which the hit took place [MeV].
Returns
The momentum of the particle.
Definition at line 102 of file SimTrackerHit.h.
 { return {px_, py_, pz_}; };
References px_, py_, and pz_.
Referenced by ldmx::EcalVetoProcessor::produce(), ldmx::TrackerVetoProcessor::produce(), and ldmx::EventObjects::SetSimThresh().
getPathLength()
float ldmx::SimTrackerHit::getPathLength () const inline
Get the path length between the start and end points of the hit [mm].
Returns
The path length of the hit.
Definition at line 95 of file SimTrackerHit.h.
 { return pathLength_; };
References pathLength_.
getPdgID()
int ldmx::SimTrackerHit::getPdgID () const inline
Get the Sim particle track ID of the hit.
Returns
The Sim particle track ID of the hit.
Definition at line 114 of file SimTrackerHit.h.
 { return pdgID_; };
References pdgID_.
getPosition()
std::vector<float> ldmx::SimTrackerHit::getPosition () const inline
Get the XYZ position of the hit [mm].
Returns
The position of the hit.
Definition at line 70 of file SimTrackerHit.h.
 { return {x_, y_, z_}; };
References x_, y_, and z_.
Referenced by ldmx::DetectorGeometry::getBoundingBox().
getTime()
float ldmx::SimTrackerHit::getTime () const inline
Get the global time of the hit [ns].
Returns
The global time of the hit.
Definition at line 88 of file SimTrackerHit.h.
 { return time_; };
References time_.
Referenced by operator<().
getTrackID()
int ldmx::SimTrackerHit::getTrackID () const inline
Get the Sim particle track ID of the hit.
Returns
The Sim particle track ID of the hit.
Definition at line 108 of file SimTrackerHit.h.
 { return trackID_; };
References trackID_.
Referenced by ldmx::FindableTrackProcessor::createHitMap().
operator<()
bool ldmx::SimTrackerHit::operator< (const SimTrackerHit & rhs) const inline
Sort by time of hit
Definition at line 191 of file SimTrackerHit.h.
{
                 return this->getTime() < rhs.getTime();
             }
References getTime().
Print()
void ldmx::SimTrackerHit::Print () const
Print a description of this object.
setEdep()
void ldmx::SimTrackerHit::setEdep (const float edep) inline
Set the energy deposited on the hit [MeV].
Parameters
edep The energy deposited on the hit.
Definition at line 147 of file SimTrackerHit.h.
 { this->edep_ = edep; };
References edep_.
Referenced by ldmx::RootPersistencyManager::writeTrackerHitsCollection().
setEnergy()
void ldmx::SimTrackerHit::setEnergy (const float energy) inline
Set the energy of the hit.
Parameters
e The energy of the hit.
Definition at line 153 of file SimTrackerHit.h.
 { energy_ = energy; };
References energy_.
Referenced by ldmx::RootPersistencyManager::writeTrackerHitsCollection().
setID()
void ldmx::SimTrackerHit::setID (const long id) inline
Set the detector ID of the hit.
Parameters
id The detector ID of the hit.
Definition at line 120 of file SimTrackerHit.h.
 { this->id_ = id; };
References id_.
Referenced by ldmx::RootPersistencyManager::writeTrackerHitsCollection().
setLayerID()
void ldmx::SimTrackerHit::setLayerID (const int layerID) inline
Set the geometric layer ID of the hit.
Parameters
layerID The layer ID of the hit.
Definition at line 126 of file SimTrackerHit.h.
 { this->layerID_ = layerID; };
References layerID_.
Referenced by ldmx::RootPersistencyManager::writeTrackerHitsCollection().
setModuleID()
void ldmx::SimTrackerHit::setModuleID (const int moduleID) inline
Set the module ID associated with a hit. This is used to uniquely identify a sensor within a layer.
Returns
moduleID The module ID associated with a hit.
Definition at line 133 of file SimTrackerHit.h.
 { this->moduleID_ = moduleID; };
References moduleID_.
Referenced by ldmx::RootPersistencyManager::writeTrackerHitsCollection().
setMomentum()
void ldmx::SimTrackerHit::setMomentum (const float px, const float py, const float pz)
Set the momentum of the particle at the position at which the hit took place [GeV].
Parameters
px The X momentum.
py The Y momentum.
pz The Z momentum.
Referenced by ldmx::RootPersistencyManager::writeTrackerHitsCollection().
setPathLength()
void ldmx::SimTrackerHit::setPathLength (const float pathLength) inline
Set the path length of the hit [mm].
Parameters
pathLength The path length of the hit.
Definition at line 165 of file SimTrackerHit.h.
 { this->pathLength_ = pathLength; };
References pathLength_.
Referenced by ldmx::RootPersistencyManager::writeTrackerHitsCollection().
setPdgID()
void ldmx::SimTrackerHit::setPdgID (const int simPdgID) inline
Set the Sim particle track ID of the hit.
Returns
The Sim particle track ID of the hit.
Definition at line 186 of file SimTrackerHit.h.
 { this->pdgID_ = simPdgID; };
References pdgID_.
Referenced by ldmx::RootPersistencyManager::writeTrackerHitsCollection().
setPosition()
void ldmx::SimTrackerHit::setPosition (const float x, const float y, const float z)
Set the position of the hit [mm].
Parameters
x The X position.
y The Y position.
z The Z position.
Referenced by ldmx::RootPersistencyManager::writeTrackerHitsCollection().
setTime()
void ldmx::SimTrackerHit::setTime (const float time) inline
Set the global time of the hit [ns].
Parameters
time The global time of the hit.
Definition at line 159 of file SimTrackerHit.h.
 { this->time_ = time; };
References time_.
Referenced by ldmx::RootPersistencyManager::writeTrackerHitsCollection().
setTrackID()
void ldmx::SimTrackerHit::setTrackID (const int simTrackID) inline
Set the Sim particle track ID of the hit.
Returns
The Sim particle track ID of the hit.
Definition at line 180 of file SimTrackerHit.h.
 { this->trackID_ = simTrackID; };
References trackID_.
Referenced by ldmx::RootPersistencyManager::writeTrackerHitsCollection().
Member Data Documentation
edep_
float ldmx::SimTrackerHit::edep_ {0} private
The energy deposited on the hit.
Definition at line 213 of file SimTrackerHit.h.
Referenced by getEdep(), and setEdep().
energy_
float ldmx::SimTrackerHit::energy_ {0} private
The total energy.
Definition at line 238 of file SimTrackerHit.h.
Referenced by getEnergy(), and setEnergy().
id_
int ldmx::SimTrackerHit::id_ {0} private
The detector ID.
Definition at line 200 of file SimTrackerHit.h.
Referenced by getID(), and setID().
layerID_
int ldmx::SimTrackerHit::layerID_ {0} private
The layer ID.
Definition at line 205 of file SimTrackerHit.h.
Referenced by getLayerID(), and setLayerID().
moduleID_
int ldmx::SimTrackerHit::moduleID_ {0} private
The module ID.
Definition at line 208 of file SimTrackerHit.h.
Referenced by getModuleID(), and setModuleID().
pathLength_
float ldmx::SimTrackerHit::pathLength_ {0} private
The path length of the hit.
Definition at line 258 of file SimTrackerHit.h.
Referenced by getPathLength(), and setPathLength().
pdgID_
int ldmx::SimTrackerHit::pdgID_ {0} private
The Sim PDG ID.
Definition at line 268 of file SimTrackerHit.h.
Referenced by getPdgID(), and setPdgID().
px_
float ldmx::SimTrackerHit::px_ {0} private
The X momentum.
Definition at line 223 of file SimTrackerHit.h.
Referenced by getMomentum().
py_
float ldmx::SimTrackerHit::py_ {0} private
The Y momentum.
Definition at line 228 of file SimTrackerHit.h.
Referenced by getMomentum().
pz_
float ldmx::SimTrackerHit::pz_ {0} private
The Z momentum.
Definition at line 233 of file SimTrackerHit.h.
Referenced by getMomentum().
time_
float ldmx::SimTrackerHit::time_ {0} private
The global time of the hit.
Definition at line 218 of file SimTrackerHit.h.
Referenced by getTime(), and setTime().
trackID_
int ldmx::SimTrackerHit::trackID_ {0} private
The Sim Track ID.
Definition at line 263 of file SimTrackerHit.h.
Referenced by getTrackID(), and setTrackID().
x_
float ldmx::SimTrackerHit::x_ {0} private
The X position.
Definition at line 243 of file SimTrackerHit.h.
Referenced by getPosition().
y_
float ldmx::SimTrackerHit::y_ {0} private
The Y position.
Definition at line 248 of file SimTrackerHit.h.
Referenced by getPosition().
z_
float ldmx::SimTrackerHit::z_ {0} private
The Z position.
Definition at line 253 of file SimTrackerHit.h.
Referenced by getPosition().
The documentation for this class was generated from the following file:
Event/include/Event/SimTrackerHit.h