LDMX Software: trigscint::QIEDecoder Class Reference
trigscint::QIEDecoder Class Reference
Public Member Functions
QIEDecoder (const std::string &name, framework::Process &process)
~QIEDecoder ()=default
virtual void configure (framework::config::Parameters &ps)
virtual void produce (framework::Event &event)
virtual void onFileOpen ()
virtual void onFileClose ()
virtual void onProcessStart ()
virtual void onProcessEnd ()
Public Member Functions inherited from framework::Producer
Producer (const std::string &name, Process &process)
virtual void beforeNewRun (ldmx::RunHeader &header)
Public Member Functions inherited from framework::EventProcessor
EventProcessor (const std::string &name, Process &process)
virtual ~EventProcessor ()
virtual void onNewRun (const ldmx::RunHeader &runHeader)
virtual void onFileOpen (EventFile &eventFile)
virtual void onFileClose (EventFile &eventFile)
template<class T >
const T & getCondition (const std::string &condition_name)
TDirectory * getHistoDirectory ()
void setStorageHint (framework::StorageControlHint hint)
void setStorageHint (framework::StorageControlHint hint, const std::string &purposeString)
int getLogFrequency () const
int getRunNumber () const
std::string getName () const
void createHistograms (const std::vector< framework::config::Parameters > &histos)
Private Attributes
std::string channelMapFileName_
the channel mapping
std::ifstream channelMapFile_
std::map< int, int > channelMap_
std::string inputCollection_
std::string outputCollection_
std::string inputPassName_
bool verbose_ {false}
int nChannels_ {50}
Additional Inherited Members
Static Public Member Functions inherited from framework::EventProcessor
static void declare (const std::string &classname, int classtype, EventProcessorMaker *)
Static Public Attributes inherited from framework::Producer
static const int CLASSTYPE {1}
Protected Member Functions inherited from framework::EventProcessor
void abortEvent ()
Protected Attributes inherited from framework::EventProcessor
HistogramHelper histograms_
Interface class for making and filling histograms.
NtupleManager & ntuple_ {NtupleManager::getInstance()}
Manager for any ntuples.
logging::logger theLog_
The logger for this EventProcessor.
Detailed Description
Definition at line 16 of file QIEDecoder.h.
Constructor & Destructor Documentation
QIEDecoder()
trigscint::QIEDecoder::QIEDecoder (const std::string & name, framework::Process & process) inline
Definition at line 18 of file QIEDecoder.h.
      : Producer(name, process) {}
~QIEDecoder()
trigscint::QIEDecoder::~QIEDecoder () default
Default destructor, closes up boost archive and input stream
Member Function Documentation
configure()
void trigscint::QIEDecoder::configure (framework::config::Parameters & ps) virtual
Configure our converter based off the configuration parameters decoded from the passed python script
Reimplemented from framework::EventProcessor.
Definition at line 8 of file QIEDecoder.cxx.
{
  // Configure this instance of the encoder
   outputCollection_ = ps.getParameter<std::string>("output_collection");
   inputCollection_ = ps.getParameter<std::string>("input_collection");
   inputPassName_ = ps.getParameter<std::string>("input_pass_name");
   channelMapFileName_ = ps.getParameter<std::string>("channel_map_file");
   nChannels_ = ps.getParameter<int>("number_channels");
   verbose_ = ps.getParameter<bool>("verbose");
   ldmx_log(debug) << "In configure, got parameters:" <<
     "\noutput_collection = " << outputCollection_ <<
     "\ninput_collection = " << inputCollection_ <<
     "\ninput_pass_name  = " << inputPassName_ <<
     "\nchannel_map_file = " <<  channelMapFileName_ <<
     "\nnumber_channels  = " <<  nChannels_ <<
     "\nverbose          = " << verbose_ ;
   channelMapFile_.open(channelMapFileName_, std::ios::in);
   if (! channelMapFile_.is_open() ){
     EXCEPTION_RAISE("BadMapFile",  "The channel mapping file cannot be opened."); // <-- appears this needs implementing first
     ldmx_log(fatal) << "The channel mapping file cannot be opened.";
     return;
   }
   int chID, elID;
   while (! channelMapFile_.eof() ){
     channelMapFile_ >> elID >> chID ;
     // make the map based on electronics ID, to look up channel ID.
     // the reason is, we will only know the elecID from the position
     // of the word in the stream. so these need to be strictly ordered.
     // writing the right bar in the right position is easier if we can just
     // read this map from beginning to end.
     // barID can always be set, or looked up, as a property of the digi.
     // here make the elecID the key (other way around when encoding)
     channelMap_.insert(std::pair<int,int>(elID, chID));
     ldmx_log(debug) << elID << "  chID " << chID ;
   }
   channelMapFile_.close();
   if (elID != nChannels_ - 1 )
     ldmx_log(fatal) << "The set number of channels " << nChannels_ << " seems not to match the number from the map (+1) :" << elID;
   return;
 }
References channelMapFileName_, and framework::config::Parameters::getParameter().
onFileClose()
void trigscint::QIEDecoder::onFileClose () virtual
Definition at line 191 of file QIEDecoder.cxx.
{
  ldmx_log(debug) << "Closing file!";
  return;
}
onFileOpen()
void trigscint::QIEDecoder::onFileOpen () virtual
Definition at line 185 of file QIEDecoder.cxx.
{
  ldmx_log(debug) << "Opening file!";
  return;
}
onProcessEnd()
void trigscint::QIEDecoder::onProcessEnd () virtual
Callback for the EventProcessor to take any necessary action when the processing of events finishes, such as calculating job-summary quantities.
Reimplemented from framework::EventProcessor.
Definition at line 203 of file QIEDecoder.cxx.
{
  ldmx_log(debug) << "Process ends!";
  return;
}
onProcessStart()
void trigscint::QIEDecoder::onProcessStart () virtual
Callback for the EventProcessor to take any necessary action when the processing of events starts, such as creating histograms.
Reimplemented from framework::EventProcessor.
Definition at line 197 of file QIEDecoder.cxx.
{
  ldmx_log(debug) << "Process starts!";
  return;
}
produce()
void trigscint::QIEDecoder::produce (framework::Event & event) virtual
Process the event and put new data products into it.
Parameters
event The Event to process.
Implements framework::Producer.
Definition at line 53 of file QIEDecoder.cxx.
{
    ldmx_log(debug)
      << "QIEDecoder: produce() starts! Event number: "
      << event.getEventHeader().getEventNumber();
  int nSamp = QIEStream::NUM_SAMPLES ;
  ldmx_log(debug) << "num samples = " << nSamp;
  ldmx_log(debug) << "Looking up input collection " << inputCollection_ << "_" << inputPassName_;
  const auto eventStream{event.getCollection<uint8_t>( inputCollection_, inputPassName_)};
  ldmx_log(debug) << "Got input collection" << inputCollection_ << "_" << inputPassName_;
  // trigger ID event number
  // this is the one word that spans several bytes
  uint16_t triggerID =0; // =eventStream.at(QIEStream::TRIGID_POS);
  for (int iW = 0 ; iW < QIEStream::TRIGID_LEN_BYTES; iW++) {
    //assume the whole 2B are written as a single 16 bits word
    int pos = QIEStream::TRIGID_POS+(QIEStream::TRIGID_LEN_BYTES -1 - iW);
    uint8_t tIDword = eventStream.at( pos );
    ldmx_log(debug) << "trigger word at position " << pos << " (with iW = " << iW << ") = " << std::bitset<8>(tIDword ) ;
    triggerID |= (tIDword << iW*8); //shift by a byte at a time
  }
  ldmx_log(debug) << " got triggerID " << std::bitset<16>(triggerID) ; //eventStream.at(0);
  if ( triggerID != event.getEventHeader().getEventNumber() ) {
    // this probably only applies to digi emulation,
    // unless an event number is explicitly set in unpacking
    ldmx_log(fatal) << "Got event number mismatch: framework reports " <<
      event.getEventHeader().getEventNumber() <<", stream says " << triggerID ;
  }
  // error word
  /* the error word contains
     - 4 trailing reserved 0's, for now
     - isCIDunsync : if there is a mismatch between CID reported by channels within the same time sample
     - isCIDskipped : if there is a gap in the CID increment of a channel beweeen samples
     - isCRC0malformed : if there was an issue with CRC from fiber0
     - isCRC1malformed : if there was an issue with CRC from fiber1
  */
  uint8_t flags = eventStream.at(QIEStream::ERROR_POS);
  bool isCIDskipped { (flags >> QIEStream::CID_SKIP_POS) & mask8<QIEStream::FLAG_SIZE_BITS>::m};
  bool isCIDunsync { (flags >> QIEStream::CID_UNSYNC_POS) & mask8<QIEStream::FLAG_SIZE_BITS>::m};
  bool isCRC1malformed{ (flags >> QIEStream::CRC1_ERR_POS) & mask8<QIEStream::FLAG_SIZE_BITS>::m};
  bool isCRC0malformed{ (flags >> QIEStream::CRC0_ERR_POS) & mask8<QIEStream::FLAG_SIZE_BITS>::m};
  //checksum
  uint8_t referenceChecksum = 30;  // really, this is just a random number for now. TODO> implement a checksum set/get
  int checksum = eventStream.at(QIEStream::CHECKSUM_POS);
  if ( checksum != referenceChecksum)
    ldmx_log(fatal) << "Got checksum mismatch: expected " << (int)referenceChecksum << ", stream says " << checksum ;
  if (isCIDunsync)
    ldmx_log(debug) << "Found unsynced CIDs!";
  if (isCIDskipped)
    ldmx_log(fatal) << "Found skipped CIDs!" ;
  /* -- TS event header done; read the channel contents -- */
  std::vector<trigscint::TrigScintQIEDigis> outDigis;
  std::map < int, std::vector<int>> ADCmap;
  std::map < int, std::vector<int>> TDCmap;
  // read in words from the stream. line them up per channel and time sample.
  // channels are in the electronics ordering
  int iWstart = std::max( std::max(QIEStream::ERROR_POS, QIEStream::CHECKSUM_POS),
                          QIEStream::TRIGID_POS+(QIEStream::TRIGID_LEN_BYTES)) +1;  //probably overkill :D should be 4
  int nWords = nSamp*nChannels_*2 + iWstart; //1 ADC, 1 TDC per channel per sample, + the words in the header
  int iWord = iWstart;
  ldmx_log(debug) << "Event parsing starts at vector idx " << iWstart << " and nWords = " << nWords;
  // outer loop: over nSamples
  // inner loop over nChannels to get ADCs, then repeat to get TDCs
  for (int iS = 0; iS < nSamp; iS++) {
    for (int iQ = 0; iQ < nChannels_ ; iQ++) {
      if ( iWord >= nWords ) {
        ldmx_log(fatal) << "More words than expected! Breaking ADC loop in sample " << iS << " at iQ = " << iQ;
        break;
      }
      uint8_t val = eventStream.at(iWord);
      if (val > 0) {    //add only the digis with non-zero ADC value
        ldmx_log(debug) << "got ADC value " << (unsigned)val << " at channel (elec) idx " << iQ ;
        if ( ADCmap.find( iQ ) == ADCmap.end() ) { // we have a new channel
          std::vector <int > adcs(nSamp, 0);
          ADCmap.insert(std::pair<int, std::vector <int> >(iQ, adcs));
        }
        ADCmap[ iQ ].at(iS) = val;
      }
      iWord++;
    }
    for (int iQ = 0; iQ < nChannels_ ; iQ++) {
      if ( iWord >= nWords ) {
        ldmx_log(debug) << "More words than expected! Breaking TDC loop in sample " << iS << " at iQ = " << iQ;
        break;
      }
      uint8_t val = eventStream.at(iWord);
      if (val > 0) { // TODO: check if this channel is also present in ADC map? in the end?
        ldmx_log(debug) << "got TDC value " << (unsigned)val << " at channel (elec) idx " << iQ ;;
        if ( TDCmap.find( iQ ) == TDCmap.end() ) { // we have a new channel
          std::vector <int > tdcs(nSamp, 0);
          TDCmap.insert(std::pair<int, std::vector <int> >(iQ, tdcs));
        }
        //this is LETDC; only the two most significant bits included
        // they are shipped as least significant bits --> shift them
        TDCmap[ iQ ].at(iS) = val*16;
      }
      iWord++;
    }
    ldmx_log(debug) << "Done with sample " << iS ;
  }
  ldmx_log(debug) << "Done reading in header, ADC and TDC for event " << (unsigned)triggerID ;
  for (std::map<int, std::vector<int>>::iterator itr = ADCmap.begin(); itr != ADCmap.end(); ++itr) {
    TrigScintQIEDigis  digi;
    digi.setADC( itr->second );
    if (channelMap_.find( itr->first ) == channelMap_.end() ) {
      ldmx_log(fatal) << "Couldn't find the bar ID corresponding to electronics ID " << itr->first << "!! Skipping." ;
      continue;
    }
    int bar = channelMap_[itr->first];
    digi.setChanID( bar );
    digi.setTDC( TDCmap[itr->first] );
    outDigis.push_back( digi );
    ldmx_log(debug) << "Iterator points to key " << itr->first
                    << " and mapped channel supposedly  is " << bar ;
    ldmx_log(debug) << "Made digi with barID = " << digi.getChanID()
                    << ", third adc value " << digi.getADC().at(2)
                    << " and third tdc " << digi.getTDC().at(2) ;
  }
  event.add(outputCollection_, outDigis);
  }
References trigscint::TrigScintQIEDigis::getADC(), trigscint::TrigScintQIEDigis::getChanID(), framework::Event::getEventHeader(), ldmx::EventHeader::getEventNumber(), trigscint::TrigScintQIEDigis::getTDC(), trigscint::TrigScintQIEDigis::setADC(), trigscint::TrigScintQIEDigis::setChanID(), and trigscint::TrigScintQIEDigis::setTDC().
Member Data Documentation
channelMap_
std::map< int, int> trigscint::QIEDecoder::channelMap_ private
Definition at line 47 of file QIEDecoder.h.
channelMapFile_
std::ifstream trigscint::QIEDecoder::channelMapFile_ private
Definition at line 46 of file QIEDecoder.h.
channelMapFileName_
std::string trigscint::QIEDecoder::channelMapFileName_ private
the channel mapping
Definition at line 45 of file QIEDecoder.h.
Referenced by configure().
inputCollection_
std::string trigscint::QIEDecoder::inputCollection_ private
Definition at line 50 of file QIEDecoder.h.
inputPassName_
std::string trigscint::QIEDecoder::inputPassName_ private
Definition at line 52 of file QIEDecoder.h.
nChannels_
int trigscint::QIEDecoder::nChannels_ {50} private
Definition at line 58 of file QIEDecoder.h.
outputCollection_
std::string trigscint::QIEDecoder::outputCollection_ private
Definition at line 51 of file QIEDecoder.h.
verbose_
bool trigscint::QIEDecoder::verbose_ {false} private
Definition at line 55 of file QIEDecoder.h.
The documentation for this class was generated from the following files:
TrigScint/include/TrigScint/QIEDecoder.h
TrigScint/src/TrigScint/QIEDecoder.cxx