LDMX Software: ecal::EcalRecProducer Class Reference
ecal::EcalRecProducer Class Reference
Performs basic ECal reconstruction.
#include <EcalRecProducer.h>
Public Member Functions
EcalRecProducer (const std::string &name, framework::Process &process)
virtual ~EcalRecProducer ()
virtual void configure (framework::config::Parameters &)
virtual void produce (framework::Event &event)
Public Member Functions inherited from framework::Producer
Producer (const std::string &name, Process &process)
virtual void beforeNewRun (ldmx::RunHeader &header)
Public Member Functions inherited from framework::EventProcessor
EventProcessor (const std::string &name, Process &process)
virtual ~EventProcessor ()
virtual void onNewRun (const ldmx::RunHeader &runHeader)
virtual void onFileOpen (EventFile &eventFile)
virtual void onFileClose (EventFile &eventFile)
virtual void onProcessStart ()
virtual void onProcessEnd ()
template<class T >
const T & getCondition (const std::string &condition_name)
TDirectory * getHistoDirectory ()
void setStorageHint (framework::StorageControlHint hint)
void setStorageHint (framework::StorageControlHint hint, const std::string &purposeString)
int getLogFrequency () const
int getRunNumber () const
std::string getName () const
void createHistograms (const std::vector< framework::config::Parameters > &histos)
Private Attributes
std::string digiCollName_
std::string digiPassName_
std::string simHitCollName_
simhit collection name
std::string simHitPassName_
simhit pass name
std::string recHitCollName_
output hit collection name
double mip_si_energy_
Energy [MeV] deposited by a MIP in Si 0.5mm thick.
double clock_cycle_
Length of clock cycle [ns].
double charge_per_mip_
Number of electrons generated by average MIP in Si 0.5mm thick.
std::vector< double > layerWeights_
double secondOrderEnergyCorrection_
Additional Inherited Members
Static Public Member Functions inherited from framework::EventProcessor
static void declare (const std::string &classname, int classtype, EventProcessorMaker *)
Static Public Attributes inherited from framework::Producer
static const int CLASSTYPE {1}
Protected Member Functions inherited from framework::EventProcessor
void abortEvent ()
Protected Attributes inherited from framework::EventProcessor
HistogramHelper histograms_
Interface class for making and filling histograms.
NtupleManager & ntuple_ {NtupleManager::getInstance()}
Manager for any ntuples.
logging::logger theLog_
The logger for this EventProcessor.
Detailed Description
Performs basic ECal reconstruction.
Reconstruction is done from the EcalDigi samples. Some hard-coded parameters are used for position and energy calculation.
Definition at line 34 of file EcalRecProducer.h.
Constructor & Destructor Documentation
EcalRecProducer()
ecal::EcalRecProducer::EcalRecProducer (const std::string & name, framework::Process & process)
Constructor
Definition at line 13 of file EcalRecProducer.cxx.
    : Producer(name, process) {}
~EcalRecProducer()
ecal::EcalRecProducer::~EcalRecProducer () virtual
Destructor
Definition at line 17 of file EcalRecProducer.cxx.
{}
Member Function Documentation
configure()
void ecal::EcalRecProducer::configure (framework::config::Parameters & ps) virtual
Grabs configure parameters from the python config file.
Reimplemented from framework::EventProcessor.
Definition at line 19 of file EcalRecProducer.cxx.
{
  // collection names
  digiCollName_ = ps.getParameter<std::string>("digiCollName");
  digiPassName_ = ps.getParameter<std::string>("digiPassName");
  simHitCollName_ = ps.getParameter<std::string>("simHitCollName");
  simHitPassName_ = ps.getParameter<std::string>("simHitPassName");
  recHitCollName_ = ps.getParameter<std::string>("recHitCollName");
  layerWeights_ = ps.getParameter<std::vector<double>>("layerWeights");
  secondOrderEnergyCorrection_ =
      ps.getParameter<double>("secondOrderEnergyCorrection");
  mip_si_energy_ = ps.getParameter<double>("mip_si_energy");
  clock_cycle_ = ps.getParameter<double>("clock_cycle");
  charge_per_mip_ = ps.getParameter<double>("charge_per_mip");
}
References charge_per_mip_, clock_cycle_, digiCollName_, digiPassName_, framework::config::Parameters::getParameter(), layerWeights_, mip_si_energy_, recHitCollName_, secondOrderEnergyCorrection_, simHitCollName_, and simHitPassName_.
produce()
void ecal::EcalRecProducer::produce (framework::Event & event) virtual
Produce EcalHits and put them into the event bus using the EcalDigis as input.
This function unfolds the digi samples taken by the HGC ROC and reconstructs their energy using knowledge of how the chip operates and the position using EcalHexReadout.
Negative Electron (charge) count This reconstruction error occurs when the ADC value is below the ADC pedestal for that channel. In the normal running mode, this will never happen because our front-end (the digi emulator or the digitizer itself) will suppress any signals that are below the readout threshold. Nevertheless, in some running modes, we don't have this zero suppression, so we need to check that the reconstruction charge (count of electrons) is non-negative.
Implements framework::Producer.
Definition at line 36 of file EcalRecProducer.cxx.
{
  // Get the Ecal Geometry
  const ldmx::EcalHexReadout& hexReadout = getCondition<ldmx::EcalHexReadout>(
      ldmx::EcalHexReadout::CONDITIONS_OBJECT_NAME);
  // Get the reconstruction parameters
  EcalReconConditions the_conditions(
      getCondition<conditions::DoubleTableCondition>(
          EcalReconConditions::CONDITIONS_NAME));
  std::vector<ldmx::EcalHit> ecalRecHits;
  auto ecalDigis =
      event.getObject<ldmx::HgcrocDigiCollection>(digiCollName_, digiPassName_);
  // loop through digis
  for (auto digi : ecalDigis) {
    // ID from first digi sample
    //  assuming rest of samples have same ID
    ldmx::EcalID id(digi.id());
    // ID to real space position
    double x, y, z;
    hexReadout.getCellAbsolutePosition(id, x, y, z);
    // TOA is the time of arrival with respect to the 25ns clock window
    //  TODO what to do if hit NOT in first clock cycle?
    double timeRelClock25 = digi.soi().toa() * (clock_cycle_ / 1024);  // ns
    double hitTime = timeRelClock25;
    // get the estimated charge deposited from digi samples
    double charge(0.);
    /* debug printout
    std::cout << "Recon { "
        << "ID: " << id << ", "
        << "TOA: " << hitTime << "ns } ";
        */
    if (digi.isTOT()) {
      // TOT - number of clock ticks that pulse was over threshold
      //  this is related to the amplitude of the pulse approximately through a
      //  linear drain rate the amplitude of the pulse is related to the energy
      //  deposited
      // convert the time over threshold into a total energy deposited in the
      // silicon
      //  (time over threshold [ns] - pedestal) * gain
      charge = (digi.tot() - the_conditions.totPedestal(id)) *
               the_conditions.totGain(id);
      /* debug printout
      std::cout << "TOT Mode -> " << digi.tot() << "TDC -> " << charge << " fC";
       */
    } else {
      // ADC mode of readout
      // ADC - voltage measurement at a specific time of the pulse
      // Pulse Shape:
      //  p[0]/(1.0+exp(p[1](t-p[2]+p[3]-p[4])))/(1.0+exp(p[5]*(t-p[6]+p[3]-p[4])))
      //  p[0] = amplitude to be fit (TBD)
      //  p[1] = -0.345 shape parameter - rate of up slope
      //  p[2] = 70.6547 shape parameter - time of up slope relative to shape
      //  fit p[3] = 77.732 shape parameter - time of peak relative to shape fit
      //  p[4] = peak time to be fit (TBD)
      //  p[5] = 0.140068 shape parameter - rate of down slope
      //  p[6] = 87.7649 shape paramter - time of down slope relative to shape
      //  fit
      // These measurements can be used to fit the pulse shape if TOT is not
      // available. For now, we simply take the measurement of the SOI as the
      // peak amplitude.
      charge = (digi.soi().adc_t() - the_conditions.adcPedestal(id)) *
               the_conditions.adcGain(id);
      /* debug printout
      std::cout << "ADC Mode -> " << charge << " fC";
       */
    }
    if (charge < 0) continue;
    double num_mips_equivalent = charge / charge_per_mip_;
    double energy_deposited_in_Si = num_mips_equivalent * mip_si_energy_;
    /* debug printout
    std::cout << " -> " << num_mips_equivalent
        << " equiv MIPs -> " << energy_deposited_in_Si << " MeV"
        << std::endl;
     */
    // incorporate layer weights
    double reconstructed_energy =
        (num_mips_equivalent *
             layerWeights_.at(
                 id.layer())       // energy lost in non-sensitive layers
         + energy_deposited_in_Si  // energy deposited in Si itself
         ) *
        secondOrderEnergyCorrection_;
    // copy over information to rec hit structure in new collection
    ldmx::EcalHit recHit;
    recHit.setID(id.raw());
    recHit.setXPos(x);
    recHit.setYPos(y);
    recHit.setZPos(z);
    recHit.setAmplitude(energy_deposited_in_Si);
    recHit.setEnergy(reconstructed_energy);
    recHit.setTime(hitTime);
    ecalRecHits.push_back(recHit);
  }
  if (event.exists(simHitCollName_, simHitPassName_)) {
    // ecal sim hits exist ==> label which hits are real and which are pure
    // noise
    auto ecalSimHits{event.getCollection<ldmx::SimCalorimeterHit>(
        simHitCollName_, simHitPassName_)};
    std::set<int> real_hits;
    for (auto const& sim_hit : ecalSimHits) real_hits.insert(sim_hit.getID());
    for (auto& hit : ecalRecHits)
      hit.setNoise(real_hits.find(hit.getID()) == real_hits.end());
  }
  // add collection to event bus
  event.add(recHitCollName_, ecalRecHits);
}
References ecal::EcalReconConditions::adcGain(), ecal::EcalReconConditions::adcPedestal(), charge_per_mip_, clock_cycle_, ecal::EcalReconConditions::CONDITIONS_NAME, digiCollName_, digiPassName_, framework::Event::exists(), ldmx::EcalHexReadout::getCellAbsolutePosition(), layerWeights_, mip_si_energy_, recHitCollName_, secondOrderEnergyCorrection_, ldmx::CalorimeterHit::setAmplitude(), ldmx::CalorimeterHit::setEnergy(), ldmx::CalorimeterHit::setID(), ldmx::CalorimeterHit::setTime(), ldmx::CalorimeterHit::setXPos(), ldmx::CalorimeterHit::setYPos(), ldmx::CalorimeterHit::setZPos(), simHitCollName_, simHitPassName_, ecal::EcalReconConditions::totGain(), and ecal::EcalReconConditions::totPedestal().
Member Data Documentation
charge_per_mip_
double ecal::EcalRecProducer::charge_per_mip_ private
Number of electrons generated by average MIP in Si 0.5mm thick.
Definition at line 84 of file EcalRecProducer.h.
Referenced by configure(), and produce().
clock_cycle_
double ecal::EcalRecProducer::clock_cycle_ private
Length of clock cycle [ns].
Definition at line 81 of file EcalRecProducer.h.
Referenced by configure(), and produce().
digiCollName_
std::string ecal::EcalRecProducer::digiCollName_ private
Digi Collection Name to use as input
Definition at line 63 of file EcalRecProducer.h.
Referenced by configure(), and produce().
digiPassName_
std::string ecal::EcalRecProducer::digiPassName_ private
Digi Pass Name to use as input
Definition at line 66 of file EcalRecProducer.h.
Referenced by configure(), and produce().
layerWeights_
std::vector<double> ecal::EcalRecProducer::layerWeights_ private
Layer Weights to use for this reconstruction
Layer weights account for the energy lost in the absorber directly in front of the Silicon layer where the measured energy was deposited. These are determined by calculating the average amount of energy lost by a MIP passing through the extra material between sensitive layers.
Definition at line 94 of file EcalRecProducer.h.
Referenced by configure(), and produce().
mip_si_energy_
double ecal::EcalRecProducer::mip_si_energy_ private
Energy [MeV] deposited by a MIP in Si 0.5mm thick.
Definition at line 78 of file EcalRecProducer.h.
Referenced by configure(), and produce().
recHitCollName_
std::string ecal::EcalRecProducer::recHitCollName_ private
output hit collection name
Definition at line 75 of file EcalRecProducer.h.
Referenced by configure(), and produce().
secondOrderEnergyCorrection_
double ecal::EcalRecProducer::secondOrderEnergyCorrection_ private
Second Order Energy Correction to use for this reconstruction
This is a shift applied to all of the energies in order to have the mean of the total energy deposited in the ECal be accurate. This is less physically motivated than the layer weights and is more of a calibration number.
Definition at line 104 of file EcalRecProducer.h.
Referenced by configure(), and produce().
simHitCollName_
std::string ecal::EcalRecProducer::simHitCollName_ private
simhit collection name
Definition at line 69 of file EcalRecProducer.h.
Referenced by configure(), and produce().
simHitPassName_
std::string ecal::EcalRecProducer::simHitPassName_ private
simhit pass name
Definition at line 72 of file EcalRecProducer.h.
Referenced by configure(), and produce().
The documentation for this class was generated from the following files:
Ecal/include/Ecal/EcalRecProducer.h
Ecal/src/Ecal/EcalRecProducer.cxx