LDMX Software: ecal::EcalClusterProducer Class Reference
ecal::EcalClusterProducer Class Reference
Simple algorithm that does clustering in the ECal.
#include <EcalClusterProducer.h>
Public Member Functions
EcalClusterProducer (const std::string &name, framework::Process &process)
void configure (framework::config::Parameters &parameters) final override
virtual void produce (framework::Event &event)
Public Member Functions inherited from framework::Producer
Producer (const std::string &name, Process &process)
virtual void produce (Event &event)=0
virtual void beforeNewRun (ldmx::RunHeader &header)
Public Member Functions inherited from framework::EventProcessor
EventProcessor (const std::string &name, Process &process)
virtual ~EventProcessor ()
virtual void configure (framework::config::Parameters &parameters)
virtual void onNewRun (const ldmx::RunHeader &runHeader)
virtual void onFileOpen (EventFile &eventFile)
virtual void onFileClose (EventFile &eventFile)
virtual void onProcessStart ()
virtual void onProcessEnd ()
template<class T >
const T & getCondition (const std::string &condition_name)
TDirectory * getHistoDirectory ()
void setStorageHint (framework::StorageControlHint hint)
void setStorageHint (framework::StorageControlHint hint, const std::string &purposeString)
int getLogFrequency () const
int getRunNumber () const
std::string getName () const
void createHistograms (const std::vector< framework::config::Parameters > &histos)
Private Attributes
double seedThreshold_ {0}
double cutoff_ {0}
std::string digisPassName_
std::string algoCollName_
std::string clusterCollName_
TString algoName_
Additional Inherited Members
Static Public Member Functions inherited from framework::EventProcessor
static void declare (const std::string &classname, int classtype, EventProcessorMaker *)
Static Public Attributes inherited from framework::Producer
static const int CLASSTYPE {1}
Protected Member Functions inherited from framework::EventProcessor
void abortEvent ()
Protected Attributes inherited from framework::EventProcessor
HistogramHelper histograms_
Interface class for making and filling histograms.
NtupleManager & ntuple_ {NtupleManager::getInstance()}
Manager for any ntuples.
logging::logger theLog_
The logger for this EventProcessor.
Detailed Description
Simple algorithm that does clustering in the ECal.
Definition at line 45 of file EcalClusterProducer.h.
Constructor & Destructor Documentation
EcalClusterProducer()
ecal::EcalClusterProducer::EcalClusterProducer (const std::string & name, framework::Process & process)
Definition at line 11 of file EcalClusterProducer.cxx.
    : Producer(name, process) {}
~EcalClusterProducer()
ecal::EcalClusterProducer::~EcalClusterProducer () virtual
Definition at line 15 of file EcalClusterProducer.cxx.
{}
Member Function Documentation
configure()
void ecal::EcalClusterProducer::configure (framework::config::Parameters & parameters) final override virtual
Configure the processor using the given user specified parameters.
Parameters
parameters Set of parameters used to configure this processor.
Reimplemented from framework::EventProcessor.
Definition at line 17 of file EcalClusterProducer.cxx.
{
  cutoff_ = parameters.getParameter<double>("cutoff");
  seedThreshold_ = parameters.getParameter<double>("seedThreshold");
  digisPassName_ = parameters.getParameter<std::string>("digisPassName");
  algoCollName_ = parameters.getParameter<std::string>("algoCollName");
  algoName_ = parameters.getParameter<std::string>("algoName");
  clusterCollName_ = parameters.getParameter<std::string>("clusterCollName");
}
References framework::config::Parameters::getParameter().
produce()
void ecal::EcalClusterProducer::produce (framework::Event & event) virtual
Process the event and put new data products into it.
Parameters
event The Event to process.
Implements framework::Producer.
Definition at line 26 of file EcalClusterProducer.cxx.
{
  // Get the Ecal Geometry
  const ldmx::EcalHexReadout& hexReadout = getCondition<ldmx::EcalHexReadout>(
      ldmx::EcalHexReadout::CONDITIONS_OBJECT_NAME);
  TemplatedClusterFinder<MyClusterWeight> cf;
  std::vector<ldmx::EcalHit> ecalHits =
      event.getCollection<ldmx::EcalHit>("ecalDigis", digisPassName_);
  int nEcalDigis = ecalHits.size();
  // Don't do anything if there are no ECal digis!
  if (!(nEcalDigis > 0)) {
    return;
  }
  for (ldmx::EcalHit& hit : ecalHits) {
    // Skip zero energy digis.
    if (hit.getEnergy() == 0) {
      continue;
    }
    cf.add(&hit, hexReadout);
  }
  cf.cluster(seedThreshold_, cutoff_);
  std::vector<WorkingCluster> wcVec = cf.getClusters();
  std::map<int, double> cWeights = cf.getWeights();
  ldmx::ClusterAlgoResult algoResult;
  algoResult.set(algoName_, 3, cWeights.rbegin()->first);
  algoResult.setAlgoVar(0, cutoff_);
  algoResult.setAlgoVar(1, seedThreshold_);
  algoResult.setAlgoVar(2, cf.getNSeeds());
  std::map<int, double>::iterator it = cWeights.begin();
  for (it = cWeights.begin(); it != cWeights.end(); it++) {
    algoResult.setWeight(it->first, it->second / 100);
  }
  std::vector<ldmx::EcalCluster> ecalClusters;
  for (int aWC = 0; aWC < wcVec.size(); aWC++) {
    ldmx::EcalCluster cluster;
    cluster.setEnergy(wcVec[aWC].centroid().E());
    cluster.setCentroidXYZ(wcVec[aWC].centroid().Px(),
                           wcVec[aWC].centroid().Py(),
                           wcVec[aWC].centroid().Pz());
    cluster.setNHits(wcVec[aWC].getHits().size());
    cluster.addHits(wcVec[aWC].getHits());
    ecalClusters.push_back(cluster);
  }
  event.add(clusterCollName_, ecalClusters);
  event.add(algoCollName_, algoResult);
}
References ldmx::EcalCluster::addHits(), ldmx::ClusterAlgoResult::set(), ldmx::ClusterAlgoResult::setAlgoVar(), ldmx::EcalCluster::setCentroidXYZ(), ldmx::EcalCluster::setEnergy(), ldmx::EcalCluster::setNHits(), and ldmx::ClusterAlgoResult::setWeight().
Member Data Documentation
algoCollName_
std::string ecal::EcalClusterProducer::algoCollName_ private
Definition at line 64 of file EcalClusterProducer.h.
algoName_
TString ecal::EcalClusterProducer::algoName_ private
The name of the cluster algorithm used.
Definition at line 68 of file EcalClusterProducer.h.
clusterCollName_
std::string ecal::EcalClusterProducer::clusterCollName_ private
Definition at line 65 of file EcalClusterProducer.h.
cutoff_
double ecal::EcalClusterProducer::cutoff_ {0} private
Definition at line 62 of file EcalClusterProducer.h.
digisPassName_
std::string ecal::EcalClusterProducer::digisPassName_ private
Definition at line 63 of file EcalClusterProducer.h.
seedThreshold_
double ecal::EcalClusterProducer::seedThreshold_ {0} private
Definition at line 61 of file EcalClusterProducer.h.
The documentation for this class was generated from the following files:
Ecal/include/Ecal/EcalClusterProducer.h
Ecal/src/Ecal/EcalClusterProducer.cxx