LDMX Software: ldmx::SimCalorimeterHit Class Reference
ldmx::SimCalorimeterHit Class Reference
Stores simulated calorimeter hit information.
#include <SimCalorimeterHit.h>
Classes
class Contrib
Information about a contribution to the hit in the associated cell.
Public Member Functions
SimCalorimeterHit ()
virtual ~SimCalorimeterHit ()
void Clear ()
void Print () const
int getID () const
void setID (const int id)
float getEdep () const
void setEdep (const float edep)
std::vector< float > getPosition () const
std::vector< float > getPreStepPosition () const
std::vector< float > getPostStepPosition () const
void setPosition (const float x, const float y, const float z)
void setPreStepPosition (const float x, const float y, const float z)
void setPostStepPosition (const float x, const float y, const float z)
void setPathLength (const float length)
void setPreStepTime (const float time)
void setPostStepTime (const float time)
void setVelocity (float velocity)
float getTime () const
float getPreStepTime () const
float getPostStepTime () const
float getVelocity () const
void setTime (const float time)
unsigned getNumberOfContribs () const
void addContrib (int incidentID, int trackID, int pdgCode, float edep, float time)
Contrib getContrib (int i) const
int findContribIndex (int trackID, int pdgCode) const
void updateContrib (int i, float edep, float time)
bool operator< (const SimCalorimeterHit &rhs) const
Static Public Attributes
static const std::string ECAL_COLLECTION
name of the ecal sim collection, should match gdml
static const std::string HCAL_COLLECTION
name of the hcal sim collection, should match gdml
Private Attributes
int id_ {0}
float edep_ {0}
float x_ {0}
float y_ {0}
float z_ {0}
float time_ {0}
std::vector< int > trackIDContribs_
std::vector< int > incidentIDContribs_
std::vector< int > pdgCodeContribs_
std::vector< float > edepContribs_
std::vector< float > timeContribs_
unsigned nContribs_ {0}
float pathLength_ {-1}
float preStepX_ {0}
float preStepY_ {0}
float preStepZ_ {0}
float preStepTime_ {0}
float postStepX_ {0}
float postStepY_ {0}
float postStepZ_ {0}
float postStepTime_ {0}
float velocity_ {-1}
Detailed Description
Stores simulated calorimeter hit information.
Note
This class represents simulated hit information from a calorimeter detector. It provides access to the cell ID, energy deposition, cell position and time. Additionally, individual depositions or steps from MC particles are tabulated as contributions stored in vectors. Contribution information includes a reference to the relevant SimParticle, the PDG code of the actual particle which deposited energy (may be different from the actual SimParticle), the time of the contribution and the energy deposition.
Definition at line 31 of file SimCalorimeterHit.h.
Constructor & Destructor Documentation
SimCalorimeterHit()
ldmx::SimCalorimeterHit::SimCalorimeterHit ()
Class constructor.
~SimCalorimeterHit()
virtual ldmx::SimCalorimeterHit::~SimCalorimeterHit () virtual
Class destructor.
Member Function Documentation
addContrib()
void ldmx::SimCalorimeterHit::addContrib (int incidentID, int trackID, int pdgCode, float edep, float time)
Add a hit contribution from a SimParticle.
Parameters
incidentID the Geant4 track ID for the particle's parent incident on the Calorimeter region
trackID the Geant4 track ID for the particle
pdgCode The PDG code of the actual track.
edep The energy deposition of the hit [MeV].
time The time of the hit [ns].
Referenced by simcore::TrigScintSD::ProcessHits().
Clear()
void ldmx::SimCalorimeterHit::Clear ()
Clear the data in the object.
findContribIndex()
int ldmx::SimCalorimeterHit::findContribIndex (int trackID, int pdgCode) const
Find the index of a hit contribution from a SimParticle and PDG code.
Parameters
trackID the track ID of the particle causing the hit
pdgCode The PDG code of the contribution.
Returns
The index of the contribution or -1 if none exists.
getContrib()
Contrib ldmx::SimCalorimeterHit::getContrib (int i) const
Get a hit contribution by index.
Parameters
i The index of the hit contribution.
Returns
The hit contribution at the index.
Referenced by hcal::HcalDigiProducer::produce().
getEdep()
float ldmx::SimCalorimeterHit::getEdep () const inline
Get the energy deposition of the hit [MeV].
Returns
The energy deposition of the hit.
Definition at line 106 of file SimCalorimeterHit.h.
{ return edep_; }
References edep_.
getID()
int ldmx::SimCalorimeterHit::getID () const inline
Get the detector ID.
Returns
The detector ID.
Definition at line 94 of file SimCalorimeterHit.h.
{ return id_; }
References id_.
Referenced by ecal::EcalDigiProducer::produce(), and hcal::HcalDigiProducer::produce().
getNumberOfContribs()
unsigned ldmx::SimCalorimeterHit::getNumberOfContribs () const inline
Get the number of hit contributions.
Returns
The number of hit contributions.
Definition at line 232 of file SimCalorimeterHit.h.
{ return nContribs_; }
References nContribs_.
Referenced by dqm::SimObjects::analyze(), and hcal::HcalDigiProducer::produce().
getPosition()
std::vector< float > ldmx::SimCalorimeterHit::getPosition () const inline
Get the XYZ position of the hit [mm].
Returns
The XYZ position of the hit.
Definition at line 118 of file SimCalorimeterHit.h.
{ return {x_, y_, z_}; }
References x_, y_, and z_.
Referenced by hcal::HcalDigiProducer::produce().
getPostStepPosition()
std::vector< float > ldmx::SimCalorimeterHit::getPostStepPosition () const inline
Get the XYZ post-step position of the hit in the coordinate frame of the sensitive volume [mm].
Returns
The XYZ position of the hit.
Definition at line 131 of file SimCalorimeterHit.h.
{ return {postStepX_, postStepY_, postStepZ_}; }
References postStepX_.
getPostStepTime()
float ldmx::SimCalorimeterHit::getPostStepTime () const inline
Get the post-step time of the hit [ns].
Returns
The global time of the hit after the interaction.
Definition at line 213 of file SimCalorimeterHit.h.
{ return postStepTime_; }
References postStepTime_.
getPreStepPosition()
std::vector< float > ldmx::SimCalorimeterHit::getPreStepPosition () const inline
Get the XYZ pre-step position of the hit in the coordinate frame of the sensitive volume [mm].
Returns
The local XYZ position of the hit.
Definition at line 125 of file SimCalorimeterHit.h.
{ return {preStepX_, preStepY_, preStepZ_}; }
References preStepX_.
getPreStepTime()
float ldmx::SimCalorimeterHit::getPreStepTime () const inline
Get the pre-step time of the hit [ns].
Returns
The global time of the hit before the interaction.
Definition at line 208 of file SimCalorimeterHit.h.
{ return preStepTime_; }
References preStepTime_.
getTime()
float ldmx::SimCalorimeterHit::getTime () const inline
Get the global time of the hit [ns].
Returns
The global time of the hit.
Definition at line 203 of file SimCalorimeterHit.h.
{ return time_; }
References time_.
Referenced by operator<().
getVelocity()
float ldmx::SimCalorimeterHit::getVelocity () const inline
Get the track velocity of the hit [mm/ns].
Returns
Thetrack velocity of the hit.
Definition at line 219 of file SimCalorimeterHit.h.
{return velocity_;}
References velocity_.
operator<()
bool ldmx::SimCalorimeterHit::operator< (const SimCalorimeterHit & rhs) const inline
Sort by time of hit
Definition at line 273 of file SimCalorimeterHit.h.
{
    return this->getTime() < rhs.getTime();
  }
References getTime().
Print()
void ldmx::SimCalorimeterHit::Print () const
Print out the object.
Referenced by recon::OverlayProducer::produce().
setEdep()
void ldmx::SimCalorimeterHit::setEdep (const float edep) inline
Set the energy deposition of the hit [MeV].
Parameters
edep The energy deposition of the hit.
Definition at line 112 of file SimCalorimeterHit.h.
{ this->edep_ = edep; }
References edep_.
setID()
void ldmx::SimCalorimeterHit::setID (const int id) inline
Set the detector ID. @id The detector ID.
Definition at line 100 of file SimCalorimeterHit.h.
{ this->id_ = id; }
References id_.
Referenced by simcore::TrigScintSD::ProcessHits().
setPathLength()
void ldmx::SimCalorimeterHit::setPathLength (const float length) inline
Set the physical path length for the interaction [mm].
Parameters
length The physical path lenght
Definition at line 172 of file SimCalorimeterHit.h.
{
    pathLength_ = length;
  }
References pathLength_.
Referenced by simcore::TrigScintSD::ProcessHits().
setPosition()
void ldmx::SimCalorimeterHit::setPosition (const float x, const float y, const float z) inline
Set the XYZ position of the hit [mm].
Parameters
x The X position.
y The Y position.
z The Z position.
Definition at line 138 of file SimCalorimeterHit.h.
{
    this->x_ = x;
    this->y_ = y;
    this->z_ = z;
  }
References x_, y_, and z_.
Referenced by simcore::TrigScintSD::ProcessHits().
setPostStepPosition()
void ldmx::SimCalorimeterHit::setPostStepPosition (const float x, const float y, const float z) inline
Set the XYZ post-step position of the hit in the coordinate frame of the sensitive volume [mm].
Parameters
x The X position.
y The Y position.
z The Z position.
Definition at line 162 of file SimCalorimeterHit.h.
{
    postStepX_ = x;
    postStepY_ = y;
    postStepZ_ = z;
  }
References postStepX_.
Referenced by simcore::TrigScintSD::ProcessHits().
setPostStepTime()
void ldmx::SimCalorimeterHit::setPostStepTime (const float time) inline
Set global post-step time of the hit [ns].
Parameters
time The time before the step
Definition at line 186 of file SimCalorimeterHit.h.
{
    postStepTime_ = time;
  }
References postStepTime_.
Referenced by simcore::TrigScintSD::ProcessHits().
setPreStepPosition()
void ldmx::SimCalorimeterHit::setPreStepPosition (const float x, const float y, const float z) inline
Set the XYZ pre-step position of the hit in the coordinate frame of the sensitive volume [mm].
Parameters
x The X position.
y The Y position.
z The Z position.
Definition at line 150 of file SimCalorimeterHit.h.
{
    preStepX_ = x;
    preStepY_ = y;
    preStepZ_ = z;
  }
References preStepX_.
Referenced by simcore::TrigScintSD::ProcessHits().
setPreStepTime()
void ldmx::SimCalorimeterHit::setPreStepTime (const float time) inline
Set global pre-step time of the hit [ns].
Parameters
time The time before the step
Definition at line 179 of file SimCalorimeterHit.h.
{
    preStepTime_ = time;
  }
References preStepTime_.
Referenced by simcore::TrigScintSD::ProcessHits().
setTime()
void ldmx::SimCalorimeterHit::setTime (const float time) inline
Set the time of the hit [ns].
Parameters
time The time of the hit.
Definition at line 226 of file SimCalorimeterHit.h.
{ this->time_ = time; }
References time_.
setVelocity()
void ldmx::SimCalorimeterHit::setVelocity (float velocity) inline
Set the velocity of the track [mm/ns].
Parameters
velocity The track velocity
Definition at line 194 of file SimCalorimeterHit.h.
{
    velocity_ = velocity;
  }
References velocity_.
Referenced by simcore::TrigScintSD::ProcessHits().
updateContrib()
void ldmx::SimCalorimeterHit::updateContrib (int i, float edep, float time)
Update an existing hit contribution by incrementing its edep and setting the time if the new time is less than the old one.
Parameters
i The index of the contribution.
edep The additional energy contribution [MeV].
time The time of the contribution [ns].
Member Data Documentation
ECAL_COLLECTION
const std::string ldmx::SimCalorimeterHit::ECAL_COLLECTION static
name of the ecal sim collection, should match gdml
Definition at line 34 of file SimCalorimeterHit.h.
edep_
float ldmx::SimCalorimeterHit::edep_ {0} private
The energy deposition.
Definition at line 290 of file SimCalorimeterHit.h.
Referenced by getEdep(), and setEdep().
edepContribs_
std::vector<float> ldmx::SimCalorimeterHit::edepContribs_ private
The list of energy depositions contributing to the hit.
Definition at line 331 of file SimCalorimeterHit.h.
HCAL_COLLECTION
const std::string ldmx::SimCalorimeterHit::HCAL_COLLECTION static
name of the hcal sim collection, should match gdml
Definition at line 37 of file SimCalorimeterHit.h.
id_
int ldmx::SimCalorimeterHit::id_ {0} private
Member variables used in all calorimeter types The detector ID.
Definition at line 285 of file SimCalorimeterHit.h.
Referenced by getID(), and setID().
incidentIDContribs_
std::vector<int> ldmx::SimCalorimeterHit::incidentIDContribs_ private
The list of incident IDs contributing to the hit
Definition at line 321 of file SimCalorimeterHit.h.
nContribs_
unsigned ldmx::SimCalorimeterHit::nContribs_ {0} private
The number of hit contributions.
Definition at line 341 of file SimCalorimeterHit.h.
Referenced by getNumberOfContribs().
pathLength_
float ldmx::SimCalorimeterHit::pathLength_ {-1} private
The true path length [mm]. Can in general differ from the distance between the pre and post step position.
Definition at line 352 of file SimCalorimeterHit.h.
Referenced by setPathLength().
pdgCodeContribs_
std::vector<int> ldmx::SimCalorimeterHit::pdgCodeContribs_ private
The list of PDG codes contributing to the hit.
Definition at line 326 of file SimCalorimeterHit.h.
postStepTime_
float ldmx::SimCalorimeterHit::postStepTime_ {0} private
The global time after the interaction [ns]
Definition at line 376 of file SimCalorimeterHit.h.
Referenced by getPostStepTime(), and setPostStepTime().
postStepX_
float ldmx::SimCalorimeterHit::postStepX_ {0} private
The X, Y, and Z positions [mm] after the interaction in the coordinate frame of the sensitive volume.
Definition at line 370 of file SimCalorimeterHit.h.
Referenced by getPostStepPosition(), and setPostStepPosition().
postStepY_
float ldmx::SimCalorimeterHit::postStepY_ {0} private
Definition at line 371 of file SimCalorimeterHit.h.
postStepZ_
float ldmx::SimCalorimeterHit::postStepZ_ {0} private
Definition at line 372 of file SimCalorimeterHit.h.
preStepTime_
float ldmx::SimCalorimeterHit::preStepTime_ {0} private
The global time before the interaction [ns]
Definition at line 365 of file SimCalorimeterHit.h.
Referenced by getPreStepTime(), and setPreStepTime().
preStepX_
float ldmx::SimCalorimeterHit::preStepX_ {0} private
The X, Y, and Z positions [mm] before the interaction in the coordinate frame of the sensitive volume.
Definition at line 359 of file SimCalorimeterHit.h.
Referenced by getPreStepPosition(), and setPreStepPosition().
preStepY_
float ldmx::SimCalorimeterHit::preStepY_ {0} private
Definition at line 360 of file SimCalorimeterHit.h.
preStepZ_
float ldmx::SimCalorimeterHit::preStepZ_ {0} private
Definition at line 361 of file SimCalorimeterHit.h.
time_
float ldmx::SimCalorimeterHit::time_ {0} private
The global time of the hit.
Definition at line 311 of file SimCalorimeterHit.h.
Referenced by getTime(), and setTime().
timeContribs_
std::vector<float> ldmx::SimCalorimeterHit::timeContribs_ private
The list of times contributing to the hit.
Definition at line 336 of file SimCalorimeterHit.h.
trackIDContribs_
std::vector<int> ldmx::SimCalorimeterHit::trackIDContribs_ private
The list of track IDs contributing to the hit.
Definition at line 316 of file SimCalorimeterHit.h.
velocity_
float ldmx::SimCalorimeterHit::velocity_ {-1} private
The track velocity [mm/ns].
Definition at line 381 of file SimCalorimeterHit.h.
Referenced by getVelocity(), and setVelocity().
x_
float ldmx::SimCalorimeterHit::x_ {0} private
The X position.
Definition at line 295 of file SimCalorimeterHit.h.
Referenced by getPosition(), and setPosition().
y_
float ldmx::SimCalorimeterHit::y_ {0} private
The Y position.
Definition at line 300 of file SimCalorimeterHit.h.
Referenced by getPosition(), and setPosition().
z_
float ldmx::SimCalorimeterHit::z_ {0} private
The Z position.
Definition at line 305 of file SimCalorimeterHit.h.
Referenced by getPosition(), and setPosition().
The documentation for this class was generated from the following file:
SimCore/include/SimCore/Event/SimCalorimeterHit.h