LDMX Software: dqm::TrigScintDQM Class Reference
dqm::TrigScintDQM Class Reference
Public Member Functions
TrigScintDQM (const std::string &name, framework::Process &process)
~TrigScintDQM ()
void configure (framework::config::Parameters &pSet)
void analyze (const framework::Event &event)
void onProcessStart ()
Public Member Functions inherited from framework::Analyzer
Analyzer (const std::string &name, Process &process)
Public Member Functions inherited from framework::EventProcessor
EventProcessor (const std::string &name, Process &process)
virtual ~EventProcessor ()
virtual void onNewRun (const ldmx::RunHeader &runHeader)
virtual void onFileOpen (EventFile &eventFile)
virtual void onFileClose (EventFile &eventFile)
virtual void onProcessEnd ()
template<class T >
const T & getCondition (const std::string &condition_name)
TDirectory * getHistoDirectory ()
void setStorageHint (framework::StorageControlHint hint)
void setStorageHint (framework::StorageControlHint hint, const std::string &purposeString)
int getLogFrequency () const
int getRunNumber () const
std::string getName () const
void createHistograms (const std::vector< framework::config::Parameters > &histos)
Private Attributes
std::string hitCollectionName_ {"TriggerPadUpSimHits"}
Name of trigger pad hit collection.
std::string padName_ {"_up"}
Name of Pad.
Additional Inherited Members
Static Public Member Functions inherited from framework::EventProcessor
static void declare (const std::string &classname, int classtype, EventProcessorMaker *)
Static Public Attributes inherited from framework::Analyzer
static const int CLASSTYPE {2}
Protected Member Functions inherited from framework::EventProcessor
void abortEvent ()
Protected Attributes inherited from framework::EventProcessor
HistogramHelper histograms_
Interface class for making and filling histograms.
NtupleManager & ntuple_ {NtupleManager::getInstance()}
Manager for any ntuples.
logging::logger theLog_
The logger for this EventProcessor.
Detailed Description
Definition at line 31 of file TrigScintDQM.h.
Constructor & Destructor Documentation
TrigScintDQM()
dqm::TrigScintDQM::TrigScintDQM (const std::string & name, framework::Process & process)
Constructor
Definition at line 6 of file TrigScintDQM.cxx.
     : framework::Analyzer(name, process) {}
~TrigScintDQM()
dqm::TrigScintDQM::~TrigScintDQM ()
Destructor
Definition at line 9 of file TrigScintDQM.cxx.
 {}
Member Function Documentation
analyze()
void dqm::TrigScintDQM::analyze (const framework::Event & event) virtual
Process the event and make histograms ro summaries.
Parameters
event The event to analyze.
Implements framework::Analyzer.
Definition at line 47 of file TrigScintDQM.cxx.
{
   const std::vector<ldmx::SimCalorimeterHit> TrigScintHits =
       event.getCollection<ldmx::SimCalorimeterHit>(hitCollectionName_);
   // Get the total hit count
   int hitCount = TrigScintHits.size();
   histograms_.fill("n_hits", hitCount);
   double totalEnergy{0};
   for (const ldmx::SimCalorimeterHit &hit : TrigScintHits) {
     ldmx::TrigScintID detID(hit.getID());
     int bar = detID.bar();
     histograms_.fill("energy", hit.getEdep());
     histograms_.fill("hit_time", hit.getTime());
     histograms_.fill("id", bar);
     std::vector<float> posvec = hit.getPosition();
     histograms_.fill("x", posvec.at(0));
     histograms_.fill("y", posvec.at(1));
     histograms_.fill("z", posvec.at(2));
     totalEnergy += hit.getEdep();
   }
   histograms_.fill("total_energy", totalEnergy);
 }
References ldmx::TrigScintID::bar(), framework::HistogramHelper::fill(), framework::EventProcessor::histograms_, and hitCollectionName_.
configure()
void dqm::TrigScintDQM::configure (framework::config::Parameters & pSet) virtual
Configure the processor using the given user specified parameters.
Parameters
pSet Set of parameters used to configure this processor.
Reimplemented from framework::EventProcessor.
Definition at line 39 of file TrigScintDQM.cxx.
{
   hitCollectionName_ = ps.getParameter<std::string>("hit_collection");
   padName_ = ps.getParameter<std::string>("pad");
   std::cout << "In TrigScintDQM::configure, got parameters "
             << hitCollectionName_ << " and " << padName_ << std::endl;
 }
References framework::config::Parameters::getParameter(), hitCollectionName_, and padName_.
onProcessStart()
void dqm::TrigScintDQM::onProcessStart () virtual
Method executed before processing of events begins.
Reimplemented from framework::EventProcessor.
Definition at line 11 of file TrigScintDQM.cxx.
{
   std::cout << "Process starts!" << std::endl;
   getHistoDirectory();
   histograms_.create("id", "Channel ID of sim hit", 100, 0, 100);
   histograms_.create("total_energy", "Total energy deposition in the pad/event",
                      3000, 0, 3000);
   histograms_.create("n_hits", "TrigScint hit multiplicity in the pad/event",
                      100, 0, 100);
   histograms_.create("x", "Hit x position", 1000, -100, 100);
   histograms_.create("y", "Hit y position", 1000, -100, 100);
   histograms_.create("z", "Hit z position", 1000, -900, 100);
   histograms_.create("energy", "Energy deposition in a TrigScint bar", 1500, 0,
                      1500);
   histograms_.create("hit_time", "TrigScint hit time (ns)", 1600, -100, 1500);
   histograms_.create("max_pe:time", "Max Photoelectrons in a TrigScint bar",
                      1500, 0, 1500, "TrigScint max PE hit time (ns)", 1500, 0,
                      1500);
   histograms_.create("min_time_hit_above_thresh:pe",
                      "Photoelectrons in a TrigScint bar", 1500, 0, 1500,
                      "Earliest time of TrigScint hit above threshold (ns)",
                      1600, -100, 1500);
 }
References framework::HistogramHelper::create(), framework::EventProcessor::getHistoDirectory(), and framework::EventProcessor::histograms_.
The documentation for this class was generated from the following files:
DQM/include/DQM/TrigScintDQM.h
DQM/src/DQM/TrigScintDQM.cxx