LDMX Software: ldmx::EventObjects Class Reference
ldmx::EventObjects Class Reference
Drawing methods for event objects.
#include <EventObjects.h>
Public Member Functions
EventObjects ()
~EventObjects ()
void Initialize ()
void drawECALHits (std::vector< EcalHit > hits)
void drawHCALHits (std::vector< HcalHit > hits)
void drawRecoilHits (std::vector< SimTrackerHit > hits)
void drawECALClusters (std::vector< EcalCluster > clusters)
void drawECALSimParticles (std::vector< SimTrackerHit > ecalSimParticles)
void SetSimThresh (double simThresh)
void ColorClusters ()
TEveElement * getHitCollections ()
TEveElement * getRecoObjects ()
Private Attributes
TEveElement * ecalHits_
TEveElement * hcalHits_
TEveElement * recoilTrackerHits_
TEveElement * ecalClusters_
TEveElement * ecalSimParticles_
TEveElement * hits_
TEveElement * recoObjs_
double simThresh_ = 0
std::vector< Color_t > colors_ = {kRed, kBlue, kGreen, kYellow, kMagenta, kBlack, kOrange, kPink}
TRandom r_
Detailed Description
Drawing methods for event objects.
Both ECAL and HCAL hits are colored by their relative energy/pe deposits.
Definition at line 35 of file EventObjects.h.
Constructor & Destructor Documentation
EventObjects()
ldmx::EventObjects::EventObjects ()
Constructor Defines new necessary objects.
See also
Initialize
Definition at line 5 of file EventObjects.cxx.
{
         Initialize();
     }
References Initialize().
~EventObjects()
ldmx::EventObjects::~EventObjects () inline
Destructor Deletes objects that have been constructed.
Definition at line 50 of file EventObjects.h.
{
                 delete ecalHits_;
                 delete hcalHits_;
                 delete recoilTrackerHits_;
                 delete ecalClusters_;
                 delete ecalSimParticles_;
                 delete hits_;
                 delete recoObjs_;
             }
Member Function Documentation
ColorClusters()
void ldmx::EventObjects::ColorClusters ()
Colors ecal clusters according to colors_
Definition at line 61 of file EventObjects.cxx.
{
         TEveElement* clusters = recoObjs_->FindChild("ECAL Clusters");
         if (clusters == 0) {
             std::cout << "[ EventObjects ] : No clusters to color!" << std::endl;
             return;
         }
         int theColor = 0;
         TEveElement::List_i cluster;
         for (cluster = clusters->BeginChildren(); cluster != clusters->EndChildren(); cluster++) {
             TEveElement* el = *cluster;
             TEveElement::List_i hit;
             Int_t color = 0;
             if (!el->IsPickable()) {
                 color = 19;
             } else if (theColor < 9) {
                 color = colors_[theColor];
                 theColor++;
             } else {
                 Int_t ci = 200*r_.Rndm();
                 color = ci;
                 std::cout << "[ EventObjects ] : Using random colors to fill in extra clusters." << std::endl;
             }
             for (hit = el->BeginChildren(); hit != el->EndChildren(); hit++) {
                 TEveElement* elChild = *hit;
                 elChild->SetMainColor(color);
             }
         }
     }
References colors_.
Referenced by ldmx::EventDisplay::ColorClusters().
drawECALClusters()
void ldmx::EventObjects::drawECALClusters (std::vector< EcalCluster > clusters)
Draws the hits in the input collection assuming that they are EcalClusters
Definition at line 186 of file EventObjects.cxx.
{
         TEveRGBAPalette* palette = new TEveRGBAPalette(0,4000.0);
         int iC = 0;
         for (const EcalCluster &cluster : clusters ) {
             TString clusterName;
             clusterName.Form("ECAL Cluster %d", iC);
             TEveElement* ecalCluster = new TEveElementList(clusterName);
             double energy = cluster.getEnergy();
             std::vector<unsigned int> clusterHitIDs = cluster.getHitIDs();
             int numHits = clusterHitIDs.size();
             for (int iHit = 0; iHit < numHits; iHit++) {
                 EcalID id(clusterHitIDs.at(iHit));
                 const UChar_t* rgb = palette->ColorFromValue(energy);
                 TColor* aColor = new TColor();
                 Int_t color = aColor->GetColor((Int_t)rgb[0], (Int_t)rgb[1], (Int_t)rgb[2]);
                 TEveGeoShape* ecalDigiHit = EveShapeDrawer::getInstance().drawHexPrism(
                         DetectorGeometry::getInstance().getHexPrism( id ),
                         0, 0, 0,
                         color, 0, "RecHit");
                 ecalCluster->AddElement(ecalDigiHit);
                 if (numHits < 2) {
                     ecalCluster->SetPickableRecursively(0);
                 } else {
                     ecalCluster->SetPickableRecursively(1);
                 }
             }
             ecalClusters_->AddElement(ecalCluster);
             iC++;
         }
         ecalClusters_->SetPickable(1);
         recoObjs_->AddElement(ecalClusters_);
     }
References ldmx::EveShapeDrawer::drawHexPrism(), ldmx::DetectorGeometry::getInstance(), and ldmx::EveShapeDrawer::getInstance().
Referenced by ldmx::EventDisplay::GotoEvent().
drawECALHits()
void ldmx::EventObjects::drawECALHits (std::vector< EcalHit > hits)
Draws the hits in the input collection assuming that they are EcalHits
Definition at line 94 of file EventObjects.cxx.
{
         TEveRGBAPalette* palette = new TEveRGBAPalette(0,500.0);
         std::sort(hits.begin(), hits.end(), compEcalHits);
         for ( const EcalHit &hit : hits ) {
             double energy = hit.getEnergy();
             if (energy == 0) { continue; }
             TString digiName;
             digiName.Form("%1.5g MeV", energy);
             const UChar_t* rgb = palette->ColorFromValue(energy);
             TColor* aColor = new TColor();
             Int_t color = aColor->GetColor((Int_t)rgb[0], (Int_t)rgb[1], (Int_t)rgb[2]);
             TEveGeoShape* ecalDigiHit = EveShapeDrawer::getInstance().drawHexPrism(
                     DetectorGeometry::getInstance().getHexPrism( EcalID(hit.getID()) ),
                     0, 0, 0,
                     color, 0, digiName);
             ecalHits_->AddElement(ecalDigiHit);
         }
         ecalHits_->SetPickableRecursively(1);
         hits_->AddElement(ecalHits_);
     }
References ldmx::EveShapeDrawer::drawHexPrism(), ldmx::DetectorGeometry::getInstance(), and ldmx::EveShapeDrawer::getInstance().
Referenced by ldmx::EventDisplay::GotoEvent().
drawECALSimParticles()
void ldmx::EventObjects::drawECALSimParticles (std::vector< SimTrackerHit > ecalSimParticles)
Draws the hits in the input collection assuming that they are SimTrackerHits that hit the Ecal Scoring Planes
Definition at line 231 of file EventObjects.cxx.
{
         std::sort(ecalSimParticles.begin(), ecalSimParticles.end(), compScorePlaneHits );
         auto lastUniqueEntry = std::unique( ecalSimParticles.begin() , ecalSimParticles.end() , areScorePlaneHitsEqual );
         ecalSimParticles.erase( lastUniqueEntry , ecalSimParticles.end() );
         for ( const SimTrackerHit &spHit : ecalSimParticles ) {
             std::vector<double> pVec = spHit.getMomentum();
             double p = pow(pow(pVec[0],2)+pow(pVec[1],2)+pow(pVec[2],2),0.5);
             double E = spHit.getEnergy();
             std::vector<float> simStart = spHit.getPosition();
             std::vector<double> simDir   = pVec;
             double rCheck = pow(pow(simDir[0],2)+pow(simDir[1],2)+pow(simDir[2],2),0.5);
             double scale = 1;
             double largest = 0;
             if (abs(simDir[0]) > 3500.0) {
                  scale = 500.0/abs(simDir[0]);
                  largest = simDir[0];
             }
             if (abs(simDir[1]) > 3500.0 && abs(simDir[1]) > largest) {
                  scale = 500.0/abs(simDir[1]);
                  largest = simDir[1];
             }
             if (abs(simDir[2]) > 3500.0 && abs(simDir[2]) > 3500) {
                  scale = 500.0/abs(simDir[2]);
             }
             double r = pow(pow(scale*(simDir[0]),2) + pow(scale*(simDir[1]),2) + pow(scale*(simDir[2]),2),0.5);
             signed int pdgID = spHit.getPdgID();
             TEveArrow* simArr = new TEveArrow(scale*simDir[0],scale*simDir[1],scale*simDir[2],simStart[0],simStart[1],simStart[2]);
             simArr->SetMainColor(kBlack);
             simArr->SetTubeR(60*0.02/r);
             simArr->SetConeL(100*0.02/r);
             simArr->SetConeR(150*0.02/r);
             simArr->SetPickable(kTRUE);
             if (p < simThresh_) { simArr->SetRnrSelf(kFALSE); }
             TString name;
             name.Form("PDG = %d, p = %1.5g MeV/c", pdgID, p);
             simArr->SetElementName(name);
             ecalSimParticles_->AddElement(simArr);
         }
         hits_->AddElement(ecalSimParticles_);
     }
Referenced by ldmx::EventDisplay::GotoEvent().
drawHCALHits()
void ldmx::EventObjects::drawHCALHits (std::vector< HcalHit > hits)
Draws the hits in the input collection assuming that they are HcalHits
Definition at line 126 of file EventObjects.cxx.
{
         TEveRGBAPalette* palette = new TEveRGBAPalette(0,100.0);
         std::sort(hits.begin(), hits.end(), compHcalHits);
         for ( const HcalHit &hit : hits ) {
             int pe = hit.getPE();
             if (pe == 0) { continue; }
             HcalID id(hit.getID());
             const UChar_t* rgb = palette->ColorFromValue(pe);
             TColor* aColor = new TColor();
             Int_t color = aColor->GetColor((Int_t)rgb[0], (Int_t)rgb[1], (Int_t)rgb[2]);
             TString digiName;
             digiName.Form("%d PEs, Section %d, Layer %d, Bar %d, Z %1.5g", pe,
                     id.section(), id.layer(), id.strip(), hit.getZPos());
             BoundingBox hcal_hit_bb = DetectorGeometry::getInstance().getBoundingBox( hit );
             TEveGeoShape *hcalDigiHit = EveShapeDrawer::getInstance().drawRectPrism(
                     hcal_hit_bb ,
                     0, 0, 0, color, 0, digiName );
             if ( hcalDigiHit ) {
                 if ( hit.isNoise() ) { hcalDigiHit->SetRnrSelf(0); }
                 hcalHits_->AddElement(hcalDigiHit);
             } // successfully created hcal digi hit
         } //loop through sorted hit list
         hcalHits_->SetPickableRecursively(1);
         hits_->AddElement(hcalHits_);
     }
References ldmx::EveShapeDrawer::drawRectPrism(), ldmx::DetectorGeometry::getBoundingBox(), ldmx::DetectorGeometry::getInstance(), and ldmx::EveShapeDrawer::getInstance().
Referenced by ldmx::EventDisplay::GotoEvent().
drawRecoilHits()
void ldmx::EventObjects::drawRecoilHits (std::vector< SimTrackerHit > hits)
Draws the hits in the input collection assuming that they are SimTrackerHits that hit the recoil tracker.
Definition at line 163 of file EventObjects.cxx.
{
         int iter = 0;
         for ( const SimTrackerHit &hit : hits ) {
             std::vector<float> xyzPos = hit.getPosition();
             double energy = hit.getEdep();
             TString recoilName;
             recoilName.Form("Recoil Hit %d", iter);
             TEveGeoShape *recoilHit = EveShapeDrawer::getInstance().drawRectPrism(
                     DetectorGeometry::getInstance().getBoundingBox( hit ) ,
                     0, 0, DetectorGeometry::getInstance().getRotAngle( hit.getLayerID() , hit.getModuleID() )*180/M_PI,
                     kRed+1, 0, recoilName );
             recoilTrackerHits_->AddElement(recoilHit);
             iter++;
         }
         hits_->AddElement(recoilTrackerHits_);
     }
References ldmx::EveShapeDrawer::drawRectPrism(), ldmx::DetectorGeometry::getInstance(), and ldmx::EveShapeDrawer::getInstance().
Referenced by ldmx::EventDisplay::GotoEvent().
getHitCollections()
TEveElement* ldmx::EventObjects::getHitCollections () inline
Get the hits Eve Element Used to attach these Eve Elements to the Eve Manager.
Definition at line 110 of file EventObjects.h.
 { return hits_; }
Referenced by ldmx::EventDisplay::GotoEvent().
getRecoObjects()
TEveElement* ldmx::EventObjects::getRecoObjects () inline
Get the recoObjs Eve Element Used to attach these Eve Elements to the Eve Manager.
Definition at line 116 of file EventObjects.h.
 { return recoObjs_; }
Referenced by ldmx::EventDisplay::GotoEvent().
Initialize()
void ldmx::EventObjects::Initialize ()
Defines new Eve Element Lists for the event objects.
Definition at line 9 of file EventObjects.cxx.
{
         //collections of event objects
         ecalHits_           = new TEveElementList("ECAL RecHits");
         hcalHits_           = new TEveElementList("HCAL RecHits");
         recoilTrackerHits_  = new TEveElementList("Recoil Sim Hits");
         ecalClusters_       = new TEveElementList("ECAL Clusters");
         ecalSimParticles_   = new TEveElementList("ECAL SP Sim Particles");
         //packages of event objects to be passed to event display manager
         hits_               = new TEveElementList("Reco Hits");
         recoObjs_           = new TEveElementList("Reco Objects");
     }
Referenced by EventObjects(), and ldmx::EventDisplay::GotoEvent().
SetSimThresh()
void ldmx::EventObjects::SetSimThresh (double simThresh)
Sets the energy threshold for a sim particle to be drawn.
Parameters
simThresh minimum energy to be included
Definition at line 40 of file EventObjects.cxx.
{
         simThresh_ = simThresh;
         TEveElement* spHits = 0;
         spHits = hits_->FindChild("ECAL SP Sim Particles");
         TEveElement::List_i sim;
         for (sim = spHits->BeginChildren(); sim != spHits->EndChildren(); sim++) {
             TEveElement* el = *sim;
             SimTrackerHit* sp = (ldmx::SimTrackerHit*)el->GetSourceObject();
             std::vector<double> pVec = sp->getMomentum();
             double p = pow(pow(pVec[0],2) + pow(pVec[1],2) + pow(pVec[2],2),0.5);
             if (p < simThresh_) {
                 el->SetRnrSelf(kFALSE);
             } else {
                 el->SetRnrSelf(kTRUE);
             }
         }
     }
References ldmx::SimTrackerHit::getMomentum().
Referenced by ldmx::EventDisplay::SetSimThresh().
Member Data Documentation
colors_
std::vector<Color_t> ldmx::EventObjects::colors_ = {kRed, kBlue, kGreen, kYellow, kMagenta, kBlack, kOrange, kPink} private
list of colors to use with ecal clusters
Definition at line 132 of file EventObjects.h.
Referenced by ColorClusters().
The documentation for this class was generated from the following files:
EventDisplay/include/EventDisplay/EventObjects.h
EventDisplay/src/EventDisplay/EventObjects.cxx