LDMX Software: ldmx::TrackMap Class Reference
ldmx::TrackMap Class Reference
Defines a map of track ID to parent ID and Trajectory.
#include <TrackMap.h>
Public Types
typedef std::map< G4int, G4int > TrackIDMap
Public Member Functions
void addSecondary (G4int trackID, G4int parentID)
int findIncident (G4int trackID)
bool hasTrajectory (G4int trackID) const
void addTrajectory (Trajectory *traj)
bool contains (G4int trackID) const
int getParent (int trackID) const
Trajectory * getTrajectory (G4int trackID) const
void clear ()
Private Attributes
TrackIDMap trackIDMap_
Trajectory::TrajectoryMap trajectoryMap_
Detailed Description
Defines a map of track ID to parent ID and Trajectory.
Note
This class provides a record of track ancestry which is used to connect track IDs to their parents. It also maps track IDs to Trajectory objects.
Definition at line 27 of file TrackMap.h.
Member Typedef Documentation
TrackIDMap
typedef std::map<G4int, G4int> ldmx::TrackMap::TrackIDMap
Map of track ID to parent ID.
Definition at line 34 of file TrackMap.h.
Member Function Documentation
addSecondary()
void ldmx::TrackMap::addSecondary (G4int trackID, G4int parentID) inline
Add a record in the map connecting a track ID to its parent ID.
Parameters
trackID The track ID.
parentID The parent track ID.
Definition at line 41 of file TrackMap.h.
{
                 trackIDMap_[trackID] = parentID;
             }
References trackIDMap_.
Referenced by ldmx::UserTrackingAction::processTrack().
addTrajectory()
void ldmx::TrackMap::addTrajectory (Trajectory * traj) inline
Add a Trajectory which will be associated with its track ID in the map.
Parameters
traj The Trajectory to add.
Definition at line 70 of file TrackMap.h.
{
                 trajectoryMap_[traj->GetTrackID()] = traj;
             }
References ldmx::Trajectory::GetTrackID(), and trajectoryMap_.
Referenced by ldmx::UserTrackingAction::storeTrajectory().
clear()
void ldmx::TrackMap::clear ()
Clear the internal maps.
Definition at line 36 of file TrackMap.cxx.
{
         trajectoryMap_.clear();
         trackIDMap_.clear();
     }
References trackIDMap_, and trajectoryMap_.
Referenced by ldmx::UserEventAction::BeginOfEventAction().
contains()
bool ldmx::TrackMap::contains (G4int trackID) const inline
Return true if the track ID is in the ancestry map
Returns
True if the track ID is in the ancestry map
Definition at line 78 of file TrackMap.h.
{
                 return trackIDMap_.find(trackID) != trackIDMap_.end();
             }
References trackIDMap_.
Referenced by findIncident(), and ldmx::UserTrackingAction::PreUserTrackingAction().
findIncident()
int ldmx::TrackMap::findIncident (G4int trackID)
Find a trajectory's nearest parent that is incident on the calorimeter region
If this track ID does not have such a trajectory, then the track ID of the primary in its parentage is returned.
Parameters
trackID The track ID of the trajectory to search its parentage for the incident
Definition at line 12 of file TrackMap.cxx.
{
         int currTrackID = trackID;
         bool foundIncident = false;
         while ( not foundIncident ) {
             if ( this->contains(currTrackID) ) {
                 //currTrackID is not a primary and has parent stored
                 currTrackID = this->getParent(currTrackID);
                 if ( this->hasTrajectory(currTrackID) ) {
                     //curr track ID is being stored
                     auto region{this->getTrajectory(currTrackID)->getVertexRegion()};
                     if ( region.find("Calorimeter") == std::string::npos ) {
                         //curr track originated outside cal region
                         foundIncident = true;
                     }
                 }
             } else {
                 //curr Track ID is a primary and has already been
                 //checked above, give up
                 foundIncident = true;
             }
         }
         return currTrackID;
     }
References contains(), getParent(), getTrajectory(), and hasTrajectory().
getParent()
int ldmx::TrackMap::getParent (int trackID) const inline
Get parent track id
Parameters
[in] track Id to get parent for
Returns
track ID of parent track
Definition at line 87 of file TrackMap.h.
{
                 return trackIDMap_.at(trackID);
             }
References trackIDMap_.
Referenced by findIncident().
getTrajectory()
Trajectory* ldmx::TrackMap::getTrajectory (G4int trackID) const inline
Get a Trajectory from a track ID.
Returns
A Trajectory from a track ID.
Note
Does not search for a parent Trajectory if this track ID is not assigned to a Trajectory.
Definition at line 97 of file TrackMap.h.
{
                 if (hasTrajectory(trackID)) {
                     return trajectoryMap_.at(trackID);
                 } else {
                     return nullptr;
                 }
             }
References hasTrajectory(), and trajectoryMap_.
Referenced by findIncident().
hasTrajectory()
bool ldmx::TrackMap::hasTrajectory (G4int trackID) const inline
Return true if the given track ID has an explicitly assigned trajectory.
Parameters
trackID The track ID.
Returns
True if the track ID has an assigned Trajectory.
Note
This method does not search through the track parentage for the first available Trajectory.
Definition at line 62 of file TrackMap.h.
{
                 return trajectoryMap_.find(trackID) != trajectoryMap_.end();
             }
References trajectoryMap_.
Referenced by findIncident(), getTrajectory(), ldmx::UserTrackingAction::PostUserTrackingAction(), and ldmx::UserTrackingAction::PreUserTrackingAction().
Member Data Documentation
trackIDMap_
TrackIDMap ldmx::TrackMap::trackIDMap_ private
Map of track IDs to parent IDs.
Definition at line 113 of file TrackMap.h.
Referenced by addSecondary(), clear(), contains(), and getParent().
trajectoryMap_
Trajectory::TrajectoryMap ldmx::TrackMap::trajectoryMap_ private
Map of track IDs to Trajectory objects.
Definition at line 116 of file TrackMap.h.
Referenced by addTrajectory(), clear(), getTrajectory(), and hasTrajectory().
The documentation for this class was generated from the following files:
SimCore/include/SimCore/TrackMap.h
SimCore/src/TrackMap.cxx