LDMX Software: conditions::HomogenousTableCondition< T > Class Template Reference
conditions::HomogenousTableCondition< T > Class Template Reference
Public Member Functions
HomogenousTableCondition (const std::string &name, const std::vector< std::string > &columns)
void clear ()
void add (unsigned int id, const std::vector< T > &values)
T get (unsigned int id, unsigned int col) const
std::pair< unsigned int, std::vector< T > > getRow (unsigned int irow) const
T getByName (unsigned int id, const std::string &colname) const
Public Member Functions inherited from conditions::BaseTableCondition
BaseTableCondition (const std::string &name, const std::vector< std::string > &columns)
unsigned int getColumnNumber (const std::string &colname) const
unsigned int getColumnCount () const
const std::string & getColumnName (unsigned int icol) const
unsigned int getRowId (unsigned int irow) const
const std::vector< std::string > & getColumnNames () const
std::size_t getRowCount () const
void setIdMask (unsigned int mask)
unsigned int getIdMask () const
Public Member Functions inherited from framework::ConditionsObject
ConditionsObject (const std::string &name)
virtual ~ConditionsObject ()
std::string getName () const
Private Attributes
std::vector< T > values_
Additional Inherited Members
Protected Member Functions inherited from conditions::BaseTableCondition
std::size_t findKey (unsigned int id) const
std::size_t findKeyInsert (unsigned int id) const
Protected Attributes inherited from conditions::BaseTableCondition
std::vector< std::string > columns_
unsigned int columnCount_
std::vector< uint32_t > keys_
unsigned int idMask_
Detailed Description
template<class T>
class conditions::HomogenousTableCondition< T >
Definition at line 101 of file SimpleTableCondition.h.
Constructor & Destructor Documentation
HomogenousTableCondition()
template<class T > conditions::HomogenousTableCondition< T >::HomogenousTableCondition (const std::string & name, const std::vector< std::string > & columns) inline
Definition at line 103 of file SimpleTableCondition.h.
      : BaseTableCondition(name, columns) {}
~HomogenousTableCondition()
template<class T > virtual conditions::HomogenousTableCondition< T >::~HomogenousTableCondition () inline virtual
Definition at line 107 of file SimpleTableCondition.h.
{}
Member Function Documentation
add()
template<class T > void conditions::HomogenousTableCondition< T >::add (unsigned int id, const std::vector< T > & values) inline
Add an entry to the table
Definition at line 118 of file SimpleTableCondition.h.
{
    if (values.size() != columnCount_) {
      EXCEPTION_RAISE("ConditionsException",
                      getName() + ": Attempted to insert a row with " +
                          std::to_string(values.size()) +
                          " columns into a table with " +
                          std::to_string(columnCount_) + " columns");
    }
    std::size_t loc = findKey(id);
    if (loc != getRowCount()) {
      EXCEPTION_RAISE("ConditionsException",
                      "Attempted to add condition in " + getName() +
                          " for existing id " + std::to_string(id));
    }
    loc = findKeyInsert(id);  // where to put it
    // insert into the keys
    keys_.insert(keys_.begin() + loc, id);
    // insert into the values
    values_.insert(values_.begin() + loc * columnCount_, values.begin(),
                   values.end());
  }
References framework::ConditionsObject::getName(), and conditions::BaseTableCondition::getRowCount().
Referenced by conditions::SimpleCSVTableProvider::getCondition().
clear()
template<class T > void conditions::HomogenousTableCondition< T >::clear () inline
Clear the contents
Definition at line 112 of file SimpleTableCondition.h.
               {
    keys_.clear();
    values_.clear();
  }
get()
template<class T > T conditions::HomogenousTableCondition< T >::get (unsigned int id, unsigned int col) const inline
Get an entry by DetectorId and number. Throws an exception when id is unavailble
Definition at line 145 of file SimpleTableCondition.h.
{
    std::size_t irow = findKey(id);
    if (col >= columnCount_ || irow == getRowCount()) {  // raise exception
      EXCEPTION_RAISE("ConditionsException",
                      "No such column " + std::to_string(col) + " or id " +
                          std::to_string(id));
    }
    return values_[irow * columnCount_ + col];
  }
References conditions::BaseTableCondition::getRowCount().
Referenced by ecal::EcalReconConditions::adcGain(), hcal::HcalReconConditions::adcGain(), ecal::EcalReconConditions::adcPedestal(), hcal::HcalReconConditions::adcPedestal(), ldmx::HgcrocTriggerConditions::adcPedestal(), ldmx::HgcrocTriggerConditions::adcThreshold(), conditions::HomogenousTableCondition< T >::getByName(), ldmx::HgcrocEmulator::getCondition(), ecal::EcalReconConditions::totGain(), hcal::HcalReconConditions::totGain(), ldmx::HgcrocTriggerConditions::totGain(), ecal::EcalReconConditions::totPedestal(), hcal::HcalReconConditions::totPedestal(), ldmx::HgcrocTriggerConditions::totPedestal(), and ldmx::HgcrocTriggerConditions::totThreshold().
getByName()
template<class T > T conditions::HomogenousTableCondition< T >::getByName (unsigned int id, const std::string & colname) const inline
Get a column by DetectorId and name Throws an exception when
Note
This is an inefficient process. Suggest caching the return of "getColumnNumber()" and using getColumn directly
Definition at line 175 of file SimpleTableCondition.h.
{
    return get(id, getColumnNumber(colname));
  }
References conditions::HomogenousTableCondition< T >::get(), and conditions::BaseTableCondition::getColumnNumber().
getRow()
template<class T > std::pair< unsigned int, std::vector< T > > conditions::HomogenousTableCondition< T >::getRow (unsigned int irow) const inline
Get a row by number Used primarily for persisting the SimpleTableCondition
Definition at line 159 of file SimpleTableCondition.h.
{
    if (irow >= getRowCount()) {  // raise exception
      EXCEPTION_RAISE("ConditionsException",
                      "Row out of range: " + std::to_string(irow));
    }
    std::vector<T> rv(&(values_[irow * columnCount_]),
                      &(values_[(irow + 1) * columnCount_]));
    return std::pair<unsigned int, std::vector<T> >(keys_[irow], rv);
  }
References conditions::BaseTableCondition::getRowCount().
Member Data Documentation
values_
template<class T > std::vector<T> conditions::HomogenousTableCondition< T >::values_ private
Definition at line 180 of file SimpleTableCondition.h.
The documentation for this class was generated from the following file:
Conditions/include/Conditions/SimpleTableCondition.h