LDMX Software: ldmx::Process Class Reference
ldmx::Process Class Reference
Class which represents the process under execution.
#include <Process.h>
Public Member Functions
Process (const Parameters &configuration)
~Process ()
const std::string & getPassName () const
int getRunNumber () const
const EventHeader * getEventHeader () const
Conditions & getConditions ()
int getLogFrequency () const
void run ()
void requestFinish ()
TDirectory * makeHistoDirectory (const std::string &dirName)
TDirectory * openHistoFile ()
StorageControl & getStorageController ()
Static Public Member Functions
static Process getDummy ()
Private Member Functions
Process ()
Private Attributes
std::string passname_
int eventLimit_
int logFrequency_
int termLevelInt_
int fileLevelInt_
std::string logFileName_
int maxTries_
StorageControl m_storageController
std::vector< EventProcessor * > sequence_
Conditions conditions_
std::vector< std::string > inputFiles_
std::vector< std::string > outputFiles_
int compressionSetting_
std::vector< std::string > dropKeepRules_
int runForGeneration_ {1}
std::string histoFilename_
const EventHeader * eventHeader_
TFile * histoTFile_ {0}
Detailed Description
Class which represents the process under execution.
Definition at line 34 of file Process.h.
Constructor & Destructor Documentation
Process() [1/2]
ldmx::Process::Process (const Parameters & configuration)
Class constructor.
Parameters
configuration Parameters to configure process with
Definition at line 22 of file Process.cxx.
                                                   : conditions_{*this} {
         passname_      = configuration.getParameter<std::string>("passName");
         histoFilename_ = configuration.getParameter<std::string>("histogramFile","");
         logFileName_   = configuration.getParameter<std::string>("logFileName","");
         maxTries_           = configuration.getParameter<int>("maxTriesPerEvent",1);
         eventLimit_         = configuration.getParameter<int>("maxEvents",-1);
         logFrequency_       = configuration.getParameter<int>("logFrequency",-1);
         compressionSetting_ = configuration.getParameter<int>("compressionSetting",9);
         termLevelInt_       = configuration.getParameter<int>("termLogLevel",2);
         fileLevelInt_       = configuration.getParameter<int>("fileLogLevel",0);
         inputFiles_    = configuration.getParameter<std::vector<std::string>>("inputFiles" ,{});
         outputFiles_   = configuration.getParameter<std::vector<std::string>>("outputFiles",{});
         dropKeepRules_ = configuration.getParameter<std::vector<std::string>>("keep"       ,{});
         eventHeader_   = 0;
         auto run{configuration.getParameter<int>("run",-1)};
         if ( run > 0 ) runForGeneration_ = run;
         auto libs{configuration.getParameter<std::vector<std::string>>("libraries",{})};
         std::for_each(libs.begin(), libs.end(),
                 [](auto& lib) { PluginFactory::getInstance().loadLibrary(lib);}
                 );
         m_storageController.setDefaultKeep(
                        configuration.getParameter<bool>("skimDefaultIsKeep",true)
                 );
         auto skimRules{configuration.getParameter<std::vector<std::string>>("skimRules",{})};
         for (size_t i=0; i<skimRules.size(); i+=2) {
             m_storageController.addRule(skimRules[i],skimRules[i+1]);
         }
         auto sequence{configuration.getParameter<std::vector<Parameters>>("sequence",{})};
         if ( sequence.empty() && configuration.getParameter<bool>("testingMode",false)) {
             EXCEPTION_RAISE(
                     "NoSeq",
                     "No sequence has been defined. What should I be doing?\nUse p.sequence to tell me what processors to run."
                     );
         }
         for (auto proc : sequence) {
             auto className{proc.getParameter<std::string>("className")};
             auto instanceName{proc.getParameter<std::string>("instanceName")};
             EventProcessor* ep = PluginFactory::getInstance().createEventProcessor(
                     className, instanceName, *this);
             if (ep == 0) {
                 EXCEPTION_RAISE("UnableToCreate",
                         "Unable to create instance '" + instanceName + "' of class '" + className
                         + "'. Did you load the library that this class is apart of?");
             }
             auto histograms{proc.getParameter<std::vector<Parameters>>("histograms",{})};
             if (!histograms.empty()) {
                 ep->getHistoDirectory();
                 ep->createHistograms( histograms );
             }
             ep->configure(proc);
             sequence_.push_back(ep);
         }
         auto conditionsObjectProviders{configuration.getParameter<std::vector<Parameters> >("conditionsObjectProviders",{})};
         for (auto cop : conditionsObjectProviders) {
             auto className{cop.getParameter<std::string>("className")};
             auto instanceName{cop.getParameter<std::string>("instanceName")};
             auto tagName{cop.getParameter<std::string>("tagName")};
             conditions_.createConditionsObjectProvider(className, instanceName, tagName, cop);
         }
     }
~Process()
ldmx::Process::~Process ()
Class Destructor
Cleans up sequence of EventProcessors. These processors were created by ConfigurePython and should be deleted.
Definition at line 94 of file Process.cxx.
                       {
         for ( EventProcessor *ep : sequence_ ) {
             delete ep;
         }
     }
References sequence_.
Process() [2/2]
ldmx::Process::Process () inline private
Private dummy constructor We hide it here because it shouldn't be used anywhere else.
nothing on purpose
Definition at line 127 of file Process.h.
 : conditions_{*this} {  }
Referenced by getDummy().
Member Function Documentation
getConditions()
Conditions& ldmx::Process::getConditions () inline
Get a reference to the conditions system
Definition at line 74 of file Process.h.
 { return conditions_; }
References conditions_.
Referenced by ldmx::EventProcessor::getConditions().
getDummy()
static Process ldmx::Process::getDummy () inline static
Get a dummy process
This function returns an instance of this class without any configuration. This is only helpful in the use case where the user is writing a test for a processor and needs to pass a Process object to the processor's constructor.
Returns
Process without any configuration
Definition at line 117 of file Process.h.
{
                 return std::move(Process());
             }
References Process().
getEventHeader()
const EventHeader* ldmx::Process::getEventHeader () const inline
Get the pointer to the current event header, if defined
Definition at line 69 of file Process.h.
 { return eventHeader_; }
References eventHeader_.
Referenced by ldmx::EventProcessor::getEventHeader().
getLogFrequency()
int ldmx::Process::getLogFrequency () const inline
Get the frequency with which the event information is printed.
Returns
integer log frequency (negative if turned off)
Definition at line 80 of file Process.h.
 { return logFrequency_; }
References logFrequency_.
Referenced by ldmx::EventProcessor::getLogFrequency(), and run().
getPassName()
const std::string& ldmx::Process::getPassName () const inline
Get the processing pass label.
Returns
The processing pass label.
Definition at line 56 of file Process.h.
{
                 return passname_;
             }
References passname_.
getRunNumber()
int ldmx::Process::getRunNumber () const
Get the current run number or the run number to be used when initiating new events from the job
Returns
int Run number
Definition at line 376 of file Process.cxx.
{
         return (eventHeader_)?(eventHeader_->getRun()):(runForGeneration_);
     }
References eventHeader_, ldmx::EventHeader::getRun(), and runForGeneration_.
Referenced by ldmx::EventProcessor::getRunNumber().
getStorageController()
StorageControl& ldmx::Process::getStorageController () inline
Access the storage control unit for this process
Definition at line 105 of file Process.h.
 { return m_storageController; }
References m_storageController.
Referenced by ldmx::EventProcessor::setStorageHint().
makeHistoDirectory()
TDirectory * ldmx::Process::makeHistoDirectory (const std::string & dirName)
Construct a TDirectory* for the given module
Definition at line 380 of file Process.cxx.
{
         auto owner{openHistoFile()};
         TDirectory* child = owner->mkdir((char*) dirName.c_str());
         if (child)
             child->cd();
         return child;
     }
References openHistoFile().
Referenced by ldmx::EventProcessor::getHistoDirectory().
openHistoFile()
TDirectory * ldmx::Process::openHistoFile ()
Open a ROOT TFile to write histograms and TTrees.
Definition at line 388 of file Process.cxx.
{
         TDirectory* owner{nullptr};
         if (histoFilename_.empty()) {
             //trying to write histograms/ntuples but no file defined
             EXCEPTION_RAISE(
                     "NoHistFileName",
                     "You did not provide the necessary histogram file name to put your histograms (or ntuples) in.\n    Provide this name in the python configuration with 'p.histogramFile = \"myHistFile.root\"' where p is the Process object."
                     );
         } else if (histoTFile_ == nullptr) {
             histoTFile_ = new TFile(histoFilename_.c_str(), "RECREATE");
             owner = histoTFile_;
         } else owner = histoTFile_;
         owner->cd();
         return owner;
     }
References histoFilename_, and histoTFile_.
Referenced by makeHistoDirectory().
requestFinish()
void ldmx::Process::requestFinish () inline
Request that the processing finish with this event
Definition at line 90 of file Process.h.
 { eventLimit_=0; }
References eventLimit_.
run()
void ldmx::Process::run ()
Run the process.
Definition at line 100 of file Process.cxx.
                       {
         // set up the logging for this run
         logging::open(
                 logging::convertLevel(termLevelInt_),
                 logging::convertLevel(fileLevelInt_),
                 logFileName_ //if this is empty string, no file is logged to
                 );
         // create a logger for this process
         //      other objects will have their own channels
         //      the ldmx_log macro uses a variable called theLog_,
         //      so we are going to name it that for now.
         auto theLog_{logging::makeLogger("Process")};
         try {
             // Counter to keep track of the number of events that have been
             // procesed
             auto n_events_processed{0};
             //event bus for this process
             Event theEvent(passname_);
             // Start by notifying everyone that modules processing is beginning
             for (auto module : sequence_) module->onProcessStart();
             // If we have no input files, but do have an event number, run for
             // that number of events and generate an output file.
             if (inputFiles_.empty() && eventLimit_ > 0) {
                 if ( outputFiles_.empty() ) {
                     EXCEPTION_RAISE(
                             "InvalidConfig",
                             "No input files or output files were given."
                             );
                 } else if ( outputFiles_.size() > 1 ) {
                     ldmx_log(warn) << "Several output files given with no input files. "
                         << "Only the first output file '" << outputFiles_.at(0) << "' will be used.";
                 }
                 std::string outputFileName = outputFiles_.at(0);
                 EventFile outFile(outputFileName, compressionSetting_);
                 for (auto module : sequence_) module->onFileOpen(outFile);
                 outFile.setupEvent(&theEvent);
                 for ( auto rule : dropKeepRules_ ) outFile.addDrop(rule);
                 int numTries = 0; //number of tries for the current event number
                 while (n_events_processed < eventLimit_) {
                     EventHeader& eh = theEvent.getEventHeader();
                     eh.setRun(runForGeneration_);
                     eh.setEventNumber(n_events_processed + 1);
                     eh.setTimestamp(TTimeStamp());
                     // event header pointer grab
                     eventHeader_=theEvent.getEventHeaderPtr();
                     numTries++;
                     // reset the storage controller state
                     m_storageController.resetEventState();
                     if ( numTries <= 1 and getLogFrequency() > 0 and (eh.getEventNumber() % getLogFrequency() == 0 ) ) {
                         TTimeStamp t;
                         ldmx_log(info) << "Processing " << n_events_processed + 1
                             << " Run " << theEvent.getEventHeader().getRun()
                             << " Event " << theEvent.getEventHeader().getEventNumber()
                             << "  (" << t.AsString("lc") << ")";
                     }
                     bool eventAborted = false;
                     for (auto module : sequence_) {
                         try {
                             if (dynamic_cast<Producer*>(module)) {
                                 (dynamic_cast<Producer*>(module))->produce(theEvent);
                             } else if (dynamic_cast<Analyzer*>(module)) {
                                 (dynamic_cast<Analyzer*>(module))->analyze(theEvent);
                             }
                         } catch( AbortEventException& ) {
                             eventAborted = true;
                             break;
                         }
                     }
                     outFile.nextEvent( eventAborted ? false : m_storageController.keepEvent() /*ignore storage control if event aborted*/);
                     if ( not eventAborted or numTries >= maxTries_ ) {
                         n_events_processed++; //increment events made
                         NtupleManager::getInstance().fill();  //fill ntuples
                         numTries = 0; //reset try counter
                     }
                     NtupleManager::getInstance().clear();
                     theEvent.Clear();
                 }
                 for (auto module : sequence_) module->onFileClose(outFile);
                 outFile.close();
             } else {
                 //there are input files
                 EventFile* outFile(0);
                 bool singleOutput = false;
                 if ( outputFiles_.size() == 1 ) {
                     singleOutput = true;
                 } else if ( !outputFiles_.empty() and outputFiles_.size() != inputFiles_.size() ) {
                     EXCEPTION_RAISE(
                             "Process" ,
                             "Unable to handle case of different number of input and output files (other than zero/one ouput file)."
                             );
                 }
                 // next, loop through the files
                 int ifile = 0;
                 int wasRun = -1;
                 for (auto infilename : inputFiles_) {
                     EventFile inFile(infilename);
                     ldmx_log(info) << "Opening file " << infilename;
                     for (auto module : sequence_) module->onFileOpen(inFile);
                     //configure event file that will be iterated over
                     EventFile* masterFile;
                     if ( !outputFiles_.empty() ) {
                         //setup new output file if either
                         // 1) we are not in single output mode
                         // 2) this is the first input file
                         if ( !singleOutput or ifile == 0 ) {
                             //setup new output file
                             outFile = new EventFile(outputFiles_[ifile], &inFile, singleOutput, compressionSetting_ );
                             ifile++;
                             //setup theEvent we will iterate over
                             if (outFile) {
                                 outFile->setupEvent( &theEvent );
                                 masterFile = outFile;
                             } else {
                                 EXCEPTION_RAISE(
                                         "Process",
                                         "Unable to construct output file for " + outputFiles_[ifile]
                                         );
                             }
                             for ( auto rule : dropKeepRules_ ) outFile->addDrop(rule);
                         } else {
                             //all other input files
                             outFile->updateParent( &inFile );
                             masterFile = outFile;
                         } //check if in singleOutput mode
                     } else {
                         //empty output file list, use inputFile as master file
                         inFile.setupEvent( &theEvent );
                         masterFile = &inFile;
                     }
                     bool eventAborted = false;
                     while (masterFile->nextEvent(eventAborted ? false : m_storageController.keepEvent()/*ignore storage controller if event aborted*/)
                             && (eventLimit_ < 0 || (n_events_processed) < eventLimit_)) {
                         // clean up for storage control calculation
                         m_storageController.resetEventState();
                         // event header pointer grab
                         eventHeader_=theEvent.getEventHeaderPtr();
                         // notify for new run if necessary
                         if (theEvent.getEventHeader().getRun() != wasRun) {
                             wasRun = theEvent.getEventHeader().getRun();
                             try {
                                 const RunHeader& runHeader = masterFile->getRunHeader(wasRun);
                                 ldmx_log(info) << "Got new run header from '" << masterFile->getFileName() << "' ...";
                                 runHeader.Print(); //TODO print run header into log
                                 for (auto module : sequence_) {
                                     module->onNewRun(runHeader);
                                 }
                             } catch (const Exception&) {
                                 ldmx_log(warn) << "Run header for run " << wasRun << " was not found!";
                             }
                         }
                         if ( (logFrequency_ != -1) && ((n_events_processed + 1)%logFrequency_ == 0)) {
                             TTimeStamp t;
                             ldmx_log(info) << "Processing " << n_events_processed + 1
                                       << " Run " << theEvent.getEventHeader().getRun()
                                       << " Event " << theEvent.getEventHeader().getEventNumber()
                                       << "  (" << t.AsString("lc") << ")";
                         }
                         eventAborted = false;
                         for (auto module : sequence_) {
                             try {
                                 if (dynamic_cast<Producer*>(module)) {
                                     (dynamic_cast<Producer*>(module))->produce(theEvent);
                                 } else if (dynamic_cast<Analyzer*>(module)) {
                                     (dynamic_cast<Analyzer*>(module))->analyze(theEvent);
                                 }
                             } catch( AbortEventException& ) {
                                 eventAborted = true;
                                 break;
                             }
                         }
                         if ( not eventAborted ) NtupleManager::getInstance().fill();
                         NtupleManager::getInstance().clear();
                         n_events_processed++;
                     } //loop through events
                     if (eventLimit_ > 0 && n_events_processed == eventLimit_) {
                         ldmx_log(info) << "Reached event limit of " << eventLimit_ << " events";
                     }
                     if (eventLimit_ == 0 && n_events_processed > eventLimit_) {
                         ldmx_log(warn) << "Processing interrupted";
                     }
                     ldmx_log(info) << "Closing file " << infilename;
                     for (auto module : sequence_) module->onFileClose(inFile);
                     inFile.close();
                     // Reset the event in case of multiple input files
                     theEvent.onEndOfFile();
                     if ( outFile and !singleOutput ) {
                         outFile->close();
                         delete outFile;
                         outFile = nullptr;
                     }
                 } //loop through input files
                 if ( outFile ) {
                     //close outFile
                     //  outFile would survive to here in single output mode
                     outFile->close();
                     delete outFile;
                     outFile = nullptr;
                 }
             } //are there input files? if-else tree
             //close up histogram file if anything was put into it
             if (histoTFile_) {
                 histoTFile_->Write();
                 delete histoTFile_;
                 histoTFile_ = 0;
             }
             // finally, notify everyone that we are stopping
             for (auto module : sequence_) {
                 module->onProcessEnd();
             }
         } catch (Exception& e) {
             ldmx_log(fatal) << "[" << e.name() << "] : " << e.message() << "\n"
                             << "  at " << e.module() << ":" << e.line() << " in " << e.function();
         }
         //we're done so let's close up the logging
         logging::close();
     }
References ldmx::EventFile::addDrop(), ldmx::Event::Clear(), ldmx::NtupleManager::clear(), ldmx::EventFile::close(), compressionSetting_, dropKeepRules_, eventHeader_, eventLimit_, fileLevelInt_, ldmx::Exception::function(), ldmx::Event::getEventHeader(), ldmx::Event::getEventHeaderPtr(), ldmx::EventHeader::getEventNumber(), ldmx::NtupleManager::getInstance(), getLogFrequency(), ldmx::EventHeader::getRun(), ldmx::EventFile::getRunHeader(), histoTFile_, inputFiles_, ldmx::StorageControl::keepEvent(), ldmx::Exception::line(), logFileName_, logFrequency_, m_storageController, maxTries_, ldmx::Exception::message(), ldmx::Exception::module(), ldmx::Exception::name(), ldmx::EventFile::nextEvent(), ldmx::Event::onEndOfFile(), outputFiles_, passname_, ldmx::RunHeader::Print(), ldmx::StorageControl::resetEventState(), runForGeneration_, sequence_, ldmx::EventHeader::setEventNumber(), ldmx::EventHeader::setRun(), ldmx::EventHeader::setTimestamp(), ldmx::EventFile::setupEvent(), termLevelInt_, and ldmx::EventFile::updateParent().
Member Data Documentation
compressionSetting_
int ldmx::Process::compressionSetting_ private
Compression setting to pass to output files
Look at the documentation for the TFile constructor if you want to learn more details. Essentially, setting = 100*algo + level with algo = 0 being the global default.
Definition at line 174 of file Process.h.
Referenced by run().
conditions_
Conditions ldmx::Process::conditions_ private
Set of ConditionsProviders
Definition at line 159 of file Process.h.
Referenced by getConditions().
dropKeepRules_
std::vector<std::string> ldmx::Process::dropKeepRules_ private
Set of drop/keep rules.
Definition at line 177 of file Process.h.
Referenced by run().
eventHeader_
const EventHeader* ldmx::Process::eventHeader_ private
Pointer to the current EventHeader, used for Conditions information
Definition at line 186 of file Process.h.
Referenced by getEventHeader(), getRunNumber(), and run().
eventLimit_
int ldmx::Process::eventLimit_ private
Limit on events to process.
Definition at line 135 of file Process.h.
Referenced by requestFinish(), and run().
fileLevelInt_
int ldmx::Process::fileLevelInt_ private
Integer form of logging level to print to file
Definition at line 144 of file Process.h.
Referenced by run().
histoFilename_
std::string ldmx::Process::histoFilename_ private
Filename for histograms and other user products
Definition at line 183 of file Process.h.
Referenced by openHistoFile().
histoTFile_
TFile* ldmx::Process::histoTFile_ {0} private
TFile for histograms and other user products
Definition at line 189 of file Process.h.
Referenced by openHistoFile(), and run().
inputFiles_
std::vector<std::string> ldmx::Process::inputFiles_ private
List of input files to process. May be empty if this Process will generate new events.
Definition at line 162 of file Process.h.
Referenced by run().
logFileName_
std::string ldmx::Process::logFileName_ private
Name of file to print logging to
Definition at line 147 of file Process.h.
Referenced by run().
logFrequency_
int ldmx::Process::logFrequency_ private
The frequency with which event info is printed.
Definition at line 138 of file Process.h.
Referenced by getLogFrequency(), and run().
m_storageController
StorageControl ldmx::Process::m_storageController private
Storage controller
Definition at line 153 of file Process.h.
Referenced by getStorageController(), and run().
maxTries_
int ldmx::Process::maxTries_ private
Maximum number of attempts to make before giving up on an event
Definition at line 150 of file Process.h.
Referenced by run().
outputFiles_
std::vector<std::string> ldmx::Process::outputFiles_ private
List of output file names. If empty, no output file will be created.
Definition at line 165 of file Process.h.
Referenced by run().
passname_
std::string ldmx::Process::passname_ private
Processing pass name.
Definition at line 132 of file Process.h.
Referenced by getPassName(), and run().
runForGeneration_
int ldmx::Process::runForGeneration_ {1} private
Run number to use if generating events.
Definition at line 180 of file Process.h.
Referenced by getRunNumber(), and run().
sequence_
std::vector<EventProcessor*> ldmx::Process::sequence_ private
Ordered list of EventProcessors to execute.
Definition at line 156 of file Process.h.
Referenced by run(), and ~Process().
termLevelInt_
int ldmx::Process::termLevelInt_ private
Integer form of logging level to print to terminal
Definition at line 141 of file Process.h.
Referenced by run().
The documentation for this class was generated from the following files:
Framework/include/Framework/Process.h
Framework/src/Process.cxx