LDMX Software: ldmx::Simulator Class Reference
ldmx::Simulator Class Reference
Producer that runs Geant4 simulation inside of ldmx-app.
#include <Simulator.h>
Public Member Functions
Simulator (const std::string &name, ldmx::Process &process)
~Simulator ()
void configure (Parameters &parameters) final override
void beforeNewRun (RunHeader &header) final override
void onNewRun (const RunHeader &header) final override
virtual void produce (ldmx::Event &event) final override
void onFileOpen (EventFile &eventFile) final override
void onFileClose (EventFile &eventFile) final override
void onProcessStart () final override
void onProcessEnd () final override
Callback called once processing is complete.
Public Member Functions inherited from ldmx::Producer
Producer (const std::string &name, Process &process)
Public Member Functions inherited from ldmx::EventProcessor
EventProcessor (const std::string &name, Process &process)
virtual ~EventProcessor ()
template<class T >
const T & getCondition (const std::string &condition_name)
TDirectory * getHistoDirectory ()
void setStorageHint (ldmx::StorageControlHint hint)
void setStorageHint (ldmx::StorageControlHint hint, const std::string &purposeString)
int getLogFrequency () const
int getRunNumber () const
std::string getName () const
void createHistograms (const std::vector< Parameters > &histos)
Private Member Functions
bool allowed (const std::string &command) const
void setSeeds (std::vector< int > seeds)
Private Attributes
std::unique_ptr< RunManager > runManager_
Manager controlling G4 simulation run.
G4UImanager * uiManager_ {nullptr}
User interface handle.
std::unique_ptr< RootPersistencyManager > persistencyManager_
PersistencyManager.
std::unique_ptr< G4UIsession > sessionHandle_
Handle to the G4Session -> how to deal with G4cout and G4cerr.
int numEventsBegan_ {0}
Number of events started.
int numEventsCompleted_ {0}
Number of events completed.
Parameters parameters_
The parameters used to configure the simulation.
int verbosity_ {1}
Vebosity for the simulation.
Static Private Attributes
static const std::vector< std::string > invalidCommands_
Additional Inherited Members
Static Public Member Functions inherited from ldmx::EventProcessor
static void declare (const std::string &classname, int classtype, EventProcessorMaker *)
Static Public Attributes inherited from ldmx::Producer
static const int CLASSTYPE {1}
Protected Member Functions inherited from ldmx::EventProcessor
void abortEvent ()
Protected Attributes inherited from ldmx::EventProcessor
HistogramHelper histograms_
Interface class for making and filling histograms.
NtupleManager & ntuple_ {NtupleManager::getInstance()}
Manager for any ntuples.
logging::logger theLog_
The logger for this EventProcessor.
Detailed Description
Producer that runs Geant4 simulation inside of ldmx-app.
Most (if not all) of the heavy lifting is done in the classes in the Sim* modules. This producer is mainly focused on calling appropriate functions at the right time in the processing chain.
Definition at line 53 of file Simulator.h.
Constructor & Destructor Documentation
Simulator()
ldmx::Simulator::Simulator (const std::string & name, ldmx::Process & process)
Constructor.
Blank Producer constructor Constructs object that are non-configurable.
Parameters
name Name for this instance of the class.
process The Process class assocaited with EventProcessor, provided by the Framework.
Definition at line 46 of file Simulator.cxx.
                                                                 : Producer( name , process ) {
   // Get the ui manager from geant
   //      This pointer is handled by Geant4
   uiManager_ = G4UImanager::GetUIpointer();
 }
References uiManager_.
~Simulator()
ldmx::Simulator::~Simulator ()
Destructor.
Deletes hanging pointers
Definition at line 54 of file Simulator.cxx.
 { }
Member Function Documentation
allowed()
bool ldmx::Simulator::allowed (const std::string & command) const private
Check if the input command is allowed to be run.
Looks for sub-strings matching the ones listed as an invalid command. These invalid commands are mostly commands where control has been handed over to Simulator.
Definition at line 350 of file Simulator.cxx.
{
   for ( const std::string &invalidSubstring : invalidCommands_ ) {
     if ( command.find( invalidSubstring ) != std::string::npos ) {
       //found invalid substring in this command ==> NOT ALLOWED
       return false;
     }
   }
   //checked all invalid commands ==> ALLOWED
   return true;
 }
References invalidCommands_.
Referenced by configure(), and onProcessStart().
beforeNewRun()
void ldmx::Simulator::beforeNewRun (RunHeader & header) final override virtual
Before the Run Starts (but after configuration is complete) write out simulatin parameters to the run header
Parameters
[in,out] header RunHeader for this run
Reimplemented from ldmx::Producer.
Definition at line 127 of file Simulator.cxx.
{
   // Get the detector header from the user detector construction
   DetectorConstruction* detector
       = static_cast<RunManager*>(RunManager::GetRunManager())->getDetectorConstruction();
   if (!detector or !detector->getDetectorHeader())
     EXCEPTION_RAISE("SimSetup","Detector not constructed before run start.");
   header.setDetectorName(detector->getDetectorHeader()->getName());
   header.setDescription(parameters_.getParameter<std::string>("description"));
   header.setIntParameter("Save ECal Hit Contribs" , parameters_.getParameter<bool>("enableHitContribs"));
   header.setIntParameter("Compress ECal Hit Contribs" , parameters_.getParameter<bool>("compressHitContribs"));
   header.setIntParameter("Included Scoring Planes" , !parameters_.getParameter<std::string>("scoringPlanes").empty() );
   header.setIntParameter("Use Random Seed from Event Header" , parameters_.getParameter<bool>("rootPrimaryGenUseSeed") );
   //lambda function for dumping 3-vectors into the run header
   auto threeVectorDump = [&header](const std::string& name, const std::vector<double>& vec) {
                            header.setFloatParameter( name + " X" , vec.at(0) );
                            header.setFloatParameter( name + " Y" , vec.at(1) );
                            header.setFloatParameter( name + " Z" , vec.at(2) );
                          };
   auto beamSpotSmear{parameters_.getParameter<std::vector<double>>("beamSpotSmear",{})};
   if ( !beamSpotSmear.empty() ) threeVectorDump( "Smear Beam Spot [mm]" , beamSpotSmear );
   //lambda function for dumping vectors of strings to the run header
   auto stringVectorDump = [&header](const std::string& name, const std::vector<std::string>& vec ) {
                             int index = 0;
                             for ( auto const & val : vec ) {
                               header.setStringParameter( name + " " + std::to_string(++index) , val );
                             }
                           };
   stringVectorDump( "Pre Init Command"  , parameters_.getParameter<std::vector<std::string>>("preInitCommands",{}) );
   stringVectorDump( "Post Init Command" , parameters_.getParameter<std::vector<std::string>>("postInitCommands",{}) );
   if ( parameters_.getParameter<bool>("biasing_enabled") ) {
     header.setStringParameter("Biasing Process"  , parameters_.getParameter<std::string>("biasing_process"));
     header.setStringParameter("Biasing Volume"   , parameters_.getParameter<std::string>("biasing_volume"));
     header.setStringParameter("Biasing Particle" , parameters_.getParameter<std::string>("biasing_particle"));
     header.setIntParameter(   "Biasing All"      , parameters_.getParameter<bool>(       "biasing_all" ));
     header.setIntParameter(   "Biasing Incident" , parameters_.getParameter<bool>(       "biasing_incident" ));
     header.setIntParameter(   "Biasing Disable EM",parameters_.getParameter<bool>(       "biasing_disableEMBiasing" ));
     header.setIntParameter(   "Biasing Factor"   , parameters_.getParameter<int>(        "biasing_factor" ));
     header.setFloatParameter( "Biasing Threshold", parameters_.getParameter<double>(     "biasing_threshold" ));
   }
   auto apMass{parameters_.getParameter<double>("APrimeMass")};
   if ( apMass > 0 ) {
     header.setFloatParameter(  "A' Mass [MeV]" , apMass );
     header.setFloatParameter(  "Dark Brem Global Bias" , parameters_.getParameter<double>("darkbrem_globalxsecfactor") );
     header.setStringParameter( "Dark Brem Vertex Library Path" , parameters_.getParameter<std::string>("darkbrem_madgraphfilepath") );
     header.setIntParameter(    "Dark Brem Interpretation Method" , parameters_.getParameter<int>("darkbrem_method") );
   }
   auto generators{parameters_.getParameter<std::vector<Parameters>>("generators")};
   int counter = 0;
   for ( auto const &gen : generators ) {
     std::string genID = "Gen " + std::to_string(++counter);
     auto className{gen.getParameter<std::string>("class_name")};
     header.setStringParameter( genID + " Class" , className );
     if ( className.find("ldmx::ParticleGun") != std::string::npos ) {
       header.setFloatParameter( genID + " Time [ns]" , gen.getParameter<double>("time") );
       header.setFloatParameter( genID + " Energy [MeV]" , gen.getParameter<double>("energy") );
       header.setStringParameter( genID + " Particle" , gen.getParameter<std::string>("particle") );
       threeVectorDump( genID + " Position [mm]" , gen.getParameter<std::vector<double>>("position") );
       threeVectorDump( genID + " Direction" , gen.getParameter<std::vector<double>>("direction") );
     } else if ( className.find("ldmx::MultiParticleGunPrimaryGenerator") != std::string::npos ) {
       header.setIntParameter( genID + " Poisson Enabled" , gen.getParameter<bool>("enablePoisson") );
       header.setIntParameter( genID + " N Particles" , gen.getParameter<int>("nParticles") );
       header.setIntParameter( genID + " PDG ID" , gen.getParameter<int>("pdgID") );
       threeVectorDump( genID + " Vertex [mm]" , gen.getParameter<std::vector<double>>("vertex") );
       threeVectorDump( genID + " Momentum [MeV]" , gen.getParameter<std::vector<double>>("momentum") );
     } else if ( className.find("ldmx::LHEPrimaryGenerator") != std::string::npos ) {
       header.setStringParameter( genID + " LHE File" , gen.getParameter<std::string>("filePath") );
     } else if ( className.find("ldmx::RootCompleteReSim") != std::string::npos ) {
       header.setStringParameter( genID + " ROOT File" , gen.getParameter<std::string>("filePath") );
     } else if ( className.find("ldmx::RootSimFromEcalSP") != std::string::npos ) {
       header.setStringParameter( genID + " ROOT File" , gen.getParameter<std::string>("filePath") );
       header.setFloatParameter( genID + " Time Cutoff [ns]" , gen.getParameter<double>("time_cutoff") );
     } else if ( className.find("ldmx::GeneralParticleSource") != std::string::npos ) {
       stringVectorDump( genID + " Init Cmd" , gen.getParameter<std::vector<std::string>>("initCommands") );
     } else  {
         ldmx_log(warn) << "Unrecognized primary generator '" << className << "'. "
                 << "Will not be saving details to RunHeader.";
     }
   }
   // Set a string parameter with the Geant4 SHA-1.
   if (G4RunManagerKernel::GetRunManagerKernel()) {
     G4String g4Version{G4RunManagerKernel::GetRunManagerKernel()->GetVersionString()};
     header.setStringParameter("Geant4 revision", g4Version);
   } else {
     ldmx_log(warn) << "Unable to access G4 RunManager Kernel. Will not store G4 Version string.";
   }
   header.setStringParameter("ldmx-sw revision", GIT_SHA1);
 }
References ldmx::DetectorConstruction::getDetectorHeader(), ldmx::DetectorHeader::getName(), ldmx::Parameters::getParameter(), parameters_, ldmx::RunHeader::setDescription(), ldmx::RunHeader::setDetectorName(), ldmx::RunHeader::setFloatParameter(), ldmx::RunHeader::setIntParameter(), and ldmx::RunHeader::setStringParameter().
configure()
void ldmx::Simulator::configure (Parameters & parameters) final override virtual
Callback for the processor to configure itself from the given set of parameters.
Parameters
parameters ParameterSet for configuration.
Reimplemented from ldmx::EventProcessor.
Definition at line 56 of file Simulator.cxx.
{
   // parameters used to configure the simulation
   parameters_ = parameters;
   // Set the verbosity level.  The default level  is 0.
   verbosity_ = parameters_.getParameter< int >("verbosity");
   // If the verbosity level is set to 0,
   // If the verbosity level is > 1, log everything to a file. Otherwise,
   // dump the output. If a prefix has been specified, append it ot the
   // log message.
   auto loggingPrefix = parameters_.getParameter< std::string >("logging_prefix");
   if ( verbosity_ == 0 ) sessionHandle_ = std::make_unique<BatchSession>();
   else if ( verbosity_ > 1 ) {
     if ( loggingPrefix.empty() ) sessionHandle_ = std::make_unique<LoggedSession>();
     else sessionHandle_ = std::make_unique<LoggedSession>( loggingPrefix + "_G4cout.log" , loggingPrefix + "_G4cerr.log" );
   }
   if (sessionHandle_ != nullptr) uiManager_->SetCoutDestination( sessionHandle_.get() );
   // Instantiate the run manager.
   runManager_ = std::make_unique<RunManager>(parameters);
   // Instantiate the GDML parser and corresponding messenger owned and
   // managed by DetectorConstruction
   G4GDMLParser *parser = new G4GDMLParser;
   // Instantiate the class so cascade parameters can be set.
   G4CascadeParameters::Instance();
   // Set the DetectorConstruction instance used to build the detector
   // from the GDML description.
   runManager_->SetUserInitialization( new DetectorConstruction( parser , parameters ) );
   // Parse the detector geometry and validate if specified.
   auto detectorPath{parameters_.getParameter< std::string >("detector")};
   auto validateGeometry{parameters_.getParameter< bool >("validate_detector")};
   if ( verbosity_ > 0 ) {
     std::cout << "[ Simulator ] : Reading in geometry from '" << detectorPath << "'... " << std::flush;
   }
   G4GeometryManager::GetInstance()->OpenGeometry();
   parser->Read( detectorPath, validateGeometry );
   runManager_->DefineWorldVolume( parser->GetWorldVolume() );
   auto preInitCommands = parameters_.getParameter< std::vector< std::string > >("preInitCommands" ,{} );
   for ( const std::string& cmd : preInitCommands ) {
     if ( allowed(cmd) ) {
       int g4Ret = uiManager_->ApplyCommand( cmd );
       if ( g4Ret > 0 ) {
         EXCEPTION_RAISE(
             "PreInitCmd",
             "Pre Initialization command '" + cmd + "' returned a failue status from Geant4: " + std::to_string(g4Ret)
                         );
       }
     } else {
       EXCEPTION_RAISE(
           "PreInitCmd",
           "Pre Initialization command '" + cmd + "' is not allowed because another part of Simulator handles it."
                       );
     }
   }
 }
References allowed(), ldmx::Parameters::getParameter(), parameters_, runManager_, sessionHandle_, uiManager_, and verbosity_.
onFileClose()
void ldmx::Simulator::onFileClose (EventFile & eventFile) final override virtual
Callback for the EventProcessor to take any necessary action when a file is closed.
Parameters
eventFile The intput/output file.
Reimplemented from ldmx::EventProcessor.
Definition at line 306 of file Simulator.cxx.
{
   // End the current run and print out some basic statistics if verbose
   // level > 0.
   runManager_->TerminateEventLoop();
   // Pass the **real** number of events to the persistency manager
   persistencyManager_->setNumEvents( numEventsBegan_ , numEventsCompleted_ );
   // Persist any remaining events, call the end of run action and
   // terminate the Geant4 kernel.
   runManager_->RunTermination();
   // Cleanup persistency manager
   //  Geant4 expects us to handle the persistency manager
   //  In order to avoid segfaulting nonsense, I delete it here
   //  so that it is deleted before the EventFile it references
   //  is deleted
   persistencyManager_.reset( nullptr );
 }
References numEventsBegan_, numEventsCompleted_, persistencyManager_, and runManager_.
onFileOpen()
void ldmx::Simulator::onFileOpen (EventFile & eventFile) final override virtual
Callback for the EventProcessor to take any necessary action when a new file is opened.
Parameters
eventFile The input/output file.
Reimplemented from ldmx::EventProcessor.
Definition at line 121 of file Simulator.cxx.
{
   // Initialize persistency manager and connect it to the current EventFile
   persistencyManager_ = std::make_unique<RootPersistencyManager>(file, parameters_, this->getRunNumber());
   persistencyManager_->Initialize();
 }
References ldmx::EventProcessor::getRunNumber(), parameters_, and persistencyManager_.
onNewRun()
void ldmx::Simulator::onNewRun (const RunHeader & header) final override virtual
Before the run starts (but after the conditions are configured) set up the random seeds for this run.
Parameters
[in] header RunHeader for this run, unused
Reimplemented from ldmx::EventProcessor.
Definition at line 230 of file Simulator.cxx.
{
   const RandomNumberSeedService& rseed = getCondition<RandomNumberSeedService>(RandomNumberSeedService::CONDITIONS_OBJECT_NAME);
   std::vector<int> seeds;
   seeds.push_back(rseed.getSeed("Simulator[0]"));
   seeds.push_back(rseed.getSeed("Simulator[1]"));
   setSeeds(seeds);
 }
References ldmx::RandomNumberSeedService::CONDITIONS_OBJECT_NAME, ldmx::RandomNumberSeedService::getSeed(), and setSeeds().
onProcessStart()
void ldmx::Simulator::onProcessStart () final override virtual
Initialization of simulation
This uses the parameters set in the configure method to construct and initialize the simulation objects.
This function runs the post init setup commands.
Reimplemented from ldmx::EventProcessor.
Definition at line 270 of file Simulator.cxx.
{
   //initialize run
   runManager_->Initialize();
   // Get the extra simulation configuring commands
   auto postInitCommands = parameters_.getParameter< std::vector< std::string > >("postInitCommands",{});
   for ( const std::string& cmd : postInitCommands ) {
     if ( allowed(cmd) ) {
       int g4Ret = uiManager_->ApplyCommand( cmd );
       if ( g4Ret > 0 ) {
         EXCEPTION_RAISE(
             "PostInitCmd",
             "Post Initialization command '" + cmd + "' returned a failue status from Geant4: " + std::to_string(g4Ret)
                         );
       }
     } else {
       EXCEPTION_RAISE(
           "PostInitCmd",
           "Post Initialization command '" + cmd + "' is not allowed because another part of Simulator handles it."
                       );
     }
   }
   // Instantiate the scoring worlds including any parallel worlds.
   runManager_->ConstructScoringWorlds();
   // Initialize the current run
   runManager_->RunInitialization();
   // Initialize the event processing
   runManager_->InitializeEventLoop( 1 );
   return;
 }
References allowed(), ldmx::Parameters::getParameter(), parameters_, runManager_, and uiManager_.
produce()
void ldmx::Simulator::produce (ldmx::Event & event) final override virtual
Run simulation and export results to output event.
Parameters
event The event to process.
Implements ldmx::Producer.
Definition at line 238 of file Simulator.cxx.
{
   // Pass the current LDMX event object to the persistency manager.  This
   // is needed by the persistency manager to fill the current event.
   persistencyManager_->setCurrentEvent( &event );
   // Generate and process a Geant4 event.
   numEventsBegan_++;
   runManager_->ProcessOneEvent( event.getEventHeader().getEventNumber() );
   // If a Geant4 event has been aborted, skip the rest of the processing
   // sequence. This will immediately force the simulation to move on to
   // the next event.
   if ( runManager_->GetCurrentEvent()->IsAborted() ) {
     runManager_->TerminateOneEvent(); //clean up event objects
     this->abortEvent();  //get out of processors loop
   }
   if ( this->getLogFrequency() > 0 and event.getEventHeader().getEventNumber() % this->getLogFrequency() == 0 ) {
     //print according to log frequency and verbosity
     if ( verbosity_ > 1 ) std::cout << "[ Simulator ] : Printing event contents:" << std::endl;
     event.Print( verbosity_ );
   }
   // Terminate the event.  This checks if an event is to be stored or
   // stacked for later.
   numEventsCompleted_++;
   runManager_->TerminateOneEvent();
   return;
 }
References ldmx::EventProcessor::abortEvent(), ldmx::Event::getEventHeader(), ldmx::EventHeader::getEventNumber(), ldmx::EventProcessor::getLogFrequency(), numEventsBegan_, numEventsCompleted_, persistencyManager_, runManager_, and verbosity_.
setSeeds()
void ldmx::Simulator::setSeeds (std::vector< int > seeds) private
Set the seeds to be used by the Geant4 random engine.
Parameters
[in] seeds A vector of seeds to pass to the G4 random engine. The vector must contain at least 2 seeds otherwise an exception is thrown.
Definition at line 361 of file Simulator.cxx.
{
   // If no seeds have been specified then return immediately.
   if (seeds.empty()) return;
   // If seeds are specified, make sure that the container has at least
   // two seeds.  If not, throw an exception.
   if (seeds.size() == 1) {
     EXCEPTION_RAISE("ConfigurationException", "At least two seeds need to be specified.");
   }
   // Create the array of seeds and pass them to G4Random.  Currently,
   // only 100 seeds can be specified at a time.  If less than 100
   // seeds are specified, the remaining slots are set to 0.
   std::vector< long > seedVec(100, 0);
   for (std::size_t index{0}; index < seeds.size(); ++index) seedVec[index] = static_cast<long>(seeds[index]);
   // Pass the array of seeds to the random engine.
   G4Random::setTheSeeds(&seedVec[0]);
 }
Referenced by onNewRun().
Member Data Documentation
invalidCommands_
const std::vector< std::string > ldmx::Simulator::invalidCommands_ static private
Initial value:
= {
  "/run/initialize",
  "/run/beamOn",
  "/random/setSeeds",
  "ldmx",
  "/persistency/gdml/read"
}
Commands not allowed to be passed from python config file This is because Simulator already runs them.
Definition at line 173 of file Simulator.h.
Referenced by allowed().
The documentation for this class was generated from the following files:
SimCore/include/SimCore/Simulator.h
SimCore/src/Simulator.cxx