LDMX Software: framework::test::TestProducer Class Reference
framework::test::TestProducer Class Reference
Public Member Functions
TestProducer (const std::string &name, Process &p)
void configure (framework::config::Parameters &p) final override
void beforeNewRun (ldmx::RunHeader &header) final override
void produce (framework::Event &event) final override
Public Member Functions inherited from framework::Producer
Producer (const std::string &name, Process &process)
virtual void produce (Event &event)=0
virtual void beforeNewRun (ldmx::RunHeader &header)
Public Member Functions inherited from framework::EventProcessor
EventProcessor (const std::string &name, Process &process)
virtual ~EventProcessor ()
virtual void configure (framework::config::Parameters &parameters)
virtual void onNewRun (const ldmx::RunHeader &runHeader)
virtual void onFileOpen (EventFile &eventFile)
virtual void onFileClose (EventFile &eventFile)
virtual void onProcessStart ()
virtual void onProcessEnd ()
template<class T >
const T & getCondition (const std::string &condition_name)
TDirectory * getHistoDirectory ()
void setStorageHint (framework::StorageControlHint hint)
void setStorageHint (framework::StorageControlHint hint, const std::string &purposeString)
int getLogFrequency () const
int getRunNumber () const
std::string getName () const
void createHistograms (const std::vector< framework::config::Parameters > &histos)
Private Attributes
int events_
number of events we've gotten to
bool createRunHeader_
should we create the run header?
Additional Inherited Members
Static Public Member Functions inherited from framework::EventProcessor
static void declare (const std::string &classname, int classtype, EventProcessorMaker *)
Static Public Attributes inherited from framework::Producer
static const int CLASSTYPE {1}
Protected Member Functions inherited from framework::EventProcessor
void abortEvent ()
Protected Attributes inherited from framework::EventProcessor
HistogramHelper histograms_
Interface class for making and filling histograms.
NtupleManager & ntuple_ {NtupleManager::getInstance()}
Manager for any ntuples.
logging::logger theLog_
The logger for this EventProcessor.
Detailed Description
Bare producer that creates a collection and an object and puts them on the event bus.
The pattern this producer creates is the following:
The vector of Calorimeter hits has the same number of entries as the event number
The IDs of the calorimeter hits are set to 10*eventNumber+their_index
The input object is an HcalVetoResult where events with an event index pass
The max PE hit in the HcalVetoResult has an ID equal to the event index
If a run header is created, the event count and the run number are equal
Checks
Event::add function does not throw any errors.
Writes and adds a run header where the run number and the number of events are the same.
sets a storage hint
Definition at line 39 of file FunctionalCoreTest.cxx.
Constructor & Destructor Documentation
TestProducer()
framework::test::TestProducer::TestProducer (const std::string & name, Process & p) inline
Definition at line 47 of file FunctionalCoreTest.cxx.
: Producer(name, p) {}
~TestProducer()
framework::test::TestProducer::~TestProducer () inline
Definition at line 48 of file FunctionalCoreTest.cxx.
{}
Member Function Documentation
beforeNewRun()
void framework::test::TestProducer::beforeNewRun (ldmx::RunHeader & header) inline final override virtual
Handle allowing producers to modify run headers before the run begins
Parameters
header RunHeader for Producer to add parameters to
Reimplemented from framework::Producer.
Definition at line 54 of file FunctionalCoreTest.cxx.
{
    if (not createRunHeader_) return;
    header.setIntParameter("Should Be Run Number", header.getRunNumber());
    return;
  }
References createRunHeader_.
configure()
void framework::test::TestProducer::configure (framework::config::Parameters & parameters) inline final override virtual
Callback for the EventProcessor to configure itself from the given set of parameters.
The parameters a processor has access to are the member variables of the python class in the sequence that has className equal to the EventProcessor class name.
For an example, look at MyProcessor.
Parameters
parameters Parameters for configuration.
Reimplemented from framework::EventProcessor.
Definition at line 50 of file FunctionalCoreTest.cxx.
{
    createRunHeader_ = p.getParameter<bool>("createRunHeader");
  }
References createRunHeader_.
produce()
void framework::test::TestProducer::produce (framework::Event & event) inline final override virtual
Process the event and put new data products into it.
Parameters
event The Event to process.
Implements framework::Producer.
Definition at line 60 of file FunctionalCoreTest.cxx.
{
    int i_event = event.getEventNumber();
    REQUIRE(i_event > 0);
    std::vector<ldmx::CalorimeterHit> caloHits;
    for (int i = 0; i < i_event; i++) {
      caloHits.emplace_back();
      caloHits.back().setID(i_event * 10 + i);
    }
    REQUIRE_NOTHROW(event.add("TestCollection", caloHits));
    ldmx::HcalHit maxPEHit;
    maxPEHit.setID(i_event);
    ldmx::HcalVetoResult res;
    res.setMaxPEHit(maxPEHit);
    res.setVetoResult(i_event % 2 == 0);
    REQUIRE_NOTHROW(event.add("TestObject", res));
    events_ = i_event;
    std::vector<int> event_indices = {i_event, i_event};
    REQUIRE_NOTHROW(event.add("EventIndex", event_indices));
    float test_float = i_event * 0.1;
    REQUIRE_NOTHROW(event.add("EventTenth", test_float));
    if (res.passesVeto()) setStorageHint(hint_mustKeep);
    return;
  }
References events_, ldmx::HcalVetoResult::passesVeto(), ldmx::CalorimeterHit::setID(), ldmx::HcalVetoResult::setMaxPEHit(), framework::EventProcessor::setStorageHint(), and ldmx::HcalVetoResult::setVetoResult().
Member Data Documentation
createRunHeader_
bool framework::test::TestProducer::createRunHeader_ private
should we create the run header?
Definition at line 44 of file FunctionalCoreTest.cxx.
Referenced by beforeNewRun(), and configure().
events_
int framework::test::TestProducer::events_ private
number of events we've gotten to
Definition at line 41 of file FunctionalCoreTest.cxx.
Referenced by produce().
The documentation for this class was generated from the following file:
Framework/test/FunctionalCoreTest.cxx