LDMX Software: dqm::NtuplizeHgcrocDigiCollection Class Reference
dqm::NtuplizeHgcrocDigiCollection Class Reference
Public Member Functions
NtuplizeHgcrocDigiCollection (std::string const &n, framework::Process &p)
void configure (framework::config::Parameters &ps) final override
void onProcessStart () final override
void analyze (const framework::Event &event) final override
Public Member Functions inherited from framework::Analyzer
Analyzer (const std::string &name, Process &process)
virtual void analyze (const Event &event)=0
Public Member Functions inherited from framework::EventProcessor
EventProcessor (const std::string &name, Process &process)
virtual ~EventProcessor ()
virtual void configure (framework::config::Parameters &parameters)
virtual void onNewRun (const ldmx::RunHeader &runHeader)
virtual void onFileOpen (EventFile &eventFile)
virtual void onFileClose (EventFile &eventFile)
virtual void onProcessStart ()
virtual void onProcessEnd ()
template<class T >
const T & getCondition (const std::string &condition_name)
TDirectory * getHistoDirectory ()
void setStorageHint (framework::StorageControlHint hint)
void setStorageHint (framework::StorageControlHint hint, const std::string &purposeString)
int getLogFrequency () const
int getRunNumber () const
std::string getName () const
void createHistograms (const std::vector< framework::config::Parameters > &histos)
Private Attributes
std::string input_name_
std::string input_pass_
std::string pedestal_table_
int ldmxsw_event_
int version_
int pf_event_
int pf_ticks_
int pf_spill_
int raw_id_
int adc_
int raw_adc_
int tot_
int toa_
int i_sample_
int fpga_
int link_
int channel_
int index_
int section_
int layer_
int strip_
int end_
bool tot_prog_
bool tot_comp_
bool aligned_
bool using_eid_
bool already_aligned_
TTree * flat_tree_
Additional Inherited Members
Static Public Member Functions inherited from framework::EventProcessor
static void declare (const std::string &classname, int classtype, EventProcessorMaker *)
Static Public Attributes inherited from framework::Analyzer
static const int CLASSTYPE {2}
Protected Member Functions inherited from framework::EventProcessor
void abortEvent ()
Protected Attributes inherited from framework::EventProcessor
HistogramHelper histograms_
Interface class for making and filling histograms.
NtupleManager & ntuple_ {NtupleManager::getInstance()}
Manager for any ntuples.
logging::logger theLog_
The logger for this EventProcessor.
Detailed Description
Definition at line 10 of file NtuplizeHgcrocDigiCollection.cxx.
Constructor & Destructor Documentation
NtuplizeHgcrocDigiCollection()
dqm::NtuplizeHgcrocDigiCollection::NtuplizeHgcrocDigiCollection (std::string const & n, framework::Process & p) inline
Definition at line 21 of file NtuplizeHgcrocDigiCollection.cxx.
      : framework::Analyzer(n, p) {}
~NtuplizeHgcrocDigiCollection()
dqm::NtuplizeHgcrocDigiCollection::~NtuplizeHgcrocDigiCollection () inline
Definition at line 23 of file NtuplizeHgcrocDigiCollection.cxx.
{}
Member Function Documentation
analyze()
void dqm::NtuplizeHgcrocDigiCollection::analyze (const framework::Event & event) final override virtual
Process the event and make histograms or summaries
Parameters
event The Event to analyze
Implements framework::Analyzer.
Definition at line 71 of file NtuplizeHgcrocDigiCollection.cxx.
{
  // get the reconstruction parameters
  auto pedestal_table{getCondition<conditions::IntegerTableCondition>(pedestal_table_)};
  ldmxsw_event_ = event.getEventNumber();
  if (already_aligned_) {
    aligned_ = event.getObject<bool>(input_name_+"Aligned", input_pass_);
  } else {
    aligned_ = false;
    version_ = event.getObject<int>(input_name_+"Version", input_pass_);
    pf_event_ = event.getObject<int>(input_name_+"Number", input_pass_);
    pf_ticks_ = event.getObject<int>(input_name_+"Ticks", input_pass_);
    pf_spill_ = event.getObject<int>(input_name_+"Spill", input_pass_);
  }
  auto const& digis{
      event.getObject<ldmx::HgcrocDigiCollection>(input_name_, input_pass_)};
  for (std::size_t i_digi{0}; i_digi < digis.size(); i_digi++) {
    auto d{digis.getDigi(i_digi)};
    raw_id_ = static_cast<int>(d.id());
    if (using_eid_) {
      ldmx::HcalElectronicsID eid(d.id());
      fpga_ = eid.fiber();
      link_ = eid.elink();
      channel_ = eid.channel();
      index_ = eid.index();
    } else {
      ldmx::HcalDigiID detid(d.id());
      section_ = detid.section();
      layer_ = detid.layer();
      strip_ = detid.strip();
      end_ = detid.end();
    }
    for (i_sample_ = 0; i_sample_ < digis.getNumSamplesPerDigi(); i_sample_++) {
      tot_prog_ = d.at(i_sample_).isTOTinProgress();
      tot_comp_ = d.at(i_sample_).isTOTComplete();
      tot_ = d.at(i_sample_).tot();
      toa_ = d.at(i_sample_).toa();
      int adc_t = d.at(i_sample_).adc_t();
      raw_adc_ = adc_t;
      adc_ =  adc_t - pedestal_table.get(d.id(), 0);
      flat_tree_->Fill();
    }
  }
}
References ldmx::HcalElectronicsID::channel(), ldmx::HcalElectronicsID::elink(), ldmx::HcalDigiID::end(), ldmx::HcalElectronicsID::fiber(), ldmx::HgcrocDigiCollection::getDigi(), ldmx::HcalElectronicsID::index(), ldmx::HcalDigiID::layer(), ldmx::HcalDigiID::section(), and ldmx::HcalDigiID::strip().
configure()
void dqm::NtuplizeHgcrocDigiCollection::configure (framework::config::Parameters & parameters) inline final override virtual
Callback for the EventProcessor to configure itself from the given set of parameters.
The parameters a processor has access to are the member variables of the python class in the sequence that has className equal to the EventProcessor class name.
For an example, look at MyProcessor.
Parameters
parameters Parameters for configuration.
Reimplemented from framework::EventProcessor.
Definition at line 25 of file NtuplizeHgcrocDigiCollection.cxx.
{
    input_name_ = ps.getParameter<std::string>("input_name");
    input_pass_ = ps.getParameter<std::string>("input_pass");
    pedestal_table_ = ps.getParameter<std::string>("pedestal_table");
    using_eid_ = ps.getParameter<bool>("using_eid");
    already_aligned_ = ps.getParameter<bool>("already_aligned");
  }
onProcessStart()
void dqm::NtuplizeHgcrocDigiCollection::onProcessStart () inline final override virtual
Callback for the EventProcessor to take any necessary action when the processing of events starts, such as creating histograms.
Reimplemented from framework::EventProcessor.
Definition at line 33 of file NtuplizeHgcrocDigiCollection.cxx.
{
    getHistoDirectory();
    // cleaned up when histogram file is closed
    flat_tree_ = new TTree("hgcroc", "Ntuplized HGC ROC Digi Collection");
    flat_tree_->Branch("raw_id", &raw_id_);
    flat_tree_->Branch("adc", &adc_);
    flat_tree_->Branch("tot", &tot_);
    flat_tree_->Branch("toa", &toa_);
    flat_tree_->Branch("raw_adc", &raw_adc_);
    flat_tree_->Branch("i_sample", &i_sample_);
    flat_tree_->Branch("ldmxsw_event", &ldmxsw_event_);
    flat_tree_->Branch("pf_event", &pf_event_);
    flat_tree_->Branch("pf_ticks", &pf_ticks_);
    if (not already_aligned_) {
      flat_tree_->Branch("pf_event", &pf_event_);
      flat_tree_->Branch("pf_spill", &pf_spill_);
      flat_tree_->Branch("pf_ticks", &pf_ticks_);
    }
    flat_tree_->Branch("tot_prog", &tot_prog_);
    flat_tree_->Branch("tot_comp", &tot_comp_);
    flat_tree_->Branch("aligned", &aligned_);
    if (using_eid_) {
      flat_tree_->Branch("fpga", &fpga_);
      flat_tree_->Branch("link", &link_);
      flat_tree_->Branch("channel", &channel_);
      flat_tree_->Branch("index", &index_);
    } else {
      flat_tree_->Branch("section", &section_);
      flat_tree_->Branch("layer", &layer_);
      flat_tree_->Branch("strip", &strip_);
      flat_tree_->Branch("end", &end_);
    }
  }
References framework::EventProcessor::getHistoDirectory().
Member Data Documentation
adc_
int dqm::NtuplizeHgcrocDigiCollection::adc_ private
Definition at line 13 of file NtuplizeHgcrocDigiCollection.cxx.
aligned_
bool dqm::NtuplizeHgcrocDigiCollection::aligned_ private
Definition at line 16 of file NtuplizeHgcrocDigiCollection.cxx.
already_aligned_
bool dqm::NtuplizeHgcrocDigiCollection::already_aligned_ private
Definition at line 17 of file NtuplizeHgcrocDigiCollection.cxx.
channel_
int dqm::NtuplizeHgcrocDigiCollection::channel_ private
Definition at line 14 of file NtuplizeHgcrocDigiCollection.cxx.
end_
int dqm::NtuplizeHgcrocDigiCollection::end_ private
Definition at line 15 of file NtuplizeHgcrocDigiCollection.cxx.
flat_tree_
TTree* dqm::NtuplizeHgcrocDigiCollection::flat_tree_ private
Definition at line 18 of file NtuplizeHgcrocDigiCollection.cxx.
fpga_
int dqm::NtuplizeHgcrocDigiCollection::fpga_ private
Definition at line 14 of file NtuplizeHgcrocDigiCollection.cxx.
i_sample_
int dqm::NtuplizeHgcrocDigiCollection::i_sample_ private
Definition at line 13 of file NtuplizeHgcrocDigiCollection.cxx.
index_
int dqm::NtuplizeHgcrocDigiCollection::index_ private
Definition at line 14 of file NtuplizeHgcrocDigiCollection.cxx.
input_name_
std::string dqm::NtuplizeHgcrocDigiCollection::input_name_ private
Definition at line 11 of file NtuplizeHgcrocDigiCollection.cxx.
input_pass_
std::string dqm::NtuplizeHgcrocDigiCollection::input_pass_ private
Definition at line 11 of file NtuplizeHgcrocDigiCollection.cxx.
layer_
int dqm::NtuplizeHgcrocDigiCollection::layer_ private
Definition at line 15 of file NtuplizeHgcrocDigiCollection.cxx.
ldmxsw_event_
int dqm::NtuplizeHgcrocDigiCollection::ldmxsw_event_ private
Definition at line 12 of file NtuplizeHgcrocDigiCollection.cxx.
link_
int dqm::NtuplizeHgcrocDigiCollection::link_ private
Definition at line 14 of file NtuplizeHgcrocDigiCollection.cxx.
pedestal_table_
std::string dqm::NtuplizeHgcrocDigiCollection::pedestal_table_ private
Definition at line 11 of file NtuplizeHgcrocDigiCollection.cxx.
pf_event_
int dqm::NtuplizeHgcrocDigiCollection::pf_event_ private
Definition at line 12 of file NtuplizeHgcrocDigiCollection.cxx.
pf_spill_
int dqm::NtuplizeHgcrocDigiCollection::pf_spill_ private
Definition at line 12 of file NtuplizeHgcrocDigiCollection.cxx.
pf_ticks_
int dqm::NtuplizeHgcrocDigiCollection::pf_ticks_ private
Definition at line 12 of file NtuplizeHgcrocDigiCollection.cxx.
raw_adc_
int dqm::NtuplizeHgcrocDigiCollection::raw_adc_ private
Definition at line 13 of file NtuplizeHgcrocDigiCollection.cxx.
raw_id_
int dqm::NtuplizeHgcrocDigiCollection::raw_id_ private
Definition at line 13 of file NtuplizeHgcrocDigiCollection.cxx.
section_
int dqm::NtuplizeHgcrocDigiCollection::section_ private
Definition at line 15 of file NtuplizeHgcrocDigiCollection.cxx.
strip_
int dqm::NtuplizeHgcrocDigiCollection::strip_ private
Definition at line 15 of file NtuplizeHgcrocDigiCollection.cxx.
toa_
int dqm::NtuplizeHgcrocDigiCollection::toa_ private
Definition at line 13 of file NtuplizeHgcrocDigiCollection.cxx.
tot_
int dqm::NtuplizeHgcrocDigiCollection::tot_ private
Definition at line 13 of file NtuplizeHgcrocDigiCollection.cxx.
tot_comp_
bool dqm::NtuplizeHgcrocDigiCollection::tot_comp_ private
Definition at line 16 of file NtuplizeHgcrocDigiCollection.cxx.
tot_prog_
bool dqm::NtuplizeHgcrocDigiCollection::tot_prog_ private
Definition at line 16 of file NtuplizeHgcrocDigiCollection.cxx.
using_eid_
bool dqm::NtuplizeHgcrocDigiCollection::using_eid_ private
Definition at line 17 of file NtuplizeHgcrocDigiCollection.cxx.
version_
int dqm::NtuplizeHgcrocDigiCollection::version_ private
Definition at line 12 of file NtuplizeHgcrocDigiCollection.cxx.
The documentation for this class was generated from the following file:
DQM/src/DQM/NtuplizeHgcrocDigiCollection.cxx