LDMX Software: ldmx::HgcrocTriggerConditions Class Reference
ldmx::HgcrocTriggerConditions Class Reference
#include <HgcrocTriggerCalculations.h>
Public Member Functions
HgcrocTriggerConditions (const conditions::IntegerTableCondition &, bool validate=true)
int adcPedestal (unsigned int id) const
int adcThreshold (unsigned int id) const
int totPedestal (unsigned int id) const
int totThreshold (unsigned int id) const
int totGain (unsigned int id) const
Static Public Attributes
static const unsigned int IADC_PEDESTAL = 0
column index for ADC pedestal
static const unsigned int IADC_THRESHOLD = 1
column index for ADC threshold
static const unsigned int ITOT_PEDESTAL = 2
column index for TOT pedestal
static const unsigned int ITOT_THRESHOLD = 3
column index for TOT threshold
static const unsigned int ITOT_GAIN = 4
column index for TOT gain
Private Attributes
const conditions::IntegerTableCondition & ict_
reference to the table of conditions storing the chip conditions
Detailed Description
Class to wrap around an integer table of conditions.
This hardcodes the column numbers and checks that the hardcoded numbers match the imported columns during construction.
Definition at line 23 of file HgcrocTriggerCalculations.h.
Constructor & Destructor Documentation
HgcrocTriggerConditions()
ldmx::HgcrocTriggerConditions::HgcrocTriggerConditions (const conditions::IntegerTableCondition & ict, bool validate = true)
Constructor
Assign the conditions table to use and (if validate is true), check if the hard-coded column indices correctly match the table that is passed.
@raises Exception if any of the column names from the passed table do not match the hardcoded indices.
Definition at line 8 of file HgcrocTriggerCalculations.cxx.
    : ict_{ict} {
  if (!validate) return;
  if (ict_.getColumnCount() < 5) {
    EXCEPTION_RAISE(
        "ConditionsException",
        "Inconsistent condition for HgcrocTriggerConditions :" + ict.getName());
  }
  std::vector<std::string> expected_colnames;
  expected_colnames.push_back("ADC_PEDESTAL");
  expected_colnames.push_back("ADC_THRESHOLD");
  expected_colnames.push_back("TOT_PEDESTAL");
  expected_colnames.push_back("TOT_THRESHOLD");
  expected_colnames.push_back("TOT_GAIN");
  for (size_t i = 0; i < 5; i++) {
    if (ict_.getColumnNames()[i] != expected_colnames[i]) {
      EXCEPTION_RAISE("ConditionsException",
                      "Expected column '" + expected_colnames[i] + "', got '" +
                          ict_.getColumnNames()[i] + "'");
    }
  }
}
References conditions::BaseTableCondition::getColumnCount(), conditions::BaseTableCondition::getColumnNames(), framework::ConditionsObject::getName(), and ict_.
Member Function Documentation
adcPedestal()
int ldmx::HgcrocTriggerConditions::adcPedestal (unsigned int id) const inline
get the ADC pedestal
Parameters
[in] id raw ID for specific chip
Returns
the ADC pedestal for that chip
Definition at line 55 of file HgcrocTriggerCalculations.h.
{ return ict_.get(id, IADC_PEDESTAL); }
References conditions::HomogenousTableCondition< T >::get(), IADC_PEDESTAL, and ict_.
Referenced by ldmx::HgcrocTriggerCalculations::addDigi().
adcThreshold()
int ldmx::HgcrocTriggerConditions::adcThreshold (unsigned int id) const inline
get the ADC threshold
Parameters
[in] id raw ID for specific chip
Returns
the ADC threshold for that chip
Definition at line 63 of file HgcrocTriggerCalculations.h.
{
    return ict_.get(id, IADC_THRESHOLD);
  }
References conditions::HomogenousTableCondition< T >::get(), IADC_THRESHOLD, and ict_.
Referenced by ldmx::HgcrocTriggerCalculations::addDigi().
totGain()
int ldmx::HgcrocTriggerConditions::totGain (unsigned int id) const inline
get the TOT gain
Parameters
[in] id raw ID for specific chip
Returns
the TOT gain for that chip
Definition at line 91 of file HgcrocTriggerCalculations.h.
{ return ict_.get(id, ITOT_GAIN); }
References conditions::HomogenousTableCondition< T >::get(), ict_, and ITOT_GAIN.
Referenced by ldmx::HgcrocTriggerCalculations::addDigi().
totPedestal()
int ldmx::HgcrocTriggerConditions::totPedestal (unsigned int id) const inline
get the TOT pedestal
Parameters
[in] id raw ID for specific chip
Returns
the TOT pedestal for that chip
Definition at line 73 of file HgcrocTriggerCalculations.h.
{ return ict_.get(id, ITOT_PEDESTAL); }
References conditions::HomogenousTableCondition< T >::get(), ict_, and ITOT_PEDESTAL.
Referenced by ldmx::HgcrocTriggerCalculations::addDigi().
totThreshold()
int ldmx::HgcrocTriggerConditions::totThreshold (unsigned int id) const inline
get the TOT threshold
Parameters
[in] id raw ID for specific chip
Returns
the TOT threshold for that chip
Definition at line 81 of file HgcrocTriggerCalculations.h.
{
    return ict_.get(id, ITOT_THRESHOLD);
  }
References conditions::HomogenousTableCondition< T >::get(), ict_, and ITOT_THRESHOLD.
Referenced by ldmx::HgcrocTriggerCalculations::addDigi().
Member Data Documentation
IADC_PEDESTAL
const unsigned int ldmx::HgcrocTriggerConditions::IADC_PEDESTAL = 0 static
column index for ADC pedestal
Definition at line 26 of file HgcrocTriggerCalculations.h.
Referenced by adcPedestal().
IADC_THRESHOLD
const unsigned int ldmx::HgcrocTriggerConditions::IADC_THRESHOLD = 1 static
column index for ADC threshold
Definition at line 28 of file HgcrocTriggerCalculations.h.
Referenced by adcThreshold().
ict_
const conditions::IntegerTableCondition& ldmx::HgcrocTriggerConditions::ict_ private
reference to the table of conditions storing the chip conditions
Definition at line 95 of file HgcrocTriggerCalculations.h.
Referenced by adcPedestal(), adcThreshold(), HgcrocTriggerConditions(), totGain(), totPedestal(), and totThreshold().
ITOT_GAIN
const unsigned int ldmx::HgcrocTriggerConditions::ITOT_GAIN = 4 static
column index for TOT gain
Definition at line 34 of file HgcrocTriggerCalculations.h.
Referenced by totGain().
ITOT_PEDESTAL
const unsigned int ldmx::HgcrocTriggerConditions::ITOT_PEDESTAL = 2 static
column index for TOT pedestal
Definition at line 30 of file HgcrocTriggerCalculations.h.
Referenced by totPedestal().
ITOT_THRESHOLD
const unsigned int ldmx::HgcrocTriggerConditions::ITOT_THRESHOLD = 3 static
column index for TOT threshold
Definition at line 32 of file HgcrocTriggerCalculations.h.
Referenced by totThreshold().
The documentation for this class was generated from the following files:
Tools/include/Tools/HgcrocTriggerCalculations.h
Tools/src/Tools/HgcrocTriggerCalculations.cxx