LDMX Software: ldmx::CalorimeterHit Class Reference
ldmx::CalorimeterHit Class Reference
Represents a reconstructed hit in a calorimeter cell within the detector.
#include <CalorimeterHit.h>
Public Member Functions
CalorimeterHit ()
virtual ~CalorimeterHit ()
void Clear ()
void Print () const
int getID () const
void setID (int id)
float getAmplitude () const
void setAmplitude (float amplitude)
float getEnergy () const
void setEnergy (float energy)
float getTime () const
void setTime (float time)
float getXPos () const
void setXPos (float xpos)
float getYPos () const
void setYPos (float ypos)
float getZPos () const
void setZPos (float zpos)
bool isNoise () const
void setNoise (bool yes)
bool operator< (const CalorimeterHit &rhs) const
Private Member Functions
ClassDef (CalorimeterHit, 1)
Private Attributes
int id_ {0}
float amplitude_ {0}
float energy_ {0}
float time_ {0}
float xpos_
float ypos_
float zpos_
bool isNoise_
Detailed Description
Represents a reconstructed hit in a calorimeter cell within the detector.
Note
This class represents the reconstructed hit information from a calorimeter including detector ID, raw amplitude, corrected energy and time.
Definition at line 25 of file CalorimeterHit.h.
Constructor & Destructor Documentation
CalorimeterHit()
ldmx::CalorimeterHit::CalorimeterHit () inline
Class constructor.
Definition at line 30 of file CalorimeterHit.h.
{}
~CalorimeterHit()
virtual ldmx::CalorimeterHit::~CalorimeterHit () inline virtual
Class destructor.
Definition at line 35 of file CalorimeterHit.h.
{}
Member Function Documentation
ClassDef()
ldmx::CalorimeterHit::ClassDef (CalorimeterHit , 1) private
The ROOT class definition.
Clear()
void ldmx::CalorimeterHit::Clear ()
Clear the data in the object.
getAmplitude()
float ldmx::CalorimeterHit::getAmplitude () const inline
Get the amplitude of the hit, which is proportional to the signal in the calorimeter cell without sampling factor corrections. Units depend on the calorimeter.
Returns
The amplitude of the hit
Definition at line 65 of file CalorimeterHit.h.
{ return amplitude_; }
References amplitude_.
getEnergy()
float ldmx::CalorimeterHit::getEnergy () const inline
Get the calorimetric energy of the hit, corrected for sampling factors [MeV].
Returns
The energy of the hit
Definition at line 80 of file CalorimeterHit.h.
{ return energy_; }
References energy_.
Referenced by ecal::WorkingCluster::add(), trigscint::TrigScintClusterProducer::addHit(), trigscint::TestBeamClusterProducer::addHit(), and hcal::HcalWABVetoProcessor::produce().
getID()
int ldmx::CalorimeterHit::getID () const inline
Get the detector ID.
Returns
The detector ID.
Definition at line 51 of file CalorimeterHit.h.
{ return id_; }
References id_.
Referenced by ecal::WorkingCluster::add(), and eventdisplay::DetectorGeometry::getBoundingBox().
getTime()
float ldmx::CalorimeterHit::getTime () const inline
Get the time of the hit [ns].
Returns
The time of the hit
Definition at line 93 of file CalorimeterHit.h.
{ return time_; }
References time_.
Referenced by trigscint::TrigScintClusterProducer::addHit(), trigscint::TestBeamClusterProducer::addHit(), and operator<().
getXPos()
float ldmx::CalorimeterHit::getXPos () const inline
Get the X position of the hit [mm].
Returns
the x position of the hit
Definition at line 105 of file CalorimeterHit.h.
{ return xpos_; }
References xpos_.
Referenced by eventdisplay::DetectorGeometry::getBoundingBox().
getYPos()
float ldmx::CalorimeterHit::getYPos () const inline
Get the Y position of the hit [mm].
Returns
the y position of the hit
Definition at line 117 of file CalorimeterHit.h.
{ return ypos_; }
References ypos_.
Referenced by eventdisplay::DetectorGeometry::getBoundingBox().
getZPos()
float ldmx::CalorimeterHit::getZPos () const inline
Get the Z position of the hit [mm].
Returns
the z position of the hit
Definition at line 129 of file CalorimeterHit.h.
{ return zpos_; }
References zpos_.
isNoise()
bool ldmx::CalorimeterHit::isNoise () const inline
Is this hit a noise hit?
Returns
true if this hit is a noise hit
Definition at line 141 of file CalorimeterHit.h.
{ return isNoise_; }
References isNoise_.
operator<()
bool ldmx::CalorimeterHit::operator< (const CalorimeterHit & rhs) const inline
Sort by time of hit
Definition at line 152 of file CalorimeterHit.h.
{
    return this->getTime() < rhs.getTime();
  }
References getTime().
Print()
void ldmx::CalorimeterHit::Print () const
Print out the object.
setAmplitude()
void ldmx::CalorimeterHit::setAmplitude (float amplitude) inline
Set the amplitude of the hit, which is proportional to the signal in the calorimeter cell without sampling factor corrections. Units depend on the calorimeter.
Parameters
amplitude The amplitude of the hit
Definition at line 73 of file CalorimeterHit.h.
{ amplitude_ = amplitude; }
References amplitude_.
Referenced by ecal::EcalRecProducer::produce(), trigscint::TestBeamHitProducer::produce(), trigscint::TrigScintDigiProducer::produce(), trigscint::TrigScintRecHitProducer::produce(), hcal::HcalRecProducer::produce(), hcal::HcalDoubleEndRecProducer::produce(), and hcal::HcalSingleEndRecProducer::produce().
setEnergy()
void ldmx::CalorimeterHit::setEnergy (float energy) inline
Set the calorimetric energy of the hit, corrected for sampling factors [MeV].
Parameters
energy The energy of the hit
Definition at line 87 of file CalorimeterHit.h.
{ energy_ = energy; }
References energy_.
Referenced by ecal::EcalRecProducer::produce(), trigscint::TestBeamHitProducer::produce(), trigscint::TrigScintDigiProducer::produce(), trigscint::TrigScintRecHitProducer::produce(), hcal::HcalRecProducer::produce(), hcal::HcalDoubleEndRecProducer::produce(), and hcal::HcalSingleEndRecProducer::produce().
setID()
void ldmx::CalorimeterHit::setID (int id) inline
Set the detector ID. @id The detector ID.
Definition at line 57 of file CalorimeterHit.h.
{ id_ = id; }
References id_.
Referenced by ecal::EcalRecProducer::produce(), trigscint::TrigScintDigiProducer::produce(), framework::test::TestProducer::produce(), hcal::HcalRecProducer::produce(), hcal::HcalDoubleEndRecProducer::produce(), and hcal::HcalSingleEndRecProducer::produce().
setNoise()
void ldmx::CalorimeterHit::setNoise (bool yes) inline
Set if this hit is a noise hit.
Parameters
yes true if this hit is a noise hit
Definition at line 147 of file CalorimeterHit.h.
{ isNoise_ = yes; }
References isNoise_.
Referenced by trigscint::TrigScintDigiProducer::produce().
setTime()
void ldmx::CalorimeterHit::setTime (float time) inline
Set the time of the hit [ns].
Parameters
time The time of the hit
Definition at line 99 of file CalorimeterHit.h.
{ time_ = time; }
References time_.
Referenced by ecal::EcalRecProducer::produce(), trigscint::TestBeamHitProducer::produce(), trigscint::TrigScintDigiProducer::produce(), trigscint::TrigScintRecHitProducer::produce(), hcal::HcalRecProducer::produce(), hcal::HcalDoubleEndRecProducer::produce(), and hcal::HcalSingleEndRecProducer::produce().
setXPos()
void ldmx::CalorimeterHit::setXPos (float xpos) inline
Set the X position of the hit [mm].
Parameters
xpos the x position of the hit
Definition at line 111 of file CalorimeterHit.h.
{ xpos_ = xpos; }
References xpos_.
Referenced by ecal::EcalRecProducer::produce(), trigscint::TrigScintDigiProducer::produce(), hcal::HcalRecProducer::produce(), hcal::HcalDoubleEndRecProducer::produce(), and hcal::HcalSingleEndRecProducer::produce().
setYPos()
void ldmx::CalorimeterHit::setYPos (float ypos) inline
Set the Y position of the hit [mm].
Parameters
ypos the y position of the hit
Definition at line 123 of file CalorimeterHit.h.
{ ypos_ = ypos; }
References ypos_.
Referenced by ecal::EcalRecProducer::produce(), trigscint::TrigScintDigiProducer::produce(), hcal::HcalRecProducer::produce(), hcal::HcalDoubleEndRecProducer::produce(), and hcal::HcalSingleEndRecProducer::produce().
setZPos()
void ldmx::CalorimeterHit::setZPos (float zpos) inline
Set the Z position of the hit [mm].
Parameters
zpos the z position of the hit
Definition at line 135 of file CalorimeterHit.h.
{ zpos_ = zpos; }
References zpos_.
Referenced by ecal::EcalRecProducer::produce(), trigscint::TrigScintDigiProducer::produce(), hcal::HcalRecProducer::produce(), hcal::HcalDoubleEndRecProducer::produce(), and hcal::HcalSingleEndRecProducer::produce().
Member Data Documentation
amplitude_
float ldmx::CalorimeterHit::amplitude_ {0} private
The amplitude value before sampling corrections.
Definition at line 161 of file CalorimeterHit.h.
Referenced by getAmplitude(), and setAmplitude().
energy_
float ldmx::CalorimeterHit::energy_ {0} private
The energy of the hit corrected by a sampling fraction.
Definition at line 164 of file CalorimeterHit.h.
Referenced by getEnergy(), and setEnergy().
id_
int ldmx::CalorimeterHit::id_ {0} private
The detector ID of the hit.
Definition at line 158 of file CalorimeterHit.h.
Referenced by getID(), and setID().
isNoise_
bool ldmx::CalorimeterHit::isNoise_ private
Is this a noise hit?
Definition at line 179 of file CalorimeterHit.h.
Referenced by isNoise(), and setNoise().
time_
float ldmx::CalorimeterHit::time_ {0} private
The time of the hit.
Definition at line 167 of file CalorimeterHit.h.
Referenced by getTime(), and setTime().
xpos_
float ldmx::CalorimeterHit::xpos_ private
X Position of the hit
Definition at line 170 of file CalorimeterHit.h.
Referenced by getXPos(), and setXPos().
ypos_
float ldmx::CalorimeterHit::ypos_ private
Y Position of the hit
Definition at line 173 of file CalorimeterHit.h.
Referenced by getYPos(), and setYPos().
zpos_
float ldmx::CalorimeterHit::zpos_ private
Z Position of the hit
Definition at line 176 of file CalorimeterHit.h.
Referenced by getZPos(), and setZPos().
The documentation for this class was generated from the following file:
Recon/include/Recon/Event/CalorimeterHit.h