LDMX Software: simcore::APrimePhysics Class Reference
simcore::APrimePhysics Class Reference
Defines basic APrime physics.
#include <APrimePhysics.h>
Public Member Functions
APrimePhysics (const framework::config::Parameters &params)
virtual ~APrimePhysics ()
void ConstructParticle ()
void ConstructProcess ()
Static Public Attributes
static const std::string NAME = "APrime"
Private Attributes
G4double ap_mass_
the mass of the A' for this run
bool enable_
is dark brem enabled for this run?
framework::config::Parameters parameters_
Detailed Description
Defines basic APrime physics.
It constructs the APrime particle and links the dark brem process to the electron.
See also
G4APrime
G4DarkBremsstrahlung in G4DarkBreM
Note
This class basically does not do anything except register the custom particle (G4APrime) and custom process (G4DarkBremsstrahlung).
Definition at line 35 of file APrimePhysics.h.
Constructor & Destructor Documentation
APrimePhysics()
simcore::APrimePhysics::APrimePhysics (const framework::config::Parameters & params)
Class constructor.
Parameters
params Parameters to configure the dark brem process
Definition at line 21 of file APrimePhysics.cxx.
    : G4VPhysicsConstructor(APrimePhysics::NAME), parameters_{params} {
  ap_mass_ = parameters_.getParameter<double>("ap_mass", 0.) * MeV;
  enable_ = parameters_.getParameter<bool>("enable", false);
}
References ap_mass_, enable_, framework::config::Parameters::getParameter(), and parameters_.
~APrimePhysics()
virtual simcore::APrimePhysics::~APrimePhysics () inline virtual
Class destructor.
Nothing right now.
Definition at line 58 of file APrimePhysics.h.
{}
Member Function Documentation
ConstructParticle()
void simcore::APrimePhysics::ConstructParticle ()
Construct particle.
Insert A' into the Geant4 particle table. Geant4 registers all instances derived from G4ParticleDefinition and deletes them at the end of processing.
Uses the A' mass given by the parameter APrimeMass to inform the G4APrime instance what mass to use.
See also
G4APrime
Insert A-prime into the Geant4 particle table. For now we flag it as stable.
Geant4 registers all instances derived from G4ParticleDefinition and deletes them at the end of the run. We configure the A' to have the input mass and the PDG ID number of 622.
Definition at line 27 of file APrimePhysics.cxx.
{
  G4APrime::Initialize(ap_mass_, 622);
}
References ap_mass_, and G4APrime::Initialize().
ConstructProcess()
void simcore::APrimePhysics::ConstructProcess ()
Construct the process.
Links the dark brem processs to the electron through the process manager only if the dark brem process is enabled ('enable' is True).
G4ProcessManager registers and cleans up any created processes, so we can forget about it after creating it.
See also
G4DarkBremsstrahlung in G4DarkBreM
Definition at line 39 of file APrimePhysics.cxx.
{
  // add process to electron if we are enabled
  if (enable_) {
    auto model{parameters_.getParameter<framework::config::Parameters>("model")};
    auto model_name{model.getParameter<std::string>("name")};
    if (model_name == "vertex_library" or model_name == "g4db") {
      static const std::map<std::string,g4db::G4DarkBreMModel::ScalingMethod> method_lut = {
        { "forward_only", g4db::G4DarkBreMModel::ScalingMethod::ForwardOnly },
        { "cm_scaling"  , g4db::G4DarkBreMModel::ScalingMethod::CMScaling },
        { "undefined"   , g4db::G4DarkBreMModel::ScalingMethod::Undefined }
      };
      auto scaling_method_it{method_lut.find(model.getParameter<std::string>("method"))};
      if (scaling_method_it == method_lut.end()) {
        EXCEPTION_RAISE("BadConf","Unrecognized scaling method '"+
            model.getParameter<std::string>("method") + "',"
            " options are 'forward_only', 'cm_scaling', or 'undefined'.");
      }
      auto proc = new G4DarkBremsstrahlung(
        std::make_shared<g4db::G4DarkBreMModel>(
              model.getParameter<std::string>("library_path"),
              false /* dark brem off muons instead of electrons - we always DB off electrons here */,
              model.getParameter<double>("threshold"),
              model.getParameter<double>("epsilon"),
              scaling_method_it->second),
          parameters_.getParameter<bool>("only_one_per_event"),
          1., /* global bias - should use bias operator instead */
          parameters_.getParameter<bool>("cache_xsec"));
    } else {
      EXCEPTION_RAISE("BadConf",
          "Unrecognized model name '"+model_name+"'.");
    }
    G4cout << "[ APrimePhysics ] : Initialization of dark brem complete" << G4endl;
  }
}
References g4db::G4DarkBreMModel::CMScaling, enable_, g4db::G4DarkBreMModel::ForwardOnly, framework::config::Parameters::getParameter(), parameters_, and g4db::G4DarkBreMModel::Undefined.
Member Data Documentation
ap_mass_
G4double simcore::APrimePhysics::ap_mass_ private
the mass of the A' for this run
Definition at line 89 of file APrimePhysics.h.
Referenced by APrimePhysics(), and ConstructParticle().
enable_
bool simcore::APrimePhysics::enable_ private
is dark brem enabled for this run?
Definition at line 92 of file APrimePhysics.h.
Referenced by APrimePhysics(), and ConstructProcess().
NAME
const std::string simcore::APrimePhysics::NAME = "APrime" static
The name of this physics constructor.
Passed into Geant4 to register this physics, should not conflict with any other Geant4 physics.
Definition at line 44 of file APrimePhysics.h.
parameters_
framework::config::Parameters simcore::APrimePhysics::parameters_ private
Dark brem parameters to pass to the process (if enabled)
Note
This can't be a reference because we pass it to the process after the configuration step from our POV is done. Thus we need our own copy that won't be destroyed.
Definition at line 101 of file APrimePhysics.h.
Referenced by APrimePhysics(), and ConstructProcess().
The documentation for this class was generated from the following files:
SimCore/include/SimCore/APrimePhysics.h
SimCore/src/SimCore/APrimePhysics.cxx