LDMX Software: ldmx::TrackerVetoResult Class Reference
ldmx::TrackerVetoResult Class Reference
Public Member Functions
TrackerVetoResult ()
~TrackerVetoResult ()
void Clear ()
void Print () const
bool passesVeto () const
void setVetoResult (const bool &passesVeto=true)
Private Member Functions
ClassDef (TrackerVetoResult, 1)
Private Attributes
bool passesVeto_ {false}
Detailed Description
Definition at line 18 of file TrackerVetoResult.h.
Constructor & Destructor Documentation
TrackerVetoResult()
ldmx::TrackerVetoResult::TrackerVetoResult ()
Constructor
~TrackerVetoResult()
ldmx::TrackerVetoResult::~TrackerVetoResult ()
Destructor
Member Function Documentation
Clear()
void ldmx::TrackerVetoResult::Clear ()
Reset the object.
passesVeto()
bool ldmx::TrackerVetoResult::passesVeto () const inline
Checks if the event passes the Hcal veto.
Definition at line 35 of file TrackerVetoResult.h.
 { return passesVeto_; };
References passesVeto_.
Referenced by ldmx::RecoilTrackerDQM::analyze(), and setVetoResult().
Print()
void ldmx::TrackerVetoResult::Print () const
Print out the object
setVetoResult()
void ldmx::TrackerVetoResult::setVetoResult (const bool & passesVeto = true) inline
Sets whether the Hcal veto was passed or not.
Parameters
passesVeto Veto result.
Definition at line 42 of file TrackerVetoResult.h.
{
                 passesVeto_ = passesVeto;
             }
References passesVeto(), and passesVeto_.
Referenced by ldmx::TrackerVetoProcessor::produce().
Member Data Documentation
passesVeto_
bool ldmx::TrackerVetoResult::passesVeto_ {false} private
Flag indicating whether the event passes the Hcal veto.
Definition at line 49 of file TrackerVetoResult.h.
Referenced by passesVeto(), and setVetoResult().
The documentation for this class was generated from the following file:
Event/include/Event/TrackerVetoResult.h