LDMX Software: ldmx::EcalGeometryProvider Class Reference
ldmx::EcalGeometryProvider Class Reference
Public Member Functions
EcalGeometryProvider (const std::string &name, const std::string &tagname, const Parameters &parameters, Process &process)
virtual ~EcalGeometryProvider ()
virtual std::pair< const ConditionsObject *, ConditionsIOV > getCondition (const EventHeader &context)
virtual void releaseConditionsObject (const ConditionsObject *co)
virtual void onNewRun (RunHeader &rh)
Public Member Functions inherited from ldmx::ConditionsObjectProvider
ConditionsObjectProvider (const std::string &objname, const std::string &tagname, const Parameters &parameters, Process &process)
virtual ~ConditionsObjectProvider ()
virtual void onProcessStart ()
virtual void onProcessEnd ()
const std::string & getConditionObjectName () const
const std::string & getTagName () const
Private Attributes
Parameters params_
std::string detectorGeometry_
EcalHexReadout * ecalGeometry_
Additional Inherited Members
Static Public Member Functions inherited from ldmx::ConditionsObjectProvider
static void declare (const std::string &classname, ConditionsObjectProviderMaker *)
Static Public Attributes inherited from ldmx::ConditionsObjectProvider
static const int CLASSTYPE {10}
Protected Member Functions inherited from ldmx::ConditionsObjectProvider
std::pair< const ConditionsObject *, ConditionsIOV > requestParentCondition (const std::string &name, const EventHeader &context)
const Process & process () const
Protected Attributes inherited from ldmx::ConditionsObjectProvider
logging::logger theLog_
The logger for this ConditionsObjectProvider.
Detailed Description
Definition at line 16 of file EcalGeometryProvider.cxx.
Constructor & Destructor Documentation
EcalGeometryProvider()
ldmx::EcalGeometryProvider::EcalGeometryProvider (const std::string & name, const std::string & tagname, const Parameters & parameters, Process & process)
Class constructor
Parameters
parameters – uses the "EcalHexReadout" section to configure the EcalHexReadout
Definition at line 61 of file EcalGeometryProvider.cxx.
                                                                                                                                           : ConditionsObjectProvider{EcalHexReadout::CONDITIONS_OBJECT_NAME,tagname,parameters,process}, params_{parameters} {
   ecalGeometry_=0;
 }
References ldmx::ConditionsObjectProvider::process().
~EcalGeometryProvider()
ldmx::EcalGeometryProvider::~EcalGeometryProvider () virtual
Destructor
Definition at line 66 of file EcalGeometryProvider.cxx.
{
   if (ecalGeometry_) delete ecalGeometry_;
   ecalGeometry_=0;
 }
Member Function Documentation
getCondition()
std::pair< const ConditionsObject *, ConditionsIOV > ldmx::EcalGeometryProvider::getCondition (const EventHeader & context) virtual
Provides access to the EcalHexReadout or EcalTriggerGeometry
Note
Currently, these are assumed to be valid for all time, but this behavior could be changed. Users should not cache the pointer between events
Implements ldmx::ConditionsObjectProvider.
Definition at line 71 of file EcalGeometryProvider.cxx.
{
   static const std::string KEYNAME("detectors_valid");
   if (!ecalGeometry_) {
     Parameters phex=(params_.exists("EcalHexReadout"))?(params_.getParameter<Parameters>("EcalHexReadout")):(params_);
     // search through the subtrees
     for (auto key: phex.keys()) {
       Parameters pver=phex.getParameter<Parameters>(key);
       if (!pver.exists(KEYNAME)) {
         ldmx_log(warn) << "No parameter " << KEYNAME << " found in " << key;
         // log strange situation and continue
         continue;
       }
      std::vector<std::string> dets_valid=pver.getParameter<std::vector<std::string> >(KEYNAME);
       for (auto detregex : dets_valid) {
         std::string regex(detregex);
         if (regex.empty()) continue; // no empty regex allowed
         if (regex[0]!='^') regex.insert(0,1,'^');
         if (regex.back()!='$') regex+='$';
         regex_t reg;
         int rv=regcomp(&reg,regex.c_str(),REG_EXTENDED|REG_ICASE|REG_NOSUB);
         if (rv) {
           char err[1024];
           regerror(rv,&reg,err,1024);
           EXCEPTION_RAISE("GeometryException","Invalid detector regular expression : '"+regex+"' "
                           +err);
         }
         int nmatch=regexec(&reg,detectorGeometry_.c_str(),0,0,0);
         regfree(&reg);
         if (!nmatch) {
           ecalGeometry_=new EcalHexReadout(pver);
           break;
         }
       }
       if (ecalGeometry_) break;
     }
     if (!ecalGeometry_) {
       EXCEPTION_RAISE("GeometryException","Unable to create EcalHexReadout");
     }
   }
   return std::make_pair(ecalGeometry_,ConditionsIOV(context.getRun(),context.getRun(),true,true));
 }
References detectorGeometry_, ldmx::Parameters::exists(), ldmx::Parameters::getParameter(), ldmx::EventHeader::getRun(), ldmx::Parameters::keys(), and params_.
onNewRun()
virtual void ldmx::EcalGeometryProvider::onNewRun (RunHeader &) inline virtual
Callback for the ConditionsObjectProvider to take any necessary action when the processing of events starts for a given run.
Reimplemented from ldmx::ConditionsObjectProvider.
Definition at line 41 of file EcalGeometryProvider.cxx.
{
     if (detectorGeometry_.empty()) detectorGeometry_=rh.getDetectorName();
     else if (ecalGeometry_!=nullptr && detectorGeometry_!=rh.getDetectorName()) {
       EXCEPTION_RAISE("GeometryException","Attempting to run a single job with multiple geometries "+detectorGeometry_+" and '"+rh.getDetectorName()+"'");
     }
     //make sure detector name has been set
     if (detectorGeometry_.empty())
         EXCEPTION_RAISE("GeometryException","EcalGeometryProvider unable to get the name of the detector from the RunHeader.");
   }
References detectorGeometry_, and ldmx::RunHeader::getDetectorName().
releaseConditionsObject()
virtual void ldmx::EcalGeometryProvider::releaseConditionsObject (const ConditionsObject * co) inline virtual
Take no action on release, as the object is permanently owned by the Provider
Reimplemented from ldmx::ConditionsObjectProvider.
Definition at line 38 of file EcalGeometryProvider.cxx.
{
   }
Member Data Documentation
detectorGeometry_
std::string ldmx::EcalGeometryProvider::detectorGeometry_ private
Geometry as last used
Definition at line 56 of file EcalGeometryProvider.cxx.
Referenced by getCondition(), and onNewRun().
params_
Parameters ldmx::EcalGeometryProvider::params_ private
Handle to the parameters, needed for future use during get condition
Definition at line 54 of file EcalGeometryProvider.cxx.
Referenced by getCondition().
The documentation for this class was generated from the following file:
Ecal/src/EcalGeometryProvider.cxx