LDMX Software: hcal::HcalWABVetoProcessor Class Reference
hcal::HcalWABVetoProcessor Class Reference
Public Member Functions
HcalWABVetoProcessor (const std::string &name, framework::Process &process)
~HcalWABVetoProcessor ()
void configure (framework::config::Parameters &parameters) final override
void produce (framework::Event &event)
Public Member Functions inherited from framework::Producer
Producer (const std::string &name, Process &process)
virtual void produce (Event &event)=0
virtual void beforeNewRun (ldmx::RunHeader &header)
Public Member Functions inherited from framework::EventProcessor
EventProcessor (const std::string &name, Process &process)
virtual ~EventProcessor ()
virtual void configure (framework::config::Parameters &parameters)
virtual void onNewRun (const ldmx::RunHeader &runHeader)
virtual void onFileOpen (EventFile &eventFile)
virtual void onFileClose (EventFile &eventFile)
virtual void onProcessStart ()
virtual void onProcessEnd ()
template<class T >
const T & getCondition (const std::string &condition_name)
TDirectory * getHistoDirectory ()
void setStorageHint (framework::StorageControlHint hint)
void setStorageHint (framework::StorageControlHint hint, const std::string &purposeString)
int getLogFrequency () const
int getRunNumber () const
std::string getName () const
void createHistograms (const std::vector< framework::config::Parameters > &histos)
Private Attributes
double maxtotalEnergyCompare_ {1000.}
double mintotalEnergyCompare_ {0.}
double maxnClusters_ {0.}
double maxMeanHitsPerCluster_ {0.}
double maxMeanEnergyPerCluster_ {0.}
std::string outputCollName_
std::string inputHCALClusterCollName_
std::string inputHCALHitCollName_
std::string inputECALHitCollName_
Additional Inherited Members
Static Public Member Functions inherited from framework::EventProcessor
static void declare (const std::string &classname, int classtype, EventProcessorMaker *)
Static Public Attributes inherited from framework::Producer
static const int CLASSTYPE {1}
Protected Member Functions inherited from framework::EventProcessor
void abortEvent ()
Protected Attributes inherited from framework::EventProcessor
HistogramHelper histograms_
Interface class for making and filling histograms.
NtupleManager & ntuple_ {NtupleManager::getInstance()}
Manager for any ntuples.
logging::logger theLog_
The logger for this EventProcessor.
Detailed Description
Definition at line 27 of file HcalWABVetoProcessor.h.
Constructor & Destructor Documentation
HcalWABVetoProcessor()
hcal::HcalWABVetoProcessor::HcalWABVetoProcessor (const std::string & name, framework::Process & process)
Constructor
Definition at line 18 of file HcalWABVetoProcessor.cxx.
    : Producer(name, process) {}
~HcalWABVetoProcessor()
hcal::HcalWABVetoProcessor::~HcalWABVetoProcessor ()
Destructor
Definition at line 22 of file HcalWABVetoProcessor.cxx.
{}
Member Function Documentation
configure()
void hcal::HcalWABVetoProcessor::configure (framework::config::Parameters & parameters) final override virtual
Configure the processor using the given user specified parameters.
Parameters
parameters Set of parameters used to configure this processor.
Reimplemented from framework::EventProcessor.
Definition at line 24 of file HcalWABVetoProcessor.cxx.
{
  maxtotalEnergyCompare_ =
      parameters.getParameter<double>("max_total_energy_compare");
  mintotalEnergyCompare_ =
      parameters.getParameter<double>("min_total_energy_compare");
  maxnClusters_ = parameters.getParameter<double>("n_clusters");
  maxMeanHitsPerCluster_ =
      parameters.getParameter<double>("mean_hits_per_cluster");
  maxMeanEnergyPerCluster_ =
      parameters.getParameter<double>("mean_energy_per_cluster");
  outputCollName_ = parameters.getParameter<std::string>("outputCollName");
  inputHCALClusterCollName_ =
      parameters.getParameter<std::string>("inputHCALClusterCollName");
  inputHCALHitCollName_ =
      parameters.getParameter<std::string>("inputHCALHitCollName");
  inputECALHitCollName_ =
      parameters.getParameter<std::string>("inputECALHitCollName");
}
References framework::config::Parameters::getParameter().
produce()
void hcal::HcalWABVetoProcessor::produce (framework::Event & event) virtual
Run the processor and create a collection of results which indicate if the event passes/fails the Hcal veto.
Parameters
event The event to process.
Implements framework::Producer.
Definition at line 44 of file HcalWABVetoProcessor.cxx.
{
  // Get the collection of sim particles from the event
  // HCAL:
  const std::vector<ldmx::HcalHit> hcalRecHits =
      event.getCollection<ldmx::HcalHit>(inputHCALHitCollName_);
  // ECAL:
  const std::vector<ldmx::EcalHit> ecalRecHits =
      event.getCollection<ldmx::EcalHit>(inputECALHitCollName_);
  // Clusters:
  const std::vector<ldmx::HcalCluster> hcalClusters =
      event.getCollection<ldmx::HcalCluster>(inputHCALClusterCollName_);
  // Loop over all of the Hcal hits and calculate to total photoelectrons
  // in the event.
  float totalHCALEnergy{0};
  float totalECALEnergy{0};
  float maxPE{-1000};
  const ldmx::HcalHit *maxPEHit;
  for (const ldmx::HcalHit &hcalHit : hcalRecHits) {
    if (hcalHit.isNoise() == 0) {
      totalHCALEnergy += hcalHit.getPE();
    }
    // Find the maximum PE in the list
    if (maxPE < hcalHit.getPE()) {
      maxPE = hcalHit.getPE();
      maxPEHit = &hcalHit;
    }
  }
  for (const ldmx::EcalHit &ecalHit : ecalRecHits) {
    if (ecalHit.isNoise() == 0) {
      totalECALEnergy += ecalHit.getEnergy();
    }
  }
  std::vector<double> nhits;
  std::vector<double> energies;
  unsigned int nClusters = 0;
  for (const ldmx::HcalCluster &hcalCluster : hcalClusters) {
    nClusters += 1;
    energies.push_back(hcalCluster.getEnergy());
    nhits.push_back(hcalCluster.getNHits());
  }
  double meanEnergy =
      std::accumulate(energies.begin(), energies.end(), 0.0) / energies.size();
  double meanNhits =
      std::accumulate(nhits.begin(), nhits.end(), 0.0) / nhits.size();
  bool passesEnergyCombo =
      (((totalECALEnergy + totalHCALEnergy) < maxtotalEnergyCompare_));
  bool passesnClusters = (nClusters < maxnClusters_);
  bool passesNHits = ((meanNhits < maxMeanHitsPerCluster_) or isnan(meanNhits));
  bool passesEnergy =
      ((meanEnergy < maxMeanEnergyPerCluster_) or isnan(meanEnergy));
  // total veto:
  bool passesVeto =
      (passesEnergyCombo and passesnClusters and passesNHits and passesEnergy);
  // set result:
  ldmx::HcalVetoResult result;
  result.setVetoResult(passesVeto);
  result.setMaxPEHit(*maxPEHit);
  if (passesVeto) {
    setStorageHint(framework::hint_shouldKeep);
  } else {
    setStorageHint(framework::hint_shouldDrop);
  }
  event.add(outputCollName_, result);
}
References ldmx::CalorimeterHit::getEnergy(), ldmx::HcalHit::getPE(), ldmx::HcalVetoResult::setMaxPEHit(), framework::EventProcessor::setStorageHint(), and ldmx::HcalVetoResult::setVetoResult().
Member Data Documentation
inputECALHitCollName_
std::string hcal::HcalWABVetoProcessor::inputECALHitCollName_ private
Definition at line 64 of file HcalWABVetoProcessor.h.
inputHCALClusterCollName_
std::string hcal::HcalWABVetoProcessor::inputHCALClusterCollName_ private
Definition at line 62 of file HcalWABVetoProcessor.h.
inputHCALHitCollName_
std::string hcal::HcalWABVetoProcessor::inputHCALHitCollName_ private
Definition at line 63 of file HcalWABVetoProcessor.h.
maxMeanEnergyPerCluster_
double hcal::HcalWABVetoProcessor::maxMeanEnergyPerCluster_ {0.} private
Definition at line 60 of file HcalWABVetoProcessor.h.
maxMeanHitsPerCluster_
double hcal::HcalWABVetoProcessor::maxMeanHitsPerCluster_ {0.} private
Definition at line 58 of file HcalWABVetoProcessor.h.
maxnClusters_
double hcal::HcalWABVetoProcessor::maxnClusters_ {0.} private
Definition at line 56 of file HcalWABVetoProcessor.h.
maxtotalEnergyCompare_
double hcal::HcalWABVetoProcessor::maxtotalEnergyCompare_ {1000.} private
Definition at line 52 of file HcalWABVetoProcessor.h.
mintotalEnergyCompare_
double hcal::HcalWABVetoProcessor::mintotalEnergyCompare_ {0.} private
Definition at line 54 of file HcalWABVetoProcessor.h.
outputCollName_
std::string hcal::HcalWABVetoProcessor::outputCollName_ private
Definition at line 61 of file HcalWABVetoProcessor.h.
The documentation for this class was generated from the following files:
Hcal/include/Hcal/HcalWABVetoProcessor.h
Hcal/src/Hcal/HcalWABVetoProcessor.cxx