LDMX Software: packing::rawdatafile::SubsystemPacket Class Reference
packing::rawdatafile::SubsystemPacket Class Reference
#include <SubsystemPacket.h>
Public Member Functions
SubsystemPacket ()=default
default constructor for reading
SubsystemPacket (uint32_t event, uint16_t id, std::vector< uint32_t > data)
constructor for writing
std::vector< uint32_t > header () const
std::vector< uint32_t > & data ()
const uint16_t & id () const
std::vector< uint32_t > tail () const
utility::Reader & read (utility::Reader &r)
utility::Writer & write (utility::Writer &w) const
utility::CRC & add (utility::CRC &c) const
Private Attributes
uint32_t event_
uint16_t id_
std::vector< uint32_t > data_
bool crc_ok_
unsigned int crc_
Detailed Description
SubsystemPacket structure
Definition at line 16 of file SubsystemPacket.h.
Constructor & Destructor Documentation
SubsystemPacket()
packing::rawdatafile::SubsystemPacket::SubsystemPacket (uint32_t event, uint16_t id, std::vector< uint32_t > data)
constructor for writing
Definition at line 9 of file SubsystemPacket.cxx.
                                                                                      : event_{event}, id_{id}, data_{data} {
  crc_ok_ = true;
  utility::CRC crc;
  crc << data_;
  crc_ = crc.get();
}
References packing::utility::CRC::get().
Member Function Documentation
add()
utility::CRC & packing::rawdatafile::SubsystemPacket::add (utility::CRC & c) const
add the subsystem packet to the input crc
Definition at line 52 of file SubsystemPacket.cxx.
{
  std::vector<uint32_t> head{header()}, t{tail()};
  c << head << data_ << t;
  return c;
}
References header(), and tail().
data()
std::vector< uint32_t > & packing::rawdatafile::SubsystemPacket::data () inline
Get data
Definition at line 32 of file SubsystemPacket.h.
{
    return data_;
  }
header()
std::vector< uint32_t > packing::rawdatafile::SubsystemPacket::header () const
get the header words
Definition at line 18 of file SubsystemPacket.cxx.
{
  uint32_t word = ((id_ & utility::mask<16>) << 16)
        +((data_.size() & utility::mask<15>) << 1)
        +crc_ok_;
  return { word, event_ };
}
Referenced by add(), and write().
id()
const uint16_t & packing::rawdatafile::SubsystemPacket::id () const inline
Definition at line 35 of file SubsystemPacket.h.
{ return id_; }
read()
utility::Reader & packing::rawdatafile::SubsystemPacket::read (utility::Reader & r)
read the subsystem packet from the input reader
Definition at line 29 of file SubsystemPacket.cxx.
{
  uint32_t word;
  r >> word;
  id_ = (word >> 16) & utility::mask<16>;
  uint32_t len = (word >> 1) & utility::mask<15>;
  crc_ok_ = word & utility::mask<1>;
  r >> event_;
  r.read(data_, len);
  r >> crc_;
  return r;
}
References packing::utility::Reader::read().
tail()
std::vector< uint32_t > packing::rawdatafile::SubsystemPacket::tail () const
get the tailing words
Definition at line 25 of file SubsystemPacket.cxx.
{
  return { crc_ };
}
Referenced by add(), and write().
write()
utility::Writer & packing::rawdatafile::SubsystemPacket::write (utility::Writer & w) const
write the subsystem packet to the input writer
Definition at line 46 of file SubsystemPacket.cxx.
{
  std::vector<uint32_t> head{header()}, t{tail()};
  w << head << data_ << t;
  return w;
}
References header(), and tail().
Member Data Documentation
crc_
unsigned int packing::rawdatafile::SubsystemPacket::crc_ private
Definition at line 61 of file SubsystemPacket.h.
crc_ok_
bool packing::rawdatafile::SubsystemPacket::crc_ok_ private
Definition at line 60 of file SubsystemPacket.h.
data_
std::vector<uint32_t> packing::rawdatafile::SubsystemPacket::data_ private
Definition at line 59 of file SubsystemPacket.h.
event_
uint32_t packing::rawdatafile::SubsystemPacket::event_ private
Definition at line 57 of file SubsystemPacket.h.
id_
uint16_t packing::rawdatafile::SubsystemPacket::id_ private
Definition at line 58 of file SubsystemPacket.h.
The documentation for this class was generated from the following files:
Packing/include/Packing/RawDataFile/SubsystemPacket.h
Packing/src/Packing/RawDataFile/SubsystemPacket.cxx