LDMX Software: trigscint::QIEStream Class Reference
trigscint::QIEStream Class Reference
class for storing QIE output as a binary stream
#include <QIEStream.h>
Public Member Functions
QIEStream ()=default
Default constructor.
~QIEStream ()=default
Default destructor.
void Print (Option_t *option="") const
void Clear (Option_t *option="")
bool operator< (const QIEStream &rhs) const
int getChannelID () const
uint8_t getElectronicsID () const
std::vector< int > getADC () const
std::vector< int > getTDC () const
std::vector< int > getCID () const
void setChannelID (const int chanid)
void setElectronicsID (const int elecid)
void setADC (const std::vector< int > adc)
void setTDC (const std::vector< int > tdc)
void setCID (const std::vector< int > cid)
Static Public Attributes
static const int TRIGID_POS {0}
static const int ERROR_POS {1}
static const int CHECKSUM_POS {2}
static const int FLAG_SIZE {1}
static const int CRC0_ERR_POS {0}
static const int CRC1_ERR_POS {1}
static const int CID_UNSYNC_POS {2}
static const int CID_SKIP_POS {3}
static const int NUM_SAMPLES {5}
Private Member Functions
ClassDef (QIEStream, 1)
Private Attributes
int chanID_
detector channel ID (bar nb)
int electronicsID_
electronics ID
std::vector< int > adcs_
Analog to Digital counts.
std::vector< int > tdcs_
Time to Digital counts.
std::vector< int > cids_
Capacitor IDs.
Detailed Description
class for storing QIE output as a binary stream
Definition at line 26 of file QIEStream.h.
Member Function Documentation
Clear()
void trigscint::QIEStream::Clear (Option_t * option = "")
A dummy function
Note
required by Event/include/Event/EventDef.h
getADC()
std::vector< int > trigscint::QIEStream::getADC () const inline
Get ADCs of all time samples
Definition at line 68 of file QIEStream.h.
{ return adcs_; }
References adcs_.
getChannelID()
int trigscint::QIEStream::getChannelID () const inline
Get channel ID
Definition at line 58 of file QIEStream.h.
{ return chanID_; }
References chanID_.
getCID()
std::vector< int > trigscint::QIEStream::getCID () const inline
Get Cap IDs of all time samples
Definition at line 79 of file QIEStream.h.
{ return cids_; }
References cids_.
getElectronicsID()
uint8_t trigscint::QIEStream::getElectronicsID () const inline
Get electronics ID
Definition at line 63 of file QIEStream.h.
{ return electronicsID_; }
References electronicsID_.
getTDC()
std::vector< int > trigscint::QIEStream::getTDC () const inline
Get TDCs of all time samples
Definition at line 73 of file QIEStream.h.
{ return tdcs_; }
References tdcs_.
operator<()
bool trigscint::QIEStream::operator< (const QIEStream & rhs) const inline
A dummy operator overloading
Note
required for declaring std::vector<> in EventDef.h
Definition at line 51 of file QIEStream.h.
{
    return this->chanID_ < rhs.chanID_;
  }
References chanID_.
Print()
void trigscint::QIEStream::Print (Option_t * option = "") const
Print ifo about the class
Note
required by EventDef.h
setADC()
void trigscint::QIEStream::setADC (const std::vector< int > adc) inline
Store adcs of all time samples
Parameters
adc_ array of adcs
Definition at line 96 of file QIEStream.h.
{ adcs_ = adc; }
References adcs_.
Referenced by trigscint::QIEDecoder::produce(), and trigscint::QIEEncoder::produce().
setChannelID()
void trigscint::QIEStream::setChannelID (const int chanid) inline
Store the channel ID
Definition at line 85 of file QIEStream.h.
{ chanID_ = chanid; }
References chanID_.
setCID()
void trigscint::QIEStream::setCID (const std::vector< int > cid) inline
Store cids of all time samples
Parameters
cid_ array of cids
Definition at line 109 of file QIEStream.h.
{ cids_ = cid; }
References cids_.
Referenced by trigscint::QIEDecoder::produce(), and trigscint::QIEEncoder::produce().
setElectronicsID()
void trigscint::QIEStream::setElectronicsID (const int elecid) inline
Store the electronics ID
Definition at line 90 of file QIEStream.h.
{ electronicsID_ = elecid; }
References electronicsID_.
Referenced by trigscint::QIEEncoder::produce().
setTDC()
void trigscint::QIEStream::setTDC (const std::vector< int > tdc) inline
Store tdcs of all time samples
Parameters
tdc_ array of tdcs
Definition at line 102 of file QIEStream.h.
{ tdcs_ = tdc; }
References tdcs_.
Referenced by trigscint::QIEDecoder::produce(), and trigscint::QIEEncoder::produce().
Member Data Documentation
adcs_
std::vector<int> trigscint::QIEStream::adcs_ private
Analog to Digital counts.
Definition at line 133 of file QIEStream.h.
Referenced by getADC(), and setADC().
chanID_
int trigscint::QIEStream::chanID_ private
detector channel ID (bar nb)
Definition at line 128 of file QIEStream.h.
Referenced by getChannelID(), operator<(), and setChannelID().
CHECKSUM_POS
const int trigscint::QIEStream::CHECKSUM_POS {2} static
Definition at line 117 of file QIEStream.h.
CID_SKIP_POS
const int trigscint::QIEStream::CID_SKIP_POS {3} static
Definition at line 123 of file QIEStream.h.
CID_UNSYNC_POS
const int trigscint::QIEStream::CID_UNSYNC_POS {2} static
Definition at line 122 of file QIEStream.h.
cids_
std::vector<int> trigscint::QIEStream::cids_ private
Capacitor IDs.
Definition at line 137 of file QIEStream.h.
Referenced by getCID(), and setCID().
CRC0_ERR_POS
const int trigscint::QIEStream::CRC0_ERR_POS {0} static
Definition at line 120 of file QIEStream.h.
CRC1_ERR_POS
const int trigscint::QIEStream::CRC1_ERR_POS {1} static
Definition at line 121 of file QIEStream.h.
electronicsID_
int trigscint::QIEStream::electronicsID_ private
electronics ID
Definition at line 130 of file QIEStream.h.
Referenced by getElectronicsID(), and setElectronicsID().
ERROR_POS
const int trigscint::QIEStream::ERROR_POS {1} static
Definition at line 116 of file QIEStream.h.
FLAG_SIZE
const int trigscint::QIEStream::FLAG_SIZE {1} static
Definition at line 119 of file QIEStream.h.
NUM_SAMPLES
const int trigscint::QIEStream::NUM_SAMPLES {5} static
Definition at line 124 of file QIEStream.h.
tdcs_
std::vector<int> trigscint::QIEStream::tdcs_ private
Time to Digital counts.
Definition at line 135 of file QIEStream.h.
Referenced by getTDC(), and setTDC().
TRIGID_POS
const int trigscint::QIEStream::TRIGID_POS {0} static
Definition at line 115 of file QIEStream.h.
The documentation for this class was generated from the following file:
TrigScint/include/TrigScint/Event/QIEStream.h