LDMX Software: ecal::EcalTriggerGeometry Class Reference
ecal::EcalTriggerGeometry Class Reference
defines the relationship between precision cells and trigger cells and provides geometry information for trigger cells
#include <EcalTriggerGeometry.h>
Public Member Functions
EcalTriggerGeometry (int symmetry, const ldmx::EcalHexReadout *ecalGeom=0)
std::vector< ldmx::EcalID > contentsOfTriggerCell (ldmx::EcalTriggerID triggerCell) const
ldmx::EcalID centerInTriggerCell (ldmx::EcalTriggerID triggerCell) const
ldmx::EcalTriggerID belongsTo (ldmx::EcalID precisionCell) const
std::pair< double, double > globalPosition (ldmx::EcalTriggerID triggerCell) const
std::pair< double, double > localPosition (ldmx::EcalTriggerID triggerCell) const
Public Member Functions inherited from framework::ConditionsObject
ConditionsObject (const std::string &name)
virtual ~ConditionsObject ()
std::string getName () const
Static Public Attributes
static constexpr const char * CONDITIONS_OBJECT_NAME {"EcalTriggerGeometry"}
Private Attributes
int symmetry_
const ldmx::EcalHexReadout * ecalGeometry_
std::map< ldmx::EcalID, ldmx::EcalTriggerID > precision2trigger_
std::map< ldmx::EcalTriggerID, std::vector< ldmx::EcalID > > trigger2precision_
Detailed Description
defines the relationship between precision cells and trigger cells and provides geometry information for trigger cells
Definition at line 31 of file EcalTriggerGeometry.h.
Constructor & Destructor Documentation
EcalTriggerGeometry()
ecal::EcalTriggerGeometry::EcalTriggerGeometry (int symmetry, const ldmx::EcalHexReadout * ecalGeom = 0)
lower left-sector
upper-left sector
Definition at line 17 of file EcalTriggerGeometry.cxx.
    : ConditionsObject(CONDITIONS_OBJECT_NAME),
      symmetry_{symmetry},
      ecalGeometry_{ecalGeom} {
  if ((symmetry_ & MODULES_MASK) == INPLANE_IDENTICAL) {
    // first set is the same regardless of alignment...
    int tcell = 0;
    for (int v = 1; v <= 10; v += 3) {
      for (int u = 1; u <= 10; u += 3) {
        ldmx::EcalTriggerID tid(0, 0, tcell);
        std::vector<ldmx::EcalID> pids;
        for (int du = -1; du <= 1; du++) {
          for (int dv = -1; dv <= 1; dv++) {
            ldmx::EcalID pid(0, 0, u + du, v + dv);
            precision2trigger_[pid] = tid;
            pids.push_back(pid);
          }
        }
        trigger2precision_[tid] = pids;
        tcell++;
      }
    }
    for (int v = 13; v <= 22; v += 3) {
      for (int u = v - 10; u <= v; u += 3) {
        ldmx::EcalTriggerID tid(0, 0, tcell);
        std::vector<ldmx::EcalID> pids;
        for (int dv = -1; dv <= 1; dv++) {
          for (int du = -1; du <= 1; du++) {
            ldmx::EcalID pid(0, 0, u + du + dv,
                             v + dv);  // changes directions here
            precision2trigger_[pid] = tid;
            pids.push_back(pid);
          }
        }
        trigger2precision_[tid] = pids;
        tcell++;
      }
    }
    // right side
    for (int v = 2; v <= 22; v += 3) {
      int irow = (v - 2) / 3;
      for (int icol = 0; icol <= std::min(irow, 3); icol++) {
        if (irow - icol >= 4) continue;
        ldmx::EcalTriggerID tid(0, 0, tcell);
        std::vector<ldmx::EcalID> pids;
        int u = 13 + 3 * icol;
        for (int dv = -1; dv <= 1; dv++) {
          for (int du = -1; du <= 1; du++) {
            ldmx::EcalID pid(0, 0, u + du, v + du + dv);
            precision2trigger_[pid] = tid;
            pids.push_back(pid);
          }
        }
        trigger2precision_[tid] = pids;
        tcell++;
      }
    }
  } else {
    // raise an exception...
  }
}
References precision2trigger_, symmetry_, and trigger2precision_.
Member Function Documentation
belongsTo()
ldmx::EcalTriggerID ecal::EcalTriggerGeometry::belongsTo (ldmx::EcalID precisionCell) const
Returns which trigger cell this precision cell is associated with, or a null id if there is no such association.
Definition at line 117 of file EcalTriggerGeometry.cxx.
{
  ldmx::EcalID effId;
  if ((symmetry_ & MODULES_MASK) == INPLANE_IDENTICAL) {
    effId = ldmx::EcalID(0, 0, precisionCell.cell());
  }
  auto ptr = precision2trigger_.find(effId);
  if (ptr == precision2trigger_.end()) {
    return ldmx::EcalTriggerID(0, 0, 0);  // not ideal
  } else {
    return ldmx::EcalTriggerID(precisionCell.layer(), precisionCell.module(),
                               ptr->second.triggercell());
  }
}
References ldmx::EcalID::cell(), ldmx::EcalID::layer(), ldmx::EcalID::module(), precision2trigger_, and symmetry_.
Referenced by ecal::EcalTrigPrimDigiProducer::produce().
centerInTriggerCell()
ldmx::EcalID ecal::EcalTriggerGeometry::centerInTriggerCell (ldmx::EcalTriggerID triggerCell) const
Returns the set of precision (full-granularity/DAQ) cell which is the center of the given trigger cell.
Definition at line 100 of file EcalTriggerGeometry.cxx.
{
  ldmx::EcalTriggerID effId;
  if ((symmetry_ & MODULES_MASK) == INPLANE_IDENTICAL) {
    effId = ldmx::EcalTriggerID(0, 0, triggerCell.triggercell());
  }
  auto ptr = trigger2precision_.find(effId);
  if (ptr == trigger2precision_.end()) {
    std::stringstream ss;
    ss << "Unable to find trigger cell " << triggerCell;
    EXCEPTION_RAISE("EcalGeometryException", ss.str());
  }
  return ldmx::EcalID(triggerCell.layer(), triggerCell.module(),
                      ptr->second[4].cell());
}
References ldmx::EcalTriggerID::layer(), ldmx::EcalTriggerID::module(), symmetry_, trigger2precision_, and ldmx::EcalTriggerID::triggercell().
Referenced by globalPosition(), and localPosition().
contentsOfTriggerCell()
std::vector< ldmx::EcalID > ecal::EcalTriggerGeometry::contentsOfTriggerCell (ldmx::EcalTriggerID triggerCell) const
Returns the set of precision (full-granularity/DAQ) cells which are associated with the given trigger cell.
Definition at line 83 of file EcalTriggerGeometry.cxx.
{
  ldmx::EcalTriggerID effId;
  std::vector<ldmx::EcalID> retval;
  if ((symmetry_ & MODULES_MASK) == INPLANE_IDENTICAL) {
    effId = ldmx::EcalTriggerID(0, 0, triggerCell.triggercell());
  }
  auto ptr = trigger2precision_.find(effId);
  if (ptr != trigger2precision_.end()) {
    for (auto idz : ptr->second) {
      retval.push_back(
          ldmx::EcalID(triggerCell.layer(), triggerCell.module(), idz.cell()));
    }
  }
  return retval;
}
References ldmx::EcalTriggerID::layer(), ldmx::EcalTriggerID::module(), symmetry_, trigger2precision_, and ldmx::EcalTriggerID::triggercell().
globalPosition()
std::pair< double, double > ecal::EcalTriggerGeometry::globalPosition (ldmx::EcalTriggerID triggerCell) const
Returns the center of the given trigger cell, depends on Ecal Geometry (ldmx::EcalHexReadout)
Definition at line 133 of file EcalTriggerGeometry.cxx.
{
  if (!ecalGeometry_) return std::pair<double, double>(0, 0);
  ldmx::EcalID pid = centerInTriggerCell(triggerCell);
  return ecalGeometry_->getCellCenterAbsolute(pid);
}
References centerInTriggerCell(), ecalGeometry_, and ldmx::EcalHexReadout::getCellCenterAbsolute().
localPosition()
std::pair< double, double > ecal::EcalTriggerGeometry::localPosition (ldmx::EcalTriggerID triggerCell) const
Returns the local (within module) center of the given trigger cell, depends on Ecal Geometry (ldmx::EcalHexReadout)
Definition at line 140 of file EcalTriggerGeometry.cxx.
{
  if (!ecalGeometry_) return std::pair<double, double>(0, 0);
  ldmx::EcalID pid = centerInTriggerCell(triggerCell);
  return ecalGeometry_->getCellCenterRelative(pid.cell());
}
References ldmx::EcalID::cell(), centerInTriggerCell(), ecalGeometry_, and ldmx::EcalHexReadout::getCellCenterRelative().
Member Data Documentation
CONDITIONS_OBJECT_NAME
constexpr const char* ecal::EcalTriggerGeometry::CONDITIONS_OBJECT_NAME {"EcalTriggerGeometry"} static constexpr
Definition at line 33 of file EcalTriggerGeometry.h.
ecalGeometry_
const ldmx::EcalHexReadout* ecal::EcalTriggerGeometry::ecalGeometry_ private
Reference to the Ecal geometry used for trigger geometry information
Definition at line 73 of file EcalTriggerGeometry.h.
Referenced by globalPosition(), and localPosition().
precision2trigger_
std::map<ldmx::EcalID, ldmx::EcalTriggerID> ecal::EcalTriggerGeometry::precision2trigger_ private
Map of precision cells to trigger cells, under symmetry assumptions
Definition at line 76 of file EcalTriggerGeometry.h.
Referenced by belongsTo(), and EcalTriggerGeometry().
symmetry_
int ecal::EcalTriggerGeometry::symmetry_ private
Identifies what symmetries apply in this case, such as all layers being identical, or all even and odd planes being identical and whether all modules on the same plane are identical.
Definition at line 71 of file EcalTriggerGeometry.h.
Referenced by belongsTo(), centerInTriggerCell(), contentsOfTriggerCell(), and EcalTriggerGeometry().
trigger2precision_
std::map<ldmx::EcalTriggerID, std::vector<ldmx::EcalID> > ecal::EcalTriggerGeometry::trigger2precision_ private
Map of trigger cells to precision cells, under symmetry assumptions
Definition at line 79 of file EcalTriggerGeometry.h.
Referenced by centerInTriggerCell(), contentsOfTriggerCell(), and EcalTriggerGeometry().
The documentation for this class was generated from the following files:
Ecal/include/Ecal/EcalTriggerGeometry.h
Ecal/src/Ecal/EcalTriggerGeometry.cxx