LDMX Software: ldmx::DNNEcalVetoProcessor Class Reference
ldmx::DNNEcalVetoProcessor Class Reference
Determines if event is vetoable using ECAL hit information w/ a deep neural network.
#include <DNNEcalVetoProcessor.h>
Public Member Functions
DNNEcalVetoProcessor (const std::string &name, Process &process)
void configure (Parameters &parameters) final override
void produce (Event &event)
Public Member Functions inherited from ldmx::Producer
Producer (const std::string &name, Process &process)
Public Member Functions inherited from ldmx::EventProcessor
EventProcessor (const std::string &name, Process &process)
virtual ~EventProcessor ()
virtual void onNewRun (const RunHeader &runHeader)
virtual void onFileOpen (EventFile &eventFile)
virtual void onFileClose (EventFile &eventFile)
virtual void onProcessStart ()
virtual void onProcessEnd ()
TDirectory * getHistoDirectory ()
void setStorageHint (ldmx::StorageControlHint hint)
void setStorageHint (ldmx::StorageControlHint hint, const std::string &purposeString)
void createHistograms (const std::vector< Parameters > &histos)
Private Member Functions
void make_inputs (const std::vector< EcalHit > &ecalRecHits)
Private Attributes
float disc_cut_ = -99
std::vector< std::vector< float > > data_
std::unique_ptr< EcalHexReadout > hexReadout_
std::string collectionName_ {"DNNEcalVeto"}
bool debug_ = false
Static Private Attributes
constexpr static unsigned int max_num_hits_ = 50
constexpr static unsigned int n_coordinate_dim_ = 3
constexpr static unsigned int coordinate_x_offset_ = 0
constexpr static unsigned int coordinate_y_offset_ = max_num_hits_
constexpr static unsigned int coordinate_z_offset_ = 2 * max_num_hits_
constexpr static unsigned int n_feature_dim_ = 5
constexpr static unsigned int feature_x_offset_ = 0
constexpr static unsigned int feature_y_offset_ = max_num_hits_
constexpr static unsigned int feature_z_offset_ = 2 * max_num_hits_
constexpr static unsigned int feature_layerid_offset_ = 3 * max_num_hits_
constexpr static unsigned int feature_energy_offset_ = 4 * max_num_hits_
static const std::vector< std::string > input_names_ {"coordinates", "features"}
static const std::vector< unsigned int > input_sizes_
Additional Inherited Members
Static Public Member Functions inherited from ldmx::EventProcessor
static void declare (const std::string &classname, int classtype, EventProcessorMaker *)
Static Public Attributes inherited from ldmx::Producer
static const int CLASSTYPE {1}
Protected Member Functions inherited from ldmx::EventProcessor
void abortEvent ()
Protected Attributes inherited from ldmx::EventProcessor
Process & process_
HistogramHelper histograms_
Interface class for making and filling histograms.
NtupleManager & ntuple_ {NtupleManager::getInstance()}
Manager for any ntuples.
logging::logger theLog_
The logger for this EventProcessor.
Detailed Description
Determines if event is vetoable using ECAL hit information w/ a deep neural network.
Definition at line 26 of file DNNEcalVetoProcessor.h.
Member Function Documentation
configure()
void ldmx::DNNEcalVetoProcessor::configure (Parameters & parameters) final override virtual
Callback for the EventProcessor to configure itself from the given set of parameters.
The parameters a processor has access to are the member variables of the python class in the sequence that has className equal to the EventProcessor class name.
For an example, look at MyProcessor.
Parameters
parameters Parameters for configuration.
Reimplemented from ldmx::EventProcessor.
Definition at line 22 of file DNNEcalVetoProcessor.cxx.
{
     // These are the v12 parameters
     //  all distances in mm
     double moduleRadius = 85.0; //same as default
     int    numCellsWide = 23; //same as default
     double moduleGap = 1.5;
     double ecalFrontZ = 220;
     std::vector<double> ecalSensLayersZ = {
          7.850,
         13.300,
         26.400,
         33.500,
         47.950,
         56.550,
         72.250,
         81.350,
         97.050,
         106.150,
         121.850,
         130.950,
         146.650,
         155.750,
         171.450,
         180.550,
         196.250,
         205.350,
         221.050,
         230.150,
         245.850,
         254.950,
         270.650,
         279.750,
         298.950,
         311.550,
         330.750,
         343.350,
         362.550,
         375.150,
         394.350,
         406.950,
         426.150,
         438.750
     };
     hexReadout_ = std::make_unique<EcalHexReadout>(
             moduleRadius,
             moduleGap,
             numCellsWide,
             ecalSensLayersZ,
             ecalFrontZ
             );
     disc_cut_ = parameters.getParameter<double>("disc_cut");
 #ifdef LDMX_USE_ONNXRUNTIME
     rt_ = std::make_unique<Ort::ONNXRuntime>(parameters.getParameter<std::string>("model_path"));
 #else
     EXCEPTION_RAISE("DNNEcalVetoProcessor",
                     "Cannot run DNN because ONNXRuntime is not installed.");
 #endif
     // debug mode
     debug_ = parameters.getParameter<bool>("debug");
     if (debug_) {
       std::cout << "=== Module position map ===" << std::endl;
       for (const auto &p : hexReadout_->getCellModulePositionMap()) {
         std::cout << p.first << " " << p.second.first << " " << p.second.second << std::endl;
       }
       std::cout << "=== Layer Zs ===" << std::endl;
       for (unsigned layer=0; layer<34; ++layer) {
         std::cout << hexReadout_->getZPosition(layer) << std::endl;
       }
       std::cout << std::endl << "========================" << std::endl;
     }
     // Set the collection name as defined in the configuration
     collectionName_ = parameters.getParameter<std::string>("collection_name");
   }
References collectionName_, and ldmx::Parameters::getParameter().
make_inputs()
void ldmx::DNNEcalVetoProcessor::make_inputs (const std::vector< EcalHit > & ecalRecHits) private
Make inputs to the DNN from ECAL RecHits.
Parameters
ecalRecHits The EcalHit collection.
Definition at line 135 of file DNNEcalVetoProcessor.cxx.
{
     // clear data
     for (auto &v : data_){
       std::fill(v.begin(), v.end(), 0);
     }
     unsigned idx = 0;
     for (const auto& hit : ecalRecHits) {
       if (hit.getEnergy() <= 0) continue;
       double x = 0, y = 0, z = 0;
       hexReadout_->getCellAbsolutePosition(hit.getID(), x, y, z);
       data_[0].at(coordinate_x_offset_ + idx) = x;
       data_[0].at(coordinate_y_offset_ + idx) = y;
       data_[0].at(coordinate_z_offset_ + idx) = z;
       data_[1].at(feature_x_offset_ + idx) = x;
       data_[1].at(feature_y_offset_ + idx) = y;
       data_[1].at(feature_z_offset_ + idx) = z;
       data_[1].at(feature_layerid_offset_ + idx) = hit.getLayer();
       data_[1].at(feature_energy_offset_ + idx) = std::log(hit.getEnergy());
       ++idx;
     }
     if (debug_) {
       for (unsigned iname=0; iname<input_names_.size(); ++iname) {
         std::cout << "=== " << input_names_[iname] << " ===" << std::endl;
         for (unsigned i=0; i<input_sizes_[iname]; ++i){
           std::cout << data_[iname].at(i) << ", ";
           if ((i + 1) % max_num_hits_ == 0) {
             std::cout << std::endl;
           }
         }
       }
     } // debug
   }
References max_num_hits_.
Referenced by produce().
produce()
void ldmx::DNNEcalVetoProcessor::produce (Event & event) virtual
Process the event and put new data products into it.
Parameters
event The Event to process.
Implements ldmx::Producer.
Definition at line 100 of file DNNEcalVetoProcessor.cxx.
{
     EcalVetoResult result;
     // Get the collection of digitized Ecal hits from the event.
     const auto ecalRecHits = event.getCollection<EcalHit>("EcalRecHits");
     auto nhits = std::count_if(ecalRecHits.begin(), ecalRecHits.end(), [](const EcalHit& hit){ return hit.getEnergy()>0; });
     if (nhits < max_num_hits_) {
       // make inputs
       make_inputs(ecalRecHits);
       // run the DNN
 #ifdef LDMX_USE_ONNXRUNTIME
       auto outputs = rt_->run(input_names_, data_)[0];
       result.setDiscValue(outputs.at(1));
 #endif
     } else {
       result.setDiscValue(-99);
     }
     if (debug_) {
       std::cout << "... disc_val = " << result.getDisc() << std::endl;
     }
     result.setVetoResult(result.getDisc() > disc_cut_);
     // If the event passes the veto, keep it. Otherwise, drop the event.
     if (result.passesVeto()) {
       setStorageHint(hint_shouldKeep);
     } else {
       setStorageHint(hint_shouldDrop);
     }
     event.add(collectionName_, result);
   }
References collectionName_, make_inputs(), max_num_hits_, ldmx::EcalVetoResult::passesVeto(), and ldmx::EventProcessor::setStorageHint().
Member Data Documentation
collectionName_
std::string ldmx::DNNEcalVetoProcessor::collectionName_ {"DNNEcalVeto"} private
Name of the collection which will containt the results.
Definition at line 69 of file DNNEcalVetoProcessor.h.
Referenced by configure(), and produce().
input_sizes_
const std::vector< unsigned int > ldmx::DNNEcalVetoProcessor::input_sizes_ static private
Initial value:
{
    n_coordinate_dim_*max_num_hits_, n_feature_dim_*max_num_hits_}
Definition at line 58 of file DNNEcalVetoProcessor.h.
max_num_hits_
constexpr static unsigned int ldmx::DNNEcalVetoProcessor::max_num_hits_ = 50 static constexpr private
Maximum number of hits allowed in ECAL. Events with more hits will be marked as BKG directly without running the DNN.
Definition at line 43 of file DNNEcalVetoProcessor.h.
Referenced by make_inputs(), and produce().
The documentation for this class was generated from the following files:
Ecal/include/Ecal/DNNEcalVetoProcessor.h
Ecal/src/DNNEcalVetoProcessor.cxx