LDMX Software: trigscint::TrigScintQIEDigis Class Reference
trigscint::TrigScintQIEDigis Class Reference
class for storing QIE output
#include <TrigScintQIEDigis.h>
Public Member Functions
TrigScintQIEDigis ()=default
Default constructor.
~TrigScintQIEDigis ()=default
Default destructor.
void Print (Option_t *option="") const
void Clear (Option_t *option="")
bool operator< (const TrigScintQIEDigis &rhs) const
int getChanID () const
int getElecID () const
std::vector< int > getADC () const
std::vector< int > getTDC () const
std::vector< int > getCID () const
void setTimeSinceSpill (const uint32_t timeSpill)
uint32_t getTimeSinceSpill () const
void setChanID (const int chanid)
void setElecID (const int elecid)
void setADC (const std::vector< int > adc)
void setTDC (const std::vector< int > tdc)
void setCID (const std::vector< int > cid)
Protected Attributes
int chanID_
channel ID
int elecID_ {-1}
channel ID
std::vector< int > adcs_
analog to digital counts
std::vector< int > tdcs_
Time to Digital counts.
uint32_t timeSinceSpillCounter_
Time since spill (a counter, to be divided by 125e6 or so)
Private Member Functions
ClassDef (TrigScintQIEDigis, 1)
Private Attributes
std::vector< int > cids_
capacitor IDs
Detailed Description
class for storing QIE output
Definition at line 13 of file TrigScintQIEDigis.h.
Member Function Documentation
Clear()
void trigscint::TrigScintQIEDigis::Clear (Option_t * option = "")
A dummy function
Note
required by Event/include/Event/EventDef.h
Definition at line 23 of file TrigScintQIEDigis.cxx.
{}
getADC()
std::vector< int > trigscint::TrigScintQIEDigis::getADC () const inline
Get ADCs of all time samples
Definition at line 55 of file TrigScintQIEDigis.h.
{ return adcs_; }
References adcs_.
Referenced by trigscint::EventReadoutProducer::produce(), and trigscint::QIEDecoder::produce().
getChanID()
int trigscint::TrigScintQIEDigis::getChanID () const inline
Get channel ID
Definition at line 45 of file TrigScintQIEDigis.h.
{ return chanID_; }
References chanID_.
Referenced by trigscint::EventReadoutProducer::produce(), and trigscint::QIEDecoder::produce().
getCID()
std::vector< int > trigscint::TrigScintQIEDigis::getCID () const inline
Get Cap IDs of all time samples
Definition at line 65 of file TrigScintQIEDigis.h.
{ return cids_; }
References cids_.
getElecID()
int trigscint::TrigScintQIEDigis::getElecID () const inline
Get electronics ID
Definition at line 50 of file TrigScintQIEDigis.h.
{ return elecID_; }
References elecID_.
Referenced by trigscint::QIEDecoder::produce().
getTDC()
std::vector< int > trigscint::TrigScintQIEDigis::getTDC () const inline
Get tdcs of all time samples
Definition at line 60 of file TrigScintQIEDigis.h.
{ return tdcs_; }
References tdcs_.
Referenced by trigscint::QIEDecoder::produce().
getTimeSinceSpill()
uint32_t trigscint::TrigScintQIEDigis::getTimeSinceSpill () const inline
Store the event time since spill counter
Definition at line 77 of file TrigScintQIEDigis.h.
{ return timeSinceSpillCounter_; }
References timeSinceSpillCounter_.
Referenced by dqm::NtuplizeTrigScintQIEDigis::analyze(), and trigscint::QIEDecoder::produce().
operator<()
bool trigscint::TrigScintQIEDigis::operator< (const TrigScintQIEDigis & rhs) const inline
A dummy operator overloading
Note
required for declaring std::vector<> in EventDef.h
Definition at line 38 of file TrigScintQIEDigis.h.
{
    return this->chanID_ < rhs.chanID_;
  }
References chanID_.
Print()
void trigscint::TrigScintQIEDigis::Print (Option_t * option = "") const
Print ifo about the class
Note
required by EventDef.h
Definition at line 14 of file TrigScintQIEDigis.cxx.
{
  std::cout << "TrigScintQIEDigis { "
            << "chanID= " << chanID_ << ", "
            << "ADC[0]= " << adcs_[0] << ", "
            << "TDC[0]= " << tdcs_[0] << ", "
            << "CID[0]= " << tdcs_[0] << ", "
            << "}\n";
}
References adcs_, chanID_, and tdcs_.
setADC()
void trigscint::TrigScintQIEDigis::setADC (const std::vector< int > adc) inline
Store adcs of all time samples
Parameters
adc_ array of adcs
Definition at line 95 of file TrigScintQIEDigis.h.
{ adcs_ = adc; }
References adcs_.
Referenced by trigscint::EventReadoutProducer::produce(), trigscint::QIEDecoder::produce(), and trigscint::TrigScintQIEDigiProducer::produce().
setChanID()
void trigscint::TrigScintQIEDigis::setChanID (const int chanid) inline
Store the channel ID
Definition at line 83 of file TrigScintQIEDigis.h.
{ chanID_ = chanid; }
References chanID_.
Referenced by trigscint::EventReadoutProducer::produce(), trigscint::QIEDecoder::produce(), and trigscint::TrigScintQIEDigiProducer::produce().
setCID()
void trigscint::TrigScintQIEDigis::setCID (const std::vector< int > cid) inline
Store cids of all time samples
Parameters
cid_ array of cids
Definition at line 107 of file TrigScintQIEDigis.h.
{ cids_ = cid; }
References cids_.
Referenced by trigscint::TrigScintQIEDigiProducer::produce().
setElecID()
void trigscint::TrigScintQIEDigis::setElecID (const int elecid) inline
Store the electronics ID
Definition at line 88 of file TrigScintQIEDigis.h.
{ elecID_ = elecid; }
References elecID_.
Referenced by trigscint::EventReadoutProducer::produce(), and trigscint::QIEDecoder::produce().
setTDC()
void trigscint::TrigScintQIEDigis::setTDC (const std::vector< int > tdc) inline
Store tdcs of all time samples
Parameters
tdc_ array of tdcs
Definition at line 101 of file TrigScintQIEDigis.h.
{ tdcs_ = tdc; }
References tdcs_.
Referenced by trigscint::EventReadoutProducer::produce(), trigscint::QIEDecoder::produce(), and trigscint::TrigScintQIEDigiProducer::produce().
setTimeSinceSpill()
void trigscint::TrigScintQIEDigis::setTimeSinceSpill (const uint32_t timeSpill) inline
Store the event time since spill counter
Definition at line 71 of file TrigScintQIEDigis.h.
{ timeSinceSpillCounter_ = timeSpill; }
References timeSinceSpillCounter_.
Referenced by trigscint::EventReadoutProducer::produce(), and trigscint::QIEDecoder::produce().
Member Data Documentation
adcs_
std::vector<int> trigscint::TrigScintQIEDigis::adcs_ protected
analog to digital counts
Definition at line 116 of file TrigScintQIEDigis.h.
Referenced by getADC(), trigscint::EventReadout::Print(), Print(), and setADC().
chanID_
int trigscint::TrigScintQIEDigis::chanID_ protected
channel ID
Definition at line 111 of file TrigScintQIEDigis.h.
Referenced by getChanID(), trigscint::EventReadout::operator<(), operator<(), trigscint::EventReadout::Print(), Print(), and setChanID().
cids_
std::vector<int> trigscint::TrigScintQIEDigis::cids_ private
capacitor IDs
Definition at line 127 of file TrigScintQIEDigis.h.
Referenced by getCID(), and setCID().
elecID_
int trigscint::TrigScintQIEDigis::elecID_ {-1} protected
channel ID
Definition at line 113 of file TrigScintQIEDigis.h.
Referenced by getElecID(), and setElecID().
tdcs_
std::vector<int> trigscint::TrigScintQIEDigis::tdcs_ protected
Time to Digital counts.
Definition at line 119 of file TrigScintQIEDigis.h.
Referenced by getTDC(), Print(), and setTDC().
timeSinceSpillCounter_
uint32_t trigscint::TrigScintQIEDigis::timeSinceSpillCounter_ protected
Time since spill (a counter, to be divided by 125e6 or so)
Definition at line 122 of file TrigScintQIEDigis.h.
Referenced by getTimeSinceSpill(), and setTimeSinceSpill().
The documentation for this class was generated from the following files:
TrigScint/include/TrigScint/Event/TrigScintQIEDigis.h
TrigScint/src/TrigScint/Event/TrigScintQIEDigis.cxx