LDMX Software: packing::utility::Reader Class Reference
packing::utility::Reader Class Reference
#include <Reader.h>
Public Member Functions
Reader ()
void open (const std::string &file_name)
Reader (const std::string &file_name)
~Reader ()=default
destructor, close the input file stream
void seek (int off, std::ios_base::seekdir dir=std::ios::beg)
template<typename WordType , std::enable_if_t< std::is_integral< WordType >::value, bool > = true>
void seek (int off, std::ios_base::seekdir dir=std::ios::beg)
int tell ()
template<typename WordType >
int tell ()
template<typename WordType , std::enable_if_t< std::is_integral< WordType >::value, bool > = true>
Reader & read (WordType *w, std::size_t count)
template<typename WordType , std::enable_if_t< std::is_integral< WordType >::value, bool > = true>
Reader & operator>> (WordType &w)
template<typename ObjectType , std::enable_if_t< std::is_class< ObjectType >::value, bool > = true>
Reader & operator>> (ObjectType &o)
template<typename ContentType >
Reader & read (std::vector< ContentType > &vec, std::size_t count)
bool operator! () const
operator bool () const
bool eof ()
Private Attributes
std::ifstream file_
file stream we are reading from
std::size_t file_size_
file size in bytes
Detailed Description
Reading a raw data file.
We wrap a basic std::ifstream in order to make the retrieving of specific-width words easier for ourselves.
Definition at line 19 of file Reader.h.
Constructor & Destructor Documentation
Reader() [1/2]
packing::utility::Reader::Reader () inline
default constructor
We make sure that our input file stream will not skip white space.
Definition at line 26 of file Reader.h.
           {
    file_.unsetf(std::ios::skipws);
  }
References file_.
Reader() [2/2]
packing::utility::Reader::Reader (const std::string & file_name) inline
Constructor that also opens the input file
See also
open
Parameters
[in] file_name full path to the file we are going to open
Definition at line 49 of file Reader.h.
                                     : Reader() {
    this->open(file_name);
  }
References open().
Member Function Documentation
eof()
bool packing::utility::Reader::eof () inline
check if file is done
Just calls the underlying ifstream eof.
Returns
true if we have reached the end of file.
Definition at line 215 of file Reader.h.
             {
    return file_.eof() or file_.tellg() == file_size_;
  }
References file_, and file_size_.
Referenced by packing::SingleSubsystemUnpacker::produce().
open()
void packing::utility::Reader::open (const std::string & file_name) inline
Open a file with this reader
We open the file as an input, binary file.
Parameters
[in] file_name full path to the file we are going to open
Definition at line 37 of file Reader.h.
{
    file_.open(file_name, std::ios::in | std::ios::binary);
    file_.seekg(0,std::ios::end);
    file_size_ = file_.tellg();
    file_.seekg(0);
  }
References file_, and file_size_.
Referenced by packing::SingleSubsystemUnpacker::configure(), packing::rawdatafile::File::File(), and Reader().
operator bool()
packing::utility::Reader::operator bool () const inline
Check if reader is in good/bad state
Following the C++ reference, we pass-along the check on if our ifstream is in a fail state.
Defining this operator allows us to do the following.
Reader r('dummy.raw') if (r) { std::cout << "dummy.raw was opened good" << std::endl; }
Returns
bool true if ifstream is in good state
Definition at line 204 of file Reader.h.
{
    return !file_.fail();
  }
References file_.
operator!()
bool packing::utility::Reader::operator! () const inline
Check if reader is in a fail state
Following the C++ reference, we pass-along the check on if our ifstream is in a fail state.
Returns
bool true if ifstream is in fail state
Definition at line 185 of file Reader.h.
{
    return file_.fail();
  }
References file_.
operator>>() [1/2]
template<typename ObjectType , std::enable_if_t< std::is_class< ObjectType >::value, bool > = true> Reader & packing::utility::Reader::operator>> (ObjectType & o) inline
Stream into a class object
We assume that the class we are streaming to has a specific method defined.
Reader& read(Reader&)
This can be satisfied by the classes that we own and operate.
Template Parameters
in] ObjectType class type to read
Parameters
[in] o instance of object to read into
Returns
*this
Definition at line 149 of file Reader.h.
{
    return o.read(*this);
  }
References read().
operator>>() [2/2]
template<typename WordType , std::enable_if_t< std::is_integral< WordType >::value, bool > = true> Reader & packing::utility::Reader::operator>> (WordType & w) inline
Stream the next word into the input handle
This implementation of the stream operator is only available to handles of integral types. Helps for shorthand of only grabbing a single word from the reader.
See also
read
Template Parameters
in] WordType integral-type word to read out
Parameters
[in] w reference to word to read into
Returns
handle to modified reader
Definition at line 131 of file Reader.h.
{
    return read(&w, 1);
  }
References read().
read() [1/2]
template<typename ContentType > Reader & packing::utility::Reader::read (std::vector< ContentType > & vec, std::size_t count) inline
Read the next 'count' objects into the input vector.
This is common enough, I wanted to specialize the read function.
The std::vector::resize is helpful for avoiding additional copies while the vector is being expanded. After allocating the space for each entry in the vector, we call the stream operator from *this into each entry in order, leaving early if a failure occurs.
Template Parameters
in] ContentType type of object inside the vector
Parameters
[in] vec object vector to read into
[in] count number of objects to read
Returns
*this
Definition at line 169 of file Reader.h.
{
    vec.resize(count);
    for (auto& w : vec) {
      if(!(*this >> w)) return *this;
    }
    return *this;
  }
read() [2/2]
template<typename WordType , std::enable_if_t< std::is_integral< WordType >::value, bool > = true> Reader & packing::utility::Reader::read (WordType * w, std::size_t count) inline
Read the next 'count' words into the input handle.
This implementation of read is only available to pointers to integral types. We assume that whatever space pointed to by w already has the space reserved necessary for the input words.
Template Parameters
in] WordType integral-type word to read out
Parameters
[in] w pointer to WordType array to write data to
[in] count number of words to read
Returns
(*this)
Definition at line 113 of file Reader.h.
{
    file_.read(reinterpret_cast<char*>(w), sizeof(WordType)*count);
    return *this;
  }
References file_.
Referenced by operator>>(), packing::SingleSubsystemUnpacker::read(), packing::rawdatafile::EventPacket::read(), and packing::rawdatafile::SubsystemPacket::read().
seek() [1/2]
void packing::utility::Reader::seek (int off, std::ios_base::seekdir dir = std::ios::beg) inline
Go ("seek") a specific position in the file.
This non-template version of seek uses the default meaning of the "off" parameter in which it counts bytes.
Parameters
[in] off number of bytes to move relative to dir
[in] dir location flag for the file, default is beginning
Definition at line 65 of file Reader.h.
{
    file_.seekg(off, dir);
  }
References file_.
Referenced by packing::rawdatafile::File::File(), and seek().
seek() [2/2]
template<typename WordType , std::enable_if_t< std::is_integral< WordType >::value, bool > = true> void packing::utility::Reader::seek (int off, std::ios_base::seekdir dir = std::ios::beg) inline
Seek by number of words
This template version of seek uses the input word type to move around by the count of the input words rather than the count of bytes.
Template Parameters
in] WordType Integral-type to count by
Parameters
[in] off number of words to move relative to dir
[in] dir location flag for the file, default is beginning
Definition at line 81 of file Reader.h.
{
    seek(off*sizeof(WordType), dir);
  }
References seek().
tell() [1/2]
int packing::utility::Reader::tell () inline
Tell us where the reader is
Returns
int number of bytes relative to beginning of file
Definition at line 90 of file Reader.h.
{ return file_.tellg(); }
References file_.
Referenced by packing::rawdatafile::File::File().
tell() [2/2]
template<typename WordType > int packing::utility::Reader::tell () inline
Tell by number of words
Returns
int number of words relative to beginning of file
Definition at line 98 of file Reader.h.
{ return tell()/sizeof(WordType); }
References tell().
Referenced by tell().
Member Data Documentation
file_
std::ifstream packing::utility::Reader::file_ private
file stream we are reading from
Definition at line 221 of file Reader.h.
Referenced by eof(), open(), operator bool(), operator!(), read(), Reader(), seek(), and tell().
file_size_
std::size_t packing::utility::Reader::file_size_ private
file size in bytes
Definition at line 223 of file Reader.h.
Referenced by eof(), and open().
The documentation for this class was generated from the following file:
Packing/include/Packing/Utility/Reader.h