LDMX Software: hcal::HcalReconConditions Class Reference
hcal::HcalReconConditions Class Reference
#include <HcalReconConditions.h>
Public Member Functions
HcalReconConditions (const conditions::DoubleTableCondition &table, bool validate=true)
double adcPedestal (const ldmx::HcalDigiID &id) const
double adcGain (const ldmx::HcalDigiID &id) const
double totPedestal (const ldmx::HcalDigiID &id) const
double totGain (const ldmx::HcalDigiID &id) const
Static Public Attributes
static const std::string CONDITIONS_NAME = "HcalReconConditions"
static const unsigned int IADC_PEDESTAL = 0
column index for ADC pedestal
static const unsigned int IADC_GAIN = 1
column index for ADC threshold
static const unsigned int ITOT_PEDESTAL = 2
column index for TOT pedestal
static const unsigned int ITOT_GAIN = 3
column index for TOT gain
static const std::vector< std::string > EXPECTED_COLUMNS
Private Attributes
const conditions::DoubleTableCondition & the_table_
reference to the table of conditions storing the chip conditions
Detailed Description
Class to wrap around an double table of conditions.
This hardcodes the column numbers and checks that the hardcoded numbers match the imported columns during construction.
Definition at line 17 of file HcalReconConditions.h.
Constructor & Destructor Documentation
HcalReconConditions()
hcal::HcalReconConditions::HcalReconConditions (const conditions::DoubleTableCondition & table, bool validate = true)
Constructor
Assign the conditions table to use and (if validate is true), check if the hard-coded column indices correctly match the table that is passed.
@raises Exception if any of the column names from the passed table do not match the hardcoded indices.
Parameters
[in] table double table of reconstruction conditions
[in] validate true if you want to check the columns
Definition at line 14 of file HcalReconConditions.cxx.
    : the_table_{table} {
  // leave early if we don't want to validate
  if (!validate) return;
  if (the_table_.getColumnCount() != EXPECTED_COLUMNS.size()) {
    EXCEPTION_RAISE(
        "ConditionsException",
        "Inconsistent condition for HcalReconConditions :" + table.getName());
  }
  // not using fancy C++17 to shorten this because we want the error to
  // tell us where the failure is
  for (size_t i = 0; i < EXPECTED_COLUMNS.size(); i++) {
    if (the_table_.getColumnNames().at(i) != EXPECTED_COLUMNS.at(i)) {
      EXCEPTION_RAISE("ConditionsException",
                      "Expected column '" + EXPECTED_COLUMNS.at(i) +
                          "', got '" + the_table_.getColumnNames().at(i) + "'");
    }  // does name match?
  }    // loop through columns
}
References EXPECTED_COLUMNS, conditions::BaseTableCondition::getColumnCount(), conditions::BaseTableCondition::getColumnNames(), framework::ConditionsObject::getName(), and the_table_.
Member Function Documentation
adcGain()
double hcal::HcalReconConditions::adcGain (const ldmx::HcalDigiID & id) const inline
get the ADC gain
The ADC gain converts the ADC counts measuring a voltage amplitude into an estimated charge deposition [fC].
Parameters
[in] id raw ID for specific chip
Returns
the ADC threshold for that chip in fC/counts
Definition at line 70 of file HcalReconConditions.h.
{
    return the_table_.get(id.raw(), IADC_GAIN);
  }
References conditions::HomogenousTableCondition< T >::get(), IADC_GAIN, and the_table_.
Referenced by hcal::HcalRecProducer::produce().
adcPedestal()
double hcal::HcalReconConditions::adcPedestal (const ldmx::HcalDigiID & id) const inline
get the ADC pedestal
Parameters
[in] id HCal Digi ID for specific chip
Returns
the ADC pedestal for that chip in counts
Definition at line 56 of file HcalReconConditions.h.
{
    return the_table_.get(id.raw(), IADC_PEDESTAL);
  }
References conditions::HomogenousTableCondition< T >::get(), IADC_PEDESTAL, and the_table_.
Referenced by hcal::HcalRecProducer::produce().
totGain()
double hcal::HcalReconConditions::totGain (const ldmx::HcalDigiID & id) const inline
get the TOT gain
The TOT gain converts counts measuring time over threshold into an estimate for charge deposited in that cell [fC].
Parameters
[in] id HCal Digi ID for specific chip
Returns
the TOT gain for that chip in fC/counts
Definition at line 94 of file HcalReconConditions.h.
{
    return the_table_.get(id.raw(), ITOT_GAIN);
  }
References conditions::HomogenousTableCondition< T >::get(), ITOT_GAIN, and the_table_.
Referenced by hcal::HcalRecProducer::produce().
totPedestal()
double hcal::HcalReconConditions::totPedestal (const ldmx::HcalDigiID & id) const inline
get the TOT pedestal
Parameters
[in] id HCal Digi ID for specific chip
Returns
the TOT pedestal for that chip in counts
Definition at line 80 of file HcalReconConditions.h.
{
    return the_table_.get(id.raw(), ITOT_PEDESTAL);
  }
References conditions::HomogenousTableCondition< T >::get(), ITOT_PEDESTAL, and the_table_.
Referenced by hcal::HcalRecProducer::produce().
Member Data Documentation
CONDITIONS_NAME
const std::string hcal::HcalReconConditions::CONDITIONS_NAME = "HcalReconConditions" static
the name of the HcalReconConditions table (must match python registration name)
Definition at line 21 of file HcalReconConditions.h.
Referenced by hcal::HcalRecProducer::produce().
EXPECTED_COLUMNS
const std::vector< std::string > hcal::HcalReconConditions::EXPECTED_COLUMNS static
Initial value:
= {
    "ADC_PEDESTAL", "ADC_GAIN", "TOT_PEDESTAL", "TOT_GAIN"}
expected order of column names matching the above indices (must match the indices above)
The order of these column names needs to match the indices listed in the header.
Definition at line 32 of file HcalReconConditions.h.
Referenced by HcalReconConditions().
IADC_GAIN
const unsigned int hcal::HcalReconConditions::IADC_GAIN = 1 static
column index for ADC threshold
Definition at line 25 of file HcalReconConditions.h.
Referenced by adcGain().
IADC_PEDESTAL
const unsigned int hcal::HcalReconConditions::IADC_PEDESTAL = 0 static
column index for ADC pedestal
Definition at line 23 of file HcalReconConditions.h.
Referenced by adcPedestal().
ITOT_GAIN
const unsigned int hcal::HcalReconConditions::ITOT_GAIN = 3 static
column index for TOT gain
Definition at line 29 of file HcalReconConditions.h.
Referenced by totGain().
ITOT_PEDESTAL
const unsigned int hcal::HcalReconConditions::ITOT_PEDESTAL = 2 static
column index for TOT pedestal
Definition at line 27 of file HcalReconConditions.h.
Referenced by totPedestal().
the_table_
const conditions::DoubleTableCondition& hcal::HcalReconConditions::the_table_ private
reference to the table of conditions storing the chip conditions
Definition at line 100 of file HcalReconConditions.h.
Referenced by adcGain(), adcPedestal(), HcalReconConditions(), totGain(), and totPedestal().
The documentation for this class was generated from the following files:
Hcal/include/Hcal/HcalReconConditions.h
Hcal/src/Hcal/HcalReconConditions.cxx