LDMX Software: eventdisplay::Display Class Reference
eventdisplay::Display Class Reference
Public Member Functions
Display (TEveManager *manager, bool verbose)
virtual ~Display ()
bool SetFile (const TString file)
void NextEvent ()
void GetECALRecHitsCollInput ()
void GetClustersCollInput ()
void GetTrackerHitsCollInput ()
void GetHCALRecHitsCollInput ()
void GetEcalSimParticlesCollInput ()
bool SetSimThresh ()
void ColorClusters ()
Private Member Functions
std::string getText (TGTextEntry *box) const
template<typename EventObjectType >
void draw (const std::string &name)
ClassDef (Display, 2)
Private Attributes
bool verbose_
framework::Event the_event_ {"display"}
Event bus for reading from input file.
std::unique_ptr< framework::EventFile > the_file_
Handle to input file we will be reading.
std::string clustersCollName_ = "ecalClusters"
name of ecal clusters collection in event tree
std::string ecalRecHitsCollName_ = "EcalRecHits"
name of ecalRecHits collection in event tree
std::string hcalRecHitsCollName_ = "HcalRecHits"
name of hcalRecHits collection in event tree
std::string trackerHitsCollName_ = "RecoilSimHits"
name of recoil hitss collection in event tree
std::string ecalSimParticlesCollName_ = "EcalScoringPlaneHits"
name of ecal sim particles collection in
EveDetectorGeometry * theDetector_ {nullptr}
drawing methods for the detector geometry
Objects objects_
drawing methods for event objects
TGTextEntry * textBoxClustersCollName_
TGTextEntry * textBoxSimThresh_
TGTextEntry * textBoxEcalRecHitsCollName_
TGTextEntry * textBoxHcalRecHitsCollName_
TGTextEntry * textBoxTrackerHitsCollName_
TGTextEntry * textBoxEcalScorePlaneBranch_
TEveManager * manager_ {nullptr}
event display manager
Detailed Description
Definition at line 36 of file Display.h.
Constructor & Destructor Documentation
Display()
eventdisplay::Display::Display (TEveManager * manager, bool verbose)
Constructor Builds window frame and and control panel. Imports geometry from EveDetectorGeometry.
Definition at line 13 of file Display.cxx.
    : TGMainFrame(gClient->GetRoot(), 320, 320), verbose_(verbose) {
  /****************************************************************************
   * GUI Set Up
   ***************************************************************************/
  SetWindowName("LDMX Event Display");
  manager_ = manager;
  TGLViewer* viewer = manager_->GetDefaultGLViewer();
  viewer->UseLightColorSet();
  if (verbose_) {
    std::cout << "[ Display ] : Drawing detector geometry... "
              << std::flush;
  }
  // when the first TGeoShape (a TGeoTube) is drawn, ROOT creates a default
  // geometry for this drawing and
  // prints an Info statement to std-out. Currently, I can't figure out how to
  // turn this behavior off.
  theDetector_ = new EveDetectorGeometry();
  manager_->AddEvent(new TEveEventManager("LDMX Detector", ""));
  manager_->AddElement(theDetector_->getECAL());
  manager_->AddElement(theDetector_->getHCAL());
  manager_->AddElement(theDetector_->getRecoilTracker());
  manager_->AddEvent(new TEveEventManager("LDMX Event", ""));
  if (verbose_) {
    std::cout << "done" << std::endl;
    std::cout << "[ Display ] : Constructing and linking buttons... "
              << std::flush;
  }
  TGVerticalFrame* contents = new TGVerticalFrame(this, 1000, 1200);
  TGHorizontalFrame* commandFrameNextEvent =
      new TGHorizontalFrame(contents, 100, 0);
  TGHorizontalFrame* commandFrameColorClusters =
      new TGHorizontalFrame(contents, 100, 0);
  TGHorizontalFrame* commandFrameEcalClusterBranch =
      new TGHorizontalFrame(contents, 100, 0);
  TGHorizontalFrame* commandFrameSimThresh =
      new TGHorizontalFrame(contents, 100, 0);
  TGHorizontalFrame* commandFrameEcalHitBranch =
      new TGHorizontalFrame(contents, 100, 0);
  TGHorizontalFrame* commandFrameHcalHitBranch =
      new TGHorizontalFrame(contents, 100, 0);
  TGHorizontalFrame* commandFrameTrackerHitsBranch =
      new TGHorizontalFrame(contents, 100, 0);
  TGHorizontalFrame* commandFrameEcalScorePlaneBranch =
      new TGHorizontalFrame(contents, 100, 0);
  TGButton* buttonColor =
      new TGTextButton(commandFrameColorClusters, "Color Clusters");
  commandFrameColorClusters->AddFrame(buttonColor,
                                      new TGLayoutHints(kLHintsExpandX));
  buttonColor->Connect("Pressed()", "eventdisplay::Display", this,
                       "ColorClusters()");
  TGButton* buttonNext =
      new TGTextButton(commandFrameNextEvent, "Next Event >>>");
  commandFrameNextEvent->AddFrame(buttonNext,
                                  new TGLayoutHints(kLHintsExpandX));
  buttonNext->Connect("Pressed()", "eventdisplay::Display", this, "NextEvent()");
  textBoxClustersCollName_ =
      new TGTextEntry(commandFrameEcalClusterBranch, new TGTextBuffer(100));
  commandFrameEcalClusterBranch->AddFrame(textBoxClustersCollName_,
                                          new TGLayoutHints(kLHintsExpandX));
  TGButton* buttonClusterName =
      new TGTextButton(commandFrameEcalClusterBranch, "Set Clusters Branch");
  commandFrameEcalClusterBranch->AddFrame(buttonClusterName,
                                          new TGLayoutHints(kLHintsExpandX));
  buttonClusterName->Connect("Pressed()", "eventdisplay::Display", this,
                             "GetClustersCollInput()");
  textBoxSimThresh_ =
      new TGTextEntry(commandFrameSimThresh, new TGTextBuffer(100));
  commandFrameSimThresh->AddFrame(textBoxSimThresh_,
                                  new TGLayoutHints(kLHintsExpandX));
  TGButton* buttonDrawThresh =
      new TGTextButton(commandFrameSimThresh, "Sim P [MeV] Threshold");
  commandFrameSimThresh->AddFrame(buttonDrawThresh,
                                  new TGLayoutHints(kLHintsExpandX));
  buttonDrawThresh->Connect("Pressed()", "eventdisplay::Display", this,
                            "SetSimThresh()");
  textBoxEcalRecHitsCollName_ =
      new TGTextEntry(commandFrameEcalHitBranch, new TGTextBuffer(100));
  commandFrameEcalHitBranch->AddFrame(textBoxEcalRecHitsCollName_,
                                      new TGLayoutHints(kLHintsExpandX));
  TGButton* buttonSetECALBranch =
      new TGTextButton(commandFrameEcalHitBranch, "Set ECAL RecHits Branch");
  commandFrameEcalHitBranch->AddFrame(buttonSetECALBranch,
                                      new TGLayoutHints(kLHintsExpandX));
  buttonSetECALBranch->Connect("Pressed()", "eventdisplay::Display", this,
                               "GetECALRecHitsCollInput()");
  textBoxHcalRecHitsCollName_ =
      new TGTextEntry(commandFrameHcalHitBranch, new TGTextBuffer(100));
  commandFrameHcalHitBranch->AddFrame(textBoxHcalRecHitsCollName_,
                                      new TGLayoutHints(kLHintsExpandX));
  TGButton* buttonSetHCALBranch =
      new TGTextButton(commandFrameHcalHitBranch, "Set HCAL RecHits Branch");
  commandFrameHcalHitBranch->AddFrame(buttonSetHCALBranch,
                                      new TGLayoutHints(kLHintsExpandX));
  buttonSetHCALBranch->Connect("Pressed()", "eventdisplay::Display", this,
                               "GetHCALRecHitsCollInput()");
  textBoxTrackerHitsCollName_ =
      new TGTextEntry(commandFrameTrackerHitsBranch, new TGTextBuffer(100));
  commandFrameTrackerHitsBranch->AddFrame(textBoxTrackerHitsCollName_,
                                          new TGLayoutHints(kLHintsExpandX));
  TGButton* buttonSetRecoilBranch =
      new TGTextButton(commandFrameTrackerHitsBranch, "Set Recoil Sims Branch");
  commandFrameTrackerHitsBranch->AddFrame(buttonSetRecoilBranch,
                                          new TGLayoutHints(kLHintsExpandX));
  buttonSetRecoilBranch->Connect("Pressed()", "eventdisplay::Display", this,
                                 "GetTrackerHitsCollInput()");
  textBoxEcalScorePlaneBranch_ =
      new TGTextEntry(commandFrameEcalScorePlaneBranch, new TGTextBuffer(100));
  commandFrameEcalScorePlaneBranch->AddFrame(textBoxEcalScorePlaneBranch_,
                                             new TGLayoutHints(kLHintsExpandX));
  TGButton* buttonSetSimParticlesBranch = new TGTextButton(
      commandFrameEcalScorePlaneBranch, "Set Ecal SP Branch");
  commandFrameEcalScorePlaneBranch->AddFrame(buttonSetSimParticlesBranch,
                                             new TGLayoutHints(kLHintsExpandX));
  buttonSetSimParticlesBranch->Connect("Pressed()", "eventdisplay::Display", this,
                                       "GetEcalSimParticlesCollInput()");
  // Order from top to bottom here
  contents->AddFrame(commandFrameEcalHitBranch,
                     new TGLayoutHints(kLHintsExpandX | kLHintsExpandY));
  contents->AddFrame(commandFrameHcalHitBranch,
                     new TGLayoutHints(kLHintsExpandX | kLHintsExpandY));
  contents->AddFrame(commandFrameTrackerHitsBranch,
                     new TGLayoutHints(kLHintsExpandX | kLHintsExpandY));
  contents->AddFrame(commandFrameEcalScorePlaneBranch,
                     new TGLayoutHints(kLHintsExpandX | kLHintsExpandY));
  contents->AddFrame(commandFrameEcalClusterBranch,
                     new TGLayoutHints(kLHintsExpandX | kLHintsExpandY));
  contents->AddFrame(commandFrameNextEvent,
                     new TGLayoutHints(kLHintsExpandX | kLHintsExpandY));
  contents->AddFrame(commandFrameColorClusters,
                     new TGLayoutHints(kLHintsExpandX | kLHintsExpandY));
  contents->AddFrame(commandFrameSimThresh,
                     new TGLayoutHints(kLHintsExpandX | kLHintsExpandY));
  AddFrame(contents, new TGLayoutHints(kLHintsExpandX | kLHintsExpandY));
  MapSubwindows();
  Resize(GetDefaultSize());
  MapWindow();
  manager_->FullRedraw3D(kTRUE);
  if (verbose_) {
    std::cout << "done" << std::endl;
  }
}
References eventdisplay::EveDetectorGeometry::getECAL(), eventdisplay::EveDetectorGeometry::getHCAL(), eventdisplay::EveDetectorGeometry::getRecoilTracker(), manager_, and theDetector_.
~Display()
virtual eventdisplay::Display::~Display () inline virtual
Destructor Deletes hanging pointers from constructor and closes the TFile.
Definition at line 49 of file Display.h.
                     {
    // need to delete EventFile so that it is deleted before Event
    the_file_.reset(nullptr);
    delete theDetector_;
    delete textBoxClustersCollName_;
    delete textBoxSimThresh_;
    delete textBoxEcalRecHitsCollName_;
    delete textBoxHcalRecHitsCollName_;
    delete textBoxTrackerHitsCollName_;
    delete textBoxEcalScorePlaneBranch_;
    delete manager_;
  }
References manager_, the_file_, and theDetector_.
Member Function Documentation
ColorClusters()
void eventdisplay::Display::ColorClusters ()
Colors cluster objects and redraws.
Definition at line 278 of file Display.cxx.
{
  objects_.ColorClusters();
  manager_->RegisterRedraw3D();
  manager_->FullRedraw3D(kFALSE, kTRUE);
}
References eventdisplay::Objects::ColorClusters(), manager_, and objects_.
draw()
template<typename EventObjectType > void eventdisplay::Display::draw (const std::string & name) inline private
Templated draw method
Definition at line 133 of file Display.h.
{
    try {
      auto event_object{the_event_.getObject<EventObjectType>(name)};
      objects_.draw(event_object);
      if (verbose_) {
        std::cout << "[ Display ] : Loaded '" << name
          << "' into memory as a EVE object." << std::endl;
      }
    } catch(const framework::exception::Exception& e) {
      std::cerr << "[ Display ] : Unable to draw an event object." << std::endl;
      std::cerr << "[" << e.name() << "] : " << e.message() << "\n"
        << "  at " << e.module() << ":" << e.line() << " in "
        << e.function() << std::endl;
    }
  }
References eventdisplay::Objects::draw(), framework::exception::Exception::function(), framework::Event::getObject(), framework::exception::Exception::line(), framework::exception::Exception::message(), framework::exception::Exception::module(), framework::exception::Exception::name(), objects_, and the_event_.
GetClustersCollInput()
void eventdisplay::Display::GetClustersCollInput ()
Gets clusters collection name from text box
Definition at line 251 of file Display.cxx.
{
  clustersCollName_ = getText(textBoxClustersCollName_);
}
References clustersCollName_, and getText().
GetECALRecHitsCollInput()
void eventdisplay::Display::GetECALRecHitsCollInput ()
Gets ecalRecHits collection name from text box
Definition at line 239 of file Display.cxx.
{
  ecalRecHitsCollName_ = getText(textBoxEcalRecHitsCollName_);
}
References ecalRecHitsCollName_, and getText().
GetEcalSimParticlesCollInput()
void eventdisplay::Display::GetEcalSimParticlesCollInput ()
Gets ECAL Sim Particles Branch name from text box
Definition at line 255 of file Display.cxx.
{
  ecalSimParticlesCollName_ = getText(textBoxEcalScorePlaneBranch_);
}
References ecalSimParticlesCollName_, and getText().
GetHCALRecHitsCollInput()
void eventdisplay::Display::GetHCALRecHitsCollInput ()
Gets hcalRecHits collection name from text box
Definition at line 243 of file Display.cxx.
{
  hcalRecHitsCollName_ = getText(textBoxHcalRecHitsCollName_);
}
References getText(), and hcalRecHitsCollName_.
getText()
std::string eventdisplay::Display::getText (TGTextEntry * box) const inline private
Get the text from the input text box
Definition at line 125 of file Display.h.
{
    return box->GetText();
  }
Referenced by GetClustersCollInput(), GetECALRecHitsCollInput(), GetEcalSimParticlesCollInput(), GetHCALRecHitsCollInput(), and GetTrackerHitsCollInput().
GetTrackerHitsCollInput()
void eventdisplay::Display::GetTrackerHitsCollInput ()
Gets trackerHits collection name from text box
Definition at line 247 of file Display.cxx.
{
  trackerHitsCollName_ = getText(textBoxTrackerHitsCollName_);
}
References getText(), and trackerHitsCollName_.
NextEvent()
void eventdisplay::Display::NextEvent ()
Goes forward one event unless the current event number equals the maximum event number.
Definition at line 206 of file Display.cxx.
{
  if (the_file_->nextEvent(false)) {
    manager_->GetCurrentEvent()->DestroyElements();
    objects_.Initialize();
    if (verbose_) {
      std::cout << "[ Display ] : Loading new event " << "... " << std::endl;
    }
    //draw<std::vector<ldmx::EcalHit>>(ecalRecHitsCollName_);
    //draw<std::vector<ldmx::HcalHit>>(hcalRecHitsCollName_);
    //draw<std::vector<ldmx::EcalCluster>>(clustersCollName_);
    draw<std::vector<ldmx::SimTrackerHit>>(trackerHitsCollName_);
    draw<std::vector<ldmx::SimTrackerHit>>(ecalSimParticlesCollName_);
    draw<std::vector<ldmx::SimCalorimeterHit>>("EcalSimHits");
    draw<std::vector<ldmx::SimCalorimeterHit>>("HcalSimHits");
    draw<std::map<int,ldmx::SimParticle>>("SimParticles");
    if (verbose_) std::cout << "[ Display ] : Done loading event objects into EVE objects." << std::endl;
    manager_->AddElement(objects_.getSimObjects());
    manager_->AddElement(objects_.getRecObjects());
    manager_->Redraw3D(kFALSE);
    if (verbose_) std::cout << "[ Display ] : Done redrawing." << std::endl;
  } else {
    std::cout << "[ Display ] : Already at last event in file."
              << std::endl;
    return;
  }
}
References ecalSimParticlesCollName_, eventdisplay::Objects::getRecObjects(), eventdisplay::Objects::getSimObjects(), eventdisplay::Objects::Initialize(), manager_, objects_, the_file_, and trackerHitsCollName_.
SetFile()
bool eventdisplay::Display::SetFile (const TString file)
Opens input file and attempts to obtain the necessary information from it.
Attempts to import the event objects from the event tree using the 'Get...' methods below.
Parameters
file name of file with events
Returns
true if successfully opened file and found tree named eventTreeName_
false unable to open file or find tree named eventTreeName_
Definition at line 183 of file Display.cxx.
{
  try {
    framework::config::Parameters file_config;
    file_config.addParameter("tree_name",std::string("LDMX_Events"));
    the_file_ = std::make_unique<framework::EventFile>(file_config,file.Data());
    the_file_->setupEvent(&the_event_);
    if (verbose_) {
      std::cout << "[ Display ] : Input root file opened successfully."
                << std::endl;
    }
  } catch (const framework::exception::Exception& e) {
    std::cerr << "[ Display ] : Input root file cannot be opened." << std::endl;
    std::cerr << "[" << e.name() << "] : " << e.message() << "\n"
      << "  at " << e.module() << ":" << e.line() << " in "
      << e.function() << "\nStack trace: " << std::endl
      << e.stackTrace();
    return false;
  }
  return true;
}
References framework::config::Parameters::addParameter(), framework::exception::Exception::function(), framework::exception::Exception::line(), framework::exception::Exception::message(), framework::exception::Exception::module(), framework::exception::Exception::name(), framework::exception::Exception::stackTrace(), the_event_, and the_file_.
Referenced by main().
SetSimThresh()
bool eventdisplay::Display::SetSimThresh ()
Sets threshold energy from a SimParticle to be drawn from text box. Re-draws the display.
Returns
bool success check
Definition at line 259 of file Display.cxx.
{
  double thresh = atof(textBoxSimThresh_->GetText());
  if (thresh == 0 && std::string(textBoxSimThresh_->GetText()) != "0") {
    std::cout << "[ Display ] : Invalid sim energy threshold entered: \""
              << textBoxSimThresh_->GetText() << "\"" << std::endl;
    return false;
  } else if (verbose_) {
    std::cout << "[ Display ] : Setting SimParticle energy threshold to "
              << thresh << std::endl;
  }
  objects_.SetSimThresh(thresh);
  manager_->RegisterRedraw3D();
  manager_->FullRedraw3D(kFALSE, kTRUE);
  return true;
}
References manager_, objects_, and eventdisplay::Objects::SetSimThresh().
Member Data Documentation
clustersCollName_
std::string eventdisplay::Display::clustersCollName_ = "ecalClusters" private
name of ecal clusters collection in event tree
Definition at line 161 of file Display.h.
Referenced by GetClustersCollInput().
ecalRecHitsCollName_
std::string eventdisplay::Display::ecalRecHitsCollName_ = "EcalRecHits" private
name of ecalRecHits collection in event tree
Definition at line 163 of file Display.h.
Referenced by GetECALRecHitsCollInput().
ecalSimParticlesCollName_
std::string eventdisplay::Display::ecalSimParticlesCollName_ = "EcalScoringPlaneHits" private
name of ecal sim particles collection in
Definition at line 169 of file Display.h.
Referenced by GetEcalSimParticlesCollInput(), and NextEvent().
hcalRecHitsCollName_
std::string eventdisplay::Display::hcalRecHitsCollName_ = "HcalRecHits" private
name of hcalRecHits collection in event tree
Definition at line 165 of file Display.h.
Referenced by GetHCALRecHitsCollInput().
manager_
TEveManager* eventdisplay::Display::manager_ {nullptr} private
event display manager
Definition at line 185 of file Display.h.
Referenced by ColorClusters(), Display(), NextEvent(), SetSimThresh(), and ~Display().
objects_
Objects eventdisplay::Display::objects_ private
drawing methods for event objects
Definition at line 175 of file Display.h.
Referenced by ColorClusters(), draw(), NextEvent(), and SetSimThresh().
textBoxClustersCollName_
TGTextEntry* eventdisplay::Display::textBoxClustersCollName_ private
Definition at line 177 of file Display.h.
textBoxEcalRecHitsCollName_
TGTextEntry* eventdisplay::Display::textBoxEcalRecHitsCollName_ private
Definition at line 179 of file Display.h.
textBoxEcalScorePlaneBranch_
TGTextEntry* eventdisplay::Display::textBoxEcalScorePlaneBranch_ private
Definition at line 182 of file Display.h.
textBoxHcalRecHitsCollName_
TGTextEntry* eventdisplay::Display::textBoxHcalRecHitsCollName_ private
Definition at line 180 of file Display.h.
textBoxSimThresh_
TGTextEntry* eventdisplay::Display::textBoxSimThresh_ private
Definition at line 178 of file Display.h.
textBoxTrackerHitsCollName_
TGTextEntry* eventdisplay::Display::textBoxTrackerHitsCollName_ private
Definition at line 181 of file Display.h.
the_event_
framework::Event eventdisplay::Display::the_event_ {"display"} private
Event bus for reading from input file.
Definition at line 155 of file Display.h.
Referenced by draw(), and SetFile().
the_file_
std::unique_ptr<framework::EventFile> eventdisplay::Display::the_file_ private
Handle to input file we will be reading.
Definition at line 158 of file Display.h.
Referenced by NextEvent(), SetFile(), and ~Display().
theDetector_
EveDetectorGeometry* eventdisplay::Display::theDetector_ {nullptr} private
drawing methods for the detector geometry
Definition at line 172 of file Display.h.
Referenced by Display(), and ~Display().
trackerHitsCollName_
std::string eventdisplay::Display::trackerHitsCollName_ = "RecoilSimHits" private
name of recoil hitss collection in event tree
Definition at line 167 of file Display.h.
Referenced by GetTrackerHitsCollInput(), and NextEvent().
verbose_
bool eventdisplay::Display::verbose_ private
Definition at line 152 of file Display.h.
The documentation for this class was generated from the following files:
EventDisplay/include/EventDisplay/Display.h
EventDisplay/src/EventDisplay/Display.cxx