LDMX Software: packing::rawdatafile::EventPacket Class Reference
packing::rawdatafile::EventPacket Class Reference
#include <EventPacket.h>
Public Member Functions
EventPacket ()=default
default constructor for reading
EventPacket (uint32_t id, const std::map< uint16_t, std::vector< uint32_t > > &unwrapped_subsys_data)
define event id for reading
std::vector< uint32_t > header () const
Get the header words.
std::vector< uint32_t > tail () const
Get the tail words.
const uint32_t & id () const
std::vector< SubsystemPacket > & data ()
utility::Reader & read (utility::Reader &r)
utility::Writer & write (utility::Writer &w) const
utility::CRC & add (utility::CRC &c) const
Private Attributes
uint32_t id_
uint16_t event_length_in_words_
std::vector< SubsystemPacket > subsys_data_
bool crc_ok_
uint32_t crc_
Detailed Description
Event Packet structure
Definition at line 17 of file EventPacket.h.
Constructor & Destructor Documentation
EventPacket()
packing::rawdatafile::EventPacket::EventPacket (uint32_t id, const std::map< uint16_t, std::vector< uint32_t > > & unwrapped_subsys_data)
define event id for reading
Definition at line 9 of file EventPacket.cxx.
  : id_{id}, event_length_in_words_{0} {
  crc_ok_ = true;
  utility::CRC crc;
  for (auto const&[subsys_id, subsys_data] : unwrapped_subsys_data) {
    subsys_data_.emplace_back(id_,subsys_id,subsys_data);
    auto& subsys = subsys_data_.back();
    crc << subsys;
    event_length_in_words_ += subsys.header().size()+subsys.data().size()+subsys.tail().size();
  }
  crc_ = crc.get();
}
References packing::utility::CRC::get().
Member Function Documentation
add()
utility::CRC & packing::rawdatafile::EventPacket::add (utility::CRC & c) const
add the event packet to the input crc
Definition at line 57 of file EventPacket.cxx.
{
  std::vector<uint32_t> h{header()},t{tail()};
  c << h << subsys_data_ << t;
  return c;
}
References header(), and tail().
data()
std::vector< SubsystemPacket > & packing::rawdatafile::EventPacket::data () inline
Definition at line 32 of file EventPacket.h.
{ return subsys_data_; }
header()
std::vector< uint32_t > packing::rawdatafile::EventPacket::header () const
Get the header words.
Definition at line 25 of file EventPacket.cxx.
{
  uint32_t word = ((subsys_data_.size() & utility::mask<16>) << 16)
    + ((event_length_in_words_ & utility::mask<15>) << 1)
    + crc_ok_;
  return { id_ , word };
}
Referenced by add(), and write().
id()
const uint32_t & packing::rawdatafile::EventPacket::id () const inline
Definition at line 31 of file EventPacket.h.
{ return id_; }
read()
utility::Reader & packing::rawdatafile::EventPacket::read (utility::Reader & r)
read the event packet from the input reader
Definition at line 36 of file EventPacket.cxx.
{
  r >> id_;
  uint32_t word;
  r >> word;
  uint16_t num_subsys = (word >> 16) & utility::mask<16>;
  event_length_in_words_ = (word >> 1) & utility::mask<15>;
  crc_ok_ = word & utility::mask<1>;
  r.read(subsys_data_, num_subsys);
  r >> crc_;
}
References packing::utility::Reader::read().
tail()
std::vector< uint32_t > packing::rawdatafile::EventPacket::tail () const
Get the tail words.
Definition at line 32 of file EventPacket.cxx.
{
  return { crc_ };
}
Referenced by add(), and write().
write()
utility::Writer & packing::rawdatafile::EventPacket::write (utility::Writer & w) const
write the event packet to the input writer
Definition at line 51 of file EventPacket.cxx.
{
  std::vector<uint32_t> h{header()},t{tail()};
  w << h << subsys_data_ << t;
  return w;
}
References header(), and tail().
Member Data Documentation
crc_
uint32_t packing::rawdatafile::EventPacket::crc_ private
Definition at line 53 of file EventPacket.h.
crc_ok_
bool packing::rawdatafile::EventPacket::crc_ok_ private
Definition at line 52 of file EventPacket.h.
event_length_in_words_
uint16_t packing::rawdatafile::EventPacket::event_length_in_words_ private
Definition at line 50 of file EventPacket.h.
id_
uint32_t packing::rawdatafile::EventPacket::id_ private
Definition at line 49 of file EventPacket.h.
subsys_data_
std::vector<SubsystemPacket> packing::rawdatafile::EventPacket::subsys_data_ private
Definition at line 51 of file EventPacket.h.
The documentation for this class was generated from the following files:
Packing/include/Packing/RawDataFile/EventPacket.h
Packing/src/Packing/RawDataFile/EventPacket.cxx