LDMX Software: biasing::TargetDarkBremFilter Class Reference
biasing::TargetDarkBremFilter Class Reference
#include <TargetDarkBremFilter.h>
Public Member Functions
TargetDarkBremFilter (const std::string &name, framework::config::Parameters &parameters)
~TargetDarkBremFilter ()
std::vector< simcore::TYPE > getTypes () final override
void stepping (const G4Step *step)
Public Member Functions inherited from simcore::UserAction
UserAction (const std::string &name, framework::config::Parameters &parameters)
virtual ~UserAction ()
Destructor.
virtual void BeginOfEventAction (const G4Event *)
virtual void EndOfEventAction (const G4Event *)
virtual void BeginOfRunAction (const G4Run *)
virtual void EndOfRunAction (const G4Run *)
virtual void PreUserTrackingAction (const G4Track *)
virtual void PostUserTrackingAction (const G4Track *)
virtual void stepping (const G4Step *)
virtual G4ClassificationOfNewTrack ClassifyNewTrack (const G4Track *, const G4ClassificationOfNewTrack &cl)
virtual void NewStage ()
virtual void PrepareNewEvent ()
virtual std::vector< TYPE > getTypes ()=0
Private Member Functions
bool isOutsideTargetRegion (const G4VPhysicalVolume *vol) const
bool isOutsideTargetRegion (const G4LogicalVolume *vol) const
void AbortEvent (const std::string &reason) const
Private Attributes
double threshold_
Additional Inherited Members
Static Public Member Functions inherited from simcore::UserAction
static void declare (const std::string &className, UserActionBuilder *builder)
Static Protected Member Functions inherited from simcore::UserAction
static UserEventInformation * getEventInfo ()
Protected Attributes inherited from simcore::UserAction
std::string name_ {""}
Name of the UserAction.
framework::config::Parameters parameters_
The set of parameters used to configure this class.
Detailed Description
This class is meant to filter for events that produce a dark brem matching originating in the target and matching the following parameters.
 threshold: minimum energy [MeV] A' needs to have
See also
TargetBremFilter This filter is designed similar to the target brem filter where we check the secondaries of the primary electron if it is stopping within the target or if it is leaving the target region.
Definition at line 44 of file TargetDarkBremFilter.h.
Constructor & Destructor Documentation
TargetDarkBremFilter()
TargetDarkBremFilter::TargetDarkBremFilter (const std::string & name, framework::config::Parameters & parameters)
Class constructor.
Retrieve the necessary configuration parameters
Definition at line 18 of file TargetDarkBremFilter.cxx.
    : simcore::UserAction(name, parameters) {
  threshold_ = parameters.getParameter<double>("threshold");
}
References framework::config::Parameters::getParameter(), and threshold_.
~TargetDarkBremFilter()
biasing::TargetDarkBremFilter::~TargetDarkBremFilter () inline
Class destructor.
Definition at line 57 of file TargetDarkBremFilter.h.
{}
Member Function Documentation
AbortEvent()
void TargetDarkBremFilter::AbortEvent (const std::string & reason) const private
Helper to abort an event with a message
Tells the RunManger to abort the current event after displaying the input message.
Parameters
[in] reason reason for aborting the event
Definition at line 117 of file TargetDarkBremFilter.cxx.
{
  if (G4RunManager::GetRunManager()->GetVerboseLevel() > 1) {
    std::cout << "[ TargetDarkBremFilter ]: "
              << "("
              << G4EventManager::GetEventManager()
                     ->GetConstCurrentEvent()
                     ->GetEventID()
              << ") " << reason << " Aborting event." << std::endl;
  }
  G4RunManager::GetRunManager()->AbortEvent();
  return;
}
Referenced by stepping().
getTypes()
std::vector< simcore::TYPE > biasing::TargetDarkBremFilter::getTypes () inline final override virtual
Get the types of actions this class can do
Returns
list of action types this class does
Implements simcore::UserAction.
Definition at line 64 of file TargetDarkBremFilter.h.
{
    return {simcore::TYPE::STEPPING};
  }
isOutsideTargetRegion() [1/2]
bool biasing::TargetDarkBremFilter::isOutsideTargetRegion (const G4LogicalVolume * vol) const inline private
Check if the volume is outside the target region
Note
will return true if vol is nullptr.
Parameters
[in] vol G4LogicalVolume to check region
Returns
true if vol is outside target region or nullptr or doesn't have a region
Definition at line 103 of file TargetDarkBremFilter.h.
{
    if (!vol) return true;
    auto region = vol->GetRegion();
    return region ? (region->GetName().compareTo("target") != 0) : true;
  }
isOutsideTargetRegion() [2/2]
bool biasing::TargetDarkBremFilter::isOutsideTargetRegion (const G4VPhysicalVolume * vol) const inline private
Check if the volume is outside the target region
Note
will return true if vol is nullptr
Parameters
[in] vol G4VPhysicalVolume to check region
Returns
true if vol is outside target region or nullptr
Definition at line 90 of file TargetDarkBremFilter.h.
{
    return vol ? isOutsideTargetRegion(vol->GetLogicalVolume()) : true;
  }
References isOutsideTargetRegion().
Referenced by isOutsideTargetRegion(), and stepping().
stepping()
void TargetDarkBremFilter::stepping (const G4Step * step) virtual
Looking for A' while primary is stepping.
We make sure that the current track is the primary electron that is within the target region. Then if the track is either stopped or leaving the target region, we look through its secondaries for a good A'.
Parameters
[in] step current G4Step
check on first step of A' to see if it originated in correct volume this needs to be here because sometimes the electron dark brems in the tagger and misses the target completely std::cout << "[ TargetDarkBremFilter ] : " << "(" << G4EventManager::GetEventManager() ->GetConstCurrentEvent() ->GetEventID() << ") " << "A' originated in " << track->GetLogicalVolumeAtVertex()->GetName() << std::endl;
Reimplemented from simcore::UserAction.
Definition at line 24 of file TargetDarkBremFilter.cxx.
{
  // don't process if event is already aborted
  if (G4EventManager::GetEventManager()->GetConstCurrentEvent()->IsAborted())
    return;
  // Get the track associated with this step.
  auto track{step->GetTrack()};
  // Leave if track is not an electron
  auto particle_def{track->GetParticleDefinition()};
  if (particle_def != G4Electron::Electron()) {
    if (particle_def == simcore::darkbrem::G4APrime::APrime() and
        track->GetCurrentStepNumber() == 1) {
      if (isOutsideTargetRegion(track->GetLogicalVolumeAtVertex()))
        AbortEvent("A' was not created within target.");
    }  // first step of A'
    return;
  }
  // Leave if track is not primary
  if (track->GetParentID() != 0) return;
  // Leave if track is not in target region
  if (isOutsideTargetRegion(track->GetVolume())) return;
  if (isOutsideTargetRegion(track->GetNextVolume())  // leaving target region
      or
      track->GetTrackStatus() == fStopAndKill  // stopping within target region
      or track->GetKineticEnergy() == 0.       // stopping within target region
  ) {
    // Get the electron secondries
    const std::vector<G4Track*>* secondaries{step->GetSecondary()};
    if (not secondaries or secondaries->size() == 0) {
      AbortEvent("Primary electron did not create secondaries.");
      return;
    } else {
      // check secondaries to see if we made a dark brem
      for (auto& secondary_track : *secondaries) {
        if (secondary_track->GetParticleDefinition() ==
            simcore::darkbrem::G4APrime::APrime()) {
          // we found an A', woo-hoo!
          if (secondary_track->GetTotalEnergy() < threshold_) {
            AbortEvent(
                "A' was not created with total energy above input threshold.");
            return;
          }
          if (isOutsideTargetRegion(secondary_track->GetVolume())) {
            AbortEvent("A' was not created within target.");
            return;
          }
          /* debug message
          std::cout << "[ TargetDarkBremFilter ] : "
              << "(" <<
          G4EventManager::GetEventManager()->GetConstCurrentEvent()->GetEventID()
          << ") "
              << "Found an A' weighted " << secondary_track->GetWeight()
              << " originating in " <<
          secondary_track->GetVolume()->GetLogicalVolume()->GetName()
              << " with energy " << secondary_track->GetTotalEnergy() << " MeV."
              << std::endl;
           */
          // we found a good A', so we can leave
          return;
        }  // this secondary is an A'
      }    // loop through secondaries
    }      // are there secondaries to loop through
    // got here without finding A'
    AbortEvent("Primary electron did not create A'.");
    return;
  }  // should check secondaries of primary
  // get here if we are the primary in the target region,
  //  but shouldn't check the secondaries yet
  return;
}
References AbortEvent(), simcore::darkbrem::G4APrime::APrime(), isOutsideTargetRegion(), and threshold_.
Member Data Documentation
threshold_
double biasing::TargetDarkBremFilter::threshold_ private
Minimum energy [MeV] that the A' should have to keep the event.
Also used by PartialEnergySorter to determine which tracks should be processed first.
Parameter Name: 'threshold'
Definition at line 128 of file TargetDarkBremFilter.h.
Referenced by stepping(), and TargetDarkBremFilter().
The documentation for this class was generated from the following files:
Biasing/include/Biasing/TargetDarkBremFilter.h
Biasing/src/Biasing/TargetDarkBremFilter.cxx