LDMX Software: simcore::EcalHitIO Class Reference
simcore::EcalHitIO Class Reference
Provides hit readout for simulated ECal detector.
#include <EcalHitIO.h>
Public Types
typedef std::pair< int, int > LayerCellPair
Public Member Functions
EcalHitIO (ConditionsInterface &ci)
~EcalHitIO ()
void configure (const framework::config::Parameters &ps)
void writeHitsCollection (G4CalorimeterHitsCollection *hc, std::vector< ldmx::SimCalorimeterHit > &outputColl)
void setEnableHitContribs (bool enableHitContribs)
void setCompressHitContribs (bool compressHitContribs)
Private Attributes
ConditionsInterface & conditionsIntf_
ConditionsInterface.
bool enableHitContribs_ {true}
bool compressHitContribs_ {true}
Detailed Description
Provides hit readout for simulated ECal detector.
Note
This class uses the EcalHexReadout to transform the G4CalorimeterHit hits collection into a collection of SimCalorimeterHit objects assigned to hexagonal cells by their ID and positions. Energy depositions in the same cells are combined together into single hits.
It can be run in three modes:
Compressed hit contributions combined by matching SimParticle and PDG code (default mode)
Full hit contributions with one record per step (when compressHitContribs_ is false)
No hit contribution information where energy is combined but vectors are not filled (when enableHitContribs_ is false)
Definition at line 37 of file EcalHitIO.h.
Member Typedef Documentation
LayerCellPair
typedef std::pair<int, int> simcore::EcalHitIO::LayerCellPair
Layer-cell pair.
Definition at line 42 of file EcalHitIO.h.
Constructor & Destructor Documentation
EcalHitIO()
simcore::EcalHitIO::EcalHitIO (ConditionsInterface & ci) inline
Class constructor.
Definition at line 48 of file EcalHitIO.h.
: conditionsIntf_(ci) {}
~EcalHitIO()
simcore::EcalHitIO::~EcalHitIO () inline
Class destructor.
Definition at line 53 of file EcalHitIO.h.
{}
Member Function Documentation
configure()
void simcore::EcalHitIO::configure (const framework::config::Parameters & ps)
Configure the EcalHitIO using the passed parameters
Definition at line 14 of file EcalHitIO.cxx.
{
  enableHitContribs_ = ps.getParameter<bool>("enableHitContribs");
  compressHitContribs_ = ps.getParameter<bool>("compressHitContribs");
}
References compressHitContribs_, enableHitContribs_, and framework::config::Parameters::getParameter().
Referenced by simcore::persist::RootPersistencyManager::RootPersistencyManager().
setCompressHitContribs()
void simcore::EcalHitIO::setCompressHitContribs (bool compressHitContribs) inline
Set whether hit contributions should be compressed by particle and PDG code.
Parameters
compressHitContribs True to compress hit contribution information.
Definition at line 81 of file EcalHitIO.h.
{
    compressHitContribs_ = compressHitContribs;
  }
References compressHitContribs_.
setEnableHitContribs()
void simcore::EcalHitIO::setEnableHitContribs (bool enableHitContribs) inline
Set whether hit contributions should be enabled for the output hits.
Parameters
enableHitContribs True to enable hit contributions.
Definition at line 72 of file EcalHitIO.h.
{
    enableHitContribs_ = enableHitContribs;
  }
References enableHitContribs_.
writeHitsCollection()
void simcore::EcalHitIO::writeHitsCollection (G4CalorimeterHitsCollection * hc, std::vector< ldmx::SimCalorimeterHit > & outputColl)
Write out a Geant4 hits collection to the provided ROOT array.
Parameters
hc The input hits collection.
outputColl The output collection in ROOT.
Assign XY position to the hit using the ECal hex readout. Z position is set from the original hit, which should be the middle of the sensor.
Definition at line 19 of file EcalHitIO.cxx.
{
  const ldmx::EcalHexReadout& hexReadout =
      conditionsIntf_.getCondition<ldmx::EcalHexReadout>(
          ldmx::EcalHexReadout::CONDITIONS_OBJECT_NAME);
  // get ancestral mapping of tracks
  auto trackMap{UserTrackingAction::getUserTrackingAction()->getTrackMap()};
  int nHits = hc->GetSize();
  std::map<int, ldmx::SimCalorimeterHit> hitMap;
  // Loop over input hits from Geant4.
  for (int iHit = 0; iHit < nHits; iHit++) {
    // Get the hit and its ID.
    G4CalorimeterHit* g4hit = (G4CalorimeterHit*)hc->GetHit(iHit);
    int hitID = g4hit->getID();
    // See if hit exists in map already.
    std::map<int, ldmx::SimCalorimeterHit>::iterator it = hitMap.find(hitID);
    // Is it a new hit?
    if (it == hitMap.end()) {
      // Create sim hit and assign the ID.
      hitMap[hitID] = ldmx::SimCalorimeterHit();
      hitMap[hitID].setID(hitID);
      double x, y, z;
      hexReadout.getCellAbsolutePosition(hitID, x, y, z);
      hitMap[hitID].setPosition(x, y, z);
    }
    // Get info from the G4 hit.
    float edep = g4hit->getEdep();
    float time = g4hit->getTime();
    int pdgCode = g4hit->getPdgCode();
    // Is hit contrib output enabled?
    if (enableHitContribs_) {
      // Find the SimParticle associated with this hit.
      int trackID = g4hit->getTrackID();
      // Find if there is an existing hit contrib.
      int contribIndex = hitMap[hitID].findContribIndex(trackID, pdgCode);
      // Is contrib output being compressed and a record exists for this
      // SimParticle and PDG code?
      if (compressHitContribs_ && contribIndex != -1) {
        // Update an existing hit contrib.
        hitMap[hitID].updateContrib(contribIndex, edep, time);
      } else {
        // Add a hit contrib because all steps are being saved or there is not
        // an existing record.
        hitMap[hitID].addContrib(trackMap->findIncident(trackID), trackID,
                                 pdgCode, edep, time);
      }
    } else {
      // Hit contributions are not being saved so manually increment the edep
      // and set time.
      hitMap[hitID].setEdep(hitMap[hitID].getEdep() + edep);
      if (time < hitMap[hitID].getTime() || hitMap[hitID].getTime() == 0) {
        hitMap[hitID].setTime(time);
      }
    }  // contrib output enabled or not
  }    // loop through geant4 hits
  // copy aggregated hits into output collection
  outputColl.clear();
  for (auto& mapHit : hitMap) {
    outputColl.push_back(mapHit.second);
  }
  return;
}
References compressHitContribs_, conditionsIntf_, enableHitContribs_, ldmx::EcalHexReadout::getCellAbsolutePosition(), simcore::ConditionsInterface::getCondition(), simcore::G4CalorimeterHit::getEdep(), simcore::G4CalorimeterHit::getID(), simcore::G4CalorimeterHit::getPdgCode(), simcore::G4CalorimeterHit::getTime(), simcore::G4CalorimeterHit::getTrackID(), simcore::UserTrackingAction::getTrackMap(), and simcore::UserTrackingAction::getUserTrackingAction().
Referenced by simcore::persist::RootPersistencyManager::writeHitsCollections().
Member Data Documentation
compressHitContribs_
bool simcore::EcalHitIO::compressHitContribs_ {true} private
Enable compression of hit contributions by SimParticle and PDG code.
Definition at line 97 of file EcalHitIO.h.
Referenced by configure(), setCompressHitContribs(), and writeHitsCollection().
conditionsIntf_
ConditionsInterface& simcore::EcalHitIO::conditionsIntf_ private
ConditionsInterface.
Definition at line 87 of file EcalHitIO.h.
Referenced by writeHitsCollection().
enableHitContribs_
bool simcore::EcalHitIO::enableHitContribs_ {true} private
Enable hit contribution output.
Definition at line 92 of file EcalHitIO.h.
Referenced by configure(), setEnableHitContribs(), and writeHitsCollection().
The documentation for this class was generated from the following files:
SimCore/include/SimCore/EcalHitIO.h
SimCore/src/SimCore/EcalHitIO.cxx