LDMX Software: ldmx::EcalCluster Class Reference
ldmx::EcalCluster Class Reference
Stores cluster information from the ECal.
#include <EcalCluster.h>
Public Member Functions
EcalCluster ()
virtual ~EcalCluster ()
void Print () const
void Clear ()
void addHits (const std::vector< const ldmx::EcalHit * > hitsVec)
void setEnergy (double energy)
void setNHits (int nHits)
void setIDs (std::vector< unsigned int > &hitIDs)
void setCentroidXYZ (double x, double y, double z)
double getEnergy () const
int getNHits () const
double getCentroidX () const
double getCentroidY () const
double getCentroidZ () const
const std::vector< unsigned int > & getHitIDs () const
bool operator< (const EcalCluster &rhs) const
Private Member Functions
ClassDef (EcalCluster, 1)
Private Attributes
std::vector< unsigned int > hitIDs_
double energy_ {0}
int nHits_ {0}
double centroidX_ {0}
double centroidY_ {0}
double centroidZ_ {0}
Detailed Description
Stores cluster information from the ECal.
Definition at line 27 of file EcalCluster.h.
Constructor & Destructor Documentation
EcalCluster()
ldmx::EcalCluster::EcalCluster ()
Class constructor.
~EcalCluster()
virtual ldmx::EcalCluster::~EcalCluster () virtual
Class destructor.
Member Function Documentation
addHits()
void ldmx::EcalCluster::addHits (const std::vector< const ldmx::EcalHit * > hitsVec)
Take in the hits that make up the cluster.
Parameters
hit The digi hit's entry number in the events digi collection.
Referenced by ecal::EcalClusterProducer::produce().
Clear()
void ldmx::EcalCluster::Clear ()
Reset the EcalCluster object.
getCentroidX()
double ldmx::EcalCluster::getCentroidX () const inline
Definition at line 91 of file EcalCluster.h.
{ return centroidX_; }
getCentroidY()
double ldmx::EcalCluster::getCentroidY () const inline
Definition at line 93 of file EcalCluster.h.
{ return centroidY_; }
getCentroidZ()
double ldmx::EcalCluster::getCentroidZ () const inline
Definition at line 95 of file EcalCluster.h.
{ return centroidZ_; }
getEnergy()
double ldmx::EcalCluster::getEnergy () const inline
Definition at line 87 of file EcalCluster.h.
{ return energy_; }
getHitIDs()
const std::vector< unsigned int > & ldmx::EcalCluster::getHitIDs () const inline
Definition at line 97 of file EcalCluster.h.
{ return hitIDs_; }
getNHits()
int ldmx::EcalCluster::getNHits () const inline
Definition at line 89 of file EcalCluster.h.
{ return nHits_; }
operator<()
bool ldmx::EcalCluster::operator< (const EcalCluster & rhs) const inline
Definition at line 99 of file EcalCluster.h.
{
    return this->getEnergy() < rhs.getEnergy();
  }
Print()
void ldmx::EcalCluster::Print () const
Print a description of this object.
setCentroidXYZ()
void ldmx::EcalCluster::setCentroidXYZ (double x, double y, double z) inline
Sets the three coordinates of the cluster centroid
Parameters
x The x coordinate.
y The y coordinate.
z The z coordinate.
Definition at line 81 of file EcalCluster.h.
{
    centroidX_ = x;
    centroidY_ = y;
    centroidZ_ = z;
  }
Referenced by ecal::EcalClusterProducer::produce().
setEnergy()
void ldmx::EcalCluster::setEnergy (double energy) inline
Sets total energy for the cluster.
Parameters
energy The total energy of the cluster.
Definition at line 60 of file EcalCluster.h.
{ energy_ = energy; }
Referenced by ecal::EcalClusterProducer::produce().
setIDs()
void ldmx::EcalCluster::setIDs (std::vector< unsigned int > & hitIDs) inline
Sets a sorted vector for the IDs of the hits that make up the cluster.
Parameters
IDs Sorted vector of hit IDs.
Definition at line 73 of file EcalCluster.h.
{ hitIDs_ = hitIDs; }
setNHits()
void ldmx::EcalCluster::setNHits (int nHits) inline
Sets total number of hits in the cluster.
Parameters
nHits The total number of hits.
Definition at line 66 of file EcalCluster.h.
{ nHits_ = nHits; }
Referenced by ecal::EcalClusterProducer::produce().
Member Data Documentation
centroidX_
double ldmx::EcalCluster::centroidX_ {0} private
Definition at line 107 of file EcalCluster.h.
centroidY_
double ldmx::EcalCluster::centroidY_ {0} private
Definition at line 108 of file EcalCluster.h.
centroidZ_
double ldmx::EcalCluster::centroidZ_ {0} private
Definition at line 109 of file EcalCluster.h.
energy_
double ldmx::EcalCluster::energy_ {0} private
Definition at line 105 of file EcalCluster.h.
hitIDs_
std::vector<unsigned int> ldmx::EcalCluster::hitIDs_ private
Definition at line 104 of file EcalCluster.h.
nHits_
int ldmx::EcalCluster::nHits_ {0} private
Definition at line 106 of file EcalCluster.h.
The documentation for this class was generated from the following file:
Ecal/include/Ecal/Event/EcalCluster.h