LDMX Software: ecal::EcalTrigPrimDigiProducer Class Reference
ecal::EcalTrigPrimDigiProducer Class Reference
Public Member Functions
EcalTrigPrimDigiProducer (const std::string &name, framework::Process &process)
virtual void configure (framework::config::Parameters &)
virtual void produce (framework::Event &event)
Public Member Functions inherited from framework::Producer
Producer (const std::string &name, Process &process)
virtual void produce (Event &event)=0
virtual void beforeNewRun (ldmx::RunHeader &header)
Public Member Functions inherited from framework::EventProcessor
EventProcessor (const std::string &name, Process &process)
virtual ~EventProcessor ()
virtual void configure (framework::config::Parameters &parameters)
virtual void onNewRun (const ldmx::RunHeader &runHeader)
virtual void onFileOpen (EventFile &eventFile)
virtual void onFileClose (EventFile &eventFile)
virtual void onProcessStart ()
virtual void onProcessEnd ()
template<class T >
const T & getCondition (const std::string &condition_name)
TDirectory * getHistoDirectory ()
void setStorageHint (framework::StorageControlHint hint)
void setStorageHint (framework::StorageControlHint hint, const std::string &purposeString)
int getLogFrequency () const
int getRunNumber () const
std::string getName () const
void createHistograms (const std::vector< framework::config::Parameters > &histos)
Private Attributes
std::string digiCollName_
std::string digiPassName_
std::string condObjName_
Additional Inherited Members
Static Public Member Functions inherited from framework::EventProcessor
static void declare (const std::string &classname, int classtype, EventProcessorMaker *)
Static Public Attributes inherited from framework::Producer
static const int CLASSTYPE {1}
Protected Member Functions inherited from framework::EventProcessor
void abortEvent ()
Protected Attributes inherited from framework::EventProcessor
HistogramHelper histograms_
Interface class for making and filling histograms.
NtupleManager & ntuple_ {NtupleManager::getInstance()}
Manager for any ntuples.
logging::logger theLog_
The logger for this EventProcessor.
Detailed Description
Definition at line 24 of file EcalTrigPrimDigiProducer.h.
Constructor & Destructor Documentation
EcalTrigPrimDigiProducer()
ecal::EcalTrigPrimDigiProducer::EcalTrigPrimDigiProducer (const std::string & name, framework::Process & process)
Constructor
Definition at line 9 of file EcalTrigPrimDigiProducer.cxx.
    : Producer(name, process) {}
Member Function Documentation
configure()
void ecal::EcalTrigPrimDigiProducer::configure (framework::config::Parameters & ps) virtual
Grabs configure parameters from the python config file.
Parameter Default inputDigiCollName EcalDigis inputDigiPassName "" <– blank means take any pass if only one collection exists
Reimplemented from framework::EventProcessor.
Definition at line 13 of file EcalTrigPrimDigiProducer.cxx.
{
  digiCollName_ = ps.getParameter<std::string>("digiCollName");
  digiPassName_ = ps.getParameter<std::string>("digiPassName");
  condObjName_ =
      ps.getParameter<std::string>("condObjName", "EcalTrigPrimDigiConditions");
}
References condObjName_, digiCollName_, digiPassName_, and framework::config::Parameters::getParameter().
produce()
void ecal::EcalTrigPrimDigiProducer::produce (framework::Event & event) virtual
Produce EcalHits and put them into the event bus using the EcalDigis as input.
Implements framework::Producer.
Definition at line 20 of file EcalTrigPrimDigiProducer.cxx.
{
  const EcalTriggerGeometry& geom = getCondition<EcalTriggerGeometry>(
      EcalTriggerGeometry::CONDITIONS_OBJECT_NAME);
  const ldmx::HgcrocDigiCollection& ecalDigis =
      event.getObject<ldmx::HgcrocDigiCollection>(digiCollName_, digiPassName_);
  // get the calibration object
  const conditions::IntegerTableCondition& conditions =
      getCondition<conditions::IntegerTableCondition>(condObjName_);
  // construct the calculator...
  ldmx::HgcrocTriggerCalculations calc(conditions);
  // Loop over the digis
  for (unsigned int ix = 0; ix < ecalDigis.getNumDigis(); ix++) {
    const ldmx::HgcrocDigiCollection::HgcrocDigi pdigi = ecalDigis.getDigi(ix);
    // std::cout << EcalID(pdigi.id()) << pdigi << std::endl;
    ldmx::EcalTriggerID tid = geom.belongsTo(ldmx::EcalID(pdigi.id()));
    if (!tid.null()) {
      int tot = 0;
      if (pdigi.soi().isTOTComplete()) tot = pdigi.soi().tot();
      calc.addDigi(pdigi.id(), tid.raw(), pdigi.soi().adc_t(), tot);
    }
  }
  // Now, we compress the digis
  calc.compressDigis(9);  // 9 is the number for Ecal...
  const std::map<unsigned int, uint8_t>& results = calc.compressedEnergies();
  ldmx::HgcrocTrigDigiCollection tdigis;
  for (auto result : results) {
    if (result.second > 0) {
      tdigis.push_back(ldmx::HgcrocTrigDigi(result.first, result.second));
      // std::cout << EcalTriggerID(result.first) << "  " << tdigis.back() <<
      // std::endl;
    }
  }
  // std::cout << ecalDigis.size() << " " << tdigis.size() << std::endl;
  event.add(getName(), tdigis);
}
References ldmx::HgcrocDigiCollection::Sample::adc_t(), ldmx::HgcrocTriggerCalculations::addDigi(), ecal::EcalTriggerGeometry::belongsTo(), ldmx::HgcrocTriggerCalculations::compressDigis(), ldmx::HgcrocTriggerCalculations::compressedEnergies(), condObjName_, digiCollName_, digiPassName_, ldmx::HgcrocDigiCollection::getDigi(), framework::EventProcessor::getName(), ldmx::HgcrocDigiCollection::getNumDigis(), ldmx::HgcrocDigiCollection::HgcrocDigi::id(), ldmx::HgcrocDigiCollection::Sample::isTOTComplete(), ldmx::DetectorID::null(), ldmx::DetectorID::raw(), ldmx::HgcrocDigiCollection::HgcrocDigi::soi(), and ldmx::HgcrocDigiCollection::Sample::tot().
Member Data Documentation
condObjName_
std::string ecal::EcalTrigPrimDigiProducer::condObjName_ private
Conditions object for the calibration information
Definition at line 56 of file EcalTrigPrimDigiProducer.h.
Referenced by configure(), and produce().
digiCollName_
std::string ecal::EcalTrigPrimDigiProducer::digiCollName_ private
Digi Collection Name to use as input
Definition at line 50 of file EcalTrigPrimDigiProducer.h.
Referenced by configure(), and produce().
digiPassName_
std::string ecal::EcalTrigPrimDigiProducer::digiPassName_ private
Digi Pass Name to use as input
Definition at line 53 of file EcalTrigPrimDigiProducer.h.
Referenced by configure(), and produce().
The documentation for this class was generated from the following files:
Ecal/include/Ecal/EcalTrigPrimDigiProducer.h
Ecal/src/Ecal/EcalTrigPrimDigiProducer.cxx