LDMX Software: framework::ConditionsIOV Class Reference
framework::ConditionsIOV Class Reference
Class which defines the run/event/type range for which a given condition is valid, including for all time.
#include <ConditionsIOV.h>
Public Member Functions
ConditionsIOV ()
ConditionsIOV (bool validForData, bool validForMC)
ConditionsIOV (int firstRun, int lastRun, bool validForData=true, bool validForMC=true)
bool validForEvent (const ldmx::EventHeader &eh) const
bool overlaps (const ConditionsIOV &iov) const
void Print () const
std::string ToString () const
void stream (std::ostream &) const
Private Attributes
int firstRun_
int lastRun_
bool validForData_
bool validForMC_
Detailed Description
Class which defines the run/event/type range for which a given condition is valid, including for all time.
Definition at line 33 of file ConditionsIOV.h.
Constructor & Destructor Documentation
ConditionsIOV() [1/3]
framework::ConditionsIOV::ConditionsIOV () inline
Constructor for null validity
Definition at line 38 of file ConditionsIOV.h.
      : firstRun_{0}, lastRun_{0}, validForData_{false}, validForMC_{false} {}
ConditionsIOV() [2/3]
framework::ConditionsIOV::ConditionsIOV (bool validForData, bool validForMC) inline
Constructor for a unlimited validity
Definition at line 44 of file ConditionsIOV.h.
      : firstRun_(-1),
        lastRun_(-1),
        validForData_{validForData},
        validForMC_{validForMC} {}
ConditionsIOV() [3/3]
framework::ConditionsIOV::ConditionsIOV (int firstRun, int lastRun, bool validForData = true, bool validForMC = true) inline
Constructor for a run-limited validity
firstRun should be -1 if valid from beginning of time
lastRun should be -1 if valid to end of time
Definition at line 55 of file ConditionsIOV.h.
      : firstRun_(firstRun),
        lastRun_(lastRun),
        validForData_{validForData},
        validForMC_{validForMC} {}
Member Function Documentation
overlaps()
bool framework::ConditionsIOV::overlaps (const ConditionsIOV & iov) const
Checks to see if this IOV overlaps with the given IOV
Definition at line 20 of file ConditionsIOV.cxx.
{
  if (iov.validForData_ != validForData_ && iov.validForMC_ != validForMC_)
    return false;
  if (iov.firstRun_ < lastRun_) return false;  // starts after this IOV
  if (iov.lastRun_ < firstRun_) return false;  // ends before this IOV
  return true;
}
References firstRun_, lastRun_, validForData_, and validForMC_.
Print()
void framework::ConditionsIOV::Print () const
Print the object to std::cout
Definition at line 28 of file ConditionsIOV.cxx.
{
  stream(std::cout);
  std::cout << std::endl;
}
References stream().
stream()
void framework::ConditionsIOV::stream (std::ostream & s) const
Stream the object contents to an output stream
Definition at line 39 of file ConditionsIOV.cxx.
{
  s << "IOV(" << firstRun_ << "->";
  if (lastRun_ == -1)
    s << "[all runs]";
  else
    s << lastRun_;
  if (validForData_) s << ",Data";
  if (validForMC_) s << ",MC";
  s << ")";
}
References firstRun_, lastRun_, validForData_, and validForMC_.
Referenced by Print(), and ToString().
ToString()
std::string framework::ConditionsIOV::ToString () const
Print the object to a string
Definition at line 33 of file ConditionsIOV.cxx.
{
  std::stringstream s;
  stream(s);
  return s.str();
}
References stream().
validForEvent()
bool framework::ConditionsIOV::validForEvent (const ldmx::EventHeader & eh) const
Checks to see if this condition is valid for the given event using information from the header
Definition at line 14 of file ConditionsIOV.cxx.
{
  return (eh.getRun() >= firstRun_ || firstRun_ == -1) &&
         (eh.getRun() <= lastRun_ || lastRun_ == -1) &&
         ((eh.isRealData()) ? (validForData_) : (validForMC_));
}
References firstRun_, ldmx::EventHeader::getRun(), ldmx::EventHeader::isRealData(), lastRun_, validForData_, and validForMC_.
Member Data Documentation
firstRun_
int framework::ConditionsIOV::firstRun_ private
First run for which this condition is valid
Definition at line 86 of file ConditionsIOV.h.
Referenced by overlaps(), stream(), and validForEvent().
lastRun_
int framework::ConditionsIOV::lastRun_ private
Last run for which this condition is valid or -1 for infinite validity
Definition at line 89 of file ConditionsIOV.h.
Referenced by overlaps(), stream(), and validForEvent().
validForData_
bool framework::ConditionsIOV::validForData_ private
Is this Condition valid for real data?
Definition at line 92 of file ConditionsIOV.h.
Referenced by overlaps(), stream(), and validForEvent().
validForMC_
bool framework::ConditionsIOV::validForMC_ private
Is this Condition valid for simulation?
Definition at line 95 of file ConditionsIOV.h.
Referenced by overlaps(), stream(), and validForEvent().
The documentation for this class was generated from the following files:
Framework/include/Framework/ConditionsIOV.h
Framework/src/Framework/ConditionsIOV.cxx