LDMX Software: biasing::MidShowerNuclearBkgdFilter Class Reference
biasing::MidShowerNuclearBkgdFilter Class Reference
#include <MidShowerNuclearBkgdFilter.h>
Public Member Functions
MidShowerNuclearBkgdFilter (const std::string &name, framework::config::Parameters &parameters)
~MidShowerNuclearBkgdFilter ()
std::vector< simcore::TYPE > getTypes () final override
void BeginOfEventAction (const G4Event *event) final override
void stepping (const G4Step *step) final override
void NewStage () final override
Public Member Functions inherited from simcore::UserAction
UserAction (const std::string &name, framework::config::Parameters &parameters)
virtual ~UserAction ()
Destructor.
virtual void BeginOfEventAction (const G4Event *)
virtual void EndOfEventAction (const G4Event *)
virtual void BeginOfRunAction (const G4Run *)
virtual void EndOfRunAction (const G4Run *)
virtual void PreUserTrackingAction (const G4Track *)
virtual void PostUserTrackingAction (const G4Track *)
virtual void stepping (const G4Step *)
virtual G4ClassificationOfNewTrack ClassifyNewTrack (const G4Track *, const G4ClassificationOfNewTrack &cl)
virtual void NewStage ()
virtual void PrepareNewEvent ()
virtual std::vector< TYPE > getTypes ()=0
Private Member Functions
bool isOutsideCalorimeterRegion (const G4Step *step) const
bool isNuclearProcess (const G4VProcess *proc) const
void save (const G4Track *track) const
void AbortEvent (const std::string &reason) const
Private Attributes
double threshold_
std::vector< std::string > nuclear_processes_
double total_process_energy_ {0.}
Additional Inherited Members
Public Types inherited from simcore::UserAction
using Factory = ::simcore::Factory< UserAction, std::shared_ptr< UserAction >, const std::string &, framework::config::Parameters & >
factory for user actions
Protected Member Functions inherited from simcore::UserAction
UserEventInformation * getEventInfo () const
const std::map< int, ldmx::SimParticle > & getCurrentParticleMap () const
Protected Attributes inherited from simcore::UserAction
std::string name_ {""}
Name of the UserAction.
framework::config::Parameters parameters_
The set of parameters used to configure this class.
Detailed Description
The basic premis of this filter is to add up all of the energy "lost" to the configured process. Whenever a particle makes a step and has secondaries within that step going to the input process, we add its change in energy to the running total for the event. When the PartialEnergySorter has run out of "high" energy particles to process (when NewStage is called) we check if the running total is high enough to keep the event.
See also
PartialEnergySorter Here we assume that the partial energy sorter is being run in sequence with this filter.
Definition at line 29 of file MidShowerNuclearBkgdFilter.h.
Constructor & Destructor Documentation
MidShowerNuclearBkgdFilter()
biasing::MidShowerNuclearBkgdFilter::MidShowerNuclearBkgdFilter (const std::string & name, framework::config::Parameters & parameters)
Class constructor.
Retrieve the necessary configuration parameters
Definition at line 10 of file MidShowerNuclearBkgdFilter.cxx.
    : simcore::UserAction(name, parameters) {
  threshold_ = parameters.getParameter<double>("threshold");
  nuclear_processes_ = {"photonNuclear", "electronNuclear"};
}
References framework::config::Parameters::getParameter(), nuclear_processes_, and threshold_.
~MidShowerNuclearBkgdFilter()
biasing::MidShowerNuclearBkgdFilter::~MidShowerNuclearBkgdFilter () inline
Class destructor.
Definition at line 42 of file MidShowerNuclearBkgdFilter.h.
{}
Member Function Documentation
AbortEvent()
void biasing::MidShowerNuclearBkgdFilter::AbortEvent (const std::string & reason) const private
Helper to abort an event with a message
Tells the RunManger to abort the current event after displaying the input message.
Parameters
[in] reason reason for aborting the event
Definition at line 101 of file MidShowerNuclearBkgdFilter.cxx.
{
  if (G4RunManager::GetRunManager()->GetVerboseLevel() > 1) {
    std::cout << "[ MidShowerNuclearBkgdFilter ]: "
              << "("
              << G4EventManager::GetEventManager()
                     ->GetConstCurrentEvent()
                     ->GetEventID()
              << ") " << reason << " Aborting event." << std::endl;
  }
  G4RunManager::GetRunManager()->AbortEvent();
  return;
}
Referenced by NewStage().
BeginOfEventAction()
void biasing::MidShowerNuclearBkgdFilter::BeginOfEventAction (const G4Event * event) final override virtual
Reset the total energy going to the configured process.
Parameters
[in] event not used
Reimplemented from simcore::UserAction.
Definition at line 17 of file MidShowerNuclearBkgdFilter.cxx.
{
  /* debug printout
  std::cout
      << "[ MidShowerNuclearBkgdFilter ]: "
      << "("
      << G4EventManager::GetEventManager()->GetConstCurrentEvent()->GetEventID()
      << ") "
      << "starting new simulation event." << std::endl;
   */
  total_process_energy_ = 0.;
}
References total_process_energy_.
getTypes()
std::vector< simcore::TYPE > biasing::MidShowerNuclearBkgdFilter::getTypes () inline final override virtual
Get the types of actions this class can do
Returns
list of action types this class does
Implements simcore::UserAction.
Definition at line 49 of file MidShowerNuclearBkgdFilter.h.
{
    return {simcore::TYPE::STACKING, simcore::TYPE::STEPPING,
            simcore::TYPE::EVENT};
  }
isNuclearProcess()
bool biasing::MidShowerNuclearBkgdFilter::isNuclearProcess (const G4VProcess * proc) const private
Checks if the passed process is any of the nuclear interactions
Note
A 'nullptr' process is not a nuclear process.
Parameters
[in] proc G4VProcess* to check
Returns
true if process is one of the nuclear interactions
Definition at line 84 of file MidShowerNuclearBkgdFilter.cxx.
{
  if (proc) {
    const G4String& proc_name{proc->GetProcessName()};
    for (auto const& option : nuclear_processes_) {
      if (proc_name.contains(option)) return true;
    }  // loop over nuclear processes
  }    // pointer exists
  return false;
}
References nuclear_processes_.
Referenced by stepping().
isOutsideCalorimeterRegion()
bool biasing::MidShowerNuclearBkgdFilter::isOutsideCalorimeterRegion (const G4Step * step) const private
Checks if the passed step is outside of the CalorimeterRegion.
Parameters
[in] step const G4Step to check
Returns
true if passed step is outside of the CalorimeterRegion.
Definition at line 74 of file MidShowerNuclearBkgdFilter.cxx.
{
  // the pointers in this chain are assumed to be always valid
  auto reg{step->GetTrack()->GetVolume()->GetLogicalVolume()->GetRegion()};
  if (reg) return (reg->GetName() != "CalorimeterRegion");
  // region is nullptr ==> no region defined for current volume
  //  ==> outside CalorimeterRegion
  return true;
}
Referenced by stepping().
NewStage()
void biasing::MidShowerNuclearBkgdFilter::NewStage () final override virtual
When using the PartialEnergySorter, the first time that a new stage begins is when all particles are now below the threshold.
We take this opportunity to make sure that enough energy has gone to the products of the input process.
See also
PartialEnergySort::NewStage
AbortEvent
Reimplemented from simcore::UserAction.
Definition at line 61 of file MidShowerNuclearBkgdFilter.cxx.
{
  /* debug printout
  std::cout
      << "[ MidShowerNuclearBkgdFilter ]: "
      << "("
      << G4EventManager::GetEventManager()->GetConstCurrentEvent()->GetEventID()
      << ") " << total_process_energy_ << " MeV went nuclear." << std::endl;
   */
  if (total_process_energy_ < threshold_)
    AbortEvent("Not enough energy went to the input process.");
  return;
}
References AbortEvent(), threshold_, and total_process_energy_.
save()
void biasing::MidShowerNuclearBkgdFilter::save (const G4Track * track) const private
Helper to save the passed track
Note
Assumes user track information has already been created for the input track.
Parameters
[in] track G4Track to persist into output
Definition at line 95 of file MidShowerNuclearBkgdFilter.cxx.
{
  auto track_info{simcore::UserTrackInformation::get(track)};
  track_info->setSaveFlag(true);
  return;
}
References simcore::UserTrackInformation::get(), and simcore::UserTrackInformation::setSaveFlag().
Referenced by stepping().
stepping()
void biasing::MidShowerNuclearBkgdFilter::stepping (const G4Step * step) final override virtual
We follow the simulation along each step and check if any secondaries of the input process were created.
If they were created, we add the change in energy to the total energy "lost" to the input process.
Note
Only includes the steps that are within the 'CalorimeterRegion' in the search for interesting products.
See also
isOutsideCalorimeterRegion
anyCreatedViaProcess
Parameters
[in] step current G4Step
Reimplemented from simcore::UserAction.
Definition at line 29 of file MidShowerNuclearBkgdFilter.cxx.
{
  // skip steps that are outside the calorimeter region
  if (isOutsideCalorimeterRegion(step)) return;
  if (getEventInfo()->wasLastStepPN() or getEventInfo()->wasLastStepEN()) {
    // there are interesting secondaries in this step
    double pre_energy = step->GetPreStepPoint()->GetTotalEnergy();
    double post_energy = step->GetPostStepPoint()->GetTotalEnergy();
    total_process_energy_ += pre_energy - post_energy;
    const G4Track* track = step->GetTrack();
    /* debug printout
    std::cout << "[ MidShowerNuclearBkgdFilter ]: "
              << "("
              << G4EventManager::GetEventManager()
                     ->GetConstCurrentEvent()
                     ->GetEventID()
              << ") "
              << "Track " << track->GetParentID() << " created "
              << track->GetTrackID() << " which went from " << pre_energy
              << " MeV to " << post_energy << " via a nuclear process." <<
    std::endl;
     */
    // make sure this track is saved
    save(track);
  } else if (const G4Track * track{step->GetTrack()};
             track->GetCurrentStepNumber() == 1 and
             isNuclearProcess(track->GetCreatorProcess())) {
    save(track);
  }
}
References simcore::UserAction::getEventInfo(), isNuclearProcess(), isOutsideCalorimeterRegion(), save(), and total_process_energy_.
Member Data Documentation
nuclear_processes_
std::vector<std::string> biasing::MidShowerNuclearBkgdFilter::nuclear_processes_ private
Processes to look for
Definition at line 147 of file MidShowerNuclearBkgdFilter.h.
Referenced by isNuclearProcess(), and MidShowerNuclearBkgdFilter().
threshold_
double biasing::MidShowerNuclearBkgdFilter::threshold_ private
Minimum energy [MeV] that the process products need to have to keep the event.
Also used by PartialEnergySorter to determine which tracks should be processed first.
Parameter Name: 'threshold'
Definition at line 142 of file MidShowerNuclearBkgdFilter.h.
Referenced by MidShowerNuclearBkgdFilter(), and NewStage().
total_process_energy_
double biasing::MidShowerNuclearBkgdFilter::total_process_energy_ {0.} private
Total energy gone to the process in the current event
Reset to 0. in BeginOfEventAction
Definition at line 154 of file MidShowerNuclearBkgdFilter.h.
Referenced by BeginOfEventAction(), NewStage(), and stepping().
The documentation for this class was generated from the following files:
Biasing/include/Biasing/MidShowerNuclearBkgdFilter.h
Biasing/src/Biasing/MidShowerNuclearBkgdFilter.cxx