LDMX Software: simcore::darkbrem::ElementXsecCache Class Reference
simcore::darkbrem::ElementXsecCache Class Reference
#include <G4eDarkBremsstrahlung.h>
Public Member Functions
ElementXsecCache ()=default
ElementXsecCache (std::shared_ptr< G4eDarkBremsstrahlungModel > model)
G4double get (G4double energy, G4double A, G4double Z)
void stream (std::ostream &o) const
Private Types
typedef unsigned long int key_t
The type for the key we use in the cache.
Private Member Functions
key_t computeKey (G4double energy, G4double A, G4double Z) const
Private Attributes
std::map< key_t, G4double > the_cache_
the actual map from cache keys to calculated cross sections
std::shared_ptr< G4eDarkBremsstrahlungModel > model_
shared pointer to the model for calculating cross sections
Static Private Attributes
static const key_t MAX_A {1000}
The maximum value of A.
static const key_t MAX_E {30000}
The maximum value for energy [MeV].
Friends
std::ostream & operator<< (std::ostream &o, const ElementXsecCache c)
Detailed Description
The cache of already computed cross sections
We make a specific class for the cache in order to keep the key encoding/decoding process in a central location.
Definition at line 108 of file G4eDarkBremsstrahlung.h.
Member Typedef Documentation
key_t
typedef unsigned long int simcore::darkbrem::ElementXsecCache::key_t private
The type for the key we use in the cache.
Definition at line 158 of file G4eDarkBremsstrahlung.h.
Constructor & Destructor Documentation
ElementXsecCache() [1/2]
simcore::darkbrem::ElementXsecCache::ElementXsecCache () default
Default constructor
Does nothing interesting, but no model for calculating cross section has been set.
ElementXsecCache() [2/2]
simcore::darkbrem::ElementXsecCache::ElementXsecCache (std::shared_ptr< G4eDarkBremsstrahlungModel > model) inline
Constructor with a model to calculate the cross section.
Definition at line 121 of file G4eDarkBremsstrahlung.h.
      : model_{model} {}
Member Function Documentation
computeKey()
ElementXsecCache::key_t simcore::darkbrem::ElementXsecCache::computeKey (G4double energy, G4double A, G4double Z) const private
Compute a key for the cache map Generating a unique key after making the energy [MeV] an integer. The atomic mass (A) and charge (Z) are given by Geant4 as doubles as well, so I cast them to integers before computing the key.
This is what you would edit if you want a more/less find-grained cache of Xsecs. Right now, since the internal unit of energy in Geant4 is MeV, the cache is binned at the 1MeV scale.
Parameters
[in] energy Energy of incident electron [MeV]
[in] A atomic mass of element [atomic mass units]
[in] Z atomic number of element [num protons]
Returns
unsigned integer cache key for these three inputs
Definition at line 48 of file G4eDarkBremsstrahlung.cxx.
{
  key_t energyKey = energy;
  key_t AKey = A;
  key_t ZKey = Z;
  return (ZKey * MAX_A + AKey) * MAX_E + energyKey;
}
References MAX_A, and MAX_E.
Referenced by get().
get()
G4double simcore::darkbrem::ElementXsecCache::get (G4double energy, G4double A, G4double Z)
Get the value of the cross section for the input variables and calculate the cross section if it wasn't calculated before.
@raises Exception if no model is available for calculating cross sections
Parameters
[in] energy Energy of incident electron [MeV]
[in] A atomic mass of element [atomic mass units]
[in] Z atomic number of element [num protons]
Returns
cross section corresponding to the input parameters (including units Geant4 style)
Definition at line 22 of file G4eDarkBremsstrahlung.cxx.
{
  key_t key = computeKey(energy, A, Z);
  if (the_cache_.find(key) == the_cache_.end()) {
    if (model_.get() == nullptr) {
      EXCEPTION_RAISE("BadCache",
                      "ElementXsecCache not given a model to calculate cross "
                      "sections with.");
    }
    the_cache_[key] = model_->ComputeCrossSectionPerAtom(energy, A, Z);
  }
  return the_cache_.at(key);
}
References computeKey(), model_, and the_cache_.
Referenced by simcore::darkbrem::G4eDarkBremsstrahlung::CalculateCommonXsec(), and simcore::darkbrem::G4eDarkBremsstrahlung::GetMeanFreePath().
stream()
void simcore::darkbrem::ElementXsecCache::stream (std::ostream & o) const
Stream the entire table into the output stream.
Parameters
[in,out] o ostream to write to
Definition at line 35 of file G4eDarkBremsstrahlung.cxx.
{
  o << "A [au],Z [protons],Energy [MeV],Xsec [pb]\n"
    << std::setprecision(std::numeric_limits<double>::digits10 +
                         1);  // maximum precision
  for (auto const& [key, xsec] : the_cache_) {
    key_t E = key % MAX_E;
    key_t A = ((key - E) / MAX_E) % MAX_A;
    key_t Z = ((key - E) / MAX_E - A) / MAX_A;
    o << A << "," << Z << "," << E << "," << xsec / CLHEP::picobarn << "\n";
  }
  o << std::endl;
}
References MAX_A, MAX_E, and the_cache_.
Friends And Related Function Documentation
operator<<
std::ostream & operator<< (std::ostream & o, const ElementXsecCache c) friend
Overload the streaming operator for ease
Parameters
[in] o ostream to write to
[in] c cache to write out
Returns
modified ostream
Definition at line 151 of file G4eDarkBremsstrahlung.h.
{
    c.stream(o);
    return o;
  }
Member Data Documentation
MAX_A
const key_t simcore::darkbrem::ElementXsecCache::MAX_A {1000} static private
The maximum value of A.
Definition at line 161 of file G4eDarkBremsstrahlung.h.
Referenced by computeKey(), and stream().
MAX_E
const key_t simcore::darkbrem::ElementXsecCache::MAX_E {30000} static private
The maximum value for energy [MeV].
Definition at line 164 of file G4eDarkBremsstrahlung.h.
Referenced by computeKey(), and stream().
model_
std::shared_ptr<G4eDarkBremsstrahlungModel> simcore::darkbrem::ElementXsecCache::model_ private
shared pointer to the model for calculating cross sections
Definition at line 188 of file G4eDarkBremsstrahlung.h.
Referenced by get().
the_cache_
std::map<key_t, G4double> simcore::darkbrem::ElementXsecCache::the_cache_ private
the actual map from cache keys to calculated cross sections
Definition at line 185 of file G4eDarkBremsstrahlung.h.
Referenced by get(), and stream().
The documentation for this class was generated from the following files:
SimCore/include/SimCore/DarkBrem/G4eDarkBremsstrahlung.h
SimCore/src/SimCore/DarkBrem/G4eDarkBremsstrahlung.cxx