LDMX Software: hcal::HcalClusterProducer Class Reference
hcal::HcalClusterProducer Class Reference
Make clusters from hits in the HCAL.
#include <HcalClusterProducer.h>
Public Member Functions
HcalClusterProducer (const std::string &name, framework::Process &process)
void configure (framework::config::Parameters &parameters) final override
virtual void produce (framework::Event &event)
Public Member Functions inherited from framework::Producer
Producer (const std::string &name, Process &process)
virtual void produce (Event &event)=0
virtual void beforeNewRun (ldmx::RunHeader &header)
Public Member Functions inherited from framework::EventProcessor
EventProcessor (const std::string &name, Process &process)
virtual ~EventProcessor ()
virtual void configure (framework::config::Parameters &parameters)
virtual void onNewRun (const ldmx::RunHeader &runHeader)
virtual void onFileOpen (EventFile &eventFile)
virtual void onFileClose (EventFile &eventFile)
virtual void onProcessStart ()
virtual void onProcessEnd ()
template<class T >
const T & getCondition (const std::string &condition_name)
TDirectory * getHistoDirectory ()
void setStorageHint (framework::StorageControlHint hint)
void setStorageHint (framework::StorageControlHint hint, const std::string &purposeString)
int getLogFrequency () const
int getRunNumber () const
std::string getName () const
void createHistograms (const std::vector< framework::config::Parameters > &histos)
Private Attributes
bool verbose_ {false}
double EnoiseCut_ {0.}
double deltaTime_ {0}
double deltaR_ {0}
double EminCluster_ {0.}
double cutOff_ {0.}
std::string clusterCollName_
Additional Inherited Members
Static Public Member Functions inherited from framework::EventProcessor
static void declare (const std::string &classname, int classtype, EventProcessorMaker *)
Static Public Attributes inherited from framework::Producer
static const int CLASSTYPE {1}
Protected Member Functions inherited from framework::EventProcessor
void abortEvent ()
Protected Attributes inherited from framework::EventProcessor
HistogramHelper histograms_
Interface class for making and filling histograms.
NtupleManager & ntuple_ {NtupleManager::getInstance()}
Manager for any ntuples.
logging::logger theLog_
The logger for this EventProcessor.
Detailed Description
Make clusters from hits in the HCAL.
Definition at line 35 of file HcalClusterProducer.h.
Constructor & Destructor Documentation
HcalClusterProducer()
hcal::HcalClusterProducer::HcalClusterProducer (const std::string & name, framework::Process & process)
Definition at line 15 of file HcalClusterProducer.cxx.
    : Producer(name, process) {}
~HcalClusterProducer()
virtual hcal::HcalClusterProducer::~HcalClusterProducer () inline virtual
Definition at line 41 of file HcalClusterProducer.h.
{;}
Member Function Documentation
configure()
void hcal::HcalClusterProducer::configure (framework::config::Parameters & parameters) final override virtual
Configure the processor using the given user specified parameters.
Parameters
parameters Set of parameters used to configure this processor.
Reimplemented from framework::EventProcessor.
Definition at line 19 of file HcalClusterProducer.cxx.
{
  EnoiseCut_ = parameters.getParameter<double>("EnoiseCut");
  deltaTime_ = parameters.getParameter<double>("deltaTime");
  deltaR_ = parameters.getParameter<double>("deltaR");
  EminCluster_ = parameters.getParameter<double>("EminCluster");
  cutOff_ = parameters.getParameter<double>("cutOff");
  clusterCollName_ = parameters.getParameter<std::string>("clusterCollName");
}
References framework::config::Parameters::getParameter().
produce()
void hcal::HcalClusterProducer::produce (framework::Event & event) virtual
Process the event and put new data products into it.
Parameters
event The Event to process.
Implements framework::Producer.
Definition at line 33 of file HcalClusterProducer.cxx.
{
  const ldmx::HcalGeometry& hcalGeom = getCondition<ldmx::HcalGeometry>(
      ldmx::HcalGeometry::CONDITIONS_OBJECT_NAME);
  TemplatedClusterFinder<MyClusterWeight> finder;
  std::vector<ldmx::HcalCluster> hcalClusters;
  std::list<const ldmx::HcalHit*> seedList;
  std::vector<ldmx::HcalHit> hcalHits =
      event.getCollection<ldmx::HcalHit>("HcalRecHits");
  if (hcalHits.empty()) {
    return;
  }
  for (ldmx::HcalHit& hit : hcalHits) {
    if (hit.getEnergy() < EnoiseCut_) continue;
    if (hit.getEnergy() == 0) continue;
    finder.add(&hit, hcalGeom);
  }
  // seedList.sort([](const ldmx::HcalHit* a, const ldmx::HcalHit* b) {return
  // a->getEnergy() > b->getEnergy();});
  finder.cluster(EminCluster_, cutOff_, deltaTime_);
  std::vector<WorkingCluster> wcVec = finder.getClusters();
  for (unsigned int c = 0; c < wcVec.size(); c++) {
    if (wcVec[c].empty()) continue;
    ldmx::HcalCluster cluster;
    cluster.setEnergy(wcVec[c].centroid().E());
    cluster.setCentroidXYZ(wcVec[c].centroid().Px(), wcVec[c].centroid().Py(),
                           wcVec[c].centroid().Pz());
    cluster.setNHits(wcVec[c].getHits().size());
    cluster.addHits(wcVec[c].getHits());
    std::vector<const ldmx::HcalHit*> hits = wcVec[c].getHits();
    if (hits.size() > 0) {
      std::sort(hits.begin(), hits.end(), compHitTimes);
      cluster.setTime(hits[0]->getTime());
    }
    hcalClusters.push_back(cluster);
  }
  event.add(clusterCollName_, hcalClusters);
}
References ldmx::HcalCluster::addHits(), ldmx::HcalGeometry::CONDITIONS_OBJECT_NAME, ldmx::HcalCluster::setCentroidXYZ(), ldmx::HcalCluster::setEnergy(), and ldmx::HcalCluster::setNHits().
Member Data Documentation
clusterCollName_
std::string hcal::HcalClusterProducer::clusterCollName_ private
Definition at line 61 of file HcalClusterProducer.h.
cutOff_
double hcal::HcalClusterProducer::cutOff_ {0.} private
Definition at line 60 of file HcalClusterProducer.h.
deltaR_
double hcal::HcalClusterProducer::deltaR_ {0} private
Definition at line 58 of file HcalClusterProducer.h.
deltaTime_
double hcal::HcalClusterProducer::deltaTime_ {0} private
Definition at line 57 of file HcalClusterProducer.h.
EminCluster_
double hcal::HcalClusterProducer::EminCluster_ {0.} private
Definition at line 59 of file HcalClusterProducer.h.
EnoiseCut_
double hcal::HcalClusterProducer::EnoiseCut_ {0.} private
Definition at line 56 of file HcalClusterProducer.h.
verbose_
bool hcal::HcalClusterProducer::verbose_ {false} private
Definition at line 54 of file HcalClusterProducer.h.
The documentation for this class was generated from the following files:
Hcal/include/Hcal/HcalClusterProducer.h
Hcal/src/Hcal/HcalClusterProducer.cxx