LDMX Software: ldmx::DummyAnalyzer Class Reference
ldmx::DummyAnalyzer Class Reference
A dummy Analyzer implementation that just prints some messages and makes a simple histogram of calorimeter energy.
Public Member Functions
DummyAnalyzer (const std::string &name, ldmx::Process &process)
void configure (Parameters &parameters) final override
~DummyAnalyzer ()
Destructor.
void analyze (const ldmx::Event &event) final override
void onFileOpen (EventFile &eventFile) final override
void onFileClose (EventFile &eventFile) final override
void onProcessStart () final override
void onProcessEnd () final override
Public Member Functions inherited from ldmx::Analyzer
Analyzer (const std::string &name, Process &process)
Public Member Functions inherited from ldmx::EventProcessor
EventProcessor (const std::string &name, Process &process)
virtual ~EventProcessor ()
virtual void onNewRun (const RunHeader &runHeader)
TDirectory * getHistoDirectory ()
void setStorageHint (ldmx::StorageControlHint hint)
void setStorageHint (ldmx::StorageControlHint hint, const std::string &purposeString)
void createHistograms (const std::vector< Parameters > &histos)
Private Attributes
TH1 * hEnergy {nullptr}
Histogram of the calorimeter energy.
std::string caloCol_
int ievt {0}
Event counter.
Additional Inherited Members
Static Public Member Functions inherited from ldmx::EventProcessor
static void declare (const std::string &classname, int classtype, EventProcessorMaker *)
Static Public Attributes inherited from ldmx::Analyzer
static const int CLASSTYPE {2}
Protected Member Functions inherited from ldmx::EventProcessor
void abortEvent ()
Protected Attributes inherited from ldmx::EventProcessor
Process & process_
HistogramHelper histograms_
Interface class for making and filling histograms.
NtupleManager & ntuple_ {NtupleManager::getInstance()}
Manager for any ntuples.
Detailed Description
A dummy Analyzer implementation that just prints some messages and makes a simple histogram of calorimeter energy.
Definition at line 42 of file DummyAnalyzer.cxx.
Constructor & Destructor Documentation
DummyAnalyzer()
ldmx::DummyAnalyzer::DummyAnalyzer (const std::string & name, ldmx::Process & process) inline
Class constructor.
Parameters
name Name for this instance of the class.
process The Process used to run this analyzer, provided by the framework.
Definition at line 53 of file DummyAnalyzer.cxx.
                 : ldmx::Analyzer(name, process) {
             }
Member Function Documentation
analyze()
void ldmx::DummyAnalyzer::analyze (const ldmx::Event & event) inline final override virtual
Process the event, print some messages, and make a simple histogram and ntuple out of the calorimeter energy.
Parameters
event The event to analyze.
Implements ldmx::Analyzer.
Definition at line 75 of file DummyAnalyzer.cxx.
{
                 std::cout << "[ DummyAnalyzer]: Analyzing an event!" << std::endl;
                 // Get the collection of calorimeter hits from the event.
                 auto tca = event.getCollection<CalorimeterHit>(caloCol_);
                 // Loop through the collection and fill the histogram
                 float maxEnergyHit = -1.;
                 for (const CalorimeterHit &hit : tca) {
                     // Fill the histogram
                     hEnergy->Fill(hit.getEnergy());
                     // Check if this hits energy is bigger
                     if ( hit.getEnergy() > maxEnergyHit ) maxEnergyHit = hit.getEnergy();
                 }
                 // set the ntuple variable
                 //  the ntuple is filled at the end of each event
                 ntuple_.setVar<float>("energy", maxEnergyHit);
                 // Print out all of the product tags in the event.
                 if (ievt == 0) {
                     std::cout << "[ DummyAnalyzer ]: Demonstration of printing out all the event contents." << std::endl;
                     auto pts = event.getProducts();
                     for (const auto &j : pts) std::cout << "\t" << j << std::endl;
                 }
                 // Search for all of the products with the pass name 'sim'
                 if (ievt == 1) {
                     std::cout << "[ DummyAnalyzer ]: Demonstration of searching for all products with pass name 'sim'." << std::endl;
                     auto pts = event.searchProducts("","sim","");
                     for (const auto &j : pts) std::cout << "\t" << j << std::endl;
                 }
                 //  Search for all of the products with the 'cal' in the product
                 //  name.
                 if (ievt == 2) {
                     std::cout << "[ DummyAnalyzer ]: Demonstration of searching for all products with 'cal' anywhere in the product name"
                               << std::endl;
                     auto pts = event.searchProducts(".*cal.*","","");
                     for (const auto &j : pts) std::cout << "\t" << j << std::endl;
                 }
                 ++ievt;
             }
References caloCol_, hEnergy, ievt, ldmx::EventProcessor::ntuple_, and ldmx::NtupleManager::setVar().
configure()
void ldmx::DummyAnalyzer::configure (Parameters & parameters) inline final override virtual
Configure the processor using the given user specified parameters.
Parameters
pSet Set of parameters used to configure this processor.
Reimplemented from ldmx::EventProcessor.
Definition at line 62 of file DummyAnalyzer.cxx.
{
                 caloCol_ = parameters.getParameter< std::string >("caloHitCollection");
             }
References caloCol_.
onFileClose()
void ldmx::DummyAnalyzer::onFileClose (EventFile & eventFile) inline final override virtual
Callback for the analyzer to take any action once the file has been closed.
Reimplemented from ldmx::EventProcessor.
Definition at line 143 of file DummyAnalyzer.cxx.
{
                 std::cout << "[ DummyAnalyzer ]: Closing "
                           << eventFile.getFileName() << "!" << std::endl;
             }
onFileOpen()
void ldmx::DummyAnalyzer::onFileOpen (EventFile & eventFile) inline final override virtual
Callback for the analyer to take any action once a file has been opened.
Reimplemented from ldmx::EventProcessor.
Definition at line 134 of file DummyAnalyzer.cxx.
{
                 std::cout << "[ DummyAnalyzer ]: Opening "
                           << eventFile.getFileName() << "!" << std::endl;
             }
onProcessEnd()
void ldmx::DummyAnalyzer::onProcessEnd () inline final override virtual
Callback for the analyzer to take any action after the processing of all events has ended.
Reimplemented from ldmx::EventProcessor.
Definition at line 176 of file DummyAnalyzer.cxx.
{
                 std::cout << "[ DummyAnalyzer ]: Finishing processing!" << std::endl;
             }
onProcessStart()
void ldmx::DummyAnalyzer::onProcessStart () inline final override virtual
Callback for the analyzer to take any action before the processing of events begins.
Reimplemented from ldmx::EventProcessor.
Definition at line 152 of file DummyAnalyzer.cxx.
{
                 std::cout << "[ DummyAnalyzer ]: Starting processing!" << std::endl;
                 // Create a tree.  Note that the openHistoFile method needs to
                 // be called first.  By doing so, the histogram file is opened
                 // if it hasn't been by another process and the current
                 // directory is changed to the top level directory.
                 process_.openHistoFile();
                 // Create a tree and add variable to it
                 //    the ntuple_ member variable is inherited from EventProcessor
                 ntuple_.create("Dummy");
                 ntuple_.addVar<float>("Dummy", /* tree name */
                                       "energy");
                 // Create all histograms needed by the analyzer
                 getHistoDirectory();
                 hEnergy = new TH1F("Energy","Energy",500,0.0,1.0);
             }
References ldmx::NtupleManager::addVar(), ldmx::NtupleManager::create(), ldmx::EventProcessor::getHistoDirectory(), hEnergy, ldmx::EventProcessor::ntuple_, ldmx::Process::openHistoFile(), and ldmx::EventProcessor::process_.
Member Data Documentation
caloCol_
std::string ldmx::DummyAnalyzer::caloCol_ private
Name of the collection containing the name of the calorimeter hits.
Definition at line 189 of file DummyAnalyzer.cxx.
Referenced by analyze(), and configure().
The documentation for this class was generated from the following file:
Framework/src/DummyAnalyzer.cxx