LDMX Software: ldmx::DetectorIDInterpreter Class Reference
ldmx::DetectorIDInterpreter Class Reference
Class provides an "introspection" capability for the 32-bit packed IDs used for uniquely identifying hits and detector components.
#include <DetectorIDInterpreter.h>
Classes
struct IDSignature
struct SubdetectorIDFields
Public Types
typedef unsigned FieldValue
typedef std::vector< FieldValue > FieldValueList
Public Member Functions
DetectorIDInterpreter (DetectorID detid)
DetectorID getId () const
void setRawValue (DetectorID rawValue)
FieldValue getFieldValue (int i) const
void setFieldValue (int i, FieldValue value)
void setFieldValue (const std::string &fieldName, FieldValue fieldValue)
int getFieldCount () const
const IDField::IDFieldList & getFieldList () const
const IDField * getField (const std::string &fieldName) const
FieldValue getFieldValue (const std::string &fieldName) const
Static Public Member Functions
static void registerInterpreter (SubdetectorIDType idtype, const IDField::IDFieldList &fieldList)
static void registerInterpreter (SubdetectorIDType idtype, unsigned int mask, unsigned int equality, const IDField::IDFieldList &fieldList)
Private Member Functions
void init ()
void unpack ()
void pack ()
Static Private Member Functions
static void loadStandardInterpreters ()
Private Attributes
DetectorID id_
FieldValueList fieldValues_
const SubdetectorIDFields * p_fieldInfo_
Static Private Attributes
static std::map< IDSignature, const SubdetectorIDFields * > g_rosettaStone
Detailed Description
Class provides an "introspection" capability for the 32-bit packed IDs used for uniquely identifying hits and detector components.
Note
Represents an ID in the detector with a raw, 32-bit value which can be unpacked into a list of field values or packed from a list of field values.
Definition at line 25 of file DetectorIDInterpreter.h.
Member Typedef Documentation
FieldValue
typedef unsigned ldmx::DetectorIDInterpreter::FieldValue
Definition of the field value type.
Definition at line 35 of file DetectorIDInterpreter.h.
FieldValueList
typedef std::vector<FieldValue> ldmx::DetectorIDInterpreter::FieldValueList
A list of field values.
Definition at line 40 of file DetectorIDInterpreter.h.
Constructor & Destructor Documentation
DetectorIDInterpreter() [1/2]
ldmx::DetectorIDInterpreter::DetectorIDInterpreter ()
Definition at line 16 of file DetectorIDInterpreter.cxx.
                                             : id_(), p_fieldInfo_(0) {
  init();
}
DetectorIDInterpreter() [2/2]
ldmx::DetectorIDInterpreter::DetectorIDInterpreter (DetectorID detid)
Definition at line 20 of file DetectorIDInterpreter.cxx.
    : id_(did), p_fieldInfo_(0) {
  init();
  unpack();
}
~DetectorIDInterpreter()
ldmx::DetectorIDInterpreter::~DetectorIDInterpreter ()
Definition at line 15 of file DetectorIDInterpreter.cxx.
{}
Member Function Documentation
getField()
const IDField * ldmx::DetectorIDInterpreter::getField (const std::string & fieldName) const
Get the information for a field by name.
Returns
The information of the field.
Definition at line 71 of file DetectorIDInterpreter.cxx.
{
  auto byname = p_fieldInfo_->fieldMap_.find(fieldName);
  if (byname != p_fieldInfo_->fieldMap_.end()) return (byname->second);
  return 0;
}
getFieldCount()
int ldmx::DetectorIDInterpreter::getFieldCount () const inline
Get the list of field information.
Returns
The list of field information.
Definition at line 78 of file DetectorIDInterpreter.h.
{ return int(p_fieldInfo_->fieldList_.size()); }
References p_fieldInfo_.
getFieldList()
const IDField::IDFieldList & ldmx::DetectorIDInterpreter::getFieldList () const inline
Get the list of field information.
Returns
The list of field information.
Definition at line 84 of file DetectorIDInterpreter.h.
{
    return p_fieldInfo_->fieldList_;
  }
References p_fieldInfo_.
getFieldValue() [1/2]
DetectorIDInterpreter::FieldValue ldmx::DetectorIDInterpreter::getFieldValue (const std::string & fieldName) const
Decode and return a field's value by name (e.g. "layer").
Returns
The value of the field.
Definition at line 78 of file DetectorIDInterpreter.cxx.
{
  auto byname = p_fieldInfo_->fieldMap_.find(fieldName);
  return getFieldValue(byname->second->getIndex());
}
getFieldValue() [2/2]
DetectorIDInterpreter::FieldValue ldmx::DetectorIDInterpreter::getFieldValue (int i) const
Decode and return a field's value from the raw ID.
Parameters
i The index of the field value.
Definition at line 51 of file DetectorIDInterpreter.cxx.
                 {
  IDField* field = p_fieldInfo_->fieldList_.at(i);
  unsigned result = (field->getBitMask() & id_.raw()) >> field->getStartBit();
  return result;
}
References ldmx::IDField::getBitMask(), and ldmx::IDField::getStartBit().
Referenced by TEST_CASE().
getId()
DetectorID ldmx::DetectorIDInterpreter::getId () const inline
Get the raw value of the detector ID.
Returns
The raw value.
Definition at line 46 of file DetectorIDInterpreter.h.
{ return id_; }
References id_.
Referenced by TEST_CASE().
init()
void ldmx::DetectorIDInterpreter::init () private
Reinitialize the ID in case the field list changed. This is called automatically by setFieldList. Function should be called by a subclass if a new field list is set outside that method or if new fields are added to the existing list.
Definition at line 84 of file DetectorIDInterpreter.cxx.
{
  if (g_rosettaStone.empty()) loadStandardInterpreters();
  p_fieldInfo_ = 0;
  if (id_.null()) return;
  for (auto ptr : g_rosettaStone) {
    if ((id_.raw() & ptr.first.mask_) == ptr.first.comparison_) {
      p_fieldInfo_ = (ptr.second);
      this->fieldValues_.resize(p_fieldInfo_->fieldList_.size());
      return;
    }
  }
  // fell through, no match
  IDSignature sig;
  sig.comparison_ = 0;
  sig.mask_ = DetectorID::SUBDETECTORID_MASK << DetectorID::SUBDETECTORID_SHIFT;
  auto ptr = g_rosettaStone.find(sig);
  p_fieldInfo_ = (ptr->second);
  this->fieldValues_.resize(p_fieldInfo_->fieldList_.size());
}
loadStandardInterpreters()
void ldmx::DetectorIDInterpreter::loadStandardInterpreters () static private
Load the standard field interpreters if not yet loaded. @important Developers of new Ids should add construction calls here!
Definition at line 146 of file DetectorIDInterpreter.cxx.
{
  if (!g_rosettaStone.empty()) return;
  IDField::IDFieldList fields;
  fields.push_back(
      new IDField("subdetector", 0, DetectorID::SUBDETECTORID_SHIFT, 31));
  fields.push_back(
      new IDField("payload", 2, 0, DetectorID::SUBDETECTORID_SHIFT - 1));
  registerInterpreter(SD_NULL, fields);
  EcalID::createInterpreters();
  EcalTriggerID::createInterpreters();
  HcalID::createInterpreters();
  TrackerID::createInterpreters();
  TrigScintID::createInterpreters();
  SimSpecialID::createInterpreters();
}
pack()
void ldmx::DetectorIDInterpreter::pack () private
Pack the current list of field values into a raw value.
Definition at line 41 of file DetectorIDInterpreter.cxx.
{
  DetectorID::RawValue rawValue = 0;
  for (auto field : p_fieldInfo_->fieldList_) {
    unsigned fieldValue = fieldValues_[field->getIndex()];
    rawValue =
        rawValue | ((fieldValue << field->getStartBit()) & field->getBitMask());
  }
  id_.setRawValue(rawValue);
}
registerInterpreter() [1/2]
void ldmx::DetectorIDInterpreter::registerInterpreter (SubdetectorIDType idtype, const IDField::IDFieldList & fieldList) static
Register a new field interpreter for a given subdetector id
Definition at line 109 of file DetectorIDInterpreter.cxx.
{
  IDSignature sig;
  sig.comparison_ = idtype << DetectorID::SUBDETECTORID_SHIFT;
  sig.mask_ = DetectorID::SUBDETECTORID_MASK << DetectorID::SUBDETECTORID_SHIFT;
  if (g_rosettaStone.find(sig) != g_rosettaStone.end()) {
    EXCEPTION_RAISE("DetectorIDException",
                    "Attempted to replace interpreter for subdetector " +
                        std::to_string(idtype));
  }
  SubdetectorIDFields* fields = new SubdetectorIDFields();
  fields->fieldList_ = fieldList;
  for (auto it : fieldList) fields->fieldMap_[it->getFieldName()] = it;
  g_rosettaStone[sig] = fields;
}
registerInterpreter() [2/2]
void ldmx::DetectorIDInterpreter::registerInterpreter (SubdetectorIDType idtype, unsigned int mask, unsigned int equality, const IDField::IDFieldList & fieldList) static
Register a new field interpreter for a more-complex case where additional bits are needed to determine format
Definition at line 125 of file DetectorIDInterpreter.cxx.
{
  IDSignature sig;
  sig.comparison_ = (idtype << DetectorID::SUBDETECTORID_SHIFT) | equality;
  sig.mask_ =
      (DetectorID::SUBDETECTORID_MASK << DetectorID::SUBDETECTORID_SHIFT) |
      mask;
  if (g_rosettaStone.find(sig) != g_rosettaStone.end()) {
    EXCEPTION_RAISE("DetectorIDException",
                    "Attempted to replace interpreter for subdetector " +
                        std::to_string(idtype) + " mask " +
                        std::to_string(mask) + " equality " +
                        std::to_string(equality));
  }
  SubdetectorIDFields* fields = new SubdetectorIDFields();
  fields->fieldList_ = fieldList;
  for (auto it : fieldList) fields->fieldMap_[it->getFieldName()] = it;
  g_rosettaStone[sig] = fields;
}
setFieldValue() [1/2]
void ldmx::DetectorIDInterpreter::setFieldValue (const std::string & fieldName, FieldValue fieldValue)
Set a field value by its name.
Parameters
fieldName The name of the field.
fieldValue The new value of the field.
Definition at line 63 of file DetectorIDInterpreter.cxx.
{
  auto byname = p_fieldInfo_->fieldMap_.find(fieldName);
  if (byname != p_fieldInfo_->fieldMap_.end())
    fieldValues_[byname->second->getIndex()] = fieldValue;
  pack();  // keep packed
}
setFieldValue() [2/2]
void ldmx::DetectorIDInterpreter::setFieldValue (int i, FieldValue value)
Set a field value by index in the field value list.
Parameters
i The index of the field value.
value The new field value.
Definition at line 58 of file DetectorIDInterpreter.cxx.
{
  fieldValues_[i] = val;
  pack();  // keep packed
}
Referenced by TEST_CASE().
setRawValue()
void ldmx::DetectorIDInterpreter::setRawValue (DetectorID rawValue)
Set the raw value of the detector ID.
Parameters
rawValue The raw value of the ID.
Definition at line 26 of file DetectorIDInterpreter.cxx.
{
  id_ = rawValue;
  init();
  unpack();
}
unpack()
void ldmx::DetectorIDInterpreter::unpack () private
Unpack the current raw value into a list.
Definition at line 32 of file DetectorIDInterpreter.cxx.
{
  std::fill(fieldValues_.begin(), fieldValues_.end(), 0);
  if (!p_fieldInfo_) return;
  for (auto field : p_fieldInfo_->fieldList_) {
    unsigned result = (field->getBitMask() & id_.raw()) >> field->getStartBit();
    this->fieldValues_[field->getIndex()] = result;
  }
}
Member Data Documentation
fieldValues_
FieldValueList ldmx::DetectorIDInterpreter::fieldValues_ private
The unpacked list of field values.
Definition at line 149 of file DetectorIDInterpreter.h.
g_rosettaStone
std::map< DetectorIDInterpreter::IDSignature, const DetectorIDInterpreter::SubdetectorIDFields * > ldmx::DetectorIDInterpreter::g_rosettaStone static private
Definition at line 164 of file DetectorIDInterpreter.h.
id_
DetectorID ldmx::DetectorIDInterpreter::id_ private
The raw, packed value of the ID.
Definition at line 144 of file DetectorIDInterpreter.h.
Referenced by getId().
p_fieldInfo_
const SubdetectorIDFields* ldmx::DetectorIDInterpreter::p_fieldInfo_ private
Pointer to the appropriate field info for this class
Definition at line 169 of file DetectorIDInterpreter.h.
Referenced by getFieldCount(), and getFieldList().
The documentation for this class was generated from the following files:
DetDescr/include/DetDescr/DetectorIDInterpreter.h
DetDescr/src/DetDescr/DetectorIDInterpreter.cxx