LDMX Software: simcore::UserPrimaryParticleInformation Class Reference
simcore::UserPrimaryParticleInformation Class Reference
Defines extra information attached to a Geant4 primary particle.
#include <UserPrimaryParticleInformation.h>
Public Member Functions
UserPrimaryParticleInformation ()
virtual ~UserPrimaryParticleInformation ()
void setHepEvtStatus (int hepEvtStatus)
int getHepEvtStatus ()
void Print () const
Private Attributes
int hepEvtStatus_ {-1}
Detailed Description
Defines extra information attached to a Geant4 primary particle.
Definition at line 19 of file UserPrimaryParticleInformation.h.
Constructor & Destructor Documentation
UserPrimaryParticleInformation()
simcore::UserPrimaryParticleInformation::UserPrimaryParticleInformation () inline
Class Constructor.
Definition at line 25 of file UserPrimaryParticleInformation.h.
{ ; }
~UserPrimaryParticleInformation()
virtual simcore::UserPrimaryParticleInformation::~UserPrimaryParticleInformation () inline virtual
Class destructor.
Definition at line 30 of file UserPrimaryParticleInformation.h.
{ ; }
Member Function Documentation
getHepEvtStatus()
int simcore::UserPrimaryParticleInformation::getHepEvtStatus () inline
Get the HEP event status.
Returns
The HEP event status.
Definition at line 42 of file UserPrimaryParticleInformation.h.
{ return hepEvtStatus_; }
References hepEvtStatus_.
Referenced by simcore::PrimaryGeneratorAction::GeneratePrimaries(), and simcore::UserTrackingAction::PreUserTrackingAction().
Print()
void simcore::UserPrimaryParticleInformation::Print () const inline
Implement virtual method (no-op).
Definition at line 47 of file UserPrimaryParticleInformation.h.
{}
setHepEvtStatus()
void simcore::UserPrimaryParticleInformation::setHepEvtStatus (int hepEvtStatus) inline
Set the HEP event status (generator status) e.g. from an LHE particle.
Parameters
hepEvtStatus The HEP event status.
Definition at line 36 of file UserPrimaryParticleInformation.h.
{ hepEvtStatus_ = hepEvtStatus; }
References hepEvtStatus_.
Referenced by simcore::LHEPrimaryGenerator::GeneratePrimaryVertex(), and simcore::MultiParticleGunPrimaryGenerator::GeneratePrimaryVertex().
Member Data Documentation
hepEvtStatus_
int simcore::UserPrimaryParticleInformation::hepEvtStatus_ {-1} private
The HEP event status.
Definition at line 53 of file UserPrimaryParticleInformation.h.
Referenced by getHepEvtStatus(), and setHepEvtStatus().
The documentation for this class was generated from the following file:
SimCore/include/SimCore/UserPrimaryParticleInformation.h