LDMX Software: framework::ConditionsObjectProvider Class Reference
framework::ConditionsObjectProvider Class Reference abstract
Base class for all providers of conditions objects.
#include <ConditionsObjectProvider.h>
Public Member Functions
ConditionsObjectProvider (const std::string &objname, const std::string &tagname, const framework::config::Parameters &parameters, Process &process)
virtual ~ConditionsObjectProvider ()
virtual std::pair< const ConditionsObject *, ConditionsIOV > getCondition (const ldmx::EventHeader &context)=0
virtual void releaseConditionsObject (const ConditionsObject *co)
virtual void onProcessStart ()
virtual void onProcessEnd ()
virtual void onNewRun (ldmx::RunHeader &)
const std::string & getConditionObjectName () const
const std::string & getTagName () const
Static Public Member Functions
static void declare (const std::string &classname, ConditionsObjectProviderMaker *)
Static Public Attributes
static const int CLASSTYPE {10}
Protected Member Functions
std::pair< const ConditionsObject *, ConditionsIOV > requestParentCondition (const std::string &name, const ldmx::EventHeader &context)
const Process & process () const
Protected Attributes
logging::logger theLog_
The logger for this ConditionsObjectProvider.
Private Attributes
Process & process_
std::string objectName_
std::string tagname_
Detailed Description
Base class for all providers of conditions objects.
Definition at line 48 of file ConditionsObjectProvider.h.
Constructor & Destructor Documentation
ConditionsObjectProvider()
ConditionsObjectProvider::ConditionsObjectProvider (const std::string & objname, const std::string & tagname, const framework::config::Parameters & parameters, Process & process)
Class constructor.
Parameters
name Name for this instance of the class.
tagName The tag for the database entry (should not include whitespace)
process The Process class associated with ConditionsObjectProvider, provided by the framework.
Note
The name provided to this function should not be the class name, but rather a logical label for this instance of the class, as more than one copy of a given class can be loaded into a Process with different parameters. Names should not include whitespace or special characters.
Definition at line 9 of file ConditionsObjectProvider.cxx.
    : process_{process},
      objectName_{objname},
      tagname_{tagname},
      theLog_{logging::makeLogger(objname)} {}
~ConditionsObjectProvider()
virtual framework::ConditionsObjectProvider::~ConditionsObjectProvider () inline virtual
Class destructor.
Definition at line 75 of file ConditionsObjectProvider.h.
{ ; }
Member Function Documentation
declare()
void ConditionsObjectProvider::declare (const std::string & classname, ConditionsObjectProviderMaker * maker) static
Internal function which is part of the PluginFactory machinery.
Parameters
classname The class name of the processor.
Definition at line 25 of file ConditionsObjectProvider.cxx.
{
  PluginFactory::getInstance().registerConditionsObjectProvider(
      classname, CLASSTYPE, maker);
}
References CLASSTYPE, framework::PluginFactory::getInstance(), and framework::PluginFactory::registerConditionsObjectProvider().
getCondition()
virtual std::pair< const ConditionsObject *, ConditionsIOV > framework::ConditionsObjectProvider::getCondition (const ldmx::EventHeader & context) pure virtual
Pure virtual getCondition function. Must be implemented by any Conditions providers.
Implemented in conditions::SimpleCSVTableProvider, ecal::EcalDetectorMapLoader, ecal::EcalGeometryProvider, ecal::EcalTriggerGeometryProvider, framework::RandomNumberSeedService, hcal::HcalDetectorMapLoader, hcal::HcalGeometryProvider, and hcal::HcalTriggerGeometryProvider.
getConditionObjectName()
const std::string & framework::ConditionsObjectProvider::getConditionObjectName () const inline
Get the list of conditions objects available from this provider.
Definition at line 115 of file ConditionsObjectProvider.h.
{ return objectName_; }
References objectName_.
Referenced by framework::Conditions::createConditionsObjectProvider().
getTagName()
const std::string & framework::ConditionsObjectProvider::getTagName () const inline
Access the tag name
Definition at line 127 of file ConditionsObjectProvider.h.
{ return tagname_; }
References tagname_.
onNewRun()
virtual void framework::ConditionsObjectProvider::onNewRun (ldmx::RunHeader &) inline virtual
Callback for the ConditionsObjectProvider to take any necessary action when the processing of events starts for a given run.
Reimplemented in framework::RandomNumberSeedService, ecal::EcalGeometryProvider, and hcal::HcalGeometryProvider.
Definition at line 110 of file ConditionsObjectProvider.h.
{}
onProcessEnd()
virtual void framework::ConditionsObjectProvider::onProcessEnd () inline virtual
Callback for the ConditionsObjectProvider to take any necessary action when the processing of events finishes, such as closing database connections.
Definition at line 104 of file ConditionsObjectProvider.h.
{}
onProcessStart()
virtual void framework::ConditionsObjectProvider::onProcessStart () inline virtual
Callback for the ConditionsObjectProvider to take any necessary action when the processing of events starts.
Definition at line 97 of file ConditionsObjectProvider.h.
{}
process()
const Process & framework::ConditionsObjectProvider::process () const inline protected
Get the process handle
Definition at line 138 of file ConditionsObjectProvider.h.
{ return process_; }
References process_.
Referenced by framework::RandomNumberSeedService::onNewRun().
releaseConditionsObject()
virtual void framework::ConditionsObjectProvider::releaseConditionsObject (const ConditionsObject * co) inline virtual
Called by conditions system when done with a conditions object, appropriate point for cleanup.
Note
Default behavior is to delete the object!
Reimplemented in framework::RandomNumberSeedService, ecal::EcalDetectorMapLoader, ecal::EcalGeometryProvider, ecal::EcalTriggerGeometryProvider, hcal::HcalDetectorMapLoader, hcal::HcalGeometryProvider, and hcal::HcalTriggerGeometryProvider.
Definition at line 89 of file ConditionsObjectProvider.h.
{
    delete co;
  }
requestParentCondition()
std::pair< const ConditionsObject *, ConditionsIOV > ConditionsObjectProvider::requestParentCondition (const std::string & name, const ldmx::EventHeader & context) protected
Request another condition needed to construct this condition
Definition at line 18 of file ConditionsObjectProvider.cxx.
{
  const ConditionsObject* obj = process_.getConditions().getConditionPtr(name);
  ConditionsIOV iov = process_.getConditions().getConditionIOV(name);
  return std::make_pair(obj, iov);
}
References framework::Conditions::getConditionIOV(), framework::Conditions::getConditionPtr(), framework::Process::getConditions(), and process_.
Referenced by ecal::EcalTriggerGeometryProvider::getCondition().
Member Data Documentation
CLASSTYPE
const int framework::ConditionsObjectProvider::CLASSTYPE {10} static
Constant used to types by the PluginFactory
Definition at line 51 of file ConditionsObjectProvider.h.
Referenced by declare().
objectName_
std::string framework::ConditionsObjectProvider::objectName_ private
The name of the object provided by this provider.
Definition at line 145 of file ConditionsObjectProvider.h.
Referenced by getConditionObjectName().
process_
Process& framework::ConditionsObjectProvider::process_ private
Handle to the Process.
Definition at line 142 of file ConditionsObjectProvider.h.
Referenced by process(), and requestParentCondition().
tagname_
std::string framework::ConditionsObjectProvider::tagname_ private
The tag name for the ConditionsObjectProvider.
Definition at line 148 of file ConditionsObjectProvider.h.
Referenced by getTagName().
theLog_
logging::logger framework::ConditionsObjectProvider::theLog_ protected
The logger for this ConditionsObjectProvider.
Definition at line 135 of file ConditionsObjectProvider.h.
The documentation for this class was generated from the following files:
Framework/include/Framework/ConditionsObjectProvider.h
Framework/src/Framework/ConditionsObjectProvider.cxx