LDMX Software: ldmx::test::TestProducer Class Reference
ldmx::test::TestProducer Class Reference
Public Member Functions
TestProducer (const std::string &name, Process &p)
void configure (Parameters &p) final override
void produce (Event &event) final override
void onFileClose (EventFile &eventFile) final override
Public Member Functions inherited from ldmx::Producer
Producer (const std::string &name, Process &process)
Public Member Functions inherited from ldmx::EventProcessor
EventProcessor (const std::string &name, Process &process)
virtual ~EventProcessor ()
virtual void onNewRun (const RunHeader &runHeader)
virtual void onFileOpen (EventFile &eventFile)
virtual void onProcessStart ()
virtual void onProcessEnd ()
TDirectory * getHistoDirectory ()
void setStorageHint (ldmx::StorageControlHint hint)
void setStorageHint (ldmx::StorageControlHint hint, const std::string &purposeString)
int getLogFrequency () const
int getRunNumber () const
void createHistograms (const std::vector< Parameters > &histos)
Private Attributes
int events_
number of events we've gotten to
bool createRunHeader_
should we create the run header?
Additional Inherited Members
Static Public Member Functions inherited from ldmx::EventProcessor
static void declare (const std::string &classname, int classtype, EventProcessorMaker *)
Static Public Attributes inherited from ldmx::Producer
static const int CLASSTYPE {1}
Protected Member Functions inherited from ldmx::EventProcessor
void abortEvent ()
Protected Attributes inherited from ldmx::EventProcessor
HistogramHelper histograms_
Interface class for making and filling histograms.
NtupleManager & ntuple_ {NtupleManager::getInstance()}
Manager for any ntuples.
logging::logger theLog_
The logger for this EventProcessor.
Detailed Description
Bare producer that creates a collection and an object and puts them on the event bus.
The pattern this producer creates is the following:
The vector of Calorimeter hits has the same number of entries as the event number
The IDs of the calorimeter hits are set to 10*eventNumber+their_index
The input object is an HcalVetoResult where events with an event index pass
The max PE hit in the HcalVetoResult has an ID equal to the event index
If a run header is created, the event count and the run number are equal
Checks
Event::add function does not throw any errors.
Writes and adds a run header where the run number and the number of events are the same.
sets a storage hint
Definition at line 39 of file FunctionalCoreTest.cxx.
Member Function Documentation
configure()
void ldmx::test::TestProducer::configure (Parameters & parameters) inline final override virtual
Callback for the EventProcessor to configure itself from the given set of parameters.
The parameters a processor has access to are the member variables of the python class in the sequence that has className equal to the EventProcessor class name.
For an example, look at MyProcessor.
Parameters
parameters Parameters for configuration.
Reimplemented from ldmx::EventProcessor.
Definition at line 52 of file FunctionalCoreTest.cxx.
{
             createRunHeader_ = p.getParameter<bool>("createRunHeader");
         }
References createRunHeader_.
onFileClose()
void ldmx::test::TestProducer::onFileClose (EventFile & eventFile) inline final override virtual
Callback for the EventProcessor to take any necessary action when a event input ROOT file is closed.
Parameters
filename Input event ROOT file name
Note
This callback is rarely used.
Reimplemented from ldmx::EventProcessor.
Definition at line 86 of file FunctionalCoreTest.cxx.
{
             if ( not createRunHeader_ ) return;
             RunHeader runHeader( events_ , "No Detector" , "Test Run" );
             runHeader.setIntParameter( "Event Count" , events_ );
             //stores run header to runtree in output file
             eventFile.writeRunHeader( runHeader );
             return;
         }
References createRunHeader_, events_, and ldmx::RunHeader::setIntParameter().
produce()
void ldmx::test::TestProducer::produce (Event & event) inline final override virtual
Process the event and put new data products into it.
Parameters
event The Event to process.
Implements ldmx::Producer.
Definition at line 56 of file FunctionalCoreTest.cxx.
{
             int i_event = event.getEventNumber();
             REQUIRE( i_event > 0 );
             std::vector<CalorimeterHit> caloHits;
             for ( int i = 0; i < i_event; i++ ) {
                 caloHits.emplace_back();
                 caloHits.back().setID( i_event*10 + i );
             }
             REQUIRE_NOTHROW( event.add( "TestCollection" , caloHits ) );
             HcalHit maxPEHit;
             maxPEHit.setID( i_event );
             HcalVetoResult res;
             res.setMaxPEHit( maxPEHit );
             res.setVetoResult( i_event % 2 == 0 );
             REQUIRE_NOTHROW( event.add( "TestObject" , res ) );
             events_ = i_event;
             if ( res.passesVeto() ) setStorageHint( hint_mustKeep );
             return;
         }
References events_, ldmx::HcalVetoResult::passesVeto(), ldmx::CalorimeterHit::setID(), ldmx::HcalVetoResult::setMaxPEHit(), ldmx::EventProcessor::setStorageHint(), and ldmx::HcalVetoResult::setVetoResult().
The documentation for this class was generated from the following file:
Framework/test/FunctionalCoreTest.cxx