LDMX Software: ldmx::EcalHexReadout Class Reference
ldmx::EcalHexReadout Class Reference
Implementation of ECal hexagonal cell readout.
#include <EcalHexReadout.h>
Public Member Functions
virtual ~EcalHexReadout ()
void getCellAbsolutePosition (EcalID id, double &x, double &y, double &z) const
double getZPosition (int layer) const
int getNumLayers () const
std::pair< double, double > getModuleCenter (int moduleID) const
int getNumModulesPerLayer () const
int getModuleID (double x, double y) const
int getCellIDRelative (double x, double y) const
int getNumCellsPerModule () const
std::pair< double, double > getCellCenterRelative (int cellID) const
EcalID getCellModuleID (double x, double y) const
std::pair< double, double > getCellCenterAbsolute (EcalID cellModuleID) const
double distanceToEdge (EcalID cellModuleID) const
bool isEdgeCell (EcalID cellModuleID) const
bool isInside (double normX, double normY) const
std::vector< EcalID > getNN (EcalID id) const
bool isNN (EcalID centroid, EcalID probe) const
std::vector< EcalID > getNNN (EcalID id) const
bool isNNN (EcalID centroid, EcalID probe) const
double getModuleMinR () const
double getModuleMaxR () const
double getCellMinR () const
double getCellMaxR () const
const std::map< int, std::pair< double, double > > & getCellPositionMap () const
const std::map< EcalID, std::pair< double, double > > & getCellModulePositionMap () const
TH2Poly * getCellPolyMap () const
Public Member Functions inherited from framework::ConditionsObject
ConditionsObject (const std::string &name)
virtual ~ConditionsObject ()
std::string getName () const
Static Public Member Functions
static EcalHexReadout * debugMake (const framework::config::Parameters &p)
Static Public Attributes
static constexpr const char * CONDITIONS_OBJECT_NAME {"EcalHexReadout"}
Private Member Functions
EcalHexReadout (const framework::config::Parameters &ps)
void buildModuleMap ()
void buildCellMap ()
void buildCellModuleMap ()
void buildNeighborMaps ()
void buildTriggerGroup ()
Private Attributes
int verbose_ {2}
verbosity, not configurable but helpful if developing
double gap_
Gap between module flat sides [mm].
double cellr_ {0}
Center-to-Flat Radius of cell hexagon [mm].
double moduler_ {0}
Center-to-Flat Radius of module hexagon [mm].
double cellR_ {0}
Center-to-Corner Radius of cell hexagon [mm].
double moduleR_ {0}
Center-to-Corner Radius of module hexagon [mm].
bool cornersSideUp_
indicator of geometry orientation – if true, flower shape's corners side (ie: side with two modules) is at the top
double nCellRHeight_ {0}
double ecalFrontZ_ {0}
Front of ECal relative to world geometry [mm].
std::vector< double > layerZPositions_
The layer Z postions are with respect to the front of the ECal [mm].
std::map< int, std::pair< double, double > > modulePositionMap_
std::map< int, std::pair< double, double > > cellPositionMap_
Position of cell centers relative to module (uses cell ID as key)
std::map< EcalID, std::pair< double, double > > cellModulePositionMap_
std::map< EcalID, std::vector< EcalID > > NNMap_
std::map< EcalID, std::vector< EcalID > > NNNMap_
std::vector< int > triggerGroups_
List of Trigger Group IDs (index is cell ID)
TH2Poly ecalMap_
Friends
class ecal::EcalGeometryProvider
Detailed Description
Implementation of ECal hexagonal cell readout.
This is the object that does the extra geometry not implemented in the gdml. In order to save time during the simulation, the individual cells in the readout hexagons are not constructed individually in Geant4. This means we have to have a translation between position and cell ID which is accomplished by this class.
ORIENTATION ASSUMPTIONS:
modules are oriented flat side down.
cells are oriented corner side down.
SOME GEOMETRY:
hexagons have two radii:
r (half of flat-to-flat width) and R (half of corner-to-corner width).
r = (sqrt(3)/2)R and s = R, where s is the length of an edge.
for seven ecal modules oriented flat-side-down, maximum x and y extents are:
deltaY = 6r' + 2g = 3sqrt(3)R' + 2g
deltaX = 4R' + s' + 2g/cos(30 deg) = 5R' + 4g/sqrt(3)
where g is uniform gap width between modules, and primed variables correspond to modules.
THIS GRID:
column-to-column distance in a grid such as ours is 2r = sqrt(3)R.
row-to-row distance is 1.5R (easy to observe that twice that distance = 3R)
The cell radius is calculated from the total number of center-to-corner cell radii that span the module height. This count can have fractional counts to account for the fractions of cell radii at the module edges.
Definition at line 67 of file EcalHexReadout.h.
Constructor & Destructor Documentation
~EcalHexReadout()
virtual ldmx::EcalHexReadout::~EcalHexReadout () inline virtual
Class destructor.
Does nothing because the stl containers clean up automatically.
Definition at line 76 of file EcalHexReadout.h.
{}
EcalHexReadout()
ldmx::EcalHexReadout::EcalHexReadout (const framework::config::Parameters & ps) private
Class constructor, for use only by the provider
Parameters
ps Parameters to configure the EcalHexReadout
Definition at line 15 of file EcalHexReadout.cxx.
    : framework::ConditionsObject(EcalHexReadout::CONDITIONS_OBJECT_NAME) {
  layerZPositions_ = ps.getParameter<std::vector<double>>("layerZPositions");
  ecalFrontZ_ = ps.getParameter<double>("ecalFrontZ");
  moduler_ = ps.getParameter<double>("moduleMinR");
  gap_ = ps.getParameter<double>("gap");
  nCellRHeight_ = ps.getParameter<double>("nCellRHeight");
  verbose_ = ps.getParameter<int>("verbose");
  cornersSideUp_ = ps.getParameter<bool>("cornersSideUp");
  moduleR_ = moduler_ * (2 / sqrt(3));
  cellR_ = 2 * moduler_ / nCellRHeight_;
  cellr_ = (sqrt(3.) / 2.) * cellR_;
  if (verbose_ > 0) {
    std::cout << std::endl
              << "[EcalHexReadout] Verbosity set in header to " << verbose_
              << std::endl;
    std::cout << "     Building module map with gap " << std::setprecision(2)
              << gap_ << ", nCellRHeight " << nCellRHeight_
              << ",  min/max radii of cell " << cellr_ << " / " << cellR_
              << ", and module " << moduler_ << " / " << moduleR_ << std::endl;
  }
  buildModuleMap();
  buildCellMap();
  buildCellModuleMap();
  buildNeighborMaps();
  if (verbose_ > 0) {
    std::cout << std::endl;
  }
}
References buildCellMap(), buildCellModuleMap(), buildModuleMap(), buildNeighborMaps(), cellr_, cellR_, cornersSideUp_, ecalFrontZ_, gap_, framework::config::Parameters::getParameter(), layerZPositions_, moduler_, moduleR_, nCellRHeight_, and verbose_.
Member Function Documentation
buildCellMap()
void ldmx::EcalHexReadout::buildCellMap () private
Constructs the flat-bottomed hexagonal grid (cellID) of corner-down hexagonal cells.
Sets ecalMap_ with the defined bins being the ecal cells in coordinates with respect to the module center. Also sets cellPostionMap_ with the keys being the cell ID and the values being the position of the cell with respect to the module center.
Strategy
Use ROOT's TH2Poly::HoneyComb method to build a large hexagonal grid, then copy the polygons from it which overlap with the module with more than one vertex.
A vertex between three cells is placed at the origin, then the bottom left corner of the honeycomb and the number of x and y cells across the honeycomb is calculated by continuing to decrement the grid x/y point until the module center-to-flat distance is reached.
The hexagons that only have one vertex outside the module hexagon leave a small space un-covered by the tiling, so the vertices adjacent to the external vertex are projected onto the module edge.
Parameters
[in] cellr_ the center-to-flat cell radius
[in] cellR_ the center-to-corner cell radius
[in] moduler_ the center-to-flat module radius
[in] moduleR_ the center-to-flat module radius
[out] ecalMap_ TH2Poly with local cell ID to local cell position mapping
[out] cellPostionMap_ map of local cell ID to cell center position relative to module
STRATEGY rotated cells are hardcoded unrotated cells use ROOT HoneyComb method (build large hex grid, copy polygons that cover module)
Definition at line 86 of file EcalHexReadout.cxx.
{
  if (cornersSideUp_) {
    Double_t a = cellR_;  // cell long radius (or hexagon flat side length)
    Double_t xCenter = 0.;
    Double_t yCenter = 0.;
    Double_t numberOfCellsFlatSide = 12;
    Double_t x[6], y[6];
    //(xLoop,yLoop)-coordinate of the first starting vertex in the "for" loops
    //(xTemp,yTemp)-the changing starting vertex as loops through columns/rows
    Double_t xLoop, yLoop, xTemp, yTemp;
    int yColNum;
    int ecalMapID = 0;
    // The hexagon grid divides into two sections: two trapezoids
    // Cell map starts from top left
    // Section 1: Left trapezoid (13cell short base, 24cell long base, 12cell
    // lateral side
    xLoop = xCenter - a * 18.0;
    yLoop = yCenter + a * 18.0 / TMath::Sqrt(3);
    for (int xCounter = 0; xCounter < numberOfCellsFlatSide;
         xCounter++) {  // lateral side->12cells
      yTemp = yLoop;    // resets the temporary variable
      yColNum =
          numberOfCellsFlatSide + xCounter + 1;  // number of cells in each column
      for (int yCounter = 0; yCounter < yColNum; yCounter++) {
        // Create a cell: go clockwise around the hexagon vertices starting from
        // the left-most one
        x[0] = xLoop;
        y[0] = yTemp;
        x[1] = x[0] + a / 2.0;
        y[1] = y[0] + a * TMath::Sqrt(3) / 2.0;
        x[2] = x[1] + a;
        y[2] = y[1];
        x[3] = x[2] + a / 2.0;
        y[3] = y[0];
        x[4] = x[2];
        y[4] = y[3] - a * TMath::Sqrt(3) / 2.0;
        x[5] = x[1];
        y[5] = y[4];
        ecalMap_.AddBin(6, x, y);
        double cellx = (x[0] + x[3]) / 2;
        double celly = (y[1] + y[4]) / 2;
        cellPositionMap_[ecalMapID] = std::pair<double, double>(cellx, celly);
        ecalMapID++;
        // Go down
        yTemp -= a * TMath::Sqrt(3);
      }
      // Increment the starting position from column to column
      yLoop += a * TMath::Sqrt(3) / 2.0;
      xLoop += 1.5 * a;
    }
    // Section 2: Right trapezoid (12cell short base, 23cell long base, 12cell
    // lateral side
    xLoop = xCenter;
    yLoop = yCenter + a * 11.0 * TMath::Sqrt(3);
    for (int xCounter = 0; xCounter < numberOfCellsFlatSide; xCounter++) {
      yTemp = yLoop;
      yColNum = 2 * numberOfCellsFlatSide - xCounter -
                1;  // number of cells in each column
      for (int yCounter = 0; yCounter < yColNum; yCounter++) {
        // Create a cell: go clockwise around the hexagon vertices starting from
        // the left-most one
        x[0] = xLoop;
        y[0] = yTemp;
        x[1] = x[0] + a / 2.0;
        y[1] = y[0] + a * TMath::Sqrt(3) / 2.0;
        x[2] = x[1] + a;
        y[2] = y[1];
        x[3] = x[2] + a / 2.0;
        y[3] = y[0];
        x[4] = x[2];
        y[4] = y[3] - a * TMath::Sqrt(3) / 2.0;
        x[5] = x[1];
        y[5] = y[4];
        ecalMap_.AddBin(6, x, y);
        double cellx = (x[0] + x[3]) / 2;
        double celly = (y[1] + y[4]) / 2;
        cellPositionMap_[ecalMapID] = std::pair<double, double>(cellx, celly);
        ecalMapID++;
        // Go down
        yTemp -= a * TMath::Sqrt(3);
      }
      // Increment the starting position from column to column
      yLoop -= a * TMath::Sqrt(3) / 2.0;
      xLoop += 1.5 * a;
    }
  }
  else {
    TH2Poly gridMap;
    // make hexagonal grid [boundary is rectangle] larger than the module
    double gridMinX = 0., gridMinY = 0.;  // start at the origin
    int numXCells = 0, numYCells = 0;
    // first x-cell is only a half
    gridMinX -= cellr_;
    numXCells++;
    while (gridMinX > -1 * moduleR_) {
      gridMinX -= 2 * cellr_;  // decrement x by cell center-to-flat diameter
      numXCells++;
    }
    while (gridMinY > -1 * moduler_) {
      // decrement y by cell center-to-corner radius
      //  alternate between a full corner-to-corner diameter
      //  and a side of a cell (center-to-corner radius)
      if (numYCells % 2 == 0)
    gridMinY -= 1 * cellR_;
      else
    gridMinY -= 2 * cellR_;
      numYCells++;
    }
    // only counted one half of the cells
    numXCells *= 2;
    numYCells *= 2;
    gridMap.Honeycomb(gridMinX, gridMinY, cellR_, numXCells, numYCells);
    if (verbose_ > 0) {
      std::cout << std::endl;
      std::cout << std::setprecision(2) << "[buildCellMap] cell rmin: " << cellr_
        << " cell rmax: " << cellR_ << " (gridMinX,gridMinY) = ("
        << gridMinX << "," << gridMinY << ")"
        << " (numXCells,numYCells) = (" << numXCells << "," << numYCells
        << ")" << std::endl;
    }
    // copy cells lying within module boundaries to a module grid
    TListIter next(gridMap.GetBins());  // a TH2Poly is a TList of TH2PolyBin
    TH2PolyBin* polyBin = 0;
    TGraph* poly = 0;   // a polygon returned by TH2Poly is a TGraph
    int ecalMapID = 0;  // ecalMap cell IDs go from 0 to N-1, not equal to
    // original grid cell ID.
    while ((polyBin = (TH2PolyBin*)next())) {
      // these bins are coming from the honeycomb
      //  grid so we assume that they are regular
      //  hexagons i.e. has 6 vertices
      poly = (TGraph*)polyBin->GetPolygon();
      // decide whether to copy polygon to new map.
      // use all vertices in case of cut-off edge polygons.
      int numVerticesInside = 0;
      double vertex_x[6], vertex_y[6];  // vertices of the cell
      bool isinside[6];                 // which vertices are inside
      if (verbose_ > 2) std::cout << "[buildCellMap] Cell vertices" << std::endl;
      for (unsigned i = 0; i < 6; i++) {
    poly->GetPoint(i, vertex_x[i], vertex_y[i]);
    if (verbose_ > 2) {
      std::cout << "     vtx # " << i << std::endl;
      std::cout << "     vtx x,y " << vertex_x[i] << " " << vertex_y[i]
            << std::endl;
    }
    isinside[i] = isInside(vertex_x[i] / moduleR_, vertex_y[i] / moduleR_);
    if (isinside[i]) numVerticesInside++;
      }
      if (numVerticesInside > 1) {
    // Include this cell if more than one of its vertices is inside the module
    // hexagon
    double actual_x[8], actual_y[8];
    int num_vertices{0};
    if (numVerticesInside < 6) {
      // This cell is stradling the edge of the module
      // and is NOT cleanly cut by module edge
      if (verbose_ > 1) {
        std::cout << "[buildCellMap] Polygon " << ecalMapID
              << " has vertices poking out of module hexagon."
              << std::endl;
      }
      // loop through vertices
      for (int i = 0; i < 6; i++) {
        int up = i == 5 ? 0 : i + 1;
        int dn = i == 0 ? 5 : i - 1;
        if (isinside[i] and (not isinside[up] or not isinside[dn])) {
          // this vertex is inside the module hexagon and is adjacent to a
          // vertex outside
            // ==> project this vertex onto the nearest edge of the module
            // hexagon
            // determine which side of hexagon we should project onto
          double edge_origin_x, edge_origin_y;
          double edge_dest_x, edge_dest_y;
          if (vertex_x[i] < -moduleR_ / 2.) {
        // sloped edge on negative-x side
        edge_origin_x = -1. * moduleR_;
        edge_origin_y = 0.;
        edge_dest_x = -0.5 * moduleR_;
        edge_dest_y = moduler_;
          } else if (vertex_x[i] > moduleR_ / 2.) {
        // sloped edge on positive-x side
        edge_origin_x = 0.5 * moduleR_;
        edge_origin_y = moduler_;
        edge_dest_x = moduleR_;
        edge_dest_y = 0.;
          } else {
        // flat edge at top
        edge_origin_x = 0.5 * moduleR_;
        edge_origin_y = moduler_;
        edge_dest_x = -0.5 * moduleR_;
        edge_dest_y = moduler_;
          }
          // flip to bottom half if below x-axis
          if (vertex_y[i] < 0) {
        edge_dest_y *= -1;
        edge_origin_y *= -1;
          }
          // get edge slope vector
          double edge_slope_x = edge_dest_x - edge_origin_x;
          double edge_slope_y = edge_dest_y - edge_origin_y;
          if (verbose_ > 2) {
              std::cout
        << "Vertex " << i
        << " is inside and adjacent to a vertex outside the module."
        << std::endl;
              std::cout << "Working on edge with slope (" << edge_slope_x << ","
                        << edge_slope_y << ")"
                        << " and origin (" << edge_origin_x << ","
                        << edge_origin_y << ")" << std::endl;
          }
          // project vertices adjacent to the vertex outside the module onto
          // the module edge
          double projection_factor =
                ((vertex_x[i] - edge_origin_x) * edge_slope_x +
                 (vertex_y[i] - edge_origin_y) * edge_slope_y) /
                (edge_slope_x * edge_slope_x + edge_slope_y * edge_slope_y);
          double proj_x = edge_origin_x + projection_factor * edge_slope_x;
          double proj_y = edge_origin_y + projection_factor * edge_slope_y;
          if (not isinside[up]) {
        // the next point is outside
        actual_x[num_vertices] = vertex_x[i];
        actual_y[num_vertices] = vertex_y[i];
        actual_x[num_vertices + 1] = proj_x;
        actual_y[num_vertices + 1] = proj_y;
          } else {
        // the previous point was outside
        actual_x[num_vertices] = proj_x;
        actual_y[num_vertices] = proj_y;
        actual_x[num_vertices + 1] = vertex_x[i];
        actual_y[num_vertices + 1] = vertex_y[i];
          }
          num_vertices += 2;
          if (verbose_ > 2) {
        std::cout << "New Vertex " << i << " : (" << vertex_x[i] << ","
              << vertex_y[i] << ")" << std::endl;
          }
        } else {
          actual_x[num_vertices] = vertex_x[i];
          actual_y[num_vertices] = vertex_y[i];
          num_vertices++;
        }  // should we project or not
      }    // loop through vertices
    } else {
      // all 6 inside, just copy the vertices over
      num_vertices = 6;
      for (int i = 0; i < 6; i++) {
        actual_x[i] = vertex_x[i];
        actual_y[i] = vertex_y[i];
      }
    }  // if numVerticesInside is less than 5
    // ecalMap_ needs to have its own copy of the polygon TGraph
    //  otherwise, we get a seg fault when EcalHexReadout is destructed
    //  because the polygon that was copied over from gridMap is deleted at
    //  the end of this function
    ecalMap_.AddBin(num_vertices, actual_x, actual_y);
    double x = (polyBin->GetXMax() + polyBin->GetXMin()) / 2.;
    double y = (polyBin->GetYMax() + polyBin->GetYMin()) / 2.;
    if (verbose_ > 1) {
      std::cout << "[buildCellMap] Copying poly with ID "
            << polyBin->GetBinNumber() << " and (x,y) ("
            << std::setprecision(2) << x << "," << y << ")" << std::endl;
    }
    // save cell location as center of ENTIRE hexagon
    cellPositionMap_[ecalMapID] = std::pair<double, double>(x, y);
    ecalMapID++;  // incrememnt cell ID
      }               // if num vertices inside is > 1
    }                 // loop over larger grid spanning module hexagon
  }
  if (verbose_ > 0) std::cout << std::endl;
  return;
}
References cellPositionMap_, cellr_, cellR_, cornersSideUp_, ecalMap_, isInside(), moduler_, moduleR_, and verbose_.
Referenced by EcalHexReadout().
buildCellModuleMap()
void ldmx::EcalHexReadout::buildCellModuleMap () private
Constructs the positions of all the cells in a layer relative to the ecal center.
This uses the modulePostionMap_ and cellPositionMap_ to calculate the center of all cells relative to the ecal center.
Parameters
[in] modulePositionMap_ map of module IDs to module centers relative to ecal
[in] cellPositionMap_ map of cell IDs to cell centers relative to module
[out]
Definition at line 386 of file EcalHexReadout.cxx.
{
  if (verbose_ > 0)
    std::cout << std::endl
              << "[buildCellModuleMap] Building cellModule position map"
              << std::endl;
  for (auto const& module : modulePositionMap_) {
    int moduleID = module.first;
    double moduleX = module.second.first;
    double moduleY = module.second.second;
    for (auto const& cell : cellPositionMap_) {
      int cellID = cell.first;
      double cellX = cell.second.first;
      double cellY = cell.second.second;
      double x = cellX + moduleX;
      double y = cellY + moduleY;
      cellModulePositionMap_[EcalID(0, moduleID, cellID)] =
          std::pair<double, double>(x, y);
    }
  }
  if (verbose_ > 0)
    std::cout << "  contained " << cellModulePositionMap_.size() << " entries. "
              << std::endl;
}
References cellModulePositionMap_, cellPositionMap_, modulePositionMap_, and verbose_.
Referenced by EcalHexReadout().
buildModuleMap()
void ldmx::EcalHexReadout::buildModuleMap () private
Constructs the positions of the seven modules (moduleID) relative to the ecal center
Sets modulePositionMap_ using the module IDs for keys and the centers of the module hexagons for values.
The module IDs are set in the ecal.gdml file and are replicated here.
0 for center module
1 on top (12 o'clock)
clockwise till 6 at 11 o'clock
Parameters
[in] gap_ separation between module flat-sides
[in] moduler_ center-to-flat module radius
[out] modulePositionMap_ map of module IDs to module centers relative to ecal
Definition at line 50 of file EcalHexReadout.cxx.
{
  if (verbose_ > 0) {
    std::cout
        << std::endl
        << "[buildModuleMap] Building module position map for module min r of "
        << moduler_ << "    and gap of " << gap_ << std::endl;
  }
  double C_PI = 3.14159265358979323846;  // or TMath::Pi(), #define, atan(), ...
  if (cornersSideUp_) {
  // module IDs are 0 for ecal center, 1 at right, and clockwise till 6
    modulePositionMap_[0] = std::pair<double, double>(0., 0.);
    for (unsigned id = 1; id < 7; id++) {
      double x = (2. * moduler_ + gap_) * cos((id-1) * (C_PI / 3.));
      double y = - (2. * moduler_ + gap_) * sin((id-1) * (C_PI / 3.));
      modulePositionMap_[id] = std::pair<double, double>(x, y);
      if (verbose_ > 2)
    std::cout << TString::Format("   id %d is at (%.2f, %.2f)", id, x, y)
          << std::endl;
    }
  }
  else {
    // module IDs are 0 for ecal center, 1 at right, and counterclockwise till 6 at 11 o'clock
    modulePositionMap_[0] = std::pair<double, double>(0., 0.);
    for (unsigned id = 1; id < 7; id++) {
      double x = (2. * moduler_ + gap_) * sin((id - 1) * (C_PI / 3.));
      double y = (2. * moduler_ + gap_) * cos((id - 1) * (C_PI / 3.));
      modulePositionMap_[id] = std::pair<double, double>(x, y);
      if (verbose_ > 2)
    std::cout << TString::Format("   id %d is at (%.2f, %.2f)", id, x, y)
          << std::endl;
    }
  }
  if (verbose_ > 0) std::cout << std::endl;
}
References cornersSideUp_, gap_, modulePositionMap_, moduler_, and verbose_.
Referenced by EcalHexReadout().
buildNeighborMaps()
void ldmx::EcalHexReadout::buildNeighborMaps () private
Construts NNMap and NNNMap
Since this only occurs once during processing, we can be wasteful. We do a nested loop over the entire cellular position map and calculate neighbors by seeing which cells are within multiples of the cellular radius of each other.
Parameters
[in] cellModulePostionMap_ map of cells to cell centers relative to ecal
[out] NNMap_ map of cell IDs to list of cell IDs that are its nearest neighbors
[out] NNNMap_ map of cell IDs to list of cell IDs that are its next-to-nearest neighbors
STRATEGY Neighbors may include from other modules. All this is precomputed. So we can be wasteful here. Gaps may be nonzero, so we simply apply an anulus requirement (r < point <= r+dr) using total x,y positions relative to the ecal center (cell+module positions). This makes the routine portable to future cell layouts. Note that the module centers already take into account a nonzero gap. The number of neighbors is not simple because: edges, and that module edges have cutoff cells. (NN) Center within [1*cellr_, 3*cellr_] (NNN) Center within [3*cellr_, 4.5*cellr_] Chosen b/c in ideal case, centers are at 2*cell_ (NN), and at 3*cellR_=3.46*cellr_ and 4*cellr_ (NNN).
Definition at line 410 of file EcalHexReadout.cxx.
{
  NNMap_.clear();
  NNNMap_.clear();
  for (auto const& centerChannel : cellModulePositionMap_) {
    EcalID centerID = centerChannel.first;
    double centerX = centerChannel.second.first;
    double centerY = centerChannel.second.second;
    for (auto const& probeChannel : cellModulePositionMap_) {
      EcalID probeID = probeChannel.first;
      double probeX = probeChannel.second.first;
      double probeY = probeChannel.second.second;
      double dist = sqrt((probeX - centerX) * (probeX - centerX) +
                         (probeY - centerY) * (probeY - centerY));
      if (dist > 1 * cellr_ && dist <= 3. * cellr_) {
        NNMap_[centerID].push_back(probeID);
      } else if (dist > 3. * cellr_ && dist <= 4.5 * cellr_) {
        NNNMap_[centerID].push_back(probeID);
      }
    }
    if (verbose_ > 1)
      std::cout << TString::Format("Found %d NN and %d NNN for cellModuleID ",
                                   int(NNMap_[centerID].size()),
                                   int(NNNMap_[centerID].size()))
                << centerID
                << TString::Format(" with x,y (%.2f,%.2f)", centerX, centerY)
                << std::endl;
  }
  if (verbose_ > 2) {
    double specialX =
        0.5 * moduleR_ - 0.5 * cellr_;  // center of cell which is upper-right
                                        // corner of center module
    double specialY = moduler_ - 0.5 * cellR_;
    EcalID specialCellModuleID = getCellModuleID(specialX, specialY);
    std::cout << "The neighbors of the bin in the upper-right corner of the "
                 "center module, with cellModuleID "
              << specialCellModuleID << " include " << std::endl;
    for (auto centerNN : NNMap_.at(specialCellModuleID)) {
      std::cout << " NN " << centerNN
                << TString::Format(" (x,y) (%.2f, %.2f)",
                                   getCellCenterAbsolute(centerNN).first,
                                   getCellCenterAbsolute(centerNN).second)
                << std::endl;
    }
    for (auto centerNNN : NNNMap_.at(specialCellModuleID)) {
      std::cout << " NNN " << centerNNN
                << TString::Format(" (x,y) (%.2f, %.2f)",
                                   getCellCenterAbsolute(centerNNN).first,
                                   getCellCenterAbsolute(centerNNN).second)
                << std::endl;
    }
    std::cout << TString::Format(
                     "This bin is a distance of %.2f away from a module edge. "
                     "Decision isEdge %d.",
                     distanceToEdge(specialCellModuleID),
                     isEdgeCell(specialCellModuleID))
              << std::endl;
  }
  if (verbose_ > 0) std::cout << std::endl;
  return;
}
References cellModulePositionMap_, cellr_, cellR_, distanceToEdge(), getCellCenterAbsolute(), getCellModuleID(), isEdgeCell(), moduler_, moduleR_, NNMap_, NNNMap_, and verbose_.
Referenced by EcalHexReadout().
buildTriggerGroup()
void ldmx::EcalHexReadout::buildTriggerGroup () private
Constructs list of trigger groups.
The list of trigger groups uses the index as the cell ID and the value as the ID of the trigger group.
For the ECal, cells are grouped into 3x3 "squares" and integrated over for the trigger. This function builds a list for finding which trigger group a cell is in.
debugMake()
static EcalHexReadout * ldmx::EcalHexReadout::debugMake (const framework::config::Parameters & p) inline static
Definition at line 398 of file EcalHexReadout.h.
{
    return new EcalHexReadout(p);
  }
distanceToEdge()
double ldmx::EcalHexReadout::distanceToEdge (EcalID cellModuleID) const
Distance to module edge, and whether cell is on edge of module.
@TODO Use getNN()/getNNN() + isEdgeCell() to expand functionality.
Parameters
[in] cellModuleID EcalId where all we care about is module and cell
Returns
distance to edge of the module
Definition at line 484 of file EcalHexReadout.cxx.
{
  // https://math.stackexchange.com/questions/1210572/find-the-distance-to-the-edge-of-a-hexagon
  int cellID = cellModuleID.cell();
  std::pair<double, double> cellLocation = getCellCenterRelative(cellID);
  double x = fabs(cellLocation.first);  // bring to first quadrant
  double y = fabs(cellLocation.second);
  double r = sqrt(x * x + y * y);
  double theta = (r > 1E-3) ? fabs(std::atan(y / x)) : 0;
  if (x < moduleR_ / 2.)
    return (moduler_ - y);  // closest line is straight vertical to top edge
  double dist =
      sqrt(3.) * moduleR_ / (std::sin(theta) + sqrt(3.) * std::cos(theta));
  return dist;
}
References ldmx::EcalID::cell(), getCellCenterRelative(), moduler_, and moduleR_.
Referenced by buildNeighborMaps(), and isEdgeCell().
getCellAbsolutePosition()
void ldmx::EcalHexReadout::getCellAbsolutePosition (EcalID id, double & x, double & y, double & z) const inline
Get entire real space position for the cell with the input raw ID
Inputs x,y,z will be set to the calculated position
See also
getCellCenterAbsolute and getZPosition
Parameters
[in] id EcalID for the cell we want the position of
[out] x set to x-coordinate of cell center
[out] y set to y-coordinate of cell center
[out] z set to z-coordinate of cell center
Definition at line 90 of file EcalHexReadout.h.
{
    std::pair<double, double> xy =
        this->getCellCenterAbsolute(EcalID(0, id.module(), id.cell()));
    x = xy.first;
    y = xy.second;
    z = getZPosition(id.layer());
    return;
  }
References getCellCenterAbsolute(), and getZPosition().
Referenced by ecal::DNNEcalVetoProcessor::make_inputs(), and ecal::EcalRecProducer::produce().
getCellCenterAbsolute()
std::pair< double, double > ldmx::EcalHexReadout::getCellCenterAbsolute (EcalID cellModuleID) const inline
Get a cell center XY position relative to ecal center from a combined cellModuleID.
Exceptions
std::out_of_range if EcalID isn't created with valid cell or module IDs.
Parameters
cellModuleID EcalID where all we care about is module and cell
Returns
The XY position of the center of the cell.
Definition at line 250 of file EcalHexReadout.h.
{
    return cellModulePositionMap_.at(
        EcalID(0, cellModuleID.module(), cellModuleID.cell()));
  }
References ldmx::EcalID::cell(), cellModulePositionMap_, and ldmx::EcalID::module().
Referenced by buildNeighborMaps(), getCellAbsolutePosition(), and ecal::EcalTriggerGeometry::globalPosition().
getCellCenterRelative()
std::pair< double, double > ldmx::EcalHexReadout::getCellCenterRelative (int cellID) const inline
Get a cell center XY position relative to module center from a cell ID.
Exceptions
Exception if invalid cell ID is input.
Parameters
cellID The cell ID.
Returns
The (x,y) position of the center of the cell.
Definition at line 209 of file EcalHexReadout.h.
{
    // this map search is probably just as fine as the TList search for the cell
    // in ecalMap.
    //   wonder why TH2Poly->GetBin(ID) doesn't exist. plus the map is useful by
    //   itself.
    auto search = cellPositionMap_.find(cellID);
    if (search == cellPositionMap_.end()) {
      EXCEPTION_RAISE("InvalidCellID",
                      "Cell " + std::to_string(cellID) + " is not valid.");
    }
    return search->second;
  }
References cellPositionMap_.
Referenced by distanceToEdge(), and ecal::EcalTriggerGeometry::localPosition().
getCellIDRelative()
int ldmx::EcalHexReadout::getCellIDRelative (double x, double y) const inline
Get a cell ID from an XY position relative to module center.
This is where invalid (x,y) from external calls will end up failing and need error handling.
Note
One option for assigning dead material is to do it here. If the input (x,y) relative to the module is close enough to the edge (for example), we could return a special cell ID (-1 for example) that signals that this hit is in a dead region.
Parameters
x Any X position [mm]
y Any Y position [mm]
Returns
local cell ID to the module
Definition at line 174 of file EcalHexReadout.h.
{
    int bin = ecalMap_.FindBin(x, y) -
              1;  // NB FindBin indices starts from 1, our maps start from 0
    if (bin < 0) {
      TString error_msg = TString(
                              "[EcalHexReadout::getCellIDRelative] Relative "
                              "coordinates are outside module hexagon!") +
                          TString::Format(
                              " Is the gap used by EcalHexReadout (%.2f mm) "
                              "and the minimum module radius (%.2f mm)",
                              gap_, moduler_) +
                          TString::Format(
                              " the same as hexagon_gap and Hex_radius in "
                              "ecal.gdml? Received (x,y) = (%.2f,%.2f).",
                              x, y);
      EXCEPTION_RAISE("InvalidArg", error_msg.Data());
    }
    return bin;
  }
References ecalMap_, gap_, and moduler_.
Referenced by getCellModuleID().
getCellMaxR()
double ldmx::EcalHexReadout::getCellMaxR () const inline
Get the center-to-corner radius of the cell hexagons
Returns
cell max radius [mm]
Definition at line 370 of file EcalHexReadout.h.
{ return cellR_; }
References cellR_.
getCellMinR()
double ldmx::EcalHexReadout::getCellMinR () const inline
Get the center-to-flat radius of the cell hexagons
Returns
cell min radius [mm]
Definition at line 363 of file EcalHexReadout.h.
{ return cellr_; }
References cellr_.
getCellModuleID()
EcalID ldmx::EcalHexReadout::getCellModuleID (double x, double y) const inline
Get a combined cellModule ID from an XY position relative to ecal center.
See also
getCellIDRelative and getModuleID
Parameters
x Any X position [mm]
y Any Y position [mm]
Returns
an EcalID that has the correct module and cell information while layer is set to zero
Definition at line 232 of file EcalHexReadout.h.
{
    int moduleID = getModuleID(x, y);
    double relX = x - modulePositionMap_.at(moduleID).first;
    double relY = y - modulePositionMap_.at(moduleID).second;
    int cellID = getCellIDRelative(relX, relY);
    return EcalID(0, moduleID, cellID);
  }
References getCellIDRelative(), getModuleID(), and modulePositionMap_.
Referenced by buildNeighborMaps().
getCellModulePositionMap()
const std::map< EcalID, std::pair< double, double > > & ldmx::EcalHexReadout::getCellModulePositionMap () const inline
Get a const reference to the full cell-module position map.
Definition at line 382 of file EcalHexReadout.h.
            {
    return cellModulePositionMap_;
  }
References cellModulePositionMap_.
getCellPolyMap()
TH2Poly * ldmx::EcalHexReadout::getCellPolyMap () const inline
Get a reference to the TH2Poly used for Cell IDs.
Note
This is only helpful in the use case where you want to print the cell ID <-> cell position map. DO NOT USE THIS OTHERWISE.
Returns
pointer to member variable ecalMap_
Definition at line 396 of file EcalHexReadout.h.
{ return &ecalMap_; }
References ecalMap_.
getCellPositionMap()
const std::map< int, std::pair< double, double > > & ldmx::EcalHexReadout::getCellPositionMap () const inline
Get a const reference to the cell center position map.
Definition at line 375 of file EcalHexReadout.h.
{
    return cellPositionMap_;
  }
References cellPositionMap_.
getModuleCenter()
std::pair< double, double > ldmx::EcalHexReadout::getModuleCenter (int moduleID) const inline
Get a module center position relative to the ecal center [mm]
Parameters
[in] moduleID id of the module
Returns
(x,y) coordinate pair for center of module
Definition at line 124 of file EcalHexReadout.h.
{
    return modulePositionMap_.at(moduleID);
  }
References modulePositionMap_.
getModuleID()
int ldmx::EcalHexReadout::getModuleID (double x, double y) const inline
Get a module ID from an XY position relative to the ecal center [mm]
Parameters
[in] x x-coordinate for test position
[in] y y-coordinate for test position
Returns
module ID that coordinate (x,y) is in
Definition at line 142 of file EcalHexReadout.h.
{
    int bestID = -1;
    double bestDist = 1E6;
    for (auto const& module : modulePositionMap_) {
      int mID = module.first;
      double mX = module.second.first;
      double mY = module.second.second;
      double dist = sqrt((x - mX) * (x - mX) + (y - mY) * (y - mY));
      if (dist < moduler_) return mID;
      if (dist < bestDist) {
        bestID = mID;
        bestDist = dist;
      }
    }
    return bestID;
  }
References modulePositionMap_, and moduler_.
Referenced by getCellModuleID().
getModuleMaxR()
double ldmx::EcalHexReadout::getModuleMaxR () const inline
Get the center-to-corner radius of the module hexagons
Returns
module max radius [mm]
Definition at line 356 of file EcalHexReadout.h.
{ return moduleR_; }
References moduleR_.
getModuleMinR()
double ldmx::EcalHexReadout::getModuleMinR () const inline
Get the center-to-flat radius of the module hexagons
Returns
module min radius [mm]
Definition at line 349 of file EcalHexReadout.h.
{ return moduler_; }
References moduler_.
getNN()
std::vector< EcalID > ldmx::EcalHexReadout::getNN (EcalID id) const inline
Get the Nearest Neighbors of the input ID
Parameters
id id to get
Returns
list of EcalID that are the inputs nearest neighbors
Definition at line 297 of file EcalHexReadout.h.
{
    auto list = NNMap_.at(EcalID(0, id.module(), id.cell()));
    for (auto& flat : list) id = EcalID(id.layer(), flat.module(), flat.cell());
    return list;
  }
References NNMap_.
Referenced by isNN().
getNNN()
std::vector< EcalID > ldmx::EcalHexReadout::getNNN (EcalID id) const inline
Get the Next-to-Nearest Neighbors of the input ID
Parameters
id id to get
Returns
list of EcalID that are the inputs next-to-nearest neighbors
Definition at line 323 of file EcalHexReadout.h.
{
    auto list = NNNMap_.at(EcalID(0, id.module(), id.cell()));
    for (auto& flat : list) id = EcalID(id.layer(), flat.module(), flat.cell());
    return list;
  }
References NNNMap_.
Referenced by isNNN().
getNumCellsPerModule()
int ldmx::EcalHexReadout::getNumCellsPerModule () const inline
Get the number of cells in an ecal module
Returns
number of cells in the ecal module
Definition at line 199 of file EcalHexReadout.h.
{ return ecalMap_.GetNumberOfBins(); }
References ecalMap_.
getNumLayers()
int ldmx::EcalHexReadout::getNumLayers () const inline
Get the number of layers in the Ecal Geometry
Returns
number fo layers in geometry
Definition at line 116 of file EcalHexReadout.h.
{ return layerZPositions_.size(); }
References layerZPositions_.
getNumModulesPerLayer()
int ldmx::EcalHexReadout::getNumModulesPerLayer () const inline
Get the number of modules in the Ecal flower
Returns
number of modules
Definition at line 133 of file EcalHexReadout.h.
{ return modulePositionMap_.size(); }
References modulePositionMap_.
getZPosition()
double ldmx::EcalHexReadout::getZPosition (int layer) const inline
Get the z-coordinate given the layer id
Parameters
[in] layer int layer id
Returns
z-coordinate of the input sensitive layer
Definition at line 107 of file EcalHexReadout.h.
{
    return ecalFrontZ_ + layerZPositions_.at(layer);
  }
References ecalFrontZ_, and layerZPositions_.
Referenced by getCellAbsolutePosition(), and ecal::EcalVetoProcessor::produce().
isEdgeCell()
bool ldmx::EcalHexReadout::isEdgeCell (EcalID cellModuleID) const inline
Check if input cell is on the edge of a module.
See also
distanceToEdge
Parameters
[in] cellModuleID EcalId where all we care about is module and cell return true if distance to edge is less than max cell radius
Definition at line 273 of file EcalHexReadout.h.
{
    return (distanceToEdge(cellModuleID) < cellR_);
  }
References cellR_, and distanceToEdge().
Referenced by buildNeighborMaps().
isInside()
bool ldmx::EcalHexReadout::isInside (double normX, double normY) const
Determines if point (x,y), already normed to max hexagon radius, lies within a hexagon. Corners are (1,0) and (0.5,sqrt(3)/2). Uses "<", not "<=".
Parameters
[in] normX X-coordinate relative to module hexagon divided by maximum hexagon radius
[in] normY Y-coordinate relative to module hexagon divided by maximum hexagon radius
Returns
true if (normX,normY) is within the hexagon centered at the origin with maximum radius 1.
Definition at line 499 of file EcalHexReadout.cxx.
{
  if (verbose_ > 2)
    std::cout << TString::Format(
                     "[isInside] Checking if normXY=(%.2f,%.2f) is inside.",
                     normX, normY)
              << std::endl;
  normX = fabs(normX), normY = fabs(normY);
  double xvec = -1, yvec = -1. / sqrt(3);
  double xref = 0.5, yref = sqrt(3) / 2.;
  if ((normX > 1.) || (normY > yref)) {
    if (verbose_ > 2)
      std::cout << "[isInside]   they are outside quadrant." << std::endl;
    return false;
  }
  double dotProd = (xvec * (normX - xref) + yvec * (normY - yref));
  if (verbose_ > 2)
    std::cout << TString::Format(
                     "[isInside] they are inside quadrant. Dot product (>0 is "
                     "inside): %.2f ",
                     dotProd)
              << std::endl;
  return (dotProd > 0.);
}
References verbose_.
Referenced by buildCellMap().
isNN()
bool ldmx::EcalHexReadout::isNN (EcalID centroid, EcalID probe) const inline
Check if the probe id is one of the nearest neightbors of the centroid id
Parameters
probe id to check if it is nearest neighbor
centroid id that is center of neighbors
Returns
true if probe ID is a nearest neighbor of the centroid
Definition at line 310 of file EcalHexReadout.h.
{
    for (auto& id : getNN(centroid)) {
      if (id == probe) return true;
    }
    return false;
  }
References getNN().
Referenced by ecal::EcalVetoProcessor::isInShowerInnerRing().
isNNN()
bool ldmx::EcalHexReadout::isNNN (EcalID centroid, EcalID probe) const inline
Check if the probe id is one of the next-to-nearest neightbors of the centroid id
Parameters
probe id to check if it is a next-to-nearest neighbor
centroid id that is center of neighbors
Returns
true if probe ID is a next-to-nearest neighbor of the centroid
Definition at line 337 of file EcalHexReadout.h.
{
    for (auto& id : getNNN(centroid)) {
      if (id == probe) return true;
    }
    return false;
  }
References getNNN().
Friends And Related Function Documentation
ecal::EcalGeometryProvider
friend class ecal::EcalGeometryProvider friend
Definition at line 409 of file EcalHexReadout.h.
Member Data Documentation
cellModulePositionMap_
std::map<EcalID, std::pair<double, double> > ldmx::EcalHexReadout::cellModulePositionMap_ private
Position of cell centers relative to world geometry (uses ID with real cell and module and layer as zero for key)
Definition at line 554 of file EcalHexReadout.h.
Referenced by buildCellModuleMap(), buildNeighborMaps(), getCellCenterAbsolute(), and getCellModulePositionMap().
cellPositionMap_
std::map<int, std::pair<double, double> > ldmx::EcalHexReadout::cellPositionMap_ private
Position of cell centers relative to module (uses cell ID as key)
Definition at line 550 of file EcalHexReadout.h.
Referenced by buildCellMap(), buildCellModuleMap(), getCellCenterRelative(), and getCellPositionMap().
cellr_
double ldmx::EcalHexReadout::cellr_ {0} private
Center-to-Flat Radius of cell hexagon [mm].
Definition at line 516 of file EcalHexReadout.h.
Referenced by buildCellMap(), buildNeighborMaps(), EcalHexReadout(), and getCellMinR().
cellR_
double ldmx::EcalHexReadout::cellR_ {0} private
Center-to-Corner Radius of cell hexagon [mm].
Definition at line 522 of file EcalHexReadout.h.
Referenced by buildCellMap(), buildNeighborMaps(), EcalHexReadout(), getCellMaxR(), and isEdgeCell().
CONDITIONS_OBJECT_NAME
constexpr const char* ldmx::EcalHexReadout::CONDITIONS_OBJECT_NAME {"EcalHexReadout"} static constexpr
Definition at line 69 of file EcalHexReadout.h.
cornersSideUp_
bool ldmx::EcalHexReadout::cornersSideUp_ private
indicator of geometry orientation – if true, flower shape's corners side (ie: side with two modules) is at the top
Definition at line 528 of file EcalHexReadout.h.
Referenced by buildCellMap(), buildModuleMap(), and EcalHexReadout().
ecalFrontZ_
double ldmx::EcalHexReadout::ecalFrontZ_ {0} private
Front of ECal relative to world geometry [mm].
Definition at line 540 of file EcalHexReadout.h.
Referenced by EcalHexReadout(), and getZPosition().
ecalMap_
TH2Poly ldmx::EcalHexReadout::ecalMap_ mutable private
Honeycomb Binning from ROOT
Needs to be mutable because ROOT doesn't have good const handling
Definition at line 572 of file EcalHexReadout.h.
Referenced by buildCellMap(), getCellIDRelative(), getCellPolyMap(), and getNumCellsPerModule().
gap_
double ldmx::EcalHexReadout::gap_ private
Gap between module flat sides [mm].
Definition at line 513 of file EcalHexReadout.h.
Referenced by buildModuleMap(), EcalHexReadout(), and getCellIDRelative().
layerZPositions_
std::vector<double> ldmx::EcalHexReadout::layerZPositions_ private
The layer Z postions are with respect to the front of the ECal [mm].
Definition at line 543 of file EcalHexReadout.h.
Referenced by EcalHexReadout(), getNumLayers(), and getZPosition().
modulePositionMap_
std::map<int, std::pair<double, double> > ldmx::EcalHexReadout::modulePositionMap_ private
Postion of module centers relative to world geometry (uses module ID as key)
Definition at line 547 of file EcalHexReadout.h.
Referenced by buildCellModuleMap(), buildModuleMap(), getCellModuleID(), getModuleCenter(), getModuleID(), and getNumModulesPerLayer().
moduler_
double ldmx::EcalHexReadout::moduler_ {0} private
Center-to-Flat Radius of module hexagon [mm].
Definition at line 519 of file EcalHexReadout.h.
Referenced by buildCellMap(), buildModuleMap(), buildNeighborMaps(), distanceToEdge(), EcalHexReadout(), getCellIDRelative(), getModuleID(), and getModuleMinR().
moduleR_
double ldmx::EcalHexReadout::moduleR_ {0} private
Center-to-Corner Radius of module hexagon [mm].
Definition at line 525 of file EcalHexReadout.h.
Referenced by buildCellMap(), buildNeighborMaps(), distanceToEdge(), EcalHexReadout(), and getModuleMaxR().
nCellRHeight_
double ldmx::EcalHexReadout::nCellRHeight_ {0} private
Number of cell center-to-corner radii (one side of the cell) from the bottom to the top of the module
Could be fractional depending on how many fractions of a radii are spanning between the center of the top/bottom cell row and the edge of the module
Definition at line 537 of file EcalHexReadout.h.
Referenced by EcalHexReadout().
NNMap_
std::map<EcalID, std::vector<EcalID> > ldmx::EcalHexReadout::NNMap_ private
Map of cell ID to neighboring cells (uses ID with real cell and module and layer as zero for key)
Definition at line 558 of file EcalHexReadout.h.
Referenced by buildNeighborMaps(), and getNN().
NNNMap_
std::map<EcalID, std::vector<EcalID> > ldmx::EcalHexReadout::NNNMap_ private
Map of cell ID to neighbors of neighbor cells (uses ID with real cell and module and layer as zero for key)
Definition at line 562 of file EcalHexReadout.h.
Referenced by buildNeighborMaps(), and getNNN().
triggerGroups_
std::vector<int> ldmx::EcalHexReadout::triggerGroups_ private
List of Trigger Group IDs (index is cell ID)
Definition at line 565 of file EcalHexReadout.h.
verbose_
int ldmx::EcalHexReadout::verbose_ {2} private
verbosity, not configurable but helpful if developing
Definition at line 510 of file EcalHexReadout.h.
Referenced by buildCellMap(), buildCellModuleMap(), buildModuleMap(), buildNeighborMaps(), EcalHexReadout(), and isInside().
The documentation for this class was generated from the following files:
DetDescr/include/DetDescr/EcalHexReadout.h
DetDescr/src/DetDescr/EcalHexReadout.cxx