LDMX Software: simcore::Trajectory Class Reference
simcore::Trajectory Class Reference
Trajectory implementation for storing track info for persistence and visualization.
#include <Trajectory.h>
Public Types
typedef std::map< int, Trajectory * > TrajectoryMap
Public Member Functions
Trajectory (const G4Track *aTrack)
virtual ~Trajectory ()
void * operator new (size_t s)
void operator delete (void *obj)
G4int GetTrackID () const
G4int GetParentID () const
G4String GetParticleName () const
G4double GetCharge () const
G4int GetPDGEncoding () const
G4ThreeVector GetInitialMomentum () const
int GetPointEntries () const
G4VTrajectoryPoint * GetPoint (G4int i) const
void AppendStep (const G4Step *aStep)
void MergeTrajectory (G4VTrajectory *secondTrajectory)
G4ThreeVector getEndPoint () const
G4double getEnergy () const
G4double getMass () const
G4float getGlobalTime () const
G4int getGenStatus () const
const G4ThreeVector & getVertexPosition () const
void setGenStatus (int genStatus)
int getProcessType ()
void setEndPointMomentum (const G4Track *aTrack)
const G4ThreeVector & getEndPointMomentum () const
std::string getVertexVolume () const
std::string getVertexRegion () const
Static Public Member Functions
static Trajectory * findByTrackID (G4TrajectoryContainer *trajCont, int trackID)
Private Attributes
TrajectoryPointContainer * trajPoints_
G4ParticleDefinition * particleDef_
G4int trackID_
G4int parentID_
G4double energy_
G4double mass_
G4float globalTime_
G4int genStatus_
G4ThreeVector initialMomentum_
G4ThreeVector endPointMomentum_
G4ThreeVector vertexPosition_
std::string vertexVolume_
The particle's creation volume.
std::string vertexRegion_
int processType_
Detailed Description
Trajectory implementation for storing track info for persistence and visualization.
Note
Class is based on this Geant4 tip: Trajectory Event Tip
Definition at line 34 of file Trajectory.h.
Member Typedef Documentation
TrajectoryMap
typedef std::map<int, Trajectory*> simcore::Trajectory::TrajectoryMap
Map of track ID to Trajectory objects.
Definition at line 37 of file Trajectory.h.
Constructor & Destructor Documentation
Trajectory()
simcore::Trajectory::Trajectory (const G4Track * aTrack)
Class constructor.
Parameters
aTrack The Track from which to construct the trajectory.
Definition at line 15 of file Trajectory.cxx.
                                             : genStatus_(0) {
   // Copy basic info from the track.
   particleDef_ = aTrack->GetDefinition();
   mass_ = aTrack->GetDynamicParticle()->GetMass();
   trackID_ = aTrack->GetTrackID();
   parentID_ = aTrack->GetParentID();
   globalTime_ = aTrack->GetGlobalTime();
   vertexPosition_ = aTrack->GetVertexPosition();
   energy_ = aTrack->GetVertexKineticEnergy() + mass_;
   // Set the process type.
   const G4VProcess* process = aTrack->GetCreatorProcess();
   if (process) {
     const G4String& processName = process->GetProcessName();
     ldmx::SimParticle::ProcessType processType =
         ldmx::SimParticle::findProcessType(processName);
     processType_ = processType;
     // Uncomment this to see what process types are being saved.  --JM
     // std::cout << "Trajectory - set process type " << processType
     //        << " from <" << processName << ">" << std::endl;
   } else {
     processType_ = ldmx::SimParticle::ProcessType::unknown;
   }
   // Get the track information. This is used to set the track vertex
   // volume and initial momentum.
   auto trackInfo{
       dynamic_cast<UserTrackInformation*>(aTrack->GetUserInformation())};
   // Set the vertex volume
   vertexVolume_ = trackInfo->getVertexVolume();
   vertexRegion_ = aTrack->GetLogicalVolumeAtVertex()->GetRegion()->GetName();
   // Set initial momentum from track information.
   const G4ThreeVector& p = trackInfo->getInitialMomentum();
   initialMomentum_.set(p.x(), p.y(), p.z());
   // If the track has not been stepped, then only the first point is added.
   // Otherwise, the track has already been stepped so we add also its last
   // location which should be its endpoint.
   trajPoints_ = new TrajectoryPointContainer();
   trajPoints_->push_back(new G4TrajectoryPoint(aTrack->GetVertexPosition()));
   if (aTrack->GetTrackStatus() == G4TrackStatus::fStopAndKill) {
     trajPoints_->push_back(new G4TrajectoryPoint(aTrack->GetPosition()));
   }
 }
References energy_, ldmx::SimParticle::findProcessType(), globalTime_, initialMomentum_, mass_, parentID_, particleDef_, processType_, trackID_, trajPoints_, vertexPosition_, vertexRegion_, and vertexVolume_.
~Trajectory()
simcore::Trajectory::~Trajectory () virtual
Class destructor.
Definition at line 62 of file Trajectory.cxx.
{
   // Delete trajectory points and their container.
   size_t i;
   for (i = 0; i < trajPoints_->size(); i++) {
     delete (*trajPoints_)[i];
   }
   trajPoints_->clear();
   delete trajPoints_;
 }
References trajPoints_.
Member Function Documentation
AppendStep()
void simcore::Trajectory::AppendStep (const G4Step * aStep)
Append a step to the trajectory.
Parameters
aStep The step info.
Definition at line 72 of file Trajectory.cxx.
{
   trajPoints_->push_back(
       new G4TrajectoryPoint(aStep->GetPostStepPoint()->GetPosition()));
 }
References trajPoints_.
findByTrackID()
Trajectory * simcore::Trajectory::findByTrackID (G4TrajectoryContainer * trajCont, int trackID) static
Find a Trajectory by its track ID within a G4TrajectoryContainer.
Parameters
trajCont The G4TrajectoryContainer to search.
trackID The track ID.
Returns
The matching Trajectory or null if does not exist.
Definition at line 133 of file Trajectory.cxx.
{
   TrajectoryVector* vec = trajCont->GetVector();
   for (TrajectoryVector::const_iterator it = vec->begin(); it != vec->end();
        it++) {
     if ((*it)->GetTrackID() == trackID) {
       return dynamic_cast<Trajectory*>(*it);
     }
   }
   return nullptr;
 }
GetCharge()
G4double simcore::Trajectory::GetCharge () const
Get the charge of the particle.
Returns
The charge of the particle.
Definition at line 85 of file Trajectory.cxx.
 { return particleDef_->GetPDGCharge(); }
References particleDef_.
Referenced by simcore::persist::SimParticleBuilder::buildSimParticles().
getEndPoint()
G4ThreeVector simcore::Trajectory::getEndPoint () const
Get the trajectory end point [mm].
Returns
The trajectory end point.
Definition at line 115 of file Trajectory.cxx.
{
   return GetPoint(GetPointEntries() - 1)->GetPosition();
 }
References GetPoint(), and GetPointEntries().
Referenced by simcore::persist::SimParticleBuilder::buildSimParticles().
getEnergy()
G4double simcore::Trajectory::getEnergy () const
Get the particle's energy [MeV].
Returns
The trajectory's energy.
Definition at line 119 of file Trajectory.cxx.
 { return energy_; }
References energy_.
Referenced by simcore::persist::SimParticleBuilder::buildSimParticles().
getGenStatus()
G4int simcore::Trajectory::getGenStatus () const
Get the generator status (greater than zero for generator particle).
Returns
The particle's generator status.
Definition at line 125 of file Trajectory.cxx.
 { return genStatus_; }
References genStatus_.
Referenced by simcore::persist::SimParticleBuilder::buildSimParticles().
getGlobalTime()
G4float simcore::Trajectory::getGlobalTime () const
Get the global creation time of the trajectory.
Definition at line 123 of file Trajectory.cxx.
 { return globalTime_; }
References globalTime_.
Referenced by simcore::persist::SimParticleBuilder::buildSimParticles().
GetInitialMomentum()
G4ThreeVector simcore::Trajectory::GetInitialMomentum () const
Get the initial track momentum [MeV].
Returns
The initial track momentum.
Definition at line 91 of file Trajectory.cxx.
{
   return initialMomentum_;
 }
References initialMomentum_.
Referenced by simcore::persist::SimParticleBuilder::buildSimParticles().
getMass()
G4double simcore::Trajectory::getMass () const
Get the particle's mass [MeV].
Returns
The particle's mass.
Definition at line 121 of file Trajectory.cxx.
 { return mass_; }
References mass_.
Referenced by simcore::persist::SimParticleBuilder::buildSimParticles().
GetParentID()
G4int simcore::Trajectory::GetParentID () const
Get the parent track ID.
Returns
The parent track ID.
Definition at line 79 of file Trajectory.cxx.
 { return parentID_; }
References parentID_.
Referenced by simcore::persist::SimParticleBuilder::buildSimParticles().
GetParticleName()
G4String simcore::Trajectory::GetParticleName () const
Get the name of the associated particle.
Returns
The name of the particle.
Definition at line 81 of file Trajectory.cxx.
{
   return particleDef_->GetParticleName();
 }
References particleDef_.
GetPDGEncoding()
G4int simcore::Trajectory::GetPDGEncoding () const
Get the PDG encoding of the particle.
Returns
The PDG encoding of the particle.
Definition at line 87 of file Trajectory.cxx.
{
   return particleDef_->GetPDGEncoding();
 }
References particleDef_.
Referenced by simcore::persist::SimParticleBuilder::buildSimParticles().
GetPoint()
G4VTrajectoryPoint * simcore::Trajectory::GetPoint (G4int i) const
Get a trajectory point.
Parameters
i The index of the trajectory point.
Definition at line 97 of file Trajectory.cxx.
{
   return (*trajPoints_)[i];
 }
References trajPoints_.
Referenced by getEndPoint().
GetPointEntries()
int simcore::Trajectory::GetPointEntries () const
Get the number of trajectory points.
Returns
The number of trajectory points.
Definition at line 95 of file Trajectory.cxx.
 { return trajPoints_->size(); }
References trajPoints_.
Referenced by getEndPoint(), and MergeTrajectory().
getProcessType()
int simcore::Trajectory::getProcessType () inline
Get the creator process type of this particle. This corresponds to the value returned by G4VProcess::GetProcessSubType() e.g. 121 for products of photonuclear reactions.
Returns
The creator process type of this particle.
Definition at line 180 of file Trajectory.h.
 { return processType_; }
References processType_.
Referenced by simcore::persist::SimParticleBuilder::buildSimParticles().
GetTrackID()
G4int simcore::Trajectory::GetTrackID () const
Get the associated track ID.
Returns
The track ID.
Definition at line 77 of file Trajectory.cxx.
 { return trackID_; }
References trackID_.
Referenced by simcore::TrackMap::addTrajectory(), and simcore::persist::SimParticleBuilder::buildSimParticles().
getVertexPosition()
const G4ThreeVector & simcore::Trajectory::getVertexPosition () const
Get the particle's vertex position.
Returns
The particle's vertex position.
Definition at line 127 of file Trajectory.cxx.
{
   return vertexPosition_;
 }
References vertexPosition_.
Referenced by simcore::persist::SimParticleBuilder::buildSimParticles().
MergeTrajectory()
void simcore::Trajectory::MergeTrajectory (G4VTrajectory * secondTrajectory)
Merge a trajectory into this one.
Parameters
secondTrajectory The trajectory to merge into this one.
Definition at line 101 of file Trajectory.cxx.
{
   if (secondTrajectory == NULL) {
     return;
   }
   Trajectory* seco = (Trajectory*)secondTrajectory;
   G4int ent = seco->GetPointEntries();
   for (int i = 1; i < ent; i++) {
     trajPoints_->push_back((*(seco->trajPoints_))[i]);
   }
   delete (*seco->trajPoints_)[0];
   seco->trajPoints_->clear();
 }
References GetPointEntries(), and trajPoints_.
operator delete()
void simcore::Trajectory::operator delete (void * obj) inline
Delete a trajectory.
Parameters
obj The object to delete.
Definition at line 257 of file Trajectory.h.
{
   TrajectoryAllocator.FreeSingle((Trajectory*)aTrajectory);
 }
References simcore::TrajectoryAllocator.
operator new()
void * simcore::Trajectory::operator new (size_t s) inline
Create a new trajectory.
Parameters
s The size of the object.
Definition at line 251 of file Trajectory.h.
{
   void* aTrajectory;
   aTrajectory = (void*)TrajectoryAllocator.MallocSingle();
   return aTrajectory;
 }
References simcore::TrajectoryAllocator.
setGenStatus()
void simcore::Trajectory::setGenStatus (int genStatus)
Set the generator status of the particle.
Parameters
genStatus The particle's generator status.
Definition at line 131 of file Trajectory.cxx.
 { genStatus_ = theGenStatus; }
References genStatus_.
Referenced by simcore::UserTrackingAction::storeTrajectory().
Member Data Documentation
endPointMomentum_
G4ThreeVector simcore::Trajectory::endPointMomentum_ private
The momentum at the particle's end point.
Definition at line 227 of file Trajectory.h.
energy_
G4double simcore::Trajectory::energy_ private
The particle's energy.
Definition at line 212 of file Trajectory.h.
Referenced by getEnergy(), and Trajectory().
genStatus_
G4int simcore::Trajectory::genStatus_ private
The particle's generator status.
Definition at line 221 of file Trajectory.h.
Referenced by getGenStatus(), and setGenStatus().
globalTime_
G4float simcore::Trajectory::globalTime_ private
The particle's global time.
Definition at line 218 of file Trajectory.h.
Referenced by getGlobalTime(), and Trajectory().
initialMomentum_
G4ThreeVector simcore::Trajectory::initialMomentum_ private
The particle's initial momentum.
Definition at line 224 of file Trajectory.h.
Referenced by GetInitialMomentum(), and Trajectory().
mass_
G4double simcore::Trajectory::mass_ private
The particle's mass.
Definition at line 215 of file Trajectory.h.
Referenced by getMass(), and Trajectory().
parentID_
G4int simcore::Trajectory::parentID_ private
The parent track ID.
Definition at line 209 of file Trajectory.h.
Referenced by GetParentID(), and Trajectory().
particleDef_
G4ParticleDefinition* simcore::Trajectory::particleDef_ private
The particle definition.
Definition at line 203 of file Trajectory.h.
Referenced by GetCharge(), GetParticleName(), GetPDGEncoding(), and Trajectory().
processType_
int simcore::Trajectory::processType_ private
The type of the process which created the track.
Definition at line 243 of file Trajectory.h.
Referenced by getProcessType(), and Trajectory().
trackID_
G4int simcore::Trajectory::trackID_ private
The track ID.
Definition at line 206 of file Trajectory.h.
Referenced by GetTrackID(), and Trajectory().
trajPoints_
TrajectoryPointContainer* simcore::Trajectory::trajPoints_ private
The list of trajectory points.
Definition at line 200 of file Trajectory.h.
Referenced by AppendStep(), GetPoint(), GetPointEntries(), MergeTrajectory(), Trajectory(), and ~Trajectory().
vertexPosition_
G4ThreeVector simcore::Trajectory::vertexPosition_ private
The particle's vertex position.
Definition at line 230 of file Trajectory.h.
Referenced by getVertexPosition(), and Trajectory().
vertexRegion_
std::string simcore::Trajectory::vertexRegion_ private
The particle's create region This variable is not stored in the output SimParticle event, but it is helpful for the TrackMap::findIncident function.
Definition at line 240 of file Trajectory.h.
Referenced by Trajectory().
The documentation for this class was generated from the following files:
SimCore/include/SimCore/Trajectory.h
SimCore/src/SimCore/Trajectory.cxx