LDMX Software: ldmx::TrigScintCluster Class Reference
ldmx::TrigScintCluster Class Reference
Stores cluster information from the trigger scintillator pads. Adds on the ECal cluster functionality.
#include <TrigScintCluster.h>
Public Member Functions
TrigScintCluster ()=default
virtual ~TrigScintCluster ()
void Print (Option_t *option="") const
void Clear (Option_t *option="")
void addHit (uint idx, const ldmx::TrigScintHit *hit)
void setSeed (int idx)
void setEnergy (double energy)
void setPE (float PE)
void setNHits (int nHits)
void setIDs (std::vector< unsigned int > &hitIDs)
void setCentroidXYZ (double x, double y, double z)
void setCentroid (double centroid)
void setTime (float t)
float getTime () const
void setBeamEfrac (float e)
float getBeamEfrac () const
int getSeed () const
double getEnergy () const
double getPE () const
int getNHits () const
double getCentroidX () const
double getCentroidY () const
double getCentroidZ () const
const std::vector< unsigned int > & getHitIDs () const
double getCentroid () const
bool operator< (const TrigScintCluster &rhs) const
Private Member Functions
ClassDef (TrigScintCluster, 1)
Private Attributes
std::vector< unsigned int > hitIDs_
double energy_ {0}
int nHits_ {0}
float PE_ {0}
int seed_ {-1}
double centroid_ {-1}
double centroidX_ {0}
double centroidY_ {0}
double centroidZ_ {0}
float beamEfrac_ {0.}
float time_ {0.}
Detailed Description
Stores cluster information from the trigger scintillator pads. Adds on the ECal cluster functionality.
Definition at line 21 of file TrigScintCluster.h.
Constructor & Destructor Documentation
TrigScintCluster()
ldmx::TrigScintCluster::TrigScintCluster () default
Class constructor.
~TrigScintCluster()
virtual ldmx::TrigScintCluster::~TrigScintCluster () virtual
Class destructor.
Member Function Documentation
addHit()
void ldmx::TrigScintCluster::addHit (uint idx, const ldmx::TrigScintHit * hit)
Take in the hits that make up the cluster.
Parameters
idx The digi hit's entry number in the event's digi collection.
hit The digi hit
ClassDef()
ldmx::TrigScintCluster::ClassDef (TrigScintCluster , 1) private
The ROOT class definition.
Clear()
void ldmx::TrigScintCluster::Clear (Option_t * option = "")
Reset the TrigScintCluster object.
getBeamEfrac()
float ldmx::TrigScintCluster::getBeamEfrac () const inline
Get beam energy fraction of hit.
Definition at line 108 of file TrigScintCluster.h.
{ return beamEfrac_; }
getCentroid()
double ldmx::TrigScintCluster::getCentroid () const inline
Get the cluster centroid in units of channel nb
Definition at line 135 of file TrigScintCluster.h.
{ return centroid_; }
getCentroidX()
double ldmx::TrigScintCluster::getCentroidX () const inline
Get cluster centroid in x [mm] (not implmented)
Definition at line 123 of file TrigScintCluster.h.
{ return centroidX_; }
getCentroidY()
double ldmx::TrigScintCluster::getCentroidY () const inline
Get cluster centroid in y [mm] (not implmented)
Definition at line 126 of file TrigScintCluster.h.
{ return centroidY_; }
getCentroidZ()
double ldmx::TrigScintCluster::getCentroidZ () const inline
Get cluster centroid in z [mm] (not implmented)
Definition at line 129 of file TrigScintCluster.h.
{ return centroidZ_; }
getEnergy()
double ldmx::TrigScintCluster::getEnergy () const inline
Get cluster total energy deposition
Definition at line 114 of file TrigScintCluster.h.
{ return energy_; }
getHitIDs()
const std::vector< unsigned int > & ldmx::TrigScintCluster::getHitIDs () const inline
Get vector of channel IDs of hits forming the cluster
Definition at line 132 of file TrigScintCluster.h.
{ return hitIDs_; }
getNHits()
int ldmx::TrigScintCluster::getNHits () const inline
Get the number of hits constituting the cluster
Definition at line 120 of file TrigScintCluster.h.
{ return nHits_; }
getPE()
double ldmx::TrigScintCluster::getPE () const inline
Get cluster total photoelectron count
Definition at line 117 of file TrigScintCluster.h.
{ return PE_; }
getSeed()
int ldmx::TrigScintCluster::getSeed () const inline
Get cluster seed channel nb
Definition at line 111 of file TrigScintCluster.h.
{ return seed_; }
getTime()
float ldmx::TrigScintCluster::getTime () const inline
Get time of hit.
Definition at line 102 of file TrigScintCluster.h.
{ return time_; }
operator<()
bool ldmx::TrigScintCluster::operator< (const TrigScintCluster & rhs) const inline
Definition at line 137 of file TrigScintCluster.h.
{
    return this->getEnergy() < rhs.getEnergy();
  }
Print()
void ldmx::TrigScintCluster::Print (Option_t * option = "") const
Print a description of this object.
Referenced by trigscint::TestBeamClusterProducer::produce(), and trigscint::TrigScintClusterProducer::produce().
setBeamEfrac()
void ldmx::TrigScintCluster::setBeamEfrac (float e) inline
Set beam energy fraction of hit.
Definition at line 105 of file TrigScintCluster.h.
{ beamEfrac_ = e; }
Referenced by trigscint::TestBeamClusterProducer::produce(), and trigscint::TrigScintClusterProducer::produce().
setCentroid()
void ldmx::TrigScintCluster::setCentroid (double centroid) inline
Parameters
centroid The channel ID centroid
Definition at line 96 of file TrigScintCluster.h.
{ centroid_ = centroid; }
Referenced by trigscint::TestBeamClusterProducer::produce(), and trigscint::TrigScintClusterProducer::produce().
setCentroidXYZ()
void ldmx::TrigScintCluster::setCentroidXYZ (double x, double y, double z) inline
The cluster centroid in x,y,z
Parameters
x Cluster x coordinate
y Cluster y coordinate
z Cluster z coordinate (not implemented)
Definition at line 87 of file TrigScintCluster.h.
{
    centroidX_ = x;
    centroidY_ = y;
    centroidZ_ = z;
  }
Referenced by trigscint::TrigScintClusterProducer::produce().
setEnergy()
void ldmx::TrigScintCluster::setEnergy (double energy) inline
Set the cluster energy
Parameters
energy The cluster energy deposition (in units given by hit)
Definition at line 61 of file TrigScintCluster.h.
{ energy_ = energy; }
Referenced by trigscint::TestBeamClusterProducer::produce(), and trigscint::TrigScintClusterProducer::produce().
setIDs()
void ldmx::TrigScintCluster::setIDs (std::vector< unsigned int > & hitIDs) inline
The channel numbers of hits forming the cluster
Parameters
hitIDs vector of channel numbers of hits forming the cluster
Definition at line 79 of file TrigScintCluster.h.
{ hitIDs_ = hitIDs; }
Referenced by trigscint::TestBeamClusterProducer::produce(), and trigscint::TrigScintClusterProducer::produce().
setNHits()
void ldmx::TrigScintCluster::setNHits (int nHits) inline
The number of hits forming the cluster
Parameters
nHits Number of hits forming the cluster
Definition at line 73 of file TrigScintCluster.h.
{ nHits_ = nHits; }
Referenced by trigscint::TestBeamClusterProducer::produce(), and trigscint::TrigScintClusterProducer::produce().
setPE()
void ldmx::TrigScintCluster::setPE (float PE) inline
Set the cluster photoelectron count (PE)
Parameters
PE The cluster photoelectron count
Definition at line 67 of file TrigScintCluster.h.
{ PE_ = PE; }
Referenced by trigscint::TestBeamClusterProducer::produce(), and trigscint::TrigScintClusterProducer::produce().
setSeed()
void ldmx::TrigScintCluster::setSeed (int idx) inline
Parameters
idx The digi collection index of the hit seeding the cluster
Definition at line 55 of file TrigScintCluster.h.
{ seed_ = idx; }
Referenced by trigscint::TestBeamClusterProducer::produce(), and trigscint::TrigScintClusterProducer::produce().
setTime()
void ldmx::TrigScintCluster::setTime (float t) inline
Set time of hit.
Definition at line 99 of file TrigScintCluster.h.
{ time_ = t; }
Referenced by trigscint::TestBeamClusterProducer::produce(), and trigscint::TrigScintClusterProducer::produce().
Member Data Documentation
beamEfrac_
float ldmx::TrigScintCluster::beamEfrac_ {0.} private
Definition at line 172 of file TrigScintCluster.h.
centroid_
double ldmx::TrigScintCluster::centroid_ {-1} private
Definition at line 159 of file TrigScintCluster.h.
centroidX_
double ldmx::TrigScintCluster::centroidX_ {0} private
Definition at line 162 of file TrigScintCluster.h.
centroidY_
double ldmx::TrigScintCluster::centroidY_ {0} private
Definition at line 165 of file TrigScintCluster.h.
centroidZ_
double ldmx::TrigScintCluster::centroidZ_ {0} private
Definition at line 168 of file TrigScintCluster.h.
energy_
double ldmx::TrigScintCluster::energy_ {0} private
Definition at line 146 of file TrigScintCluster.h.
hitIDs_
std::vector<unsigned int> ldmx::TrigScintCluster::hitIDs_ private
Definition at line 143 of file TrigScintCluster.h.
nHits_
int ldmx::TrigScintCluster::nHits_ {0} private
Definition at line 149 of file TrigScintCluster.h.
PE_
float ldmx::TrigScintCluster::PE_ {0} private
Definition at line 152 of file TrigScintCluster.h.
seed_
int ldmx::TrigScintCluster::seed_ {-1} private
Definition at line 155 of file TrigScintCluster.h.
time_
float ldmx::TrigScintCluster::time_ {0.} private
Definition at line 176 of file TrigScintCluster.h.
The documentation for this class was generated from the following file:
TrigScint/include/TrigScint/Event/TrigScintCluster.h