LDMX Software: hcal::utility::Reader Class Reference
hcal::utility::Reader Class Reference
#include <HcalRawDecoder.h>
Public Member Functions
Reader ()
construct a reader but it is not open yet
void open (const std::vector< uint32_t > &b)
void open (const std::string &file_name)
operator bool () const
uint32_t next ()
Reader & operator>> (uint32_t &w)
bool isFile () const
void rewind (long int n)
Private Member Functions
uint32_t vector_pop ()
uint32_t file_pop ()
Private Attributes
bool is_open_
is the reader opened?
const std::vector< uint32_t > * buffer_handle_ {nullptr}
vector buffer reference
long int i_curr_ {-1}
current iterator
std::ifstream file_
file stream reference
Detailed Description
A reader that behaves the same for buffers coming from a raw file or a buffer that is a vector of unsigned ints.
The common aspect of both of these reading modes is that we want to decode on a word-by-word basis where the words are 32-bit integers.
Definition at line 23 of file HcalRawDecoder.h.
Constructor & Destructor Documentation
Reader()
hcal::utility::Reader::Reader () inline
construct a reader but it is not open yet
Definition at line 26 of file HcalRawDecoder.h.
: is_open_{false}, buffer_handle_{nullptr} {}
Member Function Documentation
file_pop()
uint32_t hcal::utility::Reader::file_pop () private
Pop the next word out of the file. We only read from the file if the file is in a good state so that we don't accidentally seg fault. Otherwise we will just return a un-assigned word.
Definition at line 50 of file HcalRawDecoder.cxx.
{
  uint32_t w;
  if (file_) file_.read(reinterpret_cast<char*>(&w), 4);
  return w;
}
References file_.
Referenced by next().
isFile()
bool hcal::utility::Reader::isFile () const inline
Check if we are reading in file mode.
Returns
true if we and the ifstream are both open
Definition at line 74 of file HcalRawDecoder.h.
{ return (is_open_ and file_.is_open()); }
References file_, and is_open_.
Referenced by next(), operator bool(), hcal::HcalRawDecoder::produce(), and rewind().
next()
uint32_t hcal::utility::Reader::next ()
Get the next word from the buffer
See also
file_pop for file mode
vector_pop for vector mode
Definition at line 30 of file HcalRawDecoder.cxx.
                      {
  if (isFile())
    return file_pop();
  else
    return vector_pop();
}
References file_pop(), isFile(), and vector_pop().
Referenced by operator>>().
open() [1/2]
void hcal::utility::Reader::open (const std::string & file_name)
Open the reader with a file to read.
Definition at line 24 of file HcalRawDecoder.cxx.
{
  file_.unsetf(std::ios::skipws);
  file_.open(file_name, std::ios::binary | std::ios::in);
  is_open_ = true;
}
References file_, and is_open_.
open() [2/2]
void hcal::utility::Reader::open (const std::vector< uint32_t > & b)
Open the reader with a vector to read
Definition at line 19 of file HcalRawDecoder.cxx.
{
  buffer_handle_ = &b;
  is_open_ = true;
}
References buffer_handle_, and is_open_.
Referenced by hcal::HcalRawDecoder::configure(), and hcal::HcalRawDecoder::produce().
operator bool()
hcal::utility::Reader::operator bool () const inline
Check if the reader is in a good state.
Returns
true if open and not at the end of file (or vector)
Definition at line 43 of file HcalRawDecoder.h.
{
    if (!is_open_)
      return false;
    else if (isFile()) {
      return bool(file_);
    } else
      return (i_curr_ < buffer_handle_->size());
  }
References file_, is_open_, and isFile().
operator>>()
Reader & hcal::utility::Reader::operator>> (uint32_t & w) inline
Put the next word from the buffer in the passed reference. Return the state of the reader after this is done.
Definition at line 64 of file HcalRawDecoder.h.
{
    w = next();
    return *this;
  }
References next().
rewind()
void hcal::utility::Reader::rewind (long int n)
Sometimes we need to check the next few header words but then re-read them later. This function allows us to backtrack by n words.
Parameters
[in] n number of 32-bit words to back track by
Definition at line 37 of file HcalRawDecoder.cxx.
{
  if (isFile()) {
    file_.seekg(file_.tellg() - 4 * n);
  } else {
    i_curr_ - n;
  }
}
References file_, i_curr_, and isFile().
vector_pop()
uint32_t hcal::utility::Reader::vector_pop () private
Pop the next value of the buffer "off" the vector. This just increments our index and returns the word at that location.
Exceptions
std::out_of_range if we try to pop a word past the end of the vector.
Definition at line 45 of file HcalRawDecoder.cxx.
{
  ++i_curr_;
  return buffer_handle_->at(i_curr_);
}
References buffer_handle_, and i_curr_.
Referenced by next().
Member Data Documentation
buffer_handle_
const std::vector<uint32_t>* hcal::utility::Reader::buffer_handle_ {nullptr} private
vector buffer reference
Definition at line 108 of file HcalRawDecoder.h.
Referenced by open(), and vector_pop().
file_
std::ifstream hcal::utility::Reader::file_ private
file stream reference
Definition at line 112 of file HcalRawDecoder.h.
Referenced by file_pop(), isFile(), open(), operator bool(), and rewind().
i_curr_
long int hcal::utility::Reader::i_curr_ {-1} private
current iterator
Definition at line 110 of file HcalRawDecoder.h.
Referenced by rewind(), and vector_pop().
is_open_
bool hcal::utility::Reader::is_open_ private
is the reader opened?
Definition at line 106 of file HcalRawDecoder.h.
Referenced by isFile(), open(), and operator bool().
The documentation for this class was generated from the following files:
Hcal/include/Hcal/HcalRawDecoder.h
Hcal/src/Hcal/HcalRawDecoder.cxx