LDMX Software: simcore::ReSimulator Class Reference
simcore::ReSimulator Class Reference
Public Member Functions
ReSimulator (const std::string &name, framework::Process &process)
void configure (framework::config::Parameters &parameters) final override
void produce (framework::Event &event) override
Public Member Functions inherited from simcore::SimulatorBase
SimulatorBase (const std::string &name, framework::Process &process)
void configure (framework::config::Parameters &parameters) override
Public Member Functions inherited from framework::Producer
Producer (const std::string &name, Process &process)
virtual void produce (Event &event)=0
virtual void beforeNewRun (ldmx::RunHeader &header)
Public Member Functions inherited from framework::EventProcessor
EventProcessor (const std::string &name, Process &process)
virtual ~EventProcessor ()
virtual void configure (framework::config::Parameters &parameters)
virtual void onNewRun (const ldmx::RunHeader &runHeader)
virtual void onFileOpen (EventFile &eventFile)
virtual void onFileClose (EventFile &eventFile)
virtual void onProcessStart ()
virtual void onProcessEnd ()
template<class T >
const T & getCondition (const std::string &condition_name)
TDirectory * getHistoDirectory ()
void setStorageHint (framework::StorageControlHint hint)
void setStorageHint (framework::StorageControlHint hint, const std::string &purposeString)
int getLogFrequency () const
int getRunNumber () const
std::string getName () const
void createHistograms (const std::vector< framework::config::Parameters > &histos)
Private Attributes
std::vector< int > events_to_resimulate_
bool resimulate_all_events
int events_resimulated = 0
Additional Inherited Members
Static Public Member Functions inherited from framework::EventProcessor
static void declare (const std::string &classname, int classtype, EventProcessorMaker *)
Static Public Attributes inherited from framework::Producer
static const int CLASSTYPE {1}
Protected Member Functions inherited from simcore::SimulatorBase
void onProcessEnd () override
Callback called once processing is complete.
void onProcessStart () override
virtual void updateEventHeader (ldmx::EventHeader &eventHeader) const
virtual void saveTracks (framework::Event &event)
virtual void saveSDHits (framework::Event &event)
virtual void produce (framework::Event &event) override=0
Protected Member Functions inherited from framework::EventProcessor
void abortEvent ()
Protected Attributes inherited from simcore::SimulatorBase
ConditionsInterface conditionsIntf_
Conditions interface.
G4UImanager * uiManager_ {nullptr}
User interface handle.
std::unique_ptr< RunManager > runManager_
Manager controlling G4 simulation run.
std::unique_ptr< G4UIsession > sessionHandle_
Handle to the G4Session -> how to deal with G4cout and G4cerr.
int verbosity_ {1}
Vebosity for the simulation.
framework::config::Parameters parameters_
The parameters used to configure the simulation.
std::vector< std::string > preInitCommands_
std::vector< std::string > postInitCommands_
Protected Attributes inherited from framework::EventProcessor
HistogramHelper histograms_
Interface class for making and filling histograms.
NtupleManager & ntuple_ {NtupleManager::getInstance()}
Manager for any ntuples.
logging::logger theLog_
The logger for this EventProcessor.
Static Protected Attributes inherited from simcore::SimulatorBase
static const std::vector< std::string > invalidCommands_
Detailed Description
Definition at line 9 of file ReSimulator.h.
Constructor & Destructor Documentation
ReSimulator()
simcore::ReSimulator::ReSimulator (const std::string & name, framework::Process & process) inline
Definition at line 11 of file ReSimulator.h.
      : SimulatorBase{name, process} {}
Member Function Documentation
configure()
void simcore::ReSimulator::configure (framework::config::Parameters & parameters) final override virtual
Callback for the EventProcessor to configure itself from the given set of parameters.
The parameters a processor has access to are the member variables of the python class in the sequence that has className equal to the EventProcessor class name.
For an example, look at MyProcessor.
Parameters
parameters Parameters for configuration.
Reimplemented from framework::EventProcessor.
Definition at line 5 of file ReSimulator.cxx.
{
  SimulatorBase::configure(parameters);
  resimulate_all_events =
      parameters.getParameter<bool>("resimulate_all_events");
  if (!resimulate_all_events) {
    events_to_resimulate_ =
        parameters.getParameter<std::vector<int>>("events_to_resimulate", {});
    if (events_to_resimulate_.size() == 0) {
      EXCEPTION_RAISE(
          "ReSimNoEvents",
          "ReSim was configured with resimulate_all_events marked false but "
          "no event numbers were requested.\n\nDid you forget to configure "
          "the events_to_resimulate parameter?\n");
    }
  }
}
References simcore::SimulatorBase::configure(), framework::config::Parameters::getParameter(), and resimulate_all_events.
produce()
void simcore::ReSimulator::produce (framework::Event & event) override virtual
Process the event and put new data products into it.
Parameters
event The Event to process.
Implements simcore::SimulatorBase.
Definition at line 21 of file ReSimulator.cxx.
{
  /* numEventsBegan_++; */
  auto& eventHeader{event.getEventHeader()};
  const auto eventNumber{eventHeader.getEventNumber()};
  if (!resimulate_all_events) {
    auto found = std::find(std::begin(events_to_resimulate_),
                           std::end(events_to_resimulate_), eventNumber);
    if (found == std::end(events_to_resimulate_)) {
      if (verbosity_ > 1) {
        std::cout << "Skipping event: " << eventNumber
                  << " since it wasn't part of the requested events..."
                  << std::endl;
      }
      this->abortEvent();  // get out of processors loop
      return;
    }
  }
  if (verbosity_ > 0) {
    std::cout << "Resimulating " << eventNumber << std::endl;
  }
  std::istringstream iss(eventHeader.getStringParameter("eventSeed"));
  G4Random::restoreFullState(iss);
  runManager_->ProcessOneEvent(eventNumber);
  if (verbosity_ > 1) {
    std::cout << "Finished with event number " << eventNumber << std::endl;
  }
  if (runManager_->GetCurrentEvent()->IsAborted()) {
    runManager_->TerminateOneEvent();
    SensitiveDetector::Factory::get().apply(
        [](auto sd) { sd->OnFinishedEvent(); });
    EXCEPTION_RAISE(
        "ReSimAbortedEvent",
        "Resimulation resulted in an aborted event, something is wrong with "
        "the seed from event " +
            std::to_string(eventNumber));
  }
  eventHeader.setEventNumber(++events_resimulated);
  updateEventHeader(eventHeader);
  saveTracks(event);
  saveSDHits(event);
  runManager_->TerminateOneEvent();
}
References framework::EventProcessor::abortEvent(), simcore::Factory< Prototype, PrototypePtr, PrototypeConstructorArgs >::apply(), simcore::Factory< Prototype, PrototypePtr, PrototypeConstructorArgs >::get(), resimulate_all_events, simcore::SimulatorBase::runManager_, and simcore::SimulatorBase::verbosity_.
Member Data Documentation
events_resimulated
int simcore::ReSimulator::events_resimulated = 0 private
Definition at line 48 of file ReSimulator.h.
events_to_resimulate_
std::vector<int> simcore::ReSimulator::events_to_resimulate_ private
Definition at line 36 of file ReSimulator.h.
resimulate_all_events
bool simcore::ReSimulator::resimulate_all_events private
Whether to resimulate all events in the input files
Definition at line 41 of file ReSimulator.h.
Referenced by configure(), and produce().
The documentation for this class was generated from the following files:
SimCore/include/SimCore/ReSimulator.h
SimCore/src/SimCore/ReSimulator.cxx