LDMX Software: simcore::SensitiveDetector Class Reference
simcore::SensitiveDetector Class Reference abstract
#include <SensitiveDetector.h>
Public Types
using Factory = ::simcore::Factory< SensitiveDetector, SensitiveDetector *, const std::string &, simcore::ConditionsInterface &, const framework::config::Parameters & >
Public Member Functions
SensitiveDetector (const std::string &name, simcore::ConditionsInterface &ci, const framework::config::Parameters &parameters)
virtual ~SensitiveDetector ()
virtual bool isSensDet (G4LogicalVolume *lv) const =0
virtual G4bool ProcessHits (G4Step *step, G4TouchableHistory *hist)=0
virtual void saveHits (framework::Event &event)=0
virtual void EndOfEvent (G4HCofThisEvent *) final override
virtual void EndOfEvent ()=0
Protected Member Functions
template<class T >
const T & getCondition (const std::string &condition_name)
bool isGeantino (const G4Step *step) const
const TrackMap & getTrackMap () const
Private Attributes
simcore::ConditionsInterface & conditions_interface_
Handle to our interface to conditions objects.
Detailed Description
Dynamically loaded Geant4 SensitiveDetector for saving hits in specific volumes within the simulation
Definition at line 23 of file SensitiveDetector.h.
Member Typedef Documentation
Factory
using simcore::SensitiveDetector::Factory = ::simcore::Factory<SensitiveDetector, SensitiveDetector*, const std::string&, simcore::ConditionsInterface&, const framework::config::Parameters&>
The SD Factory
We have the factory create raw pointers since the G4SDManager handles destruction of all of the registered SensitiveDetectors.
Definition at line 42 of file SensitiveDetector.h.
Constructor & Destructor Documentation
SensitiveDetector()
simcore::SensitiveDetector::SensitiveDetector (const std::string & name, simcore::ConditionsInterface & ci, const framework::config::Parameters & parameters)
Constructor
Parameters
[in] name unique instance name for this sensitive detector
[in] ci handle to current conditions interface
[in] parameters python configuration parameters
Definition at line 12 of file SensitiveDetector.cxx.
    : G4VSensitiveDetector(name), conditions_interface_(ci) {
  // register us with the manager
  G4SDManager::GetSDMpointer()->AddNewDetector(this);
}
~SensitiveDetector()
simcore::SensitiveDetector::~SensitiveDetector () virtual
Destructor
Definition at line 20 of file SensitiveDetector.cxx.
{}
Member Function Documentation
EndOfEvent() [1/2]
virtual void simcore::SensitiveDetector::EndOfEvent () pure virtual
Cleanup SD and prepare a new-event state
Implemented in simcore::EcalSD, simcore::HcalSD, simcore::ScoringPlaneSD, simcore::TrackerSD, and simcore::TrigScintSD.
EndOfEvent() [2/2]
virtual void simcore::SensitiveDetector::EndOfEvent (G4HCofThisEvent *) inline final override virtual
This is Geant4's handle to tell us the event is ending
Since we are handling the Hit Collections (HC) directly, the input to this function is of no use to us. This is simply here to make sure that we can reset the SD to a new-event state whether or not a given event was serialized.
Definition at line 91 of file SensitiveDetector.h.
{}
getCondition()
template<class T > const T & simcore::SensitiveDetector::getCondition (const std::string & condition_name) inline protected
Record the configuration of this detector into the run header.
Parameters
[in,out] header RunHeader to write configuration to Get a condition object from the conditions interface
Used in the same way that EventProcessors can retrieve conditions.
Template Parameters
in,out] T type of condition to get
Parameters
[in] name name of condition to get
Returns
condition object requested
Definition at line 115 of file SensitiveDetector.h.
{
    return conditions_interface_.getCondition<T>(condition_name);
  }
References conditions_interface_, and simcore::ConditionsInterface::getCondition().
getTrackMap()
const TrackMap & simcore::SensitiveDetector::getTrackMap () const inline protected
Get a handle to the current track map.
The track map is created only after the event begins, so you will get a segmentation violation if you call this function before an event has started.
Definition at line 134 of file SensitiveDetector.h.
{
    return simcore::g4user::TrackingAction::get()->getTrackMap();
  }
References simcore::g4user::TrackingAction::get(), and simcore::g4user::TrackingAction::getTrackMap().
Referenced by simcore::EcalSD::ProcessHits(), and simcore::HcalSD::ProcessHits().
isGeantino()
bool simcore::SensitiveDetector::isGeantino (const G4Step * step) const protected
Check if the passed step is a step of a geantino
Parameters
[in] step Current step to check
Returns
true if step is coming from neutral/charged genatino
Definition at line 22 of file SensitiveDetector.cxx.
{
  auto particle_def{step->GetTrack()->GetDefinition()};
  return (particle_def == G4Geantino::Definition() or
          particle_def == G4ChargedGeantino::Definition());
}
Referenced by simcore::EcalSD::ProcessHits(), simcore::HcalSD::ProcessHits(), simcore::TrackerSD::ProcessHits(), and simcore::TrigScintSD::ProcessHits().
isSensDet()
virtual bool simcore::SensitiveDetector::isSensDet (G4LogicalVolume * lv) const pure virtual
Here, we must determine if we should be attached to the input logical volume. Return 'true' if we should be attached to it and 'false' otherwise.
Parameters
[in] lv logical volume to check
Returns
true if the input lv should be connected to this sensitive detector
Implemented in simcore::EcalSD, simcore::TrigScintSD, simcore::HcalSD, simcore::ScoringPlaneSD, and simcore::TrackerSD.
ProcessHits()
virtual G4bool simcore::SensitiveDetector::ProcessHits (G4Step * step, G4TouchableHistory * hist) pure virtual
This is Geant4's handle to tell us that a particle has stepped through our sensitive detector and we should process its interaction with us.
Parameters
[in] step the step that happened within one of our logical volumes
[in] hist the touchable history of the step
Implemented in simcore::EcalSD, simcore::HcalSD, simcore::ScoringPlaneSD, simcore::TrackerSD, and simcore::TrigScintSD.
saveHits()
virtual void simcore::SensitiveDetector::saveHits (framework::Event & event) pure virtual
We are given the event bus here and we must decide now what to persist into the event.
This function must perform two tasks.
End-of-event processing on the collected data (e.g. filtering or merging events) before serilization.
Serialization of collected data with event.add
Parameters
[in,out] event event bus to add thing(s) to
Implemented in simcore::EcalSD, simcore::HcalSD, simcore::ScoringPlaneSD, simcore::TrackerSD, and simcore::TrigScintSD.
Member Data Documentation
conditions_interface_
simcore::ConditionsInterface& simcore::SensitiveDetector::conditions_interface_ private
Handle to our interface to conditions objects.
Definition at line 140 of file SensitiveDetector.h.
Referenced by getCondition().
The documentation for this class was generated from the following files:
SimCore/include/SimCore/SensitiveDetector.h
SimCore/src/SimCore/SensitiveDetector.cxx