LDMX Software: simcore::UserEventAction Class Reference
simcore::UserEventAction Class Reference
Implementation of user event action hook.
#include <UserEventAction.h>
Public Member Functions
UserEventAction ()
virtual ~UserEventAction ()
void BeginOfEventAction (const G4Event *event)
void EndOfEventAction (const G4Event *event)
void registerAction (UserAction *eventAction)
Private Attributes
std::vector< UserAction * > eventActions_
Detailed Description
Implementation of user event action hook.
Definition at line 34 of file UserEventAction.h.
Constructor & Destructor Documentation
UserEventAction()
simcore::UserEventAction::UserEventAction () inline
Class constructor.
Definition at line 39 of file UserEventAction.h.
 {}
~UserEventAction()
virtual simcore::UserEventAction::~UserEventAction () inline virtual
Class destructor.
Definition at line 44 of file UserEventAction.h.
 {}
Member Function Documentation
BeginOfEventAction()
void simcore::UserEventAction::BeginOfEventAction (const G4Event * event)
Implementation of begin of event hook.
Parameters
event The Geant4 event.
Definition at line 24 of file UserEventAction.cxx.
{
   // Clear the global track map.
   UserTrackingAction::getUserTrackingAction()->getTrackMap()->clear();
   // Call user event actions
   for (auto& eventAction : eventActions_)
     eventAction->BeginOfEventAction(event);
 }
References simcore::TrackMap::clear(), simcore::UserTrackingAction::getTrackMap(), and simcore::UserTrackingAction::getUserTrackingAction().
EndOfEventAction()
void simcore::UserEventAction::EndOfEventAction (const G4Event * event)
Implementation of end of event hook.
Parameters
event The Geant4 event.
Definition at line 33 of file UserEventAction.cxx.
{
   // Call user event actions
   for (auto& eventAction : eventActions_) eventAction->EndOfEventAction(event);
 }
registerAction()
void simcore::UserEventAction::registerAction (UserAction * eventAction) inline
Register a user action of type EventAction with this class.
Parameters
action User action of type EventAction
Definition at line 63 of file UserEventAction.h.
{
     eventActions_.push_back(eventAction);
   }
The documentation for this class was generated from the following files:
SimCore/include/SimCore/UserEventAction.h
SimCore/src/SimCore/UserEventAction.cxx