LDMX Software: ldmx::PrimaryGeneratorAction Class Reference
ldmx::PrimaryGeneratorAction Class Reference
Implementation of Geant4 primary generator action.
#include <PrimaryGeneratorAction.h>
Public Member Functions
PrimaryGeneratorAction (Parameters &parameters)
virtual ~PrimaryGeneratorAction ()
void GeneratePrimaries (G4Event *event) final override
Private Member Functions
void smearingBeamspot (G4Event *event)
void setUserPrimaryInfo (G4Event *event)
Private Attributes
PrimaryGeneratorManager & manager_
Manager of all generators used by the event.
std::unique_ptr< TRandom3 > random_
Random number generator.
Parameters parameters_
The parameters used to configure the primary generator of choice.
bool useBeamspot_ {false}
double beamspotXSize_ {0}
double beamspotYSize_ {0}
double beamspotZSize_ {0.}
bool time_shift_primaries_ {true}
Detailed Description
Implementation of Geant4 primary generator action.
Definition at line 41 of file PrimaryGeneratorAction.h.
Constructor & Destructor Documentation
~PrimaryGeneratorAction()
ldmx::PrimaryGeneratorAction::~PrimaryGeneratorAction () virtual
Class destructor.
Definition at line 68 of file PrimaryGeneratorAction.cxx.
 { }
Member Function Documentation
GeneratePrimaries()
void ldmx::PrimaryGeneratorAction::GeneratePrimaries (G4Event * event) final override
Generate the event.
Parameters
event The Geant4 event.
Get the list of generators that will be used for this event
Definition at line 70 of file PrimaryGeneratorAction.cxx.
{
         auto generators{manager_.getGenerators()};
         // Generator the primary vertex
         std::for_each( generators.begin(), generators.end(),
                 [event](const auto& generator) { generator->GeneratePrimaryVertex(event); } );
         // smear all primary vertices (if activated)
         if (event->GetNumberOfPrimaryVertex() > 0) {
             setUserPrimaryInfo(event);
             if (useBeamspot_) smearingBeamspot(event);
             if (time_shift_primaries_) {
               // shift the time so that a light-speed particle
               // arrives at the target at 0ns
               int nPV = event->GetNumberOfPrimaryVertex();
               for (int iPV = 0; iPV < nPV; ++iPV) {
                 G4PrimaryVertex *pv = event->GetPrimaryVertex(iPV);
                 pv->SetT0( pv->GetT0() + pv->GetZ0()/299.702547 );
               }
             }
         } else {
             EXCEPTION_RAISE(
                     "NoPrimaries",
                     "No primary vertices were produced by any of the generators."
                     );
         }
     }
References ldmx::PrimaryGeneratorManager::getGenerators(), manager_, setUserPrimaryInfo(), smearingBeamspot(), time_shift_primaries_, and useBeamspot_.
setUserPrimaryInfo()
void ldmx::PrimaryGeneratorAction::setUserPrimaryInfo (G4Event * event) private
Set UserInformation for primary vertices if they haven't been set before.
Some features downstream of the primaries require certain user info to function properly. This ensures that it happens.
Makes sure that each particle on each primary vertex has
A defined UserPrimaryParticleInformation member
The HepEvtStatus for this primary info is non-zero
Parameters
event Geant4 event to go through primaries
Definition at line 120 of file PrimaryGeneratorAction.cxx.
{
         int nPV = event->GetNumberOfPrimaryVertex();
         for (int iPV = 0; iPV < nPV; ++iPV) {
             G4PrimaryVertex* vertex = event->GetPrimaryVertex(iPV);
             // Loop over all particle associated with the primary vertex and
             // set the generator status to 1.
             for (int iparticle = 0; iparticle < vertex->GetNumberOfParticle(); ++iparticle) {
                 G4PrimaryParticle* primary = vertex->GetPrimary(iparticle);
                 auto primaryInfo{dynamic_cast<UserPrimaryParticleInformation*>(primary->GetUserInformation())};
                 if( not primaryInfo ) {
                     // no user info defined
                     //  ==> make a new one
                     primaryInfo = new UserPrimaryParticleInformation;
                     primary->SetUserInformation( primaryInfo );
                 }//check if primaryinfo is defined
                 int hepStatus = primaryInfo->getHepEvtStatus();
                 if ( hepStatus <= 0 ) {
                     //undefined hepStatus ==> set to 1
                     primaryInfo->setHepEvtStatus(1);
                 }//check if hepStatus defined
             }//iparticle - loop over primary particles
         } //iPV - loop over primary vertices
     }
References ldmx::UserPrimaryParticleInformation::getHepEvtStatus().
Referenced by GeneratePrimaries().
smearingBeamspot()
void ldmx::PrimaryGeneratorAction::smearingBeamspot (G4Event * event) private
Smearing beamspot
Parameters
event The Geant4 event.
Definition at line 100 of file PrimaryGeneratorAction.cxx.
{
         double IPWidthX = beamspotXSize_/2.;
         double IPWidthY = beamspotYSize_/2.;
         double IPWidthZ = beamspotZSize_/2.;
         int nPV = event->GetNumberOfPrimaryVertex();
         for (int iPV = 0; iPV < nPV; ++iPV) {
             G4PrimaryVertex* curPV = event->GetPrimaryVertex(iPV);
             double x0_i = curPV->GetX0();
             double y0_i = curPV->GetY0();
             double z0_i = curPV->GetZ0();
             double x0_f = random_->Uniform( x0_i - IPWidthX, x0_i + IPWidthX );
             double y0_f = random_->Uniform( y0_i - IPWidthY, y0_i + IPWidthY );
             double z0_f = random_->Uniform( z0_i - IPWidthZ, z0_i + IPWidthZ );
             curPV->SetPosition( x0_f, y0_f, z0_f );
         }
     }
References beamspotXSize_, beamspotYSize_, beamspotZSize_, and random_.
Referenced by GeneratePrimaries().
Member Data Documentation
beamspotXSize_
double ldmx::PrimaryGeneratorAction::beamspotXSize_ {0} private
Extent of the beamspot in x.
Definition at line 102 of file PrimaryGeneratorAction.h.
Referenced by smearingBeamspot().
beamspotYSize_
double ldmx::PrimaryGeneratorAction::beamspotYSize_ {0} private
Extent of the beamspot in y.
Definition at line 105 of file PrimaryGeneratorAction.h.
Referenced by smearingBeamspot().
beamspotZSize_
double ldmx::PrimaryGeneratorAction::beamspotZSize_ {0.} private
Extent of the beamspot in y.
Definition at line 108 of file PrimaryGeneratorAction.h.
Referenced by smearingBeamspot().
time_shift_primaries_
bool ldmx::PrimaryGeneratorAction::time_shift_primaries_ {true} private
Should we time-shift so that the primary vertices arrive (or originate) at t=0ns at z=0mm?
Note
This should remain true unless the user knows what they are doing!
Definition at line 116 of file PrimaryGeneratorAction.h.
Referenced by GeneratePrimaries().
useBeamspot_
bool ldmx::PrimaryGeneratorAction::useBeamspot_ {false} private
Flag denoting whether the vertex position of a particle should be smeared.
Definition at line 99 of file PrimaryGeneratorAction.h.
Referenced by GeneratePrimaries().
The documentation for this class was generated from the following files:
SimCore/include/SimCore/PrimaryGeneratorAction.h
SimCore/src/PrimaryGeneratorAction.cxx