LDMX Software: simcore::darkbrem::G4APrime Class Reference
simcore::darkbrem::G4APrime Class Reference
Static Public Member Functions
static G4APrime * APrime (G4double theMass=-1 *MeV)
Private Member Functions
G4APrime (const G4String &Name, G4double mass, G4double width, G4double charge, G4int iSpin, G4int iParity, G4int iConjugation, G4int iIsospin, G4int iIsospin3, G4int gParity, const G4String &pType, G4int lepton, G4int baryon, G4int encoding, G4bool stable, G4double lifetime, G4DecayTable *decaytable)
virtual ~G4APrime ()
Static Private Attributes
static G4APrime * theAPrime = 0
Detailed Description
Definition at line 20 of file G4APrime.h.
Constructor & Destructor Documentation
G4APrime()
simcore::darkbrem::G4APrime::G4APrime (const G4String & Name, G4double mass, G4double width, G4double charge, G4int iSpin, G4int iParity, G4int iConjugation, G4int iIsospin, G4int iIsospin3, G4int gParity, const G4String & pType, G4int lepton, G4int baryon, G4int encoding, G4bool stable, G4double lifetime, G4DecayTable * decaytable) inline private
Constructor
Passes all parameters to the base class constructor to register this particle definition with Geant4.
Definition at line 31 of file G4APrime.h.
      : G4ParticleDefinition(Name, mass, width, charge, iSpin, iParity,
                             iConjugation, iIsospin, iIsospin3, gParity, pType,
                             lepton, baryon, encoding, stable, lifetime,
                             decaytable) {}
Referenced by APrime().
~G4APrime()
virtual simcore::darkbrem::G4APrime::~G4APrime () inline private virtual
Destructor
Does nothing on purpose.
Definition at line 46 of file G4APrime.h.
{}
Member Function Documentation
APrime()
G4APrime * simcore::darkbrem::G4APrime::APrime (G4double theMass = -1 * MeV) static
Accessor for APrime definition
The first call to this function defines the mass and then later calls can call it without an argument because we will just return the single instance of the A' definition.
Parameters
[in] theMass mass of the A' in MeV
Definition at line 19 of file G4APrime.cxx.
{
  if (!theAPrime) {
    if (theMass < 0)
      EXCEPTION_RAISE("APMass", "APrime doesn't have a mass set!");
    const G4String& name = "A^1";
    G4double mass = theMass;
    G4double width = 0.;
    G4double charge = 0;
    G4int iSpin = 0;
    G4int iParity = 0;
    G4int iConjugation = 0;
    G4int iIsospin = 0;
    G4int iIsospin3 = 0;
    G4int gParity = 0;
    const G4String& pType = "APrime";
    G4int lepton = 0;
    G4int baryon = 0;
    G4int encoding = 622;    // PDG ID
    G4bool stable = true;    // stable - no decay
    G4double lifetime = -1;  // stable - no decay
    G4DecayTable* decaytable = 0;
    theAPrime =
        new G4APrime(name, mass, width, charge, iSpin, iParity, iConjugation,
                     iIsospin, iIsospin3, gParity, pType, lepton, baryon,
                     encoding, stable, lifetime, decaytable);
  }
  return theAPrime;
}
References G4APrime(), and theAPrime.
Referenced by biasing::EcalDarkBremFilter::ClassifyNewTrack(), simcore::darkbrem::DarkBremVertexLibraryModel::ComputeCrossSectionPerAtom(), simcore::darkbrem::APrimePhysics::ConstructParticle(), simcore::darkbrem::DarkBremVertexLibraryModel::DarkBremVertexLibraryModel(), simcore::darkbrem::DarkBremVertexLibraryModel::GenerateChange(), biasing::EcalDarkBremFilter::PostUserTrackingAction(), and biasing::TargetDarkBremFilter::stepping().
Member Data Documentation
theAPrime
G4APrime * simcore::darkbrem::G4APrime::theAPrime = 0 static private
Reference to single particle definition of A'
Definition at line 23 of file G4APrime.h.
Referenced by APrime().
The documentation for this class was generated from the following files:
SimCore/include/SimCore/DarkBrem/G4APrime.h
SimCore/src/SimCore/DarkBrem/G4APrime.cxx