LDMX Software: ldmx::TrackerID Class Reference
ldmx::TrackerID Class Reference
Extension of DetectorID providing access to layer and module number for tracker IDs.
#include <TrackerID.h>
Public Member Functions
TrackerID ()
TrackerID (const DetectorID id)
TrackerID (RawValue rawid)
TrackerID (SubdetectorIDType system, unsigned int layer, unsigned int module)
int module () const
int layer () const
Public Member Functions inherited from ldmx::DetectorID
DetectorID ()
Class constructor for a null DetectorID.
DetectorID (RawValue rawid)
Class constructor from a raw 32-bit integer.
DetectorID (SubdetectorIDType sdtype, RawValue raw_subpayload)
bool null () const
SubdetectorIDType subdet () const
RawValue raw () const
void setRawValue (RawValue rawValue)
bool operator< (const DetectorID &id) const
bool operator== (const DetectorID &id) const
bool operator!= (const DetectorID &id) const
Static Public Member Functions
static void createInterpreters ()
Static Public Attributes
static const RawValue LAYER_MASK {0xFF}
static const RawValue LAYER_SHIFT {0}
static const RawValue MODULE_MASK {0x1F}
static const RawValue MODULE_SHIFT {8}
Static Public Attributes inherited from ldmx::DetectorID
static const RawValue SUBDETECTORID_MASK {0x3F}
static const RawValue SUBDETECTORID_SHIFT {26}
static const RawValue SUBDETECTOR_PAYLOAD_MASK {0x3FFFFFF}
Additional Inherited Members
Public Types inherited from ldmx::DetectorID
typedef uint32_t RawValue
Protected Attributes inherited from ldmx::DetectorID
RawValue id_
The raw, packed value of the ID.
Detailed Description
Extension of DetectorID providing access to layer and module number for tracker IDs.
Definition at line 20 of file TrackerID.h.
Constructor & Destructor Documentation
TrackerID() [1/4]
ldmx::TrackerID::TrackerID () inline
Create a null TrackerID (not useful)
Definition at line 30 of file TrackerID.h.
{}
TrackerID() [2/4]
ldmx::TrackerID::TrackerID (const DetectorID id) inline
Create from a DetectorID, but check
Definition at line 35 of file TrackerID.h.
                                 : DetectorID(id) {
    SUBDETECTORID_TEST2("TrackerID", SD_TRACKER_TAGGER, SD_TRACKER_RECOIL);
  }
TrackerID() [3/4]
ldmx::TrackerID::TrackerID (RawValue rawid) inline
Create from a raw id, but check
Definition at line 42 of file TrackerID.h.
                            : DetectorID(rawid) {
    SUBDETECTORID_TEST2("TrackerID", SD_TRACKER_TAGGER, SD_TRACKER_RECOIL);
  }
TrackerID() [4/4]
ldmx::TrackerID::TrackerID (SubdetectorIDType system, unsigned int layer, unsigned int module) inline
Create from values
Definition at line 48 of file TrackerID.h.
      : DetectorID(system, 0) {
    id_ |= (layer & LAYER_MASK) << LAYER_SHIFT;
    id_ |= (module & MODULE_MASK) << MODULE_SHIFT;
  }
References ldmx::DetectorID::id_, layer(), and module().
Member Function Documentation
createInterpreters()
void ldmx::TrackerID::createInterpreters () static
Definition at line 19 of file TrackerID.cxx.
{
  IDField::IDFieldList fields;
  fields.push_back(new IDField("subdetector", 0, SUBDETECTORID_SHIFT, 31));
  fields.push_back(
      new IDField("layer", 1, LAYER_SHIFT,
                  LAYER_SHIFT + IDField::countOnes(LAYER_MASK) - 1));
  fields.push_back(
      new IDField("module", 2, MODULE_SHIFT,
                  MODULE_SHIFT + IDField::countOnes(MODULE_MASK) - 1));
  DetectorIDInterpreter::registerInterpreter(SD_TRACKER_TAGGER, fields);
  DetectorIDInterpreter::registerInterpreter(SD_TRACKER_RECOIL, fields);
}
layer()
int ldmx::TrackerID::layer () const inline
Get the value of the layer field from the ID.
Returns
The value of the layer field.
Definition at line 64 of file TrackerID.h.
{ return (id_ >> LAYER_SHIFT) & LAYER_MASK; }
References ldmx::DetectorID::id_.
Referenced by TEST_CASE(), and TrackerID().
module()
int ldmx::TrackerID::module () const inline
Get the value of the module field from the ID.
Returns
The value of the module field.
Definition at line 58 of file TrackerID.h.
{ return (id_ >> MODULE_SHIFT) & MODULE_MASK; }
References ldmx::DetectorID::id_.
Referenced by TEST_CASE(), and TrackerID().
Member Data Documentation
LAYER_MASK
const RawValue ldmx::TrackerID::LAYER_MASK {0xFF} static
Definition at line 22 of file TrackerID.h.
LAYER_SHIFT
const RawValue ldmx::TrackerID::LAYER_SHIFT {0} static
Definition at line 23 of file TrackerID.h.
MODULE_MASK
const RawValue ldmx::TrackerID::MODULE_MASK {0x1F} static
Definition at line 24 of file TrackerID.h.
MODULE_SHIFT
const RawValue ldmx::TrackerID::MODULE_SHIFT {8} static
Definition at line 25 of file TrackerID.h.
The documentation for this class was generated from the following files:
DetDescr/include/DetDescr/TrackerID.h
DetDescr/src/DetDescr/TrackerID.cxx