LDMX Software: simcore::HcalSD Class Reference
simcore::HcalSD Class Reference
#include <HcalSD.h>
Public Member Functions
HcalSD (const std::string &name, simcore::ConditionsInterface &ci, const framework::config::Parameters &params)
~HcalSD ()
Destructor.
bool isSensDet (G4LogicalVolume *volume) const final override
ldmx::HcalID decodeCopyNumber (const std::uint32_t copyNumber, const G4ThreeVector &localPosition, const G4Box *scint)
virtual G4bool ProcessHits (G4Step *aStep, G4TouchableHistory *ROhist) final override
virtual void saveHits (framework::Event &event) final override
virtual void EndOfEvent () final override
Public Member Functions inherited from simcore::SensitiveDetector
SensitiveDetector (const std::string &name, simcore::ConditionsInterface &ci, const framework::config::Parameters &parameters)
virtual ~SensitiveDetector ()
virtual bool isSensDet (G4LogicalVolume *lv) const =0
virtual G4bool ProcessHits (G4Step *step, G4TouchableHistory *hist)=0
virtual void saveHits (framework::Event &event)=0
virtual void EndOfEvent (G4HCofThisEvent *) final override
virtual void EndOfEvent ()=0
Static Public Attributes
static const std::string COLLECTION_NAME = "HcalSimHits"
name of collection to be added to event bus
Private Attributes
std::vector< std::string > gdmlIdentifiers_
double birksc1_
double birksc2_
std::vector< ldmx::SimCalorimeterHit > hits_
Additional Inherited Members
Public Types inherited from simcore::SensitiveDetector
using Factory = ::simcore::Factory< SensitiveDetector, SensitiveDetector *, const std::string &, simcore::ConditionsInterface &, const framework::config::Parameters & >
Protected Member Functions inherited from simcore::SensitiveDetector
template<class T >
const T & getCondition (const std::string &condition_name)
bool isGeantino (const G4Step *step) const
const TrackMap & getTrackMap () const
Detailed Description
Class defining a sensitive detector of type HCal.
Definition at line 24 of file HcalSD.h.
Constructor & Destructor Documentation
HcalSD()
simcore::HcalSD::HcalSD (const std::string & name, simcore::ConditionsInterface & ci, const framework::config::Parameters & params)
Constructor
Parameters
name The name of the sensitive detector.
ci Conditions interface handle
params python configuration parameters
Definition at line 22 of file HcalSD.cxx.
    : SensitiveDetector(name, ci, p), birksc1_(1.29e-2), birksc2_(9.59e-6) {
  gdmlIdentifiers_ = {
      p.getParameter<std::vector<std::string>>("gdml_identifiers")};
}
References framework::config::Parameters::getParameter().
~HcalSD()
simcore::HcalSD::~HcalSD ()
Destructor.
Definition at line 29 of file HcalSD.cxx.
{}
Member Function Documentation
decodeCopyNumber()
ldmx::HcalID simcore::HcalSD::decodeCopyNumber (const std::uint32_t copyNumber, const G4ThreeVector & localPosition, const G4Box * scint)
Decode copy number of scintillator bar.
Parameters
copyNumber The copy number of the scintillator volume.
localPosition The position of the hit (step mid-point).
scint The G4Box of the scintillator volume.
Definition at line 31 of file HcalSD.cxx.
{
  const unsigned int version{copyNumber / 0x01000000};
  if (version != 0) {
    typedef ldmx::PackedIndex<256, 256, 256> Index;
    return ldmx::HcalID{Index(copyNumber).field2(), Index(copyNumber).field1(), Index(copyNumber).field0()};
  } else {
    const auto& geometry = getCondition<ldmx::HcalGeometry>(
                                ldmx::HcalGeometry::CONDITIONS_OBJECT_NAME);
    unsigned int stripID = 0;
    const unsigned int section = copyNumber / 1000;
    const unsigned int layer = copyNumber % 1000;
    // 5cm wide bars are HARD-CODED
    if (section == ldmx::HcalID::BACK) {
      if (geometry.layerIsHorizontal(layer)) {
        stripID = int((localPosition.y() + scint->GetYHalfLength()) / 50.0);
      } else {
        stripID = int((localPosition.x() + scint->GetXHalfLength()) / 50.0);
      }
    } else {
      stripID = int((localPosition.z() + scint->GetZHalfLength()) / 50.0);
    }
    return ldmx::HcalID{section, layer, stripID};
  }
}
References ldmx::HcalGeometry::CONDITIONS_OBJECT_NAME.
Referenced by ProcessHits().
EndOfEvent()
virtual void simcore::HcalSD::EndOfEvent () inline final override virtual
Cleanup SD and prepare a new-event state
Implements simcore::SensitiveDetector.
Definition at line 91 of file HcalSD.h.
{ hits_.clear(); }
isSensDet()
bool simcore::HcalSD::isSensDet (G4LogicalVolume * volume) const inline final override virtual
Check if the input logical volume is a part of the hcal sensitive volumes.
Note
This will match if a) the volume has the auxiliary tag "Region" set to contain to "CalorimeterRegion" and b) the volume name contains one of the identifiers in the gdml_identifiers parameter
Implements simcore::SensitiveDetector.
Definition at line 50 of file HcalSD.h.
{
    auto region = volume->GetRegion();
    if (region and region->GetName().contains("CalorimeterRegion")) {
      const auto name{volume->GetName()};
      return std::find_if(std::begin(gdmlIdentifiers_),
                          std::end(gdmlIdentifiers_),
                          [&name](const auto& identifier) {
                            return name.contains(identifier);
                          }) != std::end(gdmlIdentifiers_);
    }
    return false;
  }
ProcessHits()
G4bool simcore::HcalSD::ProcessHits (G4Step * aStep, G4TouchableHistory * ROhist) final override virtual
Create a hit out of the energy deposition deposited during a step.
Parameters
[in] step The current step.
[in] history The readout history.
topTransform translates to the local bar but does not do the rotation (this is because we don't do a rotation when placing the bars in the GDML)
the logic below does the rotation to the local coordiates where x : short transverse side of bar y : long transverse side of bar z : along length of bar
a lot of this logic could (and should) probably be moved into the geometry condition for the HCal so that it is more easily maintainable
Note
This logic only applies to the v14 and prototype detector; however, support for v12 is not broken because no studies using these pre/post step positions have been (or should be) done with the v12 detector.
Implements simcore::SensitiveDetector.
Definition at line 59 of file HcalSD.cxx.
{
  // Get the edep from the step.
  G4double edep = aStep->GetTotalEnergyDeposit();
  // Skip steps with no energy dep which come from non-Geantino particles.
  if (edep == 0.0 and not isGeantino(aStep)) {
    if (verboseLevel > 2) {
      std::cout << "CalorimeterSD skipping step with zero edep." << std::endl
                << std::endl;
    }
    return false;
  }
  //---------------------------------------------------------------------------------------------------
  //                Birks' Law
  //                ===========
  //
  //                      In the case of Scintillator as active medium, we can
  //              describe the quenching effects with the Birks' law,
  //              using the expression and the coefficients taken from
  //              the paper NIM 80 (1970) 239-244 for the organic
  //              scintillator NE-102:
  //                                     S*dE/dr
  //                    dL/dr = -----------------------------------
  //                               1 + C1*(dE/dr)
  //              with:
  //                    S=1
  //                    C1 = 1.29 x 10^-2  g*cm^-2*MeV^-1
  //                    C2 = 9.59 x 10^-6  g^2*cm^-4*MeV^-2
  //              These are the same values used by ATLAS TileCal
  //              and CMS HCAL (and also the default in Geant3).
  //              You can try different values for these parameters,
  //              to have an idea on the uncertainties due to them,
  //              by uncommenting one of the lines below.
  //              To get the "dE/dr" that appears in the formula,
  //              which has the dimensions
  //                    [ dE/dr ] = MeV * cm^2 / g
  //              we have to divide the energy deposit in MeV by the
  //              product of the step length (in cm) and the density
  //              of the scintillator:
  G4double birksFactor(1.0);
  G4double stepLength = aStep->GetStepLength() / CLHEP::cm;
  // Do not apply Birks for gamma deposits!
  if (stepLength > 1.0e-6)  // Check, cut if necessary.
  {
    G4double rho = aStep->GetPreStepPoint()->GetMaterial()->GetDensity() /
                   (CLHEP::g / CLHEP::cm3);
    G4double dedx = edep / (rho * stepLength);  //[MeV*cm^2/g]
    birksFactor = 1.0 / (1.0 + birksc1_ * dedx + birksc2_ * dedx * dedx);
    if (aStep->GetTrack()->GetDefinition() == G4Gamma::GammaDefinition())
      birksFactor = 1.0;
    if (aStep->GetTrack()->GetDefinition() == G4Neutron::NeutronDefinition())
      birksFactor = 1.0;
  }
  // update edep to include birksFactor
  edep *= birksFactor;
  // Create a new cal hit.
  ldmx::SimCalorimeterHit& hit{hits_.emplace_back()};
  // Get the scintillator solid box
  G4Box* scint = static_cast<G4Box*>(aStep->GetPreStepPoint()
                                         ->GetTouchableHandle()
                                         ->GetVolume()
                                         ->GetLogicalVolume()
                                         ->GetSolid());
  // Set the step mid-point as the hit position.
  G4StepPoint* prePoint = aStep->GetPreStepPoint();
  G4StepPoint* postPoint = aStep->GetPostStepPoint();
  // A Geant4 "touchable" is a way to uniquely identify a particular volume,
  // short for touchable detector element. See the detector definition and
  // response section of the Geant4 application developers manual for details.
  //
  // The TouchableHandle is just a reference counted pointer to a
  // G4TouchableHistory object, which is a concrete implementation of a
  // G4Touchable interface.
  //
  auto touchableHistory{prePoint->GetTouchableHandle()->GetHistory()};
  // Affine transform for converting between local and global coordinates
  auto topTransform{touchableHistory->GetTopTransform()};
  G4ThreeVector position =
      0.5 * (prePoint->GetPosition() + postPoint->GetPosition());
  G4ThreeVector localPosition = topTransform.TransformPoint(position);
  hit.setPosition(position[0], position[1], position[2]);
  // Create the ID for the hit. Note 2 here corresponds to the "depth" of the
  // geometry tree. If this changes in the GDML, this would have to be updated
  // here. Currently, 0 corresponds to the world volume, 1 corresponds to the
  // Hcal, and 2 to the bars/absorbers
  int copyNum = touchableHistory->GetVolume(2)->GetCopyNo();
  ldmx::HcalID id = decodeCopyNumber(copyNum, localPosition, scint);
  hit.setID(id.raw());
  // add one contributor for this hit with
  //  ID of ancestor incident on Cal-Region
  //  ID of this track
  //  PDG of this track
  //  EDEP (including birks factor)
  //  time of this hit
  const G4Track* track = aStep->GetTrack();
  int track_id = track->GetTrackID();
  hit.addContrib(getTrackMap().findIncident(track_id), track_id,
                 track->GetParticleDefinition()->GetPDGEncoding(),
                 edep, track->GetGlobalTime());
  //
  // Pre/post step details for scintillator response simulation
  // Convert back to mm
  hit.setPathLength(stepLength * CLHEP::cm / CLHEP::mm);
  hit.setVelocity(track->GetVelocity());
  // Convert pre/post step position from global coordinates to coordinates within the
  // scintillator bar
  const auto localPreStepPoint{topTransform.TransformPoint(prePoint->GetPosition())};
  const auto localPostStepPoint{topTransform.TransformPoint(postPoint->GetPosition())};
  const auto& geometry = getCondition<ldmx::HcalGeometry>(
      ldmx::HcalGeometry::CONDITIONS_OBJECT_NAME);
  switch (id.getSection()) {
    case ldmx::HcalID::BACK   :
      if (geometry.layerIsHorizontal(id.layer())) {
        hit.setPreStepPosition(localPreStepPoint[2], localPreStepPoint[1], localPreStepPoint[0]);
        hit.setPostStepPosition(localPostStepPoint[2], localPostStepPoint[1], localPostStepPoint[0]);
      } else {
        hit.setPreStepPosition(localPreStepPoint[2], localPreStepPoint[0], localPreStepPoint[1]);
        hit.setPostStepPosition(localPostStepPoint[2], localPostStepPoint[0], localPostStepPoint[1]);
      }
      break;
    case ldmx::HcalID::TOP    :
    case ldmx::HcalID::BOTTOM :
      if (id.layer() % 2 == 0) {
        hit.setPreStepPosition(localPreStepPoint[1], localPreStepPoint[2], localPreStepPoint[0]);
        hit.setPostStepPosition(localPostStepPoint[1], localPostStepPoint[2], localPostStepPoint[0]);
      } else {
        hit.setPreStepPosition(localPreStepPoint[1], localPreStepPoint[0], localPreStepPoint[2]);
        hit.setPostStepPosition(localPostStepPoint[1], localPostStepPoint[0], localPostStepPoint[2]);
      }
      break;
    case ldmx::HcalID::RIGHT  :
    case ldmx::HcalID::LEFT   :
      if (id.layer() % 2 == 0) {
        hit.setPreStepPosition(localPreStepPoint[0], localPreStepPoint[2], localPreStepPoint[1]);
        hit.setPostStepPosition(localPostStepPoint[0], localPostStepPoint[2], localPostStepPoint[1]);
      } else {
        hit.setPreStepPosition(localPreStepPoint[0], localPreStepPoint[1], localPreStepPoint[2]);
        hit.setPostStepPosition(localPostStepPoint[0], localPostStepPoint[1], localPostStepPoint[2]);
      }
      break;
    default :
      EXCEPTION_RAISE("HcalSDHit","Found an unknown HCal section");
  }
  hit.setPreStepTime(prePoint->GetGlobalTime());
  hit.setPostStepTime(postPoint->GetGlobalTime());
  // do we want to set the hit coordinate in the middle of the absorber?
  // G4ThreeVector volumePosition =
  // aStep->GetPreStepPoint()->GetTouchableHandle()->GetHistory()->GetTopTransform().Inverse().TransformPoint(G4ThreeVector());
  // if (section==ldmx::HcalID::BACK) hit->setPosition(position[0], position[1],
  // volumePosition.z()); elseif (section==ldmx::HcalID::TOP ||
  // section==ldmx::HcalID::BOTTOM) hit->setPosition(position[0], volumePosition.y(),
  // position[2]); elseif (section==ldmx::HcalID::LEFT || section==ldmx::HcalID::RIGHT)
  // hit->setPosition(volumePosition.x(),position[1] , position[2]);
  if (this->verboseLevel > 2) { hit.Print(); }
  return true;
}
References ldmx::HcalGeometry::CONDITIONS_OBJECT_NAME, decodeCopyNumber(), simcore::SensitiveDetector::getTrackMap(), and simcore::SensitiveDetector::isGeantino().
saveHits()
virtual void simcore::HcalSD::saveHits (framework::Event & event) inline final override virtual
Add our hits to the event bus and then reset the container
Implements simcore::SensitiveDetector.
Definition at line 87 of file HcalSD.h.
{
    event.add(COLLECTION_NAME, hits_);
  }
References COLLECTION_NAME.
Member Data Documentation
birksc1_
double simcore::HcalSD::birksc1_ private
Definition at line 101 of file HcalSD.h.
birksc2_
double simcore::HcalSD::birksc2_ private
Definition at line 104 of file HcalSD.h.
COLLECTION_NAME
const std::string simcore::HcalSD::COLLECTION_NAME = "HcalSimHits" static
name of collection to be added to event bus
Definition at line 27 of file HcalSD.h.
Referenced by saveHits().
gdmlIdentifiers_
std::vector<std::string> simcore::HcalSD::gdmlIdentifiers_ private
Definition at line 99 of file HcalSD.h.
hits_
std::vector<ldmx::SimCalorimeterHit> simcore::HcalSD::hits_ private
Definition at line 107 of file HcalSD.h.
The documentation for this class was generated from the following files:
SimCore/include/SimCore/SDs/HcalSD.h
SimCore/src/SimCore/SDs/HcalSD.cxx