LDMX Software: Framework/test/FunctionalCoreTest.cxx File Reference
FunctionalCoreTest.cxx File Reference
Test the operation of Framework processing.
#include "Exception/catch.hpp"
#include <cstdio>
#include "TH1F.h"
#include "TFile.h"
#include "TTreeReader.h"
#include "Event/EventDef.h"
#include "Framework/Process.h"
#include "Framework/EventProcessor.h"
#include "Framework/EventFile.h"
Classes
class ldmx::test::TestProducer
class ldmx::test::TestAnalyzer
class ldmx::test::isGoodHistogramFile
class ldmx::test::isGoodEventFile
Namespaces
ldmx
All classes in the ldmx-sw project use this namespace.
Functions
static bool ldmx::test::removeFile (const char *filepath)
TEST_CASE ("Core Framework Functionality", "[Framework][functionality]")
Detailed Description
Test the operation of Framework processing.
Author
Tom Eichlersmith, University of Minnesota
Definition in file FunctionalCoreTest.cxx.
Function Documentation
removeFile()
static bool ldmx::test::removeFile (const char * filepath) static
@func removeFile Deletes the file and returns whether the deletion was successful.
This is just a helper function during development. Sometimes it is helpful to leave the generated files, so maybe we can make the removal optional?
Definition at line 347 of file FunctionalCoreTest.cxx.
{
     return remove( filepath ) == 0;
 }
References ldmx::test::removeFile().
Referenced by ldmx::test::removeFile().
TEST_CASE()
TEST_CASE ("Core Framework Functionality" , "" [Framework][functionality])
Test for C++ Framework processing.
This test is aimed at checking that core functionalities are operational. Python configuration, Simulation, and other add-on functionalities are tested separately.
This test does not check complicated combinations for drop/keep rules and skimming rules. I (Tom E) avoided this because this test is already very large and complicated. TODO write a more full (and separate) test for these parts of the framework.
Assumptions:
Any vector of objects behaves like a vector of CalorimeterHits when viewed from core
Any object behaves like a HcalVetoResult when viewed from core
What does this even test?
Event::add an object and a vector of objects (changing size and content)
Event::get an object and a vector of objects (changing size and content)
Event can switch to different input tree (Multiple Input Files)
Creating and filling a histogram
Reading from input file(s)
Production Mode (no input files)
Analysis Mode (no output event files, only output histogram file)
Merge Mode (several input files to one output file)
N-to-N Mode (several input files to several output files)
writing histogram to a file
writing to an output file
writing and reading run headers
drop/keep rules for event bus passengers
skimming events (only keeping events meeting a certain criteria)
Definition at line 385 of file FunctionalCoreTest.cxx.
{
     using namespace ldmx;
     Process p("test");
     REQUIRE( p.getPassName() == "test" );
     //Process owns and deletes the processors
     auto proHdl = new test::TestProducer( p );
     auto anaHdl = new test::TestAnalyzer( p );
     SECTION( "Production Mode" ) {
         //no input files, only output files
         const char *event_file_path = "test_productionmode_events.root";
         p.setOutputFileName( event_file_path );
         p.setEventLimit( 3 );
         p.addToSequence( proHdl );
         proHdl->shouldMakeRunHeader( true );
         p.setRunNumber( 3 );
         SECTION( "only producers" ) {
             SECTION( "no drop/keep rules" ) {
                 p.run();
                 CHECK_THAT( event_file_path , test::isGoodEventFile( "test" , 3 , 1 ) );
             }
             SECTION( "drop TestCollection" ) {
                 p.addDropKeepRule( "drop .*Collection.*" );
                 p.run();
                 CHECK_THAT( event_file_path , test::isGoodEventFile( "test" , 3 , 1 , false ) );
             }
             SECTION( "skim for even indexed events" ) {
                 p.getStorageController().setDefaultKeep( false );
                 p.getStorageController().addRule( "TestProducer" , "" );
                 p.run();
                 CHECK_THAT( event_file_path , test::isGoodEventFile( "test" , 1 , 1 ) );
             }
         }
         SECTION( "with Analyses" ) {
             const char *hist_file_path = "test_productionmode_withanalyses_hists.root";
             p.setHistogramFileName( hist_file_path );
             p.addToSequence( anaHdl );
             SECTION( "no drop/keep rules" ) {
                 p.run();
                 CHECK_THAT( event_file_path , test::isGoodEventFile( "test" , 3 , 1 ) );
             }
             SECTION( "drop TestCollection" ) {
                 p.addDropKeepRule( "drop .*Collection.*" );
                 p.run();
                 CHECK_THAT( event_file_path , test::isGoodEventFile( "test" , 3 , 1 , false ) );
             }
             SECTION( "skim for even indexed events" ) {
                 p.getStorageController().setDefaultKeep( false );
                 p.getStorageController().addRule( "TestProducer" , "" );
                 p.run();
                 CHECK_THAT( event_file_path , test::isGoodEventFile( "test" , 1 , 1 ) );
             }
             CHECK_THAT( hist_file_path , test::isGoodHistogramFile( 1+2+3 ) );
             CHECK( test::removeFile( hist_file_path ) );
         }
         CHECK( test::removeFile( event_file_path ) );
     }//Production Mode
     SECTION( "Need Input Files" ) {
         Process makeInputs( "makeInputs" );
         auto inputProHdl = new test::TestProducer( makeInputs );
         makeInputs.addToSequence( inputProHdl );
         inputProHdl->shouldMakeRunHeader( true );
         const char * input_file_2_events = "test_needinputfiles_2_events.root";
         makeInputs.setOutputFileName( input_file_2_events );
         makeInputs.setEventLimit( 2 );
         makeInputs.setRunNumber( 2 );
         REQUIRE_NOTHROW( makeInputs.run() );
         REQUIRE_THAT( input_file_2_events , test::isGoodEventFile( "makeInputs" , 2 , 1) );
         const char * input_file_3_events = "test_needinputfiles_3_events.root";
         makeInputs.setOutputFileName( input_file_3_events );
         makeInputs.setEventLimit( 3 );
         makeInputs.setRunNumber( 3 );
         REQUIRE_NOTHROW( makeInputs.run() );
         REQUIRE_THAT( input_file_3_events , test::isGoodEventFile( "makeInputs" , 3 , 1) );
         const char * input_file_4_events = "test_needinputfiles_4_events.root";
         makeInputs.setOutputFileName( input_file_4_events );
         makeInputs.setEventLimit( 4 );
         makeInputs.setRunNumber( 4 );
         REQUIRE_NOTHROW( makeInputs.run() );
         REQUIRE_THAT( input_file_4_events , test::isGoodEventFile( "makeInputs" , 4 , 1) );
         SECTION( "Analysis Mode" ) {
             //no output files, only histogram output
             p.addToSequence( anaHdl );
             const char *hist_file_path = "test_analysismode_hists.root";
             p.setHistogramFileName( hist_file_path );
             SECTION( "one input file" ) {
                 p.addFileToProcess( input_file_2_events );
                 p.run();
                 CHECK_THAT( hist_file_path , test::isGoodHistogramFile( 1+2 ) );
                 CHECK( test::removeFile( hist_file_path ) );
             }
             SECTION( "multiple input files" ) {
                 p.addFileToProcess( input_file_2_events );
                 p.addFileToProcess( input_file_3_events );
                 p.addFileToProcess( input_file_4_events );
                 p.run();
                 CHECK_THAT( hist_file_path , test::isGoodHistogramFile( 1+2+1+2+3+1+2+3+4 ) );
                 CHECK( test::removeFile( hist_file_path ) );
             }
         }//Analysis Mode
         SECTION( "Merge Mode" ) {
             //many input files to one output file
             p.addFileToProcess( input_file_2_events );
             p.addFileToProcess( input_file_3_events );
             p.addFileToProcess( input_file_4_events );
             const char *event_file_path = "test_mergemode_events.root";
             p.setOutputFileName( event_file_path );
             SECTION( "no processors" ) {
                 SECTION( "no drop/keep rules" ) {
                     p.run();
                     CHECK_THAT( event_file_path , test::isGoodEventFile( "makeInputs" , 2+3+4 , 3 ) );
                 }
                 SECTION( "drop TestCollection" ) {
                     p.addDropKeepRule( "drop .*Collection.*" );
                     p.run();
                     CHECK_THAT( event_file_path , test::isGoodEventFile( "makeInputs" , 2+3+4 , 3 , false ) );
                 }
             }
             SECTION( "with analyzers" ) {
                 p.addToSequence( anaHdl );
                 const char *hist_file_path = "test_mergemode_withanalyzers_hists.root";
                 p.setHistogramFileName( hist_file_path );
                 SECTION( "no drop/keep rules" ) {
                     p.run();
                     CHECK_THAT( event_file_path , test::isGoodEventFile( "makeInputs" , 2+3+4 , 3 ) );
                 }
                 SECTION( "drop TestCollection" ) {
                     p.addDropKeepRule( "drop .*Collection.*" );
                     p.run();
                     CHECK_THAT( event_file_path , test::isGoodEventFile( "makeInputs" , 2+3+4 , 3 , false ) );
                 }
                 CHECK_THAT( hist_file_path , test::isGoodHistogramFile( 1+2+1+2+3+1+2+3+4 ) );
                 CHECK( test::removeFile( hist_file_path ) );
             }
             SECTION( "with producers" ) {
                 p.addToSequence( proHdl );
                 SECTION( "not listening to storage hints" ) {
                     p.run();
                     CHECK_THAT( event_file_path , test::isGoodEventFile( "test" , 2+3+4 , 3 ) );
                 }
                 SECTION( "skim for even indexed events" ) {
                     p.getStorageController().setDefaultKeep( false );
                     p.getStorageController().addRule( "TestProducer" , "" );
                     p.run();
                     CHECK_THAT( event_file_path , test::isGoodEventFile( "test" , 1+1+2 , 3 ) );
                 }
             }
             CHECK( test::removeFile( event_file_path ) );
         } //Merge Mode
         SECTION( "N-to-N Mode" ) {
             //many input files to many output files
             p.addFileToProcess( input_file_2_events );
             p.addFileToProcess( input_file_3_events );
             p.addFileToProcess( input_file_4_events );
             const char * output_2_events = "test_NtoNmode_output_2_events.root";
             const char * output_3_events = "test_NtoNmode_output_3_events.root";
             const char * output_4_events = "test_NtoNmode_output_4_events.root";
             p.addOutputFileName( output_2_events );
             p.addOutputFileName( output_3_events );
             p.addOutputFileName( output_4_events );
             SECTION( "no processors" ) {
                 SECTION( "no drop/keep rules" ) {
                     p.run();
                     CHECK_THAT( output_2_events , test::isGoodEventFile( "makeInputs" , 2 , 1 ) );
                     CHECK_THAT( output_3_events , test::isGoodEventFile( "makeInputs" , 3 , 1 ) );
                     CHECK_THAT( output_4_events , test::isGoodEventFile( "makeInputs" , 4 , 1 ) );
                 }
                 SECTION( "drop TestCollection" ) {
                     p.addDropKeepRule( "drop .*Collection.*" );
                     p.run();
                     CHECK_THAT( output_2_events , test::isGoodEventFile( "makeInputs" , 2 , 1 , false ) );
                     CHECK_THAT( output_3_events , test::isGoodEventFile( "makeInputs" , 3 , 1 , false ) );
                     CHECK_THAT( output_4_events , test::isGoodEventFile( "makeInputs" , 4 , 1 , false ) );
                 }
             }
             SECTION( "with analyzer" ) {
                 p.addToSequence( anaHdl );
                 const char *hist_file_path = "test_NtoNmode_withanalyzer_hists.root";
                 p.setHistogramFileName( hist_file_path );
                 SECTION( "no drop/keep rules" ) {
                     p.run();
                     CHECK_THAT( output_2_events , test::isGoodEventFile( "makeInputs" , 2 , 1 ) );
                     CHECK_THAT( output_3_events , test::isGoodEventFile( "makeInputs" , 3 , 1 ) );
                     CHECK_THAT( output_4_events , test::isGoodEventFile( "makeInputs" , 4 , 1 ) );
                 }
                 SECTION( "drop TestCollection" ) {
                     p.addDropKeepRule( "drop .*Collection.*" );
                     p.run();
                     CHECK_THAT( output_2_events , test::isGoodEventFile( "makeInputs" , 2 , 1 , false ) );
                     CHECK_THAT( output_3_events , test::isGoodEventFile( "makeInputs" , 3 , 1 , false ) );
                     CHECK_THAT( output_4_events , test::isGoodEventFile( "makeInputs" , 4 , 1 , false ) );
                 }
                 CHECK_THAT( hist_file_path , test::isGoodHistogramFile( 1+2+1+2+3+1+2+3+4 ) );
                 CHECK( test::removeFile( hist_file_path ) );
             }
             SECTION( "with producers" ) {
                 p.addToSequence( proHdl );
                 SECTION( "not listening to storage hints" ) {
                     p.run();
                     //checks that produced objects were written correctly
                     CHECK_THAT( output_2_events , test::isGoodEventFile( "test" , 2 , 1 ) );
                     CHECK_THAT( output_3_events , test::isGoodEventFile( "test" , 3 , 1 ) );
                     CHECK_THAT( output_4_events , test::isGoodEventFile( "test" , 4 , 1 ) );
                 }
                 SECTION( "skimming for even-indexed events" ) {
                     p.getStorageController().setDefaultKeep( false );
                     p.getStorageController().addRule( "TestProducer" , "" );
                     p.run();
                     CHECK_THAT( output_2_events , test::isGoodEventFile( "test" , 1 , 1 ) );
                     CHECK_THAT( output_3_events , test::isGoodEventFile( "test" , 1 , 1 ) );
                     CHECK_THAT( output_4_events , test::isGoodEventFile( "test" , 2 , 1 ) );
                 }
             }
             CHECK( test::removeFile( output_2_events ) );
             CHECK( test::removeFile( output_3_events ) );
             CHECK( test::removeFile( output_4_events ) );
         } // N-to-N Mode
         //cleanup
         CHECK( test::removeFile( input_file_2_events ) );
         CHECK( test::removeFile( input_file_3_events ) );
         CHECK( test::removeFile( input_file_4_events ) );
     } //need input files
 }//process test
References ldmx::Process::addDropKeepRule(), ldmx::Process::addFileToProcess(), ldmx::Process::addOutputFileName(), ldmx::StorageControl::addRule(), ldmx::Process::addToSequence(), ldmx::Process::getPassName(), ldmx::Process::getStorageController(), ldmx::Process::run(), ldmx::StorageControl::setDefaultKeep(), ldmx::Process::setEventLimit(), ldmx::Process::setHistogramFileName(), ldmx::Process::setOutputFileName(), and ldmx::Process::setRunNumber().