LDMX Software: Recon/include/Recon/Event/HgcrocDigiCollection.h File Reference
HgcrocDigiCollection.h File Reference
Class that represents a digitized hit in a calorimeter cell readout by an HGCROC.
#include "TObject.h"
#include <stdint.h>
#include <iostream>
#include <vector>
Classes
class ldmx::HgcrocDigiCollection
Represents a collection of the digi hits readout by an HGCROC.
class ldmx::HgcrocDigiCollection::Sample
One sample of a digi channel corresponding to one clock of the HGCROC chip.
class ldmx::HgcrocDigiCollection::HgcrocDigi
class ldmx::HgcrocDigiCollection::iterator
Functions
std::ostream & operator<< (std::ostream &s, const ldmx::HgcrocDigiCollection::Sample &sample)
std::ostream & operator<< (std::ostream &s, const ldmx::HgcrocDigiCollection::HgcrocDigi &digi)
std::ostream & operator<< (std::ostream &s, const ldmx::HgcrocDigiCollection &col)
Detailed Description
Class that represents a digitized hit in a calorimeter cell readout by an HGCROC.
Author
Cameron Bravo, SLAC National Accelerator Laboratory
Tom Eichlersmith, University of Minnesota
Definition in file HgcrocDigiCollection.h.
Function Documentation
operator<<() [1/3]
std::ostream & operator<< (std::ostream & s, const ldmx::HgcrocDigiCollection & col)
Streamer for HgcrocDigiCollection
Prints all of the digi's using their streamer.
Parameters
[in] s ostream to print sample to
[in] col HgcrocDigiCollection to print
Returns
modified ostream
Definition at line 133 of file HgcrocDigiCollection.cxx.
{
  s << "HgcrocDigiCollection { " << std::endl;
  for (unsigned int iDigi = 0; iDigi < col.getNumDigis(); iDigi++)
    s << "  " << col.getDigi(iDigi) << std::endl;
  s << "}";
  return s;
}
References ldmx::HgcrocDigiCollection::getDigi(), and ldmx::HgcrocDigiCollection::getNumDigis().
operator<<() [2/3]
std::ostream & operator<< (std::ostream & s, const ldmx::HgcrocDigiCollection::HgcrocDigi & digi)
Streamer for HgcrocDigiCollection::HgcrocDigi
Prints TOT measurement (if it was TOT) or SOI otherwise
Parameters
[in] s ostream to print sample to
[in] digi HgcrocDigi to print
Returns
modified ostream
Definition at line 119 of file HgcrocDigiCollection.cxx.
{
  s << "HgcrocDigi { ";
  s << " Id: 0x" << std::hex << digi.id() << std::dec << " ";
  if (digi.isADC())
    s << "ADC Mode -> SOI: " << digi.soi() << " }";
  else
    s << "TOT Mode -> " << digi.tot() << " }";
  return s;
}
References ldmx::HgcrocDigiCollection::HgcrocDigi::id(), ldmx::HgcrocDigiCollection::HgcrocDigi::isADC(), ldmx::HgcrocDigiCollection::HgcrocDigi::soi(), and ldmx::HgcrocDigiCollection::HgcrocDigi::tot().
operator<<() [3/3]
std::ostream & operator<< (std::ostream & s, const ldmx::HgcrocDigiCollection::Sample & sample)
Streamer for the HgcrocDigiCollection::Sample
Prints Flags and three ten bit measurements.
Parameters
[in] s ostream to print sample to
[in] sample Sample to print
Returns
modified ostream
Definition at line 100 of file HgcrocDigiCollection.cxx.
{
  s << "Sample { "
    << "tot prog: " << sample.isTOTinProgress() << ", "
    << "tot comp: " << sample.isTOTComplete() << ", ";
  if (sample.isTOTComplete() and sample.isTOTinProgress())
    s << "adc t: " << sample.adc_t() << ", "
      << "tot: " << sample.tot() << ", ";
  else if (sample.isTOTComplete())
    s << "adc t-1: " << sample.adc_tm1() << ", "
      << "tot: " << sample.tot() << ", ";
  else
    s << "adc t-1: " << sample.adc_tm1() << ", "
      << "adc t: " << sample.adc_t() << ", ";
  s << "toa: " << sample.toa() << " }";
  return s;
}
References ldmx::HgcrocDigiCollection::Sample::adc_t(), ldmx::HgcrocDigiCollection::Sample::adc_tm1(), ldmx::HgcrocDigiCollection::Sample::isTOTComplete(), ldmx::HgcrocDigiCollection::Sample::isTOTinProgress(), ldmx::HgcrocDigiCollection::Sample::toa(), and ldmx::HgcrocDigiCollection::Sample::tot().