LDMX Software: g4db Namespace Reference
g4db Namespace Reference
Namespaces
namespace example
namespace parse
Classes
class ElementXsecCache
class ElementXsecInterpolation
class G4DarkBreMModel
struct OutgoingKinematics
class PrototypeModel
Functions
void parseLibrary (const std::string &path, int aprime_lhe_id, std::map< int, std::map< double, std::vector< OutgoingKinematics > > > &lib)
void dumpLibrary (std::ostream &o, const std::map< int, std::map< double, std::vector< OutgoingKinematics > > > &lib)
template<typename IntegrandFunction >
static double integrate (IntegrandFunction F, double low, double high)
static double flux_factor_chi_numerical (G4double A, G4double Z, double tmin, double tmax)
bool hasEnding (const std::string &str, const std::string &end)
Detailed Description
G4DarkBreM internal namespace
Function Documentation
dumpLibrary()
void g4db::dumpLibrary (std::ostream & o, const std::map< int, std::map< double, std::vector< OutgoingKinematics > > > & lib)
Dump the input library to the input output stream
Note
This is only helpful for our extraction executable and for testing that the parsing is performing correctly.
Parameters
[in,out] o output stream to write CSV to
[in] lib library to write out
This function writes out the input library as CSV to the input output stream in the same format as expected by parse::csv.
This function writes out the input library as CSV to the input output stream in the same format as expected by parse::csv.
Definition at line 246 of file ParseLibrary.cxx.
{
  o << "target_Z,incident_energy,recoil_energy,recoil_px,recoil_py,recoil_pz,"
         "centerMomentum_energy,centerMomentum_px,centerMomentum_py,centerMomentum_pz\n";
  for (const auto& Z_submap : lib) {
    for (const auto& beam_events : Z_submap.second) {
      for (const auto& sample : beam_events.second) {
        o << Z_submap.first << ','
          << sample.E << ','
          << sample.lepton.e() << ','
          << sample.lepton.px() << ','
          << sample.lepton.py() << ','
          << sample.lepton.pz() << ','
          << sample.centerMomentum.e() << ','
          << sample.centerMomentum.px() << ','
          << sample.centerMomentum.py() << ','
          << sample.centerMomentum.pz() << '\n';
      }
    }
  }
  o.flush();
}
flux_factor_chi_numerical()
static double g4db::flux_factor_chi_numerical (G4double A, G4double Z, double tmin, double tmax) static
numerically integrate the value of the flux factor chi
The integration of the form factor into the flux factor can be done analytically with a tool like mathematica, but when including the inelastic term, it produces such a complicated result that the numerical integration is actually faster than the analytical one.
The form factors are copied from Appendix A (Eq A18 and A19) of https://journals.aps.org/prd/pdf/10.1103/PhysRevD.80.075018
Here, the equations are listed for reference.
where
is the mass of the electron in GeV
is the mass of the proton in GeV
is the proton
is the atomic mass of the target nucleus in amu
is the atomic number of the target nucleus
Parameters
[in] A atomic mass of the target nucleus in amu
[in] Z atomic number of target nucleus
[in] tmin lower limit of integration over t
[in] tmax upper limit of integration over t
We've manually expanded the integrand to cancel out the 1/t^2 factor from the differential, this helps the numerical integration converge because we aren't teetering on the edge of division by zero
The auto used in the integrand definition represents a function whose return value is a double and which has a single input lnt. This lambda expression saves us the time of having to re-calculate the form factor constants that do not depend on t because it can inherit their values from the environment. The return value is a double since it is calculated by simple arithmetic operations on doubles.
The integrand is so sharply peaked at t close to tmin, it is very helpful to do the integration in the variable u = ln(t) rather than t itself.
Definition at line 94 of file G4DarkBreMModel.cxx.
{
  /*
   * bin = (mu_p^2 - 1)/(4 m_pr^2)
   * mel = mass of electron in GeV
   */
  static const double bin = (2.79*2.79 - 1)/(4*0.938*0.938),
                      mel = 0.000511;
  const double ael = 111.0*pow(Z,-1./3.)/mel,
               del = 0.164*pow(A,-2./3.),
               ain = 773.0*pow(Z,-2./3.)/mel,
               din = 0.71,
               ael_inv2 = pow(ael, -2),
               ain_inv2 = pow(ain, -2);
  auto integrand = [&](double lnt) {
    double t = exp(lnt);
    double ael_factor = 1./(ael_inv2 + t),
           del_factor = 1./(1+t/del),
           ain_factor = 1./(ain_inv2 + t),
           din_factor = 1./(1+t/din),
           nucl = (1 + t*bin);
    return (pow(ael_factor*del_factor*Z, 2)
            + Z*pow(ain_factor*nucl*din_factor*din_factor*din_factor*din_factor, 2)
           )*(t-tmin)*t;
  };
  return integrate(integrand,log(tmin),log(tmax));
}
References integrate().
Referenced by g4db::G4DarkBreMModel::ComputeCrossSectionPerAtom().
hasEnding()
bool g4db::hasEnding (const std::string & str, const std::string & end)
Check if the input string has the input ending
Parameters
[in] str string to test
[in] end ending to have
Returns
true if the last characters of str are end
Definition at line 24 of file ParseLibrary.cxx.
{
  if (str.length() >= end.length()) {
    return (str.compare(str.length() - end.length(), end.length(), end) == 0);
  } else {
    return false;
  }
}
Referenced by parseLibrary().
integrate()
template<typename IntegrandFunction > static double g4db::integrate (IntegrandFunction F, double low, double high) static
The integration method we will be using for our numerical integrals
The Gauss-Kronrod method was chosen due to its ability to limit the number of calls to the function representing the integrand which should help improve performance for us due to the complexity of our integrand. The order of the GK method was chosen after some experimentation, starting at a high value (61) and then lowering it to achieve better performance while checking the accuracy of the results.
As explained in the Boost GK Docs, generally the error estimation technique for this method is overly pessimistic, so we can confidently set the maximum depth low and the desired relative error high compared to other methods. We have followed the examples in the docs where we use max_depth to 5 and relative error to 1e-9.
Template Parameters
IntegrandFunction function type whose signature is double(*)(double).
Parameters
[in] F function to integrate
[in] low lower limit of integration
[in] high upper limit of integration
Definition at line 54 of file G4DarkBreMModel.cxx.
{
  using int_method = boost::math::quadrature::gauss_kronrod<double, 61>;
  return int_method::integrate(F, low, high, 5, 1e-9);
}
Referenced by g4db::G4DarkBreMModel::ComputeCrossSectionPerAtom(), and flux_factor_chi_numerical().
parseLibrary()
void g4db::parseLibrary (const std::string & path, int aprime_lhe_id, std::map< int, std::map< double, std::vector< OutgoingKinematics > > > & lib)
parse the input library and return the in-memory kinematics library
Library Specification
A "library" includes a single file or a directory holding multiple files. No subdirectories are inspected, so the directory must be "flat". Each file in a library can either be a CSV file or an LHE file, both of which can be compressed by gzip if desired.
CSV
The CSV file is expected to have a single header line which names the columns. These column names have no requirements (besides the existence of this line).
The CSV is required to have 10 columns on all non-empty lines of the file. The 10 columns of the CSV all are in MeV and in order are
The target Z
The incident lepton energy
The total energy of the recoil
The x-component of the recoil momentum
The y-component of the recoil momentum
The z-component of the recoil momentum
The total energy of the A'
The x-component of the A' momentum
The y-component of the A' momentum
The z-component of the A' momentum
LHE
The LHE files must have dark brem events in it where "dark brem event" in this context is defined below.
lepton_id -1 <skip> <skip> <skip> <skip> px py pz E m
<skip-line>
<skip-line>
lepton_id 1 <skip> <skip> <skip> <skip> px py pz E m
<skip-line>
<skip-line>
aprime_id 1 <skip> <skip> <skip> <skip> px py pz E m
We also check each line if it contains a 'Znuc' string. Looking for the target Z value from this line matching the following format.
<num>   <Z> # Znuc <other comments>
This is supposed to match a line of the param_card dumped into the header of the LHE. In other words, this parser should function properly if your MG/ME model has a configurable parameter in param_card.dat for the target Z and that parameter is called 'Znuc'.
This matches a subcomponent of the LHE scheme written by MadGraph/MadEvent (hence the reason this is the "lhe" parser); however, a lot of information is skipped and additional assumptions are made in order to increase the parsing speed.
The lepton_id is allowed to be either 11 or 13 everywhere. No consistency checking is done.
The E from the first line is used as the incident lepton energy. The four-momentum from the middle line is the recoil lepton's four momentum, and the four-momentum from the last line is used in conjuction with the recoil four-momentum to calculate the center of momentum vector.
Parameters
[in] path path to library to parse
[in] aprime_lhe_id the ID number for the A' (aka dark photon) in the library being parsed
[in,out] lib map of target Z and incident energy keys to set of outgoing kinematics
If the input path has one of the four file extensions below, we assume it is a file to be parsed into the library.
'.csv'
'.csv.gz'
'.lhe'
'.lhe.gz'
If the extension ends with '.gz', then a decompression step is added to the input stream. Boost.Iostream provides the gzip_decompressor "filter" which does the decompression on the data stream as it is being read in.
See also
parse::csv for files ending with '.csv' or '.csv.gz'
parse::lhe for files ending with '.lhe' or '.lhe.gz'
If the input path does not match one of the four accepted extensions, then we assume it is a directory
Note
We do not recursively enter subdirectories.
If any of the directory entries has one of the acceptable extensions, we recursively call this function on that file path so that it can be parsed into the library.
If we can't open the path that we assumed was a directory as a directory, we end processing.
If the input path has one of the four file extensions below, we assume it is a file to be parsed into the library.
'.csv'
'.csv.gz'
'.lhe'
'.lhe.gz'
If the extension ends with '.gz', then a decompression step is added to the input stream. Boost.Iostream provides the gzip_decompressor "filter" which does the decompression on the data stream as it is being read in.
See also
parse::csv for files ending with '.csv' or '.csv.gz'
parse::lhe for files ending with '.lhe' or '.lhe.gz'
If the input path does not match one of the four accepted extensions, then we assume it is a directory
Note
We do not recursively enter subdirectories.
If any of the directory entries has one of the acceptable extensions, we recursively call this function on that file path so that it can be parsed into the library.
If we can't open the path that we assumed was a directory as a directory, we end processing.
Definition at line 189 of file ParseLibrary.cxx.
{
  if (hasEnding(path, ".csv") or hasEnding(path, ".csv.gz") or hasEnding(path, ".lhe") or hasEnding(path, ".lhe.gz")) {
    boost::iostreams::filtering_istream reader;
    if (hasEnding(path, ".gz")) reader.push(boost::iostreams::gzip_decompressor());
    reader.push(boost::iostreams::file_source(path));
    if (hasEnding(path, ".csv") or hasEnding(path, ".csv.gz")) parse::csv(reader, lib);
    else parse::lhe(reader, aprime_lhe_id, lib);
  } else {
    DIR *dir;            // handle to opened directory
    struct dirent *ent;  // handle to entry inside directory
    if ((dir = opendir(path.c_str())) != NULL) {
      // directory can be opened
      while ((ent = readdir(dir)) != NULL) {
        std::string fp = path + '/' + std::string(ent->d_name);
        if (hasEnding(fp,".lhe") or hasEnding(fp, ".lhe.gz")
            or hasEnding(fp,".csv") or hasEnding(fp, ".csv.gz")) {
          parseLibrary(fp, aprime_lhe_id, lib);
        }
      }
      closedir(dir);
    } else {
      throw std::runtime_error("Unable to open '"+path+"' as a directory.");
    }
  }
}
References g4db::parse::csv(), hasEnding(), g4db::parse::lhe(), and parseLibrary().
Referenced by parseLibrary(), and g4db::G4DarkBreMModel::SetMadGraphDataLibrary().