LDMX Software: Event/include/Event/ProductTag.h File Reference
ProductTag.h File Reference
Class defining the identity of a data product in the event.
#include <ostream>
#include <string>
Classes
class ldmx::ProductTag
Defines the identity of a product and can be used for searches.
Namespaces
ldmx
All classes in the ldmx-sw project use this namespace.
Functions
std::ostream & operator<< (std::ostream &, const ldmx::ProductTag &)
Detailed Description
Class defining the identity of a data product in the event.
Author
Jeremy Mans, University of Minnesota
Definition in file ProductTag.h.
Function Documentation
operator<<()
std::ostream& operator<< (std::ostream & , const ldmx::ProductTag &)
Print/stream method for ldmx::ProductTag
Definition at line 4 of file ProductTag.cxx.
{
   return s << pt.name() << "_" << pt.passname() << "_" << pt.type();
 }
References ldmx::ProductTag::name(), ldmx::ProductTag::passname(), and ldmx::ProductTag::type().