LDMX Software: packing::FiberTrackerBinaryPacket Struct Reference
packing::FiberTrackerBinaryPacket Struct Reference
Public Member Functions
bool next (FiberTrackerEvent &e)
utility::Reader & read (utility::Reader &r)
Public Attributes
int acqMode
long int acqStamp
int acqType
int acqTypeAllowed
std::string coincidenceInUse
int counts
long int countsRecords
long int countsRecordsWithZeroEvents
long int countsTrigs
std::string cycleName
long int cycleStamp
std::string equipmentName
int eventSelectionAcq
std::vector< FiberTrackerEvent > eventsData
int i_event {0}
index of event we are on (for next)
double meanSNew
std::string message
std::vector< double > profile
std::vector< double > profileStandAlone
std::string timeFirstEvent
std::string timeFirstTrigger
std::string timeLastEvent
std::string timeLastTrigger
int trigger
int triggerOffsetAcq
int triggerSelectionAcq
Detailed Description
Each one of these packets represents an entire spill of data
Definition at line 151 of file FiberTrackerRawDecoder.cxx.
Member Function Documentation
next()
bool packing::FiberTrackerBinaryPacket::next (FiberTrackerEvent & e) inline
Definition at line 184 of file FiberTrackerRawDecoder.cxx.
{
    i_event++;
    if (i_event < eventsData.size()) {
      e = eventsData.at(i_event);
      return true;
    }
    return false;
  }
read()
utility::Reader & packing::FiberTrackerBinaryPacket::read (utility::Reader & r) inline
27 fields in order, all are present
Definition at line 196 of file FiberTrackerRawDecoder.cxx.
{
    int i_field{0};
    acqMode = FiberTrackerField(r,++i_field).to_int();
#ifdef DEBUG
    std::cout << i_field << " " << "acqMode = " << acqMode << std::endl;
#endif
    acqStamp = FiberTrackerField(r,++i_field).to_long();
#ifdef DEBUG
    std::cout << i_field << " " << "acqStamp = " << acqStamp << std::endl;
#endif
    acqType = FiberTrackerField(r,++i_field).to_int();
#ifdef DEBUG
    std::cout << i_field << " " << "acqType = " << acqType << std::endl;
#endif
    acqTypeAllowed = FiberTrackerField(r,++i_field).to_int();
#ifdef DEBUG
    std::cout << i_field << " " << "acqTypeAllowed = " << acqTypeAllowed << std::endl;
#endif
    coincidenceInUse = FiberTrackerField(r,++i_field).to_string();
#ifdef DEBUG
    std::cout << i_field << " " << "coincidenceInUse = " << coincidenceInUse << std::endl;
#endif
    counts = FiberTrackerField(r,++i_field).to_int();
#ifdef DEBUG
    std::cout << i_field << " " << "counts = " << counts << std::endl;
#endif
    countsRecords = FiberTrackerField(r,++i_field).to_long();
#ifdef DEBUG
    std::cout << i_field << " " << "countsRecords = " << countsRecords << std::endl;
#endif
    countsRecordsWithZeroEvents = FiberTrackerField(r,++i_field).to_long();
#ifdef DEBUG
    std::cout << i_field << " " << "countsRecordsWithZeroEvents = " << countsRecordsWithZeroEvents << std::endl;
#endif
    countsTrigs = FiberTrackerField(r,++i_field).to_long();
#ifdef DEBUG
    std::cout << i_field << " " << "countsTrigs = " << countsTrigs << std::endl;
#endif
    cycleName = FiberTrackerField(r,++i_field).to_string();
#ifdef DEBUG
    std::cout << i_field << " " << "cycleName = " << cycleName << std::endl;
#endif
    cycleStamp = FiberTrackerField(r,++i_field).to_long();
#ifdef DEBUG
    std::cout << i_field << " " << "cycleStamp = " << cycleStamp << std::endl;
#endif
    equipmentName = FiberTrackerField(r,++i_field).to_string();
#ifdef DEBUG
    std::cout << i_field << " " << "equipmentName = " << equipmentName << std::endl;
#endif
    eventSelectionAcq = FiberTrackerField(r,++i_field).to_int();
#ifdef DEBUG
    std::cout << i_field << " " << "eventSelectionAcq = " << eventSelectionAcq << std::endl;
#endif
    FiberTrackerField events_data_field(r,++i_field);
    i_event = -1;
    eventsData.clear();
    eventsData.reserve( events_data_field.value().size()/10 );
    for (std::size_t i_word{0}; i_word < events_data_field.value().size(); i_word += 10) {
      eventsData.emplace_back(events_data_field.value(), i_word);
    }
#ifdef DEBUG
    std::cout << i_field << " " << "eventsData (size = " << eventsData.size() << ")" << std::endl;
#endif
    meanSNew = FiberTrackerField(r,++i_field).to_double();
#ifdef DEBUG
    std::cout << i_field << " " << "meanSNew = " << meanSNew << std::endl;
#endif
    message = FiberTrackerField(r,++i_field).to_string();
#ifdef DEBUG
    std::cout << i_field << " " << "message = " << message << std::endl;
#endif
    FiberTrackerField profile_field(r,++i_field);
    profile.clear();
    profile.reserve( profile_field.value().size()/2 );
    for (std::size_t i_word{0}; i_word < profile_field.value().size(); i_word += 2) {
      profile.push_back(profile_field.to_double(i_word));
    }
#ifdef DEBUG
    std::cout << i_field << " " << "profile size " << profile.size() << std::endl;
#endif
    // fields 18 and 19 are skipped
    i_field += 2;
    FiberTrackerField profileStandAlone_field(r,++i_field);
    profileStandAlone.clear();
    profileStandAlone.reserve( profileStandAlone_field.value().size()/2 );
    for (std::size_t i_word{0}; i_word < profileStandAlone_field.value().size(); i_word += 2) {
      profileStandAlone.push_back(profileStandAlone_field.to_double(i_word));
    }
#ifdef DEBUG
    std::cout << i_field << " " << "profileStandAlone size " << profileStandAlone.size() << std::endl;
#endif
    timeFirstEvent = FiberTrackerField(r,++i_field).to_string();
#ifdef DEBUG
    std::cout << i_field << " " << "timeFirstEvent = " << timeFirstEvent << std::endl;
#endif
    timeFirstTrigger = FiberTrackerField(r,++i_field).to_string();
#ifdef DEBUG
    std::cout << i_field << " " << "timeFirstTrigger = " << timeFirstTrigger << std::endl;
#endif
    timeLastEvent = FiberTrackerField(r,++i_field).to_string();
#ifdef DEBUG
    std::cout << i_field << " " << "timeLastEvent = " << timeLastEvent << std::endl;
#endif
    timeLastTrigger = FiberTrackerField(r,++i_field).to_string();
#ifdef DEBUG
    std::cout << i_field << " " << "timeLastTrigger = " << timeLastTrigger << std::endl;
#endif
    trigger = FiberTrackerField(r,++i_field).to_int();
#ifdef DEBUG
    std::cout << i_field << " " << "trigger = " << trigger << std::endl;
#endif
    triggerOffsetAcq = FiberTrackerField(r,++i_field).to_int();
#ifdef DEBUG
    std::cout << i_field << " " << "triggerOffsetAcq = " << triggerOffsetAcq << std::endl;
#endif
    triggerSelectionAcq = FiberTrackerField(r,++i_field).to_int();
#ifdef DEBUG
    std::cout << i_field << " " << "triggerSelectionAcq = " << triggerSelectionAcq << std::endl;
#endif
    return r;
  }
References eventsData, i_event, packing::FiberTrackerField::to_double(), packing::FiberTrackerField::to_int(), packing::FiberTrackerField::to_long(), packing::FiberTrackerField::to_string(), and packing::FiberTrackerField::value().
Member Data Documentation
acqMode
int packing::FiberTrackerBinaryPacket::acqMode
Definition at line 152 of file FiberTrackerRawDecoder.cxx.
acqStamp
long int packing::FiberTrackerBinaryPacket::acqStamp
Definition at line 153 of file FiberTrackerRawDecoder.cxx.
acqType
int packing::FiberTrackerBinaryPacket::acqType
Definition at line 154 of file FiberTrackerRawDecoder.cxx.
acqTypeAllowed
int packing::FiberTrackerBinaryPacket::acqTypeAllowed
Definition at line 155 of file FiberTrackerRawDecoder.cxx.
coincidenceInUse
std::string packing::FiberTrackerBinaryPacket::coincidenceInUse
Definition at line 156 of file FiberTrackerRawDecoder.cxx.
counts
int packing::FiberTrackerBinaryPacket::counts
Definition at line 157 of file FiberTrackerRawDecoder.cxx.
countsRecords
long int packing::FiberTrackerBinaryPacket::countsRecords
Definition at line 158 of file FiberTrackerRawDecoder.cxx.
countsRecordsWithZeroEvents
long int packing::FiberTrackerBinaryPacket::countsRecordsWithZeroEvents
Definition at line 159 of file FiberTrackerRawDecoder.cxx.
countsTrigs
long int packing::FiberTrackerBinaryPacket::countsTrigs
Definition at line 160 of file FiberTrackerRawDecoder.cxx.
cycleName
std::string packing::FiberTrackerBinaryPacket::cycleName
Definition at line 161 of file FiberTrackerRawDecoder.cxx.
cycleStamp
long int packing::FiberTrackerBinaryPacket::cycleStamp
Definition at line 162 of file FiberTrackerRawDecoder.cxx.
equipmentName
std::string packing::FiberTrackerBinaryPacket::equipmentName
Definition at line 163 of file FiberTrackerRawDecoder.cxx.
eventsData
std::vector<FiberTrackerEvent> packing::FiberTrackerBinaryPacket::eventsData
This is the actual event data in which we are interested
Definition at line 168 of file FiberTrackerRawDecoder.cxx.
Referenced by read().
eventSelectionAcq
int packing::FiberTrackerBinaryPacket::eventSelectionAcq
Definition at line 164 of file FiberTrackerRawDecoder.cxx.
i_event
int packing::FiberTrackerBinaryPacket::i_event {0}
index of event we are on (for next)
Definition at line 170 of file FiberTrackerRawDecoder.cxx.
Referenced by read().
meanSNew
double packing::FiberTrackerBinaryPacket::meanSNew
Definition at line 172 of file FiberTrackerRawDecoder.cxx.
message
std::string packing::FiberTrackerBinaryPacket::message
Definition at line 173 of file FiberTrackerRawDecoder.cxx.
profile
std::vector<double> packing::FiberTrackerBinaryPacket::profile
Definition at line 174 of file FiberTrackerRawDecoder.cxx.
profileStandAlone
std::vector<double> packing::FiberTrackerBinaryPacket::profileStandAlone
Definition at line 175 of file FiberTrackerRawDecoder.cxx.
timeFirstEvent
std::string packing::FiberTrackerBinaryPacket::timeFirstEvent
Definition at line 176 of file FiberTrackerRawDecoder.cxx.
timeFirstTrigger
std::string packing::FiberTrackerBinaryPacket::timeFirstTrigger
Definition at line 177 of file FiberTrackerRawDecoder.cxx.
timeLastEvent
std::string packing::FiberTrackerBinaryPacket::timeLastEvent
Definition at line 178 of file FiberTrackerRawDecoder.cxx.
timeLastTrigger
std::string packing::FiberTrackerBinaryPacket::timeLastTrigger
Definition at line 179 of file FiberTrackerRawDecoder.cxx.
trigger
int packing::FiberTrackerBinaryPacket::trigger
Definition at line 180 of file FiberTrackerRawDecoder.cxx.
triggerOffsetAcq
int packing::FiberTrackerBinaryPacket::triggerOffsetAcq
Definition at line 181 of file FiberTrackerRawDecoder.cxx.
triggerSelectionAcq
int packing::FiberTrackerBinaryPacket::triggerSelectionAcq
Definition at line 182 of file FiberTrackerRawDecoder.cxx.
The documentation for this struct was generated from the following file:
Packing/src/Packing/FiberTrackerRawDecoder.cxx